<a href="https://colab.research.google.com/github/amzad-786githumb/Privacy-Preserving-Synthetic-Tabular-Data-Generation-Using-Generative-Adversarial-Networks/blob/main/04_Baseline_Deep_Models.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# ==============================================================================
# NOTEBOOK 04
# Deep Learning Synthetic Data Generation
# ==============================================================================
#
# Research Title:
# Privacy-Preserving High-Fidelity Synthetic Data Generation:
# A Unified Statistical and Machine Learning Framework
#
# Researcher:
# Mohd Amzad
#
# Notebook:
# 04 - Deep Learning Synthetic Data Generation
#
# Purpose:
# Train and evaluate deep learning-based synthetic tabular data generators,
# compare them with statistical baseline models from Notebook 03, and prepare
# high-quality synthetic datasets for downstream privacy and utility evaluation.
#
# Models Implemented:
#   • CTGAN
#   • TVAE
#   • DP-CTGAN
#
# Previous Notebook:
#   Notebook 03 - Statistical Synthetic Data Generation
#
# Next Notebook:
#   Notebook 05 - Proposed SPP-GAN Framework
#
# ==============================================================================

In [1]:
# ==============================================================================
# Research Objectives
# ==============================================================================

NOTEBOOK_OBJECTIVES = [

    "Load processed datasets and metadata generated in Notebook 02.",

    "Train CTGAN as the primary GAN-based baseline model.",

    "Train TVAE as the variational autoencoder baseline.",

    "Train Differentially Private CTGAN (DP-CTGAN) using privacy-aware training.",

    "Generate synthetic datasets using each deep learning model.",

    "Compare deep learning models with statistical baselines from Notebook 03.",

    "Evaluate synthetic datasets using fidelity, utility, and privacy metrics.",

    "Save trained models, synthetic datasets, checkpoints, reports, and metadata.",

    "Prepare reproducible outputs for Notebook 05 (Proposed SPP-GAN)."

]

print("=" * 100)
print("NOTEBOOK OBJECTIVES")
print("=" * 100)

for i, objective in enumerate(NOTEBOOK_OBJECTIVES, start=1):

    print(f"{i}. {objective}")

====================================================================================================
NOTEBOOK OBJECTIVES
====================================================================================================
1. Load processed datasets and metadata generated in Notebook 02.
2. Train CTGAN as the primary GAN-based baseline model.
3. Train TVAE as the variational autoencoder baseline.
4. Train Differentially Private CTGAN (DP-CTGAN) using privacy-aware training.
5. Generate synthetic datasets using each deep learning model.
6. Compare deep learning models with statistical baselines from Notebook 03.
7. Evaluate synthetic datasets using fidelity, utility, and privacy metrics.
8. Save trained models, synthetic datasets, checkpoints, reports, and metadata.
9. Prepare reproducible outputs for Notebook 05 (Proposed SPP-GAN).

In [2]:
# ==============================================================================
# Research Workflow
# ==============================================================================

WORKFLOW = [

    "Load Project Configuration",

    "Verify Environment",

    "Load Processed Datasets",

    "Load Metadata",

    "Train CTGAN",

    "Generate CTGAN Synthetic Data",

    "Train TVAE",

    "Generate TVAE Synthetic Data",

    "Train DP-CTGAN",

    "Generate DP-CTGAN Synthetic Data",

    "Evaluate Deep Learning Models",

    "Compare with Statistical Models",

    "Save Reports",

    "Notebook Verification"

]

print("=" * 100)
print("NOTEBOOK 04 WORKFLOW")
print("=" * 100)

for step, task in enumerate(WORKFLOW, start=1):

    print(f"Step {step:02d} : {task}")

====================================================================================================
NOTEBOOK 04 WORKFLOW
====================================================================================================
Step 01 : Load Project Configuration
Step 02 : Verify Environment
Step 03 : Load Processed Datasets
Step 04 : Load Metadata
Step 05 : Train CTGAN
Step 06 : Generate CTGAN Synthetic Data
Step 07 : Train TVAE
Step 08 : Generate TVAE Synthetic Data
Step 09 : Train DP-CTGAN
Step 10 : Generate DP-CTGAN Synthetic Data
Step 11 : Evaluate Deep Learning Models
Step 12 : Compare with Statistical Models
Step 13 : Save Reports
Step 14 : Notebook Verification

In [3]:
# ==============================================================================
# Deep Learning Model Overview
# ==============================================================================

import pandas as pd

MODEL_OVERVIEW = pd.DataFrame({

    "Model":[

        "CTGAN",

        "TVAE",

        "DP-CTGAN"

    ],

    "Category":[

        "GAN",

        "Variational Autoencoder",

        "Privacy-Preserving GAN"

    ],

    "Purpose":[

        "Baseline tabular synthetic data generation",

        "Latent representation learning",

        "Privacy-preserving synthetic data generation"

    ],

    "Strength":[

        "Captures complex tabular distributions",

        "Stable latent space representation",

        "Balances privacy and utility"

    ],

    "Output":[

        "Synthetic Dataset",

        "Synthetic Dataset",

        "Synthetic Dataset"

    ]

})

print("=" * 100)
print("DEEP LEARNING MODEL OVERVIEW")
print("=" * 100)

display(MODEL_OVERVIEW)

====================================================================================================
DEEP LEARNING MODEL OVERVIEW
====================================================================================================

,Model,Category,Purpose,Strength,Output
0,CTGAN,GAN,Baseline tabular synthetic data generation,Captures complex tabular distributions,Synthetic Dataset
1,TVAE,Variational Autoencoder,Latent representation learning,Stable latent space representation,Synthetic Dataset
2,DP-CTGAN,Privacy-Preserving GAN,Privacy-preserving synthetic data generation,Balances privacy and utility,Synthetic Dataset

In [4]:
# ==============================================================================
# Comparison with Notebook 03
# ==============================================================================

COMPARISON = pd.DataFrame({

    "Aspect":[

        "Learning Principle",

        "Relationship Modeling",

        "Data Type Support",

        "Captures Nonlinearity",

        "Privacy Support",

        "Training Complexity",

        "Primary Output"

    ],

    "Notebook 03":[

        "Statistical Estimation",

        "Linear / Copula-based",

        "Mixed",

        "Limited",

        "None",

        "Low",

        "Statistical Synthetic Data"

    ],

    "Notebook 04":[

        "Deep Neural Networks",

        "Nonlinear Representation Learning",

        "Mixed",

        "Excellent",

        "DP-CTGAN",

        "High",

        "Deep Learning Synthetic Data"

    ]

})

print("=" * 100)
print("NOTEBOOK 03 vs NOTEBOOK 04")
print("=" * 100)

display(COMPARISON)

====================================================================================================
NOTEBOOK 03 vs NOTEBOOK 04
====================================================================================================

,Aspect,Notebook 03,Notebook 04
0,Learning Principle,Statistical Estimation,Deep Neural Networks
1,Relationship Modeling,Linear / Copula-based,Nonlinear Representation Learning
2,Data Type Support,Mixed,Mixed
3,Captures Nonlinearity,Limited,Excellent
4,Privacy Support,None,DP-CTGAN
5,Training Complexity,Low,High
6,Primary Output,Statistical Synthetic Data,Deep Learning Synthetic Data

In [5]:
# ==============================================================================
# Expected Outputs
# ==============================================================================

EXPECTED_OUTPUTS = [

    "CTGAN trained models",

    "TVAE trained models",

    "DP-CTGAN trained models",

    "Synthetic datasets",

    "Training checkpoints",

    "Training history",

    "Evaluation reports",

    "Comparison reports",

    "JSON metadata",

    "Manifest",

    "Notebook verification report"

]

print("=" * 100)
print("EXPECTED OUTPUTS")
print("=" * 100)

for item in EXPECTED_OUTPUTS:

    print(f"✓ {item}")

====================================================================================================
EXPECTED OUTPUTS
====================================================================================================
✓ CTGAN trained models
✓ TVAE trained models
✓ DP-CTGAN trained models
✓ Synthetic datasets
✓ Training checkpoints
✓ Training history
✓ Evaluation reports
✓ Comparison reports
✓ JSON metadata
✓ Manifest
✓ Notebook verification report

In [6]:
# ==============================================================================
# Research Pipeline
# ==============================================================================

print("=" * 100)
print("DEEP LEARNING RESEARCH PIPELINE")
print("=" * 100)

pipeline = """

Notebook 02
│
├── Processed Datasets
├── Metadata
│
▼
Notebook 03
│
├── Gaussian Multivariate
├── Gaussian Copula
│
▼
Notebook 04
│
├── CTGAN
├── TVAE
├── DP-CTGAN
│
├── Synthetic Data Generation
├── Model Evaluation
├── Statistical Comparison
├── Utility Evaluation
├── Privacy Evaluation
│
▼
Notebook 05
│
└── Proposed SPP-GAN
│
▼
Notebook 06
│
└── Unified Benchmark Evaluation
"""

print(pipeline)

====================================================================================================
DEEP LEARNING RESEARCH PIPELINE
====================================================================================================


Notebook 02
│
├── Processed Datasets
├── Metadata
│
▼
Notebook 03
│
├── Gaussian Multivariate
├── Gaussian Copula
│
▼
Notebook 04
│
├── CTGAN
├── TVAE
├── DP-CTGAN
│
├── Synthetic Data Generation
├── Model Evaluation
├── Statistical Comparison
├── Utility Evaluation
├── Privacy Evaluation
│
▼
Notebook 05
│
└── Proposed SPP-GAN
│
▼
Notebook 06
│
└── Unified Benchmark Evaluation

In [7]:
# ==============================================================================
# Notebook Initialization
# ==============================================================================

print("=" * 100)
print("NOTEBOOK 04 INITIALIZATION")
print("=" * 100)

print("Research Title : Privacy-Preserving High-Fidelity Synthetic Data Generation")
print("Notebook       : 04")
print("Phase          : Deep Learning Synthetic Data Generation")
print("Status         : READY")
print("Next Section   : Part B - Load Project Configuration")

print("=" * 100)

====================================================================================================
NOTEBOOK 04 INITIALIZATION
====================================================================================================
Research Title : Privacy-Preserving High-Fidelity Synthetic Data Generation
Notebook       : 04
Phase          : Deep Learning Synthetic Data Generation
Status         : READY
Next Section   : Part B - Load Project Configuration
====================================================================================================

In [8]:
# ==============================================================================
# Part B - Load Project Configuration
# B1. Mount Google Drive
# ==============================================================================

from google.colab import drive
import os

drive.mount('/content/drive', force_remount=False)

PROJECT_ROOT = "/content/drive/MyDrive/SPP_GAN_Project"

if not os.path.exists(PROJECT_ROOT):
    raise FileNotFoundError(
        f"Project directory not found:\n{PROJECT_ROOT}"
    )

print("="*100)
print("GOOGLE DRIVE MOUNTED SUCCESSFULLY")
print("="*100)
print(PROJECT_ROOT)

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
====================================================================================================
GOOGLE DRIVE MOUNTED SUCCESSFULLY
====================================================================================================
/content/drive/MyDrive/SPP_GAN_Project

In [9]:
# ==============================================================================
# B2. Import Libraries
# ==============================================================================

import os
import json
import yaml
import random
import warnings
import platform
import numpy as np
import pandas as pd

import torch

warnings.filterwarnings("ignore")

print("Libraries imported successfully.")

Libraries imported successfully.

In [10]:
# ==============================================================================
# B3. Load Configuration Files
# ==============================================================================

CONFIG_DIR = os.path.join(PROJECT_ROOT, "configs")

CONFIG_FILE = os.path.join(CONFIG_DIR, "config.yaml")

ENVIRONMENT_FILE = os.path.join(CONFIG_DIR, "environment.json")

if not os.path.exists(CONFIG_FILE):
    raise FileNotFoundError(CONFIG_FILE)

if not os.path.exists(ENVIRONMENT_FILE):
    raise FileNotFoundError(ENVIRONMENT_FILE)

with open(CONFIG_FILE, "r") as f:
    CONFIG = yaml.safe_load(f)

with open(ENVIRONMENT_FILE, "r") as f:
    ENVIRONMENT = json.load(f)

print("Configuration files loaded successfully.")

Configuration files loaded successfully.

In [11]:
# ==============================================================================
# B4. Project Paths
# ==============================================================================

PATHS = CONFIG["paths"]

PROJECT_ROOT = PATHS["root"]

RAW_DATA_DIR = PATHS["raw_data"]

PROCESSED_DATA_DIR = PATHS["processed_data"]

SYNTHETIC_DATA_DIR = PATHS["synthetic_data"]

METADATA_DIR = PATHS["metadata"]

MODEL_DIR = PATHS["models"]

REPORT_DIR = PATHS["reports"]

RESULT_DIR = PATHS["results"]

CHECKPOINT_DIR = PATHS["checkpoints"]

CONFIG_DIR = PATHS["configs"]

STATISTICAL_MODEL_DIR = PATHS["statistical_models"]

os.makedirs(MODEL_DIR, exist_ok=True)
os.makedirs(REPORT_DIR, exist_ok=True)
os.makedirs(CHECKPOINT_DIR, exist_ok=True)
os.makedirs(SYNTHETIC_DATA_DIR, exist_ok=True)

print("="*100)
print("PROJECT PATHS")
print("="*100)

for key, value in PATHS.items():
    print(f"{key:<20} : {value}")

====================================================================================================
PROJECT PATHS
====================================================================================================
root                 : /content/drive/MyDrive/SPP_GAN_Project
configs              : /content/drive/MyDrive/SPP_GAN_Project/configs
datasets             : /content/drive/MyDrive/SPP_GAN_Project/datasets
raw_data             : /content/drive/MyDrive/SPP_GAN_Project/datasets/raw
processed_data       : /content/drive/MyDrive/SPP_GAN_Project/datasets/processed
synthetic_data       : /content/drive/MyDrive/SPP_GAN_Project/datasets/synthetic
metadata             : /content/drive/MyDrive/SPP_GAN_Project/metadata
statistical_models   : /content/drive/MyDrive/SPP_GAN_Project/statistical_models
models               : /content/drive/MyDrive/SPP_GAN_Project/models
checkpoints          : /content/drive/MyDrive/SPP_GAN_Project/checkpoints
results              : /content/drive/MyDrive/SPP_GAN_Project/results
reports              : /content/drive/MyDrive/SPP_GAN_Project/reports

In [12]:
# ==============================================================================
# B5. Reproducibility
# ==============================================================================

SEED = CONFIG["reproducibility"]["seed"]

random.seed(SEED)

np.random.seed(SEED)

torch.manual_seed(SEED)

if torch.cuda.is_available():
    torch.cuda.manual_seed(SEED)
    torch.cuda.manual_seed_all(SEED)

print("="*100)
print("RANDOM SEED CONFIGURED")
print("="*100)
print(SEED)

====================================================================================================
RANDOM SEED CONFIGURED
====================================================================================================
42

In [13]:
# ==============================================================================
# B6. Hardware Detection
# ==============================================================================

GPU_AVAILABLE = torch.cuda.is_available()

DEVICE = torch.device("cuda" if GPU_AVAILABLE else "cpu")

if GPU_AVAILABLE:

    GPU_NAME = torch.cuda.get_device_name(0)

    GPU_COUNT = torch.cuda.device_count()

    CUDA_VERSION = torch.version.cuda

else:

    GPU_NAME = "CPU"

    GPU_COUNT = 0

    CUDA_VERSION = None

print("="*100)
print("HARDWARE CONFIGURATION")
print("="*100)

print(f"Operating System : {platform.system()}")

print(f"Python Version   : {platform.python_version()}")

print(f"PyTorch Version  : {torch.__version__}")

print(f"Device           : {DEVICE}")

print(f"GPU Available    : {GPU_AVAILABLE}")

print(f"GPU Name         : {GPU_NAME}")

print(f"GPU Count        : {GPU_COUNT}")

print(f"CUDA Version     : {CUDA_VERSION}")

====================================================================================================
HARDWARE CONFIGURATION
====================================================================================================
Operating System : Linux
Python Version   : 3.12.13
PyTorch Version  : 2.11.0+cpu
Device           : cpu
GPU Available    : False
GPU Name         : CPU
GPU Count        : 0
CUDA Version     : None

In [14]:
# ==============================================================================
# B7. Configure Reproducibility
# ==============================================================================

torch.backends.cudnn.deterministic = True

torch.backends.cudnn.benchmark = False

os.environ["PYTHONHASHSEED"] = str(SEED)

print("="*100)
print("REPRODUCIBILITY CONFIGURED")
print("="*100)

print("Deterministic Mode : Enabled")

print("Benchmark Mode     : Disabled")

print("Python Hash Seed   :", os.environ["PYTHONHASHSEED"])

====================================================================================================
REPRODUCIBILITY CONFIGURED
====================================================================================================
Deterministic Mode : Enabled
Benchmark Mode     : Disabled
Python Hash Seed   : 42

In [15]:
# ==============================================================================
# B8. Deep Learning Configuration
# ==============================================================================

TRAINING = CONFIG["training"]

EPOCHS = TRAINING["epochs"]

BATCH_SIZE = TRAINING["batch_size"]

LEARNING_RATE = TRAINING["learning_rate"]

LATENT_DIM = TRAINING["latent_dimension"]

OPTIMIZER = TRAINING["optimizer"]

BETA1 = TRAINING["beta1"]

BETA2 = TRAINING["beta2"]

GRADIENT_CLIP = TRAINING["gradient_clip"]

print("="*100)
print("TRAINING CONFIGURATION")
print("="*100)

print(f"Epochs           : {EPOCHS}")

print(f"Batch Size       : {BATCH_SIZE}")

print(f"Learning Rate    : {LEARNING_RATE}")

print(f"Latent Dimension : {LATENT_DIM}")

print(f"Optimizer        : {OPTIMIZER}")

print(f"Beta1            : {BETA1}")

print(f"Beta2            : {BETA2}")

print(f"Gradient Clip    : {GRADIENT_CLIP}")

====================================================================================================
TRAINING CONFIGURATION
====================================================================================================
Epochs           : 200
Batch Size       : 256
Learning Rate    : 0.0002
Latent Dimension : 128
Optimizer        : Adam
Beta1            : 0.5
Beta2            : 0.999
Gradient Clip    : 1.0

In [16]:
# ==============================================================================
# B9. Differential Privacy Configuration
# ==============================================================================

PRIVACY = CONFIG["privacy"]

EPSILON = PRIVACY["epsilon"]

DELTA = PRIVACY["delta"]

NOISE_MULTIPLIER = PRIVACY["noise_multiplier"]

MAX_GRAD_NORM = PRIVACY["max_grad_norm"]

print("="*100)
print("DIFFERENTIAL PRIVACY CONFIGURATION")
print("="*100)

print(f"Epsilon           : {EPSILON}")

print(f"Delta             : {DELTA}")

print(f"Noise Multiplier  : {NOISE_MULTIPLIER}")

print(f"Max Grad Norm     : {MAX_GRAD_NORM}")

====================================================================================================
DIFFERENTIAL PRIVACY CONFIGURATION
====================================================================================================
Epsilon           : 5.0
Delta             : 1e-05
Noise Multiplier  : 1.1
Max Grad Norm     : 1.0

In [17]:
# ==============================================================================
# B10. Configuration Summary
# ==============================================================================

SUMMARY = pd.DataFrame({

    "Parameter":[

        "Project",

        "Research",

        "Device",

        "GPU",

        "Seed",

        "Epochs",

        "Batch Size",

        "Learning Rate",

        "Latent Dimension",

        "Privacy Epsilon"

    ],

    "Value":[

        CONFIG["project"]["project_name"],

        CONFIG["project"]["research_title"],

        str(DEVICE),

        GPU_NAME,

        SEED,

        EPOCHS,

        BATCH_SIZE,

        LEARNING_RATE,

        LATENT_DIM,

        EPSILON

    ]

})

print("="*100)
print("CONFIGURATION SUMMARY")
print("="*100)

display(SUMMARY)

====================================================================================================
CONFIGURATION SUMMARY
====================================================================================================

          Parameter                                              Value
0           Project                                    SPP_GAN_Project
1          Research  Privacy-Preserving High-Fidelity Synthetic Dat...
2            Device                                                cpu
3               GPU                                                CPU
4              Seed                                                 42
5            Epochs                                                200
6        Batch Size                                                256
7     Learning Rate                                             0.0002
8  Latent Dimension                                                128
9   Privacy Epsilon                                                5.0

In [18]:
# ==============================================================================
# B11. Verification
# ==============================================================================

print("="*100)
print("PART B VERIFICATION")
print("="*100)

verification = {

    "Google Drive":
        os.path.exists(PROJECT_ROOT),

    "config.yaml":
        os.path.exists(CONFIG_FILE),

    "environment.json":
        os.path.exists(ENVIRONMENT_FILE),

    "Project Paths":
        os.path.exists(PROCESSED_DATA_DIR),

    "Metadata":
        os.path.exists(METADATA_DIR),

    "Reports":
        os.path.exists(REPORT_DIR),

    "Models":
        os.path.exists(MODEL_DIR),

    "Random Seed":
        isinstance(SEED, int),

    "Device":
        DEVICE is not None

}

VERIFY_DF = pd.DataFrame({

    "Component": verification.keys(),

    "Status": verification.values()

})

VERIFY_DF["Result"] = VERIFY_DF["Status"].map(
    lambda x: "PASS" if x else "FAIL"
)

display(VERIFY_DF)

if VERIFY_DF["Status"].all():

    print("\n" + "="*100)
    print("✓ PART B COMPLETED SUCCESSFULLY")
    print("Project configuration loaded successfully.")
    print("Ready for Part C - Verify Project Environment")
    print("="*100)

else:

    raise RuntimeError("Part B verification failed.")

====================================================================================================
PART B VERIFICATION
====================================================================================================

          Component  Status Result
0      Google Drive    True   PASS
1       config.yaml    True   PASS
2  environment.json    True   PASS
3     Project Paths    True   PASS
4          Metadata    True   PASS
5           Reports    True   PASS
6            Models    True   PASS
7       Random Seed    True   PASS
8            Device    True   PASS

====================================================================================================
✓ PART B COMPLETED SUCCESSFULLY
Project configuration loaded successfully.
Ready for Part C - Verify Project Environment
====================================================================================================

In [19]:
# ==============================================================================
# Part C - Verify Project Environment
# C1. Verify Project Folder Structure
# ==============================================================================

import os
import pandas as pd

print("="*100)
print("VERIFYING PROJECT FOLDER STRUCTURE")
print("="*100)

FOLDERS = {

    "Project Root": PROJECT_ROOT,

    "Configs": CONFIG_DIR,

    "Raw Data": RAW_DATA_DIR,

    "Processed Data": PROCESSED_DATA_DIR,

    "Synthetic Data": SYNTHETIC_DATA_DIR,

    "Metadata": METADATA_DIR,

    "Models": MODEL_DIR,

    "Statistical Models": STATISTICAL_MODEL_DIR,

    "Reports": REPORT_DIR,

    "Results": RESULT_DIR,

    "Checkpoints": CHECKPOINT_DIR

}

folder_results = []

for name, path in FOLDERS.items():

    folder_results.append({

        "Component": name,

        "Path": path,

        "Status": os.path.exists(path)

    })

FOLDER_DF = pd.DataFrame(folder_results)

FOLDER_DF["Result"] = FOLDER_DF["Status"].map(
    lambda x: "PASS" if x else "FAIL"
)

display(FOLDER_DF)

====================================================================================================
VERIFYING PROJECT FOLDER STRUCTURE
====================================================================================================

,Component,Path,Status,Result
0,Project Root,/content/drive/MyDrive/SPP_GAN_Project,True,PASS
1,Configs,/content/drive/MyDrive/SPP_GAN_Project/configs,True,PASS
2,Raw Data,/content/drive/MyDrive/SPP_GAN_Project/dataset...,True,PASS
3,Processed Data,/content/drive/MyDrive/SPP_GAN_Project/dataset...,True,PASS
4,Synthetic Data,/content/drive/MyDrive/SPP_GAN_Project/dataset...,True,PASS
5,Metadata,/content/drive/MyDrive/SPP_GAN_Project/metadata,True,PASS
6,Models,/content/drive/MyDrive/SPP_GAN_Project/models,True,PASS
7,Statistical Models,/content/drive/MyDrive/SPP_GAN_Project/statist...,True,PASS
8,Reports,/content/drive/MyDrive/SPP_GAN_Project/reports,True,PASS
9,Results,/content/drive/MyDrive/SPP_GAN_Project/results,True,PASS
10,Checkpoints,/content/drive/MyDrive/SPP_GAN_Project/checkpo...,True,PASS

In [20]:
# ==============================================================================
# C2. Verify Processed Datasets
# ==============================================================================

print("="*100)
print("VERIFYING PROCESSED DATASETS")
print("="*100)

DATASET_RESULTS = []

EXPECTED_DATASETS = [

    "adult_income",

    "bank_marketing",

    "breast_cancer"

]

for dataset in EXPECTED_DATASETS:

    file = os.path.join(
        PROCESSED_DATA_DIR,
        f"{dataset}_processed.csv"
    )

    exists = os.path.exists(file)

    rows = None
    cols = None

    if exists:

        df = pd.read_csv(file)

        rows = len(df)

        cols = df.shape[1]

    DATASET_RESULTS.append({

        "Dataset": dataset,

        "Rows": rows,

        "Columns": cols,

        "Status": exists

    })

DATASET_DF = pd.DataFrame(DATASET_RESULTS)

DATASET_DF["Result"] = DATASET_DF["Status"].map(
    lambda x:"PASS" if x else "FAIL"
)

display(DATASET_DF)

====================================================================================================
VERIFYING PROCESSED DATASETS
====================================================================================================

          Dataset   Rows  Columns  Status Result
0    adult_income  32510       15    True   PASS
1  bank_marketing  45211       17    True   PASS
2   breast_cancer    569       32    True   PASS

In [21]:
# ==============================================================================
# C3. Verify Dataset Splits (Robust Version)
# Automatically detects multiple split directory layouts
# ==============================================================================

print("=" * 100)
print("VERIFYING DATASET SPLITS")
print("=" * 100)

import os
import pandas as pd

EXPECTED_DATASETS = [
    "adult_income",
    "bank_marketing",
    "breast_cancer"
]

SPLITS = ["train", "validation", "test"]

split_results = []

# --------------------------------------------------------------------------
# Possible layouts produced by different notebook versions
# --------------------------------------------------------------------------

def locate_split_file(dataset, split):

    candidate_paths = [

        # Processed folder layouts
        os.path.join(PROCESSED_DATA_DIR,
                     f"{dataset}_{split}.csv"),

        os.path.join(PROCESSED_DATA_DIR,
                     dataset,
                     f"{split}.csv"),

        os.path.join(PROCESSED_DATA_DIR,
                     "splits",
                     f"{dataset}_{split}.csv"),

        os.path.join(PROCESSED_DATA_DIR,
                     "splits",
                     dataset,
                     f"{split}.csv"),

        # ------------------------------------------------------------------
        # Actual Notebook 02 output
        # datasets/splits/<dataset>/<split>.csv
        # ------------------------------------------------------------------

        os.path.join(
            PROJECT_ROOT,
            "datasets",
            "splits",
            dataset,
            f"{split}.csv"
        ),

        os.path.join(
            PROJECT_ROOT,
            "datasets",
            "splits",
            f"{dataset}_{split}.csv"
        )
    ]

    for path in candidate_paths:

        if os.path.exists(path):
            return path

    return None

for dataset in EXPECTED_DATASETS:

    for split in SPLITS:

        file_path = locate_split_file(dataset, split)

        exists = file_path is not None

        rows = None

        if exists:

            try:
                rows = len(pd.read_csv(file_path))
            except:
                rows = None

        split_results.append({

            "Dataset": dataset,

            "Split": split,

            "Found": exists,

            "Rows": rows,

            "Location": file_path if exists else "Not Found"

        })

SPLIT_DF = pd.DataFrame(split_results)

SPLIT_DF["Result"] = SPLIT_DF["Found"].map(
    lambda x: "PASS" if x else "FAIL"
)

display(SPLIT_DF)

print()

print("Summary")

print("-" * 100)

summary = SPLIT_DF.groupby("Dataset")["Found"].all()

for dataset, status in summary.items():

    symbol = "✓" if status else "✗"

    print(f"{symbol} {dataset:<20} {'PASS' if status else 'FAIL'}")

====================================================================================================
VERIFYING DATASET SPLITS
====================================================================================================

,Dataset,Split,Found,Rows,Location,Result
0,adult_income,train,True,22756,/content/drive/MyDrive/SPP_GAN_Project/dataset...,PASS
1,adult_income,validation,True,4877,/content/drive/MyDrive/SPP_GAN_Project/dataset...,PASS
2,adult_income,test,True,4877,/content/drive/MyDrive/SPP_GAN_Project/dataset...,PASS
3,bank_marketing,train,True,31647,/content/drive/MyDrive/SPP_GAN_Project/dataset...,PASS
4,bank_marketing,validation,True,6782,/content/drive/MyDrive/SPP_GAN_Project/dataset...,PASS
5,bank_marketing,test,True,6782,/content/drive/MyDrive/SPP_GAN_Project/dataset...,PASS
6,breast_cancer,train,True,398,/content/drive/MyDrive/SPP_GAN_Project/dataset...,PASS
7,breast_cancer,validation,True,85,/content/drive/MyDrive/SPP_GAN_Project/dataset...,PASS
8,breast_cancer,test,True,86,/content/drive/MyDrive/SPP_GAN_Project/dataset...,PASS

Summary
----------------------------------------------------------------------------------------------------
✓ adult_income         PASS
✓ bank_marketing       PASS
✓ breast_cancer        PASS

In [22]:
# ==============================================================================
# C4. Verify Metadata
# ==============================================================================

print("="*100)
print("VERIFYING METADATA")
print("="*100)

metadata_results=[]

for dataset in EXPECTED_DATASETS:

    file=os.path.join(

        METADATA_DIR,

        f"{dataset}_metadata.json"

    )

    metadata_results.append({

        "Dataset":dataset,

        "Status":os.path.exists(file)

    })

METADATA_DF=pd.DataFrame(metadata_results)

METADATA_DF["Result"]=METADATA_DF["Status"].map(
    lambda x:"PASS" if x else "FAIL"
)

display(METADATA_DF)

====================================================================================================
VERIFYING METADATA
====================================================================================================

          Dataset  Status Result
0    adult_income    True   PASS
1  bank_marketing    True   PASS
2   breast_cancer    True   PASS

In [23]:
# ==============================================================================
# C5. Verify Statistical Models
# ==============================================================================

print("="*100)
print("VERIFYING STATISTICAL MODELS")
print("="*100)

MODEL_RESULTS=[]

for dataset in EXPECTED_DATASETS:

    gaussian=os.path.join(

        STATISTICAL_MODEL_DIR,

        "gaussian_multivariate",

        f"{dataset}_gaussian.pkl"

    )

    copula=os.path.join(

        STATISTICAL_MODEL_DIR,

        "gaussian_copula",

        f"{dataset}_gaussian_copula.pkl"

    )

    MODEL_RESULTS.append({

        "Dataset":dataset,

        "Gaussian":os.path.exists(gaussian),

        "Copula":os.path.exists(copula)

    })

MODEL_DF=pd.DataFrame(MODEL_RESULTS)

display(MODEL_DF)

====================================================================================================
VERIFYING STATISTICAL MODELS
====================================================================================================

          Dataset  Gaussian  Copula
0    adult_income      True    True
1  bank_marketing      True    True
2   breast_cancer      True    True

In [24]:
# ==============================================================================
# C6. Verify Synthetic Statistical Datasets
# ==============================================================================

print("="*100)
print("VERIFYING SYNTHETIC DATASETS")
print("="*100)

synthetic=[]

for dataset in EXPECTED_DATASETS:

    gaussian=os.path.join(

        SYNTHETIC_DATA_DIR,

        "gaussian_multivariate",

        f"{dataset}_synthetic.csv"

    )

    copula=os.path.join(

        SYNTHETIC_DATA_DIR,

        "gaussian_copula",

        f"{dataset}_synthetic.csv"

    )

    synthetic.append({

        "Dataset":dataset,

        "Gaussian":os.path.exists(gaussian),

        "Copula":os.path.exists(copula)

    })

SYNTHETIC_DF=pd.DataFrame(synthetic)

display(SYNTHETIC_DF)

====================================================================================================
VERIFYING SYNTHETIC DATASETS
====================================================================================================

          Dataset  Gaussian  Copula
0    adult_income      True    True
1  bank_marketing      True    True
2   breast_cancer      True    True

In [25]:
# ==============================================================================
# C7. Verify Required Packages
# ==============================================================================

print("="*100)
print("VERIFYING REQUIRED PACKAGES")
print("="*100)

packages=[

    "numpy",

    "pandas",

    "torch",

    "sklearn",

    "scipy",

    "matplotlib",

    "joblib",

    "yaml"

]

package_results=[]

import importlib

for package in packages:

    try:

        importlib.import_module(package)

        status=True

    except:

        status=False

    package_results.append({

        "Package":package,

        "Installed":status

    })

PACKAGE_DF=pd.DataFrame(package_results)

PACKAGE_DF["Result"]=PACKAGE_DF["Installed"].map(
    lambda x:"PASS" if x else "FAIL"
)

display(PACKAGE_DF)

====================================================================================================
VERIFYING REQUIRED PACKAGES
====================================================================================================

      Package  Installed Result
0       numpy       True   PASS
1      pandas       True   PASS
2       torch       True   PASS
3     sklearn       True   PASS
4       scipy       True   PASS
5  matplotlib       True   PASS
6      joblib       True   PASS
7        yaml       True   PASS

In [26]:
# ==============================================================================
# C8. Hardware Verification
# ==============================================================================

print("="*100)
print("HARDWARE CHECK")
print("="*100)

GPU=torch.cuda.is_available()

print("Device :",DEVICE)

print("GPU Available :",GPU)

if GPU:

    print("GPU :",torch.cuda.get_device_name(0))

else:

    print("Running on CPU")

====================================================================================================
HARDWARE CHECK
====================================================================================================
Device : cpu
GPU Available : False
Running on CPU

In [27]:
print("="*100)
print("NOTEBOOK READINESS")
print("="*100)

verification={

    "Folders":
        FOLDER_DF["Status"].all(),

    "Processed Datasets":
        DATASET_DF["Status"].all(),

    "Dataset Splits":
        SPLIT_DF["Found"].all(),

    "Metadata":
        METADATA_DF["Status"].all(),

    "Statistical Models":
        MODEL_DF["Gaussian"].all() and MODEL_DF["Copula"].all(),

    "Synthetic Data":
        SYNTHETIC_DF["Gaussian"].all() and SYNTHETIC_DF["Copula"].all(),

    "Packages":
        PACKAGE_DF["Installed"].all()

}

VERIFY_DF=pd.DataFrame({

    "Component":verification.keys(),

    "Status":verification.values()

})

VERIFY_DF["Result"]=VERIFY_DF["Status"].map(
    lambda x:"PASS" if x else "FAIL"
)

display(VERIFY_DF)

if VERIFY_DF["Status"].all():

    print("\n"+"="*100)
    print("✓ PART C COMPLETED SUCCESSFULLY")
    print("Notebook 04 environment verified.")
    print("Ready for Part D - Load Processed Datasets")
    print("="*100)

else:

    failed=VERIFY_DF[VERIFY_DF["Status"]==False]

    display(failed)

    raise RuntimeError("Part C verification failed.")

====================================================================================================
NOTEBOOK READINESS
====================================================================================================

            Component  Status Result
0             Folders    True   PASS
1  Processed Datasets    True   PASS
2      Dataset Splits    True   PASS
3            Metadata    True   PASS
4  Statistical Models    True   PASS
5      Synthetic Data    True   PASS
6            Packages    True   PASS

====================================================================================================
✓ PART C COMPLETED SUCCESSFULLY
Notebook 04 environment verified.
Ready for Part D - Load Processed Datasets
====================================================================================================

In [28]:
# ==============================================================================
# Part D - Load Processed Datasets
# D1. Load Processed Datasets
# ==============================================================================

print("="*100)
print("LOADING PROCESSED DATASETS")
print("="*100)

PROCESSED_DATASETS = {}

EXPECTED_DATASETS = {
    "adult_income": "income",
    "bank_marketing": "y",
    "breast_cancer": "diagnosis"
}

for dataset in EXPECTED_DATASETS:

    file_path = os.path.join(
        PROCESSED_DATA_DIR,
        f"{dataset}_processed.csv"
    )

    if not os.path.exists(file_path):
        raise FileNotFoundError(file_path)

    df = pd.read_csv(file_path)

    PROCESSED_DATASETS[dataset] = df

    print(f"{dataset:<20} {df.shape}")

print("\nLoaded:", len(PROCESSED_DATASETS), "datasets")

====================================================================================================
LOADING PROCESSED DATASETS
====================================================================================================
adult_income         (32510, 15)
bank_marketing       (45211, 17)
breast_cancer        (569, 32)

Loaded: 3 datasets

In [29]:
# ==============================================================================
# D2. Load Dataset Splits
# ==============================================================================

print("="*100)
print("LOADING TRAIN / VALIDATION / TEST SPLITS")
print("="*100)

TRAIN_SPLITS = {}
VALIDATION_SPLITS = {}
TEST_SPLITS = {}

SPLIT_DATA_DIR = os.path.join(
    PROJECT_ROOT,
    "datasets",
    "splits"
)

for dataset in EXPECTED_DATASETS:

    dataset_folder = os.path.join(
        SPLIT_DATA_DIR,
        dataset
    )

    train_file = os.path.join(dataset_folder, "train.csv")
    validation_file = os.path.join(dataset_folder, "validation.csv")
    test_file = os.path.join(dataset_folder, "test.csv")

    TRAIN_SPLITS[dataset] = pd.read_csv(train_file)
    VALIDATION_SPLITS[dataset] = pd.read_csv(validation_file)
    TEST_SPLITS[dataset] = pd.read_csv(test_file)

    print(f"\n{dataset}")

    print("Train      :", TRAIN_SPLITS[dataset].shape)

    print("Validation :", VALIDATION_SPLITS[dataset].shape)

    print("Test       :", TEST_SPLITS[dataset].shape)

    # ==============================================================================
# Align split column order with processed datasets
# ==============================================================================

print("=" * 100)
print("ALIGNING SPLIT COLUMN ORDER")
print("=" * 100)

for dataset in EXPECTED_DATASETS:

    reference_columns = PROCESSED_DATASETS[dataset].columns.tolist()

    TRAIN_SPLITS[dataset] = TRAIN_SPLITS[dataset][reference_columns]

    VALIDATION_SPLITS[dataset] = VALIDATION_SPLITS[dataset][reference_columns]

    TEST_SPLITS[dataset] = TEST_SPLITS[dataset][reference_columns]

    print(f"{dataset:<20} ✓ Columns aligned")

====================================================================================================
LOADING TRAIN / VALIDATION / TEST SPLITS
====================================================================================================

adult_income
Train      : (22756, 15)
Validation : (4877, 15)
Test       : (4877, 15)

bank_marketing
Train      : (31647, 17)
Validation : (6782, 17)
Test       : (6782, 17)

breast_cancer
Train      : (398, 32)
Validation : (85, 32)
Test       : (86, 32)
====================================================================================================
ALIGNING SPLIT COLUMN ORDER
====================================================================================================
adult_income         ✓ Columns aligned
bank_marketing       ✓ Columns aligned
breast_cancer        ✓ Columns aligned

In [30]:
# ==============================================================================
# D3. Schema Validation
# ==============================================================================

print("="*100)
print("SCHEMA VALIDATION")
print("="*100)

schema_results = []

for dataset in EXPECTED_DATASETS:

    full_columns = list(PROCESSED_DATASETS[dataset].columns)

    train_columns = list(TRAIN_SPLITS[dataset].columns)

    valid_columns = list(VALIDATION_SPLITS[dataset].columns)

    test_columns = list(TEST_SPLITS[dataset].columns)

    schema_results.append({

        "Dataset": dataset,

        "Train": full_columns == train_columns,

        "Validation": full_columns == valid_columns,

        "Test": full_columns == test_columns

    })

SCHEMA_DF = pd.DataFrame(schema_results)

display(SCHEMA_DF)

====================================================================================================
SCHEMA VALIDATION
====================================================================================================

          Dataset  Train  Validation  Test
0    adult_income   True        True  True
1  bank_marketing   True        True  True
2   breast_cancer   True        True  True

In [31]:
# ==============================================================================
# D4. Dataset Summary
# ==============================================================================

print("="*100)
print("DATASET SUMMARY")
print("="*100)

summary = []

for dataset, df in PROCESSED_DATASETS.items():

    summary.append({

        "Dataset": dataset,

        "Rows": len(df),

        "Columns": df.shape[1],

        "Numeric": len(df.select_dtypes(include="number").columns),

        "Categorical": len(df.select_dtypes(exclude="number").columns),

        "Missing Values": int(df.isna().sum().sum()),

        "Duplicate Rows": int(df.duplicated().sum())

    })

SUMMARY_DF = pd.DataFrame(summary)

display(SUMMARY_DF)

====================================================================================================
DATASET SUMMARY
====================================================================================================

,Dataset,Rows,Columns,Numeric,Categorical,Missing Values,Duplicate Rows
0,adult_income,32510,15,15,0,0,0
1,bank_marketing,45211,17,17,0,0,0
2,breast_cancer,569,32,32,0,0,0

In [32]:
# ==============================================================================
# D5. Feature Type Validation
# ==============================================================================

print("="*100)
print("FEATURE TYPE VALIDATION")
print("="*100)

feature_summary = []

for dataset, df in PROCESSED_DATASETS.items():

    numeric = list(df.select_dtypes(include="number").columns)

    categorical = list(df.select_dtypes(exclude="number").columns)

    feature_summary.append({

        "Dataset": dataset,

        "Numeric Features": len(numeric),

        "Categorical Features": len(categorical)

    })

FEATURE_DF = pd.DataFrame(feature_summary)

display(FEATURE_DF)

====================================================================================================
FEATURE TYPE VALIDATION
====================================================================================================

          Dataset  Numeric Features  Categorical Features
0    adult_income                15                     0
1  bank_marketing                17                     0
2   breast_cancer                32                     0

In [33]:
# ==============================================================================
# D6. Target Validation
# ==============================================================================

print("="*100)
print("TARGET VALIDATION")
print("="*100)

target_results = []

for dataset, target in EXPECTED_DATASETS.items():

    df = PROCESSED_DATASETS[dataset]

    exists = target in df.columns

    classes = None

    if exists:

        classes = df[target].nunique()

    target_results.append({

        "Dataset": dataset,

        "Target": target,

        "Exists": exists,

        "Classes": classes

    })

TARGET_DF = pd.DataFrame(target_results)

display(TARGET_DF)

====================================================================================================
TARGET VALIDATION
====================================================================================================

          Dataset     Target  Exists  Classes
0    adult_income     income    True        2
1  bank_marketing          y    True        2
2   breast_cancer  diagnosis    True        2

In [34]:
# ==============================================================================
# D7. Verification
# ==============================================================================

print("="*100)
print("PART D VERIFICATION")
print("="*100)

verification = {

    "Processed Datasets":
        len(PROCESSED_DATASETS) == 3,

    "Train Splits":
        len(TRAIN_SPLITS) == 3,

    "Validation Splits":
        len(VALIDATION_SPLITS) == 3,

    "Test Splits":
        len(TEST_SPLITS) == 3,

    "Schema Validation":
        SCHEMA_DF[["Train","Validation","Test"]].all().all(),

    "Target Validation":
        TARGET_DF["Exists"].all(),

    "Missing Values":
        SUMMARY_DF["Missing Values"].sum() == 0

}

VERIFY_DF = pd.DataFrame({

    "Component": verification.keys(),

    "Status": verification.values()

})

VERIFY_DF["Result"] = VERIFY_DF["Status"].map(
    lambda x: "PASS" if x else "FAIL"
)

display(VERIFY_DF)

if VERIFY_DF["Status"].all():

    print("\n" + "="*100)

    print("✓ PART D COMPLETED SUCCESSFULLY")

    print("Processed datasets successfully loaded.")

    print("Ready for Part E - Load Metadata")

    print("="*100)

else:

    raise RuntimeError("Part D verification failed.")

====================================================================================================
PART D VERIFICATION
====================================================================================================

            Component  Status Result
0  Processed Datasets    True   PASS
1        Train Splits    True   PASS
2   Validation Splits    True   PASS
3         Test Splits    True   PASS
4   Schema Validation    True   PASS
5   Target Validation    True   PASS
6      Missing Values    True   PASS

====================================================================================================
✓ PART D COMPLETED SUCCESSFULLY
Processed datasets successfully loaded.
Ready for Part E - Load Metadata
====================================================================================================

In [35]:
# ==============================================================================
# Part E - Load Metadata
# E1. Load SDV Metadata
# ==============================================================================

import os
import json
import pandas as pd

print("="*100)
print("LOADING SDV METADATA")
print("="*100)

METADATA_OBJECTS = {}
METADATA_JSON = {}

EXPECTED_DATASETS = {
    "adult_income": "income",
    "bank_marketing": "y",
    "breast_cancer": "diagnosis"
}

for dataset in EXPECTED_DATASETS:

    metadata_file = os.path.join(
        METADATA_DIR,
        f"{dataset}_metadata.json"
    )

    if not os.path.exists(metadata_file):
        raise FileNotFoundError(metadata_file)

    with open(metadata_file, "r") as f:
        metadata = json.load(f)

    METADATA_JSON[dataset] = metadata

    print(f"{dataset:<20} Loaded")

print("\nTotal Metadata Files:", len(METADATA_JSON))

====================================================================================================
LOADING SDV METADATA
====================================================================================================
adult_income         Loaded
bank_marketing       Loaded
breast_cancer        Loaded

Total Metadata Files: 3

In [36]:
# ==============================================================================
# E2. Validate Metadata Consistency
# ==============================================================================

print("="*100)
print("VALIDATING METADATA")
print("="*100)

validation = []

for dataset in EXPECTED_DATASETS:

    df = PROCESSED_DATASETS[dataset]

    metadata = METADATA_JSON[dataset]

    # ------------------------------------------------------------------
    # Detect SDV metadata structure automatically
    # ------------------------------------------------------------------

    if "features" in metadata and isinstance(metadata["features"], dict):

        metadata_columns = list(metadata["features"].keys())

    elif "tables" in metadata:

        table_name = list(metadata["tables"].keys())[0]

        metadata_columns = list(
            metadata["tables"][table_name]["columns"].keys()
        )

    else:

        metadata_columns = []

    dataset_columns = list(df.columns)

    validation.append({

        "Dataset": dataset,

        "Dataset Columns": len(dataset_columns),

        "Metadata Columns": len(metadata_columns),

        "Columns Match":
            set(dataset_columns) == set(metadata_columns)

    })

METADATA_VALIDATION_DF = pd.DataFrame(validation)

display(METADATA_VALIDATION_DF)

====================================================================================================
VALIDATING METADATA
====================================================================================================

          Dataset  Dataset Columns  Metadata Columns  Columns Match
0    adult_income               15                15           True
1  bank_marketing               17                17           True
2   breast_cancer               32                32           True

In [37]:
# ==============================================================================
# E3. Metadata Summary
# ==============================================================================

print("="*100)
print("METADATA SUMMARY")
print("="*100)

summary = []

for dataset in EXPECTED_DATASETS:

    metadata = METADATA_JSON[dataset]

    # Check for 'features' key for single table metadata structure (preferred)
    if "features" in metadata and isinstance(metadata["features"], dict):

        columns = metadata["features"]

    # Fallback to 'tables' key for multi-table metadata structure
    elif "tables" in metadata:

        table = list(metadata["tables"].keys())[0]

        columns = metadata["tables"][table]["columns"]

    else:
        # Handle cases where neither expected structure is found, or 'features' is not a dict.
        # This might indicate an unexpected metadata format.
        columns = {}

    numerical = 0
    categorical = 0
    boolean = 0
    datetime = 0
    other = 0

    for column in columns.values():

        sdtype = column.get("sdtype","unknown")

        if sdtype == "numerical":
            numerical += 1

        elif sdtype == "categorical":
            categorical += 1

        elif sdtype == "boolean":
            boolean += 1

        elif sdtype == "datetime":
            datetime += 1

        else:
            other += 1

    summary.append({

        "Dataset": dataset,

        "Total Columns": len(columns),

        "Numerical": numerical,

        "Categorical": categorical,

        "Boolean": boolean,

        "Datetime": datetime,

        "Other": other

    })

METADATA_SUMMARY_DF = pd.DataFrame(summary)

display(METADATA_SUMMARY_DF)

====================================================================================================
METADATA SUMMARY
====================================================================================================

,Dataset,Total Columns,Numerical,Categorical,Boolean,Datetime,Other
0,adult_income,15,0,0,0,0,15
1,bank_marketing,17,0,0,0,0,17
2,breast_cancer,32,0,0,0,0,32

In [38]:
# ==============================================================================
# E4. Verification
# ==============================================================================

print("="*100)
print("PART E VERIFICATION")
print("="*100)

verification = {

    "Metadata Loaded":
        len(METADATA_JSON) == 3,

    "Metadata Validation":
        METADATA_VALIDATION_DF["Columns Match"].all(),

    "Metadata Summary":
        len(METADATA_SUMMARY_DF) == 3

}

VERIFY_DF = pd.DataFrame({

    "Component": verification.keys(),

    "Status": verification.values()

})

VERIFY_DF["Result"] = VERIFY_DF["Status"].map(
    lambda x: "PASS" if x else "FAIL"
)

display(VERIFY_DF)

if VERIFY_DF["Status"].all():

    print("\n" + "="*100)

    print("✓ PART E COMPLETED SUCCESSFULLY")

    print("Metadata successfully loaded and validated.")

    print("Ready for Part F - CTGAN Data Preparation")

    print("="*100)

else:

    failed = VERIFY_DF[VERIFY_DF["Status"] == False]

    display(failed)

    raise RuntimeError("Part E verification failed.")

====================================================================================================
PART E VERIFICATION
====================================================================================================

             Component  Status Result
0      Metadata Loaded    True   PASS
1  Metadata Validation    True   PASS
2     Metadata Summary    True   PASS

====================================================================================================
✓ PART E COMPLETED SUCCESSFULLY
Metadata successfully loaded and validated.
Ready for Part F - CTGAN Data Preparation
====================================================================================================

In [39]:
# ==============================================================================
# Part F - CTGAN Baseline Preparation
# F1. Imports
# ==============================================================================

print("=" * 100)
print("PART F - CTGAN BASELINE PREPARATION")
print("=" * 100)

!pip install sdv

import os
import json
import random
import warnings

import numpy as np
import pandas as pd
import torch

from sdv.single_table import CTGANSynthesizer
from sdv.metadata import SingleTableMetadata

warnings.filterwarnings("ignore")

====================================================================================================
PART F - CTGAN BASELINE PREPARATION
====================================================================================================
Requirement already satisfied: sdv in /usr/local/lib/python3.12/dist-packages (1.37.3)
Requirement already satisfied: boto3<2.0.0,>=1.28 in /usr/local/lib/python3.12/dist-packages (from sdv) (1.43.50)
Requirement already satisfied: botocore<2.0.0,>=1.31 in /usr/local/lib/python3.12/dist-packages (from sdv) (1.43.50)
Requirement already satisfied: cloudpickle>=2.1.0 in /usr/local/lib/python3.12/dist-packages (from sdv) (3.1.2)
Requirement already satisfied: graphviz>=0.13.2 in /usr/local/lib/python3.12/dist-packages (from sdv) (0.21)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from sdv) (2.0.2)
Requirement already satisfied: pandas<3,>=2.1.1 in /usr/local/lib/python3.12/dist-packages (from sdv) (2.2.2)
Requirement already satisfied: tqdm>=4.29 in /usr/local/lib/python3.12/dist-packages (from sdv) (4.67.3)
Requirement already satisfied: copulas>=0.12.1 in /usr/local/lib/python3.12/dist-packages (from sdv) (0.14.1)
Requirement already satisfied: ctgan>=0.11.1 in /usr/local/lib/python3.12/dist-packages (from sdv) (0.12.1)
Requirement already satisfied: deepecho>=0.7.0 in /usr/local/lib/python3.12/dist-packages (from sdv) (0.8.1)
Requirement already satisfied: rdt>=1.18.2 in /usr/local/lib/python3.12/dist-packages (from sdv) (1.21.1)
Requirement already satisfied: sdmetrics>=0.28.0 in /usr/local/lib/python3.12/dist-packages (from sdv) (0.28.1)
Requirement already satisfied: platformdirs>=4.0 in /usr/local/lib/python3.12/dist-packages (from sdv) (4.10.0)
Requirement already satisfied: pyyaml>=6.0.1 in /usr/local/lib/python3.12/dist-packages (from sdv) (6.0.3)
Requirement already satisfied: jmespath<2.0.0,>=0.7.1 in /usr/local/lib/python3.12/dist-packages (from boto3<2.0.0,>=1.28->sdv) (1.1.0)
Requirement already satisfied: s3transfer<0.20.0,>=0.19.0 in /usr/local/lib/python3.12/dist-packages (from boto3<2.0.0,>=1.28->sdv) (0.19.1)
Requirement already satisfied: python-dateutil<3.0.0,>=2.1 in /usr/local/lib/python3.12/dist-packages (from botocore<2.0.0,>=1.31->sdv) (2.9.0.post0)
Requirement already satisfied: urllib3!=2.2.0,<3,>=1.25.4 in /usr/local/lib/python3.12/dist-packages (from botocore<2.0.0,>=1.31->sdv) (2.5.0)
Requirement already satisfied: plotly>=5.10.0 in /usr/local/lib/python3.12/dist-packages (from copulas>=0.12.1->sdv) (5.24.1)
Requirement already satisfied: scipy>=1.12.0 in /usr/local/lib/python3.12/dist-packages (from copulas>=0.12.1->sdv) (1.16.3)
Requirement already satisfied: torch>=2.3.0 in /usr/local/lib/python3.12/dist-packages (from ctgan>=0.11.1->sdv) (2.11.0+cpu)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas<3,>=2.1.1->sdv) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas<3,>=2.1.1->sdv) (2026.3)
Requirement already satisfied: scikit-learn>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from rdt>=1.18.2->sdv) (1.6.1)
Requirement already satisfied: Faker!=37.11.0,>=17 in /usr/local/lib/python3.12/dist-packages (from rdt>=1.18.2->sdv) (40.31.0)
Requirement already satisfied: tenacity>=6.2.0 in /usr/local/lib/python3.12/dist-packages (from plotly>=5.10.0->copulas>=0.12.1->sdv) (9.1.4)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from plotly>=5.10.0->copulas>=0.12.1->sdv) (26.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil<3.0.0,>=2.1->botocore<2.0.0,>=1.31->sdv) (1.17.0)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn>=1.3.1->rdt>=1.18.2->sdv) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn>=1.3.1->rdt>=1.18.2->sdv) (3.6.0)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from torch>=2.3.0->ctgan>=0.11.1->sdv) (3.29.7)
Requirement already satisfied: typing-extensions>=4.10.0 in /usr/local/lib/python3.12/dist-packages (from torch>=2.3.0->ctgan>=0.11.1->sdv) (4.16.0)
Requirement already satisfied: setuptools<82 in /usr/local/lib/python3.12/dist-packages (from torch>=2.3.0->ctgan>=0.11.1->sdv) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch>=2.3.0->ctgan>=0.11.1->sdv) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch>=2.3.0->ctgan>=0.11.1->sdv) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch>=2.3.0->ctgan>=0.11.1->sdv) (3.1.6)
Requirement already satisfied: fsspec>=0.8.5 in /usr/local/lib/python3.12/dist-packages (from torch>=2.3.0->ctgan>=0.11.1->sdv) (2025.3.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch>=2.3.0->ctgan>=0.11.1->sdv) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch>=2.3.0->ctgan>=0.11.1->sdv) (3.0.3)

In [40]:
# ==============================================================================
# F2. Hyperparameters
# ==============================================================================

print("=" * 100)
print("CTGAN HYPERPARAMETERS")
print("=" * 100)

CTGAN_CONFIG = {

    "epochs": 200,

    "batch_size": 250,

    "embedding_dim": 128,

    "generator_dim": (256, 256),

    "discriminator_dim": (256, 256),

    "generator_lr": 2e-4,

    "discriminator_lr": 2e-4,

    "generator_decay": 1e-6,

    "discriminator_decay": 1e-6,

    "discriminator_steps": 1,

    "verbose": True,

    "cuda": torch.cuda.is_available()

}

for k, v in CTGAN_CONFIG.items():
    print(f"{k:<25}: {v}")

====================================================================================================
CTGAN HYPERPARAMETERS
====================================================================================================
epochs                   : 200
batch_size               : 250
embedding_dim            : 128
generator_dim            : (256, 256)
discriminator_dim        : (256, 256)
generator_lr             : 0.0002
discriminator_lr         : 0.0002
generator_decay          : 1e-06
discriminator_decay      : 1e-06
discriminator_steps      : 1
verbose                  : True
cuda                     : False

In [41]:
# ==============================================================================
# F3. Load SDV Metadata Objects
# ==============================================================================

print("=" * 100)
print("PREPARING SDV METADATA")
print("=" * 100)

SDV_METADATA = {}

for dataset in EXPECTED_DATASETS:

    # The metadata for each dataset has already been loaded into METADATA_JSON
    # in section E1 (Load SDV Metadata).
    # We can create a SingleTableMetadata object directly from the dictionary.
    metadata_dict = METADATA_JSON[dataset]

    # Instantiate an empty SingleTableMetadata object
    sdv_metadata_obj = SingleTableMetadata()

    # Populate the metadata object using the 'features' dictionary
    for column_name, column_details in metadata_dict["features"].items():
        sdtype = column_details.get("type") # Assuming 'type' in your metadata maps to 'sdtype'
        if sdtype: # Only add if a type is specified
            sdv_metadata_obj.add_column(column_name=column_name, sdtype=sdtype)

    # The 'set_model_target' method is no longer available in sdv.SingleTableMetadata.
    # The target column information is passed to the synthesizer when it's initialized.
    # if "target_column" in metadata_dict and metadata_dict["target_column"] is not None:
    #     sdv_metadata_obj.set_model_target(metadata_dict["target_column"])

    SDV_METADATA[dataset] = sdv_metadata_obj

    print(f"{dataset:<20} Loaded")

====================================================================================================
PREPARING SDV METADATA
====================================================================================================
adult_income         Loaded
bank_marketing       Loaded
breast_cancer        Loaded

In [42]:
# ==============================================================================
# F4. Device Configuration
# ==============================================================================

print("=" * 100)
print("DEVICE CONFIGURATION")
print("=" * 100)

DEVICE = "cuda" if torch.cuda.is_available() else "cpu"

print("Device :", DEVICE)

if DEVICE == "cuda":

    print("GPU :", torch.cuda.get_device_name(0))

    print("CUDA :", torch.version.cuda)

else:

    print("Running on CPU")

====================================================================================================
DEVICE CONFIGURATION
====================================================================================================
Device : cpu
Running on CPU

In [43]:
# ==============================================================================
# F5. Dataset Preparation
# ==============================================================================

print("=" * 100)
print("PREPARING TRAINING DATA")
print("=" * 100)

CTGAN_TRAIN_DATA = {}

for dataset in EXPECTED_DATASETS:

    df = TRAIN_SPLITS[dataset].copy()

    CTGAN_TRAIN_DATA[dataset] = df

    print(

        f"{dataset:<20}"

        f"Rows={len(df):<8}"

        f"Cols={df.shape[1]}"

    )

====================================================================================================
PREPARING TRAINING DATA
====================================================================================================
adult_income        Rows=22756   Cols=15
bank_marketing      Rows=31647   Cols=17
breast_cancer       Rows=398     Cols=32

In [44]:
# ==============================================================================
# F6. Initialize CTGAN Models
# ==============================================================================

print("=" * 100)
print("INITIALIZING CTGAN MODELS")
print("=" * 100)

CTGAN_MODELS = {}

for dataset in EXPECTED_DATASETS:

    synthesizer = CTGANSynthesizer(

        metadata=SDV_METADATA[dataset],

        epochs=CTGAN_CONFIG["epochs"],

        batch_size=CTGAN_CONFIG["batch_size"],

        embedding_dim=CTGAN_CONFIG["embedding_dim"],

        generator_dim=CTGAN_CONFIG["generator_dim"],

        discriminator_dim=CTGAN_CONFIG["discriminator_dim"],

        generator_lr=CTGAN_CONFIG["generator_lr"],

        discriminator_lr=CTGAN_CONFIG["discriminator_lr"],

        generator_decay=CTGAN_CONFIG["generator_decay"],

        discriminator_decay=CTGAN_CONFIG["discriminator_decay"],

        discriminator_steps=CTGAN_CONFIG["discriminator_steps"],

        cuda=CTGAN_CONFIG["cuda"],

        verbose=CTGAN_CONFIG["verbose"]

    )

    CTGAN_MODELS[dataset] = synthesizer

    print(f"{dataset:<20} ✓ Initialized")

====================================================================================================
INITIALIZING CTGAN MODELS
====================================================================================================
adult_income         ✓ Initialized
bank_marketing       ✓ Initialized
breast_cancer        ✓ Initialized

In [45]:
# ==============================================================================
# F7. Preparation Summary
# ==============================================================================

print("=" * 100)
print("CTGAN PREPARATION SUMMARY")
print("=" * 100)

summary = []

for dataset in EXPECTED_DATASETS:

    summary.append({

        "Dataset": dataset,

        "Training Rows": len(CTGAN_TRAIN_DATA[dataset]),

        "Training Columns": CTGAN_TRAIN_DATA[dataset].shape[1],

        "Metadata Loaded": dataset in SDV_METADATA,

        "Model Initialized": dataset in CTGAN_MODELS

    })

CTGAN_PREP_DF = pd.DataFrame(summary)

display(CTGAN_PREP_DF)

====================================================================================================
CTGAN PREPARATION SUMMARY
====================================================================================================

,Dataset,Training Rows,Training Columns,Metadata Loaded,Model Initialized
0,adult_income,22756,15,True,True
1,bank_marketing,31647,17,True,True
2,breast_cancer,398,32,True,True

In [46]:
# ==============================================================================
# F8. Verification
# ==============================================================================

print("=" * 100)
print("PART F VERIFICATION")
print("=" * 100)

verification = {

    "Metadata Loaded":
        len(SDV_METADATA) == 3,

    "Training Data":
        len(CTGAN_TRAIN_DATA) == 3,

    "Models Initialized":
        len(CTGAN_MODELS) == 3,

    "GPU Configuration":
        DEVICE in ["cpu", "cuda"],

    "Hyperparameters":
        CTGAN_CONFIG["epochs"] > 0

}

VERIFY_DF = pd.DataFrame({

    "Component": verification.keys(),

    "Status": verification.values()

})

VERIFY_DF["Result"] = VERIFY_DF["Status"].map(
    lambda x: "PASS" if x else "FAIL"
)

display(VERIFY_DF)

if VERIFY_DF["Status"].all():

    print("\n" + "=" * 100)
    print("✓ PART F COMPLETED SUCCESSFULLY")
    print("CTGAN models are initialized and ready for training.")
    print("Ready for Part G - CTGAN Training")
    print("=" * 100)

else:

    raise RuntimeError("Part F verification failed.")

====================================================================================================
PART F VERIFICATION
====================================================================================================

            Component  Status Result
0     Metadata Loaded    True   PASS
1       Training Data    True   PASS
2  Models Initialized    True   PASS
3   GPU Configuration    True   PASS
4     Hyperparameters    True   PASS

====================================================================================================
✓ PART F COMPLETED SUCCESSFULLY
CTGAN models are initialized and ready for training.
Ready for Part G - CTGAN Training
====================================================================================================

In [47]:
# ==============================================================================
# Part G — CTGAN Training
# G1 — Training Setup
# ==============================================================================

print("=" * 100)
print("PART G1 — CTGAN TRAINING SETUP")
print("=" * 100)

import os
import json
import time
import random
from datetime import datetime

import numpy as np
import pandas as pd
import torch

# ==============================================================================
# Reproducibility
# ==============================================================================

SEED = 42

random.seed(SEED)
np.random.seed(SEED)
torch.manual_seed(SEED)

if torch.cuda.is_available():
    torch.cuda.manual_seed(SEED)
    torch.cuda.manual_seed_all(SEED)

# ==============================================================================
# Create output folders
# ==============================================================================

CTGAN_ROOT = os.path.join(
    PROJECT_ROOT,
    "models",
    "ctgan"
)

CTGAN_MODEL_DIR = os.path.join(
    CTGAN_ROOT,
    "trained_models"
)

CTGAN_LOG_DIR = os.path.join(
    CTGAN_ROOT,
    "training_logs"
)

CTGAN_REPORT_DIR = os.path.join(
    PROJECT_ROOT,
    "reports",
    "CTGAN"
)

CTGAN_SYNTHETIC_DIR = os.path.join(
    PROJECT_ROOT,
    "datasets",
    "synthetic",
    "CTGAN"
)

directories = [

    CTGAN_ROOT,

    CTGAN_MODEL_DIR,

    CTGAN_LOG_DIR,

    CTGAN_REPORT_DIR,

    CTGAN_SYNTHETIC_DIR

]

for directory in directories:

    os.makedirs(directory, exist_ok=True)

print("Output directories verified.")

# ==============================================================================
# Training configuration
# ==============================================================================

TRAINING_CONFIGURATION = {

    "Model":"CTGAN",

    "Epochs":CTGAN_CONFIG["epochs"],

    "Batch Size":CTGAN_CONFIG["batch_size"],

    "Embedding Dimension":CTGAN_CONFIG["embedding_dim"],

    "Generator Dimension":CTGAN_CONFIG["generator_dim"],

    "Discriminator Dimension":CTGAN_CONFIG["discriminator_dim"],

    "Generator LR":CTGAN_CONFIG["generator_lr"],

    "Discriminator LR":CTGAN_CONFIG["discriminator_lr"],

    "Device":DEVICE,

    "Random Seed":SEED,

    "Started":datetime.now().strftime("%Y-%m-%d %H:%M:%S")

}

print("\nTraining Configuration")

for k,v in TRAINING_CONFIGURATION.items():

    print(f"{k:<25}: {v}")

# ==============================================================================
# Initialize Training History
# ==============================================================================

CTGAN_HISTORY = {}

TRAINING_SUMMARY = []

MODEL_PATHS = {}

TRAINING_LOGS = {}

# ==============================================================================
# Dataset information
# ==============================================================================

print("\n")
print("="*100)
print("TRAINING DATA SUMMARY")
print("="*100)

dataset_summary = []

for dataset, df in CTGAN_TRAIN_DATA.items():

    dataset_summary.append({

        "Dataset":dataset,

        "Rows":len(df),

        "Columns":df.shape[1],

        "Numeric":

            len(df.select_dtypes(include=np.number).columns),

        "Categorical":

            len(df.select_dtypes(exclude=np.number).columns)

    })

DATASET_SUMMARY_DF = pd.DataFrame(dataset_summary)

display(DATASET_SUMMARY_DF)

# ==============================================================================
# Initialize timers
# ==============================================================================

NOTEBOOK_TRAINING_START = time.time()

print("\nTraining timer initialized.")

# ==============================================================================
# Log configuration
# ==============================================================================

CONFIG_FILE = os.path.join(

    CTGAN_LOG_DIR,

    "training_configuration.json"

)

with open(CONFIG_FILE,"w") as fp:

    json.dump(

        TRAINING_CONFIGURATION,

        fp,

        indent=4

    )

print("Training configuration saved.")

# ==============================================================================
# Ready status
# ==============================================================================

READY_FOR_TRAINING = True

print("\n")

print("="*100)

print("✓ CTGAN TRAINING ENVIRONMENT READY")

print("="*100)

====================================================================================================
PART G1 — CTGAN TRAINING SETUP
====================================================================================================
Output directories verified.

Training Configuration
Model                    : CTGAN
Epochs                   : 200
Batch Size               : 250
Embedding Dimension      : 128
Generator Dimension      : (256, 256)
Discriminator Dimension  : (256, 256)
Generator LR             : 0.0002
Discriminator LR         : 0.0002
Device                   : cpu
Random Seed              : 42
Started                  : 2026-07-17 17:01:39


====================================================================================================
TRAINING DATA SUMMARY
====================================================================================================

          Dataset   Rows  Columns  Numeric  Categorical
0    adult_income  22756       15       15            0
1  bank_marketing  31647       17       17            0
2   breast_cancer    398       32       32            0

Training timer initialized.
Training configuration saved.


====================================================================================================
✓ CTGAN TRAINING ENVIRONMENT READY
====================================================================================================

In [49]:
import os
import time
import pickle
import traceback
from datetime import datetime

SUCCESSFUL_MODELS = []
FAILED_MODELS = []

# The original code here was trying to use 'train_df' before it was defined.
# Also, the batch_size for the CTGAN models is already set in CTGAN_CONFIG
# and passed during synthesizer initialization (see Part F6).
# Thus, these lines are not needed and were causing a NameError.
# rows = len(train_df)

# if rows < 1000:
#     batch_size = 50
# else:
#     batch_size = 250

for dataset in CTGAN_TRAIN_DATA.keys():

    print("\n" + "=" * 100)
    print(f"Training Dataset : {dataset}")
    print("=" * 100)

    train_df = CTGAN_TRAIN_DATA[dataset]
    synthesizer = CTGAN_MODELS[dataset]

    start_time = time.time()

    training_status = "SUCCESS"
    error_message = ""

    try:

        print(f"Rows    : {len(train_df):,}")
        print(f"Columns : {train_df.shape[1]}")

        print("\nStarting CTGAN training...\n")

        # ----------------------------------------------------------------------
        # Train CTGAN
        # ----------------------------------------------------------------------

        synthesizer.fit(train_df)

        elapsed = time.time() - start_time

        print(f"\nTraining completed in {elapsed:.2f} seconds")

        # ----------------------------------------------------------------------
        # Save trained model
        # ----------------------------------------------------------------------

        model_path = os.path.join(
            CTGAN_MODEL_DIR,
            f"{dataset}_ctgan.pkl"
        )

        with open(model_path, "wb") as f:
            pickle.dump(synthesizer, f)

        MODEL_PATHS[dataset] = model_path

        SUCCESSFUL_MODELS.append(dataset)

        print("Model saved:")
        print(model_path)

    except Exception as e:

        elapsed = time.time() - start_time

        training_status = "FAILED"

        error_message = str(e)

        FAILED_MODELS.append(dataset)

        print("\nTraining FAILED\n")

        traceback.print_exc()

    # --------------------------------------------------------------------------
    # Store history
    # --------------------------------------------------------------------------

    CTGAN_HISTORY[dataset] = {

        "dataset": dataset,

        "rows": len(train_df),

        "columns": train_df.shape[1],

        "start_time":
            datetime.fromtimestamp(start_time).strftime("%Y-%m-%d %H:%M:%S"),

        "elapsed_seconds": round(elapsed, 2),

        "status": training_status,

        "model_path":
            MODEL_PATHS.get(dataset, None),

        "error":
            error_message

    }

    TRAINING_SUMMARY.append({

        "Dataset": dataset,

        "Rows": len(train_df),

        "Columns": train_df.shape[1],

        "Training Time (sec)": round(elapsed, 2),

        "Status": training_status,

        "Model Saved":
            training_status == "SUCCESS"

    })

print("\n")
print("=" * 100)
print("CTGAN TRAINING FINISHED")
print("=" * 100)

print(f"Successful Models : {len(SUCCESSFUL_MODELS)}")
print(f"Failed Models     : {len(FAILED_MODELS)}")

if len(FAILED_MODELS):

    print("\nFailed Datasets")

    for d in FAILED_MODELS:
        print("-", d)

====================================================================================================
Training Dataset : adult_income
====================================================================================================
Rows    : 22,756
Columns : 15

Starting CTGAN training...

Gen. (+00.15) | Discrim. (-00.56): 100%|██████████| 200/200 [24:08<00:00,  7.24s/it]

Training completed in 1501.17 seconds
Model saved:
/content/drive/MyDrive/SPP_GAN_Project/models/ctgan/trained_models/adult_income_ctgan.pkl

====================================================================================================
Training Dataset : bank_marketing
====================================================================================================
Rows    : 31,647
Columns : 17

Starting CTGAN training...

Gen. (-00.83) | Discrim. (-00.08): 100%|██████████| 200/200 [27:40<00:00,  8.30s/it]

Training completed in 1725.51 seconds
Model saved:
/content/drive/MyDrive/SPP_GAN_Project/models/ctgan/trained_models/bank_marketing_ctgan.pkl

====================================================================================================
Training Dataset : breast_cancer
====================================================================================================
Rows    : 398
Columns : 32

Starting CTGAN training...

Gen. (-02.18) | Discrim. (-00.48): 100%|██████████| 200/200 [00:17<00:00, 11.61it/s]

Training completed in 25.91 seconds
Model saved:
/content/drive/MyDrive/SPP_GAN_Project/models/ctgan/trained_models/breast_cancer_ctgan.pkl


====================================================================================================
CTGAN TRAINING FINISHED
====================================================================================================
Successful Models : 3
Failed Models     : 0

In [50]:
# ==============================================================================
# Part G3 - Training Time & Progress Logging
# G3.1 Build Training Log
# ==============================================================================

print("=" * 100)
print("PART G3 - TRAINING TIME & PROGRESS LOGGING")
print("=" * 100)

TRAINING_LOG_DF = pd.DataFrame(TRAINING_SUMMARY)

TRAINING_LOG_DF = TRAINING_LOG_DF.sort_values("Dataset")

display(TRAINING_LOG_DF)

====================================================================================================
PART G3 - TRAINING TIME & PROGRESS LOGGING
====================================================================================================

          Dataset   Rows  Columns  Training Time (sec)   Status  Model Saved
0    adult_income  22756       15              1501.17  SUCCESS         True
1  bank_marketing  31647       17              1725.51  SUCCESS         True
2   breast_cancer    398       32                25.91  SUCCESS         True

In [51]:
# ==============================================================================
# G3.2 Detailed Training History
# ==============================================================================

history_rows = []

for dataset in CTGAN_HISTORY:

    info = CTGAN_HISTORY[dataset]

    history_rows.append({

        "Dataset": info["dataset"],

        "Rows": info["rows"],

        "Columns": info["columns"],

        "Training Started": info["start_time"],

        "Training Time (sec)": info["elapsed_seconds"],

        "Training Time (min)": round(info["elapsed_seconds"] / 60, 2),

        "Status": info["status"],

        "Model Path": info["model_path"]

    })

CTGAN_HISTORY_DF = pd.DataFrame(history_rows)

display(CTGAN_HISTORY_DF)

,Dataset,Rows,Columns,Training Started,Training Time (sec),Training Time (min),Status,Model Path
0,adult_income,22756,15,2026-07-17 17:02:45,1501.17,25.02,SUCCESS,/content/drive/MyDrive/SPP_GAN_Project/models/...
1,bank_marketing,31647,17,2026-07-17 17:27:47,1725.51,28.76,SUCCESS,/content/drive/MyDrive/SPP_GAN_Project/models/...
2,breast_cancer,398,32,2026-07-17 17:56:32,25.91,0.43,SUCCESS,/content/drive/MyDrive/SPP_GAN_Project/models/...

In [52]:
# ==============================================================================
# G3.3 Overall Statistics
# ==============================================================================

print("=" * 100)
print("OVERALL TRAINING STATISTICS")
print("=" * 100)

total_time = CTGAN_HISTORY_DF["Training Time (sec)"].sum()

average_time = CTGAN_HISTORY_DF["Training Time (sec)"].mean()

fastest = CTGAN_HISTORY_DF.loc[
    CTGAN_HISTORY_DF["Training Time (sec)"].idxmin()
]

slowest = CTGAN_HISTORY_DF.loc[
    CTGAN_HISTORY_DF["Training Time (sec)"].idxmax()
]

print(f"Total Training Time   : {total_time:.2f} sec")
print(f"Average Training Time : {average_time:.2f} sec")
print()

print(f"Fastest Dataset : {fastest['Dataset']}")
print(f"Time            : {fastest['Training Time (sec)']:.2f} sec")

print()

print(f"Slowest Dataset : {slowest['Dataset']}")
print(f"Time            : {slowest['Training Time (sec)']:.2f} sec")

====================================================================================================
OVERALL TRAINING STATISTICS
====================================================================================================
Total Training Time   : 3252.59 sec
Average Training Time : 1084.20 sec

Fastest Dataset : breast_cancer
Time            : 25.91 sec

Slowest Dataset : bank_marketing
Time            : 1725.51 sec

In [53]:
# ==============================================================================
# G3.4 Save Logs
# ==============================================================================

TRAINING_LOG_CSV = os.path.join(

    CTGAN_LOG_DIR,

    "training_log.csv"

)

TRAINING_HISTORY_CSV = os.path.join(

    CTGAN_LOG_DIR,

    "training_history.csv"

)

TRAINING_LOG_DF.to_csv(

    TRAINING_LOG_CSV,

    index=False

)

CTGAN_HISTORY_DF.to_csv(

    TRAINING_HISTORY_CSV,

    index=False

)

print("Training log saved:")
print(TRAINING_LOG_CSV)

print()

print("Training history saved:")
print(TRAINING_HISTORY_CSV)

Training log saved:
/content/drive/MyDrive/SPP_GAN_Project/models/ctgan/training_logs/training_log.csv

Training history saved:
/content/drive/MyDrive/SPP_GAN_Project/models/ctgan/training_logs/training_history.csv

In [54]:
# ==============================================================================
# G3.5 Save JSON Metadata
# ==============================================================================

TRAINING_METADATA = {

    "Model": "CTGAN",

    "Epochs": CTGAN_CONFIG["epochs"],

    "Batch Size": CTGAN_CONFIG["batch_size"],

    "Embedding Dimension": CTGAN_CONFIG["embedding_dim"],

    "Device": DEVICE,

    "Datasets": len(CTGAN_HISTORY),

    "Successful Models": len(SUCCESSFUL_MODELS),

    "Failed Models": len(FAILED_MODELS),

    "Total Training Time (sec)": float(total_time),

    "Average Training Time (sec)": float(average_time)

}

metadata_file = os.path.join(

    CTGAN_LOG_DIR,

    "training_metadata.json"

)

with open(metadata_file, "w") as fp:

    json.dump(

        TRAINING_METADATA,

        fp,

        indent=4

    )

print("Training metadata saved.")

Training metadata saved.

In [55]:
# ==============================================================================
# G3.6 Verification
# ==============================================================================

print("=" * 100)
print("PART G3 VERIFICATION")
print("=" * 100)

verification = {

    "Training Log":
        os.path.exists(TRAINING_LOG_CSV),

    "Training History":
        os.path.exists(TRAINING_HISTORY_CSV),

    "Training Metadata":
        os.path.exists(metadata_file),

    "History Available":
        len(CTGAN_HISTORY) == 3,

    "No Failed Models":
        len(FAILED_MODELS) == 0

}

VERIFY_DF = pd.DataFrame({

    "Component": verification.keys(),

    "Status": verification.values()

})

VERIFY_DF["Result"] = VERIFY_DF["Status"].map(

    lambda x: "PASS" if x else "FAIL"

)

display(VERIFY_DF)

if VERIFY_DF["Status"].all():

    print("\n" + "=" * 100)
    print("✓ PART G3 COMPLETED SUCCESSFULLY")
    print("Training logs successfully generated.")
    print("Ready for G4 - Save Trained Models")
    print("=" * 100)

else:

    failed = VERIFY_DF[VERIFY_DF["Status"] == False]

    display(failed)

    raise RuntimeError("Part G3 verification failed.")

====================================================================================================
PART G3 VERIFICATION
====================================================================================================

           Component  Status Result
0       Training Log    True   PASS
1   Training History    True   PASS
2  Training Metadata    True   PASS
3  History Available    True   PASS
4   No Failed Models    True   PASS

====================================================================================================
✓ PART G3 COMPLETED SUCCESSFULLY
Training logs successfully generated.
Ready for G4 - Save Trained Models
====================================================================================================

In [56]:
# ==============================================================================
# PART G4.1 — VERIFY TRAINED MODELS
# ==============================================================================

print("="*100)
print("PART G4.1 — VERIFY TRAINED MODELS")
print("="*100)

print(f"Total Models : {len(CTGAN_MODELS)}")

for name in CTGAN_MODELS.keys():
    print(f"✓ {name}")

====================================================================================================
PART G4.1 — VERIFY TRAINED MODELS
====================================================================================================
Total Models : 3
✓ adult_income
✓ bank_marketing
✓ breast_cancer

In [58]:
# ==============================================================================
# PART G4.2 — SAVE TRAINED CTGAN MODELS
# ==============================================================================

import os
import pickle

MODEL_SAVE_DIR = os.path.join(
    PATHS["models"],
    "ctgan",
    "trained_models"
)

os.makedirs(MODEL_SAVE_DIR, exist_ok=True)

MODEL_REGISTRY = []

print("="*100)
print("SAVING TRAINED CTGAN MODELS")
print("="*100)

for dataset_name, model in CTGAN_MODELS.items():

    model_path = os.path.join(
        MODEL_SAVE_DIR,
        f"{dataset_name}_ctgan.pkl"
    )

    model.save(model_path)

    file_size = round(
        os.path.getsize(model_path)/(1024*1024),
        2
    )

    MODEL_REGISTRY.append({

        "Dataset": dataset_name,

        "Model": "CTGAN",

        "Status": "Saved",

        "Model Path": model_path,

        "File Size (MB)": file_size

    })

    print(f"✓ {dataset_name}")
    print(f"Saved : {model_path}")
    print(f"Size  : {file_size:.2f} MB")
    print()

====================================================================================================
SAVING TRAINED CTGAN MODELS
====================================================================================================
✓ adult_income
Saved : /content/drive/MyDrive/SPP_GAN_Project/models/ctgan/trained_models/adult_income_ctgan.pkl
Size  : 1.24 MB

✓ bank_marketing
Saved : /content/drive/MyDrive/SPP_GAN_Project/models/ctgan/trained_models/bank_marketing_ctgan.pkl
Size  : 1.28 MB

✓ breast_cancer
Saved : /content/drive/MyDrive/SPP_GAN_Project/models/ctgan/trained_models/breast_cancer_ctgan.pkl
Size  : 1.78 MB

In [59]:
# ==============================================================================
# PART G4.3 — MODEL REGISTRY
# ==============================================================================

MODEL_REGISTRY_DF = pd.DataFrame(MODEL_REGISTRY)

display(MODEL_REGISTRY_DF)

,Dataset,Model,Status,Model Path,File Size (MB)
0,adult_income,CTGAN,Saved,/content/drive/MyDrive/SPP_GAN_Project/models/...,1.24
1,bank_marketing,CTGAN,Saved,/content/drive/MyDrive/SPP_GAN_Project/models/...,1.28
2,breast_cancer,CTGAN,Saved,/content/drive/MyDrive/SPP_GAN_Project/models/...,1.78

In [60]:
# ==============================================================================
# PART G4.4 — SAVE MODEL REGISTRY
# ==============================================================================

registry_csv = os.path.join(
    MODEL_SAVE_DIR,
    "ctgan_model_registry.csv"
)

registry_json = os.path.join(
    MODEL_SAVE_DIR,
    "ctgan_model_registry.json"
)

MODEL_REGISTRY_DF.to_csv(
    registry_csv,
    index=False
)

MODEL_REGISTRY_DF.to_json(
    registry_json,
    orient="records",
    indent=4
)

print("Registry Saved")

print(registry_csv)
print(registry_json)

Registry Saved
/content/drive/MyDrive/SPP_GAN_Project/models/ctgan/trained_models/ctgan_model_registry.csv
/content/drive/MyDrive/SPP_GAN_Project/models/ctgan/trained_models/ctgan_model_registry.json

In [61]:
# ==============================================================================
# PART G4.5 — VERIFICATION
# ==============================================================================

verification = []

verification.append([
    "Models Trained",
    len(CTGAN_MODELS)==3
])

verification.append([
    "Registry Created",
    len(MODEL_REGISTRY_DF)==3
])

verification.append([
    "Registry CSV",
    os.path.exists(registry_csv)
])

verification.append([
    "Registry JSON",
    os.path.exists(registry_json)
])

for dataset in CTGAN_MODELS.keys():

    verification.append([

        f"{dataset} Model",

        os.path.exists(
            os.path.join(
                MODEL_SAVE_DIR,
                f"{dataset}_ctgan.pkl"
            )
        )

    ])

VERIFY_DF = pd.DataFrame(
    verification,
    columns=["Component","Status"]
)

VERIFY_DF["Result"] = VERIFY_DF["Status"].map(
    lambda x:"PASS" if x else "FAIL"
)

print("="*100)
print("PART G4 VERIFICATION")
print("="*100)

display(VERIFY_DF)

if VERIFY_DF["Status"].all():

    print("\n" + "="*100)
    print("✓ PART G4 COMPLETED SUCCESSFULLY")
    print("All CTGAN models saved successfully.")
    print("Ready for Part H — Synthetic Data Generation")
    print("="*100)

else:

    failed = VERIFY_DF[VERIFY_DF["Status"]==False]

    display(failed)

    raise RuntimeError("Part G4 verification failed.")

====================================================================================================
PART G4 VERIFICATION
====================================================================================================

              Component  Status Result
0        Models Trained    True   PASS
1      Registry Created    True   PASS
2          Registry CSV    True   PASS
3         Registry JSON    True   PASS
4    adult_income Model    True   PASS
5  bank_marketing Model    True   PASS
6   breast_cancer Model    True   PASS

====================================================================================================
✓ PART G4 COMPLETED SUCCESSFULLY
All CTGAN models saved successfully.
Ready for Part H — Synthetic Data Generation
====================================================================================================

In [1]:
# ==============================================================================
# PART H1 — LOAD TRAINED CTGAN MODELS
# ==============================================================================

print("=" * 100)
print("PART H1 — LOAD TRAINED CTGAN MODELS")
print("=" * 100)

import os
from sdv.single_table import CTGANSynthesizer

LOADED_CTGAN_MODELS = {}

MODEL_DIR = os.path.join(
    PROJECT_PATHS["models"],
    "ctgan",
    "trained_models"
)

for dataset in EXPECTED_DATASETS:

    model_path = os.path.join(
        MODEL_DIR,
        f"{dataset}_ctgan.pkl"
    )

    if not os.path.exists(model_path):
        raise FileNotFoundError(model_path)

    model = CTGANSynthesizer.load(model_path)

    LOADED_CTGAN_MODELS[dataset] = model

    print(f"✓ {dataset:<20} Loaded")

print("\nTotal Models Loaded :", len(LOADED_CTGAN_MODELS))

====================================================================================================
PART H1 — LOAD TRAINED CTGAN MODELS
====================================================================================================

ModuleNotFoundError: No module named 'sdv'

In [ ]:
# ==============================================================================
# PART H2 — GENERATE SYNTHETIC DATASETS
# ==============================================================================

print("=" * 100)
print("GENERATING SYNTHETIC DATASETS")
print("=" * 100)

SYNTHETIC_DATASETS = {}

for dataset in EXPECTED_DATASETS:

    real_df = PROCESSED_DATASETS[dataset]

    n_rows = len(real_df)

    print(f"\nGenerating {dataset}")
    print(f"Rows : {n_rows:,}")

    synthetic_df = LOADED_CTGAN_MODELS[dataset].sample(
        num_rows=n_rows
    )

    SYNTHETIC_DATASETS[dataset] = synthetic_df

    print("Completed")

In [ ]:
# ==============================================================================
# PART H3 — VALIDATE SYNTHETIC DATASETS
# ==============================================================================

print("=" * 100)
print("VALIDATING SYNTHETIC DATASETS")
print("=" * 100)

validation = []

for dataset in EXPECTED_DATASETS:

    real = PROCESSED_DATASETS[dataset]

    fake = SYNTHETIC_DATASETS[dataset]

    validation.append({

        "Dataset": dataset,

        "Rows Match":
            len(real) == len(fake),

        "Columns Match":
            list(real.columns) == list(fake.columns),

        "Missing Values":
            int(fake.isna().sum().sum()),

        "Duplicates":
            int(fake.duplicated().sum())

    })

VALIDATION_DF = pd.DataFrame(validation)

display(VALIDATION_DF)

In [ ]:
# ==============================================================================
# PART H4 — SAVE SYNTHETIC DATASETS
# ==============================================================================

print("=" * 100)
print("SAVING SYNTHETIC DATASETS")
print("=" * 100)

SYNTHETIC_DIR = os.path.join(
    PROJECT_PATHS["datasets"],
    "synthetic",
    "CTGAN"
)

os.makedirs(SYNTHETIC_DIR, exist_ok=True)

saved_files = []

for dataset, df in SYNTHETIC_DATASETS.items():

    save_path = os.path.join(
        SYNTHETIC_DIR,
        f"{dataset}_synthetic.csv"
    )

    df.to_csv(
        save_path,
        index=False
    )

    saved_files.append(save_path)

    print(f"✓ {dataset}")

In [ ]:
# ==============================================================================
# PART H5 — SYNTHETIC DATASET SUMMARY
# ==============================================================================

summary = []

for dataset in EXPECTED_DATASETS:

    real = PROCESSED_DATASETS[dataset]

    fake = SYNTHETIC_DATASETS[dataset]

    summary.append({

        "Dataset": dataset,

        "Real Rows": len(real),

        "Synthetic Rows": len(fake),

        "Columns": fake.shape[1],

        "Missing Values":
            int(fake.isna().sum().sum()),

        "Duplicate Rows":
            int(fake.duplicated().sum())

    })

SYNTHETIC_SUMMARY = pd.DataFrame(summary)

display(SYNTHETIC_SUMMARY)

summary_csv = os.path.join(
    SYNTHETIC_DIR,
    "synthetic_dataset_summary.csv"
)

SYNTHETIC_SUMMARY.to_csv(
    summary_csv,
    index=False
)

In [ ]:
# ==============================================================================
# PART H6 — VERIFICATION
# ==============================================================================

verification = {

    "Models Loaded":
        len(LOADED_CTGAN_MODELS) == len(EXPECTED_DATASETS),

    "Synthetic Datasets":
        len(SYNTHETIC_DATASETS) == len(EXPECTED_DATASETS),

    "Summary Created":
        os.path.exists(summary_csv),

    "All Files Saved":
        all(os.path.exists(f) for f in saved_files)
}

VERIFY_DF = pd.DataFrame({
    "Component": verification.keys(),
    "Status": verification.values()
})

VERIFY_DF["Result"] = VERIFY_DF["Status"].map(
    lambda x: "PASS" if x else "FAIL"
)

display(VERIFY_DF)

if VERIFY_DF["Status"].all():

    print("\n" + "=" * 100)
    print("✓ PART H COMPLETED SUCCESSFULLY")
    print("Synthetic datasets generated and saved.")
    print("Ready for Part I — CTGAN Evaluation")
    print("=" * 100)

else:

    failed = VERIFY_DF[VERIFY_DF["Status"] == False]

    display(failed)

    raise RuntimeError("Part H verification failed.")

In [ ]:
# ==============================================================================
# PART I1 — LOAD REAL & SYNTHETIC DATASETS
# ==============================================================================

print("=" * 100)
print("PART I1 — LOAD REAL & SYNTHETIC DATASETS")
print("=" * 100)

import os
import pandas as pd

# ==============================================================================
# Dataset Containers
# ==============================================================================

REAL_DATASETS = {}
SYNTHETIC_DATASETS = {}

# ==============================================================================
# Dataset Paths
# ==============================================================================

REAL_DATA_DIR = PROJECT_PATHS["processed_data"]

SYNTHETIC_DATA_DIR = os.path.join(
    PROJECT_PATHS["datasets"],
    "synthetic",
    "CTGAN"
)

print("\nReal Dataset Directory")
print(REAL_DATA_DIR)

print("\nSynthetic Dataset Directory")
print(SYNTHETIC_DATA_DIR)

# ==============================================================================
# Dataset Names
# ==============================================================================

DATASETS = list(CONFIG["datasets"].keys())

print("\nDatasets")

for dataset in DATASETS:
    print(f"• {dataset}")

# ==============================================================================
# Load Datasets
# ==============================================================================

summary_rows = []

for dataset in DATASETS:

    print("\n" + "-" * 80)
    print(f"Loading {dataset}")

    real_path = os.path.join(
        REAL_DATA_DIR,
        f"{dataset}_processed.csv"
    )

    synthetic_path = os.path.join(
        SYNTHETIC_DATA_DIR,
        f"{dataset}_synthetic.csv"
    )

    if not os.path.exists(real_path):
        raise FileNotFoundError(real_path)

    if not os.path.exists(synthetic_path):
        raise FileNotFoundError(synthetic_path)

    real_df = pd.read_csv(real_path)

    synthetic_df = pd.read_csv(synthetic_path)

    REAL_DATASETS[dataset] = real_df

    SYNTHETIC_DATASETS[dataset] = synthetic_df

    summary_rows.append({

        "Dataset": dataset,

        "Real Rows": len(real_df),

        "Synthetic Rows": len(synthetic_df),

        "Columns": real_df.shape[1],

        "Real Missing":
            int(real_df.isna().sum().sum()),

        "Synthetic Missing":
            int(synthetic_df.isna().sum().sum())

    })

    print("✓ Loaded Successfully")

print("\nAll datasets loaded successfully.")

In [ ]:
# ==============================================================================
# DATASET SUMMARY
# ==============================================================================

SUMMARY_DF = pd.DataFrame(summary_rows)

display(SUMMARY_DF)

In [ ]:
# ==============================================================================
# SCHEMA CONSISTENCY
# ==============================================================================

print("=" * 100)
print("SCHEMA CONSISTENCY")
print("=" * 100)

schema_results = []

for dataset in DATASETS:

    real = REAL_DATASETS[dataset]

    synthetic = SYNTHETIC_DATASETS[dataset]

    same_columns = list(real.columns) == list(synthetic.columns)

    same_dtypes = all(
        real.dtypes.astype(str).values ==
        synthetic.dtypes.astype(str).values
    )

    schema_results.append({

        "Dataset": dataset,

        "Columns Match": same_columns,

        "Data Types Match": same_dtypes

    })

SCHEMA_DF = pd.DataFrame(schema_results)

display(SCHEMA_DF)

In [ ]:
# ==============================================================================
# FEATURE TYPE SUMMARY
# ==============================================================================

feature_rows = []

for dataset in DATASETS:

    df = REAL_DATASETS[dataset]

    feature_rows.append({

        "Dataset": dataset,

        "Numerical":

            len(df.select_dtypes(include="number").columns),

        "Categorical":

            len(df.select_dtypes(exclude="number").columns),

        "Total Features":

            df.shape[1]

    })

FEATURE_DF = pd.DataFrame(feature_rows)

display(FEATURE_DF)

In [ ]:
# ==============================================================================
# SAVE DATASET SUMMARY
# ==============================================================================

REPORT_DIR = os.path.join(
    PROJECT_PATHS["reports"],
    "CTGAN_Evaluation"
)

os.makedirs(REPORT_DIR, exist_ok=True)

SUMMARY_DF.to_csv(
    os.path.join(
        REPORT_DIR,
        "dataset_summary.csv"
    ),
    index=False
)

SCHEMA_DF.to_csv(
    os.path.join(
        REPORT_DIR,
        "schema_validation.csv"
    ),
    index=False
)

FEATURE_DF.to_csv(
    os.path.join(
        REPORT_DIR,
        "feature_summary.csv"
    ),
    index=False
)

print("Dataset summaries saved.")

In [ ]:
# ==============================================================================
# PART I1 VERIFICATION
# ==============================================================================

verification = {

    "Real Datasets Loaded":
        len(REAL_DATASETS) == len(DATASETS),

    "Synthetic Datasets Loaded":
        len(SYNTHETIC_DATASETS) == len(DATASETS),

    "Schema Summary":
        len(SCHEMA_DF) == len(DATASETS),

    "Feature Summary":
        len(FEATURE_DF) == len(DATASETS),

    "Dataset Summary":
        len(SUMMARY_DF) == len(DATASETS)

}

VERIFY_DF = pd.DataFrame({

    "Component": verification.keys(),

    "Status": verification.values()

})

VERIFY_DF["Result"] = VERIFY_DF["Status"].map(
    lambda x: "PASS" if x else "FAIL"
)

print("=" * 100)
print("PART I1 VERIFICATION")
print("=" * 100)

display(VERIFY_DF)

if VERIFY_DF["Status"].all():

    print("\n" + "=" * 100)
    print("✓ PART I1 COMPLETED SUCCESSFULLY")
    print("Real and synthetic datasets loaded successfully.")
    print("Ready for Part I2 — Dataset Structure Evaluation")
    print("=" * 100)

else:

    failed = VERIFY_DF[VERIFY_DF["Status"] == False]

    display(failed)

    raise RuntimeError("Part I1 verification failed.")

In [ ]:
# ==============================================================================
# PART I2.1 — DATASET STRUCTURE EVALUATION
# ==============================================================================

print("=" * 100)
print("PART I2 — DATASET STRUCTURE EVALUATION")
print("=" * 100)

STRUCTURE_RESULTS = []

for dataset in DATASETS:

    real = REAL_DATASETS[dataset]
    fake = SYNTHETIC_DATASETS[dataset]

    target = CONFIG["datasets"][dataset]["target"]

    row_match = len(real) == len(fake)
    col_match = real.shape[1] == fake.shape[1]

    column_order = list(real.columns) == list(fake.columns)
    column_set = set(real.columns) == set(fake.columns)

    dtype_match = all(
        real.dtypes.astype(str).values ==
        fake.dtypes.astype(str).values
    )

    num_real = len(real.select_dtypes(include="number").columns)
    num_fake = len(fake.select_dtypes(include="number").columns)

    cat_real = len(real.select_dtypes(exclude="number").columns)
    cat_fake = len(fake.select_dtypes(exclude="number").columns)

    STRUCTURE_RESULTS.append({

        "Dataset": dataset,

        "Rows Match": row_match,

        "Columns Match": col_match,

        "Column Order": column_order,

        "Column Names": column_set,

        "Data Types": dtype_match,

        "Numeric Features":
            num_real == num_fake,

        "Categorical Features":
            cat_real == cat_fake,

        "Target Exists":
            target in fake.columns,

        "Real Memory (MB)":
            round(real.memory_usage(deep=True).sum()/1024**2,2),

        "Synthetic Memory (MB)":
            round(fake.memory_usage(deep=True).sum()/1024**2,2)

    })

STRUCTURE_DF = pd.DataFrame(STRUCTURE_RESULTS)

display(STRUCTURE_DF)

In [ ]:
# ==============================================================================
# TARGET VARIABLE VALIDATION
# ==============================================================================

TARGET_RESULTS = []

for dataset in DATASETS:

    target = CONFIG["datasets"][dataset]["target"]

    real = REAL_DATASETS[dataset]
    fake = SYNTHETIC_DATASETS[dataset]

    TARGET_RESULTS.append({

        "Dataset": dataset,

        "Target": target,

        "Real Classes":
            real[target].nunique(),

        "Synthetic Classes":
            fake[target].nunique(),

        "Class Count Match":
            real[target].nunique() == fake[target].nunique()

    })

TARGET_STRUCTURE_DF = pd.DataFrame(TARGET_RESULTS)

display(TARGET_STRUCTURE_DF)

In [ ]:
# ==============================================================================
# STRUCTURAL SIMILARITY SCORE
# ==============================================================================

scores = []

for _, row in STRUCTURE_DF.iterrows():

    score = 0

    checks = [

        "Rows Match",
        "Columns Match",
        "Column Order",
        "Column Names",
        "Data Types",
        "Numeric Features",
        "Categorical Features",
        "Target Exists"

    ]

    for c in checks:

        if row[c]:

            score += 1

    similarity = round(score/len(checks)*100,2)

    scores.append(similarity)

STRUCTURE_DF["Structure Score (%)"] = scores

display(STRUCTURE_DF)

In [ ]:
# ==============================================================================
# SAVE STRUCTURE REPORT
# ==============================================================================

structure_report = os.path.join(

    REPORT_DIR,

    "dataset_structure_evaluation.csv"

)

target_report = os.path.join(

    REPORT_DIR,

    "target_structure_evaluation.csv"

)

STRUCTURE_DF.to_csv(

    structure_report,

    index=False

)

TARGET_STRUCTURE_DF.to_csv(

    target_report,

    index=False

)

print("Structure reports saved.")

In [ ]:
# ==============================================================================
# STRUCTURE SUMMARY
# ==============================================================================

summary = STRUCTURE_DF[

    [

        "Dataset",

        "Structure Score (%)"

    ]

]

display(summary)

print()

print("Average Structural Similarity")

print(

    round(

        summary["Structure Score (%)"].mean(),

        2

    ),

    "%"

)

In [ ]:
# ==============================================================================
# PART I2 VERIFICATION
# ==============================================================================

verification = {

    "Structure Evaluation":
        len(STRUCTURE_DF)==len(DATASETS),

    "Target Evaluation":
        len(TARGET_STRUCTURE_DF)==len(DATASETS),

    "Structure Report":
        os.path.exists(structure_report),

    "Target Report":
        os.path.exists(target_report),

    "Average Score > 95%":
        STRUCTURE_DF["Structure Score (%)"].mean() >=95

}

VERIFY_DF = pd.DataFrame({

    "Component":verification.keys(),

    "Status":verification.values()

})

VERIFY_DF["Result"] = VERIFY_DF["Status"].map(

    lambda x:"PASS" if x else "FAIL"

)

print("="*100)

print("PART I2 VERIFICATION")

print("="*100)

display(VERIFY_DF)

if VERIFY_DF["Status"].all():

    print("\n"+"="*100)

    print("✓ PART I2 COMPLETED SUCCESSFULLY")

    print("Dataset structures successfully validated.")

    print("Ready for Part I3 — Missing Value Evaluation")

    print("="*100)

else:

    display(

        VERIFY_DF[VERIFY_DF["Status"]==False]

    )

    raise RuntimeError(

        "Part I2 verification failed."

    )

In [ ]:
# ==============================================================================
# PART I3.1 — OVERALL MISSING VALUE EVALUATION
# ==============================================================================

print("=" * 100)
print("PART I3 — MISSING VALUE EVALUATION")
print("=" * 100)

import os
import pandas as pd
import numpy as np

MISSING_SUMMARY = []

for dataset in DATASETS:

    real = REAL_DATASETS[dataset]
    synthetic = SYNTHETIC_DATASETS[dataset]

    real_missing = int(real.isna().sum().sum())
    synthetic_missing = int(synthetic.isna().sum().sum())

    real_percent = round(
        real.isna().sum().sum() /
        (real.shape[0] * real.shape[1]) * 100,
        4
    )

    synthetic_percent = round(
        synthetic.isna().sum().sum() /
        (synthetic.shape[0] * synthetic.shape[1]) * 100,
        4
    )

    MISSING_SUMMARY.append({

        "Dataset": dataset,

        "Real Missing": real_missing,

        "Synthetic Missing": synthetic_missing,

        "Real Missing (%)": real_percent,

        "Synthetic Missing (%)": synthetic_percent,

        "Difference": synthetic_missing - real_missing

    })

MISSING_SUMMARY_DF = pd.DataFrame(MISSING_SUMMARY)

display(MISSING_SUMMARY_DF)

In [ ]:
# ==============================================================================
# COLUMN-WISE MISSING VALUES
# ==============================================================================

COLUMN_MISSING = {}

for dataset in DATASETS:

    real = REAL_DATASETS[dataset]
    synthetic = SYNTHETIC_DATASETS[dataset]

    report = pd.DataFrame({

        "Feature": real.columns,

        "Real Missing":
            real.isna().sum().values,

        "Synthetic Missing":
            synthetic.isna().sum().values

    })

    report["Difference"] = (

        report["Synthetic Missing"]

        -

        report["Real Missing"]

    )

    COLUMN_MISSING[dataset] = report

    print("\n" + "=" * 80)
    print(dataset.upper())
    display(report)

In [ ]:
# ==============================================================================
# MISSING VALUE HEATMAPS
# ==============================================================================

import matplotlib.pyplot as plt

HEATMAP_DIR = os.path.join(
    REPORT_DIR,
    "missing_value_heatmaps"
)

os.makedirs(HEATMAP_DIR, exist_ok=True)

for dataset in DATASETS:

    real = REAL_DATASETS[dataset]
    synthetic = SYNTHETIC_DATASETS[dataset]

    fig, ax = plt.subplots(
        figsize=(14,5)
    )

    comparison = pd.DataFrame({

        "Real":
            real.isna().sum(),

        "Synthetic":
            synthetic.isna().sum()

    })

    comparison.plot(
        kind="bar",
        ax=ax
    )

    ax.set_title(f"{dataset} Missing Values")

    plt.tight_layout()

    plt.savefig(

        os.path.join(

            HEATMAP_DIR,

            f"{dataset}_missing_values.png"

        ),

        dpi=300

    )

    plt.show()

print("Missing value plots generated.")

In [ ]:
# ==============================================================================
# MISSING VALUE SCORE
# ==============================================================================

scores = []

for _, row in MISSING_SUMMARY_DF.iterrows():

    if row["Difference"] == 0:

        score = 100

    else:

        score = max(

            0,

            100 -

            abs(row["Difference"])

        )

    scores.append(score)

MISSING_SUMMARY_DF["Missing Value Score"] = scores

display(MISSING_SUMMARY_DF)

In [ ]:
# ==============================================================================
# SAVE REPORTS
# ==============================================================================

missing_summary_csv = os.path.join(

    REPORT_DIR,

    "missing_value_summary.csv"

)

MISSING_SUMMARY_DF.to_csv(

    missing_summary_csv,

    index=False

)

for dataset in DATASETS:

    COLUMN_MISSING[dataset].to_csv(

        os.path.join(

            REPORT_DIR,

            f"{dataset}_missing_report.csv"

        ),

        index=False

    )

print("Missing value reports saved.")

In [ ]:
# ==============================================================================
# OVERALL SUMMARY
# ==============================================================================

print("=" * 100)
print("OVERALL MISSING VALUE SUMMARY")
print("=" * 100)

display(

    MISSING_SUMMARY_DF[

        [

            "Dataset",

            "Real Missing",

            "Synthetic Missing",

            "Missing Value Score"

        ]

    ]

)

print()

print(

    "Average Missing Value Score :",

    round(

        MISSING_SUMMARY_DF["Missing Value Score"].mean(),

        2

    ),

    "%"

)

In [ ]:
# ==============================================================================
# PART I3 VERIFICATION
# ==============================================================================

verification = {

    "Summary Created":

        len(MISSING_SUMMARY_DF) == len(DATASETS),

    "Column Reports":

        len(COLUMN_MISSING) == len(DATASETS),

    "Summary CSV":

        os.path.exists(

            missing_summary_csv

        ),

    "Heatmaps":

        os.path.exists(

            HEATMAP_DIR

        ),

    "Average Score > 95%":

        MISSING_SUMMARY_DF[

            "Missing Value Score"

        ].mean() >= 95

}

VERIFY_DF = pd.DataFrame({

    "Component":

        verification.keys(),

    "Status":

        verification.values()

})

VERIFY_DF["Result"] = VERIFY_DF["Status"].map(

    lambda x:

    "PASS" if x else "FAIL"

)

print("=" * 100)
print("PART I3 VERIFICATION")
print("=" * 100)

display(VERIFY_DF)

if VERIFY_DF["Status"].all():

    print("\n" + "=" * 100)
    print("✓ PART I3 COMPLETED SUCCESSFULLY")
    print("Missing value evaluation completed.")
    print("Ready for Part I4 — Descriptive Statistics Comparison")
    print("=" * 100)

else:

    display(

        VERIFY_DF[

            VERIFY_DF["Status"] == False

        ]

    )

    raise RuntimeError(

        "Part I3 verification failed."

    )

In [ ]:
# ==============================================================================
# PART I4.1 — DESCRIPTIVE STATISTICS COMPARISON
# ==============================================================================

print("=" * 100)
print("PART I4 — DESCRIPTIVE STATISTICS COMPARISON")
print("=" * 100)

import os
import numpy as np
import pandas as pd

STATISTICS_REPORT = {}

for dataset in DATASETS:

    print("\n" + "="*80)
    print(dataset.upper())
    print("="*80)

    real = REAL_DATASETS[dataset]
    fake = SYNTHETIC_DATASETS[dataset]

    numeric_cols = real.select_dtypes(include=np.number).columns

    report = []

    for col in numeric_cols:

        report.append({

            "Feature": col,

            "Real Mean": real[col].mean(),
            "Synthetic Mean": fake[col].mean(),

            "Real Median": real[col].median(),
            "Synthetic Median": fake[col].median(),

            "Real Std": real[col].std(),
            "Synthetic Std": fake[col].std(),

            "Real Min": real[col].min(),
            "Synthetic Min": fake[col].min(),

            "Real Max": real[col].max(),
            "Synthetic Max": fake[col].max(),

            "Real Q1": real[col].quantile(0.25),
            "Synthetic Q1": fake[col].quantile(0.25),

            "Real Q3": real[col].quantile(0.75),
            "Synthetic Q3": fake[col].quantile(0.75)

        })

    report = pd.DataFrame(report)

    STATISTICS_REPORT[dataset] = report

    display(report.head())

In [ ]:
# ==============================================================================
# MEAN DIFFERENCE
# ==============================================================================

MEAN_RESULTS = {}

for dataset, report in STATISTICS_REPORT.items():

    result = report.copy()

    result["Mean Difference"] = (
        result["Synthetic Mean"] -
        result["Real Mean"]
    ).abs()

    result["Median Difference"] = (
        result["Synthetic Median"] -
        result["Real Median"]
    ).abs()

    result["Std Difference"] = (
        result["Synthetic Std"] -
        result["Real Std"]
    ).abs()

    MEAN_RESULTS[dataset] = result

    print("\n", dataset)

    display(
        result[
            [
                "Feature",
                "Mean Difference",
                "Median Difference",
                "Std Difference"
            ]
        ]
    )

In [ ]:
# ==============================================================================
# DATASET SUMMARY STATISTICS
# ==============================================================================

SUMMARY_STATS = []

for dataset, report in MEAN_RESULTS.items():

    SUMMARY_STATS.append({

        "Dataset": dataset,

        "Average Mean Difference":
            report["Mean Difference"].mean(),

        "Average Median Difference":
            report["Median Difference"].mean(),

        "Average Std Difference":
            report["Std Difference"].mean()

    })

SUMMARY_STATS_DF = pd.DataFrame(SUMMARY_STATS)

display(SUMMARY_STATS_DF)

In [ ]:
# ==============================================================================
# DESCRIPTIVE STATISTICS SCORE
# ==============================================================================

scores = []

for _, row in SUMMARY_STATS_DF.iterrows():

    error = (
        row["Average Mean Difference"] +
        row["Average Median Difference"] +
        row["Average Std Difference"]
    ) / 3

    score = max(0, 100 - error)

    scores.append(round(score,2))

SUMMARY_STATS_DF["Statistics Score"] = scores

display(SUMMARY_STATS_DF)

In [ ]:
# ==============================================================================
# BOXPLOT COMPARISON
# ==============================================================================

import matplotlib.pyplot as plt

BOXPLOT_DIR = os.path.join(
    REPORT_DIR,
    "boxplot_comparison"
)

os.makedirs(BOXPLOT_DIR, exist_ok=True)

for dataset in DATASETS:

    real = REAL_DATASETS[dataset]
    fake = SYNTHETIC_DATASETS[dataset]

    numeric_cols = real.select_dtypes(include=np.number).columns[:6]

    for col in numeric_cols:

        fig = plt.figure(figsize=(6,5))

        plt.boxplot(
            [real[col], fake[col]],
            labels=["Real","Synthetic"]
        )

        plt.title(f"{dataset} : {col}")

        plt.tight_layout()

        plt.savefig(
            os.path.join(
                BOXPLOT_DIR,
                f"{dataset}_{col}.png"
            ),
            dpi=300
        )

        plt.close()

print("Boxplots saved.")

In [ ]:
# ==============================================================================
# SAVE REPORTS
# ==============================================================================

STAT_DIR = os.path.join(
    REPORT_DIR,
    "descriptive_statistics"
)

os.makedirs(STAT_DIR, exist_ok=True)

for dataset, df in MEAN_RESULTS.items():

    df.to_csv(
        os.path.join(
            STAT_DIR,
            f"{dataset}_statistics.csv"
        ),
        index=False
    )

SUMMARY_STATS_DF.to_csv(
    os.path.join(
        STAT_DIR,
        "summary_statistics.csv"
    ),
    index=False
)

print("Descriptive statistics reports saved.")

In [ ]:
# ==============================================================================
# OVERALL SUMMARY
# ==============================================================================

print("="*100)
print("DESCRIPTIVE STATISTICS SUMMARY")
print("="*100)

display(SUMMARY_STATS_DF)

print()

print(
    "Average Statistics Score :",
    round(
        SUMMARY_STATS_DF["Statistics Score"].mean(),
        2
    ),
    "%"
)

In [ ]:
# ==============================================================================
# PART I4 VERIFICATION
# ==============================================================================

verification = {

    "Statistics Generated":
        len(STATISTICS_REPORT)==len(DATASETS),

    "Difference Calculated":
        len(MEAN_RESULTS)==len(DATASETS),

    "Summary Created":
        len(SUMMARY_STATS_DF)==len(DATASETS),

    "Statistics Reports":
        os.path.exists(STAT_DIR),

    "Boxplots":
        os.path.exists(BOXPLOT_DIR)

}

VERIFY_DF = pd.DataFrame({

    "Component":
        verification.keys(),

    "Status":
        verification.values()

})

VERIFY_DF["Result"] = VERIFY_DF["Status"].map(
    lambda x:"PASS" if x else "FAIL"
)

print("="*100)
print("PART I4 VERIFICATION")
print("="*100)

display(VERIFY_DF)

if VERIFY_DF["Status"].all():

    print("\n"+"="*100)
    print("✓ PART I4 COMPLETED SUCCESSFULLY")
    print("Descriptive statistics comparison completed.")
    print("Ready for Part I5 — Distribution Similarity")
    print("="*100)

else:

    display(
        VERIFY_DF[
            VERIFY_DF["Status"]==False
        ]
    )

    raise RuntimeError(
        "Part I4 verification failed."
    )

In [ ]:
# ==============================================================================
# PART I5.1 — IMPORTS & EVALUATION SETUP
# Research: Privacy-Preserving High-Fidelity Synthetic Data Generation
# ==============================================================================

print("=" * 100)
print("PART I5.1 — IMPORTS & EVALUATION SETUP")
print("=" * 100)

import os
import json
import warnings
import numpy as np
import pandas as pd

from scipy.stats import ks_2samp
from scipy.stats import wasserstein_distance
from scipy.spatial.distance import jensenshannon

import matplotlib.pyplot as plt

warnings.filterwarnings("ignore")

# ==============================================================================
# Random Seed
# ==============================================================================

SEED = CONFIG["reproducibility"]["seed"]

np.random.seed(SEED)

print(f"Random Seed : {SEED}")

# ==============================================================================
# Evaluation Directories
# ==============================================================================

EVALUATION_DIR = os.path.join(
    REPORT_DIR,
    "distribution_similarity"
)

PLOT_DIR = os.path.join(
    EVALUATION_DIR,
    "plots"
)

HISTOGRAM_DIR = os.path.join(
    PLOT_DIR,
    "histograms"
)

KDE_DIR = os.path.join(
    PLOT_DIR,
    "kde"
)

CDF_DIR = os.path.join(
    PLOT_DIR,
    "cdf"
)

for folder in [

    EVALUATION_DIR,
    PLOT_DIR,
    HISTOGRAM_DIR,
    KDE_DIR,
    CDF_DIR

]:

    os.makedirs(folder, exist_ok=True)

print("Evaluation folders created.")

In [ ]:
# ==============================================================================
# RESULT CONTAINERS
# ==============================================================================

KS_RESULTS = {}

WASSERSTEIN_RESULTS = {}

JSD_RESULTS = {}

FIDELITY_RESULTS = {}

SUMMARY_RESULTS = []

print("Evaluation containers initialized.")

In [ ]:
# ==============================================================================
# NUMERIC FEATURE DETECTION
# ==============================================================================

NUMERIC_COLUMNS = {}

for dataset in DATASETS:

    real = REAL_DATASETS[dataset]

    numeric = list(

        real.select_dtypes(

            include=np.number

        ).columns

    )

    NUMERIC_COLUMNS[dataset] = numeric

print()

for dataset in DATASETS:

    print(

        f"{dataset:20s}",

        len(NUMERIC_COLUMNS[dataset]),

        "numeric features"

    )

In [ ]:
# ==============================================================================
# SAFE HISTOGRAM
# ==============================================================================

def compute_histogram(values, bins=30):

    values = np.asarray(values)

    values = values[~np.isnan(values)]

    if len(values) == 0:

        return np.ones(bins) / bins

    hist, _ = np.histogram(

        values,

        bins=bins,

        density=True

    )

    hist = hist + 1e-12

    hist = hist / hist.sum()

    return hist

In [ ]:
# ==============================================================================
# JENSEN-SHANNON DIVERGENCE
# ==============================================================================

def calculate_jsd(

        real_values,

        synthetic_values,

        bins=30

):

    real_hist = compute_histogram(

        real_values,

        bins

    )

    synthetic_hist = compute_histogram(

        synthetic_values,

        bins

    )

    return float(

        jensenshannon(

            real_hist,

            synthetic_hist

        )

    )

In [ ]:
# ==============================================================================
# SAFE ARRAY PREPARATION
# ==============================================================================

def prepare_numeric(real, synthetic):

    real = pd.to_numeric(

        real,

        errors="coerce"

    ).dropna()

    synthetic = pd.to_numeric(

        synthetic,

        errors="coerce"

    ).dropna()

    return real, synthetic

In [ ]:
# ==============================================================================
# FIDELITY SCORE
# ==============================================================================

def fidelity_score(

        ks,

        wasserstein,

        jsd

):

    ks_score = (1 - ks) * 100

    js_score = (1 - jsd) * 100

    wd_score = 100 / (1 + wasserstein)

    return round(

        (

            ks_score +

            js_score +

            wd_score

        ) / 3,

        2

    )

In [ ]:
# ==============================================================================
# DATASET SUMMARY
# ==============================================================================

summary = []

for dataset in DATASETS:

    real = REAL_DATASETS[dataset]

    fake = SYNTHETIC_DATASETS[dataset]

    summary.append({

        "Dataset":

            dataset,

        "Rows (Real)":

            len(real),

        "Rows (Synthetic)":

            len(fake),

        "Numeric Features":

            len(

                NUMERIC_COLUMNS[dataset]

            ),

        "Categorical Features":

            real.shape[1] -

            len(NUMERIC_COLUMNS[dataset])

    })

SUMMARY_DF = pd.DataFrame(summary)

display(SUMMARY_DF)

In [ ]:
# ==============================================================================
# SAVE DATASET SUMMARY
# ==============================================================================

SUMMARY_DF.to_csv(

    os.path.join(

        EVALUATION_DIR,

        "dataset_summary.csv"

    ),

    index=False

)

print("Dataset summary saved.")

In [ ]:
# ==============================================================================
# PART I5.1 VERIFICATION
# ==============================================================================

verification = {

    "Evaluation Directory":

        os.path.exists(EVALUATION_DIR),

    "Histogram Directory":

        os.path.exists(HISTOGRAM_DIR),

    "KDE Directory":

        os.path.exists(KDE_DIR),

    "CDF Directory":

        os.path.exists(CDF_DIR),

    "Numeric Columns":

        len(NUMERIC_COLUMNS) == len(DATASETS),

    "Summary":

        len(SUMMARY_DF) == len(DATASETS)

}

VERIFY_DF = pd.DataFrame({

    "Component":

        verification.keys(),

    "Status":

        verification.values()

})

VERIFY_DF["Result"] = VERIFY_DF["Status"].map(

    lambda x:

    "PASS" if x else "FAIL"

)

print("=" * 100)
print("PART I5.1 VERIFICATION")
print("=" * 100)

display(VERIFY_DF)

if VERIFY_DF["Status"].all():

    print("\n" + "=" * 100)
    print("✓ PART I5.1 COMPLETED SUCCESSFULLY")
    print("Ready for Part I5.2 — Kolmogorov–Smirnov (KS) Test")
    print("=" * 100)

else:

    display(

        VERIFY_DF[

            VERIFY_DF["Status"] == False

        ]

    )

    raise RuntimeError(

        "Part I5.1 verification failed."

    )

In [ ]:
# ==============================================================================
# PART I5.2.1 — KOLMOGOROV-SMIRNOV TEST
# ==============================================================================

print("=" * 100)
print("PART I5.2 — KOLMOGOROV-SMIRNOV TEST")
print("=" * 100)

from scipy.stats import ks_2samp

KS_RESULTS = {}
KS_SUMMARY = []

for dataset in DATASETS:

    print(f"\nProcessing : {dataset}")

    real = REAL_DATASETS[dataset]
    synthetic = SYNTHETIC_DATASETS[dataset]

    rows = []

    for feature in NUMERIC_COLUMNS[dataset]:

        real_values, synthetic_values = prepare_numeric(
            real[feature],
            synthetic[feature]
        )

        if len(real_values) < 2 or len(synthetic_values) < 2:

            statistic = np.nan
            pvalue = np.nan
            decision = "INSUFFICIENT DATA"

        else:

            statistic, pvalue = ks_2samp(
                real_values,
                synthetic_values
            )

            decision = (
                "SIMILAR"
                if pvalue >= 0.05
                else "DIFFERENT"
            )

        rows.append({

            "Feature": feature,

            "KS Statistic": round(statistic,6)
            if pd.notna(statistic) else np.nan,

            "P-Value": round(pvalue,6)
            if pd.notna(pvalue) else np.nan,

            "Decision": decision

        })

    result = pd.DataFrame(rows)

    KS_RESULTS[dataset] = result

    display(result.head())

In [ ]:
# ==============================================================================
# DATASET KS SUMMARY
# ==============================================================================

for dataset, result in KS_RESULTS.items():

    avg_ks = result["KS Statistic"].mean()

    avg_p = result["P-Value"].mean()

    similar = (result["Decision"]=="SIMILAR").sum()

    total = len(result)

    KS_SUMMARY.append({

        "Dataset": dataset,

        "Features": total,

        "Average KS": round(avg_ks,4),

        "Average P-Value": round(avg_p,4),

        "Similar Features": similar,

        "Different Features": total-similar,

        "Similarity (%)": round(
            similar/total*100,
            2
        )

    })

KS_SUMMARY_DF = pd.DataFrame(KS_SUMMARY)

display(KS_SUMMARY_DF)

In [ ]:
# ==============================================================================
# KS SIMILARITY SCORE
# ==============================================================================

KS_SUMMARY_DF["KS Score"] = (

    100 -

    KS_SUMMARY_DF["Average KS"]*100

).clip(lower=0)

display(KS_SUMMARY_DF)

In [ ]:
# ==============================================================================
# SAVE REPORTS
# ==============================================================================

KS_DIR = os.path.join(

    EVALUATION_DIR,

    "ks_test"

)

os.makedirs(KS_DIR, exist_ok=True)

for dataset, report in KS_RESULTS.items():

    report.to_csv(

        os.path.join(

            KS_DIR,

            f"{dataset}_ks_results.csv"

        ),

        index=False

    )

KS_SUMMARY_DF.to_csv(

    os.path.join(

        KS_DIR,

        "ks_summary.csv"

    ),

    index=False

)

print("KS reports saved.")

In [ ]:
# ==============================================================================
# OVERALL SUMMARY
# ==============================================================================

print("="*100)
print("KS TEST SUMMARY")
print("="*100)

display(KS_SUMMARY_DF)

print()

print(

    "Average Similarity :",

    round(

        KS_SUMMARY_DF["Similarity (%)"].mean(),

        2

    ),

    "%"

)

print(

    "Average KS Score :",

    round(

        KS_SUMMARY_DF["KS Score"].mean(),

        2

    )

)

In [ ]:
# ==============================================================================
# STORE RESULTS
# ==============================================================================

FIDELITY_RESULTS["KS Test"] = KS_SUMMARY_DF.copy()

SUMMARY_RESULTS.append(

    KS_SUMMARY_DF

)

print("KS results stored.")

In [ ]:
# ==============================================================================
# PART I5.2 VERIFICATION
# ==============================================================================

verification = {

    "KS Results":

        len(KS_RESULTS)==len(DATASETS),

    "KS Summary":

        len(KS_SUMMARY_DF)==len(DATASETS),

    "Reports Saved":

        os.path.exists(KS_DIR),

    "Average Score":

        KS_SUMMARY_DF["KS Score"].mean()>=0

}

VERIFY_DF = pd.DataFrame({

    "Component":

        verification.keys(),

    "Status":

        verification.values()

})

VERIFY_DF["Result"] = VERIFY_DF["Status"].map(

    lambda x:

    "PASS" if x else "FAIL"

)

print("="*100)
print("PART I5.2 VERIFICATION")
print("="*100)

display(VERIFY_DF)

if VERIFY_DF["Status"].all():

    print("\n"+"="*100)

    print("✓ PART I5.2 COMPLETED SUCCESSFULLY")

    print("Ready for Part I5.3 — Wasserstein Distance")

    print("="*100)

else:

    display(

        VERIFY_DF[VERIFY_DF["Status"]==False]

    )

    raise RuntimeError(

        "Part I5.2 verification failed."

    )

In [ ]:
# ==============================================================================
# PART I5.3.1 — WASSERSTEIN DISTANCE
# ==============================================================================

print("=" * 100)
print("PART I5.3 — WASSERSTEIN DISTANCE")
print("=" * 100)

from scipy.stats import wasserstein_distance

WASSERSTEIN_RESULTS = {}
WASSERSTEIN_SUMMARY = []

for dataset in DATASETS:

    print(f"\nProcessing : {dataset}")

    real = REAL_DATASETS[dataset]
    synthetic = SYNTHETIC_DATASETS[dataset]

    rows = []

    for feature in NUMERIC_COLUMNS[dataset]:

        real_values, synthetic_values = prepare_numeric(
            real[feature],
            synthetic[feature]
        )

        if len(real_values) < 2 or len(synthetic_values) < 2:

            distance = np.nan

        else:

            distance = wasserstein_distance(
                real_values,
                synthetic_values
            )

        rows.append({

            "Feature": feature,

            "Wasserstein Distance":
                round(distance, 6)
                if pd.notna(distance)
                else np.nan

        })

    result = pd.DataFrame(rows)

    WASSERSTEIN_RESULTS[dataset] = result

    display(result.head())

In [ ]:
# ==============================================================================
# DATASET SUMMARY
# ==============================================================================

for dataset, result in WASSERSTEIN_RESULTS.items():

    avg_distance = result[
        "Wasserstein Distance"
    ].mean()

    min_distance = result[
        "Wasserstein Distance"
    ].min()

    max_distance = result[
        "Wasserstein Distance"
    ].max()

    WASSERSTEIN_SUMMARY.append({

        "Dataset": dataset,

        "Features": len(result),

        "Average Distance":
            round(avg_distance,6),

        "Minimum Distance":
            round(min_distance,6),

        "Maximum Distance":
            round(max_distance,6)

    })

WASSERSTEIN_SUMMARY_DF = pd.DataFrame(
    WASSERSTEIN_SUMMARY
)

display(WASSERSTEIN_SUMMARY_DF)

In [ ]:
# ==============================================================================
# DISTANCE BAR CHART
# ==============================================================================

WD_PLOT_DIR = os.path.join(
    EVALUATION_DIR,
    "wasserstein_plots"
)

os.makedirs(WD_PLOT_DIR, exist_ok=True)

for dataset, report in WASSERSTEIN_RESULTS.items():

    plt.figure(figsize=(12,5))

    plt.bar(
        report["Feature"],
        report["Wasserstein Distance"]
    )

    plt.xticks(rotation=90)

    plt.ylabel("Distance")

    plt.title(
        f"{dataset} Wasserstein Distance"
    )

    plt.tight_layout()

    plt.savefig(
        os.path.join(
            WD_PLOT_DIR,
            f"{dataset}_wasserstein.png"
        ),
        dpi=300
    )

    plt.close()

print("Plots saved.")

In [ ]:
# ==============================================================================
# SAVE REPORTS
# ==============================================================================

WD_DIR = os.path.join(
    EVALUATION_DIR,
    "wasserstein"
)

os.makedirs(WD_DIR, exist_ok=True)

for dataset, report in WASSERSTEIN_RESULTS.items():

    report.to_csv(
        os.path.join(
            WD_DIR,
            f"{dataset}_wasserstein.csv"
        ),
        index=False
    )

WASSERSTEIN_SUMMARY_DF.to_csv(
    os.path.join(
        WD_DIR,
        "wasserstein_summary.csv"
    ),
    index=False
)

print("Wasserstein reports saved.")

In [ ]:
# ==============================================================================
# OVERALL SUMMARY
# ==============================================================================

print("=" * 100)
print("WASSERSTEIN SUMMARY")
print("=" * 100)

display(WASSERSTEIN_SUMMARY_DF)

print()

print(
    "Average Wasserstein Score :",
    round(
        WASSERSTEIN_SUMMARY_DF[
            "Wasserstein Score"
        ].mean(),
        2
    )
)

In [ ]:
# ==============================================================================
# STORE RESULTS
# ==============================================================================

FIDELITY_RESULTS["Wasserstein"] = (
    WASSERSTEIN_SUMMARY_DF.copy()
)

SUMMARY_RESULTS.append(
    WASSERSTEIN_SUMMARY_DF
)

print("Stored for final evaluation.")

In [ ]:
# ==============================================================================
# PART I5.3 VERIFICATION
# ==============================================================================

verification = {

    "Distance Results":
        len(WASSERSTEIN_RESULTS) == len(DATASETS),

    "Summary":
        len(WASSERSTEIN_SUMMARY_DF) == len(DATASETS),

    "Reports":
        os.path.exists(WD_DIR),

    "Plots":
        os.path.exists(WD_PLOT_DIR)

}

VERIFY_DF = pd.DataFrame({

    "Component":
        verification.keys(),

    "Status":
        verification.values()

})

VERIFY_DF["Result"] = VERIFY_DF["Status"].map(
    lambda x: "PASS" if x else "FAIL"
)

print("=" * 100)
print("PART I5.3 VERIFICATION")
print("=" * 100)

display(VERIFY_DF)

if VERIFY_DF["Status"].all():

    print("\n" + "=" * 100)
    print("✓ PART I5.3 COMPLETED SUCCESSFULLY")
    print("Ready for Part I5.4 — Jensen–Shannon Divergence")
    print("=" * 100)

else:

    display(
        VERIFY_DF[
            VERIFY_DF["Status"] == False
        ]
    )

    raise RuntimeError(
        "Part I5.3 verification failed."
    )

In [ ]:
# ==============================================================================
# PART I5.4.1 — JENSEN-SHANNON DIVERGENCE
# ==============================================================================

print("=" * 100)
print("PART I5.4 — JENSEN-SHANNON DIVERGENCE")
print("=" * 100)

JSD_RESULTS = {}
JSD_SUMMARY = []

for dataset in DATASETS:

    print(f"\nProcessing : {dataset}")

    real = REAL_DATASETS[dataset]
    synthetic = SYNTHETIC_DATASETS[dataset]

    rows = []

    for feature in NUMERIC_COLUMNS[dataset]:

        real_values, synthetic_values = prepare_numeric(
            real[feature],
            synthetic[feature]
        )

        if len(real_values) < 2 or len(synthetic_values) < 2:

            jsd = np.nan

        else:

            try:

                jsd = calculate_jsd(
                    real_values,
                    synthetic_values,
                    bins=30
                )

            except Exception:

                jsd = np.nan

        rows.append({

            "Feature": feature,

            "JSD": round(jsd,6)
            if pd.notna(jsd)
            else np.nan

        })

    result = pd.DataFrame(rows)

    JSD_RESULTS[dataset] = result

    display(result.head())

In [ ]:
# ==============================================================================
# DATASET SUMMARY
# ==============================================================================

for dataset, report in JSD_RESULTS.items():

    avg_jsd = report["JSD"].mean()

    min_jsd = report["JSD"].min()

    max_jsd = report["JSD"].max()

    JSD_SUMMARY.append({

        "Dataset": dataset,

        "Features": len(report),

        "Average JSD":
            round(avg_jsd,6),

        "Minimum JSD":
            round(min_jsd,6),

        "Maximum JSD":
            round(max_jsd,6)

    })

JSD_SUMMARY_DF = pd.DataFrame(JSD_SUMMARY)

display(JSD_SUMMARY_DF)

In [ ]:
# ==============================================================================
# JSD SCORE
# ==============================================================================

JSD_SUMMARY_DF["JSD Score"] = (

    1 -

    JSD_SUMMARY_DF["Average JSD"]

) * 100

JSD_SUMMARY_DF["JSD Score"] = (
    JSD_SUMMARY_DF["JSD Score"]
    .clip(lower=0)
    .round(2)
)

display(JSD_SUMMARY_DF)

In [ ]:
# ==============================================================================
# FEATURE JSD PLOTS
# ==============================================================================

JSD_PLOT_DIR = os.path.join(
    EVALUATION_DIR,
    "jsd_plots"
)

os.makedirs(JSD_PLOT_DIR, exist_ok=True)

for dataset, report in JSD_RESULTS.items():

    plt.figure(figsize=(12,5))

    plt.bar(
        report["Feature"],
        report["JSD"]
    )

    plt.xticks(rotation=90)

    plt.ylabel("JSD")

    plt.title(
        f"{dataset} Jensen-Shannon Divergence"
    )

    plt.tight_layout()

    plt.savefig(
        os.path.join(
            JSD_PLOT_DIR,
            f"{dataset}_jsd.png"
        ),
        dpi=300
    )

    plt.close()

print("JSD plots saved.")

In [ ]:
# ==============================================================================
# SAVE REPORTS
# ==============================================================================

JSD_DIR = os.path.join(
    EVALUATION_DIR,
    "jsd"
)

os.makedirs(JSD_DIR, exist_ok=True)

for dataset, report in JSD_RESULTS.items():

    report.to_csv(

        os.path.join(

            JSD_DIR,

            f"{dataset}_jsd.csv"

        ),

        index=False

    )

JSD_SUMMARY_DF.to_csv(

    os.path.join(

        JSD_DIR,

        "jsd_summary.csv"

    ),

    index=False

)

print("JSD reports saved.")

In [ ]:
# ==============================================================================
# OVERALL SUMMARY
# ==============================================================================

print("="*100)
print("JENSEN-SHANNON DIVERGENCE SUMMARY")
print("="*100)

display(JSD_SUMMARY_DF)

print()

print(

    "Average JSD Score :",

    round(

        JSD_SUMMARY_DF["JSD Score"].mean(),

        2

    )

)

In [ ]:
# ==============================================================================
# STORE RESULTS
# ==============================================================================

FIDELITY_RESULTS["JSD"] = (
    JSD_SUMMARY_DF.copy()
)

SUMMARY_RESULTS.append(
    JSD_SUMMARY_DF
)

print("JSD results stored.")

In [ ]:
# ==============================================================================
# PART I5.4 VERIFICATION
# ==============================================================================

verification = {

    "JSD Results":
        len(JSD_RESULTS) == len(DATASETS),

    "Summary":
        len(JSD_SUMMARY_DF) == len(DATASETS),

    "Reports":
        os.path.exists(JSD_DIR),

    "Plots":
        os.path.exists(JSD_PLOT_DIR)

}

VERIFY_DF = pd.DataFrame({

    "Component":
        verification.keys(),

    "Status":
        verification.values()

})

VERIFY_DF["Result"] = VERIFY_DF["Status"].map(
    lambda x: "PASS" if x else "FAIL"
)

print("="*100)
print("PART I5.4 VERIFICATION")
print("="*100)

display(VERIFY_DF)

if VERIFY_DF["Status"].all():

    print("\n" + "="*100)
    print("✓ PART I5.4 COMPLETED SUCCESSFULLY")
    print("Ready for Part I5.5 — Distribution Comparison Plots")
    print("="*100)

else:

    display(
        VERIFY_DF[
            VERIFY_DF["Status"] == False
        ]
    )

    raise RuntimeError(
        "Part I5.4 verification failed."
    )