<a href="https://colab.research.google.com/github/amzad-786githumb/Privacy-Preserving-Synthetic-Tabular-Data-Generation-Using-Generative-Adversarial-Networks/blob/main/05_Proposed_SPP_GAN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# ================================================================
# NOTEBOOK 05
# Deep Learning Synthetic Data Generation – TVAE
# =================================================================

NOTEBOOK_INFO = """
Research Title
--------------
SPP-GAN: A Privacy-Preserving Statistical–Machine Learning Framework for
High-Fidelity Synthetic Tabular Data Generation

Researcher
----------
Mohd Amzad

Notebook
--------
Notebook 05 – Deep Learning Synthetic Data Generation (TVAE)

Purpose
-------
This notebook implements the Tabular Variational Autoencoder (TVAE) for
synthetic tabular data generation using the preprocessed datasets produced in
Notebook 02. The trained models are used to generate high-quality synthetic
datasets that will be evaluated in subsequent notebooks for statistical
fidelity, data utility, privacy preservation, and downstream machine learning
performance.

Model Implemented
-----------------
• Tabular Variational Autoencoder (TVAE)

Inputs
------
Notebook 02
• Preprocessed datasets
• Dataset metadata
• Train, validation, and test splits

Notebook 03
• Statistical synthetic data generation outputs
• Standardized evaluation methodology

Outputs
-------
• Trained TVAE models
• Synthetic datasets
• Model checkpoints
• Training history
• Generated visualizations
• Dataset metadata
• Intermediate artifacts for downstream evaluation

Workflow
--------
A. Notebook Overview
B. Environment Setup
C. Project Configuration
D. Dataset Validation
E. Load Processed Datasets
F. Metadata Preparation
G. TVAE Model Configuration
H. TVAE Training
I. Synthetic Data Generation
J. Model Validation
K. Save Models and Synthetic Datasets
L. Final Verification

Version
-------
1.0
"""

In [27]:
# ==============================================================================
# PART A1 — NOTEBOOK OBJECTIVES
# ==============================================================================

NOTEBOOK_OBJECTIVES = [
    "Load processed datasets and project configuration.",
    "Detect and validate dataset metadata.",
    "Configure and train TVAE models.",
    "Generate synthetic datasets using trained TVAE models.",
    "Save trained TVAE models and generated synthetic datasets.",
    "Verify all outputs for downstream evaluation."
]

print("=" * 80)
print("NOTEBOOK OBJECTIVES")
print("=" * 80)

for i, objective in enumerate(NOTEBOOK_OBJECTIVES, start=1):
    print(f"{i}. {objective}")

================================================================================
NOTEBOOK OBJECTIVES
================================================================================
1. Load processed datasets and project configuration.
2. Detect and validate dataset metadata.
3. Configure and train TVAE models.
4. Generate synthetic datasets using trained TVAE models.
5. Save trained TVAE models and generated synthetic datasets.
6. Verify all outputs for downstream evaluation.

In [28]:
# ==============================================================================
# PART B1 - INSTALL REQUIRED PACKAGES
# ==============================================================================

!pip -q install -U sdv
!pip -q install -U torch
!pip -q install -U tqdm
!pip -q install -U joblib
!pip -q install -U pyyaml

print("✓ Required packages installed successfully.")

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 526.6/526.6 MB 3.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 366.2/366.2 MB 3.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 170.1/170.1 MB 6.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 206.0/206.0 MB 3.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 60.4/60.4 MB 6.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 197.7/197.7 MB 4.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 423.1/423.1 MB 1.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.7/10.7 MB 102.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 90.2/90.2 MB 8.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.2/2.2 MB 68.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 214.1/214.1 MB 3.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.2/1.2 MB 57.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 59.5/59.5 MB 19.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 200.9/200.9 MB 3.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 145.9/145.9 MB 6.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 148.0/148.0 kB 10.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.7/6.7 MB 85.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.0/1.0 MB 49.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 54.6/54.6 kB 4.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 40.7/40.7 MB 15.5 MB/s eta 0:00:00
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
ipython 7.34.0 requires jedi>=0.16, which is not installed.
torchvision 0.26.0+cpu requires torch==2.11.0, but you have torch 2.13.0 which is incompatible.
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 57.3/57.3 kB 2.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 80.2/80.2 kB 4.2 MB/s eta 0:00:00
✓ Required packages installed successfully.

In [29]:
# ==============================================================================
# PART B2 - ENVIRONMENT & PROJECT CONFIGURATION
# ==============================================================================

from google.colab import drive
import os

# ------------------------------------------------------------------------------
# Mount Google Drive
# ------------------------------------------------------------------------------

drive.mount("/content/drive", force_remount=False)

# ------------------------------------------------------------------------------
# Project Configuration
# ------------------------------------------------------------------------------

PROJECT_NAME = "SPP_GAN_Project"
ROOT_DIR = os.path.join("/content/drive/MyDrive", PROJECT_NAME)

if not os.path.isdir(ROOT_DIR):
    raise FileNotFoundError(
        f"Project directory not found:\n{ROOT_DIR}"
    )

# ------------------------------------------------------------------------------
# Project Directories
# ------------------------------------------------------------------------------

DATASET_DIR = os.path.join(ROOT_DIR, "datasets")
PROCESSED_DATASET_DIR = os.path.join(DATASET_DIR, "processed")
SPLIT_DATASET_DIR = os.path.join(DATASET_DIR, "splits")
SYNTHETIC_DATASET_DIR = os.path.join(DATASET_DIR, "synthetic", "TVAE")

MODEL_DIR = os.path.join(ROOT_DIR, "models", "TVAE")
METADATA_DIR = os.path.join(ROOT_DIR, "metadata")
CHECKPOINT_DIR = os.path.join(ROOT_DIR, "checkpoints", "TVAE")
HISTORY_DIR = os.path.join(ROOT_DIR, "histories", "TVAE")

REPORT_DIR = os.path.join(ROOT_DIR, "reports", "TVAE")
RESULT_DIR = os.path.join(ROOT_DIR, "results", "TVAE")

# ------------------------------------------------------------------------------
# Create Output Directories
# ------------------------------------------------------------------------------

OUTPUT_DIRECTORIES = [
    MODEL_DIR,
    SYNTHETIC_DATASET_DIR,
    CHECKPOINT_DIR,
    HISTORY_DIR,
    REPORT_DIR,
    RESULT_DIR
]

for directory in OUTPUT_DIRECTORIES:
    os.makedirs(directory, exist_ok=True)

# ------------------------------------------------------------------------------
# Verify Required Directories
# ------------------------------------------------------------------------------

REQUIRED_DIRECTORIES = [
    ROOT_DIR,
    DATASET_DIR,
    PROCESSED_DATASET_DIR,
    SPLIT_DATASET_DIR,
    METADATA_DIR
]

missing_directories = [
    directory
    for directory in REQUIRED_DIRECTORIES
    if not os.path.isdir(directory)
]

if missing_directories:
    raise FileNotFoundError(
        "The following required directories are missing:\n"
        + "\n".join(missing_directories)
    )

print("✓ Google Drive mounted successfully.")
print("✓ Project configuration loaded successfully.")

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
✓ Google Drive mounted successfully.
✓ Project configuration loaded successfully.

In [30]:
# ==============================================================================
# PART B3 - IMPORT LIBRARIES
# ==============================================================================

# ------------------------------------------------------------------------------
# Standard Libraries
# ------------------------------------------------------------------------------

import json
import random
import yaml
import warnings

# ------------------------------------------------------------------------------
# Numerical Computing
# ------------------------------------------------------------------------------

import numpy as np
import pandas as pd

# ------------------------------------------------------------------------------
# Visualization
# ------------------------------------------------------------------------------

import matplotlib.pyplot as plt

# ------------------------------------------------------------------------------
# PyTorch
# ------------------------------------------------------------------------------

import torch

# ------------------------------------------------------------------------------
# SDV
# ------------------------------------------------------------------------------

from sdv.metadata import SingleTableMetadata
from sdv.single_table import TVAESynthesizer

# ------------------------------------------------------------------------------
# Utilities
# ------------------------------------------------------------------------------

from tqdm.auto import tqdm

# ------------------------------------------------------------------------------
# Settings
# ------------------------------------------------------------------------------

warnings.filterwarnings("ignore")

print(
    f"Environment Ready | "
    f"PyTorch {torch.__version__} | "
    f"NumPy {np.__version__} | "
    f"Pandas {pd.__version__}"
)

Environment Ready | PyTorch 2.11.0+cpu | NumPy 2.0.2 | Pandas 2.2.2

In [31]:
# ==============================================================================
# PART B4 - LOAD PROJECT CONFIGURATION
# ==============================================================================

# ------------------------------------------------------------------------------
# Configuration Files
# ------------------------------------------------------------------------------

CONFIG_DIR = os.path.join(ROOT_DIR, "configs")

CONFIG_FILE = os.path.join(CONFIG_DIR, "config.yaml")
ENVIRONMENT_FILE = os.path.join(CONFIG_DIR, "environment.json")

# ------------------------------------------------------------------------------
# Verify Configuration Files
# ------------------------------------------------------------------------------

for file_path in [CONFIG_FILE, ENVIRONMENT_FILE]:

    if not os.path.isfile(file_path):

        raise FileNotFoundError(
            f"Missing configuration file:\n{file_path}"
        )

# ------------------------------------------------------------------------------
# Load Configuration Files
# ------------------------------------------------------------------------------

with open(CONFIG_FILE, "r") as file:
    CONFIG = yaml.safe_load(file)

with open(ENVIRONMENT_FILE, "r") as file:
    ENVIRONMENT = json.load(file)

# ------------------------------------------------------------------------------
# Verify Required Configuration Sections
# ------------------------------------------------------------------------------

REQUIRED_SECTIONS = {
    "project",
    "datasets",
    "models",
    "training",
    "privacy",
    "experiment"
}

missing_sections = REQUIRED_SECTIONS - set(CONFIG.keys())

if missing_sections:

    raise KeyError(
        "Missing configuration sections:\n"
        + "\n".join(sorted(missing_sections))
    )

# ------------------------------------------------------------------------------
# Frequently Used Configuration Objects
# ------------------------------------------------------------------------------

PROJECT_CONFIG = CONFIG["project"]
DATASET_CONFIG = CONFIG["datasets"]
MODEL_CONFIG = CONFIG["models"]
TRAINING_CONFIG = CONFIG["training"]
PRIVACY_CONFIG = CONFIG["privacy"]
EXPERIMENT_CONFIG = CONFIG["experiment"]

print(
    f"✓ Configuration loaded successfully | "
    f"{PROJECT_CONFIG['project_name']} | "
    f"{len(DATASET_CONFIG)} datasets | "
    f"{len(MODEL_CONFIG)} models"
)

✓ Configuration loaded successfully | SPP_GAN_Project | 3 datasets | 5 models

In [32]:
# ==============================================================================
# PART B5 - PROJECT PATHS
# ==============================================================================

# ------------------------------------------------------------------------------
# Load Project Paths
# ------------------------------------------------------------------------------

PATHS = CONFIG["paths"]

PROJECT_ROOT = PATHS["root"]

# Configuration
CONFIG_DIR = PATHS["configs"]

# Datasets
DATASET_DIR = PATHS["datasets"]
RAW_DATA_DIR = PATHS["raw_data"]
PROCESSED_DATA_DIR = PATHS["processed_data"]
SYNTHETIC_DATA_DIR = PATHS["synthetic_data"]

# Metadata
METADATA_DIR = PATHS["metadata"]

# TVAE Model
MODEL_DIR = PATHS["models"]
TVAE_MODEL_DIR = PATHS["tvae_models"]

# Results
RESULT_DIR = PATHS["results"]
TRAINING_RESULT_DIR = PATHS["training_results"]
TRAINING_HISTORY_DIR = PATHS["training_history"]
TRAINING_LOG_DIR = PATHS["training_logs"]
TRAINING_LOSS_DIR = PATHS["training_losses"]
TRAINING_PLOT_DIR = PATHS["training_plots"]

# Reports
REPORT_DIR = PATHS["reports"]

# Checkpoints
CHECKPOINT_DIR = PATHS["checkpoints"]

# ------------------------------------------------------------------------------
# Create Required Directories
# ------------------------------------------------------------------------------

DIRECTORIES = [

    TVAE_MODEL_DIR,

    SYNTHETIC_DATA_DIR,

    CHECKPOINT_DIR,

    REPORT_DIR,

    RESULT_DIR,

    TRAINING_RESULT_DIR,

    TRAINING_HISTORY_DIR,

    TRAINING_LOG_DIR,

    TRAINING_LOSS_DIR,

    TRAINING_PLOT_DIR

]

for directory in DIRECTORIES:
    os.makedirs(directory, exist_ok=True)

# ------------------------------------------------------------------------------
# Verify Project Structure
# ------------------------------------------------------------------------------

print("=" * 100)
print("PROJECT PATHS")
print("=" * 100)

verification = {}

for directory in DIRECTORIES:

    status = os.path.isdir(directory)

    verification[directory] = status

    print(f"{directory:<70} {'PASS' if status else 'FAIL'}")

print("\n" + "=" * 100)

passed = sum(verification.values())
total = len(verification)

print(f"Directories Verified : {passed}/{total}")

if passed == total:

    print("✓ Project structure verified successfully.")

else:

    raise RuntimeError("Directory verification failed.")

====================================================================================================
PROJECT PATHS
====================================================================================================
/content/drive/MyDrive/SPP_GAN_Project/models/tvae                     PASS
/content/drive/MyDrive/SPP_GAN_Project/datasets/synthetic              PASS
/content/drive/MyDrive/SPP_GAN_Project/checkpoints                     PASS
/content/drive/MyDrive/SPP_GAN_Project/reports                         PASS
/content/drive/MyDrive/SPP_GAN_Project/results                         PASS
/content/drive/MyDrive/SPP_GAN_Project/results/training                PASS
/content/drive/MyDrive/SPP_GAN_Project/results/training/history        PASS
/content/drive/MyDrive/SPP_GAN_Project/results/training/logs           PASS
/content/drive/MyDrive/SPP_GAN_Project/results/training/losses         PASS
/content/drive/MyDrive/SPP_GAN_Project/results/training/plots          PASS

====================================================================================================
Directories Verified : 10/10
✓ Project structure verified successfully.

In [33]:
# ==============================================================================
# PART B6 - REPRODUCIBILITY CONFIGURATION
# ==============================================================================

# ------------------------------------------------------------------------------
# Load Reproducibility Settings
# ------------------------------------------------------------------------------

REPRO_CONFIG = CONFIG["reproducibility"]

SEED = REPRO_CONFIG["seed"]

# ------------------------------------------------------------------------------
# Set Random Seeds
# ------------------------------------------------------------------------------

random.seed(SEED)
np.random.seed(SEED)
torch.manual_seed(SEED)

if torch.cuda.is_available():

    torch.cuda.manual_seed(SEED)
    torch.cuda.manual_seed_all(SEED)

# ------------------------------------------------------------------------------
# Configure cuDNN
# ------------------------------------------------------------------------------

torch.backends.cudnn.deterministic = REPRO_CONFIG.get(
    "deterministic",
    True
)

torch.backends.cudnn.benchmark = REPRO_CONFIG.get(
    "benchmark",
    False
)

# ------------------------------------------------------------------------------
# Environment Summary
# ------------------------------------------------------------------------------

DEVICE = torch.device(
    "cuda" if torch.cuda.is_available() else "cpu"
)

print(
    f"✓ Reproducibility configured | "
    f"Seed={SEED} | "
    f"Device={DEVICE}"
)

✓ Reproducibility configured | Seed=42 | Device=cpu

In [35]:
# ==============================================================================
# PART B7 - HARDWARE DETECTION
# ==============================================================================

import platform

# ------------------------------------------------------------------------------
# Detect Hardware
# ------------------------------------------------------------------------------

GPU_AVAILABLE = torch.cuda.is_available()

if GPU_AVAILABLE:

    GPU_NAME = torch.cuda.get_device_name(0)

    GPU_COUNT = torch.cuda.device_count()

    CUDA_VERSION = torch.version.cuda

    GPU_MEMORY_GB = round(
        torch.cuda.get_device_properties(0).total_memory / (1024 ** 3),
        2
    )

else:

    GPU_NAME = "CPU"

    GPU_COUNT = 0

    CUDA_VERSION = "N/A"

    GPU_MEMORY_GB = "N/A"

CPU_NAME = platform.processor()

PYTHON_VERSION = platform.python_version()

PYTORCH_VERSION = torch.__version__

OPERATING_SYSTEM = platform.system()

OS_VERSION = platform.release()

ARCHITECTURE = platform.machine()

# ------------------------------------------------------------------------------
# Display Hardware Configuration
# ------------------------------------------------------------------------------

print("=" * 100)
print("PART B7 - HARDWARE CONFIGURATION")
print("=" * 100)

print(f"Operating System     : {OPERATING_SYSTEM}")
print(f"OS Version           : {OS_VERSION}")
print(f"Architecture         : {ARCHITECTURE}")
print(f"Processor            : {CPU_NAME}")

print("-" * 100)

print(f"Python Version       : {PYTHON_VERSION}")
print(f"PyTorch Version      : {PYTORCH_VERSION}")

print("-" * 100)

print(f"Execution Device     : {DEVICE}")
print(f"GPU Available        : {GPU_AVAILABLE}")
print(f"GPU Name             : {GPU_NAME}")
print(f"GPU Count            : {GPU_COUNT}")
print(f"CUDA Version         : {CUDA_VERSION}")
print(f"GPU Memory (GB)      : {GPU_MEMORY_GB}")

print("=" * 100)
print("✓ Hardware detection completed successfully.")

====================================================================================================
PART B7 - HARDWARE CONFIGURATION
====================================================================================================
Operating System     : Linux
OS Version           : 6.6.122+
Architecture         : x86_64
Processor            : x86_64
----------------------------------------------------------------------------------------------------
Python Version       : 3.12.13
PyTorch Version      : 2.11.0+cpu
----------------------------------------------------------------------------------------------------
Execution Device     : cpu
GPU Available        : False
GPU Name             : CPU
GPU Count            : 0
CUDA Version         : N/A
GPU Memory (GB)      : N/A
====================================================================================================
✓ Hardware detection completed successfully.

In [38]:
# ==============================================================================
# PART B8 - TVAE CONFIGURATION
# ==============================================================================

# ------------------------------------------------------------------------------
# Training Parameters
# ------------------------------------------------------------------------------

EPOCHS = TRAINING_CONFIG["epochs"]
BATCH_SIZE = TRAINING_CONFIG["batch_size"]
LEARNING_RATE = TRAINING_CONFIG["learning_rate"]

# ------------------------------------------------------------------------------
# TVAE Hyperparameters
# ------------------------------------------------------------------------------

EMBEDDING_DIM = 128
COMPRESS_DIMS = (128, 128)
DECOMPRESS_DIMS = (128, 128)
LOSS_FACTOR = 2

print("=" * 100)
print("PART B8 - TVAE CONFIGURATION")
print("=" * 100)

print(f"Epochs            : {EPOCHS}")
print(f"Batch Size        : {BATCH_SIZE}")
print(f"Learning Rate     : {LEARNING_RATE}")
print(f"Embedding Dim     : {EMBEDDING_DIM}")
print(f"Compress Dims     : {COMPRESS_DIMS}")
print(f"Decompress Dims   : {DECOMPRESS_DIMS}")
print(f"Loss Factor       : {LOSS_FACTOR}")

print("=" * 100)
print("✓ TVAE configuration loaded successfully.")

====================================================================================================
PART B8 - TVAE CONFIGURATION
====================================================================================================
Epochs            : 100
Batch Size        : 256
Learning Rate     : 0.0002
Embedding Dim     : 128
Compress Dims     : (128, 128)
Decompress Dims   : (128, 128)
Loss Factor       : 2
====================================================================================================
✓ TVAE configuration loaded successfully.

In [39]:
# ==============================================================================
# PART C1 - VERIFY PROCESSED DATASETS
# ==============================================================================

DATASET_RESULTS = []

for dataset_name, dataset_info in CONFIG["datasets"].items():

    dataset_file = dataset_info["processed_file"]

    if not os.path.isfile(dataset_file):

        raise FileNotFoundError(
            f"Processed dataset not found:\n{dataset_file}"
        )

    df = pd.read_csv(dataset_file)

    DATASET_RESULTS.append({

        "Dataset": dataset_name,

        "File": os.path.basename(dataset_file),

        "Rows": df.shape[0],

        "Columns": df.shape[1],

        "Status": "PASS" if not df.empty else "FAIL"

    })

DATASET_DF = pd.DataFrame(DATASET_RESULTS)

print("=" * 100)
print("PART C1 - PROCESSED DATASET VERIFICATION")
print("=" * 100)

display(DATASET_DF)

if (DATASET_DF["Status"] == "PASS").all():

    print(f"\n✓ Verified {len(DATASET_DF)} processed datasets successfully.")

else:

    raise RuntimeError(
        "One or more processed datasets failed verification."
    )

====================================================================================================
PART C1 - PROCESSED DATASET VERIFICATION
====================================================================================================

          Dataset                          File    Rows  Columns Status
0    adult_income    adult_income_processed.csv   32515       15   PASS
1  bank_marketing  bank_marketing_processed.csv   45211       17   PASS
2  diabetes_130us  diabetes_130us_processed.csv  101766       48   PASS

✓ Verified 3 processed datasets successfully.

In [40]:
# ==============================================================================
# PART C2 - VERIFY DATASET SPLITS
# ==============================================================================

SPLITS = ("train", "validation", "test")

SPLIT_RESULTS = []

for dataset_name in CONFIG["datasets"]:

    for split in SPLITS:

        file_path = os.path.join(
            SPLIT_DATASET_DIR,
            dataset_name,
            f"{split}.csv"
        )

        if not os.path.isfile(file_path):

            raise FileNotFoundError(
                f"Missing split file:\n{file_path}"
            )

        df = pd.read_csv(file_path)

        SPLIT_RESULTS.append({

            "Dataset": dataset_name,

            "Split": split,

            "Rows": df.shape[0],

            "Columns": df.shape[1],

            "Status": "PASS" if not df.empty else "FAIL"

        })

SPLIT_DF = pd.DataFrame(SPLIT_RESULTS)

print("=" * 100)
print("PART C2 - DATASET SPLIT VERIFICATION")
print("=" * 100)

display(SPLIT_DF)

if (SPLIT_DF["Status"] == "PASS").all():

    print(
        f"\n✓ Verified {len(SPLIT_DF)} dataset splits successfully."
    )

else:

    raise RuntimeError(
        "One or more dataset splits failed verification."
    )

====================================================================================================
PART C2 - DATASET SPLIT VERIFICATION
====================================================================================================

          Dataset       Split   Rows  Columns Status
0    adult_income       train  22756       15   PASS
1    adult_income  validation   4877       15   PASS
2    adult_income        test   4877       15   PASS
3  bank_marketing       train  31647       17   PASS
4  bank_marketing  validation   6782       17   PASS
5  bank_marketing        test   6782       17   PASS
6  diabetes_130us       train  71236       48   PASS
7  diabetes_130us  validation  15265       48   PASS
8  diabetes_130us        test  15265       48   PASS

✓ Verified 9 dataset splits successfully.

In [41]:
# ==============================================================================
# PART C3 - VERIFY METADATA FILES
# ==============================================================================

METADATA_RESULTS = []

for dataset_name, dataset_info in CONFIG["datasets"].items():

    metadata_file = dataset_info["metadata_file"]

    if not os.path.isfile(metadata_file):

        raise FileNotFoundError(
            f"Metadata file not found:\n{metadata_file}"
        )

    try:

        with open(metadata_file, "r") as file:
            json.load(file)

        status = "PASS"

    except json.JSONDecodeError:

        status = "FAIL"

    METADATA_RESULTS.append({

        "Dataset": dataset_name,

        "Metadata File": os.path.basename(metadata_file),

        "Status": status

    })

METADATA_DF = pd.DataFrame(METADATA_RESULTS)

print("=" * 100)
print("PART C3 - METADATA VERIFICATION")
print("=" * 100)

display(METADATA_DF)

if (METADATA_DF["Status"] == "PASS").all():

    print(f"\n✓ Verified {len(METADATA_DF)} metadata files successfully.")

else:

    raise RuntimeError(
        "One or more metadata files are invalid."
    )

====================================================================================================
PART C3 - METADATA VERIFICATION
====================================================================================================

          Dataset                 Metadata File Status
0    adult_income    adult_income_metadata.json   PASS
1  bank_marketing  bank_marketing_metadata.json   PASS
2  diabetes_130us  diabetes_130us_metadata.json   PASS

✓ Verified 3 metadata files successfully.

In [42]:
# ==============================================================================
# PART D1 - LOAD PROCESSED DATASETS
# ==============================================================================

PROCESSED_DATASETS = {}
DATASET_SUMMARY = []

for dataset_name, dataset_info in CONFIG["datasets"].items():

    file_path = dataset_info["processed_file"]

    if not os.path.isfile(file_path):

        raise FileNotFoundError(
            f"Processed dataset not found:\n{file_path}"
        )

    df = pd.read_csv(file_path)

    PROCESSED_DATASETS[dataset_name] = df

    DATASET_SUMMARY.append({

        "Dataset": dataset_name,

        "Rows": df.shape[0],

        "Columns": df.shape[1],

        "Target": dataset_info["target"],

        "Missing Values": int(df.isna().sum().sum()),

        "Duplicate Rows": int(df.duplicated().sum())

    })

DATASET_SUMMARY_DF = pd.DataFrame(DATASET_SUMMARY)

print("=" * 100)
print("PART D1 - PROCESSED DATASETS LOADED")
print("=" * 100)

display(DATASET_SUMMARY_DF)

print(f"\n✓ Loaded {len(PROCESSED_DATASETS)} processed datasets successfully.")

====================================================================================================
PART D1 - PROCESSED DATASETS LOADED
====================================================================================================

          Dataset    Rows  Columns      Target  Missing Values  Duplicate Rows
0    adult_income   32515       15      income               0               0
1  bank_marketing   45211       17           y               0               0
2  diabetes_130us  101766       48  readmitted               0               0

✓ Loaded 3 processed datasets successfully.

In [43]:
# ==============================================================================
# PART D2 - LOAD DATASET SPLITS
# ==============================================================================

print("=" * 100)
print("PART D2 - LOADING TRAIN / VALIDATION / TEST SPLITS")
print("=" * 100)

TRAIN_SPLITS = {}
VALIDATION_SPLITS = {}
TEST_SPLITS = {}

SPLIT_SUMMARY = []

for dataset_name in CONFIG["datasets"]:

    dataset_folder = os.path.join(
        SPLIT_DATASET_DIR,
        dataset_name
    )

    train_file = os.path.join(dataset_folder, "train.csv")
    validation_file = os.path.join(dataset_folder, "validation.csv")
    test_file = os.path.join(dataset_folder, "test.csv")

    required_files = {
        "Train": train_file,
        "Validation": validation_file,
        "Test": test_file
    }

    for split_name, file_path in required_files.items():

        if not os.path.isfile(file_path):

            raise FileNotFoundError(
                f"{split_name} split not found:\n{file_path}"
            )

    train_df = pd.read_csv(train_file)
    validation_df = pd.read_csv(validation_file)
    test_df = pd.read_csv(test_file)

    # --------------------------------------------------------------------------
    # Align column order with processed dataset
    # --------------------------------------------------------------------------

    reference_columns = PROCESSED_DATASETS[dataset_name].columns.tolist()

    train_df = train_df[reference_columns]
    validation_df = validation_df[reference_columns]
    test_df = test_df[reference_columns]

    TRAIN_SPLITS[dataset_name] = train_df
    VALIDATION_SPLITS[dataset_name] = validation_df
    TEST_SPLITS[dataset_name] = test_df

    SPLIT_SUMMARY.append({

        "Dataset": dataset_name,

        "Train Rows": train_df.shape[0],

        "Validation Rows": validation_df.shape[0],

        "Test Rows": test_df.shape[0],

        "Columns": train_df.shape[1]

    })

SPLIT_SUMMARY_DF = pd.DataFrame(SPLIT_SUMMARY)

print("=" * 100)
print("PART D2 - DATASET SPLIT SUMMARY")
print("=" * 100)

display(SPLIT_SUMMARY_DF)

print("\n✓ All dataset splits loaded successfully.")
print("✓ Column ordering aligned with processed datasets.")

====================================================================================================
PART D2 - LOADING TRAIN / VALIDATION / TEST SPLITS
====================================================================================================
====================================================================================================
PART D2 - DATASET SPLIT SUMMARY
====================================================================================================

          Dataset  Train Rows  Validation Rows  Test Rows  Columns
0    adult_income       22756             4877       4877       15
1  bank_marketing       31647             6782       6782       17
2  diabetes_130us       71236            15265      15265       48

✓ All dataset splits loaded successfully.
✓ Column ordering aligned with processed datasets.

In [44]:
# ==============================================================================
# PART D3 - DATASET SUMMARY
# ==============================================================================

SUMMARY_RESULTS = []

for dataset_name, df in PROCESSED_DATASETS.items():

    target_column = CONFIG["datasets"][dataset_name]["target"]

    SUMMARY_RESULTS.append({

        "Dataset": dataset_name,

        "Rows": df.shape[0],

        "Columns": df.shape[1],

        "Target": target_column,

        "Numeric Features":
            df.select_dtypes(include=np.number).shape[1],

        "Categorical Features":
            df.select_dtypes(exclude=np.number).shape[1],

        "Missing Values":
            int(df.isna().sum().sum()),

        "Duplicate Rows":
            int(df.duplicated().sum())

    })

DATASET_PROFILE_DF = pd.DataFrame(SUMMARY_RESULTS)

print("=" * 100)
print("PART D3 - DATASET PROFILE")
print("=" * 100)

display(DATASET_PROFILE_DF)

print(
    f"\n✓ Dataset profile generated for "
    f"{len(DATASET_PROFILE_DF)} datasets."
)

====================================================================================================
PART D3 - DATASET PROFILE
====================================================================================================

          Dataset    Rows  Columns      Target  Numeric Features  Categorical Features  Missing Values  Duplicate Rows
0    adult_income   32515       15      income                15                     0               0               0
1  bank_marketing   45211       17           y                17                     0               0               0
2  diabetes_130us  101766       48  readmitted                48                     0               0               0

✓ Dataset profile generated for 3 datasets.

In [45]:
# ==============================================================================
# PART D4 - FEATURE INFORMATION
# ==============================================================================

NUMERIC_COLUMNS = {}
CATEGORICAL_COLUMNS = {}
TARGET_COLUMNS = {}

FEATURE_SUMMARY = []

for dataset_name, df in PROCESSED_DATASETS.items():

    target_column = CONFIG["datasets"][dataset_name]["target"]

    TARGET_COLUMNS[dataset_name] = target_column

    feature_df = df.drop(columns=[target_column])

    numeric_columns = (
        feature_df
        .select_dtypes(include=np.number)
        .columns
        .tolist()
    )

    categorical_columns = (
        feature_df
        .select_dtypes(exclude=np.number)
        .columns
        .tolist()
    )

    NUMERIC_COLUMNS[dataset_name] = numeric_columns
    CATEGORICAL_COLUMNS[dataset_name] = categorical_columns

    FEATURE_SUMMARY.append({

        "Dataset": dataset_name,

        "Total Features": feature_df.shape[1],

        "Numeric Features": len(numeric_columns),

        "Categorical Features": len(categorical_columns),

        "Target Column": target_column

    })

FEATURE_SUMMARY_DF = pd.DataFrame(FEATURE_SUMMARY)

print("=" * 100)
print("PART D4 - FEATURE INFORMATION")
print("=" * 100)

display(FEATURE_SUMMARY_DF)

print(
    f"\n✓ Feature information extracted for "
    f"{len(FEATURE_SUMMARY_DF)} datasets."
)

====================================================================================================
PART D4 - FEATURE INFORMATION
====================================================================================================

          Dataset  Total Features  Numeric Features  Categorical Features Target Column
0    adult_income              14                14                     0        income
1  bank_marketing              16                16                     0             y
2  diabetes_130us              47                47                     0    readmitted

✓ Feature information extracted for 3 datasets.

In [46]:
# ==============================================================================
# PART D5 - VALIDATE TARGET COLUMNS
# ==============================================================================

TARGET_VALIDATION = []

for dataset_name, dataset_info in CONFIG["datasets"].items():

    target_column = dataset_info["target"]

    exists = target_column in PROCESSED_DATASETS[dataset_name].columns

    TARGET_VALIDATION.append({

        "Dataset": dataset_name,

        "Target Column": target_column,

        "Status": "PASS" if exists else "FAIL"

    })

    if not exists:

        raise ValueError(
            f"{dataset_name}: Target column '{target_column}' not found."
        )

TARGET_VALIDATION_DF = pd.DataFrame(TARGET_VALIDATION)

print("=" * 100)
print("PART D5 - TARGET COLUMN VALIDATION")
print("=" * 100)

display(TARGET_VALIDATION_DF)

print(
    f"\n✓ Validated target columns for "
    f"{len(TARGET_VALIDATION_DF)} datasets."
)

====================================================================================================
PART D5 - TARGET COLUMN VALIDATION
====================================================================================================

          Dataset Target Column Status
0    adult_income        income   PASS
1  bank_marketing             y   PASS
2  diabetes_130us    readmitted   PASS

✓ Validated target columns for 3 datasets.

In [47]:
# ==============================================================================
# PART E1 - LOAD DATASET METADATA
# ==============================================================================

METADATA = {}
METADATA_SUMMARY = []

for dataset_name, dataset_info in CONFIG["datasets"].items():

    metadata_file = dataset_info["metadata_file"]

    if not os.path.isfile(metadata_file):

        raise FileNotFoundError(
            f"Metadata file not found:\n{metadata_file}"
        )

    with open(metadata_file, "r") as file:

        metadata = json.load(file)

    METADATA[dataset_name] = metadata

    METADATA_SUMMARY.append({

        "Dataset": dataset_name,

        "Metadata File": os.path.basename(metadata_file),

        "Metadata Loaded": True

    })

METADATA_DF = pd.DataFrame(METADATA_SUMMARY)

print("=" * 100)
print("PART E1 - DATASET METADATA LOADING")
print("=" * 100)

display(METADATA_DF)

print(
    f"\n✓ Loaded metadata for "
    f"{len(METADATA_DF)} datasets successfully."
)

====================================================================================================
PART E1 - DATASET METADATA LOADING
====================================================================================================

          Dataset                 Metadata File  Metadata Loaded
0    adult_income    adult_income_metadata.json             True
1  bank_marketing  bank_marketing_metadata.json             True
2  diabetes_130us  diabetes_130us_metadata.json             True

✓ Loaded metadata for 3 datasets successfully.

In [49]:
# ==============================================================================
# PART E2 - VALIDATE METADATA CONSISTENCY
# ==============================================================================

METADATA_VALIDATION = []

for dataset_name, df in PROCESSED_DATASETS.items():

    metadata = METADATA[dataset_name]

    dataset_columns = df.columns.tolist()

    if "features" not in metadata:

        raise KeyError(
            f"'features' not found in metadata for {dataset_name}"
        )

    metadata_columns = list(
        metadata["features"].keys()
    )

    columns_match = (
        dataset_columns == metadata_columns
    )

    METADATA_VALIDATION.append({

        "Dataset": dataset_name,

        "Dataset Columns": len(dataset_columns),

        "Metadata Columns": len(metadata_columns),

        "Columns Match": columns_match,

        "Status": "PASS" if columns_match else "FAIL"

    })


METADATA_VALIDATION_DF = pd.DataFrame(
    METADATA_VALIDATION
)

print("=" * 100)
print("PART E2 - METADATA CONSISTENCY VALIDATION")
print("=" * 100)

display(METADATA_VALIDATION_DF)


if not METADATA_VALIDATION_DF["Columns Match"].all():

    raise ValueError(
        "Dataset columns and metadata features are inconsistent."
    )


print("\n✓ Metadata consistency validation completed successfully.")

====================================================================================================
PART E2 - METADATA CONSISTENCY VALIDATION
====================================================================================================

          Dataset  Dataset Columns  Metadata Columns  Columns Match Status
0    adult_income               15                15           True   PASS
1  bank_marketing               17                17           True   PASS
2  diabetes_130us               48                48           True   PASS

✓ Metadata consistency validation completed successfully.

In [50]:
# ==============================================================================
# PART E3 - METADATA SUMMARY
# ==============================================================================

METADATA_SUMMARY = []

for dataset_name, metadata in METADATA.items():

    METADATA_SUMMARY.append({

        "Dataset": dataset_name,

        "Rows": metadata["rows"],

        "Columns": metadata["columns"],

        "Target Column": metadata["target_column"],

        "Total Features": len(metadata["features"])

    })


METADATA_SUMMARY_DF = pd.DataFrame(
    METADATA_SUMMARY
)

print("=" * 100)
print("PART E3 - METADATA SUMMARY")
print("=" * 100)

display(METADATA_SUMMARY_DF)

print(
    f"\n✓ Metadata summary generated for "
    f"{len(METADATA_SUMMARY_DF)} datasets."
)

====================================================================================================
PART E3 - METADATA SUMMARY
====================================================================================================

          Dataset    Rows  Columns Target Column  Total Features
0    adult_income   32510       15        income              15
1  bank_marketing   45211       17             y              17
2  diabetes_130us  101766       48    readmitted              48

✓ Metadata summary generated for 3 datasets.

In [51]:
# ==============================================================================
# PART E4 - METADATA PIPELINE VERIFICATION
# ==============================================================================

print("=" * 100)
print("PART E4 - METADATA PIPELINE VERIFICATION")
print("=" * 100)

verification = {

    "Metadata Loaded":
        len(METADATA) == len(CONFIG["datasets"]),

    "Metadata Consistency":
        METADATA_VALIDATION_DF["Columns Match"].all()

}


VERIFY_DF = pd.DataFrame({

    "Component": verification.keys(),

    "Status": verification.values()

})


VERIFY_DF["Result"] = VERIFY_DF["Status"].map(

    lambda x: "PASS" if x else "FAIL"

)


display(VERIFY_DF)


if not VERIFY_DF["Status"].all():

    display(
        VERIFY_DF[
            VERIFY_DF["Status"] == False
        ]
    )

    raise RuntimeError(
        "Metadata pipeline verification failed."
    )


print(
    "\n✓ PART E4 completed successfully."
)
print("✓ Metadata is ready for TVAE training.")

====================================================================================================
PART E4 - METADATA PIPELINE VERIFICATION
====================================================================================================

              Component  Status Result
0       Metadata Loaded    True   PASS
1  Metadata Consistency    True   PASS

✓ PART E4 completed successfully.
✓ Metadata is ready for TVAE training.

In [52]:
# ==============================================================================
# PART F1 - INITIALIZE TVAE TRAINING
# ==============================================================================

print("=" * 100)
print("TVAE BASELINE PREPARATION")
print("=" * 100)

TVAE_MODELS = {}

TVAE_HISTORY = {}

TVAE_SYNTHETIC_DATASETS = {}

print(f"Datasets Ready : {len(PROCESSED_DATASETS)}")

print(f"Metadata Ready : {len(METADATA)}")

print("✓ TVAE initialization completed.")

====================================================================================================
TVAE BASELINE PREPARATION
====================================================================================================
Datasets Ready : 3
Metadata Ready : 3
✓ TVAE initialization completed.

In [53]:
# ==============================================================================
# PART F2 - TVAE HYPERPARAMETERS
# ==============================================================================

TVAE_CONFIG = {

    "epochs":
        TRAINING_CONFIG["epochs"],

    "batch_size":
        TRAINING_CONFIG["batch_size"],

    "embedding_dim":
        128,

    "compress_dims":
        (128, 128),

    "decompress_dims":
        (128, 128),

    "loss_factor":
        2,

    "cuda":
        DEVICE.type == "cuda"

}


print("=" * 100)
print("TVAE HYPERPARAMETERS")
print("=" * 100)

display(
    pd.DataFrame(
        TVAE_CONFIG.items(),
        columns=["Parameter", "Value"]
    )
)

print("✓ TVAE hyperparameters configured.")

====================================================================================================
TVAE HYPERPARAMETERS
====================================================================================================

         Parameter       Value
0           epochs         100
1       batch_size         256
2    embedding_dim         128
3    compress_dims  (128, 128)
4  decompress_dims  (128, 128)
5      loss_factor           2
6             cuda       False

✓ TVAE hyperparameters configured.

In [54]:
# ==============================================================================
# PART F3 - CREATE SDV METADATA OBJECTS FOR TVAE
# ==============================================================================

from sdv.metadata import SingleTableMetadata

print("=" * 100)
print("CREATING SDV METADATA OBJECTS FOR TVAE")
print("=" * 100)

SDV_METADATA = {}

SDV_METADATA_SUMMARY = []

for dataset_name, df in PROCESSED_DATASETS.items():

    metadata = SingleTableMetadata()

    metadata.detect_from_dataframe(
        data=df
    )

    SDV_METADATA[dataset_name] = metadata

    SDV_METADATA_SUMMARY.append({

        "Dataset": dataset_name,

        "Rows": df.shape[0],

        "Columns": df.shape[1],

        "Metadata Status": "Created"

    })


SDV_METADATA_SUMMARY_DF = pd.DataFrame(
    SDV_METADATA_SUMMARY
)


display(SDV_METADATA_SUMMARY_DF)


print(
    "\n✓ SDV metadata objects created successfully for TVAE."
)

====================================================================================================
CREATING SDV METADATA OBJECTS FOR TVAE
====================================================================================================

          Dataset    Rows  Columns Metadata Status
0    adult_income   32515       15         Created
1  bank_marketing   45211       17         Created
2  diabetes_130us  101766       48         Created

✓ SDV metadata objects created successfully for TVAE.

In [55]:
# ==============================================================================
# PART F4 - PREPARE TVAE TRAINING DATA
# ==============================================================================

TVAE_TRAIN_DATA = {}

TVAE_DATASET_INFO = []

for dataset_name, train_df in TRAIN_SPLITS.items():

    df = train_df.copy()

    TVAE_TRAIN_DATA[dataset_name] = df

    TVAE_DATASET_INFO.append({

        "Dataset": dataset_name,

        "Training Rows": df.shape[0],

        "Training Columns": df.shape[1],

        "Data Ready": True

    })


TVAE_DATASET_INFO_DF = pd.DataFrame(
    TVAE_DATASET_INFO
)


print("=" * 100)
print("PART F4 - TVAE TRAINING DATA PREPARATION")
print("=" * 100)

display(TVAE_DATASET_INFO_DF)


print("\n✓ TVAE training datasets prepared successfully.")

====================================================================================================
PART F4 - TVAE TRAINING DATA PREPARATION
====================================================================================================

          Dataset  Training Rows  Training Columns  Data Ready
0    adult_income          22756                15        True
1  bank_marketing          31647                17        True
2  diabetes_130us          71236                48        True

✓ TVAE training datasets prepared successfully.

In [56]:
# ==============================================================================
# PART F5 - INITIALIZE TVAE MODELS
# ==============================================================================

print("=" * 100)
print("INITIALIZING TVAE MODELS")
print("=" * 100)


# ------------------------------------------------------------------------------
# Reset Containers
# ------------------------------------------------------------------------------

TVAE_MODELS = {}

TVAE_MODEL_SUMMARY = []


AVAILABLE_DATASETS = list(
    TVAE_TRAIN_DATA.keys()
)


# ------------------------------------------------------------------------------
# Initialize TVAE Models
# ------------------------------------------------------------------------------

for dataset_name in AVAILABLE_DATASETS:

    print(f"Creating TVAE model : {dataset_name}")


    synthesizer = TVAESynthesizer(

        metadata=SDV_METADATA[dataset_name],

        epochs=TVAE_CONFIG["epochs"],

        batch_size=TVAE_CONFIG["batch_size"],

        embedding_dim=TVAE_CONFIG["embedding_dim"],

        compress_dims=TVAE_CONFIG["compress_dims"],

        decompress_dims=TVAE_CONFIG["decompress_dims"],

        loss_factor=TVAE_CONFIG["loss_factor"],

        cuda=TVAE_CONFIG["cuda"]

    )


    TVAE_MODELS[dataset_name] = synthesizer


    parameters = synthesizer.get_parameters()


    TVAE_MODEL_SUMMARY.append({

        "Dataset": dataset_name,

        "Epochs": parameters["epochs"],

        "Batch Size": parameters["batch_size"],

        "Embedding Dim": parameters["embedding_dim"],

        "Compress Dims": parameters["compress_dims"],

        "Decompress Dims": parameters["decompress_dims"],

        "Status": "Initialized"

    })


# ------------------------------------------------------------------------------
# Summary
# ------------------------------------------------------------------------------

TVAE_MODEL_SUMMARY_DF = pd.DataFrame(
    TVAE_MODEL_SUMMARY
)


display(
    TVAE_MODEL_SUMMARY_DF
)


# ------------------------------------------------------------------------------
# Verification
# ------------------------------------------------------------------------------

print("\n" + "=" * 100)
print("TVAE MODEL VERIFICATION")
print("=" * 100)


for dataset_name, synthesizer in TVAE_MODELS.items():

    params = synthesizer.get_parameters()

    print(f"Dataset          : {dataset_name}")
    print(f"Epochs           : {params['epochs']}")
    print(f"Batch Size       : {params['batch_size']}")
    print(f"Embedding Dim    : {params['embedding_dim']}")
    print(f"Compress Dims    : {params['compress_dims']}")
    print(f"Decompress Dims  : {params['decompress_dims']}")
    print("-" * 100)


print("✓ TVAE models initialized successfully.")
print("✓ Ready for Part G - TVAE Training.")

====================================================================================================
INITIALIZING TVAE MODELS
====================================================================================================
Creating TVAE model : adult_income
Creating TVAE model : bank_marketing
Creating TVAE model : diabetes_130us

          Dataset  Epochs  Batch Size  Embedding Dim Compress Dims Decompress Dims       Status
0    adult_income     100         256            128    (128, 128)      (128, 128)  Initialized
1  bank_marketing     100         256            128    (128, 128)      (128, 128)  Initialized
2  diabetes_130us     100         256            128    (128, 128)      (128, 128)  Initialized

====================================================================================================
TVAE MODEL VERIFICATION
====================================================================================================
Dataset          : adult_income
Epochs           : 100
Batch Size       : 256
Embedding Dim    : 128
Compress Dims    : (128, 128)
Decompress Dims  : (128, 128)
----------------------------------------------------------------------------------------------------
Dataset          : bank_marketing
Epochs           : 100
Batch Size       : 256
Embedding Dim    : 128
Compress Dims    : (128, 128)
Decompress Dims  : (128, 128)
----------------------------------------------------------------------------------------------------
Dataset          : diabetes_130us
Epochs           : 100
Batch Size       : 256
Embedding Dim    : 128
Compress Dims    : (128, 128)
Decompress Dims  : (128, 128)
----------------------------------------------------------------------------------------------------
✓ TVAE models initialized successfully.
✓ Ready for Part G - TVAE Training.

In [57]:
# ==============================================================================
# PART F6 - TVAE MODEL INITIALIZATION VERIFICATION
# ==============================================================================

print("=" * 100)
print("TVAE INITIALIZATION VERIFICATION")
print("=" * 100)


assert len(TVAE_MODELS) == len(CONFIG["datasets"]), \
    "TVAE initialization failed."


assert len(SDV_METADATA) == len(CONFIG["datasets"]), \
    "SDV metadata objects missing."


assert len(TVAE_TRAIN_DATA) == len(CONFIG["datasets"]), \
    "TVAE training data preparation failed."


print("✓ TVAE models initialized successfully.")
print("✓ SDV metadata verified.")
print("✓ TVAE training data verified.")

print("\nReady for Part G - TVAE Training")

====================================================================================================
TVAE INITIALIZATION VERIFICATION
====================================================================================================
✓ TVAE models initialized successfully.
✓ SDV metadata verified.
✓ TVAE training data verified.

Ready for Part G - TVAE Training

In [58]:
# ==============================================================================
# PART G — TVAE TRAINING
# G1. Training Setup
# ==============================================================================

print("=" * 100)
print("PART G1 — TVAE TRAINING SETUP")
print("=" * 100)


import os
import json
import time
import random
from datetime import datetime

import numpy as np
import pandas as pd
import torch
import sdv


# ==============================================================================
# Reproducibility
# ==============================================================================

SEED = REPRO_CONFIG["seed"]

random.seed(SEED)

np.random.seed(SEED)

torch.manual_seed(SEED)

if torch.cuda.is_available():

    torch.cuda.manual_seed(SEED)

    torch.cuda.manual_seed_all(SEED)



# ==============================================================================
# Device Configuration
# ==============================================================================

if isinstance(DEVICE, torch.device):

    DEVICE_NAME = DEVICE.type

else:

    DEVICE_NAME = str(DEVICE).lower()


GPU_AVAILABLE = torch.cuda.is_available()



# ==============================================================================
# Available Datasets
# ==============================================================================

AVAILABLE_DATASETS = list(
    TVAE_TRAIN_DATA.keys()
)


print(f"Datasets Available : {len(AVAILABLE_DATASETS)}")


for dataset in AVAILABLE_DATASETS:

    print(f"   • {dataset}")



# ==============================================================================
# Output Directories
# ==============================================================================

TVAE_ROOT = os.path.join(
    PROJECT_ROOT,
    "models",
    "tvae"
)


TVAE_MODEL_DIR = os.path.join(
    TVAE_ROOT,
    "trained_models"
)


TVAE_LOG_DIR = os.path.join(
    TVAE_ROOT,
    "training_logs"
)


TVAE_REPORT_DIR = os.path.join(
    PROJECT_ROOT,
    "reports",
    "TVAE"
)


TVAE_SYNTHETIC_DIR = os.path.join(
    PROJECT_ROOT,
    "datasets",
    "synthetic",
    "TVAE"
)


DIRECTORIES = [

    TVAE_ROOT,

    TVAE_MODEL_DIR,

    TVAE_LOG_DIR,

    TVAE_REPORT_DIR,

    TVAE_SYNTHETIC_DIR

]


for directory in DIRECTORIES:

    os.makedirs(
        directory,
        exist_ok=True
    )


print("\n✓ TVAE output directories verified.")



# ==============================================================================
# Training Configuration
# ==============================================================================

TRAINING_CONFIGURATION = {

    "model": "TVAE",

    "datasets": AVAILABLE_DATASETS,

    "number_of_datasets": len(AVAILABLE_DATASETS),


    "epochs":
        TVAE_CONFIG["epochs"],


    "batch_size":
        TVAE_CONFIG["batch_size"],


    "embedding_dim":
        TVAE_CONFIG["embedding_dim"],


    "compress_dims":
        list(TVAE_CONFIG["compress_dims"]),


    "decompress_dims":
        list(TVAE_CONFIG["decompress_dims"]),


    "loss_factor":
        TVAE_CONFIG["loss_factor"],


    "device":
        DEVICE_NAME,


    "gpu_available":
        GPU_AVAILABLE,


    "random_seed":
        SEED,


    "sdv_version":
        sdv.__version__,


    "pytorch_version":
        torch.__version__,


    "model_directory":
        TVAE_MODEL_DIR,


    "log_directory":
        TVAE_LOG_DIR,


    "synthetic_directory":
        TVAE_SYNTHETIC_DIR,


    "report_directory":
        TVAE_REPORT_DIR,


    "started":
        datetime.now().strftime(
            "%Y-%m-%d %H:%M:%S"
        )

}


print("\nTraining Configuration")

print("-" * 100)


for key, value in TRAINING_CONFIGURATION.items():

    print(
        f"{key:<25}: {value}"
    )



# ==============================================================================
# Training Containers
# ==============================================================================

TVAE_HISTORY = {}

TVAE_TRAINING_SUMMARY = []

TVAE_MODEL_PATHS = {}

TVAE_TRAINING_LOGS = {}

TVAE_SYNTHETIC_DATASETS = {}

TVAE_TRAINING_TIMES = {}



# ==============================================================================
# Dataset Summary
# ==============================================================================

print("\n" + "=" * 100)

print("TVAE TRAINING DATA SUMMARY")

print("=" * 100)


SUMMARY = []


for dataset_name in AVAILABLE_DATASETS:

    df = TVAE_TRAIN_DATA[dataset_name]


    SUMMARY.append({

        "Dataset": dataset_name,

        "Rows": len(df),

        "Columns": df.shape[1],

        "Numeric Features":
            len(
                df.select_dtypes(
                    include=np.number
                ).columns
            ),

        "Categorical Features":
            len(
                df.select_dtypes(
                    exclude=np.number
                ).columns
            )

    })


DATASET_SUMMARY_DF = pd.DataFrame(
    SUMMARY
)


display(DATASET_SUMMARY_DF)



# ==============================================================================
# Training Timer
# ==============================================================================

NOTEBOOK_TRAINING_START = time.time()


print("\n✓ Training timer initialized.")



# ==============================================================================
# Save Training Configuration
# ==============================================================================

TRAINING_CONFIG_FILE = os.path.join(

    TVAE_LOG_DIR,

    "training_configuration.json"

)


with open(TRAINING_CONFIG_FILE, "w") as fp:

    json.dump(

        TRAINING_CONFIGURATION,

        fp,

        indent=4

    )


print("✓ Training configuration saved.")



# ==============================================================================
# Final Verification
# ==============================================================================

READY_FOR_TRAINING = (

    len(AVAILABLE_DATASETS) > 0

    and

    len(TVAE_MODELS) == len(AVAILABLE_DATASETS)

)



print("\n" + "=" * 100)


if READY_FOR_TRAINING:

    print("✓ TVAE TRAINING ENVIRONMENT READY")

    print(f"✓ Device          : {DEVICE_NAME.upper()}")

    print(f"✓ GPU Available   : {GPU_AVAILABLE}")

    print(f"✓ Datasets Loaded : {len(AVAILABLE_DATASETS)}")

    print(f"✓ Models Ready    : {len(TVAE_MODELS)}")

    print("✓ Ready for G2 - TVAE Model Training")


else:

    raise RuntimeError(
        "TVAE training environment is not ready."
    )


print("=" * 100)

====================================================================================================
PART G1 — TVAE TRAINING SETUP
====================================================================================================
Datasets Available : 3
   • adult_income
   • bank_marketing
   • diabetes_130us

✓ TVAE output directories verified.

Training Configuration
----------------------------------------------------------------------------------------------------
model                    : TVAE
datasets                 : ['adult_income', 'bank_marketing', 'diabetes_130us']
number_of_datasets       : 3
epochs                   : 100
batch_size               : 256
embedding_dim            : 128
compress_dims            : [128, 128]
decompress_dims          : [128, 128]
loss_factor              : 2
device                   : cpu
gpu_available            : False
random_seed              : 42
sdv_version              : 1.37.4
pytorch_version          : 2.11.0+cpu
model_directory          : /content/drive/MyDrive/SPP_GAN_Project/models/tvae/trained_models
log_directory            : /content/drive/MyDrive/SPP_GAN_Project/models/tvae/training_logs
synthetic_directory      : /content/drive/MyDrive/SPP_GAN_Project/datasets/synthetic/TVAE
report_directory         : /content/drive/MyDrive/SPP_GAN_Project/reports/TVAE
started                  : 2026-08-05 19:05:50

====================================================================================================
TVAE TRAINING DATA SUMMARY
====================================================================================================

          Dataset   Rows  Columns  Numeric Features  Categorical Features
0    adult_income  22756       15                15                     0
1  bank_marketing  31647       17                17                     0
2  diabetes_130us  71236       48                48                     0

✓ Training timer initialized.
✓ Training configuration saved.

====================================================================================================
✓ TVAE TRAINING ENVIRONMENT READY
✓ Device          : CPU
✓ GPU Available   : False
✓ Datasets Loaded : 3
✓ Models Ready    : 3
✓ Ready for G2 - TVAE Model Training
====================================================================================================

In [ ]:
# ==============================================================================
# PART G2 - TRAIN TVAE MODELS
# ==============================================================================

import os
import time
import json
import traceback
import joblib

from datetime import datetime


print("=" * 100)
print("G2. TRAINING TVAE MODELS")
print("=" * 100)



# ------------------------------------------------------------------------------
# Reset Training Containers
# ------------------------------------------------------------------------------

SUCCESSFUL_MODELS = []

FAILED_MODELS = []

TRAINED_TVAE_MODELS = {}

TVAE_HISTORY = {}

TVAE_TRAINING_SUMMARY = []

TVAE_MODEL_PATHS = {}

TVAE_TRAINING_LOGS = {}



# ------------------------------------------------------------------------------
# Training Loop
# ------------------------------------------------------------------------------

for dataset_name in AVAILABLE_DATASETS:


    print("\n" + "=" * 100)

    print(
        f"Training Dataset : {dataset_name}"
    )

    print("=" * 100)



    train_df = TVAE_TRAIN_DATA[dataset_name]


    synthesizer = TVAE_MODELS[dataset_name]


    start_time = time.time()

    start_timestamp = datetime.now()


    status = "SUCCESS"

    error_message = ""

    model_path = None



    try:


        print(
            f"Rows    : {len(train_df):,}"
        )

        print(
            f"Columns : {train_df.shape[1]}"
        )


        print(
            "\nStarting TVAE training...\n"
        )



        # ----------------------------------------------------------------------
        # Train TVAE
        # ----------------------------------------------------------------------

        synthesizer.fit(train_df)



        elapsed = time.time() - start_time



        TRAINED_TVAE_MODELS[dataset_name] = synthesizer



        # ----------------------------------------------------------------------
        # Save Model
        # ----------------------------------------------------------------------

        model_path = os.path.join(

            TVAE_MODEL_DIR,

            f"{dataset_name}_tvae.pkl"

        )


        joblib.dump(

            synthesizer,

            model_path

        )


        TVAE_MODEL_PATHS[dataset_name] = model_path


        SUCCESSFUL_MODELS.append(dataset_name)



        print(
            f"\n✓ Training completed in {elapsed:.2f} seconds"
        )


        print(
            "✓ Model saved successfully"
        )



    except Exception as e:


        elapsed = time.time() - start_time


        status = "FAILED"


        error_message = str(e)


        FAILED_MODELS.append(dataset_name)


        print("\n✗ Training FAILED")


        traceback.print_exc()




    # ------------------------------------------------------------------------------
    # Save Training History
    # ------------------------------------------------------------------------------

    history = {


        "dataset": dataset_name,


        "rows": len(train_df),


        "columns": train_df.shape[1],


        "embedding_dim": TVAE_CONFIG["embedding_dim"],


        "compress_dims":
            list(TVAE_CONFIG["compress_dims"]),


        "decompress_dims":
            list(TVAE_CONFIG["decompress_dims"]),


        "loss_factor":
            TVAE_CONFIG["loss_factor"],


        "start_time":
            start_timestamp.strftime(
                "%Y-%m-%d %H:%M:%S"
            ),


        "end_time":
            datetime.now().strftime(
                "%Y-%m-%d %H:%M:%S"
            ),


        "training_time_seconds":
            round(elapsed,2),


        "status": status,


        "model_path": model_path,


        "error": error_message

    }



    TVAE_HISTORY[dataset_name] = history



    log_file = os.path.join(

        TVAE_LOG_DIR,

        f"{dataset_name}_training_log.json"

    )


    with open(log_file, "w") as fp:


        json.dump(

            history,

            fp,

            indent=4

        )



    TVAE_TRAINING_LOGS[dataset_name] = log_file



    TVAE_TRAINING_SUMMARY.append({


        "Dataset": dataset_name,


        "Rows": len(train_df),


        "Columns": train_df.shape[1],


        "Training Time (sec)": round(elapsed,2),


        "Status": status,


        "Model Saved": status == "SUCCESS"

    })




# ------------------------------------------------------------------------------
# Final Summary
# ------------------------------------------------------------------------------

print("\n" + "=" * 100)

print("TVAE TRAINING COMPLETED")

print("=" * 100)



print(
    f"Successful Models : {len(SUCCESSFUL_MODELS)}"
)


print(
    f"Failed Models     : {len(FAILED_MODELS)}"
)



if FAILED_MODELS:


    print("\nFailed Datasets:")


    for dataset in FAILED_MODELS:

        print(
            f" - {dataset}"
        )



TVAE_TRAINING_SUMMARY_DF = pd.DataFrame(

    TVAE_TRAINING_SUMMARY

)



display(

    TVAE_TRAINING_SUMMARY_DF

)



if len(SUCCESSFUL_MODELS) == len(AVAILABLE_DATASETS):


    print("\n✓ All TVAE models trained successfully.")


else:


    print("\n⚠ Some TVAE models failed.")

====================================================================================================
G2. TRAINING TVAE MODELS
====================================================================================================

====================================================================================================
Training Dataset : adult_income
====================================================================================================
Rows    : 22,756
Columns : 15

Starting TVAE training...


✓ Training completed in 211.02 seconds
✓ Model saved successfully

====================================================================================================
Training Dataset : bank_marketing
====================================================================================================
Rows    : 31,647
Columns : 17

Starting TVAE training...


✓ Training completed in 362.61 seconds
✓ Model saved successfully

====================================================================================================
Training Dataset : diabetes_130us
====================================================================================================
Rows    : 71,236
Columns : 48

Starting TVAE training...

In [ ]:
# ==============================================================================
# PART G3 - TRAINING TIME & PROGRESS LOGGING
# ==============================================================================

print("=" * 100)
print("PART G3 - TVAE TRAINING TIME & PROGRESS LOGGING")
print("=" * 100)


import os
import pandas as pd



# ------------------------------------------------------------------------------
# Verify Training Summary
# ------------------------------------------------------------------------------

if "TVAE_TRAINING_SUMMARY" not in globals():

    raise RuntimeError(
        "TVAE_TRAINING_SUMMARY not found.\n"
        "Execute Part G2 before running Part G3."
    )


if len(TVAE_TRAINING_SUMMARY) == 0:

    raise RuntimeError(
        "TVAE_TRAINING_SUMMARY is empty.\n"
        "No TVAE training results available."
    )



# ------------------------------------------------------------------------------
# Create DataFrame
# ------------------------------------------------------------------------------

TVAE_TRAINING_LOG_DF = pd.DataFrame(
    TVAE_TRAINING_SUMMARY
)


if "Dataset" in TVAE_TRAINING_LOG_DF.columns:

    TVAE_TRAINING_LOG_DF = (

        TVAE_TRAINING_LOG_DF

        .sort_values("Dataset")

        .reset_index(drop=True)

    )


display(
    TVAE_TRAINING_LOG_DF
)



# ------------------------------------------------------------------------------
# Training Statistics
# ------------------------------------------------------------------------------

total_models = len(
    TVAE_TRAINING_LOG_DF
)


successful_models = (

    TVAE_TRAINING_LOG_DF["Status"] == "SUCCESS"

).sum()


failed_models = (

    TVAE_TRAINING_LOG_DF["Status"] == "FAILED"

).sum()



success_rate = (

    successful_models / total_models * 100

    if total_models > 0

    else 0

)



if "Training Time (sec)" in TVAE_TRAINING_LOG_DF.columns:


    total_time = (

        TVAE_TRAINING_LOG_DF["Training Time (sec)"]

        .sum()

    )


    average_time = (

        TVAE_TRAINING_LOG_DF["Training Time (sec)"]

        .mean()

    )


    minimum_time = (

        TVAE_TRAINING_LOG_DF["Training Time (sec)"]

        .min()

    )


    maximum_time = (

        TVAE_TRAINING_LOG_DF["Training Time (sec)"]

        .max()

    )


else:

    total_time = 0

    average_time = 0

    minimum_time = 0

    maximum_time = 0



# ------------------------------------------------------------------------------
# Save TVAE Training Log
# ------------------------------------------------------------------------------

os.makedirs(

    TVAE_LOG_DIR,

    exist_ok=True

)


TVAE_TRAINING_LOG_FILE = os.path.join(

    TVAE_LOG_DIR,

    "tvae_training_summary.csv"

)


TVAE_TRAINING_LOG_DF.to_csv(

    TVAE_TRAINING_LOG_FILE,

    index=False

)



# ------------------------------------------------------------------------------
# Summary
# ------------------------------------------------------------------------------

print("\n" + "=" * 100)

print("TVAE TRAINING SUMMARY")

print("=" * 100)


print(f"Total Models        : {total_models}")

print(f"Successful Models   : {successful_models}")

print(f"Failed Models       : {failed_models}")

print(f"Success Rate        : {success_rate:.2f}%")

print(f"Total Training Time : {total_time:.2f} sec")

print(f"Average Time        : {average_time:.2f} sec")

print(f"Minimum Time        : {minimum_time:.2f} sec")

print(f"Maximum Time        : {maximum_time:.2f} sec")


print("\nTraining Log Saved:")

print(TVAE_TRAINING_LOG_FILE)


print("\n✓ TVAE training progress logged successfully.")

print("✓ TVAE training summary saved.")

print("✓ Ready for Part G4 - Save Trained TVAE Models.")

             Component  Status Result
0  Configuration Table    True   PASS
1        Summary Saved    True   PASS

✓ PART 5.6.3 Completed Successfully

In [ ]:
# ==============================================================================
# PART G4 - Detailed TVAE Training History
# ==============================================================================

print("=" * 100)
print("PART G4 - DETAILED TVAE TRAINING HISTORY")
print("=" * 100)

# ------------------------------------------------------------------------------
# Verify Training History
# ------------------------------------------------------------------------------

if "TVAE_HISTORY" not in globals():

    raise RuntimeError(
        "TVAE_HISTORY not found.\n"
        "Please execute Part G2 first."
    )

if len(TVAE_HISTORY) == 0:

    raise RuntimeError(
        "No TVAE training history available."
    )

# ------------------------------------------------------------------------------
# Build History Table
# ------------------------------------------------------------------------------

history_rows = []

for dataset_name, info in TVAE_HISTORY.items():

    training_seconds = info.get(
        "training_time_seconds",
        0
    )

    history_rows.append({

        "Dataset": dataset_name,

        "Rows": info.get(
            "rows",
            0
        ),

        "Columns": info.get(
            "columns",
            0
        ),

        "Training Started": info.get(
            "start_time",
            "N/A"
        ),

        "Training Finished": info.get(
            "end_time",
            "N/A"
        ),

        "Training Time (sec)": round(
            training_seconds,
            2
        ),

        "Training Time (min)": round(
            training_seconds / 60,
            2
        ),

        "Status": info.get(
            "status",
            "UNKNOWN"
        ),

        "Model Saved": (
            "Yes"
            if info.get("model_path")
            else "No"
        ),

        "Model Path": info.get(
            "model_path",
            "Not Available"
        ),

        "Error": (
            info.get("error", "")
            if info.get("status") == "FAILED"
            else ""
        )
    })

TVAE_HISTORY_DF = pd.DataFrame(
    history_rows
)

TVAE_HISTORY_DF = (
    TVAE_HISTORY_DF
    .sort_values("Dataset")
    .reset_index(drop=True)
)

display(TVAE_HISTORY_DF)

# ------------------------------------------------------------------------------
# Summary
# ------------------------------------------------------------------------------

print("\n" + "=" * 100)
print("TVAE TRAINING HISTORY SUMMARY")
print("=" * 100)

total_models = len(
    TVAE_HISTORY_DF
)

successful = (
    TVAE_HISTORY_DF["Status"] == "SUCCESS"
).sum()

failed = (
    TVAE_HISTORY_DF["Status"] == "FAILED"
).sum()

total_time = (
    TVAE_HISTORY_DF["Training Time (sec)"]
    .sum()
)

average_time = (
    TVAE_HISTORY_DF["Training Time (sec)"]
    .mean()
)

print(f"Datasets Processed : {total_models}")
print(f"Successful Models  : {successful}")
print(f"Failed Models      : {failed}")
print(f"Total Time (sec)   : {total_time:.2f}")
print(f"Average Time (sec) : {average_time:.2f}")

print("\n✓ Detailed TVAE training history generated successfully.")
print("✓ Ready for Part G5.")

====================================================================================================
PART 5.6.4 — TVAE TRAINING
====================================================================================================

====================================================================================================
Training TVAE : adult_income
====================================================================================================
Dataset Shape : (32510, 15)

Loss: -19.88: 100%|██████████| 200/200 [32:09<00:00,  9.65s/it]

✓ Training Completed
Training Time : 1984.05 seconds

====================================================================================================
Training TVAE : bank_marketing
====================================================================================================
Dataset Shape : (45211, 17)

Loss: -12.26: 100%|██████████| 200/200 [52:04<00:00, 15.62s/it]

✓ Training Completed
Training Time : 3183.86 seconds

====================================================================================================
Training TVAE : breast_cancer
====================================================================================================
Dataset Shape : (569, 32)

Loss: -14.20: 100%|██████████| 200/200 [00:18<00:00, 10.75it/s]

✓ Training Completed
Training Time : 37.22 seconds

====================================================================================================
Total TVAE Training Time : 5205.14 seconds
====================================================================================================

In [ ]:
# ==============================================================================
# PART G5 - Overall TVAE Training Statistics
# ==============================================================================

print("=" * 100)
print("PART G5 - OVERALL TVAE TRAINING STATISTICS")
print("=" * 100)

# ------------------------------------------------------------------------------
# Verify Training History
# ------------------------------------------------------------------------------

if "TVAE_HISTORY_DF" not in globals():

    raise RuntimeError(
        "TVAE_HISTORY_DF not found.\n"
        "Please execute Part G4 first."
    )

if TVAE_HISTORY_DF.empty:

    raise RuntimeError(
        "Training history is empty."
    )

# ------------------------------------------------------------------------------
# Overall Statistics
# ------------------------------------------------------------------------------

total_models = len(
    TVAE_HISTORY_DF
)

successful_models = (
    TVAE_HISTORY_DF["Status"] == "SUCCESS"
).sum()

failed_models = (
    TVAE_HISTORY_DF["Status"] == "FAILED"
).sum()

success_rate = (
    successful_models / total_models * 100
)

print(f"Datasets Processed  : {total_models}")
print(f"Successful Models   : {successful_models}")
print(f"Failed Models       : {failed_models}")
print(f"Success Rate        : {success_rate:.2f}%")

# ------------------------------------------------------------------------------
# Successful Models Statistics
# ------------------------------------------------------------------------------

SUCCESS_HISTORY = TVAE_HISTORY_DF[
    TVAE_HISTORY_DF["Status"] == "SUCCESS"
].copy()

if not SUCCESS_HISTORY.empty:

    total_time = (
        SUCCESS_HISTORY["Training Time (sec)"]
        .sum()
    )

    average_time = (
        SUCCESS_HISTORY["Training Time (sec)"]
        .mean()
    )

    fastest = SUCCESS_HISTORY.loc[
        SUCCESS_HISTORY["Training Time (sec)"].idxmin()
    ]

    slowest = SUCCESS_HISTORY.loc[
        SUCCESS_HISTORY["Training Time (sec)"].idxmax()
    ]

    print("\n" + "-" * 100)

    print(f"Total Training Time   : {total_time:.2f} sec")
    print(f"Average Training Time : {average_time:.2f} sec")

    print("\nFastest Model")
    print("-" * 40)
    print(f"Dataset        : {fastest['Dataset']}")
    print(f"Training Time  : {fastest['Training Time (sec)']:.2f} sec")

    print("\nSlowest Model")
    print("-" * 40)
    print(f"Dataset        : {slowest['Dataset']}")
    print(f"Training Time  : {slowest['Training Time (sec)']:.2f} sec")

else:

    print("\nNo successful TVAE models were trained.")

print("\n" + "=" * 100)
print("✓ Overall TVAE training statistics generated successfully.")
print("✓ Ready for Part G6.")
print("=" * 100)

          Dataset   Rows  Columns  Epochs  Batch Size  Embedding Dimension  Training Time (Seconds)   Status
0    adult_income  32510       15     200         256                  128                1984.0500  Success
1  bank_marketing  45211       17     200         256                  128                3183.8600  Success
2   breast_cancer    569       32     200         256                  128                  37.2200  Success

In [ ]:
# ==============================================================================
# PART G6 - Save TVAE Training Logs
# ==============================================================================

import os
import pickle

print("=" * 100)
print("PART G6 - SAVE TVAE TRAINING LOGS")
print("=" * 100)

# ------------------------------------------------------------------------------
# Verify Required Objects
# ------------------------------------------------------------------------------

if "TVAE_TRAINING_LOG_DF" not in globals():

    raise RuntimeError(
        "TVAE_TRAINING_LOG_DF not found.\n"
        "Please execute Part G3 first."
    )

if "TVAE_HISTORY_DF" not in globals():

    raise RuntimeError(
        "TVAE_HISTORY_DF not found.\n"
        "Please execute Part G4 first."
    )

if "TVAE_HISTORY" not in globals():

    raise RuntimeError(
        "TVAE_HISTORY not found.\n"
        "Please execute Part G2 first."
    )

# ------------------------------------------------------------------------------
# Create Output Directory
# ------------------------------------------------------------------------------

os.makedirs(
    TVAE_LOG_DIR,
    exist_ok=True
)

# ------------------------------------------------------------------------------
# Output Files
# ------------------------------------------------------------------------------

TVAE_TRAINING_LOG_CSV = os.path.join(
    TVAE_LOG_DIR,
    "training_log.csv"
)

TVAE_TRAINING_HISTORY_CSV = os.path.join(
    TVAE_LOG_DIR,
    "training_history.csv"
)

TVAE_TRAINING_HISTORY_PKL = os.path.join(
    TVAE_LOG_DIR,
    "training_history.pkl"
)

# ------------------------------------------------------------------------------
# Save Files
# ------------------------------------------------------------------------------

TVAE_TRAINING_LOG_DF.to_csv(
    TVAE_TRAINING_LOG_CSV,
    index=False
)

TVAE_HISTORY_DF.to_csv(
    TVAE_TRAINING_HISTORY_CSV,
    index=False
)

with open(TVAE_TRAINING_HISTORY_PKL, "wb") as file:

    pickle.dump(
        TVAE_HISTORY,
        file
    )

# ------------------------------------------------------------------------------
# Summary
# ------------------------------------------------------------------------------

print(
    f"Training Log Records     : {len(TVAE_TRAINING_LOG_DF)}"
)

print(
    f"Training History Records : {len(TVAE_HISTORY_DF)}"
)

print("\n✓ Training log saved.")
print("✓ Training history saved.")
print("✓ Training history object saved.")

print("\n" + "=" * 100)
print("✓ PART G6 COMPLETED SUCCESSFULLY")
print("✓ All TVAE training logs saved.")
print("✓ Ready for Part G7.")
print("=" * 100)

Training summary saved to:
/content/drive/MyDrive/SPP_GAN_Project/reports/TVAE/tvae_training_summary.csv

In [ ]:
# ==============================================================================
# PART G7 - Save TVAE Training Metadata
# ==============================================================================

import os
import json
from datetime import datetime

print("=" * 100)
print("PART G7 - SAVE TVAE TRAINING METADATA")
print("=" * 100)

# ------------------------------------------------------------------------------
# Verify Required Objects
# ------------------------------------------------------------------------------

required_objects = [
    "TVAE_HISTORY_DF",
    "TVAE_CONFIG",
    "TVAE_LOG_DIR"
]

missing_objects = [
    obj
    for obj in required_objects
    if obj not in globals()
]

if missing_objects:

    raise RuntimeError(
        "Missing required objects:\n"
        f"{missing_objects}"
    )

# ------------------------------------------------------------------------------
# Device Information
# ------------------------------------------------------------------------------

if isinstance(DEVICE, torch.device):

    device_name = DEVICE.type

else:

    device_name = str(DEVICE)

# ------------------------------------------------------------------------------
# Training Metadata
# ------------------------------------------------------------------------------

TRAINING_METADATA = {

    "model": "TVAE",

    "training_date":
        datetime.now().strftime("%Y-%m-%d %H:%M:%S"),

    "device":
        device_name,

    "datasets_processed":
        int(len(TVAE_HISTORY_DF)),

    "dataset_names":
        sorted(
            TVAE_HISTORY_DF["Dataset"].tolist()
        ),

    "successful_models":
        int(
            (TVAE_HISTORY_DF["Status"] == "SUCCESS").sum()
        ),

    "failed_models":
        int(
            (TVAE_HISTORY_DF["Status"] == "FAILED").sum()
        ),

    "epochs":
        int(TVAE_CONFIG["epochs"]),

    "batch_size":
        int(TVAE_CONFIG["batch_size"]),

    "learning_rate":
        float(TVAE_CONFIG["learning_rate"]),

    "embedding_dimension":
        int(TVAE_CONFIG.get("embedding_dim", 128)),

    "compress_dimensions":
        list(
            TVAE_CONFIG.get(
                "compress_dims",
                []
            )
        ),

    "decompress_dimensions":
        list(
            TVAE_CONFIG.get(
                "decompress_dims",
                []
            )
        )
}

# ------------------------------------------------------------------------------
# Save Metadata
# ------------------------------------------------------------------------------

os.makedirs(
    TVAE_LOG_DIR,
    exist_ok=True
)

TRAINING_METADATA_FILE = os.path.join(
    TVAE_LOG_DIR,
    "training_metadata.json"
)

with open(
    TRAINING_METADATA_FILE,
    "w",
    encoding="utf-8"
) as file:

    json.dump(
        TRAINING_METADATA,
        file,
        indent=4,
        ensure_ascii=False
    )

# ------------------------------------------------------------------------------
# Verification
# ------------------------------------------------------------------------------

if not os.path.exists(TRAINING_METADATA_FILE):

    raise FileNotFoundError(
        "Failed to save training metadata."
    )

# ------------------------------------------------------------------------------
# Summary
# ------------------------------------------------------------------------------

print(f"Metadata File : {TRAINING_METADATA_FILE}")
print(f"Datasets      : {TRAINING_METADATA['datasets_processed']}")
print(f"Successful    : {TRAINING_METADATA['successful_models']}")
print(f"Failed        : {TRAINING_METADATA['failed_models']}")

print("\n" + "=" * 100)
print("✓ PART G7 COMPLETED SUCCESSFULLY")
print("✓ TVAE training metadata saved.")
print("✓ Ready for Part G8.")
print("=" * 100)

====================================================================================================
PART 5.6.4 VERIFICATION
====================================================================================================

                 Component  Status Result
0   Three Datasets Trained    True   PASS
1   Training Summary Saved    True   PASS
2  All Training Successful    True   PASS

✓ PART 5.6.4 Completed Successfully

In [ ]:
# ==============================================================================
# PART G8 - Verification of Saved TVAE Models
# ==============================================================================

print("=" * 100)
print("PART G8 - VERIFY SAVED TVAE MODELS")
print("=" * 100)

# ------------------------------------------------------------------------------
# Verify Required Objects
# ------------------------------------------------------------------------------

required_objects = [
    "TVAE_TRAINING_SUMMARY",
    "TVAE_HISTORY",
    "SUCCESSFUL_MODELS",
    "FAILED_MODELS",
    "TVAE_MODEL_DIR",
    "TVAE_TRAINING_LOG_CSV",
    "TVAE_TRAINING_HISTORY_CSV",
    "TRAINING_METADATA_FILE"
]

missing = [
    obj
    for obj in required_objects
    if obj not in globals()
]

if missing:

    raise RuntimeError(
        f"Missing required objects:\n{missing}"
    )

# ------------------------------------------------------------------------------
# Verify Saved Model Files
# ------------------------------------------------------------------------------

MODEL_SAVE_RESULTS = []

for dataset in SUCCESSFUL_MODELS:

    model_path = os.path.join(
        TVAE_MODEL_DIR,
        f"{dataset}_tvae.pkl"
    )

    MODEL_SAVE_RESULTS.append({

        "Dataset": dataset,

        "Model Exists": os.path.exists(model_path),

        "Model File": model_path

    })

MODEL_SAVE_DF = pd.DataFrame(
    MODEL_SAVE_RESULTS
)

display(
    MODEL_SAVE_DF
)

# ------------------------------------------------------------------------------
# Verification
# ------------------------------------------------------------------------------

verification = {

    "Training Log Saved":
        os.path.exists(
            TVAE_TRAINING_LOG_CSV
        ),

    "Training History Saved":
        os.path.exists(
            TVAE_TRAINING_HISTORY_CSV
        ),

    "Training Metadata Saved":
        os.path.exists(
            TRAINING_METADATA_FILE
        ),

    "Training History Available":
        len(TVAE_HISTORY) > 0,

    "Training Summary Available":
        len(TVAE_TRAINING_SUMMARY) > 0,

    "Successful Models Available":
        len(SUCCESSFUL_MODELS) > 0,

    "All Saved Models Exist":
        (
            MODEL_SAVE_DF["Model Exists"].all()
            if not MODEL_SAVE_DF.empty
            else False
        ),

    "Model Directory Exists":
        os.path.exists(
            TVAE_MODEL_DIR
        )
}

VERIFY_DF = pd.DataFrame({

    "Component": verification.keys(),

    "Status": verification.values()

})

VERIFY_DF["Result"] = VERIFY_DF["Status"].map(
    lambda x: "PASS" if x else "FAIL"
)

display(
    VERIFY_DF
)

# ------------------------------------------------------------------------------
# Summary
# ------------------------------------------------------------------------------

print("\n" + "=" * 100)
print("PART G8 SUMMARY")
print("=" * 100)

print(f"Successful Models : {len(SUCCESSFUL_MODELS)}")
print(f"Failed Models     : {len(FAILED_MODELS)}")
print(f"Verified Models   : {len(MODEL_SAVE_DF)}")

passed = VERIFY_DF["Status"].sum()

total = len(VERIFY_DF)

print(f"\nVerification Checks : {passed}/{total}")

if VERIFY_DF["Status"].all():

    print("\n" + "=" * 100)
    print("✓ PART G8 COMPLETED SUCCESSFULLY")
    print("✓ Saved TVAE models verified.")
    print("✓ Training logs verified.")
    print("✓ Training metadata verified.")
    print("✓ Ready for Part G9")
    print("=" * 100)

else:

    failed = VERIFY_DF.loc[
        ~VERIFY_DF["Status"],
        "Component"
    ].tolist()

    print("\nFailed Components:")

    for item in failed:
        print(f"  • {item}")

    raise RuntimeError(
        "Part G8 verification failed."
    )

====================================================================================================
PART 5.6.5 — SAVE TRAINED TVAE MODELS
====================================================================================================

Saving TVAE Model : adult_income
✓ Model Saved
/content/drive/MyDrive/SPP_GAN_Project/models/TVAE/adult_income_tvae.pkl

Saving TVAE Model : bank_marketing
✓ Model Saved
/content/drive/MyDrive/SPP_GAN_Project/models/TVAE/bank_marketing_tvae.pkl

Saving TVAE Model : breast_cancer
✓ Model Saved
/content/drive/MyDrive/SPP_GAN_Project/models/TVAE/breast_cancer_tvae.pkl

In [ ]:
# ==============================================================================
# PART G9 — VERIFY TRAINED TVAE MODELS
# ==============================================================================

print("=" * 100)
print("PART G9 — VERIFY TRAINED TVAE MODELS")
print("=" * 100)

import os
import joblib

from sdv.single_table import TVAESynthesizer

# ------------------------------------------------------------------------------
# Verify required objects
# ------------------------------------------------------------------------------

required_objects = [
    "SUCCESSFUL_MODELS",
    "TVAE_MODEL_DIR"
]

missing = [
    obj for obj in required_objects
    if obj not in globals()
]

if missing:
    raise RuntimeError(
        "Missing required objects:\n"
        f"{missing}"
    )

if len(SUCCESSFUL_MODELS) == 0:
    raise RuntimeError(
        "No successfully trained TVAE models were found.\n"
        "Please execute Part G2 first."
    )

# ------------------------------------------------------------------------------
# Verify Saved Models
# ------------------------------------------------------------------------------

verification = []

for dataset in SUCCESSFUL_MODELS:

    model_path = os.path.join(
        TVAE_MODEL_DIR,
        f"{dataset}_tvae.pkl"
    )

    file_exists = os.path.exists(model_path)
    loadable = False
    valid_type = False
    sample_generation = False
    file_size_mb = 0.0
    error_message = ""

    if file_exists:

        file_size_mb = round(
            os.path.getsize(model_path) / (1024 ** 2),
            2
        )

        try:

            loaded_model = joblib.load(model_path)

            loadable = True

            valid_type = isinstance(
                loaded_model,
                TVAESynthesizer
            )

            if valid_type:

                try:

                    sample = loaded_model.sample(
                        num_rows=2
                    )

                    sample_generation = (
                        sample is not None
                        and len(sample) == 2
                    )

                except Exception as e:

                    error_message = str(e)

        except Exception as e:

            error_message = str(e)

    verification.append({

        "Dataset": dataset,

        "Model File": file_exists,

        "Loadable": loadable,

        "Valid TVAE": valid_type,

        "Sample Generation": sample_generation,

        "File Size (MB)": file_size_mb,

        "Result":
            (
                "PASS"
                if (
                    file_exists
                    and loadable
                    and valid_type
                    and sample_generation
                )
                else "FAIL"
            ),

        "Error": error_message

    })

# ------------------------------------------------------------------------------
# Verification DataFrame
# ------------------------------------------------------------------------------

MODEL_VERIFICATION_DF = pd.DataFrame(
    verification
)

MODEL_VERIFICATION_DF = (
    MODEL_VERIFICATION_DF
    .sort_values("Dataset")
    .reset_index(drop=True)
)

display(MODEL_VERIFICATION_DF)

# ------------------------------------------------------------------------------
# Summary
# ------------------------------------------------------------------------------

print("\n" + "=" * 100)
print("MODEL VERIFICATION SUMMARY")
print("=" * 100)

passed = (
    MODEL_VERIFICATION_DF["Result"] == "PASS"
).sum()

total = len(MODEL_VERIFICATION_DF)

failed = total - passed

success_rate = (
    (passed / total) * 100
    if total > 0
    else 0.0
)

print(f"Models Verified : {total}")
print(f"Passed          : {passed}")
print(f"Failed          : {failed}")
print(f"Success Rate    : {success_rate:.2f}%")

if failed == 0:

    print("\n" + "=" * 100)
    print("✓ PART G9 COMPLETED SUCCESSFULLY")
    print("✓ All TVAE models loaded successfully.")
    print("✓ All models are valid TVAE synthesizers.")
    print("✓ Synthetic sample generation verified.")
    print("✓ Ready for Part H - Synthetic Data Generation")
    print("=" * 100)

else:

    print("\nFailed Models:\n")

    display(
        MODEL_VERIFICATION_DF[
            MODEL_VERIFICATION_DF["Result"] == "FAIL"
        ]
    )

    raise RuntimeError(
        "One or more TVAE models failed verification."
    )

          Dataset                                         Model File  Exists  Model Size (MB)
0    adult_income  /content/drive/MyDrive/SPP_GAN_Project/models/...    True           1.2300
1  bank_marketing  /content/drive/MyDrive/SPP_GAN_Project/models/...    True           1.4800
2   breast_cancer  /content/drive/MyDrive/SPP_GAN_Project/models/...    True           1.2800

In [ ]:
# ==============================================================================
# H1. Load Trained TVAE Models
# ==============================================================================

import os
import joblib

print("=" * 100)
print("H1. LOADING TRAINED TVAE MODELS")
print("=" * 100)

# ------------------------------------------------------------------------------
# Verify model directory
# ------------------------------------------------------------------------------

if not os.path.exists(TVAE_MODEL_DIR):
    raise FileNotFoundError(
        f"TVAE model directory not found:\n{TVAE_MODEL_DIR}"
    )

# ------------------------------------------------------------------------------
# Load trained models
# ------------------------------------------------------------------------------

LOADED_TVAE_MODELS = {}

LOADED_MODEL_SUMMARY = []

for dataset in AVAILABLE_DATASETS:

    model_path = os.path.join(
        TVAE_MODEL_DIR,
        f"{dataset}_tvae.pkl"
    )

    if not os.path.exists(model_path):
        raise FileNotFoundError(
            f"Model not found:\n{model_path}"
        )

    try:

        model = joblib.load(model_path)

        LOADED_TVAE_MODELS[dataset] = model

        LOADED_MODEL_SUMMARY.append({

            "Dataset": dataset,

            "Model Loaded": True,

            "File Size (MB)": round(
                os.path.getsize(model_path) / (1024 ** 2),
                2
            )

        })

        print(f"✓ {dataset:<25} Loaded")

    except Exception as e:

        raise RuntimeError(
            f"Failed to load model '{dataset}':\n{e}"
        )

# ------------------------------------------------------------------------------
# Summary
# ------------------------------------------------------------------------------

LOADED_MODEL_SUMMARY_DF = pd.DataFrame(
    LOADED_MODEL_SUMMARY
)

display(LOADED_MODEL_SUMMARY_DF)

print("\n" + "=" * 100)
print("MODEL LOADING SUMMARY")
print("=" * 100)

print(f"Models Loaded : {len(LOADED_TVAE_MODELS)}")
print(f"Datasets      : {len(AVAILABLE_DATASETS)}")

print("\n✓ All TVAE models loaded successfully.")

Model inventory saved to:
/content/drive/MyDrive/SPP_GAN_Project/reports/TVAE/tvae_saved_models_summary.csv

In [ ]:
# ==============================================================================
# PART H2 — GENERATE SYNTHETIC DATASETS
# ==============================================================================

import time
import pandas as pd

print("=" * 100)
print("PART H2 — GENERATING SYNTHETIC DATASETS")
print("=" * 100)

SYNTHETIC_DATASETS = {}

GENERATION_SUMMARY = []

FAILED_DATASETS = []

for dataset in AVAILABLE_DATASETS:

    print("\n" + "-" * 100)
    print(f"Dataset : {dataset}")
    print("-" * 100)

    real_df = PROCESSED_DATASETS[dataset]

    n_rows = len(real_df)

    start_time = time.time()

    try:

        # ----------------------------------------------------------------------
        # Generate Synthetic Dataset
        # ----------------------------------------------------------------------

        synthetic_df = LOADED_TVAE_MODELS[dataset].sample(
            num_rows=n_rows
        )

        # ----------------------------------------------------------------------
        # Restore Original Column Order
        # ----------------------------------------------------------------------

        synthetic_df = synthetic_df[
            real_df.columns
        ]

        # ----------------------------------------------------------------------
        # Restore Original Data Types
        # ----------------------------------------------------------------------

        for column in real_df.columns:

            real_dtype = real_df[column].dtype

            try:

                if pd.api.types.is_integer_dtype(real_dtype):

                    synthetic_df[column] = (
                        pd.to_numeric(
                            synthetic_df[column],
                            errors="coerce"
                        )
                        .round()
                        .astype(real_dtype)
                    )

                elif pd.api.types.is_float_dtype(real_dtype):

                    synthetic_df[column] = (
                        pd.to_numeric(
                            synthetic_df[column],
                            errors="coerce"
                        )
                        .astype(real_dtype)
                    )

                elif pd.api.types.is_bool_dtype(real_dtype):

                    synthetic_df[column] = (
                        synthetic_df[column]
                        .astype(real_dtype)
                    )

                elif pd.api.types.is_datetime64_any_dtype(real_dtype):

                    synthetic_df[column] = pd.to_datetime(
                        synthetic_df[column],
                        errors="coerce"
                    )

                elif pd.api.types.is_categorical_dtype(real_dtype):

                    synthetic_df[column] = pd.Categorical(
                        synthetic_df[column],
                        categories=real_df[column].cat.categories,
                        ordered=real_df[column].cat.ordered
                    )

                elif pd.api.types.is_string_dtype(real_dtype):

                    synthetic_df[column] = (
                        synthetic_df[column]
                        .astype("string")
                    )

                elif real_dtype == object:

                    synthetic_df[column] = (
                        synthetic_df[column]
                        .astype(object)
                    )

                else:

                    synthetic_df[column] = (
                        synthetic_df[column]
                        .astype(real_dtype)
                    )

            except Exception:

                print(
                    f"Warning: Unable to convert "
                    f"'{column}' to {real_dtype}."
                )

        # ----------------------------------------------------------------------
        # Store Dataset
        # ----------------------------------------------------------------------

        elapsed = round(
            time.time() - start_time,
            2
        )

        SYNTHETIC_DATASETS[dataset] = synthetic_df

        GENERATION_SUMMARY.append({

            "Dataset": dataset,

            "Real Rows": len(real_df),

            "Synthetic Rows": len(synthetic_df),

            "Columns": synthetic_df.shape[1],

            "Generation Time (sec)": elapsed,

            "Status": "SUCCESS"

        })

        print(f"Rows Generated : {len(synthetic_df):,}")
        print(f"Columns        : {synthetic_df.shape[1]}")
        print(f"Time           : {elapsed:.2f} sec")
        print("Status         : SUCCESS")

    except Exception as e:

        elapsed = round(
            time.time() - start_time,
            2
        )

        FAILED_DATASETS.append(dataset)

        GENERATION_SUMMARY.append({

            "Dataset": dataset,

            "Real Rows": len(real_df),

            "Synthetic Rows": 0,

            "Columns": 0,

            "Generation Time (sec)": elapsed,

            "Status": "FAILED"

        })

        print("Status : FAILED")
        print(e)

# ------------------------------------------------------------------------------
# Generation Summary
# ------------------------------------------------------------------------------

GENERATION_SUMMARY_DF = pd.DataFrame(
    GENERATION_SUMMARY
)

display(GENERATION_SUMMARY_DF)

print("\n" + "=" * 100)
print("GENERATION SUMMARY")
print("=" * 100)

successful = (
    GENERATION_SUMMARY_DF["Status"] == "SUCCESS"
).sum()

failed = (
    GENERATION_SUMMARY_DF["Status"] == "FAILED"
).sum()

print(f"Successful Datasets : {successful}")
print(f"Failed Datasets     : {failed}")

if failed:

    print("\nFailed Datasets:")

    for dataset in FAILED_DATASETS:
        print(f"  • {dataset}")

else:

    print("\n✓ TVAE synthetic datasets generated successfully.")

====================================================================================================
PART 5.6.5 VERIFICATION
====================================================================================================

               Component  Status Result
0     Three Models Saved    True   PASS
1  All Model Files Exist    True   PASS
2        Inventory Saved    True   PASS

✓ PART 5.6.5 Completed Successfully

In [ ]:
# ==============================================================================
# PART H3 — VALIDATE SYNTHETIC DATASETS
# ==============================================================================

import os
import numpy as np
import pandas as pd

print("=" * 100)
print("PART H3 — VALIDATING TVAE SYNTHETIC DATASETS")
print("=" * 100)

# ------------------------------------------------------------------------------
# Verify required objects
# ------------------------------------------------------------------------------

required_objects = [
    "AVAILABLE_DATASETS",
    "PROCESSED_DATASETS",
    "SYNTHETIC_DATASETS",
    "REPORT_DIR"
]

missing = [
    obj for obj in required_objects
    if obj not in globals()
]

if missing:
    raise RuntimeError(
        f"Missing required objects:\n{missing}"
    )

validation_results = []

# ------------------------------------------------------------------------------
# Validate every dataset
# ------------------------------------------------------------------------------

for dataset in AVAILABLE_DATASETS:

    if dataset not in SYNTHETIC_DATASETS:

        validation_results.append({

            "Dataset": dataset,
            "Rows Match": False,
            "Columns Match": False,
            "Column Order": False,
            "Data Types Match": False,
            "Missing Values": -1,
            "Duplicate Rows": -1,
            "Infinite Values": -1,
            "Empty Columns": -1,
            "Validation Score": 0,
            "Status": False

        })

        continue

    real_df = PROCESSED_DATASETS[dataset]
    synthetic_df = SYNTHETIC_DATASETS[dataset]

    # ------------------------------------------------------------------------------
    # Structure Validation
    # ------------------------------------------------------------------------------

    rows_match = len(real_df) == len(synthetic_df)

    columns_match = (
        set(real_df.columns) ==
        set(synthetic_df.columns)
    )

    column_order = (
        list(real_df.columns) ==
        list(synthetic_df.columns)
    )

    dtype_match = (
        real_df.dtypes.astype(str).tolist() ==
        synthetic_df.dtypes.astype(str).tolist()
    )

    # ------------------------------------------------------------------------------
    # Data Quality Validation
    # ------------------------------------------------------------------------------

    missing_values = int(
        synthetic_df.isna().sum().sum()
    )

    duplicate_rows = int(
        synthetic_df.duplicated().sum()
    )

    numeric_df = synthetic_df.select_dtypes(
        include=np.number
    )

    infinite_values = (
        int(np.isinf(numeric_df.to_numpy()).sum())
        if not numeric_df.empty
        else 0
    )

    empty_columns = int(
        synthetic_df.isna().all().sum()
    )

    # ------------------------------------------------------------------------------
    # Validation Score
    # ------------------------------------------------------------------------------

    checks = [

        rows_match,
        columns_match,
        column_order,
        dtype_match,
        missing_values == 0,
        infinite_values == 0,
        empty_columns == 0

    ]

    score = round(
        100 * sum(checks) / len(checks),
        2
    )

    status = all(checks)

    validation_results.append({

        "Dataset": dataset,

        "Rows Match": rows_match,

        "Columns Match": columns_match,

        "Column Order": column_order,

        "Data Types Match": dtype_match,

        "Missing Values": missing_values,

        "Duplicate Rows": duplicate_rows,

        "Infinite Values": infinite_values,

        "Empty Columns": empty_columns,

        "Validation Score": score,

        "Status": status

    })

# ------------------------------------------------------------------------------
# Results
# ------------------------------------------------------------------------------

VALIDATION_DF = pd.DataFrame(
    validation_results
)

VALIDATION_DF["Result"] = VALIDATION_DF["Status"].map(
    lambda x: "PASS" if x else "FAIL"
)

display(VALIDATION_DF)

# ------------------------------------------------------------------------------
# Save Report
# ------------------------------------------------------------------------------

os.makedirs(
    REPORT_DIR,
    exist_ok=True
)

VALIDATION_REPORT = os.path.join(
    REPORT_DIR,
    "tvae_synthetic_dataset_validation.csv"
)

VALIDATION_DF.to_csv(
    VALIDATION_REPORT,
    index=False
)

# ------------------------------------------------------------------------------
# Summary
# ------------------------------------------------------------------------------

print("\n" + "=" * 100)
print("VALIDATION SUMMARY")
print("=" * 100)

passed = int(
    VALIDATION_DF["Status"].sum()
)

total = len(
    VALIDATION_DF
)

print(f"Datasets Validated : {total}")
print(f"Passed             : {passed}")
print(f"Failed             : {total - passed}")
print(f"Success Rate       : {(passed / total) * 100:.2f}%")

if passed == total:

    print("\n✓ All TVAE synthetic datasets passed validation.")

else:

    print("\nFailed Datasets:")

    for dataset in VALIDATION_DF.loc[
        ~VALIDATION_DF["Status"],
        "Dataset"
    ]:
        print(f"  • {dataset}")

print("\nValidation report saved:")
print(VALIDATION_REPORT)

====================================================================================================
PART 5.7.1 — GENERATE SYNTHETIC DATA
====================================================================================================

====================================================================================================
Generating Synthetic Data : adult_income
====================================================================================================
Rows to Generate : 32510
✓ Synthetic Dataset Generated
Shape : (32510, 15)

====================================================================================================
Generating Synthetic Data : bank_marketing
====================================================================================================
Rows to Generate : 45211
✓ Synthetic Dataset Generated
Shape : (45211, 17)

====================================================================================================
Generating Synthetic Data : breast_cancer
====================================================================================================
Rows to Generate : 569
✓ Synthetic Dataset Generated
Shape : (569, 32)

In [ ]:
# ==============================================================================
# PART H4 - SAVE SYNTHETIC DATASETS
# ==============================================================================

import os
import pandas as pd

print("=" * 100)
print("PART H4 - SAVE SYNTHETIC DATASETS")
print("=" * 100)


required_objects = [

    "SYNTHETIC_DATASETS",
    "CTGAN_SYNTHETIC_DIR"

]


missing = [

    obj
    for obj in required_objects
    if obj not in globals()

]


if missing:

    raise RuntimeError(
        f"Missing required objects:\n{missing}"
    )


os.makedirs(

    CTGAN_SYNTHETIC_DIR,

    exist_ok=True

)


SYNTHETIC_DATASET_PATHS = {}

SAVE_RESULTS = []


for dataset, df in SYNTHETIC_DATASETS.items():

    save_path = os.path.join(

        CTGAN_SYNTHETIC_DIR,

        f"{dataset}_synthetic.csv"

    )


    try:

        df.to_csv(

            save_path,

            index=False

        )


        exists = os.path.exists(
            save_path
        )


        size_mb = round(

            os.path.getsize(save_path)
            /
            (1024 ** 2),

            2

        )


        SYNTHETIC_DATASET_PATHS[dataset] = save_path


        status = "PASS"

        error = ""


    except Exception as e:


        exists = False

        size_mb = 0

        status = "FAIL"

        error = str(e)


    SAVE_RESULTS.append({

        "Dataset": dataset,

        "Rows": len(df),

        "Columns": df.shape[1],

        "File Size (MB)": size_mb,

        "Saved": exists,

        "Result": status,

        "Path": save_path,

        "Error": error

    })


SAVED_SYNTHETIC_DF = pd.DataFrame(
    SAVE_RESULTS
)


display(SAVED_SYNTHETIC_DF)


print("\n" + "=" * 100)
print("SAVE SUMMARY")
print("=" * 100)


total = len(SAVED_SYNTHETIC_DF)

saved = int(
    SAVED_SYNTHETIC_DF["Saved"].sum()
)


print(f"Datasets Processed : {total}")
print(f"Datasets Saved     : {saved}")
print(f"Failed Saves       : {total - saved}")


if saved == total:

    print("\n✓ All synthetic datasets saved successfully.")

else:

    raise RuntimeError(
        "Some synthetic datasets failed to save."
    )

====================================================================================================
SAVING SYNTHETIC DATASETS
====================================================================================================
✓ Saved : adult_income
✓ Saved : bank_marketing
✓ Saved : breast_cancer

In [ ]:
# ==============================================================================
# PART H5 — VERIFICATION
# ==============================================================================

import os
import pandas as pd

print("=" * 100)
print("PART H5 — TVAE VERIFICATION")
print("=" * 100)

# ------------------------------------------------------------------------------
# Verify required objects
# ------------------------------------------------------------------------------

required_objects = [
    "AVAILABLE_DATASETS",
    "LOADED_TVAE_MODELS",
    "SYNTHETIC_DATASETS",
    "VALIDATION_DF",
    "SAVED_SYNTHETIC_DF",
    "TVAE_SYNTHETIC_DIR"
]

missing = [
    obj
    for obj in required_objects
    if obj not in globals()
]

if missing:

    raise RuntimeError(
        f"Missing required objects:\n{missing}"
    )

# ------------------------------------------------------------------------------
# Verification
# ------------------------------------------------------------------------------

verification = {

    "TVAE Models Loaded":
        len(LOADED_TVAE_MODELS) == len(AVAILABLE_DATASETS),

    "Synthetic Datasets Generated":
        len(SYNTHETIC_DATASETS) == len(AVAILABLE_DATASETS),

    "Synthetic Dataset Validation Completed":
        len(VALIDATION_DF) == len(AVAILABLE_DATASETS),

    "Validation Passed":
        VALIDATION_DF["Status"].all(),

    "Synthetic Datasets Saved":
        SAVED_SYNTHETIC_DF["Saved"].all(),

    "TVAE Synthetic Directory Exists":
        os.path.exists(TVAE_SYNTHETIC_DIR)

}

VERIFY_DF = pd.DataFrame({

    "Component":
        verification.keys(),

    "Status":
        verification.values()

})

VERIFY_DF["Result"] = VERIFY_DF["Status"].map(
    lambda x:
        "PASS" if x else "FAIL"
)

display(VERIFY_DF)

# ------------------------------------------------------------------------------
# Summary
# ------------------------------------------------------------------------------

print("\n" + "=" * 100)
print("PART H5 TVAE VERIFICATION SUMMARY")
print("=" * 100)

passed = int(
    VERIFY_DF["Status"].sum()
)

total = len(
    VERIFY_DF
)

print(f"Checks Passed : {passed}/{total}")
print(f"Success Rate  : {(passed / total) * 100:.2f}%")

if passed == total:

    print("\n✓ Part H completed successfully.")
    print("✓ TVAE models loaded.")
    print("✓ Synthetic datasets generated.")
    print("✓ Synthetic datasets validated.")
    print("✓ Synthetic datasets saved.")
    print("✓ Ready for Notebook I - Evaluation.")

else:

    print("\nFailed Components:")

    for component in VERIFY_DF.loc[
        ~VERIFY_DF["Status"],
        "Component"
    ]:

        print(f"  • {component}")

    raise RuntimeError(
        "TVAE Part H verification failed."
    )

          Dataset  Real Rows  Synthetic Rows  Columns
0    adult_income      32510           32510       15
1  bank_marketing      45211           45211       17
2   breast_cancer        569             569       32

Summary Saved To:
/content/drive/MyDrive/SPP_GAN_Project/reports/TVAE/tvae_synthetic_dataset_summary.csv

In [ ]:
# ==============================================================================
# PART I1 — LOAD REAL & SYNTHETIC DATASETS
# ==============================================================================

import os
import pandas as pd

print("=" * 100)
print("PART I1 — LOAD REAL & TVAE SYNTHETIC DATASETS")
print("=" * 100)

# ------------------------------------------------------------------------------
# Verify required objects
# ------------------------------------------------------------------------------

required_objects = [
    "PATHS",
    "CONFIG"
]

missing = [
    obj
    for obj in required_objects
    if obj not in globals()
]

if missing:

    raise RuntimeError(
        f"Missing required objects:\n{missing}"
    )

# ------------------------------------------------------------------------------
# Dataset containers
# ------------------------------------------------------------------------------

REAL_DATASETS = {}
SYNTHETIC_DATASETS = {}

# ------------------------------------------------------------------------------
# Directories
# ------------------------------------------------------------------------------

REAL_DATA_DIR = PATHS["processed_data"]

TVAE_SYNTHETIC_DIR = os.path.join(
    PATHS["datasets"],
    "synthetic",
    "TVAE"
)

if not os.path.isdir(REAL_DATA_DIR):

    raise FileNotFoundError(
        REAL_DATA_DIR
    )

if not os.path.isdir(TVAE_SYNTHETIC_DIR):

    raise FileNotFoundError(
        TVAE_SYNTHETIC_DIR
    )

# ------------------------------------------------------------------------------
# Dataset list
# ------------------------------------------------------------------------------

DATASETS = list(
    CONFIG["datasets"].keys()
)

summary = []

# ------------------------------------------------------------------------------
# Load datasets
# ------------------------------------------------------------------------------

for dataset in DATASETS:

    real_path = os.path.join(
        REAL_DATA_DIR,
        f"{dataset}_processed.csv"
    )

    synthetic_path = os.path.join(
        TVAE_SYNTHETIC_DIR,
        f"{dataset}_synthetic.csv"
    )

    if not os.path.exists(real_path):

        raise FileNotFoundError(
            real_path
        )

    if not os.path.exists(synthetic_path):

        raise FileNotFoundError(
            synthetic_path
        )

    real_df = pd.read_csv(
        real_path
    )

    synthetic_df = pd.read_csv(
        synthetic_path
    )

    REAL_DATASETS[dataset] = real_df

    SYNTHETIC_DATASETS[dataset] = synthetic_df

    columns_match = (
        list(real_df.columns)
        ==
        list(synthetic_df.columns)
    )

    dtypes_match = (
        real_df.dtypes.astype(str).tolist()
        ==
        synthetic_df.dtypes.astype(str).tolist()
    )

    rows_match = (
        len(real_df)
        ==
        len(synthetic_df)
    )

    summary.append({

        "Dataset": dataset,

        "Real Shape": real_df.shape,

        "Synthetic Shape": synthetic_df.shape,

        "Rows Match": rows_match,

        "Columns Match": columns_match,

        "Data Types Match": dtypes_match,

        "Real Missing":
            int(real_df.isna().sum().sum()),

        "Synthetic Missing":
            int(synthetic_df.isna().sum().sum()),

        "Real Size (MB)":
            round(
                os.path.getsize(real_path) / (1024 ** 2),
                2
            ),

        "Synthetic Size (MB)":
            round(
                os.path.getsize(synthetic_path) / (1024 ** 2),
                2
            )

    })

# ------------------------------------------------------------------------------
# Summary
# ------------------------------------------------------------------------------

DATASET_LOAD_DF = pd.DataFrame(
    summary
)

DATASET_LOAD_DF["Result"] = (
    DATASET_LOAD_DF["Rows Match"]
    &
    DATASET_LOAD_DF["Columns Match"]
    &
    DATASET_LOAD_DF["Data Types Match"]
).map({

    True: "PASS",

    False: "FAIL"

})

display(
    DATASET_LOAD_DF
)

print("\n" + "=" * 100)
print("TVAE DATASET LOADING SUMMARY")
print("=" * 100)

passed = (
    DATASET_LOAD_DF["Result"] == "PASS"
).sum()

total = len(
    DATASET_LOAD_DF
)

print(f"Datasets Loaded : {total}")
print(f"Passed          : {passed}")
print(f"Failed          : {total - passed}")
print(f"Success Rate    : {(passed / total) * 100:.2f}%")

print("\n✓ Real and TVAE synthetic datasets loaded successfully.")

====================================================================================================
PART 5.8.4 — FINAL VERIFICATION
====================================================================================================

          Dataset  Model  Synthetic Dataset Result
0    adult_income   True               True   PASS
1  bank_marketing   True               True   PASS
2   breast_cancer   True               True   PASS

✓ PART 5.8 COMPLETED SUCCESSFULLY

In [ ]:
# ==============================================================================
# PART I2 — TVAE SCHEMA CONSISTENCY
# ==============================================================================

print("=" * 100)
print("PART I2 — TVAE SCHEMA CONSISTENCY")
print("=" * 100)

# ------------------------------------------------------------------------------
# Verify required objects
# ------------------------------------------------------------------------------

required_objects = [
    "REAL_DATASETS",
    "SYNTHETIC_DATASETS",
    "DATASETS"
]

missing = [
    obj
    for obj in required_objects
    if obj not in globals()
]

if missing:

    raise RuntimeError(
        "Missing required objects:\n"
        f"{missing}\n\n"
        "Please execute Part I1 first."
    )

# ------------------------------------------------------------------------------
# Schema Validation
# ------------------------------------------------------------------------------

schema_results = []

for dataset in DATASETS:

    real_df = REAL_DATASETS[dataset]

    synthetic_df = SYNTHETIC_DATASETS[dataset]

    rows_match = (
        len(real_df)
        ==
        len(synthetic_df)
    )

    column_count_match = (
        real_df.shape[1]
        ==
        synthetic_df.shape[1]
    )

    column_name_match = (
        list(real_df.columns)
        ==
        list(synthetic_df.columns)
    )

    dtype_match = (
        real_df.dtypes.astype(str).tolist()
        ==
        synthetic_df.dtypes.astype(str).tolist()
    )

    schema_results.append({

        "Dataset": dataset,

        "Rows Match": rows_match,

        "Column Count Match": column_count_match,

        "Column Names Match": column_name_match,

        "Data Types Match": dtype_match

    })

# ------------------------------------------------------------------------------
# Results
# ------------------------------------------------------------------------------

SCHEMA_DF = pd.DataFrame(
    schema_results
)

SCHEMA_DF["Result"] = (
    SCHEMA_DF["Rows Match"]
    &
    SCHEMA_DF["Column Count Match"]
    &
    SCHEMA_DF["Column Names Match"]
    &
    SCHEMA_DF["Data Types Match"]
).map({

    True: "PASS",

    False: "FAIL"

})

display(
    SCHEMA_DF
)

# ------------------------------------------------------------------------------
# Summary
# ------------------------------------------------------------------------------

print("\n" + "=" * 100)
print("TVAE SCHEMA VALIDATION SUMMARY")
print("=" * 100)

passed = (
    SCHEMA_DF["Result"] == "PASS"
).sum()

total = len(
    SCHEMA_DF
)

print(f"Datasets Checked : {total}")
print(f"Passed           : {passed}")
print(f"Failed           : {total - passed}")

if passed == total:

    print("\n✓ All TVAE synthetic datasets passed schema validation.")

else:

    failed = SCHEMA_DF.loc[
        SCHEMA_DF["Result"] == "FAIL",
        "Dataset"
    ].tolist()

    print("\nFailed Datasets:")

    for dataset in failed:

        print(f"  • {dataset}")

====================================================================================================
VERIFY TRAINED TVAE MODELS
====================================================================================================

          Dataset  Exists
0    adult_income    True
1  bank_marketing    True
2   breast_cancer    True

In [ ]:
# ==============================================================================
# PART I3 — FEATURE TYPE SUMMARY
# ==============================================================================

print("=" * 100)
print("PART I3 — FEATURE TYPE SUMMARY")
print("=" * 100)

# ------------------------------------------------------------------------------
# Verify required objects
# ------------------------------------------------------------------------------

required_objects = [
    "REAL_DATASETS",
    "SYNTHETIC_DATASETS",
    "DATASETS"
]

missing = [
    obj for obj in required_objects
    if obj not in globals()
]

if missing:
    raise RuntimeError(
        f"Missing required objects:\n{missing}\n\n"
        "Please execute Part I1 first."
    )

# ------------------------------------------------------------------------------
# Feature Summary
# ------------------------------------------------------------------------------

feature_rows = []

for dataset in DATASETS:

    real_df = REAL_DATASETS[dataset]
    synthetic_df = SYNTHETIC_DATASETS[dataset]

    real_numeric_columns = (
        real_df
        .select_dtypes(include=np.number)
        .columns
        .tolist()
    )

    real_categorical_columns = (
        real_df
        .select_dtypes(exclude=np.number)
        .columns
        .tolist()
    )

    synthetic_numeric_columns = (
        synthetic_df
        .select_dtypes(include=np.number)
        .columns
        .tolist()
    )

    synthetic_categorical_columns = (
        synthetic_df
        .select_dtypes(exclude=np.number)
        .columns
        .tolist()
    )

    feature_rows.append({

        "Dataset": dataset,

        "Total Features":
            real_df.shape[1],

        "Synthetic Features":
            synthetic_df.shape[1],

        "Real Numerical":
            len(real_numeric_columns),

        "Synthetic Numerical":
            len(synthetic_numeric_columns),

        "Real Categorical":
            len(real_categorical_columns),

        "Synthetic Categorical":
            len(synthetic_categorical_columns),

        "Feature Types Match":
            (
                len(real_numeric_columns)
                ==
                len(synthetic_numeric_columns)
                and
                len(real_categorical_columns)
                ==
                len(synthetic_categorical_columns)
            )

    })

# ------------------------------------------------------------------------------
# Results
# ------------------------------------------------------------------------------

FEATURE_DF = pd.DataFrame(feature_rows)

FEATURE_DF["Result"] = FEATURE_DF[
    "Feature Types Match"
].map({

    True: "PASS",
    False: "FAIL"

})

display(FEATURE_DF)

# ------------------------------------------------------------------------------
# Summary
# ------------------------------------------------------------------------------

print("\n" + "=" * 100)
print("FEATURE TYPE SUMMARY")
print("=" * 100)

passed = (
    FEATURE_DF["Result"] == "PASS"
).sum()

total = len(FEATURE_DF)

print(f"Datasets Checked : {total}")
print(f"Passed           : {passed}")
print(f"Failed           : {total - passed}")
print(f"Success Rate     : {(passed / total) * 100:.2f}%")

if passed == total:

    print("\n✓ All datasets passed feature type validation.")

else:

    print("\nFailed Datasets:")

    failed = FEATURE_DF.loc[
        FEATURE_DF["Result"] == "FAIL",
        "Dataset"
    ].tolist()

    for dataset in failed:
        print(f"  • {dataset}")

====================================================================================================
VERIFY SYNTHETIC DATASETS
====================================================================================================

          Dataset   Rows  Columns  Exists
0    adult_income  32510       15    True
1  bank_marketing  45211       17    True
2   breast_cancer    569       32    True

In [ ]:
# ==============================================================================
# PART I4 — SAVE DATASET SUMMARY
# ==============================================================================

print("=" * 100)
print("PART I4 — SAVE DATASET SUMMARY")
print("=" * 100)

# ------------------------------------------------------------------------------
# Verify required objects
# ------------------------------------------------------------------------------

required_objects = {
    "DATASET_LOAD_DF": "Run Part I1 first.",
    "SCHEMA_DF": "Run Part I2 first.",
    "FEATURE_DF": "Run Part I3 first."
}

missing = [
    f"{obj} ({msg})"
    for obj, msg in required_objects.items()
    if obj not in globals()
]

if missing:
    raise RuntimeError(
        "Required objects are missing:\n\n"
        + "\n".join(missing)
    )

# ------------------------------------------------------------------------------
# Create Report Directory
# ------------------------------------------------------------------------------

REPORT_DIR = os.path.join(
    PATHS["reports"],
    "TVAE_Evaluation"
)

os.makedirs(
    REPORT_DIR,
    exist_ok=True
)

# ------------------------------------------------------------------------------
# Output Files
# ------------------------------------------------------------------------------

DATASET_SUMMARY_FILE = os.path.join(
    REPORT_DIR,
    "dataset_summary.csv"
)

SCHEMA_FILE = os.path.join(
    REPORT_DIR,
    "schema_validation.csv"
)

FEATURE_FILE = os.path.join(
    REPORT_DIR,
    "feature_summary.csv"
)

# ------------------------------------------------------------------------------
# Save Reports
# ------------------------------------------------------------------------------

DATASET_LOAD_DF.to_csv(
    DATASET_SUMMARY_FILE,
    index=False
)

SCHEMA_DF.to_csv(
    SCHEMA_FILE,
    index=False
)

FEATURE_DF.to_csv(
    FEATURE_FILE,
    index=False
)

# ------------------------------------------------------------------------------
# Verification
# ------------------------------------------------------------------------------

REPORT_FILES_DF = pd.DataFrame({

    "Report": [

        "Dataset Summary",
        "Schema Validation",
        "Feature Summary"

    ],

    "File": [

        DATASET_SUMMARY_FILE,
        SCHEMA_FILE,
        FEATURE_FILE

    ]

})

REPORT_FILES_DF["Exists"] = REPORT_FILES_DF["File"].apply(
    os.path.exists
)

REPORT_FILES_DF["Result"] = REPORT_FILES_DF["Exists"].map(
    lambda x: "PASS" if x else "FAIL"
)

display(REPORT_FILES_DF)

# ------------------------------------------------------------------------------
# Summary
# ------------------------------------------------------------------------------

print("\n" + "=" * 100)
print("REPORT SUMMARY")
print("=" * 100)

passed = int(
    REPORT_FILES_DF["Exists"].sum()
)

total = len(REPORT_FILES_DF)

print(f"Reports Saved : {passed}/{total}")
print(f"Report Folder : {REPORT_DIR}")

print()

for _, row in REPORT_FILES_DF.iterrows():

    print(
        f"{row['Report']:<20} : {row['Result']}"
    )

if REPORT_FILES_DF["Exists"].all():

    print("\n✓ Dataset summary saved successfully.")
    print("✓ Schema validation saved successfully.")
    print("✓ Feature summary saved successfully.")
    print("✓ All TVAE evaluation reports saved successfully.")

else:

    failed_reports = REPORT_FILES_DF.loc[
        ~REPORT_FILES_DF["Exists"],
        "Report"
    ].tolist()

    print("\nFailed Reports:")

    for report in failed_reports:
        print(f"  • {report}")

    raise RuntimeError(
        "One or more evaluation reports could not be saved."
    )

====================================================================================================
VERIFY METADATA
====================================================================================================

          Dataset  Metadata
0    adult_income      True
1  bank_marketing      True
2   breast_cancer      True

In [ ]:
# ==============================================================================
# PART I5 — VERIFICATION
# ==============================================================================

print("=" * 100)
print("PART I5 — VERIFICATION")
print("=" * 100)

# ------------------------------------------------------------------------------
# Verify required objects
# ------------------------------------------------------------------------------

required_objects = [
    "REAL_DATASETS",
    "SYNTHETIC_DATASETS",
    "DATASET_LOAD_DF",
    "SCHEMA_DF",
    "FEATURE_DF"
]

missing = [
    obj for obj in required_objects
    if obj not in globals()
]

if missing:
    raise RuntimeError(
        "Missing required objects:\n"
        f"{missing}"
    )

# ------------------------------------------------------------------------------
# Verification
# ------------------------------------------------------------------------------

verification = {

    "Real Datasets Loaded":
        len(REAL_DATASETS) == len(DATASETS),

    "Synthetic TVAE Datasets Loaded":
        len(SYNTHETIC_DATASETS) == len(DATASETS),

    "Dataset Loading Summary":
        len(DATASET_LOAD_DF) == len(DATASETS),

    "Schema Validation":
        SCHEMA_DF["Result"].eq("PASS").all(),

    "Feature Summary":
        FEATURE_DF["Result"].eq("PASS").all(),

    "Dataset Summary Report":
        os.path.exists(DATASET_SUMMARY_FILE),

    "Schema Validation Report":
        os.path.exists(SCHEMA_FILE),

    "Feature Summary Report":
        os.path.exists(FEATURE_FILE)

}

VERIFY_DF = pd.DataFrame({

    "Component": verification.keys(),

    "Status": verification.values()

})

VERIFY_DF["Result"] = VERIFY_DF["Status"].map(
    lambda x: "PASS" if x else "FAIL"
)

display(VERIFY_DF)

# ------------------------------------------------------------------------------
# Summary
# ------------------------------------------------------------------------------

print("\n" + "=" * 100)
print("PART I VERIFICATION SUMMARY")
print("=" * 100)

passed = int(
    VERIFY_DF["Status"].sum()
)

total = len(VERIFY_DF)

print(f"Checks Passed : {passed}/{total}")
print(f"Success Rate  : {(passed / total) * 100:.2f}%")

if VERIFY_DF["Status"].all():

    print("\n" + "=" * 100)
    print("✓ PART I COMPLETED SUCCESSFULLY")
    print("✓ Real datasets loaded.")
    print("✓ TVAE synthetic datasets loaded.")
    print("✓ Schema validation completed.")
    print("✓ Feature type validation completed.")
    print("✓ TVAE evaluation reports saved.")
    print("✓ Ready for Part J — Statistical Similarity Evaluation")
    print("=" * 100)

else:

    print("\nFailed Components:")

    failed = VERIFY_DF.loc[
        ~VERIFY_DF["Status"],
        "Component"
    ].tolist()

    for component in failed:
        print(f"  • {component}")

    raise RuntimeError(
        "Part I verification failed."
    )

====================================================================================================
TVAE TRAINING SUMMARY
====================================================================================================

          Dataset  Processed Dataset  Metadata  TVAE Model  Synthetic Dataset  PASS
0    adult_income               True      True        True               True  True
1  bank_marketing               True      True        True               True  True
2   breast_cancer               True      True        True               True  True

In [ ]:
# ==============================================================================
# PART I6 — DATASET STRUCTURE EVALUATION
# ==============================================================================

print("=" * 100)
print("PART I6 — DATASET STRUCTURE EVALUATION")
print("=" * 100)

# ------------------------------------------------------------------------------
# Verify required objects
# ------------------------------------------------------------------------------

required_objects = [
    "REAL_DATASETS",
    "SYNTHETIC_DATASETS",
    "DATASETS",
    "CONFIG"
]

missing = [
    obj for obj in required_objects
    if obj not in globals()
]

if missing:
    raise RuntimeError(
        "Missing required objects:\n"
        f"{missing}\n\n"
        "Please execute Parts I1-I5 first."
    )

# ------------------------------------------------------------------------------
# Dataset Structure Evaluation
# ------------------------------------------------------------------------------

STRUCTURE_RESULTS = []

for dataset in DATASETS:

    real_df = REAL_DATASETS[dataset]
    synthetic_df = SYNTHETIC_DATASETS[dataset]

    target_column = CONFIG["datasets"][dataset]["target"]

    # --------------------------------------------------------------------------
    # Structural Checks
    # --------------------------------------------------------------------------

    rows_match = (
        len(real_df) == len(synthetic_df)
    )

    columns_match = (
        real_df.shape[1] == synthetic_df.shape[1]
    )

    column_order_match = (
        list(real_df.columns) ==
        list(synthetic_df.columns)
    )

    column_names_match = (
        set(real_df.columns) ==
        set(synthetic_df.columns)
    )

    dtype_match = (
        real_df.dtypes.astype(str).tolist()
        ==
        synthetic_df.dtypes.astype(str).tolist()
    )

    # --------------------------------------------------------------------------
    # Feature Type Checks
    # --------------------------------------------------------------------------

    real_numeric = len(
        real_df.select_dtypes(include=np.number).columns
    )

    synthetic_numeric = len(
        synthetic_df.select_dtypes(include=np.number).columns
    )

    real_categorical = len(
        real_df.select_dtypes(exclude=np.number).columns
    )

    synthetic_categorical = len(
        synthetic_df.select_dtypes(exclude=np.number).columns
    )

    numeric_features_match = (
        real_numeric == synthetic_numeric
    )

    categorical_features_match = (
        real_categorical == synthetic_categorical
    )

    # --------------------------------------------------------------------------
    # Target Check
    # --------------------------------------------------------------------------

    target_exists = (
        target_column in synthetic_df.columns
    )

    # --------------------------------------------------------------------------
    # Memory Usage
    # --------------------------------------------------------------------------

    real_memory = round(
        real_df.memory_usage(deep=True).sum() / 1024**2,
        2
    )

    synthetic_memory = round(
        synthetic_df.memory_usage(deep=True).sum() / 1024**2,
        2
    )

    # --------------------------------------------------------------------------
    # Store Results
    # --------------------------------------------------------------------------

    STRUCTURE_RESULTS.append({

        "Dataset": dataset,

        "Rows Match": rows_match,

        "Columns Match": columns_match,

        "Column Order Match": column_order_match,

        "Column Names Match": column_names_match,

        "Data Types Match": dtype_match,

        "Numeric Features Match":
            numeric_features_match,

        "Categorical Features Match":
            categorical_features_match,

        "Target Exists":
            target_exists,

        "Real Numeric Features":
            real_numeric,

        "Synthetic Numeric Features":
            synthetic_numeric,

        "Real Categorical Features":
            real_categorical,

        "Synthetic Categorical Features":
            synthetic_categorical,

        "Real Memory (MB)":
            real_memory,

        "Synthetic Memory (MB)":
            synthetic_memory

    })

# ------------------------------------------------------------------------------
# Create Dataset Structure DataFrame
# ------------------------------------------------------------------------------

DATASET_STRUCTURE_DF = pd.DataFrame(
    STRUCTURE_RESULTS
)

# ------------------------------------------------------------------------------
# Overall Structure Result
# ------------------------------------------------------------------------------

DATASET_STRUCTURE_DF["Result"] = (

    DATASET_STRUCTURE_DF["Rows Match"] &
    DATASET_STRUCTURE_DF["Columns Match"] &
    DATASET_STRUCTURE_DF["Column Order Match"] &
    DATASET_STRUCTURE_DF["Column Names Match"] &
    DATASET_STRUCTURE_DF["Data Types Match"] &
    DATASET_STRUCTURE_DF["Numeric Features Match"] &
    DATASET_STRUCTURE_DF["Categorical Features Match"] &
    DATASET_STRUCTURE_DF["Target Exists"]

).map({

    True: "PASS",
    False: "FAIL"

})

display(DATASET_STRUCTURE_DF)

# ------------------------------------------------------------------------------
# Summary
# ------------------------------------------------------------------------------

print("\n" + "=" * 100)
print("TVAE DATASET STRUCTURE SUMMARY")
print("=" * 100)

passed = (
    DATASET_STRUCTURE_DF["Result"] == "PASS"
).sum()

total = len(DATASET_STRUCTURE_DF)

print(f"Datasets Checked : {total}")
print(f"Passed           : {passed}")
print(f"Failed           : {total - passed}")

if passed == total:

    print("\n✓ TVAE dataset structure validation completed successfully.")

else:

    print("\n⚠ Structure mismatch detected.")

    failed = DATASET_STRUCTURE_DF.loc[
        DATASET_STRUCTURE_DF["Result"] == "FAIL",
        "Dataset"
    ].tolist()

    print("\nFailed Datasets:")

    for dataset in failed:
        print(f"  • {dataset}")

====================================================================================================
FINAL NOTEBOOK VERIFICATION
====================================================================================================

        Component  Status Result
0  Processed Data    True   PASS
1        Metadata    True   PASS
2     TVAE Models    True   PASS
3  Synthetic Data    True   PASS

====================================================================================================
✓ NOTEBOOK 05 COMPLETED SUCCESSFULLY
====================================================================================================

In [ ]:
# ==============================================================================
# PART I7 — TARGET STRUCTURE EVALUATION
# ==============================================================================

print("=" * 100)
print("PART I7 — TARGET STRUCTURE EVALUATION")
print("=" * 100)

# ------------------------------------------------------------------------------
# Verify required objects
# ------------------------------------------------------------------------------

required_objects = [
    "REAL_DATASETS",
    "SYNTHETIC_DATASETS",
    "DATASETS",
    "TARGET_COLUMNS"
]

missing = [
    obj for obj in required_objects
    if obj not in globals()
]

if missing:
    raise RuntimeError(
        "Missing required objects:\n"
        f"{missing}\n\n"
        "Please execute Parts I1-I6 first."
    )

# ------------------------------------------------------------------------------
# Target Structure Evaluation
# ------------------------------------------------------------------------------

TARGET_STRUCTURE_RESULTS = []

for dataset in DATASETS:

    real_df = REAL_DATASETS[dataset]
    synthetic_df = SYNTHETIC_DATASETS[dataset]

    target_col = TARGET_COLUMNS[dataset]

    real_target = real_df[target_col]
    synthetic_target = synthetic_df[target_col]

    target_exists = (
        target_col in synthetic_df.columns
    )

    dtype_match = (
        real_target.dtype ==
        synthetic_target.dtype
    )

    class_count_match = (
        real_target.nunique()
        ==
        synthetic_target.nunique()
    )

    class_labels_match = (
        set(real_target.unique())
        ==
        set(synthetic_target.unique())
    )

    TARGET_STRUCTURE_RESULTS.append({

        "Dataset": dataset,

        "Target Column": target_col,

        "Target Exists":
            target_exists,

        "Data Type Match":
            dtype_match,

        "Class Count Match":
            class_count_match,

        "Class Labels Match":
            class_labels_match

    })

# ------------------------------------------------------------------------------
# Results
# ------------------------------------------------------------------------------

TARGET_STRUCTURE_DF = pd.DataFrame(
    TARGET_STRUCTURE_RESULTS
)

TARGET_STRUCTURE_DF["Result"] = (

    TARGET_STRUCTURE_DF["Target Exists"] &
    TARGET_STRUCTURE_DF["Data Type Match"] &
    TARGET_STRUCTURE_DF["Class Count Match"] &
    TARGET_STRUCTURE_DF["Class Labels Match"]

).map({

    True: "PASS",
    False: "FAIL"

})

display(TARGET_STRUCTURE_DF)

# ------------------------------------------------------------------------------
# Summary
# ------------------------------------------------------------------------------

print("\n" + "=" * 100)
print("TVAE TARGET STRUCTURE SUMMARY")
print("=" * 100)

passed = (
    TARGET_STRUCTURE_DF["Result"] == "PASS"
).sum()

total = len(TARGET_STRUCTURE_DF)

print(f"Datasets Checked : {total}")
print(f"Passed           : {passed}")
print(f"Failed           : {total - passed}")
print(f"Success Rate     : {(passed / total) * 100:.2f}%")

if passed == total:

    print("\n✓ TVAE target structure validation completed successfully.")

else:

    print("\n⚠ Target structure mismatch detected.")

    failed = TARGET_STRUCTURE_DF.loc[
        TARGET_STRUCTURE_DF["Result"] == "FAIL",
        "Dataset"
    ].tolist()

    print("\nFailed Datasets:")

    for dataset in failed:
        print(f"  • {dataset}")

In [ ]:
# ==============================================================================
# PART I8 — STRUCTURAL CONSISTENCY SCORE
# ==============================================================================

print("=" * 100)
print("PART I8 — STRUCTURAL CONSISTENCY SCORE")
print("=" * 100)

# ------------------------------------------------------------------------------
# Verify required objects
# ------------------------------------------------------------------------------

required_objects = [
    "SCHEMA_DF",
    "FEATURE_DF",
    "TARGET_STRUCTURE_DF",
    "DATASETS"
]

missing = [
    obj
    for obj in required_objects
    if obj not in globals()
]

if missing:

    raise RuntimeError(
        "Missing required objects:\n"
        f"{missing}\n\n"
        "Please execute Parts I2, I3 and I7 first."
    )

# ------------------------------------------------------------------------------
# Calculate Structural Consistency Score
# ------------------------------------------------------------------------------

STRUCTURAL_RESULTS = []

for dataset in DATASETS:

    schema_row = SCHEMA_DF[
        SCHEMA_DF["Dataset"] == dataset
    ].iloc[0]

    feature_row = FEATURE_DF[
        FEATURE_DF["Dataset"] == dataset
    ].iloc[0]

    target_row = TARGET_STRUCTURE_DF[
        TARGET_STRUCTURE_DF["Dataset"] == dataset
    ].iloc[0]

    checks = {

        "Rows Match":
            bool(schema_row["Rows Match"]),

        "Column Count Match":
            bool(schema_row["Column Count Match"]),

        "Column Names Match":
            bool(schema_row["Column Names Match"]),

        "Data Types Match":
            bool(schema_row["Data Types Match"]),

        "Feature Types Match":
            bool(feature_row["Feature Types Match"]),

        "Target Exists":
            bool(target_row["Target Exists"]),

        "Target Data Type Match":
            bool(target_row["Data Type Match"]),

        "Target Class Count Match":
            bool(target_row["Class Count Match"]),

        "Target Class Labels Match":
            bool(target_row["Class Labels Match"])

    }

    score = round(
        (sum(checks.values()) / len(checks)) * 100,
        2
    )

    STRUCTURAL_RESULTS.append({

        "Dataset": dataset,

        **checks,

        "Structural Consistency Score (%)": score,

        "Result":
            "PASS"
            if score == 100
            else "FAIL"

    })

# ------------------------------------------------------------------------------
# Create Result DataFrame
# ------------------------------------------------------------------------------

STRUCTURAL_CONSISTENCY_DF = pd.DataFrame(
    STRUCTURAL_RESULTS
)

display(
    STRUCTURAL_CONSISTENCY_DF
)

# ------------------------------------------------------------------------------
# Summary
# ------------------------------------------------------------------------------

print("\n" + "=" * 100)
print("STRUCTURAL CONSISTENCY SUMMARY")
print("=" * 100)

overall_score = round(
    STRUCTURAL_CONSISTENCY_DF[
        "Structural Consistency Score (%)"
    ].mean(),
    2
)

passed = (
    STRUCTURAL_CONSISTENCY_DF["Result"] == "PASS"
).sum()

total = len(
    STRUCTURAL_CONSISTENCY_DF
)

print(
    f"Datasets Evaluated : {total}"
)

print(
    f"Passed             : {passed}"
)

print(
    f"Failed             : {total - passed}"
)

print(
    f"Overall Structural Consistency : {overall_score}%"
)

if passed == total:

    print("\n✓ All datasets achieved structural consistency.")

else:

    print("\n⚠ Structural mismatch detected.")

    failed = STRUCTURAL_CONSISTENCY_DF.loc[
        STRUCTURAL_CONSISTENCY_DF["Result"] == "FAIL",
        "Dataset"
    ].tolist()

    print("\nFailed Datasets:")

    for dataset in failed:

        print(f"  • {dataset}")

print("\n✓ Structural consistency evaluation completed successfully.")

In [ ]:
# ==============================================================================
# PART I9 — SAVE STRUCTURAL EVALUATION REPORTS
# ==============================================================================

print("=" * 100)
print("PART I9 — SAVE STRUCTURAL EVALUATION REPORTS")
print("=" * 100)

# ------------------------------------------------------------------------------
# Verify Required Objects
# ------------------------------------------------------------------------------

required_objects = [
    "DATASET_STRUCTURE_DF",
    "TARGET_STRUCTURE_DF",
    "STRUCTURAL_CONSISTENCY_DF",
    "REPORT_DIR"
]

missing = [
    obj
    for obj in required_objects
    if obj not in globals()
]

if missing:

    raise RuntimeError(
        "Missing required objects:\n"
        f"{missing}\n\n"
        "Please execute Parts I6-I8 first."
    )

# ------------------------------------------------------------------------------
# Create Report Directory
# ------------------------------------------------------------------------------

os.makedirs(
    REPORT_DIR,
    exist_ok=True
)

# ------------------------------------------------------------------------------
# Report Paths
# ------------------------------------------------------------------------------

STRUCTURE_REPORT = os.path.join(
    REPORT_DIR,
    "dataset_structure_evaluation.csv"
)

TARGET_REPORT = os.path.join(
    REPORT_DIR,
    "target_variable_structure_evaluation.csv"
)

CONSISTENCY_REPORT = os.path.join(
    REPORT_DIR,
    "dataset_structural_consistency_evaluation.csv"
)

# ------------------------------------------------------------------------------
# Save Reports
# ------------------------------------------------------------------------------

DATASET_STRUCTURE_DF.to_csv(
    STRUCTURE_REPORT,
    index=False
)

TARGET_STRUCTURE_DF.to_csv(
    TARGET_REPORT,
    index=False
)

STRUCTURAL_CONSISTENCY_DF.to_csv(
    CONSISTENCY_REPORT,
    index=False
)

# ------------------------------------------------------------------------------
# Verification
# ------------------------------------------------------------------------------

REPORT_STATUS_DF = pd.DataFrame({

    "Report": [
        "Dataset Structure Evaluation",
        "Target Variable Evaluation",
        "Structural Consistency Evaluation"
    ],

    "File": [
        STRUCTURE_REPORT,
        TARGET_REPORT,
        CONSISTENCY_REPORT
    ]

})

REPORT_STATUS_DF["Exists"] = REPORT_STATUS_DF["File"].apply(
    os.path.exists
)

REPORT_STATUS_DF["Result"] = REPORT_STATUS_DF["Exists"].map(
    {
        True: "PASS",
        False: "FAIL"
    }
)

display(
    REPORT_STATUS_DF
)

# ------------------------------------------------------------------------------
# Summary
# ------------------------------------------------------------------------------

print("\n" + "=" * 100)
print("STRUCTURAL EVALUATION REPORT SUMMARY")
print("=" * 100)

passed = int(
    REPORT_STATUS_DF["Exists"].sum()
)

total = len(
    REPORT_STATUS_DF
)

print(
    f"Reports Saved : {passed}/{total}"
)

print(
    f"Location      : {REPORT_DIR}"
)

if REPORT_STATUS_DF["Exists"].all():

    print("\n✓ Dataset structure report saved.")
    print("✓ Target variable report saved.")
    print("✓ Structural consistency report saved.")
    print("✓ PART I9 COMPLETED SUCCESSFULLY.")

else:

    print("\nFailed Reports:")

    failed = REPORT_STATUS_DF.loc[
        ~REPORT_STATUS_DF["Exists"],
        "Report"
    ].tolist()

    for report in failed:

        print(f"  • {report}")

    raise RuntimeError(
        "Structural evaluation report saving failed."
    )

In [ ]:
# ==============================================================================
# PART I10 — VERIFICATION
# ==============================================================================

print("=" * 100)
print("PART I10 — VERIFICATION")
print("=" * 100)

# ------------------------------------------------------------------------------
# Verify Required Objects
# ------------------------------------------------------------------------------

required_objects = [
    "DATASET_STRUCTURE_DF",
    "TARGET_STRUCTURE_DF",
    "STRUCTURAL_CONSISTENCY_DF",
    "STRUCTURE_REPORT",
    "TARGET_REPORT",
    "CONSISTENCY_REPORT"
]

missing = [
    obj
    for obj in required_objects
    if obj not in globals()
]

if missing:

    raise RuntimeError(
        "Missing required objects:\n"
        f"{missing}"
    )

# ------------------------------------------------------------------------------
# Verification Checks
# ------------------------------------------------------------------------------

average_score = (
    STRUCTURAL_CONSISTENCY_DF[
        "Structural Consistency Score (%)"
    ].mean()
)

verification = {

    "Dataset Structure Evaluation":
        len(DATASET_STRUCTURE_DF) == len(DATASETS),

    "Target Structure Evaluation":
        len(TARGET_STRUCTURE_DF) == len(DATASETS),

    "Structural Consistency Evaluation":
        len(STRUCTURAL_CONSISTENCY_DF) == len(DATASETS),

    "Dataset Structure Report":
        os.path.exists(STRUCTURE_REPORT),

    "Target Structure Report":
        os.path.exists(TARGET_REPORT),

    "Structural Consistency Report":
        os.path.exists(CONSISTENCY_REPORT),

    "Average Structural Consistency >= 95%":
        average_score >= 95

}

VERIFY_DF = pd.DataFrame({

    "Component": verification.keys(),

    "Status": verification.values()

})

VERIFY_DF["Result"] = VERIFY_DF["Status"].map(
    {
        True: "PASS",
        False: "FAIL"
    }
)

display(
    VERIFY_DF
)

# ------------------------------------------------------------------------------
# Summary
# ------------------------------------------------------------------------------

print("\n" + "=" * 100)
print("PART I10 VERIFICATION SUMMARY")
print("=" * 100)

passed = int(
    VERIFY_DF["Status"].sum()
)

total = len(
    VERIFY_DF
)

print(
    f"Checks Passed : {passed}/{total}"
)

print(
    f"Average Structural Consistency : {average_score:.2f}%"
)

if VERIFY_DF["Status"].all():

    print("\n" + "=" * 100)
    print("✓ PART I10 COMPLETED SUCCESSFULLY")
    print("✓ Dataset structure evaluation completed.")
    print("✓ Target variable evaluation completed.")
    print("✓ Structural consistency calculated.")
    print("✓ Evaluation reports saved.")
    print("✓ Ready for statistical similarity evaluation.")
    print("=" * 100)

else:

    print("\nFailed Components:")

    failed = VERIFY_DF.loc[
        ~VERIFY_DF["Status"],
        "Component"
    ].tolist()

    for item in failed:

        print(f"  • {item}")

    raise RuntimeError(
        "Part I10 verification failed."
    )

In [ ]:
# ==============================================================================
# PART I11 — OVERALL MISSING VALUE EVALUATION
# ==============================================================================

print("=" * 100)
print("PART I11 — OVERALL MISSING VALUE EVALUATION")
print("=" * 100)

# ------------------------------------------------------------------------------
# Verify Required Objects
# ------------------------------------------------------------------------------

required_objects = [
    "REAL_DATASETS",
    "SYNTHETIC_DATASETS",
    "DATASETS"
]

missing = [
    obj
    for obj in required_objects
    if obj not in globals()
]

if missing:

    raise RuntimeError(
        "Missing required objects:\n"
        f"{missing}"
    )

# ------------------------------------------------------------------------------
# Missing Value Evaluation
# ------------------------------------------------------------------------------

MISSING_SUMMARY = []

for dataset in DATASETS:

    real = REAL_DATASETS[dataset]

    synthetic = SYNTHETIC_DATASETS[dataset]

    real_missing = int(
        real.isna().sum().sum()
    )

    synthetic_missing = int(
        synthetic.isna().sum().sum()
    )

    total_values = (
        real.shape[0] *
        real.shape[1]
    )

    real_percent = round(
        (real_missing / total_values) * 100,
        4
    )

    synthetic_percent = round(
        (synthetic_missing / total_values) * 100,
        4
    )

    missing_difference = round(
        abs(
            synthetic_percent -
            real_percent
        ),
        4
    )

    preservation_score = round(
        max(
            0,
            100 - (missing_difference * 100)
        ),
        2
    )

    MISSING_SUMMARY.append({

        "Dataset": dataset,

        "Real Missing Values":
            real_missing,

        "Synthetic Missing Values":
            synthetic_missing,

        "Real Missing (%)":
            real_percent,

        "Synthetic Missing (%)":
            synthetic_percent,

        "Missing Difference (%)":
            missing_difference,

        "Missing Value Preservation Score (%)":
            preservation_score,

        "Result":
            "PASS"
            if missing_difference <= 1
            else "FAIL"

    })

# ------------------------------------------------------------------------------
# Results
# ------------------------------------------------------------------------------

MISSING_SUMMARY_DF = pd.DataFrame(
    MISSING_SUMMARY
)

display(
    MISSING_SUMMARY_DF
)

# ------------------------------------------------------------------------------
# Summary
# ------------------------------------------------------------------------------

print("\n" + "=" * 100)
print("MISSING VALUE SUMMARY")
print("=" * 100)

datasets_evaluated = len(
    MISSING_SUMMARY_DF
)

passed = (
    MISSING_SUMMARY_DF["Result"] == "PASS"
).sum()

average_score = round(
    MISSING_SUMMARY_DF[
        "Missing Value Preservation Score (%)"
    ].mean(),
    2
)

print(
    f"Datasets Evaluated : {datasets_evaluated}"
)

print(
    f"Passed             : {passed}"
)

print(
    f"Failed             : {datasets_evaluated - passed}"
)

print(
    f"Average Preservation Score : {average_score}%"
)

if passed == datasets_evaluated:

    print("\n✓ Missing value patterns preserved successfully.")

else:

    print("\n⚠ Missing value differences detected.")

print("\n✓ Missing value evaluation completed successfully.")

In [ ]:
# ==============================================================================
# PART I12 — COLUMN-WISE MISSING VALUE EVALUATION
# ==============================================================================

print("=" * 100)
print("PART I12 — COLUMN-WISE MISSING VALUE EVALUATION")
print("=" * 100)

# ------------------------------------------------------------------------------
# Verify Required Objects
# ------------------------------------------------------------------------------

required_objects = [
    "REAL_DATASETS",
    "SYNTHETIC_DATASETS",
    "DATASETS"
]

missing = [
    obj
    for obj in required_objects
    if obj not in globals()
]

if missing:

    raise RuntimeError(
        "Missing required objects:\n"
        f"{missing}"
    )

# ------------------------------------------------------------------------------
# Column-wise Missing Evaluation
# ------------------------------------------------------------------------------

COLUMN_MISSING = {}

COLUMN_MISSING_SUMMARY = []

for dataset in DATASETS:

    real = REAL_DATASETS[dataset]

    synthetic = SYNTHETIC_DATASETS[dataset]

    if list(real.columns) != list(synthetic.columns):

        raise ValueError(
            f"Column mismatch detected in {dataset}"
        )

    total_rows = len(real)

    report = pd.DataFrame({

        "Feature": real.columns,

        "Real Missing Values":
            real.isna().sum().values,

        "Synthetic Missing Values":
            synthetic.isna().sum().values

    })

    report["Real Missing (%)"] = round(
        (
            report["Real Missing Values"] /
            total_rows
        ) * 100,
        4
    )

    report["Synthetic Missing (%)"] = round(
        (
            report["Synthetic Missing Values"] /
            total_rows
        ) * 100,
        4
    )

    report["Missing Difference"] = round(
        abs(
            report["Synthetic Missing (%)"]
            -
            report["Real Missing (%)"]
        ),
        4
    )

    report["Preservation Score (%)"] = round(
        (
            100 -
            report["Missing Difference"] * 100
        ).clip(lower=0),
        2
    )

    report["Match"] = report[
        "Missing Difference"
    ].apply(
        lambda x:
        "PASS"
        if x <= 1
        else "DIFFERENCE"
    )

    COLUMN_MISSING[dataset] = report

    COLUMN_MISSING_SUMMARY.append({

        "Dataset": dataset,

        "Total Features":
            len(report),

        "Matched Features":
            (
                report["Match"] == "PASS"
            ).sum(),

        "Average Preservation Score (%)":
            round(
                report[
                    "Preservation Score (%)"
                ].mean(),
                2
            )

    })

    print("\n" + "=" * 80)
    print(dataset.upper())
    print("=" * 80)

    display(report)

# ------------------------------------------------------------------------------
# Summary
# ------------------------------------------------------------------------------

COLUMN_MISSING_SUMMARY_DF = pd.DataFrame(
    COLUMN_MISSING_SUMMARY
)

display(
    COLUMN_MISSING_SUMMARY_DF
)

print("\n" + "=" * 100)
print("COLUMN-WISE MISSING VALUE SUMMARY")
print("=" * 100)

print(
    f"Datasets Evaluated : {len(COLUMN_MISSING)}"
)

print(
    f"Average Preservation Score : "
    f"{COLUMN_MISSING_SUMMARY_DF['Average Preservation Score (%)'].mean():.2f}%"
)

print("\n✓ Column-wise missing value evaluation completed successfully.")

In [ ]:
# ==============================================================================
# PART I13 — MISSING VALUE COMPARISON PLOTS
# ==============================================================================

print("=" * 100)
print("PART I13 — MISSING VALUE COMPARISON PLOTS")
print("=" * 100)

# ------------------------------------------------------------------------------
# Verify Required Objects
# ------------------------------------------------------------------------------

required_objects = [
    "REAL_DATASETS",
    "SYNTHETIC_DATASETS",
    "DATASETS",
    "REPORT_DIR"
]

missing = [
    obj
    for obj in required_objects
    if obj not in globals()
]

if missing:

    raise RuntimeError(
        "Missing required objects:\n"
        f"{missing}"
    )

# ------------------------------------------------------------------------------
# Create Plot Directory
# ------------------------------------------------------------------------------

MISSING_PLOT_DIR = os.path.join(
    REPORT_DIR,
    "missing_value_plots"
)

os.makedirs(
    MISSING_PLOT_DIR,
    exist_ok=True
)

# ------------------------------------------------------------------------------
# Generate Missing Value Comparison Plots
# ------------------------------------------------------------------------------

PLOT_RESULTS = []

for dataset in DATASETS:

    real = REAL_DATASETS[dataset]

    synthetic = SYNTHETIC_DATASETS[dataset]

    comparison = pd.DataFrame({

        "Real":
            real.isna().sum(),

        "Synthetic":
            synthetic.isna().sum()

    })

    plt.figure(
        figsize=(14, 5)
    )

    x = np.arange(
        len(comparison.index)
    )

    width = 0.35

    plt.bar(
        x - width / 2,
        comparison["Real"],
        width,
        label="Real"
    )

    plt.bar(
        x + width / 2,
        comparison["Synthetic"],
        width,
        label="Synthetic"
    )

    plt.xticks(
        x,
        comparison.index,
        rotation=45,
        ha="right"
    )

    plt.title(
        f"{dataset} Missing Value Comparison"
    )

    plt.xlabel(
        "Features"
    )

    plt.ylabel(
        "Missing Values"
    )

    plt.legend()

    plt.tight_layout()

    plot_path = os.path.join(
        MISSING_PLOT_DIR,
        f"{dataset}_missing_value_comparison.png"
    )

    plt.savefig(
        plot_path,
        dpi=300,
        bbox_inches="tight"
    )

    plt.show()

    plt.close()

    PLOT_RESULTS.append({

        "Dataset": dataset,

        "Plot Path": plot_path,

        "Saved": os.path.exists(plot_path)

    })

# ------------------------------------------------------------------------------
# Plot Verification
# ------------------------------------------------------------------------------

MISSING_PLOT_DF = pd.DataFrame(
    PLOT_RESULTS
)

MISSING_PLOT_DF["Result"] = MISSING_PLOT_DF["Saved"].map(
    {
        True: "PASS",
        False: "FAIL"
    }
)

display(
    MISSING_PLOT_DF
)

# ------------------------------------------------------------------------------
# Summary
# ------------------------------------------------------------------------------

print("\n" + "=" * 100)
print("MISSING VALUE PLOT SUMMARY")
print("=" * 100)

passed = int(
    MISSING_PLOT_DF["Saved"].sum()
)

total = len(
    MISSING_PLOT_DF
)

print(
    f"Plots Generated : {passed}/{total}"
)

if MISSING_PLOT_DF["Saved"].all():

    print("\n✓ Missing value comparison plots generated successfully.")
    print(
        f"Location : {MISSING_PLOT_DIR}"
    )

else:

    failed = MISSING_PLOT_DF.loc[
        ~MISSING_PLOT_DF["Saved"],
        "Dataset"
    ].tolist()

    print("\nFailed Plots:")

    for dataset in failed:

        print(f"  • {dataset}")

In [ ]:
# ==============================================================================
# PART I14 — TVAE MISSING VALUE SCORE
# ==============================================================================

print("=" * 100)
print("PART I14 — TVAE MISSING VALUE SCORE")
print("=" * 100)

# ------------------------------------------------------------------------------
# Verify Required Objects
# ------------------------------------------------------------------------------

required_objects = [
    "MISSING_SUMMARY_DF"
]

missing = [
    obj for obj in required_objects
    if obj not in globals()
]

if missing:

    raise RuntimeError(
        "Missing required objects:\n"
        f"{missing}\n\n"
        "Please execute Parts I11-I13 first."
    )

# ------------------------------------------------------------------------------
# Calculate Missing Value Score
# ------------------------------------------------------------------------------

scores = []

for _, row in MISSING_SUMMARY_DF.iterrows():

    difference = abs(
        row["Synthetic Missing (%)"]
        -
        row["Real Missing (%)"]
    )

    score = round(
        max(
            0,
            100 - difference
        ),
        2
    )

    scores.append(score)

# Add score column

MISSING_SUMMARY_DF[
    "TVAE Missing Value Score (%)"
] = scores


display(MISSING_SUMMARY_DF)

# ------------------------------------------------------------------------------
# Summary
# ------------------------------------------------------------------------------

print("\n" + "=" * 100)
print("TVAE MISSING VALUE SCORE SUMMARY")
print("=" * 100)


overall_score = round(
    MISSING_SUMMARY_DF[
        "TVAE Missing Value Score (%)"
    ].mean(),
    2
)


print(
    f"Overall TVAE Missing Value Score : {overall_score}%"
)


print(
    "\n✓ TVAE missing value evaluation completed successfully."
)

In [ ]:
# ==============================================================================
# PART I15 — SAVE TVAE MISSING VALUE REPORTS
# ==============================================================================

print("=" * 100)
print("PART I15 — SAVE TVAE MISSING VALUE REPORTS")
print("=" * 100)

# ------------------------------------------------------------------------------
# Verify Required Objects
# ------------------------------------------------------------------------------

required_objects = [
    "REPORT_DIR",
    "MISSING_SUMMARY_DF",
    "COLUMN_MISSING",
    "DATASETS"
]

missing = [
    obj for obj in required_objects
    if obj not in globals()
]

if missing:

    raise RuntimeError(
        "Missing required objects:\n"
        f"{missing}\n\n"
        "Please execute Parts I11-I14 first."
    )

# ------------------------------------------------------------------------------
# Create TVAE Evaluation Directory
# ------------------------------------------------------------------------------

TVAE_MISSING_REPORT_DIR = os.path.join(
    REPORT_DIR,
    "TVAE_Missing_Value_Evaluation"
)

os.makedirs(
    TVAE_MISSING_REPORT_DIR,
    exist_ok=True
)

# ------------------------------------------------------------------------------
# Save Overall Missing Summary
# ------------------------------------------------------------------------------

missing_summary_csv = os.path.join(
    TVAE_MISSING_REPORT_DIR,
    "tvae_missing_value_summary.csv"
)


MISSING_SUMMARY_DF.to_csv(
    missing_summary_csv,
    index=False
)


# ------------------------------------------------------------------------------
# Save Column-wise Missing Reports
# ------------------------------------------------------------------------------

column_reports = []


for dataset in DATASETS:

    file_path = os.path.join(
        TVAE_MISSING_REPORT_DIR,
        f"{dataset}_tvae_column_missing_report.csv"
    )


    COLUMN_MISSING[dataset].to_csv(
        file_path,
        index=False
    )


    column_reports.append(file_path)


# ------------------------------------------------------------------------------
# Verification
# ------------------------------------------------------------------------------

missing_report_files = [

    missing_summary_csv

] + column_reports


REPORT_CHECK_DF = pd.DataFrame({

    "File": missing_report_files

})


REPORT_CHECK_DF["Exists"] = REPORT_CHECK_DF["File"].apply(
    os.path.exists
)


REPORT_CHECK_DF["Result"] = REPORT_CHECK_DF["Exists"].map(
    {
        True: "PASS",
        False: "FAIL"
    }
)


display(REPORT_CHECK_DF)


# ------------------------------------------------------------------------------
# Summary
# ------------------------------------------------------------------------------

print("\n" + "=" * 100)
print("TVAE MISSING VALUE REPORT SUMMARY")
print("=" * 100)


passed = int(
    REPORT_CHECK_DF["Exists"].sum()
)


total = len(
    REPORT_CHECK_DF
)


print(
    f"Reports Saved : {passed}/{total}"
)


print(
    f"Report Folder : {TVAE_MISSING_REPORT_DIR}"
)


if REPORT_CHECK_DF["Exists"].all():

    print("\n✓ TVAE missing value reports saved successfully.")

else:

    print("\n⚠ Some TVAE missing value reports failed.")


    failed = REPORT_CHECK_DF.loc[
        ~REPORT_CHECK_DF["Exists"],
        "File"
    ].tolist()


    for file in failed:

        print(f"  • {file}")

In [ ]:
# ==============================================================================
# PART I16 — OVERALL TVAE MISSING VALUE SUMMARY
# ==============================================================================

print("=" * 100)
print("PART I16 — OVERALL TVAE MISSING VALUE SUMMARY")
print("=" * 100)


# ------------------------------------------------------------------------------
# Verify Required Objects
# ------------------------------------------------------------------------------

required_objects = [
    "MISSING_SUMMARY_DF",
    "DATASETS"
]


missing = [
    obj for obj in required_objects
    if obj not in globals()
]


if missing:

    raise RuntimeError(
        "Missing required objects:\n"
        f"{missing}\n\n"
        "Please execute Parts I11-I15 first."
    )


# ------------------------------------------------------------------------------
# Display Summary
# ------------------------------------------------------------------------------

display(
    MISSING_SUMMARY_DF
)


# ------------------------------------------------------------------------------
# Calculate Overall TVAE Missing Value Score
# ------------------------------------------------------------------------------

overall_missing_score = round(

    MISSING_SUMMARY_DF[
        "TVAE Missing Value Score (%)"
    ].mean(),

    2
)


# ------------------------------------------------------------------------------
# Summary
# ------------------------------------------------------------------------------

print("\n" + "=" * 100)
print("TVAE MISSING VALUE EVALUATION SUMMARY")
print("=" * 100)


print(
    f"Datasets Evaluated : {len(MISSING_SUMMARY_DF)}"
)


print(
    f"Average TVAE Missing Value Score : {overall_missing_score}%"
)


if overall_missing_score >= 95:

    print(
        "\n✓ Excellent TVAE missing value preservation."
    )


elif overall_missing_score >= 80:

    print(
        "\n✓ Acceptable TVAE missing value preservation."
    )


else:

    print(
        "\n⚠ TVAE missing value distribution differs significantly."
    )


print("=" * 100)

In [ ]:
# ==============================================================================
# PART I17 — TVAE MISSING VALUE VERIFICATION
# ==============================================================================

print("=" * 100)
print("PART I17 — TVAE MISSING VALUE VERIFICATION")
print("=" * 100)


# ------------------------------------------------------------------------------
# Verify Required Objects
# ------------------------------------------------------------------------------

required_objects = [

    "MISSING_SUMMARY_DF",

    "COLUMN_MISSING",

    "missing_summary_csv",

    "MISSING_PLOT_DIR",

    "overall_missing_score"

]


missing = [

    obj for obj in required_objects

    if obj not in globals()

]


if missing:

    raise RuntimeError(

        "Missing required objects:\n"
        f"{missing}\n\n"
        "Please execute Parts I11-I16 first."

    )


# ------------------------------------------------------------------------------
# Verification Checks
# ------------------------------------------------------------------------------

verification = {


    "Missing Summary Created":

        len(MISSING_SUMMARY_DF) == len(DATASETS),


    "Column Missing Reports Created":

        len(COLUMN_MISSING) == len(DATASETS),


    "Missing Summary CSV Saved":

        os.path.exists(
            missing_summary_csv
        ),


    "Missing Value Plot Directory Exists":

        os.path.exists(
            MISSING_PLOT_DIR
        ),


    "Average TVAE Missing Value Score >= 95%":

        overall_missing_score >= 95


}


VERIFY_DF = pd.DataFrame({

    "Component":
        verification.keys(),


    "Status":
        verification.values()

})


VERIFY_DF["Result"] = VERIFY_DF["Status"].map(

    {

        True: "PASS",

        False: "FAIL"

    }

)


display(VERIFY_DF)


# ------------------------------------------------------------------------------
# Summary
# ------------------------------------------------------------------------------

print("\n" + "=" * 100)
print("PART I17 TVAE VERIFICATION SUMMARY")
print("=" * 100)


passed = int(

    VERIFY_DF["Status"].sum()

)


total = len(

    VERIFY_DF

)


print(
    f"Checks Passed : {passed}/{total}"
)


if VERIFY_DF["Status"].all():


    print("\n" + "=" * 100)

    print("✓ PART I17 COMPLETED SUCCESSFULLY")

    print("✓ TVAE missing value summary generated.")

    print("✓ Column-wise missing evaluation completed.")

    print("✓ TVAE missing value reports saved.")

    print("✓ Missing value plots generated.")

    print("✓ Ready for Part J1 — Descriptive Statistics Comparison")

    print("=" * 100)


else:


    print("\nFailed Components:")


    failed = VERIFY_DF.loc[

        ~VERIFY_DF["Status"],

        "Component"

    ].tolist()


    for item in failed:

        print(f"  • {item}")


    raise RuntimeError(

        "Part I17 TVAE verification failed."

    )