In [1]:
# =============================================================================
# Notebook 06
# Privacy-Preserving GAN for Synthetic Tabular Data
# Part 6.1 : Environment Setup
# Block 1 : Install Required Packages
# =============================================================================

print("=" * 80)
print("Installing Required Packages")
print("=" * 80)

# Upgrade pip
!pip -q install --upgrade pip

# Deep Learning
!pip -q install torch torchvision torchaudio

# Differential Privacy
!pip -q install opacus

# Data Processing
!pip -q install pandas numpy scipy scikit-learn

# Visualization
!pip -q install matplotlib seaborn

# Utilities
!pip -q install tqdm pyyaml joblib

print("\nAll packages installed successfully.")

================================================================================
Installing Required Packages
================================================================================
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.8/1.8 MB 34.5 MB/s eta 0:00:00

All packages installed successfully.

In [2]:
# =============================================================================
# Block 2 : Import Libraries
# =============================================================================

import os
import gc
import random
import warnings
from pathlib import Path

import yaml
import joblib

import numpy as np
import pandas as pd

import matplotlib.pyplot as plt

from tqdm.auto import tqdm

import torch
import torch.nn as nn
import torch.optim as optim

from torch.utils.data import (
    TensorDataset,
    DataLoader
)

from sklearn.preprocessing import StandardScaler

from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    roc_auc_score
)

from scipy.stats import (
    ks_2samp,
    wasserstein_distance
)

from scipy.spatial.distance import jensenshannon

from opacus import PrivacyEngine

warnings.filterwarnings("ignore")

print("Libraries imported successfully.")

Libraries imported successfully.

In [3]:
# =============================================================================
# Block 3 : Mount Google Drive
# =============================================================================

from google.colab import drive

drive.mount("/content/drive")

PROJECT_DIR = Path(
    "/content/drive/MyDrive/SPP_GAN_Project"
)

assert PROJECT_DIR.exists(), \
    f"Project folder not found:\n{PROJECT_DIR}"

print("=" * 80)
print("Google Drive Mounted Successfully")
print("=" * 80)

print(PROJECT_DIR)

Mounted at /content/drive
================================================================================
Google Drive Mounted Successfully
================================================================================
/content/drive/MyDrive/SPP_GAN_Project

In [4]:
# =============================================================================
# Block 4 : GPU Configuration
# =============================================================================

DEVICE = torch.device(
    "cuda" if torch.cuda.is_available() else "cpu"
)

print("=" * 80)
print("Hardware Information")
print("=" * 80)

print(f"Device : {DEVICE}")

if torch.cuda.is_available():

    print(f"GPU Name : {torch.cuda.get_device_name(0)}")

    gpu_memory = (
        torch.cuda.get_device_properties(0).total_memory
        /1024**3
    )

    print(f"GPU Memory : {gpu_memory:.2f} GB")

else:

    print("Running on CPU")

================================================================================
Hardware Information
================================================================================
Device : cuda
GPU Name : Tesla T4
GPU Memory : 14.56 GB

In [5]:
# =============================================================================
# Block 5 : Random Seed
# =============================================================================

SEED = 42

random.seed(SEED)

np.random.seed(SEED)

torch.manual_seed(SEED)

if torch.cuda.is_available():

    torch.cuda.manual_seed(SEED)

    torch.cuda.manual_seed_all(SEED)

torch.backends.cudnn.deterministic = True

torch.backends.cudnn.benchmark = False

print("=" * 80)
print("Random Seed Initialized")
print("=" * 80)

print(f"Seed : {SEED}")

================================================================================
Random Seed Initialized
================================================================================
Seed : 42

In [6]:
# =============================================================================
# Block 6 : Verify Environment
# =============================================================================

print("=" * 80)
print("Environment Summary")
print("=" * 80)

print(f"Python Version     : {os.sys.version.split()[0]}")

print(f"PyTorch Version    : {torch.__version__}")

print(f"CUDA Available     : {torch.cuda.is_available()}")

if torch.cuda.is_available():

    print(f"CUDA Version       : {torch.version.cuda}")

print(f"Working Directory  : {PROJECT_DIR}")

print(f"Training Device    : {DEVICE}")

print("\nEnvironment is ready for training.")

================================================================================
Environment Summary
================================================================================
Python Version     : 3.12.13
PyTorch Version    : 2.11.0+cu128
CUDA Available     : True
CUDA Version       : 12.8
Working Directory  : /content/drive/MyDrive/SPP_GAN_Project
Training Device    : cuda

Environment is ready for training.

In [7]:
# =============================================================================
# Part 6.2 : Project Configuration
# Block 1 : Load Configuration
# =============================================================================

CONFIG_PATH = PROJECT_DIR / "config.yaml"

assert CONFIG_PATH.exists(), \
    f"Configuration file not found:\n{CONFIG_PATH}"

with open(CONFIG_PATH, "r") as file:
    config = yaml.safe_load(file)

print("=" * 80)
print("Configuration Loaded Successfully")
print("=" * 80)

for key, value in config.items():
    print(f"{key:<25}: {value}")

================================================================================
Configuration Loaded Successfully
================================================================================
batch_size               : 256
beta1                    : 0.5
beta2                    : 0.999
delta                    : 1e-05
device                   : cuda
epochs                   : 300
gradient_clip            : 1.0
latent_dimension         : 128
learning_rate            : 0.0002
noise_multiplier         : 1.1
optimizer                : Adam
privacy_budget           : 4
seed                     : 42

In [8]:
# =============================================================================
# Block 2 : Project Directories
# =============================================================================

DATA_DIR = PROJECT_DIR / "datasets"

RAW_DATA_DIR = DATA_DIR / "raw"
PROCESSED_DATA_DIR = DATA_DIR / "processed"
SYNTHETIC_DATA_DIR = DATA_DIR / "synthetic"

MODEL_DIR = PROJECT_DIR / "models"
RESULT_DIR = PROJECT_DIR / "results"
REPORT_DIR = PROJECT_DIR / "reports"
LOG_DIR = PROJECT_DIR / "logs"
METADATA_DIR = PROJECT_DIR / "metadata"

DIRECTORIES = {
    "Raw Data": RAW_DATA_DIR,
    "Processed Data": PROCESSED_DATA_DIR,
    "Synthetic Data": SYNTHETIC_DATA_DIR,
    "Models": MODEL_DIR,
    "Results": RESULT_DIR,
    "Reports": REPORT_DIR,
    "Logs": LOG_DIR,
    "Metadata": METADATA_DIR
}

print("=" * 80)
print("Creating Project Directories")
print("=" * 80)

for name, path in DIRECTORIES.items():

    path.mkdir(parents=True, exist_ok=True)

    print(f"{name:<20}: {path}")

print("\nProject directories are ready.")

================================================================================
Creating Project Directories
================================================================================
Raw Data            : /content/drive/MyDrive/SPP_GAN_Project/datasets/raw
Processed Data      : /content/drive/MyDrive/SPP_GAN_Project/datasets/processed
Synthetic Data      : /content/drive/MyDrive/SPP_GAN_Project/datasets/synthetic
Models              : /content/drive/MyDrive/SPP_GAN_Project/models
Results             : /content/drive/MyDrive/SPP_GAN_Project/results
Reports             : /content/drive/MyDrive/SPP_GAN_Project/reports
Logs                : /content/drive/MyDrive/SPP_GAN_Project/logs
Metadata            : /content/drive/MyDrive/SPP_GAN_Project/metadata

Project directories are ready.

In [9]:
# =============================================================================
# Block 3 : Load Processed Datasets
# =============================================================================

DATASET_FILES = {

    "Adult Income":
        "adult_income_processed.csv",

    "Bank Marketing":
        "bank_marketing_processed.csv",

    "Breast Cancer":
        "breast_cancer_processed.csv"

}

datasets = {}

print("=" * 80)
print("Loading Processed Datasets")
print("=" * 80)

for dataset_name, filename in DATASET_FILES.items():

    filepath = PROCESSED_DATA_DIR / filename

    assert filepath.exists(), \
        f"Dataset not found:\n{filepath}"

    df = pd.read_csv(filepath)

    datasets[dataset_name] = df

    print(f"{dataset_name:<20} Shape : {df.shape}")

print("\nAll datasets loaded successfully.")

================================================================================
Loading Processed Datasets
================================================================================
Adult Income         Shape : (32510, 15)
Bank Marketing       Shape : (45211, 17)
Breast Cancer        Shape : (569, 32)

All datasets loaded successfully.

In [10]:
# =============================================================================
# Block 4 : Dataset Verification
# =============================================================================

summary = []

for dataset_name, df in datasets.items():

    summary.append({

        "Dataset":
            dataset_name,

        "Rows":
            df.shape[0],

        "Columns":
            df.shape[1],

        "Missing Values":
            int(df.isnull().sum().sum()),

        "Duplicate Rows":
            int(df.duplicated().sum()),

        "Memory (MB)":
            round(
                df.memory_usage(deep=True).sum()/1024**2,
                2
            )

    })

summary = pd.DataFrame(summary)

print("=" * 80)
print("Dataset Summary")
print("=" * 80)

display(summary)

================================================================================
Dataset Summary
================================================================================

          Dataset   Rows  Columns  Missing Values  Duplicate Rows  Memory (MB)
0    Adult Income  32510       15               0               0         3.72
1  Bank Marketing  45211       17               0               0         5.86
2   Breast Cancer    569       32               0               0         0.14

In [11]:
# =============================================================================
# Block 5 : Experiment Parameters
# =============================================================================

SEED = config["seed"]

LATENT_DIM = config["latent_dimension"]

BATCH_SIZE = config["batch_size"]

EPOCHS = config["epochs"]

LEARNING_RATE = config["learning_rate"]

BETA1 = config["beta1"]

BETA2 = config["beta2"]

NOISE_MULTIPLIER = config["noise_multiplier"]

MAX_GRAD_NORM = config["gradient_clip"]

EPSILON = config["privacy_budget"]

DELTA = config["delta"]

print("=" * 80)
print("Experiment Parameters")
print("=" * 80)

print(f"Seed                : {SEED}")
print(f"Latent Dimension    : {LATENT_DIM}")
print(f"Batch Size          : {BATCH_SIZE}")
print(f"Epochs              : {EPOCHS}")
print(f"Learning Rate       : {LEARNING_RATE}")
print(f"Optimizer Beta1     : {BETA1}")
print(f"Optimizer Beta2     : {BETA2}")
print(f"Privacy Budget (ε)  : {EPSILON}")
print(f"Delta (δ)           : {DELTA}")
print(f"Noise Multiplier    : {NOISE_MULTIPLIER}")
print(f"Gradient Clip       : {MAX_GRAD_NORM}")

================================================================================
Experiment Parameters
================================================================================
Seed                : 42
Latent Dimension    : 128
Batch Size          : 256
Epochs              : 300
Learning Rate       : 0.0002
Optimizer Beta1     : 0.5
Optimizer Beta2     : 0.999
Privacy Budget (ε)  : 4
Delta (δ)           : 1e-05
Noise Multiplier    : 1.1
Gradient Clip       : 1.0

In [12]:
# =============================================================================
# Block 6 : Dataset Information
# =============================================================================

dataset_info = {}

for dataset_name, df in datasets.items():

    dataset_info[dataset_name] = {

        "rows": df.shape[0],

        "columns": df.shape[1],

        "feature_names": list(df.columns),

        "input_dimension": df.shape[1]

    }

joblib.dump(
    dataset_info,
    METADATA_DIR / "dataset_info.pkl"
)

print("=" * 80)
print("Dataset Information Saved")
print("=" * 80)

for dataset_name, info in dataset_info.items():

    print(f"{dataset_name}")

    print(f"Rows              : {info['rows']}")
    print(f"Input Features    : {info['input_dimension']}")
    print("-"*50)

================================================================================
Dataset Information Saved
================================================================================
Adult Income
Rows              : 32510
Input Features    : 15
--------------------------------------------------
Bank Marketing
Rows              : 45211
Input Features    : 17
--------------------------------------------------
Breast Cancer
Rows              : 569
Input Features    : 32
--------------------------------------------------

In [13]:
# =============================================================================
# Block 7 : Project Summary
# =============================================================================

print("=" * 80)
print("Project Configuration Summary")
print("=" * 80)

print(f"Project Directory     : {PROJECT_DIR}")

print(f"Datasets Loaded       : {len(datasets)}")

print(f"Training Device       : {DEVICE}")

print(f"Model Directory       : {MODEL_DIR}")

print(f"Results Directory     : {RESULT_DIR}")

print(f"Reports Directory     : {REPORT_DIR}")

print(f"Metadata Directory    : {METADATA_DIR}")

print("\nNotebook 06 Configuration Completed Successfully.")

================================================================================
Project Configuration Summary
================================================================================
Project Directory     : /content/drive/MyDrive/SPP_GAN_Project
Datasets Loaded       : 3
Training Device       : cuda
Model Directory       : /content/drive/MyDrive/SPP_GAN_Project/models
Results Directory     : /content/drive/MyDrive/SPP_GAN_Project/results
Reports Directory     : /content/drive/MyDrive/SPP_GAN_Project/reports
Metadata Directory    : /content/drive/MyDrive/SPP_GAN_Project/metadata

Notebook 06 Configuration Completed Successfully.

In [14]:
# =============================================================================
# Part 6.3 : Tensor Dataset Preparation
# Block 1 : Validate Dataset Structure
# =============================================================================

print("=" * 80)
print("Validating Datasets")
print("=" * 80)

dataset_metadata = {}

for name, df in datasets.items():

    print(f"\n{name}")
    print("-" * 60)

    print(f"Rows            : {df.shape[0]}")
    print(f"Columns         : {df.shape[1]}")
    print(f"Missing Values  : {df.isnull().sum().sum()}")
    print(f"Duplicate Rows  : {df.duplicated().sum()}")

    dataset_metadata[name] = {
        "rows": df.shape[0],
        "columns": df.shape[1]
    }

print("\nDataset validation completed.")

================================================================================
Validating Datasets
================================================================================

Adult Income
------------------------------------------------------------
Rows            : 32510
Columns         : 15
Missing Values  : 0
Duplicate Rows  : 0

Bank Marketing
------------------------------------------------------------
Rows            : 45211
Columns         : 17
Missing Values  : 0
Duplicate Rows  : 0

Breast Cancer
------------------------------------------------------------
Rows            : 569
Columns         : 32
Missing Values  : 0
Duplicate Rows  : 0

Dataset validation completed.

In [15]:
# =============================================================================
# Block 2 : Feature / Target Separation
# =============================================================================

TARGET_COLUMNS = {

    "Adult Income": "income",

    "Bank Marketing": "y",

    "Breast Cancer": "diagnosis"

}

processed_data = {}

print("=" * 80)
print("Separating Features and Targets")
print("=" * 80)

for name, df in datasets.items():

    target = TARGET_COLUMNS[name]

    if target not in df.columns:
        raise ValueError(
            f"Target column '{target}' not found in {name}"
        )

    X = df.drop(columns=[target])

    y = df[target]

    processed_data[name] = {
        "X": X,
        "y": y
    }

    print(f"{name:<20} X:{X.shape}  y:{y.shape}")

================================================================================
Separating Features and Targets
================================================================================
Adult Income         X:(32510, 14)  y:(32510,)
Bank Marketing       X:(45211, 16)  y:(45211,)
Breast Cancer        X:(569, 31)  y:(569,)

In [16]:
# =============================================================================
# Block 3 : NumPy Conversion
# =============================================================================

numpy_data = {}

print("=" * 80)
print("Converting to NumPy Arrays")
print("=" * 80)

for name, data in processed_data.items():

    X = data["X"].astype(np.float32).to_numpy()

    y = data["y"].astype(np.float32).to_numpy()

    numpy_data[name] = {

        "X": X,

        "y": y

    }

    print(f"{name:<20} {X.shape}")

================================================================================
Converting to NumPy Arrays
================================================================================
Adult Income         (32510, 14)
Bank Marketing       (45211, 16)
Breast Cancer        (569, 31)

In [17]:
# =============================================================================
# Block 4 : Tensor Conversion
# =============================================================================

tensor_data = {}

print("=" * 80)
print("Creating PyTorch Tensors")
print("=" * 80)

for name, data in numpy_data.items():

    X_tensor = torch.tensor(
        data["X"],
        dtype=torch.float32
    )

    y_tensor = torch.tensor(
        data["y"],
        dtype=torch.float32
    )

    tensor_data[name] = {

        "X": X_tensor,

        "y": y_tensor

    }

    print(f"{name:<20} {X_tensor.shape}")

================================================================================
Creating PyTorch Tensors
================================================================================
Adult Income         torch.Size([32510, 14])
Bank Marketing       torch.Size([45211, 16])
Breast Cancer        torch.Size([569, 31])

In [18]:
# =============================================================================
# Block 5 : TensorDataset
# =============================================================================

tensor_datasets = {}

print("=" * 80)
print("Creating TensorDataset Objects")
print("=" * 80)

for name, data in tensor_data.items():

    dataset = TensorDataset(

        data["X"],

        data["y"]

    )

    tensor_datasets[name] = dataset

    print(f"{name:<20} Samples : {len(dataset)}")

================================================================================
Creating TensorDataset Objects
================================================================================
Adult Income         Samples : 32510
Bank Marketing       Samples : 45211
Breast Cancer        Samples : 569

In [93]:
# =============================================================================
# Block 6 : DataLoaders
# =============================================================================

from torch.utils.data import DataLoader

train_loaders = {}

print("=" * 80)
print("Creating DataLoaders")
print("=" * 80)

for name, dataset in tensor_datasets.items():

    loader = DataLoader(

        dataset,

        batch_size=BATCH_SIZE,

        shuffle=True,

        drop_last=True,

        pin_memory=torch.cuda.is_available(),

        num_workers=0

    )

    train_loaders[name] = loader

    print(f"{name:<20} {len(loader)} batches")

================================================================================
Creating DataLoaders
================================================================================
Adult Income         126 batches
Bank Marketing       176 batches
Breast Cancer        2 batches

In [94]:
# =============================================================================
# Block 7 : Save Metadata
# =============================================================================

tensor_metadata = {}

for name, data in tensor_data.items():

    tensor_metadata[name] = {

        "input_dimension": data["X"].shape[1],

        "num_samples": data["X"].shape[0],

        "batch_size": BATCH_SIZE

    }

metadata_path = METADATA_DIR / "tensor_metadata.pkl"

joblib.dump(

    tensor_metadata,

    metadata_path

)

print("=" * 80)
print("Tensor Metadata Saved Successfully")
print("=" * 80)

print(metadata_path)

================================================================================
Tensor Metadata Saved Successfully
================================================================================
/content/drive/MyDrive/SPP_GAN_Project/metadata/tensor_metadata.pkl

In [95]:
# =============================================================================
# Part 6.4 : Differential Privacy Configuration
# Block 1 : Load Privacy Parameters
# =============================================================================

print("=" * 80)
print("Loading Differential Privacy Parameters")
print("=" * 80)

DP_CONFIG = {

    "epsilon": EPSILON,

    "delta": DELTA,

    "noise_multiplier": NOISE_MULTIPLIER,

    "max_grad_norm": MAX_GRAD_NORM,

    "secure_mode": False

}

for key, value in DP_CONFIG.items():

    print(f"{key:<20}: {value}")

================================================================================
Loading Differential Privacy Parameters
================================================================================
epsilon             : 4
delta               : 1e-05
noise_multiplier    : 1.1
max_grad_norm       : 1.0
secure_mode         : False

In [96]:
# =============================================================================
# Block 2 : Validate Privacy Parameters
# =============================================================================

assert DP_CONFIG["epsilon"] > 0, \
    "Privacy budget (ε) must be positive."

assert DP_CONFIG["delta"] > 0, \
    "Delta must be positive."

assert DP_CONFIG["noise_multiplier"] > 0, \
    "Noise multiplier must be positive."

assert DP_CONFIG["max_grad_norm"] > 0, \
    "Gradient clipping value must be positive."

print("=" * 80)
print("Privacy Parameters Validated Successfully")
print("=" * 80)

================================================================================
Privacy Parameters Validated Successfully
================================================================================

In [97]:
# =============================================================================
# Block 3 : Privacy Summary
# =============================================================================

privacy_summary = pd.DataFrame({

    "Parameter": [

        "Privacy Budget (ε)",

        "Delta (δ)",

        "Noise Multiplier",

        "Gradient Clipping",

        "Secure Mode"

    ],

    "Value": [

        DP_CONFIG["epsilon"],

        DP_CONFIG["delta"],

        DP_CONFIG["noise_multiplier"],

        DP_CONFIG["max_grad_norm"],

        DP_CONFIG["secure_mode"]

    ]

})

display(privacy_summary)

            Parameter    Value
0  Privacy Budget (ε)        4
1           Delta (δ)  0.00001
2    Noise Multiplier      1.1
3   Gradient Clipping      1.0
4         Secure Mode    False

In [98]:
# =============================================================================
# Block 4 : Save Privacy Configuration
# =============================================================================

privacy_file = METADATA_DIR / "privacy_config.pkl"

joblib.dump(

    DP_CONFIG,

    privacy_file

)

print("=" * 80)
print("Privacy Configuration Saved")
print("=" * 80)

print(privacy_file)

================================================================================
Privacy Configuration Saved
================================================================================
/content/drive/MyDrive/SPP_GAN_Project/metadata/privacy_config.pkl

In [99]:
# =============================================================================
# Block 5 : Privacy Report
# =============================================================================

print("=" * 80)
print("Differential Privacy Report")
print("=" * 80)

print(f"Privacy Budget (ε) : {DP_CONFIG['epsilon']}")

print(f"Delta (δ)          : {DP_CONFIG['delta']}")

print(f"Noise Multiplier   : {DP_CONFIG['noise_multiplier']}")

print(f"Gradient Clip      : {DP_CONFIG['max_grad_norm']}")

print(f"Secure Mode        : {DP_CONFIG['secure_mode']}")

================================================================================
Differential Privacy Report
================================================================================
Privacy Budget (ε) : 4
Delta (δ)          : 1e-05
Noise Multiplier   : 1.1
Gradient Clip      : 1.0
Secure Mode        : False

In [100]:
# =============================================================================
# Block 6 : DP Readiness
# =============================================================================

print("=" * 80)
print("Differential Privacy Readiness")
print("=" * 80)

print("✓ Privacy parameters loaded")

print("✓ Parameters validated")

print("✓ Configuration saved")

print("✓ Ready for Opacus PrivacyEngine")

print("\nNotebook ready for Generator construction.")

================================================================================
Differential Privacy Readiness
================================================================================
✓ Privacy parameters loaded
✓ Parameters validated
✓ Configuration saved
✓ Ready for Opacus PrivacyEngine

Notebook ready for Generator construction.

In [101]:
# =============================================================================
# Part 6.5
# Block 1 : Generator Configuration
# =============================================================================

print("=" * 80)
print("Generator Configuration")
print("=" * 80)

GENERATOR_CONFIG = {

    "latent_dim": LATENT_DIM,

    "hidden_dims": [256, 512, 512, 256],

    "dropout": 0.20,

    "negative_slope": 0.2

}

print(GENERATOR_CONFIG)

================================================================================
Generator Configuration
================================================================================
{'latent_dim': 128, 'hidden_dims': [256, 512, 512, 256], 'dropout': 0.2, 'negative_slope': 0.2}

In [102]:
# =============================================================================
# Block 2 : Xavier Initialization
# =============================================================================

def initialize_weights(module):

    if isinstance(module, nn.Linear):

        nn.init.xavier_uniform_(module.weight)

        if module.bias is not None:

            nn.init.zeros_(module.bias)

In [103]:
# =============================================================================
# Block 3 : Generator
# =============================================================================

class Generator(nn.Module):

    def __init__(
        self,
        latent_dim,
        output_dim,
        hidden_dims,
        dropout=0.2
    ):

        super().__init__()

        layers = []

        in_features = latent_dim

        for hidden in hidden_dims:

            layers.extend([

                nn.Linear(in_features, hidden),

                nn.LayerNorm(hidden),

                nn.LeakyReLU(
                    negative_slope=0.2,
                    inplace=False
                ),

                nn.Dropout(dropout)

            ])

            in_features = hidden

        layers.append(

            nn.Linear(
                in_features,
                output_dim
            )

        )

        layers.append(

            nn.Tanh()

        )

        self.model = nn.Sequential(*layers)

        self.apply(initialize_weights)

    def forward(self, z):

        return self.model(z)

In [104]:
# =============================================================================
# Block 4 : Initialize Generators
# =============================================================================

generators = {}

for dataset_name, meta in tensor_metadata.items():

    generators[dataset_name] = Generator(

        latent_dim=LATENT_DIM,

        output_dim=meta["input_dimension"],

        hidden_dims=GENERATOR_CONFIG["hidden_dims"],

        dropout=GENERATOR_CONFIG["dropout"]

    ).to(DEVICE)

print("=" * 80)
print("Generators Created Successfully")
print("=" * 80)

for name in generators:

    print(name)

================================================================================
Generators Created Successfully
================================================================================
Adult Income
Bank Marketing
Breast Cancer

In [105]:
# =============================================================================
# Block 5 : Model Summary
# =============================================================================

print("=" * 80)
print("Adult Income Generator")
print("=" * 80)

print(

    generators["Adult Income"]

)

================================================================================
Adult Income Generator
================================================================================
Generator(
  (model): Sequential(
    (0): Linear(in_features=128, out_features=256, bias=True)
    (1): LayerNorm((256,), eps=1e-05, elementwise_affine=True)
    (2): LeakyReLU(negative_slope=0.2)
    (3): Dropout(p=0.2, inplace=False)
    (4): Linear(in_features=256, out_features=512, bias=True)
    (5): LayerNorm((512,), eps=1e-05, elementwise_affine=True)
    (6): LeakyReLU(negative_slope=0.2)
    (7): Dropout(p=0.2, inplace=False)
    (8): Linear(in_features=512, out_features=512, bias=True)
    (9): LayerNorm((512,), eps=1e-05, elementwise_affine=True)
    (10): LeakyReLU(negative_slope=0.2)
    (11): Dropout(p=0.2, inplace=False)
    (12): Linear(in_features=512, out_features=256, bias=True)
    (13): LayerNorm((256,), eps=1e-05, elementwise_affine=True)
    (14): LeakyReLU(negative_slope=0.2)
    (15): Dropout(p=0.2, inplace=False)
    (16): Linear(in_features=256, out_features=14, bias=True)
    (17): Tanh()
  )
)

In [106]:
# =============================================================================
# Block 6 : Forward Pass
# =============================================================================

dataset = "Adult Income"

generator = generators[dataset]

generator.train()

noise = torch.randn(

    16,

    LATENT_DIM,

    device=DEVICE

)

with torch.no_grad():

    fake = generator(noise)

print("=" * 80)
print("Generator Verification")
print("=" * 80)

print("Noise Shape :", noise.shape)

print("Output Shape:", fake.shape)

assert fake.shape == (

    16,

    tensor_metadata[dataset]["input_dimension"]

)

print("\nGenerator Ready")

================================================================================
Generator Verification
================================================================================
Noise Shape : torch.Size([16, 128])
Output Shape: torch.Size([16, 14])

Generator Ready

In [107]:
# =============================================================================
# Part 6.6
# Block 1 : Discriminator Configuration
# =============================================================================

print("=" * 80)
print("Discriminator Configuration")
print("=" * 80)

DISCRIMINATOR_CONFIG = {

    "hidden_dims": [512, 256, 128],

    "dropout": 0.30,

    "negative_slope": 0.2

}

print(DISCRIMINATOR_CONFIG)

================================================================================
Discriminator Configuration
================================================================================
{'hidden_dims': [512, 256, 128], 'dropout': 0.3, 'negative_slope': 0.2}

In [108]:
# =============================================================================
# Block 2 : Weight Initialization
# =============================================================================

def initialize_discriminator_weights(module):

    if isinstance(module, nn.Linear):

        nn.init.xavier_uniform_(module.weight)

        if module.bias is not None:

            nn.init.zeros_(module.bias)

In [109]:
# =============================================================================
# Block 3 : Discriminator Network
# =============================================================================

class Discriminator(nn.Module):

    def __init__(
        self,
        input_dim,
        hidden_dims,
        dropout=0.30
    ):

        super().__init__()

        layers = []

        in_features = input_dim

        for hidden in hidden_dims:

            layers.extend([

                nn.Linear(in_features, hidden),

                nn.LayerNorm(hidden),

                nn.LeakyReLU(
                    negative_slope=0.2,
                    inplace=False
                ),

                nn.Dropout(dropout)

            ])

            in_features = hidden

        # Output raw logits
        layers.append(

            nn.Linear(in_features, 1)

        )

        self.model = nn.Sequential(*layers)

        self.apply(initialize_discriminator_weights)

    def forward(self, x):

        return self.model(x)

In [110]:
# =============================================================================
# Block 4 : Initialize Discriminators
# =============================================================================

discriminators = {}

for dataset_name, meta in tensor_metadata.items():

    discriminators[dataset_name] = Discriminator(

        input_dim=meta["input_dimension"],

        hidden_dims=DISCRIMINATOR_CONFIG["hidden_dims"],

        dropout=DISCRIMINATOR_CONFIG["dropout"]

    ).to(DEVICE)

print("=" * 80)
print("Discriminators Created Successfully")
print("=" * 80)

for name in discriminators:

    print(name)

================================================================================
Discriminators Created Successfully
================================================================================
Adult Income
Bank Marketing
Breast Cancer

In [111]:
# =============================================================================
# Block 5 : Model Summary
# =============================================================================

print("=" * 80)
print("Adult Income Discriminator")
print("=" * 80)

print(

    discriminators["Adult Income"]

)

================================================================================
Adult Income Discriminator
================================================================================
Discriminator(
  (model): Sequential(
    (0): Linear(in_features=14, out_features=512, bias=True)
    (1): LayerNorm((512,), eps=1e-05, elementwise_affine=True)
    (2): LeakyReLU(negative_slope=0.2)
    (3): Dropout(p=0.3, inplace=False)
    (4): Linear(in_features=512, out_features=256, bias=True)
    (5): LayerNorm((256,), eps=1e-05, elementwise_affine=True)
    (6): LeakyReLU(negative_slope=0.2)
    (7): Dropout(p=0.3, inplace=False)
    (8): Linear(in_features=256, out_features=128, bias=True)
    (9): LayerNorm((128,), eps=1e-05, elementwise_affine=True)
    (10): LeakyReLU(negative_slope=0.2)
    (11): Dropout(p=0.3, inplace=False)
    (12): Linear(in_features=128, out_features=1, bias=True)
  )
)

In [112]:
# =============================================================================
# Block 6 : Verification
# =============================================================================

dataset = "Adult Income"

discriminator = discriminators[dataset]

discriminator.train()

sample = torch.randn(

    16,

    tensor_metadata[dataset]["input_dimension"],

    device=DEVICE

)

with torch.no_grad():

    output = discriminator(sample)

print("=" * 80)
print("Discriminator Verification")
print("=" * 80)

print("Input Shape :", sample.shape)

print("Output Shape:", output.shape)

assert output.shape == (16, 1)

print("\nDiscriminator Ready")

================================================================================
Discriminator Verification
================================================================================
Input Shape : torch.Size([16, 14])
Output Shape: torch.Size([16, 1])

Discriminator Ready

In [113]:
# =============================================================================
# Part 6.7
# Block 1 : Loss Function
# =============================================================================

print("=" * 80)
print("Initializing Loss Function")
print("=" * 80)

criterion = nn.BCEWithLogitsLoss()

print("Loss Function")

print(criterion)

================================================================================
Initializing Loss Function
================================================================================
Loss Function
BCEWithLogitsLoss()

In [114]:
# =============================================================================
# Block 2 : Generator Optimizers
# =============================================================================

generator_optimizers = {}

for dataset_name, generator in generators.items():

    generator_optimizers[dataset_name] = torch.optim.Adam(

        generator.parameters(),

        lr=LEARNING_RATE,

        betas=(BETA1, BETA2)

    )

print("=" * 80)
print("Generator Optimizers Created")
print("=" * 80)

print(generator_optimizers.keys())

================================================================================
Generator Optimizers Created
================================================================================
dict_keys(['Adult Income', 'Bank Marketing', 'Breast Cancer'])

In [115]:
# =============================================================================
# Block 3 : Discriminator Optimizers
# =============================================================================

discriminator_optimizers = {}

for dataset_name, discriminator in discriminators.items():

    discriminator_optimizers[dataset_name] = torch.optim.Adam(

        discriminator.parameters(),

        lr=LEARNING_RATE,

        betas=(BETA1, BETA2)

    )

print("=" * 80)
print("Discriminator Optimizers Created")
print("=" * 80)

print(discriminator_optimizers.keys())

================================================================================
Discriminator Optimizers Created
================================================================================
dict_keys(['Adult Income', 'Bank Marketing', 'Breast Cancer'])

In [116]:
# =============================================================================
# Block 4 : Learning Rate Scheduler
# =============================================================================

generator_schedulers = {}

discriminator_schedulers = {}

for dataset_name in generators.keys():

    generator_schedulers[dataset_name] = torch.optim.lr_scheduler.StepLR(

        generator_optimizers[dataset_name],

        step_size=100,

        gamma=0.5

    )

    discriminator_schedulers[dataset_name] = torch.optim.lr_scheduler.StepLR(

        discriminator_optimizers[dataset_name],

        step_size=100,

        gamma=0.5

    )

print("=" * 80)
print("Learning Rate Schedulers Created")
print("=" * 80)

================================================================================
Learning Rate Schedulers Created
================================================================================

In [117]:
# =============================================================================
# Block 5 : Mixed Precision
# =============================================================================

USE_AMP = DEVICE.type == "cuda"

if USE_AMP:

    from torch.cuda.amp import GradScaler

    scaler = GradScaler()

    print("Automatic Mixed Precision Enabled")

else:

    scaler = None

    print("Running on CPU (AMP Disabled)")

Automatic Mixed Precision Enabled

In [118]:
# =============================================================================
# Block 6 : Training State
# =============================================================================

training_state = {}

for dataset_name in generators.keys():

    training_state[dataset_name] = {

        "generator": generators[dataset_name],

        "discriminator": discriminators[dataset_name],

        "g_optimizer": generator_optimizers[dataset_name],

        "d_optimizer": discriminator_optimizers[dataset_name],

        "g_scheduler": generator_schedulers[dataset_name],

        "d_scheduler": discriminator_schedulers[dataset_name],

        "criterion": criterion,

        "train_loader": train_loaders[dataset_name], # Added the train_loader here

        "generator_loss": [],

        "discriminator_loss": [],

        "epsilon": [],

        "best_generator_loss": float("inf"),

        "best_discriminator_loss": float("inf"),

        "epoch": 0

    }

print("=" * 80)
print("Training State Created")
print("=" * 80)

print(training_state.keys())

================================================================================
Training State Created
================================================================================
dict_keys(['Adult Income', 'Bank Marketing', 'Breast Cancer'])

In [119]:
# =============================================================================
# Block 7 : Verification
# =============================================================================

print("=" * 80)
print("Training Components Summary")
print("=" * 80)

print(f"Datasets              : {len(training_state)}")

print(f"Generator Models      : {len(generators)}")

print(f"Discriminator Models  : {len(discriminators)}")

print(f"Loss Function         : {criterion.__class__.__name__}")

print(f"Optimizer             : Adam")

print(f"Scheduler             : StepLR")

print(f"Mixed Precision       : {USE_AMP}")

print(f"Learning Rate         : {LEARNING_RATE}")

print(f"Epochs                : {EPOCHS}")

print(f"Batch Size            : {BATCH_SIZE}")

print("\nTraining Components Ready.")

================================================================================
Training Components Summary
================================================================================
Datasets              : 3
Generator Models      : 3
Discriminator Models  : 3
Loss Function         : BCEWithLogitsLoss
Optimizer             : Adam
Scheduler             : StepLR
Mixed Precision       : True
Learning Rate         : 0.0002
Epochs                : 300
Batch Size            : 256

Training Components Ready.

In [125]:
# =============================================================================
# 6.8 Training Components
# =============================================================================

print("=" * 80)
print("Initializing Training Components")
print("=" * 80)

# ---------------------------------------------------------------------
# Hidden Layer Configuration
# ---------------------------------------------------------------------

GENERATOR_HIDDEN_DIMS = [256, 512, 256]

DISCRIMINATOR_HIDDEN_DIMS = [256, 512, 256]

training_state = {}

# ---------------------------------------------------------------------
# Initialize Components
# ---------------------------------------------------------------------

for dataset_name, dataset in tensor_datasets.items():

    print(f"\nInitializing : {dataset_name}")

    # -------------------------------------------------------------
    # Dataset
    # -------------------------------------------------------------

    train_tensor = dataset.tensors[0]

    input_dim = train_tensor.shape[1]

    train_loader = train_loaders[dataset_name]

    # -------------------------------------------------------------
    # Generator
    # -------------------------------------------------------------

    generator = Generator(

        latent_dim=LATENT_DIM,

        output_dim=input_dim,

        hidden_dims=GENERATOR_HIDDEN_DIMS,

        dropout=0.20

    ).to(DEVICE)

    # -------------------------------------------------------------
    # Discriminator
    # -------------------------------------------------------------

    discriminator = Discriminator(

        input_dim=input_dim,

        hidden_dims=DISCRIMINATOR_HIDDEN_DIMS,

        dropout=0.30

    ).to(DEVICE)

    # -------------------------------------------------------------
    # Optimizers
    # -------------------------------------------------------------

    optimizer_G = torch.optim.Adam(

        generator.parameters(),

        lr=LEARNING_RATE,

        betas=(BETA1, BETA2)

    )

    optimizer_D = torch.optim.Adam(

        discriminator.parameters(),

        lr=LEARNING_RATE,

        betas=(BETA1, BETA2)

    )

    # -------------------------------------------------------------
    # Loss Function
    # -------------------------------------------------------------

    criterion = nn.BCEWithLogitsLoss()

    # -------------------------------------------------------------
    # Store Everything
    # -------------------------------------------------------------

    training_state[dataset_name] = {

        "generator": generator,

        "discriminator": discriminator,

        "optimizer_G": optimizer_G,

        "optimizer_D": optimizer_D,

        "criterion": criterion,

        "train_loader": train_loader,

        "train_tensor": train_tensor,

        "input_dim": input_dim,

        "history": {

            "generator_loss": [],

            "discriminator_loss": [],

            "epsilon": []

        }

    }

    print(f"Features : {input_dim}")

print("\n" + "=" * 80)
print("Training Components Ready")
print("=" * 80)

================================================================================
Initializing Training Components
================================================================================

Initializing : Adult Income
Features : 14

Initializing : Bank Marketing
Features : 16

Initializing : Breast Cancer
Features : 31

================================================================================
Training Components Ready
================================================================================

In [126]:
# =============================================================================
# 6.9 Model Validation
# =============================================================================

print("=" * 80)
print("Validating Training Components")
print("=" * 80)

validation_passed = True

for dataset_name, state in training_state.items():

    print(f"\nDataset : {dataset_name}")
    print("-" * 60)

    generator = state["generator"]
    discriminator = state["discriminator"]
    optimizer_G = state["optimizer_G"]
    optimizer_D = state["optimizer_D"]
    criterion = state["criterion"]
    train_loader = state["train_loader"]
    train_tensor = state["train_tensor"]

    # ---------------------------------------------------------
    # Generator
    # ---------------------------------------------------------

    print("Generator               :", generator.__class__.__name__)

    # ---------------------------------------------------------
    # Discriminator
    # ---------------------------------------------------------

    print("Discriminator           :", discriminator.__class__.__name__)

    # ---------------------------------------------------------
    # Optimizers
    # ---------------------------------------------------------

    print("Generator Optimizer     :", optimizer_G.__class__.__name__)

    print("Discriminator Optimizer :", optimizer_D.__class__.__name__)

    # ---------------------------------------------------------
    # Loss
    # ---------------------------------------------------------

    print("Loss Function           :", criterion.__class__.__name__)

    # ---------------------------------------------------------
    # Dataset
    # ---------------------------------------------------------

    print("Training Samples        :", len(train_tensor))

    print("Input Features          :", train_tensor.shape[1])

    print("Batch Size              :", train_loader.batch_size)

    print("Number of Batches       :", len(train_loader))

    # ---------------------------------------------------------
    # Device
    # ---------------------------------------------------------

    gen_device = next(generator.parameters()).device

    dis_device = next(discriminator.parameters()).device

    print("Generator Device        :", gen_device)

    print("Discriminator Device    :", dis_device)

    # ---------------------------------------------------------
    # NaN Check
    # ---------------------------------------------------------

    if torch.isnan(train_tensor).any():

        print("NaN Values              : Found")

        validation_passed = False

    else:

        print("NaN Values              : None")

    # ---------------------------------------------------------
    # Dimension Check
    # ---------------------------------------------------------

    noise = torch.randn(
        2,
        LATENT_DIM,
        device=DEVICE
    )

    with torch.no_grad():

        fake = generator(noise)

        pred = discriminator(fake)

    print("Generator Output Shape  :", tuple(fake.shape))

    print("Discriminator Shape     :", tuple(pred.shape))

    expected = train_tensor.shape[1]

    if fake.shape[1] != expected:

        print("Feature Match           : FAILED")

        validation_passed = False

    else:

        print("Feature Match           : PASSED")

print("\n" + "=" * 80)

if validation_passed:

    print("All Training Components Validated Successfully")

else:

    print("Validation Failed")

print("=" * 80)

================================================================================
Validating Training Components
================================================================================

Dataset : Adult Income
------------------------------------------------------------
Generator               : Generator
Discriminator           : Discriminator
Generator Optimizer     : Adam
Discriminator Optimizer : Adam
Loss Function           : BCEWithLogitsLoss
Training Samples        : 32510
Input Features          : 14
Batch Size              : 256
Number of Batches       : 126
Generator Device        : cuda:0
Discriminator Device    : cuda:0
NaN Values              : None
Generator Output Shape  : (2, 14)
Discriminator Shape     : (2, 1)
Feature Match           : PASSED

Dataset : Bank Marketing
------------------------------------------------------------
Generator               : Generator
Discriminator           : Discriminator
Generator Optimizer     : Adam
Discriminator Optimizer : Adam
Loss Function           : BCEWithLogitsLoss
Training Samples        : 45211
Input Features          : 16
Batch Size              : 256
Number of Batches       : 176
Generator Device        : cuda:0
Discriminator Device    : cuda:0
NaN Values              : None
Generator Output Shape  : (2, 16)
Discriminator Shape     : (2, 1)
Feature Match           : PASSED

Dataset : Breast Cancer
------------------------------------------------------------
Generator               : Generator
Discriminator           : Discriminator
Generator Optimizer     : Adam
Discriminator Optimizer : Adam
Loss Function           : BCEWithLogitsLoss
Training Samples        : 569
Input Features          : 31
Batch Size              : 256
Number of Batches       : 2
Generator Device        : cuda:0
Discriminator Device    : cuda:0
NaN Values              : None
Generator Output Shape  : (2, 31)
Discriminator Shape     : (2, 1)
Feature Match           : PASSED

================================================================================
All Training Components Validated Successfully
================================================================================

In [127]:
# =============================================================================
# 6.10 PrivacyEngine Attachment
# =============================================================================

from opacus import PrivacyEngine

print("=" * 80)
print("Attaching PrivacyEngine")
print("=" * 80)

for dataset_name, state in training_state.items():

    print(f"\nDataset : {dataset_name}")
    print("-" * 60)

    # ============================================================
    # Retrieve Training Components
    # ============================================================

    generator = state["generator"]

    discriminator = state["discriminator"]

    optimizer_D = state["optimizer_D"]

    train_loader = state["train_loader"]

    # ============================================================
    # Initialize Privacy Engine
    # ============================================================

    privacy_engine = PrivacyEngine()

    # ============================================================
    # Attach Differential Privacy
    # ============================================================

    discriminator, optimizer_D, train_loader = privacy_engine.make_private(

        module=discriminator,

        optimizer=optimizer_D,

        data_loader=train_loader,

        noise_multiplier=NOISE_MULTIPLIER,

        max_grad_norm=MAX_GRAD_NORM,

        poisson_sampling=False

    )

    # ============================================================
    # Store Updated Objects
    # ============================================================

    state["generator"] = generator

    state["discriminator"] = discriminator

    state["optimizer_D"] = optimizer_D

    state["train_loader"] = train_loader

    state["privacy_engine"] = privacy_engine

    # ============================================================
    # Display Information
    # ============================================================

    print("PrivacyEngine Attached Successfully")

    print(f"Noise Multiplier : {NOISE_MULTIPLIER}")

    print(f"Max Grad Norm    : {MAX_GRAD_NORM}")

    print(f"Poisson Sampling : False")

    print(f"Batches          : {len(train_loader)}")

print("\n" + "=" * 80)
print("PrivacyEngine Successfully Attached to All Datasets")
print("=" * 80)

================================================================================
Attaching PrivacyEngine
================================================================================

Dataset : Adult Income
------------------------------------------------------------
PrivacyEngine Attached Successfully
Noise Multiplier : 1.1
Max Grad Norm    : 1.0
Poisson Sampling : False
Batches          : 126

Dataset : Bank Marketing
------------------------------------------------------------
PrivacyEngine Attached Successfully
Noise Multiplier : 1.1
Max Grad Norm    : 1.0
Poisson Sampling : False
Batches          : 176

Dataset : Breast Cancer
------------------------------------------------------------
PrivacyEngine Attached Successfully
Noise Multiplier : 1.1
Max Grad Norm    : 1.0
Poisson Sampling : False
Batches          : 2

================================================================================
PrivacyEngine Successfully Attached to All Datasets
================================================================================

In [128]:
# =============================================================================
# 6.11 Utility Functions
# =============================================================================

import torch
import numpy as np
import pandas as pd


# =============================================================================
# Generate Latent Noise
# =============================================================================

def generate_noise(
    batch_size,
    latent_dim,
    device=DEVICE
):

    return torch.randn(
        batch_size,
        latent_dim,
        device=device
    )


# =============================================================================
# Create Real Labels
# =============================================================================

def real_labels(
    batch_size,
    device=DEVICE
):

    return torch.ones(
        batch_size,
        1,
        device=device
    )


# =============================================================================
# Create Fake Labels
# =============================================================================

def fake_labels(
    batch_size,
    device=DEVICE
):

    return torch.zeros(
        batch_size,
        1,
        device=device
    )


# =============================================================================
# Compute Gradient Norm
# =============================================================================

def gradient_norm(model):

    total_norm = 0.0

    for parameter in model.parameters():

        if parameter.grad is None:

            continue

        norm = parameter.grad.detach().data.norm(2)

        total_norm += norm.item() ** 2

    return total_norm ** 0.5


# =============================================================================
# Count Trainable Parameters
# =============================================================================

def count_parameters(model):

    return sum(

        p.numel()

        for p in model.parameters()

        if p.requires_grad

    )


# =============================================================================
# Privacy Report
# =============================================================================

def privacy_report(
    privacy_engine,
    delta=DELTA
):

    try:

        epsilon = privacy_engine.get_epsilon(delta)

        return float(epsilon)

    except Exception:

        return None


# =============================================================================
# Save Loss History
# =============================================================================

def update_history(

    history,

    generator_loss,

    discriminator_loss,

    epsilon=None

):

    history["generator_loss"].append(

        float(generator_loss)

    )

    history["discriminator_loss"].append(

        float(discriminator_loss)

    )

    if epsilon is not None:

        history["epsilon"].append(

            float(epsilon)

        )


# =============================================================================
# Print Epoch Statistics
# =============================================================================

def print_epoch_statistics(

    epoch,

    total_epochs,

    generator_loss,

    discriminator_loss,

    epsilon=None

):

    print("-" * 70)

    print(

        f"Epoch [{epoch}/{total_epochs}]"

    )

    print(

        f"Generator Loss     : {generator_loss:.6f}"

    )

    print(

        f"Discriminator Loss : {discriminator_loss:.6f}"

    )

    if epsilon is not None:

        print(

            f"Privacy ε          : {epsilon:.4f}"

        )

    print("-" * 70)


# =============================================================================
# Save Model Checkpoint
# =============================================================================

def save_checkpoint(

    generator,

    discriminator,

    optimizer_G,

    optimizer_D,

    filepath

):

    torch.save(

        {

            "generator": generator.state_dict(),

            "discriminator": discriminator.state_dict(),

            "optimizer_G": optimizer_G.state_dict(),

            "optimizer_D": optimizer_D.state_dict()

        },

        filepath

    )


# =============================================================================
# Model Summary
# =============================================================================

def model_summary(

    generator,

    discriminator

):

    print("=" * 70)

    print("Model Summary")

    print("=" * 70)

    print(

        "Generator Parameters :",

        count_parameters(generator)

    )

    print(

        "Discriminator Parameters :",

        count_parameters(discriminator)

    )

    print("=" * 70)


# =============================================================================
# Generate Synthetic Samples
# =============================================================================

@torch.no_grad()

def sample_generator(

    generator,

    num_samples,

    latent_dim,

    device=DEVICE

):

    generator.eval()

    noise = generate_noise(

        num_samples,

        latent_dim,

        device

    )

    samples = generator(

        noise

    )

    return samples.cpu()


# =============================================================================
# Utility Functions Ready
# =============================================================================

print("=" * 80)
print("Utility Functions Loaded Successfully")
print("=" * 80)

================================================================================
Utility Functions Loaded Successfully
================================================================================

In [129]:
print("=" * 80)
print("Verifying DataLoaders")
print("=" * 80)

for dataset_name, state in training_state.items():

    batch = next(iter(state["train_loader"]))[0]

    print(f"\n{dataset_name}")

    print(f"Batch Shape : {batch.shape}")

    print(f"Batch Size  : {batch.shape[0]}")

    print(f"Expected    : {BATCH_SIZE}")

================================================================================
Verifying DataLoaders
================================================================================

Adult Income
Batch Shape : torch.Size([256, 14])
Batch Size  : 256
Expected    : 256

Bank Marketing
Batch Shape : torch.Size([256, 16])
Batch Size  : 256
Expected    : 256

Breast Cancer
Batch Shape : torch.Size([256, 31])
Batch Size  : 256
Expected    : 256

In [130]:
# =============================================================================
# 6.12 Batch Training
# =============================================================================

def train_batch(
    generator,
    discriminator,
    optimizer_G,
    optimizer_D,
    criterion,
    real_batch,
    latent_dim,
    device=DEVICE,
    privacy_engine=None
):

    # ---------------------------------------------------------
    # Move Real Data to Device
    # ---------------------------------------------------------

    real_batch = real_batch.to(device)

    batch_size = real_batch.size(0)

    # ---------------------------------------------------------
    # Create Labels
    # ---------------------------------------------------------

    real_target = real_labels(
        batch_size,
        device
    )

    fake_target = fake_labels(
        batch_size,
        device
    )

    # ---------------------------------------------------------
    # Train Discriminator
    # ---------------------------------------------------------

    optimizer_D.zero_grad()

    real_output = discriminator(
        real_batch
    )

    d_real_loss = criterion(
        real_output,
        real_target
    )

    noise = generate_noise(
        batch_size,
        latent_dim,
        device
    )

    fake_batch = generator(
        noise
    )

    fake_output = discriminator(
        fake_batch.detach()
    )

    d_fake_loss = criterion(
        fake_output,
        fake_target
    )

    d_loss = d_real_loss + d_fake_loss

    d_loss.backward()

    optimizer_D.step()

    # ---------------------------------------------------------
    # Train Generator
    # ---------------------------------------------------------

    optimizer_G.zero_grad()

    noise = generate_noise(
        batch_size,
        latent_dim,
        device
    )

    fake_batch = generator(
        noise
    )

    prediction = discriminator(
        fake_batch
    )

    g_loss = criterion(
        prediction,
        real_target
    )

    g_loss.backward()

    optimizer_G.step()

    # ---------------------------------------------------------
    # Gradient Norms
    # ---------------------------------------------------------

    g_grad = gradient_norm(
        generator
    )

    d_grad = gradient_norm(
        discriminator
    )

    # ---------------------------------------------------------
    # Privacy Accounting
    # ---------------------------------------------------------

    epsilon = None

    if privacy_engine is not None:

        try:

            epsilon = privacy_engine.get_epsilon(
                DELTA
            )

        except Exception:

            epsilon = None

    # ---------------------------------------------------------
    # Return Statistics
    # ---------------------------------------------------------

    return {

        "generator_loss": float(
            g_loss.item()
        ),

        "discriminator_loss": float(
            d_loss.item()
        ),

        "generator_gradient_norm": float(
            g_grad
        ),

        "discriminator_gradient_norm": float(
            d_grad
        ),

        "epsilon": epsilon

    }

In [131]:
# =============================================================================
# Test Batch Training
# =============================================================================

dataset_name = list(training_state.keys())[0]

state = training_state[dataset_name]

real_batch = next(iter(state["train_loader"]))[0]

stats = train_batch(

    generator=state["generator"],

    discriminator=state["discriminator"],

    optimizer_G=state["optimizer_G"],

    optimizer_D=state["optimizer_D"],

    criterion=state["criterion"],

    real_batch=real_batch,

    latent_dim=LATENT_DIM,

    device=DEVICE,

    privacy_engine=state.get("privacy_engine", None)

)

print("=" * 70)
print("Batch Training Successful")
print("=" * 70)

for key, value in stats.items():

    print(f"{key:30s}: {value}")

======================================================================
Batch Training Successful
======================================================================
generator_loss                : 0.8584835529327393
discriminator_loss            : 1.587960958480835
generator_gradient_norm       : 3.1252406041642424
discriminator_gradient_norm   : 7.595043154054443
epsilon                       : 0.11703399475905116

In [132]:
# =============================================================================
# 6.13 Epoch Training
# =============================================================================

def train_epoch(
    generator,
    discriminator,
    optimizer_G,
    optimizer_D,
    criterion,
    train_loader,
    latent_dim,
    device,
    privacy_engine=None
):
    """
    Train GAN for one complete epoch.

    Returns
    -------
    dict
        Epoch statistics
    """

    generator.train()
    discriminator.train()

    epoch_g_loss = 0.0
    epoch_d_loss = 0.0

    epoch_g_grad = 0.0
    epoch_d_grad = 0.0

    total_batches = 0

    for batch in train_loader:

        # ------------------------------------------------------------
        # Extract real data
        # ------------------------------------------------------------

        if isinstance(batch, (list, tuple)):
            real_batch = batch[0]
        else:
            real_batch = batch

        # ------------------------------------------------------------
        # Train one batch
        # ------------------------------------------------------------

        stats = train_batch(

            generator=generator,

            discriminator=discriminator,

            optimizer_G=optimizer_G,

            optimizer_D=optimizer_D,

            criterion=criterion,

            real_batch=real_batch,

            latent_dim=latent_dim,

            device=device,

            privacy_engine=privacy_engine

        )

        epoch_g_loss += stats["generator_loss"]
        epoch_d_loss += stats["discriminator_loss"]

        epoch_g_grad += stats["generator_gradient_norm"]
        epoch_d_grad += stats["discriminator_gradient_norm"]

        total_batches += 1

    # ------------------------------------------------------------
    # Average statistics
    # ------------------------------------------------------------

    epoch_stats = {

        "generator_loss":
            epoch_g_loss / total_batches,

        "discriminator_loss":
            epoch_d_loss / total_batches,

        "generator_gradient_norm":
            epoch_g_grad / total_batches,

        "discriminator_gradient_norm":
            epoch_d_grad / total_batches,

        "epsilon":
            stats["epsilon"]

    }

    return epoch_stats

In [133]:
print("=" * 70)
print("Testing Epoch Training")
print("=" * 70)

dataset_name = list(training_state.keys())[0]

state = training_state[dataset_name]

epoch_stats = train_epoch(

    generator=state["generator"],

    discriminator=state["discriminator"],

    optimizer_G=state["optimizer_G"],

    optimizer_D=state["optimizer_D"],

    criterion=state["criterion"],

    train_loader=state["train_loader"],

    latent_dim=LATENT_DIM,

    device=DEVICE,

    privacy_engine=state["privacy_engine"]

)

print("\nEpoch Training Successful\n")

for key, value in epoch_stats.items():
    print(f"{key:<30}: {value}")

======================================================================
Testing Epoch Training
======================================================================

Epoch Training Successful

generator_loss                : 1.1061345542234087
discriminator_loss            : 1.1338433207027496
generator_gradient_norm       : 1.8503168895880358
discriminator_gradient_norm   : 11.693013908177358
epsilon                       : 0.4797975415166143

In [134]:
# =============================================================================
# 6.14 Full Training
# =============================================================================

import copy
import os

print("=" * 80)
print("Starting Full Training")
print("=" * 80)


def train_all_datasets(
    training_state,
    epochs=EPOCHS,
    latent_dim=LATENT_DIM,
    device=DEVICE,
    save_dir=None,
    print_every=10
):
    """
    Train every dataset for multiple epochs.

    Returns
    -------
    history : dict
    best_models : dict
    """

    history = {}

    best_models = {}

    if save_dir is not None:
        os.makedirs(save_dir, exist_ok=True)

    for dataset_name, state in training_state.items():

        print("\n" + "=" * 80)
        print(f"Training : {dataset_name}")
        print("=" * 80)

        history[dataset_name] = {
            "generator_loss": [],
            "discriminator_loss": [],
            "generator_gradient_norm": [],
            "discriminator_gradient_norm": [],
            "epsilon": []
        }

        best_loss = float("inf")

        best_models[dataset_name] = None

        for epoch in range(1, epochs + 1):

            stats = train_epoch(

                generator=state["generator"],

                discriminator=state["discriminator"],

                optimizer_G=state["optimizer_G"],

                optimizer_D=state["optimizer_D"],

                criterion=state["criterion"],

                train_loader=state["train_loader"],

                latent_dim=latent_dim,

                device=device,

                privacy_engine=state["privacy_engine"]

            )

            history[dataset_name]["generator_loss"].append(
                stats["generator_loss"]
            )

            history[dataset_name]["discriminator_loss"].append(
                stats["discriminator_loss"]
            )

            history[dataset_name]["generator_gradient_norm"].append(
                stats["generator_gradient_norm"]
            )

            history[dataset_name]["discriminator_gradient_norm"].append(
                stats["discriminator_gradient_norm"]
            )

            history[dataset_name]["epsilon"].append(
                stats["epsilon"]
            )

            total_loss = (
                stats["generator_loss"] +
                stats["discriminator_loss"]
            )

            if total_loss < best_loss:

                best_loss = total_loss

                best_models[dataset_name] = copy.deepcopy(
                    state["generator"].state_dict()
                )

                if save_dir is not None:

                    torch.save(

                        best_models[dataset_name],

                        os.path.join(
                            save_dir,
                            dataset_name.replace(" ", "_") + "_best_generator.pth"
                        )

                    )

            if epoch % print_every == 0 or epoch == 1:

                print(
                    f"Epoch {epoch:3d}/{epochs}"
                    f" | G Loss: {stats['generator_loss']:.4f}"
                    f" | D Loss: {stats['discriminator_loss']:.4f}"
                    f" | ε={stats['epsilon']:.4f}"
                )

        print(f"\nFinished Training : {dataset_name}")
        print(f"Best Total Loss : {best_loss:.4f}")

    print("\n" + "=" * 80)
    print("Full Training Completed Successfully")
    print("=" * 80)

    return history, best_models

================================================================================
Starting Full Training
================================================================================

In [ ]:
# =============================================================================
# Run Full Training
# =============================================================================

SAVE_MODEL_DIR = os.path.join(
    PROJECT_DIR,
    "results",
    "training",
    "models"
)

training_history, best_generators = train_all_datasets(

    training_state=training_state,

    epochs=EPOCHS,

    latent_dim=LATENT_DIM,

    device=DEVICE,

    save_dir=SAVE_MODEL_DIR,

    print_every=10

)

================================================================================
Training : Adult Income
================================================================================
Epoch   1/300 | G Loss: 1.7382 | D Loss: 0.8822 | ε=0.6314
Epoch  10/300 | G Loss: 9.3652 | D Loss: 0.0687 | ε=1.3972
Epoch  20/300 | G Loss: 10.2529 | D Loss: 0.0498 | ε=1.9466
Epoch  30/300 | G Loss: 11.2054 | D Loss: 0.0399 | ε=2.3906
Epoch  40/300 | G Loss: 11.8690 | D Loss: 0.0293 | ε=2.7774
Epoch  50/300 | G Loss: 11.7680 | D Loss: 0.0277 | ε=3.1267
Epoch  60/300 | G Loss: 12.2632 | D Loss: 0.0287 | ε=3.4490
Epoch  70/300 | G Loss: 12.2382 | D Loss: 0.0192 | ε=3.7506
Epoch  80/300 | G Loss: 12.3771 | D Loss: 0.0214 | ε=4.0357

In [ ]:
# =============================================================================
# 6.15 Save Models
# =============================================================================

import os
import torch

print("=" * 80)
print("Saving Trained Models")
print("=" * 80)

MODEL_DIR = os.path.join(
    PROJECT_ROOT,
    "results",
    "training",
    "models"
)

os.makedirs(MODEL_DIR, exist_ok=True)

for dataset_name, state in training_state.items():

    print(f"\nSaving : {dataset_name}")

    file_prefix = dataset_name.replace(" ", "_").lower()

    # --------------------------------------------------------
    # Save Final Generator
    # --------------------------------------------------------

    generator_path = os.path.join(
        MODEL_DIR,
        f"{file_prefix}_generator_final.pth"
    )

    torch.save(

        state["generator"].state_dict(),

        generator_path

    )

    # --------------------------------------------------------
    # Save Final Discriminator
    # --------------------------------------------------------

    discriminator_path = os.path.join(
        MODEL_DIR,
        f"{file_prefix}_discriminator_final.pth"
    )

    torch.save(

        state["discriminator"].state_dict(),

        discriminator_path

    )

    # --------------------------------------------------------
    # Save Best Generator
    # --------------------------------------------------------

    if dataset_name in best_generators:

        best_generator_path = os.path.join(

            MODEL_DIR,

            f"{file_prefix}_generator_best.pth"

        )

        torch.save(

            best_generators[dataset_name],

            best_generator_path

        )

    # --------------------------------------------------------
    # Save Complete Training Checkpoint
    # --------------------------------------------------------

    checkpoint = {

        "generator_state_dict":
            state["generator"].state_dict(),

        "discriminator_state_dict":
            state["discriminator"].state_dict(),

        "optimizer_G_state_dict":
            state["optimizer_G"].state_dict(),

        "optimizer_D_state_dict":
            state["optimizer_D"].state_dict(),

        "history":
            training_history[dataset_name],

        "latent_dim":
            LATENT_DIM,

        "epochs":
            EPOCHS

    }

    checkpoint_path = os.path.join(

        MODEL_DIR,

        f"{file_prefix}_checkpoint.pth"

    )

    torch.save(

        checkpoint,

        checkpoint_path

    )

    print("✓ Generator Saved")
    print("✓ Discriminator Saved")
    print("✓ Best Generator Saved")
    print("✓ Training Checkpoint Saved")

print("\n" + "=" * 80)
print("All Models Saved Successfully")
print("=" * 80)

Training history initialized

In [ ]:
# =============================================================================
# 6.16 Generate Synthetic Data
# =============================================================================

import torch
import pandas as pd

print("=" * 80)
print("Generating Synthetic Data")
print("=" * 80)


def generate_synthetic_data(
    generator,
    original_dataframe,
    latent_dim,
    device,
    num_samples=None
):
    """
    Generate synthetic tabular data using a trained generator.
    """

    generator.eval()

    if num_samples is None:
        num_samples = len(original_dataframe)

    feature_columns = list(original_dataframe.columns)

    # --------------------------------------------------------
    # Remove target column if it was excluded during training
    # --------------------------------------------------------

    if len(feature_columns) != generator.model[-2].out_features:

        feature_columns = feature_columns[
            :generator.model[-2].out_features
        ]

    with torch.no_grad():

        noise = torch.randn(
            num_samples,
            latent_dim,
            device=device
        )

        synthetic = generator(noise)

    synthetic = synthetic.cpu().numpy()

    synthetic_df = pd.DataFrame(

        synthetic,

        columns=feature_columns

    )

    return synthetic_df


# =============================================================================
# Generate Synthetic Data for All Datasets
# =============================================================================

synthetic_datasets = {}

for dataset_name, state in training_state.items():

    print("\n" + "=" * 60)
    print(dataset_name)
    print("=" * 60)

    generator = state["generator"]

    generator.load_state_dict(

        best_generators[dataset_name]

    )

    generator.to(DEVICE)

    generator.eval()

    original_df = datasets[dataset_name]["dataframe"]

    synthetic_df = generate_synthetic_data(

        generator=generator,

        original_dataframe=original_df,

        latent_dim=LATENT_DIM,

        device=DEVICE,

        num_samples=len(original_df)

    )

    synthetic_datasets[dataset_name] = synthetic_df

    print("Original Shape  :", original_df.shape)
    print("Synthetic Shape :", synthetic_df.shape)

print("\n" + "=" * 80)
print("Synthetic Data Generation Completed")
print("=" * 80)

WARNING:opacus.data_loader:Ignoring drop_last as it is not compatible with DPDataLoader.
WARNING:opacus.data_loader:Ignoring drop_last as it is not compatible with DPDataLoader.
WARNING:opacus.data_loader:Ignoring drop_last as it is not compatible with DPDataLoader.

Adult Income: PrivacyEngine attached successfully.
Bank Marketing: PrivacyEngine attached successfully.
Breast Cancer: PrivacyEngine attached successfully.

In [ ]:
# =============================================================================
# 6.17 Save Synthetic Datasets
# =============================================================================

import os

print("=" * 80)
print("Saving Synthetic Datasets")
print("=" * 80)

# -------------------------------------------------------------------------
# Output Directory
# -------------------------------------------------------------------------

SYNTHETIC_DIR = os.path.join(
    PROJECT_ROOT,
    "results",
    "synthetic_data"
)

os.makedirs(
    SYNTHETIC_DIR,
    exist_ok=True
)

saved_files = {}

# -------------------------------------------------------------------------
# Save Each Dataset
# -------------------------------------------------------------------------

for dataset_name, synthetic_df in synthetic_datasets.items():

    file_name = (
        dataset_name
        .replace(" ", "_")
        .lower()
        + "_synthetic.csv"
    )

    file_path = os.path.join(
        SYNTHETIC_DIR,
        file_name
    )

    synthetic_df.to_csv(
        file_path,
        index=False
    )

    saved_files[dataset_name] = file_path

    print(f"\n✓ {dataset_name}")
    print(f"Rows    : {synthetic_df.shape[0]}")
    print(f"Columns : {synthetic_df.shape[1]}")
    print(f"Saved   : {file_path}")

print("\n" + "=" * 80)
print("All Synthetic Datasets Saved Successfully")
print("=" * 80)

Dataset : Adult Income
Privacy Engine: True

Dataset : Bank Marketing
Privacy Engine: True

Dataset : Breast Cancer
Privacy Engine: True

In [ ]:
# =============================================================================
# Verify Saved Synthetic Datasets
# =============================================================================

print("=" * 80)
print("Verifying Saved Files")
print("=" * 80)

for dataset_name, file_path in saved_files.items():

    df = pd.read_csv(file_path)

    print(f"\n{dataset_name}")
    print("-" * 60)
    print("Shape :", df.shape)
    print("Path  :", file_path)

Checkpoint directory:
/content/drive/MyDrive/SPP_GAN_Project/models/dp_gan/checkpoints

In [ ]:
# =============================================================================
# 6.18 Training History
# =============================================================================

import os
import matplotlib.pyplot as plt

print("=" * 80)
print("Training History Visualization")
print("=" * 80)

HISTORY_DIR = os.path.join(
    PROJECT_ROOT,
    "results",
    "training",
    "history"
)

os.makedirs(HISTORY_DIR, exist_ok=True)

for dataset_name, history in training_history.items():

    print(f"\nGenerating plots : {dataset_name}")

    epochs = range(
        1,
        len(history["generator_loss"]) + 1
    )

    # ==========================================================
    # Generator & Discriminator Loss
    # ==========================================================

    plt.figure(figsize=(10,5))

    plt.plot(
        epochs,
        history["generator_loss"],
        label="Generator Loss",
        linewidth=2
    )

    plt.plot(
        epochs,
        history["discriminator_loss"],
        label="Discriminator Loss",
        linewidth=2
    )

    plt.xlabel("Epoch")

    plt.ylabel("Loss")

    plt.title(f"{dataset_name} - Training Loss")

    plt.legend()

    plt.grid(True)

    plt.tight_layout()

    loss_path = os.path.join(
        HISTORY_DIR,
        dataset_name.replace(" ","_").lower() + "_loss.png"
    )

    plt.savefig(
        loss_path,
        dpi=300,
        bbox_inches="tight"
    )

    plt.show()

    # ==========================================================
    # Gradient Norms
    # ==========================================================

    plt.figure(figsize=(10,5))

    plt.plot(
        epochs,
        history["generator_gradient_norm"],
        label="Generator",
        linewidth=2
    )

    plt.plot(
        epochs,
        history["discriminator_gradient_norm"],
        label="Discriminator",
        linewidth=2
    )

    plt.xlabel("Epoch")

    plt.ylabel("Gradient Norm")

    plt.title(f"{dataset_name} - Gradient Norm")

    plt.legend()

    plt.grid(True)

    plt.tight_layout()

    grad_path = os.path.join(
        HISTORY_DIR,
        dataset_name.replace(" ","_").lower() + "_gradient_norm.png"
    )

    plt.savefig(
        grad_path,
        dpi=300,
        bbox_inches="tight"
    )

    plt.show()

    # ==========================================================
    # Privacy Budget
    # ==========================================================

    plt.figure(figsize=(10,5))

    plt.plot(
        epochs,
        history["epsilon"],
        linewidth=2
    )

    plt.xlabel("Epoch")

    plt.ylabel("Privacy Budget (ε)")

    plt.title(f"{dataset_name} - Privacy Budget")

    plt.grid(True)

    plt.tight_layout()

    epsilon_path = os.path.join(
        HISTORY_DIR,
        dataset_name.replace(" ","_").lower() + "_epsilon.png"
    )

    plt.savefig(
        epsilon_path,
        dpi=300,
        bbox_inches="tight"
    )

    plt.show()

    print("✓ Loss Curve Saved")
    print("✓ Gradient Curve Saved")
    print("✓ Privacy Curve Saved")

print("\n" + "=" * 80)
print("Training History Saved Successfully")
print("=" * 80)

{
    "epochs": 300,
    "batch_size": 256,
    "learning_rate": 0.0002,
    "optimizer": "Adam",
    "latent_dimension": 128,
    "data_dimension": 14
}

In [ ]:
# =============================================================================
# 6.19 Summary
# =============================================================================

import pandas as pd

print("=" * 80)
print("NOTEBOOK 6 SUMMARY")
print("=" * 80)

summary = []

for dataset_name in training_state.keys():

    history = training_history[dataset_name]

    synthetic_df = synthetic_datasets[dataset_name]

    original_df = datasets[dataset_name]["dataframe"]

    summary.append({

        "Dataset": dataset_name,

        "Original Samples": len(original_df),

        "Synthetic Samples": len(synthetic_df),

        "Features": synthetic_df.shape[1],

        "Final Generator Loss":
            round(history["generator_loss"][-1], 4),

        "Final Discriminator Loss":
            round(history["discriminator_loss"][-1], 4),

        "Final ε":
            round(history["epsilon"][-1], 4)

    })

summary_df = pd.DataFrame(summary)

print(summary_df)

print("\n" + "=" * 80)
print("Project Outputs")
print("=" * 80)

print(f"""
✓ Trained Generator Models
    {MODEL_DIR}

✓ Training History
    {HISTORY_DIR}

✓ Synthetic Datasets
    {SYNTHETIC_DIR}
""")

print("=" * 80)
print("Notebook 6 Completed Successfully")
print("=" * 80)

Generator Parameters: 569631
Discriminator Parameters: 182529

Training Components Ready ✓