# =============================================================

# NOTEBOOK 06

#

# Privacy-Preserving Deep Learning Synthetic Data Generation — DP-CTGAN

# ==============================================================

SPP-GAN: A Privacy-Preserving Statistical–Machine Learning Framework for
High-Fidelity Synthetic Tabular Data Generation

## Researcher

Mohd Amzad

## Notebook

Notebook 06 – Privacy-Preserving Deep Learning Synthetic Data Generation
(DP-CTGAN)

## Purpose

This notebook implements a Differentially Private Conditional Generative
Adversarial Network (DP-CTGAN) for privacy-preserving synthetic tabular data
generation using the preprocessed datasets produced in Notebook 02.

The notebook extends the CTGAN-based synthetic data generation process by
incorporating Differential Privacy (DP) during model training using the
Opacus privacy framework.

The trained DP-CTGAN models are used to generate synthetic datasets that
will be evaluated in subsequent notebooks using a common evaluation
framework for structural consistency, statistical fidelity, data utility,
and privacy-related performance.

## Model Implemented

• Differentially Private Conditional Generative Adversarial Network (DP-CTGAN)

## Privacy Mechanism

• Differential Privacy using DP-SGD
• Opacus PrivacyEngine
• Per-sample gradient computation
• Gradient clipping
• Gaussian noise addition
• Privacy accounting using (ε, δ)-Differential Privacy

## Inputs

### Notebook 02

• Preprocessed datasets
• Dataset metadata
• Train, validation, and test splits
• Feature information required for model training

### Project Configuration

• config.yaml
• Reproducibility settings
• DP-CTGAN hyperparameters
• Privacy parameters

## Outputs

• Trained DP-CTGAN generator models
• Trained DP-CTGAN discriminator models
• Privacy-accounting results
• Synthetic datasets
• Model checkpoints
• Training history
• Privacy-training history
• Generated visualizations
• Dataset metadata
• DP-CTGAN configuration records
• Intermediate artifacts for downstream evaluation

## Workflow

A. Notebook Overview
B. Environment Setup
C. Project Configuration
D. Dataset Loading and Validation
E. Feature and Tensor Preparation
F. Differential Privacy Configuration
G. Generator Architecture
H. Discriminator Architecture
I. Opacus Compatibility Validation
J. Loss Functions and Optimizers
K. PrivacyEngine Configuration
L. DP-CTGAN Training
M. Privacy Accounting
N. Synthetic Data Generation
O. Model and Dataset Saving
P. Training and Privacy Visualizations
Q. Final Verification

## Research Role

Notebook 06 is responsible for training the privacy-preserving DP-CTGAN
models and generating synthetic datasets.

The common evaluation of the generated synthetic datasets is performed
separately using the established evaluation workflow in Notebook 04.
This ensures that statistical fidelity, structural consistency, utility,
and other evaluation metrics are applied consistently across the different
synthetic data generation methods.

## Version

1.0

In [83]:
# ==============================================================================
# PART A1 — GOOGLE DRIVE MOUNTING
# ==============================================================================

from google.colab import drive
import os

print("=" * 100)
print("PART A1 — GOOGLE DRIVE MOUNTING")
print("=" * 100)

drive.mount(
    "/content/drive"
)

GOOGLE_DRIVE_ROOT = "/content/drive/MyDrive"

DRIVE_VERIFICATION = os.path.exists(
    GOOGLE_DRIVE_ROOT
)

print()
print("Google Drive mounted successfully.")
print(f"Google Drive Root: {GOOGLE_DRIVE_ROOT}")

====================================================================================================
PART A1 — GOOGLE DRIVE MOUNTING
====================================================================================================
Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

Google Drive mounted successfully.
Google Drive Root: /content/drive/MyDrive

In [84]:
# ==============================================================================
# PART A2 — INSTALL REQUIRED PACKAGES
# ==============================================================================

print("=" * 100)
print("PART A2 — INSTALL REQUIRED PACKAGES")
print("=" * 100)

!pip install -q opacus pyyaml scikit-learn matplotlib seaborn

print()
print("Required packages installed successfully.")

====================================================================================================
PART A2 — INSTALL REQUIRED PACKAGES
====================================================================================================

Required packages installed successfully.

In [85]:
# ==============================================================================
# PART A3 — IMPORT REQUIRED LIBRARIES
# ==============================================================================

import os
import sys
import json
import math
import random
import pickle
import platform
import warnings
from pathlib import Path
from datetime import datetime

import numpy as np
import pandas as pd

import matplotlib.pyplot as plt
import seaborn as sns

import yaml

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

import torch
import torch.nn as nn
import torch.nn.functional as F

from torch.utils.data import Dataset, DataLoader

from opacus import PrivacyEngine
from opacus.validators import ModuleValidator

warnings.filterwarnings("ignore")

print("All required libraries imported successfully.")

All required libraries imported successfully.

In [86]:
# ==============================================================================
# PART A4 — REPRODUCIBILITY CONFIGURATION
# ==============================================================================

SEED = 42

random.seed(SEED)
np.random.seed(SEED)

torch.manual_seed(SEED)

if torch.cuda.is_available():

    torch.cuda.manual_seed(SEED)
    torch.cuda.manual_seed_all(SEED)

torch.backends.cudnn.deterministic = True
torch.backends.cudnn.benchmark = False

print("=" * 100)
print("REPRODUCIBILITY CONFIGURATION")
print("=" * 100)

print(f"Global Random Seed : {SEED}")
print("Python random seed : Configured")
print("NumPy random seed  : Configured")
print("PyTorch random seed: Configured")
print("CUDA random seed   : Configured when available")
print("Deterministic mode : Enabled")

====================================================================================================
REPRODUCIBILITY CONFIGURATION
====================================================================================================
Global Random Seed : 42
Python random seed : Configured
NumPy random seed  : Configured
PyTorch random seed: Configured
CUDA random seed   : Configured when available
Deterministic mode : Enabled

In [87]:
# ==============================================================================
# PART A5 — HARDWARE AND DEVICE CONFIGURATION
# ==============================================================================

DEVICE = torch.device(
    "cuda"
    if torch.cuda.is_available()
    else "cpu"
)

print("=" * 100)
print("HARDWARE AND DEVICE CONFIGURATION")
print("=" * 100)

print(f"Selected Device : {DEVICE}")

if torch.cuda.is_available():

    print(
        f"GPU Device      : "
        f"{torch.cuda.get_device_name(0)}"
    )

    print(
        f"CUDA Version    : "
        f"{torch.version.cuda}"
    )

    print(
        f"GPU Count       : "
        f"{torch.cuda.device_count()}"
    )

    print(
        f"Current GPU ID  : "
        f"{torch.cuda.current_device()}"
    )

else:

    print(
        "GPU Device      : Not available"
    )

    print(
        "CUDA Version    : Not available"
    )

    print(
        "Training will use CPU."
    )

====================================================================================================
HARDWARE AND DEVICE CONFIGURATION
====================================================================================================
Selected Device : cpu
GPU Device      : Not available
CUDA Version    : Not available
Training will use CPU.

In [88]:
# ==============================================================================
# PART A6 — SOFTWARE VERSION VERIFICATION
# ==============================================================================

import sklearn
import opacus

SOFTWARE_VERSIONS = {

    "Python":
        platform.python_version(),

    "Operating System":
        platform.system(),

    "PyTorch":
        torch.__version__,

    "NumPy":
        np.__version__,

    "Pandas":
        pd.__version__,

    "Scikit-learn":
        sklearn.__version__,

    "Opacus":
        opacus.__version__,

    "Matplotlib":
        plt.matplotlib.__version__,

    "Seaborn":
        sns.__version__,

    "PyYAML":
        yaml.__version__,
}

print("=" * 100)
print("SOFTWARE VERSION VERIFICATION")
print("=" * 100)

for software, version in SOFTWARE_VERSIONS.items():

    print(
        f"{software:20s}: {version}"
    )

====================================================================================================
SOFTWARE VERSION VERIFICATION
====================================================================================================
Python              : 3.12.13
Operating System    : Linux
PyTorch             : 2.11.0+cpu
NumPy               : 2.0.2
Pandas              : 2.2.2
Scikit-learn        : 1.6.1
Opacus              : 1.6.0
Matplotlib          : 3.10.0
Seaborn             : 0.13.2
PyYAML              : 6.0.3

In [89]:
# ==============================================================================
# PART A7 — ENVIRONMENT VERIFICATION
# ==============================================================================

ENVIRONMENT_VERIFICATION = {

    "Google Drive Available":
        DRIVE_VERIFICATION,

    "Python Available":
        sys.version_info.major >= 3,

    "PyTorch Available":
        torch is not None,

    "NumPy Available":
        np is not None,

    "Pandas Available":
        pd is not None,

    "Scikit-learn Available":
        sklearn is not None,

    "Opacus Available":
        opacus is not None,

    "PyYAML Available":
        yaml is not None,

    "Device Configured":
        DEVICE is not None,

    "Seed Configured":
        SEED == 42,
}

print("=" * 100)
print("ENVIRONMENT VERIFICATION")
print("=" * 100)

for check, status in (
    ENVIRONMENT_VERIFICATION.items()
):

    print(
        f"{check:35s}: "
        f"{'PASS' if status else 'FAIL'}"
    )

print()

PASSED_CHECKS = sum(
    ENVIRONMENT_VERIFICATION.values()
)

TOTAL_CHECKS = len(
    ENVIRONMENT_VERIFICATION
)

print(
    f"Environment Checks: "
    f"{PASSED_CHECKS}/{TOTAL_CHECKS} Passed"
)

====================================================================================================
ENVIRONMENT VERIFICATION
====================================================================================================
Google Drive Available             : PASS
Python Available                   : PASS
PyTorch Available                  : PASS
NumPy Available                    : PASS
Pandas Available                   : PASS
Scikit-learn Available             : PASS
Opacus Available                   : PASS
PyYAML Available                   : PASS
Device Configured                  : PASS
Seed Configured                    : PASS

Environment Checks: 10/10 Passed

In [90]:
# ==============================================================================
# PART B1 — PROJECT ROOT CONFIGURATION
# ==============================================================================

print("=" * 100)
print("PART B1 — PROJECT ROOT CONFIGURATION")
print("=" * 100)

PROJECT_NAME = "SPP_GAN_Project"

PROJECT_ROOT = (
    Path(GOOGLE_DRIVE_ROOT)
    / PROJECT_NAME
)

print(
    f"Project Name : {PROJECT_NAME}"
)

print(
    f"Project Root : {PROJECT_ROOT}"
)

if not PROJECT_ROOT.exists():

    raise FileNotFoundError(
        "\nProject root was not found.\n"
        f"Expected location:\n{PROJECT_ROOT}\n\n"
        "Please verify the project folder in Google Drive."
    )

print()
print("Project root verified successfully.")

====================================================================================================
PART B1 — PROJECT ROOT CONFIGURATION
====================================================================================================
Project Name : SPP_GAN_Project
Project Root : /content/drive/MyDrive/SPP_GAN_Project

Project root verified successfully.

In [91]:
# ==============================================================================
# PART B2 — PROJECT STRUCTURE INSPECTION
# ==============================================================================

print("=" * 100)
print("PART B2 — PROJECT STRUCTURE INSPECTION")
print("=" * 100)

for item in sorted(PROJECT_ROOT.iterdir()):

    if item.is_dir():

        print(f"[DIR ] {item.name}")

    else:

        print(f"[FILE] {item.name}")

====================================================================================================
PART B2 — PROJECT STRUCTURE INSPECTION
====================================================================================================
[DIR ] checkpoints
[DIR ] config
[FILE] config.yaml
[DIR ] configs
[DIR ] datasets
[DIR ] experiments
[DIR ] figures
[DIR ] histories
[DIR ] logs
[DIR ] metadata
[DIR ] models
[DIR ] notebooks
[DIR ] plots
[DIR ] privacy
[DIR ] reports
[DIR ] results
[DIR ] statistical_models
[DIR ] synthetic_data

In [92]:
# ==============================================================================
# PART B3 — CONFIGURATION FILE DISCOVERY
# ==============================================================================

CONFIG_CANDIDATES = [

    PROJECT_ROOT / "config.yaml",

    PROJECT_ROOT / "configs" / "config.yaml",

    PROJECT_ROOT / "configuration" / "config.yaml",

    PROJECT_ROOT / "config" / "config.yaml",
]

CONFIG_PATH = None

for candidate in CONFIG_CANDIDATES:

    if candidate.exists():

        CONFIG_PATH = candidate

        break

if CONFIG_PATH is None:

    raise FileNotFoundError(
        "\nconfig.yaml could not be located.\n\n"
        "Checked the following locations:\n"
        + "\n".join(
            str(path)
            for path in CONFIG_CANDIDATES
        )
    )

print("=" * 100)
print("PART B3 — CONFIGURATION FILE DISCOVERY")
print("=" * 100)

print(
    f"Configuration File:\n{CONFIG_PATH}"
)

print()
print("Configuration file verified successfully.")

====================================================================================================
PART B3 — CONFIGURATION FILE DISCOVERY
====================================================================================================
Configuration File:
/content/drive/MyDrive/SPP_GAN_Project/config.yaml

Configuration file verified successfully.

In [93]:
# ==============================================================================
# PART B4 — LOAD PROJECT CONFIGURATION
# ==============================================================================

with open(
    CONFIG_PATH,
    "r",
    encoding="utf-8"
) as file:

    CONFIG = yaml.safe_load(file)

if CONFIG is None:

    CONFIG = {}

print("=" * 100)
print("PART B4 — PROJECT CONFIGURATION")
print("=" * 100)

print(
    json.dumps(
        CONFIG,
        indent=4,
        default=str
    )
)

====================================================================================================
PART B4 — PROJECT CONFIGURATION
====================================================================================================
{
    "batch_size": 256,
    "beta1": 0.5,
    "beta2": 0.999,
    "delta": 1e-05,
    "device": "cuda",
    "epochs": 100,
    "gradient_clip": 1.0,
    "latent_dimension": 128,
    "learning_rate": 0.0002,
    "noise_multiplier": 1.1,
    "optimizer": "Adam",
    "privacy_budget": 4,
    "seed": 42
}

In [94]:
# ==============================================================================
# PART B5 — CONFIGURATION VALIDATION
# ==============================================================================

REQUIRED_CONFIG_KEYS = [

    "batch_size",
    "epochs",
    "learning_rate",
    "beta1",
    "beta2",
    "latent_dimension",
    "privacy_budget",
    "delta",
    "noise_multiplier",
    "gradient_clip",
    "seed",
]

CONFIG_VALIDATION = {}

for key in REQUIRED_CONFIG_KEYS:

    CONFIG_VALIDATION[key] = (
        key in CONFIG
    )

print("=" * 100)
print("PART B5 — CONFIGURATION VALIDATION")
print("=" * 100)

for key, status in CONFIG_VALIDATION.items():

    print(
        f"{key:25s}: "
        f"{'PASS' if status else 'MISSING'}"
    )

MISSING_CONFIG_KEYS = [
    key
    for key, status
    in CONFIG_VALIDATION.items()
    if not status
]

if MISSING_CONFIG_KEYS:

    raise KeyError(
        "Required configuration keys are missing:\n"
        + "\n".join(
            f"• {key}"
            for key in MISSING_CONFIG_KEYS
        )
    )

print()
print("All required configuration parameters are available.")

====================================================================================================
PART B5 — CONFIGURATION VALIDATION
====================================================================================================
batch_size               : PASS
epochs                   : PASS
learning_rate            : PASS
beta1                    : PASS
beta2                    : PASS
latent_dimension         : PASS
privacy_budget           : PASS
delta                    : PASS
noise_multiplier         : PASS
gradient_clip            : PASS
seed                     : PASS

All required configuration parameters are available.

In [95]:
# ==============================================================================
# PART B6 — GENERAL PROJECT CONFIGURATION
# ==============================================================================

PROJECT_CONFIG = {

    "seed":
        int(
            CONFIG["seed"]
        ),

    "device":
        CONFIG.get(
            "device",
            str(DEVICE)
        ),

    "batch_size":
        int(
            CONFIG["batch_size"]
        ),

    "epochs":
        int(
            CONFIG["epochs"]
        ),

    "learning_rate":
        float(
            CONFIG["learning_rate"]
        ),

    "beta1":
        float(
            CONFIG["beta1"]
        ),

    "beta2":
        float(
            CONFIG["beta2"]
        ),

    "latent_dimension":
        int(
            CONFIG["latent_dimension"]
        ),
}

print("=" * 100)
print("PART B6 — GENERAL PROJECT CONFIGURATION")
print("=" * 100)

for key, value in PROJECT_CONFIG.items():

    print(f"{key:25s}: {value}")

====================================================================================================
PART B6 — GENERAL PROJECT CONFIGURATION
====================================================================================================
seed                     : 42
device                   : cuda
batch_size               : 256
epochs                   : 100
learning_rate            : 0.0002
beta1                    : 0.5
beta2                    : 0.999
latent_dimension         : 128

In [96]:
# ==============================================================================
# PART B7 — DIFFERENTIAL PRIVACY CONFIGURATION
# ==============================================================================

DP_CONFIG = {

    "privacy_budget":
        float(
            CONFIG["privacy_budget"]
        ),

    "delta":
        float(
            CONFIG["delta"]
        ),

    "noise_multiplier":
        float(
            CONFIG["noise_multiplier"]
        ),

    "gradient_clip":
        float(
            CONFIG["gradient_clip"]
        ),
}

print("=" * 100)
print("PART B7 — DIFFERENTIAL PRIVACY CONFIGURATION")
print("=" * 100)

for key, value in DP_CONFIG.items():

    print(f"{key:25s}: {value}")

====================================================================================================
PART B7 — DIFFERENTIAL PRIVACY CONFIGURATION
====================================================================================================
privacy_budget           : 4.0
delta                    : 1e-05
noise_multiplier         : 1.1
gradient_clip            : 1.0

In [97]:
# ==============================================================================
# PART B8 — DIFFERENTIAL PRIVACY PARAMETER VALIDATION
# ==============================================================================

DP_VALIDATION = {

    "Privacy Budget > 0":
        DP_CONFIG["privacy_budget"] > 0,

    "Delta > 0":
        DP_CONFIG["delta"] > 0,

    "Delta < 1":
        DP_CONFIG["delta"] < 1,

    "Noise Multiplier > 0":
        DP_CONFIG["noise_multiplier"] > 0,

    "Gradient Clip > 0":
        DP_CONFIG["gradient_clip"] > 0,
}

print("=" * 100)
print("PART B8 — DIFFERENTIAL PRIVACY PARAMETER VALIDATION")
print("=" * 100)

for check, status in DP_VALIDATION.items():

    print(
        f"{check:35s}: "
        f"{'PASS' if status else 'FAIL'}"
    )

if not all(
    DP_VALIDATION.values()
):

    raise ValueError(
        "One or more Differential Privacy parameters are invalid."
    )

print()
print(
    "Differential Privacy parameters "
    "passed validation."
)

====================================================================================================
PART B8 — DIFFERENTIAL PRIVACY PARAMETER VALIDATION
====================================================================================================
Privacy Budget > 0                 : PASS
Delta > 0                          : PASS
Delta < 1                          : PASS
Noise Multiplier > 0               : PASS
Gradient Clip > 0                  : PASS

Differential Privacy parameters passed validation.

In [98]:
# ==============================================================================
# PART B9 — PROJECT DIRECTORY CONFIGURATION
# ==============================================================================

DATA_DIR = PROJECT_ROOT / "data"

RAW_DATA_DIR = (
    DATA_DIR / "raw"
)

PROCESSED_DATA_DIR = (
    DATA_DIR / "processed"
)

NOTEBOOK_DIR = (
    PROJECT_ROOT / "notebooks"
)

MODEL_ROOT_DIR = (
    PROJECT_ROOT / "models"
)

SYNTHETIC_ROOT_DIR = (
    PROJECT_ROOT / "synthetic_data"
)

EVALUATION_ROOT_DIR = (
    PROJECT_ROOT / "evaluation"
)

REPORT_ROOT_DIR = (
    PROJECT_ROOT / "reports"
)

PLOT_ROOT_DIR = (
    PROJECT_ROOT / "plots"
)

METADATA_ROOT_DIR = (
    PROJECT_ROOT / "metadata"
)

LOG_ROOT_DIR = (
    PROJECT_ROOT / "logs"
)

print("=" * 100)
print("PART B9 — PROJECT DIRECTORY CONFIGURATION")
print("=" * 100)

PROJECT_DIRECTORIES = {

    "Project Root":
        PROJECT_ROOT,

    "Data":
        DATA_DIR,

    "Raw Data":
        RAW_DATA_DIR,

    "Processed Data":
        PROCESSED_DATA_DIR,

    "Notebooks":
        NOTEBOOK_DIR,

    "Models":
        MODEL_ROOT_DIR,

    "Synthetic Data":
        SYNTHETIC_ROOT_DIR,

    "Evaluation":
        EVALUATION_ROOT_DIR,

    "Reports":
        REPORT_ROOT_DIR,

    "Plots":
        PLOT_ROOT_DIR,

    "Metadata":
        METADATA_ROOT_DIR,

    "Logs":
        LOG_ROOT_DIR,
}

for name, path in PROJECT_DIRECTORIES.items():

    print(f"{name:20s}: {path}")

====================================================================================================
PART B9 — PROJECT DIRECTORY CONFIGURATION
====================================================================================================
Project Root        : /content/drive/MyDrive/SPP_GAN_Project
Data                : /content/drive/MyDrive/SPP_GAN_Project/data
Raw Data            : /content/drive/MyDrive/SPP_GAN_Project/data/raw
Processed Data      : /content/drive/MyDrive/SPP_GAN_Project/data/processed
Notebooks           : /content/drive/MyDrive/SPP_GAN_Project/notebooks
Models              : /content/drive/MyDrive/SPP_GAN_Project/models
Synthetic Data      : /content/drive/MyDrive/SPP_GAN_Project/synthetic_data
Evaluation          : /content/drive/MyDrive/SPP_GAN_Project/evaluation
Reports             : /content/drive/MyDrive/SPP_GAN_Project/reports
Plots               : /content/drive/MyDrive/SPP_GAN_Project/plots
Metadata            : /content/drive/MyDrive/SPP_GAN_Project/metadata
Logs                : /content/drive/MyDrive/SPP_GAN_Project/logs

In [99]:
# ==============================================================================
# PART B10 — DP-CTGAN OUTPUT DIRECTORIES
# ==============================================================================

DP_CTGAN_MODEL_DIR = (
    MODEL_ROOT_DIR / "dp_ctgan"
)

DP_CTGAN_SYNTHETIC_DIR = (
    SYNTHETIC_ROOT_DIR / "dp_ctgan"
)

DP_CTGAN_REPORT_DIR = (
    REPORT_ROOT_DIR / "dp_ctgan"
)

DP_CTGAN_PLOT_DIR = (
    PLOT_ROOT_DIR / "dp_ctgan"
)

DP_CTGAN_METADATA_DIR = (
    METADATA_ROOT_DIR / "dp_ctgan"
)

DP_CTGAN_LOG_DIR = (
    LOG_ROOT_DIR / "dp_ctgan"
)

DP_CTGAN_DIRECTORIES = {

    "DP-CTGAN Models":
        DP_CTGAN_MODEL_DIR,

    "DP-CTGAN Synthetic Data":
        DP_CTGAN_SYNTHETIC_DIR,

    "DP-CTGAN Reports":
        DP_CTGAN_REPORT_DIR,

    "DP-CTGAN Plots":
        DP_CTGAN_PLOT_DIR,

    "DP-CTGAN Metadata":
        DP_CTGAN_METADATA_DIR,

    "DP-CTGAN Logs":
        DP_CTGAN_LOG_DIR,
}

for name, path in DP_CTGAN_DIRECTORIES.items():

    path.mkdir(
        parents=True,
        exist_ok=True
    )

print("=" * 100)
print("PART B10 — DP-CTGAN OUTPUT DIRECTORIES")
print("=" * 100)

for name, path in DP_CTGAN_DIRECTORIES.items():

    print(
        f"{name:30s}: "
        f"{path}"
    )

====================================================================================================
PART B10 — DP-CTGAN OUTPUT DIRECTORIES
====================================================================================================
DP-CTGAN Models               : /content/drive/MyDrive/SPP_GAN_Project/models/dp_ctgan
DP-CTGAN Synthetic Data       : /content/drive/MyDrive/SPP_GAN_Project/synthetic_data/dp_ctgan
DP-CTGAN Reports              : /content/drive/MyDrive/SPP_GAN_Project/reports/dp_ctgan
DP-CTGAN Plots                : /content/drive/MyDrive/SPP_GAN_Project/plots/dp_ctgan
DP-CTGAN Metadata             : /content/drive/MyDrive/SPP_GAN_Project/metadata/dp_ctgan
DP-CTGAN Logs                 : /content/drive/MyDrive/SPP_GAN_Project/logs/dp_ctgan

In [100]:
# ==============================================================================
# PART B11 — SAVE ACTIVE CONFIGURATION SNAPSHOT
# ==============================================================================

ACTIVE_CONFIGURATION = {

    "notebook":
        "Notebook 06 — Privacy-Preserving CTGAN",

    "model":
        "DP-CTGAN",

    "framework":
        "SPP-GAN",

    "researcher":
        "Mohd Amzad",

    "timestamp":
        datetime.now().isoformat(),

    "project_root":
        str(PROJECT_ROOT),

    "config_file":
        str(CONFIG_PATH),

    "project_configuration":
        PROJECT_CONFIG,

    "differential_privacy_configuration":
        DP_CONFIG,

    "software_versions":
        SOFTWARE_VERSIONS,

    "device":
        str(DEVICE),

    "seed":
        SEED,
}

CONFIG_SNAPSHOT_PATH = (
    DP_CTGAN_METADATA_DIR
    / "dp_ctgan_configuration.json"
)

with open(
    CONFIG_SNAPSHOT_PATH,
    "w",
    encoding="utf-8"
) as file:

    json.dump(
        ACTIVE_CONFIGURATION,
        file,
        indent=4,
        default=str
    )

print("=" * 100)
print("PART B12 — CONFIGURATION SNAPSHOT")
print("=" * 100)

print(
    f"Configuration snapshot saved to:\n"
    f"{CONFIG_SNAPSHOT_PATH}"
)

====================================================================================================
PART B12 — CONFIGURATION SNAPSHOT
====================================================================================================
Configuration snapshot saved to:
/content/drive/MyDrive/SPP_GAN_Project/metadata/dp_ctgan/dp_ctgan_configuration.json

In [101]:
# ==============================================================================
# PART B13 — PROJECT CONFIGURATION VERIFICATION
# ==============================================================================

PROJECT_CONFIGURATION_VERIFICATION = {

    "Project Root Exists":
        PROJECT_ROOT.exists(),

    "config.yaml Exists":
        CONFIG_PATH.exists(),

    "Configuration Loaded":
        CONFIG is not None,

    "Required Configuration":
        len(MISSING_CONFIG_KEYS) == 0,

    "DP Parameters Valid":
        all(
            DP_VALIDATION.values()
        ),

    "Model Directory":
        DP_CTGAN_MODEL_DIR.exists(),

    "Synthetic Data Directory":
        DP_CTGAN_SYNTHETIC_DIR.exists(),

    "Report Directory":
        DP_CTGAN_REPORT_DIR.exists(),

    "Plot Directory":
        DP_CTGAN_PLOT_DIR.exists(),

    "Metadata Directory":
        DP_CTGAN_METADATA_DIR.exists(),

    "Log Directory":
        DP_CTGAN_LOG_DIR.exists(),

    "Configuration Snapshot":
        CONFIG_SNAPSHOT_PATH.exists(),
}

print("=" * 100)
print("PART B — PROJECT CONFIGURATION VERIFICATION")
print("=" * 100)

for check, status in (
    PROJECT_CONFIGURATION_VERIFICATION.items()
):

    print(
        f"{check:35s}: "
        f"{'PASS' if status else 'FAIL'}"
    )

B_PASSED = sum(
    PROJECT_CONFIGURATION_VERIFICATION.values()
)

B_TOTAL = len(
    PROJECT_CONFIGURATION_VERIFICATION
)

print()
print(
    f"PART B VERIFICATION: "
    f"{B_PASSED}/{B_TOTAL} CHECKS PASSED"
)

if B_PASSED != B_TOTAL:

    raise RuntimeError(
        "PART B project configuration verification failed."
    )

print()
print(
    "PART B — PROJECT CONFIGURATION "
    "COMPLETED SUCCESSFULLY."
)

====================================================================================================
PART B — PROJECT CONFIGURATION VERIFICATION
====================================================================================================
Project Root Exists                : PASS
config.yaml Exists                 : PASS
Configuration Loaded               : PASS
Required Configuration             : PASS
DP Parameters Valid                : PASS
Model Directory                    : PASS
Synthetic Data Directory           : PASS
Report Directory                   : PASS
Plot Directory                     : PASS
Metadata Directory                 : PASS
Log Directory                      : PASS
Configuration Snapshot             : PASS

PART B VERIFICATION: 12/12 CHECKS PASSED

PART B — PROJECT CONFIGURATION COMPLETED SUCCESSFULLY.

In [102]:
# ==============================================================================
# PART C1 — DATASET CONFIGURATION
# ==============================================================================

print("=" * 100)
print("PART C1 — DATASET CONFIGURATION")
print("=" * 100)

DATASETS = [
    "Adult Income",
    "Bank Marketing",
    "diabetes_130us",
]

DATASET_FILE_NAMES = {

    "Adult Income": [
        "adult_income.csv",
        "adult.csv",
        "adult_income_processed.csv",
        "adult_processed.csv",
    ],

    "Bank Marketing": [
        "bank_marketing.csv",
        "bank.csv",
        "bank_marketing_processed.csv",
        "bank_processed.csv",
    ],

    "diabetes_130us": [
        "diabetes_130us.csv",
        "diabetes_130us_processed.csv",
        "diabetic_data.csv",
        "diabetes_processed.csv",
    ],
}

print(
    f"Datasets configured: {len(DATASETS)}"
)

for index, dataset in enumerate(
    DATASETS,
    start=1
):

    print(f"{index}. {dataset}")

====================================================================================================
PART C1 — DATASET CONFIGURATION
====================================================================================================
Datasets configured: 3
1. Adult Income
2. Bank Marketing
3. diabetes_130us

In [103]:
# ==============================================================================
# PART C2 — DATASET FILE DISCOVERY
# ==============================================================================

print("=" * 100)
print("PART C2 — DATASET FILE DISCOVERY")
print("=" * 100)

DATASET_PATHS = {}
DATASET_DISCOVERY = {}

all_csv_files = list(
    PROJECT_ROOT.rglob("*.csv")
)

for dataset in DATASETS:

    DATASET_PATHS[dataset] = None
    DATASET_DISCOVERY[dataset] = False

    candidate_names = {
        name.lower()
        for name in DATASET_FILE_NAMES[dataset]
    }

    # --------------------------------------------------------------------------
    # Exact filename matching
    # --------------------------------------------------------------------------

    exact_matches = [

        path
        for path in all_csv_files
        if path.name.lower() in candidate_names
    ]

    if exact_matches:

        # Prefer processed files when multiple matches exist.
        processed_matches = [

            path
            for path in exact_matches
            if "processed" in path.name.lower()
        ]

        if processed_matches:

            DATASET_PATHS[dataset] = sorted(
                processed_matches,
                key=lambda x: len(str(x))
            )[0]

        else:

            DATASET_PATHS[dataset] = sorted(
                exact_matches,
                key=lambda x: len(str(x))
            )[0]

        DATASET_DISCOVERY[dataset] = True


print()

for dataset in DATASETS:

    path = DATASET_PATHS[dataset]

    if path is not None:

        print(f"{dataset:30s}: FOUND")

        print(f"{'':30s}  {path}")

    else:

        print(f"{dataset:30s}: NOT FOUND")

====================================================================================================
PART C2 — DATASET FILE DISCOVERY
====================================================================================================

Adult Income                  : FOUND
                                /content/drive/MyDrive/SPP_GAN_Project/datasets/processed/adult_income_processed.csv
Bank Marketing                : FOUND
                                /content/drive/MyDrive/SPP_GAN_Project/datasets/processed/bank_marketing_processed.csv
diabetes_130us                : FOUND
                                /content/drive/MyDrive/SPP_GAN_Project/datasets/processed/diabetes_130us_processed.csv

In [104]:
# ==============================================================================
# PART C3 — DATASET DISCOVERY VALIDATION
# ==============================================================================

print("=" * 100)
print("PART C3 — DATASET DISCOVERY VALIDATION")
print("=" * 100)

MISSING_DATASETS = [

    dataset
    for dataset in DATASETS
    if DATASET_PATHS[dataset] is None
]

DATASET_DISCOVERY_VERIFICATION = {

    dataset:
        DATASET_PATHS[dataset] is not None

    for dataset in DATASETS
}

for dataset, status in (
    DATASET_DISCOVERY_VERIFICATION.items()
):

    print(
        f"{dataset:30s}: "
        f"{'PASS' if status else 'FAIL'}"
    )

if MISSING_DATASETS:

    print()
    print(
        "The following datasets could not be located:"
    )

    for dataset in MISSING_DATASETS:

        print(
            f"  - {dataset}"
        )

    print()
    print(
        "Available CSV files in the project:"
    )

    for path in sorted(all_csv_files):

        print(
            f"  - {path}"
        )

    raise FileNotFoundError(
        "One or more required datasets could not be located."
    )

print()
print("All required datasets were successfully located.")

====================================================================================================
PART C3 — DATASET DISCOVERY VALIDATION
====================================================================================================
Adult Income                  : PASS
Bank Marketing                : PASS
diabetes_130us                : PASS

All required datasets were successfully located.

In [105]:
# ==============================================================================
# PART C4 — LOAD REAL DATASETS
# ==============================================================================

print("=" * 100)
print("PART C4 — LOAD REAL DATASETS")
print("=" * 100)

REAL_DATASETS = {}

for dataset in DATASETS:

    dataset_path = DATASET_PATHS[dataset]

    REAL_DATASETS[dataset] = pd.read_csv(
        dataset_path
    )

    print()
    print(
        f"{dataset}"
    )

    print(
        f"Path       : {dataset_path}"
    )

    print(
        f"Rows       : "
        f"{REAL_DATASETS[dataset].shape[0]:,}"
    )

    print(
        f"Columns    : "
        f"{REAL_DATASETS[dataset].shape[1]:,}"
    )

====================================================================================================
PART C4 — LOAD REAL DATASETS
====================================================================================================

Adult Income
Path       : /content/drive/MyDrive/SPP_GAN_Project/datasets/processed/adult_income_processed.csv
Rows       : 32,515
Columns    : 15

Bank Marketing
Path       : /content/drive/MyDrive/SPP_GAN_Project/datasets/processed/bank_marketing_processed.csv
Rows       : 45,211
Columns    : 17

diabetes_130us
Path       : /content/drive/MyDrive/SPP_GAN_Project/datasets/processed/diabetes_130us_processed.csv
Rows       : 101,766
Columns    : 48

In [106]:
# ==============================================================================
# PART C5 — DATASET STRUCTURAL SUMMARY
# ==============================================================================

print("=" * 100)
print("PART C5 — DATASET STRUCTURAL SUMMARY")
print("=" * 100)

DATASET_SUMMARY = []

for dataset in DATASETS:

    df = REAL_DATASETS[dataset]

    DATASET_SUMMARY.append({

        "Dataset":
            dataset,

        "Rows":
            df.shape[0],

        "Columns":
            df.shape[1],

        "Numeric Features":
            len(
                df.select_dtypes(
                    include=np.number
                ).columns
            ),

        "Categorical Features":
            len(
                df.select_dtypes(
                    exclude=np.number
                ).columns
            ),

        "Missing Values":
            int(
                df.isna().sum().sum()
            ),

        "Duplicate Rows":
            int(
                df.duplicated().sum()
            ),
    })

DATASET_SUMMARY_DF = pd.DataFrame(DATASET_SUMMARY)

display(DATASET_SUMMARY_DF)

====================================================================================================
PART C5 — DATASET STRUCTURAL SUMMARY
====================================================================================================

,Dataset,Rows,Columns,Numeric Features,Categorical Features,Missing Values,Duplicate Rows
0,Adult Income,32515,15,15,0,0,0
1,Bank Marketing,45211,17,17,0,0,0
2,diabetes_130us,101766,48,48,0,0,0

In [107]:
# ==============================================================================
# PART C6 — DATA TYPE INSPECTION
# ==============================================================================

print("=" * 100)
print("PART C6 — DATA TYPE INSPECTION")
print("=" * 100)

DATA_TYPES = {}

for dataset in DATASETS:

    df = REAL_DATASETS[dataset]

    DATA_TYPES[dataset] = (
        df.dtypes.astype(str).to_dict()
    )

    print()
    print("-" * 100)
    print(dataset)
    print("-" * 100)
    print(df.dtypes)

====================================================================================================
PART C6 — DATA TYPE INSPECTION
====================================================================================================

----------------------------------------------------------------------------------------------------
Adult Income
----------------------------------------------------------------------------------------------------
age               float64
workclass           int64
fnlwgt            float64
education           int64
education_num     float64
marital_status      int64
occupation          int64
relationship        int64
race                int64
sex                 int64
capital_gain      float64
capital_loss      float64
hours_per_week    float64
native_country      int64
income              int64
dtype: object

----------------------------------------------------------------------------------------------------
Bank Marketing
----------------------------------------------------------------------------------------------------
age          float64
job            int64
marital        int64
education      int64
default        int64
balance      float64
housing        int64
loan           int64
contact        int64
day          float64
month          int64
duration     float64
campaign     float64
pdays        float64
previous     float64
poutcome       int64
y              int64
dtype: object

----------------------------------------------------------------------------------------------------
diabetes_130us
----------------------------------------------------------------------------------------------------
race                          int64
gender                        int64
age                           int64
weight                        int64
admission_type_id           float64
discharge_disposition_id    float64
admission_source_id         float64
time_in_hospital            float64
payer_code                    int64
medical_specialty             int64
num_lab_procedures          float64
num_procedures              float64
num_medications             float64
number_outpatient           float64
number_emergency            float64
number_inpatient            float64
diag_1                        int64
diag_2                        int64
diag_3                        int64
number_diagnoses            float64
max_glu_serum                 int64
A1Cresult                     int64
metformin                     int64
repaglinide                   int64
nateglinide                   int64
chlorpropamide                int64
glimepiride                   int64
acetohexamide                 int64
glipizide                     int64
glyburide                     int64
tolbutamide                   int64
pioglitazone                  int64
rosiglitazone                 int64
acarbose                      int64
miglitol                      int64
troglitazone                  int64
tolazamide                    int64
examide                       int64
citoglipton                   int64
insulin                       int64
glyburide-metformin           int64
glipizide-metformin           int64
glimepiride-pioglitazone      int64
metformin-rosiglitazone       int64
metformin-pioglitazone        int64
change                        int64
diabetesMed                   int64
readmitted                    int64
dtype: object

In [108]:
# ==============================================================================
# PART C7 — FEATURE TYPE DETECTION
# ==============================================================================

print("=" * 100)
print("PART C7 — FEATURE TYPE DETECTION")
print("=" * 100)

NUMERIC_COLUMNS = {}
CATEGORICAL_COLUMNS = {}

for dataset in DATASETS:

    df = REAL_DATASETS[dataset]

    NUMERIC_COLUMNS[dataset] = list(
        df.select_dtypes(
            include=np.number
        ).columns
    )

    CATEGORICAL_COLUMNS[dataset] = list(
        df.select_dtypes(
            exclude=np.number
        ).columns
    )

    print()
    print(f"{dataset}")

    print(
        f"Numeric Features     : "
        f"{len(NUMERIC_COLUMNS[dataset])}"
    )

    print(
        f"Categorical Features : "
        f"{len(CATEGORICAL_COLUMNS[dataset])}"
    )

====================================================================================================
PART C7 — FEATURE TYPE DETECTION
====================================================================================================

Adult Income
Numeric Features     : 15
Categorical Features : 0

Bank Marketing
Numeric Features     : 17
Categorical Features : 0

diabetes_130us
Numeric Features     : 48
Categorical Features : 0

In [109]:
# ==============================================================================
# PART C8 — DATASET COLUMN INVENTORY
# ==============================================================================

print("=" * 100)
print("PART C8 — DATASET COLUMN INVENTORY")
print("=" * 100)

COLUMN_INVENTORY = {}

for dataset in DATASETS:

    df = REAL_DATASETS[dataset]

    COLUMN_INVENTORY[dataset] = {

        "All Columns":
            list(df.columns),

        "Numeric Columns":
            NUMERIC_COLUMNS[dataset],

        "Categorical Columns":
            CATEGORICAL_COLUMNS[dataset],
    }

    print()
    print("-" * 100)
    print(dataset)
    print("-" * 100)

    print(f"Total Columns: {len(df.columns)}")
    print()
    print("Numeric Columns:")

    for column in NUMERIC_COLUMNS[dataset]:

        print(f"  - {column}")

    print()
    print("Categorical Columns:")

    for column in CATEGORICAL_COLUMNS[dataset]:

        print(f"  - {column}")

====================================================================================================
PART C8 — DATASET COLUMN INVENTORY
====================================================================================================

----------------------------------------------------------------------------------------------------
Adult Income
----------------------------------------------------------------------------------------------------
Total Columns: 15

Numeric Columns:
  - age
  - workclass
  - fnlwgt
  - education
  - education_num
  - marital_status
  - occupation
  - relationship
  - race
  - sex
  - capital_gain
  - capital_loss
  - hours_per_week
  - native_country
  - income

Categorical Columns:

----------------------------------------------------------------------------------------------------
Bank Marketing
----------------------------------------------------------------------------------------------------
Total Columns: 17

Numeric Columns:
  - age
  - job
  - marital
  - education
  - default
  - balance
  - housing
  - loan
  - contact
  - day
  - month
  - duration
  - campaign
  - pdays
  - previous
  - poutcome
  - y

Categorical Columns:

----------------------------------------------------------------------------------------------------
diabetes_130us
----------------------------------------------------------------------------------------------------
Total Columns: 48

Numeric Columns:
  - race
  - gender
  - age
  - weight
  - admission_type_id
  - discharge_disposition_id
  - admission_source_id
  - time_in_hospital
  - payer_code
  - medical_specialty
  - num_lab_procedures
  - num_procedures
  - num_medications
  - number_outpatient
  - number_emergency
  - number_inpatient
  - diag_1
  - diag_2
  - diag_3
  - number_diagnoses
  - max_glu_serum
  - A1Cresult
  - metformin
  - repaglinide
  - nateglinide
  - chlorpropamide
  - glimepiride
  - acetohexamide
  - glipizide
  - glyburide
  - tolbutamide
  - pioglitazone
  - rosiglitazone
  - acarbose
  - miglitol
  - troglitazone
  - tolazamide
  - examide
  - citoglipton
  - insulin
  - glyburide-metformin
  - glipizide-metformin
  - glimepiride-pioglitazone
  - metformin-rosiglitazone
  - metformin-pioglitazone
  - change
  - diabetesMed
  - readmitted

Categorical Columns:

In [110]:
# ==============================================================================
# PART C9 — DATA QUALITY VALIDATION
# ==============================================================================

print("=" * 100)
print("PART C9 — DATA QUALITY VALIDATION")
print("=" * 100)

DATA_QUALITY_RESULTS = {}

for dataset in DATASETS:

    df = REAL_DATASETS[dataset]

    missing_values = int(
        df.isna().sum().sum()
    )

    duplicate_rows = int(
        df.duplicated().sum()
    )

    DATA_QUALITY_RESULTS[dataset] = {

        "Missing Values":
            missing_values,

        "Duplicate Rows":
            duplicate_rows,

        "Rows":
            len(df),

        "Columns":
            len(df.columns),
    }

    print()
    print(dataset)

    print(
        f"Missing Values : "
        f"{missing_values:,}"
    )

    print(
        f"Duplicate Rows : "
        f"{duplicate_rows:,}"
    )

====================================================================================================
PART C9 — DATA QUALITY VALIDATION
====================================================================================================

Adult Income
Missing Values : 0
Duplicate Rows : 0

Bank Marketing
Missing Values : 0
Duplicate Rows : 0

diabetes_130us
Missing Values : 0
Duplicate Rows : 0

In [111]:
# ==============================================================================
# PART C10 — DATASET PREVIEW
# ==============================================================================

print("=" * 100)
print("PART C10 — DATASET PREVIEW")
print("=" * 100)

for dataset in DATASETS:

    print()
    print("-" * 100)
    print(dataset)
    print("-" * 100)

    display(REAL_DATASETS[dataset].head())

====================================================================================================
PART C10 — DATASET PREVIEW
====================================================================================================

----------------------------------------------------------------------------------------------------
Adult Income
----------------------------------------------------------------------------------------------------

,age,workclass,fnlwgt,education,education_num,marital_status,occupation,relationship,race,sex,capital_gain,capital_loss,hours_per_week,native_country,income
0,0.360656,7,0.161680,9,0.739130,4,1,1,4,1,0.02174,0.0,0.375,39,0
1,0.540984,6,0.176044,9,0.739130,2,4,0,4,1,0.00000,0.0,0.000,39,0
2,0.344262,4,0.504046,11,0.391304,0,6,1,4,1,0.00000,0.0,0.375,39,0
3,0.590164,4,0.551325,1,0.217391,2,6,0,2,1,0.00000,0.0,0.375,39,0
4,0.180328,4,0.808324,9,0.739130,2,10,5,2,0,0.00000,0.0,0.375,5,0

----------------------------------------------------------------------------------------------------
Bank Marketing
----------------------------------------------------------------------------------------------------

,age,job,marital,education,default,balance,housing,loan,contact,day,month,duration,campaign,pdays,previous,poutcome,y
0,0.761905,4,1,2,0,0.756822,1,0,2,0.133333,8,0.405910,0.0,0.0,0.0,3,0
1,0.495238,9,2,1,0,0.367072,1,0,2,0.133333,8,0.234837,0.0,0.0,0.0,3,0
2,0.285714,2,1,1,0,0.362094,1,1,2,0.133333,8,0.118196,0.0,0.0,0.0,3,0
3,0.552381,1,1,3,0,0.639381,1,0,2,0.133333,8,0.143079,0.0,0.0,0.0,3,0
4,0.285714,11,2,3,0,0.361910,0,0,2,0.133333,8,0.307932,0.0,0.0,0.0,3,0

----------------------------------------------------------------------------------------------------
diabetes_130us
----------------------------------------------------------------------------------------------------

,race,gender,age,weight,admission_type_id,discharge_disposition_id,admission_source_id,time_in_hospital,payer_code,medical_specialty,...,citoglipton,insulin,glyburide-metformin,glipizide-metformin,glimepiride-pioglitazone,metformin-rosiglitazone,metformin-pioglitazone,change,diabetesMed,readmitted
0,2,0,0,8,1.0,1.0,0.0,0.000000,7,37,...,0,1,1,0,0,0,0,1,0,2
1,2,0,1,8,0.0,0.0,0.4,0.181818,7,18,...,0,3,1,0,0,0,0,0,1,1
2,0,0,2,8,0.0,0.0,0.4,0.090909,7,18,...,0,1,1,0,0,0,0,1,1,2
3,2,1,3,8,0.0,0.0,0.4,0.090909,7,18,...,0,3,1,0,0,0,0,0,1,2
4,2,1,4,8,0.0,0.0,0.4,0.000000,7,18,...,0,2,1,0,0,0,0,0,1,2

In [112]:
# ==============================================================================
# PART C11 — DATASET LOADING VERIFICATION
# ==============================================================================

print("=" * 100)
print("PART C11 — DATASET LOADING VERIFICATION")
print("=" * 100)

DATASET_LOADING_VERIFICATION = {}

for dataset in DATASETS:

    df = REAL_DATASETS.get(
        dataset
    )

    DATASET_LOADING_VERIFICATION[dataset] = (

        df is not None

        and isinstance(
            df,
            pd.DataFrame
        )

        and len(df) > 0

        and len(df.columns) > 0
    )

for dataset, status in (
    DATASET_LOADING_VERIFICATION.items()
):

    print(
        f"{dataset:30s}: "
        f"{'PASS' if status else 'FAIL'}"
    )

C_PASSED = sum(
    DATASET_LOADING_VERIFICATION.values()
)

C_TOTAL = len(
    DATASET_LOADING_VERIFICATION
)

print()
print(
    f"PART C VERIFICATION: "
    f"{C_PASSED}/{C_TOTAL} DATASETS PASSED"
)

if C_PASSED != C_TOTAL:

    raise RuntimeError(
        "PART C dataset loading verification failed."
    )

print()
print(
    "PART C — DATASET LOADING "
    "COMPLETED SUCCESSFULLY."
)

====================================================================================================
PART C11 — DATASET LOADING VERIFICATION
====================================================================================================
Adult Income                  : PASS
Bank Marketing                : PASS
diabetes_130us                : PASS

PART C VERIFICATION: 3/3 DATASETS PASSED

PART C — DATASET LOADING COMPLETED SUCCESSFULLY.

In [113]:
# ==============================================================================
# PART D1 — DATASET PREPARATION CONFIGURATION
# ==============================================================================

print("=" * 100)
print("PART D1 — DATASET PREPARATION CONFIGURATION")
print("=" * 100)

# --------------------------------------------------------------------------
# Reproducibility
# --------------------------------------------------------------------------

SPLIT_SEED = SEED

# --------------------------------------------------------------------------
# Dataset split ratios
# --------------------------------------------------------------------------

TRAIN_SIZE = 0.70
VALIDATION_SIZE = 0.15
TEST_SIZE = 0.15

# --------------------------------------------------------------------------
# Validation
# --------------------------------------------------------------------------

if not np.isclose(
    TRAIN_SIZE + VALIDATION_SIZE + TEST_SIZE,
    1.0
):
    raise ValueError(
        "Train, validation, and test proportions must sum to 1.0."
    )

print(f"Training Ratio   : {TRAIN_SIZE:.2f}")

print(f"Validation Ratio : {VALIDATION_SIZE:.2f}")

print(f"Testing Ratio    : {TEST_SIZE:.2f}")

print(f"Split Seed       : {SPLIT_SEED}")

====================================================================================================
PART D1 — DATASET PREPARATION CONFIGURATION
====================================================================================================
Training Ratio   : 0.70
Validation Ratio : 0.15
Testing Ratio    : 0.15
Split Seed       : 42

In [114]:
# ==============================================================================
# PART D2 — TARGET VARIABLE CONFIGURATION
# ==============================================================================

print("=" * 100)
print("PART D2 — TARGET VARIABLE CONFIGURATION")
print("=" * 100)

TARGET_CANDIDATES = {

    "Adult Income": [
        "income",
        "target",
        "class",
        "label",
        "income_target",
    ],

    "Bank Marketing": [
        "y",
        "target",
        "class",
        "label",
        "deposit",
    ],

    "diabetes_130us": [
        "readmitted",
        "target",
        "class",
        "label",
    ],
}

TARGET_COLUMNS = {}

for dataset in DATASETS:

    df = REAL_DATASETS[dataset]

    detected_candidates = [
        column
        for column in TARGET_CANDIDATES[dataset]
        if column in df.columns
    ]

    print()
    print(f"{dataset}")

    print(
        f"Candidate Target Columns: "
        f"{detected_candidates}"
    )

    if len(detected_candidates) == 1:

        TARGET_COLUMNS[dataset] = (
            detected_candidates[0]
        )

    elif len(detected_candidates) == 0:

        TARGET_COLUMNS[dataset] = None

        print(
            "WARNING: No target column was automatically "
            "identified."
        )

    else:

        TARGET_COLUMNS[dataset] = None

        print(
            "WARNING: Multiple possible target columns "
            "were identified."
        )

print()
print("Current Target Configuration:")

for dataset, target in TARGET_COLUMNS.items():

    print(f"{dataset:25s}: {target}")

====================================================================================================
PART D2 — TARGET VARIABLE CONFIGURATION
====================================================================================================

Adult Income
Candidate Target Columns: ['income']

Bank Marketing
Candidate Target Columns: ['y']

diabetes_130us
Candidate Target Columns: ['readmitted']

Current Target Configuration:
Adult Income             : income
Bank Marketing           : y
diabetes_130us           : readmitted

In [115]:
# ==============================================================================
# PART D3 — FEATURE AND TARGET SEPARATION
# ==============================================================================

print("=" * 100)
print("PART D4 — FEATURE AND TARGET SEPARATION")
print("=" * 100)

FEATURE_DATASETS = {}
TARGET_DATASETS = {}

for dataset in DATASETS:

    df = REAL_DATASETS[dataset]

    target_column = TARGET_COLUMNS[dataset]

    FEATURE_DATASETS[dataset] = (
        df.drop(
            columns=[target_column]
        ).copy()
    )

    TARGET_DATASETS[dataset] = (
        df[target_column].copy()
    )

    print()
    print(dataset)

    print(
        f"Features : "
        f"{FEATURE_DATASETS[dataset].shape}"
    )

    print(
        f"Target   : "
        f"{TARGET_DATASETS[dataset].shape}"
    )

    print(
        f"Target Column: "
        f"{target_column}"
    )

====================================================================================================
PART D4 — FEATURE AND TARGET SEPARATION
====================================================================================================

Adult Income
Features : (32515, 14)
Target   : (32515,)
Target Column: income

Bank Marketing
Features : (45211, 16)
Target   : (45211,)
Target Column: y

diabetes_130us
Features : (101766, 47)
Target   : (101766,)
Target Column: readmitted

In [116]:
# ==============================================================================
# PART D4 — TRAIN / VALIDATION / TEST SPLITTING
# ==============================================================================

print("=" * 100)
print("PART D6 — TRAIN / VALIDATION / TEST SPLITTING")
print("=" * 100)

TRAIN_DATASETS = {}
VALIDATION_DATASETS = {}
TEST_DATASETS = {}

TRAIN_ROW_IDS = {}
VALIDATION_ROW_IDS = {}
TEST_ROW_IDS = {}

for dataset in DATASETS:

    df = REAL_DATASETS[dataset].copy()

    target_column = TARGET_COLUMNS[dataset]

    # --------------------------------------------------------------------------
    # Preserve original row identity BEFORE splitting.
    # --------------------------------------------------------------------------

    df["_ORIGINAL_ROW_ID_"] = np.arange(
        len(df)
    )

    # --------------------------------------------------------------------------
    # First split:
    # 70% training
    # 30% temporary
    # --------------------------------------------------------------------------

    train_df, temp_df = train_test_split(
        df,
        test_size=(
            VALIDATION_SIZE + TEST_SIZE
        ),
        random_state=SPLIT_SEED,
        stratify=df[target_column]
    )

    # --------------------------------------------------------------------------
    # Second split:
    # 15% validation
    # 15% test
    # --------------------------------------------------------------------------

    relative_test_size = (
        TEST_SIZE
        /
        (VALIDATION_SIZE + TEST_SIZE)
    )

    validation_df, test_df = train_test_split(
        temp_df,
        test_size=relative_test_size,
        random_state=SPLIT_SEED,
        stratify=temp_df[target_column]
    )

    # --------------------------------------------------------------------------
    # Store original row IDs BEFORE resetting the dataframe index.
    # --------------------------------------------------------------------------

    TRAIN_ROW_IDS[dataset] = set(
        train_df["_ORIGINAL_ROW_ID_"]
    )

    VALIDATION_ROW_IDS[dataset] = set(
        validation_df["_ORIGINAL_ROW_ID_"]
    )

    TEST_ROW_IDS[dataset] = set(
        test_df["_ORIGINAL_ROW_ID_"]
    )

    # --------------------------------------------------------------------------
    # Remove technical row-ID column from modeling datasets.
    # --------------------------------------------------------------------------

    train_df = train_df.drop(
        columns=["_ORIGINAL_ROW_ID_"]
    )

    validation_df = validation_df.drop(
        columns=["_ORIGINAL_ROW_ID_"]
    )

    test_df = test_df.drop(
        columns=["_ORIGINAL_ROW_ID_"]
    )

    # --------------------------------------------------------------------------
    # Reset dataframe indexes.
    # --------------------------------------------------------------------------

    TRAIN_DATASETS[dataset] = (
        train_df.reset_index(
            drop=True
        )
    )

    VALIDATION_DATASETS[dataset] = (
        validation_df.reset_index(
            drop=True
        )
    )

    TEST_DATASETS[dataset] = (
        test_df.reset_index(
            drop=True
        )
    )

    print()
    print(dataset)

    print(
        f"Training   : "
        f"{len(TRAIN_DATASETS[dataset]):,}"
    )

    print(
        f"Validation : "
        f"{len(VALIDATION_DATASETS[dataset]):,}"
    )

    print(
        f"Testing    : "
        f"{len(TEST_DATASETS[dataset]):,}"
    )

====================================================================================================
PART D6 — TRAIN / VALIDATION / TEST SPLITTING
====================================================================================================

Adult Income
Training   : 22,760
Validation : 4,877
Testing    : 4,878

Bank Marketing
Training   : 31,647
Validation : 6,782
Testing    : 6,782

diabetes_130us
Training   : 71,236
Validation : 15,265
Testing    : 15,265

In [117]:
# ==============================================================================
# PART D5 — SPLIT SIZE VERIFICATION
# ==============================================================================

print("=" * 100)
print("PART D7 — SPLIT SIZE VERIFICATION")
print("=" * 100)

SPLIT_VERIFICATION = {}

for dataset in DATASETS:

    original_rows = len(
        REAL_DATASETS[dataset]
    )

    train_rows = len(
        TRAIN_DATASETS[dataset]
    )

    validation_rows = len(
        VALIDATION_DATASETS[dataset]
    )

    test_rows = len(
        TEST_DATASETS[dataset]
    )

    total_split_rows = (
        train_rows
        + validation_rows
        + test_rows
    )

    SPLIT_VERIFICATION[dataset] = (
        total_split_rows == original_rows
    )

    print()
    print(dataset)

    print(
        f"Original Rows : "
        f"{original_rows:,}"
    )

    print(
        f"Train Rows    : "
        f"{train_rows:,}"
    )

    print(
        f"Validation    : "
        f"{validation_rows:,}"
    )

    print(
        f"Test Rows     : "
        f"{test_rows:,}"
    )

    print(
        f"Total Split   : "
        f"{total_split_rows:,}"
    )

    print(
        f"Verification  : "
        f"{'PASS' if SPLIT_VERIFICATION[dataset] else 'FAIL'}"
    )

if not all(
    SPLIT_VERIFICATION.values()
):

    raise RuntimeError(
        "Dataset split size verification failed."
    )

====================================================================================================
PART D7 — SPLIT SIZE VERIFICATION
====================================================================================================

Adult Income
Original Rows : 32,515
Train Rows    : 22,760
Validation    : 4,877
Test Rows     : 4,878
Total Split   : 32,515
Verification  : PASS

Bank Marketing
Original Rows : 45,211
Train Rows    : 31,647
Validation    : 6,782
Test Rows     : 6,782
Total Split   : 45,211
Verification  : PASS

diabetes_130us
Original Rows : 101,766
Train Rows    : 71,236
Validation    : 15,265
Test Rows     : 15,265
Total Split   : 101,766
Verification  : PASS

In [118]:
# ==============================================================================
# PART D6 — DATA LEAKAGE VERIFICATION
# ==============================================================================

print("=" * 100)
print("PART D8 — DATA LEAKAGE VERIFICATION")
print("=" * 100)

LEAKAGE_VERIFICATION = {}

for dataset in DATASETS:

    train_ids = TRAIN_ROW_IDS[dataset]

    validation_ids = VALIDATION_ROW_IDS[dataset]

    test_ids = TEST_ROW_IDS[dataset]

    # --------------------------------------------------------------------------
    # Check pairwise overlap using ORIGINAL row identities.
    # --------------------------------------------------------------------------

    train_validation_overlap = (
        train_ids
        &
        validation_ids
    )

    train_test_overlap = (
        train_ids
        &
        test_ids
    )

    validation_test_overlap = (
        validation_ids
        &
        test_ids
    )

    # --------------------------------------------------------------------------
    # Check that every original row belongs to exactly one split.
    # --------------------------------------------------------------------------

    all_split_ids = (
        train_ids
        |
        validation_ids
        |
        test_ids
    )

    expected_ids = set(
        range(
            len(
                REAL_DATASETS[dataset]
            )
        )
    )

    complete_partition = (
        all_split_ids == expected_ids
    )

    no_overlap = (
        len(train_validation_overlap) == 0
        and
        len(train_test_overlap) == 0
        and
        len(validation_test_overlap) == 0
    )

    leakage_free = (
        no_overlap
        and
        complete_partition
    )

    LEAKAGE_VERIFICATION[dataset] = (
        leakage_free
    )

    print()
    print(dataset)
    print("-" * 100)

    print(
        f"Train ↔ Validation : "
        f"{len(train_validation_overlap)}"
    )

    print(
        f"Train ↔ Test       : "
        f"{len(train_test_overlap)}"
    )

    print(
        f"Validation ↔ Test  : "
        f"{len(validation_test_overlap)}"
    )

    print(
        f"Original Rows      : "
        f"{len(expected_ids):,}"
    )

    print(
        f"Assigned Rows      : "
        f"{len(all_split_ids):,}"
    )

    print(
        f"Complete Partition  : "
        f"{'PASS' if complete_partition else 'FAIL'}"
    )

    print(
        f"Leakage Check       : "
        f"{'PASS' if leakage_free else 'FAIL'}"
    )

if not all(
    LEAKAGE_VERIFICATION.values()
):

    raise RuntimeError(
        "Data leakage detected between dataset splits."
    )

print()
print(
    "All datasets passed the data leakage verification."
)

====================================================================================================
PART D8 — DATA LEAKAGE VERIFICATION
====================================================================================================

Adult Income
----------------------------------------------------------------------------------------------------
Train ↔ Validation : 0
Train ↔ Test       : 0
Validation ↔ Test  : 0
Original Rows      : 32,515
Assigned Rows      : 32,515
Complete Partition  : PASS
Leakage Check       : PASS

Bank Marketing
----------------------------------------------------------------------------------------------------
Train ↔ Validation : 0
Train ↔ Test       : 0
Validation ↔ Test  : 0
Original Rows      : 45,211
Assigned Rows      : 45,211
Complete Partition  : PASS
Leakage Check       : PASS

diabetes_130us
----------------------------------------------------------------------------------------------------
Train ↔ Validation : 0
Train ↔ Test       : 0
Validation ↔ Test  : 0
Original Rows      : 101,766
Assigned Rows      : 101,766
Complete Partition  : PASS
Leakage Check       : PASS

All datasets passed the data leakage verification.

In [119]:
# ==============================================================================
# PART D7 — TRAINING FEATURE TYPE IDENTIFICATION
# ==============================================================================

print("=" * 100)
print("PART D9 — TRAINING FEATURE TYPE IDENTIFICATION")
print("=" * 100)

TRAIN_NUMERIC_COLUMNS = {}
TRAIN_CATEGORICAL_COLUMNS = {}

for dataset in DATASETS:

    train_df = TRAIN_DATASETS[dataset]

    target_column = TARGET_COLUMNS[dataset]

    feature_df = train_df.drop(
        columns=[target_column]
    )

    TRAIN_NUMERIC_COLUMNS[dataset] = list(
        feature_df.select_dtypes(
            include=np.number
        ).columns
    )

    TRAIN_CATEGORICAL_COLUMNS[dataset] = list(
        feature_df.select_dtypes(
            exclude=np.number
        ).columns
    )

    print()
    print(dataset)

    print(
        f"Numeric Features     : "
        f"{len(TRAIN_NUMERIC_COLUMNS[dataset])}"
    )

    print(
        f"Categorical Features : "
        f"{len(TRAIN_CATEGORICAL_COLUMNS[dataset])}"
    )

====================================================================================================
PART D9 — TRAINING FEATURE TYPE IDENTIFICATION
====================================================================================================

Adult Income
Numeric Features     : 14
Categorical Features : 0

Bank Marketing
Numeric Features     : 16
Categorical Features : 0

diabetes_130us
Numeric Features     : 47
Categorical Features : 0

In [120]:
# ==============================================================================
# PART D8 — NUMERICAL FEATURE PREPARATION
# ==============================================================================

print("=" * 100)
print("PART D10 — NUMERICAL FEATURE PREPARATION")
print("=" * 100)

NUMERIC_SCALERS = {}

SCALED_NUMERIC_DATASETS = {}
SCALED_VALIDATION_NUMERIC_DATASETS = {}
SCALED_TEST_NUMERIC_DATASETS = {}

for dataset in DATASETS:

    train_df = TRAIN_DATASETS[dataset]
    validation_df = VALIDATION_DATASETS[dataset]
    test_df = TEST_DATASETS[dataset]

    numeric_columns = (
        TRAIN_NUMERIC_COLUMNS[dataset]
    )

    scaler = StandardScaler()

    NUMERIC_SCALERS[dataset] = scaler

    # --------------------------------------------------------------------------
    # Fit ONLY on training data.
    # --------------------------------------------------------------------------

    train_numeric = train_df[
        numeric_columns
    ]

    scaler.fit(
        train_numeric
    )

    # --------------------------------------------------------------------------
    # Transform all splits using the training-fitted scaler.
    # --------------------------------------------------------------------------

    train_scaled = scaler.transform(
        train_numeric
    )

    validation_scaled = scaler.transform(
        validation_df[
            numeric_columns
        ]
    )

    test_scaled = scaler.transform(
        test_df[
            numeric_columns
        ]
    )

    SCALED_NUMERIC_DATASETS[dataset] = (
        pd.DataFrame(
            train_scaled,
            columns=numeric_columns
        )
    )

    SCALED_VALIDATION_NUMERIC_DATASETS[dataset] = (
        pd.DataFrame(
            validation_scaled,
            columns=numeric_columns
        )
    )

    SCALED_TEST_NUMERIC_DATASETS[dataset] = (
        pd.DataFrame(
            test_scaled,
            columns=numeric_columns
        )
    )

    print()
    print(
        f"{dataset}: "
        f"{len(numeric_columns)} numeric features prepared."
    )

====================================================================================================
PART D10 — NUMERICAL FEATURE PREPARATION
====================================================================================================

Adult Income: 14 numeric features prepared.

Bank Marketing: 16 numeric features prepared.

diabetes_130us: 47 numeric features prepared.

In [121]:
# ==============================================================================
# PART D9 — CATEGORICAL FEATURE DOMAIN PREPARATION
# ==============================================================================

print("=" * 100)
print("PART D11 — CATEGORICAL FEATURE DOMAIN PREPARATION")
print("=" * 100)

CATEGORICAL_DOMAINS = {}

for dataset in DATASETS:

    train_df = TRAIN_DATASETS[dataset]

    categorical_columns = (
        TRAIN_CATEGORICAL_COLUMNS[dataset]
    )

    CATEGORICAL_DOMAINS[dataset] = {}

    for column in categorical_columns:

        categories = (
            train_df[column]
            .astype("string")
            .fillna("__MISSING__")
            .unique()
            .tolist()
        )

        CATEGORICAL_DOMAINS[dataset][column] = (
            categories
        )

    print()
    print(dataset)

    for column, categories in (
        CATEGORICAL_DOMAINS[dataset].items()
    ):

        print(
            f"{column:30s}: "
            f"{len(categories)} categories"
        )

====================================================================================================
PART D11 — CATEGORICAL FEATURE DOMAIN PREPARATION
====================================================================================================

Adult Income

Bank Marketing

diabetes_130us

In [122]:
# ==============================================================================
# PART D10 — MISSING VALUE PREPARATION
# ==============================================================================

print("=" * 100)
print("PART D12 — MISSING VALUE PREPARATION")
print("=" * 100)

NUMERIC_IMPUTATION_VALUES = {}
CATEGORICAL_MISSING_TOKEN = "__MISSING__"

for dataset in DATASETS:

    train_df = TRAIN_DATASETS[dataset]

    numeric_columns = (
        TRAIN_NUMERIC_COLUMNS[dataset]
    )

    NUMERIC_IMPUTATION_VALUES[dataset] = {}

    for column in numeric_columns:

        median_value = (
            train_df[column]
            .median()
        )

        NUMERIC_IMPUTATION_VALUES[
            dataset
        ][column] = median_value

    print()
    print(
        f"{dataset}: "
        f"Numeric imputation parameters calculated."
    )

print()
print(
    f"Categorical Missing Token: "
    f"{CATEGORICAL_MISSING_TOKEN}"
)

====================================================================================================
PART D12 — MISSING VALUE PREPARATION
====================================================================================================

Adult Income: Numeric imputation parameters calculated.

Bank Marketing: Numeric imputation parameters calculated.

diabetes_130us: Numeric imputation parameters calculated.

Categorical Missing Token: __MISSING__

In [123]:
# ==============================================================================
# PART D11 — FEATURE METADATA CONSTRUCTION
# ==============================================================================

print("=" * 100)
print("PART D11 — FEATURE METADATA CONSTRUCTION")
print("=" * 100)

FEATURE_METADATA = {}

for dataset in DATASETS:

    feature_metadata = {

        "target_column":
            TARGET_COLUMNS[dataset],

        "numeric_columns":
            TRAIN_NUMERIC_COLUMNS[dataset],

        "categorical_columns":
            TRAIN_CATEGORICAL_COLUMNS[dataset],

        "categorical_domains":
            CATEGORICAL_DOMAINS[dataset],

        "numeric_imputation_values":
            NUMERIC_IMPUTATION_VALUES[dataset],

        "categorical_missing_token":
            CATEGORICAL_MISSING_TOKEN,
    }

    FEATURE_METADATA[dataset] = (
        feature_metadata
    )

    print()
    print(dataset)

    print(
        f"Target Column       : "
        f"{feature_metadata['target_column']}"
    )

    print(
        f"Numeric Features    : "
        f"{len(feature_metadata['numeric_columns'])}"
    )

    print(
        f"Categorical Features: "
        f"{len(feature_metadata['categorical_columns'])}"
    )

====================================================================================================
PART D11 — FEATURE METADATA CONSTRUCTION
====================================================================================================

Adult Income
Target Column       : income
Numeric Features    : 14
Categorical Features: 0

Bank Marketing
Target Column       : y
Numeric Features    : 16
Categorical Features: 0

diabetes_130us
Target Column       : readmitted
Numeric Features    : 47
Categorical Features: 0

In [124]:
# ==============================================================================
# PART D12 — DATASET SPLIT SUMMARY
# ==============================================================================

print("=" * 100)
print("PART D12 — DATASET SPLIT SUMMARY")
print("=" * 100)

SPLIT_SUMMARY = []

for dataset in DATASETS:

    original_rows = len(
        REAL_DATASETS[dataset]
    )

    train_rows = len(
        TRAIN_DATASETS[dataset]
    )

    validation_rows = len(
        VALIDATION_DATASETS[dataset]
    )

    test_rows = len(
        TEST_DATASETS[dataset]
    )

    SPLIT_SUMMARY.append({

        "Dataset":
            dataset,

        "Original Rows":
            original_rows,

        "Training Rows":
            train_rows,

        "Validation Rows":
            validation_rows,

        "Test Rows":
            test_rows,

        "Training %":
            round(
                train_rows
                /
                original_rows
                * 100,
                2
            ),

        "Validation %":
            round(
                validation_rows
                /
                original_rows
                * 100,
                2
            ),

        "Test %":
            round(
                test_rows
                /
                original_rows
                * 100,
                2
            ),

        "Numeric Features":
            len(
                TRAIN_NUMERIC_COLUMNS[dataset]
            ),

        "Categorical Features":
            len(
                TRAIN_CATEGORICAL_COLUMNS[dataset]
            ),
    })

SPLIT_SUMMARY_DF = pd.DataFrame(SPLIT_SUMMARY)

display(SPLIT_SUMMARY_DF)

====================================================================================================
PART D12 — DATASET SPLIT SUMMARY
====================================================================================================

,Dataset,Original Rows,Training Rows,Validation Rows,Test Rows,Training %,Validation %,Test %,Numeric Features,Categorical Features
0,Adult Income,32515,22760,4877,4878,70.0,15.0,15.0,14,0
1,Bank Marketing,45211,31647,6782,6782,70.0,15.0,15.0,16,0
2,diabetes_130us,101766,71236,15265,15265,70.0,15.0,15.0,47,0

In [125]:
# ==============================================================================
# PART D13 — DATASET AND FEATURE PREPARATION VERIFICATION
# ==============================================================================

print("=" * 100)
print("PART D13 — DATASET AND FEATURE PREPARATION VERIFICATION")
print("=" * 100)

PREPARATION_VERIFICATION = {

    "All Datasets Loaded":
        all(
            dataset in REAL_DATASETS
            for dataset in DATASETS
        ),

    "All Training Splits Created":
        all(
            len(TRAIN_DATASETS[dataset]) > 0
            for dataset in DATASETS
        ),

    "All Validation Splits Created":
        all(
            len(VALIDATION_DATASETS[dataset]) > 0
            for dataset in DATASETS
        ),

    "All Test Splits Created":
        all(
            len(TEST_DATASETS[dataset]) > 0
            for dataset in DATASETS
        ),

    "Split Sizes Verified":
        all(
            SPLIT_VERIFICATION.values()
        ),

    "No Data Leakage":
        all(
            LEAKAGE_VERIFICATION.values()
        ),

    "Feature Metadata Created":
        len(FEATURE_METADATA) == len(DATASETS),
       }

for check, status in (
    PREPARATION_VERIFICATION.items()
):

    print(
        f"{check:35s}: "
        f"{'PASS' if status else 'FAIL'}"
    )

D_PASSED = sum(
    PREPARATION_VERIFICATION.values()
)

D_TOTAL = len(
    PREPARATION_VERIFICATION
)

print()
print(
    f"PART D VERIFICATION: "
    f"{D_PASSED}/{D_TOTAL} CHECKS PASSED"
)

if D_PASSED != D_TOTAL:

    raise RuntimeError(
        "PART D dataset and feature preparation verification failed."
    )

print()
print(
    "PART D — DATASET AND FEATURE PREPARATION "
    "COMPLETED SUCCESSFULLY."
)

====================================================================================================
PART D13 — DATASET AND FEATURE PREPARATION VERIFICATION
====================================================================================================
All Datasets Loaded                : PASS
All Training Splits Created        : PASS
All Validation Splits Created      : PASS
All Test Splits Created            : PASS
Split Sizes Verified               : PASS
No Data Leakage                    : PASS
Feature Metadata Created           : PASS

PART D VERIFICATION: 7/7 CHECKS PASSED

PART D — DATASET AND FEATURE PREPARATION COMPLETED SUCCESSFULLY.

In [126]:
# ==============================================================================
# PART E1 — DIFFERENTIAL PRIVACY PARAMETER CONFIGURATION
# ==============================================================================

print("=" * 100)
print("PART E1 — DIFFERENTIAL PRIVACY PARAMETER CONFIGURATION")
print("=" * 100)

PRIVACY_BUDGET = 4.0
PRIVACY_DELTA = 1e-5
NOISE_MULTIPLIER = 1.1
MAX_GRAD_NORM = 1.0

print(f"Privacy Budget (ε) : {PRIVACY_BUDGET}")
print(f"Privacy Delta (δ)  : {PRIVACY_DELTA}")
print(f"Noise Multiplier   : {NOISE_MULTIPLIER}")
print(f"Max Gradient Norm  : {MAX_GRAD_NORM}")

====================================================================================================
PART E1 — DIFFERENTIAL PRIVACY PARAMETER CONFIGURATION
====================================================================================================
Privacy Budget (ε) : 4.0
Privacy Delta (δ)  : 1e-05
Noise Multiplier   : 1.1
Max Gradient Norm  : 1.0

In [127]:
# ==============================================================================
# PART E2 — DP-CTGAN TRAINING CONFIGURATION
# ==============================================================================

print("=" * 100)
print("PART E2 — DP-CTGAN TRAINING CONFIGURATION")
print("=" * 100)

DP_EPOCHS = 100
DP_BATCH_SIZE = 256
DP_LEARNING_RATE = 0.0002
DP_BETA1 = 0.5
DP_BETA2 = 0.999
DP_LATENT_DIMENSION = 128

print(f"DP Epochs          : {DP_EPOCHS}")
print(f"DP Batch Size      : {DP_BATCH_SIZE}")
print(f"Learning Rate      : {DP_LEARNING_RATE}")
print(f"Adam Beta 1        : {DP_BETA1}")
print(f"Adam Beta 2        : {DP_BETA2}")
print(f"Latent Dimension   : {DP_LATENT_DIMENSION}")

====================================================================================================
PART E2 — DP-CTGAN TRAINING CONFIGURATION
====================================================================================================
DP Epochs          : 100
DP Batch Size      : 256
Learning Rate      : 0.0002
Adam Beta 1        : 0.5
Adam Beta 2        : 0.999
Latent Dimension   : 128

In [128]:
# ==============================================================================
# PART E3 — PRIVACY ACCOUNTANT CONFIGURATION
# ==============================================================================

print("=" * 100)
print("PART E3 — PRIVACY ACCOUNTANT CONFIGURATION")
print("=" * 100)

DP_ACCOUNTANT = "rdp"

print(
    f"Privacy Accountant : {DP_ACCOUNTANT.upper()}"
)

if DP_ACCOUNTANT.lower() != "rdp":
    raise ValueError(
        "Unsupported privacy accountant. "
        "This implementation requires RDP."
    )

print("Privacy accountant configuration verified.")

====================================================================================================
PART E3 — PRIVACY ACCOUNTANT CONFIGURATION
====================================================================================================
Privacy Accountant : RDP
Privacy accountant configuration verified.

In [129]:
# ==============================================================================
# PART E4 — DIFFERENTIAL PRIVACY CONFIGURATION DICTIONARY
# ==============================================================================

print("=" * 100)
print("PART E4 — DIFFERENTIAL PRIVACY CONFIGURATION DICTIONARY")
print("=" * 100)

DP_CONFIG = {
    "privacy_budget_epsilon": PRIVACY_BUDGET,
    "privacy_delta": PRIVACY_DELTA,
    "noise_multiplier": NOISE_MULTIPLIER,
    "max_grad_norm": MAX_GRAD_NORM,
    "accountant": DP_ACCOUNTANT,
    "epochs": DP_EPOCHS,
    "batch_size": DP_BATCH_SIZE,
    "learning_rate": DP_LEARNING_RATE,
    "beta1": DP_BETA1,
    "beta2": DP_BETA2,
    "latent_dimension": DP_LATENT_DIMENSION,
}

for parameter, value in DP_CONFIG.items():
    print(f"{parameter:30s}: {value}")

====================================================================================================
PART E4 — DIFFERENTIAL PRIVACY CONFIGURATION DICTIONARY
====================================================================================================
privacy_budget_epsilon        : 4.0
privacy_delta                 : 1e-05
noise_multiplier              : 1.1
max_grad_norm                 : 1.0
accountant                    : rdp
epochs                        : 100
batch_size                    : 256
learning_rate                 : 0.0002
beta1                         : 0.5
beta2                         : 0.999
latent_dimension              : 128

In [130]:
# ==============================================================================
# PART E5 — DIFFERENTIAL PRIVACY PARAMETER VALIDATION
# ==============================================================================

print("=" * 100)
print("PART E5 — DIFFERENTIAL PRIVACY PARAMETER VALIDATION")
print("=" * 100)

DP_PARAMETER_VERIFICATION = {
    "Valid Epsilon":
        PRIVACY_BUDGET > 0,
    "Valid Delta":
        0 < PRIVACY_DELTA < 1,
    "Valid Noise Multiplier":
        NOISE_MULTIPLIER > 0,
    "Valid Gradient Norm":
        MAX_GRAD_NORM > 0,
    "Valid Epochs":
        DP_EPOCHS > 0,
    "Valid Batch Size":
        DP_BATCH_SIZE > 0,
    "Valid Learning Rate":
        DP_LEARNING_RATE > 0,
    "Valid Latent Dimension":
        DP_LATENT_DIMENSION > 0,
    "Valid Accountant":
        DP_ACCOUNTANT == "rdp",
}

for check, status in DP_PARAMETER_VERIFICATION.items():
    print(
        f"{check:30s}: "
        f"{'PASS' if status else 'FAIL'}"
    )

if not all(
    DP_PARAMETER_VERIFICATION.values()
):
    raise RuntimeError(
        "Differential Privacy parameter validation failed."
    )

print()
print(
    "All Differential Privacy parameters "
    "passed validation."
)

====================================================================================================
PART E5 — DIFFERENTIAL PRIVACY PARAMETER VALIDATION
====================================================================================================
Valid Epsilon                 : PASS
Valid Delta                   : PASS
Valid Noise Multiplier        : PASS
Valid Gradient Norm           : PASS
Valid Epochs                  : PASS
Valid Batch Size              : PASS
Valid Learning Rate           : PASS
Valid Latent Dimension        : PASS
Valid Accountant              : PASS

All Differential Privacy parameters passed validation.

In [131]:
# ==============================================================================
# PART E6 — PRIVACY SAMPLING CONFIGURATION
# ==============================================================================

print("=" * 100)
print("PART E6 — PRIVACY SAMPLING CONFIGURATION")
print("=" * 100)

DP_SAMPLING_CONFIG = {}

for dataset in DATASETS:
    training_rows = len(
        TRAIN_DATASETS[dataset]
    )
    sampling_rate = (
        DP_BATCH_SIZE / training_rows
    )
    DP_SAMPLING_CONFIG[dataset] = {
        "training_rows": training_rows,
        "batch_size": DP_BATCH_SIZE,
        "sampling_rate": sampling_rate,
    }
    print()
    print(dataset)
    print(f"Training Rows : {training_rows:,}")
    print(f"Batch Size    : {DP_BATCH_SIZE:,}")
    print(f"Sampling Rate : {sampling_rate:.8f}")

====================================================================================================
PART E6 — PRIVACY SAMPLING CONFIGURATION
====================================================================================================

Adult Income
Training Rows : 22,760
Batch Size    : 256
Sampling Rate : 0.01124780

Bank Marketing
Training Rows : 31,647
Batch Size    : 256
Sampling Rate : 0.00808923

diabetes_130us
Training Rows : 71,236
Batch Size    : 256
Sampling Rate : 0.00359369

In [132]:
# ==============================================================================
# PART E7 — PRIVACY CONFIGURATION SUMMARY
# ==============================================================================

print("=" * 100)
print("PART E7 — PRIVACY CONFIGURATION SUMMARY")
print("=" * 100)

PRIVACY_SUMMARY = []

for dataset in DATASETS:
    config = DP_SAMPLING_CONFIG[dataset]
    PRIVACY_SUMMARY.append({
        "Dataset": dataset,
        "Training Rows": config["training_rows"],
        "Batch Size": config["batch_size"],
        "Sampling Rate": config["sampling_rate"],
        "Epsilon": PRIVACY_BUDGET,
        "Delta": PRIVACY_DELTA,
        "Noise Multiplier": NOISE_MULTIPLIER,
        "Max Gradient Norm": MAX_GRAD_NORM,
        "Epochs": DP_EPOCHS,
    })

PRIVACY_SUMMARY_DF = pd.DataFrame(
    PRIVACY_SUMMARY
)

display(
    PRIVACY_SUMMARY_DF
)

====================================================================================================
PART E7 — PRIVACY CONFIGURATION SUMMARY
====================================================================================================

,Dataset,Training Rows,Batch Size,Sampling Rate,Epsilon,Delta,Noise Multiplier,Max Gradient Norm,Epochs
0,Adult Income,22760,256,0.011248,4.0,0.00001,1.1,1.0,100
1,Bank Marketing,31647,256,0.008089,4.0,0.00001,1.1,1.0,100
2,diabetes_130us,71236,256,0.003594,4.0,0.00001,1.1,1.0,100

In [133]:
# ==============================================================================
# PART E8 — FINAL DIFFERENTIAL PRIVACY VERIFICATION
# ==============================================================================

print("=" * 100)
print("PART E8 — FINAL DIFFERENTIAL PRIVACY VERIFICATION")
print("=" * 100)

DP_VERIFICATION = {
    "DP Configuration Created":
        isinstance(DP_CONFIG, dict),
    "Privacy Budget Valid":
        PRIVACY_BUDGET > 0,
    "Privacy Delta Valid":
        0 < PRIVACY_DELTA < 1,
    "Noise Multiplier Valid":
        NOISE_MULTIPLIER > 0,
    "Gradient Clipping Valid":
        MAX_GRAD_NORM > 0,
    "Training Configuration Valid":
        DP_EPOCHS > 0 and DP_BATCH_SIZE > 0,
    "Sampling Configuration Created":
        len(DP_SAMPLING_CONFIG) == len(DATASETS),
    "Privacy Summary Created":
        len(PRIVACY_SUMMARY_DF) == len(DATASETS),
}

for check, status in DP_VERIFICATION.items():
    print(
        f"{check:35s}: "
        f"{'PASS' if status else 'FAIL'}"
    )

E_PASSED = sum(
    DP_VERIFICATION.values()
)

E_TOTAL = len(
    DP_VERIFICATION
)

print()
print(
    f"PART E VERIFICATION: "
    f"{E_PASSED}/{E_TOTAL} CHECKS PASSED"
)

if E_PASSED != E_TOTAL:
    raise RuntimeError(
        "PART E Differential Privacy configuration verification failed."
    )

print()
print(
    "PART E — DIFFERENTIAL PRIVACY CONFIGURATION "
    "COMPLETED SUCCESSFULLY."
)

====================================================================================================
PART E8 — FINAL DIFFERENTIAL PRIVACY VERIFICATION
====================================================================================================
DP Configuration Created           : PASS
Privacy Budget Valid               : PASS
Privacy Delta Valid                : PASS
Noise Multiplier Valid             : PASS
Gradient Clipping Valid            : PASS
Training Configuration Valid       : PASS
Sampling Configuration Created     : PASS
Privacy Summary Created            : PASS

PART E VERIFICATION: 8/8 CHECKS PASSED

PART E — DIFFERENTIAL PRIVACY CONFIGURATION COMPLETED SUCCESSFULLY.

In [134]:
# ==============================================================================
# PART F1 — GENERATOR DIMENSION CONFIGURATION
# ==============================================================================

print("=" * 100)
print("PART F1 — GENERATOR DIMENSION CONFIGURATION")
print("=" * 100)

DP_LATENT_DIMENSION = 128

GENERATOR_INPUT_DIMENSIONS = {}
GENERATOR_OUTPUT_DIMENSIONS = {}

for dataset in DATASETS:

    GENERATOR_INPUT_DIMENSIONS[dataset] = (
        DP_LATENT_DIMENSION
    )

    GENERATOR_OUTPUT_DIMENSIONS[dataset] = (
        TRAIN_DATASETS[dataset].shape[1]
    )

    print()
    print(dataset)
    print(
        f"Latent Dimension : "
        f"{GENERATOR_INPUT_DIMENSIONS[dataset]}"
    )
    print(
        f"Output Features  : "
        f"{GENERATOR_OUTPUT_DIMENSIONS[dataset]}"
    )

====================================================================================================
PART F1 — GENERATOR DIMENSION CONFIGURATION
====================================================================================================

Adult Income
Latent Dimension : 128
Output Features  : 15

Bank Marketing
Latent Dimension : 128
Output Features  : 17

diabetes_130us
Latent Dimension : 128
Output Features  : 48

In [135]:
# ==============================================================================
# PART F2 — GENERATOR ARCHITECTURE CLASS
# ==============================================================================

import torch
import torch.nn as nn

class DPCTGANGenerator(nn.Module):

    def __init__(
        self,
        latent_dimension,
        output_dimension
    ):
        super().__init__()

        self.latent_dimension = latent_dimension
        self.output_dimension = output_dimension

        self.network = nn.Sequential(
            nn.Linear(
                latent_dimension,
                512
            ),
            nn.LayerNorm(512),
            nn.LeakyReLU(
                negative_slope=0.2,
                inplace=False
            ),
            nn.Dropout(0.2),

            nn.Linear(
                512,
                256
            ),
            nn.LayerNorm(256),
            nn.LeakyReLU(
                negative_slope=0.2,
                inplace=False
            ),
            nn.Dropout(0.2),

            nn.Linear(
                256,
                128
            ),
            nn.LayerNorm(128),
            nn.LeakyReLU(
                negative_slope=0.2,
                inplace=False
            ),

            nn.Linear(
                128,
                output_dimension
            )
        )

    def forward(self, noise):

        return self.network(noise)

print(
    "DPCTGANGenerator class defined successfully."
)

DPCTGANGenerator class defined successfully.

In [136]:
# ==============================================================================
# PART F3 — GENERATOR INITIALIZATION
# ==============================================================================

print("=" * 100)
print("PART F3 — GENERATOR INITIALIZATION")
print("=" * 100)

GENERATORS = {}

for dataset in DATASETS:

    latent_dimension = (
        GENERATOR_INPUT_DIMENSIONS[dataset]
    )

    output_dimension = (
        GENERATOR_OUTPUT_DIMENSIONS[dataset]
    )

    generator = DPCTGANGenerator(
        latent_dimension=latent_dimension,
        output_dimension=output_dimension
    )

    generator = generator.to(DEVICE)

    generator.train()

    GENERATORS[dataset] = generator

    print()
    print(dataset)
    print(
        f"Latent Dimension : "
        f"{latent_dimension}"
    )
    print(
        f"Output Dimension : "
        f"{output_dimension}"
    )
    print(
        f"Device           : "
        f"{DEVICE}"
    )
    print(
        f"Training Mode    : "
        f"{generator.training}"
    )

====================================================================================================
PART F3 — GENERATOR INITIALIZATION
====================================================================================================

Adult Income
Latent Dimension : 128
Output Dimension : 15
Device           : cpu
Training Mode    : True

Bank Marketing
Latent Dimension : 128
Output Dimension : 17
Device           : cpu
Training Mode    : True

diabetes_130us
Latent Dimension : 128
Output Dimension : 48
Device           : cpu
Training Mode    : True

In [137]:
# ==============================================================================
# PART F4 — GENERATOR PARAMETER INITIALIZATION
# ==============================================================================

print("=" * 100)
print("PART F4 — GENERATOR PARAMETER INITIALIZATION")
print("=" * 100)

def initialize_generator_weights(model):

    for module in model.modules():

        if isinstance(module, nn.Linear):

            nn.init.xavier_uniform_(
                module.weight
            )

            if module.bias is not None:

                nn.init.zeros_(
                    module.bias
                )

for dataset in DATASETS:

    initialize_generator_weights(
        GENERATORS[dataset]
    )

    print(
        f"{dataset:25s}: "
        f"Weight initialization completed"
    )

====================================================================================================
PART F4 — GENERATOR PARAMETER INITIALIZATION
====================================================================================================
Adult Income             : Weight initialization completed
Bank Marketing           : Weight initialization completed
diabetes_130us           : Weight initialization completed

In [138]:
# ==============================================================================
# PART F5 — GENERATOR ARCHITECTURE SUMMARY
# ==============================================================================

print("=" * 100)
print("PART F5 — GENERATOR ARCHITECTURE SUMMARY")
print("=" * 100)

GENERATOR_PARAMETER_COUNTS = {}

for dataset in DATASETS:

    generator = GENERATORS[dataset]

    total_parameters = sum(
        parameter.numel()
        for parameter in generator.parameters()
    )

    trainable_parameters = sum(
        parameter.numel()
        for parameter in generator.parameters()
        if parameter.requires_grad
    )

    GENERATOR_PARAMETER_COUNTS[dataset] = {
        "Total Parameters": total_parameters,
        "Trainable Parameters": trainable_parameters
    }

    print()
    print(dataset)
    print(
        generator
    )
    print(
        f"Total Parameters     : "
        f"{total_parameters:,}"
    )
    print(
        f"Trainable Parameters : "
        f"{trainable_parameters:,}"
    )

====================================================================================================
PART F5 — GENERATOR ARCHITECTURE SUMMARY
====================================================================================================

Adult Income
DPCTGANGenerator(
  (network): Sequential(
    (0): Linear(in_features=128, out_features=512, bias=True)
    (1): LayerNorm((512,), eps=1e-05, elementwise_affine=True)
    (2): LeakyReLU(negative_slope=0.2)
    (3): Dropout(p=0.2, inplace=False)
    (4): Linear(in_features=512, out_features=256, bias=True)
    (5): LayerNorm((256,), eps=1e-05, elementwise_affine=True)
    (6): LeakyReLU(negative_slope=0.2)
    (7): Dropout(p=0.2, inplace=False)
    (8): Linear(in_features=256, out_features=128, bias=True)
    (9): LayerNorm((128,), eps=1e-05, elementwise_affine=True)
    (10): LeakyReLU(negative_slope=0.2)
    (11): Linear(in_features=128, out_features=15, bias=True)
  )
)
Total Parameters     : 233,999
Trainable Parameters : 233,999

Bank Marketing
DPCTGANGenerator(
  (network): Sequential(
    (0): Linear(in_features=128, out_features=512, bias=True)
    (1): LayerNorm((512,), eps=1e-05, elementwise_affine=True)
    (2): LeakyReLU(negative_slope=0.2)
    (3): Dropout(p=0.2, inplace=False)
    (4): Linear(in_features=512, out_features=256, bias=True)
    (5): LayerNorm((256,), eps=1e-05, elementwise_affine=True)
    (6): LeakyReLU(negative_slope=0.2)
    (7): Dropout(p=0.2, inplace=False)
    (8): Linear(in_features=256, out_features=128, bias=True)
    (9): LayerNorm((128,), eps=1e-05, elementwise_affine=True)
    (10): LeakyReLU(negative_slope=0.2)
    (11): Linear(in_features=128, out_features=17, bias=True)
  )
)
Total Parameters     : 234,257
Trainable Parameters : 234,257

diabetes_130us
DPCTGANGenerator(
  (network): Sequential(
    (0): Linear(in_features=128, out_features=512, bias=True)
    (1): LayerNorm((512,), eps=1e-05, elementwise_affine=True)
    (2): LeakyReLU(negative_slope=0.2)
    (3): Dropout(p=0.2, inplace=False)
    (4): Linear(in_features=512, out_features=256, bias=True)
    (5): LayerNorm((256,), eps=1e-05, elementwise_affine=True)
    (6): LeakyReLU(negative_slope=0.2)
    (7): Dropout(p=0.2, inplace=False)
    (8): Linear(in_features=256, out_features=128, bias=True)
    (9): LayerNorm((128,), eps=1e-05, elementwise_affine=True)
    (10): LeakyReLU(negative_slope=0.2)
    (11): Linear(in_features=128, out_features=48, bias=True)
  )
)
Total Parameters     : 238,256
Trainable Parameters : 238,256

In [139]:
# ==============================================================================
# PART F6 — GENERATOR OUTPUT SHAPE VALIDATION
# ==============================================================================

print("=" * 100)
print("PART F6 — GENERATOR OUTPUT SHAPE VALIDATION")
print("=" * 100)

GENERATOR_OUTPUT_VERIFICATION = {}

VALIDATION_BATCH_SIZE = 4

for dataset in DATASETS:

    generator = GENERATORS[dataset]

    expected_output_dimension = (
        TRAIN_DATASETS[dataset].shape[1]
    )

    noise = torch.randn(
        VALIDATION_BATCH_SIZE,
        DP_LATENT_DIMENSION,
        device=DEVICE
    )

    generator.eval()

    with torch.no_grad():

        generated_data = generator(
            noise
        )

    generator.train()

    actual_output_dimension = (
        generated_data.shape[1]
    )

    expected_shape = (
        VALIDATION_BATCH_SIZE,
        expected_output_dimension
    )

    actual_shape = tuple(
        generated_data.shape
    )

    dimension_check = (
        actual_output_dimension
        == expected_output_dimension
    )

    shape_check = (
        actual_shape
        == expected_shape
    )

    status = (
        dimension_check
        and shape_check
    )

    GENERATOR_OUTPUT_VERIFICATION[
        dataset
    ] = status

    print()
    print(dataset)
    print(
        f"Expected Shape : "
        f"{expected_shape}"
    )
    print(
        f"Actual Shape   : "
        f"{actual_shape}"
    )
    print(
        f"Dimension Check: "
        f"{'PASS' if dimension_check else 'FAIL'}"
    )
    print(
        f"Shape Check    : "
        f"{'PASS' if shape_check else 'FAIL'}"
    )
    print(
        f"Overall        : "
        f"{'PASS' if status else 'FAIL'}"
    )

if not all(
    GENERATOR_OUTPUT_VERIFICATION.values()
):

    raise RuntimeError(
        "Generator output dimensions do not "
        "match the training dataset dimensions."
    )

print()
print(
    "All Generator output dimensions "
    "verified successfully."
)

====================================================================================================
PART F6 — GENERATOR OUTPUT SHAPE VALIDATION
====================================================================================================

Adult Income
Expected Shape : (4, 15)
Actual Shape   : (4, 15)
Dimension Check: PASS
Shape Check    : PASS
Overall        : PASS

Bank Marketing
Expected Shape : (4, 17)
Actual Shape   : (4, 17)
Dimension Check: PASS
Shape Check    : PASS
Overall        : PASS

diabetes_130us
Expected Shape : (4, 48)
Actual Shape   : (4, 48)
Dimension Check: PASS
Shape Check    : PASS
Overall        : PASS

All Generator output dimensions verified successfully.

In [140]:
# ==============================================================================
# PART F7 — GENERATOR TRAINING MODE VALIDATION
# ==============================================================================

print("=" * 100)
print("PART F7 — GENERATOR TRAINING MODE VALIDATION")
print("=" * 100)

GENERATOR_TRAINING_MODE_VERIFICATION = {}

for dataset in DATASETS:

    generator = GENERATORS[dataset]

    generator.train()

    training_mode = (
        generator.training
    )

    GENERATOR_TRAINING_MODE_VERIFICATION[
        dataset
    ] = training_mode

    print()
    print(dataset)
    print(
        f"Training Mode : "
        f"{'PASS' if training_mode else 'FAIL'}"
    )

if not all(
    GENERATOR_TRAINING_MODE_VERIFICATION.values()
):

    raise RuntimeError(
        "One or more Generators are not "
        "in training mode."
    )

print()
print(
    "All Generators are in training mode."
)

====================================================================================================
PART F7 — GENERATOR TRAINING MODE VALIDATION
====================================================================================================

Adult Income
Training Mode : PASS

Bank Marketing
Training Mode : PASS

diabetes_130us
Training Mode : PASS

All Generators are in training mode.

In [141]:
# ==============================================================================
# PART F8 — OPACUS GENERATOR COMPATIBILITY CHECK
# ==============================================================================

print("=" * 100)
print("PART F8 — OPACUS GENERATOR COMPATIBILITY CHECK")
print("=" * 100)

try:

    from opacus.validators import ModuleValidator

except ImportError as error:

    raise ImportError(
        "Opacus is not installed. "
        "Run Part A before Part F."
    ) from error

GENERATOR_OPACUS_COMPATIBILITY = {}

for dataset in DATASETS:

    generator = GENERATORS[dataset]

    generator.train()

    errors = ModuleValidator.validate(
        generator,
        strict=False
    )

    compatibility = (
        len(errors) == 0
    )

    GENERATOR_OPACUS_COMPATIBILITY[
        dataset
    ] = compatibility

    print()
    print(dataset)

    if compatibility:

        print(
            "Opacus Compatibility: PASS"
        )

    else:

        print(
            "Opacus Compatibility: FAIL"
        )

        for error in errors:

            print(
                f"  {error}"
            )

if not all(
    GENERATOR_OPACUS_COMPATIBILITY.values()
):

    raise RuntimeError(
        "One or more Generators failed "
        "Opacus compatibility validation."
    )

print()
print(
    "All Generators passed Opacus "
    "compatibility validation."
)

====================================================================================================
PART F8 — OPACUS GENERATOR COMPATIBILITY CHECK
====================================================================================================

Adult Income
Opacus Compatibility: PASS

Bank Marketing
Opacus Compatibility: PASS

diabetes_130us
Opacus Compatibility: PASS

All Generators passed Opacus compatibility validation.

In [142]:
# ==============================================================================
# PART F9 — FINAL GENERATOR ARCHITECTURE VERIFICATION
# ==============================================================================

print("=" * 100)
print("PART F9 — FINAL GENERATOR ARCHITECTURE VERIFICATION")
print("=" * 100)

FINAL_GENERATOR_VERIFICATION = {}

for dataset in DATASETS:

    generator = GENERATORS[dataset]

    expected_features = (
        TRAIN_DATASETS[dataset].shape[1]
    )

    linear_layers = [
        layer
        for layer in generator.modules()
        if isinstance(layer, nn.Linear)
    ]

    actual_output_features = (
        linear_layers[-1].out_features
    )

    output_dimension_check = (
        actual_output_features
        == expected_features
    )

    training_mode_check = (
        generator.training
    )

    opacus_check = (
        GENERATOR_OPACUS_COMPATIBILITY[dataset]
    )

    final_status = (
        output_dimension_check
        and training_mode_check
        and opacus_check
    )

    FINAL_GENERATOR_VERIFICATION[
        dataset
    ] = final_status

    print()
    print(dataset)
    print(
        f"Training Features     : "
        f"{expected_features}"
    )
    print(
        f"Generator Output      : "
        f"{actual_output_features}"
    )
    print(
        f"Dimension Check       : "
        f"{'PASS' if output_dimension_check else 'FAIL'}"
    )
    print(
        f"Training Mode         : "
        f"{'PASS' if training_mode_check else 'FAIL'}"
    )
    print(
        f"Opacus Compatibility   : "
        f"{'PASS' if opacus_check else 'FAIL'}"
    )
    print(
        f"Final Status           : "
        f"{'PASS' if final_status else 'FAIL'}"
    )

if not all(
    FINAL_GENERATOR_VERIFICATION.values()
):

    raise RuntimeError(
        "Final Generator architecture "
        "verification failed."
    )

print()
print(
    "=" * 100
)
print(
    "PART F COMPLETED SUCCESSFULLY"
)
print(
    "All Generator architecture checks passed."
)
print(
    "=" * 100
)

====================================================================================================
PART F9 — FINAL GENERATOR ARCHITECTURE VERIFICATION
====================================================================================================

Adult Income
Training Features     : 15
Generator Output      : 15
Dimension Check       : PASS
Training Mode         : PASS
Opacus Compatibility   : PASS
Final Status           : PASS

Bank Marketing
Training Features     : 17
Generator Output      : 17
Dimension Check       : PASS
Training Mode         : PASS
Opacus Compatibility   : PASS
Final Status           : PASS

diabetes_130us
Training Features     : 48
Generator Output      : 48
Dimension Check       : PASS
Training Mode         : PASS
Opacus Compatibility   : PASS
Final Status           : PASS

====================================================================================================
PART F COMPLETED SUCCESSFULLY
All Generator architecture checks passed.
====================================================================================================

In [143]:
# ==============================================================================
# PART G1 — DISCRIMINATOR DIMENSION CONFIGURATION
# ==============================================================================

print("=" * 100)
print("PART G1 — DISCRIMINATOR DIMENSION CONFIGURATION")
print("=" * 100)

DISCRIMINATOR_INPUT_DIMENSIONS = {}

DISCRIMINATOR_OUTPUT_DIMENSION = 1

for dataset in DATASETS:

    DISCRIMINATOR_INPUT_DIMENSIONS[dataset] = (
        TRAIN_DATASETS[dataset].shape[1]
    )

    print()
    print(dataset)
    print(
        f"Input Features  : "
        f"{DISCRIMINATOR_INPUT_DIMENSIONS[dataset]}"
    )
    print(
        f"Output Features : "
        f"{DISCRIMINATOR_OUTPUT_DIMENSION}"
    )

====================================================================================================
PART G1 — DISCRIMINATOR DIMENSION CONFIGURATION
====================================================================================================

Adult Income
Input Features  : 15
Output Features : 1

Bank Marketing
Input Features  : 17
Output Features : 1

diabetes_130us
Input Features  : 48
Output Features : 1

In [144]:
# ==============================================================================
# PART G2 — DISCRIMINATOR ARCHITECTURE CLASS
# ==============================================================================

import torch
import torch.nn as nn

class DPCTGANDiscriminator(nn.Module):

    def __init__(
        self,
        input_dimension
    ):
        super().__init__()

        self.input_dimension = input_dimension

        self.network = nn.Sequential(
            nn.Linear(
                input_dimension,
                512
            ),
            nn.LayerNorm(512),
            nn.LeakyReLU(
                negative_slope=0.2,
                inplace=False
            ),
            nn.Dropout(0.3),

            nn.Linear(
                512,
                256
            ),
            nn.LayerNorm(256),
            nn.LeakyReLU(
                negative_slope=0.2,
                inplace=False
            ),
            nn.Dropout(0.3),

            nn.Linear(
                256,
                128
            ),
            nn.LayerNorm(128),
            nn.LeakyReLU(
                negative_slope=0.2,
                inplace=False
            ),
            nn.Dropout(0.3),

            nn.Linear(
                128,
                1
            )
        )

    def forward(self, data):

        return self.network(data)

print(
    "DPCTGANDiscriminator class defined successfully."
)

DPCTGANDiscriminator class defined successfully.

In [145]:
# ==============================================================================
# PART G3 — DISCRIMINATOR INITIALIZATION
# ==============================================================================

print("=" * 100)
print("PART G3 — DISCRIMINATOR INITIALIZATION")
print("=" * 100)

DISCRIMINATORS = {}

for dataset in DATASETS:

    input_dimension = (
        DISCRIMINATOR_INPUT_DIMENSIONS[dataset]
    )

    discriminator = DPCTGANDiscriminator(
        input_dimension=input_dimension
    )

    discriminator = discriminator.to(DEVICE)

    discriminator.train()

    DISCRIMINATORS[dataset] = discriminator

    print()
    print(dataset)
    print(
        f"Input Dimension : "
        f"{input_dimension}"
    )
    print(
        f"Output Dimension: "
        f"{DISCRIMINATOR_OUTPUT_DIMENSION}"
    )
    print(
        f"Device          : "
        f"{DEVICE}"
    )
    print(
        f"Training Mode   : "
        f"{discriminator.training}"
    )

====================================================================================================
PART G3 — DISCRIMINATOR INITIALIZATION
====================================================================================================

Adult Income
Input Dimension : 15
Output Dimension: 1
Device          : cpu
Training Mode   : True

Bank Marketing
Input Dimension : 17
Output Dimension: 1
Device          : cpu
Training Mode   : True

diabetes_130us
Input Dimension : 48
Output Dimension: 1
Device          : cpu
Training Mode   : True

In [146]:
# ==============================================================================
# PART G4 — DISCRIMINATOR PARAMETER INITIALIZATION
# ==============================================================================

print("=" * 100)
print("PART G4 — DISCRIMINATOR PARAMETER INITIALIZATION")
print("=" * 100)

def initialize_discriminator_weights(model):

    for module in model.modules():

        if isinstance(module, nn.Linear):

            nn.init.xavier_uniform_(
                module.weight
            )

            if module.bias is not None:

                nn.init.zeros_(
                    module.bias
                )

for dataset in DATASETS:

    initialize_discriminator_weights(
        DISCRIMINATORS[dataset]
    )

    print(
        f"{dataset:25s}: "
        f"Weight initialization completed"
    )

====================================================================================================
PART G4 — DISCRIMINATOR PARAMETER INITIALIZATION
====================================================================================================
Adult Income             : Weight initialization completed
Bank Marketing           : Weight initialization completed
diabetes_130us           : Weight initialization completed

In [147]:
# ==============================================================================
# PART G5 — DISCRIMINATOR ARCHITECTURE SUMMARY
# ==============================================================================

print("=" * 100)
print("PART G5 — DISCRIMINATOR ARCHITECTURE SUMMARY")
print("=" * 100)

DISCRIMINATOR_PARAMETER_COUNTS = {}

for dataset in DATASETS:

    discriminator = DISCRIMINATORS[dataset]

    total_parameters = sum(
        parameter.numel()
        for parameter in discriminator.parameters()
    )

    trainable_parameters = sum(
        parameter.numel()
        for parameter in discriminator.parameters()
        if parameter.requires_grad
    )

    DISCRIMINATOR_PARAMETER_COUNTS[dataset] = {
        "Total Parameters": total_parameters,
        "Trainable Parameters": trainable_parameters
    }

    print()
    print(dataset)
    print(
        discriminator
    )
    print(
        f"Total Parameters     : "
        f"{total_parameters:,}"
    )
    print(
        f"Trainable Parameters : "
        f"{trainable_parameters:,}"
    )

====================================================================================================
PART G5 — DISCRIMINATOR ARCHITECTURE SUMMARY
====================================================================================================

Adult Income
DPCTGANDiscriminator(
  (network): Sequential(
    (0): Linear(in_features=15, out_features=512, bias=True)
    (1): LayerNorm((512,), eps=1e-05, elementwise_affine=True)
    (2): LeakyReLU(negative_slope=0.2)
    (3): Dropout(p=0.3, inplace=False)
    (4): Linear(in_features=512, out_features=256, bias=True)
    (5): LayerNorm((256,), eps=1e-05, elementwise_affine=True)
    (6): LeakyReLU(negative_slope=0.2)
    (7): Dropout(p=0.3, inplace=False)
    (8): Linear(in_features=256, out_features=128, bias=True)
    (9): LayerNorm((128,), eps=1e-05, elementwise_affine=True)
    (10): LeakyReLU(negative_slope=0.2)
    (11): Dropout(p=0.3, inplace=False)
    (12): Linear(in_features=128, out_features=1, bias=True)
  )
)
Total Parameters     : 174,337
Trainable Parameters : 174,337

Bank Marketing
DPCTGANDiscriminator(
  (network): Sequential(
    (0): Linear(in_features=17, out_features=512, bias=True)
    (1): LayerNorm((512,), eps=1e-05, elementwise_affine=True)
    (2): LeakyReLU(negative_slope=0.2)
    (3): Dropout(p=0.3, inplace=False)
    (4): Linear(in_features=512, out_features=256, bias=True)
    (5): LayerNorm((256,), eps=1e-05, elementwise_affine=True)
    (6): LeakyReLU(negative_slope=0.2)
    (7): Dropout(p=0.3, inplace=False)
    (8): Linear(in_features=256, out_features=128, bias=True)
    (9): LayerNorm((128,), eps=1e-05, elementwise_affine=True)
    (10): LeakyReLU(negative_slope=0.2)
    (11): Dropout(p=0.3, inplace=False)
    (12): Linear(in_features=128, out_features=1, bias=True)
  )
)
Total Parameters     : 175,361
Trainable Parameters : 175,361

diabetes_130us
DPCTGANDiscriminator(
  (network): Sequential(
    (0): Linear(in_features=48, out_features=512, bias=True)
    (1): LayerNorm((512,), eps=1e-05, elementwise_affine=True)
    (2): LeakyReLU(negative_slope=0.2)
    (3): Dropout(p=0.3, inplace=False)
    (4): Linear(in_features=512, out_features=256, bias=True)
    (5): LayerNorm((256,), eps=1e-05, elementwise_affine=True)
    (6): LeakyReLU(negative_slope=0.2)
    (7): Dropout(p=0.3, inplace=False)
    (8): Linear(in_features=256, out_features=128, bias=True)
    (9): LayerNorm((128,), eps=1e-05, elementwise_affine=True)
    (10): LeakyReLU(negative_slope=0.2)
    (11): Dropout(p=0.3, inplace=False)
    (12): Linear(in_features=128, out_features=1, bias=True)
  )
)
Total Parameters     : 191,233
Trainable Parameters : 191,233

In [148]:
# ==============================================================================
# PART G6 — DISCRIMINATOR INPUT SHAPE VALIDATION
# ==============================================================================

print("=" * 100)
print("PART G6 — DISCRIMINATOR INPUT SHAPE VALIDATION")
print("=" * 100)

DISCRIMINATOR_INPUT_VERIFICATION = {}

VALIDATION_BATCH_SIZE = 4

for dataset in DATASETS:

    discriminator = DISCRIMINATORS[dataset]

    expected_input_dimension = (
        TRAIN_DATASETS[dataset].shape[1]
    )

    test_data = torch.randn(
        VALIDATION_BATCH_SIZE,
        expected_input_dimension,
        device=DEVICE
    )

    discriminator.eval()

    with torch.no_grad():

        discriminator_output = discriminator(
            test_data
        )

    discriminator.train()

    actual_output_shape = tuple(
        discriminator_output.shape
    )

    expected_output_shape = (
        VALIDATION_BATCH_SIZE,
        DISCRIMINATOR_OUTPUT_DIMENSION
    )

    input_dimension_check = (
        discriminator.input_dimension
        == expected_input_dimension
    )

    output_shape_check = (
        actual_output_shape
        == expected_output_shape
    )

    status = (
        input_dimension_check
        and output_shape_check
    )

    DISCRIMINATOR_INPUT_VERIFICATION[
        dataset
    ] = status

    print()
    print(dataset)
    print(
        f"Expected Input Dimension : "
        f"{expected_input_dimension}"
    )
    print(
        f"Actual Input Dimension   : "
        f"{discriminator.input_dimension}"
    )
    print(
        f"Expected Output Shape    : "
        f"{expected_output_shape}"
    )
    print(
        f"Actual Output Shape      : "
        f"{actual_output_shape}"
    )
    print(
        f"Input Dimension Check    : "
        f"{'PASS' if input_dimension_check else 'FAIL'}"
    )
    print(
        f"Output Shape Check       : "
        f"{'PASS' if output_shape_check else 'FAIL'}"
    )
    print(
        f"Overall                  : "
        f"{'PASS' if status else 'FAIL'}"
    )

if not all(
    DISCRIMINATOR_INPUT_VERIFICATION.values()
):

    raise RuntimeError(
        "Discriminator input/output dimensions "
        "do not match the training data."
    )

print()
print(
    "All Discriminator input/output dimensions "
    "verified successfully."
)

====================================================================================================
PART G6 — DISCRIMINATOR INPUT SHAPE VALIDATION
====================================================================================================

Adult Income
Expected Input Dimension : 15
Actual Input Dimension   : 15
Expected Output Shape    : (4, 1)
Actual Output Shape      : (4, 1)
Input Dimension Check    : PASS
Output Shape Check       : PASS
Overall                  : PASS

Bank Marketing
Expected Input Dimension : 17
Actual Input Dimension   : 17
Expected Output Shape    : (4, 1)
Actual Output Shape      : (4, 1)
Input Dimension Check    : PASS
Output Shape Check       : PASS
Overall                  : PASS

diabetes_130us
Expected Input Dimension : 48
Actual Input Dimension   : 48
Expected Output Shape    : (4, 1)
Actual Output Shape      : (4, 1)
Input Dimension Check    : PASS
Output Shape Check       : PASS
Overall                  : PASS

All Discriminator input/output dimensions verified successfully.

In [149]:
# ==============================================================================
# PART G7 — GENERATOR-DISCRIMINATOR COMPATIBILITY
# ==============================================================================

print("=" * 100)
print("PART G7 — GENERATOR-DISCRIMINATOR COMPATIBILITY")
print("=" * 100)

GAN_DIMENSION_COMPATIBILITY = {}

for dataset in DATASETS:

    expected_features = (
        TRAIN_DATASETS[dataset].shape[1]
    )

    generator_output = (
        GENERATOR_OUTPUT_DIMENSIONS[dataset]
    )

    discriminator_input = (
        DISCRIMINATOR_INPUT_DIMENSIONS[dataset]
    )

    compatibility = (
        expected_features
        == generator_output
        == discriminator_input
    )

    GAN_DIMENSION_COMPATIBILITY[
        dataset
    ] = compatibility

    print()
    print(dataset)
    print(
        f"Training Features       : "
        f"{expected_features}"
    )
    print(
        f"Generator Output        : "
        f"{generator_output}"
    )
    print(
        f"Discriminator Input     : "
        f"{discriminator_input}"
    )
    print(
        f"Compatibility           : "
        f"{'PASS' if compatibility else 'FAIL'}"
    )

if not all(
    GAN_DIMENSION_COMPATIBILITY.values()
):

    raise RuntimeError(
        "Generator and Discriminator dimensions "
        "are incompatible with the training data."
    )

print()
print(
    "Generator and Discriminator dimensions "
    "are fully compatible."
)

====================================================================================================
PART G7 — GENERATOR-DISCRIMINATOR COMPATIBILITY
====================================================================================================

Adult Income
Training Features       : 15
Generator Output        : 15
Discriminator Input     : 15
Compatibility           : PASS

Bank Marketing
Training Features       : 17
Generator Output        : 17
Discriminator Input     : 17
Compatibility           : PASS

diabetes_130us
Training Features       : 48
Generator Output        : 48
Discriminator Input     : 48
Compatibility           : PASS

Generator and Discriminator dimensions are fully compatible.

In [150]:
# ==============================================================================
# PART G8 — DISCRIMINATOR TRAINING MODE VALIDATION
# ==============================================================================

print("=" * 100)
print("PART G8 — DISCRIMINATOR TRAINING MODE VALIDATION")
print("=" * 100)

DISCRIMINATOR_TRAINING_MODE_VERIFICATION = {}

for dataset in DATASETS:

    discriminator = DISCRIMINATORS[dataset]

    discriminator.train()

    training_mode = (
        discriminator.training
    )

    DISCRIMINATOR_TRAINING_MODE_VERIFICATION[
        dataset
    ] = training_mode

    print()
    print(dataset)
    print(
        f"Training Mode : "
        f"{'PASS' if training_mode else 'FAIL'}"
    )

if not all(
    DISCRIMINATOR_TRAINING_MODE_VERIFICATION.values()
):

    raise RuntimeError(
        "One or more Discriminators are not "
        "in training mode."
    )

print()
print(
    "All Discriminators are in training mode."
)

====================================================================================================
PART G8 — DISCRIMINATOR TRAINING MODE VALIDATION
====================================================================================================

Adult Income
Training Mode : PASS

Bank Marketing
Training Mode : PASS

diabetes_130us
Training Mode : PASS

All Discriminators are in training mode.

In [151]:
# ==============================================================================
# PART G9 — OPACUS DISCRIMINATOR COMPATIBILITY CHECK
# ==============================================================================

from opacus.validators import ModuleValidator

print("=" * 100)
print("PART G9 — OPACUS DISCRIMINATOR COMPATIBILITY CHECK")
print("=" * 100)

DISCRIMINATOR_OPACUS_COMPATIBILITY = {}

for dataset in DATASETS:

    discriminator = DISCRIMINATORS[dataset]

    discriminator.train()

    errors = ModuleValidator.validate(
        discriminator,
        strict=False
    )

    compatibility = (
        len(errors) == 0
    )

    DISCRIMINATOR_OPACUS_COMPATIBILITY[
        dataset
    ] = compatibility

    print()
    print(dataset)

    if compatibility:

        print(
            "Opacus Compatibility: PASS"
        )

    else:

        print(
            "Opacus Compatibility: FAIL"
        )

        for error in errors:

            print(
                f"  {error}"
            )

if not all(
    DISCRIMINATOR_OPACUS_COMPATIBILITY.values()
):

    raise RuntimeError(
        "One or more Discriminators failed "
        "Opacus compatibility validation."
    )

print()
print(
    "All Discriminators passed Opacus "
    "compatibility validation."
)

====================================================================================================
PART G9 — OPACUS DISCRIMINATOR COMPATIBILITY CHECK
====================================================================================================

Adult Income
Opacus Compatibility: PASS

Bank Marketing
Opacus Compatibility: PASS

diabetes_130us
Opacus Compatibility: PASS

All Discriminators passed Opacus compatibility validation.

In [152]:
# ==============================================================================
# PART G10 — FINAL DISCRIMINATOR ARCHITECTURE VERIFICATION
# ==============================================================================

print("=" * 100)
print("PART G10 — FINAL DISCRIMINATOR ARCHITECTURE VERIFICATION")
print("=" * 100)

FINAL_DISCRIMINATOR_VERIFICATION = {}

for dataset in DATASETS:

    discriminator = DISCRIMINATORS[dataset]

    expected_features = (
        TRAIN_DATASETS[dataset].shape[1]
    )

    actual_input_features = (
        discriminator.input_dimension
    )

    dimension_check = (
        actual_input_features
        == expected_features
    )

    training_mode_check = (
        discriminator.training
    )

    opacus_check = (
        DISCRIMINATOR_OPACUS_COMPATIBILITY[
            dataset
        ]
    )

    compatibility_check = (
        GAN_DIMENSION_COMPATIBILITY[
            dataset
        ]
    )

    final_status = (
        dimension_check
        and training_mode_check
        and opacus_check
        and compatibility_check
    )

    FINAL_DISCRIMINATOR_VERIFICATION[
        dataset
    ] = final_status

    print()
    print(dataset)
    print(
        f"Training Features       : "
        f"{expected_features}"
    )
    print(
        f"Discriminator Input     : "
        f"{actual_input_features}"
    )
    print(
        f"Dimension Check         : "
        f"{'PASS' if dimension_check else 'FAIL'}"
    )
    print(
        f"Training Mode           : "
        f"{'PASS' if training_mode_check else 'FAIL'}"
    )
    print(
        f"Generator Compatibility : "
        f"{'PASS' if compatibility_check else 'FAIL'}"
    )
    print(
        f"Opacus Compatibility    : "
        f"{'PASS' if opacus_check else 'FAIL'}"
    )
    print(
        f"Final Status            : "
        f"{'PASS' if final_status else 'FAIL'}"
    )

if not all(
    FINAL_DISCRIMINATOR_VERIFICATION.values()
):

    raise RuntimeError(
        "Final Discriminator architecture "
        "verification failed."
    )

print()
print("=" * 100)
print("PART G COMPLETED SUCCESSFULLY")
print("All Discriminator architecture checks passed.")
print("=" * 100)

====================================================================================================
PART G10 — FINAL DISCRIMINATOR ARCHITECTURE VERIFICATION
====================================================================================================

Adult Income
Training Features       : 15
Discriminator Input     : 15
Dimension Check         : PASS
Training Mode           : PASS
Generator Compatibility : PASS
Opacus Compatibility    : PASS
Final Status            : PASS

Bank Marketing
Training Features       : 17
Discriminator Input     : 17
Dimension Check         : PASS
Training Mode           : PASS
Generator Compatibility : PASS
Opacus Compatibility    : PASS
Final Status            : PASS

diabetes_130us
Training Features       : 48
Discriminator Input     : 48
Dimension Check         : PASS
Training Mode           : PASS
Generator Compatibility : PASS
Opacus Compatibility    : PASS
Final Status            : PASS

====================================================================================================
PART G COMPLETED SUCCESSFULLY
All Discriminator architecture checks passed.
====================================================================================================

In [153]:
# ==============================================================================
# PART H1 — OPACUS VERSION AND ENVIRONMENT VALIDATION
# ==============================================================================

print("=" * 100)
print("PART H1 — OPACUS VERSION AND ENVIRONMENT VALIDATION")
print("=" * 100)

import torch
import opacus

print(
    f"PyTorch Version : {torch.__version__}"
)

print(
    f"Opacus Version  : {opacus.__version__}"
)

print(
    f"Device          : {DEVICE}"
)

print(
    f"Datasets        : {len(DATASETS)}"
)

print(
    f"Dataset Names   : {DATASETS}"
)

====================================================================================================
PART H1 — OPACUS VERSION AND ENVIRONMENT VALIDATION
====================================================================================================
PyTorch Version : 2.11.0+cpu
Opacus Version  : 1.6.0
Device          : cpu
Datasets        : 3
Dataset Names   : ['Adult Income', 'Bank Marketing', 'diabetes_130us']

In [154]:
# ==============================================================================
# PART H2 — OPACUS MODULE VALIDATOR IMPORT
# ==============================================================================

print("=" * 100)
print("PART H2 — OPACUS MODULE VALIDATOR IMPORT")
print("=" * 100)

from opacus.validators import ModuleValidator

print(
    "ModuleValidator imported successfully."
)

====================================================================================================
PART H2 — OPACUS MODULE VALIDATOR IMPORT
====================================================================================================
ModuleValidator imported successfully.

In [155]:
# ==============================================================================
# PART H3 — GENERATOR OPACUS VALIDATION
# ==============================================================================

print("=" * 100)
print("PART H3 — GENERATOR OPACUS VALIDATION")
print("=" * 100)

GENERATOR_OPACUS_VALIDATION = {}

for dataset in DATASETS:

    generator = GENERATORS[dataset]

    generator.train()

    errors = ModuleValidator.validate(
        generator,
        strict=False
    )

    passed = (
        len(errors) == 0
    )

    GENERATOR_OPACUS_VALIDATION[
        dataset
    ] = {
        "Passed": passed,
        "Errors": errors
    }

    print()
    print(dataset)

    print(
        f"Training Mode : "
        f"{'PASS' if generator.training else 'FAIL'}"
    )

    print(
        f"Opacus Check  : "
        f"{'PASS' if passed else 'FAIL'}"
    )

    if not passed:

        print(
            "Validation Errors:"
        )

        for error in errors:

            print(
                f"  {error}"
            )

if not all(
    result["Passed"]
    for result in GENERATOR_OPACUS_VALIDATION.values()
):

    raise RuntimeError(
        "One or more Generators failed "
        "Opacus compatibility validation."
    )

print()
print(
    "All Generators passed Opacus validation."
)

====================================================================================================
PART H3 — GENERATOR OPACUS VALIDATION
====================================================================================================

Adult Income
Training Mode : PASS
Opacus Check  : PASS

Bank Marketing
Training Mode : PASS
Opacus Check  : PASS

diabetes_130us
Training Mode : PASS
Opacus Check  : PASS

All Generators passed Opacus validation.

In [156]:
# ==============================================================================
# PART H4 — DISCRIMINATOR OPACUS VALIDATION
# ==============================================================================

print("=" * 100)
print("PART H4 — DISCRIMINATOR OPACUS VALIDATION")
print("=" * 100)

DISCRIMINATOR_OPACUS_VALIDATION = {}

for dataset in DATASETS:

    discriminator = DISCRIMINATORS[dataset]

    discriminator.train()

    errors = ModuleValidator.validate(
        discriminator,
        strict=False
    )

    passed = (
        len(errors) == 0
    )

    DISCRIMINATOR_OPACUS_VALIDATION[
        dataset
    ] = {
        "Passed": passed,
        "Errors": errors
    }

    print()
    print(dataset)

    print(
        f"Training Mode : "
        f"{'PASS' if discriminator.training else 'FAIL'}"
    )

    print(
        f"Opacus Check  : "
        f"{'PASS' if passed else 'FAIL'}"
    )

    if not passed:

        print(
            "Validation Errors:"
        )

        for error in errors:

            print(
                f"  {error}"
            )

if not all(
    result["Passed"]
    for result in DISCRIMINATOR_OPACUS_VALIDATION.values()
):

    raise RuntimeError(
        "One or more Discriminators failed "
        "Opacus compatibility validation."
    )

print()
print(
    "All Discriminators passed Opacus validation."
)

====================================================================================================
PART H4 — DISCRIMINATOR OPACUS VALIDATION
====================================================================================================

Adult Income
Training Mode : PASS
Opacus Check  : PASS

Bank Marketing
Training Mode : PASS
Opacus Check  : PASS

diabetes_130us
Training Mode : PASS
Opacus Check  : PASS

All Discriminators passed Opacus validation.

In [157]:
# ==============================================================================
# PART H5 — OPACUS UNSUPPORTED MODULE DETECTION
# ==============================================================================

print("=" * 100)
print("PART H5 — OPACUS UNSUPPORTED MODULE DETECTION")
print("=" * 100)

UNSUPPORTED_MODULES = {}

for dataset in DATASETS:

    generator = GENERATORS[dataset]
    discriminator = DISCRIMINATORS[dataset]

    generator_issues = ModuleValidator.validate(
        generator,
        strict=False
    )

    discriminator_issues = ModuleValidator.validate(
        discriminator,
        strict=False
    )

    UNSUPPORTED_MODULES[
        dataset
    ] = {
        "Generator": generator_issues,
        "Discriminator": discriminator_issues
    }

    print()
    print(dataset)

    print(
        f"Generator Unsupported Modules   : "
        f"{len(generator_issues)}"
    )

    print(
        f"Discriminator Unsupported Modules: "
        f"{len(discriminator_issues)}"
    )

    if generator_issues:

        print(
            "Generator Issues:"
        )

        for issue in generator_issues:

            print(
                f"  {issue}"
            )

    if discriminator_issues:

        print(
            "Discriminator Issues:"
        )

        for issue in discriminator_issues:

            print(
                f"  {issue}"
            )

if any(
    len(result["Generator"]) > 0
    or len(result["Discriminator"]) > 0
    for result in UNSUPPORTED_MODULES.values()
):

    raise RuntimeError(
        "Unsupported modules detected in the "
        "DP-CTGAN architecture."
    )

print()
print(
    "No unsupported modules detected."
)

====================================================================================================
PART H5 — OPACUS UNSUPPORTED MODULE DETECTION
====================================================================================================

Adult Income
Generator Unsupported Modules   : 0
Discriminator Unsupported Modules: 0

Bank Marketing
Generator Unsupported Modules   : 0
Discriminator Unsupported Modules: 0

diabetes_130us
Generator Unsupported Modules   : 0
Discriminator Unsupported Modules: 0

No unsupported modules detected.

In [158]:
# ==============================================================================
# PART H6 — GENERATOR INPUT/OUTPUT VALIDATION
# ==============================================================================

print("=" * 100)
print("PART H6 — GENERATOR INPUT/OUTPUT VALIDATION")
print("=" * 100)

GENERATOR_DIMENSION_VALIDATION = {}

VALIDATION_BATCH_SIZE = 8

for dataset in DATASETS:

    generator = GENERATORS[dataset]

    expected_input_dimension = (
        DP_LATENT_DIMENSION
    )

    expected_output_dimension = (
        TRAIN_DATASETS[dataset].shape[1]
    )

    noise = torch.randn(
        VALIDATION_BATCH_SIZE,
        expected_input_dimension,
        device=DEVICE
    )

    generator.train()

    generated_data = generator(
        noise
    )

    actual_input_dimension = (
        noise.shape[1]
    )

    actual_output_dimension = (
        generated_data.shape[1]
    )

    input_check = (
        actual_input_dimension
        == expected_input_dimension
    )

    output_check = (
        actual_output_dimension
        == expected_output_dimension
    )

    status = (
        input_check
        and output_check
    )

    GENERATOR_DIMENSION_VALIDATION[
        dataset
    ] = status

    print()
    print(dataset)

    print(
        f"Expected Input Dimension  : "
        f"{expected_input_dimension}"
    )

    print(
        f"Actual Input Dimension    : "
        f"{actual_input_dimension}"
    )

    print(
        f"Expected Output Dimension : "
        f"{expected_output_dimension}"
    )

    print(
        f"Actual Output Dimension   : "
        f"{actual_output_dimension}"
    )

    print(
        f"Input Check               : "
        f"{'PASS' if input_check else 'FAIL'}"
    )

    print(
        f"Output Check              : "
        f"{'PASS' if output_check else 'FAIL'}"
    )

    print(
        f"Overall                   : "
        f"{'PASS' if status else 'FAIL'}"
    )

if not all(
    GENERATOR_DIMENSION_VALIDATION.values()
):

    raise RuntimeError(
        "Generator input/output dimension "
        "validation failed."
    )

print()
print(
    "All Generator dimensions are valid."
)

====================================================================================================
PART H6 — GENERATOR INPUT/OUTPUT VALIDATION
====================================================================================================

Adult Income
Expected Input Dimension  : 128
Actual Input Dimension    : 128
Expected Output Dimension : 15
Actual Output Dimension   : 15
Input Check               : PASS
Output Check              : PASS
Overall                   : PASS

Bank Marketing
Expected Input Dimension  : 128
Actual Input Dimension    : 128
Expected Output Dimension : 17
Actual Output Dimension   : 17
Input Check               : PASS
Output Check              : PASS
Overall                   : PASS

diabetes_130us
Expected Input Dimension  : 128
Actual Input Dimension    : 128
Expected Output Dimension : 48
Actual Output Dimension   : 48
Input Check               : PASS
Output Check              : PASS
Overall                   : PASS

All Generator dimensions are valid.

In [159]:
# ==============================================================================
# PART H7 — DISCRIMINATOR INPUT/OUTPUT VALIDATION
# ==============================================================================

print("=" * 100)
print("PART H7 — DISCRIMINATOR INPUT/OUTPUT VALIDATION")
print("=" * 100)

DISCRIMINATOR_DIMENSION_VALIDATION = {}

VALIDATION_BATCH_SIZE = 8

for dataset in DATASETS:

    discriminator = DISCRIMINATORS[dataset]

    expected_input_dimension = (
        TRAIN_DATASETS[dataset].shape[1]
    )

    expected_output_dimension = 1

    test_data = torch.randn(
        VALIDATION_BATCH_SIZE,
        expected_input_dimension,
        device=DEVICE
    )

    discriminator.train()

    discriminator_output = discriminator(
        test_data
    )

    actual_input_dimension = (
        test_data.shape[1]
    )

    actual_output_dimension = (
        discriminator_output.shape[1]
    )

    input_check = (
        actual_input_dimension
        == expected_input_dimension
    )

    output_check = (
        actual_output_dimension
        == expected_output_dimension
    )

    status = (
        input_check
        and output_check
    )

    DISCRIMINATOR_DIMENSION_VALIDATION[
        dataset
    ] = status

    print()
    print(dataset)

    print(
        f"Expected Input Dimension  : "
        f"{expected_input_dimension}"
    )

    print(
        f"Actual Input Dimension    : "
        f"{actual_input_dimension}"
    )

    print(
        f"Expected Output Dimension : "
        f"{expected_output_dimension}"
    )

    print(
        f"Actual Output Dimension   : "
        f"{actual_output_dimension}"
    )

    print(
        f"Input Check               : "
        f"{'PASS' if input_check else 'FAIL'}"
    )

    print(
        f"Output Check              : "
        f"{'PASS' if output_check else 'FAIL'}"
    )

    print(
        f"Overall                   : "
        f"{'PASS' if status else 'FAIL'}"
    )

if not all(
    DISCRIMINATOR_DIMENSION_VALIDATION.values()
):

    raise RuntimeError(
        "Discriminator input/output dimension "
        "validation failed."
    )

print()
print(
    "All Discriminator dimensions are valid."
)

====================================================================================================
PART H7 — DISCRIMINATOR INPUT/OUTPUT VALIDATION
====================================================================================================

Adult Income
Expected Input Dimension  : 15
Actual Input Dimension    : 15
Expected Output Dimension : 1
Actual Output Dimension   : 1
Input Check               : PASS
Output Check              : PASS
Overall                   : PASS

Bank Marketing
Expected Input Dimension  : 17
Actual Input Dimension    : 17
Expected Output Dimension : 1
Actual Output Dimension   : 1
Input Check               : PASS
Output Check              : PASS
Overall                   : PASS

diabetes_130us
Expected Input Dimension  : 48
Actual Input Dimension    : 48
Expected Output Dimension : 1
Actual Output Dimension   : 1
Input Check               : PASS
Output Check              : PASS
Overall                   : PASS

All Discriminator dimensions are valid.

In [160]:
# ==============================================================================
# PART H8 — GENERATOR-DISCRIMINATOR COMPATIBILITY VALIDATION
# ==============================================================================

print("=" * 100)
print("PART H8 — GENERATOR-DISCRIMINATOR COMPATIBILITY VALIDATION")
print("=" * 100)

GAN_ARCHITECTURE_COMPATIBILITY = {}

for dataset in DATASETS:

    training_dimension = (
        TRAIN_DATASETS[dataset].shape[1]
    )

    generator_output_dimension = (
        GENERATOR_OUTPUT_DIMENSIONS[dataset]
    )

    discriminator_input_dimension = (
        DISCRIMINATOR_INPUT_DIMENSIONS[dataset]
    )

    compatible = (
        training_dimension
        == generator_output_dimension
        == discriminator_input_dimension
    )

    GAN_ARCHITECTURE_COMPATIBILITY[
        dataset
    ] = compatible

    print()
    print(dataset)

    print(
        f"Training Features       : "
        f"{training_dimension}"
    )

    print(
        f"Generator Output        : "
        f"{generator_output_dimension}"
    )

    print(
        f"Discriminator Input     : "
        f"{discriminator_input_dimension}"
    )

    print(
        f"Compatibility            : "
        f"{'PASS' if compatible else 'FAIL'}"
    )

if not all(
    GAN_ARCHITECTURE_COMPATIBILITY.values()
):

    raise RuntimeError(
        "Generator and Discriminator "
        "dimensions are incompatible."
    )

print()
print(
    "Generator–Discriminator compatibility "
    "validated successfully."
)

====================================================================================================
PART H8 — GENERATOR-DISCRIMINATOR COMPATIBILITY VALIDATION
====================================================================================================

Adult Income
Training Features       : 15
Generator Output        : 15
Discriminator Input     : 15
Compatibility            : PASS

Bank Marketing
Training Features       : 17
Generator Output        : 17
Discriminator Input     : 17
Compatibility            : PASS

diabetes_130us
Training Features       : 48
Generator Output        : 48
Discriminator Input     : 48
Compatibility            : PASS

Generator–Discriminator compatibility validated successfully.

In [161]:
# ==============================================================================
# PART H9 — TRAINING MODE VALIDATION
# ==============================================================================

print("=" * 100)
print("PART H9 — TRAINING MODE VALIDATION")
print("=" * 100)

TRAINING_MODE_VALIDATION = {}

for dataset in DATASETS:

    generator = GENERATORS[dataset]
    discriminator = DISCRIMINATORS[dataset]

    generator.train()
    discriminator.train()

    generator_training_mode = (
        generator.training
    )

    discriminator_training_mode = (
        discriminator.training
    )

    status = (
        generator_training_mode
        and discriminator_training_mode
    )

    TRAINING_MODE_VALIDATION[
        dataset
    ] = status

    print()
    print(dataset)

    print(
        f"Generator Training Mode     : "
        f"{'PASS' if generator_training_mode else 'FAIL'}"
    )

    print(
        f"Discriminator Training Mode : "
        f"{'PASS' if discriminator_training_mode else 'FAIL'}"
    )

    print(
        f"Overall                     : "
        f"{'PASS' if status else 'FAIL'}"
    )

if not all(
    TRAINING_MODE_VALIDATION.values()
):

    raise RuntimeError(
        "One or more models are not "
        "in training mode."
    )

print()
print(
    "All models are in training mode."
)

====================================================================================================
PART H9 — TRAINING MODE VALIDATION
====================================================================================================

Adult Income
Generator Training Mode     : PASS
Discriminator Training Mode : PASS
Overall                     : PASS

Bank Marketing
Generator Training Mode     : PASS
Discriminator Training Mode : PASS
Overall                     : PASS

diabetes_130us
Generator Training Mode     : PASS
Discriminator Training Mode : PASS
Overall                     : PASS

All models are in training mode.

In [162]:
# ==============================================================================
# PART H10 — OPACUS VALIDATION SUMMARY
# ==============================================================================

print("=" * 100)
print("PART H10 — OPACUS VALIDATION SUMMARY")
print("=" * 100)

OPACUS_VALIDATION_SUMMARY = {}

for dataset in DATASETS:

    generator_check = (
        GENERATOR_OPACUS_VALIDATION[
            dataset
        ]["Passed"]
    )

    discriminator_check = (
        DISCRIMINATOR_OPACUS_VALIDATION[
            dataset
        ]["Passed"]
    )

    generator_dimension_check = (
        GENERATOR_DIMENSION_VALIDATION[
            dataset
        ]
    )

    discriminator_dimension_check = (
        DISCRIMINATOR_DIMENSION_VALIDATION[
            dataset
        ]
    )

    architecture_check = (
        GAN_ARCHITECTURE_COMPATIBILITY[
            dataset
        ]
    )

    training_mode_check = (
        TRAINING_MODE_VALIDATION[
            dataset
        ]
    )

    overall_status = (
        generator_check
        and discriminator_check
        and generator_dimension_check
        and discriminator_dimension_check
        and architecture_check
        and training_mode_check
    )

    OPACUS_VALIDATION_SUMMARY[
        dataset
    ] = {
        "Generator Opacus": generator_check,
        "Discriminator Opacus": discriminator_check,
        "Generator Dimensions": generator_dimension_check,
        "Discriminator Dimensions": discriminator_dimension_check,
        "Architecture Compatibility": architecture_check,
        "Training Mode": training_mode_check,
        "Overall": overall_status
    }

    print()
    print(dataset)
    print(
        f"Generator Opacus        : "
        f"{'PASS' if generator_check else 'FAIL'}"
    )
    print(
        f"Discriminator Opacus    : "
        f"{'PASS' if discriminator_check else 'FAIL'}"
    )
    print(
        f"Generator Dimensions    : "
        f"{'PASS' if generator_dimension_check else 'FAIL'}"
    )
    print(
        f"Discriminator Dimensions: "
        f"{'PASS' if discriminator_dimension_check else 'FAIL'}"
    )
    print(
        f"Architecture Compatible : "
        f"{'PASS' if architecture_check else 'FAIL'}"
    )
    print(
        f"Training Mode            : "
        f"{'PASS' if training_mode_check else 'FAIL'}"
    )
    print(
        f"Overall                 : "
        f"{'PASS' if overall_status else 'FAIL'}"
    )

if not all(
    result["Overall"]
    for result in OPACUS_VALIDATION_SUMMARY.values()
):

    raise RuntimeError(
        "PART H failed. "
        "Do not proceed to the PrivacyEngine "
        "configuration until all validation "
        "checks pass."
    )

print()
print("=" * 100)
print("PART H COMPLETED SUCCESSFULLY")
print("All Opacus compatibility checks passed.")
print("=" * 100)

====================================================================================================
PART H10 — OPACUS VALIDATION SUMMARY
====================================================================================================

Adult Income
Generator Opacus        : PASS
Discriminator Opacus    : PASS
Generator Dimensions    : PASS
Discriminator Dimensions: PASS
Architecture Compatible : PASS
Training Mode            : PASS
Overall                 : PASS

Bank Marketing
Generator Opacus        : PASS
Discriminator Opacus    : PASS
Generator Dimensions    : PASS
Discriminator Dimensions: PASS
Architecture Compatible : PASS
Training Mode            : PASS
Overall                 : PASS

diabetes_130us
Generator Opacus        : PASS
Discriminator Opacus    : PASS
Generator Dimensions    : PASS
Discriminator Dimensions: PASS
Architecture Compatible : PASS
Training Mode            : PASS
Overall                 : PASS

====================================================================================================
PART H COMPLETED SUCCESSFULLY
All Opacus compatibility checks passed.
====================================================================================================

In [163]:
# ==============================================================================
# PART H11 — FINAL MODEL VALIDATION RECORD
# ==============================================================================

print("=" * 100)
print("PART H11 — FINAL MODEL VALIDATION RECORD")
print("=" * 100)

DP_MODEL_VALIDATION_STATUS = {}

for dataset in DATASETS:

    DP_MODEL_VALIDATION_STATUS[
        dataset
    ] = True

print(
    f"Validated Datasets : "
    f"{list(DP_MODEL_VALIDATION_STATUS.keys())}"
)

print(
    f"All Models Validated : "
    f"{all(DP_MODEL_VALIDATION_STATUS.values())}"
)

if not all(
    DP_MODEL_VALIDATION_STATUS.values()
):

    raise RuntimeError(
        "DP model validation record failed."
    )

print()
print(
    "DP-CTGAN models are ready for "
    "optimizer and PrivacyEngine configuration."
)

====================================================================================================
PART H11 — FINAL MODEL VALIDATION RECORD
====================================================================================================
Validated Datasets : ['Adult Income', 'Bank Marketing', 'diabetes_130us']
All Models Validated : True

DP-CTGAN models are ready for optimizer and PrivacyEngine configuration.

In [164]:
# ==============================================================================
# PART I1 — LOSS FUNCTION CONFIGURATION
# ==============================================================================

print("=" * 100)
print("PART I1 — LOSS FUNCTION CONFIGURATION")
print("=" * 100)

LOSS_FUNCTION_NAME = "BCEWithLogitsLoss"

print(
    f"Generator/Discriminator Loss : "
    f"{LOSS_FUNCTION_NAME}"
)

print(
    "Discriminator output activation: Raw logits"
)

print(
    "Sigmoid activation is handled internally "
    "by BCEWithLogitsLoss."
)

====================================================================================================
PART I1 — LOSS FUNCTION CONFIGURATION
====================================================================================================
Generator/Discriminator Loss : BCEWithLogitsLoss
Discriminator output activation: Raw logits
Sigmoid activation is handled internally by BCEWithLogitsLoss.

In [165]:
# ==============================================================================
# PART I2 — BINARY CROSS-ENTROPY WITH LOGITS LOSS
# ==============================================================================

import torch.nn as nn

DISCRIMINATOR_LOSS_FUNCTION = nn.BCEWithLogitsLoss()

print("=" * 100)
print("PART I2 — BINARY CROSS-ENTROPY WITH LOGITS LOSS")
print("=" * 100)

print(
    "BCEWithLogitsLoss initialized successfully."
)

print(
    f"Loss Function : "
    f"{DISCRIMINATOR_LOSS_FUNCTION}"
)

====================================================================================================
PART I2 — BINARY CROSS-ENTROPY WITH LOGITS LOSS
====================================================================================================
BCEWithLogitsLoss initialized successfully.
Loss Function : BCEWithLogitsLoss()

In [166]:
# ==============================================================================
# PART I3 — GENERATOR LOSS FUNCTION
# ==============================================================================

GENERATOR_LOSS_FUNCTION = nn.BCEWithLogitsLoss()

print("=" * 100)
print("PART I3 — GENERATOR LOSS FUNCTION")
print("=" * 100)

print(
    "Generator loss initialized successfully."
)

print(
    f"Loss Function : "
    f"{GENERATOR_LOSS_FUNCTION}"
)

====================================================================================================
PART I3 — GENERATOR LOSS FUNCTION
====================================================================================================
Generator loss initialized successfully.
Loss Function : BCEWithLogitsLoss()

In [167]:
# ==============================================================================
# PART I4 — REAL AND FAKE LABEL CONFIGURATION
# ==============================================================================

REAL_LABEL_VALUE = 1.0
FAKE_LABEL_VALUE = 0.0

print("=" * 100)
print("PART I4 — REAL AND FAKE LABEL CONFIGURATION")
print("=" * 100)

print(
    f"Real Label : {REAL_LABEL_VALUE}"
)

print(
    f"Fake Label : {FAKE_LABEL_VALUE}"
)

====================================================================================================
PART I4 — REAL AND FAKE LABEL CONFIGURATION
====================================================================================================
Real Label : 1.0
Fake Label : 0.0

In [168]:
# ==============================================================================
# PART I5 — LOSS LABEL CREATION FUNCTION
# ==============================================================================

def create_real_labels(
    batch_size,
    device
):

    return torch.full(
        (
            batch_size,
            1
        ),
        REAL_LABEL_VALUE,
        dtype=torch.float32,
        device=device
    )


def create_fake_labels(
    batch_size,
    device
):

    return torch.full(
        (
            batch_size,
            1
        ),
        FAKE_LABEL_VALUE,
        dtype=torch.float32,
        device=device
    )


print("=" * 100)
print("PART I5 — LOSS LABEL CREATION FUNCTION")
print("=" * 100)

print(
    "Real and fake label functions "
    "defined successfully."
)

====================================================================================================
PART I5 — LOSS LABEL CREATION FUNCTION
====================================================================================================
Real and fake label functions defined successfully.

In [169]:
# ==============================================================================
# PART I6 — LOSS FUNCTION SHAPE VALIDATION
# ==============================================================================

print("=" * 100)
print("PART I6 — LOSS FUNCTION SHAPE VALIDATION")
print("=" * 100)

LOSS_VALIDATION_BATCH_SIZE = 8

test_real_labels = create_real_labels(
    LOSS_VALIDATION_BATCH_SIZE,
    DEVICE
)

test_fake_labels = create_fake_labels(
    LOSS_VALIDATION_BATCH_SIZE,
    DEVICE
)

test_logits = torch.randn(
    LOSS_VALIDATION_BATCH_SIZE,
    1,
    device=DEVICE
)

real_loss = DISCRIMINATOR_LOSS_FUNCTION(
    test_logits,
    test_real_labels
)

fake_loss = DISCRIMINATOR_LOSS_FUNCTION(
    test_logits,
    test_fake_labels
)

generator_loss = GENERATOR_LOSS_FUNCTION(
    test_logits,
    test_real_labels
)

print(
    f"Logits Shape       : "
    f"{tuple(test_logits.shape)}"
)

print(
    f"Real Labels Shape  : "
    f"{tuple(test_real_labels.shape)}"
)

print(
    f"Fake Labels Shape  : "
    f"{tuple(test_fake_labels.shape)}"
)

print(
    f"Real Loss          : "
    f"{real_loss.item():.6f}"
)

print(
    f"Fake Loss          : "
    f"{fake_loss.item():.6f}"
)

print(
    f"Generator Loss     : "
    f"{generator_loss.item():.6f}"
)

if not torch.isfinite(real_loss):
    raise RuntimeError(
        "Real-data discriminator loss is not finite."
    )

if not torch.isfinite(fake_loss):
    raise RuntimeError(
        "Fake-data discriminator loss is not finite."
    )

if not torch.isfinite(generator_loss):
    raise RuntimeError(
        "Generator loss is not finite."
    )

print()
print(
    "Loss function shape and numerical "
    "validation: PASS"
)

====================================================================================================
PART I6 — LOSS FUNCTION SHAPE VALIDATION
====================================================================================================
Logits Shape       : (8, 1)
Real Labels Shape  : (8, 1)
Fake Labels Shape  : (8, 1)
Real Loss          : 1.088338
Fake Loss          : 0.636316
Generator Loss     : 1.088338

Loss function shape and numerical validation: PASS

In [170]:
# ==============================================================================
# PART I7 — DISCRIMINATOR LOSS FUNCTION
# ==============================================================================

def calculate_discriminator_loss(
    real_logits,
    fake_logits
):

    real_labels = create_real_labels(
        real_logits.size(0),
        real_logits.device
    )

    fake_labels = create_fake_labels(
        fake_logits.size(0),
        fake_logits.device
    )

    real_loss = DISCRIMINATOR_LOSS_FUNCTION(
        real_logits,
        real_labels
    )

    fake_loss = DISCRIMINATOR_LOSS_FUNCTION(
        fake_logits,
        fake_labels
    )

    discriminator_loss = (
        real_loss + fake_loss
    ) / 2.0

    return discriminator_loss


print("=" * 100)
print("PART I7 — DISCRIMINATOR LOSS FUNCTION")
print("=" * 100)

print(
    "Discriminator loss function defined successfully."
)

====================================================================================================
PART I7 — DISCRIMINATOR LOSS FUNCTION
====================================================================================================
Discriminator loss function defined successfully.

In [171]:
# ==============================================================================
# PART I8 — GENERATOR LOSS FUNCTION
# ==============================================================================

def calculate_generator_loss(
    fake_logits
):

    real_labels = create_real_labels(
        fake_logits.size(0),
        fake_logits.device
    )

    generator_loss = (
        GENERATOR_LOSS_FUNCTION(
            fake_logits,
            real_labels
        )
    )

    return generator_loss


print("=" * 100)
print("PART I8 — GENERATOR LOSS FUNCTION")
print("=" * 100)

print(
    "Generator loss function defined successfully."
)

====================================================================================================
PART I8 — GENERATOR LOSS FUNCTION
====================================================================================================
Generator loss function defined successfully.

In [172]:
# ==============================================================================
# PART I9 — GAN LOSS FUNCTION TEST")
# ==============================================================================

print("=" * 100)
print("PART I9 — GAN LOSS FUNCTION TEST")
print("=" * 100)

TEST_BATCH_SIZE = 8

test_real_logits = torch.randn(
    TEST_BATCH_SIZE,
    1,
    device=DEVICE
)

test_fake_logits = torch.randn(
    TEST_BATCH_SIZE,
    1,
    device=DEVICE
)

test_discriminator_loss = (
    calculate_discriminator_loss(
        test_real_logits,
        test_fake_logits
    )
)

test_generator_loss = (
    calculate_generator_loss(
        test_fake_logits
    )
)

print(
    f"Discriminator Loss : "
    f"{test_discriminator_loss.item():.6f}"
)

print(
    f"Generator Loss     : "
    f"{test_generator_loss.item():.6f}"
)

if not torch.isfinite(
    test_discriminator_loss
):

    raise RuntimeError(
        "Discriminator loss test failed."
    )

if not torch.isfinite(
    test_generator_loss
):

    raise RuntimeError(
        "Generator loss test failed."
    )

print()
print(
    "GAN loss function test: PASS"
)

====================================================================================================
PART I9 — GAN LOSS FUNCTION TEST
====================================================================================================
Discriminator Loss : 0.780857
Generator Loss     : 1.072260

GAN loss function test: PASS

In [173]:
# ==============================================================================
# PART I10 — DATASET-WISE LOSS VALIDATION
# ==============================================================================

print("=" * 100)
print("PART I10 — DATASET-WISE LOSS VALIDATION")
print("=" * 100)

LOSS_FUNCTION_VALIDATION = {}

for dataset in DATASETS:

    batch_size = min(
        8,
        len(TRAIN_DATASETS[dataset])
    )

    real_logits = torch.randn(
        batch_size,
        1,
        device=DEVICE
    )

    fake_logits = torch.randn(
        batch_size,
        1,
        device=DEVICE
    )

    discriminator_loss = (
        calculate_discriminator_loss(
            real_logits,
            fake_logits
        )
    )

    generator_loss = (
        calculate_generator_loss(
            fake_logits
        )
    )

    discriminator_valid = (
        torch.isfinite(
            discriminator_loss
        ).item()
    )

    generator_valid = (
        torch.isfinite(
            generator_loss
        ).item()
    )

    overall_status = (
        discriminator_valid
        and generator_valid
    )

    LOSS_FUNCTION_VALIDATION[
        dataset
    ] = overall_status

    print()
    print(dataset)

    print(
        f"Discriminator Loss : "
        f"{discriminator_loss.item():.6f}"
    )

    print(
        f"Generator Loss     : "
        f"{generator_loss.item():.6f}"
    )

    print(
        f"Discriminator Check : "
        f"{'PASS' if discriminator_valid else 'FAIL'}"
    )

    print(
        f"Generator Check     : "
        f"{'PASS' if generator_valid else 'FAIL'}"
    )

    print(
        f"Overall             : "
        f"{'PASS' if overall_status else 'FAIL'}"
    )

if not all(
    LOSS_FUNCTION_VALIDATION.values()
):

    raise RuntimeError(
        "Loss validation failed for one or more datasets."
    )

print()
print(
    "Loss functions validated for all datasets."
)

====================================================================================================
PART I10 — DATASET-WISE LOSS VALIDATION
====================================================================================================

Adult Income
Discriminator Loss : 0.835928
Generator Loss     : 0.703847
Discriminator Check : PASS
Generator Check     : PASS
Overall             : PASS

Bank Marketing
Discriminator Loss : 0.909957
Generator Loss     : 0.453247
Discriminator Check : PASS
Generator Check     : PASS
Overall             : PASS

diabetes_130us
Discriminator Loss : 0.843400
Generator Loss     : 0.988738
Discriminator Check : PASS
Generator Check     : PASS
Overall             : PASS

Loss functions validated for all datasets.

In [174]:
# ==============================================================================
# PART I11 — FINAL LOSS FUNCTION VERIFICATION
# ==============================================================================

print("=" * 100)
print("PART I11 — FINAL LOSS FUNCTION VERIFICATION")
print("=" * 100)

LOSS_FUNCTION_FINAL_STATUS = {}

for dataset in DATASETS:

    loss_check = (
        LOSS_FUNCTION_VALIDATION[dataset]
    )

    LOSS_FUNCTION_FINAL_STATUS[
        dataset
    ] = loss_check

    print()
    print(dataset)
    print(
        f"Loss Function Validation : "
        f"{'PASS' if loss_check else 'FAIL'}"
    )

if not all(
    LOSS_FUNCTION_FINAL_STATUS.values()
):

    raise RuntimeError(
        "Final loss function verification failed."
    )

print()
print("=" * 100)
print("PART I COMPLETED SUCCESSFULLY")
print("All loss function checks passed.")
print("=" * 100)

====================================================================================================
PART I11 — FINAL LOSS FUNCTION VERIFICATION
====================================================================================================

Adult Income
Loss Function Validation : PASS

Bank Marketing
Loss Function Validation : PASS

diabetes_130us
Loss Function Validation : PASS

====================================================================================================
PART I COMPLETED SUCCESSFULLY
All loss function checks passed.
====================================================================================================

In [175]:
# ==============================================================================
# PART J1 — OPTIMIZER CONFIGURATION
# ==============================================================================

print("=" * 100)
print("PART J1 — OPTIMIZER CONFIGURATION")
print("=" * 100)

OPTIMIZER_NAME = "Adam"

OPTIMIZER_LEARNING_RATE = 0.0002

OPTIMIZER_BETA1 = 0.5

OPTIMIZER_BETA2 = 0.999

OPTIMIZER_EPSILON = 1e-8

print(
    f"Optimizer        : {OPTIMIZER_NAME}"
)

print(
    f"Learning Rate     : {OPTIMIZER_LEARNING_RATE}"
)

print(
    f"Beta 1            : {OPTIMIZER_BETA1}"
)

print(
    f"Beta 2            : {OPTIMIZER_BETA2}"
)

print(
    f"Epsilon           : {OPTIMIZER_EPSILON}"
)

====================================================================================================
PART J1 — OPTIMIZER CONFIGURATION
====================================================================================================
Optimizer        : Adam
Learning Rate     : 0.0002
Beta 1            : 0.5
Beta 2            : 0.999
Epsilon           : 1e-08

In [176]:
# ==============================================================================
# PART J2 — OPTIMIZER PARAMETER VALIDATION
# ==============================================================================

print("=" * 100)
print("PART J2 — OPTIMIZER PARAMETER VALIDATION")
print("=" * 100)

if OPTIMIZER_LEARNING_RATE <= 0:

    raise ValueError(
        "Learning rate must be greater than zero."
    )

if not 0 <= OPTIMIZER_BETA1 < 1:

    raise ValueError(
        "Beta1 must be in the range [0, 1)."
    )

if not 0 <= OPTIMIZER_BETA2 < 1:

    raise ValueError(
        "Beta2 must be in the range [0, 1)."
    )

if OPTIMIZER_EPSILON <= 0:

    raise ValueError(
        "Optimizer epsilon must be greater than zero."
    )

print(
    "Learning Rate : PASS"
)

print(
    "Beta1         : PASS"
)

print(
    "Beta2         : PASS"
)

print(
    "Epsilon       : PASS"
)

print()
print(
    "Optimizer configuration validation: PASS"
)

====================================================================================================
PART J2 — OPTIMIZER PARAMETER VALIDATION
====================================================================================================
Learning Rate : PASS
Beta1         : PASS
Beta2         : PASS
Epsilon       : PASS

Optimizer configuration validation: PASS

In [177]:
# ==============================================================================
# PART J3 — GENERATOR OPTIMIZER CREATION
# ==============================================================================

print("=" * 100)
print("PART J3 — GENERATOR OPTIMIZER CREATION")
print("=" * 100)

GENERATOR_OPTIMIZERS = {}

for dataset in DATASETS:

    generator = GENERATORS[dataset]

    generator.train()

    generator_optimizer = torch.optim.Adam(
        generator.parameters(),
        lr=OPTIMIZER_LEARNING_RATE,
        betas=(
            OPTIMIZER_BETA1,
            OPTIMIZER_BETA2
        ),
        eps=OPTIMIZER_EPSILON
    )

    GENERATOR_OPTIMIZERS[
        dataset
    ] = generator_optimizer

    print()
    print(dataset)

    print(
        "Generator Optimizer : Adam"
    )

    print(
        f"Learning Rate       : "
        f"{OPTIMIZER_LEARNING_RATE}"
    )

    print(
        f"Parameters          : "
        f"{sum(p.numel() for p in generator.parameters() if p.requires_grad):,}"
    )

print()
print(
    "Generator optimizers created successfully."
)

====================================================================================================
PART J3 — GENERATOR OPTIMIZER CREATION
====================================================================================================

Adult Income
Generator Optimizer : Adam
Learning Rate       : 0.0002
Parameters          : 233,999

Bank Marketing
Generator Optimizer : Adam
Learning Rate       : 0.0002
Parameters          : 234,257

diabetes_130us
Generator Optimizer : Adam
Learning Rate       : 0.0002
Parameters          : 238,256

Generator optimizers created successfully.

In [178]:
# ==============================================================================
# PART J4 — DISCRIMINATOR OPTIMIZER CREATION
# ==============================================================================

print("=" * 100)
print("PART J4 — DISCRIMINATOR OPTIMIZER CREATION")
print("=" * 100)

DISCRIMINATOR_OPTIMIZERS = {}

for dataset in DATASETS:

    discriminator = DISCRIMINATORS[dataset]

    discriminator.train()

    discriminator_optimizer = torch.optim.Adam(
        discriminator.parameters(),
        lr=OPTIMIZER_LEARNING_RATE,
        betas=(
            OPTIMIZER_BETA1,
            OPTIMIZER_BETA2
        ),
        eps=OPTIMIZER_EPSILON
    )

    DISCRIMINATOR_OPTIMIZERS[
        dataset
    ] = discriminator_optimizer

    print()
    print(dataset)

    print(
        "Discriminator Optimizer : Adam"
    )

    print(
        f"Learning Rate           : "
        f"{OPTIMIZER_LEARNING_RATE}"
    )

    print(
        f"Parameters              : "
        f"{sum(p.numel() for p in discriminator.parameters() if p.requires_grad):,}"
    )

print()
print(
    "Discriminator optimizers created successfully."
)

====================================================================================================
PART J4 — DISCRIMINATOR OPTIMIZER CREATION
====================================================================================================

Adult Income
Discriminator Optimizer : Adam
Learning Rate           : 0.0002
Parameters              : 174,337

Bank Marketing
Discriminator Optimizer : Adam
Learning Rate           : 0.0002
Parameters              : 175,361

diabetes_130us
Discriminator Optimizer : Adam
Learning Rate           : 0.0002
Parameters              : 191,233

Discriminator optimizers created successfully.

In [179]:
# ==============================================================================
# PART J5 — OPTIMIZER TYPE VALIDATION
# ==============================================================================

print("=" * 100)
print("PART J5 — OPTIMIZER TYPE VALIDATION")
print("=" * 100)

OPTIMIZER_TYPE_VALIDATION = {}

for dataset in DATASETS:

    generator_optimizer = (
        GENERATOR_OPTIMIZERS[dataset]
    )

    discriminator_optimizer = (
        DISCRIMINATOR_OPTIMIZERS[dataset]
    )

    generator_check = isinstance(
        generator_optimizer,
        torch.optim.Adam
    )

    discriminator_check = isinstance(
        discriminator_optimizer,
        torch.optim.Adam
    )

    overall_check = (
        generator_check
        and discriminator_check
    )

    OPTIMIZER_TYPE_VALIDATION[
        dataset
    ] = overall_check

    print()
    print(dataset)

    print(
        f"Generator Optimizer     : "
        f"{'PASS' if generator_check else 'FAIL'}"
    )

    print(
        f"Discriminator Optimizer : "
        f"{'PASS' if discriminator_check else 'FAIL'}"
    )

    print(
        f"Overall                 : "
        f"{'PASS' if overall_check else 'FAIL'}"
    )

if not all(
    OPTIMIZER_TYPE_VALIDATION.values()
):

    raise RuntimeError(
        "Optimizer type validation failed."
    )

print()
print(
    "All optimizer types validated successfully."
)

====================================================================================================
PART J5 — OPTIMIZER TYPE VALIDATION
====================================================================================================

Adult Income
Generator Optimizer     : PASS
Discriminator Optimizer : PASS
Overall                 : PASS

Bank Marketing
Generator Optimizer     : PASS
Discriminator Optimizer : PASS
Overall                 : PASS

diabetes_130us
Generator Optimizer     : PASS
Discriminator Optimizer : PASS
Overall                 : PASS

All optimizer types validated successfully.

In [180]:
# ==============================================================================
# PART J6 — OPTIMIZER PARAMETER VALIDATION
# ==============================================================================

print("=" * 100)
print("PART J6 — OPTIMIZER PARAMETER VALIDATION")
print("=" * 100)

OPTIMIZER_PARAMETER_VALIDATION = {}

for dataset in DATASETS:

    generator_optimizer = (
        GENERATOR_OPTIMIZERS[dataset]
    )

    discriminator_optimizer = (
        DISCRIMINATOR_OPTIMIZERS[dataset]
    )

    generator_params = (
        generator_optimizer.param_groups[0]
    )

    discriminator_params = (
        discriminator_optimizer.param_groups[0]
    )

    generator_lr_check = (
        generator_params["lr"]
        == OPTIMIZER_LEARNING_RATE
    )

    discriminator_lr_check = (
        discriminator_params["lr"]
        == OPTIMIZER_LEARNING_RATE
    )

    generator_beta_check = (
        generator_params["betas"]
        == (
            OPTIMIZER_BETA1,
            OPTIMIZER_BETA2
        )
    )

    discriminator_beta_check = (
        discriminator_params["betas"]
        == (
            OPTIMIZER_BETA1,
            OPTIMIZER_BETA2
        )
    )

    overall_check = (
        generator_lr_check
        and discriminator_lr_check
        and generator_beta_check
        and discriminator_beta_check
    )

    OPTIMIZER_PARAMETER_VALIDATION[
        dataset
    ] = overall_check

    print()
    print(dataset)

    print(
        f"Generator Learning Rate     : "
        f"{'PASS' if generator_lr_check else 'FAIL'}"
    )

    print(
        f"Discriminator Learning Rate : "
        f"{'PASS' if discriminator_lr_check else 'FAIL'}"
    )

    print(
        f"Generator Betas             : "
        f"{'PASS' if generator_beta_check else 'FAIL'}"
    )

    print(
        f"Discriminator Betas         : "
        f"{'PASS' if discriminator_beta_check else 'FAIL'}"
    )

    print(
        f"Overall                     : "
        f"{'PASS' if overall_check else 'FAIL'}"
    )

if not all(
    OPTIMIZER_PARAMETER_VALIDATION.values()
):

    raise RuntimeError(
        "Optimizer parameter validation failed."
    )

print()
print(
    "All optimizer parameters validated successfully."
)

====================================================================================================
PART J6 — OPTIMIZER PARAMETER VALIDATION
====================================================================================================

Adult Income
Generator Learning Rate     : PASS
Discriminator Learning Rate : PASS
Generator Betas             : PASS
Discriminator Betas         : PASS
Overall                     : PASS

Bank Marketing
Generator Learning Rate     : PASS
Discriminator Learning Rate : PASS
Generator Betas             : PASS
Discriminator Betas         : PASS
Overall                     : PASS

diabetes_130us
Generator Learning Rate     : PASS
Discriminator Learning Rate : PASS
Generator Betas             : PASS
Discriminator Betas         : PASS
Overall                     : PASS

All optimizer parameters validated successfully.

In [181]:
# ==============================================================================
# PART J7 — GENERATOR OPTIMIZER PARAMETER MATCHING
# ==============================================================================

print("=" * 100)
print("PART J7 — GENERATOR OPTIMIZER PARAMETER MATCHING")
print("=" * 100)

GENERATOR_OPTIMIZER_PARAMETER_MATCH = {}

for dataset in DATASETS:

    generator = GENERATORS[dataset]

    optimizer = (
        GENERATOR_OPTIMIZERS[dataset]
    )

    model_parameters = {
        id(parameter)
        for parameter in generator.parameters()
        if parameter.requires_grad
    }

    optimizer_parameters = {
        id(parameter)
        for group in optimizer.param_groups
        for parameter in group["params"]
    }

    match = (
        model_parameters
        == optimizer_parameters
    )

    GENERATOR_OPTIMIZER_PARAMETER_MATCH[
        dataset
    ] = match

    print()
    print(dataset)

    print(
        f"Generator Parameters : "
        f"{len(model_parameters)}"
    )

    print(
        f"Optimizer Parameters : "
        f"{len(optimizer_parameters)}"
    )

    print(
        f"Parameter Match       : "
        f"{'PASS' if match else 'FAIL'}"
    )

if not all(
    GENERATOR_OPTIMIZER_PARAMETER_MATCH.values()
):

    raise RuntimeError(
        "Generator optimizer parameters do not "
        "match the Generator model parameters."
    )

print()
print(
    "All Generator optimizer parameter mappings "
    "validated successfully."
)

====================================================================================================
PART J7 — GENERATOR OPTIMIZER PARAMETER MATCHING
====================================================================================================

Adult Income
Generator Parameters : 14
Optimizer Parameters : 14
Parameter Match       : PASS

Bank Marketing
Generator Parameters : 14
Optimizer Parameters : 14
Parameter Match       : PASS

diabetes_130us
Generator Parameters : 14
Optimizer Parameters : 14
Parameter Match       : PASS

All Generator optimizer parameter mappings validated successfully.

In [182]:
# ==============================================================================
# PART J8 — DISCRIMINATOR OPTIMIZER PARAMETER MATCHING
# ==============================================================================

print("=" * 100)
print("PART J8 — DISCRIMINATOR OPTIMIZER PARAMETER MATCHING")
print("=" * 100)

DISCRIMINATOR_OPTIMIZER_PARAMETER_MATCH = {}

for dataset in DATASETS:

    discriminator = (
        DISCRIMINATORS[dataset]
    )

    optimizer = (
        DISCRIMINATOR_OPTIMIZERS[dataset]
    )

    model_parameters = {
        id(parameter)
        for parameter in discriminator.parameters()
        if parameter.requires_grad
    }

    optimizer_parameters = {
        id(parameter)
        for group in optimizer.param_groups
        for parameter in group["params"]
    }

    match = (
        model_parameters
        == optimizer_parameters
    )

    DISCRIMINATOR_OPTIMIZER_PARAMETER_MATCH[
        dataset
    ] = match

    print()
    print(dataset)

    print(
        f"Discriminator Parameters : "
        f"{len(model_parameters)}"
    )

    print(
        f"Optimizer Parameters     : "
        f"{len(optimizer_parameters)}"
    )

    print(
        f"Parameter Match           : "
        f"{'PASS' if match else 'FAIL'}"
    )

if not all(
    DISCRIMINATOR_OPTIMIZER_PARAMETER_MATCH.values()
):

    raise RuntimeError(
        "Discriminator optimizer parameters do not "
        "match the Discriminator model parameters."
    )

print()
print(
    "All Discriminator optimizer parameter mappings "
    "validated successfully."
)

====================================================================================================
PART J8 — DISCRIMINATOR OPTIMIZER PARAMETER MATCHING
====================================================================================================

Adult Income
Discriminator Parameters : 14
Optimizer Parameters     : 14
Parameter Match           : PASS

Bank Marketing
Discriminator Parameters : 14
Optimizer Parameters     : 14
Parameter Match           : PASS

diabetes_130us
Discriminator Parameters : 14
Optimizer Parameters     : 14
Parameter Match           : PASS

All Discriminator optimizer parameter mappings validated successfully.

In [183]:
# ==============================================================================
# PART J9 — OPTIMIZER GRADIENT FLOW TEST
# ==============================================================================

print("=" * 100)
print("PART J9 — OPTIMIZER GRADIENT FLOW TEST")
print("=" * 100)

OPTIMIZER_GRADIENT_VALIDATION = {}

TEST_BATCH_SIZE = 8

for dataset in DATASETS:

    generator = GENERATORS[dataset]
    discriminator = DISCRIMINATORS[dataset]

    generator_optimizer = (
        GENERATOR_OPTIMIZERS[dataset]
    )

    discriminator_optimizer = (
        DISCRIMINATOR_OPTIMIZERS[dataset]
    )

    generator.train()
    discriminator.train()

    generator_optimizer.zero_grad(
        set_to_none=True
    )

    discriminator_optimizer.zero_grad(
        set_to_none=True
    )

    noise = torch.randn(
        TEST_BATCH_SIZE,
        DP_LATENT_DIMENSION,
        device=DEVICE
    )

    generated_data = generator(
        noise
    )

    fake_logits = discriminator(
        generated_data
    )

    generator_loss = (
        calculate_generator_loss(
            fake_logits
        )
    )

    generator_loss.backward()

    generator_gradients_present = any(
        parameter.grad is not None
        for parameter in generator.parameters()
        if parameter.requires_grad
    )

    generator_optimizer.zero_grad(
        set_to_none=True
    )

    real_data = torch.as_tensor(
        TRAIN_DATASETS[dataset]
        .iloc[:TEST_BATCH_SIZE]
        .values,
        dtype=torch.float32,
        device=DEVICE
    )

    discriminator_real_logits = (
        discriminator(real_data)
    )

    discriminator_fake_logits = (
        discriminator(
            generated_data.detach()
        )
    )

    discriminator_loss = (
        calculate_discriminator_loss(
            discriminator_real_logits,
            discriminator_fake_logits
        )
    )

    discriminator_loss.backward()

    discriminator_gradients_present = any(
        parameter.grad is not None
        for parameter in discriminator.parameters()
        if parameter.requires_grad
    )

    discriminator_optimizer.zero_grad(
        set_to_none=True
    )

    status = (
        generator_gradients_present
        and discriminator_gradients_present
    )

    OPTIMIZER_GRADIENT_VALIDATION[
        dataset
    ] = status

    print()
    print(dataset)

    print(
        f"Generator Gradient Flow     : "
        f"{'PASS' if generator_gradients_present else 'FAIL'}"
    )

    print(
        f"Discriminator Gradient Flow : "
        f"{'PASS' if discriminator_gradients_present else 'FAIL'}"
    )

    print(
        f"Overall                     : "
        f"{'PASS' if status else 'FAIL'}"
    )

if not all(
    OPTIMIZER_GRADIENT_VALIDATION.values()
):

    raise RuntimeError(
        "Optimizer gradient flow validation failed."
    )

print()
print(
    "Optimizer gradient flow validated successfully."
)

====================================================================================================
PART J9 — OPTIMIZER GRADIENT FLOW TEST
====================================================================================================

Adult Income
Generator Gradient Flow     : PASS
Discriminator Gradient Flow : PASS
Overall                     : PASS

Bank Marketing
Generator Gradient Flow     : PASS
Discriminator Gradient Flow : PASS
Overall                     : PASS

diabetes_130us
Generator Gradient Flow     : PASS
Discriminator Gradient Flow : PASS
Overall                     : PASS

Optimizer gradient flow validated successfully.

In [184]:
# ==============================================================================
# PART J10 — OPTIMIZER STATE VALIDATION
# ==============================================================================

print("=" * 100)
print("PART J10 — OPTIMIZER STATE VALIDATION")
print("=" * 100)

OPTIMIZER_STATE_VALIDATION = {}

for dataset in DATASETS:

    generator_optimizer = (
        GENERATOR_OPTIMIZERS[dataset]
    )

    discriminator_optimizer = (
        DISCRIMINATOR_OPTIMIZERS[dataset]
    )

    generator_state_valid = (
        len(
            generator_optimizer.state
        ) == 0
    )

    discriminator_state_valid = (
        len(
            discriminator_optimizer.state
        ) == 0
    )

    status = (
        generator_state_valid
        and discriminator_state_valid
    )

    OPTIMIZER_STATE_VALIDATION[
        dataset
    ] = status

    print()
    print(dataset)

    print(
        f"Generator Optimizer State     : "
        f"{'PASS' if generator_state_valid else 'FAIL'}"
    )

    print(
        f"Discriminator Optimizer State : "
        f"{'PASS' if discriminator_state_valid else 'FAIL'}"
    )

    print(
        f"Overall                       : "
        f"{'PASS' if status else 'FAIL'}"
    )

print()
print(
    "Initial optimizer state validation completed."
)

====================================================================================================
PART J10 — OPTIMIZER STATE VALIDATION
====================================================================================================

Adult Income
Generator Optimizer State     : PASS
Discriminator Optimizer State : PASS
Overall                       : PASS

Bank Marketing
Generator Optimizer State     : PASS
Discriminator Optimizer State : PASS
Overall                       : PASS

diabetes_130us
Generator Optimizer State     : PASS
Discriminator Optimizer State : PASS
Overall                       : PASS

Initial optimizer state validation completed.

In [185]:
# ==============================================================================
# PART J11 — OPTIMIZER CONFIGURATION SUMMARY
# ==============================================================================

print("=" * 100)
print("PART J11 — OPTIMIZER CONFIGURATION SUMMARY")
print("=" * 100)

OPTIMIZER_CONFIGURATION_SUMMARY = {}

for dataset in DATASETS:

    generator_optimizer = (
        GENERATOR_OPTIMIZERS[dataset]
    )

    discriminator_optimizer = (
        DISCRIMINATOR_OPTIMIZERS[dataset]
    )

    generator_params = (
        generator_optimizer.param_groups[0]
    )

    discriminator_params = (
        discriminator_optimizer.param_groups[0]
    )

    OPTIMIZER_CONFIGURATION_SUMMARY[
        dataset
    ] = {
        "Optimizer": OPTIMIZER_NAME,
        "Learning Rate": OPTIMIZER_LEARNING_RATE,
        "Beta1": OPTIMIZER_BETA1,
        "Beta2": OPTIMIZER_BETA2,
        "Generator Parameters":
            sum(
                parameter.numel()
                for parameter in GENERATORS[dataset].parameters()
                if parameter.requires_grad
            ),
        "Discriminator Parameters":
            sum(
                parameter.numel()
                for parameter in DISCRIMINATORS[dataset].parameters()
                if parameter.requires_grad
            )
    }

    print()
    print(dataset)

    print(
        f"Optimizer               : "
        f"{OPTIMIZER_NAME}"
    )

    print(
        f"Learning Rate           : "
        f"{generator_params['lr']}"
    )

    print(
        f"Beta1                   : "
        f"{generator_params['betas'][0]}"
    )

    print(
        f"Beta2                   : "
        f"{generator_params['betas'][1]}"
    )

    print(
        f"Generator Parameters    : "
        f"{OPTIMIZER_CONFIGURATION_SUMMARY[dataset]['Generator Parameters']:,}"
    )

    print(
        f"Discriminator Parameters: "
        f"{OPTIMIZER_CONFIGURATION_SUMMARY[dataset]['Discriminator Parameters']:,}"
    )

====================================================================================================
PART J11 — OPTIMIZER CONFIGURATION SUMMARY
====================================================================================================

Adult Income
Optimizer               : Adam
Learning Rate           : 0.0002
Beta1                   : 0.5
Beta2                   : 0.999
Generator Parameters    : 233,999
Discriminator Parameters: 174,337

Bank Marketing
Optimizer               : Adam
Learning Rate           : 0.0002
Beta1                   : 0.5
Beta2                   : 0.999
Generator Parameters    : 234,257
Discriminator Parameters: 175,361

diabetes_130us
Optimizer               : Adam
Learning Rate           : 0.0002
Beta1                   : 0.5
Beta2                   : 0.999
Generator Parameters    : 238,256
Discriminator Parameters: 191,233

In [186]:
# ==============================================================================
# PART J12 — FINAL OPTIMIZER VERIFICATION
# ==============================================================================

print("=" * 100)
print("PART J12 — FINAL OPTIMIZER VERIFICATION")
print("=" * 100)

FINAL_OPTIMIZER_VERIFICATION = {}

for dataset in DATASETS:

    optimizer_type_check = (
        OPTIMIZER_TYPE_VALIDATION[dataset]
    )

    optimizer_parameter_check = (
        OPTIMIZER_PARAMETER_VALIDATION[dataset]
    )

    generator_mapping_check = (
        GENERATOR_OPTIMIZER_PARAMETER_MATCH[
            dataset
        ]
    )

    discriminator_mapping_check = (
        DISCRIMINATOR_OPTIMIZER_PARAMETER_MATCH[
            dataset
        ]
    )

    gradient_check = (
        OPTIMIZER_GRADIENT_VALIDATION[dataset]
    )

    final_status = (
        optimizer_type_check
        and optimizer_parameter_check
        and generator_mapping_check
        and discriminator_mapping_check
        and gradient_check
    )

    FINAL_OPTIMIZER_VERIFICATION[
        dataset
    ] = final_status

    print()
    print(dataset)

    print(
        f"Optimizer Type           : "
        f"{'PASS' if optimizer_type_check else 'FAIL'}"
    )

    print(
        f"Optimizer Parameters     : "
        f"{'PASS' if optimizer_parameter_check else 'FAIL'}"
    )

    print(
        f"Generator Mapping        : "
        f"{'PASS' if generator_mapping_check else 'FAIL'}"
    )

    print(
        f"Discriminator Mapping    : "
        f"{'PASS' if discriminator_mapping_check else 'FAIL'}"
    )

    print(
        f"Gradient Flow            : "
        f"{'PASS' if gradient_check else 'FAIL'}"
    )

    print(
        f"Final Status             : "
        f"{'PASS' if final_status else 'FAIL'}"
    )

if not all(
    FINAL_OPTIMIZER_VERIFICATION.values()
):

    raise RuntimeError(
        "Final optimizer verification failed. "
        "Do not proceed to Part K."
    )

print()
print("=" * 100)
print("PART J COMPLETED SUCCESSFULLY")
print("All optimizer checks passed.")
print("Optimizers are ready for PrivacyEngine configuration.")
print("=" * 100)

====================================================================================================
PART J12 — FINAL OPTIMIZER VERIFICATION
====================================================================================================

Adult Income
Optimizer Type           : PASS
Optimizer Parameters     : PASS
Generator Mapping        : PASS
Discriminator Mapping    : PASS
Gradient Flow            : PASS
Final Status             : PASS

Bank Marketing
Optimizer Type           : PASS
Optimizer Parameters     : PASS
Generator Mapping        : PASS
Discriminator Mapping    : PASS
Gradient Flow            : PASS
Final Status             : PASS

diabetes_130us
Optimizer Type           : PASS
Optimizer Parameters     : PASS
Generator Mapping        : PASS
Discriminator Mapping    : PASS
Gradient Flow            : PASS
Final Status             : PASS

====================================================================================================
PART J COMPLETED SUCCESSFULLY
All optimizer checks passed.
Optimizers are ready for PrivacyEngine configuration.
====================================================================================================

In [245]:
# ==============================================================================
# PART K1 — DIFFERENTIAL PRIVACY PARAMETERS
# ==============================================================================

print("=" * 100)
print("PART K1 — DIFFERENTIAL PRIVACY PARAMETERS")
print("=" * 100)


# ------------------------------------------------------------------------------
# Differential Privacy Configuration
# ------------------------------------------------------------------------------

DP_PRIVACY_BUDGET = 4.0        # epsilon
DP_DELTA = 1e-5                # delta

# Gradient clipping for DP-SGD
DP_MAX_GRAD_NORM = 1.0

# Training configuration
DP_BATCH_SIZE = 256
DP_EPOCHS = 100


# ------------------------------------------------------------------------------
# Display Configuration
# ------------------------------------------------------------------------------

DP_CONFIG = {

    "Privacy Budget (epsilon)": DP_PRIVACY_BUDGET,

    "Privacy Delta (delta)": DP_DELTA,

    "Maximum Gradient Norm": DP_MAX_GRAD_NORM,

    "Batch Size": DP_BATCH_SIZE,

    "Training Epochs": DP_EPOCHS
}


for key, value in DP_CONFIG.items():

    print(
        f"{key:30s}: {value}"
    )

====================================================================================================
PART K1 — DIFFERENTIAL PRIVACY PARAMETERS
====================================================================================================
Privacy Budget (epsilon)      : 4.0
Privacy Delta (delta)         : 1e-05
Maximum Gradient Norm         : 1.0
Batch Size                    : 256
Training Epochs               : 100

In [246]:
# ==============================================================================
# PART K2 — PRIVACY PARAMETER VALIDATION
# ==============================================================================

print("=" * 100)
print("PART K2 — PRIVACY PARAMETER VALIDATION")
print("=" * 100)


# ------------------------------------------------------------------------------
# Validate Differential Privacy Parameters
# ------------------------------------------------------------------------------

if DP_PRIVACY_BUDGET <= 0:

    raise ValueError(
        "Privacy budget epsilon must be greater than zero."
    )


if DP_PRIVACY_BUDGET > 20:

    raise ValueError(
        "Privacy budget epsilon is too large. "
        "Use a smaller value for meaningful privacy."
    )


if DP_DELTA <= 0 or DP_DELTA >= 1:

    raise ValueError(
        "Privacy delta must satisfy 0 < delta < 1."
    )


if DP_MAX_GRAD_NORM <= 0:

    raise ValueError(
        "Maximum gradient norm must be greater than zero."
    )


if DP_BATCH_SIZE <= 0:

    raise ValueError(
        "DP batch size must be greater than zero."
    )


if DP_EPOCHS <= 0:

    raise ValueError(
        "DP training epochs must be greater than zero."
    )


# ------------------------------------------------------------------------------
# Validation Report
# ------------------------------------------------------------------------------

VALIDATION_RESULTS = {

    "Privacy Budget (epsilon)": True,

    "Privacy Delta (delta)": True,

    "Gradient Clipping": True,

    "Batch Size": True,

    "Training Epochs": True
}


for key, value in VALIDATION_RESULTS.items():

    print(
        f"{key:30s}: PASS"
    )


print()

print(
    "Differential privacy parameter validation: PASS"
)

====================================================================================================
PART K2 — PRIVACY PARAMETER VALIDATION
====================================================================================================
Privacy Budget (epsilon)      : PASS
Privacy Delta (delta)         : PASS
Gradient Clipping             : PASS
Batch Size                    : PASS
Training Epochs               : PASS

Differential privacy parameter validation: PASS

In [247]:
# ==============================================================================
# PART K3 — PRIVACY ENGINE IMPORT
# ==============================================================================

print("=" * 100)
print("PART K3 — PRIVACY ENGINE IMPORT")
print("=" * 100)


import opacus

from opacus import PrivacyEngine


print(
    "PrivacyEngine imported successfully."
)


print(
    f"Opacus Version : {opacus.__version__}"
)

====================================================================================================
PART K3 — PRIVACY ENGINE IMPORT
====================================================================================================
PrivacyEngine imported successfully.
Opacus Version : 1.6.0

In [248]:
# ==============================================================================
# PART K4 — DP TRAINING DATA PREPARATION
# ==============================================================================

from torch.utils.data import TensorDataset, DataLoader


print("=" * 100)
print("PART K4 — DP TRAINING DATA PREPARATION")
print("=" * 100)


DP_TRAIN_DATASETS = {}
DP_TRAIN_TENSORS = {}
DP_TRAIN_DATALOADERS = {}


for dataset in DATASETS:

    print()
    print("-" * 80)
    print(dataset)


    train_dataframe = TRAIN_DATASETS[dataset].copy()


    # --------------------------------------------------------------------------
    # Numeric Validation
    # --------------------------------------------------------------------------

    non_numeric_columns = train_dataframe.select_dtypes(
        exclude=["number"]
    ).columns.tolist()


    if len(non_numeric_columns) > 0:

        raise TypeError(
            f"{dataset} contains non-numeric columns: "
            f"{non_numeric_columns}"
        )


    # --------------------------------------------------------------------------
    # Tensor Conversion
    # --------------------------------------------------------------------------

    train_tensor = torch.tensor(
        train_dataframe.values,
        dtype=torch.float32
    )


    # --------------------------------------------------------------------------
    # Tensor Dataset
    # --------------------------------------------------------------------------

    train_dataset = TensorDataset(
        train_tensor
    )


    # --------------------------------------------------------------------------
    # DP-Compatible DataLoader
    # --------------------------------------------------------------------------

    train_loader = DataLoader(
        train_dataset,
        batch_size=DP_BATCH_SIZE,
        shuffle=True,
        drop_last=True,
        generator=torch.Generator().manual_seed(SEED)
    )


    # --------------------------------------------------------------------------
    # Store Objects
    # --------------------------------------------------------------------------

    DP_TRAIN_DATASETS[dataset] = train_dataset

    DP_TRAIN_TENSORS[dataset] = train_tensor

    DP_TRAIN_DATALOADERS[dataset] = train_loader


    # --------------------------------------------------------------------------
    # Verification Output
    # --------------------------------------------------------------------------

    print(
        f"Rows              : {len(train_dataframe)}"
    )

    print(
        f"Features          : {train_dataframe.shape[1]}"
    )

    print(
        f"Tensor Shape      : {tuple(train_tensor.shape)}"
    )

    print(
        f"DataLoader Batches: {len(train_loader)}"
    )

    print(
        f"Batch Size        : {DP_BATCH_SIZE}"
    )

====================================================================================================
PART K4 — DP TRAINING DATA PREPARATION
====================================================================================================

--------------------------------------------------------------------------------
Adult Income
Rows              : 22760
Features          : 15
Tensor Shape      : (22760, 15)
DataLoader Batches: 88
Batch Size        : 256

--------------------------------------------------------------------------------
Bank Marketing
Rows              : 31647
Features          : 17
Tensor Shape      : (31647, 17)
DataLoader Batches: 123
Batch Size        : 256

--------------------------------------------------------------------------------
diabetes_130us
Rows              : 71236
Features          : 48
Tensor Shape      : (71236, 48)
DataLoader Batches: 278
Batch Size        : 256

In [249]:
# ==============================================================================
# PART K5 — DP TRAINING DATA VALIDATION
# ==============================================================================

print("=" * 100)
print("PART K5 — DP TRAINING DATA VALIDATION")
print("=" * 100)


DP_DATA_VALIDATION = {}


for dataset in DATASETS:

    train_dataframe = TRAIN_DATASETS[dataset]

    train_tensor = DP_TRAIN_TENSORS[dataset]

    train_loader = DP_TRAIN_DATALOADERS[dataset]


    expected_rows = len(train_dataframe)

    expected_features = train_dataframe.shape[1]


    actual_rows = train_tensor.shape[0]

    actual_features = train_tensor.shape[1]


    # --------------------------------------------------------------------------
    # Shape Validation
    # --------------------------------------------------------------------------

    tensor_shape_check = (

        actual_rows == expected_rows

        and

        actual_features == expected_features

    )


    # --------------------------------------------------------------------------
    # DataLoader Validation
    # --------------------------------------------------------------------------

    loader_check = (

        len(train_loader) > 0

        and

        train_loader.batch_size == DP_BATCH_SIZE

    )


    # --------------------------------------------------------------------------
    # Tensor Validation
    # --------------------------------------------------------------------------

    dtype_check = (

        train_tensor.dtype == torch.float32

    )


    finite_check = (

        torch.isfinite(train_tensor).all()

    )


    # --------------------------------------------------------------------------
    # Overall Status
    # --------------------------------------------------------------------------

    status = (

        tensor_shape_check

        and

        loader_check

        and

        dtype_check

        and

        finite_check

    )


    DP_DATA_VALIDATION[dataset] = status


    print()

    print(dataset)

    print(
        f"Expected Shape : ({expected_rows}, {expected_features})"
    )

    print(
        f"Actual Shape   : {tuple(train_tensor.shape)}"
    )

    print(
        f"Shape Check    : {'PASS' if tensor_shape_check else 'FAIL'}"
    )

    print(
        f"Loader Check   : {'PASS' if loader_check else 'FAIL'}"
    )

    print(
        f"Dtype Check    : {'PASS' if dtype_check else 'FAIL'}"
    )

    print(
        f"Finite Check   : {'PASS' if finite_check else 'FAIL'}"
    )

    print(
        f"Overall        : {'PASS' if status else 'FAIL'}"
    )


if not all(DP_DATA_VALIDATION.values()):

    raise RuntimeError(
        "DP training data validation failed."
    )


print()

print(
    "All DP training datasets validated successfully."
)

====================================================================================================
PART K5 — DP TRAINING DATA VALIDATION
====================================================================================================

Adult Income
Expected Shape : (22760, 15)
Actual Shape   : (22760, 15)
Shape Check    : PASS
Loader Check   : PASS
Dtype Check    : PASS
Finite Check   : PASS
Overall        : PASS

Bank Marketing
Expected Shape : (31647, 17)
Actual Shape   : (31647, 17)
Shape Check    : PASS
Loader Check   : PASS
Dtype Check    : PASS
Finite Check   : PASS
Overall        : PASS

diabetes_130us
Expected Shape : (71236, 48)
Actual Shape   : (71236, 48)
Shape Check    : PASS
Loader Check   : PASS
Dtype Check    : PASS
Finite Check   : PASS
Overall        : PASS

All DP training datasets validated successfully.

In [250]:
# ==============================================================================
# PART K6 — PRIVACY ENGINE INITIALIZATION
# ==============================================================================

print("=" * 100)
print("PART K6 — PRIVACY ENGINE INITIALIZATION")
print("=" * 100)


PRIVACY_ENGINES = {}


for dataset in DATASETS:

    privacy_engine = PrivacyEngine(
        accountant="rdp"
    )


    PRIVACY_ENGINES[dataset] = (
        privacy_engine
    )


    print()
    print(dataset)

    print(
        "PrivacyEngine initialized : PASS"
    )

    print(
        "Accountant               : RDP"
    )


print()

print(
    "PrivacyEngine objects created for all datasets."
)

====================================================================================================
PART K6 — PRIVACY ENGINE INITIALIZATION
====================================================================================================

Adult Income
PrivacyEngine initialized : PASS
Accountant               : RDP

Bank Marketing
PrivacyEngine initialized : PASS
Accountant               : RDP

diabetes_130us
PrivacyEngine initialized : PASS
Accountant               : RDP

PrivacyEngine objects created for all datasets.

In [251]:
# ==============================================================================
# PART K7 — PRE-PRIVATIZATION OPACUS VALIDATION
# ==============================================================================

print("=" * 100)
print("PART K7 — PRE-PRIVATIZATION OPACUS VALIDATION")
print("=" * 100)


PRE_DP_OPACUS_VALIDATION = {}


for dataset in DATASETS:


    discriminator = DISCRIMINATORS[dataset]


    discriminator.train()


    errors = ModuleValidator.validate(
        discriminator
    )


    passed = (
        len(errors) == 0
    )


    PRE_DP_OPACUS_VALIDATION[dataset] = passed


    print()

    print(dataset)


    print(
        f"Training Mode : "
        f"{'PASS' if discriminator.training else 'FAIL'}"
    )


    print(
        f"Opacus Check  : "
        f"{'PASS' if passed else 'FAIL'}"
    )


    if not passed:


        print()

        print(
            "Opacus Compatibility Errors:"
        )


        for error in errors:

            print(
                f"  - {error}"
            )



if not all(PRE_DP_OPACUS_VALIDATION.values()):


    raise RuntimeError(
        "One or more Discriminators failed "
        "pre-privacy Opacus validation. "
        "Fix model architecture before "
        "attaching PrivacyEngine."
    )


print()

print(
    "All Discriminators passed pre-privacy validation."
)

====================================================================================================
PART K7 — PRE-PRIVATIZATION OPACUS VALIDATION
====================================================================================================

Adult Income
Training Mode : PASS
Opacus Check  : PASS

Bank Marketing
Training Mode : PASS
Opacus Check  : PASS

diabetes_130us
Training Mode : PASS
Opacus Check  : PASS

All Discriminators passed pre-privacy validation.

In [252]:
# ==============================================================================
# PART K8 — PRIVACY ENGINE ATTACHMENT
# ==============================================================================

print("=" * 100)
print("PART K8 — PRIVACY ENGINE ATTACHMENT")
print("=" * 100)


import traceback

from opacus.accountants.utils import get_noise_multiplier


DP_PRIVATIZATION_RESULTS = {}

PRIVATE_DISCRIMINATORS = {}
PRIVATE_DISCRIMINATOR_OPTIMIZERS = {}
PRIVATE_TRAIN_LOADERS = {}

NOISE_MULTIPLIERS = {}

EPSILON_REPORT = {}


for dataset in DATASETS:

    print()
    print(dataset)


    discriminator = DISCRIMINATORS[dataset]

    discriminator_optimizer = (
        DISCRIMINATOR_OPTIMIZERS[dataset]
    )

    train_loader = (
        DP_TRAIN_DATALOADERS[dataset]
    )

    privacy_engine = (
        PRIVACY_ENGINES[dataset]
    )


    try:

        # ----------------------------------------------------------------------
        # Calculate Dataset-Specific Noise Multiplier
        # ----------------------------------------------------------------------

        sample_rate = (
            DP_BATCH_SIZE /
            len(train_loader.dataset)
        )


        noise_multiplier = get_noise_multiplier(

            target_epsilon=DP_PRIVACY_BUDGET,

            target_delta=DP_DELTA,

            sample_rate=sample_rate,

            epochs=DP_EPOCHS,

            accountant="rdp"

        )


        NOISE_MULTIPLIERS[dataset] = (
            noise_multiplier
        )


        print(
            f"Noise Multiplier       : {noise_multiplier}"
        )


        # ----------------------------------------------------------------------
        # Attach Privacy Engine
        # ----------------------------------------------------------------------

        (
            private_discriminator,

            private_optimizer,

            private_loader

        ) = privacy_engine.make_private(

            module=discriminator,

            optimizer=discriminator_optimizer,

            data_loader=train_loader,

            noise_multiplier=noise_multiplier,

            max_grad_norm=DP_MAX_GRAD_NORM,

            poisson_sampling=False

        )


        # ----------------------------------------------------------------------
        # Store Privatized Components
        # ----------------------------------------------------------------------

        PRIVATE_DISCRIMINATORS[dataset] = (
            private_discriminator
        )


        PRIVATE_DISCRIMINATOR_OPTIMIZERS[dataset] = (
            private_optimizer
        )


        PRIVATE_TRAIN_LOADERS[dataset] = (
            private_loader
        )


        # ----------------------------------------------------------------------
        # Privacy Accounting Verification
        # ----------------------------------------------------------------------

        epsilon_spent = (
            privacy_engine.get_epsilon(
                DP_DELTA
            )
        )


        EPSILON_REPORT[dataset] = (
            epsilon_spent
        )


        DP_PRIVATIZATION_RESULTS[dataset] = True


        print(
            "PrivacyEngine attached : PASS"
        )

        print(
            "Discriminator privatized: PASS"
        )

        print(
            "Optimizer privatized   : PASS"
        )

        print(
            "DataLoader privatized  : PASS"
        )

        print(
            f"Achieved Epsilon       : {epsilon_spent:.4f}"
        )


    except Exception as error:


        DP_PRIVATIZATION_RESULTS[dataset] = False


        print(
            "PrivacyEngine attached : FAIL"
        )


        print(
            f"Error Type             : {type(error).__name__}"
        )


        print(
            f"Error Message          : {error}"
        )


        print(
            "\nFULL TRACEBACK:"
        )


        traceback.print_exc()



print()

print("=" * 100)
print("DP PRIVATIZATION SUMMARY")
print("=" * 100)


for dataset, status in DP_PRIVATIZATION_RESULTS.items():

    print(
        f"{dataset:20s} : "
        f"{'PASS' if status else 'FAIL'}"
    )


if not all(DP_PRIVATIZATION_RESULTS.values()):

    raise RuntimeError(
        "One or more datasets failed PrivacyEngine attachment."
    )


print()

print(
    "All Discriminators successfully privatized."
)

====================================================================================================
PART K8 — PRIVACY ENGINE ATTACHMENT
====================================================================================================

Adult Income
Noise Multiplier       : 1.42333984375
PrivacyEngine attached : PASS
Discriminator privatized: PASS
Optimizer privatized   : PASS
DataLoader privatized  : PASS
Achieved Epsilon       : 0.0000

Bank Marketing
Noise Multiplier       : 1.2548828125
PrivacyEngine attached : PASS
Discriminator privatized: PASS
Optimizer privatized   : PASS
DataLoader privatized  : PASS
Achieved Epsilon       : 0.0000

diabetes_130us
Noise Multiplier       : 0.958251953125
PrivacyEngine attached : PASS
Discriminator privatized: PASS
Optimizer privatized   : PASS
DataLoader privatized  : PASS
Achieved Epsilon       : 0.0000

====================================================================================================
DP PRIVATIZATION SUMMARY
====================================================================================================
Adult Income         : PASS
Bank Marketing       : PASS
diabetes_130us       : PASS

All Discriminators successfully privatized.

In [253]:
# ==============================================================================
# PART K8 — PRIVACY ENGINE ATTACHMENT
# ==============================================================================

print("=" * 100)
print("PART K8 — PRIVACY ENGINE ATTACHMENT")
print("=" * 100)


from opacus.accountants.utils import get_noise_multiplier


DP_PRIVATIZATION_RESULTS = {}

PRIVATE_DISCRIMINATORS = {}
PRIVATE_DISCRIMINATOR_OPTIMIZERS = {}
PRIVATE_TRAIN_LOADERS = {}

NOISE_MULTIPLIERS = {}

EPSILON_REPORT = {}


for dataset in DATASETS:

    print()
    print(dataset)


    discriminator = DISCRIMINATORS[dataset]

    discriminator_optimizer = (
        DISCRIMINATOR_OPTIMIZERS[dataset]
    )

    train_loader = (
        DP_TRAIN_DATALOADERS[dataset]
    )

    privacy_engine = (
        PRIVACY_ENGINES[dataset]
    )


    try:


        # ----------------------------------------------------------------------
        # Calculate Dataset-Specific Noise Multiplier
        # ----------------------------------------------------------------------

        sample_rate = (
            DP_BATCH_SIZE /
            len(train_loader.dataset)
        )


        noise_multiplier = get_noise_multiplier(

            target_epsilon=DP_PRIVACY_BUDGET,

            target_delta=DP_DELTA,

            sample_rate=sample_rate,

            epochs=DP_EPOCHS,

            accountant="rdp"

        )


        NOISE_MULTIPLIERS[dataset] = (
            noise_multiplier
        )


        print(
            f"Noise Multiplier       : {noise_multiplier}"
        )


        # ----------------------------------------------------------------------
        # Attach Privacy Engine
        # ----------------------------------------------------------------------

        (
            private_discriminator,

            private_optimizer,

            private_loader

        ) = privacy_engine.make_private(

            module=discriminator,

            optimizer=discriminator_optimizer,

            data_loader=train_loader,

            noise_multiplier=noise_multiplier,

            max_grad_norm=DP_MAX_GRAD_NORM

        )


        # ----------------------------------------------------------------------
        # Store Privatized Components
        # ----------------------------------------------------------------------

        PRIVATE_DISCRIMINATORS[dataset] = (
            private_discriminator
        )


        PRIVATE_DISCRIMINATOR_OPTIMIZERS[dataset] = (
            private_optimizer
        )


        PRIVATE_TRAIN_LOADERS[dataset] = (
            private_loader
        )


        # ----------------------------------------------------------------------
        # Verify Privacy Budget
        # ----------------------------------------------------------------------

        epsilon_spent = (
            privacy_engine.get_epsilon(
                DP_DELTA
            )
        )


        EPSILON_REPORT[dataset] = (
            epsilon_spent
        )


        DP_PRIVATIZATION_RESULTS[dataset] = True


        print(
            "PrivacyEngine attached : PASS"
        )

        print(
            "Discriminator privatized: PASS"
        )

        print(
            "Optimizer privatized   : PASS"
        )

        print(
            "DataLoader privatized  : PASS"
        )

        print(
            f"Achieved Epsilon       : {epsilon_spent:.4f}"
        )


    except Exception as error:


        DP_PRIVATIZATION_RESULTS[dataset] = False


        print(
            "PrivacyEngine attached : FAIL"
        )

        print(
            f"Error Type             : {type(error).__name__}"
        )

        print(
            f"Error Message          : {error}"
        )



print()
print("=" * 100)
print("DP PRIVATIZATION SUMMARY")
print("=" * 100)


for dataset, status in DP_PRIVATIZATION_RESULTS.items():

    print(
        f"{dataset:20s} : "
        f"{'PASS' if status else 'FAIL'}"
    )


if not all(DP_PRIVATIZATION_RESULTS.values()):

    raise RuntimeError(
        "One or more datasets failed PrivacyEngine attachment."
    )


print()

print(
    "All Discriminators successfully privatized."
)

====================================================================================================
PART K8 — PRIVACY ENGINE ATTACHMENT
====================================================================================================

Adult Income

WARNING:opacus.data_loader:Ignoring drop_last as it is not compatible with DPDataLoader.

Noise Multiplier       : 1.42333984375
PrivacyEngine attached : PASS
Discriminator privatized: PASS
Optimizer privatized   : PASS
DataLoader privatized  : PASS
Achieved Epsilon       : 0.0000

Bank Marketing

WARNING:opacus.data_loader:Ignoring drop_last as it is not compatible with DPDataLoader.

Noise Multiplier       : 1.2548828125
PrivacyEngine attached : PASS
Discriminator privatized: PASS
Optimizer privatized   : PASS
DataLoader privatized  : PASS
Achieved Epsilon       : 0.0000

diabetes_130us

WARNING:opacus.data_loader:Ignoring drop_last as it is not compatible with DPDataLoader.

Noise Multiplier       : 0.958251953125
PrivacyEngine attached : PASS
Discriminator privatized: PASS
Optimizer privatized   : PASS
DataLoader privatized  : PASS
Achieved Epsilon       : 0.0000

====================================================================================================
DP PRIVATIZATION SUMMARY
====================================================================================================
Adult Income         : PASS
Bank Marketing       : PASS
diabetes_130us       : PASS

All Discriminators successfully privatized.

In [254]:
# ==============================================================================
# PART K9 — PRIVATIZED MODEL TYPE VALIDATION
# ==============================================================================

print("=" * 100)
print("PART K9 — PRIVATIZED MODEL TYPE VALIDATION")
print("=" * 100)


PRIVATIZED_MODEL_VALIDATION = {}


for dataset in DATASETS:

    print()
    print(dataset)


    # --------------------------------------------------------------------------
    # Check Privatized Objects Exist
    # --------------------------------------------------------------------------

    if dataset not in PRIVATE_DISCRIMINATORS:


        PRIVATIZED_MODEL_VALIDATION[dataset] = False


        print(
            "Privatized Model     : FAIL"
        )

        print(
            "Reason               : "
            "Private discriminator not found"
        )

        continue



    discriminator = (
        PRIVATE_DISCRIMINATORS[dataset]
    )


    optimizer = (
        PRIVATE_DISCRIMINATOR_OPTIMIZERS[dataset]
    )


    data_loader = (
        PRIVATE_TRAIN_LOADERS[dataset]
    )


    # --------------------------------------------------------------------------
    # Validation Checks
    # --------------------------------------------------------------------------

    model_check = (
        discriminator is not None
    )


    optimizer_check = (
        optimizer is not None
    )


    loader_check = (
        data_loader is not None
    )


    # Opacus wraps models using GradSampleModule
    opacus_check = (
        "GradSampleModule"
        in
        discriminator.__class__.__name__
    )


    training_mode_check = (
        discriminator.training
    )


    status = (

        model_check

        and

        optimizer_check

        and

        loader_check

        and

        opacus_check

        and

        training_mode_check

    )


    PRIVATIZED_MODEL_VALIDATION[dataset] = status



    print(
        f"Discriminator Object : "
        f"{'PASS' if model_check else 'FAIL'}"
    )


    print(
        f"Optimizer Object     : "
        f"{'PASS' if optimizer_check else 'FAIL'}"
    )


    print(
        f"DataLoader Object    : "
        f"{'PASS' if loader_check else 'FAIL'}"
    )


    print(
        f"Opacus Wrapper       : "
        f"{'PASS' if opacus_check else 'FAIL'}"
    )


    print(
        f"Training Mode        : "
        f"{'PASS' if training_mode_check else 'FAIL'}"
    )


    print(
        f"Overall              : "
        f"{'PASS' if status else 'FAIL'}"
    )



print()

print("=" * 100)

print("PRIVATIZED MODEL VALIDATION SUMMARY")

print("=" * 100)



for dataset, status in PRIVATIZED_MODEL_VALIDATION.items():

    print(
        f"{dataset:20s} : "
        f"{'PASS' if status else 'FAIL'}"
    )


print("=" * 100)



if not all(PRIVATIZED_MODEL_VALIDATION.values()):

    raise RuntimeError(
        "Privatized model validation failed."
    )


print()

print(
    "All privatized models validated successfully."
)

====================================================================================================
PART K9 — PRIVATIZED MODEL TYPE VALIDATION
====================================================================================================

Adult Income
Discriminator Object : PASS
Optimizer Object     : PASS
DataLoader Object    : PASS
Opacus Wrapper       : PASS
Training Mode        : PASS
Overall              : PASS

Bank Marketing
Discriminator Object : PASS
Optimizer Object     : PASS
DataLoader Object    : PASS
Opacus Wrapper       : PASS
Training Mode        : PASS
Overall              : PASS

diabetes_130us
Discriminator Object : PASS
Optimizer Object     : PASS
DataLoader Object    : PASS
Opacus Wrapper       : PASS
Training Mode        : PASS
Overall              : PASS

====================================================================================================
PRIVATIZED MODEL VALIDATION SUMMARY
====================================================================================================
Adult Income         : PASS
Bank Marketing       : PASS
diabetes_130us       : PASS
====================================================================================================

All privatized models validated successfully.

In [269]:
# ==============================================================================
# PART K10 — PRIVACY ACCOUNTING VALIDATION
# ==============================================================================

print("=" * 100)
print("PART K10 — PRIVACY ACCOUNTING VALIDATION")
print("=" * 100)


PRIVACY_ACCOUNTING_RESULTS = {}

ACCOUNTANT_TYPES = {}


for dataset in DATASETS:


    print()
    print(dataset)


    try:


        privacy_engine = (
            PRIVACY_ENGINES[dataset]
        )


        accountant = (
            privacy_engine.accountant
        )


        accountant_name = type(
            accountant
        ).__name__


        ACCOUNTANT_TYPES[dataset] = (
            accountant_name
        )


        print(
            f"Accountant Type     : {accountant_name}"
        )


        print(
            f"Target Epsilon      : {DP_PRIVACY_BUDGET}"
        )


        print(
            f"Target Delta        : {DP_DELTA}"
        )


        print(
            f"Max Grad Norm       : {DP_MAX_GRAD_NORM}"
        )


        print(
            f"Epochs              : {DP_EPOCHS}"
        )


        # ----------------------------------------------------------------------
        # Verify RDP Accountant
        # ----------------------------------------------------------------------

        accountant_check = (

            "RDP"

            in

            accountant_name.upper()

        )


        engine_check = (
            privacy_engine is not None
        )


        status = (
            accountant_check
            and
            engine_check
        )


        PRIVACY_ACCOUNTING_RESULTS[dataset] = status



        print(
            "Privacy Engine      : "
            f"{'PASS' if engine_check else 'FAIL'}"
        )


        print(
            "RDP Accountant      : "
            f"{'PASS' if accountant_check else 'FAIL'}"
        )


        print(
            "Accounting Status   : "
            f"{'READY' if status else 'FAIL'}"
        )



    except Exception as error:


        PRIVACY_ACCOUNTING_RESULTS[dataset] = False


        print(
            "Privacy accountant validation error:"
        )


        print(
            error
        )



print()

print("=" * 100)

print("PRIVACY ACCOUNTING SUMMARY")

print("=" * 100)



for dataset, status in PRIVACY_ACCOUNTING_RESULTS.items():

    print(
        f"{dataset:20s} : "
        f"{'PASS' if status else 'FAIL'}"
    )


print("=" * 100)



if not all(PRIVACY_ACCOUNTING_RESULTS.values()):

    raise RuntimeError(
        "Privacy accountant initialization failed."
    )


print()

print(
    "Privacy accounting infrastructure validated successfully."
)


print(
    "Epsilon calculation will be performed after DP training steps."
)

====================================================================================================
PART K10 — PRIVACY ACCOUNTING VALIDATION
====================================================================================================

Adult Income
Accountant Type     : RDPAccountant
Target Epsilon      : 4.0
Target Delta        : 1e-05
Max Grad Norm       : 1.0
Epochs              : 100
Privacy Engine      : PASS
RDP Accountant      : PASS
Accounting Status   : READY

Bank Marketing
Accountant Type     : RDPAccountant
Target Epsilon      : 4.0
Target Delta        : 1e-05
Max Grad Norm       : 1.0
Epochs              : 100
Privacy Engine      : PASS
RDP Accountant      : PASS
Accounting Status   : READY

diabetes_130us
Accountant Type     : RDPAccountant
Target Epsilon      : 4.0
Target Delta        : 1e-05
Max Grad Norm       : 1.0
Epochs              : 100
Privacy Engine      : PASS
RDP Accountant      : PASS
Accounting Status   : READY

====================================================================================================
PRIVACY ACCOUNTING SUMMARY
====================================================================================================
Adult Income         : PASS
Bank Marketing       : PASS
diabetes_130us       : PASS
====================================================================================================

Privacy accounting infrastructure validated successfully.
Epsilon calculation will be performed after DP training steps.

In [270]:
# ==============================================================================
# PART K11 — PRIVATIZED DATALOADER VALIDATION
# ==============================================================================

print("=" * 100)
print("PART K11 — PRIVATIZED DATALOADER VALIDATION")
print("=" * 100)


PRIVATIZED_DATALOADER_VALIDATION = {}


for dataset in DATASETS:


    print()
    print(dataset)


    try:


        # ----------------------------------------------------------------------
        # Use Opacus Privatized DataLoader
        # ----------------------------------------------------------------------

        data_loader = (
            PRIVATE_TRAIN_LOADERS[dataset]
        )


        first_batch = next(
            iter(data_loader)
        )


        batch_data = first_batch[0]


        expected_features = (
            TRAIN_DATASETS[dataset].shape[1]
        )


        actual_features = (
            batch_data.shape[1]
        )


        batch_check = (

            actual_features

            ==

            expected_features

        )


        loader_object_check = (
            data_loader is not None
        )


        batch_exists_check = (
            batch_data is not None
        )


        status = (

            loader_object_check

            and

            batch_exists_check

            and

            batch_check

        )


        PRIVATIZED_DATALOADER_VALIDATION[dataset] = (
            status
        )



        print(
            f"DataLoader Object : "
            f"{'PASS' if loader_object_check else 'FAIL'}"
        )


        print(
            f"Batch Available   : "
            f"{'PASS' if batch_exists_check else 'FAIL'}"
        )


        print(
            f"Batch Shape       : "
            f"{tuple(batch_data.shape)}"
        )


        print(
            f"Expected Features : "
            f"{expected_features}"
        )


        print(
            f"Actual Features   : "
            f"{actual_features}"
        )


        print(
            f"Feature Check     : "
            f"{'PASS' if batch_check else 'FAIL'}"
        )


        print(
            f"Overall           : "
            f"{'PASS' if status else 'FAIL'}"
        )



    except Exception as error:


        PRIVATIZED_DATALOADER_VALIDATION[dataset] = False


        print(
            "DataLoader validation error:"
        )


        print(
            error
        )



print()

print("=" * 100)

print("PRIVATIZED DATALOADER SUMMARY")

print("=" * 100)



for dataset, status in PRIVATIZED_DATALOADER_VALIDATION.items():

    print(
        f"{dataset:20s} : "
        f"{'PASS' if status else 'FAIL'}"
    )


print("=" * 100)



if not all(PRIVATIZED_DATALOADER_VALIDATION.values()):

    raise RuntimeError(
        "Privatized DataLoader validation failed."
    )


print()

print(
    "All privatized DataLoaders validated successfully."
)

====================================================================================================
PART K11 — PRIVATIZED DATALOADER VALIDATION
====================================================================================================

Adult Income
DataLoader Object : PASS
Batch Available   : PASS
Batch Shape       : (254, 15)
Expected Features : 15
Actual Features   : 15
Feature Check     : PASS
Overall           : PASS

Bank Marketing
DataLoader Object : PASS
Batch Available   : PASS
Batch Shape       : (239, 17)
Expected Features : 17
Actual Features   : 17
Feature Check     : PASS
Overall           : PASS

diabetes_130us
DataLoader Object : PASS
Batch Available   : PASS
Batch Shape       : (273, 48)
Expected Features : 48
Actual Features   : 48
Feature Check     : PASS
Overall           : PASS

====================================================================================================
PRIVATIZED DATALOADER SUMMARY
====================================================================================================
Adult Income         : PASS
Bank Marketing       : PASS
diabetes_130us       : PASS
====================================================================================================

All privatized DataLoaders validated successfully.

In [271]:
# ==============================================================================
# PART K12 — PRIVATIZED DISCRIMINATOR DIMENSION VALIDATION
# ==============================================================================

print("=" * 100)
print("PART K12 — PRIVATIZED DISCRIMINATOR DIMENSION VALIDATION")
print("=" * 100)


POST_DP_DIMENSION_VALIDATION = {}


VALIDATION_BATCH_SIZE = 4


for dataset in DATASETS:


    print()
    print(dataset)


    try:


        # ----------------------------------------------------------------------
        # Use Opacus Privatized Discriminator
        # ----------------------------------------------------------------------

        discriminator = (
            PRIVATE_DISCRIMINATORS[dataset]
        )


        expected_features = (
            TRAIN_DATASETS[dataset].shape[1]
        )


        test_data = torch.randn(

            VALIDATION_BATCH_SIZE,

            expected_features,

            device=DEVICE

        )


        discriminator.train()


        output = discriminator(
            test_data
        )


        expected_output_shape = (

            VALIDATION_BATCH_SIZE,

            1

        )


        actual_output_shape = (
            tuple(output.shape)
        )


        input_dimension_check = (

            test_data.shape[1]

            ==

            expected_features

        )


        output_dimension_check = (

            actual_output_shape

            ==

            expected_output_shape

        )


        status = (

            input_dimension_check

            and

            output_dimension_check

        )


        POST_DP_DIMENSION_VALIDATION[dataset] = (
            status
        )



        print(
            f"Input Shape       : "
            f"{tuple(test_data.shape)}"
        )


        print(
            f"Output Shape      : "
            f"{actual_output_shape}"
        )


        print(
            f"Input Dimension   : "
            f"{'PASS' if input_dimension_check else 'FAIL'}"
        )


        print(
            f"Output Dimension  : "
            f"{'PASS' if output_dimension_check else 'FAIL'}"
        )


        print(
            f"Overall           : "
            f"{'PASS' if status else 'FAIL'}"
        )



    except Exception as error:


        POST_DP_DIMENSION_VALIDATION[dataset] = False


        print(
            "Dimension validation error:"
        )


        print(
            error
        )



print()

print("=" * 100)

print("PRIVATIZED DISCRIMINATOR DIMENSION SUMMARY")

print("=" * 100)



for dataset, status in POST_DP_DIMENSION_VALIDATION.items():

    print(
        f"{dataset:20s} : "
        f"{'PASS' if status else 'FAIL'}"
    )


print("=" * 100)



if not all(POST_DP_DIMENSION_VALIDATION.values()):

    raise RuntimeError(
        "Privatized Discriminator dimension validation failed."
    )


print()

print(
    "All privatized Discriminator dimensions validated successfully."
)

====================================================================================================
PART K12 — PRIVATIZED DISCRIMINATOR DIMENSION VALIDATION
====================================================================================================

Adult Income
Input Shape       : (4, 15)
Output Shape      : (4, 1)
Input Dimension   : PASS
Output Dimension  : PASS
Overall           : PASS

Bank Marketing
Input Shape       : (4, 17)
Output Shape      : (4, 1)
Input Dimension   : PASS
Output Dimension  : PASS
Overall           : PASS

diabetes_130us
Input Shape       : (4, 48)
Output Shape      : (4, 1)
Input Dimension   : PASS
Output Dimension  : PASS
Overall           : PASS

====================================================================================================
PRIVATIZED DISCRIMINATOR DIMENSION SUMMARY
====================================================================================================
Adult Income         : PASS
Bank Marketing       : PASS
diabetes_130us       : PASS
====================================================================================================

All privatized Discriminator dimensions validated successfully.

In [272]:
# ==============================================================================
# PART K13 — PRIVACY ENGINE STATUS SUMMARY
# ==============================================================================

print("=" * 100)
print("PART K13 — PRIVACY ENGINE STATUS SUMMARY")
print("=" * 100)


PRIVACY_ENGINE_STATUS = {}


for dataset in DATASETS:


    attachment_check = (
        DP_PRIVATIZATION_RESULTS.get(
            dataset,
            False
        )
    )


    model_check = (
        PRIVATIZED_MODEL_VALIDATION.get(
            dataset,
            False
        )
    )


    accounting_check = (
        PRIVACY_ACCOUNTING_RESULTS.get(
            dataset,
            False
        )
    )


    loader_check = (
        PRIVATIZED_DATALOADER_VALIDATION.get(
            dataset,
            False
        )
    )


    dimension_check = (
        POST_DP_DIMENSION_VALIDATION.get(
            dataset,
            False
        )
    )


    overall_status = (

        attachment_check

        and

        model_check

        and

        accounting_check

        and

        loader_check

        and

        dimension_check

    )


    PRIVACY_ENGINE_STATUS[dataset] = {

        "PrivacyEngine": attachment_check,

        "Model": model_check,

        "PrivacyAccounting": accounting_check,

        "DataLoader": loader_check,

        "Dimensions": dimension_check,

        "Overall": overall_status

    }


    print()

    print(dataset)


    print(
        f"PrivacyEngine Attachment : "
        f"{'PASS' if attachment_check else 'FAIL'}"
    )


    print(
        f"Privatized Model         : "
        f"{'PASS' if model_check else 'FAIL'}"
    )


    print(
        f"Privacy Accounting       : "
        f"{'PASS' if accounting_check else 'FAIL'}"
    )


    print(
        f"Privatized DataLoader    : "
        f"{'PASS' if loader_check else 'FAIL'}"
    )


    print(
        f"Dimension Validation     : "
        f"{'PASS' if dimension_check else 'FAIL'}"
    )


    print(
        f"Overall                  : "
        f"{'PASS' if overall_status else 'FAIL'}"
    )



print()

print("=" * 100)

print("FINAL PRIVACY ENGINE SUMMARY")

print("=" * 100)


for dataset, result in PRIVACY_ENGINE_STATUS.items():

    print()

    print(dataset)

    for key, value in result.items():

        print(
            f"{key:25s}: "
            f"{'PASS' if value else 'FAIL'}"
        )


print("=" * 100)



if not all(
    result["Overall"]
    for result in PRIVACY_ENGINE_STATUS.values()
):

    raise RuntimeError(
        "Privacy Engine configuration failed "
        "for one or more datasets."
    )


print()

print(
    "Privacy Engine configuration validated successfully."
)

====================================================================================================
PART K13 — PRIVACY ENGINE STATUS SUMMARY
====================================================================================================

Adult Income
PrivacyEngine Attachment : PASS
Privatized Model         : PASS
Privacy Accounting       : PASS
Privatized DataLoader    : PASS
Dimension Validation     : PASS
Overall                  : PASS

Bank Marketing
PrivacyEngine Attachment : PASS
Privatized Model         : PASS
Privacy Accounting       : PASS
Privatized DataLoader    : PASS
Dimension Validation     : PASS
Overall                  : PASS

diabetes_130us
PrivacyEngine Attachment : PASS
Privatized Model         : PASS
Privacy Accounting       : PASS
Privatized DataLoader    : PASS
Dimension Validation     : PASS
Overall                  : PASS

====================================================================================================
FINAL PRIVACY ENGINE SUMMARY
====================================================================================================

Adult Income
PrivacyEngine            : PASS
Model                    : PASS
PrivacyAccounting        : PASS
DataLoader               : PASS
Dimensions               : PASS
Overall                  : PASS

Bank Marketing
PrivacyEngine            : PASS
Model                    : PASS
PrivacyAccounting        : PASS
DataLoader               : PASS
Dimensions               : PASS
Overall                  : PASS

diabetes_130us
PrivacyEngine            : PASS
Model                    : PASS
PrivacyAccounting        : PASS
DataLoader               : PASS
Dimensions               : PASS
Overall                  : PASS
====================================================================================================

Privacy Engine configuration validated successfully.

In [273]:
# ==============================================================================
# PART K14 — FINAL PRIVACY CONFIGURATION RECORD
# ==============================================================================

print("=" * 100)
print("PART K14 — FINAL PRIVACY CONFIGURATION RECORD")
print("=" * 100)


DP_CONFIGURATION = {


    # --------------------------------------------------------------------------
    # Privacy Configuration
    # --------------------------------------------------------------------------

    "Privacy Mechanism":
        "Opacus Differential Privacy",


    "Privacy Accountant":
        "RDP Accountant",


    "Privacy Budget Epsilon":
        DP_PRIVACY_BUDGET,


    "Privacy Delta":
        DP_DELTA,


    "Maximum Gradient Norm":
        DP_MAX_GRAD_NORM,


    "Noise Multipliers":
        NOISE_MULTIPLIERS,



    # --------------------------------------------------------------------------
    # Training Configuration
    # --------------------------------------------------------------------------

    "Batch Size":
        DP_BATCH_SIZE,


    "Epochs":
        DP_EPOCHS,


    "Optimizer":
        OPTIMIZER_NAME
        if "OPTIMIZER_NAME" in globals()
        else "Adam",


    "Learning Rate":
        OPTIMIZER_LEARNING_RATE
        if "OPTIMIZER_LEARNING_RATE" in globals()
        else None,


    "Beta1":
        OPTIMIZER_BETA1
        if "OPTIMIZER_BETA1" in globals()
        else None,


    "Beta2":
        OPTIMIZER_BETA2
        if "OPTIMIZER_BETA2" in globals()
        else None,



    # --------------------------------------------------------------------------
    # DP Component Information
    # --------------------------------------------------------------------------

    "Privatized Component":
        "Discriminator",


    "Datasets":
        DATASETS,



    # --------------------------------------------------------------------------
    # Software Environment
    # --------------------------------------------------------------------------

    "PyTorch Version":
        torch.__version__,


    "Opacus Version":
        opacus.__version__,



    # --------------------------------------------------------------------------
    # Validation Status
    # --------------------------------------------------------------------------

    "Privacy Pipeline Status":
        "PASS"
        if all(
            result["Overall"]
            for result in PRIVACY_ENGINE_STATUS.values()
        )
        else "FAIL"

}



for key, value in DP_CONFIGURATION.items():

    print(
        f"{key:30s}: {value}"
    )


print()

print(
    "Final privacy configuration record created successfully."
)

====================================================================================================
PART K14 — FINAL PRIVACY CONFIGURATION RECORD
====================================================================================================
Privacy Mechanism             : Opacus Differential Privacy
Privacy Accountant            : RDP Accountant
Privacy Budget Epsilon        : 4.0
Privacy Delta                 : 1e-05
Maximum Gradient Norm         : 1.0
Noise Multipliers             : {'Adult Income': 1.42333984375, 'Bank Marketing': 1.2548828125, 'diabetes_130us': 0.958251953125}
Batch Size                    : 256
Epochs                        : 100
Optimizer                     : Adam
Learning Rate                 : 0.0002
Beta1                         : 0.5
Beta2                         : 0.999
Privatized Component          : Discriminator
Datasets                      : ['Adult Income', 'Bank Marketing', 'diabetes_130us']
PyTorch Version               : 2.11.0+cpu
Opacus Version                : 1.6.0
Privacy Pipeline Status       : PASS

Final privacy configuration record created successfully.

In [274]:
# ==============================================================================
# PART K15 — FINAL PART K VERIFICATION
# ==============================================================================

print("=" * 100)
print("PART K15 — FINAL PART K VERIFICATION")
print("=" * 100)


FINAL_PRIVACY_VERIFICATION = {}


for dataset in DATASETS:


    dataset_status = (
        PRIVACY_ENGINE_STATUS.get(
            dataset,
            {}
        )
    )


    status = (
        dataset_status.get(
            "Overall",
            False
        )
    )


    FINAL_PRIVACY_VERIFICATION[dataset] = (
        status
    )


    print()

    print(dataset)


    print(
        f"PrivacyEngine Attachment : "
        f"{'PASS' if dataset_status.get('PrivacyEngine', False) else 'FAIL'}"
    )


    print(
        f"Privatized Model         : "
        f"{'PASS' if dataset_status.get('Model', False) else 'FAIL'}"
    )


    print(
        f"Privacy Accounting       : "
        f"{'PASS' if dataset_status.get('PrivacyAccounting', False) else 'FAIL'}"
    )


    print(
        f"Privatized DataLoader    : "
        f"{'PASS' if dataset_status.get('DataLoader', False) else 'FAIL'}"
    )


    print(
        f"Dimension Validation     : "
        f"{'PASS' if dataset_status.get('Dimensions', False) else 'FAIL'}"
    )


    print(
        f"Overall                  : "
        f"{'PASS' if status else 'FAIL'}"
    )



print()

print("=" * 100)

print("FINAL PRIVACY VERIFICATION SUMMARY")

print("=" * 100)



for dataset, status in FINAL_PRIVACY_VERIFICATION.items():

    print(
        f"{dataset:20s} : "
        f"{'PASS' if status else 'FAIL'}"
    )



print("=" * 100)



if not all(
    FINAL_PRIVACY_VERIFICATION.values()
):

    raise RuntimeError(
        "PART K failed. "
        "Do not proceed to PART L."
    )


print()

print("=" * 100)

print("PART K COMPLETED SUCCESSFULLY")

print(
    "Differential Privacy Engine validated successfully."
)

print(
    "Privatized Discriminators are ready for DP training."
)

print("=" * 100)

====================================================================================================
PART K15 — FINAL PART K VERIFICATION
====================================================================================================

Adult Income
PrivacyEngine Attachment : PASS
Privatized Model         : PASS
Privacy Accounting       : PASS
Privatized DataLoader    : PASS
Dimension Validation     : PASS
Overall                  : PASS

Bank Marketing
PrivacyEngine Attachment : PASS
Privatized Model         : PASS
Privacy Accounting       : PASS
Privatized DataLoader    : PASS
Dimension Validation     : PASS
Overall                  : PASS

diabetes_130us
PrivacyEngine Attachment : PASS
Privatized Model         : PASS
Privacy Accounting       : PASS
Privatized DataLoader    : PASS
Dimension Validation     : PASS
Overall                  : PASS

====================================================================================================
FINAL PRIVACY VERIFICATION SUMMARY
====================================================================================================
Adult Income         : PASS
Bank Marketing       : PASS
diabetes_130us       : PASS
====================================================================================================

====================================================================================================
PART K COMPLETED SUCCESSFULLY
Differential Privacy Engine validated successfully.
Privatized Discriminators are ready for DP training.
====================================================================================================

In [275]:
# ==============================================================================
# PART L1 — DP TRAINING CONFIGURATION
# ==============================================================================

print("=" * 100)
print("PART L1 — DP TRAINING CONFIGURATION")
print("=" * 100)


DP_CTGAN_EPOCHS = DP_EPOCHS

LATENT_DIMENSION = 128

GENERATOR_LEARNING_RATE = 0.0002

DISCRIMINATOR_LEARNING_RATE = 0.0002


print(
    f"Training Epochs       : {DP_CTGAN_EPOCHS}"
)

print(
    f"Latent Dimension      : {LATENT_DIMENSION}"
)

print(
    f"Generator LR          : {GENERATOR_LEARNING_RATE}"
)

print(
    f"Discriminator LR      : {DISCRIMINATOR_LEARNING_RATE}"
)

print()

print(
    "DP-CTGAN training configuration initialized."
)

====================================================================================================
PART L1 — DP TRAINING CONFIGURATION
====================================================================================================
Training Epochs       : 100
Latent Dimension      : 128
Generator LR          : 0.0002
Discriminator LR      : 0.0002

DP-CTGAN training configuration initialized.

In [277]:
# ==============================================================================
# PART L2.1 — GENERATOR ARCHITECTURE DEFINITION
# ==============================================================================

print("=" * 100)
print("PART L2.1 — GENERATOR ARCHITECTURE DEFINITION")
print("=" * 100)


import torch
import torch.nn as nn


class Generator(nn.Module):

    def __init__(
        self,
        latent_dim,
        output_dim
    ):

        super().__init__()


        self.network = nn.Sequential(

            nn.Linear(
                latent_dim,
                256
            ),

            nn.LayerNorm(
                256
            ),

            nn.LeakyReLU(
                0.2
            ),


            nn.Linear(
                256,
                512
            ),

            nn.LayerNorm(
                512
            ),

            nn.LeakyReLU(
                0.2
            ),


            nn.Linear(
                512,
                256
            ),

            nn.LayerNorm(
                256
            ),

            nn.LeakyReLU(
                0.2
            ),


            nn.Linear(
                256,
                output_dim
            )

        )


    def forward(
        self,
        x
    ):

        return self.network(x)



print(
    "Generator architecture created successfully."
)

====================================================================================================
PART L2.1 — GENERATOR ARCHITECTURE DEFINITION
====================================================================================================
Generator architecture created successfully.

In [278]:
# ==============================================================================
# PART L2 — GENERATOR PREPARATION
# ==============================================================================

print("=" * 100)
print("PART L2 — GENERATOR PREPARATION")
print("=" * 100)


GENERATORS = {}

GENERATOR_OPTIMIZERS = {}


for dataset in DATASETS:


    input_dimension = (
        TRAIN_DATASETS[dataset].shape[1]
    )


    generator = Generator(
        latent_dim=LATENT_DIMENSION,
        output_dim=input_dimension
    ).to(DEVICE)


    generator_optimizer = torch.optim.Adam(

        generator.parameters(),

        lr=GENERATOR_LEARNING_RATE,

        betas=(
            OPTIMIZER_BETA1,
            OPTIMIZER_BETA2
        )

    )


    GENERATORS[dataset] = generator

    GENERATOR_OPTIMIZERS[dataset] = (
        generator_optimizer
    )


    print()

    print(dataset)

    print(
        f"Generator Output Dimension : {input_dimension}"
    )

    print(
        "Generator initialized : PASS"
    )

====================================================================================================
PART L2 — GENERATOR PREPARATION
====================================================================================================

Adult Income
Generator Output Dimension : 15
Generator initialized : PASS

Bank Marketing
Generator Output Dimension : 17
Generator initialized : PASS

diabetes_130us
Generator Output Dimension : 48
Generator initialized : PASS

In [279]:
# ==============================================================================
# PART L3 — DP TRAINING STATE INITIALIZATION
# ==============================================================================

print("=" * 100)
print("PART L3 — DP TRAINING STATE INITIALIZATION")
print("=" * 100)


DP_TRAINING_HISTORY = {}

FINAL_EPSILON_REPORT = {}


for dataset in DATASETS:


    DP_TRAINING_HISTORY[dataset] = {

        "Generator Loss": [],

        "Discriminator Loss": []

    }


    FINAL_EPSILON_REPORT[dataset] = None


print(
    "DP training state initialized."
)

====================================================================================================
PART L3 — DP TRAINING STATE INITIALIZATION
====================================================================================================
DP training state initialized.

In [283]:
# ==============================================================================
# PART L4 — GENERATOR LOSS FUNCTION
# ==============================================================================

print("=" * 100)
print("PART L4 — GENERATOR LOSS FUNCTION")
print("=" * 100)


generator_loss_function = torch.nn.BCEWithLogitsLoss()


print(
    "Generator loss : BCEWithLogitsLoss"
)

====================================================================================================
PART L4 — GENERATOR LOSS FUNCTION
====================================================================================================
Generator loss : BCEWithLogitsLoss

In [284]:
# ==============================================================================
# PART L5 — DISCRIMINATOR LOSS FUNCTION
# ==============================================================================

print("=" * 100)
print("PART L5 — DISCRIMINATOR LOSS FUNCTION")
# ==============================================================================


discriminator_loss_function = torch.nn.BCEWithLogitsLoss()


print(
    "Discriminator loss : BCEWithLogitsLoss"
)

====================================================================================================
PART L5 — DISCRIMINATOR LOSS FUNCTION
Discriminator loss : BCEWithLogitsLoss

In [288]:
# ==============================================================================
# PART L5.1 — OPACUS GRADIENT SAMPLING DIAGNOSTIC
# ==============================================================================

print("=" * 100)
print("PART L5.1 — OPACUS GRADIENT SAMPLING DIAGNOSTIC")
print("=" * 100)


for dataset in DATASETS:

    print()
    print(dataset)


    discriminator = (
        PRIVATE_DISCRIMINATORS[dataset]
    )


    optimizer = (
        PRIVATE_DISCRIMINATOR_OPTIMIZERS[dataset]
    )


    loader = (
        PRIVATE_TRAIN_LOADERS[dataset]
    )


    discriminator.train()


    # --------------------------------------------------------------------------
    # Enable hooks on the actual Opacus GradSampleModule instance
    # --------------------------------------------------------------------------

    discriminator.enable_hooks()


    optimizer.zero_grad()


    batch = next(
        iter(loader)
    )


    real_data = (
        batch[0]
        .to(DEVICE)
        .float()
    )


    output = discriminator(
        real_data
    )


    if output.ndim == 1:

        output = output.reshape(
            -1,
            1
        )


    labels = torch.ones(
        output.shape[0],
        1,
        device=DEVICE
    )


    test_loss = (
        discriminator_loss_function(
            output,
            labels
        )
    )


    test_loss.backward()


    missing = []


    for name, parameter in (
        discriminator.named_parameters()
    ):

        if (
            parameter.requires_grad
            and
            parameter.grad_sample is None
        ):

            missing.append(name)


    if len(missing) == 0:

        print(
            "Per-sample gradients : PASS"
        )

        print(
            "Opacus gradient hooks : PASS"
        )

    else:

        print(
            "Per-sample gradients : FAIL"
        )

        print(
            "Missing Parameters:"
        )

        for name in missing:

            print(
                f"  {name}"
            )


    optimizer.zero_grad()


print()

print("=" * 100)
print("OPACUS GRADIENT SAMPLING DIAGNOSTIC COMPLETED")
print("=" * 100)

====================================================================================================
PART L5.1 — OPACUS GRADIENT SAMPLING DIAGNOSTIC
====================================================================================================

Adult Income

RuntimeError: The size of tensor a (251) must match the size of tensor b (268) at non-singleton dimension 0

In [286]:
# ==============================================================================
# PART L6 — DP-CTGAN TRAINING LOOP
# ==============================================================================

print("=" * 100)
print("PART L6 — DP-CTGAN TRAINING LOOP")
print("=" * 100)


DP_TRAINING_COMPLETED = {}

DP_TRAINING_ERRORS = {}


for dataset in DATASETS:

    print()
    print("=" * 80)
    print(dataset)
    print("=" * 80)


    generator = (
        GENERATORS[dataset]
    )


    generator_optimizer = (
        GENERATOR_OPTIMIZERS[dataset]
    )


    discriminator = (
        PRIVATE_DISCRIMINATORS[dataset]
    )


    discriminator_optimizer = (
        PRIVATE_DISCRIMINATOR_OPTIMIZERS[dataset]
    )


    train_loader = (
        PRIVATE_TRAIN_LOADERS[dataset]
    )


    generator.train()
    discriminator.train()


    # --------------------------------------------------------------------------
    # Ensure all discriminator parameters require gradients
    # --------------------------------------------------------------------------

    for parameter in discriminator.parameters():

        parameter.requires_grad_(True)


    dataset_completed = True


    try:

        for epoch in range(
            DP_CTGAN_EPOCHS
        ):


            epoch_g_loss = 0.0
            epoch_d_loss = 0.0


            batch_count = 0


            for batch in train_loader:


                real_data = (
                    batch[0]
                    .to(DEVICE)
                    .float()
                )


                batch_size = (
                    real_data.size(0)
                )


                # ==================================================================
                # DISCRIMINATOR UPDATE
                # ==================================================================

                for parameter in discriminator.parameters():

                    parameter.requires_grad_(True)


                discriminator_optimizer.zero_grad()


                noise = torch.randn(

                    batch_size,

                    LATENT_DIMENSION,

                    device=DEVICE

                )


                fake_data = generator(
                    noise
                ).detach()


                real_labels = torch.ones(

                    batch_size,

                    1,

                    device=DEVICE

                )


                fake_labels = torch.zeros(

                    batch_size,

                    1,

                    device=DEVICE

                )


                real_output = discriminator(
                    real_data
                )


                fake_output = discriminator(
                    fake_data
                )


                # ------------------------------------------------------------------
                # Ensure discriminator output has correct shape
                # ------------------------------------------------------------------

                if real_output.ndim == 1:

                    real_output = (
                        real_output
                        .reshape(-1, 1)
                    )


                if fake_output.ndim == 1:

                    fake_output = (
                        fake_output
                        .reshape(-1, 1)
                    )


                d_loss_real = (
                    discriminator_loss_function(
                        real_output,
                        real_labels
                    )
                )


                d_loss_fake = (
                    discriminator_loss_function(
                        fake_output,
                        fake_labels
                    )
                )


                d_loss = (
                    d_loss_real
                    +
                    d_loss_fake
                )


                d_loss.backward()


                # ------------------------------------------------------------------
                # Verify Opacus per-sample gradients BEFORE optimizer.step()
                # ------------------------------------------------------------------

                missing_grad_samples = []


                for name, parameter in (
                    discriminator.named_parameters()
                ):

                    if (
                        parameter.requires_grad
                        and
                        parameter.grad_sample is None
                    ):

                        missing_grad_samples.append(
                            name
                        )


                if missing_grad_samples:

                    raise RuntimeError(

                        "Opacus per-sample gradients "
                        "were not generated for: "

                        +
                        ", ".join(
                            missing_grad_samples
                        )

                    )


                discriminator_optimizer.step()


                # ==================================================================
                # GENERATOR UPDATE
                # ==================================================================

                # Freeze discriminator parameters.
                # The discriminator must still participate in the
                # computational graph so gradients can flow back to
                # the Generator, but its own parameters must not
                # receive gradients.

                for parameter in discriminator.parameters():

                    parameter.requires_grad_(False)


                generator_optimizer.zero_grad()


                noise = torch.randn(

                    batch_size,

                    LATENT_DIMENSION,

                    device=DEVICE

                )


                generated_data = generator(
                    noise
                )


                generated_output = discriminator(
                    generated_data
                )


                if generated_output.ndim == 1:

                    generated_output = (
                        generated_output
                        .reshape(-1, 1)
                    )


                generator_loss = (
                    generator_loss_function(

                        generated_output,

                        real_labels

                    )
                )


                generator_loss.backward()


                generator_optimizer.step()


                # ------------------------------------------------------------------
                # Restore discriminator gradients
                # ------------------------------------------------------------------

                for parameter in discriminator.parameters():

                    parameter.requires_grad_(True)


                epoch_d_loss += (
                    d_loss.detach().item()
                )


                epoch_g_loss += (
                    generator_loss.detach().item()
                )


                batch_count += 1


            # ======================================================================
            # EPOCH RESULTS
            # ======================================================================

            if batch_count == 0:

                raise RuntimeError(
                    f"No training batches were processed "
                    f"for {dataset}."
                )


            average_d_loss = (
                epoch_d_loss
                /
                batch_count
            )


            average_g_loss = (
                epoch_g_loss
                /
                batch_count
            )


            DP_TRAINING_HISTORY[dataset][
                "Discriminator Loss"
            ].append(
                average_d_loss
            )


            DP_TRAINING_HISTORY[dataset][
                "Generator Loss"
            ].append(
                average_g_loss
            )


            if (
                epoch == 0
                or
                (epoch + 1) % 10 == 0
                or
                epoch == DP_CTGAN_EPOCHS - 1
            ):

                print(

                    f"Epoch {epoch + 1:3d}/"
                    f"{DP_CTGAN_EPOCHS} | "

                    f"D Loss: "
                    f"{average_d_loss:.4f} | "

                    f"G Loss: "
                    f"{average_g_loss:.4f}"

                )


        DP_TRAINING_COMPLETED[
            dataset
        ] = True


        DP_TRAINING_ERRORS[
            dataset
        ] = None


        print()

        print(
            "DP Discriminator Training : PASS"
        )

        print(
            "Generator Training        : PASS"
        )

        print(
            "Overall Training          : PASS"
        )


    except Exception as error:

        dataset_completed = False


        DP_TRAINING_COMPLETED[
            dataset
        ] = False


        DP_TRAINING_ERRORS[
            dataset
        ] = (
            f"{type(error).__name__}: {error}"
        )


        print()

        print(
            "DP-CTGAN Training : FAIL"
        )


        print(
            f"Error Type       : "
            f"{type(error).__name__}"
        )


        print(
            f"Error Message    : "
            f"{error}"
        )


        raise


print()

print("=" * 100)
print("DP-CTGAN TRAINING SUMMARY")
print("=" * 100)


for dataset, status in (
    DP_TRAINING_COMPLETED.items()
):

    print(
        f"{dataset:20s} : "
        f"{'PASS' if status else 'FAIL'}"
    )


if not all(
    DP_TRAINING_COMPLETED.values()
):

    raise RuntimeError(
        "DP-CTGAN training failed "
        "for one or more datasets."
    )


print()

print(
    "All datasets completed DP-CTGAN training successfully."
)

====================================================================================================
PART L6 — DP-CTGAN TRAINING LOOP
====================================================================================================

================================================================================
Adult Income
================================================================================

DP-CTGAN Training : FAIL
Error Type       : RuntimeError
Error Message    : Opacus per-sample gradients were not generated for: _module.network.0.weight, _module.network.0.bias, _module.network.1.weight, _module.network.1.bias, _module.network.4.weight, _module.network.4.bias, _module.network.5.weight, _module.network.5.bias, _module.network.8.weight, _module.network.8.bias, _module.network.9.weight, _module.network.9.bias, _module.network.12.weight, _module.network.12.bias

RuntimeError: Opacus per-sample gradients were not generated for: _module.network.0.weight, _module.network.0.bias, _module.network.1.weight, _module.network.1.bias, _module.network.4.weight, _module.network.4.bias, _module.network.5.weight, _module.network.5.bias, _module.network.8.weight, _module.network.8.bias, _module.network.9.weight, _module.network.9.bias, _module.network.12.weight, _module.network.12.bias

In [267]:
# ==============================================================================
# PART L7 — DP TRAINING HISTORY INITIALIZATION
# ==============================================================================

print("=" * 100)
print("PART L7 — DP TRAINING HISTORY INITIALIZATION")
print("=" * 100)

DP_TRAINING_HISTORY = {}

DP_PRIVACY_HISTORY = {}

for dataset in DATASETS:

    DP_TRAINING_HISTORY[
        dataset
    ] = {
        "epoch": [],
        "generator_loss": [],
        "discriminator_loss": []
    }

    DP_PRIVACY_HISTORY[
        dataset
    ] = {
        "epoch": [],
        "epsilon": [],
        "delta": DP_DELTA
    }

    print(
        f"{dataset:25s}: History initialized"
    )

print()
print(
    "Training and privacy histories initialized."
)

====================================================================================================
PART L7 — DP TRAINING HISTORY INITIALIZATION
====================================================================================================
Adult Income             : History initialized
Bank Marketing           : History initialized
diabetes_130us           : History initialized

Training and privacy histories initialized.

In [268]:
# ==============================================================================
# PART L8 — DP-CTGAN TRAINING LOOP
# ==============================================================================

print("=" * 100)
print("PART L8 — DP-CTGAN TRAINING LOOP")
print("=" * 100)

for dataset in DATASETS:

    print()
    print("=" * 100)
    print(
        f"TRAINING DATASET: {dataset}"
    )
    print("=" * 100)

    generator = GENERATORS[dataset]

    discriminator = DISCRIMINATORS[dataset]

    generator_optimizer = (
        GENERATOR_OPTIMIZERS[dataset]
    )

    discriminator_optimizer = (
        DISCRIMINATOR_OPTIMIZERS[dataset]
    )

    train_loader = (
        DP_TRAIN_DATALOADERS[dataset]
    )

    privacy_engine = (
        PRIVACY_ENGINES[dataset]
    )

    generator.train()
    discriminator.train()

    dataset_feature_count = (
        TRAIN_DATASETS[dataset].shape[1]
    )

    print(
        f"Training Samples   : "
        f"{len(TRAIN_DATASETS[dataset])}"
    )

    print(
        f"Training Features  : "
        f"{dataset_feature_count}"
    )

    print(
        f"Training Epochs    : "
        f"{DP_TRAINING_EPOCHS}"
    )

    print(
        f"Latent Dimension   : "
        f"{DP_TRAINING_LATENT_DIMENSION}"
    )

    print()

    for epoch in range(
        1,
        DP_TRAINING_EPOCHS + 1
    ):

        epoch_generator_losses = []

        epoch_discriminator_losses = []

        for batch_index, batch in enumerate(
            train_loader,
            start=1
        ):

            real_data = batch[0].to(
                DEVICE,
                dtype=torch.float32
            )

            if real_data.ndim != 2:

                raise RuntimeError(
                    f"Invalid batch shape for "
                    f"{dataset}: "
                    f"{tuple(real_data.shape)}"
                )

            if (
                real_data.shape[1]
                != dataset_feature_count
            ):

                raise RuntimeError(
                    f"Feature dimension mismatch for "
                    f"{dataset}. Expected "
                    f"{dataset_feature_count}, got "
                    f"{real_data.shape[1]}."
                )

            current_batch_size = (
                real_data.size(0)
            )

            if current_batch_size <= 0:

                raise RuntimeError(
                    f"Empty batch detected for "
                    f"{dataset}."
                )

            discriminator_loss = (
                train_discriminator_step(
                    discriminator=discriminator,
                    discriminator_optimizer=(
                        discriminator_optimizer
                    ),
                    real_data=real_data,
                    generator=generator,
                    latent_dimension=(
                        DP_TRAINING_LATENT_DIMENSION
                    ),
                    discriminator_loss_function=(
                        DP_DISCRIMINATOR_LOSS_FUNCTION
                    )
                )
            )

            generator_loss = (
                train_generator_step(
                    generator=generator,
                    generator_optimizer=(
                        generator_optimizer
                    ),
                    discriminator=discriminator,
                    batch_size=current_batch_size,
                    latent_dimension=(
                        DP_TRAINING_LATENT_DIMENSION
                    ),
                    generator_loss_function=(
                        DP_GENERATOR_LOSS_FUNCTION
                    ),
                    device=DEVICE
                )
            )

            epoch_discriminator_losses.append(
                float(
                    discriminator_loss.cpu().item()
                )
            )

            epoch_generator_losses.append(
                float(
                    generator_loss.cpu().item()
                )
            )

        if not epoch_generator_losses:

            raise RuntimeError(
                f"No training batches were processed "
                f"for {dataset} during epoch {epoch}."
            )

        average_generator_loss = float(
            np.mean(
                epoch_generator_losses
            )
        )

        average_discriminator_loss = float(
            np.mean(
                epoch_discriminator_losses
            )
        )

        DP_TRAINING_HISTORY[
            dataset
        ]["epoch"].append(epoch)

        DP_TRAINING_HISTORY[
            dataset
        ]["generator_loss"].append(
            average_generator_loss
        )

        DP_TRAINING_HISTORY[
            dataset
        ]["discriminator_loss"].append(
            average_discriminator_loss
        )

        try:

            current_epsilon = (
                privacy_engine.get_epsilon(
                    delta=DP_DELTA
                )
            )

            if not np.isfinite(
                current_epsilon
            ):

                current_epsilon = np.nan

        except Exception:

            current_epsilon = np.nan

        DP_PRIVACY_HISTORY[
            dataset
        ]["epoch"].append(epoch)

        DP_PRIVACY_HISTORY[
            dataset
        ]["epsilon"].append(
            current_epsilon
        )

        if (
            epoch == 1
            or epoch % DP_TRAINING_LOG_INTERVAL == 0
            or epoch == DP_TRAINING_EPOCHS
        ):

            if np.isfinite(
                current_epsilon
            ):

                epsilon_text = (
                    f"{current_epsilon:.6f}"
                )

            else:

                epsilon_text = (
                    "Not Available"
                )

            print(
                f"Epoch {epoch:4d}/"
                f"{DP_TRAINING_EPOCHS} | "
                f"D Loss: "
                f"{average_discriminator_loss:.6f} | "
                f"G Loss: "
                f"{average_generator_loss:.6f} | "
                f"Epsilon: "
                f"{epsilon_text}"
            )

    print()
    print(
        f"Completed DP training: {dataset}"
    )

====================================================================================================
PART L8 — DP-CTGAN TRAINING LOOP
====================================================================================================

====================================================================================================
TRAINING DATASET: Adult Income
====================================================================================================
Training Samples   : 22760
Training Features  : 15
Training Epochs    : 100
Latent Dimension   : 128

RuntimeError: The size of tensor a (251) must match the size of tensor b (256) at non-singleton dimension 0

In [163]:
# ==============================================================================
# DP-CTGAN DIMENSION DIAGNOSTIC
# ==============================================================================

print("=" * 100)
print("DP-CTGAN DIMENSION DIAGNOSTIC")
print("=" * 100)

for dataset in DATASETS:
    train_features = TRAIN_DATASETS[dataset].shape[1]

    discriminator = DISCRIMINATORS[dataset]

    first_linear = None

    for layer in discriminator.modules():
        if isinstance(layer, nn.Linear):
            first_linear = layer
            break

    print()
    print(dataset)
    print(
        f"Training Features       : "
        f"{train_features}"
    )
    print(
        f"Discriminator Input     : "
        f"{first_linear.in_features}"
    )
    print(
        f"Discriminator Output    : "
        f"{first_linear.out_features}"
    )

====================================================================================================
DP-CTGAN DIMENSION DIAGNOSTIC
====================================================================================================

Adult Income
Training Features       : 15
Discriminator Input     : 14
Discriminator Output    : 512

Bank Marketing
Training Features       : 17
Discriminator Input     : 16
Discriminator Output    : 512

diabetes_130us
Training Features       : 48
Discriminator Input     : 47
Discriminator Output    : 512