# =============================================================

# NOTEBOOK 06

#

# Privacy-Preserving Deep Learning Synthetic Data Generation — DP-CTGAN

# ==============================================================

SPP-GAN: A Privacy-Preserving Statistical–Machine Learning Framework for
High-Fidelity Synthetic Tabular Data Generation

## Researcher

Mohd Amzad

## Notebook

Notebook 06 – Privacy-Preserving Deep Learning Synthetic Data Generation
(DP-CTGAN)

## Purpose

This notebook implements a Differentially Private Conditional Generative
Adversarial Network (DP-CTGAN) for privacy-preserving synthetic tabular data
generation using the preprocessed datasets produced in Notebook 02.

The notebook extends the CTGAN-based synthetic data generation process by
incorporating Differential Privacy (DP) during model training using the
Opacus privacy framework.

The trained DP-CTGAN models are used to generate synthetic datasets that
will be evaluated in subsequent notebooks using a common evaluation
framework for structural consistency, statistical fidelity, data utility,
and privacy-related performance.

## Model Implemented

• Differentially Private Conditional Generative Adversarial Network (DP-CTGAN)

## Privacy Mechanism

• Differential Privacy using DP-SGD
• Opacus PrivacyEngine
• Per-sample gradient computation
• Gradient clipping
• Gaussian noise addition
• Privacy accounting using (ε, δ)-Differential Privacy

## Inputs

### Notebook 02

• Preprocessed datasets
• Dataset metadata
• Train, validation, and test splits
• Feature information required for model training

### Project Configuration

• config.yaml
• Reproducibility settings
• DP-CTGAN hyperparameters
• Privacy parameters

## Outputs

• Trained DP-CTGAN generator models
• Trained DP-CTGAN discriminator models
• Privacy-accounting results
• Synthetic datasets
• Model checkpoints
• Training history
• Privacy-training history
• Generated visualizations
• Dataset metadata
• DP-CTGAN configuration records
• Intermediate artifacts for downstream evaluation

## Workflow

A. Notebook Overview
B. Environment Setup
C. Project Configuration
D. Dataset Loading and Validation
E. Feature and Tensor Preparation
F. Differential Privacy Configuration
G. Generator Architecture
H. Discriminator Architecture
I. Opacus Compatibility Validation
J. Loss Functions and Optimizers
K. PrivacyEngine Configuration
L. DP-CTGAN Training
M. Privacy Accounting
N. Synthetic Data Generation
O. Model and Dataset Saving
P. Training and Privacy Visualizations
Q. Final Verification

## Research Role

Notebook 06 is responsible for training the privacy-preserving DP-CTGAN
models and generating synthetic datasets.

The common evaluation of the generated synthetic datasets is performed
separately using the established evaluation workflow in Notebook 04.
This ensures that statistical fidelity, structural consistency, utility,
and other evaluation metrics are applied consistently across the different
synthetic data generation methods.

## Version

1.0

In [1]:
# ==============================================================================
# PART A1 — GOOGLE DRIVE MOUNTING
# ==============================================================================

from google.colab import drive
from pathlib import Path

print("=" * 100)
print("PART A1 — GOOGLE DRIVE MOUNTING")
print("=" * 100)

drive.mount("/content/drive")

GOOGLE_DRIVE_ROOT = Path("/content/drive/MyDrive")

DRIVE_VERIFICATION = GOOGLE_DRIVE_ROOT.exists()

if not DRIVE_VERIFICATION:
    raise FileNotFoundError(
        f"Google Drive root was not found: {GOOGLE_DRIVE_ROOT}"
    )

print(f"Google Drive Root: {GOOGLE_DRIVE_ROOT}")
print("Google Drive verification: PASS")

====================================================================================================
PART A1 — GOOGLE DRIVE MOUNTING
====================================================================================================
Mounted at /content/drive
Google Drive Root: /content/drive/MyDrive
Google Drive verification: PASS

In [2]:
# ==============================================================================
# PART A2 — INSTALL REQUIRED PACKAGES
# ==============================================================================

print("=" * 100)
print("PART A2 — INSTALL REQUIRED PACKAGES")
print("=" * 100)

%pip install -q "opacus==1.6.0" "pyyaml>=6.0"

print("Required packages installed successfully.")
print("Opacus version pinned to 1.6.0.")

====================================================================================================
PART A2 — INSTALL REQUIRED PACKAGES
====================================================================================================
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 308.9/308.9 kB 5.8 MB/s eta 0:00:00
Required packages installed successfully.
Opacus version pinned to 1.6.0.

In [3]:
# ==============================================================================
# PART A3 — IMPORT REQUIRED LIBRARIES
# ==============================================================================

import json
import math
import os
import pickle
import platform
import random
import sys
import warnings
from datetime import datetime
from pathlib import Path

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import seaborn as sns
import torch
import torch.nn as nn
import torch.nn.functional as F
import yaml
from opacus import PrivacyEngine
from opacus.validators import ModuleValidator
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from torch.utils.data import DataLoader, Dataset

warnings.filterwarnings("ignore")

print("All required libraries imported successfully.")

All required libraries imported successfully.

In [4]:
# ==============================================================================
# PART A4 — REPRODUCIBILITY CONFIGURATION
# ==============================================================================

SEED = 42

random.seed(SEED)
np.random.seed(SEED)
torch.manual_seed(SEED)

if torch.cuda.is_available():
    torch.cuda.manual_seed(SEED)
    torch.cuda.manual_seed_all(SEED)

torch.backends.cudnn.deterministic = True
torch.backends.cudnn.benchmark = False

print("=" * 100)
print("PART A4 — REPRODUCIBILITY CONFIGURATION")
print("=" * 100)
print(f"Global Random Seed : {SEED}")
print("Python random seed : Configured")
print("NumPy random seed  : Configured")
print("PyTorch random seed: Configured")
print("CUDA random seed   : Configured when available")
print("CuDNN deterministic: Enabled")

====================================================================================================
PART A4 — REPRODUCIBILITY CONFIGURATION
====================================================================================================
Global Random Seed : 42
Python random seed : Configured
NumPy random seed  : Configured
PyTorch random seed: Configured
CUDA random seed   : Configured when available
CuDNN deterministic: Enabled

In [5]:
# ==============================================================================
# PART A5 — HARDWARE AND DEVICE CONFIGURATION
# ==============================================================================

DEVICE = torch.device("cuda" if torch.cuda.is_available() else "cpu")

print("=" * 100)
print("PART A5 — HARDWARE AND DEVICE CONFIGURATION")
print("=" * 100)
print(f"Selected Device : {DEVICE}")

if DEVICE.type == "cuda":
    print(f"GPU Device      : {torch.cuda.get_device_name(0)}")
    print(f"CUDA Version    : {torch.version.cuda}")
    print(f"GPU Count       : {torch.cuda.device_count()}")
    print(f"Current GPU ID  : {torch.cuda.current_device()}")
else:
    print("GPU Device      : Not available")
    print("CUDA Version    : Not available")
    print("GPU Count       : 0")
    print("Training will use CPU.")

====================================================================================================
PART A5 — HARDWARE AND DEVICE CONFIGURATION
====================================================================================================
Selected Device : cpu
GPU Device      : Not available
CUDA Version    : Not available
GPU Count       : 0
Training will use CPU.

In [6]:
# ==============================================================================
# PART A6 — SOFTWARE VERSION VERIFICATION
# ==============================================================================

import sklearn
import opacus

SOFTWARE_VERSIONS = {
    "Python": platform.python_version(),
    "Operating System": platform.system(),
    "PyTorch": torch.__version__,
    "NumPy": np.__version__,
    "Pandas": pd.__version__,
    "Scikit-learn": sklearn.__version__,
    "Opacus": opacus.__version__,
    "Matplotlib": plt.matplotlib.__version__,
    "Seaborn": sns.__version__,
    "PyYAML": yaml.__version__,
}

print("=" * 100)
print("PART A6 — SOFTWARE VERSION VERIFICATION")
print("=" * 100)

for software, version in SOFTWARE_VERSIONS.items():
    print(f"{software:20s}: {version}")

====================================================================================================
PART A6 — SOFTWARE VERSION VERIFICATION
====================================================================================================
Python              : 3.12.13
Operating System    : Linux
PyTorch             : 2.11.0+cpu
NumPy               : 2.0.2
Pandas              : 2.2.2
Scikit-learn        : 1.6.1
Opacus              : 1.6.0
Matplotlib          : 3.10.0
Seaborn             : 0.13.2
PyYAML              : 6.0.3

In [7]:
# ==============================================================================
# PART A7 — ENVIRONMENT VERIFICATION
# ==============================================================================

ENVIRONMENT_VERIFICATION = {
    "Google Drive Available": DRIVE_VERIFICATION,
    "Python Version Valid": sys.version_info.major >= 3,
    "PyTorch Available": torch.__version__ is not None,
    "NumPy Available": np.__version__ is not None,
    "Pandas Available": pd.__version__ is not None,
    "Scikit-learn Available": sklearn.__version__ is not None,
    "Opacus Version 1.6.0": opacus.__version__ == "1.6.0",
    "PyYAML Available": yaml.__version__ is not None,
    "Device Configured": DEVICE.type in {"cpu", "cuda"},
    "Seed Configured": SEED == 42,
}

print("=" * 100)
print("PART A7 — ENVIRONMENT VERIFICATION")
print("=" * 100)

for check, status in ENVIRONMENT_VERIFICATION.items():
    print(f"{check:35s}: {'PASS' if status else 'FAIL'}")

PASSED_CHECKS = sum(ENVIRONMENT_VERIFICATION.values())
TOTAL_CHECKS = len(ENVIRONMENT_VERIFICATION)

print()
print(f"Environment Checks: {PASSED_CHECKS}/{TOTAL_CHECKS} Passed")

if PASSED_CHECKS != TOTAL_CHECKS:
    raise RuntimeError(
        "Environment verification failed. "
        "Review the failed checks before continuing."
    )

print("Environment verification: PASS")

====================================================================================================
PART A7 — ENVIRONMENT VERIFICATION
====================================================================================================
Google Drive Available             : PASS
Python Version Valid               : PASS
PyTorch Available                  : PASS
NumPy Available                    : PASS
Pandas Available                   : PASS
Scikit-learn Available             : PASS
Opacus Version 1.6.0               : PASS
PyYAML Available                   : PASS
Device Configured                  : PASS
Seed Configured                    : PASS

Environment Checks: 10/10 Passed
Environment verification: PASS

In [8]:
# ==============================================================================
# PART B1 — PROJECT ROOT CONFIGURATION
# ==============================================================================

print("=" * 100)
print("PART B1 — PROJECT ROOT CONFIGURATION")
print("=" * 100)

PROJECT_NAME = "SPP_GAN_Project"
PROJECT_ROOT = GOOGLE_DRIVE_ROOT / PROJECT_NAME

print(f"Project Name : {PROJECT_NAME}")
print(f"Project Root : {PROJECT_ROOT}")

if not PROJECT_ROOT.is_dir():
    raise FileNotFoundError(
        f"Project root was not found:\n{PROJECT_ROOT}\n\n"
        "Please verify the project folder in Google Drive."
    )

print("Project root verified successfully.")

====================================================================================================
PART B1 — PROJECT ROOT CONFIGURATION
====================================================================================================
Project Name : SPP_GAN_Project
Project Root : /content/drive/MyDrive/SPP_GAN_Project
Project root verified successfully.

In [9]:
# ==============================================================================
# PART B2 — PROJECT STRUCTURE INSPECTION
# ==============================================================================

print("=" * 100)
print("PART B2 — PROJECT STRUCTURE INSPECTION")
print("=" * 100)

PROJECT_ITEMS = sorted(PROJECT_ROOT.iterdir(), key=lambda item: (not item.is_dir(), item.name.lower()))

if not PROJECT_ITEMS:
    print("Project root is empty.")
else:
    for item in PROJECT_ITEMS:
        item_type = "[DIR ]" if item.is_dir() else "[FILE]"
        print(f"{item_type} {item.name}")

====================================================================================================
PART B2 — PROJECT STRUCTURE INSPECTION
====================================================================================================
[DIR ] checkpoints
[DIR ] config
[DIR ] configs
[DIR ] datasets
[DIR ] experiments
[DIR ] figures
[DIR ] histories
[DIR ] logs
[DIR ] metadata
[DIR ] models
[DIR ] notebooks
[DIR ] plots
[DIR ] privacy
[DIR ] reports
[DIR ] results
[DIR ] statistical_models
[DIR ] synthetic_data
[DIR ] training
[FILE] config.yaml

In [10]:
# ==============================================================================
# PART B3 — CONFIGURATION FILE DISCOVERY
# ==============================================================================

CONFIG_CANDIDATES = [
    PROJECT_ROOT / "config.yaml",
    PROJECT_ROOT / "configs" / "config.yaml",
    PROJECT_ROOT / "configuration" / "config.yaml",
    PROJECT_ROOT / "config" / "config.yaml",
]

CONFIG_PATH = next(
    (path for path in CONFIG_CANDIDATES if path.is_file()),
    None
)

print("=" * 100)
print("PART B3 — CONFIGURATION FILE DISCOVERY")
print("=" * 100)

if CONFIG_PATH is None:
    print("config.yaml was not found.")
    print()
    print("Checked locations:")
    for path in CONFIG_CANDIDATES:
        print(f"  - {path}")
    raise FileNotFoundError(
        "Configuration file could not be located."
    )

print(f"Configuration File: {CONFIG_PATH}")
print("Configuration file verified successfully.")

====================================================================================================
PART B3 — CONFIGURATION FILE DISCOVERY
====================================================================================================
Configuration File: /content/drive/MyDrive/SPP_GAN_Project/config.yaml
Configuration file verified successfully.

In [11]:
# ==============================================================================
# PART B4 — LOAD PROJECT CONFIGURATION
# ==============================================================================

with CONFIG_PATH.open("r", encoding="utf-8") as file:
    CONFIG = yaml.safe_load(file)

if CONFIG is None:
    CONFIG = {}

if not isinstance(CONFIG, dict):
    raise TypeError(
        f"Configuration must be a YAML mapping, "
        f"but received: {type(CONFIG).__name__}"
    )

print("=" * 100)
print("PART B4 — PROJECT CONFIGURATION")
print("=" * 100)
print(json.dumps(CONFIG, indent=4, default=str))

====================================================================================================
PART B4 — PROJECT CONFIGURATION
====================================================================================================
{
    "batch_size": 256,
    "beta1": 0.5,
    "beta2": 0.999,
    "delta": 1e-05,
    "device": "cuda",
    "epochs": 100,
    "gradient_clip": 1.0,
    "latent_dimension": 128,
    "learning_rate": 0.0002,
    "noise_multiplier": 1.1,
    "optimizer": "Adam",
    "privacy_budget": 4,
    "seed": 42
}

In [12]:
# ==============================================================================
# PART B5 — CONFIGURATION VALIDATION
# ==============================================================================

REQUIRED_CONFIG_KEYS = [
    "batch_size",
    "epochs",
    "learning_rate",
    "beta1",
    "beta2",
    "latent_dimension",
    "privacy_budget",
    "delta",
    "noise_multiplier",
    "gradient_clip",
    "seed",
]

CONFIG_VALIDATION = {
    key: key in CONFIG and CONFIG[key] is not None
    for key in REQUIRED_CONFIG_KEYS
}

print("=" * 100)
print("PART B5 — CONFIGURATION VALIDATION")
print("=" * 100)

for key, status in CONFIG_VALIDATION.items():
    print(f"{key:25s}: {'PASS' if status else 'MISSING'}")

MISSING_CONFIG_KEYS = [
    key
    for key, status in CONFIG_VALIDATION.items()
    if not status
]

if MISSING_CONFIG_KEYS:
    raise KeyError(
        "Required configuration parameters are missing or empty:\n"
        + "\n".join(f"- {key}" for key in MISSING_CONFIG_KEYS)
    )

CONFIG_VALUE_VALIDATION = {
    "batch_size": CONFIG["batch_size"] > 0,
    "epochs": CONFIG["epochs"] > 0,
    "learning_rate": CONFIG["learning_rate"] > 0,
    "beta1": 0 <= CONFIG["beta1"] < 1,
    "beta2": 0 <= CONFIG["beta2"] < 1,
    "latent_dimension": CONFIG["latent_dimension"] > 0,
    "privacy_budget": CONFIG["privacy_budget"] > 0,
    "delta": 0 < CONFIG["delta"] < 1,
    "noise_multiplier": CONFIG["noise_multiplier"] > 0,
    "gradient_clip": CONFIG["gradient_clip"] > 0,
    "seed": CONFIG["seed"] >= 0,
}

print()
print("Configuration Value Validation")
print("-" * 100)

for key, status in CONFIG_VALUE_VALIDATION.items():
    print(f"{key:25s}: {'PASS' if status else 'INVALID'}")

INVALID_CONFIG_VALUES = [
    key
    for key, status in CONFIG_VALUE_VALIDATION.items()
    if not status
]

if INVALID_CONFIG_VALUES:
    raise ValueError(
        "Invalid configuration values:\n"
        + "\n".join(f"- {key}" for key in INVALID_CONFIG_VALUES)
    )

print()
print("All required configuration parameters are present and valid.")

====================================================================================================
PART B5 — CONFIGURATION VALIDATION
====================================================================================================
batch_size               : PASS
epochs                   : PASS
learning_rate            : PASS
beta1                    : PASS
beta2                    : PASS
latent_dimension         : PASS
privacy_budget           : PASS
delta                    : PASS
noise_multiplier         : PASS
gradient_clip            : PASS
seed                     : PASS

Configuration Value Validation
----------------------------------------------------------------------------------------------------
batch_size               : PASS
epochs                   : PASS
learning_rate            : PASS
beta1                    : PASS
beta2                    : PASS
latent_dimension         : PASS
privacy_budget           : PASS
delta                    : PASS
noise_multiplier         : PASS
gradient_clip            : PASS
seed                     : PASS

All required configuration parameters are present and valid.

In [13]:
# ==============================================================================
# PART B6 — GENERAL PROJECT CONFIGURATION
# ==============================================================================

PROJECT_CONFIG = {
    "seed": int(CONFIG["seed"]),
    "device": str(DEVICE),
    "batch_size": int(CONFIG["batch_size"]),
    "epochs": int(CONFIG["epochs"]),
    "learning_rate": float(CONFIG["learning_rate"]),
    "beta1": float(CONFIG["beta1"]),
    "beta2": float(CONFIG["beta2"]),
    "latent_dimension": int(CONFIG["latent_dimension"]),
}

print("=" * 100)
print("PART B6 — GENERAL PROJECT CONFIGURATION")
print("=" * 100)

for key, value in PROJECT_CONFIG.items():
    print(f"{key:25s}: {value}")

====================================================================================================
PART B6 — GENERAL PROJECT CONFIGURATION
====================================================================================================
seed                     : 42
device                   : cpu
batch_size               : 256
epochs                   : 100
learning_rate            : 0.0002
beta1                    : 0.5
beta2                    : 0.999
latent_dimension         : 128

In [14]:
# ==============================================================================
# PART B7 — DIFFERENTIAL PRIVACY CONFIGURATION
# ==============================================================================

DP_CONFIG = {
    "privacy_budget": float(CONFIG["privacy_budget"]),
    "delta": float(CONFIG["delta"]),
    "noise_multiplier": float(CONFIG["noise_multiplier"]),
    "gradient_clip": float(CONFIG["gradient_clip"]),
}

print("=" * 100)
print("PART B7 — DIFFERENTIAL PRIVACY CONFIGURATION")
print("=" * 100)

for key, value in DP_CONFIG.items():
    print(f"{key:25s}: {value}")

====================================================================================================
PART B7 — DIFFERENTIAL PRIVACY CONFIGURATION
====================================================================================================
privacy_budget           : 4.0
delta                    : 1e-05
noise_multiplier         : 1.1
gradient_clip            : 1.0

In [15]:
# ==============================================================================
# PART B8 — DIFFERENTIAL PRIVACY PARAMETER VALIDATION
# ==============================================================================

DP_VALIDATION = {
    "Privacy Budget > 0": (
        np.isfinite(DP_CONFIG["privacy_budget"])
        and DP_CONFIG["privacy_budget"] > 0
    ),
    "Delta > 0": (
        np.isfinite(DP_CONFIG["delta"])
        and DP_CONFIG["delta"] > 0
    ),
    "Delta < 1": (
        np.isfinite(DP_CONFIG["delta"])
        and DP_CONFIG["delta"] < 1
    ),
    "Noise Multiplier > 0": (
        np.isfinite(DP_CONFIG["noise_multiplier"])
        and DP_CONFIG["noise_multiplier"] > 0
    ),
    "Gradient Clip > 0": (
        np.isfinite(DP_CONFIG["gradient_clip"])
        and DP_CONFIG["gradient_clip"] > 0
    ),
}

print("=" * 100)
print("PART B8 — DIFFERENTIAL PRIVACY PARAMETER VALIDATION")
print("=" * 100)

for check, status in DP_VALIDATION.items():
    print(f"{check:35s}: {'PASS' if status else 'FAIL'}")

if not all(DP_VALIDATION.values()):
    raise ValueError(
        "One or more Differential Privacy parameters are invalid."
    )

print()
print("Differential Privacy parameters passed validation.")

====================================================================================================
PART B8 — DIFFERENTIAL PRIVACY PARAMETER VALIDATION
====================================================================================================
Privacy Budget > 0                 : PASS
Delta > 0                          : PASS
Delta < 1                          : PASS
Noise Multiplier > 0               : PASS
Gradient Clip > 0                  : PASS

Differential Privacy parameters passed validation.

In [16]:
# ==============================================================================
# PART B9 — PROJECT DIRECTORY CONFIGURATION
# ==============================================================================

DATA_DIR = PROJECT_ROOT / "data"
RAW_DATA_DIR = DATA_DIR / "raw"
PROCESSED_DATA_DIR = DATA_DIR / "processed"
NOTEBOOK_DIR = PROJECT_ROOT / "notebooks"
MODEL_ROOT_DIR = PROJECT_ROOT / "models"
SYNTHETIC_ROOT_DIR = PROJECT_ROOT / "synthetic_data"
EVALUATION_ROOT_DIR = PROJECT_ROOT / "evaluation"
REPORT_ROOT_DIR = PROJECT_ROOT / "reports"
PLOT_ROOT_DIR = PROJECT_ROOT / "plots"
METADATA_ROOT_DIR = PROJECT_ROOT / "metadata"
LOG_ROOT_DIR = PROJECT_ROOT / "logs"

PROJECT_DIRECTORIES = {
    "Project Root": PROJECT_ROOT,
    "Data": DATA_DIR,
    "Raw Data": RAW_DATA_DIR,
    "Processed Data": PROCESSED_DATA_DIR,
    "Notebooks": NOTEBOOK_DIR,
    "Models": MODEL_ROOT_DIR,
    "Synthetic Data": SYNTHETIC_ROOT_DIR,
    "Evaluation": EVALUATION_ROOT_DIR,
    "Reports": REPORT_ROOT_DIR,
    "Plots": PLOT_ROOT_DIR,
    "Metadata": METADATA_ROOT_DIR,
    "Logs": LOG_ROOT_DIR,
}

print("=" * 100)
print("PART B9 — PROJECT DIRECTORY CONFIGURATION")
print("=" * 100)

for name, path in PROJECT_DIRECTORIES.items():
    print(f"{name:20s}: {path}")

====================================================================================================
PART B9 — PROJECT DIRECTORY CONFIGURATION
====================================================================================================
Project Root        : /content/drive/MyDrive/SPP_GAN_Project
Data                : /content/drive/MyDrive/SPP_GAN_Project/data
Raw Data            : /content/drive/MyDrive/SPP_GAN_Project/data/raw
Processed Data      : /content/drive/MyDrive/SPP_GAN_Project/data/processed
Notebooks           : /content/drive/MyDrive/SPP_GAN_Project/notebooks
Models              : /content/drive/MyDrive/SPP_GAN_Project/models
Synthetic Data      : /content/drive/MyDrive/SPP_GAN_Project/synthetic_data
Evaluation          : /content/drive/MyDrive/SPP_GAN_Project/evaluation
Reports             : /content/drive/MyDrive/SPP_GAN_Project/reports
Plots               : /content/drive/MyDrive/SPP_GAN_Project/plots
Metadata            : /content/drive/MyDrive/SPP_GAN_Project/metadata
Logs                : /content/drive/MyDrive/SPP_GAN_Project/logs

In [17]:
# ==============================================================================
# PART B10 — DP-CTGAN OUTPUT DIRECTORIES
# ==============================================================================

DP_CTGAN_MODEL_DIR = MODEL_ROOT_DIR / "dp_ctgan"
DP_CTGAN_SYNTHETIC_DIR = SYNTHETIC_ROOT_DIR / "dp_ctgan"
DP_CTGAN_REPORT_DIR = REPORT_ROOT_DIR / "dp_ctgan"
DP_CTGAN_PLOT_DIR = PLOT_ROOT_DIR / "dp_ctgan"
DP_CTGAN_METADATA_DIR = METADATA_ROOT_DIR / "dp_ctgan"
DP_CTGAN_LOG_DIR = LOG_ROOT_DIR / "dp_ctgan"

DP_CTGAN_DIRECTORIES = {
    "DP-CTGAN Models": DP_CTGAN_MODEL_DIR,
    "DP-CTGAN Synthetic Data": DP_CTGAN_SYNTHETIC_DIR,
    "DP-CTGAN Reports": DP_CTGAN_REPORT_DIR,
    "DP-CTGAN Plots": DP_CTGAN_PLOT_DIR,
    "DP-CTGAN Metadata": DP_CTGAN_METADATA_DIR,
    "DP-CTGAN Logs": DP_CTGAN_LOG_DIR,
}

for path in DP_CTGAN_DIRECTORIES.values():
    path.mkdir(parents=True, exist_ok=True)

print("=" * 100)
print("PART B10 — DP-CTGAN OUTPUT DIRECTORIES")
print("=" * 100)

for name, path in DP_CTGAN_DIRECTORIES.items():
    print(f"{name:30s}: {path}")

print()
print("DP-CTGAN output directories verified successfully.")

====================================================================================================
PART B10 — DP-CTGAN OUTPUT DIRECTORIES
====================================================================================================
DP-CTGAN Models               : /content/drive/MyDrive/SPP_GAN_Project/models/dp_ctgan
DP-CTGAN Synthetic Data       : /content/drive/MyDrive/SPP_GAN_Project/synthetic_data/dp_ctgan
DP-CTGAN Reports              : /content/drive/MyDrive/SPP_GAN_Project/reports/dp_ctgan
DP-CTGAN Plots                : /content/drive/MyDrive/SPP_GAN_Project/plots/dp_ctgan
DP-CTGAN Metadata             : /content/drive/MyDrive/SPP_GAN_Project/metadata/dp_ctgan
DP-CTGAN Logs                 : /content/drive/MyDrive/SPP_GAN_Project/logs/dp_ctgan

DP-CTGAN output directories verified successfully.

In [18]:
# ==============================================================================
# PART B11 — SAVE ACTIVE CONFIGURATION SNAPSHOT
# ==============================================================================

ACTIVE_CONFIGURATION = {
    "notebook": "Notebook 06 — Privacy-Preserving CTGAN",
    "model": "DP-CTGAN",
    "framework": "SPP-GAN",
    "researcher": "Mohd Amzad",
    "timestamp": datetime.now().isoformat(),
    "project_root": str(PROJECT_ROOT),
    "config_file": str(CONFIG_PATH),
    "project_configuration": PROJECT_CONFIG,
    "differential_privacy_configuration": DP_CONFIG,
    "software_versions": SOFTWARE_VERSIONS,
    "device": str(DEVICE),
    "seed": SEED,
}

CONFIG_SNAPSHOT_PATH = (
    DP_CTGAN_METADATA_DIR / "dp_ctgan_configuration.json"
)

with CONFIG_SNAPSHOT_PATH.open("w", encoding="utf-8") as file:
    json.dump(
        ACTIVE_CONFIGURATION,
        file,
        indent=4,
        default=str
    )

print("=" * 100)
print("PART B11 — CONFIGURATION SNAPSHOT")
print("=" * 100)
print(f"Configuration snapshot saved to:\n{CONFIG_SNAPSHOT_PATH}")

====================================================================================================
PART B11 — CONFIGURATION SNAPSHOT
====================================================================================================
Configuration snapshot saved to:
/content/drive/MyDrive/SPP_GAN_Project/metadata/dp_ctgan/dp_ctgan_configuration.json

In [19]:
# ==============================================================================
# PART B13 — PROJECT CONFIGURATION VERIFICATION
# ==============================================================================

PROJECT_CONFIGURATION_VERIFICATION = {
    "Project Root Exists": PROJECT_ROOT.is_dir(),
    "config.yaml Exists": CONFIG_PATH.is_file(),
    "Configuration Loaded": isinstance(CONFIG, dict),
    "Required Configuration": len(MISSING_CONFIG_KEYS) == 0,
    "DP Parameters Valid": all(DP_VALIDATION.values()),
    "Model Directory": DP_CTGAN_MODEL_DIR.is_dir(),
    "Synthetic Data Directory": DP_CTGAN_SYNTHETIC_DIR.is_dir(),
    "Report Directory": DP_CTGAN_REPORT_DIR.is_dir(),
    "Plot Directory": DP_CTGAN_PLOT_DIR.is_dir(),
    "Metadata Directory": DP_CTGAN_METADATA_DIR.is_dir(),
    "Log Directory": DP_CTGAN_LOG_DIR.is_dir(),
    "Configuration Snapshot": CONFIG_SNAPSHOT_PATH.is_file(),
}

print("=" * 100)
print("PART B13 — PROJECT CONFIGURATION VERIFICATION")
print("=" * 100)

for check, status in PROJECT_CONFIGURATION_VERIFICATION.items():
    print(f"{check:35s}: {'PASS' if status else 'FAIL'}")

B_PASSED = sum(PROJECT_CONFIGURATION_VERIFICATION.values())
B_TOTAL = len(PROJECT_CONFIGURATION_VERIFICATION)

print()
print(f"PART B VERIFICATION: {B_PASSED}/{B_TOTAL} CHECKS PASSED")

if B_PASSED != B_TOTAL:
    FAILED_B_CHECKS = [
        check
        for check, status in PROJECT_CONFIGURATION_VERIFICATION.items()
        if not status
    ]

    raise RuntimeError(
        "PART B project configuration verification failed:\n"
        + "\n".join(f"- {check}" for check in FAILED_B_CHECKS)
    )

print()
print("PART B — PROJECT CONFIGURATION COMPLETED SUCCESSFULLY.")

====================================================================================================
PART B13 — PROJECT CONFIGURATION VERIFICATION
====================================================================================================
Project Root Exists                : PASS
config.yaml Exists                 : PASS
Configuration Loaded               : PASS
Required Configuration             : PASS
DP Parameters Valid                : PASS
Model Directory                    : PASS
Synthetic Data Directory           : PASS
Report Directory                   : PASS
Plot Directory                     : PASS
Metadata Directory                 : PASS
Log Directory                      : PASS
Configuration Snapshot             : PASS

PART B VERIFICATION: 12/12 CHECKS PASSED

PART B — PROJECT CONFIGURATION COMPLETED SUCCESSFULLY.

In [20]:
# ==============================================================================
# PART C1 — DATASET CONFIGURATION
# ==============================================================================

print("=" * 100)
print("PART C1 — DATASET CONFIGURATION")
print("=" * 100)

DATASETS = [
    "Adult Income",
    "Bank Marketing",
    "diabetes_130us",
]

DATASET_FILE_NAMES = {
    "Adult Income": [
        "adult_income.csv",
        "adult.csv",
        "adult_income_processed.csv",
        "adult_processed.csv",
    ],
    "Bank Marketing": [
        "bank_marketing.csv",
        "bank.csv",
        "bank_marketing_processed.csv",
        "bank_processed.csv",
    ],
    "diabetes_130us": [
        "diabetes_130us.csv",
        "diabetes_130us_processed.csv",
        "diabetic_data.csv",
        "diabetes_processed.csv",
    ],
}

print(f"Datasets configured: {len(DATASETS)}")

for index, dataset in enumerate(DATASETS, start=1):
    print(f"{index}. {dataset}")

====================================================================================================
PART C1 — DATASET CONFIGURATION
====================================================================================================
Datasets configured: 3
1. Adult Income
2. Bank Marketing
3. diabetes_130us

In [21]:
# ==============================================================================
# PART C2 — DATASET FILE DISCOVERY
# ==============================================================================

print("=" * 100)
print("PART C2 — DATASET FILE DISCOVERY")
print("=" * 100)

DATASET_PATHS = {}
DATASET_DISCOVERY = {}
DATASET_MATCHES = {}

ALL_CSV_FILES = sorted(
    PROJECT_ROOT.rglob("*.csv"),
    key=lambda path: str(path).lower()
)

for dataset in DATASETS:
    candidate_names = {
        name.lower()
        for name in DATASET_FILE_NAMES[dataset]
    }

    exact_matches = [
        path
        for path in ALL_CSV_FILES
        if path.name.lower() in candidate_names
    ]

    DATASET_MATCHES[dataset] = exact_matches
    DATASET_PATHS[dataset] = None
    DATASET_DISCOVERY[dataset] = False

    if exact_matches:
        processed_matches = [
            path
            for path in exact_matches
            if "processed" in path.name.lower()
        ]

        selected_matches = (
            processed_matches
            if processed_matches
            else exact_matches
        )

        DATASET_PATHS[dataset] = sorted(
            selected_matches,
            key=lambda path: (len(str(path)), str(path).lower())
        )[0]

        DATASET_DISCOVERY[dataset] = True

print()

for dataset in DATASETS:
    matches = DATASET_MATCHES[dataset]
    selected_path = DATASET_PATHS[dataset]

    if selected_path is None:
        print(f"{dataset:30s}: NOT FOUND")
    else:
        print(f"{dataset:30s}: FOUND")
        print(f"{'Selected File':30s}: {selected_path}")

        if len(matches) > 1:
            print(f"{'Candidate Matches':30s}: {len(matches)}")
            for match in matches:
                print(f"{'':30s}  {match}")

====================================================================================================
PART C2 — DATASET FILE DISCOVERY
====================================================================================================

Adult Income                  : FOUND
Selected File                 : /content/drive/MyDrive/SPP_GAN_Project/datasets/processed/adult_income_processed.csv
Candidate Matches             : 2
                                /content/drive/MyDrive/SPP_GAN_Project/datasets/processed/adult_income_processed.csv
                                /content/drive/MyDrive/SPP_GAN_Project/datasets/raw/adult_income.csv
Bank Marketing                : FOUND
Selected File                 : /content/drive/MyDrive/SPP_GAN_Project/datasets/processed/bank_marketing_processed.csv
Candidate Matches             : 3
                                /content/drive/MyDrive/SPP_GAN_Project/datasets/processed/bank_marketing_processed.csv
                                /content/drive/MyDrive/SPP_GAN_Project/datasets/raw/bank.csv
                                /content/drive/MyDrive/SPP_GAN_Project/datasets/raw/bank_marketing.csv
diabetes_130us                : FOUND
Selected File                 : /content/drive/MyDrive/SPP_GAN_Project/datasets/processed/diabetes_130us_processed.csv
Candidate Matches             : 2
                                /content/drive/MyDrive/SPP_GAN_Project/datasets/processed/diabetes_130us_processed.csv
                                /content/drive/MyDrive/SPP_GAN_Project/datasets/raw/diabetes_130us.csv

In [22]:
# ==============================================================================
# PART C3 — DATASET DISCOVERY VALIDATION
# ==============================================================================

print("=" * 100)
print("PART C3 — DATASET DISCOVERY VALIDATION")
print("=" * 100)

MISSING_DATASETS = [
    dataset
    for dataset, status in DATASET_DISCOVERY.items()
    if not status
]

DATASET_DISCOVERY_VERIFICATION = {
    dataset: DATASET_DISCOVERY[dataset]
    for dataset in DATASETS
}

for dataset, status in DATASET_DISCOVERY_VERIFICATION.items():
    print(f"{dataset:30s}: {'PASS' if status else 'FAIL'}")

if MISSING_DATASETS:
    print()
    print("The following datasets could not be located:")

    for dataset in MISSING_DATASETS:
        print(f"  - {dataset}")

    print()
    print("Available CSV files in the project:")

    for path in ALL_CSV_FILES:
        print(f"  - {path}")

    raise FileNotFoundError(
        "One or more required datasets could not be located."
    )

print()
print("All required datasets were successfully located.")

====================================================================================================
PART C3 — DATASET DISCOVERY VALIDATION
====================================================================================================
Adult Income                  : PASS
Bank Marketing                : PASS
diabetes_130us                : PASS

All required datasets were successfully located.

In [23]:
# ==============================================================================
# PART C4 — LOAD REAL DATASETS
# ==============================================================================

print("=" * 100)
print("PART C4 — LOAD REAL DATASETS")
print("=" * 100)

REAL_DATASETS = {}

for dataset in DATASETS:
    dataset_path = DATASET_PATHS[dataset]

    if dataset_path is None or not dataset_path.is_file():
        raise FileNotFoundError(
            f"Dataset file is unavailable for '{dataset}': {dataset_path}"
        )

    REAL_DATASETS[dataset] = pd.read_csv(dataset_path)

    rows, columns = REAL_DATASETS[dataset].shape

    print()
    print(f"Dataset    : {dataset}")
    print(f"Path       : {dataset_path}")
    print(f"Rows       : {rows:,}")
    print(f"Columns    : {columns:,}")

print()
print(f"Successfully loaded {len(REAL_DATASETS)} dataset(s).")

====================================================================================================
PART C4 — LOAD REAL DATASETS
====================================================================================================

Dataset    : Adult Income
Path       : /content/drive/MyDrive/SPP_GAN_Project/datasets/processed/adult_income_processed.csv
Rows       : 32,515
Columns    : 15

Dataset    : Bank Marketing
Path       : /content/drive/MyDrive/SPP_GAN_Project/datasets/processed/bank_marketing_processed.csv
Rows       : 45,211
Columns    : 17

Dataset    : diabetes_130us
Path       : /content/drive/MyDrive/SPP_GAN_Project/datasets/processed/diabetes_130us_processed.csv
Rows       : 101,766
Columns    : 48

Successfully loaded 3 dataset(s).

In [24]:
# ==============================================================================
# PART C5 — DATASET STRUCTURAL SUMMARY
# ==============================================================================

print("=" * 100)
print("PART C5 — DATASET STRUCTURAL SUMMARY")
print("=" * 100)

DATASET_SUMMARY = []

for dataset in DATASETS:
    df = REAL_DATASETS[dataset]

    numeric_columns = df.select_dtypes(include=np.number).columns
    non_numeric_columns = df.select_dtypes(exclude=np.number).columns

    DATASET_SUMMARY.append({
        "Dataset": dataset,
        "Rows": df.shape[0],
        "Columns": df.shape[1],
        "Numeric Features": len(numeric_columns),
        "Non-Numeric Features": len(non_numeric_columns),
        "Missing Values": int(df.isna().sum().sum()),
        "Duplicate Rows": int(df.duplicated().sum()),
    })

DATASET_SUMMARY_DF = pd.DataFrame(DATASET_SUMMARY)

display(DATASET_SUMMARY_DF)

====================================================================================================
PART C5 — DATASET STRUCTURAL SUMMARY
====================================================================================================

,Dataset,Rows,Columns,Numeric Features,Non-Numeric Features,Missing Values,Duplicate Rows
0,Adult Income,32515,15,15,0,0,0
1,Bank Marketing,45211,17,17,0,0,0
2,diabetes_130us,101766,48,48,0,0,0

In [25]:
# ==============================================================================
# PART C6 — DATA TYPE INSPECTION
# ==============================================================================

print("=" * 100)
print("PART C6 — DATA TYPE INSPECTION")
print("=" * 100)

DATA_TYPES = {}

for dataset in DATASETS:
    if dataset not in REAL_DATASETS:
        raise KeyError(
            f"Dataset '{dataset}' is not available in REAL_DATASETS."
        )

    df = REAL_DATASETS[dataset]

    DATA_TYPES[dataset] = df.dtypes.astype(str).to_dict()

    print()
    print("-" * 100)
    print(dataset)
    print("-" * 100)
    print(df.dtypes)

====================================================================================================
PART C6 — DATA TYPE INSPECTION
====================================================================================================

----------------------------------------------------------------------------------------------------
Adult Income
----------------------------------------------------------------------------------------------------
age               float64
workclass           int64
fnlwgt            float64
education           int64
education_num     float64
marital_status      int64
occupation          int64
relationship        int64
race                int64
sex                 int64
capital_gain      float64
capital_loss      float64
hours_per_week    float64
native_country      int64
income              int64
dtype: object

----------------------------------------------------------------------------------------------------
Bank Marketing
----------------------------------------------------------------------------------------------------
age          float64
job            int64
marital        int64
education      int64
default        int64
balance      float64
housing        int64
loan           int64
contact        int64
day          float64
month          int64
duration     float64
campaign     float64
pdays        float64
previous     float64
poutcome       int64
y              int64
dtype: object

----------------------------------------------------------------------------------------------------
diabetes_130us
----------------------------------------------------------------------------------------------------
race                          int64
gender                        int64
age                           int64
weight                        int64
admission_type_id           float64
discharge_disposition_id    float64
admission_source_id         float64
time_in_hospital            float64
payer_code                    int64
medical_specialty             int64
num_lab_procedures          float64
num_procedures              float64
num_medications             float64
number_outpatient           float64
number_emergency            float64
number_inpatient            float64
diag_1                        int64
diag_2                        int64
diag_3                        int64
number_diagnoses            float64
max_glu_serum                 int64
A1Cresult                     int64
metformin                     int64
repaglinide                   int64
nateglinide                   int64
chlorpropamide                int64
glimepiride                   int64
acetohexamide                 int64
glipizide                     int64
glyburide                     int64
tolbutamide                   int64
pioglitazone                  int64
rosiglitazone                 int64
acarbose                      int64
miglitol                      int64
troglitazone                  int64
tolazamide                    int64
examide                       int64
citoglipton                   int64
insulin                       int64
glyburide-metformin           int64
glipizide-metformin           int64
glimepiride-pioglitazone      int64
metformin-rosiglitazone       int64
metformin-pioglitazone        int64
change                        int64
diabetesMed                   int64
readmitted                    int64
dtype: object

In [26]:
# ==============================================================================
# PART C7 — FEATURE TYPE DETECTION
# ==============================================================================

print("=" * 100)
print("PART C7 — FEATURE TYPE DETECTION")
print("=" * 100)

NUMERIC_COLUMNS = {}
CATEGORICAL_COLUMNS = {}
OTHER_COLUMNS = {}

for dataset in DATASETS:
    df = REAL_DATASETS[dataset]

    numeric_columns = list(
        df.select_dtypes(include=np.number).columns
    )

    categorical_columns = list(
        df.select_dtypes(
            include=["object", "category", "string", "bool"]
        ).columns
    )

    other_columns = [
        column
        for column in df.columns
        if column not in numeric_columns
        and column not in categorical_columns
    ]

    NUMERIC_COLUMNS[dataset] = numeric_columns
    CATEGORICAL_COLUMNS[dataset] = categorical_columns
    OTHER_COLUMNS[dataset] = other_columns

    print()
    print(f"Dataset              : {dataset}")
    print(f"Numeric Features     : {len(numeric_columns)}")
    print(f"Categorical Features : {len(categorical_columns)}")
    print(f"Other Features       : {len(other_columns)}")

    if other_columns:
        print(f"Other Columns        : {other_columns}")

====================================================================================================
PART C7 — FEATURE TYPE DETECTION
====================================================================================================

Dataset              : Adult Income
Numeric Features     : 15
Categorical Features : 0
Other Features       : 0

Dataset              : Bank Marketing
Numeric Features     : 17
Categorical Features : 0
Other Features       : 0

Dataset              : diabetes_130us
Numeric Features     : 48
Categorical Features : 0
Other Features       : 0

In [27]:
# ==============================================================================
# PART C8 — DATASET COLUMN INVENTORY
# ==============================================================================

print("=" * 100)
print("PART C8 — DATASET COLUMN INVENTORY")
print("=" * 100)

COLUMN_INVENTORY = {}

for dataset in DATASETS:
    df = REAL_DATASETS[dataset]

    COLUMN_INVENTORY[dataset] = {
        "All Columns": list(df.columns),
        "Numeric Columns": NUMERIC_COLUMNS[dataset],
        "Categorical Columns": CATEGORICAL_COLUMNS[dataset],
        "Other Columns": OTHER_COLUMNS[dataset],
    }

    print()
    print("-" * 100)
    print(dataset)
    print("-" * 100)

    print(f"Total Columns: {len(df.columns)}")

    print()
    print("Numeric Columns:")

    for column in NUMERIC_COLUMNS[dataset]:
        print(f"  - {column}")

    print()
    print("Categorical Columns:")

    for column in CATEGORICAL_COLUMNS[dataset]:
        print(f"  - {column}")

    if OTHER_COLUMNS[dataset]:
        print()
        print("Other Columns:")

        for column in OTHER_COLUMNS[dataset]:
            print(f"  - {column}")

====================================================================================================
PART C8 — DATASET COLUMN INVENTORY
====================================================================================================

----------------------------------------------------------------------------------------------------
Adult Income
----------------------------------------------------------------------------------------------------
Total Columns: 15

Numeric Columns:
  - age
  - workclass
  - fnlwgt
  - education
  - education_num
  - marital_status
  - occupation
  - relationship
  - race
  - sex
  - capital_gain
  - capital_loss
  - hours_per_week
  - native_country
  - income

Categorical Columns:

----------------------------------------------------------------------------------------------------
Bank Marketing
----------------------------------------------------------------------------------------------------
Total Columns: 17

Numeric Columns:
  - age
  - job
  - marital
  - education
  - default
  - balance
  - housing
  - loan
  - contact
  - day
  - month
  - duration
  - campaign
  - pdays
  - previous
  - poutcome
  - y

Categorical Columns:

----------------------------------------------------------------------------------------------------
diabetes_130us
----------------------------------------------------------------------------------------------------
Total Columns: 48

Numeric Columns:
  - race
  - gender
  - age
  - weight
  - admission_type_id
  - discharge_disposition_id
  - admission_source_id
  - time_in_hospital
  - payer_code
  - medical_specialty
  - num_lab_procedures
  - num_procedures
  - num_medications
  - number_outpatient
  - number_emergency
  - number_inpatient
  - diag_1
  - diag_2
  - diag_3
  - number_diagnoses
  - max_glu_serum
  - A1Cresult
  - metformin
  - repaglinide
  - nateglinide
  - chlorpropamide
  - glimepiride
  - acetohexamide
  - glipizide
  - glyburide
  - tolbutamide
  - pioglitazone
  - rosiglitazone
  - acarbose
  - miglitol
  - troglitazone
  - tolazamide
  - examide
  - citoglipton
  - insulin
  - glyburide-metformin
  - glipizide-metformin
  - glimepiride-pioglitazone
  - metformin-rosiglitazone
  - metformin-pioglitazone
  - change
  - diabetesMed
  - readmitted

Categorical Columns:

In [28]:
# ==============================================================================
# PART C9 — DATA QUALITY VALIDATION
# ==============================================================================

print("=" * 100)
print("PART C9 — DATA QUALITY VALIDATION")
print("=" * 100)

DATA_QUALITY_RESULTS = {}

for dataset in DATASETS:
    df = REAL_DATASETS[dataset]

    rows, columns = df.shape
    total_cells = rows * columns

    missing_values = int(df.isna().sum().sum())
    duplicate_rows = int(df.duplicated().sum())

    missing_percentage = (
        (missing_values / total_cells) * 100
        if total_cells > 0
        else 0.0
    )

    duplicate_percentage = (
        (duplicate_rows / rows) * 100
        if rows > 0
        else 0.0
    )

    DATA_QUALITY_RESULTS[dataset] = {
        "Rows": rows,
        "Columns": columns,
        "Missing Values": missing_values,
        "Missing Percentage": missing_percentage,
        "Duplicate Rows": duplicate_rows,
        "Duplicate Percentage": duplicate_percentage,
    }

    print()
    print(f"Dataset              : {dataset}")
    print(f"Rows                 : {rows:,}")
    print(f"Columns              : {columns:,}")
    print(f"Missing Values       : {missing_values:,}")
    print(f"Missing Percentage   : {missing_percentage:.4f}%")
    print(f"Duplicate Rows       : {duplicate_rows:,}")
    print(f"Duplicate Percentage : {duplicate_percentage:.4f}%")

====================================================================================================
PART C9 — DATA QUALITY VALIDATION
====================================================================================================

Dataset              : Adult Income
Rows                 : 32,515
Columns              : 15
Missing Values       : 0
Missing Percentage   : 0.0000%
Duplicate Rows       : 0
Duplicate Percentage : 0.0000%

Dataset              : Bank Marketing
Rows                 : 45,211
Columns              : 17
Missing Values       : 0
Missing Percentage   : 0.0000%
Duplicate Rows       : 0
Duplicate Percentage : 0.0000%

Dataset              : diabetes_130us
Rows                 : 101,766
Columns              : 48
Missing Values       : 0
Missing Percentage   : 0.0000%
Duplicate Rows       : 0
Duplicate Percentage : 0.0000%

In [29]:
# ==============================================================================
# PART C10 — DATASET PREVIEW
# ==============================================================================

print("=" * 100)
print("PART C10 — DATASET PREVIEW")
print("=" * 100)

for dataset in DATASETS:
    print()
    print("-" * 100)
    print(dataset)
    print("-" * 100)

    display(REAL_DATASETS[dataset].head())

====================================================================================================
PART C10 — DATASET PREVIEW
====================================================================================================

----------------------------------------------------------------------------------------------------
Adult Income
----------------------------------------------------------------------------------------------------

,age,workclass,fnlwgt,education,education_num,marital_status,occupation,relationship,race,sex,capital_gain,capital_loss,hours_per_week,native_country,income
0,0.360656,7,0.161680,9,0.739130,4,1,1,4,1,0.02174,0.0,0.375,39,0
1,0.540984,6,0.176044,9,0.739130,2,4,0,4,1,0.00000,0.0,0.000,39,0
2,0.344262,4,0.504046,11,0.391304,0,6,1,4,1,0.00000,0.0,0.375,39,0
3,0.590164,4,0.551325,1,0.217391,2,6,0,2,1,0.00000,0.0,0.375,39,0
4,0.180328,4,0.808324,9,0.739130,2,10,5,2,0,0.00000,0.0,0.375,5,0

----------------------------------------------------------------------------------------------------
Bank Marketing
----------------------------------------------------------------------------------------------------

,age,job,marital,education,default,balance,housing,loan,contact,day,month,duration,campaign,pdays,previous,poutcome,y
0,0.761905,4,1,2,0,0.756822,1,0,2,0.133333,8,0.405910,0.0,0.0,0.0,3,0
1,0.495238,9,2,1,0,0.367072,1,0,2,0.133333,8,0.234837,0.0,0.0,0.0,3,0
2,0.285714,2,1,1,0,0.362094,1,1,2,0.133333,8,0.118196,0.0,0.0,0.0,3,0
3,0.552381,1,1,3,0,0.639381,1,0,2,0.133333,8,0.143079,0.0,0.0,0.0,3,0
4,0.285714,11,2,3,0,0.361910,0,0,2,0.133333,8,0.307932,0.0,0.0,0.0,3,0

----------------------------------------------------------------------------------------------------
diabetes_130us
----------------------------------------------------------------------------------------------------

,race,gender,age,weight,admission_type_id,discharge_disposition_id,admission_source_id,time_in_hospital,payer_code,medical_specialty,...,citoglipton,insulin,glyburide-metformin,glipizide-metformin,glimepiride-pioglitazone,metformin-rosiglitazone,metformin-pioglitazone,change,diabetesMed,readmitted
0,2,0,0,8,1.0,1.0,0.0,0.000000,7,37,...,0,1,1,0,0,0,0,1,0,2
1,2,0,1,8,0.0,0.0,0.4,0.181818,7,18,...,0,3,1,0,0,0,0,0,1,1
2,0,0,2,8,0.0,0.0,0.4,0.090909,7,18,...,0,1,1,0,0,0,0,1,1,2
3,2,1,3,8,0.0,0.0,0.4,0.090909,7,18,...,0,3,1,0,0,0,0,0,1,2
4,2,1,4,8,0.0,0.0,0.4,0.000000,7,18,...,0,2,1,0,0,0,0,0,1,2

In [30]:
# ==============================================================================
# PART D1 — DATASET PREPARATION CONFIGURATION
# ==============================================================================

print("=" * 100)
print("PART D1 — DATASET PREPARATION CONFIGURATION")
print("=" * 100)

SPLIT_SEED = int(SEED)

TRAIN_SIZE = 0.70
VALIDATION_SIZE = 0.15
TEST_SIZE = 0.15

SPLIT_RATIOS = {
    "Training": TRAIN_SIZE,
    "Validation": VALIDATION_SIZE,
    "Testing": TEST_SIZE,
}

if any(
    ratio <= 0
    for ratio in SPLIT_RATIOS.values()
):
    raise ValueError(
        "Train, validation, and test proportions must all be greater than 0."
    )

if not np.isclose(
    sum(SPLIT_RATIOS.values()),
    1.0
):
    raise ValueError(
        "Train, validation, and test proportions must sum to 1.0."
    )

print(f"Training Ratio   : {TRAIN_SIZE:.2f}")
print(f"Validation Ratio : {VALIDATION_SIZE:.2f}")
print(f"Testing Ratio    : {TEST_SIZE:.2f}")
print(f"Split Seed       : {SPLIT_SEED}")

====================================================================================================
PART D1 — DATASET PREPARATION CONFIGURATION
====================================================================================================
Training Ratio   : 0.70
Validation Ratio : 0.15
Testing Ratio    : 0.15
Split Seed       : 42

In [31]:
# ==============================================================================
# PART D2 — TARGET VARIABLE CONFIGURATION
# ==============================================================================

print("=" * 100)
print("PART D2 — TARGET VARIABLE CONFIGURATION")
print("=" * 100)

TARGET_CANDIDATES = {
    "Adult Income": [
        "income",
        "target",
        "class",
        "label",
        "income_target",
    ],
    "Bank Marketing": [
        "y",
        "target",
        "class",
        "label",
        "deposit",
    ],
    "diabetes_130us": [
        "readmitted",
        "target",
        "class",
        "label",
    ],
}

TARGET_COLUMNS = {}
TARGET_DETECTION_RESULTS = {}

for dataset in DATASETS:
    if dataset not in REAL_DATASETS:
        raise KeyError(
            f"Dataset '{dataset}' is not available in REAL_DATASETS."
        )

    df = REAL_DATASETS[dataset]

    if dataset not in TARGET_CANDIDATES:
        raise KeyError(
            f"No target candidates configured for dataset '{dataset}'."
        )

    detected_candidates = [
        column
        for column in TARGET_CANDIDATES[dataset]
        if column in df.columns
    ]

    TARGET_DETECTION_RESULTS[dataset] = detected_candidates

    print()
    print(f"Dataset                  : {dataset}")
    print(f"Candidate Target Columns : {detected_candidates}")

    if len(detected_candidates) == 1:
        TARGET_COLUMNS[dataset] = detected_candidates[0]
        print(f"Selected Target          : {detected_candidates[0]}")

    elif len(detected_candidates) == 0:
        TARGET_COLUMNS[dataset] = None
        print("Selected Target          : NOT FOUND")

    else:
        TARGET_COLUMNS[dataset] = None
        print("Selected Target          : AMBIGUOUS")

print()
print("-" * 100)
print("TARGET CONFIGURATION")
print("-" * 100)

for dataset in DATASETS:
    target = TARGET_COLUMNS[dataset]
    print(f"{dataset:25s}: {target}")

INVALID_TARGET_DATASETS = [
    dataset
    for dataset in DATASETS
    if TARGET_COLUMNS[dataset] is None
]

if INVALID_TARGET_DATASETS:
    raise ValueError(
        "Target variable configuration failed for: "
        + ", ".join(INVALID_TARGET_DATASETS)
    )

print()
print("All target variables were identified uniquely.")

====================================================================================================
PART D2 — TARGET VARIABLE CONFIGURATION
====================================================================================================

Dataset                  : Adult Income
Candidate Target Columns : ['income']
Selected Target          : income

Dataset                  : Bank Marketing
Candidate Target Columns : ['y']
Selected Target          : y

Dataset                  : diabetes_130us
Candidate Target Columns : ['readmitted']
Selected Target          : readmitted

----------------------------------------------------------------------------------------------------
TARGET CONFIGURATION
----------------------------------------------------------------------------------------------------
Adult Income             : income
Bank Marketing           : y
diabetes_130us           : readmitted

All target variables were identified uniquely.

In [32]:
# ==============================================================================
# PART D3 — FEATURE AND TARGET SEPARATION
# ==============================================================================

print("=" * 100)
print("PART D3 — FEATURE AND TARGET SEPARATION")
print("=" * 100)

FEATURE_DATASETS = {}
TARGET_DATASETS = {}

for dataset in DATASETS:
    df = REAL_DATASETS[dataset]
    target_column = TARGET_COLUMNS.get(dataset)

    if target_column is None:
        raise ValueError(
            f"No valid target column configured for '{dataset}'."
        )

    if target_column not in df.columns:
        raise KeyError(
            f"Target column '{target_column}' was not found in "
            f"dataset '{dataset}'."
        )

    FEATURE_DATASETS[dataset] = df.drop(
        columns=[target_column]
    ).copy()

    TARGET_DATASETS[dataset] = df[target_column].copy()

    print()
    print(f"Dataset       : {dataset}")
    print(f"Target Column : {target_column}")
    print(f"Features      : {FEATURE_DATASETS[dataset].shape}")
    print(f"Target        : {TARGET_DATASETS[dataset].shape}")

====================================================================================================
PART D3 — FEATURE AND TARGET SEPARATION
====================================================================================================

Dataset       : Adult Income
Target Column : income
Features      : (32515, 14)
Target        : (32515,)

Dataset       : Bank Marketing
Target Column : y
Features      : (45211, 16)
Target        : (45211,)

Dataset       : diabetes_130us
Target Column : readmitted
Features      : (101766, 47)
Target        : (101766,)

In [33]:
# ==============================================================================
# PART D4 — TRAIN / VALIDATION / TEST SPLITTING
# ==============================================================================

print("=" * 100)
print("PART D4 — TRAIN / VALIDATION / TEST SPLITTING")
print("=" * 100)

TRAIN_DATASETS = {}
VALIDATION_DATASETS = {}
TEST_DATASETS = {}

TRAIN_ROW_IDS = {}
VALIDATION_ROW_IDS = {}
TEST_ROW_IDS = {}

for dataset in DATASETS:
    df = REAL_DATASETS[dataset].copy()
    target_column = TARGET_COLUMNS[dataset]

    if target_column is None:
        raise ValueError(
            f"No target column configured for '{dataset}'."
        )

    if target_column not in df.columns:
        raise KeyError(
            f"Target column '{target_column}' not found in '{dataset}'."
        )

    if df[target_column].isna().any():
        raise ValueError(
            f"Target column '{target_column}' contains missing values "
            f"in dataset '{dataset}'."
        )

    df["_ORIGINAL_ROW_ID_"] = np.arange(len(df))

    train_df, temp_df = train_test_split(
        df,
        test_size=VALIDATION_SIZE + TEST_SIZE,
        random_state=SPLIT_SEED,
        stratify=df[target_column]
    )

    relative_test_size = (
        TEST_SIZE / (VALIDATION_SIZE + TEST_SIZE)
    )

    validation_df, test_df = train_test_split(
        temp_df,
        test_size=relative_test_size,
        random_state=SPLIT_SEED,
        stratify=temp_df[target_column]
    )

    TRAIN_ROW_IDS[dataset] = set(
        train_df["_ORIGINAL_ROW_ID_"]
    )

    VALIDATION_ROW_IDS[dataset] = set(
        validation_df["_ORIGINAL_ROW_ID_"]
    )

    TEST_ROW_IDS[dataset] = set(
        test_df["_ORIGINAL_ROW_ID_"]
    )

    train_df = train_df.drop(
        columns=["_ORIGINAL_ROW_ID_"]
    )

    validation_df = validation_df.drop(
        columns=["_ORIGINAL_ROW_ID_"]
    )

    test_df = test_df.drop(
        columns=["_ORIGINAL_ROW_ID_"]
    )

    TRAIN_DATASETS[dataset] = train_df.reset_index(drop=True)
    VALIDATION_DATASETS[dataset] = validation_df.reset_index(drop=True)
    TEST_DATASETS[dataset] = test_df.reset_index(drop=True)

    print()
    print(f"Dataset     : {dataset}")
    print(f"Training    : {len(TRAIN_DATASETS[dataset]):,}")
    print(f"Validation  : {len(VALIDATION_DATASETS[dataset]):,}")
    print(f"Testing     : {len(TEST_DATASETS[dataset]):,}")

====================================================================================================
PART D4 — TRAIN / VALIDATION / TEST SPLITTING
====================================================================================================

Dataset     : Adult Income
Training    : 22,760
Validation  : 4,877
Testing     : 4,878

Dataset     : Bank Marketing
Training    : 31,647
Validation  : 6,782
Testing     : 6,782

Dataset     : diabetes_130us
Training    : 71,236
Validation  : 15,265
Testing     : 15,265

In [34]:
# ==============================================================================
# PART D5 — SPLIT SIZE AND PARTITION VERIFICATION
# ==============================================================================

print("=" * 100)
print("PART D5 — SPLIT SIZE AND PARTITION VERIFICATION")
print("=" * 100)

SPLIT_VERIFICATION = {}

for dataset in DATASETS:
    original_rows = len(REAL_DATASETS[dataset])

    train_rows = len(TRAIN_DATASETS[dataset])
    validation_rows = len(VALIDATION_DATASETS[dataset])
    test_rows = len(TEST_DATASETS[dataset])

    total_split_rows = (
        train_rows
        + validation_rows
        + test_rows
    )

    expected_train_rows = original_rows * TRAIN_SIZE
    expected_validation_rows = original_rows * VALIDATION_SIZE
    expected_test_rows = original_rows * TEST_SIZE

    train_ids = TRAIN_ROW_IDS[dataset]
    validation_ids = VALIDATION_ROW_IDS[dataset]
    test_ids = TEST_ROW_IDS[dataset]

    no_train_validation_overlap = (
        train_ids.isdisjoint(validation_ids)
    )

    no_train_test_overlap = (
        train_ids.isdisjoint(test_ids)
    )

    no_validation_test_overlap = (
        validation_ids.isdisjoint(test_ids)
    )

    all_rows_accounted_for = (
        len(train_ids | validation_ids | test_ids)
        == original_rows
    )

    size_check = (
        total_split_rows == original_rows
    )

    proportion_check = (
        np.isclose(
            train_rows / original_rows,
            TRAIN_SIZE,
            atol=1 / original_rows
        )
        and
        np.isclose(
            validation_rows / original_rows,
            VALIDATION_SIZE,
            atol=1 / original_rows
        )
        and
        np.isclose(
            test_rows / original_rows,
            TEST_SIZE,
            atol=1 / original_rows
        )
    )

    dataset_checks = {
        "Total Rows Match": size_check,
        "Train Proportion": proportion_check,
        "Train/Validation Disjoint": no_train_validation_overlap,
        "Train/Test Disjoint": no_train_test_overlap,
        "Validation/Test Disjoint": no_validation_test_overlap,
        "All Rows Accounted For": all_rows_accounted_for,
    }

    SPLIT_VERIFICATION[dataset] = dataset_checks

    print()
    print("-" * 100)
    print(dataset)
    print("-" * 100)

    print(f"Original Rows     : {original_rows:,}")
    print(f"Training Rows     : {train_rows:,}")
    print(f"Validation Rows   : {validation_rows:,}")
    print(f"Testing Rows      : {test_rows:,}")
    print(f"Total Split Rows  : {total_split_rows:,}")

    print()
    print(f"Expected Train    : {expected_train_rows:,.2f}")
    print(f"Expected Valid.   : {expected_validation_rows:,.2f}")
    print(f"Expected Test     : {expected_test_rows:,.2f}")

    print()
    for check, status in dataset_checks.items():
        print(
            f"{check:35s}: "
            f"{'PASS' if status else 'FAIL'}"
        )

FAILED_SPLIT_CHECKS = {
    dataset: [
        check
        for check, status in checks.items()
        if not status
    ]
    for dataset, checks in SPLIT_VERIFICATION.items()
    if not all(checks.values())
}

print()
print("=" * 100)
print("SPLIT VERIFICATION SUMMARY")
print("=" * 100)

for dataset, checks in SPLIT_VERIFICATION.items():
    passed = sum(checks.values())
    total = len(checks)

    print(
        f"{dataset:25s}: "
        f"{passed}/{total} checks passed"
    )

if FAILED_SPLIT_CHECKS:
    raise RuntimeError(
        "Dataset split verification failed:\n"
        + "\n".join(
            f"{dataset}: {', '.join(checks)}"
            for dataset, checks in FAILED_SPLIT_CHECKS.items()
        )
    )

print()
print("All dataset split checks passed successfully.")

====================================================================================================
PART D5 — SPLIT SIZE AND PARTITION VERIFICATION
====================================================================================================

----------------------------------------------------------------------------------------------------
Adult Income
----------------------------------------------------------------------------------------------------
Original Rows     : 32,515
Training Rows     : 22,760
Validation Rows   : 4,877
Testing Rows      : 4,878
Total Split Rows  : 32,515

Expected Train    : 22,760.50
Expected Valid.   : 4,877.25
Expected Test     : 4,877.25

Total Rows Match                   : PASS
Train Proportion                   : PASS
Train/Validation Disjoint          : PASS
Train/Test Disjoint                : PASS
Validation/Test Disjoint           : PASS
All Rows Accounted For             : PASS

----------------------------------------------------------------------------------------------------
Bank Marketing
----------------------------------------------------------------------------------------------------
Original Rows     : 45,211
Training Rows     : 31,647
Validation Rows   : 6,782
Testing Rows      : 6,782
Total Split Rows  : 45,211

Expected Train    : 31,647.70
Expected Valid.   : 6,781.65
Expected Test     : 6,781.65

Total Rows Match                   : PASS
Train Proportion                   : PASS
Train/Validation Disjoint          : PASS
Train/Test Disjoint                : PASS
Validation/Test Disjoint           : PASS
All Rows Accounted For             : PASS

----------------------------------------------------------------------------------------------------
diabetes_130us
----------------------------------------------------------------------------------------------------
Original Rows     : 101,766
Training Rows     : 71,236
Validation Rows   : 15,265
Testing Rows      : 15,265
Total Split Rows  : 101,766

Expected Train    : 71,236.20
Expected Valid.   : 15,264.90
Expected Test     : 15,264.90

Total Rows Match                   : PASS
Train Proportion                   : PASS
Train/Validation Disjoint          : PASS
Train/Test Disjoint                : PASS
Validation/Test Disjoint           : PASS
All Rows Accounted For             : PASS

====================================================================================================
SPLIT VERIFICATION SUMMARY
====================================================================================================
Adult Income             : 6/6 checks passed
Bank Marketing           : 6/6 checks passed
diabetes_130us           : 6/6 checks passed

All dataset split checks passed successfully.

In [35]:
# ==============================================================================
# PART D6 — DATA LEAKAGE VERIFICATION
# ==============================================================================

print("=" * 100)
print("PART D6 — DATA LEAKAGE VERIFICATION")
print("=" * 100)

LEAKAGE_VERIFICATION = {}

for dataset in DATASETS:
    train_ids = TRAIN_ROW_IDS[dataset]
    validation_ids = VALIDATION_ROW_IDS[dataset]
    test_ids = TEST_ROW_IDS[dataset]

    train_validation_overlap = (
        train_ids & validation_ids
    )

    train_test_overlap = (
        train_ids & test_ids
    )

    validation_test_overlap = (
        validation_ids & test_ids
    )

    expected_ids = set(
        range(len(REAL_DATASETS[dataset]))
    )

    all_split_ids = (
        train_ids
        | validation_ids
        | test_ids
    )

    no_overlap = (
        not train_validation_overlap
        and not train_test_overlap
        and not validation_test_overlap
    )

    complete_partition = (
        all_split_ids == expected_ids
    )

    leakage_free = (
        no_overlap
        and complete_partition
    )

    LEAKAGE_VERIFICATION[dataset] = {
        "Train/Validation Overlap": not train_validation_overlap,
        "Train/Test Overlap": not train_test_overlap,
        "Validation/Test Overlap": not validation_test_overlap,
        "Complete Partition": complete_partition,
        "Leakage Free": leakage_free,
    }

    print()
    print("-" * 100)
    print(dataset)
    print("-" * 100)

    print(
        f"Train ↔ Validation : "
        f"{len(train_validation_overlap)}"
    )

    print(
        f"Train ↔ Test       : "
        f"{len(train_test_overlap)}"
    )

    print(
        f"Validation ↔ Test  : "
        f"{len(validation_test_overlap)}"
    )

    print(
        f"Complete Partition : "
        f"{'PASS' if complete_partition else 'FAIL'}"
    )

    print(
        f"Leakage Check      : "
        f"{'PASS' if leakage_free else 'FAIL'}"
    )

FAILED_LEAKAGE_CHECKS = {
    dataset: [
        check
        for check, status in checks.items()
        if not status
    ]
    for dataset, checks in LEAKAGE_VERIFICATION.items()
    if not all(checks.values())
}

print()
print("=" * 100)
print("DATA LEAKAGE VERIFICATION SUMMARY")
print("=" * 100)

for dataset, checks in LEAKAGE_VERIFICATION.items():
    passed = sum(checks.values())
    total = len(checks)

    print(
        f"{dataset:25s}: "
        f"{passed}/{total} checks passed"
    )

if FAILED_LEAKAGE_CHECKS:
    raise RuntimeError(
        "Data leakage was detected between dataset splits:\n"
        + "\n".join(
            f"{dataset}: {', '.join(checks)}"
            for dataset, checks in FAILED_LEAKAGE_CHECKS.items()
        )
    )

print()
print("All datasets passed the data leakage verification.")

====================================================================================================
PART D6 — DATA LEAKAGE VERIFICATION
====================================================================================================

----------------------------------------------------------------------------------------------------
Adult Income
----------------------------------------------------------------------------------------------------
Train ↔ Validation : 0
Train ↔ Test       : 0
Validation ↔ Test  : 0
Complete Partition : PASS
Leakage Check      : PASS

----------------------------------------------------------------------------------------------------
Bank Marketing
----------------------------------------------------------------------------------------------------
Train ↔ Validation : 0
Train ↔ Test       : 0
Validation ↔ Test  : 0
Complete Partition : PASS
Leakage Check      : PASS

----------------------------------------------------------------------------------------------------
diabetes_130us
----------------------------------------------------------------------------------------------------
Train ↔ Validation : 0
Train ↔ Test       : 0
Validation ↔ Test  : 0
Complete Partition : PASS
Leakage Check      : PASS

====================================================================================================
DATA LEAKAGE VERIFICATION SUMMARY
====================================================================================================
Adult Income             : 5/5 checks passed
Bank Marketing           : 5/5 checks passed
diabetes_130us           : 5/5 checks passed

All datasets passed the data leakage verification.

In [36]:
# ==============================================================================
# PART D7 — TRAINING FEATURE TYPE IDENTIFICATION
# ==============================================================================

print("=" * 100)
print("PART D7 — TRAINING FEATURE TYPE IDENTIFICATION")
print("=" * 100)

TRAIN_NUMERIC_COLUMNS = {}
TRAIN_CATEGORICAL_COLUMNS = {}

for dataset in DATASETS:
    train_df = TRAIN_DATASETS[dataset]
    target_column = TARGET_COLUMNS[dataset]

    if target_column is None:
        raise ValueError(
            f"No target column configured for '{dataset}'."
        )

    if target_column not in train_df.columns:
        raise KeyError(
            f"Target column '{target_column}' not found in "
            f"training dataset '{dataset}'."
        )

    feature_df = train_df.drop(
        columns=[target_column]
    )

    TRAIN_NUMERIC_COLUMNS[dataset] = list(
        feature_df.select_dtypes(
            include=np.number
        ).columns
    )

    TRAIN_CATEGORICAL_COLUMNS[dataset] = list(
        feature_df.select_dtypes(
            exclude=np.number
        ).columns
    )

    print()
    print(f"Dataset              : {dataset}")
    print(
        f"Numeric Features     : "
        f"{len(TRAIN_NUMERIC_COLUMNS[dataset])}"
    )
    print(
        f"Categorical Features : "
        f"{len(TRAIN_CATEGORICAL_COLUMNS[dataset])}"
    )

====================================================================================================
PART D7 — TRAINING FEATURE TYPE IDENTIFICATION
====================================================================================================

Dataset              : Adult Income
Numeric Features     : 14
Categorical Features : 0

Dataset              : Bank Marketing
Numeric Features     : 16
Categorical Features : 0

Dataset              : diabetes_130us
Numeric Features     : 47
Categorical Features : 0

In [37]:
# ==============================================================================
# PART D8 — NUMERICAL FEATURE PREPARATION
# ==============================================================================

print("=" * 100)
print("PART D8 — NUMERICAL FEATURE PREPARATION")
print("=" * 100)

NUMERIC_SCALERS = {}

SCALED_NUMERIC_DATASETS = {}
SCALED_VALIDATION_NUMERIC_DATASETS = {}
SCALED_TEST_NUMERIC_DATASETS = {}

for dataset in DATASETS:
    train_df = TRAIN_DATASETS[dataset]
    validation_df = VALIDATION_DATASETS[dataset]
    test_df = TEST_DATASETS[dataset]

    numeric_columns = TRAIN_NUMERIC_COLUMNS[dataset]

    if not numeric_columns:
        print()
        print(f"{dataset}: No numeric features detected. Skipping scaling.")
        NUMERIC_SCALERS[dataset] = None
        SCALED_NUMERIC_DATASETS[dataset] = pd.DataFrame(
            index=train_df.index
        )
        SCALED_VALIDATION_NUMERIC_DATASETS[dataset] = pd.DataFrame(
            index=validation_df.index
        )
        SCALED_TEST_NUMERIC_DATASETS[dataset] = pd.DataFrame(
            index=test_df.index
        )
        continue

    missing_train_columns = [
        column
        for column in numeric_columns
        if column not in train_df.columns
    ]

    missing_validation_columns = [
        column
        for column in numeric_columns
        if column not in validation_df.columns
    ]

    missing_test_columns = [
        column
        for column in numeric_columns
        if column not in test_df.columns
    ]

    if missing_train_columns:
        raise KeyError(
            f"Numeric columns missing from training data for "
            f"'{dataset}': {missing_train_columns}"
        )

    if missing_validation_columns:
        raise KeyError(
            f"Numeric columns missing from validation data for "
            f"'{dataset}': {missing_validation_columns}"
        )

    if missing_test_columns:
        raise KeyError(
            f"Numeric columns missing from test data for "
            f"'{dataset}': {missing_test_columns}"
        )

    scaler = StandardScaler()

    train_numeric = train_df[numeric_columns]
    validation_numeric = validation_df[numeric_columns]
    test_numeric = test_df[numeric_columns]

    # Fit ONLY on training data.
    scaler.fit(train_numeric)

    NUMERIC_SCALERS[dataset] = scaler

    # Transform all splits using the training-fitted scaler.
    train_scaled = scaler.transform(train_numeric)
    validation_scaled = scaler.transform(validation_numeric)
    test_scaled = scaler.transform(test_numeric)

    SCALED_NUMERIC_DATASETS[dataset] = pd.DataFrame(
        train_scaled,
        columns=numeric_columns,
        index=train_df.index
    )

    SCALED_VALIDATION_NUMERIC_DATASETS[dataset] = pd.DataFrame(
        validation_scaled,
        columns=numeric_columns,
        index=validation_df.index
    )

    SCALED_TEST_NUMERIC_DATASETS[dataset] = pd.DataFrame(
        test_scaled,
        columns=numeric_columns,
        index=test_df.index
    )

    print()
    print(f"Dataset              : {dataset}")
    print(f"Numeric Features     : {len(numeric_columns)}")
    print(f"Training Shape       : {train_scaled.shape}")
    print(f"Validation Shape     : {validation_scaled.shape}")
    print(f"Testing Shape        : {test_scaled.shape}")
    print("Scaler Fit           : Training data only")

====================================================================================================
PART D8 — NUMERICAL FEATURE PREPARATION
====================================================================================================

Dataset              : Adult Income
Numeric Features     : 14
Training Shape       : (22760, 14)
Validation Shape     : (4877, 14)
Testing Shape        : (4878, 14)
Scaler Fit           : Training data only

Dataset              : Bank Marketing
Numeric Features     : 16
Training Shape       : (31647, 16)
Validation Shape     : (6782, 16)
Testing Shape        : (6782, 16)
Scaler Fit           : Training data only

Dataset              : diabetes_130us
Numeric Features     : 47
Training Shape       : (71236, 47)
Validation Shape     : (15265, 47)
Testing Shape        : (15265, 47)
Scaler Fit           : Training data only

In [38]:
# ==============================================================================
# PART D9 — CATEGORICAL FEATURE DOMAIN PREPARATION
# ==============================================================================

print("=" * 100)
print("PART D9 — CATEGORICAL FEATURE DOMAIN PREPARATION")
print("=" * 100)

CATEGORICAL_DOMAINS = {}

for dataset in DATASETS:
    train_df = TRAIN_DATASETS[dataset]
    validation_df = VALIDATION_DATASETS[dataset]
    test_df = TEST_DATASETS[dataset]

    categorical_columns = TRAIN_CATEGORICAL_COLUMNS[dataset]

    CATEGORICAL_DOMAINS[dataset] = {}

    for column in categorical_columns:
        if column not in train_df.columns:
            raise KeyError(
                f"Categorical column '{column}' not found in "
                f"training dataset '{dataset}'."
            )

        if column not in validation_df.columns:
            raise KeyError(
                f"Categorical column '{column}' not found in "
                f"validation dataset '{dataset}'."
            )

        if column not in test_df.columns:
            raise KeyError(
                f"Categorical column '{column}' not found in "
                f"test dataset '{dataset}'."
            )

        categories = (
            train_df[column]
            .astype("string")
            .fillna("__MISSING__")
            .unique()
            .tolist()
        )

        categories = sorted(
            categories,
            key=lambda value: str(value)
        )

        if "__MISSING__" not in categories:
            categories.append("__MISSING__")

        CATEGORICAL_DOMAINS[dataset][column] = categories

    print()
    print(f"Dataset: {dataset}")

    if not categorical_columns:
        print("Categorical Features: 0")
        continue

    for column, categories in CATEGORICAL_DOMAINS[dataset].items():
        print(
            f"{column:30s}: "
            f"{len(categories)} categories"
        )

====================================================================================================
PART D9 — CATEGORICAL FEATURE DOMAIN PREPARATION
====================================================================================================

Dataset: Adult Income
Categorical Features: 0

Dataset: Bank Marketing
Categorical Features: 0

Dataset: diabetes_130us
Categorical Features: 0

In [39]:
# ==============================================================================
# PART D10 — MISSING VALUE PREPARATION
# ==============================================================================

print("=" * 100)
print("PART D10 — MISSING VALUE PREPARATION")
print("=" * 100)

NUMERIC_IMPUTATION_VALUES = {}
CATEGORICAL_MISSING_TOKEN = "__MISSING__"

for dataset in DATASETS:
    train_df = TRAIN_DATASETS[dataset]

    numeric_columns = TRAIN_NUMERIC_COLUMNS[dataset]

    NUMERIC_IMPUTATION_VALUES[dataset] = {}

    if not numeric_columns:
        print()
        print(f"{dataset}: No numeric features require imputation.")
        continue

    for column in numeric_columns:
        if column not in train_df.columns:
            raise KeyError(
                f"Numeric column '{column}' not found in "
                f"training dataset '{dataset}'."
            )

        median_value = train_df[column].median()

        if pd.isna(median_value) or not np.isfinite(median_value):
            raise ValueError(
                f"Invalid median imputation value for column "
                f"'{column}' in dataset '{dataset}'."
            )

        NUMERIC_IMPUTATION_VALUES[dataset][column] = float(
            median_value
        )

    print()
    print(
        f"{dataset}: "
        f"{len(numeric_columns)} numeric imputation values calculated."
    )

print()
print(
    f"Categorical Missing Token: "
    f"{CATEGORICAL_MISSING_TOKEN}"
)

====================================================================================================
PART D10 — MISSING VALUE PREPARATION
====================================================================================================

Adult Income: 14 numeric imputation values calculated.

Bank Marketing: 16 numeric imputation values calculated.

diabetes_130us: 47 numeric imputation values calculated.

Categorical Missing Token: __MISSING__

In [40]:
# ==============================================================================
# PART D11 — FEATURE METADATA CONSTRUCTION
# ==============================================================================

print("=" * 100)
print("PART D11 — FEATURE METADATA CONSTRUCTION")
print("=" * 100)

FEATURE_METADATA = {}

for dataset in DATASETS:
    target_column = TARGET_COLUMNS[dataset]
    numeric_columns = TRAIN_NUMERIC_COLUMNS[dataset]
    categorical_columns = TRAIN_CATEGORICAL_COLUMNS[dataset]

    if target_column is None:
        raise ValueError(
            f"Target column is not configured for '{dataset}'."
        )

    if not isinstance(numeric_columns, list):
        raise TypeError(
            f"Numeric column metadata for '{dataset}' must be a list."
        )

    if not isinstance(categorical_columns, list):
        raise TypeError(
            f"Categorical column metadata for '{dataset}' must be a list."
        )

    if set(numeric_columns) & set(categorical_columns):
        raise ValueError(
            f"Feature type overlap detected in '{dataset}'."
        )

    feature_metadata = {
        "target_column": target_column,
        "numeric_columns": numeric_columns.copy(),
        "categorical_columns": categorical_columns.copy(),
        "categorical_domains": {
            column: categories.copy()
            for column, categories
            in CATEGORICAL_DOMAINS[dataset].items()
        },
        "numeric_imputation_values": (
            NUMERIC_IMPUTATION_VALUES[dataset].copy()
        ),
        "categorical_missing_token": CATEGORICAL_MISSING_TOKEN,
    }

    FEATURE_METADATA[dataset] = feature_metadata

    print()
    print(f"Dataset             : {dataset}")
    print(
        f"Target Column       : "
        f"{feature_metadata['target_column']}"
    )
    print(
        f"Numeric Features    : "
        f"{len(feature_metadata['numeric_columns'])}"
    )
    print(
        f"Categorical Features: "
        f"{len(feature_metadata['categorical_columns'])}"
    )

====================================================================================================
PART D11 — FEATURE METADATA CONSTRUCTION
====================================================================================================

Dataset             : Adult Income
Target Column       : income
Numeric Features    : 14
Categorical Features: 0

Dataset             : Bank Marketing
Target Column       : y
Numeric Features    : 16
Categorical Features: 0

Dataset             : diabetes_130us
Target Column       : readmitted
Numeric Features    : 47
Categorical Features: 0

In [41]:
# ==============================================================================
# PART D12 — DATASET SPLIT SUMMARY
# ==============================================================================

print("=" * 100)
print("PART D12 — DATASET SPLIT SUMMARY")
print("=" * 100)

SPLIT_SUMMARY = []

for dataset in DATASETS:
    original_rows = len(REAL_DATASETS[dataset])
    train_rows = len(TRAIN_DATASETS[dataset])
    validation_rows = len(VALIDATION_DATASETS[dataset])
    test_rows = len(TEST_DATASETS[dataset])

    if original_rows == 0:
        raise ValueError(
            f"Dataset '{dataset}' contains zero rows."
        )

    total_split_rows = (
        train_rows
        + validation_rows
        + test_rows
    )

    if total_split_rows != original_rows:
        raise ValueError(
            f"Split row count mismatch for '{dataset}': "
            f"{total_split_rows} != {original_rows}"
        )

    SPLIT_SUMMARY.append({
        "Dataset": dataset,
        "Original Rows": original_rows,
        "Training Rows": train_rows,
        "Validation Rows": validation_rows,
        "Test Rows": test_rows,
        "Training %": round(
            train_rows / original_rows * 100,
            2
        ),
        "Validation %": round(
            validation_rows / original_rows * 100,
            2
        ),
        "Test %": round(
            test_rows / original_rows * 100,
            2
        ),
        "Numeric Features": len(
            TRAIN_NUMERIC_COLUMNS[dataset]
        ),
        "Categorical Features": len(
            TRAIN_CATEGORICAL_COLUMNS[dataset]
        ),
    })

SPLIT_SUMMARY_DF = pd.DataFrame(SPLIT_SUMMARY)

display(SPLIT_SUMMARY_DF)

====================================================================================================
PART D12 — DATASET SPLIT SUMMARY
====================================================================================================

,Dataset,Original Rows,Training Rows,Validation Rows,Test Rows,Training %,Validation %,Test %,Numeric Features,Categorical Features
0,Adult Income,32515,22760,4877,4878,70.0,15.0,15.0,14,0
1,Bank Marketing,45211,31647,6782,6782,70.0,15.0,15.0,16,0
2,diabetes_130us,101766,71236,15265,15265,70.0,15.0,15.0,47,0

In [42]:
# ==============================================================================
# PART D13 — DATASET AND FEATURE PREPARATION VERIFICATION
# ==============================================================================

print("=" * 100)
print("PART D13 — DATASET AND FEATURE PREPARATION VERIFICATION")
print("=" * 100)

PREPARATION_VERIFICATION = {
    "All Datasets Loaded": all(
        dataset in REAL_DATASETS
        for dataset in DATASETS
    ),
    "All Training Splits Created": all(
        dataset in TRAIN_DATASETS
        and len(TRAIN_DATASETS[dataset]) > 0
        for dataset in DATASETS
    ),
    "All Validation Splits Created": all(
        dataset in VALIDATION_DATASETS
        and len(VALIDATION_DATASETS[dataset]) > 0
        for dataset in DATASETS
    ),
    "All Test Splits Created": all(
        dataset in TEST_DATASETS
        and len(TEST_DATASETS[dataset]) > 0
        for dataset in DATASETS
    ),
    "Split Sizes Verified": all(
        SPLIT_VERIFICATION.values()
    ),
    "No Data Leakage": all(
        LEAKAGE_VERIFICATION.values()
    ),
    "Numeric Feature Metadata": (
        len(TRAIN_NUMERIC_COLUMNS) == len(DATASETS)
    ),
    "Categorical Feature Metadata": (
        len(TRAIN_CATEGORICAL_COLUMNS) == len(DATASETS)
    ),
    "Categorical Domains Created": (
        len(CATEGORICAL_DOMAINS) == len(DATASETS)
    ),
    "Numeric Imputation Values Created": (
        len(NUMERIC_IMPUTATION_VALUES) == len(DATASETS)
    ),
    "Numeric Scalers Created": (
        len(NUMERIC_SCALERS) == len(DATASETS)
    ),
    "Feature Metadata Created": (
        len(FEATURE_METADATA) == len(DATASETS)
    ),
}

for check, status in PREPARATION_VERIFICATION.items():
    print(
        f"{check:40s}: "
        f"{'PASS' if status else 'FAIL'}"
    )

D_PASSED = sum(
    PREPARATION_VERIFICATION.values()
)

D_TOTAL = len(
    PREPARATION_VERIFICATION
)

print()
print(
    f"PART D VERIFICATION: "
    f"{D_PASSED}/{D_TOTAL} CHECKS PASSED"
)

if D_PASSED != D_TOTAL:
    failed_checks = [
        check
        for check, status
        in PREPARATION_VERIFICATION.items()
        if not status
    ]

    raise RuntimeError(
        "PART D dataset and feature preparation verification failed.\n"
        "Failed checks:\n"
        + "\n".join(
            f"- {check}"
            for check in failed_checks
        )
    )

print()
print(
    "PART D — DATASET AND FEATURE PREPARATION "
    "COMPLETED SUCCESSFULLY."
)

====================================================================================================
PART D13 — DATASET AND FEATURE PREPARATION VERIFICATION
====================================================================================================
All Datasets Loaded                     : PASS
All Training Splits Created             : PASS
All Validation Splits Created           : PASS
All Test Splits Created                 : PASS
Split Sizes Verified                    : PASS
No Data Leakage                         : PASS
Numeric Feature Metadata                : PASS
Categorical Feature Metadata            : PASS
Categorical Domains Created             : PASS
Numeric Imputation Values Created       : PASS
Numeric Scalers Created                 : PASS
Feature Metadata Created                : PASS

PART D VERIFICATION: 12/12 CHECKS PASSED

PART D — DATASET AND FEATURE PREPARATION COMPLETED SUCCESSFULLY.

In [43]:
# ==============================================================================
# PART E1 — DIFFERENTIAL PRIVACY PARAMETER CONFIGURATION
# ==============================================================================

print("=" * 100)
print("PART E1 — DIFFERENTIAL PRIVACY PARAMETER CONFIGURATION")
print("=" * 100)

PRIVACY_BUDGET = DP_CONFIG["privacy_budget"]
PRIVACY_DELTA = DP_CONFIG["delta"]
NOISE_MULTIPLIER = DP_CONFIG["noise_multiplier"]
MAX_GRAD_NORM = DP_CONFIG["gradient_clip"]

print(f"Privacy Budget (ε) : {PRIVACY_BUDGET}")
print(f"Privacy Delta (δ)  : {PRIVACY_DELTA}")
print(f"Noise Multiplier   : {NOISE_MULTIPLIER}")
print(f"Max Gradient Norm  : {MAX_GRAD_NORM}")

====================================================================================================
PART E1 — DIFFERENTIAL PRIVACY PARAMETER CONFIGURATION
====================================================================================================
Privacy Budget (ε) : 4.0
Privacy Delta (δ)  : 1e-05
Noise Multiplier   : 1.1
Max Gradient Norm  : 1.0

In [44]:
# ==============================================================================
# PART E2 — DP-CTGAN TRAINING CONFIGURATION
# ==============================================================================

print("=" * 100)
print("PART E2 — DP-CTGAN TRAINING CONFIGURATION")
print("=" * 100)

DP_EPOCHS = 100
DP_BATCH_SIZE = 256
DP_LEARNING_RATE = 0.0002
DP_BETA1 = 0.5
DP_BETA2 = 0.999
DP_LATENT_DIMENSION = 128

print(f"DP Epochs        : {DP_EPOCHS}")
print(f"DP Batch Size    : {DP_BATCH_SIZE}")
print(f"Learning Rate    : {DP_LEARNING_RATE}")
print(f"Adam Beta 1      : {DP_BETA1}")
print(f"Adam Beta 2      : {DP_BETA2}")
print(f"Latent Dimension : {DP_LATENT_DIMENSION}")

====================================================================================================
PART E2 — DP-CTGAN TRAINING CONFIGURATION
====================================================================================================
DP Epochs        : 100
DP Batch Size    : 256
Learning Rate    : 0.0002
Adam Beta 1      : 0.5
Adam Beta 2      : 0.999
Latent Dimension : 128

In [45]:
# ==============================================================================
# PART E3 — PRIVACY ACCOUNTANT CONFIGURATION
# ==============================================================================

print("=" * 100)
print("PART E3 — PRIVACY ACCOUNTANT CONFIGURATION")
print("=" * 100)

DP_ACCOUNTANT = "rdp"

print(f"Privacy Accountant : {DP_ACCOUNTANT.upper()}")

if DP_ACCOUNTANT.lower() != "rdp":
    raise ValueError(
        "Unsupported privacy accountant. "
        "This implementation requires RDP."
    )

print("Privacy accountant configuration verified.")

====================================================================================================
PART E3 — PRIVACY ACCOUNTANT CONFIGURATION
====================================================================================================
Privacy Accountant : RDP
Privacy accountant configuration verified.

In [46]:
# ==============================================================================
# PART E4 — DIFFERENTIAL PRIVACY CONFIGURATION DICTIONARY
# ==============================================================================

print("=" * 100)
print("PART E4 — DIFFERENTIAL PRIVACY CONFIGURATION DICTIONARY")
print("=" * 100)

DP_CONFIG = {
    "privacy_budget_epsilon": PRIVACY_BUDGET,
    "privacy_delta": PRIVACY_DELTA,
    "noise_multiplier": NOISE_MULTIPLIER,
    "max_grad_norm": MAX_GRAD_NORM,
    "accountant": DP_ACCOUNTANT,
    "epochs": DP_EPOCHS,
    "batch_size": DP_BATCH_SIZE,
    "learning_rate": DP_LEARNING_RATE,
    "beta1": DP_BETA1,
    "beta2": DP_BETA2,
    "latent_dimension": DP_LATENT_DIMENSION
}

for parameter, value in DP_CONFIG.items():
    print(f"{parameter:30s}: {value}")

====================================================================================================
PART E4 — DIFFERENTIAL PRIVACY CONFIGURATION DICTIONARY
====================================================================================================
privacy_budget_epsilon        : 4.0
privacy_delta                 : 1e-05
noise_multiplier              : 1.1
max_grad_norm                 : 1.0
accountant                    : rdp
epochs                        : 100
batch_size                    : 256
learning_rate                 : 0.0002
beta1                         : 0.5
beta2                         : 0.999
latent_dimension              : 128

In [47]:
# ==============================================================================
# PART E5 — DIFFERENTIAL PRIVACY PARAMETER VALIDATION
# ==============================================================================

print("=" * 100)
print("PART E5 — DIFFERENTIAL PRIVACY PARAMETER VALIDATION")
print("=" * 100)

DP_PARAMETER_VERIFICATION = {
    "Valid Epsilon": PRIVACY_BUDGET > 0,
    "Valid Delta": 0 < PRIVACY_DELTA < 1,
    "Valid Noise Multiplier": NOISE_MULTIPLIER > 0,
    "Valid Gradient Norm": MAX_GRAD_NORM > 0,
    "Valid Epochs": DP_EPOCHS > 0,
    "Valid Batch Size": DP_BATCH_SIZE > 0,
    "Valid Learning Rate": DP_LEARNING_RATE > 0,
    "Valid Latent Dimension": DP_LATENT_DIMENSION > 0,
    "Valid Accountant": DP_ACCOUNTANT.lower() == "rdp"
}

for check, status in DP_PARAMETER_VERIFICATION.items():
    print(f"{check:30s}: {'PASS' if status else 'FAIL'}")

if not all(DP_PARAMETER_VERIFICATION.values()):
    raise RuntimeError(
        "Differential Privacy parameter validation failed."
    )

print("\nAll Differential Privacy parameters passed validation.")

====================================================================================================
PART E5 — DIFFERENTIAL PRIVACY PARAMETER VALIDATION
====================================================================================================
Valid Epsilon                 : PASS
Valid Delta                   : PASS
Valid Noise Multiplier        : PASS
Valid Gradient Norm           : PASS
Valid Epochs                  : PASS
Valid Batch Size              : PASS
Valid Learning Rate           : PASS
Valid Latent Dimension        : PASS
Valid Accountant              : PASS

All Differential Privacy parameters passed validation.

In [48]:
# ==============================================================================
# PART E6 — PRIVACY SAMPLING CONFIGURATION
# ==============================================================================

print("=" * 100)
print("PART E6 — PRIVACY SAMPLING CONFIGURATION")
print("=" * 100)

DP_SAMPLING_CONFIG = {}

for dataset in DATASETS:
    training_rows = len(TRAIN_DATASETS[dataset])
    sampling_rate = DP_BATCH_SIZE / training_rows

    DP_SAMPLING_CONFIG[dataset] = {
        "training_rows": training_rows,
        "batch_size": DP_BATCH_SIZE,
        "sampling_rate": sampling_rate
    }

    print(f"\n{dataset}")
    print(f"Training Rows : {training_rows:,}")
    print(f"Batch Size    : {DP_BATCH_SIZE:,}")
    print(f"Sampling Rate : {sampling_rate:.8f}")

====================================================================================================
PART E6 — PRIVACY SAMPLING CONFIGURATION
====================================================================================================

Adult Income
Training Rows : 22,760
Batch Size    : 256
Sampling Rate : 0.01124780

Bank Marketing
Training Rows : 31,647
Batch Size    : 256
Sampling Rate : 0.00808923

diabetes_130us
Training Rows : 71,236
Batch Size    : 256
Sampling Rate : 0.00359369

In [49]:
# ==============================================================================
# PART E7 — PRIVACY CONFIGURATION SUMMARY
# ==============================================================================

print("=" * 100)
print("PART E7 — PRIVACY CONFIGURATION SUMMARY")
print("=" * 100)

PRIVACY_SUMMARY = []

for dataset in DATASETS:
    config = DP_SAMPLING_CONFIG[dataset]

    PRIVACY_SUMMARY.append({
        "Dataset": dataset,
        "Training Rows": config["training_rows"],
        "Batch Size": config["batch_size"],
        "Sampling Rate": config["sampling_rate"],
        "Epsilon": PRIVACY_BUDGET,
        "Delta": PRIVACY_DELTA,
        "Noise Multiplier": NOISE_MULTIPLIER,
        "Max Gradient Norm": MAX_GRAD_NORM,
        "Epochs": DP_EPOCHS
    })

PRIVACY_SUMMARY_DF = pd.DataFrame(PRIVACY_SUMMARY)

display(PRIVACY_SUMMARY_DF)

====================================================================================================
PART E7 — PRIVACY CONFIGURATION SUMMARY
====================================================================================================

,Dataset,Training Rows,Batch Size,Sampling Rate,Epsilon,Delta,Noise Multiplier,Max Gradient Norm,Epochs
0,Adult Income,22760,256,0.011248,4.0,0.00001,1.1,1.0,100
1,Bank Marketing,31647,256,0.008089,4.0,0.00001,1.1,1.0,100
2,diabetes_130us,71236,256,0.003594,4.0,0.00001,1.1,1.0,100

In [50]:
# ==============================================================================
# PART E8 — FINAL DIFFERENTIAL PRIVACY VERIFICATION
# ==============================================================================

print("=" * 100)
print("PART E8 — FINAL DIFFERENTIAL PRIVACY VERIFICATION")
print("=" * 100)

DP_VERIFICATION = {
    "DP Configuration Created": isinstance(DP_CONFIG, dict),
    "Privacy Budget Valid": PRIVACY_BUDGET > 0,
    "Privacy Delta Valid": 0 < PRIVACY_DELTA < 1,
    "Noise Multiplier Valid": NOISE_MULTIPLIER > 0,
    "Gradient Clipping Valid": MAX_GRAD_NORM > 0,
    "Training Configuration Valid": (
        DP_EPOCHS > 0 and DP_BATCH_SIZE > 0
    ),
    "Sampling Configuration Created": (
        len(DP_SAMPLING_CONFIG) == len(DATASETS)
    ),
    "Privacy Summary Created": (
        len(PRIVACY_SUMMARY_DF) == len(DATASETS)
    )
}

for check, status in DP_VERIFICATION.items():
    print(f"{check:35s}: {'PASS' if status else 'FAIL'}")

E_PASSED = sum(DP_VERIFICATION.values())
E_TOTAL = len(DP_VERIFICATION)

print(f"\nPART E VERIFICATION: {E_PASSED}/{E_TOTAL} CHECKS PASSED")

if E_PASSED != E_TOTAL:
    raise RuntimeError(
        "PART E Differential Privacy configuration verification failed."
    )

print("\nPART E — DIFFERENTIAL PRIVACY CONFIGURATION COMPLETED SUCCESSFULLY.")

====================================================================================================
PART E8 — FINAL DIFFERENTIAL PRIVACY VERIFICATION
====================================================================================================
DP Configuration Created           : PASS
Privacy Budget Valid               : PASS
Privacy Delta Valid                : PASS
Noise Multiplier Valid             : PASS
Gradient Clipping Valid            : PASS
Training Configuration Valid       : PASS
Sampling Configuration Created     : PASS
Privacy Summary Created            : PASS

PART E VERIFICATION: 8/8 CHECKS PASSED

PART E — DIFFERENTIAL PRIVACY CONFIGURATION COMPLETED SUCCESSFULLY.

In [51]:
# ==============================================================================
# PART F1 — GENERATOR DIMENSION CONFIGURATION
# ==============================================================================

print("=" * 100)
print("PART F1 — GENERATOR DIMENSION CONFIGURATION")
print("=" * 100)

GENERATOR_INPUT_DIMENSIONS = {}
GENERATOR_OUTPUT_DIMENSIONS = {}

for dataset in DATASETS:
    GENERATOR_INPUT_DIMENSIONS[dataset] = DP_LATENT_DIMENSION
    GENERATOR_OUTPUT_DIMENSIONS[dataset] = TRAIN_DATASETS[dataset].shape[1]

    print(f"\n{dataset}")
    print(f"Latent Dimension : {GENERATOR_INPUT_DIMENSIONS[dataset]}")
    print(f"Output Features  : {GENERATOR_OUTPUT_DIMENSIONS[dataset]}")

====================================================================================================
PART F1 — GENERATOR DIMENSION CONFIGURATION
====================================================================================================

Adult Income
Latent Dimension : 128
Output Features  : 15

Bank Marketing
Latent Dimension : 128
Output Features  : 17

diabetes_130us
Latent Dimension : 128
Output Features  : 48

In [52]:
# ==============================================================================
# PART F2 — GENERATOR ARCHITECTURE CLASS
# ==============================================================================

import torch
import torch.nn as nn

class DPCTGANGenerator(nn.Module):
    def __init__(self, latent_dimension, output_dimension):
        super().__init__()

        self.latent_dimension = latent_dimension
        self.output_dimension = output_dimension

        self.network = nn.Sequential(
            nn.Linear(latent_dimension, 512),
            nn.LayerNorm(512),
            nn.LeakyReLU(negative_slope=0.2, inplace=False),
            nn.Dropout(0.2),
            nn.Linear(512, 256),
            nn.LayerNorm(256),
            nn.LeakyReLU(negative_slope=0.2, inplace=False),
            nn.Dropout(0.2),
            nn.Linear(256, 128),
            nn.LayerNorm(128),
            nn.LeakyReLU(negative_slope=0.2, inplace=False),
            nn.Linear(128, output_dimension)
        )

    def forward(self, noise):
        return self.network(noise)

print("DPCTGANGenerator class defined successfully.")

DPCTGANGenerator class defined successfully.

In [53]:
# ==============================================================================
# PART F3 — GENERATOR INITIALIZATION
# ==============================================================================

print("=" * 100)
print("PART F3 — GENERATOR INITIALIZATION")
print("=" * 100)

GENERATORS = {}

for dataset in DATASETS:
    latent_dimension = GENERATOR_INPUT_DIMENSIONS[dataset]
    output_dimension = GENERATOR_OUTPUT_DIMENSIONS[dataset]

    generator = DPCTGANGenerator(
        latent_dimension=latent_dimension,
        output_dimension=output_dimension
    ).to(DEVICE)

    generator.train()
    GENERATORS[dataset] = generator

    print(f"\n{dataset}")
    print(f"Latent Dimension : {latent_dimension}")
    print(f"Output Dimension : {output_dimension}")
    print(f"Device           : {DEVICE}")
    print(f"Training Mode    : {generator.training}")

====================================================================================================
PART F3 — GENERATOR INITIALIZATION
====================================================================================================

Adult Income
Latent Dimension : 128
Output Dimension : 15
Device           : cpu
Training Mode    : True

Bank Marketing
Latent Dimension : 128
Output Dimension : 17
Device           : cpu
Training Mode    : True

diabetes_130us
Latent Dimension : 128
Output Dimension : 48
Device           : cpu
Training Mode    : True

In [54]:
# ==============================================================================
# PART F4 — GENERATOR PARAMETER INITIALIZATION
# ==============================================================================

print("=" * 100)
print("PART F4 — GENERATOR PARAMETER INITIALIZATION")
print("=" * 100)

def initialize_generator_weights(model):
    for module in model.modules():
        if isinstance(module, nn.Linear):
            nn.init.xavier_uniform_(module.weight)

            if module.bias is not None:
                nn.init.zeros_(module.bias)

for dataset in DATASETS:
    initialize_generator_weights(GENERATORS[dataset])
    print(f"{dataset:25s}: Weight initialization completed")

====================================================================================================
PART F4 — GENERATOR PARAMETER INITIALIZATION
====================================================================================================
Adult Income             : Weight initialization completed
Bank Marketing           : Weight initialization completed
diabetes_130us           : Weight initialization completed

In [55]:
# ==============================================================================
# PART F5 — GENERATOR ARCHITECTURE SUMMARY
# ==============================================================================

print("=" * 100)
print("PART F5 — GENERATOR ARCHITECTURE SUMMARY")
print("=" * 100)

GENERATOR_PARAMETER_COUNTS = {}

for dataset in DATASETS:
    generator = GENERATORS[dataset]

    total_parameters = sum(
        parameter.numel()
        for parameter in generator.parameters()
    )

    trainable_parameters = sum(
        parameter.numel()
        for parameter in generator.parameters()
        if parameter.requires_grad
    )

    GENERATOR_PARAMETER_COUNTS[dataset] = {
        "Total Parameters": total_parameters,
        "Trainable Parameters": trainable_parameters
    }

    print(f"\n{dataset}")
    print(generator)
    print(f"Total Parameters     : {total_parameters:,}")
    print(f"Trainable Parameters : {trainable_parameters:,}")

====================================================================================================
PART F5 — GENERATOR ARCHITECTURE SUMMARY
====================================================================================================

Adult Income
DPCTGANGenerator(
  (network): Sequential(
    (0): Linear(in_features=128, out_features=512, bias=True)
    (1): LayerNorm((512,), eps=1e-05, elementwise_affine=True)
    (2): LeakyReLU(negative_slope=0.2)
    (3): Dropout(p=0.2, inplace=False)
    (4): Linear(in_features=512, out_features=256, bias=True)
    (5): LayerNorm((256,), eps=1e-05, elementwise_affine=True)
    (6): LeakyReLU(negative_slope=0.2)
    (7): Dropout(p=0.2, inplace=False)
    (8): Linear(in_features=256, out_features=128, bias=True)
    (9): LayerNorm((128,), eps=1e-05, elementwise_affine=True)
    (10): LeakyReLU(negative_slope=0.2)
    (11): Linear(in_features=128, out_features=15, bias=True)
  )
)
Total Parameters     : 233,999
Trainable Parameters : 233,999

Bank Marketing
DPCTGANGenerator(
  (network): Sequential(
    (0): Linear(in_features=128, out_features=512, bias=True)
    (1): LayerNorm((512,), eps=1e-05, elementwise_affine=True)
    (2): LeakyReLU(negative_slope=0.2)
    (3): Dropout(p=0.2, inplace=False)
    (4): Linear(in_features=512, out_features=256, bias=True)
    (5): LayerNorm((256,), eps=1e-05, elementwise_affine=True)
    (6): LeakyReLU(negative_slope=0.2)
    (7): Dropout(p=0.2, inplace=False)
    (8): Linear(in_features=256, out_features=128, bias=True)
    (9): LayerNorm((128,), eps=1e-05, elementwise_affine=True)
    (10): LeakyReLU(negative_slope=0.2)
    (11): Linear(in_features=128, out_features=17, bias=True)
  )
)
Total Parameters     : 234,257
Trainable Parameters : 234,257

diabetes_130us
DPCTGANGenerator(
  (network): Sequential(
    (0): Linear(in_features=128, out_features=512, bias=True)
    (1): LayerNorm((512,), eps=1e-05, elementwise_affine=True)
    (2): LeakyReLU(negative_slope=0.2)
    (3): Dropout(p=0.2, inplace=False)
    (4): Linear(in_features=512, out_features=256, bias=True)
    (5): LayerNorm((256,), eps=1e-05, elementwise_affine=True)
    (6): LeakyReLU(negative_slope=0.2)
    (7): Dropout(p=0.2, inplace=False)
    (8): Linear(in_features=256, out_features=128, bias=True)
    (9): LayerNorm((128,), eps=1e-05, elementwise_affine=True)
    (10): LeakyReLU(negative_slope=0.2)
    (11): Linear(in_features=128, out_features=48, bias=True)
  )
)
Total Parameters     : 238,256
Trainable Parameters : 238,256

In [56]:
# ==============================================================================
# PART F6 — GENERATOR OUTPUT SHAPE VALIDATION
# ==============================================================================

print("=" * 100)
print("PART F6 — GENERATOR OUTPUT SHAPE VALIDATION")
print("=" * 100)

GENERATOR_OUTPUT_VERIFICATION = {}
VALIDATION_BATCH_SIZE = 4

for dataset in DATASETS:
    generator = GENERATORS[dataset]

    expected_output_dimension = TRAIN_DATASETS[dataset].shape[1]

    noise = torch.randn(
        VALIDATION_BATCH_SIZE,
        DP_LATENT_DIMENSION,
        device=DEVICE
    )

    generator.eval()

    with torch.no_grad():
        generated_data = generator(noise)

    generator.train()

    expected_shape = (
        VALIDATION_BATCH_SIZE,
        expected_output_dimension
    )
    actual_shape = tuple(generated_data.shape)

    dimension_check = generated_data.shape[1] == expected_output_dimension
    shape_check = actual_shape == expected_shape
    status = dimension_check and shape_check

    GENERATOR_OUTPUT_VERIFICATION[dataset] = status

    print(f"\n{dataset}")
    print(f"Expected Shape : {expected_shape}")
    print(f"Actual Shape   : {actual_shape}")
    print(f"Dimension Check: {'PASS' if dimension_check else 'FAIL'}")
    print(f"Shape Check    : {'PASS' if shape_check else 'FAIL'}")
    print(f"Overall        : {'PASS' if status else 'FAIL'}")

if not all(GENERATOR_OUTPUT_VERIFICATION.values()):
    raise RuntimeError(
        "Generator output dimensions do not match "
        "the training dataset dimensions."
    )

print("\nAll Generator output dimensions verified successfully.")

====================================================================================================
PART F6 — GENERATOR OUTPUT SHAPE VALIDATION
====================================================================================================

Adult Income
Expected Shape : (4, 15)
Actual Shape   : (4, 15)
Dimension Check: PASS
Shape Check    : PASS
Overall        : PASS

Bank Marketing
Expected Shape : (4, 17)
Actual Shape   : (4, 17)
Dimension Check: PASS
Shape Check    : PASS
Overall        : PASS

diabetes_130us
Expected Shape : (4, 48)
Actual Shape   : (4, 48)
Dimension Check: PASS
Shape Check    : PASS
Overall        : PASS

All Generator output dimensions verified successfully.

In [57]:
# ==============================================================================
# PART F7 — OPACUS GENERATOR COMPATIBILITY CHECK
# ==============================================================================

print("=" * 100)
print("PART F7 — OPACUS GENERATOR COMPATIBILITY CHECK")
print("=" * 100)

from opacus.validators import ModuleValidator

GENERATOR_OPACUS_COMPATIBILITY = {}

for dataset in DATASETS:
    generator = GENERATORS[dataset]
    generator.train()

    errors = ModuleValidator.validate(
        generator,
        strict=False
    )

    compatibility = len(errors) == 0
    GENERATOR_OPACUS_COMPATIBILITY[dataset] = compatibility

    print(f"\n{dataset}")

    if compatibility:
        print("Opacus Compatibility: PASS")
    else:
        print("Opacus Compatibility: FAIL")

        for error in errors:
            print(f"  {error}")

if not all(GENERATOR_OPACUS_COMPATIBILITY.values()):
    raise RuntimeError(
        "One or more Generators failed "
        "Opacus compatibility validation."
    )

print("\nAll Generators passed Opacus compatibility validation.")

====================================================================================================
PART F7 — OPACUS GENERATOR COMPATIBILITY CHECK
====================================================================================================

Adult Income
Opacus Compatibility: PASS

Bank Marketing
Opacus Compatibility: PASS

diabetes_130us
Opacus Compatibility: PASS

All Generators passed Opacus compatibility validation.

In [58]:
# ==============================================================================
# PART F8 — FINAL GENERATOR ARCHITECTURE VERIFICATION
# ==============================================================================

print("=" * 100)
print("PART F8 — FINAL GENERATOR ARCHITECTURE VERIFICATION")
print("=" * 100)

FINAL_GENERATOR_VERIFICATION = {}

for dataset in DATASETS:
    generator = GENERATORS[dataset]
    generator.train()

    expected_features = TRAIN_DATASETS[dataset].shape[1]

    linear_layers = [
        layer
        for layer in generator.modules()
        if isinstance(layer, nn.Linear)
    ]

    actual_output_features = linear_layers[-1].out_features

    output_dimension_check = (
        actual_output_features == expected_features
    )
    training_mode_check = generator.training
    opacus_check = GENERATOR_OPACUS_COMPATIBILITY[dataset]

    final_status = (
        output_dimension_check
        and training_mode_check
        and opacus_check
    )

    FINAL_GENERATOR_VERIFICATION[dataset] = final_status

    print(f"\n{dataset}")
    print(f"Training Features    : {expected_features}")
    print(f"Generator Output     : {actual_output_features}")
    print(f"Dimension Check      : {'PASS' if output_dimension_check else 'FAIL'}")
    print(f"Training Mode        : {'PASS' if training_mode_check else 'FAIL'}")
    print(f"Opacus Compatibility : {'PASS' if opacus_check else 'FAIL'}")
    print(f"Final Status         : {'PASS' if final_status else 'FAIL'}")

if not all(FINAL_GENERATOR_VERIFICATION.values()):
    raise RuntimeError(
        "Final Generator architecture verification failed."
    )

print("\n" + "=" * 100)
print("PART F COMPLETED SUCCESSFULLY")
print("All Generator architecture checks passed.")
print("=" * 100)

====================================================================================================
PART F8 — FINAL GENERATOR ARCHITECTURE VERIFICATION
====================================================================================================

Adult Income
Training Features    : 15
Generator Output     : 15
Dimension Check      : PASS
Training Mode        : PASS
Opacus Compatibility : PASS
Final Status         : PASS

Bank Marketing
Training Features    : 17
Generator Output     : 17
Dimension Check      : PASS
Training Mode        : PASS
Opacus Compatibility : PASS
Final Status         : PASS

diabetes_130us
Training Features    : 48
Generator Output     : 48
Dimension Check      : PASS
Training Mode        : PASS
Opacus Compatibility : PASS
Final Status         : PASS

====================================================================================================
PART F COMPLETED SUCCESSFULLY
All Generator architecture checks passed.
====================================================================================================

In [59]:
# ==============================================================================
# PART G1 — DISCRIMINATOR DIMENSION CONFIGURATION
# ==============================================================================

print("=" * 100)
print("PART G1 — DISCRIMINATOR DIMENSION CONFIGURATION")
print("=" * 100)

DISCRIMINATOR_INPUT_DIMENSIONS = {}
DISCRIMINATOR_OUTPUT_DIMENSION = 1

for dataset in DATASETS:
    DISCRIMINATOR_INPUT_DIMENSIONS[dataset] = (
        TRAIN_DATASETS[dataset].shape[1]
    )

    print(f"\n{dataset}")
    print(f"Input Features  : {DISCRIMINATOR_INPUT_DIMENSIONS[dataset]}")
    print(f"Output Features : {DISCRIMINATOR_OUTPUT_DIMENSION}")

====================================================================================================
PART G1 — DISCRIMINATOR DIMENSION CONFIGURATION
====================================================================================================

Adult Income
Input Features  : 15
Output Features : 1

Bank Marketing
Input Features  : 17
Output Features : 1

diabetes_130us
Input Features  : 48
Output Features : 1

In [60]:
# ==============================================================================
# PART G2 — DISCRIMINATOR ARCHITECTURE CLASS
# ==============================================================================

class DPCTGANDiscriminator(nn.Module):
    def __init__(self, input_dimension):
        super().__init__()

        self.input_dimension = input_dimension

        self.network = nn.Sequential(
            nn.Linear(input_dimension, 512),
            nn.LayerNorm(512),
            nn.LeakyReLU(negative_slope=0.2, inplace=False),
            nn.Dropout(0.3),
            nn.Linear(512, 256),
            nn.LayerNorm(256),
            nn.LeakyReLU(negative_slope=0.2, inplace=False),
            nn.Dropout(0.3),
            nn.Linear(256, 128),
            nn.LayerNorm(128),
            nn.LeakyReLU(negative_slope=0.2, inplace=False),
            nn.Dropout(0.3),
            nn.Linear(128, 1)
        )

    def forward(self, data):
        return self.network(data)

print("DPCTGANDiscriminator class defined successfully.")

DPCTGANDiscriminator class defined successfully.

In [61]:
# ==============================================================================
# PART G3 — DISCRIMINATOR INITIALIZATION
# ==============================================================================

print("=" * 100)
print("PART G3 — DISCRIMINATOR INITIALIZATION")
print("=" * 100)

DISCRIMINATORS = {}

for dataset in DATASETS:
    input_dimension = DISCRIMINATOR_INPUT_DIMENSIONS[dataset]

    discriminator = DPCTGANDiscriminator(
        input_dimension=input_dimension
    ).to(DEVICE)

    discriminator.train()
    DISCRIMINATORS[dataset] = discriminator

    print(f"\n{dataset}")
    print(f"Input Dimension : {input_dimension}")
    print(f"Output Dimension: {DISCRIMINATOR_OUTPUT_DIMENSION}")
    print(f"Device          : {DEVICE}")
    print(f"Training Mode   : {discriminator.training}")

====================================================================================================
PART G3 — DISCRIMINATOR INITIALIZATION
====================================================================================================

Adult Income
Input Dimension : 15
Output Dimension: 1
Device          : cpu
Training Mode   : True

Bank Marketing
Input Dimension : 17
Output Dimension: 1
Device          : cpu
Training Mode   : True

diabetes_130us
Input Dimension : 48
Output Dimension: 1
Device          : cpu
Training Mode   : True

In [62]:
# ==============================================================================
# PART G4 — DISCRIMINATOR PARAMETER INITIALIZATION
# ==============================================================================

print("=" * 100)
print("PART G4 — DISCRIMINATOR PARAMETER INITIALIZATION")
print("=" * 100)

def initialize_discriminator_weights(model):
    for module in model.modules():
        if isinstance(module, nn.Linear):
            nn.init.xavier_uniform_(module.weight)

            if module.bias is not None:
                nn.init.zeros_(module.bias)

for dataset in DATASETS:
    initialize_discriminator_weights(DISCRIMINATORS[dataset])
    print(f"{dataset:25s}: Weight initialization completed")

====================================================================================================
PART G4 — DISCRIMINATOR PARAMETER INITIALIZATION
====================================================================================================
Adult Income             : Weight initialization completed
Bank Marketing           : Weight initialization completed
diabetes_130us           : Weight initialization completed

In [63]:
# ==============================================================================
# PART G5 — DISCRIMINATOR ARCHITECTURE SUMMARY
# ==============================================================================

print("=" * 100)
print("PART G5 — DISCRIMINATOR ARCHITECTURE SUMMARY")
print("=" * 100)

DISCRIMINATOR_PARAMETER_COUNTS = {}

for dataset in DATASETS:
    discriminator = DISCRIMINATORS[dataset]

    total_parameters = sum(
        parameter.numel()
        for parameter in discriminator.parameters()
    )

    trainable_parameters = sum(
        parameter.numel()
        for parameter in discriminator.parameters()
        if parameter.requires_grad
    )

    DISCRIMINATOR_PARAMETER_COUNTS[dataset] = {
        "Total Parameters": total_parameters,
        "Trainable Parameters": trainable_parameters
    }

    print(f"\n{dataset}")
    print(discriminator)
    print(f"Total Parameters     : {total_parameters:,}")
    print(f"Trainable Parameters : {trainable_parameters:,}")

====================================================================================================
PART G5 — DISCRIMINATOR ARCHITECTURE SUMMARY
====================================================================================================

Adult Income
DPCTGANDiscriminator(
  (network): Sequential(
    (0): Linear(in_features=15, out_features=512, bias=True)
    (1): LayerNorm((512,), eps=1e-05, elementwise_affine=True)
    (2): LeakyReLU(negative_slope=0.2)
    (3): Dropout(p=0.3, inplace=False)
    (4): Linear(in_features=512, out_features=256, bias=True)
    (5): LayerNorm((256,), eps=1e-05, elementwise_affine=True)
    (6): LeakyReLU(negative_slope=0.2)
    (7): Dropout(p=0.3, inplace=False)
    (8): Linear(in_features=256, out_features=128, bias=True)
    (9): LayerNorm((128,), eps=1e-05, elementwise_affine=True)
    (10): LeakyReLU(negative_slope=0.2)
    (11): Dropout(p=0.3, inplace=False)
    (12): Linear(in_features=128, out_features=1, bias=True)
  )
)
Total Parameters     : 174,337
Trainable Parameters : 174,337

Bank Marketing
DPCTGANDiscriminator(
  (network): Sequential(
    (0): Linear(in_features=17, out_features=512, bias=True)
    (1): LayerNorm((512,), eps=1e-05, elementwise_affine=True)
    (2): LeakyReLU(negative_slope=0.2)
    (3): Dropout(p=0.3, inplace=False)
    (4): Linear(in_features=512, out_features=256, bias=True)
    (5): LayerNorm((256,), eps=1e-05, elementwise_affine=True)
    (6): LeakyReLU(negative_slope=0.2)
    (7): Dropout(p=0.3, inplace=False)
    (8): Linear(in_features=256, out_features=128, bias=True)
    (9): LayerNorm((128,), eps=1e-05, elementwise_affine=True)
    (10): LeakyReLU(negative_slope=0.2)
    (11): Dropout(p=0.3, inplace=False)
    (12): Linear(in_features=128, out_features=1, bias=True)
  )
)
Total Parameters     : 175,361
Trainable Parameters : 175,361

diabetes_130us
DPCTGANDiscriminator(
  (network): Sequential(
    (0): Linear(in_features=48, out_features=512, bias=True)
    (1): LayerNorm((512,), eps=1e-05, elementwise_affine=True)
    (2): LeakyReLU(negative_slope=0.2)
    (3): Dropout(p=0.3, inplace=False)
    (4): Linear(in_features=512, out_features=256, bias=True)
    (5): LayerNorm((256,), eps=1e-05, elementwise_affine=True)
    (6): LeakyReLU(negative_slope=0.2)
    (7): Dropout(p=0.3, inplace=False)
    (8): Linear(in_features=256, out_features=128, bias=True)
    (9): LayerNorm((128,), eps=1e-05, elementwise_affine=True)
    (10): LeakyReLU(negative_slope=0.2)
    (11): Dropout(p=0.3, inplace=False)
    (12): Linear(in_features=128, out_features=1, bias=True)
  )
)
Total Parameters     : 191,233
Trainable Parameters : 191,233

In [64]:
# ==============================================================================
# PART G6 — DISCRIMINATOR INPUT SHAPE VALIDATION
# ==============================================================================

print("=" * 100)
print("PART G6 — DISCRIMINATOR INPUT SHAPE VALIDATION")
print("=" * 100)

DISCRIMINATOR_INPUT_VERIFICATION = {}
VALIDATION_BATCH_SIZE = 4

for dataset in DATASETS:
    discriminator = DISCRIMINATORS[dataset]

    expected_input_dimension = TRAIN_DATASETS[dataset].shape[1]

    test_data = torch.randn(
        VALIDATION_BATCH_SIZE,
        expected_input_dimension,
        device=DEVICE
    )

    discriminator.eval()

    with torch.no_grad():
        discriminator_output = discriminator(test_data)

    discriminator.train()

    actual_output_shape = tuple(discriminator_output.shape)
    expected_output_shape = (
        VALIDATION_BATCH_SIZE,
        DISCRIMINATOR_OUTPUT_DIMENSION
    )

    input_dimension_check = (
        discriminator.input_dimension == expected_input_dimension
    )
    output_shape_check = actual_output_shape == expected_output_shape
    status = input_dimension_check and output_shape_check

    DISCRIMINATOR_INPUT_VERIFICATION[dataset] = status

    print(f"\n{dataset}")
    print(f"Expected Input Dimension : {expected_input_dimension}")
    print(f"Actual Input Dimension   : {discriminator.input_dimension}")
    print(f"Expected Output Shape    : {expected_output_shape}")
    print(f"Actual Output Shape      : {actual_output_shape}")
    print(f"Input Dimension Check    : {'PASS' if input_dimension_check else 'FAIL'}")
    print(f"Output Shape Check       : {'PASS' if output_shape_check else 'FAIL'}")
    print(f"Overall                  : {'PASS' if status else 'FAIL'}")

if not all(DISCRIMINATOR_INPUT_VERIFICATION.values()):
    raise RuntimeError(
        "Discriminator input/output dimensions "
        "do not match the training data."
    )

print("\nAll Discriminator input/output dimensions verified successfully.")

====================================================================================================
PART G6 — DISCRIMINATOR INPUT SHAPE VALIDATION
====================================================================================================

Adult Income
Expected Input Dimension : 15
Actual Input Dimension   : 15
Expected Output Shape    : (4, 1)
Actual Output Shape      : (4, 1)
Input Dimension Check    : PASS
Output Shape Check       : PASS
Overall                  : PASS

Bank Marketing
Expected Input Dimension : 17
Actual Input Dimension   : 17
Expected Output Shape    : (4, 1)
Actual Output Shape      : (4, 1)
Input Dimension Check    : PASS
Output Shape Check       : PASS
Overall                  : PASS

diabetes_130us
Expected Input Dimension : 48
Actual Input Dimension   : 48
Expected Output Shape    : (4, 1)
Actual Output Shape      : (4, 1)
Input Dimension Check    : PASS
Output Shape Check       : PASS
Overall                  : PASS

All Discriminator input/output dimensions verified successfully.

In [65]:
# ==============================================================================
# PART G7 — GENERATOR-DISCRIMINATOR COMPATIBILITY
# ==============================================================================

print("=" * 100)
print("PART G7 — GENERATOR-DISCRIMINATOR COMPATIBILITY")
print("=" * 100)

GAN_DIMENSION_COMPATIBILITY = {}

for dataset in DATASETS:
    expected_features = TRAIN_DATASETS[dataset].shape[1]
    generator_output = GENERATOR_OUTPUT_DIMENSIONS[dataset]
    discriminator_input = DISCRIMINATOR_INPUT_DIMENSIONS[dataset]

    compatibility = (
        expected_features
        == generator_output
        == discriminator_input
    )

    GAN_DIMENSION_COMPATIBILITY[dataset] = compatibility

    print(f"\n{dataset}")
    print(f"Training Features   : {expected_features}")
    print(f"Generator Output    : {generator_output}")
    print(f"Discriminator Input : {discriminator_input}")
    print(f"Compatibility       : {'PASS' if compatibility else 'FAIL'}")

if not all(GAN_DIMENSION_COMPATIBILITY.values()):
    raise RuntimeError(
        "Generator and Discriminator dimensions "
        "are incompatible with the training data."
    )

print("\nGenerator and Discriminator dimensions are fully compatible.")

====================================================================================================
PART G7 — GENERATOR-DISCRIMINATOR COMPATIBILITY
====================================================================================================

Adult Income
Training Features   : 15
Generator Output    : 15
Discriminator Input : 15
Compatibility       : PASS

Bank Marketing
Training Features   : 17
Generator Output    : 17
Discriminator Input : 17
Compatibility       : PASS

diabetes_130us
Training Features   : 48
Generator Output    : 48
Discriminator Input : 48
Compatibility       : PASS

Generator and Discriminator dimensions are fully compatible.

In [66]:
# ==============================================================================
# PART G8 — OPACUS DISCRIMINATOR COMPATIBILITY CHECK
# ==============================================================================

print("=" * 100)
print("PART G8 — OPACUS DISCRIMINATOR COMPATIBILITY CHECK")
print("=" * 100)

DISCRIMINATOR_OPACUS_COMPATIBILITY = {}

for dataset in DATASETS:
    discriminator = DISCRIMINATORS[dataset]
    discriminator.train()

    errors = ModuleValidator.validate(
        discriminator,
        strict=False
    )

    compatibility = len(errors) == 0
    DISCRIMINATOR_OPACUS_COMPATIBILITY[dataset] = compatibility

    print(f"\n{dataset}")

    if compatibility:
        print("Opacus Compatibility: PASS")
    else:
        print("Opacus Compatibility: FAIL")

        for error in errors:
            print(f"  {error}")

if not all(DISCRIMINATOR_OPACUS_COMPATIBILITY.values()):
    raise RuntimeError(
        "One or more Discriminators failed "
        "Opacus compatibility validation."
    )

print("\nAll Discriminators passed Opacus compatibility validation.")

====================================================================================================
PART G8 — OPACUS DISCRIMINATOR COMPATIBILITY CHECK
====================================================================================================

Adult Income
Opacus Compatibility: PASS

Bank Marketing
Opacus Compatibility: PASS

diabetes_130us
Opacus Compatibility: PASS

All Discriminators passed Opacus compatibility validation.

In [67]:
# ==============================================================================
# PART G9 — FINAL DISCRIMINATOR ARCHITECTURE VERIFICATION
# ==============================================================================

print("=" * 100)
print("PART G9 — FINAL DISCRIMINATOR ARCHITECTURE VERIFICATION")
print("=" * 100)

FINAL_DISCRIMINATOR_VERIFICATION = {}

for dataset in DATASETS:
    discriminator = DISCRIMINATORS[dataset]
    discriminator.train()

    expected_features = TRAIN_DATASETS[dataset].shape[1]
    actual_input_features = discriminator.input_dimension

    dimension_check = actual_input_features == expected_features
    training_mode_check = discriminator.training
    opacus_check = DISCRIMINATOR_OPACUS_COMPATIBILITY[dataset]
    compatibility_check = GAN_DIMENSION_COMPATIBILITY[dataset]

    final_status = (
        dimension_check
        and training_mode_check
        and opacus_check
        and compatibility_check
    )

    FINAL_DISCRIMINATOR_VERIFICATION[dataset] = final_status

    print(f"\n{dataset}")
    print(f"Training Features       : {expected_features}")
    print(f"Discriminator Input     : {actual_input_features}")
    print(f"Dimension Check         : {'PASS' if dimension_check else 'FAIL'}")
    print(f"Training Mode           : {'PASS' if training_mode_check else 'FAIL'}")
    print(f"Generator Compatibility : {'PASS' if compatibility_check else 'FAIL'}")
    print(f"Opacus Compatibility    : {'PASS' if opacus_check else 'FAIL'}")
    print(f"Final Status             : {'PASS' if final_status else 'FAIL'}")

if not all(FINAL_DISCRIMINATOR_VERIFICATION.values()):
    raise RuntimeError(
        "Final Discriminator architecture verification failed."
    )

print("\n" + "=" * 100)
print("PART G COMPLETED SUCCESSFULLY")
print("All Discriminator architecture checks passed.")
print("=" * 100)

====================================================================================================
PART G9 — FINAL DISCRIMINATOR ARCHITECTURE VERIFICATION
====================================================================================================

Adult Income
Training Features       : 15
Discriminator Input     : 15
Dimension Check         : PASS
Training Mode           : PASS
Generator Compatibility : PASS
Opacus Compatibility    : PASS
Final Status             : PASS

Bank Marketing
Training Features       : 17
Discriminator Input     : 17
Dimension Check         : PASS
Training Mode           : PASS
Generator Compatibility : PASS
Opacus Compatibility    : PASS
Final Status             : PASS

diabetes_130us
Training Features       : 48
Discriminator Input     : 48
Dimension Check         : PASS
Training Mode           : PASS
Generator Compatibility : PASS
Opacus Compatibility    : PASS
Final Status             : PASS

====================================================================================================
PART G COMPLETED SUCCESSFULLY
All Discriminator architecture checks passed.
====================================================================================================

In [68]:
# ==============================================================================
# PART H1 — OPACUS VERSION AND ENVIRONMENT VALIDATION
# ==============================================================================

print("=" * 100)
print("PART H1 — OPACUS VERSION AND ENVIRONMENT VALIDATION")
print("=" * 100)

print(f"PyTorch Version : {torch.__version__}")
print(f"Opacus Version  : {opacus.__version__}")
print(f"Device          : {DEVICE}")
print(f"Datasets        : {len(DATASETS)}")
print(f"Dataset Names   : {DATASETS}")

====================================================================================================
PART H1 — OPACUS VERSION AND ENVIRONMENT VALIDATION
====================================================================================================
PyTorch Version : 2.11.0+cpu
Opacus Version  : 1.6.0
Device          : cpu
Datasets        : 3
Dataset Names   : ['Adult Income', 'Bank Marketing', 'diabetes_130us']

In [69]:
# ==============================================================================
# PART I1 — LOSS FUNCTION CONFIGURATION
# ==============================================================================

print("=" * 100)
print("PART I1 — LOSS FUNCTION CONFIGURATION")
print("=" * 100)

LOSS_FUNCTION_NAME = "BCEWithLogitsLoss"

print(f"Loss Function       : {LOSS_FUNCTION_NAME}")
print("Discriminator Output : Raw Logits")
print("Sigmoid Activation   : Handled internally by BCEWithLogitsLoss")

====================================================================================================
PART I1 — LOSS FUNCTION CONFIGURATION
====================================================================================================
Loss Function       : BCEWithLogitsLoss
Discriminator Output : Raw Logits
Sigmoid Activation   : Handled internally by BCEWithLogitsLoss

In [70]:
# ==============================================================================
# PART I2 — BINARY CROSS-ENTROPY WITH LOGITS LOSS
# ==============================================================================

DISCRIMINATOR_LOSS_FUNCTION = nn.BCEWithLogitsLoss()

print("=" * 100)
print("PART I2 — BINARY CROSS-ENTROPY WITH LOGITS LOSS")
print("=" * 100)

print("BCEWithLogitsLoss initialized successfully.")
print(f"Loss Function : {DISCRIMINATOR_LOSS_FUNCTION}")

====================================================================================================
PART I2 — BINARY CROSS-ENTROPY WITH LOGITS LOSS
====================================================================================================
BCEWithLogitsLoss initialized successfully.
Loss Function : BCEWithLogitsLoss()

In [71]:
# ==============================================================================
# PART I3 — GENERATOR LOSS FUNCTION
# ==============================================================================

GENERATOR_LOSS_FUNCTION = DISCRIMINATOR_LOSS_FUNCTION

print("=" * 100)
print("PART I3 — GENERATOR LOSS FUNCTION")
print("=" * 100)

print("Generator loss configured successfully.")
print(f"Loss Function : {GENERATOR_LOSS_FUNCTION}")

====================================================================================================
PART I3 — GENERATOR LOSS FUNCTION
====================================================================================================
Generator loss configured successfully.
Loss Function : BCEWithLogitsLoss()

In [72]:
# ==============================================================================
# PART I4 — REAL AND FAKE LABEL CONFIGURATION
# ==============================================================================

REAL_LABEL_VALUE = 1.0
FAKE_LABEL_VALUE = 0.0

print("=" * 100)
print("PART I4 — REAL AND FAKE LABEL CONFIGURATION")
print("=" * 100)

print(f"Real Label : {REAL_LABEL_VALUE}")
print(f"Fake Label : {FAKE_LABEL_VALUE}")

====================================================================================================
PART I4 — REAL AND FAKE LABEL CONFIGURATION
====================================================================================================
Real Label : 1.0
Fake Label : 0.0

In [73]:
# ==============================================================================
# PART I5 — LOSS LABEL CREATION FUNCTION
# ==============================================================================

def create_real_labels(batch_size, device):
    return torch.full(
        (batch_size, 1),
        REAL_LABEL_VALUE,
        dtype=torch.float32,
        device=device
    )

def create_fake_labels(batch_size, device):
    return torch.full(
        (batch_size, 1),
        FAKE_LABEL_VALUE,
        dtype=torch.float32,
        device=device
    )

print("=" * 100)
print("PART I5 — LOSS LABEL CREATION FUNCTION")
print("=" * 100)

print("Real and fake label functions defined successfully.")

====================================================================================================
PART I5 — LOSS LABEL CREATION FUNCTION
====================================================================================================
Real and fake label functions defined successfully.

In [74]:
# ==============================================================================
# PART I6 — LOSS FUNCTION SHAPE VALIDATION
# ==============================================================================

print("=" * 100)
print("PART I6 — LOSS FUNCTION SHAPE VALIDATION")
print("=" * 100)

LOSS_VALIDATION_BATCH_SIZE = 8

test_real_labels = create_real_labels(
    LOSS_VALIDATION_BATCH_SIZE,
    DEVICE
)

test_fake_labels = create_fake_labels(
    LOSS_VALIDATION_BATCH_SIZE,
    DEVICE
)

test_logits = torch.randn(
    LOSS_VALIDATION_BATCH_SIZE,
    1,
    device=DEVICE
)

real_loss = DISCRIMINATOR_LOSS_FUNCTION(
    test_logits,
    test_real_labels
)

fake_loss = DISCRIMINATOR_LOSS_FUNCTION(
    test_logits,
    test_fake_labels
)

generator_loss = GENERATOR_LOSS_FUNCTION(
    test_logits,
    test_real_labels
)

print(f"Logits Shape      : {tuple(test_logits.shape)}")
print(f"Real Labels Shape : {tuple(test_real_labels.shape)}")
print(f"Fake Labels Shape : {tuple(test_fake_labels.shape)}")
print(f"Real Loss         : {real_loss.item():.6f}")
print(f"Fake Loss         : {fake_loss.item():.6f}")
print(f"Generator Loss    : {generator_loss.item():.6f}")

if not all(
    torch.isfinite(loss)
    for loss in (real_loss, fake_loss, generator_loss)
):
    raise RuntimeError(
        "One or more loss values are not finite."
    )

print("\nLoss function shape and numerical validation: PASS")

====================================================================================================
PART I6 — LOSS FUNCTION SHAPE VALIDATION
====================================================================================================
Logits Shape      : (8, 1)
Real Labels Shape : (8, 1)
Fake Labels Shape : (8, 1)
Real Loss         : 0.801194
Fake Loss         : 0.731333
Generator Loss    : 0.801194

Loss function shape and numerical validation: PASS

In [75]:
# ==============================================================================
# PART I7 — DISCRIMINATOR LOSS FUNCTION
# ==============================================================================

def calculate_discriminator_loss(real_logits, fake_logits):
    real_labels = create_real_labels(
        real_logits.size(0),
        real_logits.device
    )

    fake_labels = create_fake_labels(
        fake_logits.size(0),
        fake_logits.device
    )

    real_loss = DISCRIMINATOR_LOSS_FUNCTION(
        real_logits,
        real_labels
    )

    fake_loss = DISCRIMINATOR_LOSS_FUNCTION(
        fake_logits,
        fake_labels
    )

    return (real_loss + fake_loss) / 2.0

print("=" * 100)
print("PART I7 — DISCRIMINATOR LOSS FUNCTION")
print("=" * 100)

print("Discriminator loss function defined successfully.")

====================================================================================================
PART I7 — DISCRIMINATOR LOSS FUNCTION
====================================================================================================
Discriminator loss function defined successfully.

In [76]:
# ==============================================================================
# PART I8 — GENERATOR LOSS FUNCTION
# ==============================================================================

def calculate_generator_loss(fake_logits):
    real_labels = create_real_labels(
        fake_logits.size(0),
        fake_logits.device
    )

    return GENERATOR_LOSS_FUNCTION(
        fake_logits,
        real_labels
    )

print("=" * 100)
print("PART I8 — GENERATOR LOSS FUNCTION")
print("=" * 100)

print("Generator loss function defined successfully.")

====================================================================================================
PART I8 — GENERATOR LOSS FUNCTION
====================================================================================================
Generator loss function defined successfully.

In [77]:
# ==============================================================================
# PART I9 — GAN LOSS FUNCTION TEST
# ==============================================================================

print("=" * 100)
print("PART I9 — GAN LOSS FUNCTION TEST")
print("=" * 100)

TEST_BATCH_SIZE = 8

test_real_logits = torch.randn(
    TEST_BATCH_SIZE,
    1,
    device=DEVICE
)

test_fake_logits = torch.randn(
    TEST_BATCH_SIZE,
    1,
    device=DEVICE
)

test_discriminator_loss = calculate_discriminator_loss(
    test_real_logits,
    test_fake_logits
)

test_generator_loss = calculate_generator_loss(
    test_fake_logits
)

print(f"Discriminator Loss : {test_discriminator_loss.item():.6f}")
print(f"Generator Loss     : {test_generator_loss.item():.6f}")

if not torch.isfinite(test_discriminator_loss):
    raise RuntimeError("Discriminator loss test failed.")

if not torch.isfinite(test_generator_loss):
    raise RuntimeError("Generator loss test failed.")

print("\nGAN loss function test: PASS")

====================================================================================================
PART I9 — GAN LOSS FUNCTION TEST
====================================================================================================
Discriminator Loss : 0.630111
Generator Loss     : 0.794003

GAN loss function test: PASS

In [78]:
# ==============================================================================
# PART J1 — OPTIMIZER CONFIGURATION
# ==============================================================================

print("=" * 100)
print("PART J1 — OPTIMIZER CONFIGURATION")
print("=" * 100)

OPTIMIZER_NAME = "Adam"
OPTIMIZER_LEARNING_RATE = DP_LEARNING_RATE
OPTIMIZER_BETA1 = DP_BETA1
OPTIMIZER_BETA2 = DP_BETA2
OPTIMIZER_EPSILON = 1e-8

print(f"Optimizer    : {OPTIMIZER_NAME}")
print(f"Learning Rate : {OPTIMIZER_LEARNING_RATE}")
print(f"Beta 1        : {OPTIMIZER_BETA1}")
print(f"Beta 2        : {OPTIMIZER_BETA2}")
print(f"Epsilon       : {OPTIMIZER_EPSILON}")

====================================================================================================
PART J1 — OPTIMIZER CONFIGURATION
====================================================================================================
Optimizer    : Adam
Learning Rate : 0.0002
Beta 1        : 0.5
Beta 2        : 0.999
Epsilon       : 1e-08

In [79]:
# ==============================================================================
# PART J2 — OPTIMIZER PARAMETER VALIDATION
# ==============================================================================

print("=" * 100)
print("PART J2 — OPTIMIZER PARAMETER VALIDATION")
print("=" * 100)

OPTIMIZER_PARAMETER_CHECKS = {
    "Learning Rate": OPTIMIZER_LEARNING_RATE > 0,
    "Beta1": 0 <= OPTIMIZER_BETA1 < 1,
    "Beta2": 0 <= OPTIMIZER_BETA2 < 1,
    "Epsilon": OPTIMIZER_EPSILON > 0
}

for parameter, status in OPTIMIZER_PARAMETER_CHECKS.items():
    print(f"{parameter:15s}: {'PASS' if status else 'FAIL'}")

if not all(OPTIMIZER_PARAMETER_CHECKS.values()):
    raise ValueError(
        "One or more optimizer parameters are invalid."
    )

print("\nOptimizer configuration validation: PASS")

====================================================================================================
PART J2 — OPTIMIZER PARAMETER VALIDATION
====================================================================================================
Learning Rate  : PASS
Beta1          : PASS
Beta2          : PASS
Epsilon        : PASS

Optimizer configuration validation: PASS

In [80]:
# ==============================================================================
# PART J3 — GENERATOR OPTIMIZER CREATION
# ==============================================================================

print("=" * 100)
print("PART J3 — GENERATOR OPTIMIZER CREATION")
print("=" * 100)

GENERATOR_OPTIMIZERS = {}

for dataset in DATASETS:
    generator = GENERATORS[dataset]
    generator.train()

    generator_optimizer = torch.optim.Adam(
        generator.parameters(),
        lr=OPTIMIZER_LEARNING_RATE,
        betas=(OPTIMIZER_BETA1, OPTIMIZER_BETA2),
        eps=OPTIMIZER_EPSILON
    )

    GENERATOR_OPTIMIZERS[dataset] = generator_optimizer

    trainable_parameters = sum(
        parameter.numel()
        for parameter in generator.parameters()
        if parameter.requires_grad
    )

    print()
    print(dataset)
    print("Generator Optimizer : Adam")
    print(f"Learning Rate       : {OPTIMIZER_LEARNING_RATE}")
    print(f"Trainable Parameters: {trainable_parameters:,}")

print()
print("Generator optimizers created successfully.")

====================================================================================================
PART J3 — GENERATOR OPTIMIZER CREATION
====================================================================================================

Adult Income
Generator Optimizer : Adam
Learning Rate       : 0.0002
Trainable Parameters: 233,999

Bank Marketing
Generator Optimizer : Adam
Learning Rate       : 0.0002
Trainable Parameters: 234,257

diabetes_130us
Generator Optimizer : Adam
Learning Rate       : 0.0002
Trainable Parameters: 238,256

Generator optimizers created successfully.

In [81]:
# ==============================================================================
# PART J4 — DISCRIMINATOR OPTIMIZER CREATION
# ==============================================================================

print("=" * 100)
print("PART J4 — DISCRIMINATOR OPTIMIZER CREATION")
print("=" * 100)

DISCRIMINATOR_OPTIMIZERS = {}

for dataset in DATASETS:
    discriminator = DISCRIMINATORS[dataset]
    discriminator.train()

    discriminator_optimizer = torch.optim.Adam(
        discriminator.parameters(),
        lr=OPTIMIZER_LEARNING_RATE,
        betas=(OPTIMIZER_BETA1, OPTIMIZER_BETA2),
        eps=OPTIMIZER_EPSILON
    )

    DISCRIMINATOR_OPTIMIZERS[dataset] = discriminator_optimizer

    trainable_parameters = sum(
        parameter.numel()
        for parameter in discriminator.parameters()
        if parameter.requires_grad
    )

    print()
    print(dataset)
    print("Discriminator Optimizer : Adam")
    print(f"Learning Rate           : {OPTIMIZER_LEARNING_RATE}")
    print(f"Trainable Parameters    : {trainable_parameters:,}")

print()
print("Discriminator optimizers created successfully.")

====================================================================================================
PART J4 — DISCRIMINATOR OPTIMIZER CREATION
====================================================================================================

Adult Income
Discriminator Optimizer : Adam
Learning Rate           : 0.0002
Trainable Parameters    : 174,337

Bank Marketing
Discriminator Optimizer : Adam
Learning Rate           : 0.0002
Trainable Parameters    : 175,361

diabetes_130us
Discriminator Optimizer : Adam
Learning Rate           : 0.0002
Trainable Parameters    : 191,233

Discriminator optimizers created successfully.

In [82]:
# ==============================================================================
# PART K1 — DIFFERENTIAL PRIVACY PARAMETERS
# ==============================================================================

print("=" * 100)
print("PART K1 — DIFFERENTIAL PRIVACY PARAMETERS")
print("=" * 100)

DP_PRIVACY_BUDGET = PRIVACY_BUDGET
DP_DELTA = PRIVACY_DELTA
DP_MAX_GRAD_NORM = MAX_GRAD_NORM
DP_BATCH_SIZE = DP_BATCH_SIZE
DP_EPOCHS = DP_EPOCHS

DP_CONFIG = {
    "Privacy Budget (epsilon)": DP_PRIVACY_BUDGET,
    "Privacy Delta (delta)": DP_DELTA,
    "Maximum Gradient Norm": DP_MAX_GRAD_NORM,
    "Batch Size": DP_BATCH_SIZE,
    "Training Epochs": DP_EPOCHS
}

for key, value in DP_CONFIG.items():
    print(f"{key:30s}: {value}")

====================================================================================================
PART K1 — DIFFERENTIAL PRIVACY PARAMETERS
====================================================================================================
Privacy Budget (epsilon)      : 4.0
Privacy Delta (delta)         : 1e-05
Maximum Gradient Norm         : 1.0
Batch Size                    : 256
Training Epochs               : 100

In [83]:
# ==============================================================================
# PART K2 — DP TRAINING DATA PREPARATION
# ==============================================================================

from torch.utils.data import TensorDataset, DataLoader

print("=" * 100)
print("PART K42— DP TRAINING DATA PREPARATION")
print("=" * 100)

DP_TRAIN_DATASETS = {}
DP_TRAIN_TENSORS = {}
DP_TRAIN_DATALOADERS = {}

for dataset in DATASETS:

    print()
    print("-" * 80)
    print(dataset)

    train_dataframe = TRAIN_DATASETS[dataset].copy()

    # --------------------------------------------------------------------------
    # Numeric Validation
    # --------------------------------------------------------------------------

    non_numeric_columns = train_dataframe.select_dtypes(
        exclude=["number"]
    ).columns.tolist()

    if non_numeric_columns:
        raise TypeError(
            f"{dataset} contains non-numeric columns: "
            f"{non_numeric_columns}"
        )

    # --------------------------------------------------------------------------
    # Tensor Conversion
    # --------------------------------------------------------------------------

    train_tensor = torch.tensor(
        train_dataframe.to_numpy(),
        dtype=torch.float32
    )

    # --------------------------------------------------------------------------
    # Finite-Value Validation
    # --------------------------------------------------------------------------

    if not torch.isfinite(train_tensor).all():

        raise ValueError(
            f"{dataset} contains NaN or infinite values."
        )

    # --------------------------------------------------------------------------
    # Tensor Dataset
    # --------------------------------------------------------------------------

    train_dataset = TensorDataset(
        train_tensor
    )

    # --------------------------------------------------------------------------
    # DataLoader
    # --------------------------------------------------------------------------

    train_loader = DataLoader(
        train_dataset,
        batch_size=DP_BATCH_SIZE,
        shuffle=True,
        drop_last=False
    )

    # --------------------------------------------------------------------------
    # Store Objects
    # --------------------------------------------------------------------------

    DP_TRAIN_DATASETS[dataset] = train_dataset
    DP_TRAIN_TENSORS[dataset] = train_tensor
    DP_TRAIN_DATALOADERS[dataset] = train_loader

    # --------------------------------------------------------------------------
    # Verification
    # --------------------------------------------------------------------------

    print(
        f"Rows              : {len(train_dataframe)}"
    )

    print(
        f"Features          : {train_dataframe.shape[1]}"
    )

    print(
        f"Tensor Shape      : {tuple(train_tensor.shape)}"
    )

    print(
        f"DataLoader Batches : {len(train_loader)}"
    )

    print(
        f"Batch Size         : {DP_BATCH_SIZE}"
    )

print()
print("DP training datasets and DataLoaders prepared successfully.")

====================================================================================================
PART K42— DP TRAINING DATA PREPARATION
====================================================================================================

--------------------------------------------------------------------------------
Adult Income
Rows              : 22760
Features          : 15
Tensor Shape      : (22760, 15)
DataLoader Batches : 89
Batch Size         : 256

--------------------------------------------------------------------------------
Bank Marketing
Rows              : 31647
Features          : 17
Tensor Shape      : (31647, 17)
DataLoader Batches : 124
Batch Size         : 256

--------------------------------------------------------------------------------
diabetes_130us
Rows              : 71236
Features          : 48
Tensor Shape      : (71236, 48)
DataLoader Batches : 279
Batch Size         : 256

DP training datasets and DataLoaders prepared successfully.

In [84]:
# ==============================================================================
# PART K3 — DP TRAINING DATA VALIDATION
# ==============================================================================

print("=" * 100)
print("PART K3 — DP TRAINING DATA VALIDATION")
print("=" * 100)

DP_DATA_VALIDATION = {}

for dataset in DATASETS:

    train_dataframe = TRAIN_DATASETS[dataset]
    train_tensor = DP_TRAIN_TENSORS[dataset]
    train_loader = DP_TRAIN_DATALOADERS[dataset]

    expected_rows = len(train_dataframe)
    expected_features = train_dataframe.shape[1]

    actual_rows = train_tensor.shape[0]
    actual_features = train_tensor.shape[1]

    # --------------------------------------------------------------------------
    # Shape Validation
    # --------------------------------------------------------------------------

    tensor_shape_check = (
        actual_rows == expected_rows
        and actual_features == expected_features
    )

    # --------------------------------------------------------------------------
    # DataLoader Validation
    # --------------------------------------------------------------------------

    loader_check = (
        len(train_loader) > 0
        and train_loader.batch_size == DP_BATCH_SIZE
        and len(train_loader.dataset) == expected_rows
    )

    # --------------------------------------------------------------------------
    # Tensor Validation
    # --------------------------------------------------------------------------

    dtype_check = (
        train_tensor.dtype == torch.float32
    )

    finite_check = bool(
        torch.isfinite(train_tensor).all().item()
    )

    # --------------------------------------------------------------------------
    # Overall Status
    # --------------------------------------------------------------------------

    status = (
        tensor_shape_check
        and loader_check
        and dtype_check
        and finite_check
    )

    DP_DATA_VALIDATION[dataset] = status

    print()
    print(dataset)

    print(
        f"Expected Shape : "
        f"({expected_rows}, {expected_features})"
    )

    print(
        f"Actual Shape   : "
        f"{tuple(train_tensor.shape)}"
    )

    print(
        f"DataLoader Size: "
        f"{len(train_loader.dataset)}"
    )

    print(
        f"Batch Size     : "
        f"{train_loader.batch_size}"
    )

    print(
        f"Shape Check    : "
        f"{'PASS' if tensor_shape_check else 'FAIL'}"
    )

    print(
        f"Loader Check   : "
        f"{'PASS' if loader_check else 'FAIL'}"
    )

    print(
        f"Dtype Check    : "
        f"{'PASS' if dtype_check else 'FAIL'}"
    )

    print(
        f"Finite Check   : "
        f"{'PASS' if finite_check else 'FAIL'}"
    )

    print(
        f"Overall        : "
        f"{'PASS' if status else 'FAIL'}"
    )

if not all(DP_DATA_VALIDATION.values()):

    raise RuntimeError(
        "DP training data validation failed."
    )

print()
print(
    "All DP training datasets validated successfully."
)

====================================================================================================
PART K3 — DP TRAINING DATA VALIDATION
====================================================================================================

Adult Income
Expected Shape : (22760, 15)
Actual Shape   : (22760, 15)
DataLoader Size: 22760
Batch Size     : 256
Shape Check    : PASS
Loader Check   : PASS
Dtype Check    : PASS
Finite Check   : PASS
Overall        : PASS

Bank Marketing
Expected Shape : (31647, 17)
Actual Shape   : (31647, 17)
DataLoader Size: 31647
Batch Size     : 256
Shape Check    : PASS
Loader Check   : PASS
Dtype Check    : PASS
Finite Check   : PASS
Overall        : PASS

diabetes_130us
Expected Shape : (71236, 48)
Actual Shape   : (71236, 48)
DataLoader Size: 71236
Batch Size     : 256
Shape Check    : PASS
Loader Check   : PASS
Dtype Check    : PASS
Finite Check   : PASS
Overall        : PASS

All DP training datasets validated successfully.

In [85]:
# ==============================================================================
# PART K4 — PRIVACY ENGINE INITIALIZATION
# ==============================================================================

print("=" * 100)
print("PART K4 — PRIVACY ENGINE INITIALIZATION")
print("=" * 100)

from opacus import PrivacyEngine

PRIVACY_ACCOUNTANT = "rdp"

PRIVACY_ENGINES = {}

for dataset in DATASETS:

    privacy_engine = PrivacyEngine(
        accountant=PRIVACY_ACCOUNTANT
    )

    PRIVACY_ENGINES[dataset] = privacy_engine

    print()
    print(dataset)

    print(
        "PrivacyEngine Initialized : PASS"
    )

    print(
        f"Accountant               : "
        f"{PRIVACY_ACCOUNTANT.upper()}"
    )

print()

if len(PRIVACY_ENGINES) != len(DATASETS):

    raise RuntimeError(
        "PrivacyEngine initialization failed "
        "for one or more datasets."
    )

print(
    "PrivacyEngine objects created "
    "successfully for all datasets."
)

====================================================================================================
PART K4 — PRIVACY ENGINE INITIALIZATION
====================================================================================================

Adult Income
PrivacyEngine Initialized : PASS
Accountant               : RDP

Bank Marketing
PrivacyEngine Initialized : PASS
Accountant               : RDP

diabetes_130us
PrivacyEngine Initialized : PASS
Accountant               : RDP

PrivacyEngine objects created successfully for all datasets.

In [86]:
# ==============================================================================
# PART K5 — PRIVACY ENGINE ATTACHMENT
# ==============================================================================

print("=" * 100)
print("PART K5 — PRIVACY ENGINE ATTACHMENT")
print("=" * 100)

from opacus.accountants.utils import get_noise_multiplier

DP_PRIVATIZATION_RESULTS = {}

PRIVATE_DISCRIMINATORS = {}
PRIVATE_DISCRIMINATOR_OPTIMIZERS = {}
PRIVATE_TRAIN_LOADERS = {}

NOISE_MULTIPLIERS = {}
TARGET_EPSILON = {}
TARGET_DELTA = {}

for dataset in DATASETS:

    print()
    print("-" * 80)
    print(dataset)

    discriminator = DISCRIMINATORS[dataset]

    discriminator_optimizer = (
        DISCRIMINATOR_OPTIMIZERS[dataset]
    )

    train_loader = (
        DP_TRAIN_DATALOADERS[dataset]
    )

    privacy_engine = (
        PRIVACY_ENGINES[dataset]
    )

    # --------------------------------------------------------------------------
    # Dataset-Specific Sampling Rate
    # --------------------------------------------------------------------------

    sample_rate = (
        DP_BATCH_SIZE /
        len(train_loader.dataset)
    )

    if not 0 < sample_rate <= 1:

        raise ValueError(
            f"{dataset}: invalid sampling rate "
            f"{sample_rate:.8f}"
        )

    # --------------------------------------------------------------------------
    # Dataset-Specific Noise Multiplier
    # --------------------------------------------------------------------------

    noise_multiplier = get_noise_multiplier(
        target_epsilon=DP_PRIVACY_BUDGET,
        target_delta=DP_DELTA,
        sample_rate=sample_rate,
        epochs=DP_EPOCHS,
        accountant=PRIVACY_ACCOUNTANT
    )

    if not torch.isfinite(
        torch.tensor(noise_multiplier)
    ):

        raise RuntimeError(
            f"{dataset}: invalid noise multiplier "
            f"{noise_multiplier}"
        )

    NOISE_MULTIPLIERS[dataset] = noise_multiplier
    TARGET_EPSILON[dataset] = DP_PRIVACY_BUDGET
    TARGET_DELTA[dataset] = DP_DELTA

    print(
        f"Sample Rate            : "
        f"{sample_rate:.8f}"
    )

    print(
        f"Noise Multiplier       : "
        f"{noise_multiplier:.8f}"
    )

    # --------------------------------------------------------------------------
    # Attach PrivacyEngine
    # --------------------------------------------------------------------------

    (
        private_discriminator,
        private_optimizer,
        private_loader
    ) = privacy_engine.make_private(
        module=discriminator,
        optimizer=discriminator_optimizer,
        data_loader=train_loader,
        noise_multiplier=noise_multiplier,
        max_grad_norm=DP_MAX_GRAD_NORM,
        poisson_sampling=True
    )

    # --------------------------------------------------------------------------
    # Store Privatized Components
    # --------------------------------------------------------------------------

    PRIVATE_DISCRIMINATORS[dataset] = (
        private_discriminator
    )

    PRIVATE_DISCRIMINATOR_OPTIMIZERS[dataset] = (
        private_optimizer
    )

    PRIVATE_TRAIN_LOADERS[dataset] = (
        private_loader
    )

    # --------------------------------------------------------------------------
    # Verify Privatization
    # --------------------------------------------------------------------------

    model_private = (
        private_discriminator is not discriminator
        or hasattr(
            private_discriminator,
            "grad_sample"
        )
    )

    optimizer_private = (
        hasattr(
            private_optimizer,
            "noise_multiplier"
        )
        and hasattr(
            private_optimizer,
            "max_grad_norm"
        )
    )

    loader_private = (
        private_loader is not train_loader
        or private_loader.__class__.__name__
        == "DPDataLoader"
    )

    status = (
        model_private
        and optimizer_private
        and loader_private
    )

    DP_PRIVATIZATION_RESULTS[dataset] = status

    print(
        f"Model Privatization    : "
        f"{'PASS' if model_private else 'FAIL'}"
    )

    print(
        f"Optimizer Privatization: "
        f"{'PASS' if optimizer_private else 'FAIL'}"
    )

    print(
        f"DataLoader Privatization: "
        f"{'PASS' if loader_private else 'FAIL'}"
    )

    print(
        f"Overall                : "
        f"{'PASS' if status else 'FAIL'}"
    )

    if not status:

        raise RuntimeError(
            f"{dataset}: PrivacyEngine attachment "
            f"verification failed."
        )

# ------------------------------------------------------------------------------
# Final Verification
# ------------------------------------------------------------------------------

if not all(
    DP_PRIVATIZATION_RESULTS.values()
):

    raise RuntimeError(
        "PrivacyEngine attachment failed for "
        "one or more datasets."
    )

print()
print("=" * 100)
print("PART K8 COMPLETED SUCCESSFULLY")
print("All Discriminators successfully privatized.")
print("=" * 100)

====================================================================================================
PART K5 — PRIVACY ENGINE ATTACHMENT
====================================================================================================

--------------------------------------------------------------------------------
Adult Income
Sample Rate            : 0.01124780
Noise Multiplier       : 1.42333984
Model Privatization    : PASS
Optimizer Privatization: PASS
DataLoader Privatization: PASS
Overall                : PASS

--------------------------------------------------------------------------------
Bank Marketing
Sample Rate            : 0.00808923
Noise Multiplier       : 1.25488281
Model Privatization    : PASS
Optimizer Privatization: PASS
DataLoader Privatization: PASS
Overall                : PASS

--------------------------------------------------------------------------------
diabetes_130us
Sample Rate            : 0.00359369
Noise Multiplier       : 0.95825195
Model Privatization    : PASS
Optimizer Privatization: PASS
DataLoader Privatization: PASS
Overall                : PASS

====================================================================================================
PART K8 COMPLETED SUCCESSFULLY
All Discriminators successfully privatized.
====================================================================================================

In [87]:
# ==============================================================================
# PART K7 — PRE-PRIVATIZATION MODEL CHECK
# ==============================================================================

print("=" * 100)
print("PART K7 — PRE-PRIVATIZATION MODEL CHECK")
print("=" * 100)

PRE_DP_MODEL_VALIDATION = {}

for dataset in DATASETS:

    discriminator = DISCRIMINATORS[dataset]

    dimension_check = (
        discriminator.input_dimension
        == TRAIN_DATASETS[dataset].shape[1]
    )

    training_mode_check = (
        discriminator.training
    )

    parameter_check = all(
        parameter.requires_grad
        for parameter in discriminator.parameters()
    )

    status = (
        dimension_check
        and training_mode_check
        and parameter_check
    )

    PRE_DP_MODEL_VALIDATION[dataset] = status

    print()
    print(dataset)

    print(
        f"Input Dimension : "
        f"{'PASS' if dimension_check else 'FAIL'}"
    )

    print(
        f"Training Mode   : "
        f"{'PASS' if training_mode_check else 'FAIL'}"
    )

    print(
        f"Parameters      : "
        f"{'PASS' if parameter_check else 'FAIL'}"
    )

    print(
        f"Overall         : "
        f"{'PASS' if status else 'FAIL'}"
    )

if not all(
    PRE_DP_MODEL_VALIDATION.values()
):

    raise RuntimeError(
        "Pre-privatization model validation failed."
    )

print()
print(
    "All Discriminators passed "
    "pre-privatization model validation."
)

====================================================================================================
PART K7 — PRE-PRIVATIZATION MODEL CHECK
====================================================================================================

Adult Income
Input Dimension : PASS
Training Mode   : PASS
Parameters      : PASS
Overall         : PASS

Bank Marketing
Input Dimension : PASS
Training Mode   : PASS
Parameters      : PASS
Overall         : PASS

diabetes_130us
Input Dimension : PASS
Training Mode   : PASS
Parameters      : PASS
Overall         : PASS

All Discriminators passed pre-privatization model validation.

In [88]:
# ==============================================================================
# PART K9 — PRIVATIZED MODEL TYPE VALIDATION
# ==============================================================================

print("=" * 100)
print("PART K9 — PRIVATIZED MODEL TYPE VALIDATION")
print("=" * 100)

PRIVATIZED_MODEL_VALIDATION = {}

for dataset in DATASETS:

    print()
    print("-" * 80)
    print(dataset)

    # --------------------------------------------------------------------------
    # Check Privatized Objects Exist
    # --------------------------------------------------------------------------

    model_exists = (
        dataset in PRIVATE_DISCRIMINATORS
    )

    optimizer_exists = (
        dataset in PRIVATE_DISCRIMINATOR_OPTIMIZERS
    )

    loader_exists = (
        dataset in PRIVATE_TRAIN_LOADERS
    )

    # --------------------------------------------------------------------------
    # Handle Missing Privatized Objects
    # --------------------------------------------------------------------------

    if not (
        model_exists
        and optimizer_exists
        and loader_exists
    ):

        PRIVATIZED_MODEL_VALIDATION[dataset] = False

        print(
            "Discriminator Object : "
            f"{'PASS' if model_exists else 'FAIL'}"
        )

        print(
            "Optimizer Object     : "
            f"{'PASS' if optimizer_exists else 'FAIL'}"
        )

        print(
            "DataLoader Object    : "
            f"{'PASS' if loader_exists else 'FAIL'}"
        )

        print(
            "Opacus Wrapper       : FAIL"
        )

        print(
            "Training Mode        : FAIL"
        )

        print(
            "Overall              : FAIL"
        )

        continue

    # --------------------------------------------------------------------------
    # Retrieve Privatized Components
    # --------------------------------------------------------------------------

    discriminator = (
        PRIVATE_DISCRIMINATORS[dataset]
    )

    optimizer = (
        PRIVATE_DISCRIMINATOR_OPTIMIZERS[dataset]
    )

    data_loader = (
        PRIVATE_TRAIN_LOADERS[dataset]
    )

    # --------------------------------------------------------------------------
    # Object Validation
    # --------------------------------------------------------------------------

    model_check = (
        discriminator is not None
    )

    optimizer_check = (
        optimizer is not None
    )

    loader_check = (
        data_loader is not None
    )

    # --------------------------------------------------------------------------
    # Opacus Wrapper Validation
    # --------------------------------------------------------------------------

    discriminator_class_name = (
        discriminator.__class__.__name__
    )

    opacus_wrapper_check = (
        "GradSampleModule"
        in discriminator_class_name
    )

    # --------------------------------------------------------------------------
    # Training Mode Validation
    # --------------------------------------------------------------------------

    training_mode_check = (
        discriminator.training
    )

    # --------------------------------------------------------------------------
    # Overall Validation
    # --------------------------------------------------------------------------

    status = (
        model_check
        and optimizer_check
        and loader_check
        and opacus_wrapper_check
        and training_mode_check
    )

    PRIVATIZED_MODEL_VALIDATION[
        dataset
    ] = status

    # --------------------------------------------------------------------------
    # Display Results
    # --------------------------------------------------------------------------

    print(
        "Discriminator Object : "
        f"{'PASS' if model_check else 'FAIL'}"
    )

    print(
        "Optimizer Object     : "
        f"{'PASS' if optimizer_check else 'FAIL'}"
    )

    print(
        "DataLoader Object    : "
        f"{'PASS' if loader_check else 'FAIL'}"
    )

    print(
        "Opacus Wrapper       : "
        f"{'PASS' if opacus_wrapper_check else 'FAIL'}"
    )

    print(
        "Training Mode        : "
        f"{'PASS' if training_mode_check else 'FAIL'}"
    )

    print(
        "Overall              : "
        f"{'PASS' if status else 'FAIL'}"
    )

# ==============================================================================
# PRIVATIZED MODEL VALIDATION SUMMARY
# ==============================================================================

print()
print("=" * 100)
print("PRIVATIZED MODEL VALIDATION SUMMARY")
print("=" * 100)

for dataset, status in PRIVATIZED_MODEL_VALIDATION.items():

    print(
        f"{dataset:25s}: "
        f"{'PASS' if status else 'FAIL'}"
    )

# ==============================================================================
# FINAL VALIDATION
# ==============================================================================

if not all(
    PRIVATIZED_MODEL_VALIDATION.values()
):

    raise RuntimeError(
        "Privatized model validation failed. "
        "Do not proceed to the next DP stage."
    )

print()
print("=" * 100)
print("PART K9 COMPLETED SUCCESSFULLY")
print("All privatized models validated successfully.")
print("=" * 100)

====================================================================================================
PART K9 — PRIVATIZED MODEL TYPE VALIDATION
====================================================================================================

--------------------------------------------------------------------------------
Adult Income
Discriminator Object : PASS
Optimizer Object     : PASS
DataLoader Object    : PASS
Opacus Wrapper       : PASS
Training Mode        : PASS
Overall              : PASS

--------------------------------------------------------------------------------
Bank Marketing
Discriminator Object : PASS
Optimizer Object     : PASS
DataLoader Object    : PASS
Opacus Wrapper       : PASS
Training Mode        : PASS
Overall              : PASS

--------------------------------------------------------------------------------
diabetes_130us
Discriminator Object : PASS
Optimizer Object     : PASS
DataLoader Object    : PASS
Opacus Wrapper       : PASS
Training Mode        : PASS
Overall              : PASS

====================================================================================================
PRIVATIZED MODEL VALIDATION SUMMARY
====================================================================================================
Adult Income             : PASS
Bank Marketing           : PASS
diabetes_130us           : PASS

====================================================================================================
PART K9 COMPLETED SUCCESSFULLY
All privatized models validated successfully.
====================================================================================================

In [89]:
# ==============================================================================
# PART K10 — PRIVACY ACCOUNTING VALIDATION
# ==============================================================================

print("=" * 100)
print("PART K10 — PRIVACY ACCOUNTING VALIDATION")
print("=" * 100)

PRIVACY_ACCOUNTING_RESULTS = {}
ACCOUNTANT_TYPES = {}

for dataset in DATASETS:

    print()
    print(dataset)

    try:
        # ----------------------------------------------------------------------
        # Retrieve Privacy Engine
        # ----------------------------------------------------------------------

        privacy_engine = PRIVACY_ENGINES[dataset]

        # ----------------------------------------------------------------------
        # Retrieve Privatized Components
        # ----------------------------------------------------------------------

        private_discriminator = (
            PRIVATE_DISCRIMINATORS[dataset]
        )

        private_optimizer = (
            PRIVATE_DISCRIMINATOR_OPTIMIZERS[dataset]
        )

        private_loader = (
            PRIVATE_TRAIN_LOADERS[dataset]
        )

        # ----------------------------------------------------------------------
        # Accountant Validation
        # ----------------------------------------------------------------------

        accountant = privacy_engine.accountant

        accountant_name = type(
            accountant
        ).__name__

        ACCOUNTANT_TYPES[dataset] = accountant_name

        accountant_check = (
            "RDP"
            in accountant_name.upper()
        )

        # ----------------------------------------------------------------------
        # Privacy Engine Validation
        # ----------------------------------------------------------------------

        engine_check = (
            privacy_engine is not None
        )

        # ----------------------------------------------------------------------
        # Privatized Component Validation
        # ----------------------------------------------------------------------

        model_check = (
            private_discriminator is not None
        )

        optimizer_check = (
            private_optimizer is not None
        )

        loader_check = (
            private_loader is not None
        )

        # ----------------------------------------------------------------------
        # Training Configuration Validation
        # ----------------------------------------------------------------------

        epsilon_check = (
            DP_PRIVACY_BUDGET > 0
        )

        delta_check = (
            0 < DP_DELTA < 1
        )

        grad_norm_check = (
            DP_MAX_GRAD_NORM > 0
        )

        epochs_check = (
            DP_EPOCHS > 0
        )

        # ----------------------------------------------------------------------
        # Overall Accounting Readiness
        # ----------------------------------------------------------------------

        status = (
            engine_check
            and accountant_check
            and model_check
            and optimizer_check
            and loader_check
            and epsilon_check
            and delta_check
            and grad_norm_check
            and epochs_check
        )

        PRIVACY_ACCOUNTING_RESULTS[dataset] = status

        # ----------------------------------------------------------------------
        # Verification Output
        # ----------------------------------------------------------------------

        print(
            f"Accountant Type       : {accountant_name}"
        )

        print(
            f"Target Epsilon        : {DP_PRIVACY_BUDGET}"
        )

        print(
            f"Target Delta          : {DP_DELTA}"
        )

        print(
            f"Maximum Grad Norm     : {DP_MAX_GRAD_NORM}"
        )

        print(
            f"Training Epochs       : {DP_EPOCHS}"
        )

        print(
            f"Privacy Engine        : "
            f"{'PASS' if engine_check else 'FAIL'}"
        )

        print(
            f"RDP Accountant        : "
            f"{'PASS' if accountant_check else 'FAIL'}"
        )

        print(
            f"Privatized Model      : "
            f"{'PASS' if model_check else 'FAIL'}"
        )

        print(
            f"Privatized Optimizer  : "
            f"{'PASS' if optimizer_check else 'FAIL'}"
        )

        print(
            f"Privatized DataLoader : "
            f"{'PASS' if loader_check else 'FAIL'}"
        )

        print(
            f"Epsilon Configuration : "
            f"{'PASS' if epsilon_check else 'FAIL'}"
        )

        print(
            f"Delta Configuration   : "
            f"{'PASS' if delta_check else 'FAIL'}"
        )

        print(
            f"Gradient Norm         : "
            f"{'PASS' if grad_norm_check else 'FAIL'}"
        )

        print(
            f"Training Epochs       : "
            f"{'PASS' if epochs_check else 'FAIL'}"
        )

        print(
            f"Accounting Status     : "
            f"{'READY' if status else 'FAIL'}"
        )

    except Exception as error:

        PRIVACY_ACCOUNTING_RESULTS[dataset] = False

        print(
            "Privacy accountant validation error:"
        )

        print(
            f"{type(error).__name__}: {error}"
        )

# ==============================================================================
# PRIVACY ACCOUNTING SUMMARY
# ==============================================================================

print()
print("=" * 100)
print("PRIVACY ACCOUNTING SUMMARY")
print("=" * 100)

for dataset, status in PRIVACY_ACCOUNTING_RESULTS.items():

    print(
        f"{dataset:20s} : "
        f"{'PASS' if status else 'FAIL'}"
    )

print("=" * 100)

# ==============================================================================
# FINAL VALIDATION
# ==============================================================================

if not all(
    PRIVACY_ACCOUNTING_RESULTS.values()
):

    raise RuntimeError(
        "Privacy accounting validation failed. "
        "Do not proceed to DP training."
    )

print()
print(
    "Privacy accounting infrastructure validated successfully."
)

print(
    "Target privacy budget is configured."
)

print(
    "Actual epsilon expenditure will be evaluated "
    "after DP training steps."
)

====================================================================================================
PART K10 — PRIVACY ACCOUNTING VALIDATION
====================================================================================================

Adult Income
Accountant Type       : RDPAccountant
Target Epsilon        : 4.0
Target Delta          : 1e-05
Maximum Grad Norm     : 1.0
Training Epochs       : 100
Privacy Engine        : PASS
RDP Accountant        : PASS
Privatized Model      : PASS
Privatized Optimizer  : PASS
Privatized DataLoader : PASS
Epsilon Configuration : PASS
Delta Configuration   : PASS
Gradient Norm         : PASS
Training Epochs       : PASS
Accounting Status     : READY

Bank Marketing
Accountant Type       : RDPAccountant
Target Epsilon        : 4.0
Target Delta          : 1e-05
Maximum Grad Norm     : 1.0
Training Epochs       : 100
Privacy Engine        : PASS
RDP Accountant        : PASS
Privatized Model      : PASS
Privatized Optimizer  : PASS
Privatized DataLoader : PASS
Epsilon Configuration : PASS
Delta Configuration   : PASS
Gradient Norm         : PASS
Training Epochs       : PASS
Accounting Status     : READY

diabetes_130us
Accountant Type       : RDPAccountant
Target Epsilon        : 4.0
Target Delta          : 1e-05
Maximum Grad Norm     : 1.0
Training Epochs       : 100
Privacy Engine        : PASS
RDP Accountant        : PASS
Privatized Model      : PASS
Privatized Optimizer  : PASS
Privatized DataLoader : PASS
Epsilon Configuration : PASS
Delta Configuration   : PASS
Gradient Norm         : PASS
Training Epochs       : PASS
Accounting Status     : READY

====================================================================================================
PRIVACY ACCOUNTING SUMMARY
====================================================================================================
Adult Income         : PASS
Bank Marketing       : PASS
diabetes_130us       : PASS
====================================================================================================

Privacy accounting infrastructure validated successfully.
Target privacy budget is configured.
Actual epsilon expenditure will be evaluated after DP training steps.

In [90]:
# ==============================================================================
# PART K11 — PRIVATIZED DATALOADER VALIDATION
# ==============================================================================

print("=" * 100)
print("PART K11 — PRIVATIZED DATALOADER VALIDATION")
print("=" * 100)

PRIVATIZED_DATALOADER_VALIDATION = {}

for dataset in DATASETS:

    print()
    print(dataset)

    try:
        # ----------------------------------------------------------------------
        # Retrieve Privatized DataLoader
        # ----------------------------------------------------------------------

        data_loader = (
            PRIVATE_TRAIN_LOADERS[dataset]
        )

        loader_object_check = (
            data_loader is not None
        )

        if not loader_object_check:
            raise RuntimeError(
                "Privatized DataLoader is missing."
            )

        # ----------------------------------------------------------------------
        # DataLoader Batch Validation
        # ----------------------------------------------------------------------

        loader_length = len(data_loader)

        batch_count_check = (
            loader_length > 0
        )

        if not batch_count_check:
            raise RuntimeError(
                "Privatized DataLoader contains no batches."
            )

        # ----------------------------------------------------------------------
        # Retrieve First Batch
        # ----------------------------------------------------------------------

        first_batch = next(
            iter(data_loader)
        )

        batch_data = first_batch[0]

        batch_exists_check = (
            batch_data is not None
        )

        if not batch_exists_check:
            raise RuntimeError(
                "Privatized DataLoader returned an empty batch."
            )

        # ----------------------------------------------------------------------
        # Tensor Validation
        # ----------------------------------------------------------------------

        tensor_check = (
            torch.is_tensor(batch_data)
        )

        dimension_check = (
            batch_data.ndim == 2
        )

        dtype_check = (
            batch_data.dtype == torch.float32
        )

        finite_check = (
            torch.isfinite(batch_data).all().item()
        )

        # ----------------------------------------------------------------------
        # Feature Dimension Validation
        # ----------------------------------------------------------------------

        expected_features = (
            TRAIN_DATASETS[dataset].shape[1]
        )

        actual_features = (
            batch_data.shape[1]
        )

        feature_check = (
            actual_features
            == expected_features
        )

        # ----------------------------------------------------------------------
        # Batch Size Validation
        # ----------------------------------------------------------------------

        actual_batch_size = (
            batch_data.shape[0]
        )

        batch_size_check = (
            actual_batch_size > 0
        )

        # ----------------------------------------------------------------------
        # Overall Validation
        # ----------------------------------------------------------------------

        status = (
            loader_object_check
            and batch_count_check
            and batch_exists_check
            and tensor_check
            and dimension_check
            and dtype_check
            and finite_check
            and feature_check
            and batch_size_check
        )

        PRIVATIZED_DATALOADER_VALIDATION[
            dataset
        ] = status

        # ----------------------------------------------------------------------
        # Verification Output
        # ----------------------------------------------------------------------

        print(
            f"DataLoader Object  : "
            f"{'PASS' if loader_object_check else 'FAIL'}"
        )

        print(
            f"Batch Count        : "
            f"{loader_length}"
        )

        print(
            f"Batch Available    : "
            f"{'PASS' if batch_exists_check else 'FAIL'}"
        )

        print(
            f"Tensor Check       : "
            f"{'PASS' if tensor_check else 'FAIL'}"
        )

        print(
            f"Batch Shape        : "
            f"{tuple(batch_data.shape)}"
        )

        print(
            f"Expected Features  : "
            f"{expected_features}"
        )

        print(
            f"Actual Features    : "
            f"{actual_features}"
        )

        print(
            f"Feature Check      : "
            f"{'PASS' if feature_check else 'FAIL'}"
        )

        print(
            f"Dtype Check        : "
            f"{'PASS' if dtype_check else 'FAIL'}"
        )

        print(
            f"Finite Check       : "
            f"{'PASS' if finite_check else 'FAIL'}"
        )

        print(
            f"Batch Size         : "
            f"{actual_batch_size}"
        )

        print(
            f"Batch Size Check   : "
            f"{'PASS' if batch_size_check else 'FAIL'}"
        )

        print(
            f"Overall            : "
            f"{'PASS' if status else 'FAIL'}"
        )

    except Exception as error:

        PRIVATIZED_DATALOADER_VALIDATION[
            dataset
        ] = False

        print(
            "DataLoader validation error:"
        )

        print(
            f"{type(error).__name__}: {error}"
        )

# ==============================================================================
# PRIVATIZED DATALOADER SUMMARY
# ==============================================================================

print()
print("=" * 100)
print("PRIVATIZED DATALOADER SUMMARY")
print("=" * 100)

for dataset, status in PRIVATIZED_DATALOADER_VALIDATION.items():

    print(
        f"{dataset:20s} : "
        f"{'PASS' if status else 'FAIL'}"
    )

print("=" * 100)

# ==============================================================================
# FINAL VALIDATION
# ==============================================================================

if not all(
    PRIVATIZED_DATALOADER_VALIDATION.values()
):

    raise RuntimeError(
        "Privatized DataLoader validation failed. "
        "Do not proceed to DP training."
    )

print()
print(
    "All privatized DataLoaders validated successfully."
)

print(
    "DP training data pipeline is ready."
)

====================================================================================================
PART K11 — PRIVATIZED DATALOADER VALIDATION
====================================================================================================

Adult Income
DataLoader Object  : PASS
Batch Count        : 89
Batch Available    : PASS
Tensor Check       : PASS
Batch Shape        : (217, 15)
Expected Features  : 15
Actual Features    : 15
Feature Check      : PASS
Dtype Check        : PASS
Finite Check       : PASS
Batch Size         : 217
Batch Size Check   : PASS
Overall            : PASS

Bank Marketing
DataLoader Object  : PASS
Batch Count        : 124
Batch Available    : PASS
Tensor Check       : PASS
Batch Shape        : (242, 17)
Expected Features  : 17
Actual Features    : 17
Feature Check      : PASS
Dtype Check        : PASS
Finite Check       : PASS
Batch Size         : 242
Batch Size Check   : PASS
Overall            : PASS

diabetes_130us
DataLoader Object  : PASS
Batch Count        : 279
Batch Available    : PASS
Tensor Check       : PASS
Batch Shape        : (246, 48)
Expected Features  : 48
Actual Features    : 48
Feature Check      : PASS
Dtype Check        : PASS
Finite Check       : PASS
Batch Size         : 246
Batch Size Check   : PASS
Overall            : PASS

====================================================================================================
PRIVATIZED DATALOADER SUMMARY
====================================================================================================
Adult Income         : PASS
Bank Marketing       : PASS
diabetes_130us       : PASS
====================================================================================================

All privatized DataLoaders validated successfully.
DP training data pipeline is ready.

In [91]:
# ==============================================================================
# PART K12 — PRIVATIZED DISCRIMINATOR DIMENSION VALIDATION
# ==============================================================================

print("=" * 100)
print("PART K12 — PRIVATIZED DISCRIMINATOR DIMENSION VALIDATION")
print("=" * 100)

POST_DP_DIMENSION_VALIDATION = {}

VALIDATION_BATCH_SIZE = 4

for dataset in DATASETS:

    print()
    print(dataset)

    try:
        # ----------------------------------------------------------------------
        # Retrieve Opacus Privatized Discriminator
        # ----------------------------------------------------------------------

        discriminator = (
            PRIVATE_DISCRIMINATORS[dataset]
        )

        model_check = (
            discriminator is not None
        )

        if not model_check:
            raise RuntimeError(
                "Privatized discriminator is missing."
            )

        # ----------------------------------------------------------------------
        # Expected Dimensions
        # ----------------------------------------------------------------------

        expected_features = (
            TRAIN_DATASETS[dataset].shape[1]
        )

        expected_output_shape = (
            VALIDATION_BATCH_SIZE,
            1
        )

        # ----------------------------------------------------------------------
        # Test Input
        # ----------------------------------------------------------------------

        test_data = torch.randn(
            VALIDATION_BATCH_SIZE,
            expected_features,
            dtype=torch.float32,
            device=DEVICE
        )

        # ----------------------------------------------------------------------
        # Training Mode
        # ----------------------------------------------------------------------

        discriminator.train()

        training_mode_check = (
            discriminator.training
        )

        # ----------------------------------------------------------------------
        # Forward Pass
        # ----------------------------------------------------------------------

        output = discriminator(
            test_data
        )

        # ----------------------------------------------------------------------
        # Tensor Validation
        # ----------------------------------------------------------------------

        output_tensor_check = (
            torch.is_tensor(output)
        )

        if not output_tensor_check:
            raise RuntimeError(
                "Discriminator output is not a tensor."
            )

        # ----------------------------------------------------------------------
        # Input Dimension Validation
        # ----------------------------------------------------------------------

        actual_input_shape = (
            tuple(test_data.shape)
        )

        input_dimension_check = (
            test_data.ndim == 2
            and
            test_data.shape[1]
            == expected_features
        )

        # ----------------------------------------------------------------------
        # Output Dimension Validation
        # ----------------------------------------------------------------------

        actual_output_shape = (
            tuple(output.shape)
        )

        output_dimension_check = (
            actual_output_shape
            == expected_output_shape
        )

        # ----------------------------------------------------------------------
        # Numerical Validation
        # ----------------------------------------------------------------------

        output_finite_check = (
            torch.isfinite(output).all().item()
        )

        # ----------------------------------------------------------------------
        # Overall Validation
        # ----------------------------------------------------------------------

        status = (
            model_check
            and
            training_mode_check
            and
            output_tensor_check
            and
            input_dimension_check
            and
            output_dimension_check
            and
            output_finite_check
        )

        POST_DP_DIMENSION_VALIDATION[
            dataset
        ] = status

        # ----------------------------------------------------------------------
        # Verification Output
        # ----------------------------------------------------------------------

        print(
            f"Privatized Model   : "
            f"{'PASS' if model_check else 'FAIL'}"
        )

        print(
            f"Training Mode      : "
            f"{'PASS' if training_mode_check else 'FAIL'}"
        )

        print(
            f"Input Shape        : "
            f"{actual_input_shape}"
        )

        print(
            f"Expected Features  : "
            f"{expected_features}"
        )

        print(
            f"Input Dimension    : "
            f"{'PASS' if input_dimension_check else 'FAIL'}"
        )

        print(
            f"Output Shape       : "
            f"{actual_output_shape}"
        )

        print(
            f"Expected Output    : "
            f"{expected_output_shape}"
        )

        print(
            f"Output Dimension   : "
            f"{'PASS' if output_dimension_check else 'FAIL'}"
        )

        print(
            f"Output Tensor      : "
            f"{'PASS' if output_tensor_check else 'FAIL'}"
        )

        print(
            f"Output Finite      : "
            f"{'PASS' if output_finite_check else 'FAIL'}"
        )

        print(
            f"Overall            : "
            f"{'PASS' if status else 'FAIL'}"
        )

    except Exception as error:

        POST_DP_DIMENSION_VALIDATION[
            dataset
        ] = False

        print(
            "Dimension validation error:"
        )

        print(
            f"{type(error).__name__}: {error}"
        )

# ==============================================================================
# PRIVATIZED DISCRIMINATOR DIMENSION SUMMARY
# ==============================================================================

print()
print("=" * 100)
print("PRIVATIZED DISCRIMINATOR DIMENSION SUMMARY")
print("=" * 100)

for dataset, status in POST_DP_DIMENSION_VALIDATION.items():

    print(
        f"{dataset:20s} : "
        f"{'PASS' if status else 'FAIL'}"
    )

print("=" * 100)

# ==============================================================================
# FINAL VALIDATION
# ==============================================================================

if not all(
    POST_DP_DIMENSION_VALIDATION.values()
):

    raise RuntimeError(
        "Privatized Discriminator dimension validation failed. "
        "Do not proceed to DP training."
    )

print()
print(
    "All privatized Discriminator dimensions "
    "validated successfully."
)

print(
    "Privatized Discriminator forward-pass validation: PASS"
)

====================================================================================================
PART K12 — PRIVATIZED DISCRIMINATOR DIMENSION VALIDATION
====================================================================================================

Adult Income
Privatized Model   : PASS
Training Mode      : PASS
Input Shape        : (4, 15)
Expected Features  : 15
Input Dimension    : PASS
Output Shape       : (4, 1)
Expected Output    : (4, 1)
Output Dimension   : PASS
Output Tensor      : PASS
Output Finite      : PASS
Overall            : PASS

Bank Marketing
Privatized Model   : PASS
Training Mode      : PASS
Input Shape        : (4, 17)
Expected Features  : 17
Input Dimension    : PASS
Output Shape       : (4, 1)
Expected Output    : (4, 1)
Output Dimension   : PASS
Output Tensor      : PASS
Output Finite      : PASS
Overall            : PASS

diabetes_130us
Privatized Model   : PASS
Training Mode      : PASS
Input Shape        : (4, 48)
Expected Features  : 48
Input Dimension    : PASS
Output Shape       : (4, 1)
Expected Output    : (4, 1)
Output Dimension   : PASS
Output Tensor      : PASS
Output Finite      : PASS
Overall            : PASS

====================================================================================================
PRIVATIZED DISCRIMINATOR DIMENSION SUMMARY
====================================================================================================
Adult Income         : PASS
Bank Marketing       : PASS
diabetes_130us       : PASS
====================================================================================================

All privatized Discriminator dimensions validated successfully.
Privatized Discriminator forward-pass validation: PASS

In [92]:
# ==============================================================================
# PART K11 — PRIVATIZED DATALOADER VALIDATION
# ==============================================================================

print("=" * 100)
print("PART K11 — PRIVATIZED DATALOADER VALIDATION")
print("=" * 100)

PRIVATIZED_DATALOADER_VALIDATION = {}

for dataset in DATASETS:

    print()
    print(dataset)

    try:

        # ----------------------------------------------------------------------
        # Retrieve Opacus Privatized DataLoader
        # ----------------------------------------------------------------------

        data_loader = PRIVATE_TRAIN_LOADERS[dataset]

        # ----------------------------------------------------------------------
        # DataLoader Object Validation
        # ----------------------------------------------------------------------

        loader_object_check = (
            data_loader is not None
        )

        if not loader_object_check:
            raise RuntimeError(
                "Privatized DataLoader is None."
            )

        # ----------------------------------------------------------------------
        # Batch Retrieval
        # ----------------------------------------------------------------------

        first_batch = next(
            iter(data_loader)
        )

        batch_data = first_batch[0]

        batch_exists_check = (
            batch_data is not None
        )

        # ----------------------------------------------------------------------
        # Tensor Validation
        # ----------------------------------------------------------------------

        tensor_check = (
            torch.is_tensor(batch_data)
        )

        if not tensor_check:
            raise TypeError(
                "Privatized DataLoader batch is not a tensor."
            )

        # ----------------------------------------------------------------------
        # Expected Feature Dimension
        # ----------------------------------------------------------------------

        expected_features = (
            TRAIN_DATASETS[dataset].shape[1]
        )

        actual_features = (
            batch_data.shape[1]
        )

        feature_check = (
            batch_data.ndim == 2
            and
            actual_features == expected_features
        )

        # ----------------------------------------------------------------------
        # Dtype Validation
        # ----------------------------------------------------------------------

        dtype_check = (
            batch_data.dtype == torch.float32
        )

        # ----------------------------------------------------------------------
        # Finite Value Validation
        # ----------------------------------------------------------------------

        finite_check = (
            torch.isfinite(batch_data).all().item()
        )

        # ----------------------------------------------------------------------
        # Batch Size Validation
        # ----------------------------------------------------------------------

        actual_batch_size = (
            batch_data.shape[0]
        )

        batch_size_check = (
            actual_batch_size > 0
        )

        # ----------------------------------------------------------------------
        # Batch Count
        # ----------------------------------------------------------------------

        batch_count = len(data_loader)

        batch_count_check = (
            batch_count > 0
        )

        # ----------------------------------------------------------------------
        # Overall Validation
        # ----------------------------------------------------------------------

        status = (
            loader_object_check
            and batch_exists_check
            and tensor_check
            and feature_check
            and dtype_check
            and finite_check
            and batch_size_check
            and batch_count_check
        )

        PRIVATIZED_DATALOADER_VALIDATION[
            dataset
        ] = status

        # ----------------------------------------------------------------------
        # Output
        # ----------------------------------------------------------------------

        print(
            f"DataLoader Object  : "
            f"{'PASS' if loader_object_check else 'FAIL'}"
        )

        print(
            f"Batch Count        : "
            f"{batch_count}"
        )

        print(
            f"Batch Available    : "
            f"{'PASS' if batch_exists_check else 'FAIL'}"
        )

        print(
            f"Tensor Check       : "
            f"{'PASS' if tensor_check else 'FAIL'}"
        )

        print(
            f"Batch Shape        : "
            f"{tuple(batch_data.shape)}"
        )

        print(
            f"Expected Features  : "
            f"{expected_features}"
        )

        print(
            f"Actual Features    : "
            f"{actual_features}"
        )

        print(
            f"Feature Check      : "
            f"{'PASS' if feature_check else 'FAIL'}"
        )

        print(
            f"Dtype Check        : "
            f"{'PASS' if dtype_check else 'FAIL'}"
        )

        print(
            f"Finite Check       : "
            f"{'PASS' if finite_check else 'FAIL'}"
        )

        print(
            f"Batch Size         : "
            f"{actual_batch_size}"
        )

        print(
            f"Batch Size Check   : "
            f"{'PASS' if batch_size_check else 'FAIL'}"
        )

        print(
            f"Batch Count Check  : "
            f"{'PASS' if batch_count_check else 'FAIL'}"
        )

        print(
            f"Overall            : "
            f"{'PASS' if status else 'FAIL'}"
        )

    except Exception as error:

        PRIVATIZED_DATALOADER_VALIDATION[
            dataset
        ] = False

        print(
            "DataLoader validation error:"
        )

        print(error)


# ==============================================================================
# FINAL SUMMARY
# ==============================================================================

print()
print("=" * 100)
print("PRIVATIZED DATALOADER SUMMARY")
print("=" * 100)

for dataset, status in PRIVATIZED_DATALOADER_VALIDATION.items():

    print(
        f"{dataset:20s} : "
        f"{'PASS' if status else 'FAIL'}"
    )

print("=" * 100)

if not all(
    PRIVATIZED_DATALOADER_VALIDATION.values()
):

    raise RuntimeError(
        "Privatized DataLoader validation failed. "
        "Do not proceed to DP training."
    )

print()
print(
    "All privatized DataLoaders validated successfully."
)

====================================================================================================
PART K11 — PRIVATIZED DATALOADER VALIDATION
====================================================================================================

Adult Income
DataLoader Object  : PASS
Batch Count        : 89
Batch Available    : PASS
Tensor Check       : PASS
Batch Shape        : (284, 15)
Expected Features  : 15
Actual Features    : 15
Feature Check      : PASS
Dtype Check        : PASS
Finite Check       : PASS
Batch Size         : 284
Batch Size Check   : PASS
Batch Count Check  : PASS
Overall            : PASS

Bank Marketing
DataLoader Object  : PASS
Batch Count        : 124
Batch Available    : PASS
Tensor Check       : PASS
Batch Shape        : (228, 17)
Expected Features  : 17
Actual Features    : 17
Feature Check      : PASS
Dtype Check        : PASS
Finite Check       : PASS
Batch Size         : 228
Batch Size Check   : PASS
Batch Count Check  : PASS
Overall            : PASS

diabetes_130us
DataLoader Object  : PASS
Batch Count        : 279
Batch Available    : PASS
Tensor Check       : PASS
Batch Shape        : (240, 48)
Expected Features  : 48
Actual Features    : 48
Feature Check      : PASS
Dtype Check        : PASS
Finite Check       : PASS
Batch Size         : 240
Batch Size Check   : PASS
Batch Count Check  : PASS
Overall            : PASS

====================================================================================================
PRIVATIZED DATALOADER SUMMARY
====================================================================================================
Adult Income         : PASS
Bank Marketing       : PASS
diabetes_130us       : PASS
====================================================================================================

All privatized DataLoaders validated successfully.

In [93]:
# ==============================================================================
# PART K14 — FINAL PRIVACY CONFIGURATION RECORD
# ==============================================================================

print("=" * 100)
print("PART K14 — FINAL PRIVACY CONFIGURATION RECORD")
print("=" * 100)

# ==============================================================================
# VERIFY REQUIRED VALIDATION RECORDS
# ==============================================================================

REQUIRED_VALIDATION_RECORDS = {
    "DP Privatization":
        "DP_PRIVATIZATION_RESULTS",

    "Privatized Model":
        "PRIVATIZED_MODEL_VALIDATION",

    "Privacy Accounting":
        "PRIVACY_ACCOUNTING_RESULTS",

    "Privatized DataLoader":
        "PRIVATIZED_DATALOADER_VALIDATION",

    "Discriminator Dimensions":
        "POST_DP_DIMENSION_VALIDATION"
}

missing_records = [
    variable_name
    for variable_name in REQUIRED_VALIDATION_RECORDS.values()
    if variable_name not in globals()
]

if missing_records:

    raise RuntimeError(
        "Required privacy validation records are missing: "
        f"{missing_records}. "
        "Run K8–K13 successfully before K14."
    )

# ==============================================================================
# CALCULATE FINAL PRIVACY PIPELINE STATUS
# ==============================================================================

FINAL_PRIVACY_VALIDATION = {}

for dataset in DATASETS:

    privatization_check = (
        DP_PRIVATIZATION_RESULTS.get(
            dataset,
            False
        )
    )

    model_check = (
        PRIVATIZED_MODEL_VALIDATION.get(
            dataset,
            False
        )
    )

    accounting_check = (
        PRIVACY_ACCOUNTING_RESULTS.get(
            dataset,
            False
        )
    )

    loader_check = (
        PRIVATIZED_DATALOADER_VALIDATION.get(
            dataset,
            False
        )
    )

    dimension_check = (
        POST_DP_DIMENSION_VALIDATION.get(
            dataset,
            False
        )
    )

    overall_status = (
        privatization_check
        and model_check
        and accounting_check
        and loader_check
        and dimension_check
    )

    FINAL_PRIVACY_VALIDATION[
        dataset
    ] = overall_status

# ==============================================================================
# FINAL PRIVACY CONFIGURATION
# ==============================================================================

DP_CONFIGURATION = {

    # --------------------------------------------------------------------------
    # Privacy Configuration
    # --------------------------------------------------------------------------

    "Privacy Mechanism":
        "Opacus Differential Privacy",

    "Privacy Accountant":
        "RDP Accountant",

    "Privacy Budget Epsilon":
        DP_PRIVACY_BUDGET,

    "Privacy Delta":
        DP_DELTA,

    "Maximum Gradient Norm":
        DP_MAX_GRAD_NORM,

    "Noise Multipliers":
        NOISE_MULTIPLIERS,

    # --------------------------------------------------------------------------
    # Training Configuration
    # --------------------------------------------------------------------------

    "Batch Size":
        DP_BATCH_SIZE,

    "Epochs":
        DP_EPOCHS,

    "Optimizer":
        OPTIMIZER_NAME,

    "Learning Rate":
        OPTIMIZER_LEARNING_RATE,

    "Beta1":
        OPTIMIZER_BETA1,

    "Beta2":
        OPTIMIZER_BETA2,

    # --------------------------------------------------------------------------
    # DP Component Information
    # --------------------------------------------------------------------------

    "Privatized Component":
        "Discriminator",

    "Datasets":
        DATASETS,

    # --------------------------------------------------------------------------
    # Software Environment
    # --------------------------------------------------------------------------

    "PyTorch Version":
        torch.__version__,

    "Opacus Version":
        opacus.__version__,

    # --------------------------------------------------------------------------
    # Validation Status
    # --------------------------------------------------------------------------

    "Privacy Pipeline Status":
        (
            "PASS"
            if all(
                FINAL_PRIVACY_VALIDATION.values()
            )
            else "FAIL"
        )
}

# ==============================================================================
# DISPLAY FINAL CONFIGURATION
# ==============================================================================

for key, value in DP_CONFIGURATION.items():

    print(
        f"{key:30s}: {value}"
    )

# ==============================================================================
# DATASET-WISE FINAL VALIDATION
# ==============================================================================

print()
print("=" * 100)
print("FINAL PRIVACY VALIDATION STATUS")
print("=" * 100)

for dataset, status in FINAL_PRIVACY_VALIDATION.items():

    print(
        f"{dataset:25s}: "
        f"{'PASS' if status else 'FAIL'}"
    )

# ==============================================================================
# FINAL SAFETY CHECK
# ==============================================================================

FINAL_PRIVACY_STATUS = (
    DP_CONFIGURATION[
        "Privacy Pipeline Status"
    ]
    == "PASS"
)

print()
print(
    f"Final Privacy Pipeline : "
    f"{'PASS' if FINAL_PRIVACY_STATUS else 'FAIL'}"
)

if not FINAL_PRIVACY_STATUS:

    raise RuntimeError(
        "Final privacy configuration validation failed. "
        "Do not proceed to DP training."
    )

print()
print("=" * 100)
print("PART K14 COMPLETED SUCCESSFULLY")
print("=" * 100)

print(
    "Final privacy configuration record created successfully."
)

print(
    "All validated DP configuration parameters have been recorded."
)

print(
    "DP training may proceed."
)

====================================================================================================
PART K14 — FINAL PRIVACY CONFIGURATION RECORD
====================================================================================================
Privacy Mechanism             : Opacus Differential Privacy
Privacy Accountant            : RDP Accountant
Privacy Budget Epsilon        : 4.0
Privacy Delta                 : 1e-05
Maximum Gradient Norm         : 1.0
Noise Multipliers             : {'Adult Income': 1.42333984375, 'Bank Marketing': 1.2548828125, 'diabetes_130us': 0.958251953125}
Batch Size                    : 256
Epochs                        : 100
Optimizer                     : Adam
Learning Rate                 : 0.0002
Beta1                         : 0.5
Beta2                         : 0.999
Privatized Component          : Discriminator
Datasets                      : ['Adult Income', 'Bank Marketing', 'diabetes_130us']
PyTorch Version               : 2.11.0+cpu
Opacus Version                : 1.6.0
Privacy Pipeline Status       : PASS

====================================================================================================
FINAL PRIVACY VALIDATION STATUS
====================================================================================================
Adult Income             : PASS
Bank Marketing           : PASS
diabetes_130us           : PASS

Final Privacy Pipeline : PASS

====================================================================================================
PART K14 COMPLETED SUCCESSFULLY
====================================================================================================
Final privacy configuration record created successfully.
All validated DP configuration parameters have been recorded.
DP training may proceed.

In [94]:
# ==============================================================================
# PART K15 — FINAL PART K VERIFICATION
# ==============================================================================

print("=" * 100)
print("PART K15 — FINAL PART K VERIFICATION")
print("=" * 100)

FINAL_PRIVACY_VERIFICATION = {}

for dataset in DATASETS:

    # --------------------------------------------------------------------------
    # Retrieve Individual Validation Results
    # --------------------------------------------------------------------------

    attachment_check = (
        DP_PRIVATIZATION_RESULTS.get(
            dataset,
            False
        )
    )

    model_check = (
        PRIVATIZED_MODEL_VALIDATION.get(
            dataset,
            False
        )
    )

    accounting_check = (
        PRIVACY_ACCOUNTING_RESULTS.get(
            dataset,
            False
        )
    )

    loader_check = (
        PRIVATIZED_DATALOADER_VALIDATION.get(
            dataset,
            False
        )
    )

    dimension_check = (
        POST_DP_DIMENSION_VALIDATION.get(
            dataset,
            False
        )
    )

    # --------------------------------------------------------------------------
    # Final Dataset Status
    # --------------------------------------------------------------------------

    overall_status = (
        attachment_check
        and model_check
        and accounting_check
        and loader_check
        and dimension_check
    )

    FINAL_PRIVACY_VERIFICATION[
        dataset
    ] = overall_status

    # --------------------------------------------------------------------------
    # Display Dataset Validation
    # --------------------------------------------------------------------------

    print()
    print(dataset)

    print(
        f"PrivacyEngine Attachment : "
        f"{'PASS' if attachment_check else 'FAIL'}"
    )

    print(
        f"Privatized Model         : "
        f"{'PASS' if model_check else 'FAIL'}"
    )

    print(
        f"Privacy Accounting      : "
        f"{'PASS' if accounting_check else 'FAIL'}"
    )

    print(
        f"Privatized DataLoader   : "
        f"{'PASS' if loader_check else 'FAIL'}"
    )

    print(
        f"Dimension Validation    : "
        f"{'PASS' if dimension_check else 'FAIL'}"
    )

    print(
        f"Overall                 : "
        f"{'PASS' if overall_status else 'FAIL'}"
    )


# ==============================================================================
# FINAL PRIVACY VERIFICATION SUMMARY
# ==============================================================================

print()
print("=" * 100)
print("FINAL PRIVACY VERIFICATION SUMMARY")
print("=" * 100)

for dataset, status in FINAL_PRIVACY_VERIFICATION.items():

    print(
        f"{dataset:20s} : "
        f"{'PASS' if status else 'FAIL'}"
    )

print("=" * 100)


# ==============================================================================
# FINAL PART K SAFETY CHECK
# ==============================================================================

if not all(
    FINAL_PRIVACY_VERIFICATION.values()
):

    raise RuntimeError(
        "PART K failed. "
        "Do not proceed to PART L."
    )


print()
print("=" * 100)
print("PART K COMPLETED SUCCESSFULLY")
print("=" * 100)

print(
    "Differential Privacy Engine validated successfully."
)

print(
    "Privatized Discriminators are ready for DP training."
)

print("=" * 100)

====================================================================================================
PART K15 — FINAL PART K VERIFICATION
====================================================================================================

Adult Income
PrivacyEngine Attachment : PASS
Privatized Model         : PASS
Privacy Accounting      : PASS
Privatized DataLoader   : PASS
Dimension Validation    : PASS
Overall                 : PASS

Bank Marketing
PrivacyEngine Attachment : PASS
Privatized Model         : PASS
Privacy Accounting      : PASS
Privatized DataLoader   : PASS
Dimension Validation    : PASS
Overall                 : PASS

diabetes_130us
PrivacyEngine Attachment : PASS
Privatized Model         : PASS
Privacy Accounting      : PASS
Privatized DataLoader   : PASS
Dimension Validation    : PASS
Overall                 : PASS

====================================================================================================
FINAL PRIVACY VERIFICATION SUMMARY
====================================================================================================
Adult Income         : PASS
Bank Marketing       : PASS
diabetes_130us       : PASS
====================================================================================================

====================================================================================================
PART K COMPLETED SUCCESSFULLY
====================================================================================================
Differential Privacy Engine validated successfully.
Privatized Discriminators are ready for DP training.
====================================================================================================

In [96]:
# ==============================================================================
# PART L1 — DP-CTGAN TRAINING CONFIGURATION
# ==============================================================================

print("=" * 100)
print("PART L1 — DP-CTGAN TRAINING CONFIGURATION")
print("=" * 100)

DP_CTGAN_EPOCHS = DP_EPOCHS

LATENT_DIMENSION = 128

GENERATOR_LEARNING_RATE = 0.0002
DISCRIMINATOR_LEARNING_RATE = 0.0002

GENERATOR_BETA1 = (
    OPTIMIZER_BETA1
    if "OPTIMIZER_BETA1" in globals()
    else 0.5
)

GENERATOR_BETA2 = (
    OPTIMIZER_BETA2
    if "OPTIMIZER_BETA2" in globals()
    else 0.999
)

print(f"Training Epochs       : {DP_CTGAN_EPOCHS}")
print(f"Latent Dimension      : {LATENT_DIMENSION}")
print(f"Generator LR          : {GENERATOR_LEARNING_RATE}")
print(f"Discriminator LR       : {DISCRIMINATOR_LEARNING_RATE}")
print(f"Adam Beta1            : {GENERATOR_BETA1}")
print(f"Adam Beta2            : {GENERATOR_BETA2}")
print()
print("DP-CTGAN training configuration initialized successfully.")

====================================================================================================
PART L1 — DP-CTGAN TRAINING CONFIGURATION
====================================================================================================
Training Epochs       : 100
Latent Dimension      : 128
Generator LR          : 0.0002
Discriminator LR       : 0.0002
Adam Beta1            : 0.5
Adam Beta2            : 0.999

DP-CTGAN training configuration initialized successfully.

In [97]:
# ==============================================================================
# PART L2 — GENERATOR DEFINITION
# ==============================================================================

print("=" * 100)
print("PART L2 — GENERATOR DEFINITION")
print("=" * 100)

import torch
import torch.nn as nn


class Generator(nn.Module):

    def __init__(
        self,
        latent_dim,
        output_dim
    ):
        super().__init__()

        self.network = nn.Sequential(
            nn.Linear(latent_dim, 256),
            nn.LayerNorm(256),
            nn.LeakyReLU(0.2, inplace=False),

            nn.Linear(256, 512),
            nn.LayerNorm(512),
            nn.LeakyReLU(0.2, inplace=False),

            nn.Linear(512, 256),
            nn.LayerNorm(256),
            nn.LeakyReLU(0.2, inplace=False),

            nn.Linear(256, output_dim)
        )

    def forward(self, x):
        return self.network(x)


GENERATORS = {}
GENERATOR_OPTIMIZERS = {}

for dataset in DATASETS:

    output_dimension = TRAIN_DATASETS[dataset].shape[1]

    generator = Generator(
        latent_dim=LATENT_DIMENSION,
        output_dim=output_dimension
    ).to(DEVICE)

    generator_optimizer = torch.optim.Adam(
        generator.parameters(),
        lr=GENERATOR_LEARNING_RATE,
        betas=(
            GENERATOR_BETA1,
            GENERATOR_BETA2
        )
    )

    GENERATORS[dataset] = generator
    GENERATOR_OPTIMIZERS[dataset] = generator_optimizer

    print()
    print(dataset)
    print(f"Generator Output Dimension : {output_dimension}")
    print("Generator Initialized      : PASS")

print()
print("All generators initialized successfully.")

====================================================================================================
PART L2 — GENERATOR DEFINITION
====================================================================================================

Adult Income
Generator Output Dimension : 15
Generator Initialized      : PASS

Bank Marketing
Generator Output Dimension : 17
Generator Initialized      : PASS

diabetes_130us
Generator Output Dimension : 48
Generator Initialized      : PASS

All generators initialized successfully.

In [100]:
# ==============================================================================
# PART L3 — DP TRAINING INITIALIZATION
# ==============================================================================

print("=" * 100)
print("PART L3 — DP TRAINING INITIALIZATION")
print("=" * 100)

import torch
import torch.nn as nn

# ------------------------------------------------------------------------------
# Loss Functions
# ------------------------------------------------------------------------------

generator_loss_function = nn.BCEWithLogitsLoss()

discriminator_loss_function = nn.BCEWithLogitsLoss()

print()
print("Generator Loss Function     : BCEWithLogitsLoss")
print("Discriminator Loss Function : BCEWithLogitsLoss")

# ------------------------------------------------------------------------------
# Training State
# ------------------------------------------------------------------------------

DP_TRAINING_HISTORY = {}

DP_TRAINING_ERRORS = {}

DP_TRAINING_COMPLETED = {}

FINAL_EPSILON_REPORT = {}

# ------------------------------------------------------------------------------
# Validate Required DP Objects
# ------------------------------------------------------------------------------

for dataset in DATASETS:

    print()
    print(dataset)

    required_objects = {
        "Generator": GENERATORS,
        "Generator Optimizer": GENERATOR_OPTIMIZERS,
        "Private Discriminator": PRIVATE_DISCRIMINATORS,
        "Private Discriminator Optimizer": PRIVATE_DISCRIMINATOR_OPTIMIZERS,
        "Private DataLoader": PRIVATE_TRAIN_LOADERS,
        "Privacy Engine": PRIVACY_ENGINES
    }

    missing_objects = []

    for object_name, object_dictionary in required_objects.items():

        if dataset not in object_dictionary:

            missing_objects.append(
                object_name
            )

    if missing_objects:

        raise RuntimeError(
            f"{dataset}: Missing required objects: "
            + ", ".join(missing_objects)
        )

    # --------------------------------------------------------------------------
    # Initialize Training State
    # --------------------------------------------------------------------------

    DP_TRAINING_HISTORY[dataset] = {

        "Generator Loss": [],

        "Discriminator Loss": []

    }

    DP_TRAINING_ERRORS[dataset] = None

    DP_TRAINING_COMPLETED[dataset] = False

    FINAL_EPSILON_REPORT[dataset] = None

    # --------------------------------------------------------------------------
    # Validation Output
    # --------------------------------------------------------------------------

    print(
        "Generator             : PASS"
    )

    print(
        "Generator Optimizer   : PASS"
    )

    print(
        "Private Discriminator : PASS"
    )

    print(
        "Private Optimizer     : PASS"
    )

    print(
        "Private DataLoader    : PASS"
    )

    print(
        "Privacy Engine        : PASS"
    )

    print(
        "Training State        : PASS"
    )

print()
print("=" * 100)
print("DP TRAINING INITIALIZATION COMPLETED")
print("=" * 100)

====================================================================================================
PART L3 — DP TRAINING INITIALIZATION
====================================================================================================

Generator Loss Function     : BCEWithLogitsLoss
Discriminator Loss Function : BCEWithLogitsLoss

Adult Income
Generator             : PASS
Generator Optimizer   : PASS
Private Discriminator : PASS
Private Optimizer     : PASS
Private DataLoader    : PASS
Privacy Engine        : PASS
Training State        : PASS

Bank Marketing
Generator             : PASS
Generator Optimizer   : PASS
Private Discriminator : PASS
Private Optimizer     : PASS
Private DataLoader    : PASS
Privacy Engine        : PASS
Training State        : PASS

diabetes_130us
Generator             : PASS
Generator Optimizer   : PASS
Private Discriminator : PASS
Private Optimizer     : PASS
Private DataLoader    : PASS
Privacy Engine        : PASS
Training State        : PASS

====================================================================================================
DP TRAINING INITIALIZATION COMPLETED
====================================================================================================

In [110]:
print(type(discriminator))
print(type(discriminator_optimizer))

<class 'opacus.grad_sample.grad_sample_module.GradSampleModule'>
<class 'opacus.optimizers.optimizer.DPOptimizer'>

In [119]:
# ==============================================================================
# PART L4 — DP TRAINING LOOP
# ==============================================================================

print("=" * 100)
print("PART L4 — DP TRAINING LOOP")
print("=" * 100)

# ------------------------------------------------------------------------------
# Training result containers
# ------------------------------------------------------------------------------

DP_TRAINING_COMPLETED = {}
DP_TRAINING_ERRORS = {}

# Make sure training history exists
if "DP_TRAINING_HISTORY" not in globals():
    DP_TRAINING_HISTORY = {}

for dataset in DATASETS:

    print()
    print("=" * 80)
    print(dataset)
    print("=" * 80)

    DP_TRAINING_COMPLETED[dataset] = False
    DP_TRAINING_ERRORS[dataset] = None

    try:

        # ----------------------------------------------------------------------
        # Retrieve models, optimizers and loader
        # ----------------------------------------------------------------------

        generator = GENERATORS[dataset]
        generator_optimizer = GENERATOR_OPTIMIZERS[dataset]

        discriminator = PRIVATE_DISCRIMINATORS[dataset]
        discriminator_optimizer = PRIVATE_DISCRIMINATOR_OPTIMIZERS[dataset]

        train_loader = PRIVATE_TRAIN_LOADERS[dataset]

        generator.train()
        discriminator.train()

        # ----------------------------------------------------------------------
        # Initialize training history
        # ----------------------------------------------------------------------

        DP_TRAINING_HISTORY[dataset] = {
            "Discriminator Loss": [],
            "Generator Loss": []
        }

        # ----------------------------------------------------------------------
        # Training epochs
        # ----------------------------------------------------------------------

        for epoch in range(DP_CTGAN_EPOCHS):

            epoch_discriminator_loss = 0.0
            epoch_generator_loss = 0.0

            discriminator_batches = 0
            generator_batches = 0

            # ==================================================================
            # BATCH LOOP
            # ==================================================================

            for batch in train_loader:

                real_data = batch[0].to(DEVICE).float()

                current_batch_size = real_data.size(0)

                if current_batch_size < 2:
                    continue

                # ==============================================================
                # 1. DISCRIMINATOR UPDATE
                #
                # IMPORTANT:
                # For Opacus, do NOT calculate real and fake discriminator
                # gradients in the same backward pass.
                #
                # We therefore perform:
                #   real -> backward -> step
                #   fake -> backward -> step
                #
                # Each DP optimizer step processes exactly one forward/backward
                # operation with one consistent batch size.
                # ==============================================================

                discriminator.train()

                for parameter in discriminator.parameters():
                    parameter.requires_grad_(True)

                discriminator_optimizer.zero_grad(set_to_none=True)

                # --------------------------------------------------------------
                # REAL DATA
                # --------------------------------------------------------------

                real_output = discriminator(real_data)

                if real_output.ndim == 1:
                    real_output = real_output.reshape(-1, 1)

                real_labels = torch.ones(
                    real_output.shape[0],
                    1,
                    device=DEVICE
                )

                real_loss = discriminator_loss_function(
                    real_output,
                    real_labels
                )

                if not torch.isfinite(real_loss):
                    raise RuntimeError(
                        f"Non-finite real discriminator loss "
                        f"for {dataset}."
                    )

                real_loss.backward()

                # --------------------------------------------------------------
                # DP OPTIMIZER STEP — REAL DATA
                # --------------------------------------------------------------

                discriminator_optimizer.step()

                discriminator_optimizer.zero_grad(set_to_none=True)

                # --------------------------------------------------------------
                # FAKE DATA
                # --------------------------------------------------------------

                noise = torch.randn(
                    current_batch_size,
                    LATENT_DIMENSION,
                    device=DEVICE
                )

                with torch.no_grad():
                    fake_data = generator(noise)

                fake_output = discriminator(fake_data)

                if fake_output.ndim == 1:
                    fake_output = fake_output.reshape(-1, 1)

                fake_labels = torch.zeros(
                    fake_output.shape[0],
                    1,
                    device=DEVICE
                )

                fake_loss = discriminator_loss_function(
                    fake_output,
                    fake_labels
                )

                if not torch.isfinite(fake_loss):
                    raise RuntimeError(
                        f"Non-finite fake discriminator loss "
                        f"for {dataset}."
                    )

                fake_loss.backward()

                # --------------------------------------------------------------
                # DP OPTIMIZER STEP — FAKE DATA
                # --------------------------------------------------------------

                discriminator_optimizer.step()

                discriminator_optimizer.zero_grad(set_to_none=True)

                discriminator_loss = (
                    real_loss.detach().item()
                    +
                    fake_loss.detach().item()
                )

                epoch_discriminator_loss += discriminator_loss
                discriminator_batches += 1

                # ==============================================================
                # 2. GENERATOR UPDATE
                #
                # The discriminator is used only as a differentiable function.
                # Its parameters are frozen so that gradients flow to the
                # generator without updating discriminator parameters.
                # ==============================================================

                for parameter in discriminator.parameters():
                    parameter.requires_grad_(False)

                generator_optimizer.zero_grad(set_to_none=True)

                noise = torch.randn(
                    current_batch_size,
                    LATENT_DIMENSION,
                    device=DEVICE
                )

                generated_data = generator(noise)

                generated_output = discriminator(
                    generated_data
                )

                if generated_output.ndim == 1:
                    generated_output = generated_output.reshape(-1, 1)

                generator_labels = torch.ones(
                    generated_output.shape[0],
                    1,
                    device=DEVICE
                )

                generator_loss = generator_loss_function(
                    generated_output,
                    generator_labels
                )

                if not torch.isfinite(generator_loss):
                    raise RuntimeError(
                        f"Non-finite generator loss "
                        f"for {dataset}."
                    )

                generator_loss.backward()

                generator_optimizer.step()

                # --------------------------------------------------------------
                # Restore discriminator gradients
                # --------------------------------------------------------------

                for parameter in discriminator.parameters():
                    parameter.requires_grad_(True)

                generator_optimizer.zero_grad(set_to_none=True)

                epoch_generator_loss += (
                    generator_loss.detach().item()
                )

                generator_batches += 1

            # ==================================================================
            # END OF EPOCH
            # ==================================================================

            if discriminator_batches == 0:
                raise RuntimeError(
                    f"No discriminator batches were processed "
                    f"for {dataset}."
                )

            if generator_batches == 0:
                raise RuntimeError(
                    f"No generator batches were processed "
                    f"for {dataset}."
                )

            average_discriminator_loss = (
                epoch_discriminator_loss
                /
                discriminator_batches
            )

            average_generator_loss = (
                epoch_generator_loss
                /
                generator_batches
            )

            DP_TRAINING_HISTORY[dataset][
                "Discriminator Loss"
            ].append(
                average_discriminator_loss
            )

            DP_TRAINING_HISTORY[dataset][
                "Generator Loss"
            ].append(
                average_generator_loss
            )

            # ==================================================================
            # PROGRESS
            # ==================================================================

            if (
                epoch == 0
                or
                (epoch + 1) % 10 == 0
                or
                epoch == DP_CTGAN_EPOCHS - 1
            ):

                print(
                    f"Epoch {epoch + 1:3d}/"
                    f"{DP_CTGAN_EPOCHS} | "
                    f"D Loss: "
                    f"{average_discriminator_loss:.6f} | "
                    f"G Loss: "
                    f"{average_generator_loss:.6f}"
                )

        # ----------------------------------------------------------------------
        # Dataset training completed
        # ----------------------------------------------------------------------

        DP_TRAINING_COMPLETED[dataset] = True
        DP_TRAINING_ERRORS[dataset] = None

        print()
        print("DP Discriminator Training : PASS")
        print("Generator Training        : PASS")
        print("Overall Training          : PASS")

    except Exception as error:

        DP_TRAINING_COMPLETED[dataset] = False

        DP_TRAINING_ERRORS[dataset] = (
            f"{type(error).__name__}: {error}"
        )

        print()
        print("DP-CTGAN Training : FAIL")
        print(
            f"Error Type       : "
            f"{type(error).__name__}"
        )
        print(
            f"Error Message    : "
            f"{error}"
        )

        raise

# ==============================================================================
# TRAINING SUMMARY
# ==============================================================================

print()
print("=" * 100)
print("DP-CTGAN TRAINING SUMMARY")
print("=" * 100)

for dataset in DATASETS:

    status = DP_TRAINING_COMPLETED.get(
        dataset,
        False
    )

    print(
        f"{dataset:20s} : "
        f"{'PASS' if status else 'FAIL'}"
    )

print("=" * 100)

if not all(
    DP_TRAINING_COMPLETED.get(dataset, False)
    for dataset in DATASETS
):

    raise RuntimeError(
        "DP-CTGAN training failed "
        "for one or more datasets."
    )

print()
print(
    "All datasets completed DP-CTGAN training successfully."
)

====================================================================================================
PART L4 — DP TRAINING LOOP
====================================================================================================

================================================================================
Adult Income
================================================================================

DP-CTGAN Training : FAIL
Error Type       : TypeError
Error Message    : 'NoneType' object is not subscriptable

TypeError: 'NoneType' object is not subscriptable

In [ ]:
# ==============================================================================
# PART L5 — TRAINING HISTORY
# ==============================================================================

print("=" * 100)
print("PART L5 — TRAINING HISTORY")
print("=" * 100)

for dataset in DATASETS:

    generator_losses = DP_TRAINING_HISTORY[dataset][
        "Generator Loss"
    ]

    discriminator_losses = DP_TRAINING_HISTORY[dataset][
        "Discriminator Loss"
    ]

    generator_count = len(generator_losses)
    discriminator_count = len(discriminator_losses)

    history_check = (
        generator_count == DP_CTGAN_EPOCHS
        and
        discriminator_count == DP_CTGAN_EPOCHS
    )

    finite_check = (
        all(
            torch.isfinite(
                torch.tensor(
                    generator_losses,
                    dtype=torch.float64
                )
            ).tolist()
        )
        and
        all(
            torch.isfinite(
                torch.tensor(
                    discriminator_losses,
                    dtype=torch.float64
                )
            ).tolist()
        )
    )

    status = (
        history_check
        and
        finite_check
    )

    print()
    print(dataset)

    print(
        f"Generator Loss Entries     : "
        f"{generator_count}"
    )

    print(
        f"Discriminator Loss Entries : "
        f"{discriminator_count}"
    )

    print(
        f"Expected Epochs             : "
        f"{DP_CTGAN_EPOCHS}"
    )

    print(
        f"History Length Check        : "
        f"{'PASS' if history_check else 'FAIL'}"
    )

    print(
        f"Finite Loss Check           : "
        f"{'PASS' if finite_check else 'FAIL'}"
    )

    print(
        f"Overall                     : "
        f"{'PASS' if status else 'FAIL'}"
    )

    if not status:

        raise RuntimeError(
            f"Training history validation failed "
            f"for {dataset}."
        )

print()
print("Training history validated successfully.")

In [ ]:
# ==============================================================================
# PART L6 — TRAINING RESULTS SUMMARY
# ==============================================================================

print("=" * 100)
print("PART L6 — TRAINING RESULTS SUMMARY")
print("=" * 100)

for dataset in DATASETS:

    history = DP_TRAINING_HISTORY[dataset]

    generator_losses = history["Generator Loss"]
    discriminator_losses = history["Discriminator Loss"]

    privacy_engine = PRIVACY_ENGINES[dataset]

    try:

        final_epsilon = privacy_engine.get_epsilon(
            DP_DELTA
        )

        FINAL_EPSILON_REPORT[dataset] = final_epsilon

    except Exception as error:

        FINAL_EPSILON_REPORT[dataset] = None

        print()
        print(dataset)
        print(
            "Final Epsilon : ERROR"
        )
        print(
            f"Error Type    : "
            f"{type(error).__name__}"
        )
        print(
            f"Error Message : "
            f"{error}"
        )

        raise

    final_generator_loss = generator_losses[-1]
    final_discriminator_loss = discriminator_losses[-1]

    epsilon_valid = (
        FINAL_EPSILON_REPORT[dataset] is not None
        and
        torch.isfinite(
            torch.tensor(
                FINAL_EPSILON_REPORT[dataset],
                dtype=torch.float64
            )
        ).item()
    )

    epsilon_budget_check = (
        epsilon_valid
        and
        FINAL_EPSILON_REPORT[dataset]
        <= DP_PRIVACY_BUDGET + 1e-6
    )

    print()
    print(dataset)

    print(
        f"Final Generator Loss       : "
        f"{final_generator_loss:.6f}"
    )

    print(
        f"Final Discriminator Loss   : "
        f"{final_discriminator_loss:.6f}"
    )

    print(
        f"Target Epsilon             : "
        f"{DP_PRIVACY_BUDGET}"
    )

    print(
        f"Target Delta               : "
        f"{DP_DELTA}"
    )

    print(
        f"Final Epsilon              : "
        f"{FINAL_EPSILON_REPORT[dataset]:.6f}"
    )

    print(
        f"Epsilon Valid              : "
        f"{'PASS' if epsilon_valid else 'FAIL'}"
    )

    print(
        f"Privacy Budget Check       : "
        f"{'PASS' if epsilon_budget_check else 'FAIL'}"
    )

print()
print("DP training results summary generated successfully.")

In [ ]:
# ==============================================================================
# PART L7 — FINAL TRAINING VERIFICATION
# ==============================================================================

print("=" * 100)
print("PART L7 — FINAL TRAINING VERIFICATION")
print("=" * 100)

FINAL_DP_TRAINING_VERIFICATION = {}

for dataset in DATASETS:

    training_check = (
        DP_TRAINING_COMPLETED.get(
            dataset,
            False
        )
    )

    history = DP_TRAINING_HISTORY.get(
        dataset,
        {}
    )

    generator_history = history.get(
        "Generator Loss",
        []
    )

    discriminator_history = history.get(
        "Discriminator Loss",
        []
    )

    history_check = (
        len(generator_history)
        == DP_CTGAN_EPOCHS
        and
        len(discriminator_history)
        == DP_CTGAN_EPOCHS
    )

    epsilon = FINAL_EPSILON_REPORT.get(
        dataset,
        None
    )

    epsilon_check = (
        epsilon is not None
        and
        torch.isfinite(
            torch.tensor(
                epsilon,
                dtype=torch.float64
            )
        ).item()
        and
        epsilon <= DP_PRIVACY_BUDGET + 1e-6
    )

    generator_check = (
        dataset in GENERATORS
        and
        GENERATORS[dataset] is not None
    )

    discriminator_check = (
        dataset in PRIVATE_DISCRIMINATORS
        and
        PRIVATE_DISCRIMINATORS[dataset] is not None
    )

    overall_status = (
        training_check
        and
        history_check
        and
        epsilon_check
        and
        generator_check
        and
        discriminator_check
    )

    FINAL_DP_TRAINING_VERIFICATION[dataset] = (
        overall_status
    )

    print()
    print(dataset)

    print(
        f"Training Completed       : "
        f"{'PASS' if training_check else 'FAIL'}"
    )

    print(
        f"Training History         : "
        f"{'PASS' if history_check else 'FAIL'}"
    )

    print(
        f"Final Epsilon            : "
        f"{'PASS' if epsilon_check else 'FAIL'}"
    )

    print(
        f"Generator                : "
        f"{'PASS' if generator_check else 'FAIL'}"
    )

    print(
        f"Privatized Discriminator : "
        f"{'PASS' if discriminator_check else 'FAIL'}"
    )

    print(
        f"Overall                  : "
        f"{'PASS' if overall_status else 'FAIL'}"
    )

print()
print("=" * 100)
print("FINAL DP-CTGAN TRAINING SUMMARY")
print("=" * 100)

for dataset, status in FINAL_DP_TRAINING_VERIFICATION.items():

    print(
        f"{dataset:20s} : "
        f"{'PASS' if status else 'FAIL'}"
    )

print("=" * 100)

if not all(
    FINAL_DP_TRAINING_VERIFICATION.values()
):

    raise RuntimeError(
        "PART L failed. "
        "One or more datasets did not complete "
        "DP-CTGAN training successfully."
    )

print()
print("PART L COMPLETED SUCCESSFULLY")
print("DP-CTGAN training completed for all datasets.")
print("Final privacy accounting was successfully recorded.")
print("=" * 100)

In [125]:
# ==============================================================================
# PART L1 — DP-CTGAN TRAINING CONFIGURATION
# ==============================================================================
# Configuration-driven
# No manual hyperparameter definitions
# No Opacus
# Reuses existing project configuration and existing model dimensions
# ==============================================================================

import os
import random
import numpy as np
import torch

print("=" * 100)
print("PART L1 — DP-CTGAN TRAINING CONFIGURATION")
print("=" * 100)

# ==============================================================================
# 1. LOAD EXISTING CONFIGURATION
# ==============================================================================

if "CONFIG" not in globals():

    if "PROJECT_ROOT" not in globals():
        raise RuntimeError(
            "PROJECT_ROOT is not defined. "
            "Run the project configuration section before L1."
        )

    CONFIG_PATH = os.path.join(
        PROJECT_ROOT,
        "config.yaml"
    )

    if not os.path.exists(CONFIG_PATH):
        raise FileNotFoundError(
            f"Configuration file not found:\n{CONFIG_PATH}"
        )

    import yaml

    with open(
        CONFIG_PATH,
        "r",
        encoding="utf-8"
    ) as file:

        CONFIG = yaml.safe_load(file)

if not isinstance(CONFIG, dict):
    raise TypeError(
        "CONFIG must be a dictionary."
    )

# ==============================================================================
# 2. RECURSIVE CONFIGURATION SEARCH
# ==============================================================================

def find_config_value(*names):

    names = {
        str(name).lower()
        for name in names
    }

    def search(dictionary):

        if not isinstance(dictionary, dict):
            return None

        for key, value in dictionary.items():

            if str(key).lower() in names:
                return value

        for value in dictionary.values():

            if isinstance(value, dict):

                result = search(value)

                if result is not None:
                    return result

        return None

    return search(CONFIG)

# ==============================================================================
# 3. DEVICE
# ==============================================================================

DEVICE = torch.device(
    "cuda"
    if torch.cuda.is_available()
    else "cpu"
)

# ==============================================================================
# 4. SEED
# ==============================================================================

SEED = find_config_value(
    "seed",
    "random_seed"
)

if SEED is None:

    if "SEED" in globals():

        SEED = SEED

    else:

        raise KeyError(
            "Seed was not found in the existing project configuration."
        )

SEED = int(SEED)

random.seed(SEED)
np.random.seed(SEED)
torch.manual_seed(SEED)

if torch.cuda.is_available():

    torch.cuda.manual_seed_all(SEED)

# ==============================================================================
# 5. DIFFERENTIAL PRIVACY CONFIGURATION
# ==============================================================================

DP_PRIVACY_BUDGET = find_config_value(
    "privacy_budget",
    "epsilon",
    "dp_privacy_budget"
)

DP_DELTA = find_config_value(
    "delta",
    "dp_delta"
)

DP_MAX_GRAD_NORM = find_config_value(
    "gradient_clip",
    "max_grad_norm",
    "dp_max_grad_norm"
)

DP_NOISE_MULTIPLIER = find_config_value(
    "noise_multiplier",
    "dp_noise_multiplier"
)

# Reuse already-defined values if configuration uses different naming.

if DP_PRIVACY_BUDGET is None and "DP_PRIVACY_BUDGET" in globals():
    DP_PRIVACY_BUDGET = globals()["DP_PRIVACY_BUDGET"]

if DP_DELTA is None and "DP_DELTA" in globals():
    DP_DELTA = globals()["DP_DELTA"]

if DP_MAX_GRAD_NORM is None and "DP_MAX_GRAD_NORM" in globals():
    DP_MAX_GRAD_NORM = globals()["DP_MAX_GRAD_NORM"]

if DP_NOISE_MULTIPLIER is None and "DP_NOISE_MULTIPLIER" in globals():
    DP_NOISE_MULTIPLIER = globals()["DP_NOISE_MULTIPLIER"]

if DP_PRIVACY_BUDGET is None:
    raise KeyError(
        "Privacy budget is not available in the existing configuration."
    )

if DP_DELTA is None:
    raise KeyError(
        "Delta is not available in the existing configuration."
    )

if DP_MAX_GRAD_NORM is None:
    raise KeyError(
        "Gradient clipping norm is not available in the existing configuration."
    )

if DP_NOISE_MULTIPLIER is None:
    raise KeyError(
        "Noise multiplier is not available in the existing configuration."
    )

DP_PRIVACY_BUDGET = float(DP_PRIVACY_BUDGET)
DP_DELTA = float(DP_DELTA)
DP_MAX_GRAD_NORM = float(DP_MAX_GRAD_NORM)
DP_NOISE_MULTIPLIER = float(DP_NOISE_MULTIPLIER)

# ==============================================================================
# 6. TRAINING CONFIGURATION
# ==============================================================================

DP_CTGAN_EPOCHS = find_config_value(
    "epochs",
    "dp_ctgan_epochs"
)

DP_BATCH_SIZE = find_config_value(
    "batch_size",
    "dp_batch_size"
)

DP_LEARNING_RATE = find_config_value(
    "learning_rate",
    "lr",
    "dp_learning_rate"
)

DP_BETA1 = find_config_value(
    "beta1"
)

DP_BETA2 = find_config_value(
    "beta2"
)

LATENT_DIMENSION = find_config_value(
    "latent_dimension",
    "latent_dim",
    "generator_latent_dimension"
)

# ==============================================================================
# 7. REUSE EXISTING VALUES WHEN ALREADY CREATED
# ==============================================================================

if DP_CTGAN_EPOCHS is None and "DP_CTGAN_EPOCHS" in globals():
    DP_CTGAN_EPOCHS = globals()["DP_CTGAN_EPOCHS"]

if DP_BATCH_SIZE is None and "DP_BATCH_SIZE" in globals():
    DP_BATCH_SIZE = globals()["DP_BATCH_SIZE"]

if DP_LEARNING_RATE is None and "DP_LEARNING_RATE" in globals():
    DP_LEARNING_RATE = globals()["DP_LEARNING_RATE"]

if DP_BETA1 is None and "DP_BETA1" in globals():
    DP_BETA1 = globals()["DP_BETA1"]

if DP_BETA2 is None and "DP_BETA2" in globals():
    DP_BETA2 = globals()["DP_BETA2"]

if LATENT_DIMENSION is None and "LATENT_DIMENSION" in globals():
    LATENT_DIMENSION = globals()["LATENT_DIMENSION"]

# ==============================================================================
# 8. VALIDATE REQUIRED TRAINING CONFIGURATION
# ==============================================================================

required_training_values = {
    "DP_CTGAN_EPOCHS": DP_CTGAN_EPOCHS,
    "DP_BATCH_SIZE": DP_BATCH_SIZE,
    "DP_LEARNING_RATE": DP_LEARNING_RATE,
    "DP_BETA1": DP_BETA1,
    "DP_BETA2": DP_BETA2,
    "LATENT_DIMENSION": LATENT_DIMENSION
}

missing_values = [
    name
    for name, value in required_training_values.items()
    if value is None
]

if missing_values:

    raise KeyError(
        "The following required training configuration values "
        "are unavailable: "
        + ", ".join(missing_values)
    )

DP_CTGAN_EPOCHS = int(DP_CTGAN_EPOCHS)
DP_BATCH_SIZE = int(DP_BATCH_SIZE)
DP_LEARNING_RATE = float(DP_LEARNING_RATE)
DP_BETA1 = float(DP_BETA1)
DP_BETA2 = float(DP_BETA2)
LATENT_DIMENSION = int(LATENT_DIMENSION)

# ==============================================================================
# 9. DATALOADER CONFIGURATION
# ==============================================================================

DP_DROP_LAST = find_config_value(
    "drop_last",
    "dp_drop_last"
)

if DP_DROP_LAST is None:

    if "DP_DROP_LAST" in globals():

        DP_DROP_LAST = globals()["DP_DROP_LAST"]

    else:

        DP_DROP_LAST = False

DP_DROP_LAST = bool(DP_DROP_LAST)

# ==============================================================================
# 10. DO NOT REQUIRE HIDDEN DIMENSIONS
# ==============================================================================

# Hidden dimensions are intentionally NOT defined here.
#
# L2 will use the already-created Generator and Discriminator architectures.
# This prevents L1 from introducing a second, inconsistent architecture.

GENERATOR_HIDDEN_DIMENSION = None
DISCRIMINATOR_HIDDEN_DIMENSION = None

# ==============================================================================
# 11. VALIDATION
# ==============================================================================

if DP_PRIVACY_BUDGET <= 0:
    raise ValueError(
        "Privacy budget must be greater than zero."
    )

if not 0 < DP_DELTA < 1:
    raise ValueError(
        "Delta must be between 0 and 1."
    )

if DP_MAX_GRAD_NORM <= 0:
    raise ValueError(
        "Gradient clipping norm must be greater than zero."
    )

if DP_NOISE_MULTIPLIER <= 0:
    raise ValueError(
        "Noise multiplier must be greater than zero."
    )

if DP_CTGAN_EPOCHS <= 0:
    raise ValueError(
        "Number of epochs must be greater than zero."
    )

if DP_BATCH_SIZE <= 0:
    raise ValueError(
        "Batch size must be greater than zero."
    )

if DP_LEARNING_RATE <= 0:
    raise ValueError(
        "Learning rate must be greater than zero."
    )

if LATENT_DIMENSION <= 0:
    raise ValueError(
        "Latent dimension must be greater than zero."
    )

# ==============================================================================
# 12. FINAL CONFIGURATION DISPLAY
# ==============================================================================

print()
print("CONFIGURATION SOURCE")
print("-" * 100)

if "CONFIG_PATH" in globals():
    print(
        f"Configuration File      : "
        f"{CONFIG_PATH}"
    )
else:
    print(
        "Configuration Source    : "
        "Existing CONFIG object"
    )

print()
print("DEVICE")
print("-" * 100)

print(
    f"Device                  : "
    f"{DEVICE}"
)

print(
    f"Seed                    : "
    f"{SEED}"
)

print()
print("DIFFERENTIAL PRIVACY")
print("-" * 100)

print(
    f"Privacy Budget (epsilon): "
    f"{DP_PRIVACY_BUDGET}"
)

print(
    f"Delta                   : "
    f"{DP_DELTA}"
)

print(
    f"Gradient Clip Norm      : "
    f"{DP_MAX_GRAD_NORM}"
)

print(
    f"Noise Multiplier        : "
    f"{DP_NOISE_MULTIPLIER}"
)

print()
print("GAN TRAINING")
print("-" * 100)

print(
    f"Epochs                  : "
    f"{DP_CTGAN_EPOCHS}"
)

print(
    f"Batch Size              : "
    f"{DP_BATCH_SIZE}"
)

print(
    f"Learning Rate           : "
    f"{DP_LEARNING_RATE}"
)

print(
    f"Adam Beta1              : "
    f"{DP_BETA1}"
)

print(
    f"Adam Beta2              : "
    f"{DP_BETA2}"
)

print(
    f"Latent Dimension        : "
    f"{LATENT_DIMENSION}"
)

print()
print("ARCHITECTURE")
print("-" * 100)

print(
    "Generator Architecture  : "
    "Existing L2 Generator"
)

print(
    "Discriminator Architecture: "
    "Existing L2 Discriminator"
)

print()
print("DATALOADER")
print("-" * 100)

print(
    f"Drop Last               : "
    f"{DP_DROP_LAST}"
)

print()
print("=" * 100)
print("L1 CONFIGURATION LOADED SUCCESSFULLY")
print("=" * 100)

====================================================================================================
PART L1 — DP-CTGAN TRAINING CONFIGURATION
====================================================================================================

CONFIGURATION SOURCE
----------------------------------------------------------------------------------------------------
Configuration File      : /content/drive/MyDrive/SPP_GAN_Project/config.yaml

DEVICE
----------------------------------------------------------------------------------------------------
Device                  : cpu
Seed                    : 42

DIFFERENTIAL PRIVACY
----------------------------------------------------------------------------------------------------
Privacy Budget (epsilon): 4.0
Delta                   : 1e-05
Gradient Clip Norm      : 1.0
Noise Multiplier        : 1.1

GAN TRAINING
----------------------------------------------------------------------------------------------------
Epochs                  : 100
Batch Size              : 256
Learning Rate           : 0.0002
Adam Beta1              : 0.5
Adam Beta2              : 0.999
Latent Dimension        : 128

ARCHITECTURE
----------------------------------------------------------------------------------------------------
Generator Architecture  : Existing L2 Generator
Discriminator Architecture: Existing L2 Discriminator

DATALOADER
----------------------------------------------------------------------------------------------------
Drop Last               : False

====================================================================================================
L1 CONFIGURATION LOADED SUCCESSFULLY
====================================================================================================

In [128]:
# ==============================================================================
# PART L2 — GENERATOR AND DISCRIMINATOR DEFINITION
# ==============================================================================

print("=" * 100)
print("PART L2 — GENERATOR AND DISCRIMINATOR DEFINITION")
print("=" * 100)

# ------------------------------------------------------------------------------
# Locate training tensors
# ------------------------------------------------------------------------------

if "TRAIN_TENSORS" in globals() and isinstance(TRAIN_TENSORS, dict):

    SOURCE_TRAIN_TENSORS = TRAIN_TENSORS

elif "DP_TRAIN_TENSORS" in globals() and isinstance(DP_TRAIN_TENSORS, dict):

    SOURCE_TRAIN_TENSORS = DP_TRAIN_TENSORS

else:

    raise RuntimeError(
        "Training tensors were not found. "
        "Expected TRAIN_TENSORS or DP_TRAIN_TENSORS."
    )

# ------------------------------------------------------------------------------
# Dataset list
# ------------------------------------------------------------------------------

DATASETS = list(
    SOURCE_TRAIN_TENSORS.keys()
)

# ------------------------------------------------------------------------------
# Recover existing project configuration
# ------------------------------------------------------------------------------

def get_config_value(names):

    config_objects = []

    if "CONFIG" in globals() and isinstance(CONFIG, dict):
        config_objects.append(CONFIG)

    if "TRAINING_CONFIG" in globals() and isinstance(TRAINING_CONFIG, dict):
        config_objects.append(TRAINING_CONFIG)

    if "PROJECT_CONFIG" in globals() and isinstance(PROJECT_CONFIG, dict):
        config_objects.append(PROJECT_CONFIG)

    for config in config_objects:

        for name in names:

            if name in config:

                value = config[name]

                if value is not None:
                    return value

    for name in names:

        if name in globals():

            value = globals()[name]

            if value is not None:
                return value

    return None

# ------------------------------------------------------------------------------
# Latent dimension
# ------------------------------------------------------------------------------

LATENT_DIMENSION = get_config_value(
    [
        "latent_dimension",
        "latent_dim",
        "LATENT_DIMENSION",
        "GENERATOR_LATENT_DIMENSION"
    ]
)

if LATENT_DIMENSION is None:

    raise RuntimeError(
        "Existing project configuration does not contain "
        "the latent dimension."
    )

LATENT_DIMENSION = int(
    LATENT_DIMENSION
)

# ------------------------------------------------------------------------------
# Hidden dimension
#
# No new manual configuration is introduced.
# Use the existing latent dimension as the hidden dimension.
# ------------------------------------------------------------------------------

GENERATOR_HIDDEN_DIMENSION = get_config_value(
    [
        "generator_hidden_dimension",
        "generator_hidden_dim",
        "GENERATOR_HIDDEN_DIMENSION"
    ]
)

if GENERATOR_HIDDEN_DIMENSION is None:

    GENERATOR_HIDDEN_DIMENSION = LATENT_DIMENSION

GENERATOR_HIDDEN_DIMENSION = int(
    GENERATOR_HIDDEN_DIMENSION
)

# ------------------------------------------------------------------------------
# Discriminator hidden dimension
# ------------------------------------------------------------------------------

DISCRIMINATOR_HIDDEN_DIMENSION = get_config_value(
    [
        "discriminator_hidden_dimension",
        "discriminator_hidden_dim",
        "DISCRIMINATOR_HIDDEN_DIMENSION"
    ]
)

if DISCRIMINATOR_HIDDEN_DIMENSION is None:

    DISCRIMINATOR_HIDDEN_DIMENSION = LATENT_DIMENSION

DISCRIMINATOR_HIDDEN_DIMENSION = int(
    DISCRIMINATOR_HIDDEN_DIMENSION
)

# ------------------------------------------------------------------------------
# Validate configuration
# ------------------------------------------------------------------------------

if LATENT_DIMENSION <= 0:

    raise ValueError(
        "LATENT_DIMENSION must be greater than zero."
    )

if GENERATOR_HIDDEN_DIMENSION <= 0:

    raise ValueError(
        "GENERATOR_HIDDEN_DIMENSION must be greater than zero."
    )

if DISCRIMINATOR_HIDDEN_DIMENSION <= 0:

    raise ValueError(
        "DISCRIMINATOR_HIDDEN_DIMENSION must be greater than zero."
    )

# ------------------------------------------------------------------------------
# Generator
# ------------------------------------------------------------------------------

class DPCTGANGenerator(nn.Module):

    def __init__(
        self,
        input_dim,
        output_dim,
        hidden_dim
    ):

        super().__init__()

        self.network = nn.Sequential(

            nn.Linear(
                int(input_dim),
                int(hidden_dim)
            ),

            nn.LayerNorm(
                int(hidden_dim)
            ),

            nn.ReLU(),

            nn.Linear(
                int(hidden_dim),
                int(hidden_dim)
            ),

            nn.LayerNorm(
                int(hidden_dim)
            ),

            nn.ReLU(),

            nn.Linear(
                int(hidden_dim),
                int(output_dim)
            ),

            nn.Tanh()
        )

    def forward(self, z):

        return self.network(z)

# ------------------------------------------------------------------------------
# Discriminator
# ------------------------------------------------------------------------------

class DPCTGANDiscriminator(nn.Module):

    def __init__(
        self,
        input_dim,
        hidden_dim
    ):

        super().__init__()

        self.network = nn.Sequential(

            nn.Linear(
                int(input_dim),
                int(hidden_dim)
            ),

            nn.LayerNorm(
                int(hidden_dim)
            ),

            nn.LeakyReLU(
                0.2,
                inplace=False
            ),

            nn.Dropout(
                0.1
            ),

            nn.Linear(
                int(hidden_dim),
                int(hidden_dim)
            ),

            nn.LayerNorm(
                int(hidden_dim)
            ),

            nn.LeakyReLU(
                0.2,
                inplace=False
            ),

            nn.Dropout(
                0.1
            ),

            nn.Linear(
                int(hidden_dim),
                int(hidden_dim)
            ),

            nn.LayerNorm(
                int(hidden_dim)
            ),

            nn.LeakyReLU(
                0.2,
                inplace=False
            ),

            nn.Linear(
                int(hidden_dim),
                1
            )
        )

    def forward(self, x):

        return self.network(x)

# ------------------------------------------------------------------------------
# Containers
# ------------------------------------------------------------------------------

GENERATORS = {}

DISCRIMINATORS = {}

GENERATOR_OPTIMIZERS = {}

DISCRIMINATOR_OPTIMIZERS = {}

DP_TRAIN_LOADERS = {}

DATASET_INPUT_DIMENSIONS = {}

# ------------------------------------------------------------------------------
# Create models
# ------------------------------------------------------------------------------

for dataset in DATASETS:

    print()
    print("-" * 80)
    print(f"Dataset: {dataset}")
    print("-" * 80)

    # --------------------------------------------------------------------------
    # Training tensor
    # --------------------------------------------------------------------------

    train_tensor = SOURCE_TRAIN_TENSORS[
        dataset
    ]

    if not torch.is_tensor(train_tensor):

        train_tensor = torch.tensor(
            np.asarray(train_tensor),
            dtype=torch.float32
        )

    train_tensor = (
        train_tensor
        .detach()
        .cpu()
        .float()
    )

    if train_tensor.ndim != 2:

        raise ValueError(
            f"{dataset}: training tensor must be 2-dimensional. "
            f"Received shape {tuple(train_tensor.shape)}."
        )

    input_dim = int(
        train_tensor.shape[1]
    )

    DATASET_INPUT_DIMENSIONS[
        dataset
    ] = input_dim

    # --------------------------------------------------------------------------
    # DataLoader
    # --------------------------------------------------------------------------

    DP_TRAIN_LOADERS[
        dataset
    ] = DataLoader(

        TensorDataset(
            train_tensor
        ),

        batch_size=int(
            DP_BATCH_SIZE
        ),

        shuffle=True,

        drop_last=True
    )

    # --------------------------------------------------------------------------
    # Generator
    # --------------------------------------------------------------------------

    generator = DPCTGANGenerator(

        input_dim=LATENT_DIMENSION,

        output_dim=input_dim,

        hidden_dim=GENERATOR_HIDDEN_DIMENSION

    ).to(DEVICE)

    # --------------------------------------------------------------------------
    # Discriminator
    # --------------------------------------------------------------------------

    discriminator = DPCTGANDiscriminator(

        input_dim=input_dim,

        hidden_dim=DISCRIMINATOR_HIDDEN_DIMENSION

    ).to(DEVICE)

    # --------------------------------------------------------------------------
    # Optimizers
    # --------------------------------------------------------------------------

    generator_optimizer = torch.optim.Adam(

        generator.parameters(),

        lr=float(
            DP_LEARNING_RATE
        ),

        betas=(
            float(DP_BETA1),
            float(DP_BETA2)
        )
    )

    discriminator_optimizer = torch.optim.Adam(

        discriminator.parameters(),

        lr=float(
            DP_LEARNING_RATE
        ),

        betas=(
            float(DP_BETA1),
            float(DP_BETA2)
        )
    )

    # --------------------------------------------------------------------------
    # Store objects
    # --------------------------------------------------------------------------

    GENERATORS[
        dataset
    ] = generator

    DISCRIMINATORS[
        dataset
    ] = discriminator

    GENERATOR_OPTIMIZERS[
        dataset
    ] = generator_optimizer

    DISCRIMINATOR_OPTIMIZERS[
        dataset
    ] = discriminator_optimizer

    # --------------------------------------------------------------------------
    # Model shape verification
    # --------------------------------------------------------------------------

    test_noise = torch.randn(
        2,
        LATENT_DIMENSION,
        device=DEVICE
    )

    with torch.no_grad():

        test_fake = generator(
            test_noise
        )

        test_output = discriminator(
            test_fake
        )

    if test_fake.shape != (
        2,
        input_dim
    ):

        raise RuntimeError(
            f"{dataset}: incorrect Generator output shape. "
            f"Expected {(2, input_dim)}, "
            f"received {tuple(test_fake.shape)}."
        )

    if test_output.shape != (
        2,
        1
    ):

        raise RuntimeError(
            f"{dataset}: incorrect Discriminator output shape. "
            f"Expected {(2, 1)}, "
            f"received {tuple(test_output.shape)}."
        )

    print(
        f"Rows                     : {len(train_tensor)}"
    )

    print(
        f"Features                 : {input_dim}"
    )

    print(
        f"Latent Dimension         : {LATENT_DIMENSION}"
    )

    print(
        f"Generator Hidden Dim     : "
        f"{GENERATOR_HIDDEN_DIMENSION}"
    )

    print(
        f"Discriminator Hidden Dim : "
        f"{DISCRIMINATOR_HIDDEN_DIMENSION}"
    )

    print(
        f"Generator Output Shape   : "
        f"{tuple(test_fake.shape)}"
    )

    print(
        f"Discriminator Output     : "
        f"{tuple(test_output.shape)}"
    )

    print(
        "Model Validation         : PASS"
    )

# ------------------------------------------------------------------------------
# Final verification
# ------------------------------------------------------------------------------

if set(GENERATORS.keys()) != set(DATASETS):

    raise RuntimeError(
        "Generator creation failed."
    )

if set(DISCRIMINATORS.keys()) != set(DATASETS):

    raise RuntimeError(
        "Discriminator creation failed."
    )

if set(DP_TRAIN_LOADERS.keys()) != set(DATASETS):

    raise RuntimeError(
        "DataLoader creation failed."
    )

print()
print("=" * 100)
print("PART L2 VERIFICATION")
print("=" * 100)

print(
    f"Datasets                  : {len(DATASETS)}"
)

print(
    f"Generators                : {len(GENERATORS)}"
)

print(
    f"Discriminators             : {len(DISCRIMINATORS)}"
)

print(
    f"Training DataLoaders       : {len(DP_TRAIN_LOADERS)}"
)

print(
    f"Latent Dimension           : {LATENT_DIMENSION}"
)

print(
    f"Generator Hidden Dimension : "
    f"{GENERATOR_HIDDEN_DIMENSION}"
)

print(
    f"Discriminator Hidden Dim   : "
    f"{DISCRIMINATOR_HIDDEN_DIMENSION}"
)

print()
print(
    "PART L2 — GENERATOR AND DISCRIMINATOR DEFINITION : PASS"
)

====================================================================================================
PART L2 — GENERATOR AND DISCRIMINATOR DEFINITION
====================================================================================================

--------------------------------------------------------------------------------
Dataset: Adult Income
--------------------------------------------------------------------------------
Rows                     : 22760
Features                 : 15
Latent Dimension         : 128
Generator Hidden Dim     : 128
Discriminator Hidden Dim : 128
Generator Output Shape   : (2, 15)
Discriminator Output     : (2, 1)
Model Validation         : PASS

--------------------------------------------------------------------------------
Dataset: Bank Marketing
--------------------------------------------------------------------------------
Rows                     : 31647
Features                 : 17
Latent Dimension         : 128
Generator Hidden Dim     : 128
Discriminator Hidden Dim : 128
Generator Output Shape   : (2, 17)
Discriminator Output     : (2, 1)
Model Validation         : PASS

--------------------------------------------------------------------------------
Dataset: diabetes_130us
--------------------------------------------------------------------------------
Rows                     : 71236
Features                 : 48
Latent Dimension         : 128
Generator Hidden Dim     : 128
Discriminator Hidden Dim : 128
Generator Output Shape   : (2, 48)
Discriminator Output     : (2, 1)
Model Validation         : PASS

====================================================================================================
PART L2 VERIFICATION
====================================================================================================
Datasets                  : 3
Generators                : 3
Discriminators             : 3
Training DataLoaders       : 3
Latent Dimension           : 128
Generator Hidden Dimension : 128
Discriminator Hidden Dim   : 128

PART L2 — GENERATOR AND DISCRIMINATOR DEFINITION : PASS

In [129]:
# ==============================================================================
# PART L3 — DP TRAINING INITIALIZATION
# ==============================================================================

print("=" * 100)
print("PART L3 — DP TRAINING INITIALIZATION")
print("=" * 100)

# ------------------------------------------------------------------------------
# Loss function
# ------------------------------------------------------------------------------

DP_BCE_LOSS = nn.BCEWithLogitsLoss(
    reduction="none"
)

# ------------------------------------------------------------------------------
# Optimizer containers from L2
# ------------------------------------------------------------------------------

if "GENERATOR_OPTIMIZERS" not in globals():
    raise RuntimeError(
        "GENERATOR_OPTIMIZERS was not created in L2."
    )

if "DISCRIMINATOR_OPTIMIZERS" not in globals():
    raise RuntimeError(
        "DISCRIMINATOR_OPTIMIZERS was not created in L2."
    )

# ------------------------------------------------------------------------------
# Training history
# ------------------------------------------------------------------------------

DP_TRAINING_HISTORY = {}

# ------------------------------------------------------------------------------
# Training results
# ------------------------------------------------------------------------------

DP_TRAINING_COMPLETED = {}

DP_TRAINING_ERRORS = {}

# ------------------------------------------------------------------------------
# Privacy information
# ------------------------------------------------------------------------------

DP_PRIVACY_SUMMARY = {}

# ------------------------------------------------------------------------------
# Validate required DP configuration
# ------------------------------------------------------------------------------

required_config = {
    "DP_PRIVACY_BUDGET": DP_PRIVACY_BUDGET,
    "DP_DELTA": DP_DELTA,
    "DP_MAX_GRAD_NORM": DP_MAX_GRAD_NORM,
    "DP_NOISE_MULTIPLIER": DP_NOISE_MULTIPLIER,
    "DP_CTGAN_EPOCHS": DP_CTGAN_EPOCHS,
    "DP_BATCH_SIZE": DP_BATCH_SIZE
}

for name, value in required_config.items():

    if value is None:

        raise RuntimeError(
            f"{name} is not initialized."
        )

# ------------------------------------------------------------------------------
# Configuration validation
# ------------------------------------------------------------------------------

if DP_PRIVACY_BUDGET <= 0:

    raise ValueError(
        "DP_PRIVACY_BUDGET must be greater than zero."
    )

if not 0 < DP_DELTA < 1:

    raise ValueError(
        "DP_DELTA must be between 0 and 1."
    )

if DP_MAX_GRAD_NORM <= 0:

    raise ValueError(
        "DP_MAX_GRAD_NORM must be greater than zero."
    )

if DP_NOISE_MULTIPLIER <= 0:

    raise ValueError(
        "DP_NOISE_MULTIPLIER must be greater than zero."
    )

if DP_CTGAN_EPOCHS <= 0:

    raise ValueError(
        "DP_CTGAN_EPOCHS must be greater than zero."
    )

if DP_BATCH_SIZE <= 0:

    raise ValueError(
        "DP_BATCH_SIZE must be greater than zero."
    )

# ------------------------------------------------------------------------------
# Dataset initialization
# ------------------------------------------------------------------------------

for dataset in DATASETS:

    print()
    print("-" * 80)
    print(dataset)
    print("-" * 80)

    # --------------------------------------------------------------------------
    # Validate Generator
    # --------------------------------------------------------------------------

    if dataset not in GENERATORS:

        raise KeyError(
            f"Generator missing for {dataset}."
        )

    # --------------------------------------------------------------------------
    # Validate Discriminator
    # --------------------------------------------------------------------------

    if dataset not in DISCRIMINATORS:

        raise KeyError(
            f"Discriminator missing for {dataset}."
        )

    # --------------------------------------------------------------------------
    # Validate Generator optimizer
    # --------------------------------------------------------------------------

    if dataset not in GENERATOR_OPTIMIZERS:

        raise KeyError(
            f"Generator optimizer missing for {dataset}."
        )

    # --------------------------------------------------------------------------
    # Validate Discriminator optimizer
    # --------------------------------------------------------------------------

    if dataset not in DISCRIMINATOR_OPTIMIZERS:

        raise KeyError(
            f"Discriminator optimizer missing for {dataset}."
        )

    # --------------------------------------------------------------------------
    # Validate DataLoader
    # --------------------------------------------------------------------------

    if dataset not in DP_TRAIN_LOADERS:

        raise KeyError(
            f"Training loader missing for {dataset}."
        )

    train_loader = DP_TRAIN_LOADERS[
        dataset
    ]

    sample_count = len(
        train_loader.dataset
    )

    batch_count = len(
        train_loader
    )

    if sample_count <= 0:

        raise ValueError(
            f"{dataset}: training dataset is empty."
        )

    if batch_count <= 0:

        raise ValueError(
            f"{dataset}: DataLoader contains no batches."
        )

    # --------------------------------------------------------------------------
    # Determine actual batch size
    # --------------------------------------------------------------------------

    actual_batch_size = min(
        int(DP_BATCH_SIZE),
        int(sample_count)
    )

    # --------------------------------------------------------------------------
    # Sample rate
    # --------------------------------------------------------------------------

    sample_rate = (
        actual_batch_size /
        sample_count
    )

    # --------------------------------------------------------------------------
    # Initialize history
    # --------------------------------------------------------------------------

    DP_TRAINING_HISTORY[
        dataset
    ] = {

        "Discriminator Loss": [],

        "Generator Loss": [],

        "Gradient Norm": [],

        "Noise Scale": []

    }

    # --------------------------------------------------------------------------
    # Initialize status
    # --------------------------------------------------------------------------

    DP_TRAINING_COMPLETED[
        dataset
    ] = False

    DP_TRAINING_ERRORS[
        dataset
    ] = None

    # --------------------------------------------------------------------------
    # Privacy summary
    # --------------------------------------------------------------------------

    DP_PRIVACY_SUMMARY[
        dataset
    ] = {

        "Training Samples":
            int(sample_count),

        "Batches Per Epoch":
            int(batch_count),

        "Batch Size":
            int(actual_batch_size),

        "Sample Rate":
            float(sample_rate),

        "Epochs":
            int(DP_CTGAN_EPOCHS),

        "Epsilon Target":
            float(DP_PRIVACY_BUDGET),

        "Delta":
            float(DP_DELTA),

        "Noise Multiplier":
            float(DP_NOISE_MULTIPLIER),

        "Gradient Clip Norm":
            float(DP_MAX_GRAD_NORM)

    }

    # --------------------------------------------------------------------------
    # Display initialization
    # --------------------------------------------------------------------------

    print(
        f"Training Samples       : {sample_count}"
    )

    print(
        f"Batches / Epoch        : {batch_count}"
    )

    print(
        f"Batch Size             : {actual_batch_size}"
    )

    print(
        f"Sample Rate            : "
        f"{sample_rate:.8f}"
    )

    print(
        f"Epochs                 : "
        f"{DP_CTGAN_EPOCHS}"
    )

    print(
        f"Privacy Budget         : "
        f"{DP_PRIVACY_BUDGET}"
    )

    print(
        f"Delta                  : "
        f"{DP_DELTA}"
    )

    print(
        f"Gradient Clip Norm     : "
        f"{DP_MAX_GRAD_NORM}"
    )

    print(
        f"Noise Multiplier       : "
        f"{DP_NOISE_MULTIPLIER}"
    )

    print(
        "Initialization         : PASS"
    )

# ------------------------------------------------------------------------------
# Final verification
# ------------------------------------------------------------------------------

if set(DP_TRAINING_HISTORY.keys()) != set(DATASETS):

    raise RuntimeError(
        "Training history initialization failed."
    )

if set(DP_PRIVACY_SUMMARY.keys()) != set(DATASETS):

    raise RuntimeError(
        "Privacy summary initialization failed."
    )

if set(DP_TRAINING_COMPLETED.keys()) != set(DATASETS):

    raise RuntimeError(
        "Training status initialization failed."
    )

# ------------------------------------------------------------------------------
# Final output
# ------------------------------------------------------------------------------

print()
print("=" * 100)
print("PART L3 VERIFICATION")
print("=" * 100)

print(
    f"Datasets Initialized    : {len(DATASETS)}"
)

print(
    f"Training Histories      : "
    f"{len(DP_TRAINING_HISTORY)}"
)

print(
    f"Privacy Summaries       : "
    f"{len(DP_PRIVACY_SUMMARY)}"
)

print(
    f"Training Status Records : "
    f"{len(DP_TRAINING_COMPLETED)}"
)

print()
print(
    "Opacus                  : NOT USED"
)

print(
    "PrivacyEngine           : NOT USED"
)

print(
    "GradSampleModule        : NOT USED"
)

print(
    "Manual DP Training      : READY"
)

print()
print(
    "PART L3 — DP TRAINING INITIALIZATION : PASS"
)

====================================================================================================
PART L3 — DP TRAINING INITIALIZATION
====================================================================================================

--------------------------------------------------------------------------------
Adult Income
--------------------------------------------------------------------------------
Training Samples       : 22760
Batches / Epoch        : 88
Batch Size             : 256
Sample Rate            : 0.01124780
Epochs                 : 100
Privacy Budget         : 4.0
Delta                  : 1e-05
Gradient Clip Norm     : 1.0
Noise Multiplier       : 1.1
Initialization         : PASS

--------------------------------------------------------------------------------
Bank Marketing
--------------------------------------------------------------------------------
Training Samples       : 31647
Batches / Epoch        : 123
Batch Size             : 256
Sample Rate            : 0.00808923
Epochs                 : 100
Privacy Budget         : 4.0
Delta                  : 1e-05
Gradient Clip Norm     : 1.0
Noise Multiplier       : 1.1
Initialization         : PASS

--------------------------------------------------------------------------------
diabetes_130us
--------------------------------------------------------------------------------
Training Samples       : 71236
Batches / Epoch        : 278
Batch Size             : 256
Sample Rate            : 0.00359369
Epochs                 : 100
Privacy Budget         : 4.0
Delta                  : 1e-05
Gradient Clip Norm     : 1.0
Noise Multiplier       : 1.1
Initialization         : PASS

====================================================================================================
PART L3 VERIFICATION
====================================================================================================
Datasets Initialized    : 3
Training Histories      : 3
Privacy Summaries       : 3
Training Status Records : 3

Opacus                  : NOT USED
PrivacyEngine           : NOT USED
GradSampleModule        : NOT USED
Manual DP Training      : READY

PART L3 — DP TRAINING INITIALIZATION : PASS

In [ ]:
# ==============================================================================
# PART L4 — DP TRAINING LOOP
# ==============================================================================

print("=" * 100)
print("PART L4 — DP TRAINING LOOP")
print("=" * 100)

# ------------------------------------------------------------------------------
# Manual DP-SGD discriminator update
# ------------------------------------------------------------------------------

def manual_dp_discriminator_update(
    discriminator,
    real_data,
    fake_data,
    optimizer,
    max_grad_norm,
    noise_multiplier
):

    discriminator.train()

    optimizer.zero_grad(set_to_none=True)

    parameters = [
        parameter
        for parameter in discriminator.parameters()
        if parameter.requires_grad
    ]

    if len(parameters) == 0:
        raise RuntimeError(
            "Discriminator has no trainable parameters."
        )

    real_batch_size = real_data.size(0)
    fake_batch_size = fake_data.size(0)

    if real_batch_size != fake_batch_size:
        raise RuntimeError(
            "Real and fake batch sizes must be identical."
        )

    # --------------------------------------------------------------------------
    # Per-example gradients for REAL private data
    # --------------------------------------------------------------------------

    accumulated_real_gradients = [
        torch.zeros_like(parameter)
        for parameter in parameters
    ]

    total_real_gradient_norm = 0.0

    for sample_index in range(real_batch_size):

        real_sample = real_data[
            sample_index:sample_index + 1
        ]

        real_output = discriminator(
            real_sample
        )

        real_target = torch.ones(
            1,
            1,
            device=real_data.device
        )

        real_sample_loss = F.binary_cross_entropy_with_logits(
            real_output,
            real_target,
            reduction="mean"
        )

        sample_gradients = torch.autograd.grad(
            real_sample_loss,
            parameters,
            retain_graph=False,
            create_graph=False,
            allow_unused=False
        )

        squared_norm = torch.zeros(
            (),
            device=real_data.device
        )

        for gradient in sample_gradients:

            squared_norm = (
                squared_norm
                +
                gradient.detach().pow(2).sum()
            )

        gradient_norm = torch.sqrt(
            squared_norm + 1e-12
        )

        clipping_factor = torch.clamp(
            max_grad_norm / gradient_norm,
            max=1.0
        )

        for index, gradient in enumerate(
            sample_gradients
        ):

            accumulated_real_gradients[index].add_(
                gradient.detach()
                *
                clipping_factor
            )

        total_real_gradient_norm += (
            gradient_norm.item()
        )

    # --------------------------------------------------------------------------
    # Add Gaussian noise to REAL gradients
    # --------------------------------------------------------------------------

    noise_scale = (
        noise_multiplier
        *
        max_grad_norm
    )

    noisy_real_gradients = []

    for gradient in accumulated_real_gradients:

        noise = torch.randn_like(
            gradient
        ) * noise_scale

        noisy_gradient = (
            gradient
            +
            noise
        ) / real_batch_size

        noisy_real_gradients.append(
            noisy_gradient
        )

    # --------------------------------------------------------------------------
    # Fake-data discriminator gradient
    # --------------------------------------------------------------------------

    fake_output = discriminator(
        fake_data.detach()
    )

    fake_target = torch.zeros(
        fake_batch_size,
        1,
        device=fake_data.device
    )

    fake_loss = F.binary_cross_entropy_with_logits(
        fake_output,
        fake_target,
        reduction="mean"
    )

    fake_gradients = torch.autograd.grad(
        fake_loss,
        parameters,
        retain_graph=False,
        create_graph=False,
        allow_unused=False
    )

    # --------------------------------------------------------------------------
    # Combine REAL DP gradient + FAKE gradient
    # --------------------------------------------------------------------------

    for index, parameter in enumerate(
        parameters
    ):

        parameter.grad = (
            0.5
            *
            noisy_real_gradients[index]
            +
            0.5
            *
            fake_gradients[index].detach()
        )

    # --------------------------------------------------------------------------
    # Optimizer update
    # --------------------------------------------------------------------------

    optimizer.step()

    average_real_gradient_norm = (
        total_real_gradient_norm
        /
        real_batch_size
    )

    discriminator_loss_value = (
        0.5
        *
        (
            F.binary_cross_entropy_with_logits(
                discriminator(real_data).detach(),
                torch.ones(
                    real_batch_size,
                    1,
                    device=real_data.device
                )
            ).item()
        )
        +
        0.5
        *
        fake_loss.detach().item()
    )

    return (
        discriminator_loss_value,
        average_real_gradient_norm
    )


# ------------------------------------------------------------------------------
# Main DP-CTGAN training loop
# ------------------------------------------------------------------------------

for dataset in DATASETS:

    print()
    print("=" * 80)
    print(dataset)
    print("=" * 80)

    generator = GENERATORS[dataset]

    discriminator = DISCRIMINATORS[dataset]

    generator_optimizer = (
        GENERATOR_OPTIMIZERS[dataset]
    )

    discriminator_optimizer = (
        DISCRIMINATOR_OPTIMIZERS[dataset]
    )

    train_loader = DP_TRAIN_LOADERS[dataset]

    try:

        for epoch in range(
            DP_CTGAN_EPOCHS
        ):

            generator.train()

            discriminator.train()

            epoch_d_loss = 0.0
            epoch_g_loss = 0.0
            epoch_gradient_norm = 0.0
            epoch_batches = 0

            # ------------------------------------------------------------------
            # Training batches
            # ------------------------------------------------------------------

            for batch in train_loader:

                real_data = (
                    batch[0]
                    .to(DEVICE)
                    .float()
                )

                batch_size = real_data.size(0)

                if batch_size == 0:
                    continue

                # ==============================================================
                # DISCRIMINATOR UPDATE
                # ==============================================================

                noise = torch.randn(
                    batch_size,
                    LATENT_DIMENSION,
                    device=DEVICE
                )

                with torch.no_grad():

                    fake_data = generator(
                        noise
                    )

                (
                    discriminator_loss_value,
                    average_gradient_norm
                ) = manual_dp_discriminator_update(
                    discriminator=discriminator,
                    real_data=real_data,
                    fake_data=fake_data,
                    optimizer=discriminator_optimizer,
                    max_grad_norm=DP_MAX_GRAD_NORM,
                    noise_multiplier=DP_NOISE_MULTIPLIER
                )

                # ==============================================================
                # GENERATOR UPDATE
                # ==============================================================

                generator_optimizer.zero_grad(
                    set_to_none=True
                )

                # Freeze discriminator parameters.
                # This prevents discriminator parameters from being updated
                # during the generator step while preserving the gradient path
                # from discriminator output back to generator output.

                for parameter in discriminator.parameters():

                    parameter.requires_grad_(False)

                noise = torch.randn(
                    batch_size,
                    LATENT_DIMENSION,
                    device=DEVICE
                )

                generated_data = generator(
                    noise
                )

                generated_output = discriminator(
                    generated_data
                )

                generator_target = torch.ones(
                    batch_size,
                    1,
                    device=DEVICE
                )

                generator_loss = (
                    F.binary_cross_entropy_with_logits(
                        generated_output,
                        generator_target
                    )
                )

                generator_loss.backward()

                generator_optimizer.step()

                # Restore discriminator gradients.

                for parameter in discriminator.parameters():

                    parameter.requires_grad_(True)

                # ==============================================================
                # Statistics
                # ==============================================================

                epoch_d_loss += (
                    discriminator_loss_value
                )

                epoch_g_loss += (
                    generator_loss.detach().item()
                )

                epoch_gradient_norm += (
                    average_gradient_norm
                )

                epoch_batches += 1

            # ------------------------------------------------------------------
            # Validate epoch
            # ------------------------------------------------------------------

            if epoch_batches == 0:

                raise RuntimeError(
                    f"No training batches were processed for {dataset}."
                )

            average_d_loss = (
                epoch_d_loss
                /
                epoch_batches
            )

            average_g_loss = (
                epoch_g_loss
                /
                epoch_batches
            )

            average_gradient_norm = (
                epoch_gradient_norm
                /
                epoch_batches
            )

            if not np.isfinite(
                average_d_loss
            ):

                raise RuntimeError(
                    f"Non-finite discriminator loss "
                    f"at epoch {epoch + 1}."
                )

            if not np.isfinite(
                average_g_loss
            ):

                raise RuntimeError(
                    f"Non-finite generator loss "
                    f"at epoch {epoch + 1}."
                )

            if not np.isfinite(
                average_gradient_norm
            ):

                raise RuntimeError(
                    f"Non-finite gradient norm "
                    f"at epoch {epoch + 1}."
                )

            # ------------------------------------------------------------------
            # Store history
            # ------------------------------------------------------------------

            DP_TRAINING_HISTORY[dataset][
                "Discriminator Loss"
            ].append(
                average_d_loss
            )

            DP_TRAINING_HISTORY[dataset][
                "Generator Loss"
            ].append(
                average_g_loss
            )

            DP_TRAINING_HISTORY[dataset][
                "Gradient Norm"
            ].append(
                average_gradient_norm
            )

            DP_TRAINING_HISTORY[dataset][
                "Noise Scale"
            ].append(
                DP_NOISE_MULTIPLIER
                *
                DP_MAX_GRAD_NORM
            )

            # ------------------------------------------------------------------
            # Progress
            # ------------------------------------------------------------------

            if (
                epoch == 0
                or
                (epoch + 1) % 10 == 0
                or
                epoch == DP_CTGAN_EPOCHS - 1
            ):

                print(
                    f"Epoch {epoch + 1:3d}/"
                    f"{DP_CTGAN_EPOCHS} | "
                    f"D Loss: {average_d_loss:.4f} | "
                    f"G Loss: {average_g_loss:.4f} | "
                    f"Grad Norm: {average_gradient_norm:.4f}"
                )

        # ----------------------------------------------------------------------
        # Dataset completed
        # ----------------------------------------------------------------------

        DP_TRAINING_COMPLETED[
            dataset
        ] = True

        DP_TRAINING_ERRORS[
            dataset
        ] = None

        print()
        print("DP-CTGAN Training : PASS")

    except Exception as error:

        DP_TRAINING_COMPLETED[
            dataset
        ] = False

        DP_TRAINING_ERRORS[
            dataset
        ] = (
            f"{type(error).__name__}: {error}"
        )

        print()
        print("DP-CTGAN Training : FAIL")
        print(
            f"Error Type       : "
            f"{type(error).__name__}"
        )
        print(
            f"Error Message    : "
            f"{error}"
        )

        raise


print()
print("L4 DP training loop completed.")
print("Manual DP-SGD training completed without Opacus.")

====================================================================================================
PART L4 — DP TRAINING LOOP
====================================================================================================

================================================================================
Adult Income
================================================================================
Epoch   1/100 | D Loss: 0.2350 | G Loss: 2.4476 | Grad Norm: 4.3311

In [ ]:
# ==============================================================================
# PART L5 — TRAINING HISTORY
# ==============================================================================

print("=" * 100)
print("PART L5 — TRAINING HISTORY")
print("=" * 100)

for dataset in DATASETS:

    history = DP_TRAINING_HISTORY[dataset]

    print()
    print(dataset)

    print(
        f"Epochs Recorded       : "
        f"{len(history['Discriminator Loss'])}"
    )

    print(
        f"Discriminator Losses  : "
        f"{len(history['Discriminator Loss'])}"
    )

    print(
        f"Generator Losses      : "
        f"{len(history['Generator Loss'])}"
    )

    print(
        f"Gradient Norm Records : "
        f"{len(history['Gradient Norm'])}"
    )

    print(
        f"Noise Records         : "
        f"{len(history['Noise Scale'])}"
    )

    if history["Discriminator Loss"]:

        print(
            f"Final D Loss          : "
            f"{history['Discriminator Loss'][-1]:.6f}"
        )

    if history["Generator Loss"]:

        print(
            f"Final G Loss          : "
            f"{history['Generator Loss'][-1]:.6f}"
        )

print()
print("Training history verification completed.")

In [ ]:
# ==============================================================================
# PART L6 — TRAINING RESULTS SUMMARY
# ==============================================================================

print("=" * 100)
print("PART L6 — DP-CTGAN TRAINING RESULTS SUMMARY")
print("=" * 100)

for dataset in DATASETS:

    history = DP_TRAINING_HISTORY[dataset]

    completed = DP_TRAINING_COMPLETED.get(
        dataset,
        False
    )

    error = DP_TRAINING_ERRORS.get(
        dataset
    )

    privacy = DP_PRIVACY_SUMMARY[
        dataset
    ]

    epochs_completed = len(
        history["Discriminator Loss"]
    )

    final_d_loss = (
        history["Discriminator Loss"][-1]
        if history["Discriminator Loss"]
        else np.nan
    )

    final_g_loss = (
        history["Generator Loss"][-1]
        if history["Generator Loss"]
        else np.nan
    )

    print()
    print("-" * 80)
    print(dataset)
    print("-" * 80)

    print(
        f"Training Completed    : "
        f"{'PASS' if completed else 'FAIL'}"
    )

    print(
        f"Epochs Completed      : "
        f"{epochs_completed}"
    )

    print(
        f"Final D Loss          : "
        f"{final_d_loss:.6f}"
    )

    print(
        f"Final G Loss          : "
        f"{final_g_loss:.6f}"
    )

    print(
        f"Sample Rate           : "
        f"{privacy['Sample Rate']:.8f}"
    )

    print(
        f"Noise Multiplier      : "
        f"{privacy['Noise Multiplier']}"
    )

    print(
        f"Gradient Clip Norm    : "
        f"{privacy['Gradient Clip Norm']}"
    )

    print(
        f"Target Epsilon        : "
        f"{privacy['Epsilon Target']}"
    )

    print(
        f"Delta                 : "
        f"{privacy['Delta']}"
    )

    if error is not None:

        print(
            f"Training Error        : "
            f"{error}"
        )

print()
print("DP-CTGAN results summary generated.")

In [ ]:
# ==============================================================================
# PART L7 — FINAL TRAINING VERIFICATION
# ==============================================================================

print("=" * 100)
print("PART L7 — FINAL DP-CTGAN TRAINING VERIFICATION")
print("=" * 100)

FINAL_TRAINING_VERIFICATION = {}

# ------------------------------------------------------------------------------
# Verify every dataset
# ------------------------------------------------------------------------------

for dataset in DATASETS:

    history = DP_TRAINING_HISTORY.get(
        dataset,
        {}
    )

    discriminator_losses = history.get(
        "Discriminator Loss",
        []
    )

    generator_losses = history.get(
        "Generator Loss",
        []
    )

    gradient_norms = history.get(
        "Gradient Norm",
        []
    )

    noise_scales = history.get(
        "Noise Scale",
        []
    )

    # --------------------------------------------------------------------------
    # Individual checks
    # --------------------------------------------------------------------------

    training_completed = (
        DP_TRAINING_COMPLETED.get(
            dataset,
            False
        )
    )

    correct_epoch_count = (
        len(discriminator_losses)
        ==
        DP_CTGAN_EPOCHS
    )

    discriminator_losses_finite = (
        len(discriminator_losses) > 0
        and
        np.isfinite(
            np.asarray(
                discriminator_losses
            )
        ).all()
    )

    generator_losses_finite = (
        len(generator_losses) > 0
        and
        np.isfinite(
            np.asarray(
                generator_losses
            )
        ).all()
    )

    gradient_norms_finite = (
        len(gradient_norms) > 0
        and
        np.isfinite(
            np.asarray(
                gradient_norms
            )
        ).all()
    )

    noise_applied = (
        len(noise_scales) > 0
        and
        all(
            value > 0
            for value in noise_scales
        )
    )

    no_opacus_dependency = (
        "opacus" not in
        str(
            type(
                DISCRIMINATORS[dataset]
            )
        ).lower()
    )

    all_checks_pass = all(
        [
            training_completed,
            correct_epoch_count,
            discriminator_losses_finite,
            generator_losses_finite,
            gradient_norms_finite,
            noise_applied,
            no_opacus_dependency
        ]
    )

    FINAL_TRAINING_VERIFICATION[
        dataset
    ] = {

        "Training Completed":
            training_completed,

        "Epoch Count":
            correct_epoch_count,

        "Discriminator Loss Finite":
            discriminator_losses_finite,

        "Generator Loss Finite":
            generator_losses_finite,

        "Gradient Norm Finite":
            gradient_norms_finite,

        "Gaussian Noise Applied":
            noise_applied,

        "No Opacus Model":
            no_opacus_dependency,

        "Overall":
            all_checks_pass
    }

# ------------------------------------------------------------------------------
# Print verification
# ------------------------------------------------------------------------------

for dataset in DATASETS:

    print()
    print("-" * 80)
    print(dataset)
    print("-" * 80)

    checks = FINAL_TRAINING_VERIFICATION[
        dataset
    ]

    for check_name, status in checks.items():

        print(
            f"{check_name:30s}: "
            f"{'PASS' if status else 'FAIL'}"
        )

# ------------------------------------------------------------------------------
# Final status
# ------------------------------------------------------------------------------

ALL_DATASETS_VERIFIED = all(
    checks["Overall"]
    for checks
    in FINAL_TRAINING_VERIFICATION.values()
)

print()
print("=" * 100)

if ALL_DATASETS_VERIFIED:

    print(
        "FINAL DP-CTGAN TRAINING VERIFICATION : PASS"
    )

    print(
        "All datasets completed the non-Opacus "
        "DP training pipeline successfully."
    )

else:

    print(
        "FINAL DP-CTGAN TRAINING VERIFICATION : FAIL"
    )

    raise RuntimeError(
        "One or more datasets failed final "
        "DP-CTGAN training verification."
    )

print("=" * 100)