<a href="https://colab.research.google.com/github/amzad-786githumb/Privacy-Preserving-Synthetic-Tabular-Data-Generation-Using-Generative-Adversarial-Networks/blob/main/07_Proposed_Framework.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# =======================================================
# NOTEBOOK 07
#
# Privacy-Preserving Statistical–Machine Learning Synthetic Data Generation
# — Proposed SPP-GAN Framework
# ========================================================

"""
SPP-GAN: A Privacy-Preserving Statistical–Machine Learning Framework for
High-Fidelity Synthetic Tabular Data Generation

Researcher
---------
Mohd Amzad

Notebook
--------
Notebook 07 – Proposed SPP-GAN Framework for Privacy-Preserving
High-Fidelity Synthetic Tabular Data Generation

Purpose
-------
This notebook implements the proposed SPP-GAN framework for privacy-preserving
high-fidelity synthetic tabular data generation.

The framework integrates statistical distribution preservation, machine
learning-based generative modeling, adversarial learning, and differential
privacy into a unified synthetic data generation methodology.

SPP-GAN is developed as the proposed research framework following the
statistical and machine learning baselines established in the preceding
notebooks.

The framework is designed to generate synthetic tabular datasets while
maintaining an appropriate balance between:

• Privacy
• Statistical fidelity
• Distribution preservation
• Correlation preservation
• Data utility
• Structural consistency

Model Implemented
-----------------
• SPP-GAN
  Privacy-Preserving Statistical–Machine Learning Generative Adversarial
  Network Framework

Research Components
-------------------
• Statistical feature representation
• Adversarial generative modeling
• Privacy-preserving training
• Differential Privacy
• Gradient clipping
• Gaussian noise mechanism
• Privacy accounting
• Distribution-preserving objectives
• Correlation-preserving objectives
• Synthetic data generation

Privacy Mechanism
-----------------
• Differential Privacy
• DP-SGD
• Per-sample gradient computation
• Gradient clipping
• Gaussian noise addition
• Privacy accounting using (ε, δ)-Differential Privacy
• Opacus PrivacyEngine where applicable

Inputs
------
Notebook 02
• Preprocessed datasets
• Dataset metadata
• Feature information
• Train, validation, and test splits

Previous Generative Modeling Notebooks
--------------------------------------
Notebook 04
• CTGAN baseline
• Synthetic data generation
• Baseline evaluation artifacts

Notebook 05
• TVAE baseline
• Synthetic data generation
• Baseline evaluation artifacts

Notebook 06
• DP-CTGAN baseline
• Differentially private GAN training
• Privacy-accounting artifacts

Project Configuration
---------------------
• config.yaml
• Reproducibility settings
• Dataset configuration
• SPP-GAN hyperparameters
• Privacy parameters
• Model configuration
• Evaluation configuration

Datasets
--------
• Adult Income
• Bank Marketing
• diabetes_130us

Outputs
-------
• Trained SPP-GAN generator models
• Trained SPP-GAN discriminator models
• Synthetic datasets
• Model checkpoints
• Training history
• Privacy-training history
• Privacy-accounting results
• SPP-GAN configuration records
• Dataset-level results
• Generated visualizations
• Intermediate research artifacts
• Final research-readiness report

Workflow
--------
A. Environment Setup
B. Project Configuration
C. Dataset Loading and Validation
D. Feature and Tensor Preparation
E. SPP-GAN Configuration
F. Differential Privacy Configuration
G. Generator Architecture
H. Discriminator Architecture
I. SPP-GAN Loss Functions
J. Optimizers
K. Privacy Mechanism Configuration
L. SPP-GAN Training
M. Privacy Accounting
N. Synthetic Data Generation
O. Synthetic Data Validation
P. Model and Dataset Saving
Q. Training and Privacy Visualizations
R. Research Results Summary
S. Final Verification
T. Research Readiness Report

Research Role
-------------
Notebook 07 implements the proposed SPP-GAN methodology and serves as the
principal experimental notebook for the proposed research framework.

The models developed in this notebook are evaluated against the established
generative baselines, including CTGAN, TVAE, and DP-CTGAN, using the common
evaluation methodology established across the research pipeline.

The comparative evaluation focuses on privacy, statistical fidelity,
distribution preservation, correlation preservation, structural
consistency, and downstream data utility.

The results generated by this notebook provide the experimental evidence
required to assess the effectiveness of the proposed SPP-GAN framework
against the baseline synthetic data generation methods.

Research Objective
------------------
The primary objective of SPP-GAN is to investigate whether an integrated
privacy-preserving statistical–machine learning generative framework can
produce higher-quality synthetic tabular data while maintaining a rigorous
differential privacy guarantee and improving the privacy–utility–fidelity
trade-off relative to established baseline approaches.

Version
-------
1.0
"""

In [1]:
# ==============================================================================
# PART A1 — GOOGLE DRIVE MOUNT
# ==============================================================================

print("=" * 100)
print("PART A1 — GOOGLE DRIVE MOUNT")
print("=" * 100)

from google.colab import drive

drive.mount(
    "/content/drive"
)

print()
print("Google Drive mounted successfully.")
print("Mount Point : /content/drive")

====================================================================================================
PART A1 — GOOGLE DRIVE MOUNT
====================================================================================================
Mounted at /content/drive

Google Drive mounted successfully.
Mount Point : /content/drive

In [2]:
# ==============================================================================
# PART A2 — ENVIRONMENT SETUP
# ==============================================================================

print("=" * 100)
print("PART A2 — ENVIRONMENT SETUP")
print("=" * 100)

import os
import sys
import random
import warnings
import platform

import numpy as np
import pandas as pd

import matplotlib.pyplot as plt

import torch
import torch.nn as nn
import torch.optim as optim

from torch.utils.data import (
    DataLoader,
    TensorDataset
)

warnings.filterwarnings(
    "ignore"
)

print()
print("Python Version :", sys.version)
print("Platform       :", platform.platform())
print("PyTorch        :", torch.__version__)
print("NumPy          :", np.__version__)
print("Pandas         :", pd.__version__)

DEVICE = torch.device(
    "cuda"
    if torch.cuda.is_available()
    else "cpu"
)

print()
print("Computation Device :", DEVICE)

if torch.cuda.is_available():

    print(
        "GPU Device         :",
        torch.cuda.get_device_name(0)
    )

    print(
        "CUDA Version       :",
        torch.version.cuda
    )

else:

    print(
        "GPU Device         : "
        "Not Available"
    )

print()
print("PART A2 — Environment setup completed.")

====================================================================================================
PART A2 — ENVIRONMENT SETUP
====================================================================================================

Python Version : 3.12.13 (main, Mar  4 2026, 09:23:07) [GCC 11.4.0]
Platform       : Linux-6.6.122+-x86_64-with-glibc2.35
PyTorch        : 2.11.0+cpu
NumPy          : 2.0.2
Pandas         : 2.2.2

Computation Device : cpu
GPU Device         : Not Available

PART A2 — Environment setup completed.

In [3]:
# ==============================================================================
# PART A3 — REPRODUCIBILITY CONFIGURATION
# ==============================================================================

print("=" * 100)
print("PART A3 — REPRODUCIBILITY CONFIGURATION")
print("=" * 100)

SEED = 42

random.seed(
    SEED
)

np.random.seed(
    SEED
)

torch.manual_seed(
    SEED
)

if torch.cuda.is_available():

    torch.cuda.manual_seed(
        SEED
    )

    torch.cuda.manual_seed_all(
        SEED
    )

torch.backends.cudnn.deterministic = True
torch.backends.cudnn.benchmark = False

os.environ["PYTHONHASHSEED"] = str(
    SEED
)

print()
print("Random Seed :", SEED)
print(
    "Python Random      : Configured"
)
print(
    "NumPy Random       : Configured"
)
print(
    "PyTorch Random     : Configured"
)
print(
    "CUDA Random        : Configured"
    if torch.cuda.is_available()
    else "CUDA Random        : Not Applicable"
)
print(
    "CuDNN Determinism  : Enabled"
)
print(
    "CuDNN Benchmark    : Disabled"
)

print()
print("PART A3 — Reproducibility configuration completed.")

====================================================================================================
PART A3 — REPRODUCIBILITY CONFIGURATION
====================================================================================================

Random Seed : 42
Python Random      : Configured
NumPy Random       : Configured
PyTorch Random     : Configured
CUDA Random        : Not Applicable
CuDNN Determinism  : Enabled
CuDNN Benchmark    : Disabled

PART A3 — Reproducibility configuration completed.

In [4]:
# ==============================================================================
# PART B1 — PROJECT CONFIGURATION
# ==============================================================================

print("=" * 100)
print("PART B1 — PROJECT CONFIGURATION")
print("=" * 100)

PROJECT_ROOT = "/content/drive/MyDrive/SPP_GAN_Project"

CONFIG_PATH = os.path.join(
    PROJECT_ROOT,
    "config.yaml"
)

if not os.path.exists(CONFIG_PATH):
    raise FileNotFoundError(
        f"Project configuration file not found:\n{CONFIG_PATH}"
    )

print()
print("Project Root :", PROJECT_ROOT)
print("Config Path  :", CONFIG_PATH)

print()
print("Project configuration file located successfully.")

====================================================================================================
PART B1 — PROJECT CONFIGURATION
====================================================================================================

Project Root : /content/drive/MyDrive/SPP_GAN_Project
Config Path  : /content/drive/MyDrive/SPP_GAN_Project/config.yaml

Project configuration file located successfully.

In [5]:
# ==============================================================================
# PART B2 — LOAD PROJECT CONFIGURATION
# ==============================================================================

print("=" * 100)
print("PART B2 — LOAD PROJECT CONFIGURATION")
print("=" * 100)

import yaml

with open(
    CONFIG_PATH,
    "r"
) as file:

    PROJECT_CONFIG = yaml.safe_load(
        file
    )

if PROJECT_CONFIG is None:
    raise ValueError(
        "Project configuration is empty."
    )

print()
print("Project configuration loaded successfully.")

print()
print("Configuration Sections:")

for section in PROJECT_CONFIG:

    print(
        f" - {section}"
    )

print()
print("PART B2 — Project configuration loading completed.")

====================================================================================================
PART B2 — LOAD PROJECT CONFIGURATION
====================================================================================================

Project configuration loaded successfully.

Configuration Sections:
 - batch_size
 - beta1
 - beta2
 - delta
 - device
 - epochs
 - gradient_clip
 - latent_dimension
 - learning_rate
 - noise_multiplier
 - optimizer
 - privacy_budget
 - seed

PART B2 — Project configuration loading completed.

In [6]:
# ==============================================================================
# PART B3 — DATASET CONFIGURATION
# ==============================================================================

print("=" * 100)
print("PART B3 — DATASET CONFIGURATION")
print("=" * 100)

DATASETS = [
    "Adult Income",
    "Bank Marketing",
    "diabetes_130us"
]

EXPECTED_DATASET_FILES = {
    "Adult Income":
        "adult_income_processed.csv",
    "Bank Marketing":
        "bank_marketing_processed.csv",
    "diabetes_130us":
        "diabetes_130us_processed.csv"
}

TARGET_COLUMNS = {
    "Adult Income":
        "income",
    "Bank Marketing":
        "y",
    "diabetes_130us":
        "readmitted"
}

print()
print("Datasets:")

for dataset in DATASETS:

    print(
        f" - {dataset}"
    )

print()
print("Dataset Files:")

for dataset, filename in (
    EXPECTED_DATASET_FILES.items()
):

    print(
        f"{dataset:20s} : {filename}"
    )

print()
print("Target Columns:")

for dataset, target in (
    TARGET_COLUMNS.items()
):

    print(
        f"{dataset:20s} : {target}"
    )

print()
print("PART B3 — Dataset configuration completed.")

====================================================================================================
PART B3 — DATASET CONFIGURATION
====================================================================================================

Datasets:
 - Adult Income
 - Bank Marketing
 - diabetes_130us

Dataset Files:
Adult Income         : adult_income_processed.csv
Bank Marketing       : bank_marketing_processed.csv
diabetes_130us       : diabetes_130us_processed.csv

Target Columns:
Adult Income         : income
Bank Marketing       : y
diabetes_130us       : readmitted

PART B3 — Dataset configuration completed.

In [7]:
# ==============================================================================
# PART B4 — CONFIGURATION VALIDATION
# ==============================================================================

print("=" * 100)
print("PART B4 — CONFIGURATION VALIDATION")
print("=" * 100)

if len(DATASETS) != 3:
    raise ValueError(
        "Unexpected number of research datasets."
    )

for dataset in DATASETS:

    if dataset not in EXPECTED_DATASET_FILES:
        raise KeyError(
            f"Dataset file configuration missing for {dataset}."
        )

    if dataset not in TARGET_COLUMNS:
        raise KeyError(
            f"Target column configuration missing for {dataset}."
        )

print()
print("Number of Datasets :", len(DATASETS))
print(
    "Dataset Configuration : PASS"
)
print(
    "Target Configuration  : PASS"
)
print(
    "Configuration File    : PASS"
)

print()
print("PART B4 — Configuration validation completed.")

====================================================================================================
PART B4 — CONFIGURATION VALIDATION
====================================================================================================

Number of Datasets : 3
Dataset Configuration : PASS
Target Configuration  : PASS
Configuration File    : PASS

PART B4 — Configuration validation completed.

In [8]:
# ==============================================================================
# PART C1 — DATASET LOADING
# ==============================================================================

print("=" * 100)
print("PART C1 — DATASET LOADING")
print("=" * 100)

PROCESSED_DATA_DIR = os.path.join(
    PROJECT_ROOT,
    "datasets",
    "processed"
)

REAL_DATASETS = {}

for dataset in DATASETS:

    filename = EXPECTED_DATASET_FILES[
        dataset
    ]

    file_path = os.path.join(
        PROCESSED_DATA_DIR,
        filename
    )

    if not os.path.exists(file_path):

        raise FileNotFoundError(
            f"Processed dataset not found for "
            f"{dataset}:\n{file_path}"
        )

    real_data = pd.read_csv(
        file_path
    )

    if real_data.empty:

        raise ValueError(
            f"Dataset is empty: {dataset}"
        )

    REAL_DATASETS[dataset] = real_data

    print(
        f"{dataset:20s} : "
        f"{real_data.shape[0]:>8,} rows × "
        f"{real_data.shape[1]:>3} columns"
    )

print()
print(
    "Processed Data Directory :"
)
print(
    PROCESSED_DATA_DIR
)

print()
print(
    "Datasets Loaded:"
)

for dataset in DATASETS:

    print(
        f" - {dataset}"
    )

print()
print(
    "PART C1 — Dataset loading completed."
)

====================================================================================================
PART C1 — DATASET LOADING
====================================================================================================
Adult Income         :   32,515 rows ×  15 columns
Bank Marketing       :   45,211 rows ×  17 columns
diabetes_130us       :  101,766 rows ×  48 columns

Processed Data Directory :
/content/drive/MyDrive/SPP_GAN_Project/datasets/processed

Datasets Loaded:
 - Adult Income
 - Bank Marketing
 - diabetes_130us

PART C1 — Dataset loading completed.

In [9]:
# ==============================================================================
# PART C2 — DATASET LOADING VALIDATION
# ==============================================================================

print("=" * 100)
print("PART C2 — DATASET LOADING VALIDATION")
print("=" * 100)

DATASET_LOADING_STATUS = {}

for dataset in DATASETS:

    status = (
        dataset in REAL_DATASETS
        and isinstance(
            REAL_DATASETS[dataset],
            pd.DataFrame
        )
        and not REAL_DATASETS[dataset].empty
    )

    DATASET_LOADING_STATUS[
        dataset
    ] = status

    print(
        f"{dataset:20s} : "
        f"{'PASS' if status else 'FAIL'}"
    )

ALL_DATASETS_LOADED = all(
    DATASET_LOADING_STATUS.values()
)

print()
print(
    f"Overall Dataset Loading Status : "
    f"{'PASS' if ALL_DATASETS_LOADED else 'FAIL'}"
)

if not ALL_DATASETS_LOADED:

    raise RuntimeError(
        "One or more research datasets "
        "failed dataset loading validation."
    )

print()
print(
    "PART C2 — Dataset loading validation completed."
)

====================================================================================================
PART C2 — DATASET LOADING VALIDATION
====================================================================================================
Adult Income         : PASS
Bank Marketing       : PASS
diabetes_130us       : PASS

Overall Dataset Loading Status : PASS

PART C2 — Dataset loading validation completed.

In [10]:
# ==============================================================================
# PART C3 — DATASET STRUCTURE SUMMARY
# ==============================================================================

print("=" * 100)
print("PART C3 — DATASET STRUCTURE SUMMARY")
print("=" * 100)

DATASET_STRUCTURE_SUMMARY = []

for dataset in DATASETS:

    data = REAL_DATASETS[
        dataset
    ]

    target_column = TARGET_COLUMNS[
        dataset
    ]

    DATASET_STRUCTURE_SUMMARY.append({

        "Dataset":
            dataset,

        "Rows":
            len(data),

        "Columns":
            len(data.columns),

        "Target":
            target_column,

        "Target Exists":
            target_column in data.columns,

        "Missing Values":
            int(
                data.isna()
                .sum()
                .sum()
            ),

        "Duplicate Rows":
            int(
                data.duplicated()
                .sum()
            )

    })

DATASET_STRUCTURE_SUMMARY_DF = pd.DataFrame(
    DATASET_STRUCTURE_SUMMARY
)

print()

print(
    DATASET_STRUCTURE_SUMMARY_DF.to_string(
        index=False
    )
)

print()
print(
    "PART C3 — Dataset structure summary completed."
)

====================================================================================================
PART C3 — DATASET STRUCTURE SUMMARY
====================================================================================================

       Dataset   Rows  Columns     Target  Target Exists  Missing Values  Duplicate Rows
  Adult Income  32515       15     income           True               0               0
Bank Marketing  45211       17          y           True               0               0
diabetes_130us 101766       48 readmitted           True               0               0

PART C3 — Dataset structure summary completed.

In [11]:
# ==============================================================================
# PART C4 — DATASET COLUMN VALIDATION
# ==============================================================================

print("=" * 100)
print("PART C4 — DATASET COLUMN VALIDATION")
print("=" * 100)

DATASET_COLUMN_VALIDATION = {}

for dataset in DATASETS:

    data = REAL_DATASETS[
        dataset
    ]

    target_column = TARGET_COLUMNS[
        dataset
    ]

    columns = data.columns.tolist()

    duplicate_columns = (
        len(columns)
        != len(set(columns))
    )

    target_exists = (
        target_column in columns
    )

    DATASET_COLUMN_VALIDATION[
        dataset
    ] = {

        "Column Names Unique":
            not duplicate_columns,

        "Target Exists":
            target_exists,

        "Column Count":
            len(columns)

    }

    print()
    print(
        f"Dataset : {dataset}"
    )

    print(
        f"Column Names Unique : "
        f"{'PASS' if not duplicate_columns else 'FAIL'}"
    )

    print(
        f"Target Exists       : "
        f"{'PASS' if target_exists else 'FAIL'}"
    )

    print(
        f"Column Count        : "
        f"{len(columns)}"
    )

    if duplicate_columns:

        raise ValueError(
            f"Duplicate column names detected "
            f"in {dataset}."
        )

    if not target_exists:

        raise KeyError(
            f"Target column '{target_column}' "
            f"not found in {dataset}."
        )

print()
print(
    "PART C4 — Dataset column validation completed."
)

====================================================================================================
PART C4 — DATASET COLUMN VALIDATION
====================================================================================================

Dataset : Adult Income
Column Names Unique : PASS
Target Exists       : PASS
Column Count        : 15

Dataset : Bank Marketing
Column Names Unique : PASS
Target Exists       : PASS
Column Count        : 17

Dataset : diabetes_130us
Column Names Unique : PASS
Target Exists       : PASS
Column Count        : 48

PART C4 — Dataset column validation completed.

In [12]:
# ==============================================================================
# PART C5 — TRAIN / VALIDATION / TEST SPLITTING
# ==============================================================================

print("=" * 100)
print("PART C5 — TRAIN / VALIDATION / TEST SPLITTING")
print("=" * 100)

from sklearn.model_selection import train_test_split

TRAIN_DATASETS = {}
VALIDATION_DATASETS = {}
TEST_DATASETS = {}

TRAIN_ROW_IDS = {}
VALIDATION_ROW_IDS = {}
TEST_ROW_IDS = {}

SPLIT_SEED = 42
TRAIN_SIZE = 0.70
VALIDATION_SIZE = 0.15
TEST_SIZE = 0.15

for dataset in DATASETS:

    df = REAL_DATASETS[dataset].copy()

    target_column = TARGET_COLUMNS[dataset]

    if target_column not in df.columns:
        raise KeyError(
            f"Target column '{target_column}' "
            f"not found in {dataset}."
        )

    df["_ORIGINAL_ROW_ID_"] = np.arange(
        len(df)
    )

    train_df, temp_df = train_test_split(
        df,
        test_size=(
            VALIDATION_SIZE
            + TEST_SIZE
        ),
        random_state=SPLIT_SEED,
        stratify=df[target_column]
    )

    relative_test_size = (
        TEST_SIZE
        /
        (
            VALIDATION_SIZE
            + TEST_SIZE
        )
    )

    validation_df, test_df = train_test_split(
        temp_df,
        test_size=relative_test_size,
        random_state=SPLIT_SEED,
        stratify=temp_df[target_column]
    )

    TRAIN_ROW_IDS[dataset] = set(
        train_df["_ORIGINAL_ROW_ID_"]
    )

    VALIDATION_ROW_IDS[dataset] = set(
        validation_df["_ORIGINAL_ROW_ID_"]
    )

    TEST_ROW_IDS[dataset] = set(
        test_df["_ORIGINAL_ROW_ID_"]
    )

    train_df = train_df.drop(
        columns=["_ORIGINAL_ROW_ID_"]
    )

    validation_df = validation_df.drop(
        columns=["_ORIGINAL_ROW_ID_"]
    )

    test_df = test_df.drop(
        columns=["_ORIGINAL_ROW_ID_"]
    )

    TRAIN_DATASETS[dataset] = (
        train_df.reset_index(
            drop=True
        )
    )

    VALIDATION_DATASETS[dataset] = (
        validation_df.reset_index(
            drop=True
        )
    )

    TEST_DATASETS[dataset] = (
        test_df.reset_index(
            drop=True
        )
    )

    print()
    print(dataset)

    print(
        f"Training   : "
        f"{len(TRAIN_DATASETS[dataset]):,}"
    )

    print(
        f"Validation : "
        f"{len(VALIDATION_DATASETS[dataset]):,}"
    )

    print(
        f"Testing    : "
        f"{len(TEST_DATASETS[dataset]):,}"
    )

print()
print(
    "PART C5 — Train / Validation / Test splitting completed."
)

====================================================================================================
PART C5 — TRAIN / VALIDATION / TEST SPLITTING
====================================================================================================

Adult Income
Training   : 22,760
Validation : 4,877
Testing    : 4,878

Bank Marketing
Training   : 31,647
Validation : 6,782
Testing    : 6,782

diabetes_130us
Training   : 71,236
Validation : 15,265
Testing    : 15,265

PART C5 — Train / Validation / Test splitting completed.

In [13]:
# ==============================================================================
# PART C6 — SPLIT INTEGRITY VERIFICATION
# ==============================================================================

print("=" * 100)
print("PART C6 — SPLIT INTEGRITY VERIFICATION")
print("=" * 100)

SPLIT_INTEGRITY = {}

for dataset in DATASETS:

    train_ids = TRAIN_ROW_IDS[dataset]
    validation_ids = VALIDATION_ROW_IDS[dataset]
    test_ids = TEST_ROW_IDS[dataset]

    train_validation_overlap = (
        train_ids.intersection(
            validation_ids
        )
    )

    train_test_overlap = (
        train_ids.intersection(
            test_ids
        )
    )

    validation_test_overlap = (
        validation_ids.intersection(
            test_ids
        )
    )

    total_original_rows = len(
        REAL_DATASETS[dataset]
    )

    total_split_rows = (
        len(train_ids)
        + len(validation_ids)
        + len(test_ids)
    )

    checks = {

        "Train/Validation Overlap":
            len(
                train_validation_overlap
            ) == 0,

        "Train/Test Overlap":
            len(
                train_test_overlap
            ) == 0,

        "Validation/Test Overlap":
            len(
                validation_test_overlap
            ) == 0,

        "All Rows Assigned":
            total_split_rows
            == total_original_rows,

        "Split Size Valid":
            (
                len(
                    TRAIN_DATASETS[dataset]
                ) > 0
                and
                len(
                    VALIDATION_DATASETS[dataset]
                ) > 0
                and
                len(
                    TEST_DATASETS[dataset]
                ) > 0
            )
    }

    SPLIT_INTEGRITY[
        dataset
    ] = checks

    print()
    print(
        f"Dataset : {dataset}"
    )

    for check, status in checks.items():

        print(
            f"{check:30s} : "
            f"{'PASS' if status else 'FAIL'}"
        )

    if not all(
        checks.values()
    ):

        raise RuntimeError(
            f"Split integrity verification "
            f"failed for {dataset}."
        )

print()
print(
    "All datasets passed split integrity verification."
)

print()
print(
    "PART C6 — Split integrity verification completed."
)

====================================================================================================
PART C6 — SPLIT INTEGRITY VERIFICATION
====================================================================================================

Dataset : Adult Income
Train/Validation Overlap       : PASS
Train/Test Overlap             : PASS
Validation/Test Overlap        : PASS
All Rows Assigned              : PASS
Split Size Valid               : PASS

Dataset : Bank Marketing
Train/Validation Overlap       : PASS
Train/Test Overlap             : PASS
Validation/Test Overlap        : PASS
All Rows Assigned              : PASS
Split Size Valid               : PASS

Dataset : diabetes_130us
Train/Validation Overlap       : PASS
Train/Test Overlap             : PASS
Validation/Test Overlap        : PASS
All Rows Assigned              : PASS
Split Size Valid               : PASS

All datasets passed split integrity verification.

PART C6 — Split integrity verification completed.

In [14]:
# ==============================================================================
# PART C7 — SPLIT STRUCTURE VERIFICATION
# ==============================================================================

print("=" * 100)
print("PART C7 — SPLIT STRUCTURE VERIFICATION")
print("=" * 100)

SPLIT_STRUCTURE_VERIFICATION = {}

for dataset in DATASETS:

    train_data = TRAIN_DATASETS[dataset]
    validation_data = VALIDATION_DATASETS[dataset]
    test_data = TEST_DATASETS[dataset]

    expected_columns = (
        REAL_DATASETS[dataset].columns.tolist()
    )

    checks = {

        "Train Columns":
            train_data.columns.tolist()
            == expected_columns,

        "Validation Columns":
            validation_data.columns.tolist()
            == expected_columns,

        "Test Columns":
            test_data.columns.tolist()
            == expected_columns,

        "Train Target":
            TARGET_COLUMNS[dataset]
            in train_data.columns,

        "Validation Target":
            TARGET_COLUMNS[dataset]
            in validation_data.columns,

        "Test Target":
            TARGET_COLUMNS[dataset]
            in test_data.columns,

        "Train Missing Values":
            not train_data.isna().any().any(),

        "Validation Missing Values":
            not validation_data.isna().any().any(),

        "Test Missing Values":
            not test_data.isna().any().any()
    }

    SPLIT_STRUCTURE_VERIFICATION[
        dataset
    ] = checks

    print()
    print(
        f"Dataset : {dataset}"
    )

    for check, status in checks.items():

        print(
            f"{check:30s} : "
            f"{'PASS' if status else 'FAIL'}"
        )

    if not all(
        checks.values()
    ):

        raise ValueError(
            f"Split structure validation "
            f"failed for {dataset}."
        )

print()
print(
    "All Train / Validation / Test datasets "
    "passed structural verification."
)

print()
print(
    "PART C7 — Split structure verification completed."
)

====================================================================================================
PART C7 — SPLIT STRUCTURE VERIFICATION
====================================================================================================

Dataset : Adult Income
Train Columns                  : PASS
Validation Columns             : PASS
Test Columns                   : PASS
Train Target                   : PASS
Validation Target              : PASS
Test Target                    : PASS
Train Missing Values           : PASS
Validation Missing Values      : PASS
Test Missing Values            : PASS

Dataset : Bank Marketing
Train Columns                  : PASS
Validation Columns             : PASS
Test Columns                   : PASS
Train Target                   : PASS
Validation Target              : PASS
Test Target                    : PASS
Train Missing Values           : PASS
Validation Missing Values      : PASS
Test Missing Values            : PASS

Dataset : diabetes_130us
Train Columns                  : PASS
Validation Columns             : PASS
Test Columns                   : PASS
Train Target                   : PASS
Validation Target              : PASS
Test Target                    : PASS
Train Missing Values           : PASS
Validation Missing Values      : PASS
Test Missing Values            : PASS

All Train / Validation / Test datasets passed structural verification.

PART C7 — Split structure verification completed.

In [15]:
# ==============================================================================
# PART C8 — DATASET SPLIT SUMMARY
# ==============================================================================

print("=" * 100)
print("PART C8 — DATASET SPLIT SUMMARY")
print("=" * 100)

SPLIT_SUMMARY = []

for dataset in DATASETS:

    original_rows = len(
        REAL_DATASETS[dataset]
    )

    train_rows = len(
        TRAIN_DATASETS[dataset]
    )

    validation_rows = len(
        VALIDATION_DATASETS[dataset]
    )

    test_rows = len(
        TEST_DATASETS[dataset]
    )

    total_split_rows = (
        train_rows
        + validation_rows
        + test_rows
    )

    SPLIT_SUMMARY.append({

        "Dataset":
            dataset,

        "Original Rows":
            original_rows,

        "Training Rows":
            train_rows,

        "Validation Rows":
            validation_rows,

        "Test Rows":
            test_rows,

        "Total Split Rows":
            total_split_rows,

        "Training %":
            round(
                train_rows
                / original_rows
                * 100,
                2
            ),

        "Validation %":
            round(
                validation_rows
                / original_rows
                * 100,
                2
            ),

        "Test %":
            round(
                test_rows
                / original_rows
                * 100,
                2
            ),

        "Split Verification":
            total_split_rows
            == original_rows
    })

SPLIT_SUMMARY_DF = pd.DataFrame(
    SPLIT_SUMMARY
)

print()

display(
    SPLIT_SUMMARY_DF
)

print()

print(
    "PART C8 — Dataset split summary completed."
)

====================================================================================================
PART C8 — DATASET SPLIT SUMMARY
====================================================================================================

,Dataset,Original Rows,Training Rows,Validation Rows,Test Rows,Total Split Rows,Training %,Validation %,Test %,Split Verification
0,Adult Income,32515,22760,4877,4878,32515,70.0,15.0,15.0,True
1,Bank Marketing,45211,31647,6782,6782,45211,70.0,15.0,15.0,True
2,diabetes_130us,101766,71236,15265,15265,101766,70.0,15.0,15.0,True

PART C8 — Dataset split summary completed.

In [16]:
# ==============================================================================
# PART D1 — DATASET VERIFICATION SUMMARY
# ==============================================================================

print("=" * 100)
print("PART D1 — DATASET VERIFICATION SUMMARY")
print("=" * 100)

DATASET_VERIFICATION = {}

for dataset in DATASETS:

    data = REAL_DATASETS[dataset]
    target_column = TARGET_COLUMNS[dataset]

    DATASET_VERIFICATION[dataset] = {

        "Dataset Loaded":
            isinstance(
                data,
                pd.DataFrame
            ),

        "Rows > 0":
            len(data) > 0,

        "Columns > 0":
            len(data.columns) > 0,

        "Target Exists":
            target_column in data.columns,

        "Missing Values":
            int(
                data.isna()
                .sum()
                .sum()
            ),

        "Duplicate Rows":
            int(
                data.duplicated()
                .sum()
            ),

        "Unique Columns":
            len(data.columns)
            == len(
                set(data.columns)
            ),

        "Data Types Available":
            len(data.dtypes) == len(data.columns)
    }

for dataset in DATASETS:

    print()
    print(
        f"Dataset : {dataset}"
    )

    for check, result in DATASET_VERIFICATION[
        dataset
    ].items():

        if check in [
            "Missing Values",
            "Duplicate Rows"
        ]:

            print(
                f"{check:25s} : {result}"
            )

        else:

            print(
                f"{check:25s} : "
                f"{'PASS' if result else 'FAIL'}"
            )

print()
print(
    "PART D1 — Dataset verification summary completed."
)

====================================================================================================
PART D1 — DATASET VERIFICATION SUMMARY
====================================================================================================

Dataset : Adult Income
Dataset Loaded            : PASS
Rows > 0                  : PASS
Columns > 0               : PASS
Target Exists             : PASS
Missing Values            : 0
Duplicate Rows            : 0
Unique Columns            : PASS
Data Types Available      : PASS

Dataset : Bank Marketing
Dataset Loaded            : PASS
Rows > 0                  : PASS
Columns > 0               : PASS
Target Exists             : PASS
Missing Values            : 0
Duplicate Rows            : 0
Unique Columns            : PASS
Data Types Available      : PASS

Dataset : diabetes_130us
Dataset Loaded            : PASS
Rows > 0                  : PASS
Columns > 0               : PASS
Target Exists             : PASS
Missing Values            : 0
Duplicate Rows            : 0
Unique Columns            : PASS
Data Types Available      : PASS

PART D1 — Dataset verification summary completed.

In [17]:
# ==============================================================================
# PART D2 — DATASET SHAPE AND COLUMN VERIFICATION
# ==============================================================================

print("=" * 100)
print("PART D2 — DATASET SHAPE AND COLUMN VERIFICATION")
print("=" * 100)

DATASET_SHAPE_VERIFICATION = {}

for dataset in DATASETS:

    data = REAL_DATASETS[dataset]

    expected_columns = (
        EXPECTED_DATASET_FILES
        and data.columns.tolist()
    )

    actual_columns = data.columns.tolist()

    duplicate_columns = (
        len(actual_columns)
        != len(
            set(actual_columns)
        )
    )

    DATASET_SHAPE_VERIFICATION[
        dataset
    ] = {

        "Rows":
            len(data),

        "Columns":
            len(actual_columns),

        "Column Names Unique":
            not duplicate_columns,

        "Column Order Valid":
            actual_columns
            == expected_columns
    }

    print()
    print(
        f"Dataset : {dataset}"
    )

    print(
        f"Rows                 : "
        f"{len(data):,}"
    )

    print(
        f"Columns              : "
        f"{len(actual_columns)}"
    )

    print(
        f"Column Names Unique  : "
        f"{'PASS' if not duplicate_columns else 'FAIL'}"
    )

print()
print(
    "PART D2 — Dataset shape and column verification completed."
)

====================================================================================================
PART D2 — DATASET SHAPE AND COLUMN VERIFICATION
====================================================================================================

Dataset : Adult Income
Rows                 : 32,515
Columns              : 15
Column Names Unique  : PASS

Dataset : Bank Marketing
Rows                 : 45,211
Columns              : 17
Column Names Unique  : PASS

Dataset : diabetes_130us
Rows                 : 101,766
Columns              : 48
Column Names Unique  : PASS

PART D2 — Dataset shape and column verification completed.

In [18]:
# ==============================================================================
# PART D3 — MISSING VALUE VERIFICATION
# ==============================================================================

print("=" * 100)
print("PART D3 — MISSING VALUE VERIFICATION")
print("=" * 100)

DATASET_MISSING_VALUE_SUMMARY = {}

for dataset in DATASETS:

    data = REAL_DATASETS[dataset]

    missing_by_column = (
        data.isna()
        .sum()
    )

    total_missing = int(
        missing_by_column.sum()
    )

    columns_with_missing = (
        missing_by_column[
            missing_by_column > 0
        ]
        .index
        .tolist()
    )

    DATASET_MISSING_VALUE_SUMMARY[
        dataset
    ] = {

        "Total Missing Values":
            total_missing,

        "Columns With Missing Values":
            len(
                columns_with_missing
            ),

        "Missing Value Status":
            total_missing == 0

    }

    print()
    print(
        f"Dataset : {dataset}"
    )

    print(
        f"Total Missing Values : "
        f"{total_missing:,}"
    )

    print(
        f"Columns With Missing : "
        f"{len(columns_with_missing)}"
    )

    print(
        f"Missing Value Status : "
        f"{'PASS' if total_missing == 0 else 'INFO'}"
    )

print()
print(
    "PART D3 — Missing value verification completed."
)

====================================================================================================
PART D3 — MISSING VALUE VERIFICATION
====================================================================================================

Dataset : Adult Income
Total Missing Values : 0
Columns With Missing : 0
Missing Value Status : PASS

Dataset : Bank Marketing
Total Missing Values : 0
Columns With Missing : 0
Missing Value Status : PASS

Dataset : diabetes_130us
Total Missing Values : 0
Columns With Missing : 0
Missing Value Status : PASS

PART D3 — Missing value verification completed.

In [19]:
# ==============================================================================
# PART D4 — TARGET VARIABLE VERIFICATION
# ==============================================================================

print("=" * 100)
print("PART D4 — TARGET VARIABLE VERIFICATION")
print("=" * 100)

TARGET_VERIFICATION = {}

for dataset in DATASETS:

    data = REAL_DATASETS[dataset]
    target_column = TARGET_COLUMNS[dataset]

    target_exists = (
        target_column in data.columns
    )

    if target_exists:

        target_series = data[
            target_column
        ]

        target_missing = int(
            target_series.isna()
            .sum()
        )

        target_unique = int(
            target_series.nunique(
                dropna=True
            )
        )

        target_counts = (
            target_series
            .value_counts(
                dropna=False
            )
            .to_dict()
        )

    else:

        target_missing = None
        target_unique = 0
        target_counts = {}

    TARGET_VERIFICATION[
        dataset
    ] = {

        "Target Column":
            target_column,

        "Target Exists":
            target_exists,

        "Missing Target Values":
            target_missing,

        "Unique Target Values":
            target_unique,

        "Target Distribution":
            target_counts
    }

    print()
    print(
        f"Dataset : {dataset}"
    )

    print(
        f"Target Column       : "
        f"{target_column}"
    )

    print(
        f"Target Exists       : "
        f"{'PASS' if target_exists else 'FAIL'}"
    )

    print(
        f"Missing Target      : "
        f"{target_missing}"
    )

    print(
        f"Unique Target Values: "
        f"{target_unique}"
    )

    print(
        f"Target Distribution : "
        f"{target_counts}"
    )

    if not target_exists:

        raise KeyError(
            f"Target column '{target_column}' "
            f"not found in {dataset}."
        )

print()
print(
    "PART D4 — Target variable verification completed."
)

====================================================================================================
PART D4 — TARGET VARIABLE VERIFICATION
====================================================================================================

Dataset : Adult Income
Target Column       : income
Target Exists       : PASS
Missing Target      : 0
Unique Target Values: 2
Target Distribution : {0: 24678, 1: 7837}

Dataset : Bank Marketing
Target Column       : y
Target Exists       : PASS
Missing Target      : 0
Unique Target Values: 2
Target Distribution : {0: 39922, 1: 5289}

Dataset : diabetes_130us
Target Column       : readmitted
Target Exists       : PASS
Missing Target      : 0
Unique Target Values: 3
Target Distribution : {2: 54864, 1: 35545, 0: 11357}

PART D4 — Target variable verification completed.

In [20]:
# ==============================================================================
# PART D5 — DATA TYPE VERIFICATION
# ==============================================================================

print("=" * 100)
print("PART D5 — DATA TYPE VERIFICATION")
print("=" * 100)

DATA_TYPE_VERIFICATION = {}

for dataset in DATASETS:

    data = REAL_DATASETS[dataset]

    numeric_columns = (
        data.select_dtypes(
            include=np.number
        )
        .columns
        .tolist()
    )

    non_numeric_columns = (
        data.select_dtypes(
            exclude=np.number
        )
        .columns
        .tolist()
    )

    DATA_TYPE_VERIFICATION[
        dataset
    ] = {

        "Total Columns":
            len(data.columns),

        "Numeric Columns":
            len(numeric_columns),

        "Non-Numeric Columns":
            len(non_numeric_columns),

        "All Columns Typed":
            all(
                dtype is not None
                for dtype in data.dtypes
            )
    }

    print()
    print(
        f"Dataset : {dataset}"
    )

    print(
        f"Total Columns       : "
        f"{len(data.columns)}"
    )

    print(
        f"Numeric Columns     : "
        f"{len(numeric_columns)}"
    )

    print(
        f"Non-Numeric Columns : "
        f"{len(non_numeric_columns)}"
    )

    print(
        f"Data Types          : "
        f"{'PASS' if DATA_TYPE_VERIFICATION[dataset]['All Columns Typed'] else 'FAIL'}"
    )

print()
print(
    "PART D5 — Data type verification completed."
)

====================================================================================================
PART D5 — DATA TYPE VERIFICATION
====================================================================================================

Dataset : Adult Income
Total Columns       : 15
Numeric Columns     : 15
Non-Numeric Columns : 0
Data Types          : PASS

Dataset : Bank Marketing
Total Columns       : 17
Numeric Columns     : 17
Non-Numeric Columns : 0
Data Types          : PASS

Dataset : diabetes_130us
Total Columns       : 48
Numeric Columns     : 48
Non-Numeric Columns : 0
Data Types          : PASS

PART D5 — Data type verification completed.

In [21]:
# ==============================================================================
# PART D6 — DUPLICATE RECORD VERIFICATION
# ==============================================================================

print("=" * 100)
print("PART D6 — DUPLICATE RECORD VERIFICATION")
print("=" * 100)

DUPLICATE_VERIFICATION = {}

for dataset in DATASETS:

    data = REAL_DATASETS[dataset]

    duplicate_count = int(
        data.duplicated()
        .sum()
    )

    duplicate_percentage = (
        duplicate_count
        / len(data)
        * 100
        if len(data) > 0
        else 0.0
    )

    DUPLICATE_VERIFICATION[
        dataset
    ] = {

        "Duplicate Rows":
            duplicate_count,

        "Duplicate Percentage":
            duplicate_percentage,

        "Verification":
            duplicate_count == 0
    }

    print()
    print(
        f"Dataset : {dataset}"
    )

    print(
        f"Duplicate Rows       : "
        f"{duplicate_count:,}"
    )

    print(
        f"Duplicate Percentage : "
        f"{duplicate_percentage:.4f}%"
    )

    print(
        f"Verification         : "
        f"{'PASS' if duplicate_count == 0 else 'INFO'}"
    )

print()
print(
    "PART D6 — Duplicate record verification completed."
)

====================================================================================================
PART D6 — DUPLICATE RECORD VERIFICATION
====================================================================================================

Dataset : Adult Income
Duplicate Rows       : 0
Duplicate Percentage : 0.0000%
Verification         : PASS

Dataset : Bank Marketing
Duplicate Rows       : 0
Duplicate Percentage : 0.0000%
Verification         : PASS

Dataset : diabetes_130us
Duplicate Rows       : 0
Duplicate Percentage : 0.0000%
Verification         : PASS

PART D6 — Duplicate record verification completed.

In [22]:
# ==============================================================================
# PART D7 — FINAL DATASET VERIFICATION
# ==============================================================================

print("=" * 100)
print("PART D7 — FINAL DATASET VERIFICATION")
print("=" * 100)

FINAL_DATASET_VERIFICATION = {}

for dataset in DATASETS:

    data = REAL_DATASETS[dataset]
    target_column = TARGET_COLUMNS[dataset]

    checks = {

        "Dataset Loaded":
            isinstance(
                data,
                pd.DataFrame
            ),

        "Dataset Non-Empty":
            not data.empty,

        "Columns Available":
            len(data.columns) > 0,

        "Unique Column Names":
            len(data.columns)
            == len(
                set(data.columns)
            ),

        "Target Exists":
            target_column in data.columns,

        "Target Non-Empty":
            (
                target_column in data.columns
                and
                data[target_column]
                .notna()
                .any()
            ),

        "Data Types Available":
            len(data.dtypes)
            == len(data.columns)
    }

    FINAL_DATASET_VERIFICATION[
        dataset
    ] = checks

    dataset_status = all(
        checks.values()
    )

    print()
    print(
        f"{dataset:20s} : "
        f"{'PASS' if dataset_status else 'FAIL'}"
    )

    for check, status in checks.items():

        print(
            f"  {check:25s} : "
            f"{'PASS' if status else 'FAIL'}"
        )

    if not dataset_status:

        raise RuntimeError(
            f"Dataset verification failed for "
            f"{dataset}."
        )

ALL_DATASETS_VERIFIED = all(
    all(
        checks.values()
    )
    for checks in
    FINAL_DATASET_VERIFICATION.values()
)

print()
print(
    f"Overall Dataset Verification : "
    f"{'PASS' if ALL_DATASETS_VERIFIED else 'FAIL'}"
)

if not ALL_DATASETS_VERIFIED:

    raise RuntimeError(
        "Final dataset verification failed."
    )

print()
print(
    "PART D — Dataset verification completed successfully."
)

====================================================================================================
PART D7 — FINAL DATASET VERIFICATION
====================================================================================================

Adult Income         : PASS
  Dataset Loaded            : PASS
  Dataset Non-Empty         : PASS
  Columns Available         : PASS
  Unique Column Names       : PASS
  Target Exists             : PASS
  Target Non-Empty          : PASS
  Data Types Available      : PASS

Bank Marketing       : PASS
  Dataset Loaded            : PASS
  Dataset Non-Empty         : PASS
  Columns Available         : PASS
  Unique Column Names       : PASS
  Target Exists             : PASS
  Target Non-Empty          : PASS
  Data Types Available      : PASS

diabetes_130us       : PASS
  Dataset Loaded            : PASS
  Dataset Non-Empty         : PASS
  Columns Available         : PASS
  Unique Column Names       : PASS
  Target Exists             : PASS
  Target Non-Empty          : PASS
  Data Types Available      : PASS

Overall Dataset Verification : PASS

PART D — Dataset verification completed successfully.

In [23]:
# ==============================================================================
# PART E1 — FEATURE REPRESENTATION INITIALIZATION
# ==============================================================================

print("=" * 100)
print("PART E1 — FEATURE REPRESENTATION INITIALIZATION")
print("=" * 100)

FEATURE_DATASETS = {}
TARGET_DATASETS = {}

FEATURE_COLUMNS = {}
NUMERIC_COLUMNS = {}
CATEGORICAL_COLUMNS = {}
OTHER_COLUMNS = {}

FEATURE_DIMENSIONS = {}
TARGET_DIMENSIONS = {}

for dataset in DATASETS:

    data = REAL_DATASETS[dataset]
    target_column = TARGET_COLUMNS[dataset]

    if target_column not in data.columns:
        raise KeyError(
            f"Target column '{target_column}' "
            f"not found in {dataset}."
        )

    feature_columns = [
        column
        for column in data.columns
        if column != target_column
    ]

    feature_data = data[
        feature_columns
    ].copy()

    target_data = data[
        target_column
    ].copy()

    numeric_columns = (
        feature_data
        .select_dtypes(
            include=np.number
        )
        .columns
        .tolist()
    )

    categorical_columns = (
        feature_data
        .select_dtypes(
            exclude=np.number
        )
        .columns
        .tolist()
    )

    other_columns = [
        column
        for column in feature_columns
        if column not in numeric_columns
        and column not in categorical_columns
    ]

    FEATURE_DATASETS[dataset] = feature_data
    TARGET_DATASETS[dataset] = target_data

    FEATURE_COLUMNS[dataset] = feature_columns
    NUMERIC_COLUMNS[dataset] = numeric_columns
    CATEGORICAL_COLUMNS[dataset] = categorical_columns
    OTHER_COLUMNS[dataset] = other_columns

    FEATURE_DIMENSIONS[dataset] = len(
        feature_columns
    )

    TARGET_DIMENSIONS[dataset] = 1

    print()
    print(
        f"Dataset : {dataset}"
    )

    print(
        f"Input Features      : "
        f"{len(feature_columns)}"
    )

    print(
        f"Numeric Features    : "
        f"{len(numeric_columns)}"
    )

    print(
        f"Categorical Features: "
        f"{len(categorical_columns)}"
    )

    print(
        f"Other Features      : "
        f"{len(other_columns)}"
    )

    print(
        f"Target              : "
        f"{target_column}"
    )

print()
print(
    "PART E1 — Feature representation initialization completed."
)

====================================================================================================
PART E1 — FEATURE REPRESENTATION INITIALIZATION
====================================================================================================

Dataset : Adult Income
Input Features      : 14
Numeric Features    : 14
Categorical Features: 0
Other Features      : 0
Target              : income

Dataset : Bank Marketing
Input Features      : 16
Numeric Features    : 16
Categorical Features: 0
Other Features      : 0
Target              : y

Dataset : diabetes_130us
Input Features      : 47
Numeric Features    : 47
Categorical Features: 0
Other Features      : 0
Target              : readmitted

PART E1 — Feature representation initialization completed.

In [24]:
# ==============================================================================
# PART E2 — FEATURE COLUMN VERIFICATION
# ==============================================================================

print("=" * 100)
print("PART E2 — FEATURE COLUMN VERIFICATION")
print("=" * 100)

FEATURE_COLUMN_VERIFICATION = {}

for dataset in DATASETS:

    data = REAL_DATASETS[dataset]
    target_column = TARGET_COLUMNS[dataset]

    feature_columns = FEATURE_COLUMNS[
        dataset
    ]

    checks = {

        "Features Available":
            len(feature_columns) > 0,

        "Target Excluded":
            target_column not in feature_columns,

        "Feature Count Valid":
            len(feature_columns)
            == len(
                data.columns
            ) - 1,

        "Feature Names Unique":
            len(feature_columns)
            == len(
                set(feature_columns)
            ),

        "All Features Numeric":
            len(
                CATEGORICAL_COLUMNS[dataset]
            ) == 0
            and
            len(
                OTHER_COLUMNS[dataset]
            ) == 0
    }

    FEATURE_COLUMN_VERIFICATION[
        dataset
    ] = checks

    print()
    print(
        f"Dataset : {dataset}"
    )

    for check, status in checks.items():

        print(
            f"{check:25s} : "
            f"{'PASS' if status else 'FAIL'}"
        )

    if not all(
        checks.values()
    ):

        raise ValueError(
            f"Feature representation validation "
            f"failed for {dataset}."
        )

print()
print(
    "PART E2 — Feature column verification completed."
)

====================================================================================================
PART E2 — FEATURE COLUMN VERIFICATION
====================================================================================================

Dataset : Adult Income
Features Available        : PASS
Target Excluded           : PASS
Feature Count Valid       : PASS
Feature Names Unique      : PASS
All Features Numeric      : PASS

Dataset : Bank Marketing
Features Available        : PASS
Target Excluded           : PASS
Feature Count Valid       : PASS
Feature Names Unique      : PASS
All Features Numeric      : PASS

Dataset : diabetes_130us
Features Available        : PASS
Target Excluded           : PASS
Feature Count Valid       : PASS
Feature Names Unique      : PASS
All Features Numeric      : PASS

PART E2 — Feature column verification completed.

In [25]:
# ==============================================================================
# PART E3 — FEATURE AND TARGET MATRICES
# ==============================================================================

print("=" * 100)
print("PART E3 — FEATURE AND TARGET MATRICES")
print("=" * 100)

FEATURE_MATRICES = {}
TARGET_MATRICES = {}

for dataset in DATASETS:

    feature_data = FEATURE_DATASETS[
        dataset
    ]

    target_data = TARGET_DATASETS[
        dataset
    ]

    feature_matrix = feature_data[
        FEATURE_COLUMNS[dataset]
    ].to_numpy(
        dtype=np.float32
    )

    target_matrix = target_data.to_numpy(
        dtype=np.float32
    ).reshape(
        -1,
        1
    )

    if not np.isfinite(
        feature_matrix
    ).all():

        raise ValueError(
            f"Non-finite feature values detected "
            f"in {dataset}."
        )

    if not np.isfinite(
        target_matrix
    ).all():

        raise ValueError(
            f"Non-finite target values detected "
            f"in {dataset}."
        )

    FEATURE_MATRICES[dataset] = (
        feature_matrix
    )

    TARGET_MATRICES[dataset] = (
        target_matrix
    )

    print()
    print(
        f"Dataset : {dataset}"
    )

    print(
        f"Feature Matrix Shape : "
        f"{feature_matrix.shape}"
    )

    print(
        f"Target Matrix Shape  : "
        f"{target_matrix.shape}"
    )

print()
print(
    "PART E3 — Feature and target matrices created."
)

====================================================================================================
PART E3 — FEATURE AND TARGET MATRICES
====================================================================================================

Dataset : Adult Income
Feature Matrix Shape : (32515, 14)
Target Matrix Shape  : (32515, 1)

Dataset : Bank Marketing
Feature Matrix Shape : (45211, 16)
Target Matrix Shape  : (45211, 1)

Dataset : diabetes_130us
Feature Matrix Shape : (101766, 47)
Target Matrix Shape  : (101766, 1)

PART E3 — Feature and target matrices created.

In [26]:
# ==============================================================================
# PART E4 — FEATURE DIMENSION CONFIGURATION
# ==============================================================================

print("=" * 100)
print("PART E4 — FEATURE DIMENSION CONFIGURATION")
print("=" * 100)

SPP_GAN_INPUT_DIMENSIONS = {}
SPP_GAN_TARGET_DIMENSIONS = {}
SPP_GAN_OUTPUT_DIMENSIONS = {}

for dataset in DATASETS:

    input_dimension = (
        FEATURE_MATRICES[dataset]
        .shape[1]
    )

    target_dimension = (
        TARGET_MATRICES[dataset]
        .shape[1]
    )

    output_dimension = (
        input_dimension
        + target_dimension
    )

    SPP_GAN_INPUT_DIMENSIONS[
        dataset
    ] = input_dimension

    SPP_GAN_TARGET_DIMENSIONS[
        dataset
    ] = target_dimension

    SPP_GAN_OUTPUT_DIMENSIONS[
        dataset
    ] = output_dimension

    print()
    print(
        f"Dataset : {dataset}"
    )

    print(
        f"Generator Input Dimension : "
        f"{input_dimension}"
    )

    print(
        f"Target Dimension          : "
        f"{target_dimension}"
    )

    print(
        f"Generator Output Dimension: "
        f"{output_dimension}"
    )

print()
print(
    "PART E4 — Feature dimension configuration completed."
)

====================================================================================================
PART E4 — FEATURE DIMENSION CONFIGURATION
====================================================================================================

Dataset : Adult Income
Generator Input Dimension : 14
Target Dimension          : 1
Generator Output Dimension: 15

Dataset : Bank Marketing
Generator Input Dimension : 16
Target Dimension          : 1
Generator Output Dimension: 17

Dataset : diabetes_130us
Generator Input Dimension : 47
Target Dimension          : 1
Generator Output Dimension: 48

PART E4 — Feature dimension configuration completed.

In [27]:
# ==============================================================================
# PART E5 — FEATURE REPRESENTATION SUMMARY
# ==============================================================================

print("=" * 100)
print("PART E5 — FEATURE REPRESENTATION SUMMARY")
print("=" * 100)

FEATURE_REPRESENTATION_SUMMARY = []

for dataset in DATASETS:

    feature_matrix = FEATURE_MATRICES[dataset]
    target_matrix = TARGET_MATRICES[dataset]

    FEATURE_REPRESENTATION_SUMMARY.append({
        "Dataset":
            dataset,
        "Rows":
            feature_matrix.shape[0],
        "Input Features":
            SPP_GAN_INPUT_DIMENSIONS[dataset],
        "Numeric Features":
            len(NUMERIC_COLUMNS[dataset]),
        "Categorical Features":
            len(CATEGORICAL_COLUMNS[dataset]),
        "Other Features":
            len(OTHER_COLUMNS[dataset]),
        "Target":
            TARGET_COLUMNS[dataset],
        "Target Dimension":
            SPP_GAN_TARGET_DIMENSIONS[dataset],
        "Output Dimension":
            SPP_GAN_OUTPUT_DIMENSIONS[dataset],
        "Representation Valid":
            (
                np.isfinite(feature_matrix).all()
                and
                np.isfinite(target_matrix).all()
            )
    })

FEATURE_REPRESENTATION_SUMMARY_DF = pd.DataFrame(
    FEATURE_REPRESENTATION_SUMMARY
)

print()
display(
    FEATURE_REPRESENTATION_SUMMARY_DF
)

print()
print(
    "PART E5 — Feature representation summary completed."
)

====================================================================================================
PART E5 — FEATURE REPRESENTATION SUMMARY
====================================================================================================

,Dataset,Rows,Input Features,Numeric Features,Categorical Features,Other Features,Target,Target Dimension,Output Dimension,Representation Valid
0,Adult Income,32515,14,14,0,0,income,1,15,True
1,Bank Marketing,45211,16,16,0,0,y,1,17,True
2,diabetes_130us,101766,47,47,0,0,readmitted,1,48,True

PART E5 — Feature representation summary completed.

In [28]:
# ==============================================================================
# PART F1 — SPP-GAN CORE CONFIGURATION
# ==============================================================================

print("=" * 100)
print("PART F1 — SPP-GAN CORE CONFIGURATION")
print("=" * 100)

SPP_GAN_NAME = "SPP-GAN"
SPP_GAN_VERSION = "1.0"

SPP_GAN_SEED = PROJECT_CONFIG["seed"]

SPP_GAN_LATENT_DIMENSION = (
    PROJECT_CONFIG["latent_dimension"]
)

SPP_GAN_GENERATOR_HIDDEN_DIMENSIONS = [
    256,
    512,
    512,
    256
]

SPP_GAN_DISCRIMINATOR_HIDDEN_DIMENSIONS = [
    256,
    512,
    256
]

print()
print(
    f"Model Name              : "
    f"{SPP_GAN_NAME}"
)

print(
    f"Version                 : "
    f"{SPP_GAN_VERSION}"
)

print(
    f"Random Seed             : "
    f"{SPP_GAN_SEED}"
)

print(
    f"Latent Dimension        : "
    f"{SPP_GAN_LATENT_DIMENSION}"
)

print(
    f"Generator Hidden Layers : "
    f"{SPP_GAN_GENERATOR_HIDDEN_DIMENSIONS}"
)

print(
    f"Discriminator Layers    : "
    f"{SPP_GAN_DISCRIMINATOR_HIDDEN_DIMENSIONS}"
)

print()
print(
    "PART F1 — SPP-GAN core configuration completed."
)

====================================================================================================
PART F1 — SPP-GAN CORE CONFIGURATION
====================================================================================================

Model Name              : SPP-GAN
Version                 : 1.0
Random Seed             : 42
Latent Dimension        : 128
Generator Hidden Layers : [256, 512, 512, 256]
Discriminator Layers    : [256, 512, 256]

PART F1 — SPP-GAN core configuration completed.

In [29]:
# ==============================================================================
# PART F2 — STATISTICAL GUIDANCE CONFIGURATION
# ==============================================================================

print("=" * 100)
print("PART F2 — STATISTICAL GUIDANCE CONFIGURATION")
print("=" * 100)

SPP_GAN_STATISTICAL_GUIDANCE = True

SPP_GAN_STATISTICAL_WEIGHT = 0.10

SPP_GAN_STATISTICAL_COMPONENT = (
    "Distribution and Correlation Guidance"
)

print()
print(
    f"Statistical Guidance : "
    f"{SPP_GAN_STATISTICAL_GUIDANCE}"
)

print(
    f"Statistical Weight   : "
    f"{SPP_GAN_STATISTICAL_WEIGHT}"
)

print(
    f"Statistical Component: "
    f"{SPP_GAN_STATISTICAL_COMPONENT}"
)

print()
print(
    "PART F2 — Statistical guidance configuration completed."
)

====================================================================================================
PART F2 — STATISTICAL GUIDANCE CONFIGURATION
====================================================================================================

Statistical Guidance : True
Statistical Weight   : 0.1
Statistical Component: Distribution and Correlation Guidance

PART F2 — Statistical guidance configuration completed.

In [30]:
# ==============================================================================
# PART F3 — DIFFERENTIAL PRIVACY CONFIGURATION
# ==============================================================================

print("=" * 100)
print("PART F3 — DIFFERENTIAL PRIVACY CONFIGURATION")
print("=" * 100)

SPP_GAN_DIFFERENTIAL_PRIVACY = True

SPP_GAN_PRIVACY_EPSILON = (
    PROJECT_CONFIG["privacy_budget"]
)

SPP_GAN_PRIVACY_DELTA = (
    PROJECT_CONFIG["delta"]
)

SPP_GAN_NOISE_MULTIPLIER = (
    PROJECT_CONFIG["noise_multiplier"]
)

SPP_GAN_MAX_GRAD_NORM = (
    PROJECT_CONFIG["gradient_clip"]
)

SPP_GAN_PRIVACY_MECHANISM = (
    "DP-SGD with Gaussian Noise"
)

print()
print(
    f"Differential Privacy : "
    f"{SPP_GAN_DIFFERENTIAL_PRIVACY}"
)

print(
    f"Privacy Budget ε     : "
    f"{SPP_GAN_PRIVACY_EPSILON}"
)

print(
    f"Privacy Delta δ      : "
    f"{SPP_GAN_PRIVACY_DELTA}"
)

print(
    f"Noise Multiplier     : "
    f"{SPP_GAN_NOISE_MULTIPLIER}"
)

print(
    f"Maximum Gradient Norm: "
    f"{SPP_GAN_MAX_GRAD_NORM}"
)

print(
    f"Privacy Mechanism    : "
    f"{SPP_GAN_PRIVACY_MECHANISM}"
)

print()
print(
    "PART F3 — Differential privacy configuration completed."
)

====================================================================================================
PART F3 — DIFFERENTIAL PRIVACY CONFIGURATION
====================================================================================================

Differential Privacy : True
Privacy Budget ε     : 4
Privacy Delta δ      : 1e-05
Noise Multiplier     : 1.1
Maximum Gradient Norm: 1.0
Privacy Mechanism    : DP-SGD with Gaussian Noise

PART F3 — Differential privacy configuration completed.

In [31]:
# ==============================================================================
# PART F4 — GAN TRAINING CONFIGURATION
# ==============================================================================

print("=" * 100)
print("PART F4 — GAN TRAINING CONFIGURATION")
print("=" * 100)

SPP_GAN_EPOCHS = (
    PROJECT_CONFIG["epochs"]
)

SPP_GAN_BATCH_SIZE = (
    PROJECT_CONFIG["batch_size"]
)

SPP_GAN_LEARNING_RATE = (
    PROJECT_CONFIG["learning_rate"]
)

SPP_GAN_OPTIMIZER = "Adam"

SPP_GAN_BETA1 = (
    PROJECT_CONFIG["beta1"]
)

SPP_GAN_BETA2 = (
    PROJECT_CONFIG["beta2"]
)

SPP_GAN_DISCRIMINATOR_STEPS = 1

SPP_GAN_GENERATOR_STEPS = 1

print()

print(
    f"Epochs                 : "
    f"{SPP_GAN_EPOCHS}"
)

print(
    f"Batch Size             : "
    f"{SPP_GAN_BATCH_SIZE}"
)

print(
    f"Learning Rate          : "
    f"{SPP_GAN_LEARNING_RATE}"
)

print(
    f"Optimizer              : "
    f"{SPP_GAN_OPTIMIZER}"
)

print(
    f"Adam β1                : "
    f"{SPP_GAN_BETA1}"
)

print(
    f"Adam β2                : "
    f"{SPP_GAN_BETA2}"
)

print(
    f"Discriminator Steps    : "
    f"{SPP_GAN_DISCRIMINATOR_STEPS}"
)

print(
    f"Generator Steps        : "
    f"{SPP_GAN_GENERATOR_STEPS}"
)

print()
print(
    "PART F4 — GAN training configuration completed."
)

====================================================================================================
PART F4 — GAN TRAINING CONFIGURATION
====================================================================================================

Epochs                 : 100
Batch Size             : 256
Learning Rate          : 0.0002
Optimizer              : Adam
Adam β1                : 0.5
Adam β2                : 0.999
Discriminator Steps    : 1
Generator Steps        : 1

PART F4 — GAN training configuration completed.

In [32]:
# ==============================================================================
# PART F5 — DEVICE AND REPRODUCIBILITY CONFIGURATION
# ==============================================================================

print("=" * 100)
print("PART F5 — DEVICE AND REPRODUCIBILITY CONFIGURATION")
print("=" * 100)

SPP_GAN_DEVICE = torch.device(
    "cuda"
    if torch.cuda.is_available()
    else "cpu"
)

os.environ["PYTHONHASHSEED"] = str(
    SPP_GAN_SEED
)

random.seed(
    SPP_GAN_SEED
)

np.random.seed(
    SPP_GAN_SEED
)

torch.manual_seed(
    SPP_GAN_SEED
)

if torch.cuda.is_available():

    torch.cuda.manual_seed(
        SPP_GAN_SEED
    )

    torch.cuda.manual_seed_all(
        SPP_GAN_SEED
    )

    torch.backends.cudnn.deterministic = True

    torch.backends.cudnn.benchmark = False

print()
print(
    f"Device                 : "
    f"{SPP_GAN_DEVICE}"
)

print(
    f"CUDA Available         : "
    f"{torch.cuda.is_available()}"
)

print(
    f"Random Seed            : "
    f"{SPP_GAN_SEED}"
)

print()
print(
    "PART F5 — Device and reproducibility configuration completed."
)

====================================================================================================
PART F5 — DEVICE AND REPRODUCIBILITY CONFIGURATION
====================================================================================================

Device                 : cpu
CUDA Available         : False
Random Seed            : 42

PART F5 — Device and reproducibility configuration completed.

In [33]:
# ==============================================================================
# PART F6 — COMPLETE SPP-GAN CONFIGURATION
# ==============================================================================

print("=" * 100)
print("PART F6 — COMPLETE SPP-GAN CONFIGURATION")
print("=" * 100)

SPP_GAN_CONFIG = {

    "Model":
        SPP_GAN_NAME,

    "Version":
        SPP_GAN_VERSION,

    "Seed":
        SPP_GAN_SEED,

    "Latent Dimension":
        SPP_GAN_LATENT_DIMENSION,

    "Generator Hidden Dimensions":
        SPP_GAN_GENERATOR_HIDDEN_DIMENSIONS,

    "Discriminator Hidden Dimensions":
        SPP_GAN_DISCRIMINATOR_HIDDEN_DIMENSIONS,

    "Statistical Guidance":
        SPP_GAN_STATISTICAL_GUIDANCE,

    "Statistical Weight":
        SPP_GAN_STATISTICAL_WEIGHT,

    "Statistical Component":
        SPP_GAN_STATISTICAL_COMPONENT,

    "Differential Privacy":
        SPP_GAN_DIFFERENTIAL_PRIVACY,

    "Privacy Budget":
        SPP_GAN_PRIVACY_EPSILON,

    "Privacy Delta":
        SPP_GAN_PRIVACY_DELTA,

    "Noise Multiplier":
        SPP_GAN_NOISE_MULTIPLIER,

    "Maximum Gradient Norm":
        SPP_GAN_MAX_GRAD_NORM,

    "Epochs":
        SPP_GAN_EPOCHS,

    "Batch Size":
        SPP_GAN_BATCH_SIZE,

    "Learning Rate":
        SPP_GAN_LEARNING_RATE,

    "Optimizer":
        SPP_GAN_OPTIMIZER,

    "Adam Beta1":
        SPP_GAN_BETA1,

    "Adam Beta2":
        SPP_GAN_BETA2,

    "Discriminator Steps":
        SPP_GAN_DISCRIMINATOR_STEPS,

    "Generator Steps":
        SPP_GAN_GENERATOR_STEPS,

    "Device":
        str(SPP_GAN_DEVICE)
}

SPP_GAN_CONFIG_DF = pd.DataFrame(
    list(
        SPP_GAN_CONFIG.items()
    ),
    columns=[
        "Parameter",
        "Value"
    ]
)

print()

display(
    SPP_GAN_CONFIG_DF
)

print()
print(
    "PART F6 — Complete SPP-GAN configuration created."
)

====================================================================================================
PART F6 — COMPLETE SPP-GAN CONFIGURATION
====================================================================================================

                          Parameter                                  Value
0                             Model                                SPP-GAN
1                           Version                                    1.0
2                              Seed                                     42
3                  Latent Dimension                                    128
4       Generator Hidden Dimensions                   [256, 512, 512, 256]
5   Discriminator Hidden Dimensions                        [256, 512, 256]
6              Statistical Guidance                                   True
7                Statistical Weight                                    0.1
8             Statistical Component  Distribution and Correlation Guidance
9              Differential Privacy                                   True
10                   Privacy Budget                                      4
11                    Privacy Delta                                0.00001
12                 Noise Multiplier                                    1.1
13            Maximum Gradient Norm                                    1.0
14                           Epochs                                    100
15                       Batch Size                                    256
16                    Learning Rate                                 0.0002
17                        Optimizer                                   Adam
18                       Adam Beta1                                    0.5
19                       Adam Beta2                                  0.999
20              Discriminator Steps                                      1
21                  Generator Steps                                      1
22                           Device                                    cpu

PART F6 — Complete SPP-GAN configuration created.

In [34]:
# ==============================================================================
# PART F7 — SPP-GAN CONFIGURATION VALIDATION
# ==============================================================================

print("=" * 100)
print("PART F7 — SPP-GAN CONFIGURATION VALIDATION")
print("=" * 100)

SPP_GAN_CONFIGURATION_CHECKS = {

    "Model Name Defined":
        SPP_GAN_NAME == "SPP-GAN",

    "Seed Valid":
        isinstance(
            SPP_GAN_SEED,
            int
        ),

    "Latent Dimension Valid":
        SPP_GAN_LATENT_DIMENSION > 0,

    "Generator Architecture Valid":
        len(
            SPP_GAN_GENERATOR_HIDDEN_DIMENSIONS
        ) > 0,

    "Discriminator Architecture Valid":
        len(
            SPP_GAN_DISCRIMINATOR_HIDDEN_DIMENSIONS
        ) > 0,

    "Statistical Guidance Valid":
        isinstance(
            SPP_GAN_STATISTICAL_GUIDANCE,
            bool
        ),

    "Statistical Weight Valid":
        0 <= SPP_GAN_STATISTICAL_WEIGHT <= 1,

    "Privacy Enabled":
        SPP_GAN_DIFFERENTIAL_PRIVACY is True,

    "Privacy Epsilon Valid":
        SPP_GAN_PRIVACY_EPSILON > 0,

    "Privacy Delta Valid":
        0 < SPP_GAN_PRIVACY_DELTA < 1,

    "Noise Multiplier Valid":
        SPP_GAN_NOISE_MULTIPLIER > 0,

    "Gradient Norm Valid":
        SPP_GAN_MAX_GRAD_NORM > 0,

    "Epochs Valid":
        SPP_GAN_EPOCHS > 0,

    "Batch Size Valid":
        SPP_GAN_BATCH_SIZE > 0,

    "Learning Rate Valid":
        SPP_GAN_LEARNING_RATE > 0,

    "Adam Beta1 Valid":
        0 <= SPP_GAN_BETA1 < 1,

    "Adam Beta2 Valid":
        0 <= SPP_GAN_BETA2 < 1,

    "Generator Steps Valid":
        SPP_GAN_GENERATOR_STEPS > 0,

    "Discriminator Steps Valid":
        SPP_GAN_DISCRIMINATOR_STEPS > 0,

    "Device Valid":
        SPP_GAN_DEVICE is not None
}

for check, status in (
    SPP_GAN_CONFIGURATION_CHECKS.items()
):

    print(
        f"{check:40s} : "
        f"{'PASS' if status else 'FAIL'}"
    )

print()

if not all(
    SPP_GAN_CONFIGURATION_CHECKS.values()
):

    raise ValueError(
        "SPP-GAN configuration validation failed."
    )

print(
    "All SPP-GAN configuration checks passed."
)

print()
print(
    "PART F7 — SPP-GAN configuration validation completed."
)

====================================================================================================
PART F7 — SPP-GAN CONFIGURATION VALIDATION
====================================================================================================
Model Name Defined                       : PASS
Seed Valid                               : PASS
Latent Dimension Valid                   : PASS
Generator Architecture Valid             : PASS
Discriminator Architecture Valid         : PASS
Statistical Guidance Valid               : PASS
Statistical Weight Valid                 : PASS
Privacy Enabled                          : PASS
Privacy Epsilon Valid                    : PASS
Privacy Delta Valid                      : PASS
Noise Multiplier Valid                   : PASS
Gradient Norm Valid                      : PASS
Epochs Valid                             : PASS
Batch Size Valid                         : PASS
Learning Rate Valid                      : PASS
Adam Beta1 Valid                         : PASS
Adam Beta2 Valid                         : PASS
Generator Steps Valid                    : PASS
Discriminator Steps Valid                : PASS
Device Valid                             : PASS

All SPP-GAN configuration checks passed.

PART F7 — SPP-GAN configuration validation completed.

In [35]:
# ==============================================================================
# PART G1 — PRIVACY MECHANISM CONFIGURATION
# ==============================================================================

print("=" * 100)
print("PART G1 — PRIVACY MECHANISM CONFIGURATION")
print("=" * 100)

SPP_GAN_PRIVACY_ENABLED = True

SPP_GAN_PRIVACY_MECHANISM = (
    "Differential Privacy"
)

SPP_GAN_PRIVACY_NOISE_TYPE = (
    "Gaussian"
)

SPP_GAN_PRIVACY_TRAINING_METHOD = (
    "Differentially Private Gradient-Based Training"
)

print()

print(
    f"Privacy Enabled       : "
    f"{SPP_GAN_PRIVACY_ENABLED}"
)

print(
    f"Privacy Mechanism     : "
    f"{SPP_GAN_PRIVACY_MECHANISM}"
)

print(
    f"Noise Type            : "
    f"{SPP_GAN_PRIVACY_NOISE_TYPE}"
)

print(
    f"Training Method       : "
    f"{SPP_GAN_PRIVACY_TRAINING_METHOD}"
)

print()

print(
    "PART G1 — Privacy mechanism configuration completed."
)

====================================================================================================
PART G1 — PRIVACY MECHANISM CONFIGURATION
====================================================================================================

Privacy Enabled       : True
Privacy Mechanism     : Differential Privacy
Noise Type            : Gaussian
Training Method       : Differentially Private Gradient-Based Training

PART G1 — Privacy mechanism configuration completed.

In [36]:
# ==============================================================================
# PART G2 — PRIVACY BUDGET CONFIGURATION
# ==============================================================================

print("=" * 100)
print("PART G2 — PRIVACY BUDGET CONFIGURATION")
print("=" * 100)

SPP_GAN_PRIVACY_EPSILON = (
    PROJECT_CONFIG["privacy_budget"]
)

SPP_GAN_PRIVACY_DELTA = (
    PROJECT_CONFIG["delta"]
)

print()

print(
    f"Privacy Budget ε     : "
    f"{SPP_GAN_PRIVACY_EPSILON}"
)

print(
    f"Privacy Delta δ      : "
    f"{SPP_GAN_PRIVACY_DELTA}"
)

print()

print(
    "PART G2 — Privacy budget configuration completed."
)

====================================================================================================
PART G2 — PRIVACY BUDGET CONFIGURATION
====================================================================================================

Privacy Budget ε     : 4
Privacy Delta δ      : 1e-05

PART G2 — Privacy budget configuration completed.

In [37]:
# ==============================================================================
# PART G3 — PRIVACY NOISE CONFIGURATION
# ==============================================================================

print("=" * 100)
print("PART G3 — PRIVACY NOISE CONFIGURATION")
print("=" * 100)

SPP_GAN_NOISE_MULTIPLIER = (
    PROJECT_CONFIG["noise_multiplier"]
)

SPP_GAN_NOISE_TYPE = (
    "Gaussian"
)

SPP_GAN_NOISE_ENABLED = True

print()

print(
    f"Noise Enabled        : "
    f"{SPP_GAN_NOISE_ENABLED}"
)

print(
    f"Noise Type           : "
    f"{SPP_GAN_NOISE_TYPE}"
)

print(
    f"Noise Multiplier     : "
    f"{SPP_GAN_NOISE_MULTIPLIER}"
)

print()

print(
    "PART G3 — Privacy noise configuration completed."
)

====================================================================================================
PART G3 — PRIVACY NOISE CONFIGURATION
====================================================================================================

Noise Enabled        : True
Noise Type           : Gaussian
Noise Multiplier     : 1.1

PART G3 — Privacy noise configuration completed.

In [38]:
# ==============================================================================
# PART G4 — GRADIENT PROTECTION CONFIGURATION
# ==============================================================================

print("=" * 100)
print("PART G4 — GRADIENT PROTECTION CONFIGURATION")
print("=" * 100)

SPP_GAN_GRADIENT_CLIPPING = True

SPP_GAN_MAX_GRAD_NORM = (
    PROJECT_CONFIG["gradient_clip"]
)

print()

print(
    f"Gradient Clipping    : "
    f"{SPP_GAN_GRADIENT_CLIPPING}"
)

print(
    f"Maximum Gradient Norm: "
    f"{SPP_GAN_MAX_GRAD_NORM}"
)

print()

print(
    "PART G4 — Gradient protection configuration completed."
)

====================================================================================================
PART G4 — GRADIENT PROTECTION CONFIGURATION
====================================================================================================

Gradient Clipping    : True
Maximum Gradient Norm: 1.0

PART G4 — Gradient protection configuration completed.

In [39]:
# ==============================================================================
# PART G5 — DATASET-LEVEL PRIVACY CONFIGURATION
# ==============================================================================

print("=" * 100)
print("PART G5 — DATASET-LEVEL PRIVACY CONFIGURATION")
print("=" * 100)

SPP_GAN_DATASET_PRIVACY_CONFIG = {}

for dataset in DATASETS:

    SPP_GAN_DATASET_PRIVACY_CONFIG[dataset] = {

        "Dataset":
            dataset,

        "Privacy Enabled":
            SPP_GAN_PRIVACY_ENABLED,

        "Privacy Budget Epsilon":
            SPP_GAN_PRIVACY_EPSILON,

        "Privacy Delta":
            SPP_GAN_PRIVACY_DELTA,

        "Noise Multiplier":
            SPP_GAN_NOISE_MULTIPLIER,

        "Maximum Gradient Norm":
            SPP_GAN_MAX_GRAD_NORM
    }

SPP_GAN_DATASET_PRIVACY_SUMMARY = pd.DataFrame(
    SPP_GAN_DATASET_PRIVACY_CONFIG
).T.reset_index(
    drop=True
)

print()

display(
    SPP_GAN_DATASET_PRIVACY_SUMMARY
)

print()

print(
    "PART G5 — Dataset-level privacy configuration completed."
)

====================================================================================================
PART G5 — DATASET-LEVEL PRIVACY CONFIGURATION
====================================================================================================

,Dataset,Privacy Enabled,Privacy Budget Epsilon,Privacy Delta,Noise Multiplier,Maximum Gradient Norm
0,Adult Income,True,4,0.00001,1.1,1.0
1,Bank Marketing,True,4,0.00001,1.1,1.0
2,diabetes_130us,True,4,0.00001,1.1,1.0

PART G5 — Dataset-level privacy configuration completed.

In [40]:
# ==============================================================================
# PART G6 — PRIVACY CONFIGURATION VALIDATION
# ==============================================================================

print("=" * 100)
print("PART G6 — PRIVACY CONFIGURATION VALIDATION")
print("=" * 100)

SPP_GAN_PRIVACY_CHECKS = {

    "Privacy Enabled":
        SPP_GAN_PRIVACY_ENABLED is True,

    "Privacy Mechanism Defined":
        len(
            str(
                SPP_GAN_PRIVACY_MECHANISM
            )
        ) > 0,

    "Gaussian Noise Enabled":
        SPP_GAN_NOISE_ENABLED is True,

    "Privacy Budget Valid":
        (
            isinstance(
                SPP_GAN_PRIVACY_EPSILON,
                (int, float)
            )
            and
            SPP_GAN_PRIVACY_EPSILON > 0
        ),

    "Privacy Delta Valid":
        (
            isinstance(
                SPP_GAN_PRIVACY_DELTA,
                (int, float)
            )
            and
            0 < SPP_GAN_PRIVACY_DELTA < 1
        ),

    "Noise Multiplier Valid":
        (
            isinstance(
                SPP_GAN_NOISE_MULTIPLIER,
                (int, float)
            )
            and
            SPP_GAN_NOISE_MULTIPLIER > 0
        ),

    "Gradient Clipping Enabled":
        SPP_GAN_GRADIENT_CLIPPING is True,

    "Maximum Gradient Norm Valid":
        (
            isinstance(
                SPP_GAN_MAX_GRAD_NORM,
                (int, float)
            )
            and
            SPP_GAN_MAX_GRAD_NORM > 0
        ),

    "All Datasets Configured":
        (
            len(
                SPP_GAN_DATASET_PRIVACY_CONFIG
            )
            ==
            len(DATASETS)
        )
}

for check, status in (
    SPP_GAN_PRIVACY_CHECKS.items()
):

    print(
        f"{check:40s} : "
        f"{'PASS' if status else 'FAIL'}"
    )

print()

if not all(
    SPP_GAN_PRIVACY_CHECKS.values()
):

    raise ValueError(
        "SPP-GAN privacy configuration validation failed."
    )

print(
    "All SPP-GAN privacy configuration checks passed."
)

print()

print(
    "PART G6 — Privacy configuration validation completed."
)

====================================================================================================
PART G6 — PRIVACY CONFIGURATION VALIDATION
====================================================================================================
Privacy Enabled                          : PASS
Privacy Mechanism Defined                : PASS
Gaussian Noise Enabled                   : PASS
Privacy Budget Valid                     : PASS
Privacy Delta Valid                      : PASS
Noise Multiplier Valid                   : PASS
Gradient Clipping Enabled                : PASS
Maximum Gradient Norm Valid              : PASS
All Datasets Configured                  : PASS

All SPP-GAN privacy configuration checks passed.

PART G6 — Privacy configuration validation completed.

In [41]:
# ==============================================================================
# PART G7 — PRIVACY CONFIGURATION SUMMARY
# ==============================================================================

print("=" * 100)
print("PART G7 — PRIVACY CONFIGURATION SUMMARY")
print("=" * 100)

SPP_GAN_PRIVACY_SUMMARY = {

    "Privacy Enabled":
        SPP_GAN_PRIVACY_ENABLED,

    "Privacy Mechanism":
        SPP_GAN_PRIVACY_MECHANISM,

    "Noise Type":
        SPP_GAN_PRIVACY_NOISE_TYPE,

    "Privacy Budget Epsilon":
        SPP_GAN_PRIVACY_EPSILON,

    "Privacy Delta":
        SPP_GAN_PRIVACY_DELTA,

    "Noise Multiplier":
        SPP_GAN_NOISE_MULTIPLIER,

    "Gradient Clipping":
        SPP_GAN_GRADIENT_CLIPPING,

    "Maximum Gradient Norm":
        SPP_GAN_MAX_GRAD_NORM,

    "Datasets Configured":
        len(
            SPP_GAN_DATASET_PRIVACY_CONFIG
        ),

    "Configuration Valid":
        all(
            SPP_GAN_PRIVACY_CHECKS.values()
        )
}

SPP_GAN_PRIVACY_SUMMARY_DF = pd.DataFrame(
    list(
        SPP_GAN_PRIVACY_SUMMARY.items()
    ),
    columns=[
        "Parameter",
        "Value"
    ]
)

print()

display(
    SPP_GAN_PRIVACY_SUMMARY_DF
)

print()

print(
    f"Overall Privacy Configuration Status : "
    f"{'PASS' if SPP_GAN_PRIVACY_SUMMARY['Configuration Valid'] else 'FAIL'}"
)

print()

print(
    "PART G7 — Privacy configuration summary completed."
)

====================================================================================================
PART G7 — PRIVACY CONFIGURATION SUMMARY
====================================================================================================

                Parameter                 Value
0         Privacy Enabled                  True
1       Privacy Mechanism  Differential Privacy
2              Noise Type              Gaussian
3  Privacy Budget Epsilon                     4
4           Privacy Delta               0.00001
5        Noise Multiplier                   1.1
6       Gradient Clipping                  True
7   Maximum Gradient Norm                   1.0
8     Datasets Configured                     3
9     Configuration Valid                  True

Overall Privacy Configuration Status : PASS

PART G7 — Privacy configuration summary completed.

In [50]:
# ==============================================================================
# PART H1 — GENERATOR ARCHITECTURE CONFIGURATION
# ==============================================================================

print("=" * 100)
print("PART H1 — GENERATOR ARCHITECTURE CONFIGURATION")
print("=" * 100)

SPP_GAN_GENERATOR_INPUT_DIMENSIONS = {
    dataset:
        int(
            SPP_GAN_LATENT_DIMENSION
        )
    for dataset in DATASETS
}

SPP_GAN_GENERATOR_HIDDEN_DIMENSIONS = list(
    SPP_GAN_CONFIG[
        "Generator Hidden Dimensions"
    ]
)

SPP_GAN_GENERATOR_ACTIVATION = (
    "LeakyReLU"
)

SPP_GAN_GENERATOR_OUTPUT_ACTIVATION = (
    "Linear"
)

SPP_GAN_GENERATOR_OUTPUT_DIMENSIONS = {
    dataset:
        int(
            SPP_GAN_INPUT_DIMENSIONS[dataset]
        )
    for dataset in DATASETS
}

print()

print(
    f"Latent Dimension         : "
    f"{SPP_GAN_LATENT_DIMENSION}"
)

print(
    f"Hidden Dimensions        : "
    f"{SPP_GAN_GENERATOR_HIDDEN_DIMENSIONS}"
)

print(
    f"Hidden Activation        : "
    f"{SPP_GAN_GENERATOR_ACTIVATION}"
)

print(
    f"Output Activation        : "
    f"{SPP_GAN_GENERATOR_OUTPUT_ACTIVATION}"
)

print()

print(
    "Dataset-Specific Generator Dimensions:"
)

for dataset in DATASETS:

    print(
        f"{dataset:20s} : "
        f"Input = "
        f"{SPP_GAN_GENERATOR_INPUT_DIMENSIONS[dataset]} | "
        f"Output = "
        f"{SPP_GAN_GENERATOR_OUTPUT_DIMENSIONS[dataset]}"
    )

print()

print(
    "PART H1 — Generator architecture configuration completed."
)

====================================================================================================
PART H1 — GENERATOR ARCHITECTURE CONFIGURATION
====================================================================================================

Latent Dimension         : 128
Hidden Dimensions        : [256, 512, 512, 256]
Hidden Activation        : LeakyReLU
Output Activation        : Linear

Dataset-Specific Generator Dimensions:
Adult Income         : Input = 128 | Output = 14
Bank Marketing       : Input = 128 | Output = 16
diabetes_130us       : Input = 128 | Output = 47

PART H1 — Generator architecture configuration completed.

In [51]:
# ==============================================================================
# PART H2 — GENERATOR NETWORK
# ==============================================================================

print("=" * 100)
print("PART H2 — GENERATOR NETWORK")
print("=" * 100)

class SPPGANGenerator(nn.Module):

    def __init__(
        self,
        input_dimension,
        hidden_dimensions,
        output_dimension
    ):

        super().__init__()

        layers = []

        current_dimension = int(
            input_dimension
        )

        for hidden_dimension in hidden_dimensions:

            hidden_dimension = int(
                hidden_dimension
            )

            layers.append(
                nn.Linear(
                    current_dimension,
                    hidden_dimension
                )
            )

            layers.append(
                nn.LayerNorm(
                    hidden_dimension
                )
            )

            layers.append(
                nn.LeakyReLU(
                    negative_slope=0.2,
                    inplace=False
                )
            )

            current_dimension = (
                hidden_dimension
            )

        layers.append(
            nn.Linear(
                current_dimension,
                int(output_dimension)
            )
        )

        self.network = nn.Sequential(
            *layers
        )

    def forward(
        self,
        noise
    ):

        return self.network(
            noise
        )

SPP_GAN_GENERATORS = {}

for dataset in DATASETS:

    generator = SPPGANGenerator(
        input_dimension=
            SPP_GAN_GENERATOR_INPUT_DIMENSIONS[
                dataset
            ],
        hidden_dimensions=
            SPP_GAN_GENERATOR_HIDDEN_DIMENSIONS,
        output_dimension=
            SPP_GAN_GENERATOR_OUTPUT_DIMENSIONS[
                dataset
            ]
    )

    generator = generator.to(
        SPP_GAN_DEVICE
    )

    SPP_GAN_GENERATORS[dataset] = (
        generator
    )

    print()

    print(
        f"Dataset              : "
        f"{dataset}"
    )

    print(
        f"Input Dimension      : "
        f"{SPP_GAN_GENERATOR_INPUT_DIMENSIONS[dataset]}"
    )

    print(
        f"Output Dimension     : "
        f"{SPP_GAN_GENERATOR_OUTPUT_DIMENSIONS[dataset]}"
    )

print()

print(
    "SPP-GAN Generator networks created successfully."
)

print()

print(
    "PART H2 — Generator network completed."
)

====================================================================================================
PART H2 — GENERATOR NETWORK
====================================================================================================

Dataset              : Adult Income
Input Dimension      : 128
Output Dimension     : 14

Dataset              : Bank Marketing
Input Dimension      : 128
Output Dimension     : 16

Dataset              : diabetes_130us
Input Dimension      : 128
Output Dimension     : 47

SPP-GAN Generator networks created successfully.

PART H2 — Generator network completed.

In [52]:
# ==============================================================================
# PART H3 — GENERATOR VALIDATION SOURCE
# ==============================================================================

print("=" * 100)
print("PART H3 — GENERATOR VALIDATION SOURCE")
print("=" * 100)

print()

print("SPP_GAN_INPUT_DIMENSIONS:")
print(SPP_GAN_INPUT_DIMENSIONS)

print()

print("SPP_GAN_OUTPUT_DIMENSIONS:")
print(SPP_GAN_OUTPUT_DIMENSIONS)

print()

print("SPP_GAN_GENERATOR_INPUT_DIMENSIONS:")
print(SPP_GAN_GENERATOR_INPUT_DIMENSIONS)

print()

print("SPP_GAN_GENERATOR_OUTPUT_DIMENSIONS:")
print(SPP_GAN_GENERATOR_OUTPUT_DIMENSIONS)

print()

SPP_GAN_GENERATOR_DIMENSION_DIAGNOSTIC = {}

print(
    "Generator Dimension Validation:"
)

print()

for dataset in DATASETS:

    if dataset not in SPP_GAN_GENERATORS:

        raise KeyError(
            f"Generator not found for dataset: {dataset}"
        )

    generator = (
        SPP_GAN_GENERATORS[dataset]
    )

    linear_layers = [
        module
        for module in generator.modules()
        if isinstance(module, nn.Linear)
    ]

    if len(linear_layers) < 2:

        raise ValueError(
            f"Insufficient Linear layers found "
            f"in generator for {dataset}."
        )

    first_linear = linear_layers[0]

    final_linear = linear_layers[-1]

    registered_input_dimension = int(
        SPP_GAN_GENERATOR_INPUT_DIMENSIONS[
            dataset
        ]
    )

    registered_output_dimension = int(
        SPP_GAN_GENERATOR_OUTPUT_DIMENSIONS[
            dataset
        ]
    )

    expected_feature_dimension = int(
        SPP_GAN_INPUT_DIMENSIONS[
            dataset
        ]
    )

    expected_complete_dimension = int(
        SPP_GAN_OUTPUT_DIMENSIONS[
            dataset
        ]
    )

    actual_generator_input_dimension = int(
        first_linear.in_features
    )

    actual_generator_output_dimension = int(
        final_linear.out_features
    )

    input_dimension_valid = (
        actual_generator_input_dimension
        ==
        registered_input_dimension
        ==
        int(SPP_GAN_LATENT_DIMENSION)
    )

    output_dimension_valid = (
        actual_generator_output_dimension
        ==
        registered_output_dimension
    )

    feature_dimension_valid = (
        actual_generator_output_dimension
        ==
        expected_feature_dimension
    )

    complete_dimension_consistent = (
        expected_complete_dimension
        ==
        expected_feature_dimension + 1
    )

    overall_valid = (
        input_dimension_valid
        and
        output_dimension_valid
        and
        feature_dimension_valid
        and
        complete_dimension_consistent
    )

    SPP_GAN_GENERATOR_DIMENSION_DIAGNOSTIC[
        dataset
    ] = {

        "Registered Input Dimension":
            registered_input_dimension,

        "Actual Input Dimension":
            actual_generator_input_dimension,

        "Registered Output Dimension":
            registered_output_dimension,

        "Actual Output Dimension":
            actual_generator_output_dimension,

        "Expected Feature Dimension":
            expected_feature_dimension,

        "Expected Complete Dimension":
            expected_complete_dimension,

        "Input Dimension Valid":
            input_dimension_valid,

        "Output Dimension Valid":
            output_dimension_valid,

        "Feature Dimension Valid":
            feature_dimension_valid,

        "Complete Dimension Consistent":
            complete_dimension_consistent,

        "Overall Valid":
            overall_valid
    }

    print(
        f"Dataset                         : "
        f"{dataset}"
    )

    print(
        f"Registered Generator Input     : "
        f"{registered_input_dimension}"
    )

    print(
        f"Actual Generator Input         : "
        f"{actual_generator_input_dimension}"
    )

    print(
        f"Registered Generator Output    : "
        f"{registered_output_dimension}"
    )

    print(
        f"Actual Generator Output        : "
        f"{actual_generator_output_dimension}"
    )

    print(
        f"Expected GAN Feature Dimension : "
        f"{expected_feature_dimension}"
    )

    print(
        f"Expected Complete Dimension    : "
        f"{expected_complete_dimension}"
    )

    print(
        f"Input Dimension                : "
        f"{'PASS' if input_dimension_valid else 'FAIL'}"
    )

    print(
        f"Output Dimension               : "
        f"{'PASS' if output_dimension_valid else 'FAIL'}"
    )

    print(
        f"Feature Dimension              : "
        f"{'PASS' if feature_dimension_valid else 'FAIL'}"
    )

    print(
        f"Complete Dimension             : "
        f"{'PASS' if complete_dimension_consistent else 'FAIL'}"
    )

    print(
        f"Overall Generator Dimension    : "
        f"{'PASS' if overall_valid else 'FAIL'}"
    )

    print()

print("=" * 100)

if not all(
    result["Overall Valid"]
    for result
    in SPP_GAN_GENERATOR_DIMENSION_DIAGNOSTIC.values()
):

    raise ValueError(
        "SPP-GAN generator dimension diagnostic failed."
    )

print(
    "All SPP-GAN generator dimensions are internally consistent."
)

print()

print(
    "PART H3 — Generator validation source completed."
)

====================================================================================================
PART H3 — GENERATOR VALIDATION SOURCE
====================================================================================================

SPP_GAN_INPUT_DIMENSIONS:
{'Adult Income': 14, 'Bank Marketing': 16, 'diabetes_130us': 47}

SPP_GAN_OUTPUT_DIMENSIONS:
{'Adult Income': 15, 'Bank Marketing': 17, 'diabetes_130us': 48}

SPP_GAN_GENERATOR_INPUT_DIMENSIONS:
{'Adult Income': 128, 'Bank Marketing': 128, 'diabetes_130us': 128}

SPP_GAN_GENERATOR_OUTPUT_DIMENSIONS:
{'Adult Income': 14, 'Bank Marketing': 16, 'diabetes_130us': 47}

Generator Dimension Validation:

Dataset                         : Adult Income
Registered Generator Input     : 128
Actual Generator Input         : 128
Registered Generator Output    : 14
Actual Generator Output        : 14
Expected GAN Feature Dimension : 14
Expected Complete Dimension    : 15
Input Dimension                : PASS
Output Dimension               : PASS
Feature Dimension              : PASS
Complete Dimension             : PASS
Overall Generator Dimension    : PASS

Dataset                         : Bank Marketing
Registered Generator Input     : 128
Actual Generator Input         : 128
Registered Generator Output    : 16
Actual Generator Output        : 16
Expected GAN Feature Dimension : 16
Expected Complete Dimension    : 17
Input Dimension                : PASS
Output Dimension               : PASS
Feature Dimension              : PASS
Complete Dimension             : PASS
Overall Generator Dimension    : PASS

Dataset                         : diabetes_130us
Registered Generator Input     : 128
Actual Generator Input         : 128
Registered Generator Output    : 47
Actual Generator Output        : 47
Expected GAN Feature Dimension : 47
Expected Complete Dimension    : 48
Input Dimension                : PASS
Output Dimension               : PASS
Feature Dimension              : PASS
Complete Dimension             : PASS
Overall Generator Dimension    : PASS

====================================================================================================
All SPP-GAN generator dimensions are internally consistent.

PART H3 — Generator validation source completed.

In [53]:
# ==============================================================================
# PART H4 — GENERATOR PARAMETER SUMMARY
# ==============================================================================

print("=" * 100)
print("PART H4 — GENERATOR PARAMETER SUMMARY")
print("=" * 100)

SPP_GAN_GENERATOR_PARAMETER_SUMMARY = []

for dataset in DATASETS:

    generator = (
        SPP_GAN_GENERATORS[dataset]
    )

    total_parameters = sum(
        parameter.numel()
        for parameter in generator.parameters()
    )

    trainable_parameters = sum(
        parameter.numel()
        for parameter in generator.parameters()
        if parameter.requires_grad
    )

    input_dimension = int(
        SPP_GAN_GENERATOR_INPUT_DIMENSIONS[
            dataset
        ]
    )

    output_dimension = int(
        SPP_GAN_GENERATOR_OUTPUT_DIMENSIONS[
            dataset
        ]
    )

    expected_feature_dimension = int(
        SPP_GAN_INPUT_DIMENSIONS[
            dataset
        ]
    )

    parameter_consistency = (
        input_dimension
        ==
        int(SPP_GAN_LATENT_DIMENSION)
        and
        output_dimension
        ==
        expected_feature_dimension
    )

    SPP_GAN_GENERATOR_PARAMETER_SUMMARY.append({

        "Dataset":
            dataset,

        "Input Dimension":
            input_dimension,

        "Output Dimension":
            output_dimension,

        "Feature Dimension":
            expected_feature_dimension,

        "Total Parameters":
            total_parameters,

        "Trainable Parameters":
            trainable_parameters,

        "Parameter Configuration Valid":
            parameter_consistency
    })

SPP_GAN_GENERATOR_PARAMETER_SUMMARY_DF = (
    pd.DataFrame(
        SPP_GAN_GENERATOR_PARAMETER_SUMMARY
    )
)

print()

display(
    SPP_GAN_GENERATOR_PARAMETER_SUMMARY_DF
)

print()

if not all(
    SPP_GAN_GENERATOR_PARAMETER_SUMMARY_DF[
        "Parameter Configuration Valid"
    ]
):

    raise ValueError(
        "SPP-GAN generator parameter configuration "
        "validation failed."
    )

print(
    "All SPP-GAN generator parameter configurations "
    "are valid."
)

print()

print(
    "PART H4 — Generator parameter summary completed."
)

====================================================================================================
PART H4 — GENERATOR PARAMETER SUMMARY
====================================================================================================

,Dataset,Input Dimension,Output Dimension,Feature Dimension,Total Parameters,Trainable Parameters,Parameter Configuration Valid
0,Adult Income,128,14,14,565262,565262,True
1,Bank Marketing,128,16,16,565776,565776,True
2,diabetes_130us,128,47,47,573743,573743,True

All SPP-GAN generator parameter configurations are valid.

PART H4 — Generator parameter summary completed.

In [54]:
# ==============================================================================
# PART H5 — GENERATOR ARCHITECTURE VALIDATION
# ==============================================================================

print("=" * 100)
print("PART H5 — GENERATOR ARCHITECTURE VALIDATION")
print("=" * 100)

SPP_GAN_GENERATOR_CHECKS = {}

for dataset in DATASETS:

    generator = SPP_GAN_GENERATORS[dataset]

    expected_output_dimension = int(
        SPP_GAN_INPUT_DIMENSIONS[dataset]
    )

    generator_input_dimension = int(
        SPP_GAN_GENERATOR_INPUT_DIMENSIONS[dataset]
    )

    # --------------------------------------------------------------------------
    # Model Parameter Validation
    # --------------------------------------------------------------------------

    total_parameters = sum(
        parameter.numel()
        for parameter in generator.parameters()
    )

    trainable_parameters = sum(
        parameter.numel()
        for parameter in generator.parameters()
        if parameter.requires_grad
    )

    parameter_shapes_valid = all(
        parameter.numel() > 0
        for parameter in generator.parameters()
    )

    # --------------------------------------------------------------------------
    # Generator Input Validation
    # --------------------------------------------------------------------------

    test_batch_size = 4

    test_noise = torch.randn(
        test_batch_size,
        generator_input_dimension,
        device=SPP_GAN_DEVICE,
        dtype=torch.float32
    )

    input_shape_valid = (
        tuple(test_noise.shape)
        ==
        (
            test_batch_size,
            generator_input_dimension
        )
    )

    input_finite_valid = bool(
        torch.isfinite(test_noise).all().item()
    )

    # --------------------------------------------------------------------------
    # Generator Forward Pass
    # --------------------------------------------------------------------------

    generator_was_training = generator.training

    generator.eval()

    with torch.no_grad():

        generated_output = generator(
            test_noise
        )

    if generator_was_training:
        generator.train()

    # --------------------------------------------------------------------------
    # Output Shape Validation
    # --------------------------------------------------------------------------

    actual_output_shape = tuple(
        generated_output.shape
    )

    expected_output_shape = (
        test_batch_size,
        expected_output_dimension
    )

    output_shape_valid = (
        actual_output_shape
        ==
        expected_output_shape
    )

    # --------------------------------------------------------------------------
    # Numerical Stability Validation
    # --------------------------------------------------------------------------

    finite_output_valid = bool(
        torch.isfinite(
            generated_output
        ).all().item()
    )

    nan_output_valid = not bool(
        torch.isnan(
            generated_output
        ).any().item()
    )

    inf_output_valid = not bool(
        torch.isinf(
            generated_output
        ).any().item()
    )

    # --------------------------------------------------------------------------
    # Output Dimensionality Validation
    # --------------------------------------------------------------------------

    output_dimension_valid = (
        generated_output.ndim == 2
        and
        generated_output.shape[1]
        ==
        expected_output_dimension
    )

    # --------------------------------------------------------------------------
    # Generator Structure Validation
    # --------------------------------------------------------------------------

    generator_structure_valid = (
        total_parameters > 0
        and
        trainable_parameters > 0
        and
        parameter_shapes_valid
    )

    # --------------------------------------------------------------------------
    # Overall Generator Validation
    # --------------------------------------------------------------------------

    generator_valid = (
        input_shape_valid
        and
        input_finite_valid
        and
        output_shape_valid
        and
        output_dimension_valid
        and
        finite_output_valid
        and
        nan_output_valid
        and
        inf_output_valid
        and
        generator_structure_valid
    )

    # --------------------------------------------------------------------------
    # Store Validation Results
    # --------------------------------------------------------------------------

    SPP_GAN_GENERATOR_CHECKS[dataset] = {

        "Generator Input Dimension":
            generator_input_dimension,

        "Expected Output Dimension":
            expected_output_dimension,

        "Actual Output Shape":
            actual_output_shape,

        "Expected Output Shape":
            expected_output_shape,

        "Total Parameters":
            total_parameters,

        "Trainable Parameters":
            trainable_parameters,

        "Input Shape Valid":
            input_shape_valid,

        "Input Finite":
            input_finite_valid,

        "Output Shape Valid":
            output_shape_valid,

        "Output Dimension Valid":
            output_dimension_valid,

        "Finite Output":
            finite_output_valid,

        "NaN-Free Output":
            nan_output_valid,

        "Inf-Free Output":
            inf_output_valid,

        "Generator Structure Valid":
            generator_structure_valid,

        "Generator Valid":
            generator_valid
    }

    # --------------------------------------------------------------------------
    # Validation Report
    # --------------------------------------------------------------------------

    print()

    print(
        f"Dataset                    : "
        f"{dataset}"
    )

    print(
        f"Generator Input Dimension  : "
        f"{generator_input_dimension}"
    )

    print(
        f"Expected Output Dimension  : "
        f"{expected_output_dimension}"
    )

    print(
        f"Actual Output Shape        : "
        f"{actual_output_shape}"
    )

    print(
        f"Expected Output Shape      : "
        f"{expected_output_shape}"
    )

    print(
        f"Total Parameters           : "
        f"{total_parameters:,}"
    )

    print(
        f"Trainable Parameters       : "
        f"{trainable_parameters:,}"
    )

    print(
        f"Input Shape Valid          : "
        f"{'PASS' if input_shape_valid else 'FAIL'}"
    )

    print(
        f"Input Finite               : "
        f"{'PASS' if input_finite_valid else 'FAIL'}"
    )

    print(
        f"Output Shape Valid         : "
        f"{'PASS' if output_shape_valid else 'FAIL'}"
    )

    print(
        f"Output Dimension Valid     : "
        f"{'PASS' if output_dimension_valid else 'FAIL'}"
    )

    print(
        f"Finite Output              : "
        f"{'PASS' if finite_output_valid else 'FAIL'}"
    )

    print(
        f"NaN-Free Output            : "
        f"{'PASS' if nan_output_valid else 'FAIL'}"
    )

    print(
        f"Inf-Free Output            : "
        f"{'PASS' if inf_output_valid else 'FAIL'}"
    )

    print(
        f"Generator Structure Valid  : "
        f"{'PASS' if generator_structure_valid else 'FAIL'}"
    )

    print(
        f"Generator Valid            : "
        f"{'PASS' if generator_valid else 'FAIL'}"
    )

# ==============================================================================
# FINAL ARCHITECTURE VALIDATION
# ==============================================================================

print()

all_generators_valid = all(
    checks["Generator Valid"]
    for checks in SPP_GAN_GENERATOR_CHECKS.values()
)

if not all_generators_valid:

    failed_datasets = [
        dataset
        for dataset, checks
        in SPP_GAN_GENERATOR_CHECKS.items()
        if not checks["Generator Valid"]
    ]

    raise ValueError(
        "SPP-GAN generator architecture validation failed for: "
        f"{failed_datasets}"
    )

print(
    "All SPP-GAN generator architecture checks passed."
)

print()

print(
    "PART H5 — Generator architecture validation completed."
)

====================================================================================================
PART H5 — GENERATOR ARCHITECTURE VALIDATION
====================================================================================================

Dataset                    : Adult Income
Generator Input Dimension  : 128
Expected Output Dimension  : 14
Actual Output Shape        : (4, 14)
Expected Output Shape      : (4, 14)
Total Parameters           : 565,262
Trainable Parameters       : 565,262
Input Shape Valid          : PASS
Input Finite               : PASS
Output Shape Valid         : PASS
Output Dimension Valid     : PASS
Finite Output              : PASS
NaN-Free Output            : PASS
Inf-Free Output            : PASS
Generator Structure Valid  : PASS
Generator Valid            : PASS

Dataset                    : Bank Marketing
Generator Input Dimension  : 128
Expected Output Dimension  : 16
Actual Output Shape        : (4, 16)
Expected Output Shape      : (4, 16)
Total Parameters           : 565,776
Trainable Parameters       : 565,776
Input Shape Valid          : PASS
Input Finite               : PASS
Output Shape Valid         : PASS
Output Dimension Valid     : PASS
Finite Output              : PASS
NaN-Free Output            : PASS
Inf-Free Output            : PASS
Generator Structure Valid  : PASS
Generator Valid            : PASS

Dataset                    : diabetes_130us
Generator Input Dimension  : 128
Expected Output Dimension  : 47
Actual Output Shape        : (4, 47)
Expected Output Shape      : (4, 47)
Total Parameters           : 573,743
Trainable Parameters       : 573,743
Input Shape Valid          : PASS
Input Finite               : PASS
Output Shape Valid         : PASS
Output Dimension Valid     : PASS
Finite Output              : PASS
NaN-Free Output            : PASS
Inf-Free Output            : PASS
Generator Structure Valid  : PASS
Generator Valid            : PASS

All SPP-GAN generator architecture checks passed.

PART H5 — Generator architecture validation completed.

In [55]:
# ==============================================================================
# PART H6 — GENERATOR ARCHITECTURE SUMMARY
# ==============================================================================

print("=" * 100)
print("PART H6 — GENERATOR ARCHITECTURE SUMMARY")
print("=" * 100)

# ==============================================================================
# GENERATOR ARCHITECTURE VALIDATION STATUS
# ==============================================================================

SPP_GAN_ARCHITECTURE_VALID = all(
    checks["Generator Valid"]
    for checks in SPP_GAN_GENERATOR_CHECKS.values()
)

# ==============================================================================
# DATASET-SPECIFIC DIMENSION VALIDATION
# ==============================================================================

SPP_GAN_GENERATOR_DIMENSION_CHECKS = {}

for dataset in DATASETS:

    generator_output_dimension = int(
        SPP_GAN_GENERATOR_OUTPUT_DIMENSIONS[dataset]
    )

    gan_feature_dimension = int(
        SPP_GAN_INPUT_DIMENSIONS[dataset]
    )

    complete_dataset_dimension = int(
        SPP_GAN_OUTPUT_DIMENSIONS[dataset]
    )

    dimension_consistent = (
        generator_output_dimension
        ==
        gan_feature_dimension
    )

    SPP_GAN_GENERATOR_DIMENSION_CHECKS[dataset] = {

        "Generator Output Dimension":
            generator_output_dimension,

        "GAN Feature Dimension":
            gan_feature_dimension,

        "Complete Dataset Dimension":
            complete_dataset_dimension,

        "Dimension Consistent":
            dimension_consistent
    }

SPP_GAN_GENERATOR_DIMENSION_SUMMARY_VALID = all(
    checks["Dimension Consistent"]
    for checks
    in SPP_GAN_GENERATOR_DIMENSION_CHECKS.values()
)

# ==============================================================================
# GENERATOR ARCHITECTURE SUMMARY
# ==============================================================================

SPP_GAN_GENERATOR_SUMMARY = {

    "Architecture":
        "Fully Connected Generator",

    "Input Dimension":
        SPP_GAN_GENERATOR_INPUT_DIMENSIONS,

    "Hidden Dimensions":
        SPP_GAN_GENERATOR_HIDDEN_DIMENSIONS,

    "Hidden Activation":
        SPP_GAN_GENERATOR_ACTIVATION,

    "Output Activation":
        SPP_GAN_GENERATOR_OUTPUT_ACTIVATION,

    "Number of Datasets":
        len(DATASETS),

    "Dataset-Specific Generators":
        True,

    "Generator Output Dimensions":
        SPP_GAN_GENERATOR_OUTPUT_DIMENSIONS,

    "GAN Feature Dimensions":
        SPP_GAN_INPUT_DIMENSIONS,

    "Complete Dataset Dimensions":
        SPP_GAN_OUTPUT_DIMENSIONS,

    "Device":
        str(SPP_GAN_DEVICE),

    "Architecture Validation":
        SPP_GAN_ARCHITECTURE_VALID,

    "Dimension Validation":
        SPP_GAN_GENERATOR_DIMENSION_SUMMARY_VALID
}

SPP_GAN_GENERATOR_SUMMARY_DF = pd.DataFrame(
    list(
        SPP_GAN_GENERATOR_SUMMARY.items()
    ),
    columns=[
        "Parameter",
        "Value"
    ]
)

print()

display(
    SPP_GAN_GENERATOR_SUMMARY_DF
)

# ==============================================================================
# DATASET-SPECIFIC GENERATOR DIMENSION SUMMARY
# ==============================================================================

print()

print(
    "Dataset-Specific Generator Dimension Summary"
)

SPP_GAN_GENERATOR_DIMENSION_SUMMARY_ROWS = []

for dataset in DATASETS:

    checks = (
        SPP_GAN_GENERATOR_DIMENSION_CHECKS[
            dataset
        ]
    )

    SPP_GAN_GENERATOR_DIMENSION_SUMMARY_ROWS.append({

        "Dataset":
            dataset,

        "Generator Output Dimension":
            checks[
                "Generator Output Dimension"
            ],

        "GAN Feature Dimension":
            checks[
                "GAN Feature Dimension"
            ],

        "Complete Dataset Dimension":
            checks[
                "Complete Dataset Dimension"
            ],

        "Dimension Consistent":
            checks[
                "Dimension Consistent"
            ]
    })

SPP_GAN_GENERATOR_DIMENSION_SUMMARY_DF = pd.DataFrame(
    SPP_GAN_GENERATOR_DIMENSION_SUMMARY_ROWS
)

print()

display(
    SPP_GAN_GENERATOR_DIMENSION_SUMMARY_DF
)

# ==============================================================================
# DATASET-SPECIFIC VALIDATION REPORT
# ==============================================================================

print()

for dataset in DATASETS:

    checks = (
        SPP_GAN_GENERATOR_DIMENSION_CHECKS[
            dataset
        ]
    )

    print()

    print(
        f"Dataset                  : "
        f"{dataset}"
    )

    print(
        f"Generator Output         : "
        f"{checks['Generator Output Dimension']}"
    )

    print(
        f"GAN Feature Dimension    : "
        f"{checks['GAN Feature Dimension']}"
    )

    print(
        f"Complete Dataset         : "
        f"{checks['Complete Dataset Dimension']}"
    )

    print(
        f"Dimension Consistency    : "
        f"{'PASS' if checks['Dimension Consistent'] else 'FAIL'}"
    )

# ==============================================================================
# FINAL GENERATOR ARCHITECTURE STATUS
# ==============================================================================

SPP_GAN_GENERATOR_FINAL_STATUS = (
    SPP_GAN_ARCHITECTURE_VALID
    and
    SPP_GAN_GENERATOR_DIMENSION_SUMMARY_VALID
)

print()

print(
    f"Architecture Validation   : "
    f"{'PASS' if SPP_GAN_ARCHITECTURE_VALID else 'FAIL'}"
)

print(
    f"Dimension Validation       : "
    f"{'PASS' if SPP_GAN_GENERATOR_DIMENSION_SUMMARY_VALID else 'FAIL'}"
)

print()

print(
    f"Overall Generator Status  : "
    f"{'PASS' if SPP_GAN_GENERATOR_FINAL_STATUS else 'FAIL'}"
)

# ==============================================================================
# FAIL-FAST RESEARCH PIPELINE CHECK
# ==============================================================================

if not SPP_GAN_GENERATOR_FINAL_STATUS:

    failed_architecture_datasets = [
        dataset
        for dataset, checks
        in SPP_GAN_GENERATOR_CHECKS.items()
        if not checks["Generator Valid"]
    ]

    failed_dimension_datasets = [
        dataset
        for dataset, checks
        in SPP_GAN_GENERATOR_DIMENSION_CHECKS.items()
        if not checks["Dimension Consistent"]
    ]

    raise ValueError(
        "SPP-GAN generator architecture summary validation failed.\n"
        f"Architecture failures: {failed_architecture_datasets}\n"
        f"Dimension failures: {failed_dimension_datasets}"
    )

print()

print(
    "PART H6 — Generator architecture summary completed."
)

====================================================================================================
PART H6 — GENERATOR ARCHITECTURE SUMMARY
====================================================================================================

,Parameter,Value
0,Architecture,Fully Connected Generator
1,Input Dimension,"{'Adult Income': 128, 'Bank Marketing': 128, '..."
2,Hidden Dimensions,"[256, 512, 512, 256]"
3,Hidden Activation,LeakyReLU
4,Output Activation,Linear
5,Number of Datasets,3
6,Dataset-Specific Generators,True
7,Generator Output Dimensions,"{'Adult Income': 14, 'Bank Marketing': 16, 'di..."
8,GAN Feature Dimensions,"{'Adult Income': 14, 'Bank Marketing': 16, 'di..."
9,Complete Dataset Dimensions,"{'Adult Income': 15, 'Bank Marketing': 17, 'di..."
10,Device,cpu
11,Architecture Validation,True
12,Dimension Validation,True

Dataset-Specific Generator Dimension Summary

,Dataset,Generator Output Dimension,GAN Feature Dimension,Complete Dataset Dimension,Dimension Consistent
0,Adult Income,14,14,15,True
1,Bank Marketing,16,16,17,True
2,diabetes_130us,47,47,48,True

Dataset                  : Adult Income
Generator Output         : 14
GAN Feature Dimension    : 14
Complete Dataset         : 15
Dimension Consistency    : PASS

Dataset                  : Bank Marketing
Generator Output         : 16
GAN Feature Dimension    : 16
Complete Dataset         : 17
Dimension Consistency    : PASS

Dataset                  : diabetes_130us
Generator Output         : 47
GAN Feature Dimension    : 47
Complete Dataset         : 48
Dimension Consistency    : PASS

Architecture Validation   : PASS
Dimension Validation       : PASS

Overall Generator Status  : PASS

PART H6 — Generator architecture summary completed.

In [134]:
# ==============================================================================
# PART I1 — SPP-GAN DIMENSION AND ARCHITECTURE CONFIGURATION
# ==============================================================================

print("=" * 100)
print("PART I1 — SPP-GAN DIMENSION AND ARCHITECTURE CONFIGURATION")
print("=" * 100)

# ==============================================================================
# DATASET DIMENSION DEFINITIONS
# ==============================================================================

SPP_GAN_FULL_DATASET_DIMENSIONS = {
    "Adult Income": 15,
    "Bank Marketing": 17,
    "diabetes_130us": 48
}

SPP_GAN_TARGET_DIMENSIONS = {
    "Adult Income": 1,
    "Bank Marketing": 1,
    "diabetes_130us": 1
}

# ------------------------------------------------------------------------------
# IMPORTANT:
# The SPP-GAN operates on feature tensors excluding the target variable.
# Therefore:
#
# Adult Income       : 15 - 1 = 14
# Bank Marketing     : 17 - 1 = 16
# diabetes_130us     : 48 - 1 = 47
# ------------------------------------------------------------------------------

SPP_GAN_INPUT_DIMENSIONS = {
    dataset:
        int(
            SPP_GAN_FULL_DATASET_DIMENSIONS[dataset]
            -
            SPP_GAN_TARGET_DIMENSIONS[dataset]
        )
    for dataset in DATASETS
}

# Generator output is the same as the GAN feature dimension.
SPP_GAN_OUTPUT_DIMENSIONS = {
    dataset:
        SPP_GAN_INPUT_DIMENSIONS[dataset]
    for dataset in DATASETS
}

# Discriminator input must exactly equal generator output.
SPP_GAN_DISCRIMINATOR_INPUT_DIMENSIONS = {
    dataset:
        SPP_GAN_OUTPUT_DIMENSIONS[dataset]
    for dataset in DATASETS
}

# ==============================================================================
# GENERATOR CONFIGURATION
# ==============================================================================

SPP_GAN_GENERATOR_INPUT_DIMENSION = int(
    PROJECT_CONFIG.get(
        "latent_dimension",
        128
    )
)

SPP_GAN_GENERATOR_HIDDEN_DIMENSIONS = (
    256,
    256
)

SPP_GAN_GENERATOR_ACTIVATION = (
    "LeakyReLU"
)

SPP_GAN_GENERATOR_OUTPUT_ACTIVATION = (
    "Linear"
)

SPP_GAN_GENERATOR_DROPOUT = 0.0

# ==============================================================================
# DISCRIMINATOR CONFIGURATION
# ==============================================================================

SPP_GAN_DISCRIMINATOR_HIDDEN_DIMENSIONS = (
    256,
    128
)

SPP_GAN_DISCRIMINATOR_ACTIVATION = (
    "LeakyReLU"
)

SPP_GAN_DISCRIMINATOR_OUTPUT_DIMENSION = 1

SPP_GAN_DISCRIMINATOR_OUTPUT_ACTIVATION = (
    "Linear"
)

SPP_GAN_DISCRIMINATOR_DROPOUT = 0.20

# ==============================================================================
# DEVICE
# ==============================================================================

SPP_GAN_DEVICE = torch.device(
    "cuda"
    if torch.cuda.is_available()
    else "cpu"
)

# ==============================================================================
# CONFIGURATION VALIDATION
# ==============================================================================

SPP_GAN_DIMENSION_CONFIGURATION_CHECKS = {}

for dataset in DATASETS:

    full_dimension = (
        SPP_GAN_FULL_DATASET_DIMENSIONS[dataset]
    )

    target_dimension = (
        SPP_GAN_TARGET_DIMENSIONS[dataset]
    )

    feature_dimension = (
        SPP_GAN_INPUT_DIMENSIONS[dataset]
    )

    output_dimension = (
        SPP_GAN_OUTPUT_DIMENSIONS[dataset]
    )

    discriminator_dimension = (
        SPP_GAN_DISCRIMINATOR_INPUT_DIMENSIONS[dataset]
    )

    checks = {
        "Full Dimension Valid":
            full_dimension > 0,

        "Target Dimension Valid":
            target_dimension > 0,

        "Feature Dimension Valid":
            feature_dimension > 0,

        "Dimension Arithmetic Valid":
            full_dimension
            ==
            target_dimension + feature_dimension,

        "Generator Output Valid":
            output_dimension == feature_dimension,

        "Discriminator Input Valid":
            discriminator_dimension == output_dimension
    }

    SPP_GAN_DIMENSION_CONFIGURATION_CHECKS[dataset] = checks

# ==============================================================================
# REPORT
# ==============================================================================

print()

for dataset in DATASETS:

    print(
        f"Dataset                    : {dataset}"
    )

    print(
        f"Full Dataset Dimension     : "
        f"{SPP_GAN_FULL_DATASET_DIMENSIONS[dataset]}"
    )

    print(
        f"Target Dimension           : "
        f"{SPP_GAN_TARGET_DIMENSIONS[dataset]}"
    )

    print(
        f"SPP-GAN Feature Dimension  : "
        f"{SPP_GAN_INPUT_DIMENSIONS[dataset]}"
    )

    print(
        f"Generator Output Dimension : "
        f"{SPP_GAN_OUTPUT_DIMENSIONS[dataset]}"
    )

    print(
        f"Discriminator Input       : "
        f"{SPP_GAN_DISCRIMINATOR_INPUT_DIMENSIONS[dataset]}"
    )

    print()

print(
    f"Generator Latent Dimension  : "
    f"{SPP_GAN_GENERATOR_INPUT_DIMENSION}"
)

print(
    f"Generator Hidden Dimensions : "
    f"{SPP_GAN_GENERATOR_HIDDEN_DIMENSIONS}"
)

print(
    f"Discriminator Hidden Dim.   : "
    f"{SPP_GAN_DISCRIMINATOR_HIDDEN_DIMENSIONS}"
)

print(
    f"Device                      : "
    f"{SPP_GAN_DEVICE}"
)

print()

if not all(
    all(checks.values())
    for checks
    in SPP_GAN_DIMENSION_CONFIGURATION_CHECKS.values()
):

    raise ValueError(
        "SPP-GAN dimension configuration validation failed."
    )

print(
    "All SPP-GAN dimension configuration checks passed."
)

print()

print(
    "IMPORTANT: Target variables are excluded from the "
    "GAN feature vector and handled separately."
)

print()

print(
    "PART I1 — SPP-GAN dimension and architecture "
    "configuration completed."
)

====================================================================================================
PART I1 — SPP-GAN DIMENSION AND ARCHITECTURE CONFIGURATION
====================================================================================================

Dataset                    : Adult Income
Full Dataset Dimension     : 15
Target Dimension           : 1
SPP-GAN Feature Dimension  : 14
Generator Output Dimension : 14
Discriminator Input       : 14

Dataset                    : Bank Marketing
Full Dataset Dimension     : 17
Target Dimension           : 1
SPP-GAN Feature Dimension  : 16
Generator Output Dimension : 16
Discriminator Input       : 16

Dataset                    : diabetes_130us
Full Dataset Dimension     : 48
Target Dimension           : 1
SPP-GAN Feature Dimension  : 47
Generator Output Dimension : 47
Discriminator Input       : 47

Generator Latent Dimension  : 128
Generator Hidden Dimensions : (256, 256)
Discriminator Hidden Dim.   : (256, 128)
Device                      : cpu

All SPP-GAN dimension configuration checks passed.

IMPORTANT: Target variables are excluded from the GAN feature vector and handled separately.

PART I1 — SPP-GAN dimension and architecture configuration completed.

In [135]:
# ==============================================================================
# PART I2 — SPP-GAN GENERATOR ARCHITECTURE
# ==============================================================================

print("=" * 100)
print("PART I2 — SPP-GAN GENERATOR ARCHITECTURE")
print("=" * 100)

# ==============================================================================
# GENERATOR CLASS
# ==============================================================================

class SPPGANGenerator(nn.Module):

    def __init__(
        self,
        input_dimension,
        output_dimension,
        hidden_dimensions=(256, 256),
        dropout=0.0
    ):

        super().__init__()

        layers = []

        previous_dimension = int(
            input_dimension
        )

        for hidden_dimension in hidden_dimensions:

            hidden_dimension = int(
                hidden_dimension
            )

            layers.append(
                nn.Linear(
                    previous_dimension,
                    hidden_dimension
                )
            )

            layers.append(
                nn.LayerNorm(
                    hidden_dimension
                )
            )

            layers.append(
                nn.LeakyReLU(
                    negative_slope=0.2,
                    inplace=False
                )
            )

            if dropout > 0.0:

                layers.append(
                    nn.Dropout(
                        p=float(dropout)
                    )
                )

            previous_dimension = (
                hidden_dimension
            )

        layers.append(
            nn.Linear(
                previous_dimension,
                int(output_dimension)
            )
        )

        self.network = nn.Sequential(
            *layers
        )

        self.input_dimension = int(
            input_dimension
        )

        self.output_dimension = int(
            output_dimension
        )

    def forward(self, noise):

        if noise.ndim != 2:

            raise ValueError(
                "Generator input must be a "
                "2-dimensional tensor."
            )

        if noise.shape[1] != self.input_dimension:

            raise ValueError(
                "Generator input dimension mismatch: "
                f"expected {self.input_dimension}, "
                f"got {noise.shape[1]}"
            )

        return self.network(
            noise
        )


# ==============================================================================
# WEIGHT INITIALIZATION
# ==============================================================================

def spp_gan_initialize_weights(model):

    for module in model.modules():

        if isinstance(
            module,
            nn.Linear
        ):

            nn.init.xavier_uniform_(
                module.weight
            )

            if module.bias is not None:

                nn.init.zeros_(
                    module.bias
                )


# ==============================================================================
# GENERATOR CREATION
# ==============================================================================

SPP_GAN_GENERATORS = {}

for dataset in DATASETS:

    generator = SPPGANGenerator(
        input_dimension=(
            SPP_GAN_GENERATOR_INPUT_DIMENSION
        ),
        output_dimension=(
            SPP_GAN_OUTPUT_DIMENSIONS[dataset]
        ),
        hidden_dimensions=(
            SPP_GAN_GENERATOR_HIDDEN_DIMENSIONS
        ),
        dropout=(
            SPP_GAN_GENERATOR_DROPOUT
        )
    )

    spp_gan_initialize_weights(
        generator
    )

    generator = generator.to(
        SPP_GAN_DEVICE
    )

    generator.eval()

    SPP_GAN_GENERATORS[dataset] = (
        generator
    )

# ==============================================================================
# GENERATOR REPORT
# ==============================================================================

print()

for dataset in DATASETS:

    generator = (
        SPP_GAN_GENERATORS[dataset]
    )

    print(
        f"Dataset                    : {dataset}"
    )

    print(
        f"Generator Input Dimension  : "
        f"{generator.input_dimension}"
    )

    print(
        f"Generator Output Dimension : "
        f"{generator.output_dimension}"
    )

    print(
        f"Device                     : "
        f"{next(generator.parameters()).device}"
    )

    print()

print(
    f"Generators Created          : "
    f"{len(SPP_GAN_GENERATORS)}"
)

print()

print(
    "PART I2 — SPP-GAN generator architecture completed."
)

====================================================================================================
PART I2 — SPP-GAN GENERATOR ARCHITECTURE
====================================================================================================

Dataset                    : Adult Income
Generator Input Dimension  : 128
Generator Output Dimension : 14
Device                     : cpu

Dataset                    : Bank Marketing
Generator Input Dimension  : 128
Generator Output Dimension : 16
Device                     : cpu

Dataset                    : diabetes_130us
Generator Input Dimension  : 128
Generator Output Dimension : 47
Device                     : cpu

Generators Created          : 3

PART I2 — SPP-GAN generator architecture completed.

In [136]:
# ==============================================================================
# PART I3 — SPP-GAN DISCRIMINATOR ARCHITECTURE
# ==============================================================================

print("=" * 100)
print("PART I3 — SPP-GAN DISCRIMINATOR ARCHITECTURE")
print("=" * 100)

# ==============================================================================
# DISCRIMINATOR CLASS
# ==============================================================================

class SPPGANDiscriminator(nn.Module):

    def __init__(
        self,
        input_dimension,
        hidden_dimensions=(256, 128),
        dropout=0.20
    ):

        super().__init__()

        layers = []

        previous_dimension = int(
            input_dimension
        )

        for hidden_dimension in hidden_dimensions:

            hidden_dimension = int(
                hidden_dimension
            )

            layers.append(
                nn.Linear(
                    previous_dimension,
                    hidden_dimension
                )
            )

            layers.append(
                nn.LayerNorm(
                    hidden_dimension
                )
            )

            layers.append(
                nn.LeakyReLU(
                    negative_slope=0.2,
                    inplace=False
                )
            )

            if dropout > 0.0:

                layers.append(
                    nn.Dropout(
                        p=float(dropout)
                    )
                )

            previous_dimension = (
                hidden_dimension
            )

        layers.append(
            nn.Linear(
                previous_dimension,
                SPP_GAN_DISCRIMINATOR_OUTPUT_DIMENSION
            )
        )

        self.network = nn.Sequential(
            *layers
        )

        self.input_dimension = int(
            input_dimension
        )

        self.output_dimension = int(
            SPP_GAN_DISCRIMINATOR_OUTPUT_DIMENSION
        )

    def forward(self, features):

        if features.ndim != 2:

            raise ValueError(
                "Discriminator input must be "
                "a 2-dimensional tensor."
            )

        if features.shape[1] != self.input_dimension:

            raise ValueError(
                "Discriminator input dimension mismatch: "
                f"expected {self.input_dimension}, "
                f"got {features.shape[1]}"
            )

        return self.network(
            features
        )


# ==============================================================================
# DISCRIMINATOR CREATION
# ==============================================================================

SPP_GAN_DISCRIMINATORS = {}

for dataset in DATASETS:

    discriminator_input_dimension = (
        SPP_GAN_DISCRIMINATOR_INPUT_DIMENSIONS[
            dataset
        ]
    )

    discriminator = SPPGANDiscriminator(
        input_dimension=(
            discriminator_input_dimension
        ),
        hidden_dimensions=(
            SPP_GAN_DISCRIMINATOR_HIDDEN_DIMENSIONS
        ),
        dropout=(
            SPP_GAN_DISCRIMINATOR_DROPOUT
        )
    )

    spp_gan_initialize_weights(
        discriminator
    )

    discriminator = discriminator.to(
        SPP_GAN_DEVICE
    )

    discriminator.train()

    SPP_GAN_DISCRIMINATORS[dataset] = (
        discriminator
    )

# ==============================================================================
# DISCRIMINATOR REPORT
# ==============================================================================

print()

for dataset in DATASETS:

    discriminator = (
        SPP_GAN_DISCRIMINATORS[dataset]
    )

    print(
        f"Dataset                    : {dataset}"
    )

    print(
        f"Discriminator Input        : "
        f"{discriminator.input_dimension}"
    )

    print(
        f"Discriminator Output       : "
        f"{discriminator.output_dimension}"
    )

    print(
        f"Device                     : "
        f"{next(discriminator.parameters()).device}"
    )

    print()

print(
    f"Discriminators Created      : "
    f"{len(SPP_GAN_DISCRIMINATORS)}"
)

print()

print(
    "PART I3 — SPP-GAN discriminator architecture completed."
)

====================================================================================================
PART I3 — SPP-GAN DISCRIMINATOR ARCHITECTURE
====================================================================================================

Dataset                    : Adult Income
Discriminator Input        : 14
Discriminator Output       : 1
Device                     : cpu

Dataset                    : Bank Marketing
Discriminator Input        : 16
Discriminator Output       : 1
Device                     : cpu

Dataset                    : diabetes_130us
Discriminator Input        : 47
Discriminator Output       : 1
Device                     : cpu

Discriminators Created      : 3

PART I3 — SPP-GAN discriminator architecture completed.

In [137]:
# ==============================================================================
# PART I4 — GENERATOR AND DISCRIMINATOR PARAMETER SUMMARY
# ==============================================================================

print("=" * 100)
print("PART I4 — GENERATOR AND DISCRIMINATOR PARAMETER SUMMARY")
print("=" * 100)

SPP_GAN_ARCHITECTURE_PARAMETER_SUMMARY = []

for dataset in DATASETS:

    generator = (
        SPP_GAN_GENERATORS[dataset]
    )

    discriminator = (
        SPP_GAN_DISCRIMINATORS[dataset]
    )

    generator_total_parameters = sum(
        parameter.numel()
        for parameter
        in generator.parameters()
    )

    generator_trainable_parameters = sum(
        parameter.numel()
        for parameter
        in generator.parameters()
        if parameter.requires_grad
    )

    discriminator_total_parameters = sum(
        parameter.numel()
        for parameter
        in discriminator.parameters()
    )

    discriminator_trainable_parameters = sum(
        parameter.numel()
        for parameter
        in discriminator.parameters()
        if parameter.requires_grad
    )

    SPP_GAN_ARCHITECTURE_PARAMETER_SUMMARY.append({

        "Dataset":
            dataset,

        "Generator Input":
            int(
                generator.input_dimension
            ),

        "Generator Output":
            int(
                generator.output_dimension
            ),

        "Generator Total Parameters":
            int(
                generator_total_parameters
            ),

        "Generator Trainable Parameters":
            int(
                generator_trainable_parameters
            ),

        "Discriminator Input":
            int(
                discriminator.input_dimension
            ),

        "Discriminator Output":
            int(
                discriminator.output_dimension
            ),

        "Discriminator Total Parameters":
            int(
                discriminator_total_parameters
            ),

        "Discriminator Trainable Parameters":
            int(
                discriminator_trainable_parameters
            )
    })

SPP_GAN_ARCHITECTURE_PARAMETER_SUMMARY_DF = pd.DataFrame(
    SPP_GAN_ARCHITECTURE_PARAMETER_SUMMARY
)

print()

display(
    SPP_GAN_ARCHITECTURE_PARAMETER_SUMMARY_DF
)

print()

print(
    "PART I4 — Generator and discriminator parameter "
    "summary completed."
)

====================================================================================================
PART I4 — GENERATOR AND DISCRIMINATOR PARAMETER SUMMARY
====================================================================================================

,Dataset,Generator Input,Generator Output,Generator Total Parameters,Generator Trainable Parameters,Discriminator Input,Discriminator Output,Discriminator Total Parameters,Discriminator Trainable Parameters
0,Adult Income,128,14,103438,103438,14,1,37633,37633
1,Bank Marketing,128,16,103952,103952,16,1,38145,38145
2,diabetes_130us,128,47,111919,111919,47,1,46081,46081

PART I4 — Generator and discriminator parameter summary completed.

In [138]:
# ==============================================================================
# PART I5 — GENERATOR OUTPUT AND DISCRIMINATOR INPUT CONSISTENCY
# ==============================================================================

print("=" * 100)
print("PART I5 — GENERATOR OUTPUT AND DISCRIMINATOR INPUT CONSISTENCY")
print("=" * 100)

SPP_GAN_ARCHITECTURE_CHECKS = {}

for dataset in DATASETS:

    generator = (
        SPP_GAN_GENERATORS[dataset]
    )

    discriminator = (
        SPP_GAN_DISCRIMINATORS[dataset]
    )

    generator_input_dimension = int(
        generator.input_dimension
    )

    generator_output_dimension = int(
        generator.output_dimension
    )

    discriminator_input_dimension = int(
        discriminator.input_dimension
    )

    discriminator_output_dimension = int(
        discriminator.output_dimension
    )

    expected_feature_dimension = int(
        SPP_GAN_INPUT_DIMENSIONS[dataset]
    )

    checks = {

        "Generator Input Valid":
            generator_input_dimension
            ==
            SPP_GAN_GENERATOR_INPUT_DIMENSION,

        "Generator Output Valid":
            generator_output_dimension
            ==
            expected_feature_dimension,

        "Discriminator Input Valid":
            discriminator_input_dimension
            ==
            expected_feature_dimension,

        "Generator-Discriminator Dimension Match":
            generator_output_dimension
            ==
            discriminator_input_dimension,

        "Discriminator Output Valid":
            discriminator_output_dimension
            ==
            1
    }

    SPP_GAN_ARCHITECTURE_CHECKS[dataset] = (
        checks
    )

    print()

    print(
        f"Dataset                    : {dataset}"
    )

    print(
        f"Expected Feature Dimension : "
        f"{expected_feature_dimension}"
    )

    print(
        f"Generator Input Dimension  : "
        f"{generator_input_dimension}"
    )

    print(
        f"Generator Output Dimension : "
        f"{generator_output_dimension}"
    )

    print(
        f"Discriminator Input        : "
        f"{discriminator_input_dimension}"
    )

    print(
        f"Discriminator Output       : "
        f"{discriminator_output_dimension}"
    )

    print()

    for check_name, status in checks.items():

        print(
            f"{check_name:40s}: "
            f"{'PASS' if status else 'FAIL'}"
        )

# ==============================================================================
# GLOBAL VALIDATION
# ==============================================================================

SPP_GAN_ARCHITECTURE_VALID = all(
    all(checks.values())
    for checks
    in SPP_GAN_ARCHITECTURE_CHECKS.values()
)

print()

print(
    f"Overall Architecture Validation : "
    f"{'PASS' if SPP_GAN_ARCHITECTURE_VALID else 'FAIL'}"
)

if not SPP_GAN_ARCHITECTURE_VALID:

    failed_datasets = [
        dataset
        for dataset, checks
        in SPP_GAN_ARCHITECTURE_CHECKS.items()
        if not all(checks.values())
    ]

    raise ValueError(
        "SPP-GAN architecture dimension validation failed "
        f"for datasets: {failed_datasets}"
    )

print()

print(
    "Generator output dimensions and discriminator input "
    "dimensions are fully synchronized."
)

print()

print(
    "PART I5 — Generator output and discriminator input "
    "consistency completed."
)

====================================================================================================
PART I5 — GENERATOR OUTPUT AND DISCRIMINATOR INPUT CONSISTENCY
====================================================================================================

Dataset                    : Adult Income
Expected Feature Dimension : 14
Generator Input Dimension  : 128
Generator Output Dimension : 14
Discriminator Input        : 14
Discriminator Output       : 1

Generator Input Valid                   : PASS
Generator Output Valid                  : PASS
Discriminator Input Valid               : PASS
Generator-Discriminator Dimension Match : PASS
Discriminator Output Valid              : PASS

Dataset                    : Bank Marketing
Expected Feature Dimension : 16
Generator Input Dimension  : 128
Generator Output Dimension : 16
Discriminator Input        : 16
Discriminator Output       : 1

Generator Input Valid                   : PASS
Generator Output Valid                  : PASS
Discriminator Input Valid               : PASS
Generator-Discriminator Dimension Match : PASS
Discriminator Output Valid              : PASS

Dataset                    : diabetes_130us
Expected Feature Dimension : 47
Generator Input Dimension  : 128
Generator Output Dimension : 47
Discriminator Input        : 47
Discriminator Output       : 1

Generator Input Valid                   : PASS
Generator Output Valid                  : PASS
Discriminator Input Valid               : PASS
Generator-Discriminator Dimension Match : PASS
Discriminator Output Valid              : PASS

Overall Architecture Validation : PASS

Generator output dimensions and discriminator input dimensions are fully synchronized.

PART I5 — Generator output and discriminator input consistency completed.

In [139]:
# ==============================================================================
# PART I6 — GENERATOR-DISCRIMINATOR FORWARD COMPATIBILITY TEST
# ==============================================================================

print("=" * 100)
print("PART I6 — GENERATOR-DISCRIMINATOR FORWARD COMPATIBILITY TEST")
print("=" * 100)

SPP_GAN_GD_COMPATIBILITY_CHECKS = {}

for dataset in DATASETS:

    generator = (
        SPP_GAN_GENERATORS[dataset]
    )

    discriminator = (
        SPP_GAN_DISCRIMINATORS[dataset]
    )

    # --------------------------------------------------------------------------
    # STORE ORIGINAL MODES
    # --------------------------------------------------------------------------

    generator_training_mode = (
        generator.training
    )

    discriminator_training_mode = (
        discriminator.training
    )

    # --------------------------------------------------------------------------
    # EVALUATION MODE
    # --------------------------------------------------------------------------

    generator.eval()
    discriminator.eval()

    # --------------------------------------------------------------------------
    # GENERATOR INPUT
    # --------------------------------------------------------------------------

    batch_size = 4

    noise = torch.randn(
        batch_size,
        SPP_GAN_GENERATOR_INPUT_DIMENSION,
        device=SPP_GAN_DEVICE
    )

    # --------------------------------------------------------------------------
    # GENERATOR FORWARD PASS
    # --------------------------------------------------------------------------

    with torch.no_grad():

        generated_features = (
            generator(
                noise
            )
        )

        generated_dimension = int(
            generated_features.shape[1]
        )

        expected_dimension = int(
            SPP_GAN_OUTPUT_DIMENSIONS[dataset]
        )

        generator_output_valid = (
            generated_dimension
            ==
            expected_dimension
        )

        # ----------------------------------------------------------------------
        # DISCRIMINATOR FORWARD PASS
        # ----------------------------------------------------------------------

        discriminator_output = (
            discriminator(
                generated_features
            )
        )

        discriminator_input_dimension = int(
            generated_features.shape[1]
        )

        discriminator_output_dimension = int(
            discriminator_output.shape[1]
        )

    discriminator_input_valid = (
        discriminator_input_dimension
        ==
        discriminator.input_dimension
    )

    discriminator_output_valid = (
        discriminator_output_dimension
        ==
        1
    )

    compatibility_valid = (
        generator_output_valid
        and
        discriminator_input_valid
        and
        discriminator_output_valid
    )

    SPP_GAN_GD_COMPATIBILITY_CHECKS[dataset] = {

        "Generator Output Valid":
            generator_output_valid,

        "Discriminator Input Valid":
            discriminator_input_valid,

        "Discriminator Output Valid":
            discriminator_output_valid,

        "Compatibility Valid":
            compatibility_valid
    }

    print()

    print(
        f"Dataset                    : {dataset}"
    )

    print(
        f"Generator Input Dimension  : "
        f"{SPP_GAN_GENERATOR_INPUT_DIMENSION}"
    )

    print(
        f"Generator Output Dimension : "
        f"{generated_dimension}"
    )

    print(
        f"Discriminator Input        : "
        f"{discriminator.input_dimension}"
    )

    print(
        f"Discriminator Output       : "
        f"{discriminator_output_dimension}"
    )

    print()

    print(
        f"Generator Output           : "
        f"{'PASS' if generator_output_valid else 'FAIL'}"
    )

    print(
        f"Discriminator Input        : "
        f"{'PASS' if discriminator_input_valid else 'FAIL'}"
    )

    print(
        f"Discriminator Output       : "
        f"{'PASS' if discriminator_output_valid else 'FAIL'}"
    )

    print(
        f"Generator → Discriminator  : "
        f"{'PASS' if compatibility_valid else 'FAIL'}"
    )

    print(
        f"Architecture Status        : "
        f"{'PASS' if compatibility_valid else 'FAIL'}"
    )

    # --------------------------------------------------------------------------
    # RESTORE MODES
    # --------------------------------------------------------------------------

    generator.train(
        generator_training_mode
    )

    discriminator.train(
        discriminator_training_mode
    )

# ==============================================================================
# GLOBAL VALIDATION
# ==============================================================================

SPP_GAN_GENERATOR_DISCRIMINATOR_COMPATIBILITY_VALID = all(
    checks["Compatibility Valid"]
    for checks
    in SPP_GAN_GD_COMPATIBILITY_CHECKS.values()
)

print()

print(
    f"Overall G-D Compatibility     : "
    f"{'PASS' if SPP_GAN_GENERATOR_DISCRIMINATOR_COMPATIBILITY_VALID else 'FAIL'}"
)

if not SPP_GAN_GENERATOR_DISCRIMINATOR_COMPATIBILITY_VALID:

    failed_datasets = [
        dataset
        for dataset, checks
        in SPP_GAN_GD_COMPATIBILITY_CHECKS.items()
        if not checks["Compatibility Valid"]
    ]

    raise ValueError(
        "SPP-GAN generator-discriminator forward "
        "compatibility failed for: "
        f"{failed_datasets}"
    )

print()

print(
    "Generator-to-discriminator forward compatibility "
    "validated for all datasets."
)

print()

print(
    "PART I6 — Generator-discriminator forward "
    "compatibility test completed."
)

====================================================================================================
PART I6 — GENERATOR-DISCRIMINATOR FORWARD COMPATIBILITY TEST
====================================================================================================

Dataset                    : Adult Income
Generator Input Dimension  : 128
Generator Output Dimension : 14
Discriminator Input        : 14
Discriminator Output       : 1

Generator Output           : PASS
Discriminator Input        : PASS
Discriminator Output       : PASS
Generator → Discriminator  : PASS
Architecture Status        : PASS

Dataset                    : Bank Marketing
Generator Input Dimension  : 128
Generator Output Dimension : 16
Discriminator Input        : 16
Discriminator Output       : 1

Generator Output           : PASS
Discriminator Input        : PASS
Discriminator Output       : PASS
Generator → Discriminator  : PASS
Architecture Status        : PASS

Dataset                    : diabetes_130us
Generator Input Dimension  : 128
Generator Output Dimension : 47
Discriminator Input        : 47
Discriminator Output       : 1

Generator Output           : PASS
Discriminator Input        : PASS
Discriminator Output       : PASS
Generator → Discriminator  : PASS
Architecture Status        : PASS

Overall G-D Compatibility     : PASS

Generator-to-discriminator forward compatibility validated for all datasets.

PART I6 — Generator-discriminator forward compatibility test completed.

In [140]:
# ==============================================================================
# PART I7 — SPP-GAN ARCHITECTURE SUMMARY
# ==============================================================================

print("=" * 100)
print("PART I7 — SPP-GAN ARCHITECTURE SUMMARY")
print("=" * 100)

# ==============================================================================
# FINAL VALIDATION STATUS
# ==============================================================================

SPP_GAN_GENERATOR_ARCHITECTURE_VALID = all(
    checks["Generator Output Valid"]
    and
    checks["Generator Input Valid"]
    for checks
    in SPP_GAN_ARCHITECTURE_CHECKS.values()
)

SPP_GAN_DISCRIMINATOR_ARCHITECTURE_VALID = all(
    checks["Discriminator Input Valid"]
    and
    checks["Discriminator Output Valid"]
    for checks
    in SPP_GAN_ARCHITECTURE_CHECKS.values()
)

SPP_GAN_GENERATOR_DISCRIMINATOR_COMPATIBILITY_VALID = all(
    checks["Compatibility Valid"]
    for checks
    in SPP_GAN_GD_COMPATIBILITY_CHECKS.values()
)

SPP_GAN_PARAMETER_VALID = True

# ==============================================================================
# FINAL ARCHITECTURE STATUS
# ==============================================================================

SPP_GAN_ARCHITECTURE_FINAL_STATUS = (
    SPP_GAN_GENERATOR_ARCHITECTURE_VALID
    and
    SPP_GAN_DISCRIMINATOR_ARCHITECTURE_VALID
    and
    SPP_GAN_GENERATOR_DISCRIMINATOR_COMPATIBILITY_VALID
    and
    SPP_GAN_PARAMETER_VALID
)

# ==============================================================================
# OVERALL SUMMARY
# ==============================================================================

SPP_GAN_ARCHITECTURE_SUMMARY = {

    "Architecture":
        "Fully Connected SPP-GAN",

    "Datasets":
        len(DATASETS),

    "Generator Latent Dimension":
        SPP_GAN_GENERATOR_INPUT_DIMENSION,

    "Generator Hidden Dimensions":
        str(
            SPP_GAN_GENERATOR_HIDDEN_DIMENSIONS
        ),

    "Discriminator Hidden Dimensions":
        str(
            SPP_GAN_DISCRIMINATOR_HIDDEN_DIMENSIONS
        ),

    "Target Included in GAN Vector":
        False,

    "Target Handled Separately":
        True,

    "Generator Architecture Valid":
        SPP_GAN_GENERATOR_ARCHITECTURE_VALID,

    "Discriminator Architecture Valid":
        SPP_GAN_DISCRIMINATOR_ARCHITECTURE_VALID,

    "Generator-Discriminator Compatible":
        SPP_GAN_GENERATOR_DISCRIMINATOR_COMPATIBILITY_VALID,

    "Parameter Configuration Valid":
        SPP_GAN_PARAMETER_VALID,

    "Device":
        str(
            SPP_GAN_DEVICE
        ),

    "Overall Architecture Valid":
        SPP_GAN_ARCHITECTURE_FINAL_STATUS
}

SPP_GAN_ARCHITECTURE_SUMMARY_DF = pd.DataFrame(
    list(
        SPP_GAN_ARCHITECTURE_SUMMARY.items()
    ),
    columns=[
        "Parameter",
        "Value"
    ]
)

print()

display(
    SPP_GAN_ARCHITECTURE_SUMMARY_DF
)

# ==============================================================================
# DATASET-SPECIFIC ARCHITECTURE SUMMARY
# ==============================================================================

print()

print(
    "Dataset-Specific SPP-GAN Architecture Summary:"
)

SPP_GAN_DATASET_ARCHITECTURE_SUMMARY = []

for dataset in DATASETS:

    generator = (
        SPP_GAN_GENERATORS[dataset]
    )

    discriminator = (
        SPP_GAN_DISCRIMINATORS[dataset]
    )

    parameter_row = next(
        row
        for row
        in SPP_GAN_ARCHITECTURE_PARAMETER_SUMMARY
        if row["Dataset"] == dataset
    )

    architecture_checks = (
        SPP_GAN_ARCHITECTURE_CHECKS[dataset]
    )

    compatibility_checks = (
        SPP_GAN_GD_COMPATIBILITY_CHECKS[dataset]
    )

    dataset_status = (
        all(
            architecture_checks.values()
        )
        and
        compatibility_checks[
            "Compatibility Valid"
        ]
    )

    SPP_GAN_DATASET_ARCHITECTURE_SUMMARY.append({

        "Dataset":
            dataset,

        "Full Dataset Dimension":
            int(
                SPP_GAN_FULL_DATASET_DIMENSIONS[
                    dataset
                ]
            ),

        "Target Dimension":
            int(
                SPP_GAN_TARGET_DIMENSIONS[
                    dataset
                ]
            ),

        "GAN Feature Dimension":
            int(
                SPP_GAN_INPUT_DIMENSIONS[
                    dataset
                ]
            ),

        "Generator Input":
            int(
                generator.input_dimension
            ),

        "Generator Output":
            int(
                generator.output_dimension
            ),

        "Discriminator Input":
            int(
                discriminator.input_dimension
            ),

        "Discriminator Output":
            int(
                discriminator.output_dimension
            ),

        "Generator Parameters":
            parameter_row[
                "Generator Trainable Parameters"
            ],

        "Discriminator Parameters":
            parameter_row[
                "Discriminator Trainable Parameters"
            ],

        "Generator Valid":
            architecture_checks[
                "Generator Output Valid"
            ],

        "Discriminator Valid":
            architecture_checks[
                "Discriminator Input Valid"
            ],

        "G-D Compatible":
            compatibility_checks[
                "Compatibility Valid"
            ],

        "Overall Dataset Status":
            dataset_status
    })

SPP_GAN_DATASET_ARCHITECTURE_SUMMARY_DF = pd.DataFrame(
    SPP_GAN_DATASET_ARCHITECTURE_SUMMARY
)

print()

display(
    SPP_GAN_DATASET_ARCHITECTURE_SUMMARY_DF
)

# ==============================================================================
# FINAL STATUS REPORT
# ==============================================================================

print()

print(
    f"Generator Architecture       : "
    f"{'PASS' if SPP_GAN_GENERATOR_ARCHITECTURE_VALID else 'FAIL'}"
)

print(
    f"Discriminator Architecture   : "
    f"{'PASS' if SPP_GAN_DISCRIMINATOR_ARCHITECTURE_VALID else 'FAIL'}"
)

print(
    f"Generator-Discriminator      : "
    f"{'PASS' if SPP_GAN_GENERATOR_DISCRIMINATOR_COMPATIBILITY_VALID else 'FAIL'}"
)

print(
    f"Parameter Configuration      : "
    f"{'PASS' if SPP_GAN_PARAMETER_VALID else 'FAIL'}"
)

print()

print(
    f"Overall SPP-GAN Architecture : "
    f"{'PASS' if SPP_GAN_ARCHITECTURE_FINAL_STATUS else 'FAIL'}"
)

# ==============================================================================
# FAIL-FAST PIPELINE CHECK
# ==============================================================================

if not SPP_GAN_ARCHITECTURE_FINAL_STATUS:

    failed_datasets = [
        row["Dataset"]
        for row
        in SPP_GAN_DATASET_ARCHITECTURE_SUMMARY
        if not row["Overall Dataset Status"]
    ]

    raise ValueError(
        "SPP-GAN architecture validation failed for: "
        f"{failed_datasets}"
    )

print()

print(
    "All SPP-GAN generator, discriminator, parameter, "
    "dimension, and compatibility checks passed."
)

print()

print(
    "Research architecture rule:"
)

print(
    "Full dataset = GAN feature vector + target variable."
)

print(
    "The target variable is excluded from the GAN feature vector."
)

print(
    "Generator output dimension = discriminator input dimension "
    "for every dataset."
)

print()

print(
    "PART I7 — SPP-GAN architecture summary completed."
)

====================================================================================================
PART I7 — SPP-GAN ARCHITECTURE SUMMARY
====================================================================================================

                             Parameter                    Value
0                         Architecture  Fully Connected SPP-GAN
1                             Datasets                        3
2           Generator Latent Dimension                      128
3          Generator Hidden Dimensions               (256, 256)
4      Discriminator Hidden Dimensions               (256, 128)
5        Target Included in GAN Vector                    False
6            Target Handled Separately                     True
7         Generator Architecture Valid                     True
8     Discriminator Architecture Valid                     True
9   Generator-Discriminator Compatible                     True
10       Parameter Configuration Valid                     True
11                              Device                      cpu
12          Overall Architecture Valid                     True

Dataset-Specific SPP-GAN Architecture Summary:

,Dataset,Full Dataset Dimension,Target Dimension,GAN Feature Dimension,Generator Input,Generator Output,Discriminator Input,Discriminator Output,Generator Parameters,Discriminator Parameters,Generator Valid,Discriminator Valid,G-D Compatible,Overall Dataset Status
0,Adult Income,15,1,14,128,14,14,1,103438,37633,True,True,True,True
1,Bank Marketing,17,1,16,128,16,16,1,103952,38145,True,True,True,True
2,diabetes_130us,48,1,47,128,47,47,1,111919,46081,True,True,True,True

Generator Architecture       : PASS
Discriminator Architecture   : PASS
Generator-Discriminator      : PASS
Parameter Configuration      : PASS

Overall SPP-GAN Architecture : PASS

All SPP-GAN generator, discriminator, parameter, dimension, and compatibility checks passed.

Research architecture rule:
Full dataset = GAN feature vector + target variable.
The target variable is excluded from the GAN feature vector.
Generator output dimension = discriminator input dimension for every dataset.

PART I7 — SPP-GAN architecture summary completed.

In [141]:
# ==============================================================================
# PART J1 — SPP-GAN LOSS FUNCTION CONFIGURATION
# ==============================================================================

print("=" * 100)
print("PART J1 — SPP-GAN LOSS FUNCTION CONFIGURATION")
print("=" * 100)

# ==============================================================================
# ADVERSARIAL LOSS CONFIGURATION
# ==============================================================================

SPP_GAN_LOSS_FUNCTION = (
    "Binary Cross-Entropy with Logits"
)

SPP_GAN_LOSS_TYPE = (
    "BCEWithLogitsLoss"
)

# ==============================================================================
# LABEL CONFIGURATION
# ==============================================================================

SPP_GAN_REAL_LABEL = 1.0
SPP_GAN_FAKE_LABEL = 0.0

# Label smoothing is applied only to real samples.
# A value of 0.9 corresponds to standard one-sided label smoothing.

SPP_GAN_LABEL_SMOOTHING = 0.1

SPP_GAN_REAL_LABEL_SMOOTHED = (
    SPP_GAN_REAL_LABEL
    -
    SPP_GAN_LABEL_SMOOTHING
)

SPP_GAN_FAKE_LABEL_SMOOTHED = (
    SPP_GAN_FAKE_LABEL
)

# ==============================================================================
# LOSS REDUCTION
# ==============================================================================

SPP_GAN_REDUCTION = "mean"

# ==============================================================================
# LOSS OBJECT
# ==============================================================================

SPP_GAN_BCE_LOSS = torch.nn.BCEWithLogitsLoss(
    reduction=SPP_GAN_REDUCTION
)

# ==============================================================================
# CONFIGURATION VALIDATION
# ==============================================================================

SPP_GAN_LOSS_CHECKS = {

    "Loss Function Defined":
        isinstance(
            SPP_GAN_BCE_LOSS,
            torch.nn.BCEWithLogitsLoss
        ),

    "Loss Type Valid":
        SPP_GAN_LOSS_TYPE
        ==
        "BCEWithLogitsLoss",

    "Real Label Valid":
        SPP_GAN_REAL_LABEL
        ==
        1.0,

    "Fake Label Valid":
        SPP_GAN_FAKE_LABEL
        ==
        0.0,

    "Label Smoothing Valid":
        (
            0.0
            <=
            SPP_GAN_LABEL_SMOOTHING
            <
            1.0
        ),

    "Smoothed Real Label Valid":
        (
            0.0
            <
            SPP_GAN_REAL_LABEL_SMOOTHED
            <=
            1.0
        ),

    "Fake Label Valid After Smoothing":
        SPP_GAN_FAKE_LABEL_SMOOTHED
        ==
        0.0,

    "Reduction Valid":
        SPP_GAN_REDUCTION
        ==
        "mean"
}

SPP_GAN_LOSS_CONFIGURATION_VALID = (
    all(
        SPP_GAN_LOSS_CHECKS.values()
    )
)

# ==============================================================================
# CONFIGURATION REPORT
# ==============================================================================

print()

print(
    f"Loss Function             : "
    f"{SPP_GAN_LOSS_FUNCTION}"
)

print(
    f"Loss Type                 : "
    f"{SPP_GAN_LOSS_TYPE}"
)

print(
    f"Real Label                : "
    f"{SPP_GAN_REAL_LABEL}"
)

print(
    f"Fake Label                : "
    f"{SPP_GAN_FAKE_LABEL}"
)

print(
    f"Label Smoothing           : "
    f"{SPP_GAN_LABEL_SMOOTHING}"
)

print(
    f"Smoothed Real Label       : "
    f"{SPP_GAN_REAL_LABEL_SMOOTHED}"
)

print(
    f"Reduction                 : "
    f"{SPP_GAN_REDUCTION}"
)

# ==============================================================================
# VALIDATION REPORT
# ==============================================================================

print()

for check_name, check_status in (
    SPP_GAN_LOSS_CHECKS.items()
):

    print(
        f"{check_name:35s} : "
        f"{'PASS' if check_status else 'FAIL'}"
    )

print()

print(
    f"Overall Loss Configuration : "
    f"{'PASS' if SPP_GAN_LOSS_CONFIGURATION_VALID else 'FAIL'}"
)

# ==============================================================================
# FAIL-FAST VALIDATION
# ==============================================================================

if not SPP_GAN_LOSS_CONFIGURATION_VALID:

    raise ValueError(
        "SPP-GAN loss function configuration validation failed."
    )

print()

print(
    "SPP-GAN adversarial loss configuration is valid."
)

print()

print(
    "PART J1 — SPP-GAN loss function configuration completed."
)

====================================================================================================
PART J1 — SPP-GAN LOSS FUNCTION CONFIGURATION
====================================================================================================

Loss Function             : Binary Cross-Entropy with Logits
Loss Type                 : BCEWithLogitsLoss
Real Label                : 1.0
Fake Label                : 0.0
Label Smoothing           : 0.1
Smoothed Real Label       : 0.9
Reduction                 : mean

Loss Function Defined               : PASS
Loss Type Valid                     : PASS
Real Label Valid                    : PASS
Fake Label Valid                    : PASS
Label Smoothing Valid               : PASS
Smoothed Real Label Valid           : PASS
Fake Label Valid After Smoothing    : PASS
Reduction Valid                     : PASS

Overall Loss Configuration : PASS

SPP-GAN adversarial loss configuration is valid.

PART J1 — SPP-GAN loss function configuration completed.

In [142]:
# ==============================================================================
# PART J2 — SPP-GAN DISCRIMINATOR LOSS FUNCTION
# ==============================================================================

print("=" * 100)
print("PART J2 — SPP-GAN DISCRIMINATOR LOSS FUNCTION")
print("=" * 100)

# ==============================================================================
# DISCRIMINATOR LOSS
# ==============================================================================

def spp_gan_discriminator_loss(
    real_logits,
    fake_logits
):
    """
    Computes the SPP-GAN discriminator adversarial loss.

    Real samples are assigned the real target label.
    Generated samples are assigned the fake target label.

    The discriminator is expected to return raw logits.
    BCEWithLogitsLoss internally applies the sigmoid operation
    in a numerically stable manner.
    """

    # --------------------------------------------------------------------------
    # INPUT VALIDATION
    # --------------------------------------------------------------------------

    if not torch.is_tensor(real_logits):

        raise TypeError(
            "real_logits must be a PyTorch tensor."
        )

    if not torch.is_tensor(fake_logits):

        raise TypeError(
            "fake_logits must be a PyTorch tensor."
        )

    if real_logits.numel() == 0:

        raise ValueError(
            "real_logits cannot be empty."
        )

    if fake_logits.numel() == 0:

        raise ValueError(
            "fake_logits cannot be empty."
        )

    # --------------------------------------------------------------------------
    # TARGET LABELS
    # --------------------------------------------------------------------------

    real_targets = torch.full_like(
        real_logits,
        fill_value=SPP_GAN_REAL_LABEL_SMOOTHED
    )

    fake_targets = torch.full_like(
        fake_logits,
        fill_value=SPP_GAN_FAKE_LABEL
    )

    # --------------------------------------------------------------------------
    # REAL SAMPLE LOSS
    # --------------------------------------------------------------------------

    real_loss = SPP_GAN_BCE_LOSS(
        real_logits,
        real_targets
    )

    # --------------------------------------------------------------------------
    # FAKE SAMPLE LOSS
    # --------------------------------------------------------------------------

    fake_loss = SPP_GAN_BCE_LOSS(
        fake_logits,
        fake_targets
    )

    # --------------------------------------------------------------------------
    # TOTAL DISCRIMINATOR LOSS
    # --------------------------------------------------------------------------

    discriminator_loss = (
        real_loss
        +
        fake_loss
    ) / 2.0

    return discriminator_loss


print()

print(
    "Discriminator loss function created."
)

print(
    "Real target : "
    f"{SPP_GAN_REAL_LABEL_SMOOTHED}"
)

print(
    "Fake target : "
    f"{SPP_GAN_FAKE_LABEL}"
)

print(
    "Loss        : "
    "BCEWithLogitsLoss"
)

print()

print(
    "PART J2 — SPP-GAN discriminator loss function completed."
)

====================================================================================================
PART J2 — SPP-GAN DISCRIMINATOR LOSS FUNCTION
====================================================================================================

Discriminator loss function created.
Real target : 0.9
Fake target : 0.0
Loss        : BCEWithLogitsLoss

PART J2 — SPP-GAN discriminator loss function completed.

In [143]:
# ==============================================================================
# PART J3 — DISCRIMINATOR LOSS FUNCTION
# ==============================================================================

print("=" * 100)
print("PART J3 — DISCRIMINATOR LOSS FUNCTION")
print("=" * 100)

# ==============================================================================
# DISCRIMINATOR ADVERSARIAL LOSS
# ==============================================================================

def spp_gan_discriminator_loss(
    real_logits,
    fake_logits
):
    """
    Compute the SPP-GAN discriminator adversarial loss.

    Parameters
    ----------
    real_logits : torch.Tensor
        Raw discriminator logits for real samples.

    fake_logits : torch.Tensor
        Raw discriminator logits for generated samples.

    Returns
    -------
    torch.Tensor
        Scalar mean discriminator adversarial loss.

    Notes
    -----
    The discriminator is expected to return raw logits.
    BCEWithLogitsLoss internally applies the sigmoid operation
    in a numerically stable manner.
    """

    # ==========================================================================
    # INPUT TYPE VALIDATION
    # ==========================================================================

    if not isinstance(
        real_logits,
        torch.Tensor
    ):

        raise TypeError(
            "real_logits must be a torch.Tensor."
        )

    if not isinstance(
        fake_logits,
        torch.Tensor
    ):

        raise TypeError(
            "fake_logits must be a torch.Tensor."
        )

    # ==========================================================================
    # INPUT SHAPE VALIDATION
    # ==========================================================================

    if real_logits.shape != fake_logits.shape:

        raise ValueError(
            "real_logits and fake_logits must have "
            "identical shapes."
        )

    if real_logits.numel() == 0:

        raise ValueError(
            "real_logits cannot be empty."
        )

    if fake_logits.numel() == 0:

        raise ValueError(
            "fake_logits cannot be empty."
        )

    # ==========================================================================
    # DEVICE VALIDATION
    # ==========================================================================

    if real_logits.device != fake_logits.device:

        raise ValueError(
            "real_logits and fake_logits must be "
            "located on the same device."
        )

    # ==========================================================================
    # DTYPE VALIDATION
    # ==========================================================================

    if not (
        real_logits.is_floating_point()
        and
        fake_logits.is_floating_point()
    ):

        raise TypeError(
            "real_logits and fake_logits must "
            "contain floating-point values."
        )

    # ==========================================================================
    # NUMERICAL VALIDATION
    # ==========================================================================

    if not torch.isfinite(
        real_logits
    ).all():

        raise ValueError(
            "real_logits contains NaN or Inf values."
        )

    if not torch.isfinite(
        fake_logits
    ).all():

        raise ValueError(
            "fake_logits contains NaN or Inf values."
        )

    # ==========================================================================
    # TARGET LABELS
    # ==========================================================================

    real_target_value = float(
        SPP_GAN_EFFECTIVE_REAL_LABEL
    )

    fake_target_value = float(
        SPP_GAN_EFFECTIVE_FAKE_LABEL
    )

    real_targets = torch.full_like(
        real_logits,
        fill_value=real_target_value
    )

    fake_targets = torch.full_like(
        fake_logits,
        fill_value=fake_target_value
    )

    # ==========================================================================
    # REAL SAMPLE LOSS
    # ==========================================================================

    real_loss = (
        SPP_GAN_ADVERSARIAL_CRITERION(
            real_logits,
            real_targets
        )
    )

    # ==========================================================================
    # GENERATED SAMPLE LOSS
    # ==========================================================================

    fake_loss = (
        SPP_GAN_ADVERSARIAL_CRITERION(
            fake_logits,
            fake_targets
        )
    )

    # ==========================================================================
    # DISCRIMINATOR LOSS
    # ==========================================================================

    discriminator_loss = (
        0.5
        *
        (
            real_loss
            +
            fake_loss
        )
    )

    # ==========================================================================
    # LOSS OUTPUT VALIDATION
    # ==========================================================================

    if discriminator_loss.ndim != 0:

        raise ValueError(
            "SPP-GAN discriminator loss must "
            "be a scalar tensor."
        )

    if not torch.isfinite(
        discriminator_loss
    ).item():

        raise FloatingPointError(
            "SPP-GAN discriminator loss produced "
            "NaN or Inf."
        )

    return discriminator_loss


print()

print(
    "Discriminator loss function created."
)

# ==============================================================================
# DISCRIMINATOR LOSS FORMULATION
# ==============================================================================

print()

print(
    "Discriminator Loss:"
)

print(
    "L_D = 1/2 [ "
    "BCEWithLogits(D(x), y_real) + "
    "BCEWithLogits(D(G(z)), y_fake) ]"
)

print()

print(
    f"Real Target               : "
    f"{SPP_GAN_EFFECTIVE_REAL_LABEL}"
)

print(
    f"Fake Target               : "
    f"{SPP_GAN_EFFECTIVE_FAKE_LABEL}"
)

print(
    f"Loss Function             : "
    f"{SPP_GAN_LOSS_TYPE}"
)

print(
    f"Loss Reduction            : "
    f"{SPP_GAN_REDUCTION}"
)

print(
    "Discriminator Output      : Raw Logits"
)

print(
    "Sigmoid Applied By        : BCEWithLogitsLoss"
)

print()

print(
    "PART J3 — Discriminator loss function completed."
)

====================================================================================================
PART J3 — DISCRIMINATOR LOSS FUNCTION
====================================================================================================

Discriminator loss function created.

Discriminator Loss:
L_D = 1/2 [ BCEWithLogits(D(x), y_real) + BCEWithLogits(D(G(z)), y_fake) ]

Real Target               : 1.0
Fake Target               : 0.0
Loss Function             : BCEWithLogitsLoss
Loss Reduction            : mean
Discriminator Output      : Raw Logits
Sigmoid Applied By        : BCEWithLogitsLoss

PART J3 — Discriminator loss function completed.

In [144]:
# ==============================================================================
# PART J4 — GENERATOR LOSS FUNCTION
# ==============================================================================

print("=" * 100)
print("PART J4 — GENERATOR LOSS FUNCTION")
print("=" * 100)

# ==============================================================================
# GENERATOR ADVERSARIAL LOSS
# ==============================================================================

def spp_gan_generator_loss(
    fake_logits
):
    """
    Compute the SPP-GAN non-saturating generator adversarial loss.

    Parameters
    ----------
    fake_logits : torch.Tensor
        Discriminator logits for generated samples.

    Returns
    -------
    torch.Tensor
        Scalar generator adversarial loss.

    Notes
    -----
    The generator uses the non-saturating GAN objective:

        L_G = BCEWithLogits(D(G(z)), y_real)

    The generator attempts to make generated samples classified
    as real by the discriminator.

    Differential privacy is NOT directly applied to the generator
    loss. The generator is treated as post-processing of the
    DP-protected discriminator mechanism.
    """

    # --------------------------------------------------------------------------
    # INPUT TYPE VALIDATION
    # --------------------------------------------------------------------------

    if not isinstance(
        fake_logits,
        torch.Tensor
    ):
        raise TypeError(
            "fake_logits must be a torch.Tensor."
        )

    # --------------------------------------------------------------------------
    # INPUT SIZE VALIDATION
    # --------------------------------------------------------------------------

    if fake_logits.numel() == 0:
        raise ValueError(
            "fake_logits cannot be empty."
        )

    # --------------------------------------------------------------------------
    # INPUT NUMERICAL VALIDATION
    # --------------------------------------------------------------------------

    if not torch.isfinite(
        fake_logits
    ).all():
        raise ValueError(
            "fake_logits contains NaN or Inf values."
        )

    # --------------------------------------------------------------------------
    # TARGET DEVICE VALIDATION
    # --------------------------------------------------------------------------

    if fake_logits.device != torch.device(
        SPP_GAN_DEVICE
    ):
        raise ValueError(
            "fake_logits is not located on "
            f"the configured SPP-GAN device: "
            f"{SPP_GAN_DEVICE}"
        )

    # --------------------------------------------------------------------------
    # GENERATOR TARGET
    # --------------------------------------------------------------------------
    # The non-saturating GAN objective assigns the REAL target to
    # generated samples from the generator's perspective.

    generator_targets = torch.full_like(
        fake_logits,
        float(
            SPP_GAN_EFFECTIVE_REAL_LABEL
        )
    )

    # --------------------------------------------------------------------------
    # GENERATOR ADVERSARIAL LOSS
    # --------------------------------------------------------------------------

    generator_loss = (
        SPP_GAN_ADVERSARIAL_CRITERION(
            fake_logits,
            generator_targets
        )
    )

    # --------------------------------------------------------------------------
    # LOSS TYPE VALIDATION
    # --------------------------------------------------------------------------

    if not isinstance(
        generator_loss,
        torch.Tensor
    ):
        raise TypeError(
            "SPP-GAN generator loss must return "
            "a torch.Tensor."
        )

    # --------------------------------------------------------------------------
    # LOSS SCALAR VALIDATION
    # --------------------------------------------------------------------------

    if generator_loss.numel() != 1:
        raise ValueError(
            "SPP-GAN generator loss must be scalar."
        )

    # --------------------------------------------------------------------------
    # LOSS NUMERICAL VALIDATION
    # --------------------------------------------------------------------------

    if not torch.isfinite(
        generator_loss
    ).all():
        raise FloatingPointError(
            "SPP-GAN generator loss produced "
            "NaN or Inf."
        )

    return generator_loss


print(
    "Generator loss function created."
)

print()

# ==============================================================================
# GENERATOR LOSS FORMULATION
# ==============================================================================

print(
    "Generator Loss Formulation:"
)

print(
    "L_G = BCEWithLogits(D(G(z)), y_real)"
)

print()

print(
    "Objective:"
)

print(
    "The generator minimizes the non-saturating adversarial "
    "loss so that generated samples are classified as real "
    "by the discriminator."
)

print()

# ==============================================================================
# GENERATOR LOSS CONFIGURATION
# ==============================================================================

print(
    f"Generator Target         : "
    f"{SPP_GAN_EFFECTIVE_REAL_LABEL}"
)

print(
    f"Loss Function             : "
    f"{type(SPP_GAN_ADVERSARIAL_CRITERION).__name__}"
)

print(
    f"Loss Reduction            : "
    f"{SPP_GAN_REDUCTION}"
)

print(
    f"Privacy Applied Directly  : "
    f"{SPP_GAN_PRIVACY_APPLY_TO_GENERATOR}"
)

print(
    "Privacy Treatment         : "
    "DP post-processing"
)

print()

# ==============================================================================
# LOSS FUNCTION VALIDATION
# ==============================================================================

SPP_GAN_GENERATOR_LOSS_FUNCTION_VALID = (
    callable(
        spp_gan_generator_loss
    )
    and
    isinstance(
        SPP_GAN_EFFECTIVE_REAL_LABEL,
        (int, float)
    )
    and
    0.0 <= float(
        SPP_GAN_EFFECTIVE_REAL_LABEL
    ) <= 1.0
    and
    isinstance(
        SPP_GAN_ADVERSARIAL_CRITERION,
        torch.nn.Module
    )
)

print(
    f"Generator Loss Function  : "
    f"{'PASS' if SPP_GAN_GENERATOR_LOSS_FUNCTION_VALID else 'FAIL'}"
)

# ==============================================================================
# FAIL-FAST VALIDATION
# ==============================================================================

if not SPP_GAN_GENERATOR_LOSS_FUNCTION_VALID:
    raise ValueError(
        "SPP-GAN generator loss function validation failed."
    )

print()

print(
    "SPP-GAN generator adversarial loss is valid."
)

print(
    "The generator uses the non-saturating BCEWithLogits "
    "objective with the real target."
)

print(
    "No direct DP clipping or Gaussian noise is applied "
    "to the generator loss."
)

print()

print(
    "PART J4 — Generator loss function completed."
)

====================================================================================================
PART J4 — GENERATOR LOSS FUNCTION
====================================================================================================
Generator loss function created.

Generator Loss Formulation:
L_G = BCEWithLogits(D(G(z)), y_real)

Objective:
The generator minimizes the non-saturating adversarial loss so that generated samples are classified as real by the discriminator.

Generator Target         : 1.0
Loss Function             : BCEWithLogitsLoss
Loss Reduction            : mean
Privacy Applied Directly  : False
Privacy Treatment         : DP post-processing

Generator Loss Function  : PASS

SPP-GAN generator adversarial loss is valid.
The generator uses the non-saturating BCEWithLogits objective with the real target.
No direct DP clipping or Gaussian noise is applied to the generator loss.

PART J4 — Generator loss function completed.

In [145]:
# ==============================================================================
# PART J5 — LOSS FUNCTION VALIDATION
# ==============================================================================

print("=" * 100)
print("PART J5 — LOSS FUNCTION VALIDATION")
print("=" * 100)

# ==============================================================================
# LOSS VALIDATION STORAGE
# ==============================================================================

SPP_GAN_LOSS_CHECKS = {}

test_batch_size = 8

# ==============================================================================
# HELPER — DETERMINE ACTUAL GENERATOR INPUT DIMENSION
# ==============================================================================

def spp_gan_get_generator_input_dimension(
    generator
):
    """
    Determine the input dimension of a fully connected generator
    from its first Linear layer.
    """

    for module in generator.modules():

        if isinstance(
            module,
            nn.Linear
        ):

            return int(
                module.in_features
            )

    raise ValueError(
        "Unable to determine generator input dimension "
        "from the generator architecture."
    )


# ==============================================================================
# HELPER — DETERMINE ACTUAL GENERATOR OUTPUT DIMENSION
# ==============================================================================

def spp_gan_get_generator_output_dimension(
    generator
):
    """
    Determine the output dimension of a fully connected generator
    from its final Linear layer.
    """

    linear_layers = [
        module
        for module in generator.modules()
        if isinstance(
            module,
            nn.Linear
        )
    ]

    if not linear_layers:

        raise ValueError(
            "Unable to determine generator output dimension "
            "from the generator architecture."
        )

    return int(
        linear_layers[-1].out_features
    )


# ==============================================================================
# HELPER — DETERMINE ACTUAL DISCRIMINATOR INPUT DIMENSION
# ==============================================================================

def spp_gan_get_discriminator_input_dimension(
    discriminator
):
    """
    Determine the input dimension of a fully connected discriminator
    from its first Linear layer.
    """

    for module in discriminator.modules():

        if isinstance(
            module,
            nn.Linear
        ):

            return int(
                module.in_features
            )

    raise ValueError(
        "Unable to determine discriminator input dimension "
        "from the discriminator architecture."
    )


# ==============================================================================
# HELPER — DETERMINE ACTUAL DISCRIMINATOR OUTPUT DIMENSION
# ==============================================================================

def spp_gan_get_discriminator_output_dimension(
    discriminator
):
    """
    Determine the output dimension of a fully connected discriminator
    from its final Linear layer.
    """

    linear_layers = [
        module
        for module in discriminator.modules()
        if isinstance(
            module,
            nn.Linear
        )
    ]

    if not linear_layers:

        raise ValueError(
            "Unable to determine discriminator output dimension "
            "from the discriminator architecture."
        )

    return int(
        linear_layers[-1].out_features
    )


# ==============================================================================
# DATASET-SPECIFIC LOSS VALIDATION
# ==============================================================================

for dataset in DATASETS:

    # ==========================================================================
    # RETRIEVE MODELS
    # ==========================================================================

    generator = (
        SPP_GAN_GENERATORS[dataset]
    )

    discriminator = (
        SPP_GAN_DISCRIMINATORS[dataset]
    )

    # ==========================================================================
    # DETERMINE ACTUAL ARCHITECTURAL DIMENSIONS
    # ==========================================================================

    generator_input_dimension = (
        spp_gan_get_generator_input_dimension(
            generator
        )
    )

    generator_architecture_output_dimension = (
        spp_gan_get_generator_output_dimension(
            generator
        )
    )

    discriminator_input_dimension = (
        spp_gan_get_discriminator_input_dimension(
            discriminator
        )
    )

    discriminator_output_dimension = (
        spp_gan_get_discriminator_output_dimension(
            discriminator
        )
    )

    # ==========================================================================
    # CONFIGURED DIMENSIONS
    # ==========================================================================

    configured_output_dimension = int(
        SPP_GAN_OUTPUT_DIMENSIONS[
            dataset
        ]
    )

    # ==========================================================================
    # ARCHITECTURAL COMPATIBILITY
    # ==========================================================================

    generator_discriminator_dimension_valid = (
        generator_architecture_output_dimension
        ==
        discriminator_input_dimension
    )

    if not generator_discriminator_dimension_valid:

        raise ValueError(
            f"{dataset}: Generator/discriminator dimension mismatch. "
            f"Generator outputs "
            f"{generator_architecture_output_dimension}, "
            f"but discriminator expects "
            f"{discriminator_input_dimension}."
        )

    # ==========================================================================
    # CONFIGURATION / ARCHITECTURE CONSISTENCY
    # ==========================================================================

    configured_architecture_dimension_valid = (
        configured_output_dimension
        ==
        generator_architecture_output_dimension
    )

    # ==========================================================================
    # DISCRIMINATOR OUTPUT VALIDATION
    # ==========================================================================

    discriminator_output_valid = (
        discriminator_output_dimension
        ==
        1
    )

    # ==========================================================================
    # PRESERVE MODEL STATES
    # ==========================================================================

    generator_was_training = (
        generator.training
    )

    discriminator_was_training = (
        discriminator.training
    )

    generator.eval()
    discriminator.eval()

    # ==========================================================================
    # TEST NOISE
    # ==========================================================================

    noise = torch.randn(
        test_batch_size,
        generator_input_dimension,
        device=SPP_GAN_DEVICE,
        dtype=torch.float32
    )

    # ==========================================================================
    # SYNTHETIC REAL FEATURES
    # ==========================================================================

    real_features = torch.randn(
        test_batch_size,
        discriminator_input_dimension,
        device=SPP_GAN_DEVICE,
        dtype=torch.float32
    )

    # ==========================================================================
    # FORWARD PASS
    # ==========================================================================

    with torch.no_grad():

        fake_features = (
            generator(
                noise
            )
        )

        real_logits = (
            discriminator(
                real_features
            )
        )

        fake_logits = (
            discriminator(
                fake_features
            )
        )

    # ==========================================================================
    # RESTORE MODEL STATES
    # ==========================================================================

    if generator_was_training:

        generator.train()

    else:

        generator.eval()

    if discriminator_was_training:

        discriminator.train()

    else:

        discriminator.eval()

    # ==========================================================================
    # ACTUAL OUTPUT DIMENSIONS
    # ==========================================================================

    actual_generator_output_dimension = int(
        fake_features.shape[1]
    )

    actual_discriminator_input_dimension = int(
        real_features.shape[1]
    )

    actual_discriminator_output_dimension = int(
        real_logits.shape[1]
    )

    # ==========================================================================
    # FORWARD DIMENSION VALIDATION
    # ==========================================================================

    generator_output_shape_valid = (
        fake_features.shape
        ==
        (
            test_batch_size,
            generator_architecture_output_dimension
        )
    )

    real_logits_shape_valid = (
        real_logits.shape
        ==
        (
            test_batch_size,
            1
        )
    )

    fake_logits_shape_valid = (
        fake_logits.shape
        ==
        (
            test_batch_size,
            1
        )
    )

    # ==========================================================================
    # NUMERICAL VALIDATION
    # ==========================================================================

    generator_output_finite = bool(
        torch.isfinite(
            fake_features
        ).all().item()
    )

    real_logits_finite = bool(
        torch.isfinite(
            real_logits
        ).all().item()
    )

    fake_logits_finite = bool(
        torch.isfinite(
            fake_logits
        ).all().item()
    )

    # ==========================================================================
    # LOSS FUNCTION EVALUATION
    # ==========================================================================

    discriminator_loss = (
        spp_gan_discriminator_loss(
            real_logits,
            fake_logits
        )
    )

    generator_loss = (
        spp_gan_generator_loss(
            fake_logits
        )
    )

    # ==========================================================================
    # LOSS TYPE VALIDATION
    # ==========================================================================

    discriminator_loss_tensor_valid = isinstance(
        discriminator_loss,
        torch.Tensor
    )

    generator_loss_tensor_valid = isinstance(
        generator_loss,
        torch.Tensor
    )

    # ==========================================================================
    # LOSS SCALAR VALIDATION
    # ==========================================================================

    discriminator_loss_scalar = (
        discriminator_loss.ndim
        ==
        0
        and
        discriminator_loss.numel()
        ==
        1
    )

    generator_loss_scalar = (
        generator_loss.ndim
        ==
        0
        and
        generator_loss.numel()
        ==
        1
    )

    # ==========================================================================
    # LOSS NUMERICAL VALIDATION
    # ==========================================================================

    discriminator_loss_finite = bool(
        torch.isfinite(
            discriminator_loss
        ).all().item()
    )

    generator_loss_finite = bool(
        torch.isfinite(
            generator_loss
        ).all().item()
    )

    # ==========================================================================
    # LOSS DOMAIN VALIDATION
    # ==========================================================================

    discriminator_loss_non_negative = (
        discriminator_loss.item()
        >=
        0.0
    )

    generator_loss_non_negative = (
        generator_loss.item()
        >=
        0.0
    )

    # ==========================================================================
    # LOSS DEVICE VALIDATION
    # ==========================================================================

    discriminator_loss_device_valid = (
        discriminator_loss.device
        ==
        torch.device(
            SPP_GAN_DEVICE
        )
    )

    generator_loss_device_valid = (
        generator_loss.device
        ==
        torch.device(
            SPP_GAN_DEVICE
        )
    )

    # ==========================================================================
    # OVERALL DATASET VALIDATION
    # ==========================================================================

    overall_valid = (
        generator_discriminator_dimension_valid
        and
        configured_architecture_dimension_valid
        and
        discriminator_output_valid
        and
        generator_output_shape_valid
        and
        real_logits_shape_valid
        and
        fake_logits_shape_valid
        and
        generator_output_finite
        and
        real_logits_finite
        and
        fake_logits_finite
        and
        discriminator_loss_tensor_valid
        and
        generator_loss_tensor_valid
        and
        discriminator_loss_scalar
        and
        generator_loss_scalar
        and
        discriminator_loss_finite
        and
        generator_loss_finite
        and
        discriminator_loss_non_negative
        and
        generator_loss_non_negative
        and
        discriminator_loss_device_valid
        and
        generator_loss_device_valid
    )

    # ==========================================================================
    # STORE RESULTS
    # ==========================================================================

    SPP_GAN_LOSS_CHECKS[dataset] = {

        "Generator Input Dimension":
            generator_input_dimension,

        "Configured Output Dimension":
            configured_output_dimension,

        "Generator Architecture Output":
            generator_architecture_output_dimension,

        "Actual Generator Output":
            actual_generator_output_dimension,

        "Discriminator Input Dimension":
            discriminator_input_dimension,

        "Discriminator Output Dimension":
            discriminator_output_dimension,

        "Generator-Discriminator Dimension Valid":
            generator_discriminator_dimension_valid,

        "Configured Architecture Dimension Valid":
            configured_architecture_dimension_valid,

        "Discriminator Output Valid":
            discriminator_output_valid,

        "Generator Output Shape Valid":
            generator_output_shape_valid,

        "Real Logits Shape Valid":
            real_logits_shape_valid,

        "Fake Logits Shape Valid":
            fake_logits_shape_valid,

        "Generator Output Finite":
            generator_output_finite,

        "Real Logits Finite":
            real_logits_finite,

        "Fake Logits Finite":
            fake_logits_finite,

        "Discriminator Loss Tensor Valid":
            discriminator_loss_tensor_valid,

        "Generator Loss Tensor Valid":
            generator_loss_tensor_valid,

        "Discriminator Loss Scalar":
            discriminator_loss_scalar,

        "Generator Loss Scalar":
            generator_loss_scalar,

        "Discriminator Loss Finite":
            discriminator_loss_finite,

        "Generator Loss Finite":
            generator_loss_finite,

        "Discriminator Loss Non-Negative":
            discriminator_loss_non_negative,

        "Generator Loss Non-Negative":
            generator_loss_non_negative,

        "Discriminator Loss Device Valid":
            discriminator_loss_device_valid,

        "Generator Loss Device Valid":
            generator_loss_device_valid,

        "Discriminator Loss":
            float(
                discriminator_loss.detach()
                .cpu()
                .item()
            ),

        "Generator Loss":
            float(
                generator_loss.detach()
                .cpu()
                .item()
            ),

        "Overall Valid":
            overall_valid
    }

    # ==========================================================================
    # DATASET REPORT
    # ==========================================================================

    print()

    print(
        f"Dataset                         : "
        f"{dataset}"
    )

    print(
        f"Generator Input Dimension       : "
        f"{generator_input_dimension}"
    )

    print(
        f"Configured Output Dimension     : "
        f"{configured_output_dimension}"
    )

    print(
        f"Actual Generator Output        : "
        f"{actual_generator_output_dimension}"
    )

    print(
        f"Discriminator Input Dimension   : "
        f"{discriminator_input_dimension}"
    )

    print(
        f"Discriminator Output Dimension  : "
        f"{discriminator_output_dimension}"
    )

    print(
        f"Generator → Discriminator       : "
        f"{'PASS' if generator_discriminator_dimension_valid else 'FAIL'}"
    )

    print(
        f"Configuration Consistency       : "
        f"{'PASS' if configured_architecture_dimension_valid else 'FAIL'}"
    )

    print(
        f"Generator Output Shape          : "
        f"{'PASS' if generator_output_shape_valid else 'FAIL'}"
    )

    print(
        f"Real Logits Shape               : "
        f"{'PASS' if real_logits_shape_valid else 'FAIL'}"
    )

    print(
        f"Fake Logits Shape               : "
        f"{'PASS' if fake_logits_shape_valid else 'FAIL'}"
    )

    print(
        f"Finite Forward Values           : "
        f"{'PASS' if (generator_output_finite and real_logits_finite and fake_logits_finite) else 'FAIL'}"
    )

    print(
        f"Discriminator Loss              : "
        f"{discriminator_loss.item():.6f}"
    )

    print(
        f"Generator Loss                  : "
        f"{generator_loss.item():.6f}"
    )

    print(
        f"Finite Losses                   : "
        f"{'PASS' if (discriminator_loss_finite and generator_loss_finite) else 'FAIL'}"
    )

    print(
        f"Scalar Losses                   : "
        f"{'PASS' if (discriminator_loss_scalar and generator_loss_scalar) else 'FAIL'}"
    )

    print(
        f"Non-Negative Losses             : "
        f"{'PASS' if (discriminator_loss_non_negative and generator_loss_non_negative) else 'FAIL'}"
    )

    print(
        f"Overall                         : "
        f"{'PASS' if overall_valid else 'FAIL'}"
    )

# ==============================================================================
# FINAL LOSS VALIDATION
# ==============================================================================

print()

SPP_GAN_LOSS_VALIDATION_STATUS = all(
    checks["Overall Valid"]
    for checks
    in SPP_GAN_LOSS_CHECKS.values()
)

print(
    f"Overall SPP-GAN Loss Validation : "
    f"{'PASS' if SPP_GAN_LOSS_VALIDATION_STATUS else 'FAIL'}"
)

# ==============================================================================
# DATASET FAILURE REPORT
# ==============================================================================

if not SPP_GAN_LOSS_VALIDATION_STATUS:

    failed_datasets = [
        dataset
        for dataset, checks
        in SPP_GAN_LOSS_CHECKS.items()
        if not checks["Overall Valid"]
    ]

    print()

    print(
        "Failed Datasets:"
    )

    for dataset in failed_datasets:

        print(
            f"  - {dataset}"
        )

    print()

    raise ValueError(
        "SPP-GAN loss function validation failed "
        f"for: {failed_datasets}"
    )

# ==============================================================================
# FINAL STATUS
# ==============================================================================

print()

print(
    "All SPP-GAN loss function checks passed."
)

print(
    "Generator and discriminator dimensions are compatible."
)

print(
    "Discriminator loss is numerically valid."
)

print(
    "Generator loss is numerically valid."
)

print(
    "Loss functions produce finite scalar values."
)

print()

print(
    "PART J5 — Loss function validation completed."
)

====================================================================================================
PART J5 — LOSS FUNCTION VALIDATION
====================================================================================================

Dataset                         : Adult Income
Generator Input Dimension       : 128
Configured Output Dimension     : 14
Actual Generator Output        : 14
Discriminator Input Dimension   : 14
Discriminator Output Dimension  : 1
Generator → Discriminator       : PASS
Configuration Consistency       : PASS
Generator Output Shape          : PASS
Real Logits Shape               : PASS
Fake Logits Shape               : PASS
Finite Forward Values           : PASS
Discriminator Loss              : 1.144034
Generator Loss                  : 0.215700
Finite Losses                   : PASS
Scalar Losses                   : PASS
Non-Negative Losses             : PASS
Overall                         : PASS

Dataset                         : Bank Marketing
Generator Input Dimension       : 128
Configured Output Dimension     : 16
Actual Generator Output        : 16
Discriminator Input Dimension   : 16
Discriminator Output Dimension  : 1
Generator → Discriminator       : PASS
Configuration Consistency       : PASS
Generator Output Shape          : PASS
Real Logits Shape               : PASS
Fake Logits Shape               : PASS
Finite Forward Values           : PASS
Discriminator Loss              : 0.874128
Generator Loss                  : 0.748317
Finite Losses                   : PASS
Scalar Losses                   : PASS
Non-Negative Losses             : PASS
Overall                         : PASS

Dataset                         : diabetes_130us
Generator Input Dimension       : 128
Configured Output Dimension     : 47
Actual Generator Output        : 47
Discriminator Input Dimension   : 47
Discriminator Output Dimension  : 1
Generator → Discriminator       : PASS
Configuration Consistency       : PASS
Generator Output Shape          : PASS
Real Logits Shape               : PASS
Fake Logits Shape               : PASS
Finite Forward Values           : PASS
Discriminator Loss              : 0.690212
Generator Loss                  : 0.893763
Finite Losses                   : PASS
Scalar Losses                   : PASS
Non-Negative Losses             : PASS
Overall                         : PASS

Overall SPP-GAN Loss Validation : PASS

All SPP-GAN loss function checks passed.
Generator and discriminator dimensions are compatible.
Discriminator loss is numerically valid.
Generator loss is numerically valid.
Loss functions produce finite scalar values.

PART J5 — Loss function validation completed.

In [148]:
# ==============================================================================
# PART J6 — SPP-GAN LOSS FUNCTION SUMMARY
# ==============================================================================

print("=" * 100)
print("PART J6 — SPP-GAN LOSS FUNCTION SUMMARY")
print("=" * 100)

# ==============================================================================
# FINAL LOSS VALIDATION STATUS
# ==============================================================================

SPP_GAN_LOSS_CONFIGURATION_STATUS = bool(
    SPP_GAN_LOSS_CONFIGURATION_VALID
)

SPP_GAN_LOSS_CRITERION_STATUS = bool(
    SPP_GAN_ADVERSARIAL_LOSS_VALID
)

SPP_GAN_LOSS_FUNCTION_STATUS = bool(
    SPP_GAN_LOSS_VALIDATION_STATUS
)

SPP_GAN_LOSS_FINAL_STATUS = bool(
    SPP_GAN_LOSS_CONFIGURATION_STATUS
    and
    SPP_GAN_LOSS_CRITERION_STATUS
    and
    SPP_GAN_LOSS_FUNCTION_STATUS
)

# ==============================================================================
# LOSS CONFIGURATION SUMMARY
# ==============================================================================

SPP_GAN_LOSS_SUMMARY = {

    "Adversarial Loss":
        SPP_GAN_LOSS_FUNCTION,

    "Discriminator Objective":
        "Real samples → real target; generated samples → fake target",

    "Generator Objective":
        "Generated samples → real target",

    "Real Label":
        float(
            SPP_GAN_REAL_LABEL
        ),

    "Fake Label":
        float(
            SPP_GAN_FAKE_LABEL
        ),

    "Label Smoothing":
        float(
            SPP_GAN_LABEL_SMOOTHING
        ),

    "Effective Real Target":
        float(
            SPP_GAN_EFFECTIVE_REAL_LABEL
        ),

    "Effective Fake Target":
        float(
            SPP_GAN_EFFECTIVE_FAKE_LABEL
        ),

    "Reduction":
        SPP_GAN_REDUCTION,

    "Discriminator Output":
        SPP_GAN_DISCRIMINATOR_OUTPUT_ACTIVATION,

    "Datasets Validated":
        len(DATASETS),

    "Loss Configuration Valid":
        SPP_GAN_LOSS_CONFIGURATION_STATUS,

    "Criterion Valid":
        SPP_GAN_LOSS_CRITERION_STATUS,

    "Loss Function Valid":
        SPP_GAN_LOSS_FUNCTION_STATUS,

    "Overall Loss Status":
        SPP_GAN_LOSS_FINAL_STATUS
}

# ==============================================================================
# SUMMARY DATAFRAME
# ==============================================================================

SPP_GAN_LOSS_SUMMARY_DF = pd.DataFrame(
    list(
        SPP_GAN_LOSS_SUMMARY.items()
    ),
    columns=[
        "Parameter",
        "Value"
    ]
)

print()

display(
    SPP_GAN_LOSS_SUMMARY_DF
)

# ==============================================================================
# DATASET-SPECIFIC LOSS VALIDATION SUMMARY
# ==============================================================================

print()

print(
    "Dataset-Specific Loss Validation:"
)

SPP_GAN_LOSS_DATASET_SUMMARY = []

for dataset in DATASETS:

    checks = (
        SPP_GAN_LOSS_CHECKS[
            dataset
        ]
    )

    # --------------------------------------------------------------------------
    # SAFE KEY ACCESS
    # --------------------------------------------------------------------------

    feature_dimension_valid = bool(
        checks.get(
            "Feature Dimension Valid",
            True
        )
    )

    generator_output_valid = bool(
        checks.get(
            "Generator Output Shape Valid",
            True
        )
    )

    real_logits_valid = bool(
        checks.get(
            "Real Logits Shape Valid",
            True
        )
    )

    fake_logits_valid = bool(
        checks.get(
            "Fake Logits Shape Valid",
            True
        )
    )

    generator_output_finite = bool(
        checks.get(
            "Generator Output Finite",
            True
        )
    )

    real_logits_finite = bool(
        checks.get(
            "Real Logits Finite",
            True
        )
    )

    fake_logits_finite = bool(
        checks.get(
            "Fake Logits Finite",
            True
        )
    )

    discriminator_loss_finite = bool(
        checks.get(
            "Discriminator Loss Finite",
            True
        )
    )

    generator_loss_finite = bool(
        checks.get(
            "Generator Loss Finite",
            True
        )
    )

    discriminator_loss_scalar = bool(
        checks.get(
            "Discriminator Loss Scalar",
            True
        )
    )

    generator_loss_scalar = bool(
        checks.get(
            "Generator Loss Scalar",
            True
        )
    )

    overall_valid = bool(
        checks.get(
            "Overall Valid",
            False
        )
    )

    discriminator_loss = checks.get(
        "Discriminator Loss",
        np.nan
    )

    generator_loss = checks.get(
        "Generator Loss",
        np.nan
    )

    finite_values_valid = (
        generator_output_finite
        and
        real_logits_finite
        and
        fake_logits_finite
    )

    finite_losses_valid = (
        discriminator_loss_finite
        and
        generator_loss_finite
    )

    scalar_losses_valid = (
        discriminator_loss_scalar
        and
        generator_loss_scalar
    )

    # --------------------------------------------------------------------------
    # DATASET SUMMARY
    # --------------------------------------------------------------------------

    SPP_GAN_LOSS_DATASET_SUMMARY.append({

        "Dataset":
            dataset,

        "Feature Dimension Valid":
            feature_dimension_valid,

        "Generator Output Valid":
            generator_output_valid,

        "Real Logits Valid":
            real_logits_valid,

        "Fake Logits Valid":
            fake_logits_valid,

        "Finite Values":
            finite_values_valid,

        "Discriminator Loss":
            discriminator_loss,

        "Generator Loss":
            generator_loss,

        "Losses Finite":
            finite_losses_valid,

        "Losses Scalar":
            scalar_losses_valid,

        "Overall Valid":
            overall_valid
    })

# ==============================================================================
# DATASET SUMMARY DATAFRAME
# ==============================================================================

SPP_GAN_LOSS_DATASET_SUMMARY_DF = pd.DataFrame(
    SPP_GAN_LOSS_DATASET_SUMMARY
)

print()

display(
    SPP_GAN_LOSS_DATASET_SUMMARY_DF
)

# ==============================================================================
# FINAL STATUS REPORT
# ==============================================================================

print()

print(
    f"Loss Configuration Status      : "
    f"{'PASS' if SPP_GAN_LOSS_CONFIGURATION_STATUS else 'FAIL'}"
)

print(
    f"Adversarial Criterion Status   : "
    f"{'PASS' if SPP_GAN_LOSS_CRITERION_STATUS else 'FAIL'}"
)

print(
    f"Loss Function Validation       : "
    f"{'PASS' if SPP_GAN_LOSS_FUNCTION_STATUS else 'FAIL'}"
)

print()

print(
    f"Overall Loss Configuration     : "
    f"{'PASS' if SPP_GAN_LOSS_FINAL_STATUS else 'FAIL'}"
)

# ==============================================================================
# FAIL-FAST PIPELINE CHECK
# ==============================================================================

if not SPP_GAN_LOSS_FINAL_STATUS:

    failed_datasets = [
        dataset
        for dataset, checks
        in SPP_GAN_LOSS_CHECKS.items()
        if not checks.get(
            "Overall Valid",
            False
        )
    ]

    raise ValueError(
        "SPP-GAN loss module validation failed."
        +
        (
            f" Failed datasets: {failed_datasets}"
            if failed_datasets
            else ""
        )
    )

# ==============================================================================
# COMPLETION MESSAGE
# ==============================================================================

print()

print(
    "All SPP-GAN loss configuration, criterion, "
    "and numerical validation checks passed."
)

print()

print(
    "The SPP-GAN adversarial loss module is "
    "ready for subsequent private training."
)

print()

print(
    "PART J6 — SPP-GAN loss function summary completed."
)

====================================================================================================
PART J6 — SPP-GAN LOSS FUNCTION SUMMARY
====================================================================================================

,Parameter,Value
0,Adversarial Loss,Binary Cross-Entropy with Logits
1,Discriminator Objective,Real samples → real target; generated samples ...
2,Generator Objective,Generated samples → real target
3,Real Label,1.0
4,Fake Label,0.0
5,Label Smoothing,0.1
6,Effective Real Target,1.0
7,Effective Fake Target,0.0
8,Reduction,mean
9,Discriminator Output,Linear
10,Datasets Validated,3
11,Loss Configuration Valid,True
12,Criterion Valid,True
13,Loss Function Valid,True
14,Overall Loss Status,True

Dataset-Specific Loss Validation:

,Dataset,Feature Dimension Valid,Generator Output Valid,Real Logits Valid,Fake Logits Valid,Finite Values,Discriminator Loss,Generator Loss,Losses Finite,Losses Scalar,Overall Valid
0,Adult Income,True,True,True,True,True,1.144034,0.215700,True,True,True
1,Bank Marketing,True,True,True,True,True,0.874128,0.748317,True,True,True
2,diabetes_130us,True,True,True,True,True,0.690212,0.893763,True,True,True

Loss Configuration Status      : PASS
Adversarial Criterion Status   : PASS
Loss Function Validation       : PASS

Overall Loss Configuration     : PASS

All SPP-GAN loss configuration, criterion, and numerical validation checks passed.

The SPP-GAN adversarial loss module is ready for subsequent private training.

PART J6 — SPP-GAN loss function summary completed.

In [156]:
# ==============================================================================
# PART K1 — SPP-GAN OPTIMIZER CONFIGURATION
# ==============================================================================

print("=" * 100)
print("PART K1 — SPP-GAN OPTIMIZER CONFIGURATION")
print("=" * 100)

# ==============================================================================
# LOAD OPTIMIZER CONFIGURATION
# ==============================================================================

SPP_GAN_OPTIMIZER_NAME = str(
    PROJECT_CONFIG["optimizer"]
).strip()

SPP_GAN_LEARNING_RATE = float(
    PROJECT_CONFIG["learning_rate"]
)

SPP_GAN_BETA1 = float(
    PROJECT_CONFIG["beta1"]
)

SPP_GAN_BETA2 = float(
    PROJECT_CONFIG["beta2"]
)

# ==============================================================================
# OPTIMIZER NAME VALIDATION
# ==============================================================================

SPP_GAN_OPTIMIZER_NAME_NORMALIZED = (
    SPP_GAN_OPTIMIZER_NAME.lower()
)

SPP_GAN_SUPPORTED_OPTIMIZERS = (
    "adam",
)

SPP_GAN_OPTIMIZER_NAME_VALID = (
    SPP_GAN_OPTIMIZER_NAME_NORMALIZED
    in
    SPP_GAN_SUPPORTED_OPTIMIZERS
)

# ==============================================================================
# NUMERICAL VALIDATION
# ==============================================================================

SPP_GAN_LEARNING_RATE_VALID = (
    np.isfinite(
        SPP_GAN_LEARNING_RATE
    )
    and
    SPP_GAN_LEARNING_RATE > 0.0
)

SPP_GAN_BETA1_VALID = (
    np.isfinite(
        SPP_GAN_BETA1
    )
    and
    0.0 <= SPP_GAN_BETA1 < 1.0
)

SPP_GAN_BETA2_VALID = (
    np.isfinite(
        SPP_GAN_BETA2
    )
    and
    0.0 <= SPP_GAN_BETA2 < 1.0
)

SPP_GAN_BETA_ORDER_VALID = (
    SPP_GAN_BETA1
    <
    SPP_GAN_BETA2
)

# ==============================================================================
# OVERALL CONFIGURATION VALIDATION
# ==============================================================================

SPP_GAN_OPTIMIZER_CONFIGURATION_VALID = (
    SPP_GAN_OPTIMIZER_NAME_VALID
    and
    SPP_GAN_LEARNING_RATE_VALID
    and
    SPP_GAN_BETA1_VALID
    and
    SPP_GAN_BETA2_VALID
    and
    SPP_GAN_BETA_ORDER_VALID
)

# ==============================================================================
# CONFIGURATION REPORT
# ==============================================================================

print()

print(
    f"Optimizer                 : "
    f"{SPP_GAN_OPTIMIZER_NAME}"
)

print(
    f"Learning Rate             : "
    f"{SPP_GAN_LEARNING_RATE:.8f}"
)

print(
    f"Adam β1                   : "
    f"{SPP_GAN_BETA1:.6f}"
)

print(
    f"Adam β2                   : "
    f"{SPP_GAN_BETA2:.6f}"
)

print()

print(
    f"Optimizer Name            : "
    f"{'PASS' if SPP_GAN_OPTIMIZER_NAME_VALID else 'FAIL'}"
)

print(
    f"Learning Rate             : "
    f"{'PASS' if SPP_GAN_LEARNING_RATE_VALID else 'FAIL'}"
)

print(
    f"Adam β1                   : "
    f"{'PASS' if SPP_GAN_BETA1_VALID else 'FAIL'}"
)

print(
    f"Adam β2                   : "
    f"{'PASS' if SPP_GAN_BETA2_VALID else 'FAIL'}"
)

print(
    f"Beta Ordering             : "
    f"{'PASS' if SPP_GAN_BETA_ORDER_VALID else 'FAIL'}"
)

print()

print(
    f"Overall Configuration     : "
    f"{'PASS' if SPP_GAN_OPTIMIZER_CONFIGURATION_VALID else 'FAIL'}"
)

# ==============================================================================
# FAIL-FAST VALIDATION
# ==============================================================================

if not SPP_GAN_OPTIMIZER_CONFIGURATION_VALID:

    raise ValueError(
        "SPP-GAN optimizer configuration validation failed."
    )

print()

print(
    "SPP-GAN optimizer configuration validated successfully."
)

print()

print(
    "PART K1 — Optimizer configuration completed."
)

====================================================================================================
PART K1 — SPP-GAN OPTIMIZER CONFIGURATION
====================================================================================================

Optimizer                 : Adam
Learning Rate             : 0.00020000
Adam β1                   : 0.500000
Adam β2                   : 0.999000

Optimizer Name            : PASS
Learning Rate             : PASS
Adam β1                   : PASS
Adam β2                   : PASS
Beta Ordering             : PASS

Overall Configuration     : PASS

SPP-GAN optimizer configuration validated successfully.

PART K1 — Optimizer configuration completed.

In [157]:
# ==============================================================================
# PART K2 — OPTIMIZER CONFIGURATION VALIDATION
# ==============================================================================

print("=" * 100)
print("PART K2 — OPTIMIZER CONFIGURATION VALIDATION")
print("=" * 100)

# ==============================================================================
# OPTIMIZER TYPE VALIDATION
# ==============================================================================

SPP_GAN_OPTIMIZER_DEFINED = (
    isinstance(
        SPP_GAN_OPTIMIZER_NAME,
        str
    )
    and
    len(
        SPP_GAN_OPTIMIZER_NAME.strip()
    ) > 0
)

SPP_GAN_OPTIMIZER_SUPPORTED = (
    SPP_GAN_OPTIMIZER_NAME_NORMALIZED
    in
    SPP_GAN_SUPPORTED_OPTIMIZERS
)

# ==============================================================================
# NUMERICAL FINITENESS
# ==============================================================================

SPP_GAN_LEARNING_RATE_FINITE = bool(
    np.isfinite(
        SPP_GAN_LEARNING_RATE
    )
)

SPP_GAN_BETA1_FINITE = bool(
    np.isfinite(
        SPP_GAN_BETA1
    )
)

SPP_GAN_BETA2_FINITE = bool(
    np.isfinite(
        SPP_GAN_BETA2
    )
)

# ==============================================================================
# STRUCTURED VALIDATION CHECKS
# ==============================================================================

SPP_GAN_OPTIMIZER_CHECKS = {

    "Optimizer Defined":
        SPP_GAN_OPTIMIZER_DEFINED,

    "Optimizer Supported":
        SPP_GAN_OPTIMIZER_SUPPORTED,

    "Learning Rate Type":
        isinstance(
            SPP_GAN_LEARNING_RATE,
            (int, float, np.number)
        ),

    "Learning Rate Positive":
        SPP_GAN_LEARNING_RATE > 0.0,

    "Learning Rate Finite":
        SPP_GAN_LEARNING_RATE_FINITE,

    "Beta1 Type":
        isinstance(
            SPP_GAN_BETA1,
            (int, float, np.number)
        ),

    "Beta1 Range":
        0.0 <= SPP_GAN_BETA1 < 1.0,

    "Beta1 Finite":
        SPP_GAN_BETA1_FINITE,

    "Beta2 Type":
        isinstance(
            SPP_GAN_BETA2,
            (int, float, np.number)
        ),

    "Beta2 Range":
        0.0 <= SPP_GAN_BETA2 < 1.0,

    "Beta2 Finite":
        SPP_GAN_BETA2_FINITE,

    "Beta Ordering":
        SPP_GAN_BETA1 < SPP_GAN_BETA2
}

# ==============================================================================
# VALIDATION REPORT
# ==============================================================================

print()

for check, status in SPP_GAN_OPTIMIZER_CHECKS.items():

    print(
        f"{check:30s} : "
        f"{'PASS' if status else 'FAIL'}"
    )

# ==============================================================================
# OVERALL VALIDATION STATUS
# ==============================================================================

SPP_GAN_OPTIMIZER_VALIDATION_STATUS = (
    all(
        SPP_GAN_OPTIMIZER_CHECKS.values()
    )
)

print()

print(
    f"Overall Optimizer Validation : "
    f"{'PASS' if SPP_GAN_OPTIMIZER_VALIDATION_STATUS else 'FAIL'}"
)

# ==============================================================================
# FAIL-FAST VALIDATION
# ==============================================================================

if not SPP_GAN_OPTIMIZER_VALIDATION_STATUS:

    failed_checks = [
        check
        for check, status
        in SPP_GAN_OPTIMIZER_CHECKS.items()
        if not status
    ]

    raise ValueError(
        "SPP-GAN optimizer configuration validation failed. "
        f"Failed checks: {failed_checks}"
    )

print()

print(
    "All SPP-GAN optimizer configuration checks passed."
)

print()

print(
    "PART K2 — Optimizer configuration validation completed."
)

====================================================================================================
PART K2 — OPTIMIZER CONFIGURATION VALIDATION
====================================================================================================

Optimizer Defined              : PASS
Optimizer Supported            : PASS
Learning Rate Type             : PASS
Learning Rate Positive         : PASS
Learning Rate Finite           : PASS
Beta1 Type                     : PASS
Beta1 Range                    : PASS
Beta1 Finite                   : PASS
Beta2 Type                     : PASS
Beta2 Range                    : PASS
Beta2 Finite                   : PASS
Beta Ordering                  : PASS

Overall Optimizer Validation : PASS

All SPP-GAN optimizer configuration checks passed.

PART K2 — Optimizer configuration validation completed.

In [158]:
# ==============================================================================
# PART K3 — DATASET-SPECIFIC OPTIMIZER INITIALIZATION
# ==============================================================================

print("=" * 100)
print("PART K3 — DATASET-SPECIFIC OPTIMIZER INITIALIZATION")
print("=" * 100)

# ==============================================================================
# OPTIMIZER CONTAINERS
# ==============================================================================

SPP_GAN_GENERATOR_OPTIMIZERS = {}

SPP_GAN_DISCRIMINATOR_OPTIMIZERS = {}

SPP_GAN_OPTIMIZER_INITIALIZATION_CHECKS = {}

# ==============================================================================
# DATASET-SPECIFIC INITIALIZATION
# ==============================================================================

for dataset in DATASETS:

    generator = SPP_GAN_GENERATORS[dataset]

    discriminator = SPP_GAN_DISCRIMINATORS[dataset]

    # --------------------------------------------------------------------------
    # Dataset-Specific GAN Feature Dimension
    # --------------------------------------------------------------------------

    gan_feature_dimension = int(
        SPP_GAN_INPUT_DIMENSIONS[dataset]
    )

    discriminator_input_dimension = int(
        SPP_GAN_DISCRIMINATOR_INPUT_DIMENSIONS[dataset]
    )

    if gan_feature_dimension != discriminator_input_dimension:

        raise ValueError(
            f"{dataset}: GAN feature dimension "
            f"{gan_feature_dimension} does not match "
            f"discriminator input dimension "
            f"{discriminator_input_dimension}."
        )

    # --------------------------------------------------------------------------
    # Trainable Parameter Detection
    # --------------------------------------------------------------------------

    generator_parameters = [
        parameter
        for parameter in generator.parameters()
        if parameter.requires_grad
    ]

    discriminator_parameters = [
        parameter
        for parameter in discriminator.parameters()
        if parameter.requires_grad
    ]

    generator_trainable_parameters_valid = (
        len(generator_parameters) > 0
    )

    discriminator_trainable_parameters_valid = (
        len(discriminator_parameters) > 0
    )

    if not generator_trainable_parameters_valid:

        raise ValueError(
            f"{dataset}: Generator has no trainable parameters."
        )

    if not discriminator_trainable_parameters_valid:

        raise ValueError(
            f"{dataset}: Discriminator has no trainable parameters."
        )

    # --------------------------------------------------------------------------
    # Optimizer Initialization
    # --------------------------------------------------------------------------

    if SPP_GAN_OPTIMIZER_NAME_NORMALIZED == "adam":

        generator_optimizer = torch.optim.Adam(
            generator_parameters,
            lr=SPP_GAN_LEARNING_RATE,
            betas=(
                SPP_GAN_BETA1,
                SPP_GAN_BETA2
            ),
            weight_decay=0.0
        )

        discriminator_optimizer = torch.optim.Adam(
            discriminator_parameters,
            lr=SPP_GAN_LEARNING_RATE,
            betas=(
                SPP_GAN_BETA1,
                SPP_GAN_BETA2
            ),
            weight_decay=0.0
        )

    else:

        raise ValueError(
            f"Unsupported SPP-GAN optimizer: "
            f"{SPP_GAN_OPTIMIZER_NAME}"
        )

    # --------------------------------------------------------------------------
    # Store Optimizers
    # --------------------------------------------------------------------------

    SPP_GAN_GENERATOR_OPTIMIZERS[dataset] = (
        generator_optimizer
    )

    SPP_GAN_DISCRIMINATOR_OPTIMIZERS[dataset] = (
        discriminator_optimizer
    )

    # --------------------------------------------------------------------------
    # Parameter Registration Validation
    # --------------------------------------------------------------------------

    generator_optimizer_parameters = [
        parameter
        for group in generator_optimizer.param_groups
        for parameter in group["params"]
    ]

    discriminator_optimizer_parameters = [
        parameter
        for group in discriminator_optimizer.param_groups
        for parameter in group["params"]
    ]

    generator_parameter_identity_valid = (
        len(generator_optimizer_parameters)
        ==
        len(generator_parameters)
        and
        all(
            optimizer_parameter is model_parameter
            for optimizer_parameter, model_parameter
            in zip(
                generator_optimizer_parameters,
                generator_parameters
            )
        )
    )

    discriminator_parameter_identity_valid = (
        len(discriminator_optimizer_parameters)
        ==
        len(discriminator_parameters)
        and
        all(
            optimizer_parameter is model_parameter
            for optimizer_parameter, model_parameter
            in zip(
                discriminator_optimizer_parameters,
                discriminator_parameters
            )
        )
    )

    # --------------------------------------------------------------------------
    # Optimizer Group Validation
    # --------------------------------------------------------------------------

    generator_optimizer_valid = (
        isinstance(
            generator_optimizer,
            torch.optim.Optimizer
        )
        and
        len(
            generator_optimizer.param_groups
        ) > 0
    )

    discriminator_optimizer_valid = (
        isinstance(
            discriminator_optimizer,
            torch.optim.Optimizer
        )
        and
        len(
            discriminator_optimizer.param_groups
        ) > 0
    )

    initialization_valid = (
        generator_trainable_parameters_valid
        and
        discriminator_trainable_parameters_valid
        and
        generator_optimizer_valid
        and
        discriminator_optimizer_valid
        and
        generator_parameter_identity_valid
        and
        discriminator_parameter_identity_valid
    )

    # --------------------------------------------------------------------------
    # Store Checks
    # --------------------------------------------------------------------------

    SPP_GAN_OPTIMIZER_INITIALIZATION_CHECKS[dataset] = {

        "Generator Trainable Parameters":
            generator_trainable_parameters_valid,

        "Discriminator Trainable Parameters":
            discriminator_trainable_parameters_valid,

        "Generator Optimizer Valid":
            generator_optimizer_valid,

        "Discriminator Optimizer Valid":
            discriminator_optimizer_valid,

        "Generator Parameter Registration":
            generator_parameter_identity_valid,

        "Discriminator Parameter Registration":
            discriminator_parameter_identity_valid,

        "Initialization Valid":
            initialization_valid
    }

    # --------------------------------------------------------------------------
    # Report
    # --------------------------------------------------------------------------

    print()

    print(
        f"Dataset                         : {dataset}"
    )

    print(
        f"GAN Feature Dimension           : "
        f"{gan_feature_dimension}"
    )

    print(
        f"Generator Optimizer             : "
        f"{type(generator_optimizer).__name__}"
    )

    print(
        f"Discriminator Optimizer         : "
        f"{type(discriminator_optimizer).__name__}"
    )

    print(
        f"Learning Rate                   : "
        f"{SPP_GAN_LEARNING_RATE:.8f}"
    )

    print(
        f"Adam β1                         : "
        f"{SPP_GAN_BETA1:.6f}"
    )

    print(
        f"Adam β2                         : "
        f"{SPP_GAN_BETA2:.6f}"
    )

    print(
        f"Generator Parameters            : "
        f"{sum(p.numel() for p in generator_parameters):,}"
    )

    print(
        f"Discriminator Parameters        : "
        f"{sum(p.numel() for p in discriminator_parameters):,}"
    )

    print(
        f"Generator Optimizer             : "
        f"{'PASS' if generator_optimizer_valid else 'FAIL'}"
    )

    print(
        f"Discriminator Optimizer         : "
        f"{'PASS' if discriminator_optimizer_valid else 'FAIL'}"
    )

    print(
        f"Generator Parameter Registration: "
        f"{'PASS' if generator_parameter_identity_valid else 'FAIL'}"
    )

    print(
        f"Discriminator Parameter Register : "
        f"{'PASS' if discriminator_parameter_identity_valid else 'FAIL'}"
    )

    print(
        f"Initialization Status           : "
        f"{'PASS' if initialization_valid else 'FAIL'}"
    )

# ==============================================================================
# OVERALL INITIALIZATION STATUS
# ==============================================================================

SPP_GAN_OPTIMIZER_INITIALIZATION_STATUS = (
    len(SPP_GAN_GENERATOR_OPTIMIZERS)
    ==
    len(DATASETS)
    and
    len(SPP_GAN_DISCRIMINATOR_OPTIMIZERS)
    ==
    len(DATASETS)
    and
    all(
        checks["Initialization Valid"]
        for checks
        in SPP_GAN_OPTIMIZER_INITIALIZATION_CHECKS.values()
    )
)

print()

print(
    f"Overall Optimizer Initialization : "
    f"{'PASS' if SPP_GAN_OPTIMIZER_INITIALIZATION_STATUS else 'FAIL'}"
)

# ==============================================================================
# FAIL-FAST VALIDATION
# ==============================================================================

if not SPP_GAN_OPTIMIZER_INITIALIZATION_STATUS:

    failed_datasets = [
        dataset
        for dataset, checks
        in SPP_GAN_OPTIMIZER_INITIALIZATION_CHECKS.items()
        if not checks["Initialization Valid"]
    ]

    raise ValueError(
        "SPP-GAN optimizer initialization failed "
        f"for datasets: {failed_datasets}"
    )

print()

print(
    "All dataset-specific SPP-GAN optimizers initialized successfully."
)

print()

print(
    "PART K3 — Dataset-specific optimizer initialization completed."
)

====================================================================================================
PART K3 — DATASET-SPECIFIC OPTIMIZER INITIALIZATION
====================================================================================================

Dataset                         : Adult Income
GAN Feature Dimension           : 14
Generator Optimizer             : Adam
Discriminator Optimizer         : Adam
Learning Rate                   : 0.00020000
Adam β1                         : 0.500000
Adam β2                         : 0.999000
Generator Parameters            : 103,438
Discriminator Parameters        : 37,633
Generator Optimizer             : PASS
Discriminator Optimizer         : PASS
Generator Parameter Registration: PASS
Discriminator Parameter Register : PASS
Initialization Status           : PASS

Dataset                         : Bank Marketing
GAN Feature Dimension           : 16
Generator Optimizer             : Adam
Discriminator Optimizer         : Adam
Learning Rate                   : 0.00020000
Adam β1                         : 0.500000
Adam β2                         : 0.999000
Generator Parameters            : 103,952
Discriminator Parameters        : 38,145
Generator Optimizer             : PASS
Discriminator Optimizer         : PASS
Generator Parameter Registration: PASS
Discriminator Parameter Register : PASS
Initialization Status           : PASS

Dataset                         : diabetes_130us
GAN Feature Dimension           : 47
Generator Optimizer             : Adam
Discriminator Optimizer         : Adam
Learning Rate                   : 0.00020000
Adam β1                         : 0.500000
Adam β2                         : 0.999000
Generator Parameters            : 111,919
Discriminator Parameters        : 46,081
Generator Optimizer             : PASS
Discriminator Optimizer         : PASS
Generator Parameter Registration: PASS
Discriminator Parameter Register : PASS
Initialization Status           : PASS

Overall Optimizer Initialization : PASS

All dataset-specific SPP-GAN optimizers initialized successfully.

PART K3 — Dataset-specific optimizer initialization completed.

In [159]:
# ==============================================================================
# PART K4 — OPTIMIZER PARAMETER VALIDATION
# ==============================================================================

print("=" * 100)
print("PART K4 — OPTIMIZER PARAMETER VALIDATION")
print("=" * 100)

SPP_GAN_OPTIMIZER_PARAMETER_CHECKS = {}

# ==============================================================================
# DATASET-SPECIFIC VALIDATION
# ==============================================================================

for dataset in DATASETS:

    generator = SPP_GAN_GENERATORS[dataset]

    discriminator = SPP_GAN_DISCRIMINATORS[dataset]

    generator_optimizer = (
        SPP_GAN_GENERATOR_OPTIMIZERS[dataset]
    )

    discriminator_optimizer = (
        SPP_GAN_DISCRIMINATOR_OPTIMIZERS[dataset]
    )

    # --------------------------------------------------------------------------
    # Optimizer Type
    # --------------------------------------------------------------------------

    generator_optimizer_type_valid = (
        isinstance(
            generator_optimizer,
            torch.optim.Adam
        )
        if SPP_GAN_OPTIMIZER_NAME_NORMALIZED == "adam"
        else False
    )

    discriminator_optimizer_type_valid = (
        isinstance(
            discriminator_optimizer,
            torch.optim.Adam
        )
        if SPP_GAN_OPTIMIZER_NAME_NORMALIZED == "adam"
        else False
    )

    # --------------------------------------------------------------------------
    # Parameter Groups
    # --------------------------------------------------------------------------

    generator_parameter_groups_valid = (
        len(
            generator_optimizer.param_groups
        ) > 0
    )

    discriminator_parameter_groups_valid = (
        len(
            discriminator_optimizer.param_groups
        ) > 0
    )

    # --------------------------------------------------------------------------
    # Learning Rate
    # --------------------------------------------------------------------------

    generator_learning_rates = [
        float(group["lr"])
        for group
        in generator_optimizer.param_groups
    ]

    discriminator_learning_rates = [
        float(group["lr"])
        for group
        in discriminator_optimizer.param_groups
    ]

    generator_lr_valid = (
        all(
            np.isclose(
                lr,
                SPP_GAN_LEARNING_RATE,
                rtol=0.0,
                atol=1e-12
            )
            for lr
            in generator_learning_rates
        )
    )

    discriminator_lr_valid = (
        all(
            np.isclose(
                lr,
                SPP_GAN_LEARNING_RATE,
                rtol=0.0,
                atol=1e-12
            )
            for lr
            in discriminator_learning_rates
        )
    )

    # --------------------------------------------------------------------------
    # Adam Betas
    # --------------------------------------------------------------------------

    generator_betas = [
        tuple(group["betas"])
        for group
        in generator_optimizer.param_groups
    ]

    discriminator_betas = [
        tuple(group["betas"])
        for group
        in discriminator_optimizer.param_groups
    ]

    expected_betas = (
        SPP_GAN_BETA1,
        SPP_GAN_BETA2
    )

    generator_betas_valid = (
        all(
            np.allclose(
                betas,
                expected_betas,
                rtol=0.0,
                atol=1e-12
            )
            for betas
            in generator_betas
        )
    )

    discriminator_betas_valid = (
        all(
            np.allclose(
                betas,
                expected_betas,
                rtol=0.0,
                atol=1e-12
            )
            for betas
            in discriminator_betas
        )
    )

    # --------------------------------------------------------------------------
    # Weight Decay
    # --------------------------------------------------------------------------

    generator_weight_decay_valid = (
        all(
            np.isclose(
                float(
                    group.get(
                        "weight_decay",
                        0.0
                    )
                ),
                0.0
            )
            for group
            in generator_optimizer.param_groups
        )
    )

    discriminator_weight_decay_valid = (
        all(
            np.isclose(
                float(
                    group.get(
                        "weight_decay",
                        0.0
                    )
                ),
                0.0
            )
            for group
            in discriminator_optimizer.param_groups
        )
    )

    # --------------------------------------------------------------------------
    # Parameter Identity Validation
    # --------------------------------------------------------------------------

    generator_model_parameters = [
        parameter
        for parameter
        in generator.parameters()
        if parameter.requires_grad
    ]

    discriminator_model_parameters = [
        parameter
        for parameter
        in discriminator.parameters()
        if parameter.requires_grad
    ]

    generator_optimizer_parameters = [
        parameter
        for group
        in generator_optimizer.param_groups
        for parameter
        in group["params"]
    ]

    discriminator_optimizer_parameters = [
        parameter
        for group
        in discriminator_optimizer.param_groups
        for parameter
        in group["params"]
    ]

    generator_parameter_registration_valid = (
        len(generator_optimizer_parameters)
        ==
        len(generator_model_parameters)
        and
        all(
            optimizer_parameter is model_parameter
            for optimizer_parameter, model_parameter
            in zip(
                generator_optimizer_parameters,
                generator_model_parameters
            )
        )
    )

    discriminator_parameter_registration_valid = (
        len(discriminator_optimizer_parameters)
        ==
        len(discriminator_model_parameters)
        and
        all(
            optimizer_parameter is model_parameter
            for optimizer_parameter, model_parameter
            in zip(
                discriminator_optimizer_parameters,
                discriminator_model_parameters
            )
        )
    )

    # --------------------------------------------------------------------------
    # Overall Validation
    # --------------------------------------------------------------------------

    optimizer_valid = (
        generator_optimizer_type_valid
        and
        discriminator_optimizer_type_valid
        and
        generator_parameter_groups_valid
        and
        discriminator_parameter_groups_valid
        and
        generator_lr_valid
        and
        discriminator_lr_valid
        and
        generator_betas_valid
        and
        discriminator_betas_valid
        and
        generator_weight_decay_valid
        and
        discriminator_weight_decay_valid
        and
        generator_parameter_registration_valid
        and
        discriminator_parameter_registration_valid
    )

    # --------------------------------------------------------------------------
    # Store Validation
    # --------------------------------------------------------------------------

    SPP_GAN_OPTIMIZER_PARAMETER_CHECKS[dataset] = {

        "Generator Optimizer Type Valid":
            generator_optimizer_type_valid,

        "Discriminator Optimizer Type Valid":
            discriminator_optimizer_type_valid,

        "Generator Parameter Groups Valid":
            generator_parameter_groups_valid,

        "Discriminator Parameter Groups Valid":
            discriminator_parameter_groups_valid,

        "Generator Learning Rate Valid":
            generator_lr_valid,

        "Discriminator Learning Rate Valid":
            discriminator_lr_valid,

        "Generator Betas Valid":
            generator_betas_valid,

        "Discriminator Betas Valid":
            discriminator_betas_valid,

        "Generator Weight Decay Valid":
            generator_weight_decay_valid,

        "Discriminator Weight Decay Valid":
            discriminator_weight_decay_valid,

        "Generator Parameter Registration Valid":
            generator_parameter_registration_valid,

        "Discriminator Parameter Registration Valid":
            discriminator_parameter_registration_valid,

        "Optimizer Valid":
            optimizer_valid
    }

    # --------------------------------------------------------------------------
    # Report
    # --------------------------------------------------------------------------

    print()

    print(
        f"Dataset                         : {dataset}"
    )

    print(
        f"Generator Optimizer             : "
        f"{type(generator_optimizer).__name__}"
    )

    print(
        f"Discriminator Optimizer         : "
        f"{type(discriminator_optimizer).__name__}"
    )

    print(
        f"Generator Learning Rates        : "
        f"{generator_learning_rates}"
    )

    print(
        f"Discriminator Learning Rates    : "
        f"{discriminator_learning_rates}"
    )

    print(
        f"Generator Betas                 : "
        f"{generator_betas}"
    )

    print(
        f"Discriminator Betas             : "
        f"{discriminator_betas}"
    )

    print(
        f"Generator Trainable Parameters  : "
        f"{sum(p.numel() for p in generator_model_parameters):,}"
    )

    print(
        f"Generator Optimizer Parameters  : "
        f"{sum(p.numel() for p in generator_optimizer_parameters):,}"
    )

    print(
        f"Discriminator Trainable Params  : "
        f"{sum(p.numel() for p in discriminator_model_parameters):,}"
    )

    print(
        f"Discriminator Optimizer Params  : "
        f"{sum(p.numel() for p in discriminator_optimizer_parameters):,}"
    )

    print()

    print(
        f"Optimizer Type                  : "
        f"{'PASS' if (generator_optimizer_type_valid and discriminator_optimizer_type_valid) else 'FAIL'}"
    )

    print(
        f"Learning Rate                   : "
        f"{'PASS' if (generator_lr_valid and discriminator_lr_valid) else 'FAIL'}"
    )

    print(
        f"Adam Betas                      : "
        f"{'PASS' if (generator_betas_valid and discriminator_betas_valid) else 'FAIL'}"
    )

    print(
        f"Weight Decay                    : "
        f"{'PASS' if (generator_weight_decay_valid and discriminator_weight_decay_valid) else 'FAIL'}"
    )

    print(
        f"Parameter Registration          : "
        f"{'PASS' if (generator_parameter_registration_valid and discriminator_parameter_registration_valid) else 'FAIL'}"
    )

    print(
        f"Overall                         : "
        f"{'PASS' if optimizer_valid else 'FAIL'}"
    )

# ==============================================================================
# OVERALL VALIDATION
# ==============================================================================

SPP_GAN_OPTIMIZER_PARAMETER_VALIDATION_STATUS = (
    len(SPP_GAN_OPTIMIZER_PARAMETER_CHECKS)
    ==
    len(DATASETS)
    and
    all(
        checks["Optimizer Valid"]
        for checks
        in SPP_GAN_OPTIMIZER_PARAMETER_CHECKS.values()
    )
)

print()

print(
    f"Overall Optimizer Parameter Validation : "
    f"{'PASS' if SPP_GAN_OPTIMIZER_PARAMETER_VALIDATION_STATUS else 'FAIL'}"
)

# ==============================================================================
# FAIL-FAST
# ==============================================================================

if not SPP_GAN_OPTIMIZER_PARAMETER_VALIDATION_STATUS:

    failed_datasets = [
        dataset
        for dataset, checks
        in SPP_GAN_OPTIMIZER_PARAMETER_CHECKS.items()
        if not checks["Optimizer Valid"]
    ]

    raise ValueError(
        "SPP-GAN optimizer parameter validation failed "
        f"for datasets: {failed_datasets}"
    )

print()

print(
    "All SPP-GAN optimizer parameter checks passed."
)

print()

print(
    "PART K4 — Optimizer parameter validation completed."
)

====================================================================================================
PART K4 — OPTIMIZER PARAMETER VALIDATION
====================================================================================================

Dataset                         : Adult Income
Generator Optimizer             : Adam
Discriminator Optimizer         : Adam
Generator Learning Rates        : [0.0002]
Discriminator Learning Rates    : [0.0002]
Generator Betas                 : [(0.5, 0.999)]
Discriminator Betas             : [(0.5, 0.999)]
Generator Trainable Parameters  : 103,438
Generator Optimizer Parameters  : 103,438
Discriminator Trainable Params  : 37,633
Discriminator Optimizer Params  : 37,633

Optimizer Type                  : PASS
Learning Rate                   : PASS
Adam Betas                      : PASS
Weight Decay                    : PASS
Parameter Registration          : PASS
Overall                         : PASS

Dataset                         : Bank Marketing
Generator Optimizer             : Adam
Discriminator Optimizer         : Adam
Generator Learning Rates        : [0.0002]
Discriminator Learning Rates    : [0.0002]
Generator Betas                 : [(0.5, 0.999)]
Discriminator Betas             : [(0.5, 0.999)]
Generator Trainable Parameters  : 103,952
Generator Optimizer Parameters  : 103,952
Discriminator Trainable Params  : 38,145
Discriminator Optimizer Params  : 38,145

Optimizer Type                  : PASS
Learning Rate                   : PASS
Adam Betas                      : PASS
Weight Decay                    : PASS
Parameter Registration          : PASS
Overall                         : PASS

Dataset                         : diabetes_130us
Generator Optimizer             : Adam
Discriminator Optimizer         : Adam
Generator Learning Rates        : [0.0002]
Discriminator Learning Rates    : [0.0002]
Generator Betas                 : [(0.5, 0.999)]
Discriminator Betas             : [(0.5, 0.999)]
Generator Trainable Parameters  : 111,919
Generator Optimizer Parameters  : 111,919
Discriminator Trainable Params  : 46,081
Discriminator Optimizer Params  : 46,081

Optimizer Type                  : PASS
Learning Rate                   : PASS
Adam Betas                      : PASS
Weight Decay                    : PASS
Parameter Registration          : PASS
Overall                         : PASS

Overall Optimizer Parameter Validation : PASS

All SPP-GAN optimizer parameter checks passed.

PART K4 — Optimizer parameter validation completed.

In [160]:
# ==============================================================================
# PART K5 — OPTIMIZER GRADIENT UPDATE TEST
# ==============================================================================

print("=" * 100)
print("PART K5 — OPTIMIZER GRADIENT UPDATE TEST")
print("=" * 100)

import copy

SPP_GAN_OPTIMIZER_GRADIENT_CHECKS = {}

test_batch_size = 4

# ==============================================================================
# DATASET-SPECIFIC GRADIENT UPDATE TEST
# ==============================================================================

for dataset in DATASETS:

    generator = SPP_GAN_GENERATORS[dataset]

    discriminator = SPP_GAN_DISCRIMINATORS[dataset]

    generator_optimizer = (
        SPP_GAN_GENERATOR_OPTIMIZERS[dataset]
    )

    discriminator_optimizer = (
        SPP_GAN_DISCRIMINATOR_OPTIMIZERS[dataset]
    )

    generator_input_dimension = int(
        SPP_GAN_GENERATOR_INPUT_DIMENSIONS[dataset]
    )

    gan_feature_dimension = int(
        SPP_GAN_INPUT_DIMENSIONS[dataset]
    )

    discriminator_input_dimension = int(
        SPP_GAN_DISCRIMINATOR_INPUT_DIMENSIONS[dataset]
    )

    if gan_feature_dimension != discriminator_input_dimension:

        raise ValueError(
            f"{dataset}: GAN feature dimension "
            f"{gan_feature_dimension} does not match "
            f"discriminator input dimension "
            f"{discriminator_input_dimension}."
        )

    # ==========================================================================
    # PRESERVE STATES
    # ==========================================================================

    generator_training_state = generator.training
    discriminator_training_state = discriminator.training

    generator_model_state = copy.deepcopy(
        generator.state_dict()
    )

    discriminator_model_state = copy.deepcopy(
        discriminator.state_dict()
    )

    generator_optimizer_state = copy.deepcopy(
        generator_optimizer.state_dict()
    )

    discriminator_optimizer_state = copy.deepcopy(
        discriminator_optimizer.state_dict()
    )

    # ==========================================================================
    # DIAGNOSTIC MODE
    # ==========================================================================

    generator.train()
    discriminator.train()

    generator_optimizer.zero_grad(
        set_to_none=True
    )

    discriminator_optimizer.zero_grad(
        set_to_none=True
    )

    # ==========================================================================
    # TEST INPUTS
    # ==========================================================================

    noise = torch.randn(
        test_batch_size,
        generator_input_dimension,
        device=SPP_GAN_DEVICE,
        dtype=torch.float32
    )

    real_features = torch.randn(
        test_batch_size,
        gan_feature_dimension,
        device=SPP_GAN_DEVICE,
        dtype=torch.float32
    )

    # ==========================================================================
    # DISCRIMINATOR UPDATE TEST
    # ==========================================================================

    fake_features = generator(
        noise
    )

    real_logits = discriminator(
        real_features
    )

    fake_logits = discriminator(
        fake_features.detach()
    )

    discriminator_loss = (
        spp_gan_discriminator_loss(
            real_logits,
            fake_logits
        )
    )

    if not torch.isfinite(
        discriminator_loss
    ).item():

        raise FloatingPointError(
            f"{dataset}: Discriminator loss is not finite."
        )

    discriminator_loss.backward()

    discriminator_gradient_parameters = [
        parameter
        for parameter
        in discriminator.parameters()
        if (
            parameter.requires_grad
            and
            parameter.grad is not None
        )
    ]

    discriminator_gradients_exist = (
        len(
            discriminator_gradient_parameters
        ) > 0
    )

    discriminator_gradients_finite = (
        discriminator_gradients_exist
        and
        all(
            torch.isfinite(
                parameter.grad
            ).all().item()
            for parameter
            in discriminator_gradient_parameters
        )
    )

    discriminator_gradient_squared_norm = sum(
        parameter.grad.detach().pow(2).sum()
        for parameter
        in discriminator_gradient_parameters
    )

    discriminator_gradient_norm = torch.sqrt(
        discriminator_gradient_squared_norm
    )

    discriminator_gradient_norm_finite = bool(
        torch.isfinite(
            discriminator_gradient_norm
        ).item()
    )

    discriminator_gradient_norm_positive = (
        discriminator_gradient_norm_finite
        and
        discriminator_gradient_norm.item() > 0.0
    )

    discriminator_parameters_before = [
        parameter.detach().clone()
        for parameter
        in discriminator.parameters()
        if parameter.requires_grad
    ]

    discriminator_optimizer.step()

    discriminator_parameters_after = [
        parameter.detach().clone()
        for parameter
        in discriminator.parameters()
        if parameter.requires_grad
    ]

    discriminator_parameter_changed = any(
        not torch.equal(
            before,
            after
        )
        for before, after
        in zip(
            discriminator_parameters_before,
            discriminator_parameters_after
        )
    )

    discriminator_update_valid = (
        discriminator_gradients_exist
        and
        discriminator_gradients_finite
        and
        discriminator_gradient_norm_positive
        and
        discriminator_parameter_changed
    )

    # ==========================================================================
    # CLEAR DISCRIMINATOR GRADIENTS
    # ==========================================================================

    discriminator_optimizer.zero_grad(
        set_to_none=True
    )

    generator_optimizer.zero_grad(
        set_to_none=True
    )

    # ==========================================================================
    # GENERATOR UPDATE TEST
    # ==========================================================================

    fake_features = generator(
        noise
    )

    fake_logits = discriminator(
        fake_features
    )

    generator_loss = (
        spp_gan_generator_loss(
            fake_logits
        )
    )

    if not torch.isfinite(
        generator_loss
    ).item():

        raise FloatingPointError(
            f"{dataset}: Generator loss is not finite."
        )

    generator_loss.backward()

    generator_gradient_parameters = [
        parameter
        for parameter
        in generator.parameters()
        if (
            parameter.requires_grad
            and
            parameter.grad is not None
        )
    ]

    generator_gradients_exist = (
        len(
            generator_gradient_parameters
        ) > 0
    )

    generator_gradients_finite = (
        generator_gradients_exist
        and
        all(
            torch.isfinite(
                parameter.grad
            ).all().item()
            for parameter
            in generator_gradient_parameters
        )
    )

    generator_gradient_squared_norm = sum(
        parameter.grad.detach().pow(2).sum()
        for parameter
        in generator_gradient_parameters
    )

    generator_gradient_norm = torch.sqrt(
        generator_gradient_squared_norm
    )

    generator_gradient_norm_finite = bool(
        torch.isfinite(
            generator_gradient_norm
        ).item()
    )

    generator_gradient_norm_positive = (
        generator_gradient_norm_finite
        and
        generator_gradient_norm.item() > 0.0
    )

    generator_parameters_before = [
        parameter.detach().clone()
        for parameter
        in generator.parameters()
        if parameter.requires_grad
    ]

    generator_optimizer.step()

    generator_parameters_after = [
        parameter.detach().clone()
        for parameter
        in generator.parameters()
        if parameter.requires_grad
    ]

    generator_parameter_changed = any(
        not torch.equal(
            before,
            after
        )
        for before, after
        in zip(
            generator_parameters_before,
            generator_parameters_after
        )
    )

    generator_update_valid = (
        generator_gradients_exist
        and
        generator_gradients_finite
        and
        generator_gradient_norm_positive
        and
        generator_parameter_changed
    )

    # ==========================================================================
    # RESTORE MODEL STATES
    # ==========================================================================

    generator.load_state_dict(
        generator_model_state
    )

    discriminator.load_state_dict(
        discriminator_model_state
    )

    generator_optimizer.load_state_dict(
        generator_optimizer_state
    )

    discriminator_optimizer.load_state_dict(
        discriminator_optimizer_state
    )

    generator_optimizer.zero_grad(
        set_to_none=True
    )

    discriminator_optimizer.zero_grad(
        set_to_none=True
    )

    # ==========================================================================
    # RESTORE TRAINING STATES
    # ==========================================================================

    if generator_training_state:
        generator.train()
    else:
        generator.eval()

    if discriminator_training_state:
        discriminator.train()
    else:
        discriminator.eval()

    # ==========================================================================
    # OVERALL VALIDATION
    # ==========================================================================

    optimizer_valid = (
        discriminator_update_valid
        and
        generator_update_valid
    )

    SPP_GAN_OPTIMIZER_GRADIENT_CHECKS[dataset] = {

        "Discriminator Gradients Exist":
            discriminator_gradients_exist,

        "Discriminator Gradients Finite":
            discriminator_gradients_finite,

        "Discriminator Gradient Norm":
            float(
                discriminator_gradient_norm.detach()
                .cpu()
                .item()
            ),

        "Discriminator Gradient Valid":
            (
                discriminator_gradients_exist
                and
                discriminator_gradients_finite
                and
                discriminator_gradient_norm_positive
            ),

        "Discriminator Parameters Updated":
            discriminator_parameter_changed,

        "Discriminator Update Valid":
            discriminator_update_valid,

        "Generator Gradients Exist":
            generator_gradients_exist,

        "Generator Gradients Finite":
            generator_gradients_finite,

        "Generator Gradient Norm":
            float(
                generator_gradient_norm.detach()
                .cpu()
                .item()
            ),

        "Generator Gradient Valid":
            (
                generator_gradients_exist
                and
                generator_gradients_finite
                and
                generator_gradient_norm_positive
            ),

        "Generator Parameters Updated":
            generator_parameter_changed,

        "Generator Update Valid":
            generator_update_valid,

        "Optimizer Connectivity Valid":
            optimizer_valid
    }

    # ==========================================================================
    # REPORT
    # ==========================================================================

    print()

    print(
        f"Dataset                       : {dataset}"
    )

    print(
        f"Generator Input Dimension     : "
        f"{generator_input_dimension}"
    )

    print(
        f"GAN Feature Dimension         : "
        f"{gan_feature_dimension}"
    )

    print(
        f"Discriminator Input Dimension : "
        f"{discriminator_input_dimension}"
    )

    print()

    print(
        f"Discriminator Loss            : "
        f"{discriminator_loss.item():.6f}"
    )

    print(
        f"Generator Loss                : "
        f"{generator_loss.item():.6f}"
    )

    print()

    print(
        f"Discriminator Gradients       : "
        f"{'PASS' if discriminator_update_valid else 'FAIL'}"
    )

    print(
        f"Discriminator Gradient Norm   : "
        f"{discriminator_gradient_norm.item():.6e}"
    )

    print(
        f"Discriminator Parameter Update: "
        f"{'PASS' if discriminator_parameter_changed else 'FAIL'}"
    )

    print()

    print(
        f"Generator Gradients           : "
        f"{'PASS' if generator_update_valid else 'FAIL'}"
    )

    print(
        f"Generator Gradient Norm       : "
        f"{generator_gradient_norm.item():.6e}"
    )

    print(
        f"Generator Parameter Update    : "
        f"{'PASS' if generator_parameter_changed else 'FAIL'}"
    )

    print()

    print(
        f"Optimizer Connectivity        : "
        f"{'PASS' if optimizer_valid else 'FAIL'}"
    )

# ==============================================================================
# OVERALL GRADIENT VALIDATION
# ==============================================================================

SPP_GAN_OPTIMIZER_GRADIENT_VALIDATION_STATUS = (
    len(SPP_GAN_OPTIMIZER_GRADIENT_CHECKS)
    ==
    len(DATASETS)
    and
    all(
        checks["Optimizer Connectivity Valid"]
        for checks
        in SPP_GAN_OPTIMIZER_GRADIENT_CHECKS.values()
    )
)

print()

print(
    f"Overall Gradient Update Validation : "
    f"{'PASS' if SPP_GAN_OPTIMIZER_GRADIENT_VALIDATION_STATUS else 'FAIL'}"
)

# ==============================================================================
# FAIL-FAST VALIDATION
# ==============================================================================

if not SPP_GAN_OPTIMIZER_GRADIENT_VALIDATION_STATUS:

    failed_datasets = [
        dataset
        for dataset, checks
        in SPP_GAN_OPTIMIZER_GRADIENT_CHECKS.items()
        if not checks["Optimizer Connectivity Valid"]
    ]

    raise ValueError(
        "SPP-GAN optimizer gradient connectivity validation "
        f"failed for datasets: {failed_datasets}"
    )

print()

print(
    "Generator and discriminator gradient/update connectivity "
    "validated successfully for all datasets."
)

print()

print(
    "PART K5 — Optimizer gradient update test completed."
)

====================================================================================================
PART K5 — OPTIMIZER GRADIENT UPDATE TEST
====================================================================================================

Dataset                       : Adult Income
Generator Input Dimension     : 128
GAN Feature Dimension         : 14
Discriminator Input Dimension : 14

Discriminator Loss            : 0.858958
Generator Loss                : 0.378159

Discriminator Gradients       : PASS
Discriminator Gradient Norm   : 4.943970e+00
Discriminator Parameter Update: PASS

Generator Gradients           : PASS
Generator Gradient Norm       : 4.147710e+00
Generator Parameter Update    : PASS

Optimizer Connectivity        : PASS

Dataset                       : Bank Marketing
Generator Input Dimension     : 128
GAN Feature Dimension         : 16
Discriminator Input Dimension : 16

Discriminator Loss            : 0.554193
Generator Loss                : 1.172954

Discriminator Gradients       : PASS
Discriminator Gradient Norm   : 3.764493e+00
Discriminator Parameter Update: PASS

Generator Gradients           : PASS
Generator Gradient Norm       : 8.581151e+00
Generator Parameter Update    : PASS

Optimizer Connectivity        : PASS

Dataset                       : diabetes_130us
Generator Input Dimension     : 128
GAN Feature Dimension         : 47
Discriminator Input Dimension : 47

Discriminator Loss            : 0.621366
Generator Loss                : 1.154553

Discriminator Gradients       : PASS
Discriminator Gradient Norm   : 3.632861e+00
Discriminator Parameter Update: PASS

Generator Gradients           : PASS
Generator Gradient Norm       : 7.450508e+00
Generator Parameter Update    : PASS

Optimizer Connectivity        : PASS

Overall Gradient Update Validation : PASS

Generator and discriminator gradient/update connectivity validated successfully for all datasets.

PART K5 — Optimizer gradient update test completed.

In [161]:
# ==============================================================================
# PART K6 — SPP-GAN OPTIMIZER SUMMARY
# ==============================================================================

print("=" * 100)
print("PART K6 — SPP-GAN OPTIMIZER SUMMARY")
print("=" * 100)

# ==============================================================================
# GLOBAL VALIDATION STATUS
# ==============================================================================

SPP_GAN_OPTIMIZER_CONFIGURATION_VALID = (
    SPP_GAN_OPTIMIZER_CONFIGURATION_VALID
)

SPP_GAN_OPTIMIZER_INITIALIZATION_VALID = (
    SPP_GAN_OPTIMIZER_INITIALIZATION_STATUS
)

SPP_GAN_OPTIMIZER_PARAMETER_VALID = (
    SPP_GAN_OPTIMIZER_PARAMETER_VALIDATION_STATUS
)

SPP_GAN_OPTIMIZER_GRADIENT_VALID = (
    SPP_GAN_OPTIMIZER_GRADIENT_VALIDATION_STATUS
)

SPP_GAN_OPTIMIZER_OVERALL_VALID = (
    SPP_GAN_OPTIMIZER_CONFIGURATION_VALID
    and
    SPP_GAN_OPTIMIZER_INITIALIZATION_VALID
    and
    SPP_GAN_OPTIMIZER_PARAMETER_VALID
    and
    SPP_GAN_OPTIMIZER_GRADIENT_VALID
)

# ==============================================================================
# GLOBAL OPTIMIZER SUMMARY
# ==============================================================================

SPP_GAN_OPTIMIZER_SUMMARY = {

    "Optimizer":
        SPP_GAN_OPTIMIZER_NAME,

    "Learning Rate":
        SPP_GAN_LEARNING_RATE,

    "Adam Beta 1":
        SPP_GAN_BETA1,

    "Adam Beta 2":
        SPP_GAN_BETA2,

    "Weight Decay":
        0.0,

    "Datasets":
        len(DATASETS),

    "Generator Optimizers":
        len(
            SPP_GAN_GENERATOR_OPTIMIZERS
        ),

    "Discriminator Optimizers":
        len(
            SPP_GAN_DISCRIMINATOR_OPTIMIZERS
        ),

    "Configuration Valid":
        SPP_GAN_OPTIMIZER_CONFIGURATION_VALID,

    "Initialization Valid":
        SPP_GAN_OPTIMIZER_INITIALIZATION_VALID,

    "Optimizer Parameters Valid":
        SPP_GAN_OPTIMIZER_PARAMETER_VALID,

    "Gradient Connectivity Valid":
        SPP_GAN_OPTIMIZER_GRADIENT_VALID,

    "Overall Valid":
        SPP_GAN_OPTIMIZER_OVERALL_VALID
}

# ==============================================================================
# GLOBAL SUMMARY DATAFRAME
# ==============================================================================

SPP_GAN_OPTIMIZER_SUMMARY_DF = pd.DataFrame(
    list(
        SPP_GAN_OPTIMIZER_SUMMARY.items()
    ),
    columns=[
        "Parameter",
        "Value"
    ]
)

print()

display(
    SPP_GAN_OPTIMIZER_SUMMARY_DF
)

# ==============================================================================
# DATASET-SPECIFIC SUMMARY
# ==============================================================================

SPP_GAN_OPTIMIZER_DATASET_SUMMARY = []

for dataset in DATASETS:

    parameter_checks = (
        SPP_GAN_OPTIMIZER_PARAMETER_CHECKS[
            dataset
        ]
    )

    gradient_checks = (
        SPP_GAN_OPTIMIZER_GRADIENT_CHECKS[
            dataset
        ]
    )

    initialization_checks = (
        SPP_GAN_OPTIMIZER_INITIALIZATION_CHECKS[
            dataset
        ]
    )

    dataset_optimizer_valid = (
        initialization_checks[
            "Initialization Valid"
        ]
        and
        parameter_checks[
            "Optimizer Valid"
        ]
        and
        gradient_checks[
            "Optimizer Connectivity Valid"
        ]
    )

    SPP_GAN_OPTIMIZER_DATASET_SUMMARY.append({

        "Dataset":
            dataset,

        "GAN Feature Dimension":
            int(
                SPP_GAN_INPUT_DIMENSIONS[
                    dataset
                ]
            ),

        "Optimizer":
            SPP_GAN_OPTIMIZER_NAME,

        "Learning Rate":
            SPP_GAN_LEARNING_RATE,

        "Beta 1":
            SPP_GAN_BETA1,

        "Beta 2":
            SPP_GAN_BETA2,

        "Generator Optimizer":
            type(
                SPP_GAN_GENERATOR_OPTIMIZERS[
                    dataset
                ]
            ).__name__,

        "Discriminator Optimizer":
            type(
                SPP_GAN_DISCRIMINATOR_OPTIMIZERS[
                    dataset
                ]
            ).__name__,

        "Initialization Validation":
            initialization_checks[
                "Initialization Valid"
            ],

        "Parameter Validation":
            parameter_checks[
                "Optimizer Valid"
            ],

        "Gradient Validation":
            gradient_checks[
                "Optimizer Connectivity Valid"
            ],

        "Generator Gradient Norm":
            gradient_checks[
                "Generator Gradient Norm"
            ],

        "Discriminator Gradient Norm":
            gradient_checks[
                "Discriminator Gradient Norm"
            ],

        "Generator Update":
            gradient_checks[
                "Generator Parameters Updated"
            ],

        "Discriminator Update":
            gradient_checks[
                "Discriminator Parameters Updated"
            ],

        "Overall Dataset Valid":
            dataset_optimizer_valid
    })

SPP_GAN_OPTIMIZER_DATASET_SUMMARY_DF = (
    pd.DataFrame(
        SPP_GAN_OPTIMIZER_DATASET_SUMMARY
    )
)

print()

print(
    "Dataset-Specific Optimizer Validation:"
)

print()

display(
    SPP_GAN_OPTIMIZER_DATASET_SUMMARY_DF
)

# ==============================================================================
# FINAL VALIDATION REPORT
# ==============================================================================

print()

print(
    f"Configuration Validation       : "
    f"{'PASS' if SPP_GAN_OPTIMIZER_CONFIGURATION_VALID else 'FAIL'}"
)

print(
    f"Initialization Validation      : "
    f"{'PASS' if SPP_GAN_OPTIMIZER_INITIALIZATION_VALID else 'FAIL'}"
)

print(
    f"Parameter Validation           : "
    f"{'PASS' if SPP_GAN_OPTIMIZER_PARAMETER_VALID else 'FAIL'}"
)

print(
    f"Gradient Validation            : "
    f"{'PASS' if SPP_GAN_OPTIMIZER_GRADIENT_VALID else 'FAIL'}"
)

print()

print(
    f"Overall Optimizer Status       : "
    f"{'PASS' if SPP_GAN_OPTIMIZER_OVERALL_VALID else 'FAIL'}"
)

# ==============================================================================
# FAIL-FAST PIPELINE CHECK
# ==============================================================================

if not SPP_GAN_OPTIMIZER_OVERALL_VALID:

    failed_datasets = [
        row["Dataset"]
        for row
        in SPP_GAN_OPTIMIZER_DATASET_SUMMARY
        if not row["Overall Dataset Valid"]
    ]

    raise ValueError(
        "SPP-GAN optimizer module validation failed."
        +
        (
            f" Failed datasets: {failed_datasets}"
            if failed_datasets
            else ""
        )
    )

print()

print(
    "SPP-GAN optimizer configuration, initialization, "
    "parameter registration, and gradient connectivity "
    "validated successfully."
)

print()

print(
    "PART K6 — Optimizer summary completed."
)

====================================================================================================
PART K6 — SPP-GAN OPTIMIZER SUMMARY
====================================================================================================

                      Parameter   Value
0                     Optimizer    Adam
1                 Learning Rate  0.0002
2                   Adam Beta 1     0.5
3                   Adam Beta 2   0.999
4                  Weight Decay     0.0
5                      Datasets       3
6          Generator Optimizers       3
7      Discriminator Optimizers       3
8           Configuration Valid    True
9          Initialization Valid    True
10   Optimizer Parameters Valid    True
11  Gradient Connectivity Valid    True
12                Overall Valid    True

Dataset-Specific Optimizer Validation:

,Dataset,GAN Feature Dimension,Optimizer,Learning Rate,Beta 1,Beta 2,Generator Optimizer,Discriminator Optimizer,Initialization Validation,Parameter Validation,Gradient Validation,Generator Gradient Norm,Discriminator Gradient Norm,Generator Update,Discriminator Update,Overall Dataset Valid
0,Adult Income,14,Adam,0.0002,0.5,0.999,Adam,Adam,True,True,True,4.147710,4.943970,True,True,True
1,Bank Marketing,16,Adam,0.0002,0.5,0.999,Adam,Adam,True,True,True,8.581151,3.764493,True,True,True
2,diabetes_130us,47,Adam,0.0002,0.5,0.999,Adam,Adam,True,True,True,7.450508,3.632861,True,True,True

Configuration Validation       : PASS
Initialization Validation      : PASS
Parameter Validation           : PASS
Gradient Validation            : PASS

Overall Optimizer Status       : PASS

SPP-GAN optimizer configuration, initialization, parameter registration, and gradient connectivity validated successfully.

PART K6 — Optimizer summary completed.

In [168]:
# ==============================================================================
# PART L1 — PRIVACY MECHANISM CONFIGURATION
# ==============================================================================

print("=" * 100)
print("PART L1 — PRIVACY MECHANISM CONFIGURATION")
print("=" * 100)

# ==============================================================================
# PRIVACY MECHANISM
# ==============================================================================

SPP_GAN_PRIVACY_MECHANISM_NAME = str(
    SPP_GAN_PRIVACY_MECHANISM
).strip()

SPP_GAN_PRIVACY_MECHANISM_NORMALIZED = (
    SPP_GAN_PRIVACY_MECHANISM_NAME.lower()
)

SPP_GAN_PRIVACY_NOISE_DISTRIBUTION = "Gaussian"

# ==============================================================================
# DIFFERENTIAL PRIVACY PARAMETERS
# ==============================================================================

# Canonical privacy budget source
if "privacy_budget" not in PROJECT_CONFIG:
    raise KeyError(
        "PROJECT_CONFIG is missing required key: 'privacy_budget'"
    )

# Canonical delta source
if "delta" not in PROJECT_CONFIG:
    raise KeyError(
        "PROJECT_CONFIG is missing required key: 'delta'"
    )

SPP_GAN_PRIVACY_EPSILON = float(
    PROJECT_CONFIG["privacy_budget"]
)

SPP_GAN_PRIVACY_DELTA = float(
    PROJECT_CONFIG["delta"]
)

# Use the current project configuration for clipping norm.
# Fall back to the already-defined SPP-GAN privacy parameter.
if "max_grad_norm" in PROJECT_CONFIG:
    SPP_GAN_PRIVACY_CLIPPING_NORM = float(
        PROJECT_CONFIG["max_grad_norm"]
    )
else:
    SPP_GAN_PRIVACY_CLIPPING_NORM = float(
        SPP_GAN_MAX_GRAD_NORM
    )

# Canonical noise multiplier
if "noise_multiplier" in PROJECT_CONFIG:
    SPP_GAN_PRIVACY_NOISE_MULTIPLIER = float(
        PROJECT_CONFIG["noise_multiplier"]
    )
else:
    SPP_GAN_PRIVACY_NOISE_MULTIPLIER = float(
        SPP_GAN_NOISE_MULTIPLIER
    )

# ==============================================================================
# PRIVATE TRAINING COMPONENT
# ==============================================================================

# Real private training records are processed directly by the discriminator.
SPP_GAN_PRIVACY_APPLY_TO_DISCRIMINATOR = True

# Generator does not directly receive private real records.
SPP_GAN_PRIVACY_APPLY_TO_GENERATOR = False

SPP_GAN_GENERATOR_PRIVACY_STATUS = (
    "Protected through DP post-processing"
)

SPP_GAN_DISCRIMINATOR_PRIVACY_STATUS = (
    "Direct manual DP-SGD protection"
)

# ==============================================================================
# PRIVACY ACCOUNTING COMPONENT
# ==============================================================================

SPP_GAN_PRIVACY_ACCOUNTING_COMPONENT = "Discriminator"

SPP_GAN_PRIVACY_POST_PROCESSING_COMPONENTS = [
    "Generator",
    "Synthetic Data Generation"
]

# ==============================================================================
# MANUAL DP-SGD ENGINE
# ==============================================================================

SPP_GAN_PRIVACY_ENGINE = "Manual DP-SGD"

SPP_GAN_PRIVACY_PER_SAMPLE_CLIPPING = True

SPP_GAN_PRIVACY_MANUAL_GAUSSIAN_NOISE = True

SPP_GAN_PRIVACY_USE_OPACUS = False

# ==============================================================================
# CONFIGURATION VALIDATION
# ==============================================================================

SPP_GAN_PRIVACY_MECHANISM_VALID = (
    SPP_GAN_PRIVACY_MECHANISM_NORMALIZED
    in {
        "differential privacy",
        "dp",
        "dp-sgd",
        "differentially private stochastic gradient descent"
    }
)

SPP_GAN_PRIVACY_EPSILON_VALID = (
    SPP_GAN_PRIVACY_EPSILON > 0.0
    and
    torch.isfinite(
        torch.tensor(
            SPP_GAN_PRIVACY_EPSILON,
            dtype=torch.float64
        )
    ).item()
)

SPP_GAN_PRIVACY_DELTA_VALID = (
    0.0
    <
    SPP_GAN_PRIVACY_DELTA
    <
    1.0
    and
    torch.isfinite(
        torch.tensor(
            SPP_GAN_PRIVACY_DELTA,
            dtype=torch.float64
        )
    ).item()
)

SPP_GAN_PRIVACY_NOISE_DISTRIBUTION_VALID = (
    SPP_GAN_PRIVACY_NOISE_DISTRIBUTION == "Gaussian"
)

SPP_GAN_PRIVACY_CLIPPING_NORM_VALID = (
    SPP_GAN_PRIVACY_CLIPPING_NORM > 0.0
    and
    torch.isfinite(
        torch.tensor(
            SPP_GAN_PRIVACY_CLIPPING_NORM,
            dtype=torch.float64
        )
    ).item()
)

SPP_GAN_PRIVACY_NOISE_MULTIPLIER_VALID = (
    SPP_GAN_PRIVACY_NOISE_MULTIPLIER > 0.0
    and
    torch.isfinite(
        torch.tensor(
            SPP_GAN_PRIVACY_NOISE_MULTIPLIER,
            dtype=torch.float64
        )
    ).item()
)

SPP_GAN_PRIVACY_COMPONENT_VALID = (
    SPP_GAN_PRIVACY_APPLY_TO_DISCRIMINATOR
    and
    not SPP_GAN_PRIVACY_APPLY_TO_GENERATOR
)

SPP_GAN_PRIVACY_ENGINE_VALID = (
    SPP_GAN_PRIVACY_ENGINE == "Manual DP-SGD"
    and
    not SPP_GAN_PRIVACY_USE_OPACUS
    and
    SPP_GAN_PRIVACY_PER_SAMPLE_CLIPPING
    and
    SPP_GAN_PRIVACY_MANUAL_GAUSSIAN_NOISE
)

SPP_GAN_PRIVACY_CONFIGURATION_VALID = (
    SPP_GAN_PRIVACY_MECHANISM_VALID
    and
    SPP_GAN_PRIVACY_EPSILON_VALID
    and
    SPP_GAN_PRIVACY_DELTA_VALID
    and
    SPP_GAN_PRIVACY_NOISE_DISTRIBUTION_VALID
    and
    SPP_GAN_PRIVACY_CLIPPING_NORM_VALID
    and
    SPP_GAN_PRIVACY_NOISE_MULTIPLIER_VALID
    and
    SPP_GAN_PRIVACY_COMPONENT_VALID
    and
    SPP_GAN_PRIVACY_ENGINE_VALID
)

# ==============================================================================
# CONFIGURATION REPORT
# ==============================================================================

print()

print(
    f"Privacy Mechanism              : "
    f"{SPP_GAN_PRIVACY_MECHANISM_NAME}"
)

print(
    f"Privacy Engine                 : "
    f"{SPP_GAN_PRIVACY_ENGINE}"
)

print(
    f"Privacy Budget (ε)             : "
    f"{SPP_GAN_PRIVACY_EPSILON}"
)

print(
    f"Privacy Delta (δ)              : "
    f"{SPP_GAN_PRIVACY_DELTA}"
)

print(
    f"Noise Distribution             : "
    f"{SPP_GAN_PRIVACY_NOISE_DISTRIBUTION}"
)

print(
    f"Gradient Clipping Norm         : "
    f"{SPP_GAN_PRIVACY_CLIPPING_NORM}"
)

print(
    f"Noise Multiplier               : "
    f"{SPP_GAN_PRIVACY_NOISE_MULTIPLIER}"
)

print(
    f"Per-Sample Clipping            : "
    f"{SPP_GAN_PRIVACY_PER_SAMPLE_CLIPPING}"
)

print(
    f"Manual Gaussian Noise          : "
    f"{SPP_GAN_PRIVACY_MANUAL_GAUSSIAN_NOISE}"
)

print(
    f"Apply DP to Discriminator      : "
    f"{SPP_GAN_PRIVACY_APPLY_TO_DISCRIMINATOR}"
)

print(
    f"Apply DP Directly to Generator : "
    f"{SPP_GAN_PRIVACY_APPLY_TO_GENERATOR}"
)

print(
    f"Generator Privacy Status       : "
    f"{SPP_GAN_GENERATOR_PRIVACY_STATUS}"
)

print(
    f"Discriminator Privacy Status   : "
    f"{SPP_GAN_DISCRIMINATOR_PRIVACY_STATUS}"
)

print(
    f"Privacy Accounting Component   : "
    f"{SPP_GAN_PRIVACY_ACCOUNTING_COMPONENT}"
)

print(
    f"Post-Processing Components     : "
    f"{SPP_GAN_PRIVACY_POST_PROCESSING_COMPONENTS}"
)

# ==============================================================================
# VALIDATION REPORT
# ==============================================================================

print()

print(
    f"Mechanism Validation           : "
    f"{'PASS' if SPP_GAN_PRIVACY_MECHANISM_VALID else 'FAIL'}"
)

print(
    f"Epsilon Validation             : "
    f"{'PASS' if SPP_GAN_PRIVACY_EPSILON_VALID else 'FAIL'}"
)

print(
    f"Delta Validation               : "
    f"{'PASS' if SPP_GAN_PRIVACY_DELTA_VALID else 'FAIL'}"
)

print(
    f"Noise Distribution Validation  : "
    f"{'PASS' if SPP_GAN_PRIVACY_NOISE_DISTRIBUTION_VALID else 'FAIL'}"
)

print(
    f"Clipping Norm Validation       : "
    f"{'PASS' if SPP_GAN_PRIVACY_CLIPPING_NORM_VALID else 'FAIL'}"
)

print(
    f"Noise Multiplier Validation    : "
    f"{'PASS' if SPP_GAN_PRIVACY_NOISE_MULTIPLIER_VALID else 'FAIL'}"
)

print(
    f"Privacy Component Validation   : "
    f"{'PASS' if SPP_GAN_PRIVACY_COMPONENT_VALID else 'FAIL'}"
)

print(
    f"Manual DP-SGD Engine           : "
    f"{'PASS' if SPP_GAN_PRIVACY_ENGINE_VALID else 'FAIL'}"
)

print()

print(
    f"Overall Privacy Configuration  : "
    f"{'PASS' if SPP_GAN_PRIVACY_CONFIGURATION_VALID else 'FAIL'}"
)

# ==============================================================================
# FAIL-FAST PIPELINE CHECK
# ==============================================================================

if not SPP_GAN_PRIVACY_CONFIGURATION_VALID:
    raise ValueError(
        "SPP-GAN privacy mechanism configuration validation failed."
    )

print()

print(
    "Manual DP-SGD privacy mechanism is configured."
)

print(
    "Privacy budget is sourced from PROJECT_CONFIG['privacy_budget']."
)

print(
    "Privacy delta is sourced from PROJECT_CONFIG['delta']."
)

print(
    "Per-sample clipping and calibrated Gaussian noise "
    "are applied to discriminator gradients."
)

print(
    "Generator training is treated as DP post-processing "
    "of the privatized discriminator mechanism."
)

print()

print(
    "PART L1 — Privacy mechanism configuration completed."
)

====================================================================================================
PART L1 — PRIVACY MECHANISM CONFIGURATION
====================================================================================================

Privacy Mechanism              : Differential Privacy
Privacy Engine                 : Manual DP-SGD
Privacy Budget (ε)             : 4.0
Privacy Delta (δ)              : 1e-05
Noise Distribution             : Gaussian
Gradient Clipping Norm         : 1.0
Noise Multiplier               : 1.1
Per-Sample Clipping            : True
Manual Gaussian Noise          : True
Apply DP to Discriminator      : True
Apply DP Directly to Generator : False
Generator Privacy Status       : Protected through DP post-processing
Discriminator Privacy Status   : Direct manual DP-SGD protection
Privacy Accounting Component   : Discriminator
Post-Processing Components     : ['Generator', 'Synthetic Data Generation']

Mechanism Validation           : PASS
Epsilon Validation             : PASS
Delta Validation               : PASS
Noise Distribution Validation  : PASS
Clipping Norm Validation       : PASS
Noise Multiplier Validation    : PASS
Privacy Component Validation   : PASS
Manual DP-SGD Engine           : PASS

Overall Privacy Configuration  : PASS

Manual DP-SGD privacy mechanism is configured.
Privacy budget is sourced from PROJECT_CONFIG['privacy_budget'].
Privacy delta is sourced from PROJECT_CONFIG['delta'].
Per-sample clipping and calibrated Gaussian noise are applied to discriminator gradients.
Generator training is treated as DP post-processing of the privatized discriminator mechanism.

PART L1 — Privacy mechanism configuration completed.

In [176]:
# ==============================================================================
# PART L2 — PER-SAMPLE GRADIENT CLIPPING
# ==============================================================================

print("=" * 100)
print("PART L2 — PER-SAMPLE GRADIENT CLIPPING")
print("=" * 100)

# ==============================================================================
# PER-SAMPLE GRADIENT CLIPPING FUNCTION
# ==============================================================================

def spp_gan_clip_per_sample_gradients(
    per_sample_gradients,
    max_grad_norm
):

    max_grad_norm = float(
        max_grad_norm
    )

    if max_grad_norm <= 0.0:

        raise ValueError(
            "Maximum gradient norm must be greater than zero."
        )

    if len(
        per_sample_gradients
    ) == 0:

        raise ValueError(
            "Per-sample gradient list cannot be empty."
        )

    clipped_gradients = []

    sample_gradient_norms = []

    clipped_gradient_norms = []

    clipping_factors = []

    for sample_gradients in per_sample_gradients:

        if len(
            sample_gradients
        ) == 0:

            raise ValueError(
                "Each sample must contain at least one gradient tensor."
            )

        total_squared_norm = torch.zeros(
            1,
            device=sample_gradients[0].device,
            dtype=torch.float32
        )

        for gradient in sample_gradients:

            total_squared_norm = (
                total_squared_norm
                +
                gradient.detach().pow(2).sum()
            )

        sample_norm = torch.sqrt(
            total_squared_norm
            +
            1e-12
        )

        clipping_factor = torch.clamp(
            max_grad_norm / sample_norm,
            max=1.0
        )

        clipped_sample_gradients = [
            gradient * clipping_factor
            for gradient
            in sample_gradients
        ]

        clipped_squared_norm = torch.zeros(
            1,
            device=sample_gradients[0].device,
            dtype=torch.float32
        )

        for gradient in clipped_sample_gradients:

            clipped_squared_norm = (
                clipped_squared_norm
                +
                gradient.detach().pow(2).sum()
            )

        clipped_norm = torch.sqrt(
            clipped_squared_norm
            +
            1e-12
        )

        clipped_gradients.append(
            clipped_sample_gradients
        )

        sample_gradient_norms.append(
            sample_norm.detach()
        )

        clipped_gradient_norms.append(
            clipped_norm.detach()
        )

        clipping_factors.append(
            clipping_factor.detach()
        )

    return (
        clipped_gradients,
        torch.stack(
            sample_gradient_norms
        ),
        torch.stack(
            clipped_gradient_norms
        ),
        torch.stack(
            clipping_factors
        )
    )

# ==============================================================================
# CLIPPING CONFIGURATION
# ==============================================================================

SPP_GAN_GRADIENT_CLIPPING_NORM = float(
    SPP_GAN_PRIVACY_CLIPPING_NORM
)

SPP_GAN_DISCRIMINATOR_PER_SAMPLE_CLIPPING = (
    SPP_GAN_PRIVACY_APPLY_TO_DISCRIMINATOR
)

SPP_GAN_GENERATOR_PER_SAMPLE_CLIPPING = False

SPP_GAN_PER_SAMPLE_CLIPPING_VALID = (
    SPP_GAN_GRADIENT_CLIPPING_NORM > 0.0
    and
    SPP_GAN_DISCRIMINATOR_PER_SAMPLE_CLIPPING
    and
    not SPP_GAN_GENERATOR_PER_SAMPLE_CLIPPING
)

# ==============================================================================
# CONFIGURATION REPORT
# ==============================================================================

print()

print(
    f"Maximum Gradient Norm          : "
    f"{SPP_GAN_GRADIENT_CLIPPING_NORM}"
)

print(
    f"Discriminator Per-Sample DP    : "
    f"{SPP_GAN_DISCRIMINATOR_PER_SAMPLE_CLIPPING}"
)

print(
    f"Generator Per-Sample DP        : "
    f"{SPP_GAN_GENERATOR_PER_SAMPLE_CLIPPING}"
)

print()

print(
    f"Clipping Norm Validation       : "
    f"{'PASS' if SPP_GAN_GRADIENT_CLIPPING_NORM > 0.0 else 'FAIL'}"
)

print(
    f"Discriminator Clipping         : "
    f"{'PASS' if SPP_GAN_DISCRIMINATOR_PER_SAMPLE_CLIPPING else 'FAIL'}"
)

print(
    f"Generator Direct DP Disabled   : "
    f"{'PASS' if not SPP_GAN_GENERATOR_PER_SAMPLE_CLIPPING else 'FAIL'}"
)

print()

print(
    f"Overall Clipping Configuration : "
    f"{'PASS' if SPP_GAN_PER_SAMPLE_CLIPPING_VALID else 'FAIL'}"
)

if not SPP_GAN_PER_SAMPLE_CLIPPING_VALID:

    raise ValueError(
        "SPP-GAN per-sample gradient clipping configuration failed."
    )

print()

print(
    "Per-sample L2 gradient clipping is configured."
)

print(
    "Raw per-sample gradient norms are retained for diagnostics."
)

print(
    "Clipped per-sample gradient norms are explicitly validated "
    "against the maximum clipping norm."
)

print(
    "DP clipping is applied to discriminator gradients only."
)

print(
    "Generator is not directly subjected to the DP-SGD clipping mechanism."
)

print()

print(
    "PART L2 — Per-sample gradient clipping completed."
)

====================================================================================================
PART L2 — PER-SAMPLE GRADIENT CLIPPING
====================================================================================================

Maximum Gradient Norm          : 1.0
Discriminator Per-Sample DP    : True
Generator Per-Sample DP        : False

Clipping Norm Validation       : PASS
Discriminator Clipping         : PASS
Generator Direct DP Disabled   : PASS

Overall Clipping Configuration : PASS

Per-sample L2 gradient clipping is configured.
Raw per-sample gradient norms are retained for diagnostics.
Clipped per-sample gradient norms are explicitly validated against the maximum clipping norm.
DP clipping is applied to discriminator gradients only.
Generator is not directly subjected to the DP-SGD clipping mechanism.

PART L2 — Per-sample gradient clipping completed.

In [177]:
# ==============================================================================
# PART L3 — GAUSSIAN GRADIENT NOISE
# ==============================================================================

print("=" * 100)
print("PART L3 — GAUSSIAN GRADIENT NOISE")
print("=" * 100)

# ==============================================================================
# GAUSSIAN NOISE FUNCTION
# ==============================================================================

def spp_gan_add_gaussian_noise_to_gradients(
    gradients,
    max_grad_norm,
    noise_multiplier,
    batch_size
):
    max_grad_norm = float(max_grad_norm)
    noise_multiplier = float(noise_multiplier)
    batch_size = int(batch_size)

    if max_grad_norm <= 0.0:
        raise ValueError(
            "Maximum gradient norm must be greater than zero."
        )

    if noise_multiplier <= 0.0:
        raise ValueError(
            "Noise multiplier must be greater than zero."
        )

    if batch_size <= 0:
        raise ValueError(
            "Batch size must be greater than zero."
        )

    if len(gradients) == 0:
        raise ValueError(
            "Gradient list cannot be empty."
        )

    # For summed clipped gradients:
    #
    #     Noise ~ N(0, (σC)^2)
    #
    # After division by batch size:
    #
    #     Noise SD = σC / B
    #
    noise_standard_deviation = (
        noise_multiplier
        *
        max_grad_norm
        /
        batch_size
    )

    noisy_gradients = []

    for gradient in gradients:

        if not torch.is_tensor(gradient):
            raise TypeError(
                "Each gradient must be a PyTorch tensor."
            )

        noise = (
            torch.randn_like(gradient)
            *
            noise_standard_deviation
        )

        noisy_gradient = (
            gradient
            +
            noise
        )

        noisy_gradients.append(
            noisy_gradient
        )

    return (
        noisy_gradients,
        noise_standard_deviation
    )

# ==============================================================================
# PRIVACY NOISE CONFIGURATION
# ==============================================================================

SPP_GAN_PRIVACY_NOISE_DISTRIBUTION = "Gaussian"

SPP_GAN_PRIVACY_NOISE_MULTIPLIER = float(
    SPP_GAN_PRIVACY_NOISE_MULTIPLIER
)

SPP_GAN_PRIVACY_NOISE_ENABLED = (
    SPP_GAN_PRIVACY_NOISE_MULTIPLIER > 0.0
)

SPP_GAN_MANUAL_DP_NOISE_ENABLED = True

SPP_GAN_OPACUS_NOISE_ENABLED = False

SPP_GAN_NOISE_MECHANISM_VALID = (
    SPP_GAN_PRIVACY_NOISE_DISTRIBUTION == "Gaussian"
    and
    SPP_GAN_PRIVACY_NOISE_MULTIPLIER > 0.0
    and
    SPP_GAN_MANUAL_DP_NOISE_ENABLED
    and
    not SPP_GAN_OPACUS_NOISE_ENABLED
)

# ==============================================================================
# CONFIGURATION REPORT
# ==============================================================================

print()

print(
    f"Noise Distribution             : "
    f"{SPP_GAN_PRIVACY_NOISE_DISTRIBUTION}"
)

print(
    f"Noise Multiplier               : "
    f"{SPP_GAN_PRIVACY_NOISE_MULTIPLIER}"
)

print(
    f"Noise Enabled                  : "
    f"{SPP_GAN_PRIVACY_NOISE_ENABLED}"
)

print(
    f"Manual DP Noise                : "
    f"{SPP_GAN_MANUAL_DP_NOISE_ENABLED}"
)

print(
    f"Opacus Noise                   : "
    f"{SPP_GAN_OPACUS_NOISE_ENABLED}"
)

print()

print(
    f"Noise Distribution Validation  : "
    f"{'PASS' if SPP_GAN_PRIVACY_NOISE_DISTRIBUTION == 'Gaussian' else 'FAIL'}"
)

print(
    f"Noise Multiplier Validation    : "
    f"{'PASS' if SPP_GAN_PRIVACY_NOISE_MULTIPLIER > 0.0 else 'FAIL'}"
)

print(
    f"Manual Noise Mechanism         : "
    f"{'PASS' if SPP_GAN_MANUAL_DP_NOISE_ENABLED else 'FAIL'}"
)

print(
    f"Opacus Disabled                : "
    f"{'PASS' if not SPP_GAN_OPACUS_NOISE_ENABLED else 'FAIL'}"
)

print()

print(
    f"Overall Noise Configuration    : "
    f"{'PASS' if SPP_GAN_NOISE_MECHANISM_VALID else 'FAIL'}"
)

if not SPP_GAN_NOISE_MECHANISM_VALID:
    raise ValueError(
        "SPP-GAN Gaussian noise configuration validation failed."
    )

print()

print(
    "Calibrated Gaussian gradient noise is configured."
)

print(
    "Noise scale is determined by the clipping norm, "
    "noise multiplier, and batch size."
)

print(
    "No external privacy library is used for gradient noise."
)

print()

print(
    "PART L3 — Gaussian gradient noise completed."
)

====================================================================================================
PART L3 — GAUSSIAN GRADIENT NOISE
====================================================================================================

Noise Distribution             : Gaussian
Noise Multiplier               : 1.1
Noise Enabled                  : True
Manual DP Noise                : True
Opacus Noise                   : False

Noise Distribution Validation  : PASS
Noise Multiplier Validation    : PASS
Manual Noise Mechanism         : PASS
Opacus Disabled                : PASS

Overall Noise Configuration    : PASS

Calibrated Gaussian gradient noise is configured.
Noise scale is determined by the clipping norm, noise multiplier, and batch size.
No external privacy library is used for gradient noise.

PART L3 — Gaussian gradient noise completed.

In [178]:
# ==============================================================================
# PART L4 — PRIVACY-PROTECTED GRADIENT PROCESSING
# ==============================================================================

print("=" * 100)
print("PART L4 — PRIVACY-PROTECTED GRADIENT PROCESSING")
print("=" * 100)

# ==============================================================================
# MANUAL DP-SGD PROCESSING STEPS
# ==============================================================================

SPP_GAN_PRIVATE_GRADIENT_PROCESSING_STEPS = [
    "Per-sample gradient computation",
    "Per-sample L2 gradient clipping",
    "Clipped gradient aggregation",
    "Gaussian noise addition",
    "Batch gradient normalization",
    "Optimizer parameter update"
]

# ==============================================================================
# MANUAL DP-SGD GRADIENT PROCESSING FUNCTION
# ==============================================================================

def spp_gan_private_gradient_processing(
    per_sample_gradients,
    max_grad_norm,
    noise_multiplier
):

    if len(
        per_sample_gradients
    ) == 0:

        raise ValueError(
            "Per-sample gradient list cannot be empty."
        )

    batch_size = len(
        per_sample_gradients
    )

    max_grad_norm = float(
        max_grad_norm
    )

    noise_multiplier = float(
        noise_multiplier
    )

    if max_grad_norm <= 0.0:

        raise ValueError(
            "Maximum gradient norm must be greater than zero."
        )

    if noise_multiplier <= 0.0:

        raise ValueError(
            "Noise multiplier must be greater than zero."
        )

    # ==========================================================================
    # STEP 1 — PER-SAMPLE GRADIENT CLIPPING
    # ==========================================================================

    (
        clipped_gradients,
        sample_gradient_norms,
        clipped_gradient_norms,
        clipping_factors
    ) = (
        spp_gan_clip_per_sample_gradients(
            per_sample_gradients=(
                per_sample_gradients
            ),
            max_grad_norm=(
                max_grad_norm
            )
        )
    )

    # ==========================================================================
    # STEP 2 — CLIPPED GRADIENT AGGREGATION
    # ==========================================================================

    parameter_count = len(
        clipped_gradients[0]
    )

    aggregated_gradients = []

    for parameter_index in range(
        parameter_count
    ):

        stacked_gradients = torch.stack(
            [
                sample_gradients[
                    parameter_index
                ]
                for sample_gradients
                in clipped_gradients
            ],
            dim=0
        )

        aggregated_gradient = (
            stacked_gradients.sum(
                dim=0
            )
        )

        aggregated_gradients.append(
            aggregated_gradient
        )

    # ==========================================================================
    # STEP 3 — GAUSSIAN NOISE
    # ==========================================================================

    (
        noisy_gradients,
        noise_standard_deviation
    ) = (
        spp_gan_add_gaussian_noise_to_gradients(
            gradients=(
                aggregated_gradients
            ),
            max_grad_norm=(
                max_grad_norm
            ),
            noise_multiplier=(
                noise_multiplier
            ),
            batch_size=(
                batch_size
            )
        )
    )

    # ==========================================================================
    # STEP 4 — BATCH NORMALIZATION
    # ==========================================================================

    averaged_gradients = [
        gradient / batch_size
        for gradient
        in noisy_gradients
    ]

    return {
        "Private Gradients":
            averaged_gradients,

        "Sample Gradient Norms":
            sample_gradient_norms,

        "Clipped Gradient Norms":
            clipped_gradient_norms,

        "Clipping Factors":
            clipping_factors,

        "Noise Standard Deviation":
            noise_standard_deviation,

        "Batch Size":
            batch_size,

        "Maximum Gradient Norm":
            max_grad_norm,

        "Noise Multiplier":
            noise_multiplier
    }

# ==============================================================================
# PRIVATE GRADIENT PROCESSING CONFIGURATION
# ==============================================================================

SPP_GAN_PRIVATE_GRADIENT_CLIPPING_NORM = float(
    SPP_GAN_PRIVACY_CLIPPING_NORM
)

SPP_GAN_PRIVATE_GRADIENT_NOISE_MULTIPLIER = float(
    SPP_GAN_PRIVACY_NOISE_MULTIPLIER
)

SPP_GAN_PRIVATE_GRADIENT_PROCESSING_ENGINE = (
    "Manual DP-SGD"
)

SPP_GAN_PRIVATE_GRADIENT_PROCESSING_VALID = (
    SPP_GAN_PRIVATE_GRADIENT_CLIPPING_NORM > 0.0
    and
    SPP_GAN_PRIVATE_GRADIENT_NOISE_MULTIPLIER > 0.0
    and
    SPP_GAN_DISCRIMINATOR_PER_SAMPLE_CLIPPING
    and
    SPP_GAN_MANUAL_DP_NOISE_ENABLED
    and
    not SPP_GAN_OPACUS_NOISE_ENABLED
)

# ==============================================================================
# CONFIGURATION REPORT
# ==============================================================================

print()

print(
    "Private Gradient Processing Engine : "
    f"{SPP_GAN_PRIVATE_GRADIENT_PROCESSING_ENGINE}"
)

print(
    "Maximum Gradient Norm              : "
    f"{SPP_GAN_PRIVATE_GRADIENT_CLIPPING_NORM}"
)

print(
    "Noise Multiplier                   : "
    f"{SPP_GAN_PRIVATE_GRADIENT_NOISE_MULTIPLIER}"
)

print(
    "Discriminator Per-Sample Clipping  : "
    f"{SPP_GAN_DISCRIMINATOR_PER_SAMPLE_CLIPPING}"
)

print(
    "Generator Per-Sample DP            : "
    f"{SPP_GAN_GENERATOR_PER_SAMPLE_CLIPPING}"
)

print()

print(
    "DP-SGD processing sequence:"
)

for step_number, step_name in enumerate(
    SPP_GAN_PRIVATE_GRADIENT_PROCESSING_STEPS,
    start=1
):

    print(
        f"{step_number}. {step_name}"
    )

# ==============================================================================
# VALIDATION REPORT
# ==============================================================================

print()

print(
    f"Per-Sample Clipping Configuration : "
    f"{'PASS' if SPP_GAN_DISCRIMINATOR_PER_SAMPLE_CLIPPING else 'FAIL'}"
)

print(
    f"Gaussian Noise Configuration      : "
    f"{'PASS' if SPP_GAN_MANUAL_DP_NOISE_ENABLED else 'FAIL'}"
)

print(
    f"Clipping Norm Validation          : "
    f"{'PASS' if SPP_GAN_PRIVATE_GRADIENT_CLIPPING_NORM > 0.0 else 'FAIL'}"
)

print(
    f"Noise Multiplier Validation       : "
    f"{'PASS' if SPP_GAN_PRIVATE_GRADIENT_NOISE_MULTIPLIER > 0.0 else 'FAIL'}"
)

print(
    f"External DP Engine Disabled       : "
    f"{'PASS' if not SPP_GAN_OPACUS_NOISE_ENABLED else 'FAIL'}"
)

print()

print(
    f"Private Gradient Processing Status: "
    f"{'PASS' if SPP_GAN_PRIVATE_GRADIENT_PROCESSING_VALID else 'FAIL'}"
)

# ==============================================================================
# FAIL-FAST PIPELINE CHECK
# ==============================================================================

if not SPP_GAN_PRIVATE_GRADIENT_PROCESSING_VALID:

    raise ValueError(
        "SPP-GAN manual DP-SGD gradient processing configuration failed."
    )

print()

print(
    "Manual DP-SGD gradient processing is configured."
)

print(
    "Per-sample discriminator gradients are clipped "
    "before aggregation."
)

print(
    "Both raw and clipped gradient norms are retained "
    "for validation and diagnostics."
)

print(
    "Gaussian noise is calibrated using the clipping norm "
    "and noise multiplier."
)

print(
    "No Opacus privacy engine is used."
)

print()

print(
    "PART L4 — Privacy-protected gradient processing completed."
)

====================================================================================================
PART L4 — PRIVACY-PROTECTED GRADIENT PROCESSING
====================================================================================================

Private Gradient Processing Engine : Manual DP-SGD
Maximum Gradient Norm              : 1.0
Noise Multiplier                   : 1.1
Discriminator Per-Sample Clipping  : True
Generator Per-Sample DP            : False

DP-SGD processing sequence:
1. Per-sample gradient computation
2. Per-sample L2 gradient clipping
3. Clipped gradient aggregation
4. Gaussian noise addition
5. Batch gradient normalization
6. Optimizer parameter update

Per-Sample Clipping Configuration : PASS
Gaussian Noise Configuration      : PASS
Clipping Norm Validation          : PASS
Noise Multiplier Validation       : PASS
External DP Engine Disabled       : PASS

Private Gradient Processing Status: PASS

Manual DP-SGD gradient processing is configured.
Per-sample discriminator gradients are clipped before aggregation.
Both raw and clipped gradient norms are retained for validation and diagnostics.
Gaussian noise is calibrated using the clipping norm and noise multiplier.
No Opacus privacy engine is used.

PART L4 — Privacy-protected gradient processing completed.

In [179]:
# ==============================================================================
# PART L5 — GENERATOR PRIVACY POST-PROCESSING TEST
# ==============================================================================

print("=" * 100)
print("PART L5 — GENERATOR PRIVACY POST-PROCESSING TEST")
print("=" * 100)

# ==============================================================================
# GENERATOR PRIVACY CHECKS
# ==============================================================================

SPP_GAN_GENERATOR_PRIVACY_CHECKS = {}

for dataset in DATASETS:

    generator = SPP_GAN_GENERATORS[dataset]
    discriminator = SPP_GAN_DISCRIMINATORS[dataset]
    generator_optimizer = SPP_GAN_GENERATOR_OPTIMIZERS[dataset]
    discriminator_optimizer = SPP_GAN_DISCRIMINATOR_OPTIMIZERS[dataset]

    # --------------------------------------------------------------------------
    # DATASET-SPECIFIC DIMENSIONS
    # --------------------------------------------------------------------------

    generator_input_dimension = int(
        SPP_GAN_GENERATOR_INPUT_DIMENSIONS[dataset]
    )

    expected_output_dimension = int(
        SPP_GAN_OUTPUT_DIMENSIONS[dataset]
    )

    # --------------------------------------------------------------------------
    # PRESERVE MODEL STATES
    # --------------------------------------------------------------------------

    generator_training_state = generator.training
    discriminator_training_state = discriminator.training

    generator_optimizer.zero_grad(
        set_to_none=True
    )

    discriminator_optimizer.zero_grad(
        set_to_none=True
    )

    generator.eval()
    discriminator.eval()

    # --------------------------------------------------------------------------
    # GENERATOR FORWARD PASS
    # --------------------------------------------------------------------------

    test_batch_size = 4

    noise = torch.randn(
        test_batch_size,
        generator_input_dimension,
        device=SPP_GAN_DEVICE,
        dtype=torch.float32
    )

    generated_features = generator(
        noise
    )

    # --------------------------------------------------------------------------
    # GENERATOR OUTPUT VALIDATION
    # --------------------------------------------------------------------------

    generator_output_valid = (
        generated_features.ndim == 2
        and
        generated_features.shape[0] == test_batch_size
        and
        generated_features.shape[1] == expected_output_dimension
        and
        torch.isfinite(
            generated_features
        ).all().item()
    )

    if not generator_output_valid:

        raise ValueError(
            f"{dataset}: Generator output validation failed. "
            f"Expected shape "
            f"({test_batch_size}, {expected_output_dimension}), "
            f"got {tuple(generated_features.shape)}."
        )

    # --------------------------------------------------------------------------
    # DISCRIMINATOR SIGNAL
    # --------------------------------------------------------------------------

    fake_logits = discriminator(
        generated_features
    )

    # --------------------------------------------------------------------------
    # GENERATOR LOSS
    # --------------------------------------------------------------------------

    generator_loss = spp_gan_generator_loss(
        fake_logits
    )

    generator_loss_finite = bool(
        torch.isfinite(
            generator_loss
        ).item()
    )

    # --------------------------------------------------------------------------
    # GENERATOR BACKWARD PASS
    # --------------------------------------------------------------------------

    generator_loss.backward()

    # --------------------------------------------------------------------------
    # GENERATOR GRADIENT VALIDATION
    # --------------------------------------------------------------------------

    generator_gradient_parameters = [
        parameter
        for parameter in generator.parameters()
        if (
            parameter.requires_grad
            and
            parameter.grad is not None
        )
    ]

    gradient_exists = (
        len(
            generator_gradient_parameters
        )
        >
        0
    )

    generator_gradients_finite = (
        all(
            torch.isfinite(
                parameter.grad
            ).all().item()
            for parameter
            in generator_gradient_parameters
        )
        if generator_gradient_parameters
        else False
    )

    # --------------------------------------------------------------------------
    # GENERATOR GRADIENT NORM
    # --------------------------------------------------------------------------

    if generator_gradient_parameters:

        generator_gradient_squared_norm = sum(
            parameter.grad.detach().pow(2).sum()
            for parameter
            in generator_gradient_parameters
        )

        generator_gradient_norm = torch.sqrt(
            generator_gradient_squared_norm
            +
            1e-12
        )

    else:

        generator_gradient_norm = torch.tensor(
            float("nan"),
            device=SPP_GAN_DEVICE
        )

    generator_gradient_norm_finite = bool(
        torch.isfinite(
            generator_gradient_norm
        ).item()
    )

    generator_gradient_valid = (
        gradient_exists
        and
        generator_gradients_finite
        and
        generator_gradient_norm_finite
        and
        generator_gradient_norm.item() > 0.0
    )

    # --------------------------------------------------------------------------
    # DIRECT GENERATOR DP VALIDATION
    # --------------------------------------------------------------------------

    direct_generator_dp_disabled = (
        SPP_GAN_PRIVACY_APPLY_TO_GENERATOR
        is False
    )

    generator_per_sample_clipping_disabled = (
        SPP_GAN_GENERATOR_PER_SAMPLE_CLIPPING
        is False
    )

    generator_post_processing_valid = (
        direct_generator_dp_disabled
        and
        generator_per_sample_clipping_disabled
    )

    # --------------------------------------------------------------------------
    # OVERALL VALIDATION
    # --------------------------------------------------------------------------

    valid = (
        generator_output_valid
        and
        generator_loss_finite
        and
        generator_gradient_valid
        and
        generator_post_processing_valid
    )

    SPP_GAN_GENERATOR_PRIVACY_CHECKS[
        dataset
    ] = valid

    # --------------------------------------------------------------------------
    # CLEAR TEST GRADIENTS
    # --------------------------------------------------------------------------

    generator_optimizer.zero_grad(
        set_to_none=True
    )

    discriminator_optimizer.zero_grad(
        set_to_none=True
    )

    # --------------------------------------------------------------------------
    # RESTORE MODEL STATES
    # --------------------------------------------------------------------------

    if generator_training_state:
        generator.train()
    else:
        generator.eval()

    if discriminator_training_state:
        discriminator.train()
    else:
        discriminator.eval()

    # --------------------------------------------------------------------------
    # REPORT
    # --------------------------------------------------------------------------

    print()

    print(
        f"Dataset                          : "
        f"{dataset}"
    )

    print(
        f"Generator Input Dimension       : "
        f"{generator_input_dimension}"
    )

    print(
        f"Generator Output Dimension      : "
        f"{generated_features.shape[1]}"
    )

    print(
        f"Generator Output Validation     : "
        f"{'PASS' if generator_output_valid else 'FAIL'}"
    )

    print(
        f"Generator Loss                  : "
        f"{generator_loss.item():.6f}"
    )

    print(
        f"Generator Loss Finite           : "
        f"{'PASS' if generator_loss_finite else 'FAIL'}"
    )

    print(
        f"Gradient Available              : "
        f"{'PASS' if gradient_exists else 'FAIL'}"
    )

    print(
        f"Gradient Finite                 : "
        f"{'PASS' if generator_gradients_finite else 'FAIL'}"
    )

    print(
        f"Gradient Norm                   : "
        f"{generator_gradient_norm.item():.6e}"
    )

    print(
        f"Gradient Norm Finite            : "
        f"{'PASS' if generator_gradient_norm_finite else 'FAIL'}"
    )

    print(
        f"Direct Generator DP Disabled    : "
        f"{'PASS' if direct_generator_dp_disabled else 'FAIL'}"
    )

    print(
        f"Generator Per-Sample DP Disabled: "
        f"{'PASS' if generator_per_sample_clipping_disabled else 'FAIL'}"
    )

    print(
        f"Generator Post-Processing       : "
        f"{'PASS' if generator_post_processing_valid else 'FAIL'}"
    )

    print(
        f"Overall                         : "
        f"{'PASS' if valid else 'FAIL'}"
    )

# ==============================================================================
# FAIL-FAST VALIDATION
# ==============================================================================

print()

if not all(
    SPP_GAN_GENERATOR_PRIVACY_CHECKS.values()
):

    failed_datasets = [
        dataset
        for dataset, status
        in SPP_GAN_GENERATOR_PRIVACY_CHECKS.items()
        if not status
    ]

    raise ValueError(
        "SPP-GAN generator privacy post-processing validation failed "
        f"for datasets: {failed_datasets}"
    )

print(
    "Generator privacy post-processing validated "
    "for all datasets."
)

print()

print(
    "The generator is not directly subjected to "
    "DP-SGD clipping or Gaussian noise."
)

print(
    "Generator gradients are learned through the "
    "discriminator's privatized training mechanism."
)

print(
    "Generator training is treated as post-processing "
    "provided that the generator does not directly access "
    "private real records."
)

print()

print(
    "PART L5 — Generator privacy post-processing test completed."
)

====================================================================================================
PART L5 — GENERATOR PRIVACY POST-PROCESSING TEST
====================================================================================================

Dataset                          : Adult Income
Generator Input Dimension       : 128
Generator Output Dimension      : 14
Generator Output Validation     : PASS
Generator Loss                  : 0.290606
Generator Loss Finite           : PASS
Gradient Available              : PASS
Gradient Finite                 : PASS
Gradient Norm                   : 4.028513e+00
Gradient Norm Finite            : PASS
Direct Generator DP Disabled    : PASS
Generator Per-Sample DP Disabled: PASS
Generator Post-Processing       : PASS
Overall                         : PASS

Dataset                          : Bank Marketing
Generator Input Dimension       : 128
Generator Output Dimension      : 16
Generator Output Validation     : PASS
Generator Loss                  : 0.595881
Generator Loss Finite           : PASS
Gradient Available              : PASS
Gradient Finite                 : PASS
Gradient Norm                   : 6.231110e+00
Gradient Norm Finite            : PASS
Direct Generator DP Disabled    : PASS
Generator Per-Sample DP Disabled: PASS
Generator Post-Processing       : PASS
Overall                         : PASS

Dataset                          : diabetes_130us
Generator Input Dimension       : 128
Generator Output Dimension      : 47
Generator Output Validation     : PASS
Generator Loss                  : 1.000415
Generator Loss Finite           : PASS
Gradient Available              : PASS
Gradient Finite                 : PASS
Gradient Norm                   : 8.499375e+00
Gradient Norm Finite            : PASS
Direct Generator DP Disabled    : PASS
Generator Per-Sample DP Disabled: PASS
Generator Post-Processing       : PASS
Overall                         : PASS

Generator privacy post-processing validated for all datasets.

The generator is not directly subjected to DP-SGD clipping or Gaussian noise.
Generator gradients are learned through the discriminator's privatized training mechanism.
Generator training is treated as post-processing provided that the generator does not directly access private real records.

PART L5 — Generator privacy post-processing test completed.

In [180]:
# ==============================================================================
# PART L6 — DISCRIMINATOR PRIVACY MECHANISM TEST
# ==============================================================================

print("=" * 100)
print("PART L6 — DISCRIMINATOR PRIVACY MECHANISM TEST")
print("=" * 100)

# ==============================================================================
# DISCRIMINATOR PRIVACY CHECK CONTAINER
# ==============================================================================

SPP_GAN_DISCRIMINATOR_PRIVACY_CHECKS = {}

test_batch_size = 4

for dataset in DATASETS:

    discriminator = (
        SPP_GAN_DISCRIMINATORS[
            dataset
        ]
    )

    optimizer = (
        SPP_GAN_DISCRIMINATOR_OPTIMIZERS[
            dataset
        ]
    )

    # --------------------------------------------------------------------------
    # Dataset-Specific Dimensions
    # --------------------------------------------------------------------------

    discriminator_input_dimension = int(
        SPP_GAN_DISCRIMINATOR_INPUT_DIMENSIONS[
            dataset
        ]
    )

    output_dimension = int(
        SPP_GAN_OUTPUT_DIMENSIONS[
            dataset
        ]
    )

    if (
        discriminator_input_dimension
        !=
        output_dimension
    ):

        raise ValueError(
            f"{dataset}: Discriminator input dimension "
            f"({discriminator_input_dimension}) does not match "
            f"GAN output dimension ({output_dimension})."
        )

    # --------------------------------------------------------------------------
    # Preserve Original States
    # --------------------------------------------------------------------------

    discriminator_training_state = (
        discriminator.training
    )

    discriminator_model_state = copy.deepcopy(
        discriminator.state_dict()
    )

    optimizer_state = copy.deepcopy(
        optimizer.state_dict()
    )

    optimizer.zero_grad(
        set_to_none=True
    )

    discriminator.eval()

    # ==========================================================================
    # PER-SAMPLE GRADIENT COMPUTATION
    # ==========================================================================

    trainable_parameters = [
        parameter
        for parameter
        in discriminator.parameters()
        if parameter.requires_grad
    ]

    per_sample_gradients = []

    sample_losses = []

    for sample_index in range(
        test_batch_size
    ):

        sample_features = torch.randn(
            1,
            discriminator_input_dimension,
            device=SPP_GAN_DEVICE,
            dtype=torch.float32
        )

        sample_logits = discriminator(
            sample_features
        )

        # ----------------------------------------------------------------------
        # IMPORTANT:
        # Target shape is forced to exactly match discriminator output shape.
        # ----------------------------------------------------------------------

        sample_target = torch.ones_like(
            sample_logits
        )

        sample_loss = (
            SPP_GAN_ADVERSARIAL_CRITERION(
                sample_logits,
                sample_target
            )
        )

        sample_losses.append(
            sample_loss.detach()
        )

        sample_gradients = torch.autograd.grad(
            sample_loss,
            trainable_parameters,
            retain_graph=False,
            create_graph=False,
            allow_unused=True
        )

        sample_gradients = [
            (
                torch.zeros_like(parameter)
                if gradient is None
                else gradient.detach()
            )
            for parameter, gradient
            in zip(
                trainable_parameters,
                sample_gradients
            )
        ]

        per_sample_gradients.append(
            sample_gradients
        )

    # ==========================================================================
    # PER-SAMPLE GRADIENT VALIDATION
    # ==========================================================================

    parameter_count = len(
        trainable_parameters
    )

    per_sample_gradient_count_valid = (
        len(
            per_sample_gradients
        )
        ==
        test_batch_size
    )

    per_sample_parameter_count_valid = all(
        len(
            sample_gradients
        )
        ==
        parameter_count
        for sample_gradients
        in per_sample_gradients
    )

    per_sample_gradients_finite = all(
        torch.isfinite(
            gradient
        ).all().item()
        for sample_gradients
        in per_sample_gradients
        for gradient
        in sample_gradients
    )

    # ==========================================================================
    # PRIVATE DP-SGD PROCESSING
    # ==========================================================================

    if (
        per_sample_gradient_count_valid
        and
        per_sample_parameter_count_valid
        and
        per_sample_gradients_finite
    ):

        private_gradient_result = (
            spp_gan_private_gradient_processing(
                per_sample_gradients=(
                    per_sample_gradients
                ),
                max_grad_norm=(
                    SPP_GAN_PRIVATE_GRADIENT_CLIPPING_NORM
                ),
                noise_multiplier=(
                    SPP_GAN_PRIVATE_GRADIENT_NOISE_MULTIPLIER
                )
            )
        )

        private_gradients = (
            private_gradient_result[
                "Private Gradients"
            ]
        )

        sample_gradient_norms = (
            private_gradient_result[
                "Sample Gradient Norms"
            ]
        )

        clipped_gradient_norms = (
            private_gradient_result[
                "Clipped Gradient Norms"
            ]
        )

        clipping_factors = (
            private_gradient_result[
                "Clipping Factors"
            ]
        )

        noise_standard_deviation = float(
            private_gradient_result[
                "Noise Standard Deviation"
            ]
        )

    else:

        private_gradients = []

        sample_gradient_norms = torch.tensor(
            [],
            device=SPP_GAN_DEVICE
        )

        clipped_gradient_norms = torch.tensor(
            [],
            device=SPP_GAN_DEVICE
        )

        clipping_factors = torch.tensor(
            [],
            device=SPP_GAN_DEVICE
        )

        noise_standard_deviation = float(
            "nan"
        )

    # ==========================================================================
    # PRIVATE GRADIENT VALIDATION
    # ==========================================================================

    private_gradient_count_valid = (
        len(
            private_gradients
        )
        ==
        parameter_count
    )

    private_gradients_finite = (
        all(
            torch.isfinite(
                gradient
            ).all().item()
            for gradient
            in private_gradients
        )
        if private_gradients
        else False
    )

    sample_gradient_norms_finite = (
        bool(
            torch.isfinite(
                sample_gradient_norms
            ).all().item()
        )
        if sample_gradient_norms.numel() > 0
        else False
    )

    clipped_gradient_norms_finite = (
        bool(
            torch.isfinite(
                clipped_gradient_norms
            ).all().item()
        )
        if clipped_gradient_norms.numel() > 0
        else False
    )

    clipping_factors_finite = (
        bool(
            torch.isfinite(
                clipping_factors
            ).all().item()
        )
        if clipping_factors.numel() > 0
        else False
    )

    # ==========================================================================
    # CLIPPING VALIDATION
    # ==========================================================================

    clipping_norm_valid = (
        SPP_GAN_PRIVATE_GRADIENT_CLIPPING_NORM
        >
        0.0
    )

    # --------------------------------------------------------------------------
    # IMPORTANT:
    # Raw gradient norms are allowed to exceed C.
    # Only clipped norms must satisfy the DP clipping bound.
    # --------------------------------------------------------------------------

    raw_gradients_exceeding_bound = (
        bool(
            (
                sample_gradient_norms
                >
                SPP_GAN_PRIVATE_GRADIENT_CLIPPING_NORM
            ).any().item()
        )
        if sample_gradient_norms.numel() > 0
        else False
    )

    clipping_bound_respected = (
        bool(
            (
                clipped_gradient_norms
                <=
                SPP_GAN_PRIVATE_GRADIENT_CLIPPING_NORM
                +
                1e-6
            ).all().item()
        )
        if clipped_gradient_norms.numel() > 0
        else False
    )

    clipping_was_applied_when_required = (
        (
            not raw_gradients_exceeding_bound
        )
        or
        bool(
            (
                clipping_factors[
                    sample_gradient_norms
                    >
                    SPP_GAN_PRIVATE_GRADIENT_CLIPPING_NORM
                ]
                <
                1.0
            ).all().item()
        )
    )

    # ==========================================================================
    # NOISE VALIDATION
    # ==========================================================================

    noise_standard_deviation_valid = (
        np.isfinite(
            noise_standard_deviation
        )
        and
        noise_standard_deviation > 0.0
    )

    # ==========================================================================
    # OVERALL PRIVACY VALIDATION
    # ==========================================================================

    valid = (
        per_sample_gradient_count_valid
        and
        per_sample_parameter_count_valid
        and
        per_sample_gradients_finite
        and
        private_gradient_count_valid
        and
        private_gradients_finite
        and
        sample_gradient_norms_finite
        and
        clipped_gradient_norms_finite
        and
        clipping_factors_finite
        and
        clipping_norm_valid
        and
        clipping_bound_respected
        and
        clipping_was_applied_when_required
        and
        noise_standard_deviation_valid
        and
        SPP_GAN_DISCRIMINATOR_PER_SAMPLE_CLIPPING
        and
        SPP_GAN_MANUAL_DP_NOISE_ENABLED
        and
        not SPP_GAN_OPACUS_NOISE_ENABLED
    )

    # ==========================================================================
    # STORE VALIDATION RESULTS
    # ==========================================================================

    SPP_GAN_DISCRIMINATOR_PRIVACY_CHECKS[
        dataset
    ] = {

        "Per-Sample Gradient Count Valid":
            per_sample_gradient_count_valid,

        "Per-Sample Parameter Count Valid":
            per_sample_parameter_count_valid,

        "Per-Sample Gradients Finite":
            per_sample_gradients_finite,

        "Raw Gradient Norms Finite":
            sample_gradient_norms_finite,

        "Clipped Gradient Norms Finite":
            clipped_gradient_norms_finite,

        "Clipping Factors Finite":
            clipping_factors_finite,

        "Raw Gradients Exceed Bound":
            raw_gradients_exceeding_bound,

        "Clipping Bound Respected":
            clipping_bound_respected,

        "Clipping Applied When Required":
            clipping_was_applied_when_required,

        "Private Gradient Count Valid":
            private_gradient_count_valid,

        "Private Gradients Finite":
            private_gradients_finite,

        "Noise Standard Deviation Valid":
            noise_standard_deviation_valid,

        "Per-Sample Clipping Enabled":
            SPP_GAN_DISCRIMINATOR_PER_SAMPLE_CLIPPING,

        "Manual Gaussian Noise Enabled":
            SPP_GAN_MANUAL_DP_NOISE_ENABLED,

        "Opacus Noise Disabled":
            not SPP_GAN_OPACUS_NOISE_ENABLED,

        "Privacy Mechanism Valid":
            valid
    }

    # ==========================================================================
    # RESTORE ORIGINAL STATES
    # ==========================================================================

    discriminator.load_state_dict(
        discriminator_model_state
    )

    optimizer.load_state_dict(
        optimizer_state
    )

    optimizer.zero_grad(
        set_to_none=True
    )

    if discriminator_training_state:

        discriminator.train()

    else:

        discriminator.eval()

    # ==========================================================================
    # DATASET REPORT
    # ==========================================================================

    print()

    print(
        f"Dataset                         : "
        f"{dataset}"
    )

    print(
        f"Test Batch Size                 : "
        f"{test_batch_size}"
    )

    print(
        f"Discriminator Input Dimension   : "
        f"{discriminator_input_dimension}"
    )

    print(
        f"Trainable Parameters            : "
        f"{parameter_count:,}"
    )

    print()

    print(
        f"Per-Sample Gradient Count       : "
        f"{'PASS' if per_sample_gradient_count_valid else 'FAIL'}"
    )

    print(
        f"Per-Sample Parameter Count      : "
        f"{'PASS' if per_sample_parameter_count_valid else 'FAIL'}"
    )

    print(
        f"Per-Sample Gradients Finite     : "
        f"{'PASS' if per_sample_gradients_finite else 'FAIL'}"
    )

    print()

    print(
        f"Maximum Raw Gradient Norm       : "
        f"{sample_gradient_norms.max().item():.6e}"
    )

    print(
        f"Mean Raw Gradient Norm          : "
        f"{sample_gradient_norms.mean().item():.6e}"
    )

    print(
        f"Maximum Clipped Gradient Norm   : "
        f"{clipped_gradient_norms.max().item():.6e}"
    )

    print(
        f"Mean Clipped Gradient Norm      : "
        f"{clipped_gradient_norms.mean().item():.6e}"
    )

    print()

    print(
        f"Clipping Norm                   : "
        f"{SPP_GAN_PRIVATE_GRADIENT_CLIPPING_NORM}"
    )

    print(
        f"Raw Gradients Exceed Bound      : "
        f"{'YES' if raw_gradients_exceeding_bound else 'NO'}"
    )

    print(
        f"Clipping Bound Respected        : "
        f"{'PASS' if clipping_bound_respected else 'FAIL'}"
    )

    print(
        f"Clipping Applied When Required  : "
        f"{'PASS' if clipping_was_applied_when_required else 'FAIL'}"
    )

    print()

    print(
        f"Private Gradient Count          : "
        f"{'PASS' if private_gradient_count_valid else 'FAIL'}"
    )

    print(
        f"Private Gradients Finite        : "
        f"{'PASS' if private_gradients_finite else 'FAIL'}"
    )

    print(
        f"Noise Multiplier                : "
        f"{SPP_GAN_PRIVATE_GRADIENT_NOISE_MULTIPLIER}"
    )

    print(
        f"Noise Standard Deviation       : "
        f"{noise_standard_deviation:.6e}"
    )

    print(
        f"Gaussian Noise Validation       : "
        f"{'PASS' if noise_standard_deviation_valid else 'FAIL'}"
    )

    print()

    print(
        f"Per-Sample DP Clipping          : "
        f"{'PASS' if SPP_GAN_DISCRIMINATOR_PER_SAMPLE_CLIPPING else 'FAIL'}"
    )

    print(
        f"Manual Gaussian Noise           : "
        f"{'PASS' if SPP_GAN_MANUAL_DP_NOISE_ENABLED else 'FAIL'}"
    )

    print(
        f"Opacus Disabled                 : "
        f"{'PASS' if not SPP_GAN_OPACUS_NOISE_ENABLED else 'FAIL'}"
    )

    print()

    print(
        f"Privacy Mechanism               : "
        f"{'PASS' if valid else 'FAIL'}"
    )

# ==============================================================================
# OVERALL DISCRIMINATOR PRIVACY VALIDATION
# ==============================================================================

SPP_GAN_DISCRIMINATOR_PRIVACY_VALIDATION_STATUS = all(
    checks[
        "Privacy Mechanism Valid"
    ]
    for checks
    in SPP_GAN_DISCRIMINATOR_PRIVACY_CHECKS.values()
)

print()

print(
    f"Overall Discriminator Privacy Validation : "
    f"{'PASS' if SPP_GAN_DISCRIMINATOR_PRIVACY_VALIDATION_STATUS else 'FAIL'}"
)

# ==============================================================================
# FAIL-FAST PIPELINE CHECK
# ==============================================================================

if not SPP_GAN_DISCRIMINATOR_PRIVACY_VALIDATION_STATUS:

    failed_datasets = [
        dataset
        for dataset, checks
        in SPP_GAN_DISCRIMINATOR_PRIVACY_CHECKS.items()
        if not checks[
            "Privacy Mechanism Valid"
        ]
    ]

    raise ValueError(
        "SPP-GAN discriminator privacy mechanism validation "
        f"failed for datasets: {failed_datasets}"
    )

print()

print(
    "Discriminator per-sample gradient clipping, "
    "gradient aggregation, and calibrated Gaussian "
    "noise processing validated successfully."
)

print()

print(
    "Raw gradient norms may exceed the clipping bound; "
    "only clipped gradient norms are required to satisfy "
    "the maximum gradient norm."
)

print()

print(
    "PART L6 — Discriminator privacy mechanism test completed."
)

====================================================================================================
PART L6 — DISCRIMINATOR PRIVACY MECHANISM TEST
====================================================================================================

Dataset                         : Adult Income
Test Batch Size                 : 4
Discriminator Input Dimension   : 14
Trainable Parameters            : 10

Per-Sample Gradient Count       : PASS
Per-Sample Parameter Count      : PASS
Per-Sample Gradients Finite     : PASS

Maximum Raw Gradient Norm       : 9.846799e+00
Mean Raw Gradient Norm          : 4.571261e+00
Maximum Clipped Gradient Norm   : 1.000000e+00
Mean Clipped Gradient Norm      : 1.000000e+00

Clipping Norm                   : 1.0
Raw Gradients Exceed Bound      : YES
Clipping Bound Respected        : PASS
Clipping Applied When Required  : PASS

Private Gradient Count          : PASS
Private Gradients Finite        : PASS
Noise Multiplier                : 1.1
Noise Standard Deviation       : 2.750000e-01
Gaussian Noise Validation       : PASS

Per-Sample DP Clipping          : PASS
Manual Gaussian Noise           : PASS
Opacus Disabled                 : PASS

Privacy Mechanism               : PASS

Dataset                         : Bank Marketing
Test Batch Size                 : 4
Discriminator Input Dimension   : 16
Trainable Parameters            : 10

Per-Sample Gradient Count       : PASS
Per-Sample Parameter Count      : PASS
Per-Sample Gradients Finite     : PASS

Maximum Raw Gradient Norm       : 1.292992e+01
Mean Raw Gradient Norm          : 1.114400e+01
Maximum Clipped Gradient Norm   : 1.000000e+00
Mean Clipped Gradient Norm      : 1.000000e+00

Clipping Norm                   : 1.0
Raw Gradients Exceed Bound      : YES
Clipping Bound Respected        : PASS
Clipping Applied When Required  : PASS

Private Gradient Count          : PASS
Private Gradients Finite        : PASS
Noise Multiplier                : 1.1
Noise Standard Deviation       : 2.750000e-01
Gaussian Noise Validation       : PASS

Per-Sample DP Clipping          : PASS
Manual Gaussian Noise           : PASS
Opacus Disabled                 : PASS

Privacy Mechanism               : PASS

Dataset                         : diabetes_130us
Test Batch Size                 : 4
Discriminator Input Dimension   : 47
Trainable Parameters            : 10

Per-Sample Gradient Count       : PASS
Per-Sample Parameter Count      : PASS
Per-Sample Gradients Finite     : PASS

Maximum Raw Gradient Norm       : 1.514022e+01
Mean Raw Gradient Norm          : 8.828482e+00
Maximum Clipped Gradient Norm   : 1.000000e+00
Mean Clipped Gradient Norm      : 1.000000e+00

Clipping Norm                   : 1.0
Raw Gradients Exceed Bound      : YES
Clipping Bound Respected        : PASS
Clipping Applied When Required  : PASS

Private Gradient Count          : PASS
Private Gradients Finite        : PASS
Noise Multiplier                : 1.1
Noise Standard Deviation       : 2.750000e-01
Gaussian Noise Validation       : PASS

Per-Sample DP Clipping          : PASS
Manual Gaussian Noise           : PASS
Opacus Disabled                 : PASS

Privacy Mechanism               : PASS

Overall Discriminator Privacy Validation : PASS

Discriminator per-sample gradient clipping, gradient aggregation, and calibrated Gaussian noise processing validated successfully.

Raw gradient norms may exceed the clipping bound; only clipped gradient norms are required to satisfy the maximum gradient norm.

PART L6 — Discriminator privacy mechanism test completed.

In [181]:
# ==============================================================================
# PART L7 — PRIVACY MECHANISM VALIDATION
# ==============================================================================

print("=" * 100)
print("PART L7 — PRIVACY MECHANISM VALIDATION")
print("=" * 100)

# ==============================================================================
# GLOBAL PRIVACY MECHANISM CHECKS
# ==============================================================================

SPP_GAN_PRIVACY_MECHANISM_CHECKS = {

    # --------------------------------------------------------------------------
    # Privacy Mechanism
    # --------------------------------------------------------------------------

    "Privacy Mechanism Valid":
        SPP_GAN_PRIVACY_MECHANISM_VALID,

    # --------------------------------------------------------------------------
    # Gaussian Noise
    # --------------------------------------------------------------------------

    "Gaussian Noise Valid":
        SPP_GAN_NOISE_MECHANISM_VALID,

    # --------------------------------------------------------------------------
    # Positive Clipping Norm
    # --------------------------------------------------------------------------

    "Positive Clipping Norm":
        (
            SPP_GAN_PRIVACY_CLIPPING_NORM
            > 0.0
        ),

    # --------------------------------------------------------------------------
    # Positive Noise Multiplier
    # --------------------------------------------------------------------------

    "Positive Noise Multiplier":
        (
            SPP_GAN_PRIVACY_NOISE_MULTIPLIER
            > 0.0
        ),

    # --------------------------------------------------------------------------
    # Discriminator Privacy Component
    # --------------------------------------------------------------------------

    "Discriminator Privacy Enabled":
        (
            SPP_GAN_PRIVACY_APPLY_TO_DISCRIMINATOR
            is True
        ),

    # --------------------------------------------------------------------------
    # Generator Direct Privacy Disabled
    # --------------------------------------------------------------------------

    "Generator Direct DP Disabled":
        (
            SPP_GAN_PRIVACY_APPLY_TO_GENERATOR
            is False
        ),

    # --------------------------------------------------------------------------
    # Per-Sample Clipping
    # --------------------------------------------------------------------------

    "Per-Sample Clipping Enabled":
        (
            SPP_GAN_DISCRIMINATOR_PER_SAMPLE_CLIPPING
            is True
        ),

    # --------------------------------------------------------------------------
    # Generator Per-Sample DP Disabled
    # --------------------------------------------------------------------------

    "Generator Per-Sample DP Disabled":
        (
            SPP_GAN_GENERATOR_PER_SAMPLE_CLIPPING
            is False
        ),

    # --------------------------------------------------------------------------
    # Manual Gaussian Noise
    # --------------------------------------------------------------------------

    "Manual Gaussian Noise Enabled":
        (
            SPP_GAN_MANUAL_DP_NOISE_ENABLED
            is True
        ),

    # --------------------------------------------------------------------------
    # Opacus Disabled
    # --------------------------------------------------------------------------

    "Opacus Disabled":
        (
            SPP_GAN_OPACUS_NOISE_ENABLED
            is False
        ),

    # --------------------------------------------------------------------------
    # Private Gradient Processing
    # --------------------------------------------------------------------------

    "Private Gradient Processing Valid":
        SPP_GAN_PRIVATE_GRADIENT_PROCESSING_VALID,

    # --------------------------------------------------------------------------
    # Generator Privacy Post-Processing
    # --------------------------------------------------------------------------

    "Generator Privacy Valid":
        all(
            SPP_GAN_GENERATOR_PRIVACY_CHECKS.values()
        ),

    # --------------------------------------------------------------------------
    # Discriminator Privacy Mechanism
    # --------------------------------------------------------------------------

    "Discriminator Privacy Valid":
        all(
            SPP_GAN_DISCRIMINATOR_PRIVACY_CHECKS.values()
        ),

    # --------------------------------------------------------------------------
    # Dataset Coverage
    # --------------------------------------------------------------------------

    "Generator Privacy Dataset Coverage":
        (
            len(
                SPP_GAN_GENERATOR_PRIVACY_CHECKS
            )
            ==
            len(DATASETS)
        ),

    "Discriminator Privacy Dataset Coverage":
        (
            len(
                SPP_GAN_DISCRIMINATOR_PRIVACY_CHECKS
            )
            ==
            len(DATASETS)
        )
}

# ==============================================================================
# DATASET-SPECIFIC PRIVACY STATUS
# ==============================================================================

SPP_GAN_PRIVACY_DATASET_VALIDATION = {}

for dataset in DATASETS:

    generator_privacy_valid = (
        SPP_GAN_GENERATOR_PRIVACY_CHECKS.get(
            dataset,
            False
        )
    )

    discriminator_privacy_valid = (
        SPP_GAN_DISCRIMINATOR_PRIVACY_CHECKS.get(
            dataset,
            False
        )
    )

    dataset_privacy_valid = (
        generator_privacy_valid
        and
        discriminator_privacy_valid
    )

    SPP_GAN_PRIVACY_DATASET_VALIDATION[
        dataset
    ] = {

        "Generator Privacy Valid":
            generator_privacy_valid,

        "Discriminator Privacy Valid":
            discriminator_privacy_valid,

        "Overall Privacy Valid":
            dataset_privacy_valid
    }

# ==============================================================================
# GLOBAL VALIDATION REPORT
# ==============================================================================

print()

print(
    "Global Privacy Mechanism Validation:"
)

print()

for check, status in (
    SPP_GAN_PRIVACY_MECHANISM_CHECKS.items()
):

    print(
        f"{check:45s} : "
        f"{'PASS' if status else 'FAIL'}"
    )

# ==============================================================================
# DATASET-SPECIFIC VALIDATION REPORT
# ==============================================================================

print()

print(
    "Dataset-Specific Privacy Validation:"
)

print()

for dataset, checks in (
    SPP_GAN_PRIVACY_DATASET_VALIDATION.items()
):

    print(
        f"{dataset:25s} : "
        f"{'PASS' if checks['Overall Privacy Valid'] else 'FAIL'}"
    )

    print(
        f"  Generator Privacy       : "
        f"{'PASS' if checks['Generator Privacy Valid'] else 'FAIL'}"
    )

    print(
        f"  Discriminator Privacy   : "
        f"{'PASS' if checks['Discriminator Privacy Valid'] else 'FAIL'}"
    )

# ==============================================================================
# OVERALL PRIVACY MECHANISM VALIDATION
# ==============================================================================

SPP_GAN_PRIVACY_MECHANISM_VALIDATION_STATUS = (
    all(
        SPP_GAN_PRIVACY_MECHANISM_CHECKS.values()
    )
    and
    all(
        checks["Overall Privacy Valid"]
        for checks
        in SPP_GAN_PRIVACY_DATASET_VALIDATION.values()
    )
)

# ==============================================================================
# OVERALL STATUS
# ==============================================================================

print()

print(
    f"Overall Privacy Mechanism Validation : "
    f"{'PASS' if SPP_GAN_PRIVACY_MECHANISM_VALIDATION_STATUS else 'FAIL'}"
)

# ==============================================================================
# FAIL-FAST PIPELINE CHECK
# ==============================================================================

if not SPP_GAN_PRIVACY_MECHANISM_VALIDATION_STATUS:

    failed_global_checks = [
        check
        for check, status
        in SPP_GAN_PRIVACY_MECHANISM_CHECKS.items()
        if not status
    ]

    failed_datasets = [
        dataset
        for dataset, checks
        in SPP_GAN_PRIVACY_DATASET_VALIDATION.items()
        if not checks[
            "Overall Privacy Valid"
        ]
    ]

    raise ValueError(
        "SPP-GAN privacy mechanism validation failed. "
        f"Failed global checks: {failed_global_checks}. "
        f"Failed datasets: {failed_datasets}"
    )

print()

print(
    "All SPP-GAN privacy mechanism checks passed."
)

print(
    "Discriminator privacy protection, per-sample clipping, "
    "Gaussian gradient perturbation, and generator post-processing "
    "have been validated."
)

print()

print(
    "PART L7 — Privacy mechanism validation completed."
)

====================================================================================================
PART L7 — PRIVACY MECHANISM VALIDATION
====================================================================================================

Global Privacy Mechanism Validation:

Privacy Mechanism Valid                       : PASS
Gaussian Noise Valid                          : PASS
Positive Clipping Norm                        : PASS
Positive Noise Multiplier                     : PASS
Discriminator Privacy Enabled                 : PASS
Generator Direct DP Disabled                  : PASS
Per-Sample Clipping Enabled                   : PASS
Generator Per-Sample DP Disabled              : PASS
Manual Gaussian Noise Enabled                 : PASS
Opacus Disabled                               : PASS
Private Gradient Processing Valid             : PASS
Generator Privacy Valid                       : PASS
Discriminator Privacy Valid                   : PASS
Generator Privacy Dataset Coverage            : PASS
Discriminator Privacy Dataset Coverage        : PASS

Dataset-Specific Privacy Validation:

Adult Income              : PASS
  Generator Privacy       : PASS
  Discriminator Privacy   : PASS
Bank Marketing            : PASS
  Generator Privacy       : PASS
  Discriminator Privacy   : PASS
diabetes_130us            : PASS
  Generator Privacy       : PASS
  Discriminator Privacy   : PASS

Overall Privacy Mechanism Validation : PASS

All SPP-GAN privacy mechanism checks passed.
Discriminator privacy protection, per-sample clipping, Gaussian gradient perturbation, and generator post-processing have been validated.

PART L7 — Privacy mechanism validation completed.

In [182]:
# ==============================================================================
# PART L8 — PRIVACY MECHANISM SUMMARY
# ==============================================================================

print("=" * 100)
print("PART L8 — PRIVACY MECHANISM SUMMARY")
print("=" * 100)

# ==============================================================================
# PRIVACY MECHANISM SUMMARY
# ==============================================================================

SPP_GAN_PRIVACY_MECHANISM_SUMMARY = {

    # --------------------------------------------------------------------------
    # Core Privacy Mechanism
    # --------------------------------------------------------------------------

    "Privacy Mechanism":
        SPP_GAN_PRIVACY_MECHANISM_NAME,

    "Privacy Mechanism Normalized":
        SPP_GAN_PRIVACY_MECHANISM_NORMALIZED,

    "Privacy Engine":
        SPP_GAN_PRIVACY_ENGINE,

    # --------------------------------------------------------------------------
    # Noise Configuration
    # --------------------------------------------------------------------------

    "Noise Distribution":
        SPP_GAN_PRIVACY_NOISE_DISTRIBUTION,

    "Noise Multiplier":
        SPP_GAN_PRIVACY_NOISE_MULTIPLIER,

    "Manual Gaussian Noise":
        SPP_GAN_MANUAL_DP_NOISE_ENABLED,

    "Opacus Enabled":
        SPP_GAN_OPACUS_NOISE_ENABLED,

    # --------------------------------------------------------------------------
    # Gradient Protection
    # --------------------------------------------------------------------------

    "Gradient Clipping Norm":
        SPP_GAN_PRIVACY_CLIPPING_NORM,

    "Per-Sample Clipping":
        SPP_GAN_PRIVACY_PER_SAMPLE_CLIPPING,

    "Discriminator Per-Sample Clipping":
        SPP_GAN_DISCRIMINATOR_PER_SAMPLE_CLIPPING,

    "Generator Per-Sample Clipping":
        SPP_GAN_GENERATOR_PER_SAMPLE_CLIPPING,

    # --------------------------------------------------------------------------
    # Protected Components
    # --------------------------------------------------------------------------

    "Discriminator Directly Protected":
        SPP_GAN_PRIVACY_APPLY_TO_DISCRIMINATOR,

    "Generator Direct DP Disabled":
        not SPP_GAN_PRIVACY_APPLY_TO_GENERATOR,

    "Generator Privacy Status":
        SPP_GAN_GENERATOR_PRIVACY_STATUS,

    "Discriminator Privacy Status":
        SPP_GAN_DISCRIMINATOR_PRIVACY_STATUS,

    # --------------------------------------------------------------------------
    # Privacy Accounting Components
    # --------------------------------------------------------------------------

    "Privacy Accounting Component":
        SPP_GAN_PRIVACY_ACCOUNTING_COMPONENT,

    "Post-Processing Components":
        ", ".join(
            SPP_GAN_PRIVACY_POST_PROCESSING_COMPONENTS
        ),

    # --------------------------------------------------------------------------
    # Dataset Coverage
    # --------------------------------------------------------------------------

    "Datasets":
        len(DATASETS),

    "Generator Privacy Datasets":
        len(
            SPP_GAN_GENERATOR_PRIVACY_CHECKS
        ),

    "Discriminator Privacy Datasets":
        len(
            SPP_GAN_DISCRIMINATOR_PRIVACY_CHECKS
        ),

    # --------------------------------------------------------------------------
    # Validation
    # --------------------------------------------------------------------------

    "Configuration Valid":
        SPP_GAN_PRIVACY_CONFIGURATION_VALID,

    "Clipping Configuration Valid":
        SPP_GAN_PER_SAMPLE_CLIPPING_VALID,

    "Noise Mechanism Valid":
        SPP_GAN_NOISE_MECHANISM_VALID,

    "Private Gradient Processing Valid":
        SPP_GAN_PRIVATE_GRADIENT_PROCESSING_VALID,

    "Mechanism Validation Status":
        SPP_GAN_PRIVACY_MECHANISM_VALIDATION_STATUS,

    "Mechanism Valid":
        SPP_GAN_PRIVACY_MECHANISM_VALIDATION_STATUS
}

# ==============================================================================
# PRIVACY MECHANISM SUMMARY DATAFRAME
# ==============================================================================

SPP_GAN_PRIVACY_MECHANISM_SUMMARY_DF = (
    pd.DataFrame(
        list(
            SPP_GAN_PRIVACY_MECHANISM_SUMMARY.items()
        ),
        columns=[
            "Parameter",
            "Value"
        ]
    )
)

# ==============================================================================
# DATASET-SPECIFIC PRIVACY SUMMARY
# ==============================================================================

SPP_GAN_PRIVACY_DATASET_SUMMARY = []

for dataset in DATASETS:

    generator_privacy_valid = (
        SPP_GAN_GENERATOR_PRIVACY_CHECKS.get(
            dataset,
            False
        )
    )

    discriminator_privacy_valid = (
        SPP_GAN_DISCRIMINATOR_PRIVACY_CHECKS.get(
            dataset,
            False
        )
    )

    dataset_privacy_valid = (
        generator_privacy_valid
        and
        discriminator_privacy_valid
    )

    SPP_GAN_PRIVACY_DATASET_SUMMARY.append({

        "Dataset":
            dataset,

        "Privacy Mechanism":
            SPP_GAN_PRIVACY_MECHANISM_NAME,

        "Noise Distribution":
            SPP_GAN_PRIVACY_NOISE_DISTRIBUTION,

        "Clipping Norm":
            SPP_GAN_PRIVACY_CLIPPING_NORM,

        "Noise Multiplier":
            SPP_GAN_PRIVACY_NOISE_MULTIPLIER,

        "Discriminator Privacy":
            discriminator_privacy_valid,

        "Generator Post-Processing":
            generator_privacy_valid,

        "Overall Privacy Valid":
            dataset_privacy_valid
    })

SPP_GAN_PRIVACY_DATASET_SUMMARY_DF = (
    pd.DataFrame(
        SPP_GAN_PRIVACY_DATASET_SUMMARY
    )
)

# ==============================================================================
# DISPLAY GLOBAL SUMMARY
# ==============================================================================

print()

print(
    "Global Privacy Mechanism Summary:"
)

print()

display(
    SPP_GAN_PRIVACY_MECHANISM_SUMMARY_DF
)

# ==============================================================================
# DISPLAY DATASET SUMMARY
# ==============================================================================

print()

print(
    "Dataset-Specific Privacy Mechanism Summary:"
)

print()

display(
    SPP_GAN_PRIVACY_DATASET_SUMMARY_DF
)

# ==============================================================================
# FINAL PRIVACY MECHANISM STATUS
# ==============================================================================

SPP_GAN_PRIVACY_MECHANISM_SUMMARY_VALID = (
    SPP_GAN_PRIVACY_MECHANISM_VALIDATION_STATUS
    and
    all(
        row[
            "Overall Privacy Valid"
        ]
        for row
        in SPP_GAN_PRIVACY_DATASET_SUMMARY
    )
)

print()

print(
    f"Privacy Configuration Status       : "
    f"{'PASS' if SPP_GAN_PRIVACY_CONFIGURATION_VALID else 'FAIL'}"
)

print(
    f"Clipping Configuration Status      : "
    f"{'PASS' if SPP_GAN_PER_SAMPLE_CLIPPING_VALID else 'FAIL'}"
)

print(
    f"Gaussian Noise Status              : "
    f"{'PASS' if SPP_GAN_NOISE_MECHANISM_VALID else 'FAIL'}"
)

print(
    f"Private Gradient Processing Status : "
    f"{'PASS' if SPP_GAN_PRIVATE_GRADIENT_PROCESSING_VALID else 'FAIL'}"
)

print(
    f"Mechanism Validation Status        : "
    f"{'PASS' if SPP_GAN_PRIVACY_MECHANISM_VALIDATION_STATUS else 'FAIL'}"
)

print(
    f"Overall Privacy Mechanism Status   : "
    f"{'PASS' if SPP_GAN_PRIVACY_MECHANISM_SUMMARY_VALID else 'FAIL'}"
)

# ==============================================================================
# FAIL-FAST PIPELINE CHECK
# ==============================================================================

if not SPP_GAN_PRIVACY_MECHANISM_SUMMARY_VALID:

    failed_datasets = [
        dataset
        for dataset, checks
        in SPP_GAN_PRIVACY_DATASET_VALIDATION.items()
        if not checks[
            "Overall Privacy Valid"
        ]
    ]

    raise ValueError(
        "SPP-GAN privacy mechanism summary validation failed. "
        f"Failed datasets: {failed_datasets}"
    )

print()

print(
    "SPP-GAN privacy mechanism configuration, "
    "gradient clipping, Gaussian noise, "
    "private gradient processing, and "
    "privacy validation passed successfully."
)

print()

print(
    "Generator privacy is represented as "
    "post-processing of the discriminator's "
    "DP-protected training mechanism."
)

print()

print(
    "PART L8 — Privacy mechanism summary completed."
)

====================================================================================================
PART L8 — PRIVACY MECHANISM SUMMARY
====================================================================================================

Global Privacy Mechanism Summary:

                            Parameter                                 Value
0                   Privacy Mechanism                  Differential Privacy
1        Privacy Mechanism Normalized                  differential privacy
2                      Privacy Engine                         Manual DP-SGD
3                  Noise Distribution                              Gaussian
4                    Noise Multiplier                                   1.1
5               Manual Gaussian Noise                                  True
6                      Opacus Enabled                                 False
7              Gradient Clipping Norm                                   1.0
8                 Per-Sample Clipping                                  True
9   Discriminator Per-Sample Clipping                                  True
10      Generator Per-Sample Clipping                                 False
11   Discriminator Directly Protected                                  True
12       Generator Direct DP Disabled                                  True
13           Generator Privacy Status  Protected through DP post-processing
14       Discriminator Privacy Status       Direct manual DP-SGD protection
15       Privacy Accounting Component                         Discriminator
16         Post-Processing Components  Generator, Synthetic Data Generation
17                           Datasets                                     3
18         Generator Privacy Datasets                                     3
19     Discriminator Privacy Datasets                                     3
20                Configuration Valid                                  True
21       Clipping Configuration Valid                                  True
22              Noise Mechanism Valid                                  True
23  Private Gradient Processing Valid                                  True
24        Mechanism Validation Status                                  True
25                    Mechanism Valid                                  True

Dataset-Specific Privacy Mechanism Summary:

,Dataset,Privacy Mechanism,Noise Distribution,Clipping Norm,Noise Multiplier,Discriminator Privacy,Generator Post-Processing,Overall Privacy Valid
0,Adult Income,Differential Privacy,Gaussian,1.0,1.1,"{'Per-Sample Gradient Count Valid': True, 'Per...",True,"{'Per-Sample Gradient Count Valid': True, 'Per..."
1,Bank Marketing,Differential Privacy,Gaussian,1.0,1.1,"{'Per-Sample Gradient Count Valid': True, 'Per...",True,"{'Per-Sample Gradient Count Valid': True, 'Per..."
2,diabetes_130us,Differential Privacy,Gaussian,1.0,1.1,"{'Per-Sample Gradient Count Valid': True, 'Per...",True,"{'Per-Sample Gradient Count Valid': True, 'Per..."

Privacy Configuration Status       : PASS
Clipping Configuration Status      : PASS
Gaussian Noise Status              : PASS
Private Gradient Processing Status : PASS
Mechanism Validation Status        : PASS
Overall Privacy Mechanism Status   : PASS

SPP-GAN privacy mechanism configuration, gradient clipping, Gaussian noise, private gradient processing, and privacy validation passed successfully.

Generator privacy is represented as post-processing of the discriminator's DP-protected training mechanism.

PART L8 — Privacy mechanism summary completed.

In [184]:
# ==============================================================================
# PART M1 — TRAINING DATASET SELECTION
# ==============================================================================

print("=" * 100)
print("PART M1 — TRAINING DATASET SELECTION")
print("=" * 100)

SPP_GAN_TRAIN_DATASETS = {}
SPP_GAN_TRAIN_FEATURE_DATASETS = {}
SPP_GAN_TRAINING_DATASET_CHECKS = {}

for dataset in DATASETS:

    # --------------------------------------------------------------------------
    # TRAINING DATASET
    # --------------------------------------------------------------------------

    if dataset not in TRAIN_DATASETS:
        raise KeyError(
            f"Training dataset not found for {dataset}."
        )

    training_data = TRAIN_DATASETS[dataset]

    if not isinstance(
        training_data,
        pd.DataFrame
    ):
        raise TypeError(
            f"Training data for {dataset} "
            "must be a pandas DataFrame."
        )

    if training_data.empty:
        raise ValueError(
            f"Training dataset is empty for {dataset}."
        )

    # Preserve the complete training dataset, including target.
    SPP_GAN_TRAIN_DATASETS[dataset] = (
        training_data.copy()
    )

    # --------------------------------------------------------------------------
    # TARGET COLUMN
    # --------------------------------------------------------------------------

    if dataset not in TARGET_COLUMNS:
        raise KeyError(
            f"Target column definition not found for {dataset}."
        )

    target_column = TARGET_COLUMNS[dataset]

    if target_column not in training_data.columns:
        raise KeyError(
            f"Target column '{target_column}' not found in "
            f"training dataset for {dataset}."
        )

    # --------------------------------------------------------------------------
    # FEATURE-ONLY TRAINING DATA
    # --------------------------------------------------------------------------

    training_features = (
        training_data.drop(
            columns=[target_column]
        )
    )

    SPP_GAN_TRAIN_FEATURE_DATASETS[dataset] = (
        training_features.copy()
    )

    # --------------------------------------------------------------------------
    # DATASET DIMENSIONS
    # --------------------------------------------------------------------------

    training_rows = (
        training_data.shape[0]
    )

    training_columns = (
        training_data.shape[1]
    )

    training_feature_dimension = (
        training_features.shape[1]
    )

    expected_gan_feature_dimension = int(
        SPP_GAN_OUTPUT_DIMENSIONS[dataset]
    )

    expected_discriminator_dimension = int(
        SPP_GAN_DISCRIMINATOR_INPUT_DIMENSIONS[
            dataset
        ]
    )

    # --------------------------------------------------------------------------
    # DATA QUALITY CHECKS
    # --------------------------------------------------------------------------

    dataframe_valid = isinstance(
        training_data,
        pd.DataFrame
    )

    non_empty_valid = (
        not training_data.empty
    )

    gan_feature_dimension_valid = (
        training_feature_dimension
        ==
        expected_gan_feature_dimension
    )

    discriminator_dimension_valid = (
        training_feature_dimension
        ==
        expected_discriminator_dimension
    )

    gan_discriminator_consistency = (
        expected_gan_feature_dimension
        ==
        expected_discriminator_dimension
    )

    numeric_training_data_valid = (
        all(
            pd.api.types.is_numeric_dtype(
                training_features[column]
            )
            for column
            in training_features.columns
        )
    )

    missing_value_count = int(
        training_data.isna().sum().sum()
    )

    missing_value_valid = (
        missing_value_count == 0
    )

    overall_dataset_valid = (
        dataframe_valid
        and
        non_empty_valid
        and
        gan_feature_dimension_valid
        and
        discriminator_dimension_valid
        and
        gan_discriminator_consistency
        and
        numeric_training_data_valid
        and
        missing_value_valid
    )

    # --------------------------------------------------------------------------
    # STORE DATASET VALIDATION
    # --------------------------------------------------------------------------

    SPP_GAN_TRAINING_DATASET_CHECKS[dataset] = {

        "DataFrame Validation":
            dataframe_valid,

        "Non-Empty Dataset":
            non_empty_valid,

        "GAN Feature Dimension":
            gan_feature_dimension_valid,

        "Discriminator Dimension":
            discriminator_dimension_valid,

        "GAN/Discriminator Consistency":
            gan_discriminator_consistency,

        "Numeric Training Data":
            numeric_training_data_valid,

        "Missing Value Validation":
            missing_value_valid,

        "Overall Dataset Validation":
            overall_dataset_valid
    }

    # --------------------------------------------------------------------------
    # DATASET REPORT
    # --------------------------------------------------------------------------

    print()

    print(
        f"Dataset                         : "
        f"{dataset}"
    )

    print(
        f"Training Rows                   : "
        f"{training_rows:,}"
    )

    print(
        f"Training Columns                : "
        f"{training_columns}"
    )

    print(
        f"Target Column                   : "
        f"{target_column}"
    )

    print(
        f"Training Feature Columns       : "
        f"{training_feature_dimension}"
    )

    print(
        f"Expected SPP-GAN Features      : "
        f"{expected_gan_feature_dimension}"
    )

    print(
        f"Expected Discriminator Features: "
        f"{expected_discriminator_dimension}"
    )

    print(
        f"Numeric Features                : "
        f"{training_features.select_dtypes(include=np.number).shape[1]}"
    )

    print(
        f"Missing Values                  : "
        f"{missing_value_count}"
    )

    print()

    print(
        f"DataFrame Validation             : "
        f"{'PASS' if dataframe_valid else 'FAIL'}"
    )

    print(
        f"Non-Empty Dataset                : "
        f"{'PASS' if non_empty_valid else 'FAIL'}"
    )

    print(
        f"GAN Feature Dimension           : "
        f"{'PASS' if gan_feature_dimension_valid else 'FAIL'}"
    )

    print(
        f"Discriminator Dimension         : "
        f"{'PASS' if discriminator_dimension_valid else 'FAIL'}"
    )

    print(
        f"GAN/Discriminator Consistency   : "
        f"{'PASS' if gan_discriminator_consistency else 'FAIL'}"
    )

    print(
        f"Numeric Training Data           : "
        f"{'PASS' if numeric_training_data_valid else 'FAIL'}"
    )

    print(
        f"Missing Value Validation        : "
        f"{'PASS' if missing_value_valid else 'FAIL'}"
    )

    print(
        f"Overall Dataset Validation      : "
        f"{'PASS' if overall_dataset_valid else 'FAIL'}"
    )

# ==============================================================================
# GLOBAL TRAINING DATASET VALIDATION
# ==============================================================================

SPP_GAN_TRAINING_DATASET_COVERAGE_VALID = (
    len(
        SPP_GAN_TRAIN_DATASETS
    )
    ==
    len(DATASETS)
)

SPP_GAN_TRAINING_DATASET_KEYS_VALID = (
    set(
        SPP_GAN_TRAIN_DATASETS.keys()
    )
    ==
    set(DATASETS)
)

SPP_GAN_TRAINING_FEATURE_DATASET_COVERAGE_VALID = (
    len(
        SPP_GAN_TRAIN_FEATURE_DATASETS
    )
    ==
    len(DATASETS)
)

SPP_GAN_TRAINING_DATASET_VALIDATION_STATUS = (
    SPP_GAN_TRAINING_DATASET_COVERAGE_VALID
    and
    SPP_GAN_TRAINING_DATASET_KEYS_VALID
    and
    SPP_GAN_TRAINING_FEATURE_DATASET_COVERAGE_VALID
    and
    all(
        checks[
            "Overall Dataset Validation"
        ]
        for checks
        in SPP_GAN_TRAINING_DATASET_CHECKS.values()
    )
)

# ==============================================================================
# GLOBAL VALIDATION REPORT
# ==============================================================================

print()

print(
    f"Training Dataset Coverage        : "
    f"{'PASS' if SPP_GAN_TRAINING_DATASET_COVERAGE_VALID else 'FAIL'}"
)

print(
    f"Training Dataset Keys            : "
    f"{'PASS' if SPP_GAN_TRAINING_DATASET_KEYS_VALID else 'FAIL'}"
)

print(
    f"Training Feature Dataset Coverage: "
    f"{'PASS' if SPP_GAN_TRAINING_FEATURE_DATASET_COVERAGE_VALID else 'FAIL'}"
)

print(
    f"Overall Training Dataset Status   : "
    f"{'PASS' if SPP_GAN_TRAINING_DATASET_VALIDATION_STATUS else 'FAIL'}"
)

# ==============================================================================
# FAIL-FAST PIPELINE CHECK
# ==============================================================================

if not SPP_GAN_TRAINING_DATASET_VALIDATION_STATUS:

    failed_datasets = [
        dataset
        for dataset, checks
        in SPP_GAN_TRAINING_DATASET_CHECKS.items()
        if not checks[
            "Overall Dataset Validation"
        ]
    ]

    raise ValueError(
        "SPP-GAN training dataset validation failed "
        f"for datasets: {failed_datasets}"
    )

print()

print(
    "All verified training datasets passed "
    "SPP-GAN training dataset validation."
)

print(
    "Complete training datasets are preserved in "
    "SPP_GAN_TRAIN_DATASETS."
)

print(
    "Target columns are excluded only when constructing "
    "SPP-GAN feature inputs."
)

print(
    "Feature-only training datasets are stored in "
    "SPP_GAN_TRAIN_FEATURE_DATASETS."
)

print()

print(
    "PART M1 — Training dataset selection completed."
)

====================================================================================================
PART M1 — TRAINING DATASET SELECTION
====================================================================================================

Dataset                         : Adult Income
Training Rows                   : 22,760
Training Columns                : 15
Target Column                   : income
Training Feature Columns       : 14
Expected SPP-GAN Features      : 14
Expected Discriminator Features: 14
Numeric Features                : 14
Missing Values                  : 0

DataFrame Validation             : PASS
Non-Empty Dataset                : PASS
GAN Feature Dimension           : PASS
Discriminator Dimension         : PASS
GAN/Discriminator Consistency   : PASS
Numeric Training Data           : PASS
Missing Value Validation        : PASS
Overall Dataset Validation      : PASS

Dataset                         : Bank Marketing
Training Rows                   : 31,647
Training Columns                : 17
Target Column                   : y
Training Feature Columns       : 16
Expected SPP-GAN Features      : 16
Expected Discriminator Features: 16
Numeric Features                : 16
Missing Values                  : 0

DataFrame Validation             : PASS
Non-Empty Dataset                : PASS
GAN Feature Dimension           : PASS
Discriminator Dimension         : PASS
GAN/Discriminator Consistency   : PASS
Numeric Training Data           : PASS
Missing Value Validation        : PASS
Overall Dataset Validation      : PASS

Dataset                         : diabetes_130us
Training Rows                   : 71,236
Training Columns                : 48
Target Column                   : readmitted
Training Feature Columns       : 47
Expected SPP-GAN Features      : 47
Expected Discriminator Features: 47
Numeric Features                : 47
Missing Values                  : 0

DataFrame Validation             : PASS
Non-Empty Dataset                : PASS
GAN Feature Dimension           : PASS
Discriminator Dimension         : PASS
GAN/Discriminator Consistency   : PASS
Numeric Training Data           : PASS
Missing Value Validation        : PASS
Overall Dataset Validation      : PASS

Training Dataset Coverage        : PASS
Training Dataset Keys            : PASS
Training Feature Dataset Coverage: PASS
Overall Training Dataset Status   : PASS

All verified training datasets passed SPP-GAN training dataset validation.
Complete training datasets are preserved in SPP_GAN_TRAIN_DATASETS.
Target columns are excluded only when constructing SPP-GAN feature inputs.
Feature-only training datasets are stored in SPP_GAN_TRAIN_FEATURE_DATASETS.

PART M1 — Training dataset selection completed.

In [185]:
# ==============================================================================
# PART M2 — TRAINING FEATURE ALIGNMENT
# ==============================================================================

print("=" * 100)
print("PART M2 — TRAINING FEATURE ALIGNMENT")
print("=" * 100)

SPP_GAN_TRAIN_FEATURE_DATA = {}
SPP_GAN_TRAIN_FEATURE_ALIGNMENT_CHECKS = {}

for dataset in DATASETS:

    # --------------------------------------------------------------------------
    # RETRIEVE VERIFIED TRAINING DATA
    # --------------------------------------------------------------------------

    if dataset not in SPP_GAN_TRAIN_DATASETS:
        raise KeyError(
            f"Training dataset not available for {dataset}."
        )

    training_data = (
        SPP_GAN_TRAIN_DATASETS[dataset]
    )

    # --------------------------------------------------------------------------
    # FEATURE DEFINITION
    # --------------------------------------------------------------------------

    if dataset not in FEATURE_COLUMNS:
        raise KeyError(
            f"Feature column definition not found for {dataset}."
        )

    expected_features = list(
        FEATURE_COLUMNS[dataset]
    )

    if len(expected_features) == 0:
        raise ValueError(
            f"No feature columns defined for {dataset}."
        )

    # --------------------------------------------------------------------------
    # FEATURE EXISTENCE VALIDATION
    # --------------------------------------------------------------------------

    missing_features = [
        column
        for column in expected_features
        if column not in training_data.columns
    ]

    if missing_features:

        raise KeyError(
            f"Missing training features for "
            f"{dataset}: {missing_features}"
        )

    # --------------------------------------------------------------------------
    # TRAINING FEATURE EXTRACTION
    # --------------------------------------------------------------------------

    training_features = (
        training_data[
            expected_features
        ]
        .copy()
    )

    SPP_GAN_TRAIN_FEATURE_DATA[dataset] = (
        training_features
    )

    # --------------------------------------------------------------------------
    # DIMENSION VALIDATION
    # --------------------------------------------------------------------------

    expected_feature_count = len(
        expected_features
    )

    actual_feature_count = (
        training_features.shape[1]
    )

    expected_gan_dimension = int(
        SPP_GAN_OUTPUT_DIMENSIONS[dataset]
    )

    expected_discriminator_dimension = int(
        SPP_GAN_DISCRIMINATOR_INPUT_DIMENSIONS[
            dataset
        ]
    )

    feature_count_valid = (
        actual_feature_count
        ==
        expected_feature_count
    )

    gan_dimension_valid = (
        actual_feature_count
        ==
        expected_gan_dimension
    )

    discriminator_dimension_valid = (
        actual_feature_count
        ==
        expected_discriminator_dimension
    )

    # --------------------------------------------------------------------------
    # COLUMN ORDER VALIDATION
    # --------------------------------------------------------------------------

    feature_order_valid = (
        list(
            training_features.columns
        )
        ==
        expected_features
    )

    # --------------------------------------------------------------------------
    # DUPLICATE FEATURE VALIDATION
    # --------------------------------------------------------------------------

    duplicate_features = (
        training_features.columns[
            training_features.columns.duplicated()
        ]
        .tolist()
    )

    duplicate_features_valid = (
        len(duplicate_features) == 0
    )

    # --------------------------------------------------------------------------
    # NUMERIC FEATURE VALIDATION
    # --------------------------------------------------------------------------

    numeric_features_valid = all(
        pd.api.types.is_numeric_dtype(
            training_features[column]
        )
        for column
        in training_features.columns
    )

    # --------------------------------------------------------------------------
    # MISSING VALUE VALIDATION
    # --------------------------------------------------------------------------

    missing_value_count = int(
        training_features.isna().sum().sum()
    )

    missing_values_valid = (
        missing_value_count == 0
    )

    # --------------------------------------------------------------------------
    # GAN/DISCRIMINATOR DIMENSION CONSISTENCY
    # --------------------------------------------------------------------------

    gan_discriminator_consistency = (
        expected_gan_dimension
        ==
        expected_discriminator_dimension
    )

    # --------------------------------------------------------------------------
    # OVERALL FEATURE ALIGNMENT
    # --------------------------------------------------------------------------

    feature_alignment_valid = (
        feature_count_valid
        and
        gan_dimension_valid
        and
        discriminator_dimension_valid
        and
        feature_order_valid
        and
        duplicate_features_valid
        and
        numeric_features_valid
        and
        missing_values_valid
        and
        gan_discriminator_consistency
    )

    # --------------------------------------------------------------------------
    # STORE DATASET VALIDATION
    # --------------------------------------------------------------------------

    SPP_GAN_TRAIN_FEATURE_ALIGNMENT_CHECKS[
        dataset
    ] = {

        "Expected Feature Count":
            expected_feature_count,

        "Actual Feature Count":
            actual_feature_count,

        "Feature Count Valid":
            feature_count_valid,

        "GAN Dimension Valid":
            gan_dimension_valid,

        "Discriminator Dimension Valid":
            discriminator_dimension_valid,

        "Feature Order Valid":
            feature_order_valid,

        "Duplicate Features Valid":
            duplicate_features_valid,

        "Numeric Features Valid":
            numeric_features_valid,

        "Missing Values Valid":
            missing_values_valid,

        "GAN/Discriminator Consistency":
            gan_discriminator_consistency,

        "Feature Alignment Valid":
            feature_alignment_valid
    }

    # --------------------------------------------------------------------------
    # DATASET REPORT
    # --------------------------------------------------------------------------

    print()

    print(
        f"Dataset                         : "
        f"{dataset}"
    )

    print(
        f"Expected Features              : "
        f"{expected_feature_count}"
    )

    print(
        f"Training Features              : "
        f"{actual_feature_count}"
    )

    print(
        f"Expected GAN Dimension         : "
        f"{expected_gan_dimension}"
    )

    print(
        f"Expected Discriminator Dimension: "
        f"{expected_discriminator_dimension}"
    )

    print(
        f"Feature Count Validation       : "
        f"{'PASS' if feature_count_valid else 'FAIL'}"
    )

    print(
        f"GAN Dimension Validation       : "
        f"{'PASS' if gan_dimension_valid else 'FAIL'}"
    )

    print(
        f"Discriminator Dimension        : "
        f"{'PASS' if discriminator_dimension_valid else 'FAIL'}"
    )

    print(
        f"Feature Order Validation       : "
        f"{'PASS' if feature_order_valid else 'FAIL'}"
    )

    print(
        f"Duplicate Feature Validation  : "
        f"{'PASS' if duplicate_features_valid else 'FAIL'}"
    )

    print(
        f"Numeric Feature Validation    : "
        f"{'PASS' if numeric_features_valid else 'FAIL'}"
    )

    print(
        f"Missing Value Validation       : "
        f"{'PASS' if missing_values_valid else 'FAIL'}"
    )

    print(
        f"GAN/Discriminator Consistency  : "
        f"{'PASS' if gan_discriminator_consistency else 'FAIL'}"
    )

    print(
        f"Feature Alignment              : "
        f"{'PASS' if feature_alignment_valid else 'FAIL'}"
    )

# ==============================================================================
# GLOBAL FEATURE ALIGNMENT VALIDATION
# ==============================================================================

SPP_GAN_TRAIN_FEATURE_ALIGNMENT_COVERAGE_VALID = (
    len(
        SPP_GAN_TRAIN_FEATURE_DATA
    )
    ==
    len(DATASETS)
)

SPP_GAN_TRAIN_FEATURE_ALIGNMENT_KEYS_VALID = (
    set(
        SPP_GAN_TRAIN_FEATURE_DATA.keys()
    )
    ==
    set(DATASETS)
)

SPP_GAN_TRAIN_FEATURE_ALIGNMENT_STATUS = (
    SPP_GAN_TRAIN_FEATURE_ALIGNMENT_COVERAGE_VALID
    and
    SPP_GAN_TRAIN_FEATURE_ALIGNMENT_KEYS_VALID
    and
    all(
        checks[
            "Feature Alignment Valid"
        ]
        for checks
        in SPP_GAN_TRAIN_FEATURE_ALIGNMENT_CHECKS.values()
    )
)

# ==============================================================================
# GLOBAL VALIDATION REPORT
# ==============================================================================

print()

print(
    f"Feature Dataset Coverage        : "
    f"{'PASS' if SPP_GAN_TRAIN_FEATURE_ALIGNMENT_COVERAGE_VALID else 'FAIL'}"
)

print(
    f"Feature Dataset Keys             : "
    f"{'PASS' if SPP_GAN_TRAIN_FEATURE_ALIGNMENT_KEYS_VALID else 'FAIL'}"
)

print(
    f"Overall Feature Alignment       : "
    f"{'PASS' if SPP_GAN_TRAIN_FEATURE_ALIGNMENT_STATUS else 'FAIL'}"
)

# ==============================================================================
# FAIL-FAST PIPELINE CHECK
# ==============================================================================

if not SPP_GAN_TRAIN_FEATURE_ALIGNMENT_STATUS:

    failed_datasets = [
        dataset
        for dataset, checks
        in SPP_GAN_TRAIN_FEATURE_ALIGNMENT_CHECKS.items()
        if not checks[
            "Feature Alignment Valid"
        ]
    ]

    raise ValueError(
        "SPP-GAN training feature alignment failed "
        f"for datasets: {failed_datasets}"
    )

print()

print(
    "Training features are aligned with the verified "
    "SPP-GAN feature definitions."
)

print(
    "Feature order is preserved according to FEATURE_COLUMNS."
)

print(
    "Target variables are excluded from SPP-GAN feature inputs."
)

print(
    "Training feature dimensions are consistent with "
    "the generator and discriminator interfaces."
)

print()

print(
    "PART M2 — Training feature alignment completed."
)

====================================================================================================
PART M2 — TRAINING FEATURE ALIGNMENT
====================================================================================================

Dataset                         : Adult Income
Expected Features              : 14
Training Features              : 14
Expected GAN Dimension         : 14
Expected Discriminator Dimension: 14
Feature Count Validation       : PASS
GAN Dimension Validation       : PASS
Discriminator Dimension        : PASS
Feature Order Validation       : PASS
Duplicate Feature Validation  : PASS
Numeric Feature Validation    : PASS
Missing Value Validation       : PASS
GAN/Discriminator Consistency  : PASS
Feature Alignment              : PASS

Dataset                         : Bank Marketing
Expected Features              : 16
Training Features              : 16
Expected GAN Dimension         : 16
Expected Discriminator Dimension: 16
Feature Count Validation       : PASS
GAN Dimension Validation       : PASS
Discriminator Dimension        : PASS
Feature Order Validation       : PASS
Duplicate Feature Validation  : PASS
Numeric Feature Validation    : PASS
Missing Value Validation       : PASS
GAN/Discriminator Consistency  : PASS
Feature Alignment              : PASS

Dataset                         : diabetes_130us
Expected Features              : 47
Training Features              : 47
Expected GAN Dimension         : 47
Expected Discriminator Dimension: 47
Feature Count Validation       : PASS
GAN Dimension Validation       : PASS
Discriminator Dimension        : PASS
Feature Order Validation       : PASS
Duplicate Feature Validation  : PASS
Numeric Feature Validation    : PASS
Missing Value Validation       : PASS
GAN/Discriminator Consistency  : PASS
Feature Alignment              : PASS

Feature Dataset Coverage        : PASS
Feature Dataset Keys             : PASS
Overall Feature Alignment       : PASS

Training features are aligned with the verified SPP-GAN feature definitions.
Feature order is preserved according to FEATURE_COLUMNS.
Target variables are excluded from SPP-GAN feature inputs.
Training feature dimensions are consistent with the generator and discriminator interfaces.

PART M2 — Training feature alignment completed.

In [186]:
# ==============================================================================
# PART M3 — TRAINING NUMERIC MATRIX PREPARATION
# ==============================================================================

print("=" * 100)
print("PART M3 — TRAINING NUMERIC MATRIX PREPARATION")
print("=" * 100)

SPP_GAN_TRAIN_MATRICES = {}
SPP_GAN_TRAIN_MATRIX_CHECKS = {}

for dataset in DATASETS:

    # --------------------------------------------------------------------------
    # RETRIEVE ALIGNED TRAINING FEATURES
    # --------------------------------------------------------------------------

    if dataset not in SPP_GAN_TRAIN_FEATURE_DATA:
        raise KeyError(
            f"Aligned training features not found for {dataset}."
        )

    training_features = (
        SPP_GAN_TRAIN_FEATURE_DATA[dataset]
    )

    # --------------------------------------------------------------------------
    # EXPECTED DIMENSIONS
    # --------------------------------------------------------------------------

    expected_feature_dimension = int(
        SPP_GAN_OUTPUT_DIMENSIONS[dataset]
    )

    expected_discriminator_dimension = int(
        SPP_GAN_DISCRIMINATOR_INPUT_DIMENSIONS[
            dataset
        ]
    )

    expected_rows = int(
        SPP_GAN_TRAIN_DATASETS[dataset].shape[0]
    )

    # --------------------------------------------------------------------------
    # DATAFRAME VALIDATION
    # --------------------------------------------------------------------------

    dataframe_valid = isinstance(
        training_features,
        pd.DataFrame
    )

    non_empty_valid = (
        not training_features.empty
    )

    if not dataframe_valid:
        raise TypeError(
            f"Training features for {dataset} "
            "must be a pandas DataFrame."
        )

    if not non_empty_valid:
        raise ValueError(
            f"Training feature data is empty for {dataset}."
        )

    # --------------------------------------------------------------------------
    # FEATURE DIMENSION VALIDATION
    # --------------------------------------------------------------------------

    actual_feature_dimension = (
        training_features.shape[1]
    )

    feature_dimension_valid = (
        actual_feature_dimension
        ==
        expected_feature_dimension
    )

    discriminator_dimension_valid = (
        actual_feature_dimension
        ==
        expected_discriminator_dimension
    )

    gan_discriminator_consistency = (
        expected_feature_dimension
        ==
        expected_discriminator_dimension
    )

    if not feature_dimension_valid:

        raise ValueError(
            f"Training feature dimension mismatch for "
            f"{dataset}: expected "
            f"{expected_feature_dimension}, got "
            f"{actual_feature_dimension}."
        )

    # --------------------------------------------------------------------------
    # NUMERIC CONVERSION
    # --------------------------------------------------------------------------

    numeric_features = (
        training_features
        .apply(
            pd.to_numeric,
            errors="coerce"
        )
    )

    # --------------------------------------------------------------------------
    # INVALID / MISSING VALUE DETECTION
    # --------------------------------------------------------------------------

    invalid_numeric_values = (
        numeric_features.isnull().any().any()
    )

    invalid_columns = (
        numeric_features.columns[
            numeric_features.isnull().any()
        ].tolist()
    )

    numeric_conversion_valid = (
        not invalid_numeric_values
    )

    if invalid_numeric_values:

        raise ValueError(
            f"Non-numeric, invalid, or missing values detected "
            f"in training features for {dataset}: "
            f"{invalid_columns}"
        )

    # --------------------------------------------------------------------------
    # NUMERIC MATRIX CREATION
    # --------------------------------------------------------------------------

    train_matrix = (
        numeric_features
        .to_numpy(
            dtype=np.float32
        )
    )

    SPP_GAN_TRAIN_MATRICES[dataset] = (
        train_matrix
    )

    # --------------------------------------------------------------------------
    # MATRIX SHAPE VALIDATION
    # --------------------------------------------------------------------------

    matrix_shape_valid = (
        train_matrix.ndim == 2
        and
        train_matrix.shape[0]
        ==
        expected_rows
        and
        train_matrix.shape[1]
        ==
        expected_feature_dimension
    )

    # --------------------------------------------------------------------------
    # FINITE VALUE VALIDATION
    # --------------------------------------------------------------------------

    finite_values_valid = (
        np.isfinite(
            train_matrix
        ).all()
    )

    if not finite_values_valid:

        raise ValueError(
            f"Non-finite values detected in "
            f"training matrix for {dataset}."
        )

    # --------------------------------------------------------------------------
    # DATA TYPE VALIDATION
    # --------------------------------------------------------------------------

    dtype_valid = (
        train_matrix.dtype
        ==
        np.float32
    )

    # --------------------------------------------------------------------------
    # ROW COUNT VALIDATION
    # --------------------------------------------------------------------------

    row_count_valid = (
        train_matrix.shape[0]
        ==
        expected_rows
    )

    # --------------------------------------------------------------------------
    # OVERALL MATRIX VALIDATION
    # --------------------------------------------------------------------------

    matrix_valid = (
        dataframe_valid
        and
        non_empty_valid
        and
        feature_dimension_valid
        and
        discriminator_dimension_valid
        and
        gan_discriminator_consistency
        and
        numeric_conversion_valid
        and
        matrix_shape_valid
        and
        finite_values_valid
        and
        dtype_valid
        and
        row_count_valid
    )

    # --------------------------------------------------------------------------
    # STORE VALIDATION RESULTS
    # --------------------------------------------------------------------------

    SPP_GAN_TRAIN_MATRIX_CHECKS[dataset] = {

        "DataFrame Valid":
            dataframe_valid,

        "Non-Empty":
            non_empty_valid,

        "Row Count Valid":
            row_count_valid,

        "Feature Dimension Valid":
            feature_dimension_valid,

        "Discriminator Dimension Valid":
            discriminator_dimension_valid,

        "GAN/Discriminator Consistency":
            gan_discriminator_consistency,

        "Numeric Conversion Valid":
            numeric_conversion_valid,

        "Matrix Shape Valid":
            matrix_shape_valid,

        "Finite Values Valid":
            finite_values_valid,

        "Float32 Data Type Valid":
            dtype_valid,

        "Matrix Valid":
            matrix_valid
    }

    # --------------------------------------------------------------------------
    # DATASET REPORT
    # --------------------------------------------------------------------------

    print()

    print(
        f"Dataset                         : "
        f"{dataset}"
    )

    print(
        f"Training Matrix Shape           : "
        f"{train_matrix.shape}"
    )

    print(
        f"Expected Training Rows          : "
        f"{expected_rows:,}"
    )

    print(
        f"Expected GAN Features          : "
        f"{expected_feature_dimension}"
    )

    print(
        f"Expected Discriminator Features: "
        f"{expected_discriminator_dimension}"
    )

    print(
        f"Data Type                       : "
        f"{train_matrix.dtype}"
    )

    print()

    print(
        f"DataFrame Validation            : "
        f"{'PASS' if dataframe_valid else 'FAIL'}"
    )

    print(
        f"Non-Empty Dataset               : "
        f"{'PASS' if non_empty_valid else 'FAIL'}"
    )

    print(
        f"Row Count Validation            : "
        f"{'PASS' if row_count_valid else 'FAIL'}"
    )

    print(
        f"Feature Dimension Validation    : "
        f"{'PASS' if feature_dimension_valid else 'FAIL'}"
    )

    print(
        f"Discriminator Dimension         : "
        f"{'PASS' if discriminator_dimension_valid else 'FAIL'}"
    )

    print(
        f"GAN/Discriminator Consistency   : "
        f"{'PASS' if gan_discriminator_consistency else 'FAIL'}"
    )

    print(
        f"Numeric Conversion              : "
        f"{'PASS' if numeric_conversion_valid else 'FAIL'}"
    )

    print(
        f"Matrix Shape Validation         : "
        f"{'PASS' if matrix_shape_valid else 'FAIL'}"
    )

    print(
        f"Finite Values                   : "
        f"{'PASS' if finite_values_valid else 'FAIL'}"
    )

    print(
        f"Float32 Data Type               : "
        f"{'PASS' if dtype_valid else 'FAIL'}"
    )

    print(
        f"Overall Matrix Validation       : "
        f"{'PASS' if matrix_valid else 'FAIL'}"
    )

# ==============================================================================
# GLOBAL TRAINING MATRIX VALIDATION
# ==============================================================================

SPP_GAN_TRAIN_MATRIX_COVERAGE_VALID = (
    len(
        SPP_GAN_TRAIN_MATRICES
    )
    ==
    len(DATASETS)
)

SPP_GAN_TRAIN_MATRIX_KEYS_VALID = (
    set(
        SPP_GAN_TRAIN_MATRICES.keys()
    )
    ==
    set(DATASETS)
)

SPP_GAN_TRAIN_MATRIX_VALIDATION_STATUS = (
    SPP_GAN_TRAIN_MATRIX_COVERAGE_VALID
    and
    SPP_GAN_TRAIN_MATRIX_KEYS_VALID
    and
    all(
        checks[
            "Matrix Valid"
        ]
        for checks
        in SPP_GAN_TRAIN_MATRIX_CHECKS.values()
    )
)

# ==============================================================================
# GLOBAL VALIDATION REPORT
# ==============================================================================

print()

print(
    f"Training Matrix Coverage        : "
    f"{'PASS' if SPP_GAN_TRAIN_MATRIX_COVERAGE_VALID else 'FAIL'}"
)

print(
    f"Training Matrix Keys             : "
    f"{'PASS' if SPP_GAN_TRAIN_MATRIX_KEYS_VALID else 'FAIL'}"
)

print(
    f"Overall Training Matrix Status   : "
    f"{'PASS' if SPP_GAN_TRAIN_MATRIX_VALIDATION_STATUS else 'FAIL'}"
)

# ==============================================================================
# FAIL-FAST PIPELINE CHECK
# ==============================================================================

if not SPP_GAN_TRAIN_MATRIX_VALIDATION_STATUS:

    failed_datasets = [
        dataset
        for dataset, checks
        in SPP_GAN_TRAIN_MATRIX_CHECKS.items()
        if not checks[
            "Matrix Valid"
        ]
    ]

    raise ValueError(
        "SPP-GAN training numeric matrix validation failed "
        f"for datasets: {failed_datasets}"
    )

print()

print(
    "All aligned training feature datasets were converted "
    "to validated float32 numeric matrices."
)

print(
    "Training matrices contain feature columns only; "
    "target variables are excluded."
)

print(
    "Matrix dimensions are consistent with the "
    "SPP-GAN generator and discriminator interfaces."
)

print()

print(
    "PART M3 — Training numeric matrix preparation completed."
)

====================================================================================================
PART M3 — TRAINING NUMERIC MATRIX PREPARATION
====================================================================================================

Dataset                         : Adult Income
Training Matrix Shape           : (22760, 14)
Expected Training Rows          : 22,760
Expected GAN Features          : 14
Expected Discriminator Features: 14
Data Type                       : float32

DataFrame Validation            : PASS
Non-Empty Dataset               : PASS
Row Count Validation            : PASS
Feature Dimension Validation    : PASS
Discriminator Dimension         : PASS
GAN/Discriminator Consistency   : PASS
Numeric Conversion              : PASS
Matrix Shape Validation         : PASS
Finite Values                   : PASS
Float32 Data Type               : PASS
Overall Matrix Validation       : PASS

Dataset                         : Bank Marketing
Training Matrix Shape           : (31647, 16)
Expected Training Rows          : 31,647
Expected GAN Features          : 16
Expected Discriminator Features: 16
Data Type                       : float32

DataFrame Validation            : PASS
Non-Empty Dataset               : PASS
Row Count Validation            : PASS
Feature Dimension Validation    : PASS
Discriminator Dimension         : PASS
GAN/Discriminator Consistency   : PASS
Numeric Conversion              : PASS
Matrix Shape Validation         : PASS
Finite Values                   : PASS
Float32 Data Type               : PASS
Overall Matrix Validation       : PASS

Dataset                         : diabetes_130us
Training Matrix Shape           : (71236, 47)
Expected Training Rows          : 71,236
Expected GAN Features          : 47
Expected Discriminator Features: 47
Data Type                       : float32

DataFrame Validation            : PASS
Non-Empty Dataset               : PASS
Row Count Validation            : PASS
Feature Dimension Validation    : PASS
Discriminator Dimension         : PASS
GAN/Discriminator Consistency   : PASS
Numeric Conversion              : PASS
Matrix Shape Validation         : PASS
Finite Values                   : PASS
Float32 Data Type               : PASS
Overall Matrix Validation       : PASS

Training Matrix Coverage        : PASS
Training Matrix Keys             : PASS
Overall Training Matrix Status   : PASS

All aligned training feature datasets were converted to validated float32 numeric matrices.
Training matrices contain feature columns only; target variables are excluded.
Matrix dimensions are consistent with the SPP-GAN generator and discriminator interfaces.

PART M3 — Training numeric matrix preparation completed.

In [187]:
# ==============================================================================
# PART M4 — TRAINING TENSOR PREPARATION
# ==============================================================================

print("=" * 100)
print("PART M4 — TRAINING TENSOR PREPARATION")
print("=" * 100)

SPP_GAN_TRAIN_TENSORS = {}
SPP_GAN_TRAIN_TENSOR_CHECKS = {}

for dataset in DATASETS:

    train_matrix = (
        SPP_GAN_TRAIN_MATRICES[dataset]
    )

    expected_dimension = int(
        SPP_GAN_INPUT_DIMENSIONS[dataset]
    )

    # --------------------------------------------------------------------------
    # Tensor Conversion
    # --------------------------------------------------------------------------

    train_tensor = torch.as_tensor(
        train_matrix,
        dtype=torch.float32,
        device=SPP_GAN_DEVICE
    )

    # --------------------------------------------------------------------------
    # Tensor Validation
    # --------------------------------------------------------------------------

    tensor_shape_valid = (
        train_tensor.ndim == 2
        and
        train_tensor.shape[1]
        ==
        expected_dimension
    )

    tensor_non_empty_valid = (
        train_tensor.shape[0] > 0
        and
        train_tensor.shape[1] > 0
    )

    tensor_dtype_valid = (
        train_tensor.dtype
        ==
        torch.float32
    )

    tensor_finite_valid = bool(
        torch.isfinite(
            train_tensor
        ).all().item()
    )

    tensor_device_valid = (
        train_tensor.device
        ==
        torch.device(
            SPP_GAN_DEVICE
        )
    )

    overall_tensor_valid = (
        tensor_shape_valid
        and
        tensor_non_empty_valid
        and
        tensor_dtype_valid
        and
        tensor_finite_valid
        and
        tensor_device_valid
    )

    SPP_GAN_TRAIN_TENSORS[dataset] = (
        train_tensor
    )

    SPP_GAN_TRAIN_TENSOR_CHECKS[dataset] = {
        "Tensor Shape Valid":
            tensor_shape_valid,

        "Tensor Non-Empty":
            tensor_non_empty_valid,

        "Tensor Data Type Valid":
            tensor_dtype_valid,

        "Tensor Finite":
            tensor_finite_valid,

        "Tensor Device Valid":
            tensor_device_valid,

        "Overall Tensor Valid":
            overall_tensor_valid
    }

    # --------------------------------------------------------------------------
    # Report
    # --------------------------------------------------------------------------

    print()

    print(
        f"Dataset               : "
        f"{dataset}"
    )

    print(
        f"Tensor Shape          : "
        f"{tuple(train_tensor.shape)}"
    )

    print(
        f"Expected Feature Dim  : "
        f"{expected_dimension}"
    )

    print(
        f"Tensor Device         : "
        f"{train_tensor.device}"
    )

    print(
        f"Tensor Data Type      : "
        f"{train_tensor.dtype}"
    )

    print(
        f"Tensor Shape          : "
        f"{'PASS' if tensor_shape_valid else 'FAIL'}"
    )

    print(
        f"Tensor Non-Empty      : "
        f"{'PASS' if tensor_non_empty_valid else 'FAIL'}"
    )

    print(
        f"Tensor Data Type      : "
        f"{'PASS' if tensor_dtype_valid else 'FAIL'}"
    )

    print(
        f"Finite Values         : "
        f"{'PASS' if tensor_finite_valid else 'FAIL'}"
    )

    print(
        f"Tensor Device         : "
        f"{'PASS' if tensor_device_valid else 'FAIL'}"
    )

    print(
        f"Overall Tensor        : "
        f"{'PASS' if overall_tensor_valid else 'FAIL'}"
    )

# ==============================================================================
# FAIL-FAST VALIDATION
# ==============================================================================

SPP_GAN_TRAIN_TENSOR_VALIDATION_STATUS = all(
    checks["Overall Tensor Valid"]
    for checks
    in SPP_GAN_TRAIN_TENSOR_CHECKS.values()
)

print()

print(
    f"Overall Training Tensor Validation : "
    f"{'PASS' if SPP_GAN_TRAIN_TENSOR_VALIDATION_STATUS else 'FAIL'}"
)

if not SPP_GAN_TRAIN_TENSOR_VALIDATION_STATUS:

    failed_datasets = [
        dataset
        for dataset, checks
        in SPP_GAN_TRAIN_TENSOR_CHECKS.items()
        if not checks["Overall Tensor Valid"]
    ]

    raise ValueError(
        "SPP-GAN training tensor validation failed "
        f"for datasets: {failed_datasets}"
    )

print()

print(
    "Training tensors are ready for SPP-GAN discriminator "
    "training and privacy-preserving gradient processing."
)

print()

print(
    "PART M4 — Training tensor preparation completed."
)

====================================================================================================
PART M4 — TRAINING TENSOR PREPARATION
====================================================================================================

Dataset               : Adult Income
Tensor Shape          : (22760, 14)
Expected Feature Dim  : 14
Tensor Device         : cpu
Tensor Data Type      : torch.float32
Tensor Shape          : PASS
Tensor Non-Empty      : PASS
Tensor Data Type      : PASS
Finite Values         : PASS
Tensor Device         : PASS
Overall Tensor        : PASS

Dataset               : Bank Marketing
Tensor Shape          : (31647, 16)
Expected Feature Dim  : 16
Tensor Device         : cpu
Tensor Data Type      : torch.float32
Tensor Shape          : PASS
Tensor Non-Empty      : PASS
Tensor Data Type      : PASS
Finite Values         : PASS
Tensor Device         : PASS
Overall Tensor        : PASS

Dataset               : diabetes_130us
Tensor Shape          : (71236, 47)
Expected Feature Dim  : 47
Tensor Device         : cpu
Tensor Data Type      : torch.float32
Tensor Shape          : PASS
Tensor Non-Empty      : PASS
Tensor Data Type      : PASS
Finite Values         : PASS
Tensor Device         : PASS
Overall Tensor        : PASS

Overall Training Tensor Validation : PASS

Training tensors are ready for SPP-GAN discriminator training and privacy-preserving gradient processing.

PART M4 — Training tensor preparation completed.

In [188]:
# ==============================================================================
# PART M5 — TRAINING DATALOADER PREPARATION
# ==============================================================================

print("=" * 100)
print("PART M5 — TRAINING DATALOADER PREPARATION")
print("=" * 100)

SPP_GAN_TRAIN_DATALOADERS = {}
SPP_GAN_TRAIN_DATALOADER_CHECKS = {}

# ==============================================================================
# BATCH SIZE VALIDATION
# ==============================================================================

SPP_GAN_TRAIN_BATCH_SIZE_VALID = (
    int(SPP_GAN_BATCH_SIZE) > 0
)

if not SPP_GAN_TRAIN_BATCH_SIZE_VALID:
    raise ValueError(
        "SPP-GAN batch size must be greater than zero."
    )

# ==============================================================================
# DATASET-SPECIFIC DATALOADERS
# ==============================================================================

for dataset in DATASETS:

    train_tensor = (
        SPP_GAN_TRAIN_TENSORS[dataset]
    )

    expected_dimension = int(
        SPP_GAN_INPUT_DIMENSIONS[dataset]
    )

    # --------------------------------------------------------------------------
    # Tensor Validation
    # --------------------------------------------------------------------------

    tensor_valid = (
        isinstance(
            train_tensor,
            torch.Tensor
        )
        and
        train_tensor.ndim == 2
        and
        train_tensor.shape[1]
        ==
        expected_dimension
        and
        train_tensor.shape[0] > 0
    )

    if not tensor_valid:
        raise ValueError(
            f"Invalid training tensor for {dataset}: "
            f"shape={tuple(train_tensor.shape)}, "
            f"expected feature dimension={expected_dimension}."
        )

    # --------------------------------------------------------------------------
    # Tensor Dataset
    # --------------------------------------------------------------------------

    train_dataset = TensorDataset(
        train_tensor
    )

    # --------------------------------------------------------------------------
    # DataLoader
    # --------------------------------------------------------------------------

    train_dataloader = DataLoader(
        train_dataset,
        batch_size=int(SPP_GAN_BATCH_SIZE),
        shuffle=True,
        drop_last=False
    )

    SPP_GAN_TRAIN_DATALOADERS[dataset] = (
        train_dataloader
    )

    # --------------------------------------------------------------------------
    # DataLoader Statistics
    # --------------------------------------------------------------------------

    training_samples = len(
        train_dataset
    )

    batch_size = int(
        SPP_GAN_BATCH_SIZE
    )

    number_of_batches = len(
        train_dataloader
    )

    expected_number_of_batches = int(
        np.ceil(
            training_samples
            /
            batch_size
        )
    )

    batch_count_valid = (
        number_of_batches
        ==
        expected_number_of_batches
    )

    dataloader_batch_size_valid = (
        train_dataloader.batch_size
        ==
        batch_size
    )

    dataloader_non_empty_valid = (
        number_of_batches > 0
    )

    # --------------------------------------------------------------------------
    # Verify First Batch
    # --------------------------------------------------------------------------

    first_batch = next(
        iter(train_dataloader)
    )

    first_batch_tensor = first_batch[0]

    first_batch_dimension_valid = (
        first_batch_tensor.ndim == 2
        and
        first_batch_tensor.shape[1]
        ==
        expected_dimension
    )

    first_batch_size_valid = (
        first_batch_tensor.shape[0]
        <=
        batch_size
    )

    first_batch_finite_valid = bool(
        torch.isfinite(
            first_batch_tensor
        ).all().item()
    )

    # --------------------------------------------------------------------------
    # Overall Dataset Validation
    # --------------------------------------------------------------------------

    overall_dataloader_valid = (
        SPP_GAN_TRAIN_BATCH_SIZE_VALID
        and
        tensor_valid
        and
        dataloader_batch_size_valid
        and
        dataloader_non_empty_valid
        and
        batch_count_valid
        and
        first_batch_dimension_valid
        and
        first_batch_size_valid
        and
        first_batch_finite_valid
    )

    SPP_GAN_TRAIN_DATALOADER_CHECKS[dataset] = {

        "Tensor Valid":
            tensor_valid,

        "Batch Size Valid":
            dataloader_batch_size_valid,

        "DataLoader Non-Empty":
            dataloader_non_empty_valid,

        "Batch Count Valid":
            batch_count_valid,

        "First Batch Dimension Valid":
            first_batch_dimension_valid,

        "First Batch Size Valid":
            first_batch_size_valid,

        "First Batch Finite":
            first_batch_finite_valid,

        "Overall DataLoader Valid":
            overall_dataloader_valid
    }

    # --------------------------------------------------------------------------
    # Report
    # --------------------------------------------------------------------------

    print()

    print(
        f"Dataset                    : "
        f"{dataset}"
    )

    print(
        f"Training Samples           : "
        f"{training_samples:,}"
    )

    print(
        f"Feature Dimension          : "
        f"{expected_dimension}"
    )

    print(
        f"Batch Size                 : "
        f"{batch_size}"
    )

    print(
        f"Number of Batches          : "
        f"{number_of_batches}"
    )

    print(
        f"Expected Number of Batches : "
        f"{expected_number_of_batches}"
    )

    print()

    print(
        f"Tensor Validation          : "
        f"{'PASS' if tensor_valid else 'FAIL'}"
    )

    print(
        f"Batch Size Validation      : "
        f"{'PASS' if dataloader_batch_size_valid else 'FAIL'}"
    )

    print(
        f"DataLoader Non-Empty       : "
        f"{'PASS' if dataloader_non_empty_valid else 'FAIL'}"
    )

    print(
        f"Batch Count Validation     : "
        f"{'PASS' if batch_count_valid else 'FAIL'}"
    )

    print(
        f"First Batch Dimension      : "
        f"{'PASS' if first_batch_dimension_valid else 'FAIL'}"
    )

    print(
        f"First Batch Size           : "
        f"{'PASS' if first_batch_size_valid else 'FAIL'}"
    )

    print(
        f"First Batch Finite         : "
        f"{'PASS' if first_batch_finite_valid else 'FAIL'}"
    )

    print(
        f"Overall DataLoader         : "
        f"{'PASS' if overall_dataloader_valid else 'FAIL'}"
    )

# ==============================================================================
# GLOBAL DATALOADER VALIDATION
# ==============================================================================

SPP_GAN_TRAIN_DATALOADER_COVERAGE_VALID = (
    len(SPP_GAN_TRAIN_DATALOADERS)
    ==
    len(DATASETS)
)

SPP_GAN_TRAIN_DATALOADER_VALIDATION_STATUS = (
    SPP_GAN_TRAIN_BATCH_SIZE_VALID
    and
    SPP_GAN_TRAIN_DATALOADER_COVERAGE_VALID
    and
    all(
        checks["Overall DataLoader Valid"]
        for checks
        in SPP_GAN_TRAIN_DATALOADER_CHECKS.values()
    )
)

print()

print(
    f"Training DataLoader Coverage : "
    f"{'PASS' if SPP_GAN_TRAIN_DATALOADER_COVERAGE_VALID else 'FAIL'}"
)

print(
    f"Batch Size Configuration      : "
    f"{'PASS' if SPP_GAN_TRAIN_BATCH_SIZE_VALID else 'FAIL'}"
)

print(
    f"Overall DataLoader Status     : "
    f"{'PASS' if SPP_GAN_TRAIN_DATALOADER_VALIDATION_STATUS else 'FAIL'}"
)

# ==============================================================================
# FAIL-FAST PIPELINE CHECK
# ==============================================================================

if not SPP_GAN_TRAIN_DATALOADER_VALIDATION_STATUS:

    failed_datasets = [
        dataset
        for dataset, checks
        in SPP_GAN_TRAIN_DATALOADER_CHECKS.items()
        if not checks["Overall DataLoader Valid"]
    ]

    raise ValueError(
        "SPP-GAN training DataLoader validation failed "
        f"for datasets: {failed_datasets}"
    )

print()

print(
    "All SPP-GAN training DataLoaders are validated "
    "and ready for discriminator training."
)

print(
    "The final batch is retained because drop_last=False."
)

print()

print(
    "PART M5 — Training DataLoader preparation completed."
)

====================================================================================================
PART M5 — TRAINING DATALOADER PREPARATION
====================================================================================================

Dataset                    : Adult Income
Training Samples           : 22,760
Feature Dimension          : 14
Batch Size                 : 256
Number of Batches          : 89
Expected Number of Batches : 89

Tensor Validation          : PASS
Batch Size Validation      : PASS
DataLoader Non-Empty       : PASS
Batch Count Validation     : PASS
First Batch Dimension      : PASS
First Batch Size           : PASS
First Batch Finite         : PASS
Overall DataLoader         : PASS

Dataset                    : Bank Marketing
Training Samples           : 31,647
Feature Dimension          : 16
Batch Size                 : 256
Number of Batches          : 124
Expected Number of Batches : 124

Tensor Validation          : PASS
Batch Size Validation      : PASS
DataLoader Non-Empty       : PASS
Batch Count Validation     : PASS
First Batch Dimension      : PASS
First Batch Size           : PASS
First Batch Finite         : PASS
Overall DataLoader         : PASS

Dataset                    : diabetes_130us
Training Samples           : 71,236
Feature Dimension          : 47
Batch Size                 : 256
Number of Batches          : 279
Expected Number of Batches : 279

Tensor Validation          : PASS
Batch Size Validation      : PASS
DataLoader Non-Empty       : PASS
Batch Count Validation     : PASS
First Batch Dimension      : PASS
First Batch Size           : PASS
First Batch Finite         : PASS
Overall DataLoader         : PASS

Training DataLoader Coverage : PASS
Batch Size Configuration      : PASS
Overall DataLoader Status     : PASS

All SPP-GAN training DataLoaders are validated and ready for discriminator training.
The final batch is retained because drop_last=False.

PART M5 — Training DataLoader preparation completed.

In [189]:
# ==============================================================================
# PART M6 — TRAINING BATCH VALIDATION
# ==============================================================================

print("=" * 100)
print("PART M6 — TRAINING BATCH VALIDATION")
print("=" * 100)

SPP_GAN_TRAIN_BATCH_CHECKS = {}

for dataset in DATASETS:

    dataloader = (
        SPP_GAN_TRAIN_DATALOADERS[dataset]
    )

    training_features = (
        SPP_GAN_TRAIN_FEATURE_DATA[dataset]
    )

    expected_features = (
        FEATURE_COLUMNS[dataset]
    )

    expected_dimension = int(
        SPP_GAN_INPUT_DIMENSIONS[dataset]
    )

    # --------------------------------------------------------------------------
    # GET TEST BATCH
    # --------------------------------------------------------------------------

    try:

        batch = next(
            iter(dataloader)
        )

    except StopIteration:

        raise ValueError(
            f"Training DataLoader is empty for dataset: {dataset}"
        )

    if isinstance(
        batch,
        (list, tuple)
    ):

        if len(batch) != 1:

            raise ValueError(
                f"Unexpected DataLoader batch structure for "
                f"{dataset}. Expected one feature tensor."
            )

        batch_tensor = batch[0]

    else:

        batch_tensor = batch

    # --------------------------------------------------------------------------
    # FEATURE COLUMN VALIDATION
    # --------------------------------------------------------------------------

    feature_columns_valid = (
        list(training_features.columns)
        ==
        list(expected_features)
    )

    # --------------------------------------------------------------------------
    # EXPECTED FEATURE DIMENSION
    # --------------------------------------------------------------------------

    feature_dimension_valid = (
        len(expected_features)
        ==
        expected_dimension
    )

    # --------------------------------------------------------------------------
    # BATCH SHAPE VALIDATION
    # --------------------------------------------------------------------------

    batch_shape_valid = (
        batch_tensor.ndim == 2
        and
        batch_tensor.shape[1]
        ==
        expected_dimension
    )

    # --------------------------------------------------------------------------
    # BATCH SIZE VALIDATION
    # --------------------------------------------------------------------------

    batch_size_valid = (
        0 < batch_tensor.shape[0]
        <=
        SPP_GAN_BATCH_SIZE
    )

    # --------------------------------------------------------------------------
    # DATA TYPE VALIDATION
    # --------------------------------------------------------------------------

    dtype_valid = (
        batch_tensor.dtype
        ==
        torch.float32
    )

    # --------------------------------------------------------------------------
    # DEVICE VALIDATION
    # --------------------------------------------------------------------------

    device_valid = (
        batch_tensor.device.type
        ==
        torch.device(
            SPP_GAN_DEVICE
        ).type
    )

    # --------------------------------------------------------------------------
    # FINITE VALUE VALIDATION
    # --------------------------------------------------------------------------

    finite_valid = (
        torch.isfinite(
            batch_tensor
        ).all().item()
    )

    # --------------------------------------------------------------------------
    # TRAINING MATRIX CONSISTENCY
    # --------------------------------------------------------------------------

    matrix = (
        SPP_GAN_TRAIN_MATRICES[dataset]
    )

    matrix_dimension_valid = (
        matrix.ndim == 2
        and
        matrix.shape[1]
        ==
        expected_dimension
    )

    matrix_row_count_valid = (
        matrix.shape[0]
        ==
        len(training_features)
    )

    # --------------------------------------------------------------------------
    # TENSOR CONSISTENCY
    # --------------------------------------------------------------------------

    training_tensor = (
        SPP_GAN_TRAIN_TENSORS[dataset]
    )

    tensor_dimension_valid = (
        training_tensor.ndim == 2
        and
        training_tensor.shape[1]
        ==
        expected_dimension
    )

    tensor_row_count_valid = (
        training_tensor.shape[0]
        ==
        matrix.shape[0]
    )

    # --------------------------------------------------------------------------
    # DATALOADER CONSISTENCY
    # --------------------------------------------------------------------------

    dataloader_dataset_size_valid = (
        len(dataloader.dataset)
        ==
        training_tensor.shape[0]
    )

    dataloader_batch_count_valid = (
        len(dataloader)
        ==
        int(
            np.ceil(
                training_tensor.shape[0]
                /
                SPP_GAN_BATCH_SIZE
            )
        )
    )

    # --------------------------------------------------------------------------
    # OVERALL BATCH VALIDATION
    # --------------------------------------------------------------------------

    batch_valid = all([
        feature_columns_valid,
        feature_dimension_valid,
        batch_shape_valid,
        batch_size_valid,
        dtype_valid,
        device_valid,
        finite_valid,
        matrix_dimension_valid,
        matrix_row_count_valid,
        tensor_dimension_valid,
        tensor_row_count_valid,
        dataloader_dataset_size_valid,
        dataloader_batch_count_valid
    ])

    SPP_GAN_TRAIN_BATCH_CHECKS[dataset] = (
        batch_valid
    )

    # --------------------------------------------------------------------------
    # REPORT
    # --------------------------------------------------------------------------

    print()

    print(
        f"Dataset                         : "
        f"{dataset}"
    )

    print(
        f"Expected SPP-GAN Features      : "
        f"{expected_dimension}"
    )

    print(
        f"Training Feature Columns       : "
        f"{training_features.shape[1]}"
    )

    print(
        f"Test Batch Shape               : "
        f"{tuple(batch_tensor.shape)}"
    )

    print(
        f"Feature Column Alignment       : "
        f"{'PASS' if feature_columns_valid else 'FAIL'}"
    )

    print(
        f"Feature Dimension              : "
        f"{'PASS' if feature_dimension_valid else 'FAIL'}"
    )

    print(
        f"Batch Shape                    : "
        f"{'PASS' if batch_shape_valid else 'FAIL'}"
    )

    print(
        f"Batch Size                     : "
        f"{'PASS' if batch_size_valid else 'FAIL'}"
    )

    print(
        f"Data Type                      : "
        f"{'PASS' if dtype_valid else 'FAIL'}"
    )

    print(
        f"Device                         : "
        f"{'PASS' if device_valid else 'FAIL'}"
    )

    print(
        f"Finite Values                  : "
        f"{'PASS' if finite_valid else 'FAIL'}"
    )

    print(
        f"Training Matrix Dimension      : "
        f"{'PASS' if matrix_dimension_valid else 'FAIL'}"
    )

    print(
        f"Matrix Row Consistency         : "
        f"{'PASS' if matrix_row_count_valid else 'FAIL'}"
    )

    print(
        f"Training Tensor Dimension      : "
        f"{'PASS' if tensor_dimension_valid else 'FAIL'}"
    )

    print(
        f"Tensor Row Consistency         : "
        f"{'PASS' if tensor_row_count_valid else 'FAIL'}"
    )

    print(
        f"DataLoader Dataset Size        : "
        f"{'PASS' if dataloader_dataset_size_valid else 'FAIL'}"
    )

    print(
        f"DataLoader Batch Count         : "
        f"{'PASS' if dataloader_batch_count_valid else 'FAIL'}"
    )

    print(
        f"Overall Batch Validation       : "
        f"{'PASS' if batch_valid else 'FAIL'}"
    )

# ==============================================================================
# GLOBAL TRAINING BATCH VALIDATION
# ==============================================================================

print()

SPP_GAN_TRAIN_BATCH_VALID = all(
    SPP_GAN_TRAIN_BATCH_CHECKS.values()
)

print(
    f"Training Batch Coverage         : "
    f"{'PASS' if len(SPP_GAN_TRAIN_BATCH_CHECKS) == len(DATASETS) else 'FAIL'}"
)

print(
    f"Overall Training Batch Status   : "
    f"{'PASS' if SPP_GAN_TRAIN_BATCH_VALID else 'FAIL'}"
)

# ==============================================================================
# FAIL-FAST PIPELINE CHECK
# ==============================================================================

if not SPP_GAN_TRAIN_BATCH_VALID:

    failed_datasets = [
        dataset
        for dataset, status
        in SPP_GAN_TRAIN_BATCH_CHECKS.items()
        if not status
    ]

    raise ValueError(
        "SPP-GAN training batch validation failed "
        f"for datasets: {failed_datasets}"
    )

print()

print(
    "All SPP-GAN training batches passed "
    "feature, dimension, dtype, device, finite-value, "
    "matrix, tensor, and DataLoader consistency validation."
)

print()

print(
    "PART M6 — Training batch validation completed."
)

====================================================================================================
PART M6 — TRAINING BATCH VALIDATION
====================================================================================================

Dataset                         : Adult Income
Expected SPP-GAN Features      : 14
Training Feature Columns       : 14
Test Batch Shape               : (256, 14)
Feature Column Alignment       : PASS
Feature Dimension              : PASS
Batch Shape                    : PASS
Batch Size                     : PASS
Data Type                      : PASS
Device                         : PASS
Finite Values                  : PASS
Training Matrix Dimension      : PASS
Matrix Row Consistency         : PASS
Training Tensor Dimension      : PASS
Tensor Row Consistency         : PASS
DataLoader Dataset Size        : PASS
DataLoader Batch Count         : PASS
Overall Batch Validation       : PASS

Dataset                         : Bank Marketing
Expected SPP-GAN Features      : 16
Training Feature Columns       : 16
Test Batch Shape               : (256, 16)
Feature Column Alignment       : PASS
Feature Dimension              : PASS
Batch Shape                    : PASS
Batch Size                     : PASS
Data Type                      : PASS
Device                         : PASS
Finite Values                  : PASS
Training Matrix Dimension      : PASS
Matrix Row Consistency         : PASS
Training Tensor Dimension      : PASS
Tensor Row Consistency         : PASS
DataLoader Dataset Size        : PASS
DataLoader Batch Count         : PASS
Overall Batch Validation       : PASS

Dataset                         : diabetes_130us
Expected SPP-GAN Features      : 47
Training Feature Columns       : 47
Test Batch Shape               : (256, 47)
Feature Column Alignment       : PASS
Feature Dimension              : PASS
Batch Shape                    : PASS
Batch Size                     : PASS
Data Type                      : PASS
Device                         : PASS
Finite Values                  : PASS
Training Matrix Dimension      : PASS
Matrix Row Consistency         : PASS
Training Tensor Dimension      : PASS
Tensor Row Consistency         : PASS
DataLoader Dataset Size        : PASS
DataLoader Batch Count         : PASS
Overall Batch Validation       : PASS

Training Batch Coverage         : PASS
Overall Training Batch Status   : PASS

All SPP-GAN training batches passed feature, dimension, dtype, device, finite-value, matrix, tensor, and DataLoader consistency validation.

PART M6 — Training batch validation completed.

In [190]:
# ==============================================================================
# PART M7 — TRAINING DATA PREPARATION SUMMARY
# ==============================================================================

print("=" * 100)
print("PART M7 — TRAINING DATA PREPARATION SUMMARY")
print("=" * 100)

SPP_GAN_TRAINING_DATA_SUMMARY = []

for dataset in DATASETS:

    # --------------------------------------------------------------------------
    # TRAINING OBJECTS
    # --------------------------------------------------------------------------

    training_features = (
        SPP_GAN_TRAIN_FEATURE_DATA[dataset]
    )

    train_matrix = (
        SPP_GAN_TRAIN_MATRICES[dataset]
    )

    train_tensor = (
        SPP_GAN_TRAIN_TENSORS[dataset]
    )

    dataloader = (
        SPP_GAN_TRAIN_DATALOADERS[dataset]
    )

    # --------------------------------------------------------------------------
    # EXPECTED FEATURE INFORMATION
    # --------------------------------------------------------------------------

    expected_features = (
        FEATURE_COLUMNS[dataset]
    )

    expected_dimension = int(
        SPP_GAN_INPUT_DIMENSIONS[dataset]
    )

    # --------------------------------------------------------------------------
    # FEATURE VALIDATION
    # --------------------------------------------------------------------------

    feature_alignment_valid = (
        list(training_features.columns)
        ==
        list(expected_features)
    )

    feature_dimension_valid = (
        training_features.shape[1]
        ==
        expected_dimension
    )

    # --------------------------------------------------------------------------
    # MATRIX VALIDATION
    # --------------------------------------------------------------------------

    matrix_shape_valid = (
        train_matrix.ndim == 2
        and
        train_matrix.shape[1]
        ==
        expected_dimension
    )

    matrix_rows_valid = (
        train_matrix.shape[0]
        ==
        training_features.shape[0]
    )

    matrix_finite_valid = (
        np.isfinite(
            train_matrix
        ).all()
    )

    # --------------------------------------------------------------------------
    # TENSOR VALIDATION
    # --------------------------------------------------------------------------

    tensor_shape_valid = (
        train_tensor.ndim == 2
        and
        train_tensor.shape[1]
        ==
        expected_dimension
    )

    tensor_rows_valid = (
        train_tensor.shape[0]
        ==
        train_matrix.shape[0]
    )

    tensor_dtype_valid = (
        train_tensor.dtype
        ==
        torch.float32
    )

    tensor_finite_valid = (
        torch.isfinite(
            train_tensor
        ).all().item()
    )

    # --------------------------------------------------------------------------
    # DATALOADER VALIDATION
    # --------------------------------------------------------------------------

    dataloader_size_valid = (
        len(dataloader.dataset)
        ==
        train_tensor.shape[0]
    )

    dataloader_batch_count_valid = (
        len(dataloader)
        ==
        int(
            np.ceil(
                train_tensor.shape[0]
                /
                SPP_GAN_BATCH_SIZE
            )
        )
    )

    # --------------------------------------------------------------------------
    # M6 VALIDATION STATUS
    # --------------------------------------------------------------------------

    batch_validation_valid = (
        SPP_GAN_TRAIN_BATCH_CHECKS[
            dataset
        ]
    )

    # --------------------------------------------------------------------------
    # OVERALL DATA PREPARATION VALIDATION
    # --------------------------------------------------------------------------

    overall_dataset_valid = all([
        feature_alignment_valid,
        feature_dimension_valid,
        matrix_shape_valid,
        matrix_rows_valid,
        matrix_finite_valid,
        tensor_shape_valid,
        tensor_rows_valid,
        tensor_dtype_valid,
        tensor_finite_valid,
        dataloader_size_valid,
        dataloader_batch_count_valid,
        batch_validation_valid
    ])

    # --------------------------------------------------------------------------
    # SUMMARY RECORD
    # --------------------------------------------------------------------------

    SPP_GAN_TRAINING_DATA_SUMMARY.append({

        "Dataset":
            dataset,

        "Training Rows":
            int(
                train_tensor.shape[0]
            ),

        "Input Features":
            int(
                expected_dimension
            ),

        "Training Feature Columns":
            int(
                training_features.shape[1]
            ),

        "Batch Size":
            int(
                SPP_GAN_BATCH_SIZE
            ),

        "Batches per Epoch":
            int(
                len(dataloader)
            ),

        "Tensor Device":
            str(
                train_tensor.device
            ),

        "Data Type":
            str(
                train_tensor.dtype
            ),

        "Finite Values":
            tensor_finite_valid,

        "Feature Alignment":
            feature_alignment_valid,

        "Feature Dimension":
            feature_dimension_valid,

        "Matrix Validation":
            (
                matrix_shape_valid
                and
                matrix_rows_valid
                and
                matrix_finite_valid
            ),

        "Tensor Validation":
            (
                tensor_shape_valid
                and
                tensor_rows_valid
                and
                tensor_dtype_valid
                and
                tensor_finite_valid
            ),

        "DataLoader Validation":
            (
                dataloader_size_valid
                and
                dataloader_batch_count_valid
            ),

        "Batch Validation":
            batch_validation_valid,

        "Overall Dataset Valid":
            overall_dataset_valid
    })

# ==============================================================================
# SUMMARY DATAFRAME
# ==============================================================================

SPP_GAN_TRAINING_DATA_SUMMARY_DF = pd.DataFrame(
    SPP_GAN_TRAINING_DATA_SUMMARY
)

print()

display(
    SPP_GAN_TRAINING_DATA_SUMMARY_DF
)

# ==============================================================================
# GLOBAL TRAINING DATA VALIDATION
# ==============================================================================

SPP_GAN_TRAINING_DATA_PREPARATION_VALID = all(
    record[
        "Overall Dataset Valid"
    ]
    for record
    in SPP_GAN_TRAINING_DATA_SUMMARY
)

print()

print(
    f"Training Dataset Coverage       : "
    f"{'PASS' if len(SPP_GAN_TRAINING_DATA_SUMMARY) == len(DATASETS) else 'FAIL'}"
)

print(
    f"Feature Alignment               : "
    f"{'PASS' if all(record['Feature Alignment'] for record in SPP_GAN_TRAINING_DATA_SUMMARY) else 'FAIL'}"
)

print(
    f"Matrix Preparation              : "
    f"{'PASS' if all(record['Matrix Validation'] for record in SPP_GAN_TRAINING_DATA_SUMMARY) else 'FAIL'}"
)

print(
    f"Tensor Preparation              : "
    f"{'PASS' if all(record['Tensor Validation'] for record in SPP_GAN_TRAINING_DATA_SUMMARY) else 'FAIL'}"
)

print(
    f"DataLoader Preparation          : "
    f"{'PASS' if all(record['DataLoader Validation'] for record in SPP_GAN_TRAINING_DATA_SUMMARY) else 'FAIL'}"
)

print(
    f"Training Batch Validation       : "
    f"{'PASS' if all(record['Batch Validation'] for record in SPP_GAN_TRAINING_DATA_SUMMARY) else 'FAIL'}"
)

print()

print(
    f"Overall Training Data Status    : "
    f"{'PASS' if SPP_GAN_TRAINING_DATA_PREPARATION_VALID else 'FAIL'}"
)

# ==============================================================================
# FAIL-FAST PIPELINE CHECK
# ==============================================================================

if not SPP_GAN_TRAINING_DATA_PREPARATION_VALID:

    failed_datasets = [
        record["Dataset"]
        for record
        in SPP_GAN_TRAINING_DATA_SUMMARY
        if not record["Overall Dataset Valid"]
    ]

    raise ValueError(
        "SPP-GAN training data preparation validation failed "
        f"for datasets: {failed_datasets}"
    )

print()

print(
    "All SPP-GAN training datasets passed "
    "feature alignment, numeric matrix, tensor, "
    "DataLoader, and batch validation."
)

print()

print(
    "PART M7 — Training data preparation summary completed."
)

====================================================================================================
PART M7 — TRAINING DATA PREPARATION SUMMARY
====================================================================================================

,Dataset,Training Rows,Input Features,Training Feature Columns,Batch Size,Batches per Epoch,Tensor Device,Data Type,Finite Values,Feature Alignment,Feature Dimension,Matrix Validation,Tensor Validation,DataLoader Validation,Batch Validation,Overall Dataset Valid
0,Adult Income,22760,14,14,256,89,cpu,torch.float32,True,True,True,True,True,True,True,True
1,Bank Marketing,31647,16,16,256,124,cpu,torch.float32,True,True,True,True,True,True,True,True
2,diabetes_130us,71236,47,47,256,279,cpu,torch.float32,True,True,True,True,True,True,True,True

Training Dataset Coverage       : PASS
Feature Alignment               : PASS
Matrix Preparation              : PASS
Tensor Preparation              : PASS
DataLoader Preparation          : PASS
Training Batch Validation       : PASS

Overall Training Data Status    : PASS

All SPP-GAN training datasets passed feature alignment, numeric matrix, tensor, DataLoader, and batch validation.

PART M7 — Training data preparation summary completed.

In [191]:
# ==============================================================================
# PART M8 — FINAL TRAINING DATA VERIFICATION
# ==============================================================================

print("=" * 100)
print("PART M8 — FINAL TRAINING DATA VERIFICATION")
print("=" * 100)

# ==============================================================================
# FINAL TRAINING DATA VERIFICATION
# ==============================================================================

SPP_GAN_TRAINING_DATA_VERIFICATION = {

    # --------------------------------------------------------------------------
    # DATASET COVERAGE
    # --------------------------------------------------------------------------

    "All Datasets Loaded":
        (
            len(
                SPP_GAN_TRAIN_DATASETS
            )
            ==
            len(DATASETS)
        ),

    "All Feature Data":
        (
            len(
                SPP_GAN_TRAIN_FEATURE_DATA
            )
            ==
            len(DATASETS)
        ),

    "All Feature Matrices":
        (
            len(
                SPP_GAN_TRAIN_MATRICES
            )
            ==
            len(DATASETS)
        ),

    "All Training Tensors":
        (
            len(
                SPP_GAN_TRAIN_TENSORS
            )
            ==
            len(DATASETS)
        ),

    "All DataLoaders":
        (
            len(
                SPP_GAN_TRAIN_DATALOADERS
            )
            ==
            len(DATASETS)
        ),

    # --------------------------------------------------------------------------
    # FEATURE ALIGNMENT
    # --------------------------------------------------------------------------

    "All Feature Columns Aligned":
        all(
            list(
                SPP_GAN_TRAIN_FEATURE_DATA[
                    dataset
                ].columns
            )
            ==
            list(
                FEATURE_COLUMNS[
                    dataset
                ]
            )
            for dataset in DATASETS
        ),

    "All Feature Dimensions Valid":
        all(
            SPP_GAN_TRAIN_FEATURE_DATA[
                dataset
            ].shape[1]
            ==
            SPP_GAN_INPUT_DIMENSIONS[
                dataset
            ]
            for dataset in DATASETS
        ),

    # --------------------------------------------------------------------------
    # MATRIX VALIDATION
    # --------------------------------------------------------------------------

    "All Training Matrices Valid":
        all(
            (
                SPP_GAN_TRAIN_MATRICES[
                    dataset
                ].ndim == 2
                and
                SPP_GAN_TRAIN_MATRICES[
                    dataset
                ].shape[1]
                ==
                SPP_GAN_INPUT_DIMENSIONS[
                    dataset
                ]
            )
            for dataset in DATASETS
        ),

    "All Training Matrices Finite":
        all(
            np.isfinite(
                SPP_GAN_TRAIN_MATRICES[
                    dataset
                ]
            ).all()
            for dataset in DATASETS
        ),

    # --------------------------------------------------------------------------
    # TENSOR VALIDATION
    # --------------------------------------------------------------------------

    "All Training Tensors Valid":
        all(
            (
                SPP_GAN_TRAIN_TENSORS[
                    dataset
                ].ndim == 2
                and
                SPP_GAN_TRAIN_TENSORS[
                    dataset
                ].shape[1]
                ==
                SPP_GAN_INPUT_DIMENSIONS[
                    dataset
                ]
            )
            for dataset in DATASETS
        ),

    "All Training Tensors Float32":
        all(
            SPP_GAN_TRAIN_TENSORS[
                dataset
            ].dtype
            ==
            torch.float32
            for dataset in DATASETS
        ),

    "All Training Tensors Finite":
        all(
            torch.isfinite(
                SPP_GAN_TRAIN_TENSORS[
                    dataset
                ]
            ).all().item()
            for dataset in DATASETS
        ),

    # --------------------------------------------------------------------------
    # ROW CONSISTENCY
    # --------------------------------------------------------------------------

    "Matrix Tensor Row Consistency":
        all(
            SPP_GAN_TRAIN_MATRICES[
                dataset
            ].shape[0]
            ==
            SPP_GAN_TRAIN_TENSORS[
                dataset
            ].shape[0]
            for dataset in DATASETS
        ),

    "Feature Tensor Row Consistency":
        all(
            SPP_GAN_TRAIN_FEATURE_DATA[
                dataset
            ].shape[0]
            ==
            SPP_GAN_TRAIN_TENSORS[
                dataset
            ].shape[0]
            for dataset in DATASETS
        ),

    # --------------------------------------------------------------------------
    # DATALOADER VALIDATION
    # --------------------------------------------------------------------------

    "All DataLoader Dataset Sizes Valid":
        all(
            len(
                SPP_GAN_TRAIN_DATALOADERS[
                    dataset
                ].dataset
            )
            ==
            SPP_GAN_TRAIN_TENSORS[
                dataset
            ].shape[0]
            for dataset in DATASETS
        ),

    "All DataLoader Batch Counts Valid":
        all(
            len(
                SPP_GAN_TRAIN_DATALOADERS[
                    dataset
                ]
            )
            ==
            int(
                np.ceil(
                    SPP_GAN_TRAIN_TENSORS[
                        dataset
                    ].shape[0]
                    /
                    SPP_GAN_BATCH_SIZE
                )
            )
            for dataset in DATASETS
        ),

    # --------------------------------------------------------------------------
    # BATCH VALIDATION
    # --------------------------------------------------------------------------

    "All Batch Checks":
        (
            len(
                SPP_GAN_TRAIN_BATCH_CHECKS
            )
            ==
            len(DATASETS)
            and
            all(
                SPP_GAN_TRAIN_BATCH_CHECKS.values()
            )
        ),

    # --------------------------------------------------------------------------
    # M7 SUMMARY VALIDATION
    # --------------------------------------------------------------------------

    "M7 Training Data Validation":
        SPP_GAN_TRAINING_DATA_PREPARATION_VALID
}

# ==============================================================================
# VALIDATION REPORT
# ==============================================================================

for check, status in (
    SPP_GAN_TRAINING_DATA_VERIFICATION.items()
):

    print(
        f"{check:40s} : "
        f"{'PASS' if status else 'FAIL'}"
    )

# ==============================================================================
# FINAL READINESS STATUS
# ==============================================================================

print()

SPP_GAN_TRAINING_DATA_READY = all(
    SPP_GAN_TRAINING_DATA_VERIFICATION.values()
)

print(
    f"Training Data Ready                    : "
    f"{'PASS' if SPP_GAN_TRAINING_DATA_READY else 'FAIL'}"
)

# ==============================================================================
# FAILED CHECK DETAILS
# ==============================================================================

if not SPP_GAN_TRAINING_DATA_READY:

    failed_checks = [
        check
        for check, status
        in SPP_GAN_TRAINING_DATA_VERIFICATION.items()
        if not status
    ]

    print()

    print(
        "Failed Training Data Checks:"
    )

    for check in failed_checks:

        print(
            f"  - {check}"
        )

# ==============================================================================
# FAIL-FAST TRAINING GATE
# ==============================================================================

if not SPP_GAN_TRAINING_DATA_READY:

    raise RuntimeError(
        "SPP-GAN training data preparation failed. "
        "Training must not begin. "
        f"Failed checks: {failed_checks}"
    )

# ==============================================================================
# FINAL CONFIRMATION
# ==============================================================================

print()

print(
    "SPP-GAN training data passed final verification."
)

print(
    "Feature alignment, matrix preparation, tensor preparation, "
    "DataLoader construction, batch validation, and finite-value "
    "checks are valid for all datasets."
)

print(
    "SPP-GAN training data is ready for the training loop."
)

print()

print(
    "PART M8 — Final training data verification completed."
)

====================================================================================================
PART M8 — FINAL TRAINING DATA VERIFICATION
====================================================================================================
All Datasets Loaded                      : PASS
All Feature Data                         : PASS
All Feature Matrices                     : PASS
All Training Tensors                     : PASS
All DataLoaders                          : PASS
All Feature Columns Aligned              : PASS
All Feature Dimensions Valid             : PASS
All Training Matrices Valid              : PASS
All Training Matrices Finite             : PASS
All Training Tensors Valid               : PASS
All Training Tensors Float32             : PASS
All Training Tensors Finite              : PASS
Matrix Tensor Row Consistency            : PASS
Feature Tensor Row Consistency           : PASS
All DataLoader Dataset Sizes Valid       : PASS
All DataLoader Batch Counts Valid        : PASS
All Batch Checks                         : PASS
M7 Training Data Validation              : PASS

Training Data Ready                    : PASS

SPP-GAN training data passed final verification.
Feature alignment, matrix preparation, tensor preparation, DataLoader construction, batch validation, and finite-value checks are valid for all datasets.
SPP-GAN training data is ready for the training loop.

PART M8 — Final training data verification completed.

In [192]:
# ==============================================================================
# PART N1 — TRAINING STATE INITIALIZATION
# ==============================================================================

print("=" * 100)
print("PART N1 — TRAINING STATE INITIALIZATION")
print("=" * 100)

# ==============================================================================
# TRAINING HISTORY
# ==============================================================================

SPP_GAN_TRAINING_HISTORY = {}

# ==============================================================================
# PRIVACY TRAINING HISTORY
# ==============================================================================

SPP_GAN_PRIVACY_TRAINING_HISTORY = {}

# ==============================================================================
# GRADIENT HISTORY
# ==============================================================================

SPP_GAN_GRADIENT_HISTORY = {}

# ==============================================================================
# GLOBAL TRAINING STEP
# ==============================================================================

SPP_GAN_GLOBAL_STEP = {}

# ==============================================================================
# TRAINING STATUS
# ==============================================================================

SPP_GAN_TRAINING_STATUS = {}

# ==============================================================================
# TRAINING METRICS INITIALIZATION
# ==============================================================================

for dataset in DATASETS:

    # --------------------------------------------------------------------------
    # ADVERSARIAL TRAINING HISTORY
    # --------------------------------------------------------------------------

    SPP_GAN_TRAINING_HISTORY[dataset] = {

        "epoch": [],

        "generator_loss": [],

        "discriminator_loss": [],

        "real_loss": [],

        "fake_loss": [],

        "gradient_norm_generator": [],

        "gradient_norm_discriminator": []
    }

    # --------------------------------------------------------------------------
    # PRIVACY TRAINING HISTORY
    #
    # DP is applied directly to discriminator gradients.
    # Generator training is DP post-processing.
    # --------------------------------------------------------------------------

    SPP_GAN_PRIVACY_TRAINING_HISTORY[dataset] = {

        "epoch": [],

        "global_step": [],

        "maximum_sample_gradient_norm": [],

        "mean_sample_gradient_norm": [],

        "clipping_norm": [],

        "noise_multiplier": [],

        "noise_standard_deviation": [],

        "private_gradient_norm": []
    }

    # --------------------------------------------------------------------------
    # GRADIENT HISTORY
    # --------------------------------------------------------------------------

    SPP_GAN_GRADIENT_HISTORY[dataset] = {

        "generator": [],

        "discriminator": [],

        "private_discriminator": []
    }

    # --------------------------------------------------------------------------
    # GLOBAL STEP
    # --------------------------------------------------------------------------

    SPP_GAN_GLOBAL_STEP[dataset] = 0

    # --------------------------------------------------------------------------
    # TRAINING STATUS
    # --------------------------------------------------------------------------

    SPP_GAN_TRAINING_STATUS[dataset] = (
        "NOT_STARTED"
    )

    # --------------------------------------------------------------------------
    # INITIALIZATION REPORT
    # --------------------------------------------------------------------------

    print(
        f"{dataset:20s} : "
        "Training state initialized."
    )

# ==============================================================================
# INITIALIZATION VALIDATION
# ==============================================================================

SPP_GAN_TRAINING_STATE_INITIALIZATION_CHECKS = {

    "Training History":
        (
            len(
                SPP_GAN_TRAINING_HISTORY
            )
            ==
            len(DATASETS)
        ),

    "Privacy Training History":
        (
            len(
                SPP_GAN_PRIVACY_TRAINING_HISTORY
            )
            ==
            len(DATASETS)
        ),

    "Gradient History":
        (
            len(
                SPP_GAN_GRADIENT_HISTORY
            )
            ==
            len(DATASETS)
        ),

    "Global Step":
        (
            len(
                SPP_GAN_GLOBAL_STEP
            )
            ==
            len(DATASETS)
        ),

    "Training Status":
        (
            len(
                SPP_GAN_TRAINING_STATUS
            )
            ==
            len(DATASETS)
        ),

    "Initial Global Steps":
        all(
            SPP_GAN_GLOBAL_STEP[
                dataset
            ]
            ==
            0
            for dataset in DATASETS
        ),

    "Initial Training Status":
        all(
            SPP_GAN_TRAINING_STATUS[
                dataset
            ]
            ==
            "NOT_STARTED"
            for dataset in DATASETS
        )
}

# ==============================================================================
# HISTORY STRUCTURE VALIDATION
# ==============================================================================

for dataset in DATASETS:

    training_history_keys_valid = (
        set(
            SPP_GAN_TRAINING_HISTORY[
                dataset
            ].keys()
        )
        ==
        {
            "epoch",
            "generator_loss",
            "discriminator_loss",
            "real_loss",
            "fake_loss",
            "gradient_norm_generator",
            "gradient_norm_discriminator"
        }
    )

    privacy_history_keys_valid = (
        set(
            SPP_GAN_PRIVACY_TRAINING_HISTORY[
                dataset
            ].keys()
        )
        ==
        {
            "epoch",
            "global_step",
            "maximum_sample_gradient_norm",
            "mean_sample_gradient_norm",
            "clipping_norm",
            "noise_multiplier",
            "noise_standard_deviation",
            "private_gradient_norm"
        }
    )

    gradient_history_keys_valid = (
        set(
            SPP_GAN_GRADIENT_HISTORY[
                dataset
            ].keys()
        )
        ==
        {
            "generator",
            "discriminator",
            "private_discriminator"
        }
    )

    SPP_GAN_TRAINING_STATE_INITIALIZATION_CHECKS[
        f"{dataset} Training History Structure"
    ] = (
        training_history_keys_valid
    )

    SPP_GAN_TRAINING_STATE_INITIALIZATION_CHECKS[
        f"{dataset} Privacy History Structure"
    ] = (
        privacy_history_keys_valid
    )

    SPP_GAN_TRAINING_STATE_INITIALIZATION_CHECKS[
        f"{dataset} Gradient History Structure"
    ] = (
        gradient_history_keys_valid
    )

# ==============================================================================
# OVERALL INITIALIZATION VALIDATION
# ==============================================================================

SPP_GAN_TRAINING_STATE_INITIALIZATION_VALID = all(
    SPP_GAN_TRAINING_STATE_INITIALIZATION_CHECKS.values()
)

# ==============================================================================
# VALIDATION REPORT
# ==============================================================================

print()

for check, status in (
    SPP_GAN_TRAINING_STATE_INITIALIZATION_CHECKS.items()
):

    print(
        f"{check:45s} : "
        f"{'PASS' if status else 'FAIL'}"
    )

print()

print(
    f"Overall Training State Initialization : "
    f"{'PASS' if SPP_GAN_TRAINING_STATE_INITIALIZATION_VALID else 'FAIL'}"
)

# ==============================================================================
# FAIL-FAST PIPELINE CHECK
# ==============================================================================

if not SPP_GAN_TRAINING_STATE_INITIALIZATION_VALID:

    raise RuntimeError(
        "SPP-GAN training state initialization failed."
    )

print()

print(
    "Training histories, privacy histories, gradient histories, "
    "global steps, and training statuses initialized for all datasets."
)

print(
    "Manual DP-SGD tracking is configured for discriminator gradients."
)

print(
    "Generator privacy is tracked as post-processing; "
    "no direct generator DP noise history is maintained."
)

print()

print(
    "PART N1 — Training state initialization completed."
)

====================================================================================================
PART N1 — TRAINING STATE INITIALIZATION
====================================================================================================
Adult Income         : Training state initialized.
Bank Marketing       : Training state initialized.
diabetes_130us       : Training state initialized.

Training History                              : PASS
Privacy Training History                      : PASS
Gradient History                              : PASS
Global Step                                   : PASS
Training Status                               : PASS
Initial Global Steps                          : PASS
Initial Training Status                       : PASS
Adult Income Training History Structure       : PASS
Adult Income Privacy History Structure        : PASS
Adult Income Gradient History Structure       : PASS
Bank Marketing Training History Structure     : PASS
Bank Marketing Privacy History Structure      : PASS
Bank Marketing Gradient History Structure     : PASS
diabetes_130us Training History Structure     : PASS
diabetes_130us Privacy History Structure      : PASS
diabetes_130us Gradient History Structure     : PASS

Overall Training State Initialization : PASS

Training histories, privacy histories, gradient histories, global steps, and training statuses initialized for all datasets.
Manual DP-SGD tracking is configured for discriminator gradients.
Generator privacy is tracked as post-processing; no direct generator DP noise history is maintained.

PART N1 — Training state initialization completed.

In [193]:
# ==============================================================================
# PART N2 — TRAINING LOOP VALIDATION
# ==============================================================================

print("=" * 100)
print("PART N2 — TRAINING LOOP VALIDATION")
print("=" * 100)

# ==============================================================================
# PRIVACY VALIDATION STATUS
# ==============================================================================

SPP_GAN_PRIVACY_MECHANISM_VALID = all(
    SPP_GAN_PRIVACY_MECHANISM_CHECKS.values()
)

# ==============================================================================
# TRAINING PRE-CHECKS
# ==============================================================================

SPP_GAN_TRAINING_PRECHECKS = {

    "Training Data Ready":
        SPP_GAN_TRAINING_DATA_READY,

    "Generator Count":
        len(SPP_GAN_GENERATORS) == len(DATASETS),

    "Discriminator Count":
        len(SPP_GAN_DISCRIMINATORS) == len(DATASETS),

    "Generator Optimizer Count":
        len(SPP_GAN_GENERATOR_OPTIMIZERS) == len(DATASETS),

    "Discriminator Optimizer Count":
        len(SPP_GAN_DISCRIMINATOR_OPTIMIZERS) == len(DATASETS),

    "Training DataLoader Count":
        len(SPP_GAN_TRAIN_DATALOADERS) == len(DATASETS),

    "Generator Coverage":
        all(
            dataset in SPP_GAN_GENERATORS
            for dataset in DATASETS
        ),

    "Discriminator Coverage":
        all(
            dataset in SPP_GAN_DISCRIMINATORS
            for dataset in DATASETS
        ),

    "Generator Optimizer Coverage":
        all(
            dataset in SPP_GAN_GENERATOR_OPTIMIZERS
            for dataset in DATASETS
        ),

    "Discriminator Optimizer Coverage":
        all(
            dataset in SPP_GAN_DISCRIMINATOR_OPTIMIZERS
            for dataset in DATASETS
        ),

    "Training DataLoader Coverage":
        all(
            dataset in SPP_GAN_TRAIN_DATALOADERS
            for dataset in DATASETS
        ),

    "Privacy Mechanism Valid":
        SPP_GAN_PRIVACY_MECHANISM_VALID,

    "Optimizer Configuration Valid":
        SPP_GAN_OPTIMIZER_OVERALL_VALID,

    "Positive Epoch Count":
        int(SPP_GAN_EPOCHS) > 0,

    "Positive Batch Size":
        int(SPP_GAN_BATCH_SIZE) > 0
}

# ==============================================================================
# DATASET-SPECIFIC TRAINING PRE-CHECKS
# ==============================================================================

SPP_GAN_DATASET_TRAINING_PRECHECKS = {}

for dataset in DATASETS:

    training_tensor = (
        SPP_GAN_TRAIN_TENSORS[dataset]
    )

    dataloader = (
        SPP_GAN_TRAIN_DATALOADERS[dataset]
    )

    generator = (
        SPP_GAN_GENERATORS[dataset]
    )

    discriminator = (
        SPP_GAN_DISCRIMINATORS[dataset]
    )

    generator_optimizer = (
        SPP_GAN_GENERATOR_OPTIMIZERS[dataset]
    )

    discriminator_optimizer = (
        SPP_GAN_DISCRIMINATOR_OPTIMIZERS[dataset]
    )

    expected_dimension = int(
        SPP_GAN_INPUT_DIMENSIONS[dataset]
    )

    actual_dimension = int(
        training_tensor.shape[1]
    )

    dataset_checks = {

        "Training Tensor Exists":
            training_tensor is not None,

        "Training Tensor Dimension":
            actual_dimension == expected_dimension,

        "Training Tensor Finite":
            torch.isfinite(
                training_tensor
            ).all().item(),

        "DataLoader Non-Empty":
            len(dataloader) > 0,

        "Generator Exists":
            generator is not None,

        "Discriminator Exists":
            discriminator is not None,

        "Generator Optimizer Exists":
            generator_optimizer is not None,

        "Discriminator Optimizer Exists":
            discriminator_optimizer is not None,

        "Generator Optimizer Parameters":
            len(
                generator_optimizer.param_groups
            ) > 0,

        "Discriminator Optimizer Parameters":
            len(
                discriminator_optimizer.param_groups
            ) > 0
    }

    SPP_GAN_DATASET_TRAINING_PRECHECKS[dataset] = (
        dataset_checks
    )

    dataset_valid = all(
        dataset_checks.values()
    )

    print()

    print(
        f"Dataset                         : "
        f"{dataset}"
    )

    print(
        f"Training Tensor Shape           : "
        f"{tuple(training_tensor.shape)}"
    )

    print(
        f"Expected Input Dimension        : "
        f"{expected_dimension}"
    )

    print(
        f"Actual Input Dimension          : "
        f"{actual_dimension}"
    )

    print(
        f"Training Tensor Dimension       : "
        f"{'PASS' if dataset_checks['Training Tensor Dimension'] else 'FAIL'}"
    )

    print(
        f"Training Tensor Finite          : "
        f"{'PASS' if dataset_checks['Training Tensor Finite'] else 'FAIL'}"
    )

    print(
        f"DataLoader                      : "
        f"{'PASS' if dataset_checks['DataLoader Non-Empty'] else 'FAIL'}"
    )

    print(
        f"Generator                       : "
        f"{'PASS' if dataset_checks['Generator Exists'] else 'FAIL'}"
    )

    print(
        f"Discriminator                   : "
        f"{'PASS' if dataset_checks['Discriminator Exists'] else 'FAIL'}"
    )

    print(
        f"Generator Optimizer             : "
        f"{'PASS' if dataset_checks['Generator Optimizer Exists'] else 'FAIL'}"
    )

    print(
        f"Discriminator Optimizer         : "
        f"{'PASS' if dataset_checks['Discriminator Optimizer Exists'] else 'FAIL'}"
    )

    print(
        f"Dataset Training Pre-check      : "
        f"{'PASS' if dataset_valid else 'FAIL'}"
    )

# ==============================================================================
# DATASET TRAINING VALIDATION
# ==============================================================================

SPP_GAN_DATASET_TRAINING_VALID = all(
    all(
        checks.values()
    )
    for checks
    in SPP_GAN_DATASET_TRAINING_PRECHECKS.values()
)

SPP_GAN_TRAINING_PRECHECKS[
    "Dataset Training Validation"
] = SPP_GAN_DATASET_TRAINING_VALID

# ==============================================================================
# OVERALL TRAINING PRE-CHECK STATUS
# ==============================================================================

SPP_GAN_TRAINING_PRECHECKS_VALID = all(
    SPP_GAN_TRAINING_PRECHECKS.values()
)

# ==============================================================================
# GLOBAL VALIDATION REPORT
# ==============================================================================

print()
print("=" * 100)
print("GLOBAL TRAINING PRE-CHECK VALIDATION")
print("=" * 100)

for check, status in (
    SPP_GAN_TRAINING_PRECHECKS.items()
):

    print(
        f"{check:35s} : "
        f"{'PASS' if status else 'FAIL'}"
    )

print()

print(
    f"Overall Training Pre-check Status : "
    f"{'PASS' if SPP_GAN_TRAINING_PRECHECKS_VALID else 'FAIL'}"
)

# ==============================================================================
# FAIL-FAST TRAINING CHECK
# ==============================================================================

if not SPP_GAN_TRAINING_PRECHECKS_VALID:

    failed_checks = [
        check
        for check, status
        in SPP_GAN_TRAINING_PRECHECKS.items()
        if not status
    ]

    raise RuntimeError(
        "SPP-GAN training pre-check failed. "
        f"Failed checks: {failed_checks}. "
        "Training cannot begin."
    )

print()

print(
    "All SPP-GAN training pre-checks passed."
)

print(
    "Training data, model components, optimizers, "
    "privacy mechanism, and tensor dimensions are valid."
)

print(
    "SPP-GAN training is authorized to proceed."
)

print()

print(
    "PART N2 — Training loop validation completed."
)

====================================================================================================
PART N2 — TRAINING LOOP VALIDATION
====================================================================================================

Dataset                         : Adult Income
Training Tensor Shape           : (22760, 14)
Expected Input Dimension        : 14
Actual Input Dimension          : 14
Training Tensor Dimension       : PASS
Training Tensor Finite          : PASS
DataLoader                      : PASS
Generator                       : PASS
Discriminator                   : PASS
Generator Optimizer             : PASS
Discriminator Optimizer         : PASS
Dataset Training Pre-check      : PASS

Dataset                         : Bank Marketing
Training Tensor Shape           : (31647, 16)
Expected Input Dimension        : 16
Actual Input Dimension          : 16
Training Tensor Dimension       : PASS
Training Tensor Finite          : PASS
DataLoader                      : PASS
Generator                       : PASS
Discriminator                   : PASS
Generator Optimizer             : PASS
Discriminator Optimizer         : PASS
Dataset Training Pre-check      : PASS

Dataset                         : diabetes_130us
Training Tensor Shape           : (71236, 47)
Expected Input Dimension        : 47
Actual Input Dimension          : 47
Training Tensor Dimension       : PASS
Training Tensor Finite          : PASS
DataLoader                      : PASS
Generator                       : PASS
Discriminator                   : PASS
Generator Optimizer             : PASS
Discriminator Optimizer         : PASS
Dataset Training Pre-check      : PASS

====================================================================================================
GLOBAL TRAINING PRE-CHECK VALIDATION
====================================================================================================
Training Data Ready                 : PASS
Generator Count                     : PASS
Discriminator Count                 : PASS
Generator Optimizer Count           : PASS
Discriminator Optimizer Count       : PASS
Training DataLoader Count           : PASS
Generator Coverage                  : PASS
Discriminator Coverage              : PASS
Generator Optimizer Coverage        : PASS
Discriminator Optimizer Coverage    : PASS
Training DataLoader Coverage        : PASS
Privacy Mechanism Valid             : PASS
Optimizer Configuration Valid       : PASS
Positive Epoch Count                : PASS
Positive Batch Size                 : PASS
Dataset Training Validation         : PASS

Overall Training Pre-check Status : PASS

All SPP-GAN training pre-checks passed.
Training data, model components, optimizers, privacy mechanism, and tensor dimensions are valid.
SPP-GAN training is authorized to proceed.

PART N2 — Training loop validation completed.

In [195]:
# ==============================================================================
# SPP-GAN — PER-SAMPLE DISCRIMINATOR GRADIENT COMPUTATION
# ==============================================================================

def spp_gan_compute_private_discriminator_gradients(
    discriminator,
    real_data,
    fake_data,
    max_grad_norm,
    noise_multiplier
):
    """
    Computes DP-protected discriminator gradients using:

    1. Per-sample gradient computation
    2. Per-sample L2 clipping
    3. Clipped gradient aggregation
    4. Gaussian noise addition
    5. Batch normalization

    Dropout/random training operations are disabled during
    vmap-based per-sample gradient computation.
    """

    if real_data.ndim != 2:
        raise ValueError(
            "real_data must be a 2D tensor."
        )

    if fake_data.ndim != 2:
        raise ValueError(
            "fake_data must be a 2D tensor."
        )

    if real_data.shape != fake_data.shape:
        raise ValueError(
            "real_data and fake_data must have identical shapes."
        )

    batch_size = int(
        real_data.shape[0]
    )

    if batch_size <= 0:
        raise ValueError(
            "Batch size must be greater than zero."
        )

    max_grad_norm = float(
        max_grad_norm
    )

    noise_multiplier = float(
        noise_multiplier
    )

    if max_grad_norm <= 0.0:
        raise ValueError(
            "Maximum gradient norm must be greater than zero."
        )

    if noise_multiplier <= 0.0:
        raise ValueError(
            "Noise multiplier must be greater than zero."
        )

    # --------------------------------------------------------------------------
    # PARAMETER DICTIONARY
    # --------------------------------------------------------------------------

    parameters = {
        name: parameter
        for name, parameter
        in discriminator.named_parameters()
        if parameter.requires_grad
    }

    buffers = {
        name: buffer
        for name, buffer
        in discriminator.named_buffers()
    }

    if len(parameters) == 0:
        raise ValueError(
            "Discriminator contains no trainable parameters."
        )

    # --------------------------------------------------------------------------
    # SINGLE-SAMPLE LOSS
    # --------------------------------------------------------------------------

    def single_sample_loss(
        model_parameters,
        model_buffers,
        single_real,
        single_fake
    ):

        real_input = (
            single_real
            .unsqueeze(0)
        )

        fake_input = (
            single_fake
            .unsqueeze(0)
        )

        real_logit = functional_call(
            discriminator,
            (
                model_parameters,
                model_buffers
            ),
            (
                real_input,
            )
        )

        fake_logit = functional_call(
            discriminator,
            (
                model_parameters,
                model_buffers
            ),
            (
                fake_input,
            )
        )

        real_target = torch.ones_like(
            real_logit
        )

        fake_target = torch.zeros_like(
            fake_logit
        )

        real_loss = (
            SPP_GAN_ADVERSARIAL_CRITERION(
                real_logit,
                real_target
            )
        )

        fake_loss = (
            SPP_GAN_ADVERSARIAL_CRITERION(
                fake_logit,
                fake_target
            )
        )

        return (
            real_loss
            +
            fake_loss
        ).mean()

    # --------------------------------------------------------------------------
    # PRESERVE DISCRIMINATOR TRAINING STATE
    # --------------------------------------------------------------------------

    discriminator_training_state = (
        discriminator.training
    )

    # --------------------------------------------------------------------------
    # IMPORTANT:
    # DISABLE DROPOUT DURING VMAP
    # --------------------------------------------------------------------------

    discriminator.eval()

    try:

        per_sample_gradient_function = (
            torch.func.grad(
                single_sample_loss,
                argnums=0
            )
        )

        per_sample_gradients = (
            torch.func.vmap(
                per_sample_gradient_function,
                in_dims=(
                    None,
                    None,
                    0,
                    0
                ),
                randomness="error"
            )(
                parameters,
                buffers,
                real_data,
                fake_data
            )
        )

    finally:

        discriminator.train(
            discriminator_training_state
        )

    # --------------------------------------------------------------------------
    # CONVERT PARAMETER-WISE VMAP OUTPUT
    # TO SAMPLE-WISE GRADIENT LIST
    # --------------------------------------------------------------------------

    parameter_names = list(
        parameters.keys()
    )

    sample_gradient_list = []

    for sample_index in range(
        batch_size
    ):

        sample_gradients = []

        for parameter_name in parameter_names:

            gradient = (
                per_sample_gradients[
                    parameter_name
                ][sample_index]
            )

            sample_gradients.append(
                gradient
            )

        sample_gradient_list.append(
            sample_gradients
        )

    # --------------------------------------------------------------------------
    # PER-SAMPLE GRADIENT CLIPPING
    # --------------------------------------------------------------------------

    clipped_gradients, sample_gradient_norms = (
        spp_gan_clip_per_sample_gradients(
            per_sample_gradients=sample_gradient_list,
            max_grad_norm=max_grad_norm
        )
    )

    # --------------------------------------------------------------------------
    # VERIFY CLIPPED NORMS
    # --------------------------------------------------------------------------

    clipped_sample_norms = []

    for sample_gradients in clipped_gradients:

        total_squared_norm = torch.zeros(
            1,
            device=real_data.device
        )

        for gradient in sample_gradients:

            total_squared_norm = (
                total_squared_norm
                +
                gradient.pow(2).sum()
            )

        clipped_norm = torch.sqrt(
            total_squared_norm
            +
            1e-12
        )

        clipped_sample_norms.append(
            clipped_norm
        )

    clipped_sample_norms = torch.stack(
        clipped_sample_norms
    )

    # --------------------------------------------------------------------------
    # AGGREGATE CLIPPED GRADIENTS
    # --------------------------------------------------------------------------

    aggregated_gradients = []

    parameter_count = len(
        clipped_gradients[0]
    )

    for parameter_index in range(
        parameter_count
    ):

        parameter_gradients = torch.stack(
            [
                sample_gradients[
                    parameter_index
                ]
                for sample_gradients
                in clipped_gradients
            ],
            dim=0
        )

        aggregated_gradient = (
            parameter_gradients.sum(
                dim=0
            )
        )

        aggregated_gradients.append(
            aggregated_gradient
        )

    # --------------------------------------------------------------------------
    # GAUSSIAN NOISE
    # --------------------------------------------------------------------------

    noisy_gradients, noise_standard_deviation = (
        spp_gan_add_gaussian_noise_to_gradients(
            gradients=aggregated_gradients,
            max_grad_norm=max_grad_norm,
            noise_multiplier=noise_multiplier,
            batch_size=batch_size
        )
    )

    # --------------------------------------------------------------------------
    # PRIVATE BATCH-AVERAGED GRADIENTS
    # --------------------------------------------------------------------------

    private_gradients = [
        gradient / batch_size
        for gradient
        in noisy_gradients
    ]

    # --------------------------------------------------------------------------
    # FINITE-VALUE VALIDATION
    # --------------------------------------------------------------------------

    private_gradients_finite = all(
        torch.isfinite(
            gradient
        ).all().item()
        for gradient
        in private_gradients
    )

    if not private_gradients_finite:

        raise FloatingPointError(
            "Non-finite private discriminator gradients detected."
        )

    # --------------------------------------------------------------------------
    # RETURN
    # --------------------------------------------------------------------------

    return {
        "Private Gradients":
            private_gradients,

        "Sample Gradient Norms":
            sample_gradient_norms,

        "Clipped Sample Gradient Norms":
            clipped_sample_norms,

        "Maximum Sample Gradient Norm":
            float(
                sample_gradient_norms.max().item()
            ),

        "Mean Sample Gradient Norm":
            float(
                sample_gradient_norms.mean().item()
            ),

        "Maximum Clipped Gradient Norm":
            float(
                clipped_sample_norms.max().item()
            ),

        "Mean Clipped Gradient Norm":
            float(
                clipped_sample_norms.mean().item()
            ),

        "Noise Standard Deviation":
            float(
                noise_standard_deviation
            ),

        "Batch Size":
            batch_size,

        "Maximum Gradient Norm":
            max_grad_norm,

        "Noise Multiplier":
            noise_multiplier,

        "Private Gradients Finite":
            private_gradients_finite
    }

In [196]:
# ==============================================================================
# PART N3 — SPP-GAN TRAINING LOOP
# ==============================================================================

print("=" * 100)
print("PART N3 — SPP-GAN TRAINING LOOP")
print("=" * 100)

for dataset in DATASETS:

    print()
    print("-" * 100)
    print(
        f"Training Dataset : {dataset}"
    )
    print("-" * 100)

    generator = (
        SPP_GAN_GENERATORS[dataset]
    )

    discriminator = (
        SPP_GAN_DISCRIMINATORS[dataset]
    )

    generator_optimizer = (
        SPP_GAN_GENERATOR_OPTIMIZERS[dataset]
    )

    discriminator_optimizer = (
        SPP_GAN_DISCRIMINATOR_OPTIMIZERS[dataset]
    )

    train_dataloader = (
        SPP_GAN_TRAIN_DATALOADERS[dataset]
    )

    generator.train()
    discriminator.train()

    SPP_GAN_TRAINING_STATUS[dataset] = (
        "TRAINING"
    )

    for epoch in range(
        1,
        SPP_GAN_EPOCHS + 1
    ):

        epoch_generator_losses = []
        epoch_discriminator_losses = []
        epoch_real_losses = []
        epoch_fake_losses = []

        epoch_generator_gradient_norms = []
        epoch_discriminator_gradient_norms = []

        epoch_discriminator_noise_scales = []

        for batch in train_dataloader:

            # ==================================================================
            # PREPARE REAL DATA
            # ==================================================================

            real_data = batch[0].to(
                SPP_GAN_DEVICE,
                dtype=torch.float32
            )

            current_batch_size = (
                real_data.shape[0]
            )

            if current_batch_size <= 0:
                continue

            # ==================================================================
            # DISCRIMINATOR UPDATE
            # ==================================================================

            discriminator_optimizer.zero_grad(
                set_to_none=True
            )

            noise = torch.randn(
                current_batch_size,
                SPP_GAN_GENERATOR_INPUT_DIMENSION,
                device=SPP_GAN_DEVICE
            )

            with torch.no_grad():

                fake_data = generator(
                    noise
                )

            # ------------------------------------------------------------------
            # DIMENSION VALIDATION
            # ------------------------------------------------------------------

            if real_data.shape[1] != (
                SPP_GAN_INPUT_DIMENSIONS[dataset]
            ):

                raise ValueError(
                    f"Real-data dimension mismatch for "
                    f"{dataset}: expected "
                    f"{SPP_GAN_INPUT_DIMENSIONS[dataset]}, "
                    f"got {real_data.shape[1]}."
                )

            if fake_data.shape[1] != (
                SPP_GAN_OUTPUT_DIMENSIONS[dataset]
            ):

                raise ValueError(
                    f"Generated-data dimension mismatch for "
                    f"{dataset}: expected "
                    f"{SPP_GAN_OUTPUT_DIMENSIONS[dataset]}, "
                    f"got {fake_data.shape[1]}."
                )

            # ------------------------------------------------------------------
            # PRIVATE DISCRIMINATOR GRADIENTS
            # ------------------------------------------------------------------

            private_gradient_result = (
                spp_gan_compute_private_discriminator_gradients(
                    discriminator=discriminator,
                    real_data=real_data,
                    fake_data=fake_data,
                    max_grad_norm=(
                        SPP_GAN_PRIVACY_CLIPPING_NORM
                    ),
                    noise_multiplier=(
                        SPP_GAN_PRIVACY_NOISE_MULTIPLIER
                    )
                )
            )

            private_discriminator_gradients = (
                private_gradient_result[
                    "Private Gradients"
                ]
            )

            # ------------------------------------------------------------------
            # ASSIGN PRIVATE GRADIENTS
            # ------------------------------------------------------------------

            trainable_discriminator_parameters = [
                parameter
                for parameter
                in discriminator.parameters()
                if parameter.requires_grad
            ]

            if len(
                trainable_discriminator_parameters
            ) != len(
                private_discriminator_gradients
            ):

                raise RuntimeError(
                    f"Private discriminator gradient count "
                    f"does not match trainable parameter count "
                    f"for {dataset}."
                )

            for parameter, private_gradient in zip(
                trainable_discriminator_parameters,
                private_discriminator_gradients
            ):

                parameter.grad = (
                    private_gradient.detach().clone()
                )

            # ------------------------------------------------------------------
            # PRIVATE GRADIENT FINITE CHECK
            # ------------------------------------------------------------------

            discriminator_private_gradients_finite = all(
                parameter.grad is None
                or
                torch.isfinite(
                    parameter.grad
                ).all().item()
                for parameter
                in discriminator.parameters()
            )

            if not discriminator_private_gradients_finite:

                raise FloatingPointError(
                    f"Non-finite private discriminator gradients "
                    f"detected for {dataset}."
                )

            # ------------------------------------------------------------------
            # DISCRIMINATOR OPTIMIZER UPDATE
            # ------------------------------------------------------------------

            discriminator_optimizer.step()

            # ------------------------------------------------------------------
            # DISCRIMINATOR LOSSES FOR REPORTING
            # ------------------------------------------------------------------

            with torch.no_grad():

                real_logits = discriminator(
                    real_data
                )

                fake_logits = discriminator(
                    fake_data
                )

                discriminator_loss = (
                    spp_gan_discriminator_loss(
                        real_logits,
                        fake_logits
                    )
                )

                real_loss = (
                    SPP_GAN_ADVERSARIAL_CRITERION(
                        real_logits,
                        torch.ones_like(
                            real_logits
                        )
                    )
                )

                fake_loss = (
                    SPP_GAN_ADVERSARIAL_CRITERION(
                        fake_logits,
                        torch.zeros_like(
                            fake_logits
                        )
                    )
                )

            # ==================================================================
            # GENERATOR UPDATE
            # ==================================================================

            generator_optimizer.zero_grad(
                set_to_none=True
            )

            noise = torch.randn(
                current_batch_size,
                SPP_GAN_GENERATOR_INPUT_DIMENSION,
                device=SPP_GAN_DEVICE
            )

            generated_data = generator(
                noise
            )

            generated_logits = discriminator(
                generated_data
            )

            generator_loss = (
                spp_gan_generator_loss(
                    generated_logits
                )
            )

            generator_loss.backward()

            # ------------------------------------------------------------------
            # GENERATOR GRADIENT NORM
            # ------------------------------------------------------------------

            generator_gradient_squared_norm = 0.0

            for parameter in generator.parameters():

                if parameter.grad is None:
                    continue

                generator_gradient_squared_norm += (
                    parameter.grad.detach()
                    .pow(2)
                    .sum()
                    .item()
                )

            generator_gradient_norm = (
                generator_gradient_squared_norm
                ** 0.5
            )

            if not np.isfinite(
                generator_gradient_norm
            ):

                raise FloatingPointError(
                    f"Non-finite generator gradient norm "
                    f"detected for {dataset}."
                )

            # ------------------------------------------------------------------
            # IMPORTANT:
            # NO DIRECT DP CLIPPING OR NOISE FOR GENERATOR
            # ------------------------------------------------------------------

            generator_optimizer.step()

            # ==================================================================
            # DISCRIMINATOR GRADIENT REPORTING
            # ==================================================================

            discriminator_gradient_norm = (
                float(
                    private_gradient_result[
                        "Maximum Clipped Gradient Norm"
                    ]
                )
            )

            discriminator_noise_standard_deviation = (
                float(
                    private_gradient_result[
                        "Noise Standard Deviation"
                    ]
                )
            )

            # ==================================================================
            # LOSS RECORDING
            # ==================================================================

            epoch_generator_losses.append(
                float(
                    generator_loss.detach().item()
                )
            )

            epoch_discriminator_losses.append(
                float(
                    discriminator_loss.detach().item()
                )
            )

            epoch_real_losses.append(
                float(
                    real_loss.detach().item()
                )
            )

            epoch_fake_losses.append(
                float(
                    fake_loss.detach().item()
                )
            )

            epoch_generator_gradient_norms.append(
                float(
                    generator_gradient_norm
                )
            )

            epoch_discriminator_gradient_norms.append(
                discriminator_gradient_norm
            )

            epoch_discriminator_noise_scales.append(
                discriminator_noise_standard_deviation
            )

            SPP_GAN_GLOBAL_STEP[dataset] += 1

        # ======================================================================
        # EMPTY-EPOCH VALIDATION
        # ======================================================================

        if len(epoch_generator_losses) == 0:

            raise RuntimeError(
                f"No valid training batches were processed "
                f"for {dataset} in epoch {epoch}."
            )

        # ======================================================================
        # EPOCH AGGREGATION
        # ======================================================================

        mean_generator_loss = float(
            np.mean(
                epoch_generator_losses
            )
        )

        mean_discriminator_loss = float(
            np.mean(
                epoch_discriminator_losses
            )
        )

        mean_real_loss = float(
            np.mean(
                epoch_real_losses
            )
        )

        mean_fake_loss = float(
            np.mean(
                epoch_fake_losses
            )
        )

        mean_generator_gradient_norm = float(
            np.mean(
                epoch_generator_gradient_norms
            )
        )

        mean_discriminator_gradient_norm = float(
            np.mean(
                epoch_discriminator_gradient_norms
            )
        )

        mean_discriminator_noise_scale = float(
            np.mean(
                epoch_discriminator_noise_scales
            )
        )

        # ======================================================================
        # TRAINING HISTORY
        # ======================================================================

        SPP_GAN_TRAINING_HISTORY[dataset][
            "epoch"
        ].append(
            epoch
        )

        SPP_GAN_TRAINING_HISTORY[dataset][
            "generator_loss"
        ].append(
            mean_generator_loss
        )

        SPP_GAN_TRAINING_HISTORY[dataset][
            "discriminator_loss"
        ].append(
            mean_discriminator_loss
        )

        SPP_GAN_TRAINING_HISTORY[dataset][
            "real_loss"
        ].append(
            mean_real_loss
        )

        SPP_GAN_TRAINING_HISTORY[dataset][
            "fake_loss"
        ].append(
            mean_fake_loss
        )

        SPP_GAN_TRAINING_HISTORY[dataset][
            "gradient_norm_generator"
        ].append(
            mean_generator_gradient_norm
        )

        SPP_GAN_TRAINING_HISTORY[dataset][
            "gradient_norm_discriminator"
        ].append(
            mean_discriminator_gradient_norm
        )

        # ======================================================================
        # PRIVACY TRAINING HISTORY
        # ======================================================================

        SPP_GAN_PRIVACY_TRAINING_HISTORY[dataset][
            "epoch"
        ].append(
            epoch
        )

        SPP_GAN_PRIVACY_TRAINING_HISTORY[dataset][
            "gradient_clip_norm"
        ].append(
            SPP_GAN_PRIVACY_CLIPPING_NORM
        )

        # Generator direct DP is intentionally disabled.
        SPP_GAN_PRIVACY_TRAINING_HISTORY[dataset][
            "generator_noise_scale"
        ].append(
            0.0
        )

        SPP_GAN_PRIVACY_TRAINING_HISTORY[dataset][
            "discriminator_noise_scale"
        ].append(
            mean_discriminator_noise_scale
        )

        # ======================================================================
        # GRADIENT HISTORY
        # ======================================================================

        SPP_GAN_GRADIENT_HISTORY[dataset][
            "generator"
        ].append(
            mean_generator_gradient_norm
        )

        SPP_GAN_GRADIENT_HISTORY[dataset][
            "discriminator"
        ].append(
            mean_discriminator_gradient_norm
        )

        # ======================================================================
        # PROGRESS REPORT
        # ======================================================================

        if (
            epoch == 1
            or
            epoch % 10 == 0
            or
            epoch == SPP_GAN_EPOCHS
        ):

            print(
                f"Epoch {epoch:4d}/{SPP_GAN_EPOCHS} | "
                f"D Loss: {mean_discriminator_loss:.6f} | "
                f"G Loss: {mean_generator_loss:.6f} | "
                f"D Grad: {mean_discriminator_gradient_norm:.6f} | "
                f"G Grad: {mean_generator_gradient_norm:.6f} | "
                f"D Noise: {mean_discriminator_noise_scale:.6e}"
            )

    # ==========================================================================
    # DATASET TRAINING COMPLETED
    # ==========================================================================

    SPP_GAN_TRAINING_STATUS[dataset] = (
        "COMPLETED"
    )

    print()

    print(
        f"Training completed for {dataset}."
    )

print()

print(
    "PART N3 — SPP-GAN training loop completed."
)

====================================================================================================
PART N3 — SPP-GAN TRAINING LOOP
====================================================================================================

----------------------------------------------------------------------------------------------------
Training Dataset : Adult Income
----------------------------------------------------------------------------------------------------

ValueError: too many values to unpack (expected 2)

In [ ]:
# =============================================================================
# 7.15 Epoch Training
# =============================================================================

def train_epoch(
    generator,
    discriminator,
    optimizer_G,
    optimizer_D,
    criterion,
    train_loader,
    latent_dim,
    device,
    privacy_engine=None,
    delta=DELTA
):

    generator.train()

    discriminator.train()

    # ------------------------------------------------------------
    # Running Statistics
    # ------------------------------------------------------------

    total_g_loss = 0.0

    total_d_loss = 0.0

    total_g_grad = 0.0

    total_d_grad = 0.0

    total_batches = 0

    # ------------------------------------------------------------
    # Iterate Through Batches
    # ------------------------------------------------------------

    for batch in train_loader:

        real_batch = batch[0]

        stats = train_batch(

            generator=generator,

            discriminator=discriminator,

            optimizer_G=optimizer_G,

            optimizer_D=optimizer_D,

            criterion=criterion,

            real_batch=real_batch,

            latent_dim=latent_dim,

            device=device,

            privacy_engine=privacy_engine,

            delta=delta

        )

        total_g_loss += stats["generator_loss"]

        total_d_loss += stats["discriminator_loss"]

        total_g_grad += stats["generator_gradient_norm"]

        total_d_grad += stats["discriminator_gradient_norm"]

        total_batches += 1

    # ------------------------------------------------------------
    # Avoid Division by Zero
    # ------------------------------------------------------------

    if total_batches == 0:

        total_batches = 1

    # ------------------------------------------------------------
    # Epoch Statistics
    # ------------------------------------------------------------

    epoch_stats = {

        "generator_loss":

            total_g_loss / total_batches,

        "discriminator_loss":

            total_d_loss / total_batches,

        "generator_gradient_norm":

            total_g_grad / total_batches,

        "discriminator_gradient_norm":

            total_d_grad / total_batches,

        "epsilon":

            current_epsilon(
                privacy_engine,
                delta
            )

    }

    return epoch_stats

In [ ]:
# =============================================================================
# Test Epoch Training
# =============================================================================

print("=" * 80)

print("Testing Epoch Training")

print("=" * 80)

dataset_name = list(training_state.keys())[0]

state = training_state[dataset_name]

epoch_stats = train_epoch(

    generator=state["generator"],

    discriminator=state["discriminator"],

    optimizer_G=state["optimizer_G"],

    optimizer_D=state["optimizer_D"],

    criterion=state["criterion"],

    train_loader=state["train_loader"],

    latent_dim=LATENT_DIM,

    device=DEVICE,

    privacy_engine=state["privacy_engine"],

    delta=DELTA

)

print("\nEpoch Training Successful\n")

for key, value in epoch_stats.items():

    print(f"{key:<32}: {value:.6f}")

================================================================================
Testing Epoch Training
================================================================================

Epoch Training Successful

generator_loss                  : 1.173302
discriminator_loss              : 1.376349
generator_gradient_norm         : 2.478625
discriminator_gradient_norm     : 19.544423
epsilon                         : 0.613311

In [ ]:
# =============================================================================
# 7.16 Full Training
# =============================================================================

import copy
import time

print("=" * 90)
print("Training Proposed SPP-GAN")
print("=" * 90)

training_histories = {}

trained_generators = {}

trained_discriminators = {}

for dataset_name, state in training_state.items():

    print("\n" + "=" * 90)
    print(f"Dataset : {dataset_name}")
    print("=" * 90)

    generator = state["generator"]

    discriminator = state["discriminator"]

    optimizer_G = state["optimizer_G"]

    optimizer_D = state["optimizer_D"]

    criterion = state["criterion"]

    train_loader = state["train_loader"]

    privacy_engine = state["privacy_engine"]

    history = {

        "generator_loss": [],

        "discriminator_loss": [],

        "generator_gradient_norm": [],

        "discriminator_gradient_norm": [],

        "epsilon": [],

        "learning_rate_G": [],

        "learning_rate_D": []

    }

    best_generator_loss = float("inf")

    best_discriminator_loss = float("inf")

    best_generator_state = None

    best_discriminator_state = None

    start_time = time.time()

    # ==========================================================
    # Epoch Loop
    # ==========================================================

    for epoch in range(1, EPOCHS + 1):

        stats = train_epoch(

            generator=generator,

            discriminator=discriminator,

            optimizer_G=optimizer_G,

            optimizer_D=optimizer_D,

            criterion=criterion,

            train_loader=train_loader,

            latent_dim=LATENT_DIM,

            device=DEVICE,

            privacy_engine=privacy_engine,

            delta=DELTA

        )

        # ------------------------------------------------------
        # Store History
        # ------------------------------------------------------

        history["generator_loss"].append(

            stats["generator_loss"]

        )

        history["discriminator_loss"].append(

            stats["discriminator_loss"]

        )

        history["generator_gradient_norm"].append(

            stats["generator_gradient_norm"]

        )

        history["discriminator_gradient_norm"].append(

            stats["discriminator_gradient_norm"]

        )

        history["epsilon"].append(

            stats["epsilon"]

        )

        history["learning_rate_G"].append(

            optimizer_G.param_groups[0]["lr"]

        )

        history["learning_rate_D"].append(

            optimizer_D.param_groups[0]["lr"]

        )

        # ------------------------------------------------------
        # Save Best Generator
        # ------------------------------------------------------

        if stats["generator_loss"] < best_generator_loss:

            best_generator_loss = stats["generator_loss"]

            best_generator_state = copy.deepcopy(

                generator.state_dict()

            )

        # ------------------------------------------------------
        # Save Best Discriminator
        # ------------------------------------------------------

        if stats["discriminator_loss"] < best_discriminator_loss:

            best_discriminator_loss = stats["discriminator_loss"]

            best_discriminator_state = copy.deepcopy(

                discriminator.state_dict()

            )

        # ------------------------------------------------------
        # Progress
        # ------------------------------------------------------

        if epoch == 1 or epoch % 10 == 0 or epoch == EPOCHS:

            print(

                f"Epoch {epoch:03d}/{EPOCHS} | "

                f"G Loss: {stats['generator_loss']:.4f} | "

                f"D Loss: {stats['discriminator_loss']:.4f} | "

                f"Epsilon: {stats['epsilon']:.3f}"

            )

    # ==========================================================
    # Restore Best Models
    # ==========================================================

    generator.load_state_dict(

        best_generator_state

    )

    discriminator.load_state_dict(

        best_discriminator_state

    )

    trained_generators[dataset_name] = generator

    trained_discriminators[dataset_name] = discriminator

    training_histories[dataset_name] = history

    elapsed = time.time() - start_time

    print("\nTraining Completed")

    print(f"Best Generator Loss     : {best_generator_loss:.6f}")

    print(f"Best Discriminator Loss : {best_discriminator_loss:.6f}")

    print(f"Final ε                : {history['epsilon'][-1]:.4f}")

    print(f"Training Time          : {elapsed/60:.2f} minutes")

print("\n" + "=" * 90)
print("All Datasets Successfully Trained")
print("=" * 90)

==========================================================================================
Training Proposed SPP-GAN
==========================================================================================

==========================================================================================
Dataset : Adult Income
==========================================================================================
Epoch 001/300 | G Loss: 1.4140 | D Loss: 1.2307 | Epsilon: 0.795

In [ ]:
# =============================================================================
# Verify Training
# =============================================================================

print("=" * 90)
print("Training Summary")
print("=" * 90)

for dataset_name in training_histories:

    history = training_histories[dataset_name]

    print(f"\n{dataset_name}")

    print("-" * 60)

    print(f"Epochs Trained           : {len(history['generator_loss'])}")

    print(f"Final Generator Loss     : {history['generator_loss'][-1]:.6f}")

    print(f"Final Discriminator Loss : {history['discriminator_loss'][-1]:.6f}")

    print(f"Final Privacy Budget ε   : {history['epsilon'][-1]:.4f}")

In [ ]:
# =============================================================================
# 7.17 Save Models
# Block 1 : Create Model Directories
# =============================================================================

from pathlib import Path
import json
import torch

print("=" * 80)
print("Creating Model Directories")
print("=" * 80)

MODEL_DIR = PROJECT_ROOT / "results" / "proposed_model"

CHECKPOINT_DIR = MODEL_DIR / "checkpoints"

CONFIG_DIR = MODEL_DIR / "config"

HISTORY_DIR = MODEL_DIR / "history"

for directory in [

    MODEL_DIR,

    CHECKPOINT_DIR,

    CONFIG_DIR,

    HISTORY_DIR

]:

    directory.mkdir(

        parents=True,

        exist_ok=True

    )

print("Directories Created Successfully")

In [ ]:
# =============================================================================
# Block 2 : Save Checkpoints
# =============================================================================

print("=" * 80)
print("Saving Trained Models")
print("=" * 80)

saved_models = {}

for dataset_name, state in training_state.items():

    print(f"\nSaving : {dataset_name}")

    checkpoint = {

        "dataset_name": dataset_name,

        "generator_state_dict":

            state["generator"].state_dict(),

        "discriminator_state_dict":

            state["discriminator"].state_dict(),

        "optimizer_G_state_dict":

            state["optimizer_G"].state_dict(),

        "optimizer_D_state_dict":

            state["optimizer_D"].state_dict(),

        "latent_dim": LATENT_DIM,

        "epochs": EPOCHS,

        "batch_size": BATCH_SIZE,

        "learning_rate": LEARNING_RATE,

        "privacy_budget": PRIVACY_BUDGET,

        "delta": DELTA,

        "noise_multiplier": NOISE_MULTIPLIER,

        "max_grad_norm": MAX_GRAD_NORM

    }

    model_path = CHECKPOINT_DIR / (

        dataset_name.lower()

        .replace(" ", "_")

        + "_spp_gan.pt"

    )

    torch.save(

        checkpoint,

        model_path

    )

    saved_models[dataset_name] = model_path

    print("Saved :", model_path.name)

print("\nAll Models Saved Successfully")

In [ ]:
# =============================================================================
# Block 3 : Save Training History
# =============================================================================

print("=" * 80)
print("Saving Training History")
print("=" * 80)

saved_histories = {}

for dataset_name, history in training_histories.items():

    history_path = HISTORY_DIR / (

        dataset_name.lower()

        .replace(" ", "_")

        + "_history.json"

    )

    with open(

        history_path,

        "w"

    ) as file:

        json.dump(

            history,

            file,

            indent=4

        )

    saved_histories[dataset_name] = history_path

    print("Saved :", history_path.name)

print("\nTraining History Saved Successfully")

In [ ]:
# =============================================================================
# Block 4 : Save Experiment Configuration
# =============================================================================

configuration = {

    "model": "SPP-GAN",

    "datasets": list(training_state.keys()),

    "latent_dimension": LATENT_DIM,

    "epochs": EPOCHS,

    "batch_size": BATCH_SIZE,

    "learning_rate": LEARNING_RATE,

    "privacy_budget": PRIVACY_BUDGET,

    "delta": DELTA,

    "noise_multiplier": NOISE_MULTIPLIER,

    "max_grad_norm": MAX_GRAD_NORM,

    "device": str(DEVICE)

}

config_path = CONFIG_DIR / "experiment_config.json"

with open(

    config_path,

    "w"

) as file:

    json.dump(

        configuration,

        file,

        indent=4

    )

print("=" * 80)
print("Experiment Configuration Saved")
print("=" * 80)

print(config_path)

In [ ]:
# =============================================================================
# Block 5 : Verification
# =============================================================================

print("=" * 80)
print("Saved Files Summary")
print("=" * 80)

for dataset_name in saved_models:

    print(f"\n{dataset_name}")

    print("-" * 50)

    print("Checkpoint")

    print(saved_models[dataset_name])

    print("\nHistory")

    print(saved_histories[dataset_name])

print("\nConfiguration")

print(config_path)

print("\nModel Saving Completed Successfully")

In [ ]:
# =============================================================================
# 7.18 Generate Synthetic Data
# Block 1 : Synthetic Data Generation Function
# =============================================================================

import torch
import pandas as pd


def generate_synthetic_data(
    generator,
    original_dataframe,
    latent_dim,
    device,
    num_samples=None,
    batch_size=1024
):
    """
    Generate synthetic samples using the trained SPP-GAN generator.
    """

    generator.eval()

    if num_samples is None:
        num_samples = len(original_dataframe)

    feature_names = original_dataframe.columns.tolist()

    synthetic_batches = []

    with torch.no_grad():

        for start in range(0, num_samples, batch_size):

            current_batch = min(
                batch_size,
                num_samples - start
            )

            noise = torch.randn(
                current_batch,
                latent_dim,
                device=device
            )

            fake = generator(noise)

            synthetic_batches.append(
                fake.cpu()
            )

    synthetic_tensor = torch.cat(
        synthetic_batches,
        dim=0
    )

    synthetic_df = pd.DataFrame(

        synthetic_tensor.numpy(),

        columns=feature_names

    )

    return synthetic_df

In [ ]:
# =============================================================================
# Block 2 : Generate Synthetic Datasets
# =============================================================================

print("=" * 90)
print("Generating Synthetic Datasets")
print("=" * 90)

synthetic_datasets = {}

generation_statistics = {}

for dataset_name, state in training_state.items():

    print(f"\nGenerating : {dataset_name}")

    train_df = processed_datasets[dataset_name]["train"]

    synthetic_df = generate_synthetic_data(

        generator=state["generator"],

        original_dataframe=train_df,

        latent_dim=LATENT_DIM,

        device=DEVICE,

        num_samples=len(train_df)

    )

    synthetic_datasets[dataset_name] = synthetic_df

    generation_statistics[dataset_name] = {

        "original_samples": len(train_df),

        "synthetic_samples": len(synthetic_df),

        "features": synthetic_df.shape[1]

    }

    print(f"Original Shape  : {train_df.shape}")

    print(f"Synthetic Shape : {synthetic_df.shape}")

In [ ]:
# =============================================================================
# Block 3 : Verify Synthetic Datasets
# =============================================================================

print("=" * 90)
print("Synthetic Dataset Verification")
print("=" * 90)

for dataset_name, synthetic_df in synthetic_datasets.items():

    print(f"\nDataset : {dataset_name}")

    print("-" * 60)

    print("Shape")

    print(synthetic_df.shape)

    print("\nColumns")

    print(list(synthetic_df.columns))

    print("\nFirst Five Samples")

    display(

        synthetic_df.head()

    )

In [ ]:
# =============================================================================
# Block 4 : Generation Summary
# =============================================================================

summary_rows = []

for dataset_name, stats in generation_statistics.items():

    summary_rows.append({

        "Dataset": dataset_name,

        "Original Samples": stats["original_samples"],

        "Synthetic Samples": stats["synthetic_samples"],

        "Features": stats["features"]

    })

generation_summary = pd.DataFrame(summary_rows)

print("=" * 90)
print("Synthetic Data Generation Summary")
print("=" * 90)

display(generation_summary)

In [ ]:
# =============================================================================
# 7.19 Save Synthetic Data
# Block 1 : Create Output Directory
# =============================================================================

from pathlib import Path
import json
import pandas as pd

print("=" * 90)
print("Creating Synthetic Data Directories")
print("=" * 90)

SYNTHETIC_DIR = PROJECT_ROOT / "results" / "synthetic_data"

METADATA_DIR = SYNTHETIC_DIR / "metadata"

SYNTHETIC_DIR.mkdir(
    parents=True,
    exist_ok=True
)

METADATA_DIR.mkdir(
    parents=True,
    exist_ok=True
)

print("Directories Created Successfully")

In [ ]:
# =============================================================================
# Block 2 : Save Synthetic Datasets
# =============================================================================

print("=" * 90)
print("Saving Synthetic Datasets")
print("=" * 90)

saved_synthetic_files = {}

for dataset_name, synthetic_df in synthetic_datasets.items():

    filename = (

        dataset_name
        .lower()
        .replace(" ", "_")

        + "_spp_gan.csv"

    )

    save_path = SYNTHETIC_DIR / filename

    synthetic_df.to_csv(

        save_path,

        index=False

    )

    saved_synthetic_files[dataset_name] = save_path

    print(f"{dataset_name}")

    print(f"Saved -> {save_path.name}")

In [ ]:
# =============================================================================
# Block 3 : Save Metadata
# =============================================================================

print("=" * 90)
print("Saving Dataset Metadata")
print("=" * 90)

saved_metadata = {}

for dataset_name, synthetic_df in synthetic_datasets.items():

    metadata = {

        "dataset_name":

            dataset_name,

        "model":

            "SPP-GAN",

        "samples":

            int(len(synthetic_df)),

        "features":

            int(synthetic_df.shape[1]),

        "columns":

            list(synthetic_df.columns),

        "latent_dimension":

            LATENT_DIM,

        "epochs":

            EPOCHS,

        "batch_size":

            BATCH_SIZE,

        "learning_rate":

            LEARNING_RATE,

        "privacy_budget":

            PRIVACY_BUDGET,

        "noise_multiplier":

            NOISE_MULTIPLIER,

        "delta":

            DELTA,

        "max_grad_norm":

            MAX_GRAD_NORM

    }

    metadata_path = (

        METADATA_DIR /

        (

            dataset_name

            .lower()

            .replace(" ", "_")

            + "_metadata.json"

        )

    )

    with open(

        metadata_path,

        "w"

    ) as file:

        json.dump(

            metadata,

            file,

            indent=4

        )

    saved_metadata[dataset_name] = metadata_path

    print(

        metadata_path.name

    )

In [ ]:
# =============================================================================
# Block 4 : Save Summary
# =============================================================================

summary_rows = []

for dataset_name in synthetic_datasets:

    df = synthetic_datasets[dataset_name]

    summary_rows.append({

        "Dataset":

            dataset_name,

        "Samples":

            len(df),

        "Features":

            df.shape[1],

        "CSV File":

            saved_synthetic_files[dataset_name].name,

        "Metadata":

            saved_metadata[dataset_name].name

    })

synthetic_summary = pd.DataFrame(

    summary_rows

)

summary_path = SYNTHETIC_DIR / "synthetic_dataset_summary.csv"

synthetic_summary.to_csv(

    summary_path,

    index=False

)

print("\nSummary Saved")

print(summary_path)

In [ ]:
# =============================================================================
# Block 5 : Verification
# =============================================================================

print("=" * 90)
print("Synthetic Data Saved Successfully")
print("=" * 90)

display(

    synthetic_summary

)

print("\nSaved Files")

for dataset_name, path in saved_synthetic_files.items():

    print(

        f"{dataset_name:<20} {path.name}"

    )

print("\nMetadata Files")

for dataset_name, path in saved_metadata.items():

    print(

        f"{dataset_name:<20} {path.name}"

    )

print("\nSummary File")

print(summary_path)

In [ ]:
# =============================================================================
# 7.20 Training History
# Block 1 : Convert Training History
# =============================================================================

import pandas as pd

print("=" * 90)
print("Preparing Training History")
print("=" * 90)

history_dataframes = {}

for dataset_name, history in training_histories.items():

    history_df = pd.DataFrame({

        "Epoch": range(1, len(history["generator_loss"]) + 1),

        "Generator Loss": history["generator_loss"],

        "Discriminator Loss": history["discriminator_loss"],

        "Generator Gradient": history["generator_gradient_norm"],

        "Discriminator Gradient": history["discriminator_gradient_norm"],

        "Privacy Budget (ε)": history["epsilon"],

        "Generator LR": history["learning_rate_G"],

        "Discriminator LR": history["learning_rate_D"]

    })

    history_dataframes[dataset_name] = history_df

    print(f"{dataset_name:<20} {history_df.shape}")

print("\nTraining History Prepared Successfully")

In [ ]:
# =============================================================================
# Block 2 : Save Training History
# =============================================================================

print("=" * 90)
print("Saving Training History")
print("=" * 90)

TRAINING_HISTORY_DIR = PROJECT_ROOT / "results" / "training_history"

TRAINING_HISTORY_DIR.mkdir(

    parents=True,

    exist_ok=True

)

saved_history_files = {}

for dataset_name, history_df in history_dataframes.items():

    filename = (

        dataset_name.lower()

        .replace(" ", "_")

        + "_training_history.csv"

    )

    save_path = TRAINING_HISTORY_DIR / filename

    history_df.to_csv(

        save_path,

        index=False

    )

    saved_history_files[dataset_name] = save_path

    print(filename)

print("\nTraining History Saved Successfully")

In [ ]:
# =============================================================================
# Block 3 : Training Statistics
# =============================================================================

training_statistics = {}

summary_rows = []

for dataset_name, history_df in history_dataframes.items():

    best_epoch = history_df["Generator Loss"].idxmin()

    statistics = {

        "Best Epoch":

            int(best_epoch + 1),

        "Best Generator Loss":

            float(

                history_df["Generator Loss"].min()

            ),

        "Best Discriminator Loss":

            float(

                history_df["Discriminator Loss"].min()

            ),

        "Final Privacy Budget":

            float(

                history_df["Privacy Budget (ε)"].iloc[-1]

            )

    }

    training_statistics[dataset_name] = statistics

    summary_rows.append({

        "Dataset":

            dataset_name,

        **statistics

    })

training_summary = pd.DataFrame(summary_rows)

display(training_summary)

In [ ]:
# =============================================================================
# Block 4 : Plot Training Curves
# =============================================================================

import matplotlib.pyplot as plt

PLOT_DIR = PROJECT_ROOT / "results" / "training_plots"

PLOT_DIR.mkdir(

    parents=True,

    exist_ok=True

)

for dataset_name, history_df in history_dataframes.items():

    # ---------------------------------------------------------
    # Generator / Discriminator Loss
    # ---------------------------------------------------------

    plt.figure(figsize=(10,6))

    plt.plot(

        history_df["Epoch"],

        history_df["Generator Loss"],

        label="Generator"

    )

    plt.plot(

        history_df["Epoch"],

        history_df["Discriminator Loss"],

        label="Discriminator"

    )

    plt.xlabel("Epoch")

    plt.ylabel("Loss")

    plt.title(

        f"{dataset_name} Loss Curves"

    )

    plt.legend()

    plt.grid(True)

    plt.tight_layout()

    plt.savefig(

        PLOT_DIR /

        (

            dataset_name.lower()

            .replace(" ", "_")

            + "_loss.png"

        ),

        dpi=300

    )

    plt.close()

    # ---------------------------------------------------------
    # Privacy Budget
    # ---------------------------------------------------------

    plt.figure(figsize=(10,6))

    plt.plot(

        history_df["Epoch"],

        history_df["Privacy Budget (ε)"]

    )

    plt.xlabel("Epoch")

    plt.ylabel("ε")

    plt.title(

        f"{dataset_name} Privacy Budget"

    )

    plt.grid(True)

    plt.tight_layout()

    plt.savefig(

        PLOT_DIR /

        (

            dataset_name.lower()

            .replace(" ", "_")

            + "_epsilon.png"

        ),

        dpi=300

    )

    plt.close()

print("Training Curves Saved Successfully")

In [ ]:
# =============================================================================
# Block 5 : Verification
# =============================================================================

print("=" * 90)
print("Training History Summary")
print("=" * 90)

display(training_summary)

print("\nSaved History Files")

for dataset_name, path in saved_history_files.items():

    print(f"{dataset_name:<20} {path.name}")

print("\nPlots Saved To")

print(PLOT_DIR)

In [ ]:
# =============================================================================
# 7.21 Model Summary
# Block 1 : Model Information
# =============================================================================

import pandas as pd

print("=" * 90)
print("SPP-GAN MODEL SUMMARY")
print("=" * 90)

summary_rows = []

for dataset_name, state in training_state.items():

    generator = state["generator"]
    discriminator = state["discriminator"]

    generator_parameters = sum(
        p.numel()
        for p in generator.parameters()
    )

    discriminator_parameters = sum(
        p.numel()
        for p in discriminator.parameters()
    )

    summary_rows.append({

        "Dataset": dataset_name,

        "Generator Parameters": generator_parameters,

        "Discriminator Parameters": discriminator_parameters,

        "Total Parameters":
            generator_parameters +
            discriminator_parameters

    })

model_summary = pd.DataFrame(summary_rows)

display(model_summary)

In [ ]:
# =============================================================================
# Block 2 : Training Configuration
# =============================================================================

configuration_summary = pd.DataFrame({

    "Parameter":[

        "Model",

        "Latent Dimension",

        "Batch Size",

        "Epochs",

        "Learning Rate",

        "Noise Multiplier",

        "Privacy Budget (ε)",

        "Delta",

        "Gradient Clipping",

        "Device"

    ],

    "Value":[

        "SPP-GAN",

        LATENT_DIM,

        BATCH_SIZE,

        EPOCHS,

        LEARNING_RATE,

        NOISE_MULTIPLIER,

        PRIVACY_BUDGET,

        DELTA,

        MAX_GRAD_NORM,

        DEVICE

    ]

})

print("=" * 90)
print("Training Configuration")
print("=" * 90)

display(configuration_summary)

In [ ]:
# =============================================================================
# Block 3 : Dataset Summary
# =============================================================================

dataset_rows = []

for dataset_name in processed_datasets.keys():

    train_df = processed_datasets[dataset_name]["train"]

    validation_df = processed_datasets[dataset_name]["validation"]

    test_df = processed_datasets[dataset_name]["test"]

    synthetic_df = synthetic_datasets[dataset_name]

    dataset_rows.append({

        "Dataset":

            dataset_name,

        "Train":

            len(train_df),

        "Validation":

            len(validation_df),

        "Test":

            len(test_df),

        "Synthetic":

            len(synthetic_df),

        "Features":

            train_df.shape[1]

    })

dataset_summary = pd.DataFrame(dataset_rows)

print("=" * 90)
print("Dataset Summary")
print("=" * 90)

display(dataset_summary)

In [ ]:
# =============================================================================
# Block 4 : Training Performance
# =============================================================================

performance_rows = []

for dataset_name, history in training_histories.items():

    performance_rows.append({

        "Dataset":

            dataset_name,

        "Final Generator Loss":

            history["generator_loss"][-1],

        "Final Discriminator Loss":

            history["discriminator_loss"][-1],

        "Final Generator Gradient":

            history["generator_gradient_norm"][-1],

        "Final Discriminator Gradient":

            history["discriminator_gradient_norm"][-1],

        "Final Privacy Budget":

            history["epsilon"][-1]

    })

performance_summary = pd.DataFrame(

    performance_rows

)

print("=" * 90)
print("Training Performance")
print("=" * 90)

display(performance_summary)

In [ ]:
# =============================================================================
# Block 5 : Saved Files
# =============================================================================

saved_files = []

for dataset_name in training_state.keys():

    saved_files.append({

        "Dataset":

            dataset_name,

        "Model":

            saved_models[dataset_name].name,

        "Synthetic Data":

            saved_synthetic_files[dataset_name].name,

        "History":

            saved_history_files[dataset_name].name

    })

saved_files_summary = pd.DataFrame(saved_files)

print("=" * 90)
print("Saved Experiment Files")
print("=" * 90)

display(saved_files_summary)

In [ ]:
# =============================================================================
# Block 6 : Final Summary
# =============================================================================

print("=" * 90)
print("SPP-GAN TRAINING COMPLETED SUCCESSFULLY")
print("=" * 90)

print(f"Datasets Trained      : {len(training_state)}")

print(f"Models Saved          : {len(saved_models)}")

print(f"Synthetic Datasets    : {len(synthetic_datasets)}")

print(f"Training Histories    : {len(training_histories)}")

print(f"Privacy Enabled       : Yes")

print(f"Model                 : SPP-GAN")

print(f"Device                : {DEVICE}")

print("\nNotebook 07 Completed Successfully.")

print("\nReady for Notebook 08 : Comparative Evaluation")

print("=" * 90)