<a href="https://colab.research.google.com/github/amzad-786githumb/Privacy-Preserving-Synthetic-Tabular-Data-Generation-Using-Generative-Adversarial-Networks/blob/main/08_Comparative_evaluation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# ==============================================================================
# NOTEBOOK 08
#
# Comparative Evaluation of Privacy-Preserving Synthetic Tabular Data
# Generation Models
#
# ==============================================================================

"""
Comparative Evaluation of Privacy-Preserving Synthetic Tabular Data Generation

Researcher
----------
Mohd Amzad

Notebook
--------
Notebook 08 — Comparative Evaluation

Purpose
-------
This notebook performs the unified comparative evaluation of the synthetic
tabular data generation models developed throughout the research pipeline.

The objective is to evaluate and compare the statistical fidelity, data
utility, privacy characteristics, structural consistency, and overall
performance of the implemented synthetic data generation approaches under a
common evaluation framework.

Models Evaluated
----------------
1. Statistical Baseline Models
2. CTGAN
3. TVAE
4. DP-CTGAN
5. SPP-GAN — Proposed Framework

Research Pipeline Inputs
------------------------
This notebook consumes the validated outputs generated by the preceding
research notebooks.

Notebook 02
    • Preprocessed datasets
    • Dataset metadata
    • Feature information
    • Train/validation/test information where applicable

Notebook 03
    • Statistical synthetic-data generation results
    • Statistical evaluation artifacts

Notebook 04
    • CTGAN synthetic datasets
    • CTGAN evaluation artifacts

Notebook 05
    • TVAE synthetic datasets
    • TVAE evaluation artifacts

Notebook 06
    • DP-CTGAN synthetic datasets
    • Differential privacy configuration
    • Privacy-accounting artifacts
    • DP-CTGAN evaluation artifacts

Notebook 07
    • SPP-GAN synthetic datasets
    • SPP-GAN model results
    • Privacy-accounting artifacts
    • Training and evaluation artifacts

Datasets
--------
The comparative evaluation is performed consistently across the research
datasets:

    • Adult Income
    • Bank Marketing
    • diabetes_130us

Evaluation Framework
--------------------
All models are evaluated using a common evaluation methodology wherever the
underlying metric is applicable.

The comparative evaluation includes:

1. Structural Consistency
    • Row/column structure
    • Column names
    • Column order
    • Data types
    • Numeric feature consistency
    • Categorical feature consistency
    • Target-variable consistency
    • Missing-value consistency

2. Numerical Distribution Fidelity
    • Descriptive statistics
    • Distribution comparison
    • Kolmogorov–Smirnov statistics where applicable
    • Wasserstein distance
    • Additional distributional metrics where justified

3. Categorical Distribution Fidelity
    • Category preservation
    • Category-frequency comparison
    • Jensen–Shannon divergence where applicable
    • Total variation or equivalent categorical distribution measures

4. Correlation and Association Preservation
    • Numerical correlation preservation
    • Categorical association preservation where applicable
    • Mixed-type association analysis where justified

5. Downstream Data Utility
    • Machine-learning utility
    • Real-data model performance
    • Synthetic-data model performance
    • Train-on-Synthetic-Test-on-Real evaluation
    • Train-on-Real-Test-on-Real reference performance
    • Performance degradation analysis

6. Privacy Evaluation
    • Differential privacy configuration
    • Privacy budget (epsilon)
    • Delta
    • Noise multiplier
    • Gradient clipping
    • Privacy-accounting results
    • Privacy status and validity

7. Overall Comparative Performance
    • Dataset-level model comparison
    • Metric normalization where appropriate
    • Aggregate performance scores
    • Model ranking
    • Privacy–utility–fidelity trade-off analysis

Fair Comparison Principle
-------------------------
The comparative evaluation uses consistent datasets, preprocessing outputs,
evaluation definitions, metric directions, and reporting conventions across
all models.

Metrics are interpreted consistently:

    • Higher-is-better metrics are maximized.
    • Lower-is-better distance/error metrics are minimized.
    • Privacy parameters are reported separately from utility and fidelity
      scores and are not treated as ordinary predictive-performance metrics.

Where a metric is not applicable to a particular model or dataset, the result
is explicitly identified as not applicable rather than being replaced by an
arbitrary value.

Statistical Evaluation
----------------------
The notebook provides dataset-level and model-level comparisons using
appropriate statistical summaries and, where applicable, significance
analysis.

The evaluation is designed to distinguish between:

    • Statistical fidelity
    • Distributional fidelity
    • Structural fidelity
    • Correlation preservation
    • Downstream utility
    • Privacy protection

Comparative Analysis
--------------------
The primary comparative analysis investigates whether the proposed SPP-GAN
framework provides an improved privacy–utility–fidelity trade-off compared
with the established baseline approaches.

The analysis therefore considers:

    • Fidelity versus baseline models
    • Utility versus baseline models
    • Privacy protection
    • Structural consistency
    • Dataset-specific performance
    • Cross-dataset robustness
    • Overall comparative ranking

Outputs
-------
The notebook produces research-ready comparative artifacts, including:

    • Unified evaluation tables
    • Dataset-level comparison tables
    • Model-level comparison tables
    • Statistical fidelity summaries
    • Distributional fidelity summaries
    • Correlation-preservation summaries
    • Downstream utility summaries
    • Privacy summaries
    • Privacy–utility–fidelity analysis
    • Model ranking
    • Comparative visualizations
    • Final comparative results
    • Research findings summary
    • Research-readiness verification

Research Objective
------------------
The primary objective of this notebook is to determine whether the proposed
SPP-GAN framework demonstrates competitive or superior performance relative
to the established synthetic-data generation baselines while maintaining
the intended privacy guarantees.

The comparative evaluation provides the empirical evidence required to
assess the following research question:

Can the proposed privacy-preserving statistical–machine learning framework
generate high-fidelity synthetic tabular data while achieving a favorable
privacy–utility–fidelity trade-off compared with established statistical,
generative, and differentially private generative models?

Research Role
-------------
Notebook 08 is the final comparative evaluation stage of the experimental
pipeline.

It does not retrain the generative models.

It does not redefine preprocessing procedures.

It does not independently modify the trained models.

It consumes validated research artifacts from the preceding notebooks and
applies a common evaluation framework to generate reproducible comparative
results.

Version
-------
1.0
"""

In [41]:
# ==============================================================================
# PART A1 — INSTALL REQUIRED PACKAGES
# ==============================================================================

print("=" * 100)
print("PART A1 — INSTALLING REQUIRED EVALUATION PACKAGES")
print("=" * 100)

# ------------------------------------------------------------------------------
# Core Data Processing
# ------------------------------------------------------------------------------

!pip -q install numpy pandas scipy scikit-learn

# ------------------------------------------------------------------------------
# Visualization
# ------------------------------------------------------------------------------

!pip -q install matplotlib seaborn

# ------------------------------------------------------------------------------
# Configuration, Progress Tracking, and Artifact Management
# ------------------------------------------------------------------------------

!pip -q install pyyaml joblib tqdm

# ------------------------------------------------------------------------------
# Synthetic Data Evaluation
# ------------------------------------------------------------------------------

!pip -q install sdv sdmetrics

# ------------------------------------------------------------------------------
# Statistical Analysis
# ------------------------------------------------------------------------------

!pip -q install statsmodels pingouin

# ------------------------------------------------------------------------------
# Downstream Machine-Learning Utility Evaluation
# ------------------------------------------------------------------------------

!pip -q install xgboost lightgbm

print("\n" + "=" * 100)
print("PART A1 — REQUIRED EVALUATION PACKAGES INSTALLED SUCCESSFULLY")
print("=" * 100)

====================================================================================================
PART A1 — INSTALLING REQUIRED EVALUATION PACKAGES
====================================================================================================

====================================================================================================
PART A1 — REQUIRED EVALUATION PACKAGES INSTALLED SUCCESSFULLY
====================================================================================================

In [42]:
# ==============================================================================
# PART A2 — IMPORT REQUIRED LIBRARIES
# ==============================================================================

print("=" * 100)
print("PART A2 — IMPORTING REQUIRED EVALUATION LIBRARIES")
print("=" * 100)

# ------------------------------------------------------------------------------
# Standard Library
# ------------------------------------------------------------------------------

import os
import json
import random
import warnings
from pathlib import Path
from datetime import datetime

# ------------------------------------------------------------------------------
# Numerical Computing and Data Processing
# ------------------------------------------------------------------------------

import numpy as np
import pandas as pd

# ------------------------------------------------------------------------------
# Visualization
# ------------------------------------------------------------------------------

import matplotlib.pyplot as plt
import seaborn as sns

# ------------------------------------------------------------------------------
# Statistical Analysis
# ------------------------------------------------------------------------------

from scipy import stats

# ------------------------------------------------------------------------------
# Machine Learning — Data Splitting
# ------------------------------------------------------------------------------

from sklearn.model_selection import train_test_split

# ------------------------------------------------------------------------------
# Machine Learning — Preprocessing
# ------------------------------------------------------------------------------

from sklearn.preprocessing import StandardScaler

# ------------------------------------------------------------------------------
# Machine Learning — Classification Metrics
# ------------------------------------------------------------------------------

from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    roc_auc_score,
    confusion_matrix,
    classification_report
)

# ------------------------------------------------------------------------------
# Machine Learning — Regression Metrics
# ------------------------------------------------------------------------------

from sklearn.metrics import (
    mean_squared_error,
    mean_absolute_error,
    r2_score
)

# ------------------------------------------------------------------------------
# Machine Learning — Models
# ------------------------------------------------------------------------------

from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC

# ------------------------------------------------------------------------------
# Dimensionality Reduction
# ------------------------------------------------------------------------------

from sklearn.decomposition import PCA
from sklearn.manifold import TSNE

# ------------------------------------------------------------------------------
# Gradient Boosting Models
# ------------------------------------------------------------------------------

from xgboost import XGBClassifier
from lightgbm import LGBMClassifier

# ------------------------------------------------------------------------------
# Synthetic Data Evaluation
# ------------------------------------------------------------------------------

from sdmetrics.reports.single_table import QualityReport

# ------------------------------------------------------------------------------
# Progress Bar
# ------------------------------------------------------------------------------

from tqdm.auto import tqdm

# ------------------------------------------------------------------------------
# Warning Configuration
# ------------------------------------------------------------------------------

warnings.filterwarnings("ignore")

print("\n" + "=" * 100)
print("PART A2 — LIBRARIES IMPORTED SUCCESSFULLY")
print("=" * 100)

====================================================================================================
PART A2 — IMPORTING REQUIRED EVALUATION LIBRARIES
====================================================================================================

====================================================================================================
PART A2 — LIBRARIES IMPORTED SUCCESSFULLY
====================================================================================================

In [43]:
# ==============================================================================
# PART A3 — MOUNT GOOGLE DRIVE AND VALIDATE PROJECT ROOT
# ==============================================================================

from google.colab import drive
from pathlib import Path

print("=" * 100)
print("PART A3 — MOUNTING GOOGLE DRIVE")
print("=" * 100)

# ------------------------------------------------------------------------------
# Mount Google Drive
# ------------------------------------------------------------------------------

drive.mount("/content/drive")

# ------------------------------------------------------------------------------
# Define Project Root
# ------------------------------------------------------------------------------

PROJECT_ROOT = Path(
    "/content/drive/MyDrive/SPP_GAN_Project"
)

print("\nGoogle Drive Mounted Successfully")
print(f"Project Root : {PROJECT_ROOT}")

# ------------------------------------------------------------------------------
# Validate Project Root
# ------------------------------------------------------------------------------

if not PROJECT_ROOT.exists():
    raise FileNotFoundError(
        f"Project directory not found:\n{PROJECT_ROOT}\n\n"
        "Please verify the Google Drive project path before continuing."
    )

if not PROJECT_ROOT.is_dir():
    raise NotADirectoryError(
        f"Project root exists but is not a directory:\n{PROJECT_ROOT}"
    )

print("Project Directory Found and Validated")

print("=" * 100)
print("PART A3 — GOOGLE DRIVE AND PROJECT ROOT VALIDATION COMPLETED")
print("=" * 100)

====================================================================================================
PART A3 — MOUNTING GOOGLE DRIVE
====================================================================================================
Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

Google Drive Mounted Successfully
Project Root : /content/drive/MyDrive/SPP_GAN_Project
Project Directory Found and Validated
====================================================================================================
PART A3 — GOOGLE DRIVE AND PROJECT ROOT VALIDATION COMPLETED
====================================================================================================

In [44]:
# ==============================================================================
# PART A4 — REPRODUCIBILITY AND RANDOM SEED CONFIGURATION
# ==============================================================================

SEED = 42

# ------------------------------------------------------------------------------
# Python Random Seed
# ------------------------------------------------------------------------------

random.seed(SEED)

# ------------------------------------------------------------------------------
# NumPy Random Seed
# ------------------------------------------------------------------------------

np.random.seed(SEED)

# ------------------------------------------------------------------------------
# Python Hash Seed
# ------------------------------------------------------------------------------

os.environ["PYTHONHASHSEED"] = str(SEED)

# ------------------------------------------------------------------------------
# Reproducibility Summary
# ------------------------------------------------------------------------------

print("=" * 100)
print("PART A4 — REPRODUCIBILITY AND RANDOM SEED CONFIGURATION")
print("=" * 100)

print(f"Seed : {SEED}")
print("Python random seed initialized")
print("NumPy random seed initialized")
print("Python hash seed configured")

print("=" * 100)
print("PART A4 — REPRODUCIBILITY CONFIGURATION COMPLETED")
print("=" * 100)

====================================================================================================
PART A4 — REPRODUCIBILITY AND RANDOM SEED CONFIGURATION
====================================================================================================
Seed : 42
Python random seed initialized
NumPy random seed initialized
Python hash seed configured
====================================================================================================
PART A4 — REPRODUCIBILITY CONFIGURATION COMPLETED
====================================================================================================

In [45]:
# ==============================================================================
# PART A5 — EVALUATION RUNTIME CONFIGURATION
# ==============================================================================

print("=" * 100)
print("PART A5 — EVALUATION RUNTIME CONFIGURATION")
print("=" * 100)

# ------------------------------------------------------------------------------
# Research Evaluation Configuration
# ------------------------------------------------------------------------------

EVALUATION_VERSION = "1.0"

EVALUATION_TIMESTAMP = datetime.now().strftime(
    "%Y-%m-%d %H:%M:%S"
)

# ------------------------------------------------------------------------------
# Dataset Configuration
# ------------------------------------------------------------------------------

DATASETS = [
    "adult_income",
    "bank_marketing",
    "diabetes_130us"
]

# ------------------------------------------------------------------------------
# Model Configuration
# ------------------------------------------------------------------------------

MODELS = [
    "statistical",
    "ctgan",
    "tvae",
    "dp_ctgan",
    "spp_gan"
]

# ------------------------------------------------------------------------------
# Model Display Names
# ------------------------------------------------------------------------------

MODEL_DISPLAY_NAMES = {
    "statistical": "Statistical Baseline",
    "ctgan": "CTGAN",
    "tvae": "TVAE",
    "dp_ctgan": "DP-CTGAN",
    "spp_gan": "SPP-GAN"
}

# ------------------------------------------------------------------------------
# Evaluation Categories
# ------------------------------------------------------------------------------

EVALUATION_CATEGORIES = [
    "structural",
    "numerical_fidelity",
    "categorical_fidelity",
    "correlation",
    "sdmetrics",
    "utility",
    "privacy"
]

# ------------------------------------------------------------------------------
# Metric Direction Definitions
# ------------------------------------------------------------------------------

HIGHER_IS_BETTER_METRICS = {
    "accuracy",
    "precision",
    "recall",
    "f1",
    "roc_auc",
    "r2",
    "correlation_preservation",
    "quality_score"
}

LOWER_IS_BETTER_METRICS = {
    "ks_distance",
    "wasserstein_distance",
    "js_divergence",
    "mae",
    "mse",
    "rmse",
    "utility_degradation"
}

# ------------------------------------------------------------------------------
# Evaluation Flags
# ------------------------------------------------------------------------------

RUN_STRUCTURAL_EVALUATION = True
RUN_NUMERICAL_EVALUATION = True
RUN_CATEGORICAL_EVALUATION = True
RUN_CORRELATION_EVALUATION = True
RUN_SDMETRICS_EVALUATION = True
RUN_UTILITY_EVALUATION = True
RUN_PRIVACY_EVALUATION = True
RUN_STATISTICAL_TESTS = True
RUN_VISUALIZATIONS = True
RUN_MODEL_RANKING = True

# ------------------------------------------------------------------------------
# Output Directory Configuration
# ------------------------------------------------------------------------------

COMPARATIVE_EVALUATION_DIRECTORY = (
    PROJECT_ROOT / "Notebook_08_Comparative_Evaluation"
)

COMPARATIVE_RESULTS_DIRECTORY = (
    COMPARATIVE_EVALUATION_DIRECTORY / "results"
)

COMPARATIVE_TABLES_DIRECTORY = (
    COMPARATIVE_EVALUATION_DIRECTORY / "tables"
)

COMPARATIVE_PLOTS_DIRECTORY = (
    COMPARATIVE_EVALUATION_DIRECTORY / "visualizations"
)

COMPARATIVE_REPORTS_DIRECTORY = (
    COMPARATIVE_EVALUATION_DIRECTORY / "reports"
)

COMPARATIVE_LOGS_DIRECTORY = (
    COMPARATIVE_EVALUATION_DIRECTORY / "logs"
)

# ------------------------------------------------------------------------------
# Create Required Evaluation Directories
# ------------------------------------------------------------------------------

for directory in [
    COMPARATIVE_EVALUATION_DIRECTORY,
    COMPARATIVE_RESULTS_DIRECTORY,
    COMPARATIVE_TABLES_DIRECTORY,
    COMPARATIVE_PLOTS_DIRECTORY,
    COMPARATIVE_REPORTS_DIRECTORY,
    COMPARATIVE_LOGS_DIRECTORY
]:
    directory.mkdir(
        parents=True,
        exist_ok=True
    )

# ------------------------------------------------------------------------------
# Runtime Summary
# ------------------------------------------------------------------------------

print(f"Evaluation Version : {EVALUATION_VERSION}")
print(f"Evaluation Timestamp : {EVALUATION_TIMESTAMP}")
print(f"Random Seed : {SEED}")

print(f"\nDatasets : {DATASETS}")
print(f"Models : {MODELS}")

print("\nEvaluation Categories:")
for category in EVALUATION_CATEGORIES:
    print(f"  • {category}")

print("\nOutput Directories:")
print(f"  Evaluation Root : {COMPARATIVE_EVALUATION_DIRECTORY}")
print(f"  Results         : {COMPARATIVE_RESULTS_DIRECTORY}")
print(f"  Tables          : {COMPARATIVE_TABLES_DIRECTORY}")
print(f"  Visualizations  : {COMPARATIVE_PLOTS_DIRECTORY}")
print(f"  Reports         : {COMPARATIVE_REPORTS_DIRECTORY}")
print(f"  Logs            : {COMPARATIVE_LOGS_DIRECTORY}")

print("\n" + "=" * 100)
print("PART A5 — EVALUATION RUNTIME CONFIGURATION COMPLETED")
print("=" * 100)

====================================================================================================
PART A5 — EVALUATION RUNTIME CONFIGURATION
====================================================================================================
Evaluation Version : 1.0
Evaluation Timestamp : 2026-08-13 12:12:07
Random Seed : 42

Datasets : ['adult_income', 'bank_marketing', 'diabetes_130us']
Models : ['statistical', 'ctgan', 'tvae', 'dp_ctgan', 'spp_gan']

Evaluation Categories:
  • structural
  • numerical_fidelity
  • categorical_fidelity
  • correlation
  • sdmetrics
  • utility
  • privacy

Output Directories:
  Evaluation Root : /content/drive/MyDrive/SPP_GAN_Project/Notebook_08_Comparative_Evaluation
  Results         : /content/drive/MyDrive/SPP_GAN_Project/Notebook_08_Comparative_Evaluation/results
  Tables          : /content/drive/MyDrive/SPP_GAN_Project/Notebook_08_Comparative_Evaluation/tables
  Visualizations  : /content/drive/MyDrive/SPP_GAN_Project/Notebook_08_Comparative_Evaluation/visualizations
  Reports         : /content/drive/MyDrive/SPP_GAN_Project/Notebook_08_Comparative_Evaluation/reports
  Logs            : /content/drive/MyDrive/SPP_GAN_Project/Notebook_08_Comparative_Evaluation/logs

====================================================================================================
PART A5 — EVALUATION RUNTIME CONFIGURATION COMPLETED
====================================================================================================

In [46]:
# ==============================================================================
# PART B1 — LOAD PROJECT CONFIGURATION
# ==============================================================================

print("=" * 100)
print("PART B1 — LOADING PROJECT CONFIGURATION")
print("=" * 100)

import yaml

# ------------------------------------------------------------------------------
# Locate Configuration File
# ------------------------------------------------------------------------------

CONFIG_CANDIDATES = [
    PROJECT_ROOT / "config.yaml",
    PROJECT_ROOT / "configuration" / "config.yaml",
    PROJECT_ROOT / "configs" / "config.yaml",
    PROJECT_ROOT / "Config" / "config.yaml"
]

CONFIG_PATH = None

for candidate in CONFIG_CANDIDATES:
    if candidate.exists() and candidate.is_file():
        CONFIG_PATH = candidate
        break

if CONFIG_PATH is None:
    raise FileNotFoundError(
        "Project configuration file 'config.yaml' was not found.\n\n"
        f"Project Root:\n{PROJECT_ROOT}\n\n"
        "Checked locations:\n"
        + "\n".join(str(path) for path in CONFIG_CANDIDATES)
    )

# ------------------------------------------------------------------------------
# Load YAML Configuration
# ------------------------------------------------------------------------------

with open(CONFIG_PATH, "r", encoding="utf-8") as file:
    PROJECT_CONFIG = yaml.safe_load(file)

if PROJECT_CONFIG is None:
    raise ValueError(
        f"Configuration file is empty:\n{CONFIG_PATH}"
    )

if not isinstance(PROJECT_CONFIG, dict):
    raise TypeError(
        "Project configuration must be represented as a dictionary."
    )

print(f"Configuration File : {CONFIG_PATH}")
print(f"Configuration Sections : {list(PROJECT_CONFIG.keys())}")

print("\n" + "=" * 100)
print("PART B1 — PROJECT CONFIGURATION LOADED SUCCESSFULLY")
print("=" * 100)

====================================================================================================
PART B1 — LOADING PROJECT CONFIGURATION
====================================================================================================
Configuration File : /content/drive/MyDrive/SPP_GAN_Project/config.yaml
Configuration Sections : ['batch_size', 'beta1', 'beta2', 'delta', 'device', 'epochs', 'gradient_clip', 'latent_dimension', 'learning_rate', 'noise_multiplier', 'optimizer', 'privacy_budget', 'seed']

====================================================================================================
PART B1 — PROJECT CONFIGURATION LOADED SUCCESSFULLY
====================================================================================================

In [47]:
# ==============================================================================
# PART B2 — DEFINE RESEARCH DATASET REGISTRY
# ==============================================================================

print("=" * 100)
print("PART B2 — DEFINING RESEARCH DATASET REGISTRY")
print("=" * 100)

# ------------------------------------------------------------------------------
# Final Research Datasets
# ------------------------------------------------------------------------------

DATASET_REGISTRY = {
    "adult_income": {
        "display_name": "Adult Income",
        "target": None,
        "task_type": "classification"
    },
    "bank_marketing": {
        "display_name": "Bank Marketing",
        "target": None,
        "task_type": "classification"
    },
    "diabetes_130us": {
        "display_name": "Diabetes 130-US Hospitals",
        "target": None,
        "task_type": "classification"
    }
}

# ------------------------------------------------------------------------------
# Validate Dataset Registry
# ------------------------------------------------------------------------------

if set(DATASETS) != set(DATASET_REGISTRY.keys()):
    raise ValueError(
        "Mismatch between DATASETS and DATASET_REGISTRY.\n"
        f"DATASETS: {DATASETS}\n"
        f"Registry: {list(DATASET_REGISTRY.keys())}"
    )

print("Registered Datasets:")

for dataset_name, dataset_info in DATASET_REGISTRY.items():
    print(
        f"  • {dataset_name} | "
        f"{dataset_info['display_name']} | "
        f"{dataset_info['task_type']}"
    )

print("\n" + "=" * 100)
print("PART B2 — DATASET REGISTRY CREATED SUCCESSFULLY")
print("=" * 100)

====================================================================================================
PART B2 — DEFINING RESEARCH DATASET REGISTRY
====================================================================================================
Registered Datasets:
  • adult_income | Adult Income | classification
  • bank_marketing | Bank Marketing | classification
  • diabetes_130us | Diabetes 130-US Hospitals | classification

====================================================================================================
PART B2 — DATASET REGISTRY CREATED SUCCESSFULLY
====================================================================================================

In [48]:
# ==============================================================================
# PART B3 — DATASET SCHEMA AND TARGET DISCOVERY
# ==============================================================================

print("=" * 100)
print("PART B3 — DATASET SCHEMA AND TARGET DISCOVERY")
print("=" * 100)

# ------------------------------------------------------------------------------
# Search Project Artifacts for Metadata
# ------------------------------------------------------------------------------

METADATA_CANDIDATES = []

for path in PROJECT_ROOT.rglob("*"):

    if not path.is_file():
        continue

    if path.suffix.lower() not in {
        ".json",
        ".yaml",
        ".yml",
        ".csv"
    }:
        continue

    file_name = path.name.lower()

    metadata_keywords = [
        "metadata",
        "schema",
        "config",
        "dataset",
        "feature",
        "column"
    ]

    if any(
        keyword in file_name
        for keyword in metadata_keywords
    ):

        METADATA_CANDIDATES.append(path)

# ------------------------------------------------------------------------------
# Display Candidate Metadata Files
# ------------------------------------------------------------------------------

print("\nPotential Metadata / Schema Artifacts")

if METADATA_CANDIDATES:

    for path in METADATA_CANDIDATES:
        print(f"✓ {path}")

else:

    print("No obvious metadata artifacts found.")

# ------------------------------------------------------------------------------
# Inspect Existing Real Dataset Columns
# ------------------------------------------------------------------------------

print("\n" + "-" * 100)
print("REAL DATASET COLUMN STRUCTURES")
print("-" * 100)

DATASET_COLUMN_REGISTRY = {}

for dataset_name, df in REAL_DATASETS.items():

    columns = df.columns.tolist()

    DATASET_COLUMN_REGISTRY[
        dataset_name
    ] = columns

    print(f"\n{dataset_name}")
    print(f"Rows   : {df.shape[0]:,}")
    print(f"Columns: {df.shape[1]:,}")

    for index, column in enumerate(columns, start=1):

        print(
            f"  {index:>3}. "
            f"{column} "
            f"[{df[column].dtype}]"
        )

# ------------------------------------------------------------------------------
# Potential Target Columns
# ------------------------------------------------------------------------------

print("\n" + "-" * 100)
print("POTENTIAL TARGET COLUMNS")
print("-" * 100)

TARGET_NAME_HINTS = [
    "target",
    "label",
    "class",
    "outcome",
    "response",
    "income",
    "deposit",
    "readmitted",
    "default",
    "fraud",
    "diagnosis",
    "y"
]

POTENTIAL_TARGET_COLUMNS = {}

for dataset_name, df in REAL_DATASETS.items():

    candidates = []

    for column in df.columns:

        column_lower = str(column).lower().strip()

        # Name-based candidate
        if any(
            hint == column_lower
            or hint in column_lower
            for hint in TARGET_NAME_HINTS
        ):

            candidates.append(column)

    POTENTIAL_TARGET_COLUMNS[
        dataset_name
    ] = candidates

    print(f"\n{dataset_name}")

    if candidates:

        for column in candidates:

            print(
                f"  Candidate: {column}"
            )

    else:

        print(
            "  No target candidate identified "
            "from column names."
        )

# ------------------------------------------------------------------------------
# Create Diagnostic Table
# ------------------------------------------------------------------------------

TARGET_DISCOVERY_DF = pd.DataFrame({

    "Dataset": DATASETS,

    "Number of Columns": [
        len(
            DATASET_COLUMN_REGISTRY.get(
                dataset,
                []
            )
        )
        for dataset in DATASETS
    ],

    "Potential Target Columns": [
        POTENTIAL_TARGET_COLUMNS.get(
            dataset,
            []
        )
        for dataset in DATASETS
    ]
})

display(
    TARGET_DISCOVERY_DF
)

print("\n" + "=" * 100)
print("PART B3 — DATASET SCHEMA DISCOVERY COMPLETED")
print("=" * 100)

====================================================================================================
PART B3 — DATASET SCHEMA AND TARGET DISCOVERY
====================================================================================================

Potential Metadata / Schema Artifacts
✓ /content/drive/MyDrive/SPP_GAN_Project/config.yaml
✓ /content/drive/MyDrive/SPP_GAN_Project/results/dataset_summary.csv
✓ /content/drive/MyDrive/SPP_GAN_Project/results/dataset_validation.csv
✓ /content/drive/MyDrive/SPP_GAN_Project/results/feature_summary.csv
✓ /content/drive/MyDrive/SPP_GAN_Project/results/metadata_validation.csv
✓ /content/drive/MyDrive/SPP_GAN_Project/results/metadata_summary.csv
✓ /content/drive/MyDrive/SPP_GAN_Project/results/baseline_metadata_summary.csv
✓ /content/drive/MyDrive/SPP_GAN_Project/results/privacy_config.json
✓ /content/drive/MyDrive/SPP_GAN_Project/reports/experiment_config.json
✓ /content/drive/MyDrive/SPP_GAN_Project/reports/training_config.json
✓ /content/drive/MyDrive/SPP_GAN_Project/reports/baseline_configuration.json
✓ /content/drive/MyDrive/SPP_GAN_Project/reports/training_metadata_summary.csv
✓ /content/drive/MyDrive/SPP_GAN_Project/reports/dataset_statistics.csv
✓ /content/drive/MyDrive/SPP_GAN_Project/reports/dataset_overview.csv
✓ /content/drive/MyDrive/SPP_GAN_Project/reports/dataset_memory_usage.csv
✓ /content/drive/MyDrive/SPP_GAN_Project/reports/dataset_missing_summary.csv
✓ /content/drive/MyDrive/SPP_GAN_Project/reports/metadata_summary.csv
✓ /content/drive/MyDrive/SPP_GAN_Project/reports/dataset_split_summary.csv
✓ /content/drive/MyDrive/SPP_GAN_Project/reports/processed_dataset_summary.csv
✓ /content/drive/MyDrive/SPP_GAN_Project/reports/notebook03_dataset_summary.csv
✓ /content/drive/MyDrive/SPP_GAN_Project/reports/notebook03_metadata_summary.csv
✓ /content/drive/MyDrive/SPP_GAN_Project/reports/notebook03_dataset_information.csv
✓ /content/drive/MyDrive/SPP_GAN_Project/reports/dataset_summary.csv
✓ /content/drive/MyDrive/SPP_GAN_Project/reports/dataset_validation.csv
✓ /content/drive/MyDrive/SPP_GAN_Project/reports/feature_scaling_summary.csv
✓ /content/drive/MyDrive/SPP_GAN_Project/reports/synthetic_dataset_validation.csv
✓ /content/drive/MyDrive/SPP_GAN_Project/reports/tvae_synthetic_dataset_validation.csv
✓ /content/drive/MyDrive/SPP_GAN_Project/configs/ctgan_config.json
✓ /content/drive/MyDrive/SPP_GAN_Project/configs/tvae_config.json
✓ /content/drive/MyDrive/SPP_GAN_Project/configs/dp_ctgan_config.json
✓ /content/drive/MyDrive/SPP_GAN_Project/configs/ctabgan_config.json
✓ /content/drive/MyDrive/SPP_GAN_Project/configs/spp_gan_config.json
✓ /content/drive/MyDrive/SPP_GAN_Project/configs/loss_configuration.json
✓ /content/drive/MyDrive/SPP_GAN_Project/configs/project_config.json
✓ /content/drive/MyDrive/SPP_GAN_Project/configs/config.yaml
✓ /content/drive/MyDrive/SPP_GAN_Project/metadata/diabetes_130us_metadata.json
✓ /content/drive/MyDrive/SPP_GAN_Project/metadata/adult_income_metadata.json
✓ /content/drive/MyDrive/SPP_GAN_Project/metadata/bank_marketing_metadata.json
✓ /content/drive/MyDrive/SPP_GAN_Project/datasets/synthetic/CTGAN/synthetic_dataset_summary.csv
✓ /content/drive/MyDrive/SPP_GAN_Project/datasets/synthetic/CTGAN/synthetic_dataset_summary.json
✓ /content/drive/MyDrive/SPP_GAN_Project/models/gaussian_copula/adult_income_metadata.json
✓ /content/drive/MyDrive/SPP_GAN_Project/models/gaussian_copula/bank_marketing_metadata.json
✓ /content/drive/MyDrive/SPP_GAN_Project/models/gaussian_copula/diabetes_130us_metadata.json
✓ /content/drive/MyDrive/SPP_GAN_Project/models/baseline_models/metadata/adult_income_metadata.json
✓ /content/drive/MyDrive/SPP_GAN_Project/models/baseline_models/metadata/breast_cancer_metadata.json
✓ /content/drive/MyDrive/SPP_GAN_Project/models/baseline_models/metadata/bank_marketing_metadata.json
✓ /content/drive/MyDrive/SPP_GAN_Project/models/ctgan/training_logs/training_configuration.json
✓ /content/drive/MyDrive/SPP_GAN_Project/models/ctgan/training_logs/training_metadata.json
✓ /content/drive/MyDrive/SPP_GAN_Project/models/tvae/training_logs/training_configuration.json
✓ /content/drive/MyDrive/SPP_GAN_Project/models/tvae/training_logs/training_metadata.json
✓ /content/drive/MyDrive/SPP_GAN_Project/results/TVAE/tvae_configuration.json
✓ /content/drive/MyDrive/SPP_GAN_Project/results/privacy_models/dp_configuration.json
✓ /content/drive/MyDrive/SPP_GAN_Project/results/metadata/adult_income_metadata.json
✓ /content/drive/MyDrive/SPP_GAN_Project/results/metadata/breast_cancer_metadata.json
✓ /content/drive/MyDrive/SPP_GAN_Project/results/metadata/bank_marketing_metadata.json
✓ /content/drive/MyDrive/SPP_GAN_Project/results/privacy/privacy_configuration.json
✓ /content/drive/MyDrive/SPP_GAN_Project/results/TVAE/metadata/breast_cancer_metadata.json
✓ /content/drive/MyDrive/SPP_GAN_Project/results/TVAE/metadata/diabetes_130us_metadata.json
✓ /content/drive/MyDrive/SPP_GAN_Project/results/TVAE/metadata/adult_income_metadata.json
✓ /content/drive/MyDrive/SPP_GAN_Project/results/TVAE/metadata/bank_marketing_metadata.json
✓ /content/drive/MyDrive/SPP_GAN_Project/reports/statistical_analysis/feature_cardinality.csv
✓ /content/drive/MyDrive/SPP_GAN_Project/reports/statistical_analysis/dataset_dimensions.csv
✓ /content/drive/MyDrive/SPP_GAN_Project/reports/statistical_evaluation/dataset_size_comparison.csv
✓ /content/drive/MyDrive/SPP_GAN_Project/reports/statistical_evaluation/column_consistency.csv
✓ /content/drive/MyDrive/SPP_GAN_Project/reports/Notebook03/notebook_metadata.json
✓ /content/drive/MyDrive/SPP_GAN_Project/reports/CTGAN_Evaluation/feature_summary.csv
✓ /content/drive/MyDrive/SPP_GAN_Project/reports/CTGAN_Evaluation/schema_validation.csv
✓ /content/drive/MyDrive/SPP_GAN_Project/reports/CTGAN_Evaluation/dataset_summary.csv
✓ /content/drive/MyDrive/SPP_GAN_Project/reports/CTGAN_Evaluation/dataset_structure_evaluation.csv
✓ /content/drive/MyDrive/SPP_GAN_Project/reports/CTGAN_Evaluation/dataset_structural_consistency_evaluation.csv
✓ /content/drive/MyDrive/SPP_GAN_Project/reports/CTGAN_Evaluation/bank_marketing_column_missing_report.csv
✓ /content/drive/MyDrive/SPP_GAN_Project/reports/CTGAN_Evaluation/adult_income_column_missing_report.csv
✓ /content/drive/MyDrive/SPP_GAN_Project/reports/CTGAN_Evaluation/diabetes_130us_column_missing_report.csv
✓ /content/drive/MyDrive/SPP_GAN_Project/reports/TVAE/tvae_configuration_summary.csv
✓ /content/drive/MyDrive/SPP_GAN_Project/reports/TVAE/tvae_synthetic_dataset_summary.csv
✓ /content/drive/MyDrive/SPP_GAN_Project/reports/TVAE_Evaluation/dataset_summary.csv
✓ /content/drive/MyDrive/SPP_GAN_Project/reports/TVAE_Evaluation/feature_summary.csv
✓ /content/drive/MyDrive/SPP_GAN_Project/reports/TVAE_Evaluation/schema_validation.csv
✓ /content/drive/MyDrive/SPP_GAN_Project/reports/TVAE_Evaluation/dataset_structure_evaluation.csv
✓ /content/drive/MyDrive/SPP_GAN_Project/reports/TVAE_Evaluation/dataset_structural_consistency_evaluation.csv
✓ /content/drive/MyDrive/SPP_GAN_Project/reports/CTGAN_Evaluation/distribution_similarity/dataset_summary.csv
✓ /content/drive/MyDrive/SPP_GAN_Project/reports/CTGAN_Evaluation/correlation_evaluation/highly_correlated_feature_summary.csv
✓ /content/drive/MyDrive/SPP_GAN_Project/reports/CTGAN_Evaluation/correlation_evaluation/metadata.json
✓ /content/drive/MyDrive/SPP_GAN_Project/reports/CTGAN_Evaluation/machine_learning_utility/ml_configuration.json
✓ /content/drive/MyDrive/SPP_GAN_Project/reports/CTGAN_Evaluation/machine_learning_utility/dataset_manifest.csv
✓ /content/drive/MyDrive/SPP_GAN_Project/reports/CTGAN_Evaluation/distribution_similarity/distribution_comparison/distribution_feature_summary.csv
✓ /content/drive/MyDrive/SPP_GAN_Project/reports/CTGAN_Evaluation/distribution_similarity/distribution_comparison/distribution_dataset_summary.csv
✓ /content/drive/MyDrive/SPP_GAN_Project/reports/CTGAN_Evaluation/distribution_similarity/correlation_evaluation/reports/correlation_evaluation/metadata.json
✓ /content/drive/MyDrive/SPP_GAN_Project/reports/CTGAN_Evaluation/distribution_similarity/correlation_evaluation/reports/machine_learning_utility/ml_configuration.json
✓ /content/drive/MyDrive/SPP_GAN_Project/reports/CTGAN_Evaluation/distribution_similarity/correlation_evaluation/reports/machine_learning_utility/dataset_manifest.csv
✓ /content/drive/MyDrive/SPP_GAN_Project/reports/CTGAN_Evaluation/distribution_similarity/correlation/feature_pairs/highly_correlated_feature_summary.csv
✓ /content/drive/MyDrive/SPP_GAN_Project/reports/CTGAN_Evaluation/distribution_similarity/correlation/final_reports/highly_correlated_feature_summary.csv
✓ /content/drive/MyDrive/SPP_GAN_Project/reports/CTGAN_Evaluation/distribution_similarity/correlation/highly_correlated_pairs/highly_correlated_feature_summary.csv
✓ /content/drive/MyDrive/SPP_GAN_Project/reports/CTGAN_Evaluation/distribution_similarity/correlation/feature_pairs/adult_income/highly_correlated_feature_pairs.csv
✓ /content/drive/MyDrive/SPP_GAN_Project/reports/CTGAN_Evaluation/distribution_similarity/correlation/feature_pairs/bank_marketing/highly_correlated_feature_pairs.csv
✓ /content/drive/MyDrive/SPP_GAN_Project/reports/CTGAN_Evaluation/distribution_similarity/correlation/feature_pairs/breast_cancer/highly_correlated_feature_pairs.csv
✓ /content/drive/MyDrive/SPP_GAN_Project/reports/CTGAN_Evaluation/distribution_similarity/correlation/highly_correlated_pairs/adult_income/highly_correlated_feature_pairs.csv
✓ /content/drive/MyDrive/SPP_GAN_Project/reports/CTGAN_Evaluation/distribution_similarity/correlation/highly_correlated_pairs/bank_marketing/highly_correlated_feature_pairs.csv
✓ /content/drive/MyDrive/SPP_GAN_Project/reports/CTGAN_Evaluation/distribution_similarity/correlation/highly_correlated_pairs/diabetes_130us/highly_correlated_feature_pairs.csv
✓ /content/drive/MyDrive/SPP_GAN_Project/reports/TVAE_Evaluation/TVAE_Missing_Value_Evaluation/adult_income_tvae_column_missing_report.csv
✓ /content/drive/MyDrive/SPP_GAN_Project/reports/TVAE_Evaluation/TVAE_Missing_Value_Evaluation/diabetes_130us_tvae_column_missing_report.csv
✓ /content/drive/MyDrive/SPP_GAN_Project/reports/TVAE_Evaluation/TVAE_Missing_Value_Evaluation/bank_marketing_tvae_column_missing_report.csv
✓ /content/drive/MyDrive/SPP_GAN_Project/reports/TVAE_Evaluation/correlation_evaluation/highly_correlated_feature_summary.csv
✓ /content/drive/MyDrive/SPP_GAN_Project/reports/TVAE_Evaluation/correlation_evaluation/metadata.json
✓ /content/drive/MyDrive/SPP_GAN_Project/reports/TVAE_Evaluation/machine_learning_utility/ml_configuration.json
✓ /content/drive/MyDrive/SPP_GAN_Project/reports/TVAE_Evaluation/machine_learning_utility/dataset_level_utility_summary.csv
✓ /content/drive/MyDrive/SPP_GAN_Project/reports/TVAE_Evaluation/distribution_similarity/distribution_comparison/distribution_dataset_summary.csv
✓ /content/drive/MyDrive/SPP_GAN_Project/reports/TVAE_Evaluation/distribution_similarity/distribution_comparison/distribution_feature_summary.csv
✓ /content/drive/MyDrive/SPP_GAN_Project/reports/TVAE_Evaluation/distribution_similarity/correlation/highly_correlated_pairs/highly_correlated_feature_summary.csv
✓ /content/drive/MyDrive/SPP_GAN_Project/reports/TVAE_Evaluation/distribution_similarity/correlation/scores/correlation_dataset_ranking.csv
✓ /content/drive/MyDrive/SPP_GAN_Project/reports/TVAE_Evaluation/distribution_similarity/correlation/final_reports/highly_correlated_feature_summary.csv
✓ /content/drive/MyDrive/SPP_GAN_Project/reports/TVAE_Evaluation/distribution_similarity/correlation/highly_correlated_pairs/adult_income/highly_correlated_feature_pairs.csv
✓ /content/drive/MyDrive/SPP_GAN_Project/reports/TVAE_Evaluation/distribution_similarity/correlation/highly_correlated_pairs/bank_marketing/highly_correlated_feature_pairs.csv
✓ /content/drive/MyDrive/SPP_GAN_Project/reports/TVAE_Evaluation/distribution_similarity/correlation/highly_correlated_pairs/diabetes_130us/highly_correlated_feature_pairs.csv
✓ /content/drive/MyDrive/SPP_GAN_Project/reports/TVAE_Evaluation/machine_learning_utility/final_reports/dataset_level_utility_summary.csv
✓ /content/drive/MyDrive/SPP_GAN_Project/metadata/dp_ctgan/dp_ctgan_configuration.json
✓ /content/drive/MyDrive/SPP_GAN_Project/evaluation/dp_ctgan/training_history/Adult Income_dp_ctgan_training_history_metadata.json
✓ /content/drive/MyDrive/SPP_GAN_Project/evaluation/dp_ctgan/training_history/Bank Marketing_dp_ctgan_training_history_metadata.json
✓ /content/drive/MyDrive/SPP_GAN_Project/evaluation/dp_ctgan/training_history/diabetes_130us_dp_ctgan_training_history_metadata.json
✓ /content/drive/MyDrive/SPP_GAN_Project/data/synthetic/dp_ctgan/csv/Adult Income_dp_ctgan_metadata.json
✓ /content/drive/MyDrive/SPP_GAN_Project/data/synthetic/dp_ctgan/csv/Bank Marketing_dp_ctgan_metadata.json
✓ /content/drive/MyDrive/SPP_GAN_Project/data/synthetic/dp_ctgan/csv/diabetes_130us_dp_ctgan_metadata.json

----------------------------------------------------------------------------------------------------
REAL DATASET COLUMN STRUCTURES
----------------------------------------------------------------------------------------------------

adult_income
Rows   : 32,515
Columns: 15
    1. age [float64]
    2. workclass [int64]
    3. fnlwgt [float64]
    4. education [int64]
    5. education_num [float64]
    6. marital_status [int64]
    7. occupation [int64]
    8. relationship [int64]
    9. race [int64]
   10. sex [int64]
   11. capital_gain [float64]
   12. capital_loss [float64]
   13. hours_per_week [float64]
   14. native_country [int64]
   15. income [int64]

bank_marketing
Rows   : 45,211
Columns: 17
    1. age [float64]
    2. job [int64]
    3. marital [int64]
    4. education [int64]
    5. default [int64]
    6. balance [float64]
    7. housing [int64]
    8. loan [int64]
    9. contact [int64]
   10. day [float64]
   11. month [int64]
   12. duration [float64]
   13. campaign [float64]
   14. pdays [float64]
   15. previous [float64]
   16. poutcome [int64]
   17. y [int64]

diabetes_130us
Rows   : 101,766
Columns: 48
    1. race [int64]
    2. gender [int64]
    3. age [int64]
    4. weight [int64]
    5. admission_type_id [float64]
    6. discharge_disposition_id [float64]
    7. admission_source_id [float64]
    8. time_in_hospital [float64]
    9. payer_code [int64]
   10. medical_specialty [int64]
   11. num_lab_procedures [float64]
   12. num_procedures [float64]
   13. num_medications [float64]
   14. number_outpatient [float64]
   15. number_emergency [float64]
   16. number_inpatient [float64]
   17. diag_1 [int64]
   18. diag_2 [int64]
   19. diag_3 [int64]
   20. number_diagnoses [float64]
   21. max_glu_serum [int64]
   22. A1Cresult [int64]
   23. metformin [int64]
   24. repaglinide [int64]
   25. nateglinide [int64]
   26. chlorpropamide [int64]
   27. glimepiride [int64]
   28. acetohexamide [int64]
   29. glipizide [int64]
   30. glyburide [int64]
   31. tolbutamide [int64]
   32. pioglitazone [int64]
   33. rosiglitazone [int64]
   34. acarbose [int64]
   35. miglitol [int64]
   36. troglitazone [int64]
   37. tolazamide [int64]
   38. examide [int64]
   39. citoglipton [int64]
   40. insulin [int64]
   41. glyburide-metformin [int64]
   42. glipizide-metformin [int64]
   43. glimepiride-pioglitazone [int64]
   44. metformin-rosiglitazone [int64]
   45. metformin-pioglitazone [int64]
   46. change [int64]
   47. diabetesMed [int64]
   48. readmitted [int64]

----------------------------------------------------------------------------------------------------
POTENTIAL TARGET COLUMNS
----------------------------------------------------------------------------------------------------

adult_income
  Candidate: workclass
  Candidate: native_country
  Candidate: income

bank_marketing
  Candidate: default
  Candidate: day
  Candidate: pdays
  Candidate: poutcome
  Candidate: y

diabetes_130us
  Candidate: admission_type_id
  Candidate: payer_code
  Candidate: medical_specialty
  Candidate: number_emergency
  Candidate: glyburide
  Candidate: glyburide-metformin
  Candidate: readmitted

,Dataset,Number of Columns,Potential Target Columns
0,adult_income,15,"[workclass, native_country, income]"
1,bank_marketing,17,"[default, day, pdays, poutcome, y]"
2,diabetes_130us,48,"[admission_type_id, payer_code, medical_specia..."

====================================================================================================
PART B3 — DATASET SCHEMA DISCOVERY COMPLETED
====================================================================================================

In [49]:
# ==============================================================================
# PART B4 — DEFINE MODEL REGISTRY
# ==============================================================================

print("=" * 100)
print("PART B4 — DEFINING MODEL REGISTRY")
print("=" * 100)

MODEL_REGISTRY = {
    "statistical": {
        "display_name": "Statistical Baseline",
        "source_notebook": "Notebook 03",
        "privacy_type": "Non-DP"
    },
    "ctgan": {
        "display_name": "CTGAN",
        "source_notebook": "Notebook 04",
        "privacy_type": "Non-DP"
    },
    "tvae": {
        "display_name": "TVAE",
        "source_notebook": "Notebook 05",
        "privacy_type": "Non-DP"
    },
    "dp_ctgan": {
        "display_name": "DP-CTGAN",
        "source_notebook": "Notebook 06",
        "privacy_type": "Differential Privacy"
    },
    "spp_gan": {
        "display_name": "SPP-GAN",
        "source_notebook": "Notebook 07",
        "privacy_type": "Differential Privacy"
    }
}

# ------------------------------------------------------------------------------
# Validate Model Registry
# ------------------------------------------------------------------------------

if set(MODELS) != set(MODEL_REGISTRY.keys()):
    raise ValueError(
        "Mismatch between MODELS and MODEL_REGISTRY.\n"
        f"MODELS: {MODELS}\n"
        f"Registry: {list(MODEL_REGISTRY.keys())}"
    )

for model_name, model_info in MODEL_REGISTRY.items():

    print(
        f"  • {model_name} | "
        f"{model_info['display_name']} | "
        f"{model_info['source_notebook']} | "
        f"{model_info['privacy_type']}"
    )

print("\n" + "=" * 100)
print("PART B4 — MODEL REGISTRY CREATED SUCCESSFULLY")
print("=" * 100)

====================================================================================================
PART B4 — DEFINING MODEL REGISTRY
====================================================================================================
  • statistical | Statistical Baseline | Notebook 03 | Non-DP
  • ctgan | CTGAN | Notebook 04 | Non-DP
  • tvae | TVAE | Notebook 05 | Non-DP
  • dp_ctgan | DP-CTGAN | Notebook 06 | Differential Privacy
  • spp_gan | SPP-GAN | Notebook 07 | Differential Privacy

====================================================================================================
PART B4 — MODEL REGISTRY CREATED SUCCESSFULLY
====================================================================================================

In [50]:
# ==============================================================================
# PART B5 — DEFINE RESEARCH PIPELINE DEPENDENCY REGISTRY
# ==============================================================================

print("=" * 100)
print("PART B5 — DEFINING RESEARCH PIPELINE DEPENDENCY REGISTRY")
print("=" * 100)

RESEARCH_PIPELINE_REGISTRY = {
    "notebook_02": {
        "name": "Preprocessing",
        "role": "Reference Data and Metadata",
        "required": True
    },
    "notebook_03": {
        "name": "Statistical Module",
        "role": "Statistical Synthetic Data Baselines",
        "required": True
    },
    "notebook_04": {
        "name": "CTGAN",
        "role": "CTGAN Synthetic Data Baseline",
        "required": True
    },
    "notebook_05": {
        "name": "TVAE",
        "role": "TVAE Synthetic Data Baseline",
        "required": True
    },
    "notebook_06": {
        "name": "DP-CTGAN",
        "role": "Differentially Private GAN Baseline",
        "required": True
    },
    "notebook_07": {
        "name": "SPP-GAN",
        "role": "Proposed Privacy-Preserving Framework",
        "required": True
    }
}

print("Research Pipeline Dependencies:")

for notebook_id, notebook_info in RESEARCH_PIPELINE_REGISTRY.items():

    print(
        f"  • {notebook_id.upper()} | "
        f"{notebook_info['name']} | "
        f"{notebook_info['role']}"
    )

print("\n" + "=" * 100)
print("PART B5 — RESEARCH PIPELINE REGISTRY CREATED")
print("=" * 100)

====================================================================================================
PART B5 — DEFINING RESEARCH PIPELINE DEPENDENCY REGISTRY
====================================================================================================
Research Pipeline Dependencies:
  • NOTEBOOK_02 | Preprocessing | Reference Data and Metadata
  • NOTEBOOK_03 | Statistical Module | Statistical Synthetic Data Baselines
  • NOTEBOOK_04 | CTGAN | CTGAN Synthetic Data Baseline
  • NOTEBOOK_05 | TVAE | TVAE Synthetic Data Baseline
  • NOTEBOOK_06 | DP-CTGAN | Differentially Private GAN Baseline
  • NOTEBOOK_07 | SPP-GAN | Proposed Privacy-Preserving Framework

====================================================================================================
PART B5 — RESEARCH PIPELINE REGISTRY CREATED
====================================================================================================

In [51]:
# ==============================================================================
# PART B6 — DISCOVER PROJECT DATA AND RESULTS DIRECTORIES
# ==============================================================================

print("=" * 100)
print("PART B6 — DISCOVERING PROJECT DATA AND RESULTS DIRECTORIES")
print("=" * 100)

# ------------------------------------------------------------------------------
# Candidate Directories
# ------------------------------------------------------------------------------

DIRECTORY_CANDIDATES = {
    "data": [
        PROJECT_ROOT / "data"
    ],
    "processed": [
        PROJECT_ROOT / "data" / "processed",
        PROJECT_ROOT / "processed",
        PROJECT_ROOT / "Processed_Data",
        PROJECT_ROOT / "processed_data"
    ],
    "synthetic": [
        PROJECT_ROOT / "data" / "synthetic",
        PROJECT_ROOT / "synthetic_data",
        PROJECT_ROOT / "synthetic",
        PROJECT_ROOT / "Synthetic_Data",
        PROJECT_ROOT / "outputs" / "synthetic_data",
        PROJECT_ROOT / "results" / "synthetic_data"
    ],
    "results": [
        PROJECT_ROOT / "results",
        PROJECT_ROOT / "Results",
        PROJECT_ROOT / "outputs",
        PROJECT_ROOT / "evaluation",
        PROJECT_ROOT / "Evaluation"
    ]
}

# ------------------------------------------------------------------------------
# Discover Existing Directories
# ------------------------------------------------------------------------------

DISCOVERED_DIRECTORIES = {}

for category, candidates in DIRECTORY_CANDIDATES.items():

    existing = [
        path
        for path in candidates
        if path.exists() and path.is_dir()
    ]

    DISCOVERED_DIRECTORIES[category] = existing

# ------------------------------------------------------------------------------
# Display Discovered Directories
# ------------------------------------------------------------------------------

for category, directories in DISCOVERED_DIRECTORIES.items():

    print(f"\n{category.upper()}")

    if directories:

        for directory in directories:
            print(f"✓ {directory}")

    else:

        print("✗ No candidate directory found")

# ------------------------------------------------------------------------------
# Resolve Primary Data Directory
# ------------------------------------------------------------------------------

DATA_DIRECTORY = (
    DISCOVERED_DIRECTORIES["data"][0]
    if DISCOVERED_DIRECTORIES["data"]
    else PROJECT_ROOT
)

# ------------------------------------------------------------------------------
# Resolve Processed Data Directory
# ------------------------------------------------------------------------------

if DISCOVERED_DIRECTORIES["processed"]:

    PROCESSED_DATA_DIRECTORY = (
        DISCOVERED_DIRECTORIES["processed"][0]
    )

else:

    PROCESSED_DATA_DIRECTORY = None

# ------------------------------------------------------------------------------
# Preserve All Synthetic Data Directories
# ------------------------------------------------------------------------------

SYNTHETIC_DATA_DIRECTORIES = (
    DISCOVERED_DIRECTORIES["synthetic"]
)

if SYNTHETIC_DATA_DIRECTORIES:

    SYNTHETIC_DATA_DIRECTORY = (
        SYNTHETIC_DATA_DIRECTORIES[0]
    )

else:

    SYNTHETIC_DATA_DIRECTORY = None

# ------------------------------------------------------------------------------
# Preserve All Results Directories
# ------------------------------------------------------------------------------

RESULTS_DIRECTORIES = (
    DISCOVERED_DIRECTORIES["results"]
)

if RESULTS_DIRECTORIES:

    RESULTS_DIRECTORY = RESULTS_DIRECTORIES[0]

else:

    RESULTS_DIRECTORY = None

# ------------------------------------------------------------------------------
# Display Resolved Directories
# ------------------------------------------------------------------------------

print("\n" + "-" * 100)
print("RESOLVED PROJECT DIRECTORIES")
print("-" * 100)

print(f"Data Directory       : {DATA_DIRECTORY}")
print(f"Processed Data       : {PROCESSED_DATA_DIRECTORY}")

print("\nSynthetic Data Directories:")

if SYNTHETIC_DATA_DIRECTORIES:

    for directory in SYNTHETIC_DATA_DIRECTORIES:
        print(f"  ✓ {directory}")

else:

    print("  ✗ None found")

print("\nResults Directories:")

if RESULTS_DIRECTORIES:

    for directory in RESULTS_DIRECTORIES:
        print(f"  ✓ {directory}")

else:

    print("  ✗ None found")

print("\n" + "=" * 100)
print("PART B6 — DIRECTORY DISCOVERY COMPLETED")
print("=" * 100)

====================================================================================================
PART B6 — DISCOVERING PROJECT DATA AND RESULTS DIRECTORIES
====================================================================================================

DATA
✓ /content/drive/MyDrive/SPP_GAN_Project/data

PROCESSED
✗ No candidate directory found

SYNTHETIC
✓ /content/drive/MyDrive/SPP_GAN_Project/data/synthetic
✓ /content/drive/MyDrive/SPP_GAN_Project/synthetic_data

RESULTS
✓ /content/drive/MyDrive/SPP_GAN_Project/results
✓ /content/drive/MyDrive/SPP_GAN_Project/evaluation

----------------------------------------------------------------------------------------------------
RESOLVED PROJECT DIRECTORIES
----------------------------------------------------------------------------------------------------
Data Directory       : /content/drive/MyDrive/SPP_GAN_Project/data
Processed Data       : None

Synthetic Data Directories:
  ✓ /content/drive/MyDrive/SPP_GAN_Project/data/synthetic
  ✓ /content/drive/MyDrive/SPP_GAN_Project/synthetic_data

Results Directories:
  ✓ /content/drive/MyDrive/SPP_GAN_Project/results
  ✓ /content/drive/MyDrive/SPP_GAN_Project/evaluation

====================================================================================================
PART B6 — DIRECTORY DISCOVERY COMPLETED
====================================================================================================

In [52]:
# ==============================================================================
# PART B7 — DISCOVER RESEARCH ARTIFACTS
# ==============================================================================

print("=" * 100)
print("PART B7 — DISCOVERING RESEARCH ARTIFACTS")
print("=" * 100)

# ------------------------------------------------------------------------------
# File Extensions Relevant to Notebook 8
# ------------------------------------------------------------------------------

RESEARCH_FILE_EXTENSIONS = {
    ".csv",
    ".json",
    ".yaml",
    ".yml",
    ".pkl",
    ".joblib",
    ".pt",
    ".pth"
}

# ------------------------------------------------------------------------------
# Search Project Tree
# ------------------------------------------------------------------------------

RESEARCH_ARTIFACTS = []

for path in PROJECT_ROOT.rglob("*"):

    if not path.is_file():
        continue

    if path.suffix.lower() not in RESEARCH_FILE_EXTENSIONS:
        continue

    try:
        relative_path = path.relative_to(PROJECT_ROOT)
    except ValueError:
        relative_path = path

    RESEARCH_ARTIFACTS.append({
        "File": path.name,
        "Extension": path.suffix.lower(),
        "Relative Path": str(relative_path),
        "Absolute Path": str(path),
        "Size (KB)": round(
            path.stat().st_size / 1024,
            2
        )
    })

RESEARCH_ARTIFACTS_DF = pd.DataFrame(
    RESEARCH_ARTIFACTS
)

# ------------------------------------------------------------------------------
# Display Artifact Summary
# ------------------------------------------------------------------------------

if RESEARCH_ARTIFACTS_DF.empty:

    print("No research artifacts were discovered.")

else:

    RESEARCH_ARTIFACTS_DF = (
        RESEARCH_ARTIFACTS_DF
        .sort_values(
            by=["Extension", "Relative Path"]
        )
        .reset_index(drop=True)
    )

    print(
        f"Discovered {len(RESEARCH_ARTIFACTS_DF)} research artifacts."
    )

    display(RESEARCH_ARTIFACTS_DF)

print("\n" + "=" * 100)
print("PART B7 — RESEARCH ARTIFACT DISCOVERY COMPLETED")
print("=" * 100)

====================================================================================================
PART B7 — DISCOVERING RESEARCH ARTIFACTS
====================================================================================================
Discovered 835 research artifacts.

,File,Extension,Relative Path,Absolute Path,Size (KB)
0,Adult Income_dp_ctgan.csv,.csv,data/synthetic/dp_ctgan/csv/Adult Income_dp_ct...,/content/drive/MyDrive/SPP_GAN_Project/data/sy...,3531.70
1,Bank Marketing_dp_ctgan.csv,.csv,data/synthetic/dp_ctgan/csv/Bank Marketing_dp_...,/content/drive/MyDrive/SPP_GAN_Project/data/sy...,5789.95
2,diabetes_130us_dp_ctgan.csv,.csv,data/synthetic/dp_ctgan/csv/diabetes_130us_dp_...,/content/drive/MyDrive/SPP_GAN_Project/data/sy...,35341.77
3,adult_income_clean.csv,.csv,datasets/clean/adult_income_clean.csv,/content/drive/MyDrive/SPP_GAN_Project/dataset...,3433.58
4,bank_marketing_clean.csv,.csv,datasets/clean/bank_marketing_clean.csv,/content/drive/MyDrive/SPP_GAN_Project/dataset...,3619.23
...,...,...,...,...,...
830,bank_marketing_definition.pt,.pt,models/spp_gan/definitions/bank_marketing_defi...,/content/drive/MyDrive/SPP_GAN_Project/models/...,2363.01
831,breast_cancer_definition.pt,.pt,models/spp_gan/definitions/breast_cancer_defin...,/content/drive/MyDrive/SPP_GAN_Project/models/...,2278.16
832,Adult_Income_best_generator.pth,.pth,results/training/models/Adult_Income_best_gene...,/content/drive/MyDrive/SPP_GAN_Project/results...,1183.95
833,config.yaml,.yaml,config.yaml,/content/drive/MyDrive/SPP_GAN_Project/config....,0.20
834,config.yaml,.yaml,configs/config.yaml,/content/drive/MyDrive/SPP_GAN_Project/configs...,5.55

====================================================================================================
PART B7 — RESEARCH ARTIFACT DISCOVERY COMPLETED
====================================================================================================

In [53]:
# ==============================================================================
# PART B8 — IDENTIFY DATASET FILES
# ==============================================================================

print("=" * 100)
print("PART B8 — IDENTIFYING DATASET FILES")
print("=" * 100)

EXPECTED_DATASET_NAMES = {
    "adult_income": [
        "adult_income",
        "adult-income",
        "adult income"
    ],
    "bank_marketing": [
        "bank_marketing",
        "bank-marketing",
        "bank marketing"
    ],
    "diabetes_130us": [
        "diabetes_130us",
        "diabetes-130us",
        "diabetes 130us",
        "diabetes"
    ]
}

DATASET_FILE_REGISTRY = {
    dataset: []
    for dataset in DATASETS
}

# ------------------------------------------------------------------------------
# Search CSV Files
# ------------------------------------------------------------------------------

if not RESEARCH_ARTIFACTS_DF.empty:

    csv_files = RESEARCH_ARTIFACTS_DF[
        RESEARCH_ARTIFACTS_DF["Extension"] == ".csv"
    ]

    for dataset_name, name_patterns in EXPECTED_DATASET_NAMES.items():

        for _, row in csv_files.iterrows():

            filename_lower = row["File"].lower()
            path_lower = row["Relative Path"].lower()

            if any(
                pattern in filename_lower
                or pattern in path_lower
                for pattern in name_patterns
            ):
                DATASET_FILE_REGISTRY[dataset_name].append(
                    row["Absolute Path"]
                )

# ------------------------------------------------------------------------------
# Display Dataset Candidates
# ------------------------------------------------------------------------------

for dataset_name, files in DATASET_FILE_REGISTRY.items():

    print(f"\n{dataset_name}")

    if files:
        for file_path in files:
            print(f"  ✓ {file_path}")
    else:
        print("  ✗ No candidate dataset file found")

print("\n" + "=" * 100)
print("PART B8 — DATASET FILE DISCOVERY COMPLETED")
print("=" * 100)

====================================================================================================
PART B8 — IDENTIFYING DATASET FILES
====================================================================================================

adult_income
  ✓ /content/drive/MyDrive/SPP_GAN_Project/data/synthetic/dp_ctgan/csv/Adult Income_dp_ctgan.csv
  ✓ /content/drive/MyDrive/SPP_GAN_Project/datasets/clean/adult_income_clean.csv
  ✓ /content/drive/MyDrive/SPP_GAN_Project/datasets/deduplicated/adult_income_deduplicated.csv
  ✓ /content/drive/MyDrive/SPP_GAN_Project/datasets/encoded/adult_income_encoded.csv
  ✓ /content/drive/MyDrive/SPP_GAN_Project/datasets/intermediate/adult_income_imputed.csv
  ✓ /content/drive/MyDrive/SPP_GAN_Project/datasets/outlier_treated/adult_income_outlier_treated.csv
  ✓ /content/drive/MyDrive/SPP_GAN_Project/datasets/processed/adult_income_processed.csv
  ✓ /content/drive/MyDrive/SPP_GAN_Project/datasets/raw/adult_income.csv
  ✓ /content/drive/MyDrive/SPP_GAN_Project/datasets/scaled/adult_income_scaled.csv
  ✓ /content/drive/MyDrive/SPP_GAN_Project/datasets/splits/adult_income/test.csv
  ✓ /content/drive/MyDrive/SPP_GAN_Project/datasets/splits/adult_income/train.csv
  ✓ /content/drive/MyDrive/SPP_GAN_Project/datasets/splits/adult_income/validation.csv
  ✓ /content/drive/MyDrive/SPP_GAN_Project/datasets/synthetic/CTGAN/adult_income_synthetic.csv
  ✓ /content/drive/MyDrive/SPP_GAN_Project/datasets/synthetic/TVAE/adult_income_synthetic.csv
  ✓ /content/drive/MyDrive/SPP_GAN_Project/datasets/synthetic/adult_income_gaussian_copula.csv
  ✓ /content/drive/MyDrive/SPP_GAN_Project/datasets/synthetic/gaussian_copula/adult_income_gaussian_copula.csv
  ✓ /content/drive/MyDrive/SPP_GAN_Project/datasets/synthetic/gaussian_copula/adult_income_synthetic.csv
  ✓ /content/drive/MyDrive/SPP_GAN_Project/datasets/synthetic/gaussian_multivariate/adult_income_synthetic.csv
  ✓ /content/drive/MyDrive/SPP_GAN_Project/evaluation/dp_ctgan/training_history/Adult Income_dp_ctgan_training_history.csv
  ✓ /content/drive/MyDrive/SPP_GAN_Project/evaluation/dp_ctgan/training_history/Adult Income_training_history.csv
  ✓ /content/drive/MyDrive/SPP_GAN_Project/reports/CTGAN_Evaluation/adult_income_column_missing_report.csv
  ✓ /content/drive/MyDrive/SPP_GAN_Project/reports/CTGAN_Evaluation/adult_income_missing_report.csv
  ✓ /content/drive/MyDrive/SPP_GAN_Project/reports/CTGAN_Evaluation/descriptive_statistics/adult_income_descriptive_statistics.csv
  ✓ /content/drive/MyDrive/SPP_GAN_Project/reports/CTGAN_Evaluation/descriptive_statistics/adult_income_statistics.csv
  ✓ /content/drive/MyDrive/SPP_GAN_Project/reports/CTGAN_Evaluation/distribution_similarity/correlation/difference/adult_income/pearson_difference_matrix.csv
  ✓ /content/drive/MyDrive/SPP_GAN_Project/reports/CTGAN_Evaluation/distribution_similarity/correlation/difference/adult_income/spearman_difference_matrix.csv
  ✓ /content/drive/MyDrive/SPP_GAN_Project/reports/CTGAN_Evaluation/distribution_similarity/correlation/feature_pairs/adult_income/highly_correlated_feature_pairs.csv
  ✓ /content/drive/MyDrive/SPP_GAN_Project/reports/CTGAN_Evaluation/distribution_similarity/correlation/highly_correlated_pairs/adult_income/highly_correlated_feature_pairs.csv
  ✓ /content/drive/MyDrive/SPP_GAN_Project/reports/CTGAN_Evaluation/distribution_similarity/correlation/pearson/adult_income_pearson_difference.csv
  ✓ /content/drive/MyDrive/SPP_GAN_Project/reports/CTGAN_Evaluation/distribution_similarity/correlation/pearson/adult_income_pearson_real.csv
  ✓ /content/drive/MyDrive/SPP_GAN_Project/reports/CTGAN_Evaluation/distribution_similarity/correlation/pearson/adult_income_pearson_synthetic.csv
  ✓ /content/drive/MyDrive/SPP_GAN_Project/reports/CTGAN_Evaluation/distribution_similarity/correlation/spearman/adult_income_spearman_difference.csv
  ✓ /content/drive/MyDrive/SPP_GAN_Project/reports/CTGAN_Evaluation/distribution_similarity/correlation/spearman/adult_income_spearman_real.csv
  ✓ /content/drive/MyDrive/SPP_GAN_Project/reports/CTGAN_Evaluation/distribution_similarity/correlation/spearman/adult_income_spearman_synthetic.csv
  ✓ /content/drive/MyDrive/SPP_GAN_Project/reports/CTGAN_Evaluation/distribution_similarity/correlation_evaluation/difference_matrices/adult_income_pearson_difference_matrix.csv
  ✓ /content/drive/MyDrive/SPP_GAN_Project/reports/CTGAN_Evaluation/distribution_similarity/correlation_evaluation/difference_matrices/adult_income_spearman_difference_matrix.csv
  ✓ /content/drive/MyDrive/SPP_GAN_Project/reports/CTGAN_Evaluation/distribution_similarity/correlation_evaluation/pearson/adult_income_difference.csv
  ✓ /content/drive/MyDrive/SPP_GAN_Project/reports/CTGAN_Evaluation/distribution_similarity/correlation_evaluation/pearson/adult_income_real.csv
  ✓ /content/drive/MyDrive/SPP_GAN_Project/reports/CTGAN_Evaluation/distribution_similarity/correlation_evaluation/pearson/adult_income_synthetic.csv
  ✓ /content/drive/MyDrive/SPP_GAN_Project/reports/CTGAN_Evaluation/distribution_similarity/correlation_evaluation/reports/highly_correlated_pairs/adult_income_pearson_pairs.csv
  ✓ /content/drive/MyDrive/SPP_GAN_Project/reports/CTGAN_Evaluation/distribution_similarity/correlation_evaluation/reports/highly_correlated_pairs/adult_income_spearman_pairs.csv
  ✓ /content/drive/MyDrive/SPP_GAN_Project/reports/CTGAN_Evaluation/distribution_similarity/correlation_evaluation/spearman/adult_income_difference.csv
  ✓ /content/drive/MyDrive/SPP_GAN_Project/reports/CTGAN_Evaluation/distribution_similarity/correlation_evaluation/spearman/adult_income_real.csv
  ✓ /content/drive/MyDrive/SPP_GAN_Project/reports/CTGAN_Evaluation/distribution_similarity/correlation_evaluation/spearman/adult_income_synthetic.csv
  ✓ /content/drive/MyDrive/SPP_GAN_Project/reports/CTGAN_Evaluation/distribution_similarity/jensen_shannon_divergence/adult_income_jensen_shannon_divergence_results.csv
  ✓ /content/drive/MyDrive/SPP_GAN_Project/reports/CTGAN_Evaluation/distribution_similarity/jsd/adult_income_jsd.csv
  ✓ /content/drive/MyDrive/SPP_GAN_Project/reports/CTGAN_Evaluation/distribution_similarity/ks_test/adult_income_kolmogorov_smirnov_results.csv
  ✓ /content/drive/MyDrive/SPP_GAN_Project/reports/CTGAN_Evaluation/distribution_similarity/ks_test/adult_income_ks_report.csv
  ✓ /content/drive/MyDrive/SPP_GAN_Project/reports/CTGAN_Evaluation/distribution_similarity/ks_test/adult_income_ks_results.csv
  ✓ /content/drive/MyDrive/SPP_GAN_Project/reports/CTGAN_Evaluation/distribution_similarity/ks_test/adult_income_ks_test.csv
  ✓ /content/drive/MyDrive/SPP_GAN_Project/reports/CTGAN_Evaluation/distribution_similarity/wasserstein/adult_income_wasserstein.csv
  ✓ /content/drive/MyDrive/SPP_GAN_Project/reports/CTGAN_Evaluation/distribution_similarity/wasserstein/adult_income_wasserstein_distance_results.csv
  ✓ /content/drive/MyDrive/SPP_GAN_Project/reports/CTGAN_Evaluation/machine_learning_utility/classification_reports/adult_income_logistic_regression.csv
  ✓ /content/drive/MyDrive/SPP_GAN_Project/reports/CTGAN_Evaluation/machine_learning_utility/classification_reports/adult_income_random_forest.csv
  ✓ /content/drive/MyDrive/SPP_GAN_Project/reports/CTGAN_Evaluation/machine_learning_utility/classification_reports/adult_income_xgboost.csv
  ✓ /content/drive/MyDrive/SPP_GAN_Project/reports/CTGAN_Evaluation/machine_learning_utility/confusion_matrices/adult_income_logistic_regression.csv
  ✓ /content/drive/MyDrive/SPP_GAN_Project/reports/CTGAN_Evaluation/machine_learning_utility/confusion_matrices/adult_income_random_forest.csv
  ✓ /content/drive/MyDrive/SPP_GAN_Project/reports/CTGAN_Evaluation/machine_learning_utility/confusion_matrices/adult_income_xgboost.csv
  ✓ /content/drive/MyDrive/SPP_GAN_Project/reports/TVAE_Evaluation/TVAE_Missing_Value_Evaluation/adult_income_tvae_column_missing_report.csv
  ✓ /content/drive/MyDrive/SPP_GAN_Project/reports/TVAE_Evaluation/descriptive_statistics/adult_income_descriptive_statistics.csv
  ✓ /content/drive/MyDrive/SPP_GAN_Project/reports/TVAE_Evaluation/distribution_similarity/correlation/highly_correlated_pairs/adult_income/highly_correlated_feature_pairs.csv
  ✓ /content/drive/MyDrive/SPP_GAN_Project/reports/TVAE_Evaluation/distribution_similarity/correlation/pearson/adult_income_pearson_difference.csv
  ✓ /content/drive/MyDrive/SPP_GAN_Project/reports/TVAE_Evaluation/distribution_similarity/correlation/pearson/adult_income_pearson_real.csv
  ✓ /content/drive/MyDrive/SPP_GAN_Project/reports/TVAE_Evaluation/distribution_similarity/correlation/pearson/adult_income_pearson_synthetic.csv
  ✓ /content/drive/MyDrive/SPP_GAN_Project/reports/TVAE_Evaluation/distribution_similarity/correlation/spearman/adult_income_spearman_difference.csv
  ✓ /content/drive/MyDrive/SPP_GAN_Project/reports/TVAE_Evaluation/distribution_similarity/correlation/spearman/adult_income_spearman_real.csv
  ✓ /content/drive/MyDrive/SPP_GAN_Project/reports/TVAE_Evaluation/distribution_similarity/correlation/spearman/adult_income_spearman_synthetic.csv
  ✓ /content/drive/MyDrive/SPP_GAN_Project/reports/TVAE_Evaluation/distribution_similarity/jensen_shannon_divergence/adult_income_jensen_shannon_divergence_results.csv
  ✓ /content/drive/MyDrive/SPP_GAN_Project/reports/TVAE_Evaluation/distribution_similarity/ks_test/adult_income_kolmogorov_smirnov_results.csv
  ✓ /content/drive/MyDrive/SPP_GAN_Project/reports/TVAE_Evaluation/distribution_similarity/ks_test/adult_income_ks_report.csv
  ✓ /content/drive/MyDrive/SPP_GAN_Project/reports/TVAE_Evaluation/distribution_similarity/wasserstein/adult_income_wasserstein_distance_results.csv
  ✓ /content/drive/MyDrive/SPP_GAN_Project/reports/TVAE_Evaluation/machine_learning_utility/TVAE_TSTR/classification_reports/adult_income_logistic_regression.csv
  ✓ /content/drive/MyDrive/SPP_GAN_Project/reports/TVAE_Evaluation/machine_learning_utility/TVAE_TSTR/classification_reports/adult_income_random_forest.csv
  ✓ /content/drive/MyDrive/SPP_GAN_Project/reports/TVAE_Evaluation/machine_learning_utility/TVAE_TSTR/classification_reports/adult_income_xgboost.csv
  ✓ /content/drive/MyDrive/SPP_GAN_Project/reports/TVAE_Evaluation/machine_learning_utility/TVAE_TSTR/confusion_matrices/adult_income_logistic_regression.csv
  ✓ /content/drive/MyDrive/SPP_GAN_Project/reports/TVAE_Evaluation/machine_learning_utility/TVAE_TSTR/confusion_matrices/adult_income_random_forest.csv
  ✓ /content/drive/MyDrive/SPP_GAN_Project/reports/TVAE_Evaluation/machine_learning_utility/TVAE_TSTR/confusion_matrices/adult_income_xgboost.csv
  ✓ /content/drive/MyDrive/SPP_GAN_Project/reports/TVAE_Evaluation/machine_learning_utility/classification_reports/adult_income_logistic_regression.csv
  ✓ /content/drive/MyDrive/SPP_GAN_Project/reports/TVAE_Evaluation/machine_learning_utility/classification_reports/adult_income_random_forest.csv
  ✓ /content/drive/MyDrive/SPP_GAN_Project/reports/TVAE_Evaluation/machine_learning_utility/classification_reports/adult_income_xgboost.csv
  ✓ /content/drive/MyDrive/SPP_GAN_Project/reports/TVAE_Evaluation/machine_learning_utility/confusion_matrices/adult_income_logistic_regression.csv
  ✓ /content/drive/MyDrive/SPP_GAN_Project/reports/TVAE_Evaluation/machine_learning_utility/confusion_matrices/adult_income_random_forest.csv
  ✓ /content/drive/MyDrive/SPP_GAN_Project/reports/TVAE_Evaluation/machine_learning_utility/confusion_matrices/adult_income_xgboost.csv
  ✓ /content/drive/MyDrive/SPP_GAN_Project/reports/adult_income_categorical_imputation.csv
  ✓ /content/drive/MyDrive/SPP_GAN_Project/reports/adult_income_categorical_summary.csv
  ✓ /content/drive/MyDrive/SPP_GAN_Project/reports/adult_income_correlation_matrix.csv
  ✓ /content/drive/MyDrive/SPP_GAN_Project/reports/adult_income_descriptive_statistics.csv
  ✓ /content/drive/MyDrive/SPP_GAN_Project/reports/adult_income_duplicate_records.csv
  ✓ /content/drive/MyDrive/SPP_GAN_Project/reports/adult_income_duplicates.csv
  ✓ /content/drive/MyDrive/SPP_GAN_Project/reports/adult_income_missing_values.csv
  ✓ /content/drive/MyDrive/SPP_GAN_Project/reports/adult_income_numerical_imputation.csv
  ✓ /content/drive/MyDrive/SPP_GAN_Project/reports/adult_income_numerical_summary.csv
  ✓ /content/drive/MyDrive/SPP_GAN_Project/reports/adult_income_outlier_details.csv
  ✓ /content/drive/MyDrive/SPP_GAN_Project/reports/adult_income_pearson_matrix.csv
  ✓ /content/drive/MyDrive/SPP_GAN_Project/reports/adult_income_spearman_matrix.csv
  ✓ /content/drive/MyDrive/SPP_GAN_Project/reports/correlation_analysis/adult_income_pearson.csv
  ✓ /content/drive/MyDrive/SPP_GAN_Project/reports/correlation_analysis/adult_income_spearman.csv
  ✓ /content/drive/MyDrive/SPP_GAN_Project/reports/dependency_analysis/adult_income_chi_square.csv
  ✓ /content/drive/MyDrive/SPP_GAN_Project/reports/dependency_analysis/adult_income_covariance.csv
  ✓ /content/drive/MyDrive/SPP_GAN_Project/reports/dependency_analysis/adult_income_covariance_matrix.csv
  ✓ /content/drive/MyDrive/SPP_GAN_Project/reports/dependency_analysis/adult_income_cramers_v.csv
  ✓ /content/drive/MyDrive/SPP_GAN_Project/reports/dependency_analysis/adult_income_mutual_information.csv
  ✓ /content/drive/MyDrive/SPP_GAN_Project/reports/statistical_analysis/adult_income_categorical_summary.csv
  ✓ /content/drive/MyDrive/SPP_GAN_Project/reports/statistical_analysis/adult_income_numerical_summary.csv
  ✓ /content/drive/MyDrive/SPP_GAN_Project/results/TVAE/adult_income_tvae_synthetic.csv
  ✓ /content/drive/MyDrive/SPP_GAN_Project/results/TVAE/synthetic_data/adult_income_synthetic.csv
  ✓ /content/drive/MyDrive/SPP_GAN_Project/synthetic_data/TVAE/adult_income_TVAE_synthetic.csv

bank_marketing
  ✓ /content/drive/MyDrive/SPP_GAN_Project/data/synthetic/dp_ctgan/csv/Bank Marketing_dp_ctgan.csv
  ✓ /content/drive/MyDrive/SPP_GAN_Project/datasets/clean/bank_marketing_clean.csv
  ✓ /content/drive/MyDrive/SPP_GAN_Project/datasets/deduplicated/bank_marketing_deduplicated.csv
  ✓ /content/drive/MyDrive/SPP_GAN_Project/datasets/encoded/bank_marketing_encoded.csv
  ✓ /content/drive/MyDrive/SPP_GAN_Project/datasets/intermediate/bank_marketing_imputed.csv
  ✓ /content/drive/MyDrive/SPP_GAN_Project/datasets/outlier_treated/bank_marketing_outlier_treated.csv
  ✓ /content/drive/MyDrive/SPP_GAN_Project/datasets/processed/bank_marketing_processed.csv
  ✓ /content/drive/MyDrive/SPP_GAN_Project/datasets/raw/bank_marketing.csv
  ✓ /content/drive/MyDrive/SPP_GAN_Project/datasets/scaled/bank_marketing_scaled.csv
  ✓ /content/drive/MyDrive/SPP_GAN_Project/datasets/splits/bank_marketing/test.csv
  ✓ /content/drive/MyDrive/SPP_GAN_Project/datasets/splits/bank_marketing/train.csv
  ✓ /content/drive/MyDrive/SPP_GAN_Project/datasets/splits/bank_marketing/validation.csv
  ✓ /content/drive/MyDrive/SPP_GAN_Project/datasets/synthetic/CTGAN/bank_marketing_synthetic.csv
  ✓ /content/drive/MyDrive/SPP_GAN_Project/datasets/synthetic/TVAE/bank_marketing_synthetic.csv
  ✓ /content/drive/MyDrive/SPP_GAN_Project/datasets/synthetic/bank_marketing_gaussian_copula.csv
  ✓ /content/drive/MyDrive/SPP_GAN_Project/datasets/synthetic/gaussian_copula/bank_marketing_gaussian_copula.csv
  ✓ /content/drive/MyDrive/SPP_GAN_Project/datasets/synthetic/gaussian_copula/bank_marketing_synthetic.csv
  ✓ /content/drive/MyDrive/SPP_GAN_Project/datasets/synthetic/gaussian_multivariate/bank_marketing_synthetic.csv
  ✓ /content/drive/MyDrive/SPP_GAN_Project/evaluation/dp_ctgan/training_history/Bank Marketing_dp_ctgan_training_history.csv
  ✓ /content/drive/MyDrive/SPP_GAN_Project/evaluation/dp_ctgan/training_history/Bank Marketing_training_history.csv
  ✓ /content/drive/MyDrive/SPP_GAN_Project/reports/CTGAN_Evaluation/bank_marketing_column_missing_report.csv
  ✓ /content/drive/MyDrive/SPP_GAN_Project/reports/CTGAN_Evaluation/bank_marketing_missing_report.csv
  ✓ /content/drive/MyDrive/SPP_GAN_Project/reports/CTGAN_Evaluation/descriptive_statistics/bank_marketing_descriptive_statistics.csv
  ✓ /content/drive/MyDrive/SPP_GAN_Project/reports/CTGAN_Evaluation/descriptive_statistics/bank_marketing_statistics.csv
  ✓ /content/drive/MyDrive/SPP_GAN_Project/reports/CTGAN_Evaluation/distribution_similarity/correlation/difference/bank_marketing/pearson_difference_matrix.csv
  ✓ /content/drive/MyDrive/SPP_GAN_Project/reports/CTGAN_Evaluation/distribution_similarity/correlation/difference/bank_marketing/spearman_difference_matrix.csv
  ✓ /content/drive/MyDrive/SPP_GAN_Project/reports/CTGAN_Evaluation/distribution_similarity/correlation/feature_pairs/bank_marketing/highly_correlated_feature_pairs.csv
  ✓ /content/drive/MyDrive/SPP_GAN_Project/reports/CTGAN_Evaluation/distribution_similarity/correlation/highly_correlated_pairs/bank_marketing/highly_correlated_feature_pairs.csv
  ✓ /content/drive/MyDrive/SPP_GAN_Project/reports/CTGAN_Evaluation/distribution_similarity/correlation/pearson/bank_marketing_pearson_difference.csv
  ✓ /content/drive/MyDrive/SPP_GAN_Project/reports/CTGAN_Evaluation/distribution_similarity/correlation/pearson/bank_marketing_pearson_real.csv
  ✓ /content/drive/MyDrive/SPP_GAN_Project/reports/CTGAN_Evaluation/distribution_similarity/correlation/pearson/bank_marketing_pearson_synthetic.csv
  ✓ /content/drive/MyDrive/SPP_GAN_Project/reports/CTGAN_Evaluation/distribution_similarity/correlation/spearman/bank_marketing_spearman_difference.csv
  ✓ /content/drive/MyDrive/SPP_GAN_Project/reports/CTGAN_Evaluation/distribution_similarity/correlation/spearman/bank_marketing_spearman_real.csv
  ✓ /content/drive/MyDrive/SPP_GAN_Project/reports/CTGAN_Evaluation/distribution_similarity/correlation/spearman/bank_marketing_spearman_synthetic.csv
  ✓ /content/drive/MyDrive/SPP_GAN_Project/reports/CTGAN_Evaluation/distribution_similarity/correlation_evaluation/difference_matrices/bank_marketing_pearson_difference_matrix.csv
  ✓ /content/drive/MyDrive/SPP_GAN_Project/reports/CTGAN_Evaluation/distribution_similarity/correlation_evaluation/difference_matrices/bank_marketing_spearman_difference_matrix.csv
  ✓ /content/drive/MyDrive/SPP_GAN_Project/reports/CTGAN_Evaluation/distribution_similarity/correlation_evaluation/pearson/bank_marketing_difference.csv
  ✓ /content/drive/MyDrive/SPP_GAN_Project/reports/CTGAN_Evaluation/distribution_similarity/correlation_evaluation/pearson/bank_marketing_real.csv
  ✓ /content/drive/MyDrive/SPP_GAN_Project/reports/CTGAN_Evaluation/distribution_similarity/correlation_evaluation/pearson/bank_marketing_synthetic.csv
  ✓ /content/drive/MyDrive/SPP_GAN_Project/reports/CTGAN_Evaluation/distribution_similarity/correlation_evaluation/reports/highly_correlated_pairs/bank_marketing_pearson_pairs.csv
  ✓ /content/drive/MyDrive/SPP_GAN_Project/reports/CTGAN_Evaluation/distribution_similarity/correlation_evaluation/reports/highly_correlated_pairs/bank_marketing_spearman_pairs.csv
  ✓ /content/drive/MyDrive/SPP_GAN_Project/reports/CTGAN_Evaluation/distribution_similarity/correlation_evaluation/spearman/bank_marketing_difference.csv
  ✓ /content/drive/MyDrive/SPP_GAN_Project/reports/CTGAN_Evaluation/distribution_similarity/correlation_evaluation/spearman/bank_marketing_real.csv
  ✓ /content/drive/MyDrive/SPP_GAN_Project/reports/CTGAN_Evaluation/distribution_similarity/correlation_evaluation/spearman/bank_marketing_synthetic.csv
  ✓ /content/drive/MyDrive/SPP_GAN_Project/reports/CTGAN_Evaluation/distribution_similarity/jensen_shannon_divergence/bank_marketing_jensen_shannon_divergence_results.csv
  ✓ /content/drive/MyDrive/SPP_GAN_Project/reports/CTGAN_Evaluation/distribution_similarity/jsd/bank_marketing_jsd.csv
  ✓ /content/drive/MyDrive/SPP_GAN_Project/reports/CTGAN_Evaluation/distribution_similarity/ks_test/bank_marketing_kolmogorov_smirnov_results.csv
  ✓ /content/drive/MyDrive/SPP_GAN_Project/reports/CTGAN_Evaluation/distribution_similarity/ks_test/bank_marketing_ks_report.csv
  ✓ /content/drive/MyDrive/SPP_GAN_Project/reports/CTGAN_Evaluation/distribution_similarity/ks_test/bank_marketing_ks_results.csv

In [54]:
# ==============================================================================
# PART B9 — VALIDATE REQUIRED RESEARCH INPUTS
# ==============================================================================

print("=" * 100)
print("PART B9 — VALIDATING REQUIRED RESEARCH INPUTS")
print("=" * 100)

INPUT_VALIDATION_RESULTS = []

# ------------------------------------------------------------------------------
# Project Root
# ------------------------------------------------------------------------------

INPUT_VALIDATION_RESULTS.append({
    "Input": "Project Root",
    "Path": str(PROJECT_ROOT),
    "Exists": PROJECT_ROOT.exists(),
    "Required": True
})

# ------------------------------------------------------------------------------
# Dataset Validation
# ------------------------------------------------------------------------------

for dataset_name in DATASETS:

    candidate_files = DATASET_FILE_REGISTRY.get(
        dataset_name,
        []
    )

    INPUT_VALIDATION_RESULTS.append({
        "Input": f"{dataset_name} dataset",
        "Path": (
            candidate_files[0]
            if candidate_files
            else "NOT FOUND"
        ),
        "Exists": bool(candidate_files),
        "Required": True
    })

# ------------------------------------------------------------------------------
# Create Validation DataFrame
# ------------------------------------------------------------------------------

INPUT_VALIDATION_DF = pd.DataFrame(
    INPUT_VALIDATION_RESULTS
)

display(INPUT_VALIDATION_DF)

# ------------------------------------------------------------------------------
# Critical Validation
# ------------------------------------------------------------------------------

missing_required_inputs = INPUT_VALIDATION_DF[
    (
        INPUT_VALIDATION_DF["Required"]
        &
        ~INPUT_VALIDATION_DF["Exists"]
    )
]

if not missing_required_inputs.empty:

    print(
        "\nWARNING — Some required inputs have not yet been resolved:"
    )

    for input_name in missing_required_inputs["Input"]:
        print(f"  • {input_name}")

    print(
        "\nDo not continue to model evaluation until the actual "
        "research artifact locations are confirmed."
    )

else:

    print(
        "\nAll currently defined required research inputs were found."
    )

print("\n" + "=" * 100)
print("PART B9 — INPUT VALIDATION COMPLETED")
print("=" * 100)

====================================================================================================
PART B9 — VALIDATING REQUIRED RESEARCH INPUTS
====================================================================================================

,Input,Path,Exists,Required
0,Project Root,/content/drive/MyDrive/SPP_GAN_Project,True,True
1,adult_income dataset,/content/drive/MyDrive/SPP_GAN_Project/data/sy...,True,True
2,bank_marketing dataset,/content/drive/MyDrive/SPP_GAN_Project/data/sy...,True,True
3,diabetes_130us dataset,/content/drive/MyDrive/SPP_GAN_Project/data/sy...,True,True

All currently defined required research inputs were found.

====================================================================================================
PART B9 — INPUT VALIDATION COMPLETED
====================================================================================================

In [55]:
# ==============================================================================
# PART B10 — INITIALIZE COMPARATIVE EVALUATION REGISTRIES
# ==============================================================================

print("=" * 100)
print("PART B10 — INITIALIZING COMPARATIVE EVALUATION REGISTRIES")
print("=" * 100)

# ------------------------------------------------------------------------------
# Real Reference Data
# ------------------------------------------------------------------------------

REAL_DATASETS = {}

# ------------------------------------------------------------------------------
# Synthetic Data
# ------------------------------------------------------------------------------

SYNTHETIC_DATASETS = {
    dataset: {
        model: None
        for model in MODELS
    }
    for dataset in DATASETS
}

# ------------------------------------------------------------------------------
# Dataset Metadata
# ------------------------------------------------------------------------------

DATASET_METADATA = {}

# ------------------------------------------------------------------------------
# Evaluation Results
# ------------------------------------------------------------------------------

STRUCTURAL_RESULTS = []
NUMERICAL_FIDELITY_RESULTS = []
CATEGORICAL_FIDELITY_RESULTS = []
CORRELATION_RESULTS = []
SDMETRICS_RESULTS = []
UTILITY_RESULTS = []
PRIVACY_RESULTS = []
STATISTICAL_TEST_RESULTS = []

# ------------------------------------------------------------------------------
# Unified Results
# ------------------------------------------------------------------------------

COMPARATIVE_RESULTS = []

# ------------------------------------------------------------------------------
# Ranking Results
# ------------------------------------------------------------------------------

MODEL_RANKING_RESULTS = []

print(f"Real Dataset Registry      : {len(REAL_DATASETS)} entries")
print(f"Synthetic Dataset Registry : {len(SYNTHETIC_DATASETS)} datasets")
print(f"Models per Dataset         : {len(MODELS)}")

print("\nEvaluation registries initialized:")
print("  • Structural")
print("  • Numerical Fidelity")
print("  • Categorical Fidelity")
print("  • Correlation")
print("  • SDMetrics")
print("  • Utility")
print("  • Privacy")
print("  • Statistical Tests")
print("  • Comparative Results")
print("  • Model Ranking")

print("\n" + "=" * 100)
print("PART B10 — COMPARATIVE EVALUATION REGISTRIES INITIALIZED")
print("=" * 100)

====================================================================================================
PART B10 — INITIALIZING COMPARATIVE EVALUATION REGISTRIES
====================================================================================================
Real Dataset Registry      : 0 entries
Synthetic Dataset Registry : 3 datasets
Models per Dataset         : 5

Evaluation registries initialized:
  • Structural
  • Numerical Fidelity
  • Categorical Fidelity
  • Correlation
  • SDMetrics
  • Utility
  • Privacy
  • Statistical Tests
  • Comparative Results
  • Model Ranking

====================================================================================================
PART B10 — COMPARATIVE EVALUATION REGISTRIES INITIALIZED
====================================================================================================

In [56]:
# ==============================================================================
# PART B11 — RESEARCH PIPELINE INTEGRATION SUMMARY
# ==============================================================================

print("=" * 100)
print("PART B11 — RESEARCH PIPELINE INTEGRATION SUMMARY")
print("=" * 100)

PIPELINE_SUMMARY = pd.DataFrame([
    {
        "Notebook": "Notebook 02",
        "Component": "Preprocessing",
        "Role": "Real Reference Data and Metadata",
        "Required": True
    },
    {
        "Notebook": "Notebook 03",
        "Component": "Statistical Module",
        "Role": "Statistical Synthetic Data Baselines",
        "Required": True
    },
    {
        "Notebook": "Notebook 04",
        "Component": "CTGAN",
        "Role": "Deep Generative Baseline",
        "Required": True
    },
    {
        "Notebook": "Notebook 05",
        "Component": "TVAE",
        "Role": "Deep Generative Baseline",
        "Required": True
    },
    {
        "Notebook": "Notebook 06",
        "Component": "DP-CTGAN",
        "Role": "Differentially Private Baseline",
        "Required": True
    },
    {
        "Notebook": "Notebook 07",
        "Component": "SPP-GAN",
        "Role": "Proposed Framework",
        "Required": True
    },
    {
        "Notebook": "Notebook 08",
        "Component": "Comparative Evaluation",
        "Role": "Unified Evaluation and Research Evidence",
        "Required": True
    }
])

display(PIPELINE_SUMMARY)

print("\n" + "=" * 100)
print("PART B11 — RESEARCH PIPELINE INTEGRATION CONFIGURED")
print("=" * 100)

====================================================================================================
PART B11 — RESEARCH PIPELINE INTEGRATION SUMMARY
====================================================================================================

,Notebook,Component,Role,Required
0,Notebook 02,Preprocessing,Real Reference Data and Metadata,True
1,Notebook 03,Statistical Module,Statistical Synthetic Data Baselines,True
2,Notebook 04,CTGAN,Deep Generative Baseline,True
3,Notebook 05,TVAE,Deep Generative Baseline,True
4,Notebook 06,DP-CTGAN,Differentially Private Baseline,True
5,Notebook 07,SPP-GAN,Proposed Framework,True
6,Notebook 08,Comparative Evaluation,Unified Evaluation and Research Evidence,True

====================================================================================================
PART B11 — RESEARCH PIPELINE INTEGRATION CONFIGURED
====================================================================================================

In [57]:
# ==============================================================================
# PART C1 — DISCOVER REFERENCE DATASET FILES
# ==============================================================================

print("=" * 100)
print("PART C1 — DISCOVERING REAL REFERENCE DATASET FILES")
print("=" * 100)

# ------------------------------------------------------------------------------
# Expected Dataset Naming Patterns
# ------------------------------------------------------------------------------

REFERENCE_DATASET_PATTERNS = {
    "adult_income": [
        "adult_income",
        "adult-income",
        "adult income"
    ],
    "bank_marketing": [
        "bank_marketing",
        "bank-marketing",
        "bank marketing"
    ],
    "diabetes_130us": [
        "diabetes_130us",
        "diabetes-130us",
        "diabetes 130us",
        "diabetes"
    ]
}

# ------------------------------------------------------------------------------
# Search Locations
# ------------------------------------------------------------------------------

REFERENCE_SEARCH_DIRECTORIES = [
    DATA_DIRECTORY
]

if PROCESSED_DATA_DIRECTORY is not None:
    REFERENCE_SEARCH_DIRECTORIES.append(
        PROCESSED_DATA_DIRECTORY
    )

# Include project-level CSV files if required
REFERENCE_SEARCH_DIRECTORIES.append(
    PROJECT_ROOT
)

# Remove duplicates while preserving order
REFERENCE_SEARCH_DIRECTORIES = list(
    dict.fromkeys(
        REFERENCE_SEARCH_DIRECTORIES
    )
)

# ------------------------------------------------------------------------------
# Discover CSV Files
# ------------------------------------------------------------------------------

REFERENCE_DATASET_CANDIDATES = {
    dataset: []
    for dataset in DATASETS
}

for search_directory in REFERENCE_SEARCH_DIRECTORIES:

    if not search_directory.exists():
        continue

    for file_path in search_directory.rglob("*.csv"):

        file_name = file_path.name.lower()
        relative_path = str(
            file_path.relative_to(PROJECT_ROOT)
        ).lower()

        for dataset_name, patterns in (
            REFERENCE_DATASET_PATTERNS.items()
        ):

            if any(
                pattern in file_name
                or pattern in relative_path
                for pattern in patterns
            ):

                if str(file_path) not in (
                    REFERENCE_DATASET_CANDIDATES[
                        dataset_name
                    ]
                ):

                    REFERENCE_DATASET_CANDIDATES[
                        dataset_name
                    ].append(
                        str(file_path)
                    )

# ------------------------------------------------------------------------------
# Display Candidates
# ------------------------------------------------------------------------------

for dataset_name, candidates in (
    REFERENCE_DATASET_CANDIDATES.items()
):

    print(f"\n{dataset_name}")

    if candidates:

        for candidate in candidates:
            print(f"  ✓ {candidate}")

    else:

        print("  ✗ No reference dataset candidate found")

print("\n" + "=" * 100)
print("PART C1 — REFERENCE DATASET DISCOVERY COMPLETED")
print("=" * 100)

====================================================================================================
PART C1 — DISCOVERING REAL REFERENCE DATASET FILES
====================================================================================================

adult_income
  ✓ /content/drive/MyDrive/SPP_GAN_Project/data/synthetic/dp_ctgan/csv/Adult Income_dp_ctgan.csv
  ✓ /content/drive/MyDrive/SPP_GAN_Project/reports/adult_income_missing_values.csv
  ✓ /content/drive/MyDrive/SPP_GAN_Project/reports/adult_income_duplicates.csv
  ✓ /content/drive/MyDrive/SPP_GAN_Project/reports/adult_income_descriptive_statistics.csv
  ✓ /content/drive/MyDrive/SPP_GAN_Project/reports/adult_income_pearson_matrix.csv
  ✓ /content/drive/MyDrive/SPP_GAN_Project/reports/adult_income_spearman_matrix.csv
  ✓ /content/drive/MyDrive/SPP_GAN_Project/reports/adult_income_numerical_summary.csv
  ✓ /content/drive/MyDrive/SPP_GAN_Project/reports/adult_income_categorical_summary.csv
  ✓ /content/drive/MyDrive/SPP_GAN_Project/reports/adult_income_correlation_matrix.csv
  ✓ /content/drive/MyDrive/SPP_GAN_Project/reports/adult_income_numerical_imputation.csv
  ✓ /content/drive/MyDrive/SPP_GAN_Project/reports/adult_income_categorical_imputation.csv
  ✓ /content/drive/MyDrive/SPP_GAN_Project/reports/adult_income_duplicate_records.csv
  ✓ /content/drive/MyDrive/SPP_GAN_Project/reports/adult_income_outlier_details.csv
  ✓ /content/drive/MyDrive/SPP_GAN_Project/datasets/processed/adult_income_processed.csv
  ✓ /content/drive/MyDrive/SPP_GAN_Project/datasets/raw/adult_income.csv
  ✓ /content/drive/MyDrive/SPP_GAN_Project/datasets/synthetic/adult_income_gaussian_copula.csv
  ✓ /content/drive/MyDrive/SPP_GAN_Project/datasets/intermediate/adult_income_imputed.csv
  ✓ /content/drive/MyDrive/SPP_GAN_Project/datasets/deduplicated/adult_income_deduplicated.csv
  ✓ /content/drive/MyDrive/SPP_GAN_Project/datasets/clean/adult_income_clean.csv
  ✓ /content/drive/MyDrive/SPP_GAN_Project/datasets/outlier_treated/adult_income_outlier_treated.csv
  ✓ /content/drive/MyDrive/SPP_GAN_Project/datasets/encoded/adult_income_encoded.csv
  ✓ /content/drive/MyDrive/SPP_GAN_Project/datasets/scaled/adult_income_scaled.csv
  ✓ /content/drive/MyDrive/SPP_GAN_Project/datasets/synthetic/gaussian_multivariate/adult_income_synthetic.csv
  ✓ /content/drive/MyDrive/SPP_GAN_Project/datasets/synthetic/gaussian_copula/adult_income_gaussian_copula.csv
  ✓ /content/drive/MyDrive/SPP_GAN_Project/datasets/synthetic/gaussian_copula/adult_income_synthetic.csv
  ✓ /content/drive/MyDrive/SPP_GAN_Project/datasets/synthetic/CTGAN/adult_income_synthetic.csv
  ✓ /content/drive/MyDrive/SPP_GAN_Project/datasets/synthetic/TVAE/adult_income_synthetic.csv
  ✓ /content/drive/MyDrive/SPP_GAN_Project/datasets/splits/adult_income/test.csv
  ✓ /content/drive/MyDrive/SPP_GAN_Project/datasets/splits/adult_income/validation.csv
  ✓ /content/drive/MyDrive/SPP_GAN_Project/datasets/splits/adult_income/train.csv
  ✓ /content/drive/MyDrive/SPP_GAN_Project/synthetic_data/TVAE/adult_income_TVAE_synthetic.csv
  ✓ /content/drive/MyDrive/SPP_GAN_Project/results/TVAE/adult_income_tvae_synthetic.csv
  ✓ /content/drive/MyDrive/SPP_GAN_Project/results/TVAE/synthetic_data/adult_income_synthetic.csv
  ✓ /content/drive/MyDrive/SPP_GAN_Project/reports/statistical_analysis/adult_income_numerical_summary.csv
  ✓ /content/drive/MyDrive/SPP_GAN_Project/reports/statistical_analysis/adult_income_categorical_summary.csv
  ✓ /content/drive/MyDrive/SPP_GAN_Project/reports/correlation_analysis/adult_income_pearson.csv
  ✓ /content/drive/MyDrive/SPP_GAN_Project/reports/correlation_analysis/adult_income_spearman.csv
  ✓ /content/drive/MyDrive/SPP_GAN_Project/reports/dependency_analysis/adult_income_covariance.csv
  ✓ /content/drive/MyDrive/SPP_GAN_Project/reports/dependency_analysis/adult_income_chi_square.csv
  ✓ /content/drive/MyDrive/SPP_GAN_Project/reports/dependency_analysis/adult_income_cramers_v.csv
  ✓ /content/drive/MyDrive/SPP_GAN_Project/reports/dependency_analysis/adult_income_covariance_matrix.csv
  ✓ /content/drive/MyDrive/SPP_GAN_Project/reports/dependency_analysis/adult_income_mutual_information.csv
  ✓ /content/drive/MyDrive/SPP_GAN_Project/reports/CTGAN_Evaluation/adult_income_missing_report.csv
  ✓ /content/drive/MyDrive/SPP_GAN_Project/reports/CTGAN_Evaluation/adult_income_column_missing_report.csv
  ✓ /content/drive/MyDrive/SPP_GAN_Project/reports/CTGAN_Evaluation/descriptive_statistics/adult_income_statistics.csv
  ✓ /content/drive/MyDrive/SPP_GAN_Project/reports/CTGAN_Evaluation/descriptive_statistics/adult_income_descriptive_statistics.csv
  ✓ /content/drive/MyDrive/SPP_GAN_Project/reports/CTGAN_Evaluation/distribution_similarity/ks_test/adult_income_ks_results.csv
  ✓ /content/drive/MyDrive/SPP_GAN_Project/reports/CTGAN_Evaluation/distribution_similarity/ks_test/adult_income_ks_test.csv
  ✓ /content/drive/MyDrive/SPP_GAN_Project/reports/CTGAN_Evaluation/distribution_similarity/ks_test/adult_income_ks_report.csv
  ✓ /content/drive/MyDrive/SPP_GAN_Project/reports/CTGAN_Evaluation/distribution_similarity/ks_test/adult_income_kolmogorov_smirnov_results.csv
  ✓ /content/drive/MyDrive/SPP_GAN_Project/reports/CTGAN_Evaluation/distribution_similarity/wasserstein/adult_income_wasserstein.csv
  ✓ /content/drive/MyDrive/SPP_GAN_Project/reports/CTGAN_Evaluation/distribution_similarity/wasserstein/adult_income_wasserstein_distance_results.csv
  ✓ /content/drive/MyDrive/SPP_GAN_Project/reports/CTGAN_Evaluation/distribution_similarity/jsd/adult_income_jsd.csv
  ✓ /content/drive/MyDrive/SPP_GAN_Project/reports/CTGAN_Evaluation/distribution_similarity/jensen_shannon_divergence/adult_income_jensen_shannon_divergence_results.csv
  ✓ /content/drive/MyDrive/SPP_GAN_Project/reports/CTGAN_Evaluation/distribution_similarity/correlation_evaluation/pearson/adult_income_real.csv
  ✓ /content/drive/MyDrive/SPP_GAN_Project/reports/CTGAN_Evaluation/distribution_similarity/correlation_evaluation/pearson/adult_income_synthetic.csv
  ✓ /content/drive/MyDrive/SPP_GAN_Project/reports/CTGAN_Evaluation/distribution_similarity/correlation_evaluation/pearson/adult_income_difference.csv
  ✓ /content/drive/MyDrive/SPP_GAN_Project/reports/CTGAN_Evaluation/distribution_similarity/correlation_evaluation/spearman/adult_income_real.csv
  ✓ /content/drive/MyDrive/SPP_GAN_Project/reports/CTGAN_Evaluation/distribution_similarity/correlation_evaluation/spearman/adult_income_synthetic.csv
  ✓ /content/drive/MyDrive/SPP_GAN_Project/reports/CTGAN_Evaluation/distribution_similarity/correlation_evaluation/spearman/adult_income_difference.csv
  ✓ /content/drive/MyDrive/SPP_GAN_Project/reports/CTGAN_Evaluation/distribution_similarity/correlation_evaluation/difference_matrices/adult_income_pearson_difference_matrix.csv
  ✓ /content/drive/MyDrive/SPP_GAN_Project/reports/CTGAN_Evaluation/distribution_similarity/correlation_evaluation/difference_matrices/adult_income_spearman_difference_matrix.csv
  ✓ /content/drive/MyDrive/SPP_GAN_Project/reports/CTGAN_Evaluation/distribution_similarity/correlation_evaluation/reports/highly_correlated_pairs/adult_income_pearson_pairs.csv
  ✓ /content/drive/MyDrive/SPP_GAN_Project/reports/CTGAN_Evaluation/distribution_similarity/correlation_evaluation/reports/highly_correlated_pairs/adult_income_spearman_pairs.csv
  ✓ /content/drive/MyDrive/SPP_GAN_Project/reports/CTGAN_Evaluation/distribution_similarity/correlation/pearson/adult_income_pearson_difference.csv
  ✓ /content/drive/MyDrive/SPP_GAN_Project/reports/CTGAN_Evaluation/distribution_similarity/correlation/pearson/adult_income_pearson_synthetic.csv
  ✓ /content/drive/MyDrive/SPP_GAN_Project/reports/CTGAN_Evaluation/distribution_similarity/correlation/pearson/adult_income_pearson_real.csv
  ✓ /content/drive/MyDrive/SPP_GAN_Project/reports/CTGAN_Evaluation/distribution_similarity/correlation/spearman/adult_income_spearman_real.csv
  ✓ /content/drive/MyDrive/SPP_GAN_Project/reports/CTGAN_Evaluation/distribution_similarity/correlation/spearman/adult_income_spearman_synthetic.csv
  ✓ /content/drive/MyDrive/SPP_GAN_Project/reports/CTGAN_Evaluation/distribution_similarity/correlation/spearman/adult_income_spearman_difference.csv
  ✓ /content/drive/MyDrive/SPP_GAN_Project/reports/CTGAN_Evaluation/distribution_similarity/correlation/difference/adult_income/spearman_difference_matrix.csv
  ✓ /content/drive/MyDrive/SPP_GAN_Project/reports/CTGAN_Evaluation/distribution_similarity/correlation/difference/adult_income/pearson_difference_matrix.csv
  ✓ /content/drive/MyDrive/SPP_GAN_Project/reports/CTGAN_Evaluation/distribution_similarity/correlation/feature_pairs/adult_income/highly_correlated_feature_pairs.csv
  ✓ /content/drive/MyDrive/SPP_GAN_Project/reports/CTGAN_Evaluation/distribution_similarity/correlation/highly_correlated_pairs/adult_income/highly_correlated_feature_pairs.csv
  ✓ /content/drive/MyDrive/SPP_GAN_Project/reports/CTGAN_Evaluation/machine_learning_utility/confusion_matrices/adult_income_logistic_regression.csv
  ✓ /content/drive/MyDrive/SPP_GAN_Project/reports/CTGAN_Evaluation/machine_learning_utility/confusion_matrices/adult_income_random_forest.csv
  ✓ /content/drive/MyDrive/SPP_GAN_Project/reports/CTGAN_Evaluation/machine_learning_utility/confusion_matrices/adult_income_xgboost.csv
  ✓ /content/drive/MyDrive/SPP_GAN_Project/reports/CTGAN_Evaluation/machine_learning_utility/classification_reports/adult_income_logistic_regression.csv
  ✓ /content/drive/MyDrive/SPP_GAN_Project/reports/CTGAN_Evaluation/machine_learning_utility/classification_reports/adult_income_random_forest.csv
  ✓ /content/drive/MyDrive/SPP_GAN_Project/reports/CTGAN_Evaluation/machine_learning_utility/classification_reports/adult_income_xgboost.csv
  ✓ /content/drive/MyDrive/SPP_GAN_Project/reports/TVAE_Evaluation/TVAE_Missing_Value_Evaluation/adult_income_tvae_column_missing_report.csv
  ✓ /content/drive/MyDrive/SPP_GAN_Project/reports/TVAE_Evaluation/descriptive_statistics/adult_income_descriptive_statistics.csv
  ✓ /content/drive/MyDrive/SPP_GAN_Project/reports/TVAE_Evaluation/distribution_similarity/ks_test/adult_income_ks_report.csv
  ✓ /content/drive/MyDrive/SPP_GAN_Project/reports/TVAE_Evaluation/distribution_similarity/ks_test/adult_income_kolmogorov_smirnov_results.csv
  ✓ /content/drive/MyDrive/SPP_GAN_Project/reports/TVAE_Evaluation/distribution_similarity/wasserstein/adult_income_wasserstein_distance_results.csv
  ✓ /content/drive/MyDrive/SPP_GAN_Project/reports/TVAE_Evaluation/distribution_similarity/jensen_shannon_divergence/adult_income_jensen_shannon_divergence_results.csv
  ✓ /content/drive/MyDrive/SPP_GAN_Project/reports/TVAE_Evaluation/distribution_similarity/correlation/pearson/adult_income_pearson_real.csv
  ✓ /content/drive/MyDrive/SPP_GAN_Project/reports/TVAE_Evaluation/distribution_similarity/correlation/pearson/adult_income_pearson_synthetic.csv
  ✓ /content/drive/MyDrive/SPP_GAN_Project/reports/TVAE_Evaluation/distribution_similarity/correlation/pearson/adult_income_pearson_difference.csv
  ✓ /content/drive/MyDrive/SPP_GAN_Project/reports/TVAE_Evaluation/distribution_similarity/correlation/spearman/adult_income_spearman_real.csv
  ✓ /content/drive/MyDrive/SPP_GAN_Project/reports/TVAE_Evaluation/distribution_similarity/correlation/spearman/adult_income_spearman_difference.csv
  ✓ /content/drive/MyDrive/SPP_GAN_Project/reports/TVAE_Evaluation/distribution_similarity/correlation/spearman/adult_income_spearman_synthetic.csv
  ✓ /content/drive/MyDrive/SPP_GAN_Project/reports/TVAE_Evaluation/distribution_similarity/correlation/highly_correlated_pairs/adult_income/highly_correlated_feature_pairs.csv
  ✓ /content/drive/MyDrive/SPP_GAN_Project/reports/TVAE_Evaluation/machine_learning_utility/confusion_matrices/adult_income_logistic_regression.csv
  ✓ /content/drive/MyDrive/SPP_GAN_Project/reports/TVAE_Evaluation/machine_learning_utility/confusion_matrices/adult_income_random_forest.csv
  ✓ /content/drive/MyDrive/SPP_GAN_Project/reports/TVAE_Evaluation/machine_learning_utility/confusion_matrices/adult_income_xgboost.csv
  ✓ /content/drive/MyDrive/SPP_GAN_Project/reports/TVAE_Evaluation/machine_learning_utility/classification_reports/adult_income_logistic_regression.csv
  ✓ /content/drive/MyDrive/SPP_GAN_Project/reports/TVAE_Evaluation/machine_learning_utility/classification_reports/adult_income_random_forest.csv
  ✓ /content/drive/MyDrive/SPP_GAN_Project/reports/TVAE_Evaluation/machine_learning_utility/classification_reports/adult_income_xgboost.csv
  ✓ /content/drive/MyDrive/SPP_GAN_Project/reports/TVAE_Evaluation/machine_learning_utility/TVAE_TSTR/confusion_matrices/adult_income_logistic_regression.csv
  ✓ /content/drive/MyDrive/SPP_GAN_Project/reports/TVAE_Evaluation/machine_learning_utility/TVAE_TSTR/confusion_matrices/adult_income_random_forest.csv
  ✓ /content/drive/MyDrive/SPP_GAN_Project/reports/TVAE_Evaluation/machine_learning_utility/TVAE_TSTR/confusion_matrices/adult_income_xgboost.csv
  ✓ /content/drive/MyDrive/SPP_GAN_Project/reports/TVAE_Evaluation/machine_learning_utility/TVAE_TSTR/classification_reports/adult_income_logistic_regression.csv
  ✓ /content/drive/MyDrive/SPP_GAN_Project/reports/TVAE_Evaluation/machine_learning_utility/TVAE_TSTR/classification_reports/adult_income_random_forest.csv
  ✓ /content/drive/MyDrive/SPP_GAN_Project/reports/TVAE_Evaluation/machine_learning_utility/TVAE_TSTR/classification_reports/adult_income_xgboost.csv
  ✓ /content/drive/MyDrive/SPP_GAN_Project/evaluation/dp_ctgan/training_history/Adult Income_dp_ctgan_training_history.csv
  ✓ /content/drive/MyDrive/SPP_GAN_Project/evaluation/dp_ctgan/training_history/Adult Income_training_history.csv

bank_marketing
  ✓ /content/drive/MyDrive/SPP_GAN_Project/data/synthetic/dp_ctgan/csv/Bank Marketing_dp_ctgan.csv
  ✓ /content/drive/MyDrive/SPP_GAN_Project/reports/bank_marketing_missing_values.csv
  ✓ /content/drive/MyDrive/SPP_GAN_Project/reports/bank_marketing_duplicates.csv
  ✓ /content/drive/MyDrive/SPP_GAN_Project/reports/bank_marketing_descriptive_statistics.csv
  ✓ /content/drive/MyDrive/SPP_GAN_Project/reports/bank_marketing_pearson_matrix.csv
  ✓ /content/drive/MyDrive/SPP_GAN_Project/reports/bank_marketing_spearman_matrix.csv
  ✓ /content/drive/MyDrive/SPP_GAN_Project/reports/bank_marketing_numerical_summary.csv
  ✓ /content/drive/MyDrive/SPP_GAN_Project/reports/bank_marketing_categorical_summary.csv
  ✓ /content/drive/MyDrive/SPP_GAN_Project/reports/bank_marketing_correlation_matrix.csv
  ✓ /content/drive/MyDrive/SPP_GAN_Project/reports/bank_marketing_numerical_imputation.csv
  ✓ /content/drive/MyDrive/SPP_GAN_Project/reports/bank_marketing_categorical_imputation.csv
  ✓ /content/drive/MyDrive/SPP_GAN_Project/reports/bank_marketing_outlier_details.csv
  ✓ /content/drive/MyDrive/SPP_GAN_Project/datasets/processed/bank_marketing_processed.csv
  ✓ /content/drive/MyDrive/SPP_GAN_Project/datasets/raw/bank_marketing.csv
  ✓ /content/drive/MyDrive/SPP_GAN_Project/datasets/synthetic/bank_marketing_gaussian_copula.csv
  ✓ /content/drive/MyDrive/SPP_GAN_Project/datasets/intermediate/bank_marketing_imputed.csv
  ✓ /content/drive/MyDrive/SPP_GAN_Project/datasets/deduplicated/bank_marketing_deduplicated.csv
  ✓ /content/drive/MyDrive/SPP_GAN_Project/datasets/clean/bank_marketing_clean.csv
  ✓ /content/drive/MyDrive/SPP_GAN_Project/datasets/outlier_treated/bank_marketing_outlier_treated.csv
  ✓ /content/drive/MyDrive/SPP_GAN_Project/datasets/encoded/bank_marketing_encoded.csv
  ✓ /content/drive/MyDrive/SPP_GAN_Project/datasets/scaled/bank_marketing_scaled.csv
  ✓ /content/drive/MyDrive/SPP_GAN_Project/datasets/synthetic/gaussian_multivariate/bank_marketing_synthetic.csv
  ✓ /content/drive/MyDrive/SPP_GAN_Project/datasets/synthetic/gaussian_copula/bank_marketing_gaussian_copula.csv
  ✓ /content/drive/MyDrive/SPP_GAN_Project/datasets/synthetic/gaussian_copula/bank_marketing_synthetic.csv
  ✓ /content/drive/MyDrive/SPP_GAN_Project/datasets/synthetic/CTGAN/bank_marketing_synthetic.csv
  ✓ /content/drive/MyDrive/SPP_GAN_Project/datasets/synthetic/TVAE/bank_marketing_synthetic.csv
  ✓ /content/drive/MyDrive/SPP_GAN_Project/datasets/splits/bank_marketing/validation.csv
  ✓ /content/drive/MyDrive/SPP_GAN_Project/datasets/splits/bank_marketing/train.csv
  ✓ /content/drive/MyDrive/SPP_GAN_Project/datasets/splits/bank_marketing/test.csv
  ✓ /content/drive/MyDrive/SPP_GAN_Project/synthetic_data/TVAE/bank_marketing_TVAE_synthetic.csv
  ✓ /content/drive/MyDrive/SPP_GAN_Project/results/TVAE/bank_marketing_tvae_synthetic.csv
  ✓ /content/drive/MyDrive/SPP_GAN_Project/results/TVAE/synthetic_data/bank_marketing_synthetic.csv
  ✓ /content/drive/MyDrive/SPP_GAN_Project/reports/statistical_analysis/bank_marketing_numerical_summary.csv
  ✓ /content/drive/MyDrive/SPP_GAN_Project/reports/statistical_analysis/bank_marketing_categorical_summary.csv
  ✓ /content/drive/MyDrive/SPP_GAN_Project/reports/correlation_analysis/bank_marketing_pearson.csv
  ✓ /content/drive/MyDrive/SPP_GAN_Project/reports/correlation_analysis/bank_marketing_spearman.csv
  ✓ /content/drive/MyDrive/SPP_GAN_Project/reports/dependency_analysis/bank_marketing_covariance.csv
  ✓ /content/drive/MyDrive/SPP_GAN_Project/reports/dependency_analysis/bank_marketing_chi_square.csv
  ✓ /content/drive/MyDrive/SPP_GAN_Project/reports/dependency_analysis/bank_marketing_cramers_v.csv
  ✓ /content/drive/MyDrive/SPP_GAN_Project/reports/dependency_analysis/bank_marketing_covariance_matrix.csv
  ✓ /content/drive/MyDrive/SPP_GAN_Project/reports/dependency_analysis/bank_marketing_mutual_information.csv
  ✓ /content/drive/MyDrive/SPP_GAN_Project/reports/CTGAN_Evaluation/bank_marketing_missing_report.csv
  ✓ /content/drive/MyDrive/SPP_GAN_Project/reports/CTGAN_Evaluation/bank_marketing_column_missing_report.csv
  ✓ /content/drive/MyDrive/SPP_GAN_Project/reports/CTGAN_Evaluation/descriptive_statistics/bank_marketing_statistics.csv
  ✓ /content/drive/MyDrive/SPP_GAN_Project/reports/CTGAN_Evaluation/descriptive_statistics/bank_marketing_descriptive_statistics.csv
  ✓ /content/drive/MyDrive/SPP_GAN_Project/reports/CTGAN_Evaluation/distribution_similarity/ks_test/bank_marketing_ks_results.csv
  ✓ /content/drive/MyDrive/SPP_GAN_Project/reports/CTGAN_Evaluation/distribution_similarity/ks_test/bank_marketing_ks_test.csv
  ✓ /content/drive/MyDrive/SPP_GAN_Project/reports/CTGAN_Evaluation/distribution_similarity/ks_test/bank_marketing_ks_report.csv
  ✓ /content/drive/MyDrive/SPP_GAN_Project/reports/CTGAN_Evaluation/distribution_similarity/ks_test/bank_marketing_kolmogorov_smirnov_results.csv
  ✓ /content/drive/MyDrive/SPP_GAN_Project/reports/CTGAN_Evaluation/distribution_similarity/wasserstein/bank_marketing_wasserstein.csv
  ✓ /content/drive/MyDrive/SPP_GAN_Project/reports/CTGAN_Evaluation/distribution_similarity/wasserstein/bank_marketing_wasserstein_distance_results.csv
  ✓ /content/drive/MyDrive/SPP_GAN_Project/reports/CTGAN_Evaluation/distribution_similarity/jsd/bank_marketing_jsd.csv
  ✓ /content/drive/MyDrive/SPP_GAN_Project/reports/CTGAN_Evaluation/distribution_similarity/jensen_shannon_divergence/bank_marketing_jensen_shannon_divergence_results.csv
  ✓ /content/drive/MyDrive/SPP_GAN_Project/reports/CTGAN_Evaluation/distribution_similarity/correlation_evaluation/pearson/bank_marketing_difference.csv
  ✓ /content/drive/MyDrive/SPP_GAN_Project/reports/CTGAN_Evaluation/distribution_similarity/correlation_evaluation/pearson/bank_marketing_synthetic.csv
  ✓ /content/drive/MyDrive/SPP_GAN_Project/reports/CTGAN_Evaluation/distribution_similarity/correlation_evaluation/pearson/bank_marketing_real.csv
  ✓ /content/drive/MyDrive/SPP_GAN_Project/reports/CTGAN_Evaluation/distribution_similarity/correlation_evaluation/spearman/bank_marketing_real.csv
  ✓ /content/drive/MyDrive/SPP_GAN_Project/reports/CTGAN_Evaluation/distribution_similarity/correlation_evaluation/spearman/bank_marketing_synthetic.csv

In [58]:
# ==============================================================================
# PART C2 — RESOLVE REFERENCE DATASET PATHS
# ==============================================================================

print("=" * 100)
print("PART C2 — RESOLVING REAL REFERENCE DATASET PATHS")
print("=" * 100)

# ------------------------------------------------------------------------------
# Candidate Priority Rules
# ------------------------------------------------------------------------------

def reference_path_priority(path):
    """
    Assign a priority score to candidate reference-data paths.

    Higher score = stronger preference.
    """

    path_lower = str(path).lower()

    score = 0

    # Prefer processed/reference artifacts if explicitly present
    if "processed" in path_lower:
        score += 50

    if "preprocessed" in path_lower:
        score += 50

    if "reference" in path_lower:
        score += 40

    # Avoid synthetic data
    if "synthetic" in path_lower:
        score -= 100

    # Avoid evaluation outputs
    if "evaluation" in path_lower:
        score -= 50

    if "results" in path_lower:
        score -= 30

    return score


# ------------------------------------------------------------------------------
# Resolve Paths
# ------------------------------------------------------------------------------

REFERENCE_DATASET_PATHS = {}

REFERENCE_DATASET_RESOLUTION = []

for dataset_name, candidates in (
    REFERENCE_DATASET_CANDIDATES.items()
):

    if not candidates:
        REFERENCE_DATASET_PATHS[
            dataset_name
        ] = None

        REFERENCE_DATASET_RESOLUTION.append({
            "Dataset": dataset_name,
            "Selected Path": None,
            "Candidate Count": 0,
            "Status": "MISSING"
        })

        continue

    ranked_candidates = sorted(
        candidates,
        key=reference_path_priority,
        reverse=True
    )

    selected_path = Path(
        ranked_candidates[0]
    )

    REFERENCE_DATASET_PATHS[
        dataset_name
    ] = selected_path

    REFERENCE_DATASET_RESOLUTION.append({
        "Dataset": dataset_name,
        "Selected Path": str(selected_path),
        "Candidate Count": len(candidates),
        "Status": "RESOLVED"
    })

REFERENCE_DATASET_RESOLUTION_DF = pd.DataFrame(
    REFERENCE_DATASET_RESOLUTION
)

display(
    REFERENCE_DATASET_RESOLUTION_DF
)

print("\n" + "=" * 100)
print("PART C2 — REFERENCE DATASET PATH RESOLUTION COMPLETED")
print("=" * 100)

====================================================================================================
PART C2 — RESOLVING REAL REFERENCE DATASET PATHS
====================================================================================================

,Dataset,Selected Path,Candidate Count,Status
0,adult_income,/content/drive/MyDrive/SPP_GAN_Project/dataset...,107,RESOLVED
1,bank_marketing,/content/drive/MyDrive/SPP_GAN_Project/dataset...,106,RESOLVED
2,diabetes_130us,/content/drive/MyDrive/SPP_GAN_Project/dataset...,78,RESOLVED

====================================================================================================
PART C2 — REFERENCE DATASET PATH RESOLUTION COMPLETED
====================================================================================================

In [59]:
# ==============================================================================
# PART C3 — LOAD REAL REFERENCE DATASETS
# ==============================================================================

print("=" * 100)
print("PART C3 — LOADING REAL REFERENCE DATASETS")
print("=" * 100)

REAL_DATASETS = {}

for dataset_name in DATASETS:

    dataset_path = REFERENCE_DATASET_PATHS.get(
        dataset_name
    )

    if dataset_path is None:

        raise FileNotFoundError(
            f"Reference dataset not found for: "
            f"{dataset_name}"
        )

    if not dataset_path.exists():

        raise FileNotFoundError(
            f"Reference dataset path does not exist:\n"
            f"{dataset_path}"
        )

    print(f"\nLoading: {dataset_name}")
    print(f"Path   : {dataset_path}")

    df = pd.read_csv(
        dataset_path
    )

    if df.empty:

        raise ValueError(
            f"Reference dataset is empty:\n"
            f"{dataset_path}"
        )

    REAL_DATASETS[
        dataset_name
    ] = df

    print(
        f"Rows   : {df.shape[0]:,}"
    )

    print(
        f"Columns: {df.shape[1]:,}"
    )

print("\n" + "=" * 100)
print("PART C3 — REAL REFERENCE DATASETS LOADED SUCCESSFULLY")
print("=" * 100)

====================================================================================================
PART C3 — LOADING REAL REFERENCE DATASETS
====================================================================================================

Loading: adult_income
Path   : /content/drive/MyDrive/SPP_GAN_Project/datasets/processed/adult_income_processed.csv
Rows   : 32,515
Columns: 15

Loading: bank_marketing
Path   : /content/drive/MyDrive/SPP_GAN_Project/datasets/processed/bank_marketing_processed.csv
Rows   : 45,211
Columns: 17

Loading: diabetes_130us
Path   : /content/drive/MyDrive/SPP_GAN_Project/datasets/processed/diabetes_130us_processed.csv
Rows   : 101,766
Columns: 48

====================================================================================================
PART C3 — REAL REFERENCE DATASETS LOADED SUCCESSFULLY
====================================================================================================

In [60]:
# ==============================================================================
# PART C4 — VALIDATE REAL DATASET STRUCTURE
# ==============================================================================

print("=" * 100)
print("PART C4 — VALIDATING REAL DATASET STRUCTURE")
print("=" * 100)

REFERENCE_STRUCTURE_RESULTS = []

for dataset_name, df in REAL_DATASETS.items():

    reference_path = REFERENCE_DATASET_PATHS[
        dataset_name
    ]

    duplicate_columns = (
        df.columns[
            df.columns.duplicated()
        ].tolist()
    )

    duplicate_rows = int(
        df.duplicated().sum()
    )

    missing_column_names = any(
        str(column).strip() == ""
        for column in df.columns
    )

    REFERENCE_STRUCTURE_RESULTS.append({

        "Dataset": dataset_name,

        "Rows": df.shape[0],

        "Columns": df.shape[1],

        "Column Names Valid":
            not missing_column_names,

        "Duplicate Columns":
            len(duplicate_columns),

        "Duplicate Rows":
            duplicate_rows,

        "Empty Dataset":
            df.empty,

        "File Exists":
            reference_path.exists(),

        "Structural Status":
            (
                "PASS"
                if (
                    not df.empty
                    and reference_path.exists()
                    and not missing_column_names
                    and len(duplicate_columns) == 0
                )
                else "FAIL"
            )
    })

REFERENCE_STRUCTURE_DF = pd.DataFrame(
    REFERENCE_STRUCTURE_RESULTS
)

display(
    REFERENCE_STRUCTURE_DF
)

if (
    REFERENCE_STRUCTURE_DF[
        "Structural Status"
    ] == "FAIL"
).any():

    raise ValueError(
        "One or more real reference datasets "
        "failed structural validation."
    )

print("\n" + "=" * 100)
print("PART C4 — REFERENCE DATA STRUCTURE VALIDATED")
print("=" * 100)

====================================================================================================
PART C4 — VALIDATING REAL DATASET STRUCTURE
====================================================================================================

,Dataset,Rows,Columns,Column Names Valid,Duplicate Columns,Duplicate Rows,Empty Dataset,File Exists,Structural Status
0,adult_income,32515,15,True,0,0,False,True,PASS
1,bank_marketing,45211,17,True,0,0,False,True,PASS
2,diabetes_130us,101766,48,True,0,0,False,True,PASS

====================================================================================================
PART C4 — REFERENCE DATA STRUCTURE VALIDATED
====================================================================================================

In [61]:
# ==============================================================================
# PART C5 — VALIDATE REAL DATASET MISSING VALUES
# ==============================================================================

print("=" * 100)
print("PART C5 — VALIDATING REAL DATASET MISSING VALUES")
print("=" * 100)

REFERENCE_MISSING_VALUE_RESULTS = []

for dataset_name, df in REAL_DATASETS.items():

    total_cells = (
        df.shape[0] *
        df.shape[1]
    )

    missing_cells = int(
        df.isna().sum().sum()
    )

    missing_percentage = (
        missing_cells / total_cells * 100
        if total_cells > 0
        else 0.0
    )

    columns_with_missing = int(
        df.isna()
        .any()
        .sum()
    )

    REFERENCE_MISSING_VALUE_RESULTS.append({

        "Dataset": dataset_name,

        "Rows": df.shape[0],

        "Columns": df.shape[1],

        "Missing Cells": missing_cells,

        "Missing Percentage":
            missing_percentage,

        "Columns With Missing Values":
            columns_with_missing,

        "Missing Value Status":
            (
                "PASS"
                if missing_cells == 0
                else "INFORMATIONAL"
            )
    })

REFERENCE_MISSING_VALUE_DF = pd.DataFrame(
    REFERENCE_MISSING_VALUE_RESULTS
)

display(
    REFERENCE_MISSING_VALUE_DF
)

print("\n" + "=" * 100)
print("PART C5 — MISSING VALUE VALIDATION COMPLETED")
print("=" * 100)

====================================================================================================
PART C5 — VALIDATING REAL DATASET MISSING VALUES
====================================================================================================

,Dataset,Rows,Columns,Missing Cells,Missing Percentage,Columns With Missing Values,Missing Value Status
0,adult_income,32515,15,0,0.0,0,PASS
1,bank_marketing,45211,17,0,0.0,0,PASS
2,diabetes_130us,101766,48,0,0.0,0,PASS

====================================================================================================
PART C5 — MISSING VALUE VALIDATION COMPLETED
====================================================================================================

In [62]:
# ==============================================================================
# PART C6 — VALIDATE REAL DATASET DATA TYPES
# ==============================================================================

print("=" * 100)
print("PART C6 — VALIDATING REAL DATASET DATA TYPES")
print("=" * 100)

REFERENCE_DATATYPE_RESULTS = []

for dataset_name, df in REAL_DATASETS.items():

    numerical_columns = (
        df.select_dtypes(
            include=np.number
        ).columns.tolist()
    )

    categorical_columns = (
        df.select_dtypes(
            exclude=np.number
        ).columns.tolist()
    )

    REFERENCE_DATATYPE_RESULTS.append({

        "Dataset": dataset_name,

        "Total Columns":
            df.shape[1],

        "Numerical Columns":
            len(numerical_columns),

        "Categorical Columns":
            len(categorical_columns),

        "Numerical Features":
            numerical_columns,

        "Categorical Features":
            categorical_columns
    })

REFERENCE_DATATYPE_DF = pd.DataFrame(
    REFERENCE_DATATYPE_RESULTS
)

display(
    REFERENCE_DATATYPE_DF
)

print("\n" + "=" * 100)
print("PART C6 — DATA TYPE VALIDATION COMPLETED")
print("=" * 100)

====================================================================================================
PART C6 — VALIDATING REAL DATASET DATA TYPES
====================================================================================================

,Dataset,Total Columns,Numerical Columns,Categorical Columns,Numerical Features,Categorical Features
0,adult_income,15,15,0,"[age, workclass, fnlwgt, education, education_...",[]
1,bank_marketing,17,17,0,"[age, job, marital, education, default, balanc...",[]
2,diabetes_130us,48,48,0,"[race, gender, age, weight, admission_type_id,...",[]

====================================================================================================
PART C6 — DATA TYPE VALIDATION COMPLETED
====================================================================================================

In [63]:
# ==============================================================================
# PART C7 — REAL REFERENCE TARGET DISCOVERY AND VALIDATION
# ==============================================================================

print("=" * 100)
print("PART C7 — REAL REFERENCE TARGET DISCOVERY AND VALIDATION")
print("=" * 100)

# ------------------------------------------------------------------------------
# Target Name Patterns
# ------------------------------------------------------------------------------

TARGET_NAME_HINTS = [
    "target",
    "label",
    "class",
    "outcome",
    "response",
    "income",
    "deposit",
    "readmitted",
    "default",
    "fraud",
    "diagnosis"
]

# ------------------------------------------------------------------------------
# Discover Candidate Target Columns
# ------------------------------------------------------------------------------

REFERENCE_TARGET_CANDIDATES = {}

for dataset_name, df in REAL_DATASETS.items():

    candidates = []

    for column in df.columns:

        column_normalized = (
            str(column)
            .strip()
            .lower()
            .replace(" ", "_")
            .replace("-", "_")
        )

        if any(
            hint in column_normalized
            for hint in TARGET_NAME_HINTS
        ):

            candidates.append(column)

    REFERENCE_TARGET_CANDIDATES[
        dataset_name
    ] = candidates

# ------------------------------------------------------------------------------
# Display Candidates
# ------------------------------------------------------------------------------

print("\nPotential Target Columns")

for dataset_name, candidates in (
    REFERENCE_TARGET_CANDIDATES.items()
):

    print(f"\n{dataset_name}")

    if candidates:

        for column in candidates:

            print(
                f"  ✓ {column}"
            )

    else:

        print(
            "  No target candidate identified "
            "from column name."
        )

# ------------------------------------------------------------------------------
# Build Target Discovery Table
# ------------------------------------------------------------------------------

REFERENCE_TARGET_DISCOVERY = []

for dataset_name, df in REAL_DATASETS.items():

    candidates = REFERENCE_TARGET_CANDIDATES[
        dataset_name
    ]

    if len(candidates) == 1:

        status = "CANDIDATE_IDENTIFIED"

    elif len(candidates) > 1:

        status = "MULTIPLE_CANDIDATES"

    else:

        status = "TARGET_NOT_IDENTIFIED"

    REFERENCE_TARGET_DISCOVERY.append({

        "Dataset":
            dataset_name,

        "Candidate Target Columns":
            ", ".join(
                str(column)
                for column in candidates
            ),

        "Candidate Count":
            len(candidates),

        "Target Status":
            status
    })

REFERENCE_TARGET_DISCOVERY_DF = pd.DataFrame(
    REFERENCE_TARGET_DISCOVERY
)

display(
    REFERENCE_TARGET_DISCOVERY_DF
)

print("\n" + "=" * 100)
print("PART C7 — TARGET DISCOVERY COMPLETED")
print("=" * 100)

====================================================================================================
PART C7 — REAL REFERENCE TARGET DISCOVERY AND VALIDATION
====================================================================================================

Potential Target Columns

adult_income
  ✓ workclass
  ✓ income

bank_marketing
  ✓ default
  ✓ poutcome

diabetes_130us
  ✓ readmitted

,Dataset,Candidate Target Columns,Candidate Count,Target Status
0,adult_income,"workclass, income",2,MULTIPLE_CANDIDATES
1,bank_marketing,"default, poutcome",2,MULTIPLE_CANDIDATES
2,diabetes_130us,readmitted,1,CANDIDATE_IDENTIFIED

====================================================================================================
PART C7 — TARGET DISCOVERY COMPLETED
====================================================================================================

In [64]:
# ==============================================================================
# PART C8 — GENERATE REFERENCE DATASET METADATA
# ==============================================================================

print("=" * 100)
print("PART C8 — GENERATING REFERENCE DATASET METADATA")
print("=" * 100)

DATASET_METADATA = {}

for dataset_name, df in REAL_DATASETS.items():

    numerical_columns = (
        df.select_dtypes(
            include=np.number
        ).columns.tolist()
    )

    categorical_columns = (
        df.select_dtypes(
            exclude=np.number
        ).columns.tolist()
    )

    target_column = DATASET_REGISTRY[
        dataset_name
    ].get("target")

    DATASET_METADATA[
        dataset_name
    ] = {

        "dataset_name":
            dataset_name,

        "display_name":
            DATASET_REGISTRY[
                dataset_name
            ]["display_name"],

        "file_path":
            str(
                REFERENCE_DATASET_PATHS[
                    dataset_name
                ]
            ),

        "rows":
            int(df.shape[0]),

        "columns":
            int(df.shape[1]),

        "column_names":
            df.columns.tolist(),

        "numerical_columns":
            numerical_columns,

        "categorical_columns":
            categorical_columns,

        "target_column":
            target_column,

        "missing_cells":
            int(
                df.isna().sum().sum()
            ),

        "duplicate_rows":
            int(
                df.duplicated().sum()
            )
    }

print(
    f"Metadata generated for "
    f"{len(DATASET_METADATA)} datasets."
)

for dataset_name, metadata in (
    DATASET_METADATA.items()
):

    print(
        f"\n{dataset_name}:"
    )

    print(
        f"  Rows       : {metadata['rows']:,}"
    )

    print(
        f"  Columns    : {metadata['columns']:,}"
    )

    print(
        f"  Numerical  : "
        f"{len(metadata['numerical_columns'])}"
    )

    print(
        f"  Categorical: "
        f"{len(metadata['categorical_columns'])}"
    )

    print(
        f"  Target     : "
        f"{metadata['target_column']}"
    )

print("\n" + "=" * 100)
print("PART C8 — REFERENCE METADATA GENERATED")
print("=" * 100)

====================================================================================================
PART C8 — GENERATING REFERENCE DATASET METADATA
====================================================================================================
Metadata generated for 3 datasets.

adult_income:
  Rows       : 32,515
  Columns    : 15
  Numerical  : 15
  Categorical: 0
  Target     : None

bank_marketing:
  Rows       : 45,211
  Columns    : 17
  Numerical  : 17
  Categorical: 0
  Target     : None

diabetes_130us:
  Rows       : 101,766
  Columns    : 48
  Numerical  : 48
  Categorical: 0
  Target     : None

====================================================================================================
PART C8 — REFERENCE METADATA GENERATED
====================================================================================================

In [65]:
# ==============================================================================
# PART C9 — REFERENCE DATASET SUMMARY
# ==============================================================================

print("=" * 100)
print("PART C9 — REAL REFERENCE DATASET SUMMARY")
print("=" * 100)

REFERENCE_DATASET_SUMMARY = []

for dataset_name, df in REAL_DATASETS.items():

    metadata = DATASET_METADATA[
        dataset_name
    ]

    REFERENCE_DATASET_SUMMARY.append({

        "Dataset":
            dataset_name,

        "Display Name":
            metadata["display_name"],

        "Rows":
            metadata["rows"],

        "Columns":
            metadata["columns"],

        "Numerical Features":
            len(
                metadata[
                    "numerical_columns"
                ]
            ),

        "Categorical Features":
            len(
                metadata[
                    "categorical_columns"
                ]
            ),

        "Missing Cells":
            metadata["missing_cells"],

        "Duplicate Rows":
            metadata["duplicate_rows"],

        "Target":
            metadata["target_column"],

        "Reference Status":
            "READY"
    })

REFERENCE_DATASET_SUMMARY_DF = pd.DataFrame(
    REFERENCE_DATASET_SUMMARY
)

display(
    REFERENCE_DATASET_SUMMARY_DF
)

print("\n" + "=" * 100)
print("PART C9 — REFERENCE DATASET SUMMARY GENERATED")
print("=" * 100)

====================================================================================================
PART C9 — REAL REFERENCE DATASET SUMMARY
====================================================================================================

,Dataset,Display Name,Rows,Columns,Numerical Features,Categorical Features,Missing Cells,Duplicate Rows,Target,Reference Status
0,adult_income,Adult Income,32515,15,15,0,0,0,None,READY
1,bank_marketing,Bank Marketing,45211,17,17,0,0,0,None,READY
2,diabetes_130us,Diabetes 130-US Hospitals,101766,48,48,0,0,0,None,READY

====================================================================================================
PART C9 — REFERENCE DATASET SUMMARY GENERATED
====================================================================================================

In [66]:
# ==============================================================================
# PART C10 — FINAL REFERENCE DATA VERIFICATION
# ==============================================================================

print("=" * 100)
print("PART C10 — FINAL REAL REFERENCE DATA VERIFICATION")
print("=" * 100)

REFERENCE_VERIFICATION = []

for dataset_name in DATASETS:

    df = REAL_DATASETS.get(
        dataset_name
    )

    dataset_path = REFERENCE_DATASET_PATHS.get(
        dataset_name
    )

    checks = {

        "Dataset Loaded":
            df is not None,

        "File Exists":
            (
                dataset_path is not None
                and dataset_path.exists()
            ),

        "Rows > 0":
            (
                df is not None
                and len(df) > 0
            ),

        "Columns > 0":
            (
                df is not None
                and df.shape[1] > 0
            ),

        "Column Names Valid":
            (
                df is not None
                and all(
                    str(column).strip() != ""
                    for column in df.columns
                )
            ),

        "Duplicate Columns Absent":
            (
                df is not None
                and not df.columns.duplicated().any()
            )
    }

    overall_status = all(
        checks.values()
    )

    REFERENCE_VERIFICATION.append({

        "Dataset":
            dataset_name,

        **checks,

        "Overall Status":
            "PASS"
            if overall_status
            else "FAIL"
    })

REFERENCE_VERIFICATION_DF = pd.DataFrame(
    REFERENCE_VERIFICATION
)

display(
    REFERENCE_VERIFICATION_DF
)

# ------------------------------------------------------------------------------
# Final Gate
# ------------------------------------------------------------------------------

failed_reference_datasets = (
    REFERENCE_VERIFICATION_DF[
        REFERENCE_VERIFICATION_DF[
            "Overall Status"
        ] == "FAIL"
    ]
)

if not failed_reference_datasets.empty:

    raise RuntimeError(
        "Real reference-data verification failed for:\n"
        + "\n".join(
            f"  • {dataset}"
            for dataset in failed_reference_datasets[
                "Dataset"
            ]
        )
    )

print("\nAll real reference datasets passed final verification.")

print("\n" + "=" * 100)
print("PART C10 — REAL REFERENCE DATA READY FOR COMPARATIVE EVALUATION")
print("=" * 100)

====================================================================================================
PART C10 — FINAL REAL REFERENCE DATA VERIFICATION
====================================================================================================

,Dataset,Dataset Loaded,File Exists,Rows > 0,Columns > 0,Column Names Valid,Duplicate Columns Absent,Overall Status
0,adult_income,True,True,True,True,True,True,PASS
1,bank_marketing,True,True,True,True,True,True,PASS
2,diabetes_130us,True,True,True,True,True,True,PASS

All real reference datasets passed final verification.

====================================================================================================
PART C10 — REAL REFERENCE DATA READY FOR COMPARATIVE EVALUATION
====================================================================================================

In [68]:
# ==============================================================================
# PART D1 — SYNTHETIC DATA SOURCE CONFIGURATION
# ==============================================================================

print("=" * 100)
print("PART D1 — SYNTHETIC DATA SOURCE CONFIGURATION")
print("=" * 100)

# ------------------------------------------------------------------------------
# Synthetic Data Generation Methods
# ------------------------------------------------------------------------------

SYNTHETIC_METHODS = [
    "CTGAN",
    "TVAE",
    "DP-CTGAN",
    "SPP-GAN"
]

# ------------------------------------------------------------------------------
# Dataset Configuration
# ------------------------------------------------------------------------------

SYNTHETIC_DATASET_NAMES = [
    "adult_income",
    "bank_marketing",
    "diabetes_130us"
]

# ------------------------------------------------------------------------------
# Expected Synthetic Data Sources
# ------------------------------------------------------------------------------

SYNTHETIC_SOURCE_REGISTRY = {

    "CTGAN": {
        "notebook": "Notebook 04",
        "method_type": "Machine Learning Baseline",
        "privacy": False
    },

    "TVAE": {
        "notebook": "Notebook 05",
        "method_type": "Machine Learning Baseline",
        "privacy": False
    },

    "DP-CTGAN": {
        "notebook": "Notebook 06",
        "method_type": "Privacy-Preserving Baseline",
        "privacy": True
    },

    "SPP-GAN": {
        "notebook": "Notebook 07",
        "method_type": "Proposed Framework",
        "privacy": True
    }
}

# ------------------------------------------------------------------------------
# Display Configuration
# ------------------------------------------------------------------------------

SYNTHETIC_SOURCE_DF = pd.DataFrame.from_dict(
    SYNTHETIC_SOURCE_REGISTRY,
    orient="index"
).reset_index()

SYNTHETIC_SOURCE_DF = SYNTHETIC_SOURCE_DF.rename(
    columns={"index": "Method"}
)

display(
    SYNTHETIC_SOURCE_DF
)

print("\nSynthetic methods configured:")
for method in SYNTHETIC_METHODS:
    print(f"  ✓ {method}")

print("\n" + "=" * 100)
print("PART D1 — SYNTHETIC DATA SOURCE CONFIGURATION COMPLETED")
print("=" * 100)

====================================================================================================
PART D1 — SYNTHETIC DATA SOURCE CONFIGURATION
====================================================================================================

     Method     notebook                  method_type  privacy
0     CTGAN  Notebook 04    Machine Learning Baseline    False
1      TVAE  Notebook 05    Machine Learning Baseline    False
2  DP-CTGAN  Notebook 06  Privacy-Preserving Baseline     True
3   SPP-GAN  Notebook 07           Proposed Framework     True

Synthetic methods configured:
  ✓ CTGAN
  ✓ TVAE
  ✓ DP-CTGAN
  ✓ SPP-GAN

====================================================================================================
PART D1 — SYNTHETIC DATA SOURCE CONFIGURATION COMPLETED
====================================================================================================

In [69]:
# ==============================================================================
# PART D2 — SYNTHETIC DATASET DISCOVERY
# ==============================================================================

print("=" * 100)
print("PART D2 — SYNTHETIC DATASET DISCOVERY")
print("=" * 100)

# ------------------------------------------------------------------------------
# Discover CSV Files
# ------------------------------------------------------------------------------

ALL_SYNTHETIC_CSV_FILES = []

for path in PROJECT_ROOT.rglob("*.csv"):

    if not path.is_file():
        continue

    path_lower = str(path).lower()

    if "synthetic" in path_lower:

        ALL_SYNTHETIC_CSV_FILES.append(
            path
        )

# ------------------------------------------------------------------------------
# Display Discovered Files
# ------------------------------------------------------------------------------

print(
    f"\nSynthetic CSV files discovered: "
    f"{len(ALL_SYNTHETIC_CSV_FILES)}"
)

if ALL_SYNTHETIC_CSV_FILES:

    for path in sorted(
        ALL_SYNTHETIC_CSV_FILES
    ):

        print(
            f"✓ {path}"
        )

else:

    print(
        "✗ No synthetic CSV files discovered."
    )

# ------------------------------------------------------------------------------
# Method Name Patterns
# ------------------------------------------------------------------------------

METHOD_PATTERNS = {

    "CTGAN": [
        "ctgan"
    ],

    "TVAE": [
        "tvae"
    ],

    "DP-CTGAN": [
        "dp_ctgan",
        "dp-ctgan",
        "dpctgan"
    ],

    "SPP-GAN": [
        "spp_gan",
        "spp-gan",
        "sppgan"
    ]
}

# ------------------------------------------------------------------------------
# Dataset Name Patterns
# ------------------------------------------------------------------------------

DATASET_PATTERNS = {

    "adult_income": [
        "adult_income",
        "adult-income"
    ],

    "bank_marketing": [
        "bank_marketing",
        "bank-marketing"
    ],

    "diabetes_130us": [
        "diabetes_130us",
        "diabetes-130us"
    ]
}

# ------------------------------------------------------------------------------
# Candidate Registry
# ------------------------------------------------------------------------------

SYNTHETIC_FILE_CANDIDATES = {

    method: {
        dataset: []
        for dataset in SYNTHETIC_DATASET_NAMES
    }
    for method in SYNTHETIC_METHODS
}

for path in ALL_SYNTHETIC_CSV_FILES:

    path_text = str(path).lower()

    detected_method = None
    detected_dataset = None

    # Method detection
    for method, patterns in METHOD_PATTERNS.items():

        if any(
            pattern in path_text
            for pattern in patterns
        ):

            detected_method = method
            break

    # Dataset detection
    for dataset, patterns in DATASET_PATTERNS.items():

        if any(
            pattern in path_text
            for pattern in patterns
        ):

            detected_dataset = dataset
            break

    if (
        detected_method is not None
        and detected_dataset is not None
    ):

        SYNTHETIC_FILE_CANDIDATES[
            detected_method
        ][
            detected_dataset
        ].append(path)

# ------------------------------------------------------------------------------
# Display Candidate Matrix
# ------------------------------------------------------------------------------

print("\n" + "-" * 100)
print("SYNTHETIC DATASET CANDIDATES")
print("-" * 100)

for method in SYNTHETIC_METHODS:

    print(f"\n{method}")

    for dataset in SYNTHETIC_DATASET_NAMES:

        candidates = (
            SYNTHETIC_FILE_CANDIDATES[
                method
            ][
                dataset
            ]
        )

        print(
            f"  {dataset}: "
            f"{len(candidates)} candidate(s)"
        )

        for path in candidates:

            print(
                f"      ✓ {path}"
            )

print("\n" + "=" * 100)
print("PART D2 — SYNTHETIC DATASET DISCOVERY COMPLETED")
print("=" * 100)

====================================================================================================
PART D2 — SYNTHETIC DATASET DISCOVERY
====================================================================================================

Synthetic CSV files discovered: 68
✓ /content/drive/MyDrive/SPP_GAN_Project/data/synthetic/dp_ctgan/csv/Adult Income_dp_ctgan.csv
✓ /content/drive/MyDrive/SPP_GAN_Project/data/synthetic/dp_ctgan/csv/Bank Marketing_dp_ctgan.csv
✓ /content/drive/MyDrive/SPP_GAN_Project/data/synthetic/dp_ctgan/csv/diabetes_130us_dp_ctgan.csv
✓ /content/drive/MyDrive/SPP_GAN_Project/datasets/synthetic/CTGAN/adult_income_synthetic.csv
✓ /content/drive/MyDrive/SPP_GAN_Project/datasets/synthetic/CTGAN/bank_marketing_synthetic.csv
✓ /content/drive/MyDrive/SPP_GAN_Project/datasets/synthetic/CTGAN/breast_cancer_synthetic.csv
✓ /content/drive/MyDrive/SPP_GAN_Project/datasets/synthetic/CTGAN/diabetes_130us_synthetic.csv
✓ /content/drive/MyDrive/SPP_GAN_Project/datasets/synthetic/CTGAN/synthetic_dataset_summary.csv
✓ /content/drive/MyDrive/SPP_GAN_Project/datasets/synthetic/TVAE/adult_income_synthetic.csv
✓ /content/drive/MyDrive/SPP_GAN_Project/datasets/synthetic/TVAE/bank_marketing_synthetic.csv
✓ /content/drive/MyDrive/SPP_GAN_Project/datasets/synthetic/TVAE/diabetes_130us_synthetic.csv
✓ /content/drive/MyDrive/SPP_GAN_Project/datasets/synthetic/adult_income_gaussian_copula.csv
✓ /content/drive/MyDrive/SPP_GAN_Project/datasets/synthetic/bank_marketing_gaussian_copula.csv
✓ /content/drive/MyDrive/SPP_GAN_Project/datasets/synthetic/diabetes_130us_gaussian_copula.csv
✓ /content/drive/MyDrive/SPP_GAN_Project/datasets/synthetic/gaussian_copula/adult_income_gaussian_copula.csv
✓ /content/drive/MyDrive/SPP_GAN_Project/datasets/synthetic/gaussian_copula/adult_income_synthetic.csv
✓ /content/drive/MyDrive/SPP_GAN_Project/datasets/synthetic/gaussian_copula/bank_marketing_gaussian_copula.csv
✓ /content/drive/MyDrive/SPP_GAN_Project/datasets/synthetic/gaussian_copula/bank_marketing_synthetic.csv
✓ /content/drive/MyDrive/SPP_GAN_Project/datasets/synthetic/gaussian_copula/breast_cancer_synthetic.csv
✓ /content/drive/MyDrive/SPP_GAN_Project/datasets/synthetic/gaussian_copula/diabetes_130us_gaussian_copula.csv
✓ /content/drive/MyDrive/SPP_GAN_Project/datasets/synthetic/gaussian_copula/diabetes_130us_synthetic.csv
✓ /content/drive/MyDrive/SPP_GAN_Project/datasets/synthetic/gaussian_multivariate/adult_income_synthetic.csv
✓ /content/drive/MyDrive/SPP_GAN_Project/datasets/synthetic/gaussian_multivariate/bank_marketing_synthetic.csv
✓ /content/drive/MyDrive/SPP_GAN_Project/datasets/synthetic/gaussian_multivariate/breast_cancer_synthetic.csv
✓ /content/drive/MyDrive/SPP_GAN_Project/datasets/synthetic/gaussian_multivariate/diabetes_130us_synthetic.csv
✓ /content/drive/MyDrive/SPP_GAN_Project/evaluation/dp_ctgan/generation/synthetic_generation_summary.csv
✓ /content/drive/MyDrive/SPP_GAN_Project/reports/CTGAN_Evaluation/distribution_similarity/correlation/pearson/adult_income_pearson_synthetic.csv
✓ /content/drive/MyDrive/SPP_GAN_Project/reports/CTGAN_Evaluation/distribution_similarity/correlation/pearson/bank_marketing_pearson_synthetic.csv
✓ /content/drive/MyDrive/SPP_GAN_Project/reports/CTGAN_Evaluation/distribution_similarity/correlation/pearson/breast_cancer_pearson_synthetic.csv
✓ /content/drive/MyDrive/SPP_GAN_Project/reports/CTGAN_Evaluation/distribution_similarity/correlation/pearson/diabetes_130us_pearson_synthetic.csv
✓ /content/drive/MyDrive/SPP_GAN_Project/reports/CTGAN_Evaluation/distribution_similarity/correlation/spearman/adult_income_spearman_synthetic.csv
✓ /content/drive/MyDrive/SPP_GAN_Project/reports/CTGAN_Evaluation/distribution_similarity/correlation/spearman/bank_marketing_spearman_synthetic.csv
✓ /content/drive/MyDrive/SPP_GAN_Project/reports/CTGAN_Evaluation/distribution_similarity/correlation/spearman/breast_cancer_spearman_synthetic.csv
✓ /content/drive/MyDrive/SPP_GAN_Project/reports/CTGAN_Evaluation/distribution_similarity/correlation/spearman/diabetes_130us_spearman_synthetic.csv
✓ /content/drive/MyDrive/SPP_GAN_Project/reports/CTGAN_Evaluation/distribution_similarity/correlation_evaluation/pearson/adult_income_synthetic.csv
✓ /content/drive/MyDrive/SPP_GAN_Project/reports/CTGAN_Evaluation/distribution_similarity/correlation_evaluation/pearson/bank_marketing_synthetic.csv
✓ /content/drive/MyDrive/SPP_GAN_Project/reports/CTGAN_Evaluation/distribution_similarity/correlation_evaluation/pearson/breast_cancer_synthetic.csv
✓ /content/drive/MyDrive/SPP_GAN_Project/reports/CTGAN_Evaluation/distribution_similarity/correlation_evaluation/reports/machine_learning_utility/synthetic_model_metrics.csv
✓ /content/drive/MyDrive/SPP_GAN_Project/reports/CTGAN_Evaluation/distribution_similarity/correlation_evaluation/reports/machine_learning_utility/synthetic_model_roc_auc.csv
✓ /content/drive/MyDrive/SPP_GAN_Project/reports/CTGAN_Evaluation/distribution_similarity/correlation_evaluation/reports/machine_learning_utility/synthetic_model_validation.csv
✓ /content/drive/MyDrive/SPP_GAN_Project/reports/CTGAN_Evaluation/distribution_similarity/correlation_evaluation/spearman/adult_income_synthetic.csv
✓ /content/drive/MyDrive/SPP_GAN_Project/reports/CTGAN_Evaluation/distribution_similarity/correlation_evaluation/spearman/bank_marketing_synthetic.csv
✓ /content/drive/MyDrive/SPP_GAN_Project/reports/CTGAN_Evaluation/distribution_similarity/correlation_evaluation/spearman/breast_cancer_synthetic.csv
✓ /content/drive/MyDrive/SPP_GAN_Project/reports/CTGAN_Evaluation/machine_learning_utility/final_reports/roc_auc_synthetic.csv
✓ /content/drive/MyDrive/SPP_GAN_Project/reports/CTGAN_Evaluation/machine_learning_utility/final_reports/synthetic_model_metrics.csv
✓ /content/drive/MyDrive/SPP_GAN_Project/reports/CTGAN_Evaluation/machine_learning_utility/synthetic_model_metrics.csv
✓ /content/drive/MyDrive/SPP_GAN_Project/reports/CTGAN_Evaluation/machine_learning_utility/synthetic_model_roc_auc.csv
✓ /content/drive/MyDrive/SPP_GAN_Project/reports/CTGAN_Evaluation/machine_learning_utility/synthetic_model_validation.csv
✓ /content/drive/MyDrive/SPP_GAN_Project/reports/TVAE/tvae_synthetic_dataset_summary.csv
✓ /content/drive/MyDrive/SPP_GAN_Project/reports/TVAE_Evaluation/distribution_similarity/correlation/pearson/adult_income_pearson_synthetic.csv
✓ /content/drive/MyDrive/SPP_GAN_Project/reports/TVAE_Evaluation/distribution_similarity/correlation/pearson/bank_marketing_pearson_synthetic.csv
✓ /content/drive/MyDrive/SPP_GAN_Project/reports/TVAE_Evaluation/distribution_similarity/correlation/pearson/diabetes_130us_pearson_synthetic.csv
✓ /content/drive/MyDrive/SPP_GAN_Project/reports/TVAE_Evaluation/distribution_similarity/correlation/spearman/adult_income_spearman_synthetic.csv
✓ /content/drive/MyDrive/SPP_GAN_Project/reports/TVAE_Evaluation/distribution_similarity/correlation/spearman/bank_marketing_spearman_synthetic.csv
✓ /content/drive/MyDrive/SPP_GAN_Project/reports/TVAE_Evaluation/distribution_similarity/correlation/spearman/diabetes_130us_spearman_synthetic.csv
✓ /content/drive/MyDrive/SPP_GAN_Project/reports/TVAE_Evaluation/machine_learning_utility/final_reports/roc_auc_synthetic.csv
✓ /content/drive/MyDrive/SPP_GAN_Project/reports/TVAE_Evaluation/machine_learning_utility/final_reports/synthetic_model_metrics.csv
✓ /content/drive/MyDrive/SPP_GAN_Project/reports/synthetic_dataset_validation.csv
✓ /content/drive/MyDrive/SPP_GAN_Project/reports/tvae_synthetic_dataset_validation.csv
✓ /content/drive/MyDrive/SPP_GAN_Project/results/TVAE/adult_income_tvae_synthetic.csv
✓ /content/drive/MyDrive/SPP_GAN_Project/results/TVAE/bank_marketing_tvae_synthetic.csv
✓ /content/drive/MyDrive/SPP_GAN_Project/results/TVAE/breast_cancer_tvae_synthetic.csv
✓ /content/drive/MyDrive/SPP_GAN_Project/results/TVAE/synthetic_data/adult_income_synthetic.csv
✓ /content/drive/MyDrive/SPP_GAN_Project/results/TVAE/synthetic_data/bank_marketing_synthetic.csv
✓ /content/drive/MyDrive/SPP_GAN_Project/results/TVAE/synthetic_data/breast_cancer_synthetic.csv
✓ /content/drive/MyDrive/SPP_GAN_Project/synthetic_data/TVAE/adult_income_TVAE_synthetic.csv
✓ /content/drive/MyDrive/SPP_GAN_Project/synthetic_data/TVAE/bank_marketing_TVAE_synthetic.csv
✓ /content/drive/MyDrive/SPP_GAN_Project/synthetic_data/TVAE/breast_cancer_TVAE_synthetic.csv

----------------------------------------------------------------------------------------------------
SYNTHETIC DATASET CANDIDATES
----------------------------------------------------------------------------------------------------

CTGAN
  adult_income: 5 candidate(s)
      ✓ /content/drive/MyDrive/SPP_GAN_Project/datasets/synthetic/CTGAN/adult_income_synthetic.csv
      ✓ /content/drive/MyDrive/SPP_GAN_Project/reports/CTGAN_Evaluation/distribution_similarity/correlation_evaluation/pearson/adult_income_synthetic.csv
      ✓ /content/drive/MyDrive/SPP_GAN_Project/reports/CTGAN_Evaluation/distribution_similarity/correlation_evaluation/spearman/adult_income_synthetic.csv
      ✓ /content/drive/MyDrive/SPP_GAN_Project/reports/CTGAN_Evaluation/distribution_similarity/correlation/pearson/adult_income_pearson_synthetic.csv
      ✓ /content/drive/MyDrive/SPP_GAN_Project/reports/CTGAN_Evaluation/distribution_similarity/correlation/spearman/adult_income_spearman_synthetic.csv
  bank_marketing: 5 candidate(s)
      ✓ /content/drive/MyDrive/SPP_GAN_Project/datasets/synthetic/CTGAN/bank_marketing_synthetic.csv
      ✓ /content/drive/MyDrive/SPP_GAN_Project/reports/CTGAN_Evaluation/distribution_similarity/correlation_evaluation/pearson/bank_marketing_synthetic.csv
      ✓ /content/drive/MyDrive/SPP_GAN_Project/reports/CTGAN_Evaluation/distribution_similarity/correlation_evaluation/spearman/bank_marketing_synthetic.csv
      ✓ /content/drive/MyDrive/SPP_GAN_Project/reports/CTGAN_Evaluation/distribution_similarity/correlation/pearson/bank_marketing_pearson_synthetic.csv
      ✓ /content/drive/MyDrive/SPP_GAN_Project/reports/CTGAN_Evaluation/distribution_similarity/correlation/spearman/bank_marketing_spearman_synthetic.csv
  diabetes_130us: 4 candidate(s)
      ✓ /content/drive/MyDrive/SPP_GAN_Project/datasets/synthetic/CTGAN/diabetes_130us_synthetic.csv
      ✓ /content/drive/MyDrive/SPP_GAN_Project/reports/CTGAN_Evaluation/distribution_similarity/correlation/pearson/diabetes_130us_pearson_synthetic.csv
      ✓ /content/drive/MyDrive/SPP_GAN_Project/reports/CTGAN_Evaluation/distribution_similarity/correlation/spearman/diabetes_130us_spearman_synthetic.csv
      ✓ /content/drive/MyDrive/SPP_GAN_Project/data/synthetic/dp_ctgan/csv/diabetes_130us_dp_ctgan.csv

TVAE
  adult_income: 6 candidate(s)
      ✓ /content/drive/MyDrive/SPP_GAN_Project/datasets/synthetic/TVAE/adult_income_synthetic.csv
      ✓ /content/drive/MyDrive/SPP_GAN_Project/synthetic_data/TVAE/adult_income_TVAE_synthetic.csv
      ✓ /content/drive/MyDrive/SPP_GAN_Project/results/TVAE/adult_income_tvae_synthetic.csv
      ✓ /content/drive/MyDrive/SPP_GAN_Project/results/TVAE/synthetic_data/adult_income_synthetic.csv
      ✓ /content/drive/MyDrive/SPP_GAN_Project/reports/TVAE_Evaluation/distribution_similarity/correlation/pearson/adult_income_pearson_synthetic.csv
      ✓ /content/drive/MyDrive/SPP_GAN_Project/reports/TVAE_Evaluation/distribution_similarity/correlation/spearman/adult_income_spearman_synthetic.csv
  bank_marketing: 6 candidate(s)
      ✓ /content/drive/MyDrive/SPP_GAN_Project/datasets/synthetic/TVAE/bank_marketing_synthetic.csv
      ✓ /content/drive/MyDrive/SPP_GAN_Project/synthetic_data/TVAE/bank_marketing_TVAE_synthetic.csv
      ✓ /content/drive/MyDrive/SPP_GAN_Project/results/TVAE/bank_marketing_tvae_synthetic.csv
      ✓ /content/drive/MyDrive/SPP_GAN_Project/results/TVAE/synthetic_data/bank_marketing_synthetic.csv
      ✓ /content/drive/MyDrive/SPP_GAN_Project/reports/TVAE_Evaluation/distribution_similarity/correlation/pearson/bank_marketing_pearson_synthetic.csv
      ✓ /content/drive/MyDrive/SPP_GAN_Project/reports/TVAE_Evaluation/distribution_similarity/correlation/spearman/bank_marketing_spearman_synthetic.csv
  diabetes_130us: 3 candidate(s)
      ✓ /content/drive/MyDrive/SPP_GAN_Project/datasets/synthetic/TVAE/diabetes_130us_synthetic.csv
      ✓ /content/drive/MyDrive/SPP_GAN_Project/reports/TVAE_Evaluation/distribution_similarity/correlation/pearson/diabetes_130us_pearson_synthetic.csv
      ✓ /content/drive/MyDrive/SPP_GAN_Project/reports/TVAE_Evaluation/distribution_similarity/correlation/spearman/diabetes_130us_spearman_synthetic.csv

DP-CTGAN
  adult_income: 0 candidate(s)
  bank_marketing: 0 candidate(s)
  diabetes_130us: 0 candidate(s)

SPP-GAN
  adult_income: 4 candidate(s)
      ✓ /content/drive/MyDrive/SPP_GAN_Project/datasets/synthetic/adult_income_gaussian_copula.csv
      ✓ /content/drive/MyDrive/SPP_GAN_Project/datasets/synthetic/gaussian_multivariate/adult_income_synthetic.csv
      ✓ /content/drive/MyDrive/SPP_GAN_Project/datasets/synthetic/gaussian_copula/adult_income_gaussian_copula.csv
      ✓ /content/drive/MyDrive/SPP_GAN_Project/datasets/synthetic/gaussian_copula/adult_income_synthetic.csv
  bank_marketing: 4 candidate(s)
      ✓ /content/drive/MyDrive/SPP_GAN_Project/datasets/synthetic/bank_marketing_gaussian_copula.csv
      ✓ /content/drive/MyDrive/SPP_GAN_Project/datasets/synthetic/gaussian_multivariate/bank_marketing_synthetic.csv
      ✓ /content/drive/MyDrive/SPP_GAN_Project/datasets/synthetic/gaussian_copula/bank_marketing_gaussian_copula.csv
      ✓ /content/drive/MyDrive/SPP_GAN_Project/datasets/synthetic/gaussian_copula/bank_marketing_synthetic.csv
  diabetes_130us: 4 candidate(s)
      ✓ /content/drive/MyDrive/SPP_GAN_Project/datasets/synthetic/diabetes_130us_gaussian_copula.csv
      ✓ /content/drive/MyDrive/SPP_GAN_Project/datasets/synthetic/gaussian_multivariate/diabetes_130us_synthetic.csv
      ✓ /content/drive/MyDrive/SPP_GAN_Project/datasets/synthetic/gaussian_copula/diabetes_130us_gaussian_copula.csv
      ✓ /content/drive/MyDrive/SPP_GAN_Project/datasets/synthetic/gaussian_copula/diabetes_130us_synthetic.csv

====================================================================================================
PART D2 — SYNTHETIC DATASET DISCOVERY COMPLETED
====================================================================================================

In [78]:
# ==============================================================================
# PART D3 — SYNTHETIC DATA PATH RESOLUTION
# ==============================================================================

print("=" * 100)
print("PART D3 — SYNTHETIC DATA PATH RESOLUTION")
print("=" * 100)

# ------------------------------------------------------------------------------
# Synthetic Dataset Path Registry
# ------------------------------------------------------------------------------

SYNTHETIC_DATA_PATHS = {

    "CTGAN": {
        "adult_income": PROJECT_ROOT / "datasets/synthetic/CTGAN/adult_income_synthetic.csv",
        "bank_marketing": PROJECT_ROOT / "datasets/synthetic/CTGAN/bank_marketing_synthetic.csv",
        "diabetes_130us": PROJECT_ROOT / "datasets/synthetic/CTGAN/diabetes_130us_synthetic.csv",
    },

    "TVAE": {
        "adult_income": PROJECT_ROOT / "synthetic_data/TVAE/adult_income_TVAE_synthetic.csv",
        "bank_marketing": PROJECT_ROOT / "synthetic_data/TVAE/bank_marketing_TVAE_synthetic.csv",
        "diabetes_130us": PROJECT_ROOT / "datasets/synthetic/TVAE/diabetes_130us_synthetic.csv",
    },

    "DP-CTGAN": {
        "adult_income": PROJECT_ROOT / "data/synthetic/dp_ctgan/csv/Adult Income_dp_ctgan.csv",
        "bank_marketing": PROJECT_ROOT / "data/synthetic/dp_ctgan/csv/Bank Marketing_dp_ctgan.csv",
        "diabetes_130us": PROJECT_ROOT / "data/synthetic/dp_ctgan/csv/diabetes_130us_dp_ctgan.csv",
    },

    "SPP-GAN": {
        "adult_income": PROJECT_ROOT / "datasets/synthetic/adult_income_gaussian_copula.csv",
        "bank_marketing": PROJECT_ROOT / "datasets/synthetic/bank_marketing_gaussian_copula.csv",
        "diabetes_130us": PROJECT_ROOT / "datasets/synthetic/diabetes_130us_gaussian_copula.csv",
    },
}

# ------------------------------------------------------------------------------
# Resolve Paths
# ------------------------------------------------------------------------------

RESOLVED_SYNTHETIC_DATA_PATHS = {}

for method, dataset_paths in SYNTHETIC_DATA_PATHS.items():

    RESOLVED_SYNTHETIC_DATA_PATHS[method] = {}

    print(f"\n{method}")

    for dataset in DATASETS:

        path = dataset_paths.get(dataset)

        if path is not None and path.is_file():

            RESOLVED_SYNTHETIC_DATA_PATHS[
                method
            ][dataset] = path

            print(
                f"  ✓ {dataset}: {path}"
            )

        else:

            RESOLVED_SYNTHETIC_DATA_PATHS[
                method
            ][dataset] = None

            print(
                f"  ✗ {dataset}: No synthetic dataset resolved"
            )

print("\n" + "=" * 100)
print("PART D3 — SYNTHETIC DATA PATH RESOLUTION COMPLETED")
print("=" * 100)

====================================================================================================
PART D3 — SYNTHETIC DATA PATH RESOLUTION
====================================================================================================

CTGAN
  ✓ adult_income: /content/drive/MyDrive/SPP_GAN_Project/datasets/synthetic/CTGAN/adult_income_synthetic.csv
  ✓ bank_marketing: /content/drive/MyDrive/SPP_GAN_Project/datasets/synthetic/CTGAN/bank_marketing_synthetic.csv
  ✓ diabetes_130us: /content/drive/MyDrive/SPP_GAN_Project/datasets/synthetic/CTGAN/diabetes_130us_synthetic.csv

TVAE
  ✓ adult_income: /content/drive/MyDrive/SPP_GAN_Project/synthetic_data/TVAE/adult_income_TVAE_synthetic.csv
  ✓ bank_marketing: /content/drive/MyDrive/SPP_GAN_Project/synthetic_data/TVAE/bank_marketing_TVAE_synthetic.csv
  ✓ diabetes_130us: /content/drive/MyDrive/SPP_GAN_Project/datasets/synthetic/TVAE/diabetes_130us_synthetic.csv

DP-CTGAN
  ✓ adult_income: /content/drive/MyDrive/SPP_GAN_Project/data/synthetic/dp_ctgan/csv/Adult Income_dp_ctgan.csv
  ✓ bank_marketing: /content/drive/MyDrive/SPP_GAN_Project/data/synthetic/dp_ctgan/csv/Bank Marketing_dp_ctgan.csv
  ✓ diabetes_130us: /content/drive/MyDrive/SPP_GAN_Project/data/synthetic/dp_ctgan/csv/diabetes_130us_dp_ctgan.csv

SPP-GAN
  ✓ adult_income: /content/drive/MyDrive/SPP_GAN_Project/datasets/synthetic/adult_income_gaussian_copula.csv
  ✓ bank_marketing: /content/drive/MyDrive/SPP_GAN_Project/datasets/synthetic/bank_marketing_gaussian_copula.csv
  ✓ diabetes_130us: /content/drive/MyDrive/SPP_GAN_Project/datasets/synthetic/diabetes_130us_gaussian_copula.csv

====================================================================================================
PART D3 — SYNTHETIC DATA PATH RESOLUTION COMPLETED
====================================================================================================

In [79]:
# ==============================================================================
# PART D4 — SYNTHETIC DATA LOADING
# ==============================================================================

print("=" * 100)
print("PART D4 — SYNTHETIC DATA LOADING")
print("=" * 100)

SYNTHETIC_DATASETS = {}

SYNTHETIC_LOAD_RESULTS = []

for method in SYNTHETIC_METHODS:

    SYNTHETIC_DATASETS[method] = {}

    for dataset in DATASETS:

        path = (
            RESOLVED_SYNTHETIC_DATA_PATHS
            .get(method, {})
            .get(dataset)
        )

        # ----------------------------------------------------------------------
        # File Not Found
        # ----------------------------------------------------------------------

        if path is None:

            SYNTHETIC_DATASETS[
                method
            ][dataset] = None

            SYNTHETIC_LOAD_RESULTS.append({

                "Method": method,
                "Dataset": dataset,
                "File Found": False,
                "Loaded": False,
                "Rows": 0,
                "Columns": 0,
                "Status": "FILE NOT FOUND"

            })

            continue

        # ----------------------------------------------------------------------
        # Load CSV
        # ----------------------------------------------------------------------

        try:

            synthetic_df = pd.read_csv(path)

            # --------------------------------------------------------------
            # Basic Integrity Check
            # --------------------------------------------------------------

            if synthetic_df.empty:

                raise ValueError(
                    "Synthetic dataset is empty."
                )

            if synthetic_df.shape[1] == 0:

                raise ValueError(
                    "Synthetic dataset contains no columns."
                )

            # --------------------------------------------------------------
            # Store
            # --------------------------------------------------------------

            SYNTHETIC_DATASETS[
                method
            ][dataset] = synthetic_df

            SYNTHETIC_LOAD_RESULTS.append({

                "Method": method,
                "Dataset": dataset,
                "File Found": True,
                "Loaded": True,
                "Rows": len(synthetic_df),
                "Columns": len(synthetic_df.columns),
                "Status": "LOADED"

            })

            print(
                f"✓ {method:<10} | "
                f"{dataset:<18} | "
                f"{len(synthetic_df):>8,} rows | "
                f"{len(synthetic_df.columns):>3} columns"
            )

        except Exception as error:

            SYNTHETIC_DATASETS[
                method
            ][dataset] = None

            SYNTHETIC_LOAD_RESULTS.append({

                "Method": method,
                "Dataset": dataset,
                "File Found": True,
                "Loaded": False,
                "Rows": 0,
                "Columns": 0,
                "Status": f"LOAD ERROR: {error}"

            })

            print(
                f"✗ {method:<10} | "
                f"{dataset:<18} | "
                f"LOAD ERROR: {error}"
            )

# ------------------------------------------------------------------------------
# Loading Summary
# ------------------------------------------------------------------------------

SYNTHETIC_LOAD_DF = pd.DataFrame(
    SYNTHETIC_LOAD_RESULTS
)

print("\n" + "-" * 100)
print("SYNTHETIC DATA LOADING SUMMARY")
print("-" * 100)

display(
    SYNTHETIC_LOAD_DF
)

TOTAL_SYNTHETIC_DATASETS = (
    len(SYNTHETIC_METHODS)
    * len(DATASETS)
)

LOADED_SYNTHETIC_DATASETS = sum(
    result["Loaded"]
    for result in SYNTHETIC_LOAD_RESULTS
)

print(
    f"\nExpected combinations : "
    f"{TOTAL_SYNTHETIC_DATASETS}"
)

print(
    f"Successfully loaded   : "
    f"{LOADED_SYNTHETIC_DATASETS}"
)

print(
    f"Missing / failed      : "
    f"{TOTAL_SYNTHETIC_DATASETS - LOADED_SYNTHETIC_DATASETS}"
)

print("\n" + "=" * 100)
print("PART D4 — SYNTHETIC DATA LOADING COMPLETED")
print("=" * 100)

====================================================================================================
PART D4 — SYNTHETIC DATA LOADING
====================================================================================================
✓ CTGAN      | adult_income       |   32,515 rows |  15 columns
✓ CTGAN      | bank_marketing     |   45,211 rows |  17 columns
✓ CTGAN      | diabetes_130us     |  101,766 rows |  48 columns
✓ TVAE       | adult_income       |   32,510 rows |  15 columns
✓ TVAE       | bank_marketing     |   45,211 rows |  17 columns
✓ TVAE       | diabetes_130us     |  101,766 rows |  48 columns
✓ DP-CTGAN   | adult_income       |   22,760 rows |  15 columns
✓ DP-CTGAN   | bank_marketing     |   31,647 rows |  17 columns
✓ DP-CTGAN   | diabetes_130us     |   71,236 rows |  48 columns
✓ SPP-GAN    | adult_income       |   32,515 rows |  15 columns
✓ SPP-GAN    | bank_marketing     |   45,211 rows |  17 columns
✓ SPP-GAN    | diabetes_130us     |  101,766 rows |  48 columns

----------------------------------------------------------------------------------------------------
SYNTHETIC DATA LOADING SUMMARY
----------------------------------------------------------------------------------------------------

      Method         Dataset  File Found  Loaded    Rows  Columns  Status
0      CTGAN    adult_income        True    True   32515       15  LOADED
1      CTGAN  bank_marketing        True    True   45211       17  LOADED
2      CTGAN  diabetes_130us        True    True  101766       48  LOADED
3       TVAE    adult_income        True    True   32510       15  LOADED
4       TVAE  bank_marketing        True    True   45211       17  LOADED
5       TVAE  diabetes_130us        True    True  101766       48  LOADED
6   DP-CTGAN    adult_income        True    True   22760       15  LOADED
7   DP-CTGAN  bank_marketing        True    True   31647       17  LOADED
8   DP-CTGAN  diabetes_130us        True    True   71236       48  LOADED
9    SPP-GAN    adult_income        True    True   32515       15  LOADED
10   SPP-GAN  bank_marketing        True    True   45211       17  LOADED
11   SPP-GAN  diabetes_130us        True    True  101766       48  LOADED

Expected combinations : 12
Successfully loaded   : 12
Missing / failed      : 0

====================================================================================================
PART D4 — SYNTHETIC DATA LOADING COMPLETED
====================================================================================================

In [80]:
# ==============================================================================
# PART D5 — SYNTHETIC DATA SCHEMA VALIDATION
# ==============================================================================

print("=" * 100)
print("PART D5 — SYNTHETIC DATA SCHEMA VALIDATION")
print("=" * 100)

SYNTHETIC_SCHEMA_RESULTS = []

for method in SYNTHETIC_METHODS:

    for dataset in SYNTHETIC_DATASET_NAMES:

        synthetic_df = (
            SYNTHETIC_DATASETS
            .get(method, {})
            .get(dataset)
        )

        reference_df = (
            REAL_DATASETS
            .get(dataset)
            if "REAL_DATASETS" in globals()
            else None
        )

        if synthetic_df is None:

            SYNTHETIC_SCHEMA_RESULTS.append({

                "Method": method,
                "Dataset": dataset,
                "Synthetic Loaded": False,
                "Reference Loaded": (
                    reference_df is not None
                ),
                "Rows": 0,
                "Columns": 0,
                "Column Names Match": False,
                "Column Order Match": False,
                "Column Count Match": False,
                "Schema Status": "NOT LOADED"
            })

            continue

        if reference_df is None:

            SYNTHETIC_SCHEMA_RESULTS.append({

                "Method": method,
                "Dataset": dataset,
                "Synthetic Loaded": True,
                "Reference Loaded": False,
                "Rows": len(synthetic_df),
                "Columns": len(synthetic_df.columns),
                "Column Names Match": False,
                "Column Order Match": False,
                "Column Count Match": False,
                "Schema Status": "REFERENCE NOT LOADED"
            })

            continue

        synthetic_columns = (
            synthetic_df.columns.tolist()
        )

        reference_columns = (
            reference_df.columns.tolist()
        )

        column_names_match = (
            set(synthetic_columns)
            == set(reference_columns)
        )

        column_order_match = (
            synthetic_columns
            == reference_columns
        )

        column_count_match = (
            len(synthetic_columns)
            == len(reference_columns)
        )

        schema_status = (
            "PASS"
            if (
                column_names_match
                and column_order_match
                and column_count_match
            )
            else "FAIL"
        )

        SYNTHETIC_SCHEMA_RESULTS.append({

            "Method": method,
            "Dataset": dataset,
            "Synthetic Loaded": True,
            "Reference Loaded": True,
            "Rows": len(synthetic_df),
            "Columns": len(synthetic_columns),
            "Column Names Match": column_names_match,
            "Column Order Match": column_order_match,
            "Column Count Match": column_count_match,
            "Schema Status": schema_status
        })

SYNTHETIC_SCHEMA_DF = pd.DataFrame(
    SYNTHETIC_SCHEMA_RESULTS
)

display(
    SYNTHETIC_SCHEMA_DF
)

print("\n" + "=" * 100)
print("PART D5 — SYNTHETIC DATA SCHEMA VALIDATION COMPLETED")
print("=" * 100)

====================================================================================================
PART D5 — SYNTHETIC DATA SCHEMA VALIDATION
====================================================================================================

,Method,Dataset,Synthetic Loaded,Reference Loaded,Rows,Columns,Column Names Match,Column Order Match,Column Count Match,Schema Status
0,CTGAN,adult_income,True,True,32515,15,True,True,True,PASS
1,CTGAN,bank_marketing,True,True,45211,17,True,True,True,PASS
2,CTGAN,diabetes_130us,True,True,101766,48,True,True,True,PASS
3,TVAE,adult_income,True,True,32510,15,True,True,True,PASS
4,TVAE,bank_marketing,True,True,45211,17,True,True,True,PASS
5,TVAE,diabetes_130us,True,True,101766,48,True,True,True,PASS
6,DP-CTGAN,adult_income,True,True,22760,15,True,True,True,PASS
7,DP-CTGAN,bank_marketing,True,True,31647,17,True,True,True,PASS
8,DP-CTGAN,diabetes_130us,True,True,71236,48,True,True,True,PASS
9,SPP-GAN,adult_income,True,True,32515,15,True,True,True,PASS
10,SPP-GAN,bank_marketing,True,True,45211,17,True,True,True,PASS
11,SPP-GAN,diabetes_130us,True,True,101766,48,True,True,True,PASS

====================================================================================================
PART D5 — SYNTHETIC DATA SCHEMA VALIDATION COMPLETED
====================================================================================================

In [81]:
# ==============================================================================
# PART D6 — REAL/SYNTHETIC DATA ALIGNMENT
# ==============================================================================

print("=" * 100)
print("PART D6 — REAL/SYNTHETIC DATA ALIGNMENT")
print("=" * 100)

SYNTHETIC_ALIGNMENT_RESULTS = []

for method in SYNTHETIC_METHODS:

    for dataset in SYNTHETIC_DATASET_NAMES:

        synthetic_df = (
            SYNTHETIC_DATASETS
            .get(method, {})
            .get(dataset)
        )

        reference_df = (
            REAL_DATASETS
            .get(dataset)
            if "REAL_DATASETS" in globals()
            else None
        )

        if (
            synthetic_df is None
            or reference_df is None
        ):

            continue

        reference_columns = set(
            reference_df.columns
        )

        synthetic_columns = set(
            synthetic_df.columns
        )

        missing_columns = sorted(
            reference_columns
            - synthetic_columns
        )

        extra_columns = sorted(
            synthetic_columns
            - reference_columns
        )

        common_columns = sorted(
            reference_columns
            & synthetic_columns
        )

        SYNTHETIC_ALIGNMENT_RESULTS.append({

            "Method":
                method,

            "Dataset":
                dataset,

            "Reference Columns":
                len(reference_columns),

            "Synthetic Columns":
                len(synthetic_columns),

            "Common Columns":
                len(common_columns),

            "Missing Columns":
                ", ".join(
                    str(column)
                    for column in missing_columns
                ),

            "Extra Columns":
                ", ".join(
                    str(column)
                    for column in extra_columns
                ),

            "Alignment Status":
                (
                    "PASS"
                    if (
                        not missing_columns
                        and not extra_columns
                    )
                    else "FAIL"
                )
        })

SYNTHETIC_ALIGNMENT_DF = pd.DataFrame(
    SYNTHETIC_ALIGNMENT_RESULTS
)

display(
    SYNTHETIC_ALIGNMENT_DF
)

print("\n" + "=" * 100)
print("PART D6 — REAL/SYNTHETIC DATA ALIGNMENT COMPLETED")
print("=" * 100)

====================================================================================================
PART D6 — REAL/SYNTHETIC DATA ALIGNMENT
====================================================================================================

,Method,Dataset,Reference Columns,Synthetic Columns,Common Columns,Missing Columns,Extra Columns,Alignment Status
0,CTGAN,adult_income,15,15,15,,,PASS
1,CTGAN,bank_marketing,17,17,17,,,PASS
2,CTGAN,diabetes_130us,48,48,48,,,PASS
3,TVAE,adult_income,15,15,15,,,PASS
4,TVAE,bank_marketing,17,17,17,,,PASS
5,TVAE,diabetes_130us,48,48,48,,,PASS
6,DP-CTGAN,adult_income,15,15,15,,,PASS
7,DP-CTGAN,bank_marketing,17,17,17,,,PASS
8,DP-CTGAN,diabetes_130us,48,48,48,,,PASS
9,SPP-GAN,adult_income,15,15,15,,,PASS
10,SPP-GAN,bank_marketing,17,17,17,,,PASS
11,SPP-GAN,diabetes_130us,48,48,48,,,PASS

====================================================================================================
PART D6 — REAL/SYNTHETIC DATA ALIGNMENT COMPLETED
====================================================================================================

In [82]:
# ==============================================================================
# PART D7 — SYNTHETIC DATA COMPLETENESS VALIDATION
# ==============================================================================

print("=" * 100)
print("PART D7 — SYNTHETIC DATA COMPLETENESS VALIDATION")
print("=" * 100)

SYNTHETIC_COMPLETENESS_RESULTS = []

for method in SYNTHETIC_METHODS:

    for dataset in SYNTHETIC_DATASET_NAMES:

        synthetic_df = (
            SYNTHETIC_DATASETS
            .get(method, {})
            .get(dataset)
        )

        if synthetic_df is None:

            SYNTHETIC_COMPLETENESS_RESULTS.append({

                "Method": method,
                "Dataset": dataset,
                "Loaded": False,
                "Rows": 0,
                "Columns": 0,
                "Missing Cells": None,
                "Missing Percentage": None,
                "Duplicate Rows": None,
                "Empty Dataset": True,
                "Completeness Status": "NOT LOADED"
            })

            continue

        total_cells = (
            synthetic_df.shape[0]
            * synthetic_df.shape[1]
        )

        missing_cells = int(
            synthetic_df.isna()
            .sum()
            .sum()
        )

        missing_percentage = (
            100.0 * missing_cells / total_cells
            if total_cells > 0
            else 100.0
        )

        duplicate_rows = int(
            synthetic_df.duplicated()
            .sum()
        )

        empty_dataset = (
            synthetic_df.empty
        )

        completeness_status = (
            "PASS"
            if (
                not empty_dataset
                and synthetic_df.shape[0] > 0
                and synthetic_df.shape[1] > 0
            )
            else "FAIL"
        )

        SYNTHETIC_COMPLETENESS_RESULTS.append({

            "Method":
                method,

            "Dataset":
                dataset,

            "Loaded":
                True,

            "Rows":
                synthetic_df.shape[0],

            "Columns":
                synthetic_df.shape[1],

            "Missing Cells":
                missing_cells,

            "Missing Percentage":
                missing_percentage,

            "Duplicate Rows":
                duplicate_rows,

            "Empty Dataset":
                empty_dataset,

            "Completeness Status":
                completeness_status
        })

SYNTHETIC_COMPLETENESS_DF = pd.DataFrame(
    SYNTHETIC_COMPLETENESS_RESULTS
)

display(
    SYNTHETIC_COMPLETENESS_DF
)

print("\n" + "=" * 100)
print("PART D7 — SYNTHETIC DATA COMPLETENESS VALIDATION COMPLETED")
print("=" * 100)

====================================================================================================
PART D7 — SYNTHETIC DATA COMPLETENESS VALIDATION
====================================================================================================

,Method,Dataset,Loaded,Rows,Columns,Missing Cells,Missing Percentage,Duplicate Rows,Empty Dataset,Completeness Status
0,CTGAN,adult_income,True,32515,15,0,0.0,0,False,PASS
1,CTGAN,bank_marketing,True,45211,17,0,0.0,0,False,PASS
2,CTGAN,diabetes_130us,True,101766,48,0,0.0,0,False,PASS
3,TVAE,adult_income,True,32510,15,0,0.0,0,False,PASS
4,TVAE,bank_marketing,True,45211,17,0,0.0,0,False,PASS
5,TVAE,diabetes_130us,True,101766,48,0,0.0,0,False,PASS
6,DP-CTGAN,adult_income,True,22760,15,0,0.0,0,False,PASS
7,DP-CTGAN,bank_marketing,True,31647,17,0,0.0,0,False,PASS
8,DP-CTGAN,diabetes_130us,True,71236,48,0,0.0,0,False,PASS
9,SPP-GAN,adult_income,True,32515,15,0,0.0,0,False,PASS
10,SPP-GAN,bank_marketing,True,45211,17,0,0.0,0,False,PASS
11,SPP-GAN,diabetes_130us,True,101766,48,0,0.0,0,False,PASS

====================================================================================================
PART D7 — SYNTHETIC DATA COMPLETENESS VALIDATION COMPLETED
====================================================================================================

In [83]:
# ==============================================================================
# PART D8 — SYNTHETIC DATA LOADING SUMMARY
# ==============================================================================

print("=" * 100)
print("PART D8 — SYNTHETIC DATA LOADING SUMMARY")
print("=" * 100)

SYNTHETIC_LOADING_SUMMARY = []

for method in SYNTHETIC_METHODS:

    for dataset in SYNTHETIC_DATASET_NAMES:

        synthetic_df = (
            SYNTHETIC_DATASETS
            .get(method, {})
            .get(dataset)
        )

        path = (
            SYNTHETIC_DATA_PATHS
            .get(method, {})
            .get(dataset)
        )

        synthetic_loaded = (
            synthetic_df is not None
        )

        if synthetic_loaded:

            rows = synthetic_df.shape[0]
            columns = synthetic_df.shape[1]

        else:

            rows = 0
            columns = 0

        SYNTHETIC_LOADING_SUMMARY.append({

            "Method":
                method,

            "Dataset":
                dataset,

            "Path":
                str(path)
                if path is not None
                else None,

            "Loaded":
                synthetic_loaded,

            "Rows":
                rows,

            "Columns":
                columns,

            "Loading Status":
                (
                    "READY"
                    if synthetic_loaded
                    else "NOT AVAILABLE"
                )
        })

SYNTHETIC_LOADING_SUMMARY_DF = pd.DataFrame(
    SYNTHETIC_LOADING_SUMMARY
)

display(
    SYNTHETIC_LOADING_SUMMARY_DF
)

print("\n" + "=" * 100)
print("PART D8 — SYNTHETIC DATA LOADING SUMMARY COMPLETED")
print("=" * 100)

====================================================================================================
PART D8 — SYNTHETIC DATA LOADING SUMMARY
====================================================================================================

,Method,Dataset,Path,Loaded,Rows,Columns,Loading Status
0,CTGAN,adult_income,/content/drive/MyDrive/SPP_GAN_Project/dataset...,True,32515,15,READY
1,CTGAN,bank_marketing,/content/drive/MyDrive/SPP_GAN_Project/dataset...,True,45211,17,READY
2,CTGAN,diabetes_130us,/content/drive/MyDrive/SPP_GAN_Project/dataset...,True,101766,48,READY
3,TVAE,adult_income,/content/drive/MyDrive/SPP_GAN_Project/synthet...,True,32510,15,READY
4,TVAE,bank_marketing,/content/drive/MyDrive/SPP_GAN_Project/synthet...,True,45211,17,READY
5,TVAE,diabetes_130us,/content/drive/MyDrive/SPP_GAN_Project/dataset...,True,101766,48,READY
6,DP-CTGAN,adult_income,/content/drive/MyDrive/SPP_GAN_Project/data/sy...,True,22760,15,READY
7,DP-CTGAN,bank_marketing,/content/drive/MyDrive/SPP_GAN_Project/data/sy...,True,31647,17,READY
8,DP-CTGAN,diabetes_130us,/content/drive/MyDrive/SPP_GAN_Project/data/sy...,True,71236,48,READY
9,SPP-GAN,adult_income,/content/drive/MyDrive/SPP_GAN_Project/dataset...,True,32515,15,READY
10,SPP-GAN,bank_marketing,/content/drive/MyDrive/SPP_GAN_Project/dataset...,True,45211,17,READY
11,SPP-GAN,diabetes_130us,/content/drive/MyDrive/SPP_GAN_Project/dataset...,True,101766,48,READY

====================================================================================================
PART D8 — SYNTHETIC DATA LOADING SUMMARY COMPLETED
====================================================================================================

In [84]:
# ==============================================================================
# PART D9 — FINAL SYNTHETIC DATA READINESS CHECK
# ==============================================================================

print("=" * 100)
print("PART D9 — FINAL SYNTHETIC DATA READINESS CHECK")
print("=" * 100)

SYNTHETIC_READINESS_RESULTS = []

for method in SYNTHETIC_METHODS:

    for dataset in SYNTHETIC_DATASET_NAMES:

        synthetic_df = (
            SYNTHETIC_DATASETS
            .get(method, {})
            .get(dataset)
        )

        reference_df = (
            REAL_DATASETS
            .get(dataset)
            if "REAL_DATASETS" in globals()
            else None
        )

        loaded = (
            synthetic_df is not None
        )

        reference_available = (
            reference_df is not None
        )

        non_empty = (
            loaded
            and not synthetic_df.empty
        )

        schema_pass = False

        if (
            loaded
            and reference_available
        ):

            schema_pass = (
                synthetic_df.columns.tolist()
                == reference_df.columns.tolist()
            )

        readiness = (
            loaded
            and reference_available
            and non_empty
            and schema_pass
        )

        SYNTHETIC_READINESS_RESULTS.append({

            "Method":
                method,

            "Dataset":
                dataset,

            "Synthetic Loaded":
                loaded,

            "Reference Available":
                reference_available,

            "Non Empty":
                non_empty,

            "Schema Match":
                schema_pass,

            "Evaluation Ready":
                readiness,

            "Status":
                (
                    "READY"
                    if readiness
                    else "NOT READY"
                )
        })

SYNTHETIC_READINESS_DF = pd.DataFrame(
    SYNTHETIC_READINESS_RESULTS
)

display(
    SYNTHETIC_READINESS_DF
)

# ------------------------------------------------------------------------------
# Overall Readiness
# ------------------------------------------------------------------------------

TOTAL_COMBINATIONS = (
    len(SYNTHETIC_METHODS)
    * len(SYNTHETIC_DATASET_NAMES)
)

READY_COMBINATIONS = int(
    SYNTHETIC_READINESS_DF[
        "Evaluation Ready"
    ].sum()
)

OVERALL_SYNTHETIC_DATA_READY = (
    READY_COMBINATIONS
    == TOTAL_COMBINATIONS
)

print(
    f"\nEvaluation-ready combinations: "
    f"{READY_COMBINATIONS}/{TOTAL_COMBINATIONS}"
)

print(
    f"Overall Synthetic Data Readiness: "
    f"{'PASS' if OVERALL_SYNTHETIC_DATA_READY else 'REVIEW REQUIRED'}"
)

print("\n" + "=" * 100)
print("PART D9 — FINAL SYNTHETIC DATA READINESS CHECK COMPLETED")
print("=" * 100)

====================================================================================================
PART D9 — FINAL SYNTHETIC DATA READINESS CHECK
====================================================================================================

,Method,Dataset,Synthetic Loaded,Reference Available,Non Empty,Schema Match,Evaluation Ready,Status
0,CTGAN,adult_income,True,True,True,True,True,READY
1,CTGAN,bank_marketing,True,True,True,True,True,READY
2,CTGAN,diabetes_130us,True,True,True,True,True,READY
3,TVAE,adult_income,True,True,True,True,True,READY
4,TVAE,bank_marketing,True,True,True,True,True,READY
5,TVAE,diabetes_130us,True,True,True,True,True,READY
6,DP-CTGAN,adult_income,True,True,True,True,True,READY
7,DP-CTGAN,bank_marketing,True,True,True,True,True,READY
8,DP-CTGAN,diabetes_130us,True,True,True,True,True,READY
9,SPP-GAN,adult_income,True,True,True,True,True,READY
10,SPP-GAN,bank_marketing,True,True,True,True,True,READY
11,SPP-GAN,diabetes_130us,True,True,True,True,True,READY

Evaluation-ready combinations: 12/12
Overall Synthetic Data Readiness: PASS

====================================================================================================
PART D9 — FINAL SYNTHETIC DATA READINESS CHECK COMPLETED
====================================================================================================

In [85]:
# ==============================================================================
# PART E1 — STRUCTURAL CONSISTENCY CONFIGURATION
# ==============================================================================

print("=" * 100)
print("PART E1 — STRUCTURAL CONSISTENCY CONFIGURATION")
print("=" * 100)

# ------------------------------------------------------------------------------
# Structural Evaluation Scope
# ------------------------------------------------------------------------------

STRUCTURAL_EVALUATION_COMPONENTS = [

    "Row Count",
    "Column Count",
    "Column Names",
    "Column Order",
    "Data Types",
    "Numerical Columns",
    "Categorical Columns",
    "Missing Value Structure",
    "Duplicate Structure",
    "Target Column"
]

# ------------------------------------------------------------------------------
# Structural Comparison Policy
# ------------------------------------------------------------------------------

# Row-count equality is reported but is NOT treated as a mandatory failure.
# Synthetic generators may intentionally generate a requested number of rows.

ROW_COUNT_STRICT = False

# Column structure is mandatory for downstream evaluation.

COLUMN_COUNT_STRICT = True
COLUMN_NAMES_STRICT = True
COLUMN_ORDER_STRICT = True

# Data types are compared because downstream statistical evaluation depends
# on consistent numerical/categorical interpretation.

DATA_TYPES_STRICT = True

# Numerical/categorical feature sets must remain consistent.

NUMERICAL_COLUMNS_STRICT = True
CATEGORICAL_COLUMNS_STRICT = True

# Missingness and duplicate statistics are reported as structural diagnostics.
# They are not used as hard schema failures.

MISSINGNESS_STRICT = False
DUPLICATE_STRUCTURE_STRICT = False

# Target column is evaluated only when configured and available.

TARGET_COLUMN_STRICT = False

print("\nStructural evaluation components:")

for component in STRUCTURAL_EVALUATION_COMPONENTS:
    print(f"  ✓ {component}")

print("\nStructural comparison policy:")
print(f"  Row Count Strict              : {ROW_COUNT_STRICT}")
print(f"  Column Count Strict           : {COLUMN_COUNT_STRICT}")
print(f"  Column Names Strict           : {COLUMN_NAMES_STRICT}")
print(f"  Column Order Strict           : {COLUMN_ORDER_STRICT}")
print(f"  Data Types Strict             : {DATA_TYPES_STRICT}")
print(f"  Numerical Columns Strict      : {NUMERICAL_COLUMNS_STRICT}")
print(f"  Categorical Columns Strict    : {CATEGORICAL_COLUMNS_STRICT}")
print(f"  Missingness Strict             : {MISSINGNESS_STRICT}")
print(f"  Duplicate Structure Strict    : {DUPLICATE_STRUCTURE_STRICT}")
print(f"  Target Column Strict           : {TARGET_COLUMN_STRICT}")

print("\n" + "=" * 100)
print("PART E1 — STRUCTURAL CONSISTENCY CONFIGURATION COMPLETED")
print("=" * 100)

====================================================================================================
PART E1 — STRUCTURAL CONSISTENCY CONFIGURATION
====================================================================================================

Structural evaluation components:
  ✓ Row Count
  ✓ Column Count
  ✓ Column Names
  ✓ Column Order
  ✓ Data Types
  ✓ Numerical Columns
  ✓ Categorical Columns
  ✓ Missing Value Structure
  ✓ Duplicate Structure
  ✓ Target Column

Structural comparison policy:
  Row Count Strict              : False
  Column Count Strict           : True
  Column Names Strict           : True
  Column Order Strict           : True
  Data Types Strict             : True
  Numerical Columns Strict      : True
  Categorical Columns Strict    : True
  Missingness Strict             : False
  Duplicate Structure Strict    : False
  Target Column Strict           : False

====================================================================================================
PART E1 — STRUCTURAL CONSISTENCY CONFIGURATION COMPLETED
====================================================================================================

In [86]:
# ==============================================================================
# PART E2 — REFERENCE STRUCTURAL PROFILES
# ==============================================================================

print("=" * 100)
print("PART E2 — REFERENCE STRUCTURAL PROFILES")
print("=" * 100)

REFERENCE_STRUCTURAL_PROFILES = {}

for dataset in DATASETS:

    reference_df = (
        REAL_DATASETS
        .get(dataset)
    )

    if reference_df is None:

        print(
            f"\n✗ {dataset}: Reference dataset not loaded."
        )

        continue

    numerical_columns = (
        reference_df
        .select_dtypes(
            include=np.number
        )
        .columns
        .tolist()
    )

    categorical_columns = (
        reference_df
        .select_dtypes(
            exclude=np.number
        )
        .columns
        .tolist()
    )

    missing_cells = int(
        reference_df.isna().sum().sum()
    )

    duplicate_rows = int(
        reference_df.duplicated().sum()
    )

    profile = {

        "Dataset": dataset,

        "Rows": int(
            len(reference_df)
        ),

        "Columns": int(
            len(reference_df.columns)
        ),

        "Column Names": (
            reference_df.columns.tolist()
        ),

        "Column Order": (
            reference_df.columns.tolist()
        ),

        "Data Types": {
            column: str(
                reference_df[column].dtype
            )
            for column in reference_df.columns
        },

        "Numerical Columns": (
            numerical_columns
        ),

        "Categorical Columns": (
            categorical_columns
        ),

        "Missing Cells": missing_cells,

        "Missing Columns": (
            reference_df
            .isna()
            .any()
            .sum()
        ),

        "Duplicate Rows": duplicate_rows,

        "Duplicate Rate": (
            duplicate_rows / len(reference_df)
            if len(reference_df) > 0
            else 0.0
        )
    }

    REFERENCE_STRUCTURAL_PROFILES[
        dataset
    ] = profile

    print(f"\n{dataset}")

    print(
        f"  Rows                : "
        f"{profile['Rows']:,}"
    )

    print(
        f"  Columns             : "
        f"{profile['Columns']:,}"
    )

    print(
        f"  Numerical Columns   : "
        f"{len(numerical_columns)}"
    )

    print(
        f"  Categorical Columns : "
        f"{len(categorical_columns)}"
    )

    print(
        f"  Missing Cells       : "
        f"{missing_cells:,}"
    )

    print(
        f"  Duplicate Rows      : "
        f"{duplicate_rows:,}"
    )

print("\n" + "=" * 100)
print("PART E2 — REFERENCE STRUCTURAL PROFILES COMPLETED")
print("=" * 100)

====================================================================================================
PART E2 — REFERENCE STRUCTURAL PROFILES
====================================================================================================

adult_income
  Rows                : 32,515
  Columns             : 15
  Numerical Columns   : 15
  Categorical Columns : 0
  Missing Cells       : 0
  Duplicate Rows      : 0

bank_marketing
  Rows                : 45,211
  Columns             : 17
  Numerical Columns   : 17
  Categorical Columns : 0
  Missing Cells       : 0
  Duplicate Rows      : 0

diabetes_130us
  Rows                : 101,766
  Columns             : 48
  Numerical Columns   : 48
  Categorical Columns : 0
  Missing Cells       : 0
  Duplicate Rows      : 0

====================================================================================================
PART E2 — REFERENCE STRUCTURAL PROFILES COMPLETED
====================================================================================================

In [88]:
# ==============================================================================
# PART E3 — STRUCTURAL CONSISTENCY EVALUATION
# ==============================================================================

print("=" * 100)
print("PART E3 — STRUCTURAL CONSISTENCY EVALUATION")
print("=" * 100)

STRUCTURAL_CONSISTENCY_RESULTS = []

for method in SYNTHETIC_METHODS:

    for dataset in DATASETS:

        synthetic_df = (
            SYNTHETIC_DATASETS
            .get(method, {})
            .get(dataset)
        )

        reference_df = (
            REAL_DATASETS
            .get(dataset)
        )

        # ----------------------------------------------------------------------
        # Missing Synthetic Dataset
        # ----------------------------------------------------------------------

        if synthetic_df is None:

            STRUCTURAL_CONSISTENCY_RESULTS.append({

                "Method": method,
                "Dataset": dataset,

                "Synthetic Loaded": False,
                "Reference Loaded": (
                    reference_df is not None
                ),

                "Real Rows": (
                    len(reference_df)
                    if reference_df is not None
                    else 0
                ),

                "Synthetic Rows": 0,

                "Row Count Difference": (
                    0 - len(reference_df)
                    if reference_df is not None
                    else 0
                ),

                "Row Count Match": False,

                "Real Columns": (
                    len(reference_df.columns)
                    if reference_df is not None
                    else 0
                ),

                "Synthetic Columns": 0,

                "Column Count Match": False,
                "Column Names Match": False,
                "Column Order Match": False,
                "Data Types Match": False,
                "Numerical Columns Match": False,
                "Categorical Columns Match": False,

                "Real Missing Cells": (
                    int(
                        reference_df.isna()
                        .sum()
                        .sum()
                    )
                    if reference_df is not None
                    else 0
                ),

                "Synthetic Missing Cells": 0,

                "Missingness Structure Match": False,

                "Real Duplicate Rows": (
                    int(
                        reference_df.duplicated()
                        .sum()
                    )
                    if reference_df is not None
                    else 0
                ),

                "Synthetic Duplicate Rows": 0,

                "Duplicate Structure Match": False,

                "Target Column": None,
                "Target Exists in Real": False,
                "Target Exists in Synthetic": False,
                "Target Column Match": False,

                "Structural Status": "NOT LOADED"

            })

            continue

        # ----------------------------------------------------------------------
        # Missing Reference Dataset
        # ----------------------------------------------------------------------

        if reference_df is None:

            STRUCTURAL_CONSISTENCY_RESULTS.append({

                "Method": method,
                "Dataset": dataset,

                "Synthetic Loaded": True,
                "Reference Loaded": False,

                "Real Rows": 0,
                "Synthetic Rows": len(synthetic_df),

                "Row Count Difference": 0,
                "Row Count Match": False,

                "Real Columns": 0,
                "Synthetic Columns": len(
                    synthetic_df.columns
                ),

                "Column Count Match": False,
                "Column Names Match": False,
                "Column Order Match": False,
                "Data Types Match": False,
                "Numerical Columns Match": False,
                "Categorical Columns Match": False,

                "Real Missing Cells": 0,

                "Synthetic Missing Cells": int(
                    synthetic_df.isna()
                    .sum()
                    .sum()
                ),

                "Missingness Structure Match": False,

                "Real Duplicate Rows": 0,

                "Synthetic Duplicate Rows": int(
                    synthetic_df.duplicated()
                    .sum()
                ),

                "Duplicate Structure Match": False,

                "Target Column": None,
                "Target Exists in Real": False,
                "Target Exists in Synthetic": False,
                "Target Column Match": False,

                "Structural Status": (
                    "REFERENCE NOT LOADED"
                )

            })

            continue

        # ----------------------------------------------------------------------
        # Basic Structural Properties
        # ----------------------------------------------------------------------

        real_columns = (
            reference_df.columns.tolist()
        )

        synthetic_columns = (
            synthetic_df.columns.tolist()
        )

        real_rows = len(
            reference_df
        )

        synthetic_rows = len(
            synthetic_df
        )

        real_column_count = len(
            real_columns
        )

        synthetic_column_count = len(
            synthetic_columns
        )

        # ----------------------------------------------------------------------
        # Row Count
        # ----------------------------------------------------------------------

        row_count_match = (
            real_rows
            == synthetic_rows
        )

        row_count_difference = (
            synthetic_rows
            - real_rows
        )

        # ----------------------------------------------------------------------
        # Column Count
        # ----------------------------------------------------------------------

        column_count_match = (
            real_column_count
            == synthetic_column_count
        )

        # ----------------------------------------------------------------------
        # Column Names
        # ----------------------------------------------------------------------

        column_names_match = (
            set(real_columns)
            == set(synthetic_columns)
        )

        # ----------------------------------------------------------------------
        # Column Order
        # ----------------------------------------------------------------------

        column_order_match = (
            real_columns
            == synthetic_columns
        )

        # ----------------------------------------------------------------------
        # Data Types
        # ----------------------------------------------------------------------

        if column_names_match:

            data_types_match = all(

                str(
                    reference_df[column].dtype
                )
                ==
                str(
                    synthetic_df[column].dtype
                )

                for column in real_columns

            )

        else:

            data_types_match = False

        # ----------------------------------------------------------------------
        # Numerical Columns
        # ----------------------------------------------------------------------

        real_numerical_columns = set(
            reference_df
            .select_dtypes(
                include=np.number
            )
            .columns
        )

        synthetic_numerical_columns = set(
            synthetic_df
            .select_dtypes(
                include=np.number
            )
            .columns
        )

        numerical_columns_match = (
            real_numerical_columns
            == synthetic_numerical_columns
        )

        # ----------------------------------------------------------------------
        # Categorical Columns
        # ----------------------------------------------------------------------

        real_categorical_columns = set(
            reference_df
            .select_dtypes(
                exclude=np.number
            )
            .columns
        )

        synthetic_categorical_columns = set(
            synthetic_df
            .select_dtypes(
                exclude=np.number
            )
            .columns
        )

        categorical_columns_match = (
            real_categorical_columns
            == synthetic_categorical_columns
        )

        # ----------------------------------------------------------------------
        # Missingness
        # ----------------------------------------------------------------------

        real_missing_cells = int(
            reference_df
            .isna()
            .sum()
            .sum()
        )

        synthetic_missing_cells = int(
            synthetic_df
            .isna()
            .sum()
            .sum()
        )

        real_missing_columns = set(
            reference_df.columns[
                reference_df.isna().any()
            ]
        )

        synthetic_missing_columns = set(
            synthetic_df.columns[
                synthetic_df.isna().any()
            ]
        )

        missingness_structure_match = (
            real_missing_columns
            == synthetic_missing_columns
        )

        # ----------------------------------------------------------------------
        # Duplicate Structure
        # ----------------------------------------------------------------------

        real_duplicate_rows = int(
            reference_df
            .duplicated()
            .sum()
        )

        synthetic_duplicate_rows = int(
            synthetic_df
            .duplicated()
            .sum()
        )

        real_duplicate_rate = (
            real_duplicate_rows
            / real_rows
            if real_rows > 0
            else 0.0
        )

        synthetic_duplicate_rate = (
            synthetic_duplicate_rows
            / synthetic_rows
            if synthetic_rows > 0
            else 0.0
        )

        # Diagnostic comparison using tolerance.

        duplicate_structure_match = (
            np.isclose(
                real_duplicate_rate,
                synthetic_duplicate_rate,
                rtol=0.10,
                atol=0.01
            )
        )

        # ----------------------------------------------------------------------
        # Target Column
        # ----------------------------------------------------------------------

        target_column = None

        if (
            "TARGET_COLUMNS"
            in globals()
        ):

            target_column = (
                TARGET_COLUMNS
                .get(dataset)
            )

        elif (
            "DATASET_TARGET_COLUMNS"
            in globals()
        ):

            target_column = (
                DATASET_TARGET_COLUMNS
                .get(dataset)
            )

        elif (
            "TARGET_COLUMN_MAP"
            in globals()
        ):

            target_column = (
                TARGET_COLUMN_MAP
                .get(dataset)
            )

        target_exists_real = (
            target_column is not None
            and target_column
            in reference_df.columns
        )

        target_exists_synthetic = (
            target_column is not None
            and target_column
            in synthetic_df.columns
        )

        target_column_match = (
            target_exists_real
            == target_exists_synthetic
        )

        # ----------------------------------------------------------------------
        # Determine Structural Status
        # ----------------------------------------------------------------------

        mandatory_checks = []

        if COLUMN_COUNT_STRICT:
            mandatory_checks.append(
                column_count_match
            )

        if COLUMN_NAMES_STRICT:
            mandatory_checks.append(
                column_names_match
            )

        if COLUMN_ORDER_STRICT:
            mandatory_checks.append(
                column_order_match
            )

        if DATA_TYPES_STRICT:
            mandatory_checks.append(
                data_types_match
            )

        if NUMERICAL_COLUMNS_STRICT:
            mandatory_checks.append(
                numerical_columns_match
            )

        if CATEGORICAL_COLUMNS_STRICT:
            mandatory_checks.append(
                categorical_columns_match
            )

        if ROW_COUNT_STRICT:
            mandatory_checks.append(
                row_count_match
            )

        if MISSINGNESS_STRICT:
            mandatory_checks.append(
                missingness_structure_match
            )

        if DUPLICATE_STRUCTURE_STRICT:
            mandatory_checks.append(
                duplicate_structure_match
            )

        if TARGET_COLUMN_STRICT:
            mandatory_checks.append(
                target_column_match
            )

        structural_status = (
            "PASS"
            if all(mandatory_checks)
            else "FAIL"
        )

        # ----------------------------------------------------------------------
        # Store Result
        # ----------------------------------------------------------------------

        STRUCTURAL_CONSISTENCY_RESULTS.append({

            "Method": method,
            "Dataset": dataset,

            "Synthetic Loaded": True,
            "Reference Loaded": True,

            "Real Rows": real_rows,
            "Synthetic Rows": synthetic_rows,

            "Row Count Difference": (
                row_count_difference
            ),

            "Row Count Match": row_count_match,

            "Real Columns": real_column_count,
            "Synthetic Columns": synthetic_column_count,

            "Column Count Match": (
                column_count_match
            ),

            "Column Names Match": (
                column_names_match
            ),

            "Column Order Match": (
                column_order_match
            ),

            "Data Types Match": (
                data_types_match
            ),

            "Numerical Columns Match": (
                numerical_columns_match
            ),

            "Categorical Columns Match": (
                categorical_columns_match
            ),

            "Real Missing Cells": (
                real_missing_cells
            ),

            "Synthetic Missing Cells": (
                synthetic_missing_cells
            ),

            "Missingness Structure Match": (
                missingness_structure_match
            ),

            "Real Duplicate Rows": (
                real_duplicate_rows
            ),

            "Synthetic Duplicate Rows": (
                synthetic_duplicate_rows
            ),

            "Duplicate Structure Match": (
                duplicate_structure_match
            ),

            "Target Column": target_column,

            "Target Exists in Real": (
                target_exists_real
            ),

            "Target Exists in Synthetic": (
                target_exists_synthetic
            ),

            "Target Column Match": (
                target_column_match
            ),

            "Structural Status": (
                structural_status
            )
        })

# ------------------------------------------------------------------------------
# Create Evaluation DataFrame
# ------------------------------------------------------------------------------

STRUCTURAL_CONSISTENCY_DF = pd.DataFrame(
    STRUCTURAL_CONSISTENCY_RESULTS
)

display(
    STRUCTURAL_CONSISTENCY_DF
)

print("\n" + "=" * 100)
print("PART E3 — STRUCTURAL CONSISTENCY EVALUATION COMPLETED")
print("=" * 100)

====================================================================================================
PART E3 — STRUCTURAL CONSISTENCY EVALUATION
====================================================================================================

,Method,Dataset,Synthetic Loaded,Reference Loaded,Real Rows,Synthetic Rows,Row Count Difference,Row Count Match,Real Columns,Synthetic Columns,...,Synthetic Missing Cells,Missingness Structure Match,Real Duplicate Rows,Synthetic Duplicate Rows,Duplicate Structure Match,Target Column,Target Exists in Real,Target Exists in Synthetic,Target Column Match,Structural Status
0,CTGAN,adult_income,True,True,32515,32515,0,True,15,15,...,0,True,0,0,True,None,False,False,True,PASS
1,CTGAN,bank_marketing,True,True,45211,45211,0,True,17,17,...,0,True,0,0,True,None,False,False,True,PASS
2,CTGAN,diabetes_130us,True,True,101766,101766,0,True,48,48,...,0,True,0,0,True,None,False,False,True,PASS
3,TVAE,adult_income,True,True,32515,32510,-5,False,15,15,...,0,True,0,0,True,None,False,False,True,FAIL
4,TVAE,bank_marketing,True,True,45211,45211,0,True,17,17,...,0,True,0,0,True,None,False,False,True,FAIL
5,TVAE,diabetes_130us,True,True,101766,101766,0,True,48,48,...,0,True,0,0,True,None,False,False,True,PASS
6,DP-CTGAN,adult_income,True,True,32515,22760,-9755,False,15,15,...,0,True,0,0,True,None,False,False,True,FAIL
7,DP-CTGAN,bank_marketing,True,True,45211,31647,-13564,False,17,17,...,0,True,0,0,True,None,False,False,True,FAIL
8,DP-CTGAN,diabetes_130us,True,True,101766,71236,-30530,False,48,48,...,0,True,0,0,True,None,False,False,True,FAIL
9,SPP-GAN,adult_income,True,True,32515,32515,0,True,15,15,...,0,True,0,0,True,None,False,False,True,PASS
10,SPP-GAN,bank_marketing,True,True,45211,45211,0,True,17,17,...,0,True,0,0,True,None,False,False,True,PASS
11,SPP-GAN,diabetes_130us,True,True,101766,101766,0,True,48,48,...,0,True,0,0,True,None,False,False,True,PASS

====================================================================================================
PART E3 — STRUCTURAL CONSISTENCY EVALUATION COMPLETED
====================================================================================================

In [89]:
# ==============================================================================
# PART E4 — STRUCTURAL CONSISTENCY SUMMARY
# ==============================================================================

print("=" * 100)
print("PART E4 — STRUCTURAL CONSISTENCY SUMMARY")
print("=" * 100)

# ------------------------------------------------------------------------------
# Method-Level Summary
# ------------------------------------------------------------------------------

STRUCTURAL_METHOD_SUMMARY = []

for method in SYNTHETIC_METHODS:

    method_df = (
        STRUCTURAL_CONSISTENCY_DF[
            STRUCTURAL_CONSISTENCY_DF["Method"]
            == method
        ]
    )

    total = len(
        method_df
    )

    loaded = int(
        method_df[
            "Synthetic Loaded"
        ].sum()
    )

    passed = int(
        (
            method_df[
                "Structural Status"
            ]
            == "PASS"
        ).sum()
    )

    failed = int(
        (
            method_df[
                "Structural Status"
            ]
            == "FAIL"
        ).sum()
    )

    not_loaded = int(
        (
            method_df[
                "Structural Status"
            ]
            == "NOT LOADED"
        ).sum()
    )

    pass_rate = (
        passed / loaded * 100
        if loaded > 0
        else 0.0
    )

    STRUCTURAL_METHOD_SUMMARY.append({

        "Method": method,

        "Datasets Evaluated": total,

        "Synthetic Datasets Loaded": loaded,

        "Structural PASS": passed,

        "Structural FAIL": failed,

        "Not Loaded": not_loaded,

        "Structural Consistency Rate (%)": (
            round(pass_rate, 2)
        )
    })

STRUCTURAL_METHOD_SUMMARY_DF = pd.DataFrame(
    STRUCTURAL_METHOD_SUMMARY
)

print("\nMETHOD-LEVEL STRUCTURAL SUMMARY")

display(
    STRUCTURAL_METHOD_SUMMARY_DF
)

# ------------------------------------------------------------------------------
# Dataset-Level Summary
# ------------------------------------------------------------------------------

STRUCTURAL_DATASET_SUMMARY = []

for dataset in DATASETS:

    dataset_df = (
        STRUCTURAL_CONSISTENCY_DF[
            STRUCTURAL_CONSISTENCY_DF["Dataset"]
            == dataset
        ]
    )

    total = len(
        dataset_df
    )

    passed = int(
        (
            dataset_df[
                "Structural Status"
            ]
            == "PASS"
        ).sum()
    )

    dataset_pass_rate = (
        passed / total * 100
        if total > 0
        else 0.0
    )

    STRUCTURAL_DATASET_SUMMARY.append({

        "Dataset": dataset,

        "Methods Evaluated": total,

        "Structural PASS": passed,

        "Structural Consistency Rate (%)": (
            round(
                dataset_pass_rate,
                2
            )
        )
    })

STRUCTURAL_DATASET_SUMMARY_DF = pd.DataFrame(
    STRUCTURAL_DATASET_SUMMARY
)

print("\nDATASET-LEVEL STRUCTURAL SUMMARY")

display(
    STRUCTURAL_DATASET_SUMMARY_DF
)

# ------------------------------------------------------------------------------
# Overall Summary
# ------------------------------------------------------------------------------

TOTAL_COMBINATIONS = len(
    STRUCTURAL_CONSISTENCY_DF
)

TOTAL_LOADED = int(
    STRUCTURAL_CONSISTENCY_DF[
        "Synthetic Loaded"
    ].sum()
)

TOTAL_PASS = int(
    (
        STRUCTURAL_CONSISTENCY_DF[
            "Structural Status"
        ]
        == "PASS"
    ).sum()
)

OVERALL_STRUCTURAL_RATE = (
    TOTAL_PASS
    / TOTAL_LOADED
    * 100
    if TOTAL_LOADED > 0
    else 0.0
)

print("\n" + "-" * 100)
print("OVERALL STRUCTURAL CONSISTENCY")
print("-" * 100)

print(
    f"Total Method–Dataset Combinations : "
    f"{TOTAL_COMBINATIONS}"
)

print(
    f"Synthetic Datasets Loaded         : "
    f"{TOTAL_LOADED}"
)

print(
    f"Structural PASS                    : "
    f"{TOTAL_PASS}"
)

print(
    f"Structural Consistency Rate       : "
    f"{OVERALL_STRUCTURAL_RATE:.2f}%"
)

print("\n" + "=" * 100)
print("PART E4 — STRUCTURAL CONSISTENCY SUMMARY COMPLETED")
print("=" * 100)

====================================================================================================
PART E4 — STRUCTURAL CONSISTENCY SUMMARY
====================================================================================================

METHOD-LEVEL STRUCTURAL SUMMARY

,Method,Datasets Evaluated,Synthetic Datasets Loaded,Structural PASS,Structural FAIL,Not Loaded,Structural Consistency Rate (%)
0,CTGAN,3,3,3,0,0,100.00
1,TVAE,3,3,1,2,0,33.33
2,DP-CTGAN,3,3,0,3,0,0.00
3,SPP-GAN,3,3,3,0,0,100.00

DATASET-LEVEL STRUCTURAL SUMMARY

,Dataset,Methods Evaluated,Structural PASS,Structural Consistency Rate (%)
0,adult_income,4,2,50.0
1,bank_marketing,4,2,50.0
2,diabetes_130us,4,3,75.0

----------------------------------------------------------------------------------------------------
OVERALL STRUCTURAL CONSISTENCY
----------------------------------------------------------------------------------------------------
Total Method–Dataset Combinations : 12
Synthetic Datasets Loaded         : 12
Structural PASS                    : 7
Structural Consistency Rate       : 58.33%

====================================================================================================
PART E4 — STRUCTURAL CONSISTENCY SUMMARY COMPLETED
====================================================================================================

In [90]:
# ==============================================================================
# PART E5 — STRUCTURAL CONSISTENCY MATRIX
# ==============================================================================

print("=" * 100)
print("PART E5 — STRUCTURAL CONSISTENCY MATRIX")
print("=" * 100)

STRUCTURAL_CONSISTENCY_MATRIX = (
    STRUCTURAL_CONSISTENCY_DF
    .pivot(
        index="Dataset",
        columns="Method",
        values="Structural Status"
    )
)

display(
    STRUCTURAL_CONSISTENCY_MATRIX
)

print("\n" + "=" * 100)
print("PART E5 — STRUCTURAL CONSISTENCY MATRIX COMPLETED")
print("=" * 100)

====================================================================================================
PART E5 — STRUCTURAL CONSISTENCY MATRIX
====================================================================================================

Method         CTGAN DP-CTGAN SPP-GAN  TVAE
Dataset
adult_income    PASS     FAIL    PASS  FAIL
bank_marketing  PASS     FAIL    PASS  FAIL
diabetes_130us  PASS     FAIL    PASS  PASS

====================================================================================================
PART E5 — STRUCTURAL CONSISTENCY MATRIX COMPLETED
====================================================================================================

In [91]:
# ==============================================================================
# PART E6 — STRUCTURAL DIAGNOSTIC CHECKS
# ==============================================================================

print("=" * 100)
print("PART E6 — STRUCTURAL DIAGNOSTIC CHECKS")
print("=" * 100)

STRUCTURAL_DIAGNOSTICS = []

for method in SYNTHETIC_METHODS:

    for dataset in DATASETS:

        synthetic_df = (
            SYNTHETIC_DATASETS
            .get(method, {})
            .get(dataset)
        )

        reference_df = (
            REAL_DATASETS
            .get(dataset)
        )

        if synthetic_df is None:

            STRUCTURAL_DIAGNOSTICS.append({

                "Method": method,
                "Dataset": dataset,
                "Issue": "Synthetic dataset not loaded",
                "Severity": "CRITICAL"

            })

            continue

        if reference_df is None:

            STRUCTURAL_DIAGNOSTICS.append({

                "Method": method,
                "Dataset": dataset,
                "Issue": "Reference dataset not loaded",
                "Severity": "CRITICAL"

            })

            continue

        # ----------------------------------------------------------------------
        # Column Name Difference
        # ----------------------------------------------------------------------

        missing_in_synthetic = sorted(
            set(reference_df.columns)
            - set(synthetic_df.columns)
        )

        extra_in_synthetic = sorted(
            set(synthetic_df.columns)
            - set(reference_df.columns)
        )

        if missing_in_synthetic:

            STRUCTURAL_DIAGNOSTICS.append({

                "Method": method,
                "Dataset": dataset,

                "Issue": (
                    "Columns missing from synthetic data: "
                    + ", ".join(
                        map(
                            str,
                            missing_in_synthetic
                        )
                    )
                ),

                "Severity": "CRITICAL"
            })

        if extra_in_synthetic:

            STRUCTURAL_DIAGNOSTICS.append({

                "Method": method,
                "Dataset": dataset,

                "Issue": (
                    "Extra columns in synthetic data: "
                    + ", ".join(
                        map(
                            str,
                            extra_in_synthetic
                        )
                    )
                ),

                "Severity": "CRITICAL"
            })

        # ----------------------------------------------------------------------
        # Column Order
        # ----------------------------------------------------------------------

        if (
            reference_df.columns.tolist()
            != synthetic_df.columns.tolist()
        ):

            STRUCTURAL_DIAGNOSTICS.append({

                "Method": method,
                "Dataset": dataset,

                "Issue": "Column order differs",

                "Severity": "HIGH"
            })

        # ----------------------------------------------------------------------
        # Data Type Differences
        # ----------------------------------------------------------------------

        common_columns = [
            column
            for column in reference_df.columns
            if column in synthetic_df.columns
        ]

        for column in common_columns:

            real_dtype = str(
                reference_df[column].dtype
            )

            synthetic_dtype = str(
                synthetic_df[column].dtype
            )

            if real_dtype != synthetic_dtype:

                STRUCTURAL_DIAGNOSTICS.append({

                    "Method": method,
                    "Dataset": dataset,

                    "Issue": (
                        f"Data type mismatch in "
                        f"'{column}': "
                        f"real={real_dtype}, "
                        f"synthetic={synthetic_dtype}"
                    ),

                    "Severity": "HIGH"
                })

        # ----------------------------------------------------------------------
        # Row Count Difference
        # ----------------------------------------------------------------------

        if len(reference_df) != len(synthetic_df):

            STRUCTURAL_DIAGNOSTICS.append({

                "Method": method,
                "Dataset": dataset,

                "Issue": (
                    "Synthetic row count differs from "
                    "reference row count: "
                    f"{len(synthetic_df):,} vs "
                    f"{len(reference_df):,}"
                ),

                "Severity": "INFO"
            })

# ------------------------------------------------------------------------------
# Display Diagnostics
# ------------------------------------------------------------------------------

STRUCTURAL_DIAGNOSTICS_DF = pd.DataFrame(
    STRUCTURAL_DIAGNOSTICS
)

if STRUCTURAL_DIAGNOSTICS_DF.empty:

    print(
        "\n✓ No structural inconsistencies detected."
    )

else:

    display(
        STRUCTURAL_DIAGNOSTICS_DF
    )

print("\n" + "=" * 100)
print("PART E6 — STRUCTURAL DIAGNOSTIC CHECKS COMPLETED")
print("=" * 100)

====================================================================================================
PART E6 — STRUCTURAL DIAGNOSTIC CHECKS
====================================================================================================

,Method,Dataset,Issue,Severity
0,TVAE,adult_income,"Data type mismatch in 'education': real=int64,...",HIGH
1,TVAE,adult_income,Data type mismatch in 'occupation': real=int64...,HIGH
2,TVAE,adult_income,Data type mismatch in 'capital_gain': real=flo...,HIGH
3,TVAE,adult_income,Data type mismatch in 'capital_loss': real=flo...,HIGH
4,TVAE,adult_income,Data type mismatch in 'native_country': real=i...,HIGH
...,...,...,...,...
65,DP-CTGAN,diabetes_130us,Data type mismatch in 'metformin-pioglitazone'...,HIGH
66,DP-CTGAN,diabetes_130us,"Data type mismatch in 'change': real=int64, sy...",HIGH
67,DP-CTGAN,diabetes_130us,Data type mismatch in 'diabetesMed': real=int6...,HIGH
68,DP-CTGAN,diabetes_130us,Data type mismatch in 'readmitted': real=int64...,HIGH
69,DP-CTGAN,diabetes_130us,Synthetic row count differs from reference row...,INFO

====================================================================================================
PART E6 — STRUCTURAL DIAGNOSTIC CHECKS COMPLETED
====================================================================================================

In [92]:
# ==============================================================================
# PART E7 — STRUCTURAL VERIFICATION STATUS
# ==============================================================================

print("=" * 100)
print("PART E7 — STRUCTURAL VERIFICATION STATUS")
print("=" * 100)

STRUCTURAL_VERIFICATION = {

    "Evaluation Completed": True,

    "Methods Evaluated": (
        SYNTHETIC_METHODS.copy()
    ),

    "Datasets Evaluated": (
        DATASETS.copy()
    ),

    "Total Method-Dataset Combinations": (
        len(
            STRUCTURAL_CONSISTENCY_DF
        )
    ),

    "Synthetic Datasets Loaded": (
        int(
            STRUCTURAL_CONSISTENCY_DF[
                "Synthetic Loaded"
            ].sum()
        )
    ),

    "Structural PASS Count": (
        int(
            (
                STRUCTURAL_CONSISTENCY_DF[
                    "Structural Status"
                ]
                == "PASS"
            ).sum()
        )
    ),

    "Structural FAIL Count": (
        int(
            (
                STRUCTURAL_CONSISTENCY_DF[
                    "Structural Status"
                ]
                == "FAIL"
            ).sum()
        )
    ),

    "Not Loaded Count": (
        int(
            (
                STRUCTURAL_CONSISTENCY_DF[
                    "Structural Status"
                ]
                == "NOT LOADED"
            ).sum()
        )
    ),

    "Overall Structural Consistency Rate (%)": (
        round(
            OVERALL_STRUCTURAL_RATE,
            2
        )
    ),

    "Structural Evaluation Ready": (
        TOTAL_LOADED
        == TOTAL_COMBINATIONS
    )
}

for key, value in STRUCTURAL_VERIFICATION.items():

    print(
        f"{key:<45}: {value}"
    )

print("\n" + "=" * 100)
print("PART E7 — STRUCTURAL VERIFICATION COMPLETED")
print("=" * 100)

====================================================================================================
PART E7 — STRUCTURAL VERIFICATION STATUS
====================================================================================================
Evaluation Completed                         : True
Methods Evaluated                            : ['CTGAN', 'TVAE', 'DP-CTGAN', 'SPP-GAN']
Datasets Evaluated                           : ['adult_income', 'bank_marketing', 'diabetes_130us']
Total Method-Dataset Combinations            : 12
Synthetic Datasets Loaded                    : 12
Structural PASS Count                        : 7
Structural FAIL Count                        : 5
Not Loaded Count                             : 0
Overall Structural Consistency Rate (%)      : 58.33
Structural Evaluation Ready                  : True

====================================================================================================
PART E7 — STRUCTURAL VERIFICATION COMPLETED
====================================================================================================

In [93]:
# ==============================================================================
# PART F1 — NUMERICAL COLUMN IDENTIFICATION
# ==============================================================================

print("=" * 100)
print("PART F1 — NUMERICAL COLUMN IDENTIFICATION")
print("=" * 100)

NUMERICAL_COLUMNS_REGISTRY = {}

for dataset in DATASETS:

    reference_df = REAL_DATASETS.get(dataset)

    if reference_df is None:
        print(f"\n⚠ {dataset}: Reference dataset not loaded.")
        NUMERICAL_COLUMNS_REGISTRY[dataset] = []
        continue

    numerical_columns = reference_df.select_dtypes(
        include=[np.number]
    ).columns.tolist()

    NUMERICAL_COLUMNS_REGISTRY[dataset] = numerical_columns

    print(f"\n{dataset}")
    print(f"Total Columns     : {len(reference_df.columns)}")
    print(f"Numerical Columns : {len(numerical_columns)}")

    if numerical_columns:

        for index, column in enumerate(
            numerical_columns,
            start=1
        ):
            print(f"  {index:>3}. {column}")

    else:
        print("  No numerical columns identified.")

NUMERICAL_COLUMN_SUMMARY = pd.DataFrame({

    "Dataset": DATASETS,

    "Total Columns": [
        len(REAL_DATASETS[dataset].columns)
        if dataset in REAL_DATASETS
        else 0
        for dataset in DATASETS
    ],

    "Numerical Columns": [
        len(
            NUMERICAL_COLUMNS_REGISTRY.get(
                dataset,
                []
            )
        )
        for dataset in DATASETS
    ],

    "Numerical Column Names": [
        NUMERICAL_COLUMNS_REGISTRY.get(
            dataset,
            []
        )
        for dataset in DATASETS
    ]
})

display(NUMERICAL_COLUMN_SUMMARY)

print("\n" + "=" * 100)
print("PART F1 — NUMERICAL COLUMN IDENTIFICATION COMPLETED")
print("=" * 100)

====================================================================================================
PART F1 — NUMERICAL COLUMN IDENTIFICATION
====================================================================================================

adult_income
Total Columns     : 15
Numerical Columns : 15
    1. age
    2. workclass
    3. fnlwgt
    4. education
    5. education_num
    6. marital_status
    7. occupation
    8. relationship
    9. race
   10. sex
   11. capital_gain
   12. capital_loss
   13. hours_per_week
   14. native_country
   15. income

bank_marketing
Total Columns     : 17
Numerical Columns : 17
    1. age
    2. job
    3. marital
    4. education
    5. default
    6. balance
    7. housing
    8. loan
    9. contact
   10. day
   11. month
   12. duration
   13. campaign
   14. pdays
   15. previous
   16. poutcome
   17. y

diabetes_130us
Total Columns     : 48
Numerical Columns : 48
    1. race
    2. gender
    3. age
    4. weight
    5. admission_type_id
    6. discharge_disposition_id
    7. admission_source_id
    8. time_in_hospital
    9. payer_code
   10. medical_specialty
   11. num_lab_procedures
   12. num_procedures
   13. num_medications
   14. number_outpatient
   15. number_emergency
   16. number_inpatient
   17. diag_1
   18. diag_2
   19. diag_3
   20. number_diagnoses
   21. max_glu_serum
   22. A1Cresult
   23. metformin
   24. repaglinide
   25. nateglinide
   26. chlorpropamide
   27. glimepiride
   28. acetohexamide
   29. glipizide
   30. glyburide
   31. tolbutamide
   32. pioglitazone
   33. rosiglitazone
   34. acarbose
   35. miglitol
   36. troglitazone
   37. tolazamide
   38. examide
   39. citoglipton
   40. insulin
   41. glyburide-metformin
   42. glipizide-metformin
   43. glimepiride-pioglitazone
   44. metformin-rosiglitazone
   45. metformin-pioglitazone
   46. change
   47. diabetesMed
   48. readmitted

,Dataset,Total Columns,Numerical Columns,Numerical Column Names
0,adult_income,15,15,"[age, workclass, fnlwgt, education, education_..."
1,bank_marketing,17,17,"[age, job, marital, education, default, balanc..."
2,diabetes_130us,48,48,"[race, gender, age, weight, admission_type_id,..."

====================================================================================================
PART F1 — NUMERICAL COLUMN IDENTIFICATION COMPLETED
====================================================================================================

In [94]:
# ==============================================================================
# PART F2 — NUMERICAL DATA PREPARATION
# ==============================================================================

print("=" * 100)
print("PART F2 — NUMERICAL DATA PREPARATION")
print("=" * 100)

NUMERICAL_COMPARISON_DATA = {}

for method in SYNTHETIC_METHODS:

    NUMERICAL_COMPARISON_DATA[method] = {}

    for dataset in DATASETS:

        reference_df = REAL_DATASETS.get(dataset)

        synthetic_df = (
            SYNTHETIC_DATASETS
            .get(method, {})
            .get(dataset)
        )

        if reference_df is None or synthetic_df is None:

            NUMERICAL_COMPARISON_DATA[
                method
            ][dataset] = {}

            print(
                f"\n{method} | {dataset} : "
                "Skipped — data unavailable."
            )

            continue

        numerical_columns = (
            NUMERICAL_COLUMNS_REGISTRY
            .get(dataset, [])
        )

        common_columns = [
            column
            for column in numerical_columns
            if column in synthetic_df.columns
        ]

        dataset_comparison = {}

        for column in common_columns:

            real_values = pd.to_numeric(
                reference_df[column],
                errors="coerce"
            )

            synthetic_values = pd.to_numeric(
                synthetic_df[column],
                errors="coerce"
            )

            real_values = real_values[
                np.isfinite(real_values)
            ]

            synthetic_values = synthetic_values[
                np.isfinite(synthetic_values)
            ]

            dataset_comparison[column] = {

                "real": real_values.to_numpy(
                    dtype=float
                ),

                "synthetic": synthetic_values.to_numpy(
                    dtype=float
                )
            }

        NUMERICAL_COMPARISON_DATA[
            method
        ][dataset] = dataset_comparison

        print(
            f"\n{method} | {dataset}"
        )

        print(
            f"Common Numerical Columns : "
            f"{len(common_columns)}"
        )

print("\n" + "=" * 100)
print("PART F2 — NUMERICAL DATA PREPARATION COMPLETED")
print("=" * 100)

====================================================================================================
PART F2 — NUMERICAL DATA PREPARATION
====================================================================================================

CTGAN | adult_income
Common Numerical Columns : 15

CTGAN | bank_marketing
Common Numerical Columns : 17

CTGAN | diabetes_130us
Common Numerical Columns : 48

TVAE | adult_income
Common Numerical Columns : 15

TVAE | bank_marketing
Common Numerical Columns : 17

TVAE | diabetes_130us
Common Numerical Columns : 48

DP-CTGAN | adult_income
Common Numerical Columns : 15

DP-CTGAN | bank_marketing
Common Numerical Columns : 17

DP-CTGAN | diabetes_130us
Common Numerical Columns : 48

SPP-GAN | adult_income
Common Numerical Columns : 15

SPP-GAN | bank_marketing
Common Numerical Columns : 17

SPP-GAN | diabetes_130us
Common Numerical Columns : 48

====================================================================================================
PART F2 — NUMERICAL DATA PREPARATION COMPLETED
====================================================================================================

In [95]:
# ==============================================================================
# PART F3 — DESCRIPTIVE STATISTICS FIDELITY
# ==============================================================================

print("=" * 100)
print("PART F3 — DESCRIPTIVE STATISTICS FIDELITY")
print("=" * 100)

NUMERICAL_DESCRIPTIVE_RESULTS = []

for method in SYNTHETIC_METHODS:

    for dataset in DATASETS:

        comparison_data = (
            NUMERICAL_COMPARISON_DATA
            .get(method, {})
            .get(dataset, {})
        )

        for column, values in comparison_data.items():

            real_values = values["real"]
            synthetic_values = values["synthetic"]

            if len(real_values) == 0 or len(synthetic_values) == 0:
                continue

            real_mean = np.mean(real_values)
            synthetic_mean = np.mean(synthetic_values)

            real_std = np.std(
                real_values,
                ddof=1
            ) if len(real_values) > 1 else 0.0

            synthetic_std = np.std(
                synthetic_values,
                ddof=1
            ) if len(synthetic_values) > 1 else 0.0

            real_median = np.median(real_values)
            synthetic_median = np.median(
                synthetic_values
            )

            real_min = np.min(real_values)
            synthetic_min = np.min(
                synthetic_values
            )

            real_max = np.max(real_values)
            synthetic_max = np.max(
                synthetic_values
            )

            mean_relative_error = (
                abs(real_mean - synthetic_mean)
                / max(abs(real_mean), 1e-12)
            )

            std_relative_error = (
                abs(real_std - synthetic_std)
                / max(abs(real_std), 1e-12)
            )

            median_relative_error = (
                abs(real_median - synthetic_median)
                / max(abs(real_median), 1e-12)
            )

            NUMERICAL_DESCRIPTIVE_RESULTS.append({

                "Method": method,
                "Dataset": dataset,
                "Column": column,

                "Real Mean": real_mean,
                "Synthetic Mean": synthetic_mean,

                "Mean Relative Error": (
                    mean_relative_error
                ),

                "Real Std": real_std,
                "Synthetic Std": synthetic_std,

                "Std Relative Error": (
                    std_relative_error
                ),

                "Real Median": real_median,
                "Synthetic Median": synthetic_median,

                "Median Relative Error": (
                    median_relative_error
                ),

                "Real Min": real_min,
                "Synthetic Min": synthetic_min,

                "Real Max": real_max,
                "Synthetic Max": synthetic_max
            })

NUMERICAL_DESCRIPTIVE_DF = pd.DataFrame(
    NUMERICAL_DESCRIPTIVE_RESULTS
)

display(NUMERICAL_DESCRIPTIVE_DF)

print("\n" + "=" * 100)
print("PART F3 — DESCRIPTIVE STATISTICS FIDELITY COMPLETED")
print("=" * 100)

====================================================================================================
PART F3 — DESCRIPTIVE STATISTICS FIDELITY
====================================================================================================

,Method,Dataset,Column,Real Mean,Synthetic Mean,Mean Relative Error,Real Std,Synthetic Std,Std Relative Error,Real Median,Synthetic Median,Median Relative Error,Real Min,Synthetic Min,Real Max,Synthetic Max
0,CTGAN,adult_income,age,0.353624,0.341800,0.033439,0.222161,0.219831,0.010489,0.327869,0.311950,0.048552,0.0,0.000000,1.0,1.000000
1,CTGAN,adult_income,workclass,3.869168,3.750607,0.030642,1.456041,1.656189,0.137461,4.000000,4.000000,0.000000,0.0,0.000000,8.0,8.000000
2,CTGAN,adult_income,fnlwgt,0.432468,0.509756,0.178714,0.235627,0.241676,0.025670,0.411583,0.473199,0.149706,0.0,0.055347,1.0,1.000000
3,CTGAN,adult_income,education,10.296971,0.834415,0.918965,3.868909,0.371714,0.903923,11.000000,1.000000,0.909091,0.0,0.000000,15.0,1.000000
4,CTGAN,adult_income,education_num,0.489158,0.491431,0.004648,0.213888,0.219989,0.028523,0.478261,0.477979,0.000590,0.0,0.000000,1.0,0.961055
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
315,SPP-GAN,diabetes_130us,metformin-rosiglitazone,0.000020,0.000000,1.000000,0.004433,0.000000,1.000000,0.000000,0.000000,0.000000,0.0,0.000000,1.0,0.000000
316,SPP-GAN,diabetes_130us,metformin-pioglitazone,0.000010,0.000000,1.000000,0.003135,0.000000,1.000000,0.000000,0.000000,0.000000,0.0,0.000000,1.0,0.000000
317,SPP-GAN,diabetes_130us,change,0.538048,0.537626,0.000785,0.498553,0.498585,0.000064,1.000000,1.000000,0.000000,0.0,0.000000,1.0,1.000000
318,SPP-GAN,diabetes_130us,diabetesMed,0.770031,0.767565,0.003203,0.420815,0.422387,0.003737,1.000000,1.000000,0.000000,0.0,0.000000,1.0,1.000000
319,SPP-GAN,diabetes_130us,readmitted,1.427520,1.421408,0.004282,0.684068,0.687250,0.004651,2.000000,2.000000,0.000000,0.0,0.000000,2.0,2.000000

====================================================================================================
PART F3 — DESCRIPTIVE STATISTICS FIDELITY COMPLETED
====================================================================================================

In [96]:
# ==============================================================================
# PART F4 — NUMERICAL FIDELITY SCORES
# ==============================================================================

print("=" * 100)
print("PART F4 — NUMERICAL FIDELITY SCORES")
print("=" * 100)

NUMERICAL_FIDELITY_RESULTS = []

for method in SYNTHETIC_METHODS:

    for dataset in DATASETS:

        subset = NUMERICAL_DESCRIPTIVE_DF[
            (
                NUMERICAL_DESCRIPTIVE_DF["Method"]
                == method
            )
            &
            (
                NUMERICAL_DESCRIPTIVE_DF["Dataset"]
                == dataset
            )
        ]

        if subset.empty:
            continue

        mean_error = subset[
            "Mean Relative Error"
        ].replace(
            [np.inf, -np.inf],
            np.nan
        ).dropna()

        std_error = subset[
            "Std Relative Error"
        ].replace(
            [np.inf, -np.inf],
            np.nan
        ).dropna()

        median_error = subset[
            "Median Relative Error"
        ].replace(
            [np.inf, -np.inf],
            np.nan
        ).dropna()

        mean_error_value = (
            mean_error.mean()
            if not mean_error.empty
            else np.nan
        )

        std_error_value = (
            std_error.mean()
            if not std_error.empty
            else np.nan
        )

        median_error_value = (
            median_error.mean()
            if not median_error.empty
            else np.nan
        )

        mean_fidelity = (
            1.0 / (
                1.0 + mean_error_value
            )
            if np.isfinite(mean_error_value)
            else np.nan
        )

        std_fidelity = (
            1.0 / (
                1.0 + std_error_value
            )
            if np.isfinite(std_error_value)
            else np.nan
        )

        median_fidelity = (
            1.0 / (
                1.0 + median_error_value
            )
            if np.isfinite(median_error_value)
            else np.nan
        )

        overall_fidelity = np.nanmean([
            mean_fidelity,
            std_fidelity,
            median_fidelity
        ])

        NUMERICAL_FIDELITY_RESULTS.append({

            "Method": method,
            "Dataset": dataset,

            "Mean Relative Error":
                mean_error_value,

            "Std Relative Error":
                std_error_value,

            "Median Relative Error":
                median_error_value,

            "Mean Fidelity Score":
                mean_fidelity,

            "Std Fidelity Score":
                std_fidelity,

            "Median Fidelity Score":
                median_fidelity,

            "Overall Descriptive Fidelity":
                overall_fidelity
        })

NUMERICAL_FIDELITY_DF = pd.DataFrame(
    NUMERICAL_FIDELITY_RESULTS
)

display(NUMERICAL_FIDELITY_DF)

print("\n" + "=" * 100)
print("PART F4 — NUMERICAL FIDELITY SCORES COMPLETED")
print("=" * 100)

====================================================================================================
PART F4 — NUMERICAL FIDELITY SCORES
====================================================================================================

,Method,Dataset,Mean Relative Error,Std Relative Error,Median Relative Error,Mean Fidelity Score,Std Fidelity Score,Median Fidelity Score,Overall Descriptive Fidelity
0,CTGAN,adult_income,3.661095e-01,3.630207e-01,1.959753e-01,7.320058e-01,7.336646e-01,8.361377e-01,7.672693e-01
1,CTGAN,bank_marketing,2.125499e+00,5.258176e-01,5.882353e+10,3.199489e-01,6.553864e-01,1.700000e-11,3.251118e-01
2,CTGAN,diabetes_130us,1.696994e+01,2.123684e+00,4.169336e+10,5.564849e-02,3.201348e-01,2.398463e-11,1.252611e-01
3,TVAE,adult_income,3.709284e-01,3.774154e-01,1.957486e-01,7.294327e-01,7.259974e-01,8.362962e-01,7.639087e-01
4,TVAE,bank_marketing,2.012817e+00,5.688221e-01,5.882353e+10,3.319153e-01,6.374209e-01,1.700000e-11,3.231121e-01
5,TVAE,diabetes_130us,7.111214e-01,8.764356e-01,4.167310e+10,5.844121e-01,5.329253e-01,2.399629e-11,3.724458e-01
6,DP-CTGAN,adult_income,7.119278e+00,9.764473e-01,1.601246e+11,1.231637e-01,5.059583e-01,6.245136e-12,2.097073e-01
7,DP-CTGAN,bank_marketing,4.277855e+00,9.605723e-01,5.135990e+10,1.894709e-01,5.100552e-01,1.947044e-11,2.331754e-01
8,DP-CTGAN,diabetes_130us,2.844971e+10,3.002492e+07,2.382400e+11,3.514974e-11,3.330566e-08,4.197449e-12,1.111500e-08
9,SPP-GAN,adult_income,2.479039e+00,3.010831e-01,1.972595e+10,2.874357e-01,7.685904e-01,5.069464e-11,3.520087e-01
10,SPP-GAN,bank_marketing,2.273775e-01,1.278378e-01,2.364904e+08,8.147453e-01,8.866523e-01,4.228501e-09,5.671325e-01
11,SPP-GAN,diabetes_130us,2.413634e-01,1.128138e-01,7.498172e+08,8.055659e-01,8.986229e-01,1.333658e-09,5.680629e-01

====================================================================================================
PART F4 — NUMERICAL FIDELITY SCORES COMPLETED
====================================================================================================

In [97]:
# ==============================================================================
# PART F5 — WASSERSTEIN DISTANCE
# ==============================================================================

print("=" * 100)
print("PART F5 — WASSERSTEIN DISTANCE")
print("=" * 100)

WASSERSTEIN_RESULTS = []

for method in SYNTHETIC_METHODS:

    for dataset in DATASETS:

        comparison_data = (
            NUMERICAL_COMPARISON_DATA
            .get(method, {})
            .get(dataset, {})
        )

        for column, values in comparison_data.items():

            real_values = values["real"]
            synthetic_values = values["synthetic"]

            if (
                len(real_values) == 0
                or len(synthetic_values) == 0
            ):
                continue

            try:

                distance = stats.wasserstein_distance(
                    real_values,
                    synthetic_values
                )

            except Exception:

                distance = np.nan

            WASSERSTEIN_RESULTS.append({

                "Method": method,
                "Dataset": dataset,
                "Column": column,
                "Wasserstein Distance": distance
            })

WASSERSTEIN_DF = pd.DataFrame(
    WASSERSTEIN_RESULTS
)

display(WASSERSTEIN_DF)

print("\n" + "=" * 100)
print("PART F5 — WASSERSTEIN DISTANCE COMPLETED")
print("=" * 100)

====================================================================================================
PART F5 — WASSERSTEIN DISTANCE
====================================================================================================

      Method         Dataset                   Column  Wasserstein Distance
0      CTGAN    adult_income                      age              0.013638
1      CTGAN    adult_income                workclass              0.201292
2      CTGAN    adult_income                   fnlwgt              0.077288
3      CTGAN    adult_income                education              9.462556
4      CTGAN    adult_income            education_num              0.009551
..       ...             ...                      ...                   ...
315  SPP-GAN  diabetes_130us  metformin-rosiglitazone              0.000020
316  SPP-GAN  diabetes_130us   metformin-pioglitazone              0.000010
317  SPP-GAN  diabetes_130us                   change              0.000423
318  SPP-GAN  diabetes_130us              diabetesMed              0.002466
319  SPP-GAN  diabetes_130us               readmitted              0.006112

[320 rows x 4 columns]

====================================================================================================
PART F5 — WASSERSTEIN DISTANCE COMPLETED
====================================================================================================

In [98]:
# ==============================================================================
# PART F6 — KOLMOGOROV-SMIRNOV DISTRIBUTION TEST
# ==============================================================================

print("=" * 100)
print("PART F6 — KOLMOGOROV-SMIRNOV DISTRIBUTION TEST")
print("=" * 100)

KS_RESULTS = []

for method in SYNTHETIC_METHODS:

    for dataset in DATASETS:

        comparison_data = (
            NUMERICAL_COMPARISON_DATA
            .get(method, {})
            .get(dataset, {})
        )

        for column, values in comparison_data.items():

            real_values = values["real"]
            synthetic_values = values["synthetic"]

            if (
                len(real_values) == 0
                or len(synthetic_values) == 0
            ):
                continue

            try:

                ks_result = stats.ks_2samp(
                    real_values,
                    synthetic_values
                )

                ks_statistic = (
                    ks_result.statistic
                )

                ks_pvalue = (
                    ks_result.pvalue
                )

            except Exception:

                ks_statistic = np.nan
                ks_pvalue = np.nan

            KS_RESULTS.append({

                "Method": method,
                "Dataset": dataset,
                "Column": column,
                "KS Statistic": ks_statistic,
                "KS P-Value": ks_pvalue,

                "Distribution Match":
                    (
                        "PASS"
                        if (
                            np.isfinite(ks_pvalue)
                            and ks_pvalue >= 0.05
                        )
                        else "FAIL"
                    )
            })

KS_DF = pd.DataFrame(KS_RESULTS)

display(KS_DF)

print("\n" + "=" * 100)
print("PART F6 — KOLMOGOROV-SMIRNOV TEST COMPLETED")
print("=" * 100)

====================================================================================================
PART F6 — KOLMOGOROV-SMIRNOV DISTRIBUTION TEST
====================================================================================================

,Method,Dataset,Column,KS Statistic,KS P-Value,Distribution Match
0,CTGAN,adult_income,age,0.053391,1.014311e-40,FAIL
1,CTGAN,adult_income,workclass,0.055667,3.132874e-44,FAIL
2,CTGAN,adult_income,fnlwgt,0.167861,0.000000e+00,FAIL
3,CTGAN,adult_income,education,0.935291,0.000000e+00,FAIL
4,CTGAN,adult_income,education_num,0.180686,0.000000e+00,FAIL
...,...,...,...,...,...,...
315,SPP-GAN,diabetes_130us,metformin-rosiglitazone,0.000020,1.000000e+00,PASS
316,SPP-GAN,diabetes_130us,metformin-pioglitazone,0.000010,1.000000e+00,PASS
317,SPP-GAN,diabetes_130us,change,0.000423,1.000000e+00,PASS
318,SPP-GAN,diabetes_130us,diabetesMed,0.002466,9.155105e-01,PASS
319,SPP-GAN,diabetes_130us,readmitted,0.003469,5.717175e-01,PASS

====================================================================================================
PART F6 — KOLMOGOROV-SMIRNOV TEST COMPLETED
====================================================================================================

In [99]:
# ==============================================================================
# PART F7 — NUMERICAL FIDELITY SUMMARY
# ==============================================================================

print("=" * 100)
print("PART F7 — NUMERICAL FIDELITY SUMMARY")
print("=" * 100)

NUMERICAL_SUMMARY_RESULTS = []

for method in SYNTHETIC_METHODS:

    for dataset in DATASETS:

        fidelity_subset = NUMERICAL_FIDELITY_DF[
            (
                NUMERICAL_FIDELITY_DF["Method"]
                == method
            )
            &
            (
                NUMERICAL_FIDELITY_DF["Dataset"]
                == dataset
            )
        ]

        wasserstein_subset = WASSERSTEIN_DF[
            (
                WASSERSTEIN_DF["Method"]
                == method
            )
            &
            (
                WASSERSTEIN_DF["Dataset"]
                == dataset
            )
        ]

        ks_subset = KS_DF[
            (
                KS_DF["Method"]
                == method
            )
            &
            (
                KS_DF["Dataset"]
                == dataset
            )
        ]

        if fidelity_subset.empty:
            continue

        wasserstein_mean = (
            wasserstein_subset[
                "Wasserstein Distance"
            ]
            .replace(
                [np.inf, -np.inf],
                np.nan
            )
            .mean()
        )

        ks_statistic_mean = (
            ks_subset[
                "KS Statistic"
            ]
            .replace(
                [np.inf, -np.inf],
                np.nan
            )
            .mean()
        )

        ks_pass_rate = (
            (
                ks_subset["Distribution Match"]
                == "PASS"
            ).mean()
            if not ks_subset.empty
            else np.nan
        )

        overall_descriptive_fidelity = (
            fidelity_subset[
                "Overall Descriptive Fidelity"
            ].mean()
        )

        NUMERICAL_SUMMARY_RESULTS.append({

            "Method": method,
            "Dataset": dataset,

            "Numerical Columns Evaluated":
                len(fidelity_subset),

            "Mean Fidelity":
                fidelity_subset[
                    "Mean Fidelity Score"
                ].mean(),

            "Std Fidelity":
                fidelity_subset[
                    "Std Fidelity Score"
                ].mean(),

            "Median Fidelity":
                fidelity_subset[
                    "Median Fidelity Score"
                ].mean(),

            "Overall Descriptive Fidelity":
                overall_descriptive_fidelity,

            "Mean Wasserstein Distance":
                wasserstein_mean,

            "Mean KS Statistic":
                ks_statistic_mean,

            "KS Distribution Pass Rate":
                ks_pass_rate
        })

NUMERICAL_SUMMARY_DF = pd.DataFrame(
    NUMERICAL_SUMMARY_RESULTS
)

display(NUMERICAL_SUMMARY_DF)

print("\n" + "=" * 100)
print("PART F7 — NUMERICAL FIDELITY SUMMARY COMPLETED")
print("=" * 100)

====================================================================================================
PART F7 — NUMERICAL FIDELITY SUMMARY
====================================================================================================

,Method,Dataset,Numerical Columns Evaluated,Mean Fidelity,Std Fidelity,Median Fidelity,Overall Descriptive Fidelity,Mean Wasserstein Distance,Mean KS Statistic,KS Distribution Pass Rate
0,CTGAN,adult_income,1,7.320058e-01,7.336646e-01,8.361377e-01,7.672693e-01,3.482700,0.255324,0.000000
1,CTGAN,bank_marketing,1,3.199489e-01,6.553864e-01,1.700000e-11,3.251118e-01,0.737069,0.249181,0.000000
2,CTGAN,diabetes_130us,1,5.564849e-02,3.201348e-01,2.398463e-11,1.252611e-01,19.236481,0.202533,0.208333
3,TVAE,adult_income,1,7.294327e-01,7.259974e-01,8.362962e-01,7.639087e-01,3.488869,0.267405,0.000000
4,TVAE,bank_marketing,1,3.319153e-01,6.374209e-01,1.700000e-11,3.231121e-01,0.749365,0.284512,0.000000
5,TVAE,diabetes_130us,1,5.844121e-01,5.329253e-01,2.399629e-11,3.724458e-01,19.232601,0.198625,0.270833
6,DP-CTGAN,adult_income,1,1.231637e-01,5.059583e-01,6.245136e-12,2.097073e-01,4.393896,0.926679,0.000000
7,DP-CTGAN,bank_marketing,1,1.894709e-01,5.100552e-01,1.947044e-11,2.331754e-01,0.931404,0.823429,0.000000
8,DP-CTGAN,diabetes_130us,1,3.514974e-11,3.330566e-08,4.197449e-12,1.111500e-08,20.301597,0.982279,0.000000
9,SPP-GAN,adult_income,1,2.874357e-01,7.685904e-01,5.069464e-11,3.520087e-01,0.496618,0.237859,0.400000
10,SPP-GAN,bank_marketing,1,8.147453e-01,8.866523e-01,4.228501e-09,5.671325e-01,0.180971,0.189236,0.470588
11,SPP-GAN,diabetes_130us,1,8.055659e-01,8.986229e-01,1.333658e-09,5.680629e-01,1.332497,0.086768,0.729167

====================================================================================================
PART F7 — NUMERICAL FIDELITY SUMMARY COMPLETED
====================================================================================================

In [100]:
# ==============================================================================
# PART F8 — NUMERICAL FIDELITY RESEARCH VERIFICATION
# ==============================================================================

print("=" * 100)
print("PART F8 — NUMERICAL FIDELITY RESEARCH VERIFICATION")
print("=" * 100)

F_NUMERICAL_VERIFICATION = {

    "Datasets Configured":
        len(DATASETS) == 3,

    "Expected Datasets Present":
        set(DATASETS)
        == {
            "adult_income",
            "bank_marketing",
            "diabetes_130us"
        },

    "Methods Configured":
        len(SYNTHETIC_METHODS) == 4,

    "CTGAN Included":
        "CTGAN" in SYNTHETIC_METHODS,

    "TVAE Included":
        "TVAE" in SYNTHETIC_METHODS,

    "DP-CTGAN Included":
        "DP-CTGAN" in SYNTHETIC_METHODS,

    "SPP-GAN Included":
        "SPP-GAN" in SYNTHETIC_METHODS,

    "Numerical Fidelity Generated":
        not NUMERICAL_FIDELITY_DF.empty,

    "Wasserstein Evaluation Generated":
        not WASSERSTEIN_DF.empty,

    "KS Evaluation Generated":
        not KS_DF.empty,

    "Numerical Summary Generated":
        not NUMERICAL_SUMMARY_DF.empty
}

F_NUMERICAL_VERIFICATION_DF = pd.DataFrame(
    [
        {
            "Check": key,
            "Status": "PASS" if value else "FAIL"
        }
        for key, value
        in F_NUMERICAL_VERIFICATION.items()
    ]
)

display(
    F_NUMERICAL_VERIFICATION_DF
)

failed_checks = [
    key
    for key, value
    in F_NUMERICAL_VERIFICATION.items()
    if not value
]

print("\n" + "-" * 100)

if failed_checks:

    print("NUMERICAL FIDELITY STATUS : INCOMPLETE")

    print("\nFailed Checks:")

    for check in failed_checks:
        print(f"  ✗ {check}")

else:

    print(
        "NUMERICAL FIDELITY STATUS : "
        "READY"
    )

print("-" * 100)

print("\n" + "=" * 100)
print("PART F8 — NUMERICAL FIDELITY RESEARCH VERIFICATION COMPLETED")
print("=" * 100)

====================================================================================================
PART F8 — NUMERICAL FIDELITY RESEARCH VERIFICATION
====================================================================================================

                               Check Status
0                Datasets Configured   PASS
1          Expected Datasets Present   PASS
2                 Methods Configured   PASS
3                     CTGAN Included   PASS
4                      TVAE Included   PASS
5                  DP-CTGAN Included   PASS
6                   SPP-GAN Included   PASS
7       Numerical Fidelity Generated   PASS
8   Wasserstein Evaluation Generated   PASS
9            KS Evaluation Generated   PASS
10       Numerical Summary Generated   PASS

----------------------------------------------------------------------------------------------------
NUMERICAL FIDELITY STATUS : READY
----------------------------------------------------------------------------------------------------

====================================================================================================
PART F8 — NUMERICAL FIDELITY RESEARCH VERIFICATION COMPLETED
====================================================================================================

In [101]:
# ==============================================================================
# PART G1 — CATEGORICAL FEATURE DISCOVERY
# ==============================================================================

print("=" * 100)
print("PART G1 — CATEGORICAL FEATURE DISCOVERY")
print("=" * 100)

if "REAL_DATASETS" not in globals():
    raise NameError(
        "REAL_DATASETS is not defined. "
        "Run Section C — Real Reference Data before Section G."
    )

if "SYNTHETIC_DATASETS" not in globals():
    raise NameError(
        "SYNTHETIC_DATASETS is not defined. "
        "Run Section D — Synthetic Data Loading before Section G."
    )

CATEGORICAL_FEATURES = {}

CATEGORICAL_FEATURE_DISCOVERY_RESULTS = []

for dataset in SYNTHETIC_DATASET_NAMES:

    reference_df = REAL_DATASETS.get(dataset)

    if reference_df is None:
        print(f"\n{dataset}: Reference dataset not loaded.")
        CATEGORICAL_FEATURES[dataset] = []
        continue

    categorical_columns = (
        reference_df
        .select_dtypes(
            include=["object", "category", "bool"]
        )
        .columns
        .tolist()
    )

    CATEGORICAL_FEATURES[dataset] = categorical_columns

    print(f"\n{dataset}")
    print(f"Categorical Features : {len(categorical_columns)}")

    if categorical_columns:

        for index, column in enumerate(
            categorical_columns,
            start=1
        ):

            unique_values = (
                reference_df[column]
                .nunique(dropna=False)
            )

            CATEGORICAL_FEATURE_DISCOVERY_RESULTS.append({

                "Dataset": dataset,
                "Feature": column,
                "Unique Categories": unique_values,
                "Data Type": str(
                    reference_df[column].dtype
                )
            })

            print(
                f"  {index:>3}. "
                f"{column} "
                f"({unique_values} categories)"
            )

    else:

        print("  No categorical features detected.")

CATEGORICAL_FEATURE_DISCOVERY_DF = pd.DataFrame(
    CATEGORICAL_FEATURE_DISCOVERY_RESULTS
)

print("\n" + "-" * 100)
print("CATEGORICAL FEATURE SUMMARY")
print("-" * 100)

display(
    CATEGORICAL_FEATURE_DISCOVERY_DF
)

print("\n" + "=" * 100)
print("PART G1 — CATEGORICAL FEATURE DISCOVERY COMPLETED")
print("=" * 100)

====================================================================================================
PART G1 — CATEGORICAL FEATURE DISCOVERY
====================================================================================================

adult_income
Categorical Features : 0
  No categorical features detected.

bank_marketing
Categorical Features : 0
  No categorical features detected.

diabetes_130us
Categorical Features : 0
  No categorical features detected.

----------------------------------------------------------------------------------------------------
CATEGORICAL FEATURE SUMMARY
----------------------------------------------------------------------------------------------------

Empty DataFrame
Columns: []
Index: []

====================================================================================================
PART G1 — CATEGORICAL FEATURE DISCOVERY COMPLETED
====================================================================================================

In [102]:
# ==============================================================================
# PART G2 — CATEGORY COVERAGE
# ==============================================================================

print("=" * 100)
print("PART G2 — CATEGORY COVERAGE")
print("=" * 100)

CATEGORY_COVERAGE_RESULTS = []

for method in SYNTHETIC_METHODS:

    for dataset in SYNTHETIC_DATASET_NAMES:

        synthetic_df = (
            SYNTHETIC_DATASETS
            .get(method, {})
            .get(dataset)
        )

        reference_df = (
            REAL_DATASETS
            .get(dataset)
        )

        if synthetic_df is None or reference_df is None:
            continue

        categorical_columns = (
            CATEGORICAL_FEATURES
            .get(dataset, [])
        )

        for column in categorical_columns:

            if column not in synthetic_df.columns:
                continue

            reference_categories = set(
                reference_df[column]
                .dropna()
                .unique()
            )

            synthetic_categories = set(
                synthetic_df[column]
                .dropna()
                .unique()
            )

            if not reference_categories:

                continue

            common_categories = (
                reference_categories
                & synthetic_categories
            )

            missing_categories = (
                reference_categories
                - synthetic_categories
            )

            unexpected_categories = (
                synthetic_categories
                - reference_categories
            )

            coverage_rate = (
                len(common_categories)
                / len(reference_categories)
            )

            CATEGORY_COVERAGE_RESULTS.append({

                "Method": method,
                "Dataset": dataset,
                "Feature": column,
                "Reference Categories": len(
                    reference_categories
                ),
                "Synthetic Categories": len(
                    synthetic_categories
                ),
                "Common Categories": len(
                    common_categories
                ),
                "Missing Categories": len(
                    missing_categories
                ),
                "Unexpected Categories": len(
                    unexpected_categories
                ),
                "Category Coverage": coverage_rate
            })

CATEGORY_COVERAGE_DF = pd.DataFrame(
    CATEGORY_COVERAGE_RESULTS
)

display(
    CATEGORY_COVERAGE_DF
)

print("\n" + "-" * 100)
print("CATEGORY COVERAGE SUMMARY")
print("-" * 100)

if not CATEGORY_COVERAGE_DF.empty:

    CATEGORY_COVERAGE_SUMMARY = (
        CATEGORY_COVERAGE_DF
        .groupby(
            ["Method", "Dataset"],
            as_index=False
        )["Category Coverage"]
        .mean()
        .rename(
            columns={
                "Category Coverage":
                    "Mean Category Coverage"
            }
        )
    )

    display(
        CATEGORY_COVERAGE_SUMMARY
    )

print("\n" + "=" * 100)
print("PART G2 — CATEGORY COVERAGE COMPLETED")
print("=" * 100)

====================================================================================================
PART G2 — CATEGORY COVERAGE
====================================================================================================

Empty DataFrame
Columns: []
Index: []

----------------------------------------------------------------------------------------------------
CATEGORY COVERAGE SUMMARY
----------------------------------------------------------------------------------------------------

====================================================================================================
PART G2 — CATEGORY COVERAGE COMPLETED
====================================================================================================

In [103]:
# ==============================================================================
# PART G3 — CATEGORICAL FREQUENCY DISTRIBUTION
# ==============================================================================

print("=" * 100)
print("PART G3 — CATEGORICAL FREQUENCY DISTRIBUTION")
print("=" * 100)

CATEGORICAL_FREQUENCY_RESULTS = []

for method in SYNTHETIC_METHODS:

    for dataset in SYNTHETIC_DATASET_NAMES:

        synthetic_df = (
            SYNTHETIC_DATASETS
            .get(method, {})
            .get(dataset)
        )

        reference_df = (
            REAL_DATASETS
            .get(dataset)
        )

        if synthetic_df is None or reference_df is None:
            continue

        for column in CATEGORICAL_FEATURES.get(
            dataset,
            []
        ):

            if column not in synthetic_df.columns:
                continue

            reference_counts = (
                reference_df[column]
                .value_counts(
                    normalize=True,
                    dropna=False
                )
            )

            synthetic_counts = (
                synthetic_df[column]
                .value_counts(
                    normalize=True,
                    dropna=False
                )
            )

            categories = sorted(
                set(reference_counts.index)
                | set(synthetic_counts.index),
                key=lambda value: str(value)
            )

            for category in categories:

                real_frequency = float(
                    reference_counts.get(
                        category,
                        0.0
                    )
                )

                synthetic_frequency = float(
                    synthetic_counts.get(
                        category,
                        0.0
                    )
                )

                absolute_difference = abs(
                    real_frequency
                    - synthetic_frequency
                )

                CATEGORICAL_FREQUENCY_RESULTS.append({

                    "Method": method,
                    "Dataset": dataset,
                    "Feature": column,
                    "Category": str(category),
                    "Reference Frequency":
                        real_frequency,
                    "Synthetic Frequency":
                        synthetic_frequency,
                    "Absolute Frequency Difference":
                        absolute_difference
                })

CATEGORICAL_FREQUENCY_DF = pd.DataFrame(
    CATEGORICAL_FREQUENCY_RESULTS
)

display(
    CATEGORICAL_FREQUENCY_DF
)

print("\n" + "=" * 100)
print("PART G3 — CATEGORICAL FREQUENCY DISTRIBUTION COMPLETED")
print("=" * 100)

====================================================================================================
PART G3 — CATEGORICAL FREQUENCY DISTRIBUTION
====================================================================================================

Empty DataFrame
Columns: []
Index: []

====================================================================================================
PART G3 — CATEGORICAL FREQUENCY DISTRIBUTION COMPLETED
====================================================================================================

In [104]:
# ==============================================================================
# PART G4 — TOTAL VARIATION DISTANCE
# ==============================================================================

print("=" * 100)
print("PART G4 — TOTAL VARIATION DISTANCE")
print("=" * 100)

TVD_RESULTS = []

for method in SYNTHETIC_METHODS:

    for dataset in SYNTHETIC_DATASET_NAMES:

        synthetic_df = (
            SYNTHETIC_DATASETS
            .get(method, {})
            .get(dataset)
        )

        reference_df = (
            REAL_DATASETS
            .get(dataset)
        )

        if synthetic_df is None or reference_df is None:
            continue

        for column in CATEGORICAL_FEATURES.get(
            dataset,
            []
        ):

            if column not in synthetic_df.columns:
                continue

            reference_distribution = (
                reference_df[column]
                .value_counts(
                    normalize=True,
                    dropna=False
                )
            )

            synthetic_distribution = (
                synthetic_df[column]
                .value_counts(
                    normalize=True,
                    dropna=False
                )
            )

            categories = (
                set(reference_distribution.index)
                | set(synthetic_distribution.index)
            )

            tvd = 0.0

            for category in categories:

                p = float(
                    reference_distribution.get(
                        category,
                        0.0
                    )
                )

                q = float(
                    synthetic_distribution.get(
                        category,
                        0.0
                    )
                )

                tvd += abs(p - q)

            tvd *= 0.5

            TVD_RESULTS.append({

                "Method": method,
                "Dataset": dataset,
                "Feature": column,
                "Total Variation Distance": tvd
            })

TVD_DF = pd.DataFrame(
    TVD_RESULTS
)

display(
    TVD_DF
)

print("\n" + "-" * 100)
print("TVD SUMMARY")
print("-" * 100)

if not TVD_DF.empty:

    TVD_SUMMARY = (
        TVD_DF
        .groupby(
            ["Method", "Dataset"],
            as_index=False
        )["Total Variation Distance"]
        .mean()
        .rename(
            columns={
                "Total Variation Distance":
                    "Mean TVD"
            }
        )
    )

    display(
        TVD_SUMMARY
    )

print("\n" + "=" * 100)
print("PART G4 — TOTAL VARIATION DISTANCE COMPLETED")
print("=" * 100)

====================================================================================================
PART G4 — TOTAL VARIATION DISTANCE
====================================================================================================

Empty DataFrame
Columns: []
Index: []

----------------------------------------------------------------------------------------------------
TVD SUMMARY
----------------------------------------------------------------------------------------------------

====================================================================================================
PART G4 — TOTAL VARIATION DISTANCE COMPLETED
====================================================================================================

In [105]:
# ==============================================================================
# PART G5 — JENSEN-SHANNON DIVERGENCE
# ==============================================================================

print("=" * 100)
print("PART G5 — JENSEN-SHANNON DIVERGENCE")
print("=" * 100)

JSD_RESULTS = []

for method in SYNTHETIC_METHODS:

    for dataset in SYNTHETIC_DATASET_NAMES:

        synthetic_df = (
            SYNTHETIC_DATASETS
            .get(method, {})
            .get(dataset)
        )

        reference_df = (
            REAL_DATASETS
            .get(dataset)
        )

        if synthetic_df is None or reference_df is None:
            continue

        for column in CATEGORICAL_FEATURES.get(
            dataset,
            []
        ):

            if column not in synthetic_df.columns:
                continue

            reference_distribution = (
                reference_df[column]
                .value_counts(
                    normalize=True,
                    dropna=False
                )
            )

            synthetic_distribution = (
                synthetic_df[column]
                .value_counts(
                    normalize=True,
                    dropna=False
                )
            )

            categories = list(
                set(reference_distribution.index)
                | set(synthetic_distribution.index)
            )

            p = np.array([
                reference_distribution.get(
                    category,
                    0.0
                )
                for category in categories
            ], dtype=float)

            q = np.array([
                synthetic_distribution.get(
                    category,
                    0.0
                )
                for category in categories
            ], dtype=float)

            p_sum = p.sum()
            q_sum = q.sum()

            if p_sum <= 0 or q_sum <= 0:
                continue

            p /= p_sum
            q /= q_sum

            jsd = stats.entropy(
                p,
                (p + q) / 2,
                base=2
            ) / 2

            jsd += stats.entropy(
                q,
                (p + q) / 2,
                base=2
            ) / 2

            JSD_RESULTS.append({

                "Method": method,
                "Dataset": dataset,
                "Feature": column,
                "Jensen-Shannon Divergence": float(jsd)
            })

JSD_DF = pd.DataFrame(
    JSD_RESULTS
)

display(
    JSD_DF
)

print("\n" + "-" * 100)
print("JSD SUMMARY")
print("-" * 100)

if not JSD_DF.empty:

    JSD_SUMMARY = (
        JSD_DF
        .groupby(
            ["Method", "Dataset"],
            as_index=False
        )["Jensen-Shannon Divergence"]
        .mean()
        .rename(
            columns={
                "Jensen-Shannon Divergence":
                    "Mean JSD"
            }
        )
    )

    display(
        JSD_SUMMARY
    )

print("\n" + "=" * 100)
print("PART G5 — JENSEN-SHANNON DIVERGENCE COMPLETED")
print("=" * 100)

====================================================================================================
PART G5 — JENSEN-SHANNON DIVERGENCE
====================================================================================================

Empty DataFrame
Columns: []
Index: []

----------------------------------------------------------------------------------------------------
JSD SUMMARY
----------------------------------------------------------------------------------------------------

====================================================================================================
PART G5 — JENSEN-SHANNON DIVERGENCE COMPLETED
====================================================================================================

In [106]:
# ==============================================================================
# PART G6 — CHI-SQUARE DISTRIBUTION TEST
# ==============================================================================

print("=" * 100)
print("PART G6 — CHI-SQUARE DISTRIBUTION TEST")
print("=" * 100)

CHI_SQUARE_RESULTS = []

for method in SYNTHETIC_METHODS:

    for dataset in SYNTHETIC_DATASET_NAMES:

        synthetic_df = (
            SYNTHETIC_DATASETS
            .get(method, {})
            .get(dataset)
        )

        reference_df = (
            REAL_DATASETS
            .get(dataset)
        )

        if synthetic_df is None or reference_df is None:
            continue

        for column in CATEGORICAL_FEATURES.get(
            dataset,
            []
        ):

            if column not in synthetic_df.columns:
                continue

            reference_counts = (
                reference_df[column]
                .value_counts(
                    dropna=False
                )
            )

            synthetic_counts = (
                synthetic_df[column]
                .value_counts(
                    dropna=False
                )
            )

            categories = list(
                set(reference_counts.index)
                | set(synthetic_counts.index)
            )

            if len(categories) < 2:
                continue

            reference_total = (
                reference_counts.sum()
            )

            synthetic_total = (
                synthetic_counts.sum()
            )

            if (
                reference_total <= 0
                or synthetic_total <= 0
            ):
                continue

            reference_probabilities = np.array([
                reference_counts.get(
                    category,
                    0
                )
                for category in categories
            ], dtype=float)

            reference_probabilities /= (
                reference_probabilities.sum()
            )

            observed = np.array([
                synthetic_counts.get(
                    category,
                    0
                )
                for category in categories
            ], dtype=float)

            expected = (
                reference_probabilities
                * synthetic_total
            )

            valid = expected > 0

            if valid.sum() < 2:
                continue

            chi_square_statistic, p_value = (
                stats.chisquare(
                    f_obs=observed[valid],
                    f_exp=expected[valid]
                )
            )

            degrees_of_freedom = (
                int(valid.sum() - 1)
            )

            CHI_SQUARE_RESULTS.append({

                "Method": method,
                "Dataset": dataset,
                "Feature": column,
                "Chi-Square Statistic":
                    float(chi_square_statistic),
                "P-Value":
                    float(p_value),
                "Degrees of Freedom":
                    degrees_of_freedom,
                "Significant Difference (α=0.05)":
                    bool(p_value < 0.05)
            })

CHI_SQUARE_DF = pd.DataFrame(
    CHI_SQUARE_RESULTS
)

display(
    CHI_SQUARE_DF
)

print("\n" + "=" * 100)
print("PART G6 — CHI-SQUARE DISTRIBUTION TEST COMPLETED")
print("=" * 100)

====================================================================================================
PART G6 — CHI-SQUARE DISTRIBUTION TEST
====================================================================================================

Empty DataFrame
Columns: []
Index: []

====================================================================================================
PART G6 — CHI-SQUARE DISTRIBUTION TEST COMPLETED
====================================================================================================

In [107]:
# ==============================================================================
# PART G7 — CATEGORICAL FIDELITY SUMMARY
# ==============================================================================

print("=" * 100)
print("PART G7 — CATEGORICAL FIDELITY SUMMARY")
print("=" * 100)

SUMMARY_KEYS = [
    "Method",
    "Dataset"
]

# --------------------------------------------------------------------------
# Base Evaluation Combinations
# --------------------------------------------------------------------------

CATEGORICAL_FIDELITY_SUMMARY = []

for method in SYNTHETIC_METHODS:

    for dataset in SYNTHETIC_DATASET_NAMES:

        coverage_subset = (
            CATEGORY_COVERAGE_DF[
                (
                    CATEGORY_COVERAGE_DF["Method"]
                    == method
                )
                &
                (
                    CATEGORY_COVERAGE_DF["Dataset"]
                    == dataset
                )
            ]
            if not CATEGORY_COVERAGE_DF.empty
            else pd.DataFrame()
        )

        tvd_subset = (
            TVD_DF[
                (
                    TVD_DF["Method"]
                    == method
                )
                &
                (
                    TVD_DF["Dataset"]
                    == dataset
                )
            ]
            if not TVD_DF.empty
            else pd.DataFrame()
        )

        jsd_subset = (
            JSD_DF[
                (
                    JSD_DF["Method"]
                    == method
                )
                &
                (
                    JSD_DF["Dataset"]
                    == dataset
                )
            ]
            if not JSD_DF.empty
            else pd.DataFrame()
        )

        chi_subset = (
            CHI_SQUARE_DF[
                (
                    CHI_SQUARE_DF["Method"]
                    == method
                )
                &
                (
                    CHI_SQUARE_DF["Dataset"]
                    == dataset
                )
            ]
            if not CHI_SQUARE_DF.empty
            else pd.DataFrame()
        )

        mean_coverage = (
            coverage_subset[
                "Category Coverage"
            ].mean()
            if not coverage_subset.empty
            else np.nan
        )

        mean_tvd = (
            tvd_subset[
                "Total Variation Distance"
            ].mean()
            if not tvd_subset.empty
            else np.nan
        )

        mean_jsd = (
            jsd_subset[
                "Jensen-Shannon Divergence"
            ].mean()
            if not jsd_subset.empty
            else np.nan
        )

        mean_chi_square = (
            chi_subset[
                "Chi-Square Statistic"
            ].mean()
            if not chi_subset.empty
            else np.nan
        )

        chi_square_pass_rate = (
            (
                ~chi_subset[
                    "Significant Difference (α=0.05)"
                ]
            ).mean()
            if not chi_subset.empty
            else np.nan
        )

        evaluated_features = len(
            tvd_subset
        )

        CATEGORICAL_FIDELITY_SUMMARY.append({

            "Method": method,
            "Dataset": dataset,
            "Categorical Features Evaluated":
                evaluated_features,
            "Mean Category Coverage":
                mean_coverage,
            "Mean TVD":
                mean_tvd,
            "Mean JSD":
                mean_jsd,
            "Mean Chi-Square Statistic":
                mean_chi_square,
            "Chi-Square Non-Significant Rate":
                chi_square_pass_rate
        })

CATEGORICAL_FIDELITY_SUMMARY_DF = pd.DataFrame(
    CATEGORICAL_FIDELITY_SUMMARY
)

display(
    CATEGORICAL_FIDELITY_SUMMARY_DF
)

print("\n" + "=" * 100)
print("PART G7 — CATEGORICAL FIDELITY SUMMARY COMPLETED")
print("=" * 100)

====================================================================================================
PART G7 — CATEGORICAL FIDELITY SUMMARY
====================================================================================================

,Method,Dataset,Categorical Features Evaluated,Mean Category Coverage,Mean TVD,Mean JSD,Mean Chi-Square Statistic,Chi-Square Non-Significant Rate
0,CTGAN,adult_income,0,NaN,NaN,NaN,NaN,NaN
1,CTGAN,bank_marketing,0,NaN,NaN,NaN,NaN,NaN
2,CTGAN,diabetes_130us,0,NaN,NaN,NaN,NaN,NaN
3,TVAE,adult_income,0,NaN,NaN,NaN,NaN,NaN
4,TVAE,bank_marketing,0,NaN,NaN,NaN,NaN,NaN
5,TVAE,diabetes_130us,0,NaN,NaN,NaN,NaN,NaN
6,DP-CTGAN,adult_income,0,NaN,NaN,NaN,NaN,NaN
7,DP-CTGAN,bank_marketing,0,NaN,NaN,NaN,NaN,NaN
8,DP-CTGAN,diabetes_130us,0,NaN,NaN,NaN,NaN,NaN
9,SPP-GAN,adult_income,0,NaN,NaN,NaN,NaN,NaN
10,SPP-GAN,bank_marketing,0,NaN,NaN,NaN,NaN,NaN
11,SPP-GAN,diabetes_130us,0,NaN,NaN,NaN,NaN,NaN

====================================================================================================
PART G7 — CATEGORICAL FIDELITY SUMMARY COMPLETED
====================================================================================================

In [108]:
# ==============================================================================
# PART G8 — RESEARCH-READY CATEGORICAL FIDELITY REPORT
# ==============================================================================

print("=" * 100)
print("PART G8 — RESEARCH-READY CATEGORICAL FIDELITY REPORT")
print("=" * 100)

G8_DF = (
    CATEGORICAL_FIDELITY_SUMMARY_DF
    .copy()
)

if G8_DF.empty:

    print("No categorical fidelity results available.")

else:

    # --------------------------------------------------------------------------
    # Normalized Coverage
    # --------------------------------------------------------------------------

    G8_DF[
        "Coverage Score"
    ] = (
        G8_DF[
            "Mean Category Coverage"
        ]
        .clip(0, 1)
    )

    # --------------------------------------------------------------------------
    # Normalize TVD
    # --------------------------------------------------------------------------

    tvd_max = (
        G8_DF["Mean TVD"]
        .max(skipna=True)
    )

    if (
        pd.notna(tvd_max)
        and tvd_max > 0
    ):

        G8_DF[
            "TVD Score"
        ] = (
            1
            -
            (
                G8_DF["Mean TVD"]
                / tvd_max
            )
        ).clip(0, 1)

    else:

        G8_DF[
            "TVD Score"
        ] = 1.0

    # --------------------------------------------------------------------------
    # Normalize JSD
    # --------------------------------------------------------------------------

    jsd_max = (
        G8_DF["Mean JSD"]
        .max(skipna=True)
    )

    if (
        pd.notna(jsd_max)
        and jsd_max > 0
    ):

        G8_DF[
            "JSD Score"
        ] = (
            1
            -
            (
                G8_DF["Mean JSD"]
                / jsd_max
            )
        ).clip(0, 1)

    else:

        G8_DF[
            "JSD Score"
        ] = 1.0

    # --------------------------------------------------------------------------
    # Chi-Square Score
    # --------------------------------------------------------------------------

    G8_DF[
        "Chi-Square Score"
    ] = (
        G8_DF[
            "Chi-Square Non-Significant Rate"
        ]
        .clip(0, 1)
    )

    # --------------------------------------------------------------------------
    # Composite Categorical Fidelity Score
    #
    # Equal weighting is used only for comparative ranking.
    # --------------------------------------------------------------------------

    G8_DF[
        "Categorical Fidelity Score"
    ] = (
        G8_DF["Coverage Score"]
        + G8_DF["TVD Score"]
        + G8_DF["JSD Score"]
        + G8_DF["Chi-Square Score"]
    ) / 4.0

    # --------------------------------------------------------------------------
    # Rank Within Dataset
    # --------------------------------------------------------------------------

    G8_DF[
        "Categorical Fidelity Rank"
    ] = (
        G8_DF
        .groupby("Dataset")[
            "Categorical Fidelity Score"
        ]
        .rank(
            ascending=False,
            method="min"
        )
    )

display(
    G8_DF.sort_values(
        [
            "Dataset",
            "Categorical Fidelity Rank"
        ]
    )
)

print("\n" + "-" * 100)
print("OVERALL METHOD CATEGORICAL FIDELITY")
print("-" * 100)

G8_METHOD_SUMMARY = (
    G8_DF
    .groupby(
        "Method",
        as_index=False
    )
    .agg({

        "Categorical Fidelity Score":
            "mean",

        "Mean Category Coverage":
            "mean",

        "Mean TVD":
            "mean",

        "Mean JSD":
            "mean",

        "Chi-Square Non-Significant Rate":
            "mean"
    })
    .sort_values(
        "Categorical Fidelity Score",
        ascending=False
    )
)

G8_METHOD_SUMMARY[
    "Overall Categorical Fidelity Rank"
] = (
    G8_METHOD_SUMMARY[
        "Categorical Fidelity Score"
    ]
    .rank(
        ascending=False,
        method="min"
    )
)

display(
    G8_METHOD_SUMMARY
)

print("\n" + "=" * 100)
print("PART G8 — RESEARCH-READY CATEGORICAL FIDELITY REPORT COMPLETED")
print("=" * 100)

====================================================================================================
PART G8 — RESEARCH-READY CATEGORICAL FIDELITY REPORT
====================================================================================================

,Method,Dataset,Categorical Features Evaluated,Mean Category Coverage,Mean TVD,Mean JSD,Mean Chi-Square Statistic,Chi-Square Non-Significant Rate,Coverage Score,TVD Score,JSD Score,Chi-Square Score,Categorical Fidelity Score,Categorical Fidelity Rank
0,CTGAN,adult_income,0,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0,NaN,NaN,NaN
3,TVAE,adult_income,0,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0,NaN,NaN,NaN
6,DP-CTGAN,adult_income,0,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0,NaN,NaN,NaN
9,SPP-GAN,adult_income,0,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0,NaN,NaN,NaN
1,CTGAN,bank_marketing,0,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0,NaN,NaN,NaN
4,TVAE,bank_marketing,0,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0,NaN,NaN,NaN
7,DP-CTGAN,bank_marketing,0,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0,NaN,NaN,NaN
10,SPP-GAN,bank_marketing,0,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0,NaN,NaN,NaN
2,CTGAN,diabetes_130us,0,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0,NaN,NaN,NaN
5,TVAE,diabetes_130us,0,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0,NaN,NaN,NaN
8,DP-CTGAN,diabetes_130us,0,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0,NaN,NaN,NaN
11,SPP-GAN,diabetes_130us,0,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0,NaN,NaN,NaN

----------------------------------------------------------------------------------------------------
OVERALL METHOD CATEGORICAL FIDELITY
----------------------------------------------------------------------------------------------------

,Method,Categorical Fidelity Score,Mean Category Coverage,Mean TVD,Mean JSD,Chi-Square Non-Significant Rate,Overall Categorical Fidelity Rank
0,CTGAN,NaN,NaN,NaN,NaN,NaN,NaN
1,DP-CTGAN,NaN,NaN,NaN,NaN,NaN,NaN
2,SPP-GAN,NaN,NaN,NaN,NaN,NaN,NaN
3,TVAE,NaN,NaN,NaN,NaN,NaN,NaN

====================================================================================================
PART G8 — RESEARCH-READY CATEGORICAL FIDELITY REPORT COMPLETED
====================================================================================================

In [109]:
# ==============================================================================
# PART H1 — CORRELATION AND ASSOCIATION PREPARATION
# ==============================================================================

print("=" * 100)
print("PART H1 — CORRELATION AND ASSOCIATION PREPARATION")
print("=" * 100)

# ------------------------------------------------------------------------------
# Evaluation Containers
# ------------------------------------------------------------------------------

CORRELATION_NUMERICAL_RESULTS = []
CATEGORICAL_ASSOCIATION_RESULTS = []
MIXED_ASSOCIATION_RESULTS = []

CORRELATION_MATRIX_REGISTRY = {}
ASSOCIATION_MATRIX_REGISTRY = {}

# ------------------------------------------------------------------------------
# Required Objects
# ------------------------------------------------------------------------------

if "REAL_DATASETS" not in globals():
    raise NameError(
        "REAL_DATASETS is not defined. "
        "Section C must be executed before Section H."
    )

if "SYNTHETIC_DATASETS" not in globals():
    raise NameError(
        "SYNTHETIC_DATASETS is not defined. "
        "Section D must be executed before Section H."
    )

if "SYNTHETIC_METHODS" not in globals():
    raise NameError(
        "SYNTHETIC_METHODS is not defined."
    )

if "SYNTHETIC_DATASET_NAMES" not in globals():
    raise NameError(
        "SYNTHETIC_DATASET_NAMES is not defined."
    )

# ------------------------------------------------------------------------------
# Utility Functions
# ------------------------------------------------------------------------------

def get_numeric_columns(df):
    return df.select_dtypes(
        include=[np.number]
    ).columns.tolist()


def get_categorical_columns(df):
    return df.select_dtypes(
        include=["object", "category", "bool"]
    ).columns.tolist()


def safe_numeric_dataframe(df, columns):
    if not columns:
        return pd.DataFrame(index=df.index)

    numeric_df = df[columns].apply(
        pd.to_numeric,
        errors="coerce"
    )

    return numeric_df


def align_common_columns(real_df, synthetic_df):

    common_columns = [
        column
        for column in real_df.columns
        if column in synthetic_df.columns
    ]

    return (
        real_df[common_columns].copy(),
        synthetic_df[common_columns].copy(),
        common_columns
    )


# ------------------------------------------------------------------------------
# Dataset-Level Preparation Summary
# ------------------------------------------------------------------------------

H1_PREPARATION_RESULTS = []

for dataset in SYNTHETIC_DATASET_NAMES:

    real_df = REAL_DATASETS.get(dataset)

    if real_df is None:
        continue

    numeric_columns = get_numeric_columns(real_df)
    categorical_columns = get_categorical_columns(real_df)

    H1_PREPARATION_RESULTS.append({

        "Dataset": dataset,

        "Total Columns": len(real_df.columns),

        "Numerical Columns": len(numeric_columns),

        "Categorical Columns": len(categorical_columns),

        "Numerical Features": numeric_columns,

        "Categorical Features": categorical_columns

    })


H1_PREPARATION_DF = pd.DataFrame(
    H1_PREPARATION_RESULTS
)

display(H1_PREPARATION_DF)

print("\n" + "=" * 100)
print("PART H1 — CORRELATION AND ASSOCIATION PREPARATION COMPLETED")
print("=" * 100)

====================================================================================================
PART H1 — CORRELATION AND ASSOCIATION PREPARATION
====================================================================================================

,Dataset,Total Columns,Numerical Columns,Categorical Columns,Numerical Features,Categorical Features
0,adult_income,15,15,0,"[age, workclass, fnlwgt, education, education_...",[]
1,bank_marketing,17,17,0,"[age, job, marital, education, default, balanc...",[]
2,diabetes_130us,48,48,0,"[race, gender, age, weight, admission_type_id,...",[]

====================================================================================================
PART H1 — CORRELATION AND ASSOCIATION PREPARATION COMPLETED
====================================================================================================

In [110]:
# ==============================================================================
# PART H2 — NUMERICAL CORRELATION FIDELITY
# ==============================================================================

print("=" * 100)
print("PART H2 — NUMERICAL CORRELATION FIDELITY")
print("=" * 100)

PEARSON_CORRELATION_RESULTS = []
SPEARMAN_CORRELATION_RESULTS = []

CORRELATION_MATRIX_REGISTRY = {}

# ------------------------------------------------------------------------------
# Correlation Distance Function
# ------------------------------------------------------------------------------

def correlation_distance(real_corr, synthetic_corr):

    real_values = real_corr.values
    synthetic_values = synthetic_corr.values

    valid_mask = (
        np.isfinite(real_values)
        & np.isfinite(synthetic_values)
    )

    if not np.any(valid_mask):
        return np.nan

    return np.mean(
        np.abs(
            real_values[valid_mask]
            - synthetic_values[valid_mask]
        )
    )


# ------------------------------------------------------------------------------
# Dataset / Method Evaluation
# ------------------------------------------------------------------------------

for method in SYNTHETIC_METHODS:

    for dataset in SYNTHETIC_DATASET_NAMES:

        real_df = REAL_DATASETS.get(dataset)

        synthetic_df = (
            SYNTHETIC_DATASETS
            .get(method, {})
            .get(dataset)
        )

        if real_df is None or synthetic_df is None:
            continue

        # ----------------------------------------------------------------------
        # Numerical Columns
        # ----------------------------------------------------------------------

        numerical_columns = get_numeric_columns(real_df)

        numerical_columns = [
            column
            for column in numerical_columns
            if column in synthetic_df.columns
        ]

        if len(numerical_columns) < 2:
            continue

        real_numeric = safe_numeric_dataframe(
            real_df,
            numerical_columns
        )

        synthetic_numeric = safe_numeric_dataframe(
            synthetic_df,
            numerical_columns
        )

        # ----------------------------------------------------------------------
        # Pearson
        # ----------------------------------------------------------------------

        real_pearson = real_numeric.corr(
            method="pearson"
        )

        synthetic_pearson = synthetic_numeric.corr(
            method="pearson"
        )

        pearson_distance = correlation_distance(
            real_pearson,
            synthetic_pearson
        )

        # ----------------------------------------------------------------------
        # Spearman
        # ----------------------------------------------------------------------

        real_spearman = real_numeric.corr(
            method="spearman"
        )

        synthetic_spearman = synthetic_numeric.corr(
            method="spearman"
        )

        spearman_distance = correlation_distance(
            real_spearman,
            synthetic_spearman
        )

        # ----------------------------------------------------------------------
        # Store Matrices
        # ----------------------------------------------------------------------

        CORRELATION_MATRIX_REGISTRY[
            (method, dataset)
        ] = {

            "Real Pearson": real_pearson,

            "Synthetic Pearson": synthetic_pearson,

            "Real Spearman": real_spearman,

            "Synthetic Spearman": synthetic_spearman

        }

        # ----------------------------------------------------------------------
        # Store Summary Results
        # ----------------------------------------------------------------------

        PEARSON_CORRELATION_RESULTS.append({

            "Method": method,

            "Dataset": dataset,

            "Numerical Features": len(
                numerical_columns
            ),

            "Pearson MAE": pearson_distance,

            "Pearson Fidelity (%)":
                (
                    max(
                        0.0,
                        1.0 - pearson_distance
                    ) * 100
                    if pd.notna(pearson_distance)
                    else np.nan
                )

        })

        SPEARMAN_CORRELATION_RESULTS.append({

            "Method": method,

            "Dataset": dataset,

            "Numerical Features": len(
                numerical_columns
            ),

            "Spearman MAE": spearman_distance,

            "Spearman Fidelity (%)":
                (
                    max(
                        0.0,
                        1.0 - spearman_distance
                    ) * 100
                    if pd.notna(spearman_distance)
                    else np.nan
                )

        })


PEARSON_CORRELATION_DF = pd.DataFrame(
    PEARSON_CORRELATION_RESULTS
)

SPEARMAN_CORRELATION_DF = pd.DataFrame(
    SPEARMAN_CORRELATION_RESULTS
)

print("\nPEARSON CORRELATION FIDELITY")

display(
    PEARSON_CORRELATION_DF
)

print("\nSPEARMAN CORRELATION FIDELITY")

display(
    SPEARMAN_CORRELATION_DF
)

print("\n" + "=" * 100)
print("PART H2 — NUMERICAL CORRELATION FIDELITY COMPLETED")
print("=" * 100)

====================================================================================================
PART H2 — NUMERICAL CORRELATION FIDELITY
====================================================================================================

PEARSON CORRELATION FIDELITY

,Method,Dataset,Numerical Features,Pearson MAE,Pearson Fidelity (%)
0,CTGAN,adult_income,15,0.034169,96.583106
1,CTGAN,bank_marketing,17,0.026660,97.333975
2,CTGAN,diabetes_130us,48,0.017428,98.257207
3,TVAE,adult_income,15,0.038193,96.180669
4,TVAE,bank_marketing,17,0.029540,97.046003
5,TVAE,diabetes_130us,48,0.044433,95.556746
6,DP-CTGAN,adult_income,15,0.234718,76.528172
7,DP-CTGAN,bank_marketing,17,0.209419,79.058108
8,DP-CTGAN,diabetes_130us,48,0.309400,69.059953
9,SPP-GAN,adult_income,15,0.050547,94.945293
10,SPP-GAN,bank_marketing,17,0.045679,95.432119
11,SPP-GAN,diabetes_130us,48,0.014891,98.510893

SPEARMAN CORRELATION FIDELITY

,Method,Dataset,Numerical Features,Spearman MAE,Spearman Fidelity (%)
0,CTGAN,adult_income,15,0.040900,95.910007
1,CTGAN,bank_marketing,17,0.028994,97.100555
2,CTGAN,diabetes_130us,48,0.020870,97.912975
3,TVAE,adult_income,15,0.037277,96.272328
4,TVAE,bank_marketing,17,0.029395,97.060485
5,TVAE,diabetes_130us,48,0.045437,95.456325
6,DP-CTGAN,adult_income,15,0.236473,76.352673
7,DP-CTGAN,bank_marketing,17,0.212974,78.702554
8,DP-CTGAN,diabetes_130us,48,0.289504,71.049551
9,SPP-GAN,adult_income,15,0.055227,94.477275
10,SPP-GAN,bank_marketing,17,0.048795,95.120549
11,SPP-GAN,diabetes_130us,48,0.016515,98.348546

====================================================================================================
PART H2 — NUMERICAL CORRELATION FIDELITY COMPLETED
====================================================================================================

In [111]:
# ==============================================================================
# PART H3 — CATEGORICAL ASSOCIATION FIDELITY
# ==============================================================================

print("=" * 100)
print("PART H3 — CATEGORICAL ASSOCIATION FIDELITY")
print("=" * 100)

CATEGORICAL_ASSOCIATION_RESULTS = []

# ------------------------------------------------------------------------------
# Cramér's V
# ------------------------------------------------------------------------------

def cramers_v(x, y):

    data = pd.DataFrame({
        "x": x,
        "y": y
    }).dropna()

    if data.empty:
        return np.nan

    contingency_table = pd.crosstab(
        data["x"],
        data["y"]
    )

    if contingency_table.shape[0] < 2:
        return np.nan

    if contingency_table.shape[1] < 2:
        return np.nan

    chi2 = stats.chi2_contingency(
        contingency_table,
        correction=False
    )[0]

    n = contingency_table.values.sum()

    if n <= 0:
        return np.nan

    phi2 = chi2 / n

    rows, columns = contingency_table.shape

    denominator = min(
        columns - 1,
        rows - 1
    )

    if denominator <= 0:
        return np.nan

    return np.sqrt(
        phi2 / denominator
    )


# ------------------------------------------------------------------------------
# Dataset / Method Evaluation
# ------------------------------------------------------------------------------

for method in SYNTHETIC_METHODS:

    for dataset in SYNTHETIC_DATASET_NAMES:

        real_df = REAL_DATASETS.get(dataset)

        synthetic_df = (
            SYNTHETIC_DATASETS
            .get(method, {})
            .get(dataset)
        )

        if real_df is None or synthetic_df is None:
            continue

        categorical_columns = get_categorical_columns(
            real_df
        )

        categorical_columns = [
            column
            for column in categorical_columns
            if column in synthetic_df.columns
        ]

        if len(categorical_columns) < 2:
            continue

        # ----------------------------------------------------------------------
        # Pairwise Association
        # ----------------------------------------------------------------------

        for i in range(
            len(categorical_columns)
        ):

            for j in range(
                i + 1,
                len(categorical_columns)
            ):

                column_a = categorical_columns[i]
                column_b = categorical_columns[j]

                real_v = cramers_v(
                    real_df[column_a],
                    real_df[column_b]
                )

                synthetic_v = cramers_v(
                    synthetic_df[column_a],
                    synthetic_df[column_b]
                )

                if pd.isna(real_v) or pd.isna(
                    synthetic_v
                ):
                    continue

                association_error = abs(
                    real_v - synthetic_v
                )

                CATEGORICAL_ASSOCIATION_RESULTS.append({

                    "Method": method,

                    "Dataset": dataset,

                    "Feature A": column_a,

                    "Feature B": column_b,

                    "Real Cramer's V": real_v,

                    "Synthetic Cramer's V":
                        synthetic_v,

                    "Absolute Error":
                        association_error

                })


CATEGORICAL_ASSOCIATION_DF = pd.DataFrame(
    CATEGORICAL_ASSOCIATION_RESULTS
)

display(
    CATEGORICAL_ASSOCIATION_DF
)

print("\n" + "=" * 100)
print("PART H3 — CATEGORICAL ASSOCIATION FIDELITY COMPLETED")
print("=" * 100)

====================================================================================================
PART H3 — CATEGORICAL ASSOCIATION FIDELITY
====================================================================================================

Empty DataFrame
Columns: []
Index: []

====================================================================================================
PART H3 — CATEGORICAL ASSOCIATION FIDELITY COMPLETED
====================================================================================================

In [112]:
# ==============================================================================
# PART H4 — MIXED-TYPE ASSOCIATION FIDELITY
# ==============================================================================

print("=" * 100)
print("PART H4 — MIXED-TYPE ASSOCIATION FIDELITY")
print("=" * 100)

MIXED_ASSOCIATION_RESULTS = []

# ------------------------------------------------------------------------------
# Correlation Ratio η
# ------------------------------------------------------------------------------

def correlation_ratio(categories, values):

    data = pd.DataFrame({
        "category": categories,
        "value": values
    }).dropna()

    if data.empty:
        return np.nan

    values_array = pd.to_numeric(
        data["value"],
        errors="coerce"
    )

    valid_mask = np.isfinite(
        values_array
    )

    data = data.loc[valid_mask]

    if data.empty:
        return np.nan

    grand_mean = values_array[
        valid_mask
    ].mean()

    numerator = 0.0
    denominator = np.sum(
        (
            values_array[
                valid_mask
            ]
            - grand_mean
        ) ** 2
    )

    if denominator <= 0:
        return 0.0

    for category in data["category"].unique():

        category_values = (
            data.loc[
                data["category"] == category,
                "value"
            ]
            .astype(float)
            .values
        )

        if len(category_values) == 0:
            continue

        category_mean = (
            category_values.mean()
        )

        numerator += (
            len(category_values)
            * (
                category_mean
                - grand_mean
            ) ** 2
        )

    return np.sqrt(
        numerator / denominator
    )


# ------------------------------------------------------------------------------
# Dataset / Method Evaluation
# ------------------------------------------------------------------------------

for method in SYNTHETIC_METHODS:

    for dataset in SYNTHETIC_DATASET_NAMES:

        real_df = REAL_DATASETS.get(dataset)

        synthetic_df = (
            SYNTHETIC_DATASETS
            .get(method, {})
            .get(dataset)
        )

        if real_df is None or synthetic_df is None:
            continue

        numerical_columns = get_numeric_columns(
            real_df
        )

        categorical_columns = get_categorical_columns(
            real_df
        )

        numerical_columns = [
            column
            for column in numerical_columns
            if column in synthetic_df.columns
        ]

        categorical_columns = [
            column
            for column in categorical_columns
            if column in synthetic_df.columns
        ]

        if not numerical_columns or not categorical_columns:
            continue

        for categorical_column in categorical_columns:

            for numerical_column in numerical_columns:

                real_eta = correlation_ratio(
                    real_df[categorical_column],
                    real_df[numerical_column]
                )

                synthetic_eta = correlation_ratio(
                    synthetic_df[categorical_column],
                    synthetic_df[numerical_column]
                )

                if pd.isna(real_eta) or pd.isna(
                    synthetic_eta
                ):
                    continue

                mixed_error = abs(
                    real_eta - synthetic_eta
                )

                MIXED_ASSOCIATION_RESULTS.append({

                    "Method": method,

                    "Dataset": dataset,

                    "Categorical Feature":
                        categorical_column,

                    "Numerical Feature":
                        numerical_column,

                    "Real Eta": real_eta,

                    "Synthetic Eta":
                        synthetic_eta,

                    "Absolute Error":
                        mixed_error

                })


MIXED_ASSOCIATION_DF = pd.DataFrame(
    MIXED_ASSOCIATION_RESULTS
)

display(
    MIXED_ASSOCIATION_DF
)

print("\n" + "=" * 100)
print("PART H4 — MIXED-TYPE ASSOCIATION FIDELITY COMPLETED")
print("=" * 100)

====================================================================================================
PART H4 — MIXED-TYPE ASSOCIATION FIDELITY
====================================================================================================

Empty DataFrame
Columns: []
Index: []

====================================================================================================
PART H4 — MIXED-TYPE ASSOCIATION FIDELITY COMPLETED
====================================================================================================

In [116]:
# ==============================================================================
# PART H5 — CORRELATION AND ASSOCIATION ERROR SUMMARY
# ==============================================================================

print("=" * 100)
print("PART H5 — CORRELATION AND ASSOCIATION ERROR SUMMARY")
print("=" * 100)

# ------------------------------------------------------------------------------
# Required Columns
# ------------------------------------------------------------------------------

METRIC_COLUMN_REQUIREMENTS = {
    "PEARSON_CORRELATION_DF": [
        "Method",
        "Dataset",
        "Pearson MAE"
    ],
    "SPEARMAN_CORRELATION_DF": [
        "Method",
        "Dataset",
        "Spearman MAE"
    ],
    "CATEGORICAL_ASSOCIATION_DF": [
        "Method",
        "Dataset",
        "Absolute Error"
    ],
    "MIXED_ASSOCIATION_DF": [
        "Method",
        "Dataset",
        "Absolute Error"
    ]
}

# ------------------------------------------------------------------------------
# Safe DataFrame Preparation
# ------------------------------------------------------------------------------

def prepare_metric_dataframe(
    dataframe,
    required_columns,
    dataframe_name
):

    if dataframe is None:

        return pd.DataFrame(
            columns=required_columns
        )

    if not isinstance(
        dataframe,
        pd.DataFrame
    ):

        return pd.DataFrame(
            columns=required_columns
        )

    if dataframe.empty:

        return pd.DataFrame(
            columns=required_columns
        )

    missing_columns = [
        column
        for column in required_columns
        if column not in dataframe.columns
    ]

    if missing_columns:

        print(
            f"\nWARNING: {dataframe_name} "
            f"is missing columns: {missing_columns}"
        )

        print(
            f"Available columns: "
            f"{dataframe.columns.tolist()}"
        )

        return pd.DataFrame(
            columns=required_columns
        )

    return dataframe.copy()

# ------------------------------------------------------------------------------
# Prepare All Metric DataFrames
# ------------------------------------------------------------------------------

PEARSON_CORRELATION_DF = prepare_metric_dataframe(

    PEARSON_CORRELATION_DF
    if "PEARSON_CORRELATION_DF" in globals()
    else None,

    METRIC_COLUMN_REQUIREMENTS[
        "PEARSON_CORRELATION_DF"
    ],

    "PEARSON_CORRELATION_DF"
)

SPEARMAN_CORRELATION_DF = prepare_metric_dataframe(

    SPEARMAN_CORRELATION_DF
    if "SPEARMAN_CORRELATION_DF" in globals()
    else None,

    METRIC_COLUMN_REQUIREMENTS[
        "SPEARMAN_CORRELATION_DF"
    ],

    "SPEARMAN_CORRELATION_DF"
)

CATEGORICAL_ASSOCIATION_DF = prepare_metric_dataframe(

    CATEGORICAL_ASSOCIATION_DF
    if "CATEGORICAL_ASSOCIATION_DF" in globals()
    else None,

    METRIC_COLUMN_REQUIREMENTS[
        "CATEGORICAL_ASSOCIATION_DF"
    ],

    "CATEGORICAL_ASSOCIATION_DF"
)

MIXED_ASSOCIATION_DF = prepare_metric_dataframe(

    MIXED_ASSOCIATION_DF
    if "MIXED_ASSOCIATION_DF" in globals()
    else None,

    METRIC_COLUMN_REQUIREMENTS[
        "MIXED_ASSOCIATION_DF"
    ],

    "MIXED_ASSOCIATION_DF"
)

# ------------------------------------------------------------------------------
# Metric Availability Report
# ------------------------------------------------------------------------------

print("\n" + "-" * 100)
print("H5 METRIC AVAILABILITY")
print("-" * 100)

H5_METRIC_AVAILABILITY = pd.DataFrame({

    "Metric": [
        "Pearson Correlation",
        "Spearman Correlation",
        "Categorical Association",
        "Mixed Association"
    ],

    "Rows Available": [
        len(PEARSON_CORRELATION_DF),
        len(SPEARMAN_CORRELATION_DF),
        len(CATEGORICAL_ASSOCIATION_DF),
        len(MIXED_ASSOCIATION_DF)
    ],

    "Status": [
        "AVAILABLE"
        if not PEARSON_CORRELATION_DF.empty
        else "NO VALID OBSERVATIONS",

        "AVAILABLE"
        if not SPEARMAN_CORRELATION_DF.empty
        else "NO VALID OBSERVATIONS",

        "AVAILABLE"
        if not CATEGORICAL_ASSOCIATION_DF.empty
        else "NO VALID OBSERVATIONS",

        "AVAILABLE"
        if not MIXED_ASSOCIATION_DF.empty
        else "NO VALID OBSERVATIONS"
    ]
})

display(
    H5_METRIC_AVAILABILITY
)

# ------------------------------------------------------------------------------
# Build Summary
# ------------------------------------------------------------------------------

H5_RESULTS = []

for method in SYNTHETIC_METHODS:

    for dataset in SYNTHETIC_DATASET_NAMES:

        # ----------------------------------------------------------------------
        # Pearson
        # ----------------------------------------------------------------------

        pearson_subset = PEARSON_CORRELATION_DF.loc[
            (
                PEARSON_CORRELATION_DF["Method"]
                == method
            )
            &
            (
                PEARSON_CORRELATION_DF["Dataset"]
                == dataset
            )
        ]

        # ----------------------------------------------------------------------
        # Spearman
        # ----------------------------------------------------------------------

        spearman_subset = SPEARMAN_CORRELATION_DF.loc[
            (
                SPEARMAN_CORRELATION_DF["Method"]
                == method
            )
            &
            (
                SPEARMAN_CORRELATION_DF["Dataset"]
                == dataset
            )
        ]

        # ----------------------------------------------------------------------
        # Categorical Association
        # ----------------------------------------------------------------------

        categorical_subset = CATEGORICAL_ASSOCIATION_DF.loc[
            (
                CATEGORICAL_ASSOCIATION_DF["Method"]
                == method
            )
            &
            (
                CATEGORICAL_ASSOCIATION_DF["Dataset"]
                == dataset
            )
        ]

        # ----------------------------------------------------------------------
        # Mixed Association
        # ----------------------------------------------------------------------

        mixed_subset = MIXED_ASSOCIATION_DF.loc[
            (
                MIXED_ASSOCIATION_DF["Method"]
                == method
            )
            &
            (
                MIXED_ASSOCIATION_DF["Dataset"]
                == dataset
            )
        ]

        # ----------------------------------------------------------------------
        # Calculate Metric Errors
        # ----------------------------------------------------------------------

        pearson_error = (
            pd.to_numeric(
                pearson_subset["Pearson MAE"],
                errors="coerce"
            ).mean()
            if not pearson_subset.empty
            else np.nan
        )

        spearman_error = (
            pd.to_numeric(
                spearman_subset["Spearman MAE"],
                errors="coerce"
            ).mean()
            if not spearman_subset.empty
            else np.nan
        )

        categorical_error = (
            pd.to_numeric(
                categorical_subset["Absolute Error"],
                errors="coerce"
            ).mean()
            if not categorical_subset.empty
            else np.nan
        )

        mixed_error = (
            pd.to_numeric(
                mixed_subset["Absolute Error"],
                errors="coerce"
            ).mean()
            if not mixed_subset.empty
            else np.nan
        )

        # ----------------------------------------------------------------------
        # Available Metric Errors
        # ----------------------------------------------------------------------

        available_errors = [
            value
            for value in [
                pearson_error,
                spearman_error,
                categorical_error,
                mixed_error
            ]
            if pd.notna(value)
        ]

        # ----------------------------------------------------------------------
        # Overall Error
        # ----------------------------------------------------------------------

        overall_error = (
            float(
                np.mean(
                    available_errors
                )
            )
            if available_errors
            else np.nan
        )

        # ----------------------------------------------------------------------
        # Overall Fidelity
        # ----------------------------------------------------------------------

        overall_fidelity = (

            max(
                0.0,
                1.0 - overall_error
            ) * 100.0

            if pd.notna(
                overall_error
            )

            else np.nan
        )

        # ----------------------------------------------------------------------
        # Metric Coverage
        # ----------------------------------------------------------------------

        metric_count = len(
            available_errors
        )

        metric_coverage = (
            metric_count / 4.0
        ) * 100.0

        # ----------------------------------------------------------------------
        # Status
        # ----------------------------------------------------------------------

        if metric_count == 4:

            status = "COMPLETE"

        elif metric_count > 0:

            status = "PARTIAL"

        else:

            status = "NO VALID METRICS"

        # ----------------------------------------------------------------------
        # Append Result
        # ----------------------------------------------------------------------

        H5_RESULTS.append({

            "Method":
                method,

            "Dataset":
                dataset,

            "Pearson MAE":
                pearson_error,

            "Spearman MAE":
                spearman_error,

            "Categorical Association MAE":
                categorical_error,

            "Mixed Association MAE":
                mixed_error,

            "Available Metrics":
                metric_count,

            "Metric Coverage (%)":
                metric_coverage,

            "Overall Association Error":
                overall_error,

            "Overall Correlation/Association Fidelity (%)":
                overall_fidelity,

            "Status":
                status

        })

# ------------------------------------------------------------------------------
# Create Final H5 DataFrame
# ------------------------------------------------------------------------------

CORRELATION_ASSOCIATION_SUMMARY_DF = pd.DataFrame(
    H5_RESULTS
)

# ------------------------------------------------------------------------------
# Display
# ------------------------------------------------------------------------------

display(
    CORRELATION_ASSOCIATION_SUMMARY_DF
)

# ------------------------------------------------------------------------------
# Summary Statistics
# ------------------------------------------------------------------------------

print("\n" + "-" * 100)
print("H5 SUMMARY")
print("-" * 100)

TOTAL_COMBINATIONS = len(
    CORRELATION_ASSOCIATION_SUMMARY_DF
)

COMPLETE_COMBINATIONS = int(
    (
        CORRELATION_ASSOCIATION_SUMMARY_DF["Status"]
        == "COMPLETE"
    ).sum()
)

PARTIAL_COMBINATIONS = int(
    (
        CORRELATION_ASSOCIATION_SUMMARY_DF["Status"]
        == "PARTIAL"
    ).sum()
)

NO_METRIC_COMBINATIONS = int(
    (
        CORRELATION_ASSOCIATION_SUMMARY_DF["Status"]
        == "NO VALID METRICS"
    ).sum()
)

print(
    f"Total Method–Dataset Combinations : "
    f"{TOTAL_COMBINATIONS}"
)

print(
    f"Complete Metric Combinations      : "
    f"{COMPLETE_COMBINATIONS}"
)

print(
    f"Partial Metric Combinations       : "
    f"{PARTIAL_COMBINATIONS}"
)

print(
    f"No Valid Metric Combinations      : "
    f"{NO_METRIC_COMBINATIONS}"
)

if TOTAL_COMBINATIONS > 0:

    H5_COMPLETENESS_RATE = (
        COMPLETE_COMBINATIONS
        / TOTAL_COMBINATIONS
    ) * 100.0

else:

    H5_COMPLETENESS_RATE = np.nan

print(
    f"Complete Metric Coverage Rate     : "
    f"{H5_COMPLETENESS_RATE:.2f}%"
)

# ------------------------------------------------------------------------------
# Final Status
# ------------------------------------------------------------------------------

if NO_METRIC_COMBINATIONS == TOTAL_COMBINATIONS:

    H5_FINAL_STATUS = (
        "NO VALID CORRELATION/ASSOCIATION METRICS"
    )

elif COMPLETE_COMBINATIONS == TOTAL_COMBINATIONS:

    H5_FINAL_STATUS = "COMPLETE"

else:

    H5_FINAL_STATUS = "PARTIAL"

print(
    f"H5 Final Status                   : "
    f"{H5_FINAL_STATUS}"
)

print("\n" + "=" * 100)
print(
    "PART H5 — CORRELATION AND ASSOCIATION "
    "ERROR SUMMARY COMPLETED"
)
print("=" * 100)

====================================================================================================
PART H5 — CORRELATION AND ASSOCIATION ERROR SUMMARY
====================================================================================================

----------------------------------------------------------------------------------------------------
H5 METRIC AVAILABILITY
----------------------------------------------------------------------------------------------------

                    Metric  Rows Available                 Status
0      Pearson Correlation              12              AVAILABLE
1     Spearman Correlation              12              AVAILABLE
2  Categorical Association               0  NO VALID OBSERVATIONS
3        Mixed Association               0  NO VALID OBSERVATIONS

,Method,Dataset,Pearson MAE,Spearman MAE,Categorical Association MAE,Mixed Association MAE,Available Metrics,Metric Coverage (%),Overall Association Error,Overall Correlation/Association Fidelity (%),Status
0,CTGAN,adult_income,0.034169,0.040900,NaN,NaN,2,50.0,0.037534,96.246556,PARTIAL
1,CTGAN,bank_marketing,0.026660,0.028994,NaN,NaN,2,50.0,0.027827,97.217265,PARTIAL
2,CTGAN,diabetes_130us,0.017428,0.020870,NaN,NaN,2,50.0,0.019149,98.085091,PARTIAL
3,TVAE,adult_income,0.038193,0.037277,NaN,NaN,2,50.0,0.037735,96.226499,PARTIAL
4,TVAE,bank_marketing,0.029540,0.029395,NaN,NaN,2,50.0,0.029468,97.053244,PARTIAL
5,TVAE,diabetes_130us,0.044433,0.045437,NaN,NaN,2,50.0,0.044935,95.506536,PARTIAL
6,DP-CTGAN,adult_income,0.234718,0.236473,NaN,NaN,2,50.0,0.235596,76.440423,PARTIAL
7,DP-CTGAN,bank_marketing,0.209419,0.212974,NaN,NaN,2,50.0,0.211197,78.880331,PARTIAL
8,DP-CTGAN,diabetes_130us,0.309400,0.289504,NaN,NaN,2,50.0,0.299452,70.054752,PARTIAL
9,SPP-GAN,adult_income,0.050547,0.055227,NaN,NaN,2,50.0,0.052887,94.711284,PARTIAL
10,SPP-GAN,bank_marketing,0.045679,0.048795,NaN,NaN,2,50.0,0.047237,95.276334,PARTIAL
11,SPP-GAN,diabetes_130us,0.014891,0.016515,NaN,NaN,2,50.0,0.015703,98.429720,PARTIAL

----------------------------------------------------------------------------------------------------
H5 SUMMARY
----------------------------------------------------------------------------------------------------
Total Method–Dataset Combinations : 12
Complete Metric Combinations      : 0
Partial Metric Combinations       : 12
No Valid Metric Combinations      : 0
Complete Metric Coverage Rate     : 0.00%
H5 Final Status                   : PARTIAL

====================================================================================================
PART H5 — CORRELATION AND ASSOCIATION ERROR SUMMARY COMPLETED
====================================================================================================

In [117]:
# ==============================================================================
# PART H6 — METHOD-LEVEL CORRELATION AND ASSOCIATION RANKING
# ==============================================================================

print("=" * 100)
print("PART H6 — METHOD-LEVEL CORRELATION AND ASSOCIATION RANKING")
print("=" * 100)

# ------------------------------------------------------------------------------
# Aggregate Across Datasets
# ------------------------------------------------------------------------------

H6_METHOD_SUMMARY = (
    CORRELATION_ASSOCIATION_SUMMARY_DF
    .groupby("Method", dropna=False)
    .agg({

        "Pearson MAE": "mean",

        "Spearman MAE": "mean",

        "Categorical Association MAE": "mean",

        "Mixed Association MAE": "mean",

        "Overall Association Error": "mean",

        "Overall Correlation/Association Fidelity (%)":
            "mean"

    })
    .reset_index()
)

# ------------------------------------------------------------------------------
# Rank
# ------------------------------------------------------------------------------

H6_METHOD_SUMMARY[
    "Correlation/Association Rank"
] = (
    H6_METHOD_SUMMARY[
        "Overall Correlation/Association Fidelity (%)"
    ]
    .rank(
        ascending=False,
        method="min"
    )
    .astype("Int64")
)

H6_METHOD_SUMMARY = (
    H6_METHOD_SUMMARY
    .sort_values(
        "Correlation/Association Rank"
    )
    .reset_index(drop=True)
)

display(
    H6_METHOD_SUMMARY
)

# ------------------------------------------------------------------------------
# Best Method
# ------------------------------------------------------------------------------

if not H6_METHOD_SUMMARY.empty:

    best_method = H6_METHOD_SUMMARY.iloc[0]

    print("\nBEST METHOD FOR CORRELATION / ASSOCIATION PRESERVATION")

    print(
        f"Method   : {best_method['Method']}"
    )

    print(
        "Fidelity : "
        f"{best_method['Overall Correlation/Association Fidelity (%)']:.2f}%"
    )

# ------------------------------------------------------------------------------
# Method-Level Ranking Table
# ------------------------------------------------------------------------------

H6_CORRELATION_ASSOCIATION_RANKING = (
    H6_METHOD_SUMMARY[
        [
            "Correlation/Association Rank",
            "Method",
            "Pearson MAE",
            "Spearman MAE",
            "Categorical Association MAE",
            "Mixed Association MAE",
            "Overall Association Error",
            "Overall Correlation/Association Fidelity (%)"
        ]
    ]
)

display(
    H6_CORRELATION_ASSOCIATION_RANKING
)

print("\n" + "=" * 100)
print("PART H6 — METHOD-LEVEL CORRELATION AND ASSOCIATION RANKING COMPLETED")
print("=" * 100)

====================================================================================================
PART H6 — METHOD-LEVEL CORRELATION AND ASSOCIATION RANKING
====================================================================================================

,Method,Pearson MAE,Spearman MAE,Categorical Association MAE,Mixed Association MAE,Overall Association Error,Overall Correlation/Association Fidelity (%),Correlation/Association Rank
0,CTGAN,0.026086,0.030255,NaN,NaN,0.028170,97.182971,1
1,TVAE,0.037389,0.037370,NaN,NaN,0.037379,96.262093,2
2,SPP-GAN,0.037039,0.040179,NaN,NaN,0.038609,96.139113,3
3,DP-CTGAN,0.251179,0.246317,NaN,NaN,0.248748,75.125168,4

BEST METHOD FOR CORRELATION / ASSOCIATION PRESERVATION
Method   : CTGAN
Fidelity : 97.18%

,Correlation/Association Rank,Method,Pearson MAE,Spearman MAE,Categorical Association MAE,Mixed Association MAE,Overall Association Error,Overall Correlation/Association Fidelity (%)
0,1,CTGAN,0.026086,0.030255,NaN,NaN,0.028170,97.182971
1,2,TVAE,0.037389,0.037370,NaN,NaN,0.037379,96.262093
2,3,SPP-GAN,0.037039,0.040179,NaN,NaN,0.038609,96.139113
3,4,DP-CTGAN,0.251179,0.246317,NaN,NaN,0.248748,75.125168

====================================================================================================
PART H6 — METHOD-LEVEL CORRELATION AND ASSOCIATION RANKING COMPLETED
====================================================================================================

In [122]:
# ==============================================================================
# PART I1 — SDMETRICS ENVIRONMENT AND METRIC CONFIGURATION
# ==============================================================================

print("=" * 100)
print("PART I1 — SDMETRICS ENVIRONMENT AND METRIC CONFIGURATION")
print("=" * 100)

import inspect
import sdmetrics

from sdmetrics.reports.single_table import QualityReport

print("\nSDMetrics Configuration")
print("-" * 100)

print(f"SDMetrics Version : {sdmetrics.__version__}")

QUALITY_REPORT_SIGNATURE = inspect.signature(
    QualityReport.generate
)

print("\nQualityReport.generate Signature:")
print(QUALITY_REPORT_SIGNATURE)

# ------------------------------------------------------------------------------
# Detect Available Arguments
# ------------------------------------------------------------------------------

QUALITY_REPORT_PARAMETERS = set(
    QUALITY_REPORT_SIGNATURE.parameters.keys()
)

print("\nDetected Parameters:")
for parameter in QUALITY_REPORT_PARAMETERS:
    print(f"  ✓ {parameter}")

# ------------------------------------------------------------------------------
# Evaluation Configuration
# ------------------------------------------------------------------------------

SDMETRICS_EVALUATION_CONFIG = {

    "Report Type":
        "SingleTable QualityReport",

    "Evaluation Level":
        "Column and Column-Pair Quality",

    "Use Metadata":
        True,

    "Numerical Metrics":
        True,

    "Categorical Metrics":
        True,

    "Column Pair Metrics":
        True,

    "Aggregate Quality Score":
        True
}

print("\nEvaluation Configuration")
print("-" * 100)

for key, value in SDMETRICS_EVALUATION_CONFIG.items():
    print(f"{key:<30}: {value}")

print("\n" + "=" * 100)
print("PART I1 — SDMETRICS ENVIRONMENT AND METRIC CONFIGURATION COMPLETED")
print("=" * 100)

====================================================================================================
PART I1 — SDMETRICS ENVIRONMENT AND METRIC CONFIGURATION
====================================================================================================

SDMetrics Configuration
----------------------------------------------------------------------------------------------------
SDMetrics Version : 0.28.2

QualityReport.generate Signature:
(self, real_data, synthetic_data, metadata, verbose=True)

Detected Parameters:
  ✓ synthetic_data
  ✓ verbose
  ✓ real_data
  ✓ self
  ✓ metadata

Evaluation Configuration
----------------------------------------------------------------------------------------------------
Report Type                   : SingleTable QualityReport
Evaluation Level              : Column and Column-Pair Quality
Use Metadata                  : True
Numerical Metrics             : True
Categorical Metrics           : True
Column Pair Metrics           : True
Aggregate Quality Score       : True

====================================================================================================
PART I1 — SDMETRICS ENVIRONMENT AND METRIC CONFIGURATION COMPLETED
====================================================================================================

In [123]:
# ==============================================================================
# PART I2 — SDMETRICS METADATA PREPARATION
# ==============================================================================

print("=" * 100)
print("PART I2 — SDMETRICS METADATA PREPARATION")
print("=" * 100)

# ------------------------------------------------------------------------------
# Storage
# ------------------------------------------------------------------------------

SDMETRICS_METADATA = {}
SDMETRICS_METADATA_STATUS = []

# ------------------------------------------------------------------------------
# Detect SDV Metadata Availability
# ------------------------------------------------------------------------------

try:

    from sdv.metadata import SingleTableMetadata

    SDV_METADATA_AVAILABLE = True

    print("\n✓ SDV SingleTableMetadata available")

except ImportError:

    SDV_METADATA_AVAILABLE = False

    print("\n✗ SDV SingleTableMetadata unavailable")

# ------------------------------------------------------------------------------
# Build Metadata from Real Reference Data
# ------------------------------------------------------------------------------

if SDV_METADATA_AVAILABLE:

    for dataset in SYNTHETIC_DATASET_NAMES:

        reference_df = (
            REAL_DATASETS.get(dataset)
            if "REAL_DATASETS" in globals()
            else None
        )

        if reference_df is None:

            SDMETRICS_METADATA_STATUS.append({

                "Dataset":
                    dataset,

                "Reference Loaded":
                    False,

                "Metadata Created":
                    False,

                "Status":
                    "REFERENCE NOT LOADED"

            })

            continue

        try:

            metadata = SingleTableMetadata()

            metadata.detect_from_dataframe(
                data=reference_df
            )

            SDMETRICS_METADATA[
                dataset
            ] = metadata

            SDMETRICS_METADATA_STATUS.append({

                "Dataset":
                    dataset,

                "Reference Loaded":
                    True,

                "Metadata Created":
                    True,

                "Status":
                    "PASS"

            })

            print(
                f"✓ {dataset:<20} | "
                f"Metadata created"
            )

        except Exception as error:

            SDMETRICS_METADATA_STATUS.append({

                "Dataset":
                    dataset,

                "Reference Loaded":
                    True,

                "Metadata Created":
                    False,

                "Status":
                    f"ERROR: {type(error).__name__}"

            })

            print(
                f"✗ {dataset:<20} | "
                f"ERROR: {error}"
            )

else:

    for dataset in SYNTHETIC_DATASET_NAMES:

        SDMETRICS_METADATA_STATUS.append({

            "Dataset":
                dataset,

            "Reference Loaded":
                dataset in REAL_DATASETS,

            "Metadata Created":
                False,

            "Status":
                "SDV METADATA UNAVAILABLE"

        })

SDMETRICS_METADATA_DF = pd.DataFrame(
    SDMETRICS_METADATA_STATUS
)

print("\n" + "-" * 100)
print("SDMETRICS METADATA STATUS")
print("-" * 100)

display(
    SDMETRICS_METADATA_DF
)

print("\n" + "=" * 100)
print("PART I2 — SDMETRICS METADATA PREPARATION COMPLETED")
print("=" * 100)

====================================================================================================
PART I2 — SDMETRICS METADATA PREPARATION
====================================================================================================

✓ SDV SingleTableMetadata available
✓ adult_income         | Metadata created
✓ bank_marketing       | Metadata created
✓ diabetes_130us       | Metadata created

----------------------------------------------------------------------------------------------------
SDMETRICS METADATA STATUS
----------------------------------------------------------------------------------------------------

          Dataset  Reference Loaded  Metadata Created Status
0    adult_income              True              True   PASS
1  bank_marketing              True              True   PASS
2  diabetes_130us              True              True   PASS

====================================================================================================
PART I2 — SDMETRICS METADATA PREPARATION COMPLETED
====================================================================================================

In [128]:
# ==============================================================================
# PART I3 — SDMETRICS SINGLE-TABLE QUALITY EVALUATION
# ==============================================================================

print("=" * 100)
print("PART I3 — SDMETRICS SINGLE-TABLE QUALITY EVALUATION")
print("=" * 100)

# ------------------------------------------------------------------------------
# IMPORTS
# ------------------------------------------------------------------------------

from sdmetrics.reports.single_table import QualityReport
from sdv.metadata import SingleTableMetadata
import inspect
import numpy as np
import pandas as pd

# ------------------------------------------------------------------------------
# VERSION INFORMATION
# ------------------------------------------------------------------------------

try:
    import sdmetrics
    import sdv

    print("\nSDMetrics Version:", sdmetrics.__version__)
    print("SDV Version      :", sdv.__version__)

except Exception as error:

    print(
        "Version information unavailable:",
        error
    )

# ------------------------------------------------------------------------------
# BUILD A CLEAN METADATA REGISTRY
# ------------------------------------------------------------------------------

print("\n" + "-" * 100)
print("BUILDING CLEAN SDMETRICS METADATA")
print("-" * 100)

I3_METADATA_REGISTRY = {}

for dataset in SYNTHETIC_DATASET_NAMES:

    reference_df = (
        REAL_DATASETS.get(dataset)
        if "REAL_DATASETS" in globals()
        else None
    )

    if reference_df is None:

        print(
            f"✗ {dataset:<20} | "
            "Reference dataset unavailable"
        )

        continue

    try:

        # ----------------------------------------------------------------------
        # ALWAYS DETECT FRESH METADATA
        # ----------------------------------------------------------------------

        metadata_object = (
            SingleTableMetadata.detect_from_dataframe(
                data=reference_df
            )
        )

        # ----------------------------------------------------------------------
        # CONVERT SDV METADATA OBJECT TO DICTIONARY
        # ----------------------------------------------------------------------

        metadata_dict = metadata_object.to_dict()

        # ----------------------------------------------------------------------
        # VALIDATE METADATA STRUCTURE
        # ----------------------------------------------------------------------

        if not isinstance(metadata_dict, dict):

            raise TypeError(
                "Metadata conversion did not return "
                "a dictionary."
            )

        if "columns" not in metadata_dict:

            raise KeyError(
                "Metadata dictionary does not contain "
                "'columns'."
            )

        if not isinstance(
            metadata_dict["columns"],
            dict
        ):

            raise TypeError(
                "Metadata['columns'] must be a dictionary."
            )

        # ----------------------------------------------------------------------
        # VALIDATE EACH COLUMN DEFINITION
        # ----------------------------------------------------------------------

        invalid_columns = []

        for column_name, column_definition in (
            metadata_dict["columns"].items()
        ):

            if not isinstance(
                column_definition,
                dict
            ):

                invalid_columns.append(
                    (
                        column_name,
                        type(column_definition).__name__
                    )
                )

        if invalid_columns:

            raise TypeError(
                "Invalid column metadata detected: "
                f"{invalid_columns}"
            )

        # ----------------------------------------------------------------------
        # STORE CLEAN METADATA
        # ----------------------------------------------------------------------

        I3_METADATA_REGISTRY[
            dataset
        ] = metadata_dict

        print(
            f"✓ {dataset:<20} | "
            f"{len(metadata_dict['columns'])} columns"
        )

    except Exception as error:

        print(
            f"✗ {dataset:<20} | "
            f"METADATA ERROR: {error}"
        )

# ------------------------------------------------------------------------------
# METADATA VALIDATION SUMMARY
# ------------------------------------------------------------------------------

print("\n" + "-" * 100)
print("METADATA VALIDATION SUMMARY")
print("-" * 100)

for dataset, metadata in I3_METADATA_REGISTRY.items():

    print(
        f"✓ {dataset:<20} | "
        f"Columns: {len(metadata['columns'])}"
    )

# ------------------------------------------------------------------------------
# SDMETRICS QUALITY EVALUATION
# ------------------------------------------------------------------------------

print("\n" + "-" * 100)
print("SDMETRICS QUALITY EVALUATION")
print("-" * 100)

SDMETRICS_RESULTS = []

for method in SYNTHETIC_METHODS:

    for dataset in SYNTHETIC_DATASET_NAMES:

        reference_df = (
            REAL_DATASETS.get(dataset)
            if "REAL_DATASETS" in globals()
            else None
        )

        synthetic_df = (
            SYNTHETIC_DATASETS
            .get(method, {})
            .get(dataset)
            if "SYNTHETIC_DATASETS" in globals()
            else None
        )

        metadata_dict = (
            I3_METADATA_REGISTRY.get(dataset)
        )

        # ----------------------------------------------------------------------
        # INPUT VALIDATION
        # ----------------------------------------------------------------------

        if reference_df is None:

            SDMETRICS_RESULTS.append({

                "Method": method,
                "Dataset": dataset,
                "Reference Loaded": False,
                "Synthetic Loaded": (
                    synthetic_df is not None
                ),
                "Quality Score": np.nan,
                "Status": "REFERENCE NOT LOADED"

            })

            print(
                f"✗ {method:<12} | "
                f"{dataset:<20} | "
                "Reference not loaded"
            )

            continue

        if synthetic_df is None:

            SDMETRICS_RESULTS.append({

                "Method": method,
                "Dataset": dataset,
                "Reference Loaded": True,
                "Synthetic Loaded": False,
                "Quality Score": np.nan,
                "Status": "SYNTHETIC NOT LOADED"

            })

            print(
                f"✗ {method:<12} | "
                f"{dataset:<20} | "
                "Synthetic not loaded"
            )

            continue

        if metadata_dict is None:

            SDMETRICS_RESULTS.append({

                "Method": method,
                "Dataset": dataset,
                "Reference Loaded": True,
                "Synthetic Loaded": True,
                "Quality Score": np.nan,
                "Status": "METADATA NOT AVAILABLE"

            })

            print(
                f"✗ {method:<12} | "
                f"{dataset:<20} | "
                "Metadata unavailable"
            )

            continue

        # ----------------------------------------------------------------------
        # SCHEMA VALIDATION
        # ----------------------------------------------------------------------

        reference_columns = (
            reference_df.columns.tolist()
        )

        synthetic_columns = (
            synthetic_df.columns.tolist()
        )

        if reference_columns != synthetic_columns:

            SDMETRICS_RESULTS.append({

                "Method": method,
                "Dataset": dataset,
                "Reference Loaded": True,
                "Synthetic Loaded": True,
                "Quality Score": np.nan,
                "Status": "SCHEMA MISMATCH"

            })

            print(
                f"✗ {method:<12} | "
                f"{dataset:<20} | "
                "Schema mismatch"
            )

            continue

        # ----------------------------------------------------------------------
        # SDMETRICS QUALITY REPORT
        # ----------------------------------------------------------------------

        try:

            quality_report = QualityReport()

            # IMPORTANT:
            # Use explicit keyword arguments.
            # Pass the CLEAN metadata dictionary.

            quality_report.generate(
                real_data=reference_df,
                synthetic_data=synthetic_df,
                metadata=metadata_dict
            )

            # ------------------------------------------------------------------
            # EXTRACT OVERALL QUALITY SCORE
            # ------------------------------------------------------------------

            quality_score = (
                quality_report.get_score()
            )

            if quality_score is None:

                raise ValueError(
                    "SDMetrics returned no quality score."
                )

            quality_score = float(
                quality_score
            )

            # ------------------------------------------------------------------
            # VALIDATE SCORE
            # ------------------------------------------------------------------

            if not np.isfinite(
                quality_score
            ):

                raise ValueError(
                    "SDMetrics returned a non-finite "
                    "quality score."
                )

            # ------------------------------------------------------------------
            # STORE SUCCESSFUL RESULT
            # ------------------------------------------------------------------

            SDMETRICS_RESULTS.append({

                "Method": method,
                "Dataset": dataset,
                "Reference Loaded": True,
                "Synthetic Loaded": True,
                "Quality Score": quality_score,
                "Status": "PASS"

            })

            print(
                f"✓ {method:<12} | "
                f"{dataset:<20} | "
                f"Quality Score = "
                f"{quality_score:.6f}"
            )

        except Exception as error:

            SDMETRICS_RESULTS.append({

                "Method": method,
                "Dataset": dataset,
                "Reference Loaded": True,
                "Synthetic Loaded": True,
                "Quality Score": np.nan,
                "Status": (
                    f"ERROR: "
                    f"{type(error).__name__}"
                )

            })

            print(
                f"✗ {method:<12} | "
                f"{dataset:<20} | "
                f"ERROR: {error}"
            )

# ------------------------------------------------------------------------------
# RESULT DATAFRAME
# ------------------------------------------------------------------------------

SDMETRICS_QUALITY_DF = pd.DataFrame(
    SDMETRICS_RESULTS
)

display(
    SDMETRICS_QUALITY_DF
)

# ------------------------------------------------------------------------------
# SUMMARY
# ------------------------------------------------------------------------------

print("\n" + "-" * 100)
print("I3 SUMMARY")
print("-" * 100)

total_combinations = len(
    SDMETRICS_QUALITY_DF
)

successful_evaluations = int(
    (
        SDMETRICS_QUALITY_DF["Status"]
        == "PASS"
    ).sum()
)

failed_evaluations = (
    total_combinations
    - successful_evaluations
)

print(
    f"Total Method–Dataset Combinations : "
    f"{total_combinations}"
)

print(
    f"Successfully Evaluated             : "
    f"{successful_evaluations}"
)

print(
    f"Not Evaluated / Failed              : "
    f"{failed_evaluations}"
)

if total_combinations > 0:

    evaluation_rate = (
        successful_evaluations
        / total_combinations
        * 100
    )

else:

    evaluation_rate = 0.0

print(
    f"Evaluation Success Rate             : "
    f"{evaluation_rate:.2f}%"
)

# ------------------------------------------------------------------------------
# SCORE SUMMARY
# ------------------------------------------------------------------------------

successful_scores = (
    SDMETRICS_QUALITY_DF.loc[
        SDMETRICS_QUALITY_DF["Status"] == "PASS",
        "Quality Score"
    ]
    .dropna()
)

if not successful_scores.empty:

    print(
        f"Mean Quality Score                 : "
        f"{successful_scores.mean():.6f}"
    )

    print(
        f"Minimum Quality Score              : "
        f"{successful_scores.min():.6f}"
    )

    print(
        f"Maximum Quality Score              : "
        f"{successful_scores.max():.6f}"
    )

else:

    print(
        "Mean Quality Score                 : "
        "Not available"
    )

print("\n" + "=" * 100)
print(
    "PART I3 — SDMETRICS SINGLE-TABLE "
    "QUALITY EVALUATION COMPLETED"
)
print("=" * 100)

====================================================================================================
PART I3 — SDMETRICS SINGLE-TABLE QUALITY EVALUATION
====================================================================================================

SDMetrics Version: 0.28.2
SDV Version      : 1.38.0

----------------------------------------------------------------------------------------------------
BUILDING CLEAN SDMETRICS METADATA
----------------------------------------------------------------------------------------------------
✗ adult_income         | METADATA ERROR: SingleTableMetadata.detect_from_dataframe() missing 1 required positional argument: 'self'
✗ bank_marketing       | METADATA ERROR: SingleTableMetadata.detect_from_dataframe() missing 1 required positional argument: 'self'
✗ diabetes_130us       | METADATA ERROR: SingleTableMetadata.detect_from_dataframe() missing 1 required positional argument: 'self'

----------------------------------------------------------------------------------------------------
METADATA VALIDATION SUMMARY
----------------------------------------------------------------------------------------------------

----------------------------------------------------------------------------------------------------
SDMETRICS QUALITY EVALUATION
----------------------------------------------------------------------------------------------------
✗ CTGAN        | adult_income         | Metadata unavailable
✗ CTGAN        | bank_marketing       | Metadata unavailable
✗ CTGAN        | diabetes_130us       | Metadata unavailable
✗ TVAE         | adult_income         | Metadata unavailable
✗ TVAE         | bank_marketing       | Metadata unavailable
✗ TVAE         | diabetes_130us       | Metadata unavailable
✗ DP-CTGAN     | adult_income         | Metadata unavailable
✗ DP-CTGAN     | bank_marketing       | Metadata unavailable
✗ DP-CTGAN     | diabetes_130us       | Metadata unavailable
✗ SPP-GAN      | adult_income         | Metadata unavailable
✗ SPP-GAN      | bank_marketing       | Metadata unavailable
✗ SPP-GAN      | diabetes_130us       | Metadata unavailable

,Method,Dataset,Reference Loaded,Synthetic Loaded,Quality Score,Status
0,CTGAN,adult_income,True,True,NaN,METADATA NOT AVAILABLE
1,CTGAN,bank_marketing,True,True,NaN,METADATA NOT AVAILABLE
2,CTGAN,diabetes_130us,True,True,NaN,METADATA NOT AVAILABLE
3,TVAE,adult_income,True,True,NaN,METADATA NOT AVAILABLE
4,TVAE,bank_marketing,True,True,NaN,METADATA NOT AVAILABLE
5,TVAE,diabetes_130us,True,True,NaN,METADATA NOT AVAILABLE
6,DP-CTGAN,adult_income,True,True,NaN,METADATA NOT AVAILABLE
7,DP-CTGAN,bank_marketing,True,True,NaN,METADATA NOT AVAILABLE
8,DP-CTGAN,diabetes_130us,True,True,NaN,METADATA NOT AVAILABLE
9,SPP-GAN,adult_income,True,True,NaN,METADATA NOT AVAILABLE
10,SPP-GAN,bank_marketing,True,True,NaN,METADATA NOT AVAILABLE
11,SPP-GAN,diabetes_130us,True,True,NaN,METADATA NOT AVAILABLE

----------------------------------------------------------------------------------------------------
I3 SUMMARY
----------------------------------------------------------------------------------------------------
Total Method–Dataset Combinations : 12
Successfully Evaluated             : 0
Not Evaluated / Failed              : 12
Evaluation Success Rate             : 0.00%
Mean Quality Score                 : Not available

====================================================================================================
PART I3 — SDMETRICS SINGLE-TABLE QUALITY EVALUATION COMPLETED
====================================================================================================

In [129]:
# ==============================================================================
# PART I4 — SDMETRICS QUALITY SCORE CLASSIFICATION
# ==============================================================================

print("=" * 100)
print("PART I4 — SDMETRICS QUALITY SCORE CLASSIFICATION")
print("=" * 100)

def classify_sdmetrics_quality(score):

    if pd.isna(score):

        return "NOT AVAILABLE"

    if score >= 0.90:

        return "EXCELLENT"

    if score >= 0.75:

        return "GOOD"

    if score >= 0.60:

        return "MODERATE"

    if score >= 0.40:

        return "LOW"

    return "VERY LOW"

# ------------------------------------------------------------------------------
# Apply Classification
# ------------------------------------------------------------------------------

SDMETRICS_QUALITY_DF["Quality Classification"] = (
    SDMETRICS_QUALITY_DF[
        "Quality Score"
    ].apply(
        classify_sdmetrics_quality
    )
)

display(
    SDMETRICS_QUALITY_DF
)

print("\n" + "=" * 100)
print(
    "PART I4 — SDMETRICS QUALITY SCORE "
    "CLASSIFICATION COMPLETED"
)
print("=" * 100)

====================================================================================================
PART I4 — SDMETRICS QUALITY SCORE CLASSIFICATION
====================================================================================================

,Method,Dataset,Reference Loaded,Synthetic Loaded,Quality Score,Status,Quality Classification
0,CTGAN,adult_income,True,True,NaN,METADATA NOT AVAILABLE,NOT AVAILABLE
1,CTGAN,bank_marketing,True,True,NaN,METADATA NOT AVAILABLE,NOT AVAILABLE
2,CTGAN,diabetes_130us,True,True,NaN,METADATA NOT AVAILABLE,NOT AVAILABLE
3,TVAE,adult_income,True,True,NaN,METADATA NOT AVAILABLE,NOT AVAILABLE
4,TVAE,bank_marketing,True,True,NaN,METADATA NOT AVAILABLE,NOT AVAILABLE
5,TVAE,diabetes_130us,True,True,NaN,METADATA NOT AVAILABLE,NOT AVAILABLE
6,DP-CTGAN,adult_income,True,True,NaN,METADATA NOT AVAILABLE,NOT AVAILABLE
7,DP-CTGAN,bank_marketing,True,True,NaN,METADATA NOT AVAILABLE,NOT AVAILABLE
8,DP-CTGAN,diabetes_130us,True,True,NaN,METADATA NOT AVAILABLE,NOT AVAILABLE
9,SPP-GAN,adult_income,True,True,NaN,METADATA NOT AVAILABLE,NOT AVAILABLE
10,SPP-GAN,bank_marketing,True,True,NaN,METADATA NOT AVAILABLE,NOT AVAILABLE
11,SPP-GAN,diabetes_130us,True,True,NaN,METADATA NOT AVAILABLE,NOT AVAILABLE

====================================================================================================
PART I4 — SDMETRICS QUALITY SCORE CLASSIFICATION COMPLETED
====================================================================================================

In [130]:
# ==============================================================================
# PART I5 — SDMETRICS PROPERTY-LEVEL SUMMARY
# ==============================================================================

print("=" * 100)
print("PART I5 — SDMETRICS PROPERTY-LEVEL SUMMARY")
print("=" * 100)

if (
    "SDMETRICS_PROPERTY_DF" in globals()
    and not SDMETRICS_PROPERTY_DF.empty
):

    print("\nProperty-Level SDMetrics Results")

    display(
        SDMETRICS_PROPERTY_DF
    )

    # --------------------------------------------------------------------------
    # Identify Score Column
    # --------------------------------------------------------------------------

    score_candidates = [
        "Score",
        "score"
    ]

    SDMETRICS_PROPERTY_SCORE_COLUMN = None

    for column in score_candidates:

        if column in SDMETRICS_PROPERTY_DF.columns:

            SDMETRICS_PROPERTY_SCORE_COLUMN = column
            break

    if SDMETRICS_PROPERTY_SCORE_COLUMN:

        SDMETRICS_PROPERTY_SUMMARY_DF = (

            SDMETRICS_PROPERTY_DF

            .groupby(
                ["Method", "Dataset"],
                as_index=False
            )[SDMETRICS_PROPERTY_SCORE_COLUMN]

            .mean()

            .rename(
                columns={
                    SDMETRICS_PROPERTY_SCORE_COLUMN:
                    "Mean Property Quality Score"
                }
            )

        )

    else:

        SDMETRICS_PROPERTY_SUMMARY_DF = (
            pd.DataFrame()
        )

else:

    print(
        "\nNo SDMetrics property-level "
        "results are available."
    )

    SDMETRICS_PROPERTY_SUMMARY_DF = (
        pd.DataFrame()
    )

if not SDMETRICS_PROPERTY_SUMMARY_DF.empty:

    display(
        SDMETRICS_PROPERTY_SUMMARY_DF
    )

print("\n" + "=" * 100)
print(
    "PART I5 — SDMETRICS PROPERTY-LEVEL "
    "SUMMARY COMPLETED"
)
print("=" * 100)

====================================================================================================
PART I5 — SDMETRICS PROPERTY-LEVEL SUMMARY
====================================================================================================

No SDMetrics property-level results are available.

====================================================================================================
PART I5 — SDMETRICS PROPERTY-LEVEL SUMMARY COMPLETED
====================================================================================================

In [131]:
# ==============================================================================
# PART I6 — SDMETRICS METHOD COMPARISON
# ==============================================================================

print("=" * 100)
print("PART I6 — SDMETRICS METHOD COMPARISON")
print("=" * 100)

if (
    "SDMETRICS_QUALITY_DF" in globals()
    and not SDMETRICS_QUALITY_DF.empty
):

    SDMETRICS_METHOD_COMPARISON_DF = (

        SDMETRICS_QUALITY_DF

        .groupby(
            "Method",
            as_index=False
        )

        .agg(

            Datasets_Evaluated=(
                "Quality Score",
                lambda x: x.notna().sum()
            ),

            Mean_Quality_Score=(
                "Quality Score",
                "mean"
            ),

            Minimum_Quality_Score=(
                "Quality Score",
                "min"
            ),

            Maximum_Quality_Score=(
                "Quality Score",
                "max"
            ),

            Standard_Deviation=(
                "Quality Score",
                "std"
            )

        )

    )

    SDMETRICS_METHOD_COMPARISON_DF = (
        SDMETRICS_METHOD_COMPARISON_DF
        .rename(
            columns={
                "Datasets_Evaluated":
                    "Datasets Evaluated",

                "Mean_Quality_Score":
                    "Mean Quality Score",

                "Minimum_Quality_Score":
                    "Minimum Quality Score",

                "Maximum_Quality_Score":
                    "Maximum Quality Score",

                "Standard_Deviation":
                    "Standard Deviation"
            }
        )
    )

    display(
        SDMETRICS_METHOD_COMPARISON_DF
    )

else:

    SDMETRICS_METHOD_COMPARISON_DF = (
        pd.DataFrame()
    )

    print(
        "No SDMetrics quality results available."
    )

print("\n" + "=" * 100)
print(
    "PART I6 — SDMETRICS METHOD COMPARISON COMPLETED"
)
print("=" * 100)

====================================================================================================
PART I6 — SDMETRICS METHOD COMPARISON
====================================================================================================

,Method,Datasets Evaluated,Mean Quality Score,Minimum Quality Score,Maximum Quality Score,Standard Deviation
0,CTGAN,0,NaN,NaN,NaN,NaN
1,DP-CTGAN,0,NaN,NaN,NaN,NaN
2,SPP-GAN,0,NaN,NaN,NaN,NaN
3,TVAE,0,NaN,NaN,NaN,NaN

====================================================================================================
PART I6 — SDMETRICS METHOD COMPARISON COMPLETED
====================================================================================================

In [132]:
# ==============================================================================
# PART I7 — SDMETRICS DATASET COMPARISON
# ==============================================================================

print("=" * 100)
print("PART I7 — SDMETRICS DATASET COMPARISON")
print("=" * 100)

if (
    "SDMETRICS_QUALITY_DF" in globals()
    and not SDMETRICS_QUALITY_DF.empty
):

    SDMETRICS_DATASET_COMPARISON_DF = (

        SDMETRICS_QUALITY_DF

        .groupby(
            "Dataset",
            as_index=False
        )

        .agg(

            Methods_Evaluated=(
                "Quality Score",
                lambda x: x.notna().sum()
            ),

            Mean_Quality_Score=(
                "Quality Score",
                "mean"
            ),

            Minimum_Quality_Score=(
                "Quality Score",
                "min"
            ),

            Maximum_Quality_Score=(
                "Quality Score",
                "max"
            )

        )

    )

    SDMETRICS_DATASET_COMPARISON_DF = (
        SDMETRICS_DATASET_COMPARISON_DF
        .rename(
            columns={
                "Methods_Evaluated":
                    "Methods Evaluated",

                "Mean_Quality_Score":
                    "Mean Quality Score",

                "Minimum_Quality_Score":
                    "Minimum Quality Score",

                "Maximum_Quality_Score":
                    "Maximum Quality Score"
            }
        )
    )

    display(
        SDMETRICS_DATASET_COMPARISON_DF
    )

else:

    SDMETRICS_DATASET_COMPARISON_DF = (
        pd.DataFrame()
    )

    print(
        "No SDMetrics quality results available."
    )

print("\n" + "=" * 100)
print(
    "PART I7 — SDMETRICS DATASET COMPARISON COMPLETED"
)
print("=" * 100)

====================================================================================================
PART I7 — SDMETRICS DATASET COMPARISON
====================================================================================================

,Dataset,Methods Evaluated,Mean Quality Score,Minimum Quality Score,Maximum Quality Score
0,adult_income,0,NaN,NaN,NaN
1,bank_marketing,0,NaN,NaN,NaN
2,diabetes_130us,0,NaN,NaN,NaN

====================================================================================================
PART I7 — SDMETRICS DATASET COMPARISON COMPLETED
====================================================================================================

In [133]:
# ==============================================================================
# PART I8 — SDMETRICS EVALUATION SUMMARY
# ==============================================================================

print("=" * 100)
print("PART I8 — SDMETRICS EVALUATION SUMMARY")
print("=" * 100)

# ------------------------------------------------------------------------------
# Basic Counts
# ------------------------------------------------------------------------------

TOTAL_COMBINATIONS = (
    len(SYNTHETIC_METHODS)
    * len(SYNTHETIC_DATASET_NAMES)
)

EVALUATED_COMBINATIONS = int(
    SDMETRICS_QUALITY_DF[
        "Quality Score"
    ].notna().sum()
)

NOT_EVALUATED_COMBINATIONS = (
    TOTAL_COMBINATIONS
    - EVALUATED_COMBINATIONS
)

# ------------------------------------------------------------------------------
# Quality Statistics
# ------------------------------------------------------------------------------

if EVALUATED_COMBINATIONS > 0:

    MEAN_SD_METRICS_SCORE = (
        SDMETRICS_QUALITY_DF[
            "Quality Score"
        ].mean()
    )

    MIN_SD_METRICS_SCORE = (
        SDMETRICS_QUALITY_DF[
            "Quality Score"
        ].min()
    )

    MAX_SD_METRICS_SCORE = (
        SDMETRICS_QUALITY_DF[
            "Quality Score"
        ].max()
    )

else:

    MEAN_SD_METRICS_SCORE = np.nan
    MIN_SD_METRICS_SCORE = np.nan
    MAX_SD_METRICS_SCORE = np.nan

# ------------------------------------------------------------------------------
# Summary Table
# ------------------------------------------------------------------------------

SDMETRICS_SUMMARY_DF = pd.DataFrame({

    "Metric": [

        "Total Method-Dataset Combinations",

        "Successfully Evaluated",

        "Not Evaluated",

        "Evaluation Coverage (%)",

        "Mean SDMetrics Quality Score",

        "Minimum SDMetrics Quality Score",

        "Maximum SDMetrics Quality Score"

    ],

    "Value": [

        TOTAL_COMBINATIONS,

        EVALUATED_COMBINATIONS,

        NOT_EVALUATED_COMBINATIONS,

        (
            EVALUATED_COMBINATIONS
            / TOTAL_COMBINATIONS
            * 100
            if TOTAL_COMBINATIONS > 0
            else np.nan
        ),

        MEAN_SD_METRICS_SCORE,

        MIN_SD_METRICS_SCORE,

        MAX_SD_METRICS_SCORE

    ]

})

display(
    SDMETRICS_SUMMARY_DF
)

# ------------------------------------------------------------------------------
# Final Status
# ------------------------------------------------------------------------------

if EVALUATED_COMBINATIONS == TOTAL_COMBINATIONS:

    SDMETRICS_FINAL_STATUS = "COMPLETE"

elif EVALUATED_COMBINATIONS > 0:

    SDMETRICS_FINAL_STATUS = "PARTIAL"

else:

    SDMETRICS_FINAL_STATUS = "NOT AVAILABLE"

print(
    f"\nSDMetrics Final Status : "
    f"{SDMETRICS_FINAL_STATUS}"
)

print(
    f"Evaluation Coverage    : "
    f"{(
        EVALUATED_COMBINATIONS
        / TOTAL_COMBINATIONS
        * 100
    ) if TOTAL_COMBINATIONS > 0 else 0:.2f}%"
)

print("\n" + "=" * 100)
print(
    "PART I8 — SDMETRICS EVALUATION SUMMARY COMPLETED"
)
print("=" * 100)

====================================================================================================
PART I8 — SDMETRICS EVALUATION SUMMARY
====================================================================================================

                              Metric  Value
0  Total Method-Dataset Combinations   12.0
1             Successfully Evaluated    0.0
2                      Not Evaluated   12.0
3            Evaluation Coverage (%)    0.0
4       Mean SDMetrics Quality Score    NaN
5    Minimum SDMetrics Quality Score    NaN
6    Maximum SDMetrics Quality Score    NaN

SDMetrics Final Status : NOT AVAILABLE
Evaluation Coverage    : 0.00%

====================================================================================================
PART I8 — SDMETRICS EVALUATION SUMMARY COMPLETED
====================================================================================================

In [134]:
# ==============================================================================
# PART I9 — SDMETRICS FINAL RESEARCH EVALUATION TABLE
# ==============================================================================

print("=" * 100)
print("PART I9 — SDMETRICS FINAL RESEARCH EVALUATION TABLE")
print("=" * 100)

SDMETRICS_FINAL_DF = SDMETRICS_QUALITY_DF.copy()

if not SDMETRICS_FINAL_DF.empty:

    SDMETRICS_FINAL_DF = (
        SDMETRICS_FINAL_DF[
            [
                "Method",
                "Dataset",
                "Reference Loaded",
                "Synthetic Loaded",
                "Quality Score",
                "Quality Classification",
                "Status"
            ]
        ]
        .sort_values(
            [
                "Dataset",
                "Quality Score"
            ],
            ascending=[
                True,
                False
            ],
            na_position="last"
        )
        .reset_index(
            drop=True
        )
    )

display(
    SDMETRICS_FINAL_DF
)

print("\n" + "=" * 100)
print(
    "PART I9 — SDMETRICS FINAL RESEARCH "
    "EVALUATION TABLE COMPLETED"
)
print("=" * 100)

====================================================================================================
PART I9 — SDMETRICS FINAL RESEARCH EVALUATION TABLE
====================================================================================================

,Method,Dataset,Reference Loaded,Synthetic Loaded,Quality Score,Quality Classification,Status
0,CTGAN,adult_income,True,True,NaN,NOT AVAILABLE,METADATA NOT AVAILABLE
1,TVAE,adult_income,True,True,NaN,NOT AVAILABLE,METADATA NOT AVAILABLE
2,DP-CTGAN,adult_income,True,True,NaN,NOT AVAILABLE,METADATA NOT AVAILABLE
3,SPP-GAN,adult_income,True,True,NaN,NOT AVAILABLE,METADATA NOT AVAILABLE
4,CTGAN,bank_marketing,True,True,NaN,NOT AVAILABLE,METADATA NOT AVAILABLE
5,TVAE,bank_marketing,True,True,NaN,NOT AVAILABLE,METADATA NOT AVAILABLE
6,DP-CTGAN,bank_marketing,True,True,NaN,NOT AVAILABLE,METADATA NOT AVAILABLE
7,SPP-GAN,bank_marketing,True,True,NaN,NOT AVAILABLE,METADATA NOT AVAILABLE
8,CTGAN,diabetes_130us,True,True,NaN,NOT AVAILABLE,METADATA NOT AVAILABLE
9,TVAE,diabetes_130us,True,True,NaN,NOT AVAILABLE,METADATA NOT AVAILABLE
10,DP-CTGAN,diabetes_130us,True,True,NaN,NOT AVAILABLE,METADATA NOT AVAILABLE
11,SPP-GAN,diabetes_130us,True,True,NaN,NOT AVAILABLE,METADATA NOT AVAILABLE

====================================================================================================
PART I9 — SDMETRICS FINAL RESEARCH EVALUATION TABLE COMPLETED
====================================================================================================

In [135]:
# ==============================================================================
# PART J1 — DOWNSTREAM ML CONFIGURATION
# ==============================================================================

print("=" * 100)
print("PART J1 — DOWNSTREAM ML CONFIGURATION")
print("=" * 100)

import warnings
warnings.filterwarnings("ignore")

import numpy as np
import pandas as pd

from sklearn.base import clone
from sklearn.compose import ColumnTransformer
from sklearn.impute import SimpleImputer
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    roc_auc_score
)
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split

RANDOM_STATE = 42

# --------------------------------------------------------------------------
# DOWNSTREAM ML CONFIGURATION
# --------------------------------------------------------------------------

J_TEST_SIZE = 0.20
J_VALIDATION_SIZE = 0.20

J_PRIMARY_MODEL = "Logistic Regression"

J_DOWNSTREAM_MODELS = {
    "Logistic Regression": LogisticRegression(
        max_iter=1000,
        random_state=RANDOM_STATE
    ),
    "Random Forest": RandomForestClassifier(
        n_estimators=200,
        random_state=RANDOM_STATE,
        n_jobs=-1
    )
}

# --------------------------------------------------------------------------
# TARGET COLUMN CANDIDATES
# --------------------------------------------------------------------------

J_TARGET_CANDIDATES = {
    "adult_income": [
        "income",
        "Income",
        "target",
        "Target",
        "class",
        "Class"
    ],
    "bank_marketing": [
        "y",
        "Y",
        "target",
        "Target"
    ],
    "diabetes_130us": [
        "readmitted",
        "Readmitted",
        "target",
        "Target"
    ]
}

# --------------------------------------------------------------------------
# TARGET EXCLUSION CANDIDATES
# --------------------------------------------------------------------------

J_ID_COLUMNS = {
    "adult_income": [],
    "bank_marketing": [],
    "diabetes_130us": [
        "encounter_id",
        "patient_nbr"
    ]
}

print()
print("Downstream ML configuration:")
print(f"Random State       : {RANDOM_STATE}")
print(f"Test Size          : {J_TEST_SIZE}")
print(f"Primary Model      : {J_PRIMARY_MODEL}")
print(
    "Models Evaluated   : "
    + ", ".join(J_DOWNSTREAM_MODELS.keys())
)
print()
print("Target column candidates:")
for dataset, candidates in J_TARGET_CANDIDATES.items():
    print(f"  {dataset:<20}: {candidates}")

print()
print("=" * 100)
print("PART J1 — DOWNSTREAM ML CONFIGURATION COMPLETED")
print("=" * 100)

====================================================================================================
PART J1 — DOWNSTREAM ML CONFIGURATION
====================================================================================================

Downstream ML configuration:
Random State       : 42
Test Size          : 0.2
Primary Model      : Logistic Regression
Models Evaluated   : Logistic Regression, Random Forest

Target column candidates:
  adult_income        : ['income', 'Income', 'target', 'Target', 'class', 'Class']
  bank_marketing      : ['y', 'Y', 'target', 'Target']
  diabetes_130us      : ['readmitted', 'Readmitted', 'target', 'Target']

====================================================================================================
PART J1 — DOWNSTREAM ML CONFIGURATION COMPLETED
====================================================================================================

In [136]:
# ==============================================================================
# PART J2 — TARGET COLUMN DETECTION
# ==============================================================================

print("=" * 100)
print("PART J2 — TARGET COLUMN DETECTION")
print("=" * 100)

J_TARGET_COLUMNS = {}
J_TARGET_DETECTION_RESULTS = []

for dataset in SYNTHETIC_DATASET_NAMES:

    real_df = REAL_DATASETS.get(dataset)

    if real_df is None:
        J_TARGET_COLUMNS[dataset] = None

        J_TARGET_DETECTION_RESULTS.append({
            "Dataset": dataset,
            "Target Column": None,
            "Status": "REAL DATA NOT LOADED"
        })

        continue

    target_column = None

    # First: predefined candidates
    for candidate in J_TARGET_CANDIDATES.get(dataset, []):

        if candidate in real_df.columns:
            target_column = candidate
            break

    # Second: common fallback names
    if target_column is None:

        fallback_candidates = [
            "target",
            "Target",
            "label",
            "Label",
            "class",
            "Class",
            "outcome",
            "Outcome"
        ]

        for candidate in fallback_candidates:

            if candidate in real_df.columns:
                target_column = candidate
                break

    J_TARGET_COLUMNS[dataset] = target_column

    J_TARGET_DETECTION_RESULTS.append({
        "Dataset": dataset,
        "Target Column": target_column,
        "Status": (
            "PASS"
            if target_column is not None
            else "TARGET NOT FOUND"
        )
    })

J_TARGET_COLUMNS_DF = pd.DataFrame(
    J_TARGET_DETECTION_RESULTS
)

display(J_TARGET_COLUMNS_DF)

print()
print("Detected target columns:")

for dataset, target in J_TARGET_COLUMNS.items():
    print(
        f"  {dataset:<20}: "
        f"{target if target is not None else 'NOT FOUND'}"
    )

print()
print("=" * 100)
print("PART J2 — TARGET COLUMN DETECTION COMPLETED")
print("=" * 100)

====================================================================================================
PART J2 — TARGET COLUMN DETECTION
====================================================================================================

          Dataset Target Column Status
0    adult_income        income   PASS
1  bank_marketing             y   PASS
2  diabetes_130us    readmitted   PASS

Detected target columns:
  adult_income        : income
  bank_marketing      : y
  diabetes_130us      : readmitted

====================================================================================================
PART J2 — TARGET COLUMN DETECTION COMPLETED
====================================================================================================

In [137]:
# ==============================================================================
# PART J3 — REAL TRAIN / TEST SPLIT
# ==============================================================================

print("=" * 100)
print("PART J3 — REAL TRAIN / TEST SPLIT")
print("=" * 100)

J_REAL_TRAIN_DATA = {}
J_REAL_TEST_DATA = {}

J_SPLIT_RESULTS = []

for dataset in SYNTHETIC_DATASET_NAMES:

    real_df = REAL_DATASETS.get(dataset)
    target_column = J_TARGET_COLUMNS.get(dataset)

    if real_df is None:

        J_SPLIT_RESULTS.append({
            "Dataset": dataset,
            "Rows": 0,
            "Train Rows": 0,
            "Test Rows": 0,
            "Target Column": target_column,
            "Status": "REAL DATA NOT LOADED"
        })

        continue

    if target_column is None:

        J_SPLIT_RESULTS.append({
            "Dataset": dataset,
            "Rows": len(real_df),
            "Train Rows": 0,
            "Test Rows": 0,
            "Target Column": None,
            "Status": "TARGET NOT FOUND"
        })

        continue

    working_df = real_df.copy()

    # Remove completely empty rows
    working_df = working_df.dropna(
        how="all"
    ).reset_index(drop=True)

    X = working_df.drop(
        columns=[target_column]
    )

    y = working_df[target_column]

    # Remove configured ID columns
    id_columns = [
        column
        for column in J_ID_COLUMNS.get(dataset, [])
        if column in X.columns
    ]

    if id_columns:
        X = X.drop(
            columns=id_columns
        )

    # Stratification only when appropriate
    stratify_value = None

    if (
        y.nunique(dropna=True) > 1
        and y.value_counts(dropna=True).min() >= 2
    ):
        stratify_value = y

    X_train, X_test, y_train, y_test = train_test_split(
        X,
        y,
        test_size=J_TEST_SIZE,
        random_state=RANDOM_STATE,
        stratify=stratify_value
    )

    J_REAL_TRAIN_DATA[dataset] = (
        X_train.reset_index(drop=True),
        y_train.reset_index(drop=True)
    )

    J_REAL_TEST_DATA[dataset] = (
        X_test.reset_index(drop=True),
        y_test.reset_index(drop=True)
    )

    J_SPLIT_RESULTS.append({
        "Dataset": dataset,
        "Rows": len(working_df),
        "Train Rows": len(X_train),
        "Test Rows": len(X_test),
        "Target Column": target_column,
        "Target Classes": y.nunique(dropna=True),
        "Status": "PASS"
    })

J_SPLIT_DF = pd.DataFrame(
    J_SPLIT_RESULTS
)

display(J_SPLIT_DF)

print()
print("=" * 100)
print("PART J3 — REAL TRAIN / TEST SPLIT COMPLETED")
print("=" * 100)

====================================================================================================
PART J3 — REAL TRAIN / TEST SPLIT
====================================================================================================

,Dataset,Rows,Train Rows,Test Rows,Target Column,Target Classes,Status
0,adult_income,32515,26012,6503,income,2,PASS
1,bank_marketing,45211,36168,9043,y,2,PASS
2,diabetes_130us,101766,81412,20354,readmitted,3,PASS

====================================================================================================
PART J3 — REAL TRAIN / TEST SPLIT COMPLETED
====================================================================================================

In [138]:
# ==============================================================================
# PART J4 — PREPROCESSING PIPELINE
# ==============================================================================

print("=" * 100)
print("PART J4 — PREPROCESSING PIPELINE")
print("=" * 100)

def build_downstream_preprocessor(X):

    numeric_columns = X.select_dtypes(
        include=["number", "bool"]
    ).columns.tolist()

    categorical_columns = [
        column
        for column in X.columns
        if column not in numeric_columns
    ]

    numeric_pipeline = Pipeline(
        steps=[
            (
                "imputer",
                SimpleImputer(
                    strategy="median"
                )
            ),
            (
                "scaler",
                StandardScaler()
            )
        ]
    )

    categorical_pipeline = Pipeline(
        steps=[
            (
                "imputer",
                SimpleImputer(
                    strategy="most_frequent"
                )
            ),
            (
                "onehot",
                OneHotEncoder(
                    handle_unknown="ignore",
                    sparse_output=False
                )
            )
        ]
    )

    transformers = []

    if numeric_columns:
        transformers.append(
            (
                "numeric",
                numeric_pipeline,
                numeric_columns
            )
        )

    if categorical_columns:
        transformers.append(
            (
                "categorical",
                categorical_pipeline,
                categorical_columns
            )
        )

    preprocessor = ColumnTransformer(
        transformers=transformers,
        remainder="drop"
    )

    return preprocessor, numeric_columns, categorical_columns


J_FEATURE_SCHEMA = {}

for dataset in SYNTHETIC_DATASET_NAMES:

    if dataset not in J_REAL_TRAIN_DATA:
        continue

    X_train, _ = J_REAL_TRAIN_DATA[dataset]

    (
        _,
        numeric_columns,
        categorical_columns
    ) = build_downstream_preprocessor(X_train)

    J_FEATURE_SCHEMA[dataset] = {
        "Numeric Columns": numeric_columns,
        "Categorical Columns": categorical_columns
    }

    print()
    print(f"{dataset}")
    print(
        f"  Numeric Features     : "
        f"{len(numeric_columns)}"
    )
    print(
        f"  Categorical Features : "
        f"{len(categorical_columns)}"
    )

print()
print("=" * 100)
print("PART J4 — PREPROCESSING PIPELINE COMPLETED")
print("=" * 100)

====================================================================================================
PART J4 — PREPROCESSING PIPELINE
====================================================================================================

adult_income
  Numeric Features     : 14
  Categorical Features : 0

bank_marketing
  Numeric Features     : 16
  Categorical Features : 0

diabetes_130us
  Numeric Features     : 47
  Categorical Features : 0

====================================================================================================
PART J4 — PREPROCESSING PIPELINE COMPLETED
====================================================================================================

In [139]:
# ==============================================================================
# PART J5 — SYNTHETIC DATA ALIGNMENT
# ==============================================================================

print("=" * 100)
print("PART J5 — SYNTHETIC DATA ALIGNMENT")
print("=" * 100)

J_ALIGNED_SYNTHETIC_DATA = {}

J_ALIGNMENT_RESULTS = []

for method in SYNTHETIC_METHODS:

    J_ALIGNED_SYNTHETIC_DATA[method] = {}

    for dataset in SYNTHETIC_DATASET_NAMES:

        synthetic_df = (
            SYNTHETIC_DATASETS
            .get(method, {})
            .get(dataset)
        )

        target_column = J_TARGET_COLUMNS.get(
            dataset
        )

        if synthetic_df is None:

            J_ALIGNMENT_RESULTS.append({
                "Method": method,
                "Dataset": dataset,
                "Synthetic Loaded": False,
                "Target Present": False,
                "Feature Count": 0,
                "Status": "SYNTHETIC DATA NOT LOADED"
            })

            continue

        if target_column is None:

            J_ALIGNMENT_RESULTS.append({
                "Method": method,
                "Dataset": dataset,
                "Synthetic Loaded": True,
                "Target Present": False,
                "Feature Count": 0,
                "Status": "TARGET NOT FOUND"
            })

            continue

        if target_column not in synthetic_df.columns:

            J_ALIGNMENT_RESULTS.append({
                "Method": method,
                "Dataset": dataset,
                "Synthetic Loaded": True,
                "Target Present": False,
                "Feature Count": 0,
                "Status": "TARGET MISSING IN SYNTHETIC DATA"
            })

            continue

        X_real_train, _ = J_REAL_TRAIN_DATA.get(
            dataset,
            (None, None)
        )

        if X_real_train is None:

            J_ALIGNMENT_RESULTS.append({
                "Method": method,
                "Dataset": dataset,
                "Synthetic Loaded": True,
                "Target Present": True,
                "Feature Count": 0,
                "Status": "REAL TRAINING DATA NOT AVAILABLE"
            })

            continue

        expected_features = X_real_train.columns.tolist()

        missing_features = [
            column
            for column in expected_features
            if column not in synthetic_df.columns
        ]

        extra_features = [
            column
            for column in synthetic_df.columns
            if column not in expected_features
            and column != target_column
        ]

        if missing_features:

            J_ALIGNMENT_RESULTS.append({
                "Method": method,
                "Dataset": dataset,
                "Synthetic Loaded": True,
                "Target Present": True,
                "Feature Count": 0,
                "Missing Features": missing_features,
                "Extra Features": extra_features,
                "Status": "FEATURE MISMATCH"
            })

            continue

        aligned_columns = (
            expected_features
            + [target_column]
        )

        aligned_df = synthetic_df[
            aligned_columns
        ].copy()

        J_ALIGNED_SYNTHETIC_DATA[
            method
        ][dataset] = aligned_df

        J_ALIGNMENT_RESULTS.append({
            "Method": method,
            "Dataset": dataset,
            "Synthetic Loaded": True,
            "Target Present": True,
            "Feature Count": len(expected_features),
            "Missing Features": [],
            "Extra Features": extra_features,
            "Status": "PASS"
        })

J_ALIGNMENT_DF = pd.DataFrame(
    J_ALIGNMENT_RESULTS
)

display(J_ALIGNMENT_DF)

print()
print("=" * 100)
print("PART J5 — SYNTHETIC DATA ALIGNMENT COMPLETED")
print("=" * 100)

====================================================================================================
PART J5 — SYNTHETIC DATA ALIGNMENT
====================================================================================================

,Method,Dataset,Synthetic Loaded,Target Present,Feature Count,Missing Features,Extra Features,Status
0,CTGAN,adult_income,True,True,14,[],[],PASS
1,CTGAN,bank_marketing,True,True,16,[],[],PASS
2,CTGAN,diabetes_130us,True,True,47,[],[],PASS
3,TVAE,adult_income,True,True,14,[],[],PASS
4,TVAE,bank_marketing,True,True,16,[],[],PASS
5,TVAE,diabetes_130us,True,True,47,[],[],PASS
6,DP-CTGAN,adult_income,True,True,14,[],[],PASS
7,DP-CTGAN,bank_marketing,True,True,16,[],[],PASS
8,DP-CTGAN,diabetes_130us,True,True,47,[],[],PASS
9,SPP-GAN,adult_income,True,True,14,[],[],PASS
10,SPP-GAN,bank_marketing,True,True,16,[],[],PASS
11,SPP-GAN,diabetes_130us,True,True,47,[],[],PASS

====================================================================================================
PART J5 — SYNTHETIC DATA ALIGNMENT COMPLETED
====================================================================================================

In [140]:
# ==============================================================================
# PART J6 — DOWNSTREAM ML UTILITY EVALUATION
# ==============================================================================

print("=" * 100)
print("PART J6 — DOWNSTREAM ML UTILITY EVALUATION")
print("=" * 100)

J_UTILITY_RESULTS = []

for dataset in SYNTHETIC_DATASET_NAMES:

    if dataset not in J_REAL_TRAIN_DATA:
        continue

    if dataset not in J_REAL_TEST_DATA:
        continue

    X_real_train, y_real_train = (
        J_REAL_TRAIN_DATA[dataset]
    )

    X_real_test, y_real_test = (
        J_REAL_TEST_DATA[dataset]
    )

    for model_name, base_model in J_DOWNSTREAM_MODELS.items():

        print()
        print(
            f"Evaluating {dataset} | "
            f"{model_name}"
        )

        # ------------------------------------------------------------------
        # REAL-DATA MODEL
        # ------------------------------------------------------------------

        try:

            real_preprocessor, _, _ = (
                build_downstream_preprocessor(
                    X_real_train
                )
            )

            real_model = Pipeline(
                steps=[
                    (
                        "preprocessor",
                        real_preprocessor
                    ),
                    (
                        "model",
                        clone(base_model)
                    )
                ]
            )

            real_model.fit(
                X_real_train,
                y_real_train
            )

            real_predictions = (
                real_model.predict(
                    X_real_test
                )
            )

            real_accuracy = accuracy_score(
                y_real_test,
                real_predictions
            )

            real_precision = precision_score(
                y_real_test,
                real_predictions,
                average="weighted",
                zero_division=0
            )

            real_recall = recall_score(
                y_real_test,
                real_predictions,
                average="weighted",
                zero_division=0
            )

            real_f1 = f1_score(
                y_real_test,
                real_predictions,
                average="weighted",
                zero_division=0
            )

            real_auc = np.nan

            if (
                y_real_test.nunique() == 2
                and hasattr(
                    real_model,
                    "predict_proba"
                )
            ):

                try:

                    real_probability = (
                        real_model.predict_proba(
                            X_real_test
                        )[:, 1]
                    )

                    positive_class = (
                        real_model
                        .named_steps["model"]
                        .classes_[1]
                    )

                    y_binary = (
                        y_real_test
                        == positive_class
                    ).astype(int)

                    real_auc = roc_auc_score(
                        y_binary,
                        real_probability
                    )

                except Exception:
                    real_auc = np.nan

        except Exception as error:

            print(
                f"  Real model failed: {error}"
            )

            continue

        # ------------------------------------------------------------------
        # SYNTHETIC MODELS
        # ------------------------------------------------------------------

        for method in SYNTHETIC_METHODS:

            synthetic_df = (
                J_ALIGNED_SYNTHETIC_DATA
                .get(method, {})
                .get(dataset)
            )

            if synthetic_df is None:

                J_UTILITY_RESULTS.append({
                    "Method": method,
                    "Dataset": dataset,
                    "ML Model": model_name,
                    "Real Train Rows": len(X_real_train),
                    "Synthetic Train Rows": 0,
                    "Real Test Rows": len(X_real_test),
                    "Real Accuracy": real_accuracy,
                    "Synthetic Accuracy": np.nan,
                    "Real Precision": real_precision,
                    "Synthetic Precision": np.nan,
                    "Real Recall": real_recall,
                    "Synthetic Recall": np.nan,
                    "Real F1": real_f1,
                    "Synthetic F1": np.nan,
                    "Real ROC-AUC": real_auc,
                    "Synthetic ROC-AUC": np.nan,
                    "Status": "SYNTHETIC DATA NOT AVAILABLE"
                })

                continue

            try:

                X_synthetic = synthetic_df.drop(
                    columns=[J_TARGET_COLUMNS[dataset]]
                )

                y_synthetic = synthetic_df[
                    J_TARGET_COLUMNS[dataset]
                ]

                synthetic_preprocessor, _, _ = (
                    build_downstream_preprocessor(
                        X_synthetic
                    )
                )

                synthetic_model = Pipeline(
                    steps=[
                        (
                            "preprocessor",
                            synthetic_preprocessor
                        ),
                        (
                            "model",
                            clone(base_model)
                        )
                    ]
                )

                synthetic_model.fit(
                    X_synthetic,
                    y_synthetic
                )

                synthetic_predictions = (
                    synthetic_model.predict(
                        X_real_test
                    )
                )

                synthetic_accuracy = (
                    accuracy_score(
                        y_real_test,
                        synthetic_predictions
                    )
                )

                synthetic_precision = (
                    precision_score(
                        y_real_test,
                        synthetic_predictions,
                        average="weighted",
                        zero_division=0
                    )
                )

                synthetic_recall = (
                    recall_score(
                        y_real_test,
                        synthetic_predictions,
                        average="weighted",
                        zero_division=0
                    )
                )

                synthetic_f1 = (
                    f1_score(
                        y_real_test,
                        synthetic_predictions,
                        average="weighted",
                        zero_division=0
                    )
                )

                synthetic_auc = np.nan

                if (
                    y_real_test.nunique() == 2
                    and hasattr(
                        synthetic_model,
                        "predict_proba"
                    )
                ):

                    try:

                        synthetic_probability = (
                            synthetic_model
                            .predict_proba(
                                X_real_test
                            )[:, 1]
                        )

                        positive_class = (
                            synthetic_model
                            .named_steps["model"]
                            .classes_[1]
                        )

                        y_binary = (
                            y_real_test
                            == positive_class
                        ).astype(int)

                        synthetic_auc = (
                            roc_auc_score(
                                y_binary,
                                synthetic_probability
                            )
                        )

                    except Exception:
                        synthetic_auc = np.nan

                J_UTILITY_RESULTS.append({

                    "Method": method,
                    "Dataset": dataset,
                    "ML Model": model_name,

                    "Real Train Rows":
                        len(X_real_train),

                    "Synthetic Train Rows":
                        len(X_synthetic),

                    "Real Test Rows":
                        len(X_real_test),

                    "Real Accuracy":
                        real_accuracy,

                    "Synthetic Accuracy":
                        synthetic_accuracy,

                    "Real Precision":
                        real_precision,

                    "Synthetic Precision":
                        synthetic_precision,

                    "Real Recall":
                        real_recall,

                    "Synthetic Recall":
                        synthetic_recall,

                    "Real F1":
                        real_f1,

                    "Synthetic F1":
                        synthetic_f1,

                    "Real ROC-AUC":
                        real_auc,

                    "Synthetic ROC-AUC":
                        synthetic_auc,

                    "Status":
                        "PASS"
                })

                print(
                    f"  ✓ {method:<12} | "
                    f"Accuracy={synthetic_accuracy:.4f} | "
                    f"F1={synthetic_f1:.4f}"
                )

            except Exception as error:

                J_UTILITY_RESULTS.append({

                    "Method": method,
                    "Dataset": dataset,
                    "ML Model": model_name,

                    "Real Train Rows":
                        len(X_real_train),

                    "Synthetic Train Rows":
                        len(synthetic_df),

                    "Real Test Rows":
                        len(X_real_test),

                    "Real Accuracy":
                        real_accuracy,

                    "Synthetic Accuracy":
                        np.nan,

                    "Real Precision":
                        real_precision,

                    "Synthetic Precision":
                        np.nan,

                    "Real Recall":
                        real_recall,

                    "Synthetic Recall":
                        np.nan,

                    "Real F1":
                        real_f1,

                    "Synthetic F1":
                        np.nan,

                    "Real ROC-AUC":
                        real_auc,

                    "Synthetic ROC-AUC":
                        np.nan,

                    "Status":
                        f"ERROR: {type(error).__name__}"
                })

                print(
                    f"  ✗ {method:<12} | "
                    f"ERROR: {error}"
                )

J_UTILITY_DF = pd.DataFrame(
    J_UTILITY_RESULTS
)

display(J_UTILITY_DF)

print()
print("=" * 100)
print("PART J6 — DOWNSTREAM ML UTILITY EVALUATION COMPLETED")
print("=" * 100)

====================================================================================================
PART J6 — DOWNSTREAM ML UTILITY EVALUATION
====================================================================================================

Evaluating adult_income | Logistic Regression
  ✓ CTGAN        | Accuracy=0.7506 | F1=0.6663
  ✓ TVAE         | Accuracy=0.7390 | F1=0.6632
  ✗ DP-CTGAN     | ERROR: Unknown label type: continuous. Maybe you are trying to fit a classifier, which expects discrete classes on a regression target with continuous values.
  ✓ SPP-GAN      | Accuracy=0.7621 | F1=0.6626

Evaluating adult_income | Random Forest
  ✓ CTGAN        | Accuracy=0.7982 | F1=0.8040
  ✓ TVAE         | Accuracy=0.7958 | F1=0.7782
  ✗ DP-CTGAN     | ERROR: Unknown label type: continuous. Maybe you are trying to fit a classifier, which expects discrete classes on a regression target with continuous values.
  ✓ SPP-GAN      | Accuracy=0.7601 | F1=0.6615

Evaluating bank_marketing | Logistic Regression
  ✓ CTGAN        | Accuracy=0.7243 | F1=0.7717
  ✓ TVAE         | Accuracy=0.5503 | F1=0.6255
  ✗ DP-CTGAN     | ERROR: Unknown label type: continuous. Maybe you are trying to fit a classifier, which expects discrete classes on a regression target with continuous values.
  ✓ SPP-GAN      | Accuracy=0.8822 | F1=0.8282

Evaluating bank_marketing | Random Forest
  ✓ CTGAN        | Accuracy=0.8836 | F1=0.8856
  ✓ TVAE         | Accuracy=0.5701 | F1=0.6439
  ✗ DP-CTGAN     | ERROR: Unknown label type: continuous. Maybe you are trying to fit a classifier, which expects discrete classes on a regression target with continuous values.
  ✓ SPP-GAN      | Accuracy=0.8827 | F1=0.8292

Evaluating diabetes_130us | Logistic Regression
  ✓ CTGAN        | Accuracy=0.1117 | F1=0.0225
  ✓ TVAE         | Accuracy=0.1858 | F1=0.1615
  ✗ DP-CTGAN     | ERROR: Unknown label type: continuous. Maybe you are trying to fit a classifier, which expects discrete classes on a regression target with continuous values.
  ✓ SPP-GAN      | Accuracy=0.5545 | F1=0.4799

Evaluating diabetes_130us | Random Forest
  ✓ CTGAN        | Accuracy=0.5389 | F1=0.3789
  ✓ TVAE         | Accuracy=0.5580 | F1=0.4910
  ✗ DP-CTGAN     | ERROR: Unknown label type: continuous. Maybe you are trying to fit a classifier, which expects discrete classes on a regression target with continuous values.
  ✓ SPP-GAN      | Accuracy=0.5443 | F1=0.4489

,Method,Dataset,ML Model,Real Train Rows,Synthetic Train Rows,Real Test Rows,Real Accuracy,Synthetic Accuracy,Real Precision,Synthetic Precision,Real Recall,Synthetic Recall,Real F1,Synthetic F1,Real ROC-AUC,Synthetic ROC-AUC,Status
0,CTGAN,adult_income,Logistic Regression,26012,32515,6503,0.833461,0.750577,0.823962,0.660889,0.833461,0.750577,0.819847,0.666334,0.861611,0.711778,PASS
1,TVAE,adult_income,Logistic Regression,26012,32510,6503,0.833461,0.739044,0.823962,0.641596,0.833461,0.739044,0.819847,0.663174,0.861611,0.647378,PASS
2,DP-CTGAN,adult_income,Logistic Regression,26012,22760,6503,0.833461,NaN,0.823962,NaN,0.833461,NaN,0.819847,NaN,0.861611,NaN,ERROR: ValueError
3,SPP-GAN,adult_income,Logistic Regression,26012,32515,6503,0.833461,0.762110,0.823962,0.807984,0.833461,0.762110,0.819847,0.662555,0.861611,0.828716,PASS
4,CTGAN,adult_income,Random Forest,26012,32515,6503,0.860218,0.798247,0.855073,0.813459,0.860218,0.798247,0.856178,0.803993,0.910482,0.860162,PASS
5,TVAE,adult_income,Random Forest,26012,32510,6503,0.860218,0.795787,0.855073,0.777385,0.860218,0.795787,0.856178,0.778185,0.910482,0.838484,PASS
6,DP-CTGAN,adult_income,Random Forest,26012,22760,6503,0.860218,NaN,0.855073,NaN,0.860218,NaN,0.856178,NaN,0.910482,NaN,ERROR: ValueError
7,SPP-GAN,adult_income,Random Forest,26012,32515,6503,0.860218,0.760111,0.855073,0.722187,0.860218,0.760111,0.856178,0.661520,0.910482,0.704309,PASS
8,CTGAN,bank_marketing,Logistic Regression,36168,45211,9043,0.888090,0.724317,0.866063,0.878989,0.888090,0.724317,0.870391,0.771661,0.873401,0.813048,PASS
9,TVAE,bank_marketing,Logistic Regression,36168,45211,9043,0.888090,0.550260,0.866063,0.866999,0.888090,0.550260,0.870391,0.625478,0.873401,0.769056,PASS
10,DP-CTGAN,bank_marketing,Logistic Regression,36168,31647,9043,0.888090,NaN,0.866063,NaN,0.888090,NaN,0.870391,NaN,0.873401,NaN,ERROR: ValueError
11,SPP-GAN,bank_marketing,Logistic Regression,36168,45211,9043,0.888090,0.882229,0.866063,0.801037,0.888090,0.882229,0.870391,0.828179,0.873401,0.791847,PASS
12,CTGAN,bank_marketing,Random Forest,36168,45211,9043,0.905562,0.883556,0.893751,0.887953,0.905562,0.883556,0.895957,0.885623,0.925528,0.877446,PASS
13,TVAE,bank_marketing,Random Forest,36168,45211,9043,0.905562,0.570054,0.893751,0.864647,0.905562,0.570054,0.895957,0.643873,0.925528,0.736167,PASS
14,DP-CTGAN,bank_marketing,Random Forest,36168,31647,9043,0.905562,NaN,0.893751,NaN,0.905562,NaN,0.895957,NaN,0.925528,NaN,ERROR: ValueError
15,SPP-GAN,bank_marketing,Random Forest,36168,45211,9043,0.905562,0.882672,0.893751,0.826909,0.905562,0.882672,0.895957,0.829244,0.925528,0.802226,PASS
16,CTGAN,diabetes_130us,Logistic Regression,81412,101766,20354,0.572369,0.111673,0.513375,0.551568,0.572369,0.111673,0.509366,0.022517,NaN,NaN,PASS
17,TVAE,diabetes_130us,Logistic Regression,81412,101766,20354,0.572369,0.185811,0.513375,0.332414,0.572369,0.185811,0.509366,0.161536,NaN,NaN,PASS
18,DP-CTGAN,diabetes_130us,Logistic Regression,81412,71236,20354,0.572369,NaN,0.513375,NaN,0.572369,NaN,0.509366,NaN,NaN,NaN,ERROR: ValueError
19,SPP-GAN,diabetes_130us,Logistic Regression,81412,101766,20354,0.572369,0.554535,0.513375,0.503236,0.572369,0.554535,0.509366,0.479923,NaN,NaN,PASS
20,CTGAN,diabetes_130us,Random Forest,81412,101766,20354,0.585831,0.538911,0.558284,0.404504,0.585831,0.538911,0.536713,0.378948,NaN,NaN,PASS
21,TVAE,diabetes_130us,Random Forest,81412,101766,20354,0.585831,0.557974,0.558284,0.474018,0.585831,0.557974,0.536713,0.491005,NaN,NaN,PASS
22,DP-CTGAN,diabetes_130us,Random Forest,81412,71236,20354,0.585831,NaN,0.558284,NaN,0.585831,NaN,0.536713,NaN,NaN,NaN,ERROR: ValueError
23,SPP-GAN,diabetes_130us,Random Forest,81412,101766,20354,0.585831,0.544316,0.558284,0.455381,0.585831,0.544316,0.536713,0.448885,NaN,NaN,PASS

====================================================================================================
PART J6 — DOWNSTREAM ML UTILITY EVALUATION COMPLETED
====================================================================================================

In [141]:
# ==============================================================================
# PART J7 — UTILITY GAP AND RETENTION
# ==============================================================================

print("=" * 100)
print("PART J7 — UTILITY GAP AND RETENTION")
print("=" * 100)

J_UTILITY_METRICS = []

metric_pairs = [
    (
        "Accuracy",
        "Real Accuracy",
        "Synthetic Accuracy"
    ),
    (
        "Precision",
        "Real Precision",
        "Synthetic Precision"
    ),
    (
        "Recall",
        "Real Recall",
        "Synthetic Recall"
    ),
    (
        "F1",
        "Real F1",
        "Synthetic F1"
    ),
    (
        "ROC-AUC",
        "Real ROC-AUC",
        "Synthetic ROC-AUC"
    )
]

for _, row in J_UTILITY_DF.iterrows():

    result = {
        "Method": row["Method"],
        "Dataset": row["Dataset"],
        "ML Model": row["ML Model"]
    }

    retention_values = []

    for metric_name, real_col, synthetic_col in metric_pairs:

        real_value = row[real_col]
        synthetic_value = row[synthetic_col]

        if (
            pd.notna(real_value)
            and pd.notna(synthetic_value)
            and real_value != 0
        ):

            utility_gap = (
                real_value
                - synthetic_value
            )

            utility_retention = (
                synthetic_value
                / real_value
                * 100.0
            )

            relative_gap = (
                utility_gap
                / real_value
                * 100.0
            )

            retention_values.append(
                utility_retention
            )

        else:

            utility_gap = np.nan
            utility_retention = np.nan
            relative_gap = np.nan

        result[
            f"{metric_name} Gap"
        ] = utility_gap

        result[
            f"{metric_name} Retention (%)"
        ] = utility_retention

        result[
            f"{metric_name} Relative Gap (%)"
        ] = relative_gap

    result[
        "Overall Utility Retention (%)"
    ] = (
        np.mean(retention_values)
        if retention_values
        else np.nan
    )

    result[
        "Overall Utility Gap"
    ] = (
        1.0
        - (
            result[
                "Overall Utility Retention (%)"
            ] / 100.0
        )
        if pd.notna(
            result[
                "Overall Utility Retention (%)"
            ]
        )
        else np.nan
    )

    J_UTILITY_METRICS.append(
        result
    )

J_UTILITY_METRICS_DF = pd.DataFrame(
    J_UTILITY_METRICS
)

display(
    J_UTILITY_METRICS_DF
)

print()
print("=" * 100)
print("PART J7 — UTILITY GAP AND RETENTION COMPLETED")
print("=" * 100)

====================================================================================================
PART J7 — UTILITY GAP AND RETENTION
====================================================================================================

,Method,Dataset,ML Model,Accuracy Gap,Accuracy Retention (%),Accuracy Relative Gap (%),Precision Gap,Precision Retention (%),Precision Relative Gap (%),Recall Gap,Recall Retention (%),Recall Relative Gap (%),F1 Gap,F1 Retention (%),F1 Relative Gap (%),ROC-AUC Gap,ROC-AUC Retention (%),ROC-AUC Relative Gap (%),Overall Utility Retention (%),Overall Utility Gap
0,CTGAN,adult_income,Logistic Regression,0.082885,90.055351,9.944649,0.163073,80.208652,19.791348,0.082885,90.055351,9.944649,0.153514,81.275350,18.724650,0.149833,82.610118,17.389882,84.840964,0.151590
1,TVAE,adult_income,Logistic Regression,0.094418,88.671587,11.328413,0.182366,77.867181,22.132819,0.094418,88.671587,11.328413,0.156673,80.889949,19.110051,0.214233,75.135768,24.864232,82.247214,0.177528
2,DP-CTGAN,adult_income,Logistic Regression,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,SPP-GAN,adult_income,Logistic Regression,0.071352,91.439114,8.560886,0.015977,98.060898,1.939102,0.071352,91.439114,8.560886,0.157293,80.814391,19.185609,0.032895,96.182112,3.817888,91.587126,0.084129
4,CTGAN,adult_income,Random Forest,0.061971,92.795853,7.204147,0.041614,95.133330,4.866670,0.061971,92.795853,7.204147,0.052184,93.904950,6.095050,0.050320,94.473247,5.526753,93.820646,0.061794
5,TVAE,adult_income,Random Forest,0.064432,92.509832,7.490168,0.077688,90.914471,9.085529,0.064432,92.509832,7.490168,0.077993,90.890574,9.109426,0.071998,92.092290,7.907710,91.783400,0.082166
6,DP-CTGAN,adult_income,Random Forest,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,SPP-GAN,adult_income,Random Forest,0.100108,88.362531,11.637469,0.132886,84.459129,15.540871,0.100108,88.362531,11.637469,0.194658,77.264356,22.735644,0.206173,77.355620,22.644380,83.160834,0.168392
8,CTGAN,bank_marketing,Logistic Regression,0.163773,81.558959,18.441041,-0.012926,101.492508,-1.492508,0.163773,81.558959,18.441041,0.098730,88.656836,11.343164,0.060353,93.089886,6.910114,89.271430,0.107286
9,TVAE,bank_marketing,Logistic Regression,0.337830,61.959905,38.040095,-0.000937,100.108147,-0.108147,0.337830,61.959905,38.040095,0.244913,71.861755,28.138245,0.104345,88.053026,11.946974,76.788548,0.232115
10,DP-CTGAN,bank_marketing,Logistic Regression,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,SPP-GAN,bank_marketing,Logistic Regression,0.005861,99.340057,0.659943,0.065026,92.491771,7.508229,0.005861,99.340057,0.659943,0.042212,95.150222,4.849778,0.081554,90.662449,9.337551,95.396911,0.046031
12,CTGAN,bank_marketing,Random Forest,0.022006,97.569911,2.430089,0.005798,99.351264,0.648736,0.022006,97.569911,2.430089,0.010334,98.846626,1.153374,0.048082,94.804937,5.195063,97.628530,0.023715
13,TVAE,bank_marketing,Random Forest,0.335508,62.950299,37.049701,0.029103,96.743672,3.256328,0.335508,62.950299,37.049701,0.252084,71.864323,28.135677,0.189361,79.540261,20.459739,74.809771,0.251902
14,DP-CTGAN,bank_marketing,Random Forest,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,SPP-GAN,bank_marketing,Random Forest,0.022891,97.472219,2.527781,0.066842,92.521182,7.478818,0.022891,97.472219,2.527781,0.066713,92.554011,7.445989,0.123302,86.677656,13.322344,93.339457,0.066605
16,CTGAN,diabetes_130us,Logistic Regression,0.460696,19.510730,80.489270,-0.038193,107.439616,-7.439616,0.460696,19.510730,80.489270,0.486849,4.420560,95.579440,NaN,NaN,NaN,37.720409,0.622796
17,TVAE,diabetes_130us,Logistic Regression,0.386558,32.463519,67.536481,0.180961,64.750677,35.249323,0.386558,32.463519,67.536481,0.347830,31.713155,68.286845,NaN,NaN,NaN,40.347718,0.596523
18,DP-CTGAN,diabetes_130us,Logistic Regression,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,SPP-GAN,diabetes_130us,Logistic Regression,0.017834,96.884120,3.115880,0.010139,98.024934,1.975066,0.017834,96.884120,3.115880,0.029443,94.219634,5.780366,NaN,NaN,NaN,96.503202,0.034968
20,CTGAN,diabetes_130us,Random Forest,0.046920,91.990943,8.009057,0.153780,72.454855,27.545145,0.046920,91.990943,8.009057,0.157765,70.605325,29.394675,NaN,NaN,NaN,81.760516,0.182395
21,TVAE,diabetes_130us,Random Forest,0.027857,95.244884,4.755116,0.084267,84.906133,15.093867,0.027857,95.244884,4.755116,0.045708,91.483777,8.516223,NaN,NaN,NaN,91.719920,0.082801
22,DP-CTGAN,diabetes_130us,Random Forest,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,SPP-GAN,diabetes_130us,Random Forest,0.041515,92.913452,7.086548,0.102904,81.567902,18.432098,0.041515,92.913452,7.086548,0.087828,83.636004,16.363996,NaN,NaN,NaN,87.757703,0.122423

====================================================================================================
PART J7 — UTILITY GAP AND RETENTION COMPLETED
====================================================================================================

In [142]:
# ==============================================================================
# PART J8 — PRIMARY DOWNSTREAM UTILITY SUMMARY
# ==============================================================================

print("=" * 100)
print("PART J8 — PRIMARY DOWNSTREAM UTILITY SUMMARY")
print("=" * 100)

J_PRIMARY_RESULTS = []

primary_df = J_UTILITY_METRICS_DF[
    J_UTILITY_METRICS_DF["ML Model"]
    == J_PRIMARY_MODEL
].copy()

for _, row in primary_df.iterrows():

    J_PRIMARY_RESULTS.append({

        "Method":
            row["Method"],

        "Dataset":
            row["Dataset"],

        "ML Model":
            row["ML Model"],

        "Real F1":
            J_UTILITY_DF.loc[
                (
                    (J_UTILITY_DF["Method"] == row["Method"])
                    &
                    (J_UTILITY_DF["Dataset"] == row["Dataset"])
                    &
                    (J_UTILITY_DF["ML Model"] == row["ML Model"])
                ),
                "Real F1"
            ].iloc[0],

        "Synthetic F1":
            J_UTILITY_DF.loc[
                (
                    (J_UTILITY_DF["Method"] == row["Method"])
                    &
                    (J_UTILITY_DF["Dataset"] == row["Dataset"])
                    &
                    (J_UTILITY_DF["ML Model"] == row["ML Model"])
                ),
                "Synthetic F1"
            ].iloc[0],

        "F1 Gap":
            row["F1 Gap"],

        "F1 Retention (%)":
            row["F1 Retention (%)"],

        "Real ROC-AUC":
            J_UTILITY_DF.loc[
                (
                    (J_UTILITY_DF["Method"] == row["Method"])
                    &
                    (J_UTILITY_DF["Dataset"] == row["Dataset"])
                    &
                    (J_UTILITY_DF["ML Model"] == row["ML Model"])
                ),
                "Real ROC-AUC"
            ].iloc[0],

        "Synthetic ROC-AUC":
            J_UTILITY_DF.loc[
                (
                    (J_UTILITY_DF["Method"] == row["Method"])
                    &
                    (J_UTILITY_DF["Dataset"] == row["Dataset"])
                    &
                    (J_UTILITY_DF["ML Model"] == row["ML Model"])
                ),
                "Real ROC-AUC"
            ].iloc[0]
            if False else
            J_UTILITY_DF.loc[
                (
                    (J_UTILITY_DF["Method"] == row["Method"])
                    &
                    (J_UTILITY_DF["Dataset"] == row["Dataset"])
                    &
                    (J_UTILITY_DF["ML Model"] == row["ML Model"])
                ),
                "Synthetic ROC-AUC"
            ].iloc[0],

        "ROC-AUC Retention (%)":
            row["ROC-AUC Retention (%)"],

        "Overall Utility Retention (%)":
            row["Overall Utility Retention (%)"],

        "Status":
            "PASS"
    })

J_PRIMARY_UTILITY_DF = pd.DataFrame(
    J_PRIMARY_RESULTS
)

display(
    J_PRIMARY_UTILITY_DF
)

print()
print("=" * 100)
print("PART J8 — PRIMARY DOWNSTREAM UTILITY SUMMARY COMPLETED")
print("=" * 100)

====================================================================================================
PART J8 — PRIMARY DOWNSTREAM UTILITY SUMMARY
====================================================================================================

,Method,Dataset,ML Model,Real F1,Synthetic F1,F1 Gap,F1 Retention (%),Real ROC-AUC,Synthetic ROC-AUC,ROC-AUC Retention (%),Overall Utility Retention (%),Status
0,CTGAN,adult_income,Logistic Regression,0.819847,0.666334,0.153514,81.275350,0.861611,0.711778,82.610118,84.840964,PASS
1,TVAE,adult_income,Logistic Regression,0.819847,0.663174,0.156673,80.889949,0.861611,0.647378,75.135768,82.247214,PASS
2,DP-CTGAN,adult_income,Logistic Regression,0.819847,NaN,NaN,NaN,0.861611,NaN,NaN,NaN,PASS
3,SPP-GAN,adult_income,Logistic Regression,0.819847,0.662555,0.157293,80.814391,0.861611,0.828716,96.182112,91.587126,PASS
4,CTGAN,bank_marketing,Logistic Regression,0.870391,0.771661,0.098730,88.656836,0.873401,0.813048,93.089886,89.271430,PASS
5,TVAE,bank_marketing,Logistic Regression,0.870391,0.625478,0.244913,71.861755,0.873401,0.769056,88.053026,76.788548,PASS
6,DP-CTGAN,bank_marketing,Logistic Regression,0.870391,NaN,NaN,NaN,0.873401,NaN,NaN,NaN,PASS
7,SPP-GAN,bank_marketing,Logistic Regression,0.870391,0.828179,0.042212,95.150222,0.873401,0.791847,90.662449,95.396911,PASS
8,CTGAN,diabetes_130us,Logistic Regression,0.509366,0.022517,0.486849,4.420560,NaN,NaN,NaN,37.720409,PASS
9,TVAE,diabetes_130us,Logistic Regression,0.509366,0.161536,0.347830,31.713155,NaN,NaN,NaN,40.347718,PASS
10,DP-CTGAN,diabetes_130us,Logistic Regression,0.509366,NaN,NaN,NaN,NaN,NaN,NaN,NaN,PASS
11,SPP-GAN,diabetes_130us,Logistic Regression,0.509366,0.479923,0.029443,94.219634,NaN,NaN,NaN,96.503202,PASS

====================================================================================================
PART J8 — PRIMARY DOWNSTREAM UTILITY SUMMARY COMPLETED
====================================================================================================

In [143]:
# ==============================================================================
# PART J9 — METHOD-WISE UTILITY SUMMARY
# ==============================================================================

print("=" * 100)
print("PART J9 — METHOD-WISE UTILITY SUMMARY")
print("=" * 100)

J_METHOD_SUMMARY = (
    J_UTILITY_METRICS_DF
    .groupby("Method", dropna=False)
    .agg(
        Mean_F1_Retention=(
            "F1 Retention (%)",
            "mean"
        ),
        Mean_ROC_AUC_Retention=(
            "ROC-AUC Retention (%)",
            "mean"
        ),
        Mean_Accuracy_Retention=(
            "Accuracy Retention (%)",
            "mean"
        ),
        Mean_Overall_Utility_Retention=(
            "Overall Utility Retention (%)",
            "mean"
        ),
        Evaluated_Combinations=(
            "Overall Utility Retention (%)",
            lambda x: x.notna().sum()
        )
    )
    .reset_index()
)

J_METHOD_SUMMARY = (
    J_METHOD_SUMMARY
    .sort_values(
        "Mean_Overall_Utility_Retention",
        ascending=False
    )
    .reset_index(drop=True)
)

display(
    J_METHOD_SUMMARY
)

print()
print("=" * 100)
print("PART J9 — METHOD-WISE UTILITY SUMMARY COMPLETED")
print("=" * 100)

====================================================================================================
PART J9 — METHOD-WISE UTILITY SUMMARY
====================================================================================================

,Method,Mean_F1_Retention,Mean_ROC_AUC_Retention,Mean_Accuracy_Retention,Mean_Overall_Utility_Retention,Evaluated_Combinations
0,SPP-GAN,87.273103,87.719459,94.401916,91.290872,6
1,CTGAN,72.951608,91.244547,78.913624,80.840416,6
2,TVAE,73.117256,83.705336,72.300004,76.282762,6
3,DP-CTGAN,NaN,NaN,NaN,NaN,0

====================================================================================================
PART J9 — METHOD-WISE UTILITY SUMMARY COMPLETED
====================================================================================================

In [144]:
# ==============================================================================
# PART J10 — DATASET-WISE UTILITY SUMMARY
# ==============================================================================

print("=" * 100)
print("PART J10 — DATASET-WISE UTILITY SUMMARY")
print("=" * 100)

J_DATASET_SUMMARY = (
    J_UTILITY_METRICS_DF
    .groupby("Dataset", dropna=False)
    .agg(
        Mean_F1_Retention=(
            "F1 Retention (%)",
            "mean"
        ),
        Mean_ROC_AUC_Retention=(
            "ROC-AUC Retention (%)",
            "mean"
        ),
        Mean_Accuracy_Retention=(
            "Accuracy Retention (%)",
            "mean"
        ),
        Mean_Overall_Utility_Retention=(
            "Overall Utility Retention (%)",
            "mean"
        ),
        Evaluated_Methods=(
            "Overall Utility Retention (%)",
            lambda x: x.notna().sum()
        )
    )
    .reset_index()
)

display(
    J_DATASET_SUMMARY
)

print()
print("=" * 100)
print("PART J10 — DATASET-WISE UTILITY SUMMARY COMPLETED")
print("=" * 100)

====================================================================================================
PART J10 — DATASET-WISE UTILITY SUMMARY
====================================================================================================

,Dataset,Mean_F1_Retention,Mean_ROC_AUC_Retention,Mean_Accuracy_Retention,Mean_Overall_Utility_Retention,Evaluated_Methods
0,adult_income,84.173262,86.308192,90.639045,87.906697,6
1,bank_marketing,86.488962,88.804702,83.475225,87.872441,6
2,diabetes_130us,62.679743,NaN,71.501275,72.634911,6

====================================================================================================
PART J10 — DATASET-WISE UTILITY SUMMARY COMPLETED
====================================================================================================

In [145]:
# ==============================================================================
# PART J11 — DOWNSTREAM UTILITY RANKING
# ==============================================================================

print("=" * 100)
print("PART J11 — DOWNSTREAM UTILITY RANKING")
print("=" * 100)

J_RANKING = (
    J_UTILITY_METRICS_DF[
        [
            "Method",
            "Dataset",
            "ML Model",
            "F1 Retention (%)",
            "ROC-AUC Retention (%)",
            "Overall Utility Retention (%)"
        ]
    ]
    .copy()
)

J_RANKING[
    "Utility Rank"
] = (
    J_RANKING[
        "Overall Utility Retention (%)"
    ]
    .rank(
        ascending=False,
        method="min"
    )
)

J_RANKING = (
    J_RANKING
    .sort_values(
        [
            "Dataset",
            "Utility Rank"
        ]
    )
    .reset_index(drop=True)
)

display(
    J_RANKING
)

print()
print("=" * 100)
print("PART J11 — DOWNSTREAM UTILITY RANKING COMPLETED")
print("=" * 100)

====================================================================================================
PART J11 — DOWNSTREAM UTILITY RANKING
====================================================================================================

,Method,Dataset,ML Model,F1 Retention (%),ROC-AUC Retention (%),Overall Utility Retention (%),Utility Rank
0,CTGAN,adult_income,Random Forest,93.904950,94.473247,93.820646,4.0
1,TVAE,adult_income,Random Forest,90.890574,92.092290,91.783400,6.0
2,SPP-GAN,adult_income,Logistic Regression,80.814391,96.182112,91.587126,8.0
3,CTGAN,adult_income,Logistic Regression,81.275350,82.610118,84.840964,11.0
4,SPP-GAN,adult_income,Random Forest,77.264356,77.355620,83.160834,12.0
5,TVAE,adult_income,Logistic Regression,80.889949,75.135768,82.247214,13.0
6,DP-CTGAN,adult_income,Logistic Regression,NaN,NaN,NaN,NaN
7,DP-CTGAN,adult_income,Random Forest,NaN,NaN,NaN,NaN
8,CTGAN,bank_marketing,Random Forest,98.846626,94.804937,97.628530,1.0
9,SPP-GAN,bank_marketing,Logistic Regression,95.150222,90.662449,95.396911,3.0
10,SPP-GAN,bank_marketing,Random Forest,92.554011,86.677656,93.339457,5.0
11,CTGAN,bank_marketing,Logistic Regression,88.656836,93.089886,89.271430,9.0
12,TVAE,bank_marketing,Logistic Regression,71.861755,88.053026,76.788548,15.0
13,TVAE,bank_marketing,Random Forest,71.864323,79.540261,74.809771,16.0
14,DP-CTGAN,bank_marketing,Logistic Regression,NaN,NaN,NaN,NaN
15,DP-CTGAN,bank_marketing,Random Forest,NaN,NaN,NaN,NaN
16,SPP-GAN,diabetes_130us,Logistic Regression,94.219634,NaN,96.503202,2.0
17,TVAE,diabetes_130us,Random Forest,91.483777,NaN,91.719920,7.0
18,SPP-GAN,diabetes_130us,Random Forest,83.636004,NaN,87.757703,10.0
19,CTGAN,diabetes_130us,Random Forest,70.605325,NaN,81.760516,14.0
20,TVAE,diabetes_130us,Logistic Regression,31.713155,NaN,40.347718,17.0
21,CTGAN,diabetes_130us,Logistic Regression,4.420560,NaN,37.720409,18.0
22,DP-CTGAN,diabetes_130us,Logistic Regression,NaN,NaN,NaN,NaN
23,DP-CTGAN,diabetes_130us,Random Forest,NaN,NaN,NaN,NaN

====================================================================================================
PART J11 — DOWNSTREAM UTILITY RANKING COMPLETED
====================================================================================================

In [146]:
# ==============================================================================
# PART J12 — FINAL DOWNSTREAM ML UTILITY REPORT
# ==============================================================================

print("=" * 100)
print("PART J12 — FINAL DOWNSTREAM ML UTILITY REPORT")
print("=" * 100)

J_TOTAL_COMBINATIONS = (
    len(SYNTHETIC_METHODS)
    * len(SYNTHETIC_DATASET_NAMES)
    * len(J_DOWNSTREAM_MODELS)
)

J_SUCCESSFUL_EVALUATIONS = (
    J_UTILITY_DF["Status"]
    .eq("PASS")
    .sum()
    if not J_UTILITY_DF.empty
    else 0
)

J_SUCCESS_RATE = (
    J_SUCCESSFUL_EVALUATIONS
    / J_TOTAL_COMBINATIONS
    * 100
    if J_TOTAL_COMBINATIONS > 0
    else 0.0
)

J_MEAN_UTILITY_RETENTION = (
    J_UTILITY_METRICS_DF[
        "Overall Utility Retention (%)"
    ].mean()
    if not J_UTILITY_METRICS_DF.empty
    else np.nan
)

J_BEST_METHOD = None
J_BEST_SCORE = np.nan

if not J_METHOD_SUMMARY.empty:

    valid_method_summary = (
        J_METHOD_SUMMARY.dropna(
            subset=[
                "Mean_Overall_Utility_Retention"
            ]
        )
    )

    if not valid_method_summary.empty:

        best_row = (
            valid_method_summary.iloc[0]
        )

        J_BEST_METHOD = best_row["Method"]

        J_BEST_SCORE = (
            best_row[
                "Mean_Overall_Utility_Retention"
            ]
        )

J_FINAL_REPORT = {

    "Total Method-Dataset-Model Combinations":
        J_TOTAL_COMBINATIONS,

    "Successful Evaluations":
        int(J_SUCCESSFUL_EVALUATIONS),

    "Evaluation Success Rate (%)":
        J_SUCCESS_RATE,

    "Mean Overall Utility Retention (%)":
        J_MEAN_UTILITY_RETENTION,

    "Best Method":
        J_BEST_METHOD,

    "Best Method Mean Utility Retention (%)":
        J_BEST_SCORE,

    "Primary ML Model":
        J_PRIMARY_MODEL,

    "Real Test Set Used":
        True,

    "Common Real Test Set Across Methods":
        True,

    "Random State":
        RANDOM_STATE
}

J_FINAL_REPORT_DF = pd.DataFrame(
    [J_FINAL_REPORT]
)

display(
    J_FINAL_REPORT_DF
)

print()
print("-" * 100)
print("J SUMMARY")
print("-" * 100)

print(
    f"Total combinations : "
    f"{J_TOTAL_COMBINATIONS}"
)

print(
    f"Successful          : "
    f"{J_SUCCESSFUL_EVALUATIONS}"
)

print(
    f"Success rate        : "
    f"{J_SUCCESS_RATE:.2f}%"
)

if pd.notna(J_MEAN_UTILITY_RETENTION):

    print(
        f"Mean utility retention : "
        f"{J_MEAN_UTILITY_RETENTION:.2f}%"
    )
else:

    print(
        "Mean utility retention : "
        "Not available"
    )

print(
    f"Best method         : "
    f"{J_BEST_METHOD if J_BEST_METHOD else 'Not available'}"
)

if pd.notna(J_BEST_SCORE):

    print(
        f"Best method utility  : "
        f"{J_BEST_SCORE:.2f}%"
    )

print()
print("=" * 100)
print("PART J12 — FINAL DOWNSTREAM ML UTILITY REPORT COMPLETED")
print("=" * 100)

====================================================================================================
PART J12 — FINAL DOWNSTREAM ML UTILITY REPORT
====================================================================================================

,Total Method-Dataset-Model Combinations,Successful Evaluations,Evaluation Success Rate (%),Mean Overall Utility Retention (%),Best Method,Best Method Mean Utility Retention (%),Primary ML Model,Real Test Set Used,Common Real Test Set Across Methods,Random State
0,24,18,75.0,82.804683,SPP-GAN,91.290872,Logistic Regression,True,True,42

----------------------------------------------------------------------------------------------------
J SUMMARY
----------------------------------------------------------------------------------------------------
Total combinations : 24
Successful          : 18
Success rate        : 75.00%
Mean utility retention : 82.80%
Best method         : SPP-GAN
Best method utility  : 91.29%

====================================================================================================
PART J12 — FINAL DOWNSTREAM ML UTILITY REPORT COMPLETED
====================================================================================================

In [147]:
# ==============================================================================
# PART K1 — PRIVACY ENVIRONMENT AND CONFIGURATION
# ==============================================================================

print("=" * 100)
print("PART K1 — PRIVACY ENVIRONMENT AND CONFIGURATION")
print("=" * 100)

import os
import json
import math
import pathlib
import warnings
import numpy as np
import pandas as pd

from sklearn.preprocessing import MinMaxScaler
from sklearn.neighbors import NearestNeighbors

warnings.filterwarnings("ignore")

# ------------------------------------------------------------------------------
# REQUIRED GLOBAL OBJECTS
# ------------------------------------------------------------------------------

if "SYNTHETIC_METHODS" not in globals():
    SYNTHETIC_METHODS = [
        "CTGAN",
        "TVAE",
        "DP-CTGAN",
        "SPP-GAN"
    ]

if "SYNTHETIC_DATASET_NAMES" not in globals():
    SYNTHETIC_DATASET_NAMES = [
        "adult_income",
        "bank_marketing",
        "diabetes_130us"
    ]

if "SYNTHETIC_DATASETS" not in globals():
    raise NameError(
        "SYNTHETIC_DATASETS is not available. "
        "Run Section D — Synthetic Data Loading first."
    )

if "REAL_DATASETS" not in globals():
    raise NameError(
        "REAL_DATASETS is not available. "
        "Load the reference datasets before running Section K."
    )

# ------------------------------------------------------------------------------
# PRIVACY CONFIGURATION
# ------------------------------------------------------------------------------

K_PRIVACY_EPSILON = float(
    globals().get(
        "DP_PRIVACY_BUDGET",
        globals().get("PRIVACY_BUDGET", 4.0)
    )
)

K_PRIVACY_DELTA = float(
    globals().get(
        "DP_DELTA",
        globals().get("PRIVACY_DELTA", 1e-5)
    )
)

K_NEIGHBOR_SAMPLE_SIZE = 5000
K_MAX_CATEGORICAL_LEVELS = 100
K_RISK_THRESHOLD = 0.05

K_PRIVACY_RESULTS = []
K_DUPLICATE_RESULTS = []
K_NEAREST_NEIGHBOR_RESULTS = []
K_ATTRIBUTE_DISCLOSURE_RESULTS = []
K_KANONYMITY_RESULTS = []

print()
print("Privacy Evaluation Configuration")
print("-" * 100)
print(f"Differential Privacy Epsilon : {K_PRIVACY_EPSILON}")
print(f"Differential Privacy Delta   : {K_PRIVACY_DELTA}")
print(f"Nearest-Neighbor Sample Size : {K_NEIGHBOR_SAMPLE_SIZE}")
print(f"Risk Threshold               : {K_RISK_THRESHOLD}")

print()
print("Methods:")
for method in SYNTHETIC_METHODS:
    print(f"  ✓ {method}")

print()
print("Datasets:")
for dataset in SYNTHETIC_DATASET_NAMES:
    print(f"  ✓ {dataset}")

print()
print("=" * 100)
print("PART K1 — PRIVACY ENVIRONMENT AND CONFIGURATION COMPLETED")
print("=" * 100)

====================================================================================================
PART K1 — PRIVACY ENVIRONMENT AND CONFIGURATION
====================================================================================================

Privacy Evaluation Configuration
----------------------------------------------------------------------------------------------------
Differential Privacy Epsilon : 4.0
Differential Privacy Delta   : 1e-05
Nearest-Neighbor Sample Size : 5000
Risk Threshold               : 0.05

Methods:
  ✓ CTGAN
  ✓ TVAE
  ✓ DP-CTGAN
  ✓ SPP-GAN

Datasets:
  ✓ adult_income
  ✓ bank_marketing
  ✓ diabetes_130us

====================================================================================================
PART K1 — PRIVACY ENVIRONMENT AND CONFIGURATION COMPLETED
====================================================================================================

In [148]:
# ==============================================================================
# PART K2 — PRIVACY PREPROCESSING
# ==============================================================================

print("=" * 100)
print("PART K2 — PRIVACY PREPROCESSING")
print("=" * 100)

def prepare_privacy_data(
    real_df,
    synthetic_df,
    max_categorical_levels=100
):
    """
    Prepare real and synthetic tabular data for privacy-risk analysis.

    Numerical variables:
        - median imputation
        - joint min-max scaling

    Categorical variables:
        - string normalization
        - missing-value replacement
        - category coding using the union of real and synthetic values
    """

    real = real_df.copy()
    synthetic = synthetic_df.copy()

    common_columns = [
        column
        for column in real.columns
        if column in synthetic.columns
    ]

    real = real[common_columns].copy()
    synthetic = synthetic[common_columns].copy()

    numeric_columns = real.select_dtypes(
        include=np.number
    ).columns.tolist()

    categorical_columns = [
        column
        for column in common_columns
        if column not in numeric_columns
    ]

    real_matrix = []
    synthetic_matrix = []

    # --------------------------------------------------------------------------
    # NUMERICAL FEATURES
    # --------------------------------------------------------------------------

    for column in numeric_columns:

        real_values = pd.to_numeric(
            real[column],
            errors="coerce"
        )

        synthetic_values = pd.to_numeric(
            synthetic[column],
            errors="coerce"
        )

        median_value = real_values.median()

        if pd.isna(median_value):
            median_value = 0.0

        real_values = real_values.fillna(
            median_value
        )

        synthetic_values = synthetic_values.fillna(
            median_value
        )

        combined = pd.concat(
            [real_values, synthetic_values],
            axis=0
        )

        minimum = combined.min()
        maximum = combined.max()

        if (
            pd.isna(minimum)
            or pd.isna(maximum)
            or maximum == minimum
        ):
            real_scaled = np.zeros(
                len(real_values),
                dtype=float
            )

            synthetic_scaled = np.zeros(
                len(synthetic_values),
                dtype=float
            )

        else:

            real_scaled = (
                (real_values - minimum)
                / (maximum - minimum)
            ).to_numpy(dtype=float)

            synthetic_scaled = (
                (synthetic_values - minimum)
                / (maximum - minimum)
            ).to_numpy(dtype=float)

        real_matrix.append(real_scaled)
        synthetic_matrix.append(synthetic_scaled)

    # --------------------------------------------------------------------------
    # CATEGORICAL FEATURES
    # --------------------------------------------------------------------------

    for column in categorical_columns:

        real_values = (
            real[column]
            .astype("string")
            .fillna("__MISSING__")
            .astype(str)
        )

        synthetic_values = (
            synthetic[column]
            .astype("string")
            .fillna("__MISSING__")
            .astype(str)
        )

        combined_values = pd.concat(
            [real_values, synthetic_values],
            axis=0
        )

        categories = pd.Index(
            combined_values.unique()
        )

        if len(categories) > max_categorical_levels:
            continue

        mapping = {
            value: index / max(
                len(categories) - 1,
                1
            )
            for index, value in enumerate(categories)
        }

        real_matrix.append(
            real_values.map(mapping)
            .fillna(0.0)
            .to_numpy(dtype=float)
        )

        synthetic_matrix.append(
            synthetic_values.map(mapping)
            .fillna(0.0)
            .to_numpy(dtype=float)
        )

    if real_matrix:

        real_array = np.column_stack(
            real_matrix
        )

        synthetic_array = np.column_stack(
            synthetic_matrix
        )

    else:

        real_array = np.empty(
            (len(real), 0)
        )

        synthetic_array = np.empty(
            (len(synthetic), 0)
        )

    return (
        real_array,
        synthetic_array,
        numeric_columns,
        categorical_columns
    )


print("✓ Privacy preprocessing function prepared")

print()
print("=" * 100)
print("PART K2 — PRIVACY PREPROCESSING COMPLETED")
print("=" * 100)

====================================================================================================
PART K2 — PRIVACY PREPROCESSING
====================================================================================================
✓ Privacy preprocessing function prepared

====================================================================================================
PART K2 — PRIVACY PREPROCESSING COMPLETED
====================================================================================================

In [149]:
# ==============================================================================
# PART K3 — EXACT DUPLICATE DISCLOSURE RISK
# ==============================================================================

print("=" * 100)
print("PART K3 — EXACT DUPLICATE DISCLOSURE RISK")
print("=" * 100)

K3_RESULTS = []

for method in SYNTHETIC_METHODS:

    for dataset in SYNTHETIC_DATASET_NAMES:

        real_df = (
            REAL_DATASETS
            .get(dataset)
        )

        synthetic_df = (
            SYNTHETIC_DATASETS
            .get(method, {})
            .get(dataset)
        )

        if real_df is None or synthetic_df is None:

            K3_RESULTS.append({
                "Method": method,
                "Dataset": dataset,
                "Reference Loaded": real_df is not None,
                "Synthetic Loaded": synthetic_df is not None,
                "Real Rows": 0 if real_df is None else len(real_df),
                "Synthetic Rows": 0 if synthetic_df is None else len(synthetic_df),
                "Exact Matches": np.nan,
                "Exact Match Rate (%)": np.nan,
                "Privacy Status": "NOT EVALUATED"
            })

            continue

        common_columns = [
            column
            for column in real_df.columns
            if column in synthetic_df.columns
        ]

        real_records = set(
            real_df[
                common_columns
            ]
            .astype(str)
            .fillna("__MISSING__")
            .apply(
                tuple,
                axis=1
            )
        )

        synthetic_records = (
            synthetic_df[
                common_columns
            ]
            .astype(str)
            .fillna("__MISSING__")
            .apply(
                tuple,
                axis=1
            )
        )

        exact_matches = int(
            synthetic_records.isin(
                real_records
            ).sum()
        )

        match_rate = (
            exact_matches
            / len(synthetic_df)
            * 100
            if len(synthetic_df) > 0
            else np.nan
        )

        status = (
            "PASS"
            if exact_matches == 0
            else "REVIEW"
        )

        K3_RESULTS.append({
            "Method": method,
            "Dataset": dataset,
            "Reference Loaded": True,
            "Synthetic Loaded": True,
            "Real Rows": len(real_df),
            "Synthetic Rows": len(synthetic_df),
            "Exact Matches": exact_matches,
            "Exact Match Rate (%)": match_rate,
            "Privacy Status": status
        })

K3_DUPLICATE_DISCLOSURE_DF = pd.DataFrame(
    K3_RESULTS
)

display(
    K3_DUPLICATE_DISCLOSURE_DF
)

print()
print("=" * 100)
print("PART K3 — EXACT DUPLICATE DISCLOSURE RISK COMPLETED")
print("=" * 100)

====================================================================================================
PART K3 — EXACT DUPLICATE DISCLOSURE RISK
====================================================================================================

,Method,Dataset,Reference Loaded,Synthetic Loaded,Real Rows,Synthetic Rows,Exact Matches,Exact Match Rate (%),Privacy Status
0,CTGAN,adult_income,True,True,32515,32515,0,0.0,PASS
1,CTGAN,bank_marketing,True,True,45211,45211,0,0.0,PASS
2,CTGAN,diabetes_130us,True,True,101766,101766,0,0.0,PASS
3,TVAE,adult_income,True,True,32515,32510,0,0.0,PASS
4,TVAE,bank_marketing,True,True,45211,45211,0,0.0,PASS
5,TVAE,diabetes_130us,True,True,101766,101766,0,0.0,PASS
6,DP-CTGAN,adult_income,True,True,32515,22760,0,0.0,PASS
7,DP-CTGAN,bank_marketing,True,True,45211,31647,0,0.0,PASS
8,DP-CTGAN,diabetes_130us,True,True,101766,71236,0,0.0,PASS
9,SPP-GAN,adult_income,True,True,32515,32515,0,0.0,PASS
10,SPP-GAN,bank_marketing,True,True,45211,45211,0,0.0,PASS
11,SPP-GAN,diabetes_130us,True,True,101766,101766,0,0.0,PASS

====================================================================================================
PART K3 — EXACT DUPLICATE DISCLOSURE RISK COMPLETED
====================================================================================================

In [150]:
# ==============================================================================
# PART K4 — NEAREST-NEIGHBOR DISCLOSURE RISK
# ==============================================================================

print("=" * 100)
print("PART K4 — NEAREST-NEIGHBOR DISCLOSURE RISK")
print("=" * 100)

K4_RESULTS = []

for method in SYNTHETIC_METHODS:

    for dataset in SYNTHETIC_DATASET_NAMES:

        real_df = REAL_DATASETS.get(dataset)
        synthetic_df = (
            SYNTHETIC_DATASETS
            .get(method, {})
            .get(dataset)
        )

        if real_df is None or synthetic_df is None:

            K4_RESULTS.append({
                "Method": method,
                "Dataset": dataset,
                "Reference Loaded": real_df is not None,
                "Synthetic Loaded": synthetic_df is not None,
                "Evaluated Synthetic Records": 0,
                "Mean Nearest Distance": np.nan,
                "Median Nearest Distance": np.nan,
                "Minimum Nearest Distance": np.nan,
                "High Similarity Records": np.nan,
                "High Similarity Rate (%)": np.nan,
                "Privacy Status": "NOT EVALUATED"
            })

            continue

        try:

            real_array, synthetic_array, _, _ = (
                prepare_privacy_data(
                    real_df,
                    synthetic_df
                )
            )

            if (
                real_array.shape[1] == 0
                or len(real_array) == 0
                or len(synthetic_array) == 0
            ):
                raise ValueError(
                    "No usable features available."
                )

            if len(synthetic_array) > K_NEIGHBOR_SAMPLE_SIZE:

                rng = np.random.default_rng(42)

                selected_indices = rng.choice(
                    len(synthetic_array),
                    size=K_NEIGHBOR_SAMPLE_SIZE,
                    replace=False
                )

                synthetic_sample = (
                    synthetic_array[
                        selected_indices
                    ]
                )

            else:

                synthetic_sample = synthetic_array

            nearest_neighbors = NearestNeighbors(
                n_neighbors=1,
                metric="euclidean"
            )

            nearest_neighbors.fit(
                real_array
            )

            distances, _ = (
                nearest_neighbors.kneighbors(
                    synthetic_sample
                )
            )

            distances = distances[:, 0]

            # A distance <= 0.05 indicates extremely high similarity
            high_similarity = (
                distances <= 0.05
            )

            high_similarity_rate = (
                high_similarity.mean() * 100
            )

            if high_similarity_rate <= 5:
                privacy_status = "PASS"
            elif high_similarity_rate <= 10:
                privacy_status = "REVIEW"
            else:
                privacy_status = "HIGH RISK"

            K4_RESULTS.append({
                "Method": method,
                "Dataset": dataset,
                "Reference Loaded": True,
                "Synthetic Loaded": True,
                "Evaluated Synthetic Records": len(distances),
                "Mean Nearest Distance": float(
                    np.mean(distances)
                ),
                "Median Nearest Distance": float(
                    np.median(distances)
                ),
                "Minimum Nearest Distance": float(
                    np.min(distances)
                ),
                "High Similarity Records": int(
                    high_similarity.sum()
                ),
                "High Similarity Rate (%)": float(
                    high_similarity_rate
                ),
                "Privacy Status": privacy_status
            })

        except Exception as error:

            K4_RESULTS.append({
                "Method": method,
                "Dataset": dataset,
                "Reference Loaded": True,
                "Synthetic Loaded": True,
                "Evaluated Synthetic Records": 0,
                "Mean Nearest Distance": np.nan,
                "Median Nearest Distance": np.nan,
                "Minimum Nearest Distance": np.nan,
                "High Similarity Records": np.nan,
                "High Similarity Rate (%)": np.nan,
                "Privacy Status": f"ERROR: {type(error).__name__}"
            })

K4_NEAREST_NEIGHBOR_DF = pd.DataFrame(
    K4_RESULTS
)

display(
    K4_NEAREST_NEIGHBOR_DF
)

print()
print("=" * 100)
print("PART K4 — NEAREST-NEIGHBOR DISCLOSURE RISK COMPLETED")
print("=" * 100)

====================================================================================================
PART K4 — NEAREST-NEIGHBOR DISCLOSURE RISK
====================================================================================================

,Method,Dataset,Reference Loaded,Synthetic Loaded,Evaluated Synthetic Records,Mean Nearest Distance,Median Nearest Distance,Minimum Nearest Distance,High Similarity Records,High Similarity Rate (%),Privacy Status
0,CTGAN,adult_income,True,True,5000,0.606946,0.606646,0.126960,0,0.0,PASS
1,CTGAN,bank_marketing,True,True,5000,0.753520,0.721016,0.505227,0,0.0,PASS
2,CTGAN,diabetes_130us,True,True,5000,0.958489,0.934699,0.379754,0,0.0,PASS
3,TVAE,adult_income,True,True,5000,0.535457,0.547522,0.161411,0,0.0,PASS
4,TVAE,bank_marketing,True,True,5000,0.698963,0.673210,0.503223,0,0.0,PASS
5,TVAE,diabetes_130us,True,True,5000,0.799630,0.725315,0.321068,0,0.0,PASS
6,DP-CTGAN,adult_income,True,True,5000,1.573650,1.573712,1.539286,0,0.0,PASS
7,DP-CTGAN,bank_marketing,True,True,5000,0.314171,0.314650,0.297208,0,0.0,PASS
8,DP-CTGAN,diabetes_130us,True,True,5000,3.380177,3.380131,3.375496,0,0.0,PASS
9,SPP-GAN,adult_income,True,True,5000,0.577378,0.531705,0.073883,0,0.0,PASS
10,SPP-GAN,bank_marketing,True,True,5000,0.484732,0.463587,0.076423,0,0.0,PASS
11,SPP-GAN,diabetes_130us,True,True,5000,0.725794,0.695404,0.242178,0,0.0,PASS

====================================================================================================
PART K4 — NEAREST-NEIGHBOR DISCLOSURE RISK COMPLETED
====================================================================================================

In [151]:
# ==============================================================================
# PART K5 — ATTRIBUTE DISCLOSURE RISK
# ==============================================================================

print("=" * 100)
print("PART K5 — ATTRIBUTE DISCLOSURE RISK")
print("=" * 100)

K5_RESULTS = []

for method in SYNTHETIC_METHODS:

    for dataset in SYNTHETIC_DATASET_NAMES:

        real_df = REAL_DATASETS.get(dataset)
        synthetic_df = (
            SYNTHETIC_DATASETS
            .get(method, {})
            .get(dataset)
        )

        if real_df is None or synthetic_df is None:

            K5_RESULTS.append({
                "Method": method,
                "Dataset": dataset,
                "Evaluated Columns": 0,
                "Mean Attribute Disclosure Risk (%)": np.nan,
                "Maximum Attribute Disclosure Risk (%)": np.nan,
                "High Risk Columns": np.nan,
                "Privacy Status": "NOT EVALUATED"
            })

            continue

        risk_values = []
        high_risk_columns = 0

        for column in real_df.columns:

            if column not in synthetic_df.columns:
                continue

            real_values = (
                real_df[column]
                .astype(str)
                .fillna("__MISSING__")
            )

            synthetic_values = (
                synthetic_df[column]
                .astype(str)
                .fillna("__MISSING__")
            )

            real_distribution = (
                real_values
                .value_counts(
                    normalize=True
                )
            )

            synthetic_distribution = (
                synthetic_values
                .value_counts(
                    normalize=True
                )
            )

            all_values = (
                set(real_distribution.index)
                | set(synthetic_distribution.index)
            )

            if not all_values:
                continue

            tv_distance = 0.5 * sum(
                abs(
                    real_distribution.get(
                        value,
                        0.0
                    )
                    -
                    synthetic_distribution.get(
                        value,
                        0.0
                    )
                )
                for value in all_values
            )

            # Lower distribution distance means stronger similarity.
            # Convert to disclosure-risk proxy conservatively.
            disclosure_risk = (
                max(
                    0.0,
                    1.0 - tv_distance
                )
                * 100
            )

            risk_values.append(
                disclosure_risk
            )

            if disclosure_risk >= 95:
                high_risk_columns += 1

        mean_risk = (
            np.mean(risk_values)
            if risk_values
            else np.nan
        )

        maximum_risk = (
            np.max(risk_values)
            if risk_values
            else np.nan
        )

        if high_risk_columns == 0:
            status = "PASS"
        elif high_risk_columns <= 2:
            status = "REVIEW"
        else:
            status = "HIGH RISK"

        K5_RESULTS.append({
            "Method": method,
            "Dataset": dataset,
            "Evaluated Columns": len(risk_values),
            "Mean Attribute Disclosure Risk (%)": mean_risk,
            "Maximum Attribute Disclosure Risk (%)": maximum_risk,
            "High Risk Columns": high_risk_columns,
            "Privacy Status": status
        })

K5_ATTRIBUTE_DISCLOSURE_DF = pd.DataFrame(
    K5_RESULTS
)

display(
    K5_ATTRIBUTE_DISCLOSURE_DF
)

print()
print("=" * 100)
print("PART K5 — ATTRIBUTE DISCLOSURE RISK COMPLETED")
print("=" * 100)

====================================================================================================
PART K5 — ATTRIBUTE DISCLOSURE RISK
====================================================================================================

,Method,Dataset,Evaluated Columns,Mean Attribute Disclosure Risk (%),Maximum Attribute Disclosure Risk (%),High Risk Columns,Privacy Status
0,CTGAN,adult_income,15,5.239182e+01,9.762571e+01,2,REVIEW
1,CTGAN,bank_marketing,17,5.344977e+01,9.892283e+01,5,HIGH RISK
2,CTGAN,diabetes_130us,48,7.184581e+01,1.000000e+02,28,HIGH RISK
3,TVAE,adult_income,15,3.856762e+01,9.791863e+01,2,REVIEW
4,TVAE,bank_marketing,17,4.434813e+01,9.823715e+01,4,HIGH RISK
5,TVAE,diabetes_130us,48,7.069580e+01,1.000000e+02,22,HIGH RISK
6,DP-CTGAN,adult_income,15,8.442876e-12,4.923839e-11,0,PASS
7,DP-CTGAN,bank_marketing,17,4.287877e-11,6.675771e-11,0,PASS
8,DP-CTGAN,diabetes_130us,48,3.078556e-13,3.863576e-12,0,PASS
9,SPP-GAN,adult_income,15,4.913999e+01,9.990158e+01,6,HIGH RISK
10,SPP-GAN,bank_marketing,17,5.391478e+01,9.992922e+01,8,HIGH RISK
11,SPP-GAN,diabetes_130us,48,7.714065e+01,1.000000e+02,35,HIGH RISK

====================================================================================================
PART K5 — ATTRIBUTE DISCLOSURE RISK COMPLETED
====================================================================================================

In [152]:
# ==============================================================================
# PART K6 — K-ANONYMITY / UNIQUENESS EXPOSURE
# ==============================================================================

print("=" * 100)
print("PART K6 — K-ANONYMITY / UNIQUENESS EXPOSURE")
print("=" * 100)

K6_RESULTS = []

for method in SYNTHETIC_METHODS:

    for dataset in SYNTHETIC_DATASET_NAMES:

        real_df = REAL_DATASETS.get(dataset)
        synthetic_df = (
            SYNTHETIC_DATASETS
            .get(method, {})
            .get(dataset)
        )

        if real_df is None or synthetic_df is None:

            K6_RESULTS.append({
                "Method": method,
                "Dataset": dataset,
                "Quasi-Identifier Columns": 0,
                "Unique Synthetic Records": np.nan,
                "Synthetic Uniqueness Rate (%)": np.nan,
                "Synthetic Records Matching Unique Real Patterns": np.nan,
                "Unique Pattern Exposure (%)": np.nan,
                "Privacy Status": "NOT EVALUATED"
            })

            continue

        common_columns = [
            column
            for column in real_df.columns
            if column in synthetic_df.columns
        ]

        # Use categorical and low-cardinality variables as practical
        # quasi-identifiers.
        quasi_identifier_columns = []

        for column in common_columns:

            combined = pd.concat(
                [
                    real_df[column],
                    synthetic_df[column]
                ],
                axis=0
            )

            unique_count = (
                combined
                .nunique(
                    dropna=False
                )
            )

            if (
                unique_count <= 50
                and unique_count > 1
            ):
                quasi_identifier_columns.append(
                    column
                )

        if not quasi_identifier_columns:

            K6_RESULTS.append({
                "Method": method,
                "Dataset": dataset,
                "Quasi-Identifier Columns": 0,
                "Unique Synthetic Records": np.nan,
                "Synthetic Uniqueness Rate (%)": np.nan,
                "Synthetic Records Matching Unique Real Patterns": np.nan,
                "Unique Pattern Exposure (%)": np.nan,
                "Privacy Status": "NOT APPLICABLE"
            })

            continue

        real_qi = (
            real_df[
                quasi_identifier_columns
            ]
            .astype(str)
            .fillna("__MISSING__")
        )

        synthetic_qi = (
            synthetic_df[
                quasi_identifier_columns
            ]
            .astype(str)
            .fillna("__MISSING__")
        )

        real_pattern_counts = (
            real_qi
            .value_counts()
        )

        synthetic_pattern_counts = (
            synthetic_qi
            .value_counts()
        )

        unique_synthetic_records = int(
            (
                synthetic_pattern_counts
                == 1
            ).sum()
        )

        synthetic_uniqueness_rate = (
            unique_synthetic_records
            / len(synthetic_qi)
            * 100
            if len(synthetic_qi) > 0
            else np.nan
        )

        unique_real_patterns = set(
            real_pattern_counts[
                real_pattern_counts == 1
            ].index
        )

        synthetic_unique_real_matches = sum(
            1
            for pattern in synthetic_qi.itertuples(
                index=False,
                name=None
            )
            if pattern in unique_real_patterns
        )

        unique_pattern_exposure = (
            synthetic_unique_real_matches
            / len(synthetic_qi)
            * 100
            if len(synthetic_qi) > 0
            else np.nan
        )

        if unique_pattern_exposure <= 5:
            status = "PASS"
        elif unique_pattern_exposure <= 10:
            status = "REVIEW"
        else:
            status = "HIGH RISK"

        K6_RESULTS.append({
            "Method": method,
            "Dataset": dataset,
            "Quasi-Identifier Columns": len(
                quasi_identifier_columns
            ),
            "Unique Synthetic Records": unique_synthetic_records,
            "Synthetic Uniqueness Rate (%)": synthetic_uniqueness_rate,
            "Synthetic Records Matching Unique Real Patterns":
                synthetic_unique_real_matches,
            "Unique Pattern Exposure (%)":
                unique_pattern_exposure,
            "Privacy Status": status
        })

K6_KANONYMITY_DF = pd.DataFrame(
    K6_RESULTS
)

display(
    K6_KANONYMITY_DF
)

print()
print("=" * 100)
print("PART K6 — K-ANONYMITY / UNIQUENESS EXPOSURE COMPLETED")
print("=" * 100)

====================================================================================================
PART K6 — K-ANONYMITY / UNIQUENESS EXPOSURE
====================================================================================================

,Method,Dataset,Quasi-Identifier Columns,Unique Synthetic Records,Synthetic Uniqueness Rate (%),Synthetic Records Matching Unique Real Patterns,Unique Pattern Exposure (%),Privacy Status
0,CTGAN,adult_income,9,2083.0,6.406274,1.0,0.003076,PASS
1,CTGAN,bank_marketing,12,2782.0,6.153370,0.0,0.000000,PASS
2,CTGAN,diabetes_130us,36,58525.0,57.509384,0.0,0.000000,PASS
3,TVAE,adult_income,6,105.0,0.322978,301.0,0.925869,PASS
4,TVAE,bank_marketing,10,194.0,0.429099,0.0,0.000000,PASS
5,TVAE,diabetes_130us,36,2441.0,2.398640,0.0,0.000000,PASS
6,DP-CTGAN,adult_income,0,NaN,NaN,NaN,NaN,NOT APPLICABLE
7,DP-CTGAN,bank_marketing,1,1.0,0.003160,0.0,0.000000,PASS
8,DP-CTGAN,diabetes_130us,1,1.0,0.001404,0.0,0.000000,PASS
9,SPP-GAN,adult_income,9,25496.0,78.413040,163.0,0.501307,PASS
10,SPP-GAN,bank_marketing,10,11462.0,25.352237,4824.0,10.669970,HIGH RISK
11,SPP-GAN,diabetes_130us,35,95206.0,93.553839,816.0,0.801840,PASS

====================================================================================================
PART K6 — K-ANONYMITY / UNIQUENESS EXPOSURE COMPLETED
====================================================================================================

In [153]:
# ==============================================================================
# PART K7 — DIFFERENTIAL PRIVACY ACCOUNTING
# ==============================================================================

print("=" * 100)
print("PART K7 — DIFFERENTIAL PRIVACY ACCOUNTING")
print("=" * 100)

K7_RESULTS = []

# ------------------------------------------------------------------------------
# SEARCH EXISTING PRIVACY ACCOUNTING OBJECTS
# ------------------------------------------------------------------------------

privacy_summary_candidates = [
    "DP_PRIVACY_ACCOUNTING_SUMMARY",
    "PRIVACY_ACCOUNTING_SUMMARY",
    "DP_PRIVACY_SUMMARY",
    "PRIVACY_SUMMARY"
]

privacy_summary = None

for variable_name in privacy_summary_candidates:

    if variable_name in globals():

        candidate = globals()[variable_name]

        if isinstance(candidate, pd.DataFrame):
            privacy_summary = candidate.copy()
            break

# ------------------------------------------------------------------------------
# SEARCH COMMON COLUMNS
# ------------------------------------------------------------------------------

def find_column(
    dataframe,
    candidates
):
    if dataframe is None:
        return None

    normalized = {
        str(column).strip().lower(): column
        for column in dataframe.columns
    }

    for candidate in candidates:

        key = candidate.strip().lower()

        if key in normalized:
            return normalized[key]

    return None

epsilon_column = find_column(
    privacy_summary,
    [
        "Epsilon",
        "ε",
        "Target Epsilon",
        "Current Epsilon"
    ]
)

delta_column = find_column(
    privacy_summary,
    [
        "Delta",
        "δ",
        "Target Delta"
    ]
)

noise_column = find_column(
    privacy_summary,
    [
        "Noise Multiplier",
        "noise_multiplier"
    ]
)

accountant_column = find_column(
    privacy_summary,
    [
        "Accountant",
        "Privacy Accountant"
    ]
)

# ------------------------------------------------------------------------------
# DATASET-SPECIFIC DP CONFIGURATION
# ------------------------------------------------------------------------------

for dataset in SYNTHETIC_DATASET_NAMES:

    epsilon = np.nan
    delta = np.nan
    noise_multiplier = np.nan
    accountant = "Not Available"

    if privacy_summary is not None:

        dataset_column = find_column(
            privacy_summary,
            [
                "Dataset",
                "dataset",
                "DataSet"
            ]
        )

        if dataset_column is not None:

            subset = privacy_summary[
                privacy_summary[
                    dataset_column
                ]
                .astype(str)
                .str.lower()
                .str.replace("_", " ")
                .str.strip()
                .eq(
                    dataset.lower()
                    .replace("_", " ")
                )
            ]

            if not subset.empty:

                row = subset.iloc[0]

                if epsilon_column is not None:
                    epsilon = pd.to_numeric(
                        row[epsilon_column],
                        errors="coerce"
                    )

                if delta_column is not None:
                    delta = pd.to_numeric(
                        row[delta_column],
                        errors="coerce"
                    )

                if noise_column is not None:
                    noise_multiplier = pd.to_numeric(
                        row[noise_column],
                        errors="coerce"
                    )

                if accountant_column is not None:
                    accountant = str(
                        row[accountant_column]
                    )

    # Fall back to global DP configuration.
    if pd.isna(epsilon):
        epsilon = K_PRIVACY_EPSILON

    if pd.isna(delta):
        delta = K_PRIVACY_DELTA

    K7_RESULTS.append({
        "Method": "DP-CTGAN",
        "Dataset": dataset,
        "DP Guarantee": True,
        "Epsilon": epsilon,
        "Delta": delta,
        "Noise Multiplier": noise_multiplier,
        "Privacy Accountant": accountant,
        "DP Status": (
            "CONFIGURED"
            if pd.notna(epsilon)
            and pd.notna(delta)
            else "NOT VERIFIED"
        )
    })

# ------------------------------------------------------------------------------
# NON-DP BASELINES
# ------------------------------------------------------------------------------

for method in [
    "CTGAN",
    "TVAE",
    "SPP-GAN"
]:

    for dataset in SYNTHETIC_DATASET_NAMES:

        K7_RESULTS.append({
            "Method": method,
            "Dataset": dataset,
            "DP Guarantee": False,
            "Epsilon": np.nan,
            "Delta": np.nan,
            "Noise Multiplier": np.nan,
            "Privacy Accountant": "Not Applicable",
            "DP Status": "NO FORMAL DP GUARANTEE"
        })

DP_ACCOUNTING_DF = pd.DataFrame(
    K7_RESULTS
)

DP_ACCOUNTING_DF = DP_ACCOUNTING_DF[
    [
        "Method",
        "Dataset",
        "DP Guarantee",
        "Epsilon",
        "Delta",
        "Noise Multiplier",
        "Privacy Accountant",
        "DP Status"
    ]
]

display(
    DP_ACCOUNTING_DF
)

print()
print("=" * 100)
print("PART K7 — DIFFERENTIAL PRIVACY ACCOUNTING COMPLETED")
print("=" * 100)

====================================================================================================
PART K7 — DIFFERENTIAL PRIVACY ACCOUNTING
====================================================================================================

,Method,Dataset,DP Guarantee,Epsilon,Delta,Noise Multiplier,Privacy Accountant,DP Status
0,DP-CTGAN,adult_income,True,4.0,0.00001,NaN,Not Available,CONFIGURED
1,DP-CTGAN,bank_marketing,True,4.0,0.00001,NaN,Not Available,CONFIGURED
2,DP-CTGAN,diabetes_130us,True,4.0,0.00001,NaN,Not Available,CONFIGURED
3,CTGAN,adult_income,False,NaN,NaN,NaN,Not Applicable,NO FORMAL DP GUARANTEE
4,CTGAN,bank_marketing,False,NaN,NaN,NaN,Not Applicable,NO FORMAL DP GUARANTEE
5,CTGAN,diabetes_130us,False,NaN,NaN,NaN,Not Applicable,NO FORMAL DP GUARANTEE
6,TVAE,adult_income,False,NaN,NaN,NaN,Not Applicable,NO FORMAL DP GUARANTEE
7,TVAE,bank_marketing,False,NaN,NaN,NaN,Not Applicable,NO FORMAL DP GUARANTEE
8,TVAE,diabetes_130us,False,NaN,NaN,NaN,Not Applicable,NO FORMAL DP GUARANTEE
9,SPP-GAN,adult_income,False,NaN,NaN,NaN,Not Applicable,NO FORMAL DP GUARANTEE
10,SPP-GAN,bank_marketing,False,NaN,NaN,NaN,Not Applicable,NO FORMAL DP GUARANTEE
11,SPP-GAN,diabetes_130us,False,NaN,NaN,NaN,Not Applicable,NO FORMAL DP GUARANTEE

====================================================================================================
PART K7 — DIFFERENTIAL PRIVACY ACCOUNTING COMPLETED
====================================================================================================

In [154]:
# ==============================================================================
# PART K8 — CONSOLIDATED PRIVACY RISK SUMMARY
# ==============================================================================

print("=" * 100)
print("PART K8 — CONSOLIDATED PRIVACY RISK SUMMARY")
print("=" * 100)

K8_RESULTS = []

for method in SYNTHETIC_METHODS:

    for dataset in SYNTHETIC_DATASET_NAMES:

        duplicate_row = K3_DUPLICATE_DISCLOSURE_DF[
            (
                K3_DUPLICATE_DISCLOSURE_DF["Method"]
                == method
            )
            &
            (
                K3_DUPLICATE_DISCLOSURE_DF["Dataset"]
                == dataset
            )
        ]

        neighbor_row = K4_NEAREST_NEIGHBOR_DF[
            (
                K4_NEAREST_NEIGHBOR_DF["Method"]
                == method
            )
            &
            (
                K4_NEAREST_NEIGHBOR_DF["Dataset"]
                == dataset
            )
        ]

        attribute_row = K5_ATTRIBUTE_DISCLOSURE_DF[
            (
                K5_ATTRIBUTE_DISCLOSURE_DF["Method"]
                == method
            )
            &
            (
                K5_ATTRIBUTE_DISCLOSURE_DF["Dataset"]
                == dataset
            )
        ]

        kanonymity_row = K6_KANONYMITY_DF[
            (
                K6_KANONYMITY_DF["Method"]
                == method
            )
            &
            (
                K6_KANONYMITY_DF["Dataset"]
                == dataset
            )
        ]

        # ----------------------------------------------------------------------
        # VALUES
        # ----------------------------------------------------------------------

        exact_match_rate = np.nan

        if not duplicate_row.empty:
            exact_match_rate = pd.to_numeric(
                duplicate_row.iloc[0][
                    "Exact Match Rate (%)"
                ],
                errors="coerce"
            )

        high_similarity_rate = np.nan

        if not neighbor_row.empty:
            high_similarity_rate = pd.to_numeric(
                neighbor_row.iloc[0][
                    "High Similarity Rate (%)"
                ],
                errors="coerce"
            )

        attribute_risk = np.nan

        if not attribute_row.empty:
            attribute_risk = pd.to_numeric(
                attribute_row.iloc[0][
                    "Mean Attribute Disclosure Risk (%)"
                ],
                errors="coerce"
            )

        unique_pattern_exposure = np.nan

        if not kanonymity_row.empty:
            unique_pattern_exposure = pd.to_numeric(
                kanonymity_row.iloc[0][
                    "Unique Pattern Exposure (%)"
                ],
                errors="coerce"
            )

        # ----------------------------------------------------------------------
        # RISK SCORE
        # ----------------------------------------------------------------------
        #
        # Exact disclosure:
        #   0% = no exact disclosure
        #
        # Nearest-neighbor:
        #   high similarity rate
        #
        # Attribute disclosure:
        #   converted from similarity to risk
        #
        # Unique pattern exposure:
        #   direct exposure measure
        #
        # ----------------------------------------------------------------------

        risk_components = []

        if pd.notna(exact_match_rate):
            risk_components.append(
                min(
                    exact_match_rate,
                    100.0
                )
            )

        if pd.notna(high_similarity_rate):
            risk_components.append(
                min(
                    high_similarity_rate,
                    100.0
                )
            )

        if pd.notna(attribute_risk):
            # Attribute similarity is not itself disclosure.
            # Use a conservative scaled proxy.
            risk_components.append(
                min(
                    attribute_risk * 0.10,
                    100.0
                )
            )

        if pd.notna(unique_pattern_exposure):
            risk_components.append(
                min(
                    unique_pattern_exposure,
                    100.0
                )
            )

        overall_risk = (
            np.mean(risk_components)
            if risk_components
            else np.nan
        )

        privacy_score = (
            max(
                0.0,
                100.0 - overall_risk
            )
            if pd.notna(overall_risk)
            else np.nan
        )

        # ----------------------------------------------------------------------
        # DP GUARANTEE
        # ----------------------------------------------------------------------

        dp_guarantee = (
            method == "DP-CTGAN"
        )

        if dp_guarantee:

            privacy_status = (
                "DP GUARANTEED"
                if (
                    pd.notna(
                        K_PRIVACY_EPSILON
                    )
                    and pd.notna(
                        K_PRIVACY_DELTA
                    )
                )
                else "DP CONFIGURATION NOT VERIFIED"
            )

        elif pd.notna(overall_risk):

            if overall_risk <= 5:
                privacy_status = "LOW EMPIRICAL RISK"
            elif overall_risk <= 10:
                privacy_status = "MODERATE EMPIRICAL RISK"
            else:
                privacy_status = "HIGH EMPIRICAL RISK"

        else:

            privacy_status = "NOT EVALUATED"

        K8_RESULTS.append({

            "Method": method,

            "Dataset": dataset,

            "Exact Match Rate (%)":
                exact_match_rate,

            "High Similarity Rate (%)":
                high_similarity_rate,

            "Attribute Disclosure Risk (%)":
                attribute_risk,

            "Unique Pattern Exposure (%)":
                unique_pattern_exposure,

            "Overall Empirical Privacy Risk (%)":
                overall_risk,

            "Empirical Privacy Score (%)":
                privacy_score,

            "Formal DP Guarantee":
                dp_guarantee,

            "Privacy Status":
                privacy_status
        })

PRIVACY_RISK_SUMMARY_DF = pd.DataFrame(
    K8_RESULTS
)

display(
    PRIVACY_RISK_SUMMARY_DF
)

print()
print("=" * 100)
print("PART K8 — CONSOLIDATED PRIVACY RISK SUMMARY COMPLETED")
print("=" * 100)

====================================================================================================
PART K8 — CONSOLIDATED PRIVACY RISK SUMMARY
====================================================================================================

,Method,Dataset,Exact Match Rate (%),High Similarity Rate (%),Attribute Disclosure Risk (%),Unique Pattern Exposure (%),Overall Empirical Privacy Risk (%),Empirical Privacy Score (%),Formal DP Guarantee,Privacy Status
0,CTGAN,adult_income,0.0,0.0,5.239182e+01,0.003076,1.310564e+00,98.689436,False,LOW EMPIRICAL RISK
1,CTGAN,bank_marketing,0.0,0.0,5.344977e+01,0.000000,1.336244e+00,98.663756,False,LOW EMPIRICAL RISK
2,CTGAN,diabetes_130us,0.0,0.0,7.184581e+01,0.000000,1.796145e+00,98.203855,False,LOW EMPIRICAL RISK
3,TVAE,adult_income,0.0,0.0,3.856762e+01,0.925869,1.195658e+00,98.804342,False,LOW EMPIRICAL RISK
4,TVAE,bank_marketing,0.0,0.0,4.434813e+01,0.000000,1.108703e+00,98.891297,False,LOW EMPIRICAL RISK
5,TVAE,diabetes_130us,0.0,0.0,7.069580e+01,0.000000,1.767395e+00,98.232605,False,LOW EMPIRICAL RISK
6,DP-CTGAN,adult_income,0.0,0.0,8.442876e-12,NaN,2.814292e-13,100.000000,True,DP GUARANTEED
7,DP-CTGAN,bank_marketing,0.0,0.0,4.287877e-11,0.000000,1.071969e-12,100.000000,True,DP GUARANTEED
8,DP-CTGAN,diabetes_130us,0.0,0.0,3.078556e-13,0.000000,7.696390e-15,100.000000,True,DP GUARANTEED
9,SPP-GAN,adult_income,0.0,0.0,4.913999e+01,0.501307,1.353826e+00,98.646174,False,LOW EMPIRICAL RISK
10,SPP-GAN,bank_marketing,0.0,0.0,5.391478e+01,10.669970,4.015362e+00,95.984638,False,LOW EMPIRICAL RISK
11,SPP-GAN,diabetes_130us,0.0,0.0,7.714065e+01,0.801840,2.128976e+00,97.871024,False,LOW EMPIRICAL RISK

====================================================================================================
PART K8 — CONSOLIDATED PRIVACY RISK SUMMARY COMPLETED
====================================================================================================

In [155]:
# ==============================================================================
# PART K9 — METHOD-LEVEL PRIVACY SUMMARY
# ==============================================================================

print("=" * 100)
print("PART K9 — METHOD-LEVEL PRIVACY SUMMARY")
print("=" * 100)

K9_RESULTS = []

for method in SYNTHETIC_METHODS:

    subset = PRIVACY_RISK_SUMMARY_DF[
        PRIVACY_RISK_SUMMARY_DF["Method"]
        == method
    ]

    empirical_risk = pd.to_numeric(
        subset[
            "Overall Empirical Privacy Risk (%)"
        ],
        errors="coerce"
    )

    privacy_score = pd.to_numeric(
        subset[
            "Empirical Privacy Score (%)"
        ],
        errors="coerce"
    )

    formal_dp = bool(
        subset[
            "Formal DP Guarantee"
        ]
        .fillna(False)
        .any()
    )

    K9_RESULTS.append({

        "Method":
            method,

        "Datasets Evaluated":
            len(subset),

        "Mean Empirical Privacy Risk (%)":
            empirical_risk.mean(),

        "Maximum Empirical Privacy Risk (%)":
            empirical_risk.max(),

        "Mean Empirical Privacy Score (%)":
            privacy_score.mean(),

        "Minimum Empirical Privacy Score (%)":
            privacy_score.min(),

        "Formal Differential Privacy":
            formal_dp,

        "Overall Privacy Assessment":
            (
                "FORMAL DP + EMPIRICAL RISK ASSESSMENT"
                if formal_dp
                else "EMPIRICAL RISK ASSESSMENT ONLY"
            )
    })

PRIVACY_METHOD_SUMMARY_DF = pd.DataFrame(
    K9_RESULTS
)

display(
    PRIVACY_METHOD_SUMMARY_DF
)

print()
print("=" * 100)
print("PART K9 — METHOD-LEVEL PRIVACY SUMMARY COMPLETED")
print("=" * 100)

====================================================================================================
PART K9 — METHOD-LEVEL PRIVACY SUMMARY
====================================================================================================

,Method,Datasets Evaluated,Mean Empirical Privacy Risk (%),Maximum Empirical Privacy Risk (%),Mean Empirical Privacy Score (%),Minimum Empirical Privacy Score (%),Formal Differential Privacy,Overall Privacy Assessment
0,CTGAN,3,1.480985e+00,1.796145e+00,98.519015,98.203855,False,EMPIRICAL RISK ASSESSMENT ONLY
1,TVAE,3,1.357252e+00,1.767395e+00,98.642748,98.232605,False,EMPIRICAL RISK ASSESSMENT ONLY
2,DP-CTGAN,3,4.536983e-13,1.071969e-12,100.000000,100.000000,True,FORMAL DP + EMPIRICAL RISK ASSESSMENT
3,SPP-GAN,3,2.499388e+00,4.015362e+00,97.500612,95.984638,False,EMPIRICAL RISK ASSESSMENT ONLY

====================================================================================================
PART K9 — METHOD-LEVEL PRIVACY SUMMARY COMPLETED
====================================================================================================

In [156]:
# ==============================================================================
# PART K10 — PRIVACY METHOD RANKING
# ==============================================================================

print("=" * 100)
print("PART K10 — PRIVACY METHOD RANKING")
print("=" * 100)

PRIVACY_RANKING_DF = (
    PRIVACY_METHOD_SUMMARY_DF
    .copy()
)

PRIVACY_RANKING_DF = (
    PRIVACY_RANKING_DF
    .sort_values(
        by=[
            "Formal Differential Privacy",
            "Mean Empirical Privacy Risk (%)"
        ],
        ascending=[
            False,
            True
        ]
    )
    .reset_index(drop=True)
)

PRIVACY_RANKING_DF[
    "Privacy Rank"
] = np.arange(
    1,
    len(PRIVACY_RANKING_DF) + 1
)

display(
    PRIVACY_RANKING_DF
)

print()
print("=" * 100)
print("PART K10 — PRIVACY METHOD RANKING COMPLETED")
print("=" * 100)

====================================================================================================
PART K10 — PRIVACY METHOD RANKING
====================================================================================================

,Method,Datasets Evaluated,Mean Empirical Privacy Risk (%),Maximum Empirical Privacy Risk (%),Mean Empirical Privacy Score (%),Minimum Empirical Privacy Score (%),Formal Differential Privacy,Overall Privacy Assessment,Privacy Rank
0,DP-CTGAN,3,4.536983e-13,1.071969e-12,100.000000,100.000000,True,FORMAL DP + EMPIRICAL RISK ASSESSMENT,1
1,TVAE,3,1.357252e+00,1.767395e+00,98.642748,98.232605,False,EMPIRICAL RISK ASSESSMENT ONLY,2
2,CTGAN,3,1.480985e+00,1.796145e+00,98.519015,98.203855,False,EMPIRICAL RISK ASSESSMENT ONLY,3
3,SPP-GAN,3,2.499388e+00,4.015362e+00,97.500612,95.984638,False,EMPIRICAL RISK ASSESSMENT ONLY,4

====================================================================================================
PART K10 — PRIVACY METHOD RANKING COMPLETED
====================================================================================================

In [157]:
# ==============================================================================
# PART K11 — FINAL PRIVACY VERIFICATION
# ==============================================================================

print("=" * 100)
print("PART K11 — FINAL PRIVACY VERIFICATION")
print("=" * 100)

total_combinations = (
    len(SYNTHETIC_METHODS)
    * len(SYNTHETIC_DATASET_NAMES)
)

evaluated_combinations = (
    PRIVACY_RISK_SUMMARY_DF[
        PRIVACY_RISK_SUMMARY_DF[
            "Overall Empirical Privacy Risk (%)"
        ]
        .notna()
    ]
    .shape[0]
)

formal_dp_combinations = (
    PRIVACY_RISK_SUMMARY_DF[
        PRIVACY_RISK_SUMMARY_DF[
            "Formal DP Guarantee"
        ]
        == True
    ]
    .shape[0]
)

exact_disclosure_combinations = (
    K3_DUPLICATE_DISCLOSURE_DF[
        pd.to_numeric(
            K3_DUPLICATE_DISCLOSURE_DF[
                "Exact Match Rate (%)"
            ],
            errors="coerce"
        )
        > 0
    ]
    .shape[0]
)

high_similarity_combinations = (
    K4_NEAREST_NEIGHBOR_DF[
        pd.to_numeric(
            K4_NEAREST_NEIGHBOR_DF[
                "High Similarity Rate (%)"
            ],
            errors="coerce"
        )
        > 5
    ]
    .shape[0]
)

evaluation_rate = (
    evaluated_combinations
    / total_combinations
    * 100
    if total_combinations > 0
    else 0.0
)

print()
print("PRIVACY EVALUATION VERIFICATION")
print("-" * 100)
print(
    f"Total Method–Dataset Combinations : "
    f"{total_combinations}"
)
print(
    f"Empirically Evaluated             : "
    f"{evaluated_combinations}"
)
print(
    f"Privacy Evaluation Rate            : "
    f"{evaluation_rate:.2f}%"
)
print(
    f"Formal DP Combinations              : "
    f"{formal_dp_combinations}"
)
print(
    f"Exact Disclosure Combinations      : "
    f"{exact_disclosure_combinations}"
)
print(
    f"High Similarity Combinations       : "
    f"{high_similarity_combinations}"
)

K11_PRIVACY_VERIFICATION = {

    "Total Method-Dataset Combinations":
        total_combinations,

    "Empirically Evaluated":
        evaluated_combinations,

    "Privacy Evaluation Rate (%)":
        evaluation_rate,

    "Formal DP Combinations":
        formal_dp_combinations,

    "Exact Disclosure Combinations":
        exact_disclosure_combinations,

    "High Similarity Combinations":
        high_similarity_combinations,

    "DP Epsilon":
        K_PRIVACY_EPSILON,

    "DP Delta":
        K_PRIVACY_DELTA
}

print()
print("Verification Status:")

if evaluation_rate == 100.0:
    print("✓ All method–dataset combinations were evaluated.")
else:
    print(
        "⚠ Some method–dataset combinations were not "
        "empirically evaluated."
    )

if formal_dp_combinations > 0:
    print(
        "✓ Formal differential-privacy configuration "
        "identified for DP-CTGAN."
    )
else:
    print(
        "⚠ Formal differential-privacy configuration "
        "could not be verified."
    )

print()
print("=" * 100)
print("PART K11 — FINAL PRIVACY VERIFICATION COMPLETED")
print("=" * 100)

====================================================================================================
PART K11 — FINAL PRIVACY VERIFICATION
====================================================================================================

PRIVACY EVALUATION VERIFICATION
----------------------------------------------------------------------------------------------------
Total Method–Dataset Combinations : 12
Empirically Evaluated             : 12
Privacy Evaluation Rate            : 100.00%
Formal DP Combinations              : 3
Exact Disclosure Combinations      : 0
High Similarity Combinations       : 0

Verification Status:
✓ All method–dataset combinations were evaluated.
✓ Formal differential-privacy configuration identified for DP-CTGAN.

====================================================================================================
PART K11 — FINAL PRIVACY VERIFICATION COMPLETED
====================================================================================================

In [158]:
# ==============================================================================
# PART K12 — SAVE PRIVACY REPORTS
# ==============================================================================

print("=" * 100)
print("PART K12 — SAVE PRIVACY REPORTS")
print("=" * 100)

# ------------------------------------------------------------------------------
# OUTPUT DIRECTORY
# ------------------------------------------------------------------------------

if "SPP_GAN_RESULTS_DIRECTORY" in globals():

    K_PRIVACY_OUTPUT_DIRECTORY = pathlib.Path(
        SPP_GAN_RESULTS_DIRECTORY
    ) / "privacy"

elif "SPP_GAN_PROJECT_ROOT" in globals():

    K_PRIVACY_OUTPUT_DIRECTORY = pathlib.Path(
        SPP_GAN_PROJECT_ROOT
    ) / "evaluation" / "privacy"

else:

    K_PRIVACY_OUTPUT_DIRECTORY = pathlib.Path(
        "/content/drive/MyDrive/SPP_GAN_Project/evaluation/privacy"
    )

K_PRIVACY_OUTPUT_DIRECTORY.mkdir(
    parents=True,
    exist_ok=True
)

# ------------------------------------------------------------------------------
# SAVE DATAFRAMES
# ------------------------------------------------------------------------------

REPORTS_TO_SAVE = {

    "k3_exact_duplicate_disclosure.csv":
        K3_DUPLICATE_DISCLOSURE_DF,

    "k4_nearest_neighbor_disclosure.csv":
        K4_NEAREST_NEIGHBOR_DF,

    "k5_attribute_disclosure.csv":
        K5_ATTRIBUTE_DISCLOSURE_DF,

    "k6_kanonymity_exposure.csv":
        K6_KANONYMITY_DF,

    "k7_dp_accounting.csv":
        DP_ACCOUNTING_DF,

    "k8_privacy_risk_summary.csv":
        PRIVACY_RISK_SUMMARY_DF,

    "k9_privacy_method_summary.csv":
        PRIVACY_METHOD_SUMMARY_DF,

    "k10_privacy_ranking.csv":
        PRIVACY_RANKING_DF
}

for filename, dataframe in REPORTS_TO_SAVE.items():

    output_path = (
        K_PRIVACY_OUTPUT_DIRECTORY
        / filename
    )

    dataframe.to_csv(
        output_path,
        index=False
    )

    print(
        f"✓ Saved: {output_path}"
    )

# ------------------------------------------------------------------------------
# FINAL VERIFICATION JSON
# ------------------------------------------------------------------------------

verification_path = (
    K_PRIVACY_OUTPUT_DIRECTORY
    / "k11_privacy_verification.json"
)

with open(
    verification_path,
    "w",
    encoding="utf-8"
) as file:

    json.dump(
        K11_PRIVACY_VERIFICATION,
        file,
        indent=4,
        default=str
    )

print(
    f"✓ Saved: {verification_path}"
)

print()
print("-" * 100)
print("PRIVACY REPORT DIRECTORY")
print("-" * 100)
print(
    K_PRIVACY_OUTPUT_DIRECTORY
)

print()
print("=" * 100)
print("PART K12 — PRIVACY REPORTS SAVED SUCCESSFULLY")
print("=" * 100)

====================================================================================================
PART K12 — SAVE PRIVACY REPORTS
====================================================================================================
✓ Saved: /content/drive/MyDrive/SPP_GAN_Project/evaluation/privacy/k3_exact_duplicate_disclosure.csv
✓ Saved: /content/drive/MyDrive/SPP_GAN_Project/evaluation/privacy/k4_nearest_neighbor_disclosure.csv
✓ Saved: /content/drive/MyDrive/SPP_GAN_Project/evaluation/privacy/k5_attribute_disclosure.csv
✓ Saved: /content/drive/MyDrive/SPP_GAN_Project/evaluation/privacy/k6_kanonymity_exposure.csv
✓ Saved: /content/drive/MyDrive/SPP_GAN_Project/evaluation/privacy/k7_dp_accounting.csv
✓ Saved: /content/drive/MyDrive/SPP_GAN_Project/evaluation/privacy/k8_privacy_risk_summary.csv
✓ Saved: /content/drive/MyDrive/SPP_GAN_Project/evaluation/privacy/k9_privacy_method_summary.csv
✓ Saved: /content/drive/MyDrive/SPP_GAN_Project/evaluation/privacy/k10_privacy_ranking.csv
✓ Saved: /content/drive/MyDrive/SPP_GAN_Project/evaluation/privacy/k11_privacy_verification.json

----------------------------------------------------------------------------------------------------
PRIVACY REPORT DIRECTORY
----------------------------------------------------------------------------------------------------
/content/drive/MyDrive/SPP_GAN_Project/evaluation/privacy

====================================================================================================
PART K12 — PRIVACY REPORTS SAVED SUCCESSFULLY
====================================================================================================

In [ ]:
# =============================================================================
# Notebook 08 : Comparative Evaluation
# Section 8.10.4 : Attribute Disclosure Risk
# =============================================================================

print("="*80)
print("SECTION 8.10.4 : ATTRIBUTE DISCLOSURE RISK")
print("="*80)

from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score
)

attribute_results = []

# -----------------------------------------------------------------------------
# Attribute Disclosure Evaluation
# -----------------------------------------------------------------------------

for dataset in DATASETS:

    print(f"\nDataset : {dataset}")

    real_train = original_datasets[dataset]["train"].copy()

    real_test = original_datasets[dataset]["test"].copy()

    # -------------------------------------------------------------------------
    # Sensitive Attribute
    # -------------------------------------------------------------------------

    sensitive_col = real_train.columns[-1]

    feature_cols = [

        c for c in real_train.columns

        if c != sensitive_col

    ]

    x_test = real_test[feature_cols]

    y_test = real_test[sensitive_col]

    for generator in MODELS:

        synthetic = synthetic_datasets[dataset][generator].copy()

        x_train = synthetic[feature_cols]

        y_train = synthetic[sensitive_col]

        # ---------------------------------------------------------------------
        # Train Attack Model
        # ---------------------------------------------------------------------

        attack_model = RandomForestClassifier(

            n_estimators=200,

            random_state=RANDOM_STATE,

            n_jobs=-1

        )

        attack_model.fit(

            x_train,

            y_train

        )

        y_pred = attack_model.predict(

            x_test

        )

        acc = accuracy_score(

            y_test,

            y_pred

        )

        pre = precision_score(

            y_test,

            y_pred,

            average="weighted",

            zero_division=0

        )

        rec = recall_score(

            y_test,

            y_pred,

            average="weighted",

            zero_division=0

        )

        f1 = f1_score(

            y_test,

            y_pred,

            average="weighted",

            zero_division=0

        )

        disclosure_rate = acc

        attribute_results.append({

            "Dataset": dataset,

            "Synthetic Model": generator,

            "Disclosure Accuracy": acc,

            "Disclosure Precision": pre,

            "Disclosure Recall": rec,

            "Disclosure F1": f1,

            "Disclosure Rate": disclosure_rate

        })

# =============================================================================
# Summary Tables
# =============================================================================

attribute_results = pd.DataFrame(attribute_results)

print("\nAttribute Disclosure Results")

display(

    attribute_results.round(4)

)

# -----------------------------------------------------------------------------
# Generator Comparison
# -----------------------------------------------------------------------------

attribute_summary = (

    attribute_results

    .groupby(

        "Synthetic Model"

    )[

        [

            "Disclosure Accuracy",

            "Disclosure Precision",

            "Disclosure Recall",

            "Disclosure F1",

            "Disclosure Rate"

        ]

    ]

    .mean()

    .sort_values(

        "Disclosure Rate"

    )

    .reset_index()

)

print("\nGenerator Comparison")

display(

    attribute_summary.round(4)

)

# -----------------------------------------------------------------------------
# Dataset-wise Comparison
# -----------------------------------------------------------------------------

dataset_summary = (

    attribute_results

    .pivot_table(

        index="Dataset",

        columns="Synthetic Model",

        values="Disclosure Rate"

    )

)

print("\nDataset-wise Disclosure Rate")

display(

    dataset_summary.round(4)

)

print("\n✓ Attribute Disclosure Risk Evaluation Completed")

In [159]:
# ==============================================================================
# PART L1 — DISCLOSURE / PRIVACY RISK CONFIGURATION
# ==============================================================================

print("=" * 100)
print("PART L1 — DISCLOSURE / PRIVACY RISK CONFIGURATION")
print("=" * 100)

import os
import json
import warnings
import numpy as np
import pandas as pd

from sklearn.preprocessing import OrdinalEncoder, StandardScaler
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.neighbors import NearestNeighbors

warnings.filterwarnings("ignore")

# ------------------------------------------------------------------------------
# REQUIRED PROJECT OBJECTS
# ------------------------------------------------------------------------------

if "SYNTHETIC_METHODS" not in globals():
    SYNTHETIC_METHODS = [
        "CTGAN",
        "TVAE",
        "DP-CTGAN",
        "SPP-GAN"
    ]

if "SYNTHETIC_DATASET_NAMES" not in globals():
    SYNTHETIC_DATASET_NAMES = [
        "adult_income",
        "bank_marketing",
        "diabetes_130us"
    ]

if "SYNTHETIC_DATASETS" not in globals():
    raise NameError(
        "SYNTHETIC_DATASETS is not defined. "
        "Run Section D — Synthetic Data Loading first."
    )

if "REAL_DATASETS" not in globals():
    raise NameError(
        "REAL_DATASETS is not defined. "
        "Load the reference datasets before running Part L."
    )

# ------------------------------------------------------------------------------
# PRIVACY-RISK PARAMETERS
# ------------------------------------------------------------------------------

L_MAX_RECORDS = 10000

# Number of nearest real records examined for each synthetic record.
L_NEIGHBORS = 1

# Number of rows sampled when datasets are very large.
L_RANDOM_STATE = 42

# Standardized nearest-neighbor distance below this threshold is
# considered a high-similarity candidate.
L_HIGH_SIMILARITY_THRESHOLD = 0.10

# Distance below this threshold is considered an extremely close match.
L_EXTREME_SIMILARITY_THRESHOLD = 0.05

# Quasi-identifiers used for attribute disclosure analysis.
#
# These are intentionally conservative defaults.
# Update them if your methodology defines a specific QI set.
#
# The code automatically uses only columns that actually exist.
L_QUASI_IDENTIFIER_CANDIDATES = {

    "adult_income": [
        "age",
        "workclass",
        "education",
        "marital-status",
        "occupation",
        "relationship",
        "race",
        "sex",
        "hours-per-week",
        "native-country"
    ],

    "bank_marketing": [
        "age",
        "job",
        "marital",
        "education",
        "default",
        "housing",
        "loan",
        "contact",
        "month",
        "day_of_week",
        "campaign",
        "pdays",
        "previous"
    ],

    "diabetes_130us": [
        "race",
        "gender",
        "age",
        "admission_type_id",
        "discharge_disposition_id",
        "admission_source_id",
        "time_in_hospital",
        "medical_specialty",
        "number_diagnoses"
    ]
}

# Candidate sensitive attributes.
# The code will only use a column if it exists.
L_SENSITIVE_ATTRIBUTE_CANDIDATES = {

    "adult_income": [
        "income",
        "class",
        "target"
    ],

    "bank_marketing": [
        "y",
        "deposit",
        "target"
    ],

    "diabetes_130us": [
        "readmitted",
        "target"
    ]
}

print("✓ Disclosure-risk configuration initialized")
print(f"✓ Methods       : {SYNTHETIC_METHODS}")
print(f"✓ Datasets      : {SYNTHETIC_DATASET_NAMES}")
print(f"✓ Random State  : {L_RANDOM_STATE}")
print(f"✓ Max Records   : {L_MAX_RECORDS}")
print(f"✓ NN Neighbors  : {L_NEIGHBORS}")

print("\n" + "=" * 100)
print("PART L1 — DISCLOSURE / PRIVACY RISK CONFIGURATION COMPLETED")
print("=" * 100)

====================================================================================================
PART L1 — DISCLOSURE / PRIVACY RISK CONFIGURATION
====================================================================================================
✓ Disclosure-risk configuration initialized
✓ Methods       : ['CTGAN', 'TVAE', 'DP-CTGAN', 'SPP-GAN']
✓ Datasets      : ['adult_income', 'bank_marketing', 'diabetes_130us']
✓ Random State  : 42
✓ Max Records   : 10000
✓ NN Neighbors  : 1

====================================================================================================
PART L1 — DISCLOSURE / PRIVACY RISK CONFIGURATION COMPLETED
====================================================================================================

In [160]:
# ==============================================================================
# PART L2 — PRIVACY-RISK HELPER FUNCTIONS
# ==============================================================================

print("=" * 100)
print("PART L2 — PRIVACY-RISK HELPER FUNCTIONS")
print("=" * 100)

def _safe_copy_dataframe(df):
    """Return a defensive dataframe copy."""
    if df is None:
        return None

    if not isinstance(df, pd.DataFrame):
        return None

    return df.copy()


def _sample_dataframe(df, max_records=L_MAX_RECORDS, random_state=L_RANDOM_STATE):
    """Limit computation while preserving reproducibility."""

    if df is None or df.empty:
        return df

    if len(df) <= max_records:
        return df.copy()

    return df.sample(
        n=max_records,
        random_state=random_state
    ).copy()


def _normalize_scalar(value):
    """Normalize values for robust exact-row comparison."""

    if pd.isna(value):
        return "<NA>"

    if isinstance(value, (np.integer, int)):
        return str(int(value))

    if isinstance(value, (np.floating, float)):
        if np.isnan(value):
            return "<NA>"

        return f"{float(value):.12g}"

    return str(value).strip()


def _row_signature(row, columns):
    """Create deterministic row signature."""

    return tuple(
        _normalize_scalar(row[column])
        for column in columns
    )


def _prepare_common_columns(real_df, synthetic_df):
    """Return common columns preserving real-data column order."""

    if real_df is None or synthetic_df is None:
        return []

    return [
        column
        for column in real_df.columns
        if column in synthetic_df.columns
    ]


def _detect_column_types(df, columns):
    """Detect numerical and categorical columns."""

    numerical_columns = []
    categorical_columns = []

    for column in columns:

        if pd.api.types.is_numeric_dtype(df[column]):
            numerical_columns.append(column)

        else:
            categorical_columns.append(column)

    return numerical_columns, categorical_columns


def _build_encoded_matrix(real_df, synthetic_df, columns):
    """
    Build a common numerical representation for real and synthetic records.

    Numerical columns:
        median imputation + standardization

    Categorical columns:
        most-frequent imputation + ordinal encoding
    """

    if not columns:
        return None, None

    combined = pd.concat(
        [
            real_df[columns],
            synthetic_df[columns]
        ],
        axis=0,
        ignore_index=True
    )

    numerical_columns, categorical_columns = _detect_column_types(
        combined,
        columns
    )

    transformers = []

    if numerical_columns:
        numerical_pipeline = Pipeline(
            steps=[
                (
                    "imputer",
                    __import__("sklearn").impute.SimpleImputer(
                        strategy="median"
                    )
                ),
                (
                    "scaler",
                    StandardScaler()
                )
            ]
        )

        transformers.append(
            (
                "num",
                numerical_pipeline,
                numerical_columns
            )
        )

    if categorical_columns:
        categorical_pipeline = Pipeline(
            steps=[
                (
                    "imputer",
                    __import__("sklearn").impute.SimpleImputer(
                        strategy="most_frequent"
                    )
                ),
                (
                    "encoder",
                    OrdinalEncoder(
                        handle_unknown="use_encoded_value",
                        unknown_value=-1
                    )
                )
            ]
        )

        transformers.append(
            (
                "cat",
                categorical_pipeline,
                categorical_columns
            )
        )

    if not transformers:
        return None, None

    preprocessor = ColumnTransformer(
        transformers=transformers,
        remainder="drop"
    )

    real_matrix = preprocessor.fit_transform(
        real_df[columns]
    )

    synthetic_matrix = preprocessor.transform(
        synthetic_df[columns]
    )

    real_matrix = np.asarray(
        real_matrix,
        dtype=np.float64
    )

    synthetic_matrix = np.asarray(
        synthetic_matrix,
        dtype=np.float64
    )

    real_matrix = np.nan_to_num(
        real_matrix,
        nan=0.0,
        posinf=0.0,
        neginf=0.0
    )

    synthetic_matrix = np.nan_to_num(
        synthetic_matrix,
        nan=0.0,
        posinf=0.0,
        neginf=0.0
    )

    return real_matrix, synthetic_matrix


def _find_sensitive_column(dataset, real_df):
    """Find the first available sensitive/target column."""

    candidates = L_SENSITIVE_ATTRIBUTE_CANDIDATES.get(
        dataset,
        []
    )

    for column in candidates:

        if column in real_df.columns:
            return column

    return None


def _find_quasi_identifiers(dataset, real_df, synthetic_df):
    """Find available QI columns."""

    candidates = L_QUASI_IDENTIFIER_CANDIDATES.get(
        dataset,
        []
    )

    return [
        column
        for column in candidates
        if (
            column in real_df.columns
            and column in synthetic_df.columns
        )
    ]


print("✓ Helper functions created")

print("\n" + "=" * 100)
print("PART L2 — PRIVACY-RISK HELPER FUNCTIONS COMPLETED")
print("=" * 100)

====================================================================================================
PART L2 — PRIVACY-RISK HELPER FUNCTIONS
====================================================================================================
✓ Helper functions created

====================================================================================================
PART L2 — PRIVACY-RISK HELPER FUNCTIONS COMPLETED
====================================================================================================

In [161]:
# ==============================================================================
# PART L3 — EXACT RECORD DISCLOSURE RISK
# ==============================================================================

print("=" * 100)
print("PART L3 — EXACT RECORD DISCLOSURE RISK")
print("=" * 100)

L3_RESULTS = []

for method in SYNTHETIC_METHODS:

    for dataset in SYNTHETIC_DATASET_NAMES:

        real_df = _safe_copy_dataframe(
            REAL_DATASETS.get(dataset)
        )

        synthetic_df = _safe_copy_dataframe(
            SYNTHETIC_DATASETS
            .get(method, {})
            .get(dataset)
        )

        if real_df is None or synthetic_df is None:
            L3_RESULTS.append({
                "Method": method,
                "Dataset": dataset,
                "Real Loaded": real_df is not None,
                "Synthetic Loaded": synthetic_df is not None,
                "Comparable Columns": 0,
                "Synthetic Records": 0 if synthetic_df is None else len(synthetic_df),
                "Exact Matches": np.nan,
                "Exact Match Rate (%)": np.nan,
                "Disclosure Risk": "NOT EVALUATED"
            })

            continue

        common_columns = _prepare_common_columns(
            real_df,
            synthetic_df
        )

        if not common_columns:

            L3_RESULTS.append({
                "Method": method,
                "Dataset": dataset,
                "Real Loaded": True,
                "Synthetic Loaded": True,
                "Comparable Columns": 0,
                "Synthetic Records": len(synthetic_df),
                "Exact Matches": np.nan,
                "Exact Match Rate (%)": np.nan,
                "Disclosure Risk": "NO COMMON COLUMNS"
            })

            continue

        real_sample = _sample_dataframe(
            real_df[common_columns]
        )

        synthetic_sample = _sample_dataframe(
            synthetic_df[common_columns]
        )

        real_signatures = {
            _row_signature(
                row,
                common_columns
            )
            for _, row in real_sample.iterrows()
        }

        synthetic_signatures = [
            _row_signature(
                row,
                common_columns
            )
            for _, row in synthetic_sample.iterrows()
        ]

        exact_matches = sum(
            signature in real_signatures
            for signature in synthetic_signatures
        )

        synthetic_count = len(synthetic_signatures)

        exact_match_rate = (
            exact_matches / synthetic_count * 100
            if synthetic_count > 0
            else np.nan
        )

        if exact_matches == 0:
            risk_status = "LOW"

        elif exact_match_rate < 0.1:
            risk_status = "MODERATE"

        else:
            risk_status = "HIGH"

        L3_RESULTS.append({

            "Method": method,
            "Dataset": dataset,
            "Real Loaded": True,
            "Synthetic Loaded": True,
            "Comparable Columns": len(common_columns),
            "Synthetic Records": synthetic_count,
            "Exact Matches": exact_matches,
            "Exact Match Rate (%)": exact_match_rate,
            "Disclosure Risk": risk_status
        })

L3_EXACT_DISCLOSURE_DF = pd.DataFrame(
    L3_RESULTS
)

display(
    L3_EXACT_DISCLOSURE_DF
)

print("\n" + "-" * 100)
print("L3 SUMMARY")
print("-" * 100)

print(
    f"Total Method–Dataset Combinations : "
    f"{len(L3_EXACT_DISCLOSURE_DF)}"
)

print(
    f"Total Exact Matches               : "
    f"{pd.to_numeric(L3_EXACT_DISCLOSURE_DF['Exact Matches'], errors='coerce').sum(skipna=True):.0f}"
)

print("=" * 100)
print("PART L3 — EXACT RECORD DISCLOSURE RISK COMPLETED")
print("=" * 100)

====================================================================================================
PART L3 — EXACT RECORD DISCLOSURE RISK
====================================================================================================

,Method,Dataset,Real Loaded,Synthetic Loaded,Comparable Columns,Synthetic Records,Exact Matches,Exact Match Rate (%),Disclosure Risk
0,CTGAN,adult_income,True,True,15,10000,0,0.0,LOW
1,CTGAN,bank_marketing,True,True,17,10000,0,0.0,LOW
2,CTGAN,diabetes_130us,True,True,48,10000,0,0.0,LOW
3,TVAE,adult_income,True,True,15,10000,0,0.0,LOW
4,TVAE,bank_marketing,True,True,17,10000,0,0.0,LOW
5,TVAE,diabetes_130us,True,True,48,10000,0,0.0,LOW
6,DP-CTGAN,adult_income,True,True,15,10000,0,0.0,LOW
7,DP-CTGAN,bank_marketing,True,True,17,10000,0,0.0,LOW
8,DP-CTGAN,diabetes_130us,True,True,48,10000,0,0.0,LOW
9,SPP-GAN,adult_income,True,True,15,10000,0,0.0,LOW
10,SPP-GAN,bank_marketing,True,True,17,10000,0,0.0,LOW
11,SPP-GAN,diabetes_130us,True,True,48,10000,0,0.0,LOW

----------------------------------------------------------------------------------------------------
L3 SUMMARY
----------------------------------------------------------------------------------------------------
Total Method–Dataset Combinations : 12
Total Exact Matches               : 0
====================================================================================================
PART L3 — EXACT RECORD DISCLOSURE RISK COMPLETED
====================================================================================================

In [162]:
# ==============================================================================
# PART L4 — NEAREST-NEIGHBOR DISCLOSURE RISK
# ==============================================================================

print("=" * 100)
print("PART L4 — NEAREST-NEIGHBOR DISCLOSURE RISK")
print("=" * 100)

L4_RESULTS = []

for method in SYNTHETIC_METHODS:

    for dataset in SYNTHETIC_DATASET_NAMES:

        real_df = _safe_copy_dataframe(
            REAL_DATASETS.get(dataset)
        )

        synthetic_df = _safe_copy_dataframe(
            SYNTHETIC_DATASETS
            .get(method, {})
            .get(dataset)
        )

        if real_df is None or synthetic_df is None:

            L4_RESULTS.append({
                "Method": method,
                "Dataset": dataset,
                "Real Loaded": real_df is not None,
                "Synthetic Loaded": synthetic_df is not None,
                "Mean NN Distance": np.nan,
                "Median NN Distance": np.nan,
                "Minimum NN Distance": np.nan,
                "High Similarity Rate (%)": np.nan,
                "Extreme Similarity Rate (%)": np.nan,
                "Disclosure Risk": "NOT EVALUATED"
            })

            continue

        common_columns = _prepare_common_columns(
            real_df,
            synthetic_df
        )

        if not common_columns:

            L4_RESULTS.append({
                "Method": method,
                "Dataset": dataset,
                "Real Loaded": True,
                "Synthetic Loaded": True,
                "Mean NN Distance": np.nan,
                "Median NN Distance": np.nan,
                "Minimum NN Distance": np.nan,
                "High Similarity Rate (%)": np.nan,
                "Extreme Similarity Rate (%)": np.nan,
                "Disclosure Risk": "NO COMMON COLUMNS"
            })

            continue

        real_sample = _sample_dataframe(
            real_df[common_columns]
        )

        synthetic_sample = _sample_dataframe(
            synthetic_df[common_columns]
        )

        real_matrix, synthetic_matrix = _build_encoded_matrix(
            real_sample,
            synthetic_sample,
            common_columns
        )

        if (
            real_matrix is None
            or synthetic_matrix is None
            or len(real_matrix) == 0
            or len(synthetic_matrix) == 0
        ):

            L4_RESULTS.append({
                "Method": method,
                "Dataset": dataset,
                "Real Loaded": True,
                "Synthetic Loaded": True,
                "Mean NN Distance": np.nan,
                "Median NN Distance": np.nan,
                "Minimum NN Distance": np.nan,
                "High Similarity Rate (%)": np.nan,
                "Extreme Similarity Rate (%)": np.nan,
                "Disclosure Risk": "NOT EVALUATED"
            })

            continue

        n_neighbors = min(
            L_NEIGHBORS,
            len(real_matrix)
        )

        nn_model = NearestNeighbors(
            n_neighbors=n_neighbors,
            metric="euclidean"
        )

        nn_model.fit(real_matrix)

        distances, _ = nn_model.kneighbors(
            synthetic_matrix
        )

        nearest_distances = distances[:, 0]

        mean_distance = float(
            np.mean(nearest_distances)
        )

        median_distance = float(
            np.median(nearest_distances)
        )

        minimum_distance = float(
            np.min(nearest_distances)
        )

        high_similarity_rate = (
            np.mean(
                nearest_distances
                <= L_HIGH_SIMILARITY_THRESHOLD
            ) * 100
        )

        extreme_similarity_rate = (
            np.mean(
                nearest_distances
                <= L_EXTREME_SIMILARITY_THRESHOLD
            ) * 100
        )

        if extreme_similarity_rate > 1:
            risk_status = "HIGH"

        elif high_similarity_rate > 5:
            risk_status = "MODERATE"

        else:
            risk_status = "LOW"

        L4_RESULTS.append({

            "Method": method,
            "Dataset": dataset,
            "Real Loaded": True,
            "Synthetic Loaded": True,
            "Mean NN Distance": mean_distance,
            "Median NN Distance": median_distance,
            "Minimum NN Distance": minimum_distance,
            "High Similarity Rate (%)": high_similarity_rate,
            "Extreme Similarity Rate (%)": extreme_similarity_rate,
            "Disclosure Risk": risk_status
        })

L4_NEAREST_NEIGHBOR_DF = pd.DataFrame(
    L4_RESULTS
)

display(
    L4_NEAREST_NEIGHBOR_DF
)

print("\n" + "-" * 100)
print("L4 SUMMARY")
print("-" * 100)

print(
    f"Total Method–Dataset Combinations : "
    f"{len(L4_NEAREST_NEIGHBOR_DF)}"
)

print("=" * 100)
print("PART L4 — NEAREST-NEIGHBOR DISCLOSURE RISK COMPLETED")
print("=" * 100)

====================================================================================================
PART L4 — NEAREST-NEIGHBOR DISCLOSURE RISK
====================================================================================================

,Method,Dataset,Real Loaded,Synthetic Loaded,Mean NN Distance,Median NN Distance,Minimum NN Distance,High Similarity Rate (%),Extreme Similarity Rate (%),Disclosure Risk
0,CTGAN,adult_income,True,True,2.712083,2.706458,0.597146,0.0,0.0,LOW
1,CTGAN,bank_marketing,True,True,10.799142,9.521289,8.747922,0.0,0.0,LOW
2,CTGAN,diabetes_130us,True,True,12.137493,10.065499,3.399027,0.0,0.0,LOW
3,TVAE,adult_income,True,True,2.492361,2.522330,0.634356,0.0,0.0,LOW
4,TVAE,bank_marketing,True,True,10.508216,9.419805,8.748662,0.0,0.0,LOW
5,TVAE,diabetes_130us,True,True,9.103049,7.530243,3.510478,0.0,0.0,LOW
6,DP-CTGAN,adult_income,True,True,14.143771,14.142382,13.686026,0.0,0.0,LOW
7,DP-CTGAN,bank_marketing,True,True,4.379666,4.369347,2.833160,0.0,0.0,LOW
8,DP-CTGAN,diabetes_130us,True,True,151.041871,151.040111,150.959174,0.0,0.0,LOW
9,SPP-GAN,adult_income,True,True,3.324080,3.206671,0.349140,0.0,0.0,LOW
10,SPP-GAN,bank_marketing,True,True,2.285773,2.217732,0.470399,0.0,0.0,LOW
11,SPP-GAN,diabetes_130us,True,True,4.131466,3.997697,1.273540,0.0,0.0,LOW

----------------------------------------------------------------------------------------------------
L4 SUMMARY
----------------------------------------------------------------------------------------------------
Total Method–Dataset Combinations : 12
====================================================================================================
PART L4 — NEAREST-NEIGHBOR DISCLOSURE RISK COMPLETED
====================================================================================================

In [163]:
# ==============================================================================
# PART L5 — QUASI-IDENTIFIER AND SENSITIVE ATTRIBUTE VALIDATION
# ==============================================================================

print("=" * 100)
print("PART L5 — QUASI-IDENTIFIER AND SENSITIVE ATTRIBUTE VALIDATION")
print("=" * 100)

L5_RESULTS = []

for dataset in SYNTHETIC_DATASET_NAMES:

    real_df = REAL_DATASETS.get(dataset)

    if real_df is None:

        L5_RESULTS.append({
            "Dataset": dataset,
            "Reference Loaded": False,
            "QI Columns": [],
            "QI Count": 0,
            "Sensitive Attribute": None,
            "Sensitive Attribute Available": False,
            "Status": "REFERENCE NOT LOADED"
        })

        continue

    synthetic_candidates = []

    for method in SYNTHETIC_METHODS:

        synthetic_df = (
            SYNTHETIC_DATASETS
            .get(method, {})
            .get(dataset)
        )

        if synthetic_df is not None:
            synthetic_candidates.append(
                synthetic_df
            )

    if synthetic_candidates:

        common_synthetic_columns = set(
            synthetic_candidates[0].columns
        )

        for df in synthetic_candidates[1:]:
            common_synthetic_columns &= set(
                df.columns
            )

        reference_like_df = real_df[
            [
                column
                for column in real_df.columns
                if column in common_synthetic_columns
            ]
        ]

    else:

        reference_like_df = real_df

    qi_columns = _find_quasi_identifiers(
        dataset,
        real_df,
        reference_like_df
    )

    sensitive_column = _find_sensitive_column(
        dataset,
        real_df
    )

    L5_RESULTS.append({

        "Dataset": dataset,
        "Reference Loaded": True,
        "QI Columns": ", ".join(qi_columns),
        "QI Count": len(qi_columns),
        "Sensitive Attribute": sensitive_column,
        "Sensitive Attribute Available":
            sensitive_column is not None,
        "Status":
            "READY"
            if qi_columns and sensitive_column
            else "LIMITED"
    })

L5_QI_CONFIGURATION_DF = pd.DataFrame(
    L5_RESULTS
)

display(
    L5_QI_CONFIGURATION_DF
)

print("=" * 100)
print("PART L5 — QUASI-IDENTIFIER AND SENSITIVE ATTRIBUTE VALIDATION COMPLETED")
print("=" * 100)

====================================================================================================
PART L5 — QUASI-IDENTIFIER AND SENSITIVE ATTRIBUTE VALIDATION
====================================================================================================

,Dataset,Reference Loaded,QI Columns,QI Count,Sensitive Attribute,Sensitive Attribute Available,Status
0,adult_income,True,"age, workclass, education, occupation, relatio...",7,income,True,READY
1,bank_marketing,True,"age, job, marital, education, default, housing...",12,y,True,READY
2,diabetes_130us,True,"race, gender, age, admission_type_id, discharg...",9,readmitted,True,READY

====================================================================================================
PART L5 — QUASI-IDENTIFIER AND SENSITIVE ATTRIBUTE VALIDATION COMPLETED
====================================================================================================

In [164]:
# ==============================================================================
# PART L6 — ATTRIBUTE DISCLOSURE RISK
# ==============================================================================

print("=" * 100)
print("PART L6 — ATTRIBUTE DISCLOSURE RISK")
print("=" * 100)

L6_RESULTS = []

for method in SYNTHETIC_METHODS:

    for dataset in SYNTHETIC_DATASET_NAMES:

        real_df = _safe_copy_dataframe(
            REAL_DATASETS.get(dataset)
        )

        synthetic_df = _safe_copy_dataframe(
            SYNTHETIC_DATASETS
            .get(method, {})
            .get(dataset)
        )

        if real_df is None or synthetic_df is None:

            L6_RESULTS.append({
                "Method": method,
                "Dataset": dataset,
                "QI Count": 0,
                "Sensitive Attribute": None,
                "Evaluated Records": 0,
                "Attribute Disclosure Matches": np.nan,
                "Attribute Disclosure Rate (%)": np.nan,
                "Attribute Disclosure Risk": "NOT EVALUATED"
            })

            continue

        qi_columns = _find_quasi_identifiers(
            dataset,
            real_df,
            synthetic_df
        )

        sensitive_column = _find_sensitive_column(
            dataset,
            real_df
        )

        if (
            not qi_columns
            or sensitive_column is None
            or sensitive_column not in synthetic_df.columns
        ):

            L6_RESULTS.append({
                "Method": method,
                "Dataset": dataset,
                "QI Count": len(qi_columns),
                "Sensitive Attribute": sensitive_column,
                "Evaluated Records": 0,
                "Attribute Disclosure Matches": np.nan,
                "Attribute Disclosure Rate (%)": np.nan,
                "Attribute Disclosure Risk": "NOT EVALUATED"
            })

            continue

        real_work = _sample_dataframe(
            real_df[
                qi_columns + [sensitive_column]
            ]
        )

        synthetic_work = _sample_dataframe(
            synthetic_df[
                qi_columns + [sensitive_column]
            ]
        )

        # ----------------------------------------------------------------------
        # Create signatures based only on QIs.
        # ----------------------------------------------------------------------

        synthetic_groups = {}

        for _, row in synthetic_work.iterrows():

            signature = _row_signature(
                row,
                qi_columns
            )

            sensitive_value = _normalize_scalar(
                row[sensitive_column]
            )

            synthetic_groups.setdefault(
                signature,
                []
            ).append(
                sensitive_value
            )

        # ----------------------------------------------------------------------
        # Only evaluate QI patterns that occur in synthetic data.
        # ----------------------------------------------------------------------

        evaluated_records = 0
        disclosure_matches = 0

        for _, real_row in real_work.iterrows():

            signature = _row_signature(
                real_row,
                qi_columns
            )

            if signature not in synthetic_groups:
                continue

            synthetic_sensitive_values = (
                synthetic_groups[signature]
            )

            if not synthetic_sensitive_values:
                continue

            evaluated_records += 1

            real_sensitive_value = _normalize_scalar(
                real_row[sensitive_column]
            )

            # Majority sensitive value associated with this QI pattern.
            value_counts = pd.Series(
                synthetic_sensitive_values
            ).value_counts()

            inferred_value = value_counts.index[0]

            if inferred_value == real_sensitive_value:
                disclosure_matches += 1

        attribute_disclosure_rate = (
            disclosure_matches
            / evaluated_records
            * 100
            if evaluated_records > 0
            else np.nan
        )

        # A high rate means sensitive information may be easier to infer.
        if (
            pd.notna(attribute_disclosure_rate)
            and attribute_disclosure_rate >= 80
        ):
            risk_status = "HIGH"

        elif (
            pd.notna(attribute_disclosure_rate)
            and attribute_disclosure_rate >= 50
        ):
            risk_status = "MODERATE"

        elif pd.notna(attribute_disclosure_rate):
            risk_status = "LOW"

        else:
            risk_status = "NOT EVALUATED"

        L6_RESULTS.append({

            "Method": method,
            "Dataset": dataset,
            "QI Count": len(qi_columns),
            "Sensitive Attribute": sensitive_column,
            "Evaluated Records": evaluated_records,
            "Attribute Disclosure Matches":
                disclosure_matches,
            "Attribute Disclosure Rate (%)":
                attribute_disclosure_rate,
            "Attribute Disclosure Risk":
                risk_status
        })

L6_ATTRIBUTE_DISCLOSURE_DF = pd.DataFrame(
    L6_RESULTS
)

display(
    L6_ATTRIBUTE_DISCLOSURE_DF
)

print("\n" + "-" * 100)
print("L6 SUMMARY")
print("-" * 100)

print(
    f"Total Method–Dataset Combinations : "
    f"{len(L6_ATTRIBUTE_DISCLOSURE_DF)}"
)

print("=" * 100)
print("PART L6 — ATTRIBUTE DISCLOSURE RISK COMPLETED")
print("=" * 100)

====================================================================================================
PART L6 — ATTRIBUTE DISCLOSURE RISK
====================================================================================================

,Method,Dataset,QI Count,Sensitive Attribute,Evaluated Records,Attribute Disclosure Matches,Attribute Disclosure Rate (%),Attribute Disclosure Risk
0,CTGAN,adult_income,7,income,12,12,100.0,HIGH
1,CTGAN,bank_marketing,12,y,0,0,NaN,NOT EVALUATED
2,CTGAN,diabetes_130us,9,readmitted,0,0,NaN,NOT EVALUATED
3,TVAE,adult_income,7,income,3,3,100.0,HIGH
4,TVAE,bank_marketing,12,y,0,0,NaN,NOT EVALUATED
5,TVAE,diabetes_130us,9,readmitted,0,0,NaN,NOT EVALUATED
6,DP-CTGAN,adult_income,7,income,0,0,NaN,NOT EVALUATED
7,DP-CTGAN,bank_marketing,12,y,0,0,NaN,NOT EVALUATED
8,DP-CTGAN,diabetes_130us,9,readmitted,0,0,NaN,NOT EVALUATED
9,SPP-GAN,adult_income,7,income,0,0,NaN,NOT EVALUATED
10,SPP-GAN,bank_marketing,12,y,0,0,NaN,NOT EVALUATED
11,SPP-GAN,diabetes_130us,9,readmitted,0,0,NaN,NOT EVALUATED

----------------------------------------------------------------------------------------------------
L6 SUMMARY
----------------------------------------------------------------------------------------------------
Total Method–Dataset Combinations : 12
====================================================================================================
PART L6 — ATTRIBUTE DISCLOSURE RISK COMPLETED
====================================================================================================

In [165]:
# ==============================================================================
# PART L7 — SINGLING-OUT / CLOSEST-RECORD RISK
# ==============================================================================

print("=" * 100)
print("PART L7 — SINGLING-OUT / CLOSEST-RECORD RISK")
print("=" * 100)

L7_RESULTS = []

for method in SYNTHETIC_METHODS:

    for dataset in SYNTHETIC_DATASET_NAMES:

        real_df = _safe_copy_dataframe(
            REAL_DATASETS.get(dataset)
        )

        synthetic_df = _safe_copy_dataframe(
            SYNTHETIC_DATASETS
            .get(method, {})
            .get(dataset)
        )

        if real_df is None or synthetic_df is None:

            L7_RESULTS.append({
                "Method": method,
                "Dataset": dataset,
                "QI Count": 0,
                "Synthetic Records": 0,
                "Unique QI Patterns": np.nan,
                "Singling-Out Rate (%)": np.nan,
                "Risk Level": "NOT EVALUATED"
            })

            continue

        qi_columns = _find_quasi_identifiers(
            dataset,
            real_df,
            synthetic_df
        )

        if not qi_columns:

            L7_RESULTS.append({
                "Method": method,
                "Dataset": dataset,
                "QI Count": 0,
                "Synthetic Records": len(synthetic_df),
                "Unique QI Patterns": np.nan,
                "Singling-Out Rate (%)": np.nan,
                "Risk Level": "NOT EVALUATED"
            })

            continue

        synthetic_work = _sample_dataframe(
            synthetic_df[qi_columns]
        )

        signatures = [
            _row_signature(
                row,
                qi_columns
            )
            for _, row in synthetic_work.iterrows()
        ]

        if not signatures:

            singling_out_rate = np.nan
            unique_patterns = 0

        else:

            counts = pd.Series(signatures).value_counts()

            unique_patterns = int(
                (counts == 1).sum()
            )

            singling_out_rate = (
                unique_patterns
                / len(signatures)
                * 100
            )

        if (
            pd.notna(singling_out_rate)
            and singling_out_rate >= 80
        ):
            risk_level = "HIGH"

        elif (
            pd.notna(singling_out_rate)
            and singling_out_rate >= 50
        ):
            risk_level = "MODERATE"

        elif pd.notna(singling_out_rate):
            risk_level = "LOW"

        else:
            risk_level = "NOT EVALUATED"

        L7_RESULTS.append({

            "Method": method,
            "Dataset": dataset,
            "QI Count": len(qi_columns),
            "Synthetic Records": len(synthetic_work),
            "Unique QI Patterns": unique_patterns,
            "Singling-Out Rate (%)":
                singling_out_rate,
            "Risk Level":
                risk_level
        })

L7_SINGLING_OUT_DF = pd.DataFrame(
    L7_RESULTS
)

display(
    L7_SINGLING_OUT_DF
)

print("\n" + "=" * 100)
print("PART L7 — SINGLING-OUT / CLOSEST-RECORD RISK COMPLETED")
print("=" * 100)

====================================================================================================
PART L7 — SINGLING-OUT / CLOSEST-RECORD RISK
====================================================================================================

,Method,Dataset,QI Count,Synthetic Records,Unique QI Patterns,Singling-Out Rate (%),Risk Level
0,CTGAN,adult_income,7,10000,9895,98.95,HIGH
1,CTGAN,bank_marketing,12,10000,9986,99.86,HIGH
2,CTGAN,diabetes_130us,9,10000,10000,100.00,HIGH
3,TVAE,adult_income,7,10000,10000,100.00,HIGH
4,TVAE,bank_marketing,12,10000,10000,100.00,HIGH
5,TVAE,diabetes_130us,9,10000,10000,100.00,HIGH
6,DP-CTGAN,adult_income,7,10000,10000,100.00,HIGH
7,DP-CTGAN,bank_marketing,12,10000,10000,100.00,HIGH
8,DP-CTGAN,diabetes_130us,9,10000,10000,100.00,HIGH
9,SPP-GAN,adult_income,7,10000,10000,100.00,HIGH
10,SPP-GAN,bank_marketing,12,10000,10000,100.00,HIGH
11,SPP-GAN,diabetes_130us,9,10000,10000,100.00,HIGH

====================================================================================================
PART L7 — SINGLING-OUT / CLOSEST-RECORD RISK COMPLETED
====================================================================================================

In [166]:
# ==============================================================================
# PART L8 — OVERALL DISCLOSURE RISK SCORE
# ==============================================================================

print("=" * 100)
print("PART L8 — OVERALL DISCLOSURE RISK SCORE")
print("=" * 100)

L8_RESULTS = []

for method in SYNTHETIC_METHODS:

    for dataset in SYNTHETIC_DATASET_NAMES:

        exact_row = L3_EXACT_DISCLOSURE_DF[
            (
                L3_EXACT_DISCLOSURE_DF["Method"]
                == method
            )
            &
            (
                L3_EXACT_DISCLOSURE_DF["Dataset"]
                == dataset
            )
        ]

        nn_row = L4_NEAREST_NEIGHBOR_DF[
            (
                L4_NEAREST_NEIGHBOR_DF["Method"]
                == method
            )
            &
            (
                L4_NEAREST_NEIGHBOR_DF["Dataset"]
                == dataset
            )
        ]

        attr_row = L6_ATTRIBUTE_DISCLOSURE_DF[
            (
                L6_ATTRIBUTE_DISCLOSURE_DF["Method"]
                == method
            )
            &
            (
                L6_ATTRIBUTE_DISCLOSURE_DF["Dataset"]
                == dataset
            )
        ]

        single_row = L7_SINGLING_OUT_DF[
            (
                L7_SINGLING_OUT_DF["Method"]
                == method
            )
            &
            (
                L7_SINGLING_OUT_DF["Dataset"]
                == dataset
            )
        ]

        # ----------------------------------------------------------------------
        # Exact disclosure component
        # ----------------------------------------------------------------------

        exact_rate = np.nan

        if not exact_row.empty:
            exact_rate = pd.to_numeric(
                exact_row["Exact Match Rate (%)"],
                errors="coerce"
            ).iloc[0]

        # ----------------------------------------------------------------------
        # Nearest-neighbor component
        # ----------------------------------------------------------------------

        high_similarity_rate = np.nan

        if not nn_row.empty:
            high_similarity_rate = pd.to_numeric(
                nn_row["High Similarity Rate (%)"],
                errors="coerce"
            ).iloc[0]

        # ----------------------------------------------------------------------
        # Attribute disclosure component
        # ----------------------------------------------------------------------

        attribute_rate = np.nan

        if not attr_row.empty:
            attribute_rate = pd.to_numeric(
                attr_row["Attribute Disclosure Rate (%)"],
                errors="coerce"
            ).iloc[0]

        # ----------------------------------------------------------------------
        # Singling-out component
        # ----------------------------------------------------------------------

        singling_rate = np.nan

        if not single_row.empty:
            singling_rate = pd.to_numeric(
                single_row["Singling-Out Rate (%)"],
                errors="coerce"
            ).iloc[0]

        components = [
            exact_rate,
            high_similarity_rate,
            attribute_rate,
            singling_rate
        ]

        available_components = [
            value
            for value in components
            if pd.notna(value)
        ]

        if available_components:

            overall_risk = float(
                np.mean(
                    available_components
                )
            )

            privacy_score = max(
                0.0,
                100.0 - overall_risk
            )

        else:

            overall_risk = np.nan
            privacy_score = np.nan

        if pd.isna(overall_risk):

            risk_category = "NOT EVALUATED"

        elif overall_risk >= 50:

            risk_category = "HIGH"

        elif overall_risk >= 20:

            risk_category = "MODERATE"

        else:

            risk_category = "LOW"

        L8_RESULTS.append({

            "Method": method,
            "Dataset": dataset,
            "Exact Match Rate (%)":
                exact_rate,
            "High Similarity Rate (%)":
                high_similarity_rate,
            "Attribute Disclosure Rate (%)":
                attribute_rate,
            "Singling-Out Rate (%)":
                singling_rate,
            "Overall Disclosure Risk (%)":
                overall_risk,
            "Privacy Protection Score (%)":
                privacy_score,
            "Risk Category":
                risk_category
        })

L8_DISCLOSURE_RISK_DF = pd.DataFrame(
    L8_RESULTS
)

display(
    L8_DISCLOSURE_RISK_DF
)

print("\n" + "-" * 100)
print("L8 SUMMARY")
print("-" * 100)

print(
    f"Total Method–Dataset Combinations : "
    f"{len(L8_DISCLOSURE_RISK_DF)}"
)

print("=" * 100)
print("PART L8 — OVERALL DISCLOSURE RISK SCORE COMPLETED")
print("=" * 100)

====================================================================================================
PART L8 — OVERALL DISCLOSURE RISK SCORE
====================================================================================================

,Method,Dataset,Exact Match Rate (%),High Similarity Rate (%),Attribute Disclosure Rate (%),Singling-Out Rate (%),Overall Disclosure Risk (%),Privacy Protection Score (%),Risk Category
0,CTGAN,adult_income,0.0,0.0,100.0,98.95,49.737500,50.262500,MODERATE
1,CTGAN,bank_marketing,0.0,0.0,NaN,99.86,33.286667,66.713333,MODERATE
2,CTGAN,diabetes_130us,0.0,0.0,NaN,100.00,33.333333,66.666667,MODERATE
3,TVAE,adult_income,0.0,0.0,100.0,100.00,50.000000,50.000000,HIGH
4,TVAE,bank_marketing,0.0,0.0,NaN,100.00,33.333333,66.666667,MODERATE
5,TVAE,diabetes_130us,0.0,0.0,NaN,100.00,33.333333,66.666667,MODERATE
6,DP-CTGAN,adult_income,0.0,0.0,NaN,100.00,33.333333,66.666667,MODERATE
7,DP-CTGAN,bank_marketing,0.0,0.0,NaN,100.00,33.333333,66.666667,MODERATE
8,DP-CTGAN,diabetes_130us,0.0,0.0,NaN,100.00,33.333333,66.666667,MODERATE
9,SPP-GAN,adult_income,0.0,0.0,NaN,100.00,33.333333,66.666667,MODERATE
10,SPP-GAN,bank_marketing,0.0,0.0,NaN,100.00,33.333333,66.666667,MODERATE
11,SPP-GAN,diabetes_130us,0.0,0.0,NaN,100.00,33.333333,66.666667,MODERATE

----------------------------------------------------------------------------------------------------
L8 SUMMARY
----------------------------------------------------------------------------------------------------
Total Method–Dataset Combinations : 12
====================================================================================================
PART L8 — OVERALL DISCLOSURE RISK SCORE COMPLETED
====================================================================================================

In [167]:
# ==============================================================================
# PART L9 — METHOD-LEVEL PRIVACY RISK SUMMARY
# ==============================================================================

print("=" * 100)
print("PART L9 — METHOD-LEVEL PRIVACY RISK SUMMARY")
print("=" * 100)

L9_METHOD_RESULTS = []

for method in SYNTHETIC_METHODS:

    subset = L8_DISCLOSURE_RISK_DF[
        L8_DISCLOSURE_RISK_DF["Method"] == method
    ].copy()

    if subset.empty:

        continue

    numeric_columns = [
        "Exact Match Rate (%)",
        "High Similarity Rate (%)",
        "Attribute Disclosure Rate (%)",
        "Singling-Out Rate (%)",
        "Overall Disclosure Risk (%)",
        "Privacy Protection Score (%)"
    ]

    row = {
        "Method": method,
        "Datasets Evaluated": len(subset)
    }

    for column in numeric_columns:

        row[column] = pd.to_numeric(
            subset[column],
            errors="coerce"
        ).mean()

    valid_risk = subset[
        "Overall Disclosure Risk (%)"
    ].notna()

    row["Successful Evaluations"] = int(
        valid_risk.sum()
    )

    L9_METHOD_RESULTS.append(row)

L9_METHOD_PRIVACY_SUMMARY_DF = pd.DataFrame(
    L9_METHOD_RESULTS
)

display(
    L9_METHOD_PRIVACY_SUMMARY_DF
)

print("=" * 100)
print("PART L9 — METHOD-LEVEL PRIVACY RISK SUMMARY COMPLETED")
print("=" * 100)

====================================================================================================
PART L9 — METHOD-LEVEL PRIVACY RISK SUMMARY
====================================================================================================

,Method,Datasets Evaluated,Exact Match Rate (%),High Similarity Rate (%),Attribute Disclosure Rate (%),Singling-Out Rate (%),Overall Disclosure Risk (%),Privacy Protection Score (%),Successful Evaluations
0,CTGAN,3,0.0,0.0,100.0,99.603333,38.785833,61.214167,3
1,TVAE,3,0.0,0.0,100.0,100.000000,38.888889,61.111111,3
2,DP-CTGAN,3,0.0,0.0,NaN,100.000000,33.333333,66.666667,3
3,SPP-GAN,3,0.0,0.0,NaN,100.000000,33.333333,66.666667,3

====================================================================================================
PART L9 — METHOD-LEVEL PRIVACY RISK SUMMARY COMPLETED
====================================================================================================

In [ ]:
# =============================================================================
# Notebook 08 : Comparative Evaluation
# Section 8.13 : Publication Figures
# =============================================================================

print("="*80)
print("SECTION 8.13 : PUBLICATION FIGURES")
print("="*80)

PUBLICATION_DIR = RESULTS_DIR / "publication_figures"
PUBLICATION_DIR.mkdir(parents=True, exist_ok=True)

# =============================================================================
# Figure 1 : Overall Ranking
# =============================================================================

plt.figure(figsize=(9,5))

plt.bar(
    overall_ranking["Synthetic Model"],
    overall_ranking["Overall Score"]
)

plt.xticks(rotation=30)

plt.ylabel("Overall Score")

plt.title("Overall Ranking of Synthetic Data Generators")

plt.grid(axis="y", alpha=.3)

plt.tight_layout()

plt.savefig(
    PUBLICATION_DIR/"Figure1_OverallRanking.png",
    dpi=600
)

plt.show()

# =============================================================================
# Figure 2 : Fidelity
# =============================================================================

plt.figure(figsize=(8,5))

plt.bar(
    fidelity_score["Synthetic Model"],
    fidelity_score["Fidelity Score"]
)

plt.xticks(rotation=30)

plt.ylabel("Fidelity Score")

plt.title("Statistical Fidelity Comparison")

plt.grid(axis="y", alpha=.3)

plt.tight_layout()

plt.savefig(
    PUBLICATION_DIR/"Figure2_Fidelity.png",
    dpi=600
)

plt.show()

# =============================================================================
# Figure 3 : Utility
# =============================================================================

plt.figure(figsize=(8,5))

utility_plot = utility_score.sort_values(
    "Utility Score",
    ascending=False
)

plt.bar(

    utility_plot["Synthetic Model"],

    utility_plot["Utility Score"]

)

plt.xticks(rotation=30)

plt.ylabel("Utility Score")

plt.title("Machine Learning Utility")

plt.grid(axis="y", alpha=.3)

plt.tight_layout()

plt.savefig(

    PUBLICATION_DIR/"Figure3_Utility.png",

    dpi=600

)

plt.show()

# =============================================================================
# Figure 4 : Privacy
# =============================================================================

plt.figure(figsize=(8,5))

privacy_plot = privacy_scores.sort_values(

    "Privacy Score",

    ascending=False

)

plt.bar(

    privacy_plot["Synthetic Model"],

    privacy_plot["Privacy Score"]

)

plt.xticks(rotation=30)

plt.ylabel("Privacy Score")

plt.title("Privacy Preservation Comparison")

plt.grid(axis="y", alpha=.3)

plt.tight_layout()

plt.savefig(

    PUBLICATION_DIR/"Figure4_Privacy.png",

    dpi=600

)

plt.show()

# =============================================================================
# Figure 5 : Radar Chart
# =============================================================================

metrics = [

    "Fidelity Score",

    "Utility Score",

    "Privacy Score"

]

radar = overall_ranking.copy()

angles = np.linspace(

    0,

    2*np.pi,

    len(metrics),

    endpoint=False

)

angles = np.concatenate((angles,[angles[0]]))

fig = plt.figure(figsize=(8,8))

ax = plt.subplot(111, polar=True)

for _, row in radar.iterrows():

    values = [

        row["Fidelity Score"],

        row["Utility Score"],

        row["Privacy Score"]

    ]

    values.append(values[0])

    ax.plot(

        angles,

        values,

        linewidth=2,

        label=row["Synthetic Model"]

    )

ax.set_xticks(angles[:-1])

ax.set_xticklabels(metrics)

ax.set_title("Overall Model Comparison")

ax.legend(

    bbox_to_anchor=(1.35,1.05),

    fontsize=8

)

plt.tight_layout()

plt.savefig(

    PUBLICATION_DIR/"Figure5_RadarChart.png",

    dpi=600

)

plt.show()

# =============================================================================
# Figure 6 : Heatmap
# =============================================================================

heat = overall_ranking.set_index(

    "Synthetic Model"

)[

    [

        "Fidelity Score",

        "Utility Score",

        "Privacy Score",

        "Overall Score"

    ]

]

plt.figure(figsize=(8,5))

plt.imshow(

    heat,

    aspect="auto"

)

plt.xticks(

    range(len(heat.columns)),

    heat.columns,

    rotation=25

)

plt.yticks(

    range(len(heat.index)),

    heat.index

)

plt.colorbar(label="Score")

plt.title("Overall Evaluation Heatmap")

plt.tight_layout()

plt.savefig(

    PUBLICATION_DIR/"Figure6_Heatmap.png",

    dpi=600

)

plt.show()

# =============================================================================
# Figure 7 : Leaderboard
# =============================================================================

leaderboard = overall_ranking.sort_values(

    "Overall Score",

    ascending=False

)

plt.figure(figsize=(10,6))

plt.barh(

    leaderboard["Synthetic Model"],

    leaderboard["Overall Score"]

)

plt.xlabel("Overall Score")

plt.title("Synthetic Data Generator Leaderboard")

plt.tight_layout()

plt.savefig(

    PUBLICATION_DIR/"Figure7_Leaderboard.png",

    dpi=600

)

plt.show()

# =============================================================================
# Summary
# =============================================================================

print("\nPublication Figures Generated")

figures = sorted(PUBLICATION_DIR.glob("*.png"))

for fig in figures:

    print(f"✓ {fig.name}")

print("\nTotal Figures :", len(figures))

print("\nOutput Folder")

print(PUBLICATION_DIR)

print("\n✓ Publication figures completed successfully.")

print("="*80)
print("SECTION 8.13 COMPLETED SUCCESSFULLY")
print("="*80)

In [ ]:
# =============================================================================
# Notebook 08 : Comparative Evaluation
# Section 8.14 : Publication Tables
# =============================================================================

print("="*80)
print("SECTION 8.14 : PUBLICATION TABLES")
print("="*80)

PUBLICATION_TABLE_DIR = RESULTS_DIR / "publication_tables"
PUBLICATION_TABLE_DIR.mkdir(parents=True, exist_ok=True)

# =============================================================================
# Table 1 : Statistical Fidelity
# =============================================================================

table1 = fidelity_score.copy()

table1 = table1.sort_values(

    "Fidelity Score",

    ascending=False

)

# =============================================================================
# Table 2 : Machine Learning Utility
# =============================================================================

table2 = utility_score.copy()

table2 = table2.sort_values(

    "Utility Score",

    ascending=False

)

# =============================================================================
# Table 3 : Privacy Evaluation
# =============================================================================

table3 = privacy_scores.copy()

table3 = table3.sort_values(

    "Privacy Score",

    ascending=False

)

# =============================================================================
# Table 4 : Overall Ranking
# =============================================================================

table4 = overall_ranking.copy()

# =============================================================================
# Table 5 : Statistical Significance
# =============================================================================

table5 = friedman_summary.copy()

# =============================================================================
# Display Tables
# =============================================================================

tables = {

    "Table 1 : Fidelity Comparison"        : table1,

    "Table 2 : Utility Comparison"         : table2,

    "Table 3 : Privacy Comparison"         : table3,

    "Table 4 : Overall Model Ranking"      : table4,

    "Table 5 : Statistical Significance"   : table5

}

for title, df in tables.items():

    print("\n" + "="*80)

    print(title)

    print("="*80)

    display(df.round(4))

# =============================================================================
# Save Individual CSV Files
# =============================================================================

table1.to_csv(

    PUBLICATION_TABLE_DIR /

    "Table1_Fidelity.csv",

    index=False

)

table2.to_csv(

    PUBLICATION_TABLE_DIR /

    "Table2_Utility.csv",

    index=False

)

table3.to_csv(

    PUBLICATION_TABLE_DIR /

    "Table3_Privacy.csv",

    index=False

)

table4.to_csv(

    PUBLICATION_TABLE_DIR /

    "Table4_OverallRanking.csv",

    index=False

)

table5.to_csv(

    PUBLICATION_TABLE_DIR /

    "Table5_Statistics.csv",

    index=False

)

# =============================================================================
# Save Excel Workbook
# =============================================================================

publication_excel = PUBLICATION_TABLE_DIR / "Publication_Tables.xlsx"

with pd.ExcelWriter(

    publication_excel,

    engine="openpyxl"

) as writer:

    table1.to_excel(

        writer,

        sheet_name="Table1_Fidelity",

        index=False

    )

    table2.to_excel(

        writer,

        sheet_name="Table2_Utility",

        index=False

    )

    table3.to_excel(

        writer,

        sheet_name="Table3_Privacy",

        index=False

    )

    table4.to_excel(

        writer,

        sheet_name="Table4_Ranking",

        index=False

    )

    table5.to_excel(

        writer,

        sheet_name="Table5_Statistics",

        index=False

    )

# =============================================================================
# Summary
# =============================================================================

print("\nPublication Tables Generated")

files = sorted(PUBLICATION_TABLE_DIR.glob("*"))

for file in files:

    print(f"✓ {file.name}")

print("\nTotal Files :", len(files))

print("\nOutput Directory")

print(PUBLICATION_TABLE_DIR)

print("\n✓ Publication tables generated successfully.")

print("="*80)
print("SECTION 8.14 COMPLETED SUCCESSFULLY")
print("="*80)

In [ ]:
# =============================================================================
# Notebook 08 : Comparative Evaluation
# Section 8.15 : Export Complete Evaluation
# =============================================================================

print("=" * 80)
print("SECTION 8.15 : EXPORT COMPLETE EVALUATION")
print("=" * 80)

# =============================================================================
# Output Directory
# =============================================================================

EXPORT_DIR = RESULTS_DIR / "complete_evaluation"

EXPORT_DIR.mkdir(
    parents=True,
    exist_ok=True
)

# =============================================================================
# Export Excel Workbook
# =============================================================================

excel_path = EXPORT_DIR / "Complete_Evaluation.xlsx"

with pd.ExcelWriter(
    excel_path,
    engine="openpyxl"
) as writer:

    # -------------------------------------------------------------------------
    # Descriptive Statistics
    # -------------------------------------------------------------------------
    if "descriptive_statistics" in globals():
        descriptive_statistics.to_excel(
            writer,
            sheet_name="Descriptive Statistics",
            index=False
        )

    # -------------------------------------------------------------------------
    # Distribution Similarity
    # -------------------------------------------------------------------------
    if "distribution_results" in globals():
        distribution_results.to_excel(
            writer,
            sheet_name="Distribution Similarity",
            index=False
        )

    # -------------------------------------------------------------------------
    # Correlation Preservation
    # -------------------------------------------------------------------------
    if "correlation_summary" in globals():
        correlation_summary.to_excel(
            writer,
            sheet_name="Correlation",
            index=False
        )

    # -------------------------------------------------------------------------
    # Multivariate Similarity
    # -------------------------------------------------------------------------
    if "multivariate_summary" in globals():
        multivariate_summary.to_excel(
            writer,
            sheet_name="Multivariate",
            index=False
        )

    # -------------------------------------------------------------------------
    # Machine Learning Utility
    # -------------------------------------------------------------------------
    utility_results.to_excel(
        writer,
        sheet_name="Utility",
        index=False
    )

    generator_summary.to_excel(
        writer,
        sheet_name="Utility Ranking",
        index=False
    )

    # -------------------------------------------------------------------------
    # Privacy Evaluation
    # -------------------------------------------------------------------------
    membership_results.to_excel(
        writer,
        sheet_name="Membership Attack",
        index=False
    )

    attribute_results.to_excel(
        writer,
        sheet_name="Attribute Disclosure",
        index=False
    )

    reidentification_results.to_excel(
        writer,
        sheet_name="Reidentification",
        index=False
    )

    distance_results.to_excel(
        writer,
        sheet_name="Distance Metrics",
        index=False
    )

    privacy_scores.to_excel(
        writer,
        sheet_name="Privacy Scores",
        index=False
    )

    # -------------------------------------------------------------------------
    # Statistical Tests
    # -------------------------------------------------------------------------
    ttest_results.to_excel(
        writer,
        sheet_name="Paired t-Test",
        index=False
    )

    wilcoxon_results.to_excel(
        writer,
        sheet_name="Wilcoxon",
        index=False
    )

    friedman_summary.to_excel(
        writer,
        sheet_name="Friedman",
        index=False
    )

    # -------------------------------------------------------------------------
    # Overall Ranking
    # -------------------------------------------------------------------------
    overall_ranking.to_excel(
        writer,
        sheet_name="Overall Ranking",
        index=False
    )

print("✓ Excel workbook exported.")

# =============================================================================
# Export Major CSV Files
# =============================================================================

csv_tables = {

    "utility_results.csv": utility_results,
    "privacy_scores.csv": privacy_scores,
    "overall_ranking.csv": overall_ranking,
    "membership_results.csv": membership_results,
    "attribute_results.csv": attribute_results,
    "reidentification_results.csv": reidentification_results,
    "distance_results.csv": distance_results,
    "ttest_results.csv": ttest_results,
    "wilcoxon_results.csv": wilcoxon_results,
    "friedman_results.csv": friedman_summary

}

for filename, dataframe in csv_tables.items():

    dataframe.to_csv(
        EXPORT_DIR / filename,
        index=False
    )

print("✓ CSV files exported.")

# =============================================================================
# Export Figure Inventory
# =============================================================================

figure_files = []

for folder in [

    RESULTS_DIR / "evaluation",
    RESULTS_DIR / "publication_figures"

]:

    if folder.exists():

        figure_files.extend(folder.rglob("*.png"))

figure_inventory = pd.DataFrame({

    "Figure": [f.name for f in figure_files],

    "Location": [str(f) for f in figure_files]

})

figure_inventory.to_csv(

    EXPORT_DIR / "Figure_Inventory.csv",

    index=False

)

# =============================================================================
# Export Summary
# =============================================================================

print("\nFILES CREATED")
print("-" * 80)

for file in sorted(EXPORT_DIR.iterdir()):

    print(f"✓ {file.name}")

print("\nExport Location")

print(EXPORT_DIR)

print("\nTotal Files :", len(list(EXPORT_DIR.iterdir())))

print("\n✓ Complete evaluation exported successfully.")

print("=" * 80)
print("SECTION 8.15 COMPLETED SUCCESSFULLY")
print("=" * 80)

In [ ]:
# =============================================================================
# Notebook 08 : Comparative Evaluation
# Section 8.16 : Final Notebook Summary
# =============================================================================

print("=" * 90)
print("NOTEBOOK 08 : COMPARATIVE EVALUATION")
print("FINAL SUMMARY")
print("=" * 90)

# =============================================================================
# Best Models
# =============================================================================

best_fidelity = fidelity_score.loc[
    fidelity_score["Fidelity Score"].idxmax()
]

best_utility = utility_score.loc[
    utility_score["Utility Score"].idxmax()
]

best_privacy = privacy_scores.loc[
    privacy_scores["Privacy Score"].idxmax()
]

best_overall = overall_ranking.iloc[0]

# =============================================================================
# Final Summary Table
# =============================================================================

final_summary = pd.DataFrame({

    "Evaluation Category":[

        "Statistical Fidelity",

        "Machine Learning Utility",

        "Privacy Preservation",

        "Overall Performance"

    ],

    "Best Generator":[

        best_fidelity["Synthetic Model"],

        best_utility["Synthetic Model"],

        best_privacy["Synthetic Model"],

        best_overall["Synthetic Model"]

    ],

    "Score":[

        round(best_fidelity["Fidelity Score"],2),

        round(best_utility["Utility Score"],2),

        round(best_privacy["Privacy Score"],2),

        round(best_overall["Overall Score"],2)

    ]

})

print("\nFINAL EVALUATION SUMMARY\n")

display(final_summary)

# =============================================================================
# Publication Conclusion
# =============================================================================

print("\n" + "="*90)
print("PUBLICATION-READY CONCLUSION")
print("="*90)

print(
    f"""
The comparative evaluation investigated six synthetic tabular data generators:
Gaussian Multivariate, Gaussian Copula, CTGAN, TVAE, DP-CTGAN, and the proposed
SPP-GAN framework.

The evaluation considered three major perspectives:

• Statistical Fidelity
• Machine Learning Utility
• Privacy Preservation

The overall ranking integrated these dimensions using a weighted scoring
framework consisting of:

   • Fidelity  : 40%
   • Utility   : 30%
   • Privacy   : 30%

Based on the comprehensive evaluation, the highest overall score was achieved by

>>> {best_overall['Synthetic Model']}

Overall Score : {best_overall['Overall Score']:.2f}/100

The results indicate that this generator provides the best trade-off between

✓ Data Fidelity
✓ Downstream Machine Learning Utility
✓ Privacy Preservation

making it the most suitable model for privacy-preserving synthetic tabular data
generation among the evaluated approaches.
"""
)

# =============================================================================
# Save Final Summary
# =============================================================================

summary_file = EXPORT_DIR / "Final_Notebook_Summary.csv"

final_summary.to_csv(
    summary_file,
    index=False
)

# =============================================================================
# Completion
# =============================================================================

print("\n" + "="*90)
print("NOTEBOOK 08 COMPLETED SUCCESSFULLY")
print("="*90)

print(f"""
Datasets Evaluated          : {len(DATASETS)}

Synthetic Generators        : {len(MODELS)}

Best Fidelity Model         : {best_fidelity['Synthetic Model']}

Best Utility Model          : {best_utility['Synthetic Model']}

Best Privacy Model          : {best_privacy['Synthetic Model']}

Best Overall Model          : {best_overall['Synthetic Model']}

Overall Score               : {best_overall['Overall Score']:.2f}/100

Final Summary Saved To

{summary_file}
""")

print("="*90)
print("END OF NOTEBOOK 08")
print("="*90)